---
sidebar: sidebar 
permalink: ontap-security-hardening/create-fpolicy.html 
keywords: tr-4569, ontap hardening guide, security, native, external server, file policy, take actions, synchronous, asynchronous, storage workload security 
summary: Para proporcionar visibilidad y control de acceso a los archivos, la solución ONTAP usa la función FPolicy de NetApp. 
---
= Cree y utilice una instancia de NetApp FPolicy
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
Puede crear y utilizar un FPolicy, un componente de infraestructura de la solución ONTAP que permite a las aplicaciones de los partners supervisar y establecer permisos de acceso a archivos. Una de las aplicaciones más potentes es la seguridad de cargas de trabajo de almacenamiento, una aplicación SaaS de NetApp que proporciona visibilidad y control centralizados de todos los accesos a los datos corporativos en entornos de cloud híbrido para garantizar que se cumplan los objetivos de seguridad y cumplimiento de normativas.

El control de acceso es un concepto clave de la seguridad. La visibilidad y la capacidad de responder al acceso a archivos y a las operaciones con archivos son cruciales para mantener su política de seguridad. Para proporcionar visibilidad y control de acceso a los archivos, la solución ONTAP usa la función FPolicy de NetApp.

Se pueden establecer políticas de archivo por tipos de archivo. FPolicy determina la forma en que el sistema de almacenamiento maneja las solicitudes de sistemas cliente individuales en operaciones como crear, abrir, cambiar nombre y eliminar. A partir de ONTAP 9, el marco de notificaciones de acceso a archivos de FPolicy se ha mejorado con controles de filtrado y resiliencia ante breves interrupciones de red.

.Pasos
. Para aprovechar la función FPolicy, primero debe crear la política de FPolicy con `vserver fpolicy policy create` el comando.
+

NOTE: Además, debe usar el `-events` parámetro si utiliza FPolicy para obtener visibilidad y colección de eventos. La granularidad adicional que proporciona ONTAP permite filtrar y acceder a él según el nivel de control de los nombres de usuario. Para controlar los privilegios y el acceso con nombres de usuario, especifique el `-privilege-user-name` parámetro.

+
En el siguiente texto, se proporciona un ejemplo de creación de FPolicy:

+
[listing]
----
cluster1::> vserver fpolicy policy create -vserver vs1.example.com -policy-name vs1_pol -events cserver_evt,v1e1 -engine native -is-mandatory true -allow-privileged-access no -is-passthrough-read-enabled false
----
. Después de crear la política de FPolicy, debe habilitarla con `vserver fpolicy enable` el comando. Este comando también establece la prioridad o la secuencia de la entrada de FPolicy.
+

NOTE: La secuencia de FPolicy es importante porque, si varias políticas se han suscrito al mismo evento de acceso a archivos, la secuencia dicta el orden en que se otorga o deniega el acceso.

+
El siguiente texto proporciona una configuración de ejemplo para habilitar la política de FPolicy y validar la configuración con `vserver fpolicy show` el comando:

+
[listing]
----
cluster1::> vserver fpolicy enable -vserver vs2.example.com -policy-name vs2_pol -sequence-number 5

cluster1::> vserver fpolicy show
Vserver                 Policy Name                    Sequence  Status   Engine
----------------------- ------------------------------ --------  -------  -------
vs1.example.com         vs1_pol
vs2.example.com         vs2_pol
 external
2 entries were displayed.
----




== Mejoras de FPolicy

ONTAP 9 incluye las mejoras de FPolicy descritas en las siguientes secciones.



=== Controles de filtrado

Hay nuevos filtros disponibles para `SetAttr` y para eliminar notificaciones en las actividades del directorio.



=== Resiliencia asincrónica

Si un servidor de FPolicy que funciona en modo asíncrono experimenta una interrupción de la red, las notificaciones de FPolicy generadas durante la interrupción se almacenan en el nodo de almacenamiento. Cuando el servidor FPolicy vuelve a estar conectado, recibe alertas de las notificaciones almacenadas y pueden recogerlas del nodo de almacenamiento. El tiempo que las notificaciones se pueden almacenar durante una interrupción se puede configurar hasta 10 minutos.
