---
sidebar: sidebar 
permalink: ontap-security-hardening/lif-security.html 
keywords: tr-4569, ontap hardening guide, Data LIF, Cluster LIF, Node management LIF, Cluster management LIF, Intercluster LIF, requires private IP subnet, requires secure network, default firewall policy, is the firewall customizable, under no circumstance should any LIF roles be exposed to the internet 
summary: Comprender las características de seguridad de cada rol de LIF. 
---
= Características de seguridad de los roles de LIF en ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Una LIF es una dirección IP o un nombre de puerto a nivel mundial (WWPN) con características asociadas, como un rol, un puerto de inicio, un nodo de inicio, una lista de puertos a los que se deben conmutar por error y una política de firewall. Puede configurar las LIF en los puertos a través de los que el clúster envía y recibe comunicaciones a través de la red. Es crucial comprender las características de seguridad de cada rol de LIF.



== Roles LIF

Los roles de LIF pueden ser los siguientes:

* *Data LIF*: Una LIF asociada a una SVM y utilizada para comunicarse con los clientes.
* *Cluster LIF*: Una LIF utilizada para transportar tráfico intraclúster entre nodos de un cluster.
* *Node management LIF*: Una LIF que proporciona una dirección IP dedicada para administrar un nodo en particular en un clúster.
* *Cluster management LIF*: Un LIF que proporciona una única interfaz de gestión para todo el clúster.
* *Intercluster LIF*: Una LIF utilizada para la comunicación entre clústeres, la copia de seguridad y la replicación.




== Características de seguridad de cada rol de LIF

[cols="21%,13%,14%,18%,18%,16%"]
|===
|  | LIF de datos | LIF de clúster | LIF de gestión de nodos | LIF de gestión del clúster | LIF entre clústeres 


| ¿Requiere subred IP privada? | No | Sí | No | No | No 


| ¿Necesita una red segura? | No | Sí | No | No | Sí 


| Política de firewall predeterminada | Muy restrictivo | Completamente abierto | Mediano | Mediano | Muy restrictivo 


| ¿Es personalizable el firewall? | Sí | No | Sí | Sí | Sí 
|===
[IMPORTANT]
====
* Dado que la LIF de clúster está completamente abierta sin política de firewall configurable, debe estar en una subred IP privada en una red aislada segura.
* Los roles de LIF nunca deben exponerse a Internet.


====
Obtenga más información sobre la protección de las LIF, consulte el link:../networking/configure_firewall_policies_for_lifs.html["Configurar políticas de firewall para LIF"].
