---
sidebar: sidebar 
permalink: ontap-security-hardening/roles-applications-authentication.html 
keywords: tr-4569, ontap hardening guide, security, RBAC, roles, role, based access control, RBAC, login, application, authentication 
summary: Roles, aplicaciones y autenticación 
---
= Roles, aplicaciones y autenticación
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
ONTAP proporciona a la empresa condicionada por la seguridad la capacidad de brindar acceso granular a distintos administradores mediante diferentes métodos y aplicaciones de inicio de sesión. Esto ayuda a los clientes a crear un modelo de confianza cero centrado en los datos.

Estas son las funciones disponibles para los administradores de máquinas virtuales de almacenamiento y administradores. Se especifican los métodos de aplicación de inicio de sesión y los métodos de autenticación de inicio de sesión.



== Funciones

Con el control de acceso basado en roles, los usuarios solo tienen acceso a los sistemas y las opciones requeridas para sus roles y funciones de trabajo. La solución RBAC de ONTAP limita el acceso administrativo de los usuarios al nivel permitido por el rol que tengan definido, lo que permite a los administradores gestionar usuarios según el rol asignado. ONTAP ofrece varios roles predefinidos. Los operadores y administradores pueden crear, modificar o suprimir roles de control de acceso personalizados, y pueden especificar restricciones de cuenta para roles específicos.



=== Roles predefinidos para administradores de clúster

|===


| Este rol... | Tiene este nivel de acceso... | A los siguientes comandos o directorios de comandos 


 a| 
`admin`
 a| 
Todo
 a| 
Todos los directorios de comandos (`DEFAULT`)



 a| 
`admin-no-fsa` (Disponible a partir de ONTAP 9.12.1)
 a| 
Lectura/Escritura
 a| 
* Todos los directorios de comandos (`DEFAULT`)
* `security login rest-role`
* `security login role`




 a| 
Solo lectura
 a| 
* `security login rest-role create`
* `security login rest-role delete`
* `security login rest-role modify`
* `security login rest-role show`
* `security login role create`
* `security login role create`
* `security login role delete`
* `security login role modify`
* `security login role show`
* `volume activity-tracking`
* `volume analytics`




 a| 
Ninguno
 a| 
`volume file show-disk-usage`



 a| 
`autosupport`
 a| 
Todo
 a| 
* `set`
* `system node autosupport`




 a| 
Ninguno
 a| 
Todos los demás directorios de comandos (`DEFAULT`)



 a| 
`backup`
 a| 
Todo
 a| 
`vserver services ndmp`



 a| 
Solo lectura
 a| 
`volume`



 a| 
Ninguno
 a| 
Todos los demás directorios de comandos (`DEFAULT`)



 a| 
`readonly`
 a| 
Todo
 a| 
* `security login password`
+
Sólo para gestionar la contraseña local y la información de claves de la cuenta de usuario propia

* `set`




 a| 
Ninguno
 a| 
`security`



 a| 
Solo lectura
 a| 
Todos los demás directorios de comandos (`DEFAULT`)



 a| 
`none`
 a| 
Ninguno
 a| 
Todos los directorios de comandos (`DEFAULT`)

|===

NOTE: La `autosupport` el rol se asigna a los predefinidos `autosupport` Cuenta, que utiliza AutoSupport OnDemand. ONTAP le impide modificar o eliminar el `autosupport` cuenta. ONTAP también le impide asignar el `autosupport` función para otras cuentas de usuario.



=== Roles predefinidos para administradores de máquinas virtuales de almacenamiento (SVM)

|===


| Nombre del rol | Funcionalidades 


 a| 
`vsadmin`
 a| 
* Administrar la contraseña local y la información de clave de la cuenta de usuario propia
* Gestionar volúmenes, excepto movimientos de volúmenes
* Gestione cuotas, qtrees, copias Snapshot y archivos
* Gestionar las LUN
* Realice operaciones de SnapLock, excepto la supresión con privilegios
* Configurar protocolos: NFS, SMB, iSCSI, FC, FCoE y NVMe/FC y NVMe/TCP
* Configurar servicios: DNS, LDAP y NIS
* Supervisar trabajos
* Supervise las conexiones de red y la interfaz de red
* Supervise el estado de la SVM




 a| 
`vsadmin-volume`
 a| 
* Administrar la contraseña local y la información de clave de la cuenta de usuario propia
* Gestión de volúmenes, incluidos los movimientos de volúmenes
* Gestione cuotas, qtrees, copias Snapshot y archivos
* Gestionar las LUN
* Configurar protocolos: NFS, SMB, iSCSI, FC, FCoE y NVMe/FC y NVMe/TCP
* Configurar servicios: DNS, LDAP y NIS
* Supervise la interfaz de red
* Supervise el estado de la SVM




 a| 
`vsadmin-protocol`
 a| 
* Administrar la contraseña local y la información de clave de la cuenta de usuario propia
* Configurar protocolos: NFS, SMB, iSCSI, FC, FCoE y NVMe/FC y NVMe/TCP
* Configurar servicios: DNS, LDAP y NIS
* Gestionar las LUN
* Supervise la interfaz de red
* Supervise el estado de la SVM




 a| 
`vsadmin-backup`
 a| 
* Administrar la contraseña local y la información de clave de la cuenta de usuario propia
* Gestione las operaciones de NDMP
* Haga que un volumen restaurado sea de lectura/escritura
* Gestionar relaciones de SnapMirror y copias Snapshot
* Ver información de volúmenes y redes




 a| 
`vsadmin-snaplock`
 a| 
* Administrar la contraseña local y la información de clave de la cuenta de usuario propia
* Gestionar volúmenes, excepto movimientos de volúmenes
* Gestione cuotas, qtrees, copias Snapshot y archivos
* Realizar operaciones de SnapLock, incluida la supresión con privilegios
* Configurar protocolos: NFS y SMB
* Configurar servicios: DNS, LDAP y NIS
* Supervisar trabajos
* Supervise las conexiones de red y la interfaz de red




 a| 
`vsadmin-readonly`
 a| 
* Administrar la contraseña local y la información de clave de la cuenta de usuario propia
* Supervise el estado de la SVM
* Supervise la interfaz de red
* Ver volúmenes y LUN
* Ver servicios y protocolos


|===


== Métodos de aplicación

El método de aplicación especifica el tipo de acceso del método de inicio de sesión. Los valores posibles incluyen `console, http, ontapi, rsh, snmp, service-processor, ssh,` y `telnet`.

Configurar este parámetro `service-processor` para otorgar al usuario acceso a Service Processor. Cuando este parámetro se define en `service-processor`, el `-authentication-method` parámetro se debe definir en `password` porque el procesador de servicios sólo admite la autenticación de contraseña. Las cuentas de usuario de SVM no pueden acceder a Service Processor. Por lo tanto, los operadores y administradores no pueden utilizar el `-vserver` parámetro cuando este parámetro se define en `service-processor`.

Para restringir aún más el acceso al `service-processor` comando, utilice el comando `system service-processor ssh add-allowed-addresses`. El comando `system service-processor api-service` se puede utilizar para actualizar las configuraciones y los certificados.

Por motivos de seguridad, Telnet y el Shell remoto (RSH) están deshabilitados de forma predeterminada porque NetApp recomienda el shell seguro (SSH) para el acceso remoto seguro. Si hay un requisito o una necesidad única de Telnet o RSH, deben estar activados.

El `security protocol modify` comando modifica la configuración existente en todo el cluster de RSH y Telnet. Active RSH y Telnet en el cluster definiendo el campo Activado en `true`.



== Métodos de autenticación

El parámetro del método de autenticación especifica el método de autenticación utilizado para inicios de sesión.

[cols="33%,67%"]
|===
| Método de autenticación | Descripción 


| `cert` | Autenticación de certificado SSL 


| `community` | Cadenas de comunidad SNMP 


| `domain` | Autenticación de Active Directory 


| `nsswitch` | Autenticación LDAP o NIS 


| `password` | Contraseña 


| `publickey` | Autenticación de clave pública 


| `usm` | Modelo de seguridad de usuario SNMP 
|===

NOTE: No se recomienda el uso de NIS debido a las debilidades de seguridad del protocolo.

A partir de ONTAP 9,3, la autenticación encadenada de dos factores está disponible para cuentas SSH locales `admin` que utilizan `publickey` y contraseña como los dos métodos de autenticación. Además del `-authentication-method` campo del `security login` comando, se ha agregado un nuevo campo denominado `-second-authentication-method` . La clave pública o la contraseña se pueden especificar como `-authentication-method` o la `-second-authentication-method`. Sin embargo, durante la autenticación SSH, el orden es siempre clave pública con autenticación parcial, seguido de la solicitud de contraseña para la autenticación completa.

[listing]
----
[user@host01 ~]$ ssh ontap.netapp.local
Authenticated with partial success.
Password:
cluster1::>
----
A partir de ONTAP 9,4, `nsswitch` se puede utilizar como un segundo método de autenticación con `publickey`.

A partir de ONTAP 9.12.1, FIDO2 también se puede usar para la autenticación SSH usando un dispositivo de autenticación de hardware YubiKey u otros dispositivos compatibles con FIDO2.

A partir de ONTAP 9,13.1:

* `domain` las cuentas se pueden utilizar como un segundo método de autenticación con `publickey`.
* Contraseña de un solo uso basada en tiempo (`totp`) es un código de acceso temporal generado por un algoritmo que utiliza la hora actual del día como uno de sus factores de autenticación para el segundo método de autenticación.
* La revocación de claves públicas es compatible con claves públicas SSH, así como con certificados que se comprobarán para su caducidad/revocación durante SSH.


Para obtener más información sobre la autenticación multifactor (MFA) para el administrador del sistema de ONTAP, Active IQ Unified Manager y SSH, consulte link:http://www.netapp.com/us/media/tr-4647.pdf["TR-4647: Autenticación multifactor en ONTAP 9"^].
