---
sidebar: sidebar 
permalink: ontap-security-hardening/system-auditing.html 
keywords: tr-4569, ontap hardening guide, security, log forwarding, log encryption, events, syslog, audit, event notification 
summary: Asegure la integridad de la auditoría de eventos descargando eventos de ONTAP en un servidor syslog remoto. 
---
= Auditoría del sistema de administración de almacenamiento
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Asegure la integridad de la auditoría de eventos descargando eventos de ONTAP en un servidor syslog remoto. Este servidor podría ser un sistema de gestión de eventos de información de seguridad como Splunk.



== Enviar syslog

La información de registro y auditoría es muy valiosa para las organizaciones desde el punto de vista del soporte y la disponibilidad. Además, la información y los detalles que contienen los registros (syslog) y los informes y resultados de auditorías suelen ser de carácter confidencial. Para mantener los controles y la política de seguridad, es imprescindible que las organizaciones gestionen los datos de registro y auditoría de forma segura.

Descargar la información de syslog es necesario para limitar el alcance o la huella de una intrusión en un solo sistema o solución. Por ello, NetApp recomienda descargar la información de syslog de forma segura en una ubicación segura de almacenamiento o retención.



=== Cree un destino de reenvío de logs

Utilice `cluster log-forwarding create` el comando para crear destinos de reenvío de registros para el registro remoto.

.Parámetros
Use los siguientes parámetros para configurar `cluster log-forwarding create` el comando:

* *Destino host.* Este nombre es el nombre de host o la dirección IPv4 o IPv6 del servidor al que desea reenviar los logs.
+
[listing]
----
-destination <Remote InetAddress>
----
* *Puerto de destino.* Este es el puerto en el que recibe el servidor de destino.
+
[listing]
----
[-port <integer>]
----
* *Protocolo de reenvío de registros.* Este protocolo se utiliza para enviar mensajes al destino.
+
[listing]
----
[-protocol \{udp-unencrypted|tcp-unencrypted|tcp-encrypted}]
----
+
El protocolo de reenvío de registros puede usar uno de los valores siguientes:

+
** `udp-unencrypted`. Protocolo de datagramas de usuario sin seguridad.
** `tcp-unencrypted`. TCP sin seguridad.
** `tcp-encrypted`. TCP con seguridad de la capa de transporte (TLS).


* *Verificar la identidad del servidor de destino.* Cuando este parámetro se define en TRUE, la identidad del destino de reenvío de logs se verifica validando su certificado. El valor se puede establecer en verdadero sólo cuando se selecciona el valor en `tcpencrypted` el campo de protocolo.
+
[listing]
----
[-verify-server \{true|false}]
----
* *Instalación Syslog.* Este valor es la utilidad syslog que se debe utilizar para los registros reenviados.
+
[listing]
----
[-facility <Syslog Facility>]
----
* *Salte la prueba de conectividad.* Normalmente, el `cluster log-forwarding create` comando comprueba que se puede acceder al destino enviando un ping de protocolo de mensajes de control de Internet (ICMP) y genera un error si no se puede acceder a él. Al definir este valor `true` se omite la comprobación de ping para que pueda configurar el destino cuando no se pueda acceder a él.
+
[listing]
----
[-force [true]]
----



NOTE: NetApp recomienda el uso `cluster log-forwarding` del comando para forzar la conexión a un `-tcp-encrypted` tipo.



== Notificación de eventos

Proteger la información y los datos que salen de un sistema es vital para mantener y gestionar la política de seguridad del sistema. Los eventos generados por la solución de ONTAP ofrecen una gran cantidad de información acerca de qué se encuentra la solución, la información procesada y mucho más. La vitalidad de estos datos destaca la necesidad de gestionarlos y migrarlos de forma segura.

El `event notification create` comando envía una nueva notificación de un conjunto de eventos definidos por un filtro de eventos a uno o más destinos de notificación. Los siguientes ejemplos muestran la configuración de notificaciones de eventos y `event notification show` el comando, que muestra los filtros y los destinos de notificación de eventos configurados.

[listing]
----
cluster1::> event notification create -filter-name filter1 -destinations
 email_dest,syslog_dest,snmp-traphost

cluster1::> event notification show
ID     Filter Name       Destinations
-----  ----------------  -----------------
1 filter1 email_dest, syslog_dest, snmp-traphost
----