---
sidebar: sidebar 
permalink: authentication-access-control/disable-webauthn-mfa-task.html 
keywords: mfa, multi-factor, authentication, authorization, webauthn, FIDO2, hardware key, disable, system manager 
summary: Si habilitó la MFA de WebAuthn para usuarios de System Manager, puede deshabilitarla en cualquier momento. 
---
= Desactive WebAuthn MFA para usuarios de ONTAP System Manager
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Como administrador de ONTAP, puede deshabilitar la MFA de WebAuthn para un usuario o grupo editando el usuario o grupo con System Manager o la interfaz de línea de comandos de ONTAP.



== Desactive WebAuthn MFA para un usuario o grupo existente

Puede deshabilitar WebAuthn MFA para un usuario o grupo existente en cualquier momento.


NOTE: Si deshabilita las credenciales registradas, se conservan las credenciales. Si vuelve a activar las credenciales en el futuro, se utilizarán las mismas credenciales, por lo que el usuario no tendrá que volver a registrarse al iniciar sesión.

[role="tabbed-block"]
====
.System Manager
--
. Seleccione *Cluster > Settings*.
. Seleccione el icono de flecha junto a *Usuarios y Roles*.
. En la lista de usuarios y grupos, seleccione el usuario o grupo que desea editar.
. En la columna *MFA for HTTP* para ese usuario, seleccione *Disabled*.
. Seleccione *Guardar*.


--
.CLI
--
. Modifique un usuario o grupo existente para desactivar WebAuthn MFA para ese usuario o grupo.
+
En el siguiente ejemplo, WebAuthn MFA se deshabilita seleccionando “none” para el segundo método de autenticación.

+
[source, console]
----
security login modify -user-or-group-name <user_or_group_name> \
                     -authentication-method domain \
                     -second-authentication-method none \
                     -application http \
                     -role admin
----


--
====


== Leer más

Consulte las páginas del manual de ONTAP para este comando:

* https://docs.netapp.com/us-en/ontap-cli/security-login-modify.html["modificación del inicio de sesión de seguridad"^]

