---
sidebar: sidebar 
permalink: ransomware-solutions/ransomware-fpolicy.html 
keywords: tr-4572, technical report, ransomware, protect, protection, netapp ransomware protection, netapp tr, ontap tr 
summary: La protección contra ransomware de NetApp incluye FPolicy, que bloquea los archivos no deseados de que se almacenen en el dispositivo de almacenamiento de clase empresarial. 
---
= Bloqueo de archivos FPolicy
:allow-uri-read: 


[role="lead"]
FPolicy bloquea los archivos no deseados para que no se almacenen en su dispositivo de almacenamiento de clase empresarial. FPolicy también le ofrece una forma de bloquear las extensiones de archivos de ransomware conocidas. Un usuario sigue teniendo permisos de acceso completo a la carpeta principal, pero FPolicy no permite que un usuario almacene los archivos que marca su administrador como bloqueados. No importa si esos archivos son archivos MP3 o extensiones de archivos ransomware conocidos.



== Bloquea archivos maliciosos con el modo nativo de FPolicy

El modo nativo de FPolicy de NetApp (una evolución del nombre, Política de archivos) es un marco de bloqueo de extensiones de archivos que le permite bloquear las extensiones de archivos no deseadas para que entren en su entorno. Ha formado parte de ONTAP durante más de una década y es increíblemente útil para ayudarte a protegerte contra el ransomware. Este motor de confianza cero es valioso porque obtienes medidas de seguridad adicionales más allá de los permisos de la lista de control de acceso (ACL).

En el Administrador del sistema de ONTAP y BlueXP , hay una lista de más de 3000 extensiones de archivo disponibles para su referencia.


WARNING: Algunas extensiones pueden ser legítimas en su entorno y bloquearlas puede dar lugar a problemas inesperados. Cree su propia lista que sea adecuada para su entorno antes de configurar las FPolicy nativas.

El modo nativo de FPolicy se incluye en todas las licencias de ONTAP.

.Leer más
* https://www.netapp.com/blog/fighting-ransomware-tools/["Blog: Lucha contra el ransomware: Tercera parte: FPolicy de ONTAP, otra potente herramienta nativa (también gratuita)"^]




== Habilite el análisis de comportamiento de usuarios y entidades (UEBA) con el modo externo de FPolicy

El modo externo de FPolicy es un marco de notificación y control de actividad de archivos que proporciona visibilidad de la actividad de archivos y usuarios. Una solución externa puede utilizar estas notificaciones para realizar análisis basados en IA con el fin de detectar comportamientos maliciosos.

El modo externo de FPolicy también se puede configurar para que espere a la aprobación del servidor FPolicy antes de permitir que pasen determinadas actividades. Se pueden configurar múltiples normativas de este tipo en un clúster, lo que le proporciona una gran flexibilidad.


WARNING: Los servidores FPolicy deben responder a las solicitudes de FPolicy si se configuran para proporcionar la aprobación; de lo contrario, el rendimiento del sistema de almacenamiento puede verse afectado de forma negativa.

El modo externo FPolicy se incluye en link:../system-admin/manage-licenses-concept.html["Todas las licencias de ONTAP"].

.Leer más
* https://www.netapp.com/blog/fighting-ransomware-ontap-fpolicy/["Blog: Lucha contra el ransomware: Cuarta parte: UBA y ONTAP con el modo externo FPolicy."^]

