---
permalink: s3-config/configure-access-ldap.html 
sidebar: sidebar 
keywords: tr-4814, generate, ldap, s3, access keys, secret keys using API 
summary: Los usuarios de S3 pueden regenerar las claves para acceder a clientes de S3 mediante la API. 
---
= Configure los servicios de directorio externo para el acceso a ONTAP S3
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.14.1, los servicios para directorios externos se han integrado con el almacenamiento de objetos S3 de ONTAP. Esta integración simplifica la administración de usuarios y accesos a través de servicios de directorio externos.

Puede proporcionar grupos de usuarios que pertenecen a un servicio de directorio externo con acceso al entorno de almacenamiento de objetos de ONTAP. El protocolo ligero de acceso a directorios (LDAP) es una interfaz para la comunicación con servicios de directorio, como Active Directory, que proporcionan una base de datos y servicios para la gestión de identidades y accesos (IAM). Para proporcionar acceso, debe configurar los grupos LDAP en el entorno de ONTAP S3. Después de configurar el acceso, los miembros del grupo tienen permisos para los buckets de ONTAP S3. Para obtener más información sobre LDAP, consulte link:../nfs-config/using-ldap-concept.html["Obtenga información sobre el uso de servicios de nombres LDAP en SVM NFS de ONTAP"].

También puede configurar grupos de usuarios de Active Directory para el modo de enlace rápido, de modo que las credenciales de usuario se puedan validar y las aplicaciones S3 de terceros y de código abierto se puedan autenticar a través de conexiones LDAP.

.Antes de empezar
Asegúrese de lo siguiente antes de configurar los grupos LDAP y habilitar el modo de enlace rápido para el acceso de grupos:

. Se creó una máquina virtual de almacenamiento habilitada para S3 que contiene un servidor S3. Consulte link:../s3-config/create-svm-s3-task.html["Cree una SVM para S3"].
. Se ha creado un bloque en esa máquina virtual de almacenamiento. Consulte link:../s3-config/create-bucket-task.html["Crear un bucket"].
. DNS está configurado en la máquina virtual de almacenamiento. Consulte link:../networking/configure_dns_services_auto.html["Configure los servicios DNS"].
. Hay un certificado de entidad de certificación raíz (CA) autofirmado del servidor LDAP instalado en la máquina virtual de almacenamiento. Consulte link:../nfs-config/install-self-signed-root-ca-certificate-svm-task.html["Instalar certificados CA raíz autofirmados en la SVM"].
. Se configura un cliente LDAP con TLS habilitado en la SVM. Consulte link:../nfs-config/create-ldap-client-config-task.html["Crear configuraciones de cliente LDAP para el acceso NFS de ONTAP"] y link:../nfs-config/enable-ldap-svms-task.html["Asociar configuraciones de cliente LDAP con SVM NFS de ONTAP para obtener información"].




== Configure el acceso S3 para LDAP

. Especifique LDAP como la base de datos del servicio _name_ de la SVM para el grupo y la contraseña a LDAP:
+
[listing]
----
ns-switch modify -vserver <vserver-name> -database group -sources files,ldap
ns-switch modify -vserver <vserver-name> -database passwd -sources files,ldap
----
+
Obtenga más información acerca del comando link:https://docs.NetApp.com/us-en/ONTAP-cli/vserver-services-name-service-ns-switch-modify.html[`vserver services name-service ns-switch modify`^] en la referencia de comandos de ONTAP.

. Cree una sentencia de política de cubo de almacén de objetos con el `principal` juego en el grupo LDAP al que desea otorgar acceso:
+
[listing]
----
object-store-server bucket policy statement create -bucket <bucket-name> -effect allow -principal nasgroup/<ldap-group-name> -resource <bucket-name>, <bucket-name>/*
----
+
Ejemplo: El siguiente ejemplo crea una sentencia de política de bloque para `buck1`. La política permite el acceso del grupo LDAP `group1` al recurso (bloque y sus objetos) `buck1`.

+
[listing]
----
vserver object-store-server bucket policy add-statement -bucket buck1 -effect allow -action
GetObject,PutObject,DeleteObject,ListBucket,GetBucketAcl,GetObjectAcl,ListBucketMultipartUploads,ListMultipartUploadParts, ListBucketVersions,GetObjectTagging,PutObjectTagging,DeleteObjectTagging,GetBucketVersioning,PutBucketVersioning -principal nasgroup/group1 -resource buck1, buck1/*
----
. Verifique que un usuario del grupo LDAP `group1` pueda realizar operaciones S3 desde el cliente S3.




== Use el modo de enlace rápido LDAP para la autenticación

. Especifique LDAP como la base de datos del servicio _name_ de la SVM para el grupo y la contraseña a LDAP:
+
[listing]
----
ns-switch modify -vserver <vserver-name> -database group -sources files,ldap
ns-switch modify -vserver <vserver-name> -database passwd -sources files,ldap
----
+
Obtenga más información acerca del comando link:https://docs.NetApp.com/us-en/ONTAP-cli/vserver-services-name-service-ns-switch-modify.html[`vserver services name-service ns-switch modify`^] en la referencia de comandos de ONTAP.

. Asegúrese de que un usuario LDAP que acceda al bloque de S3 tenga permisos definidos en las políticas de bloque. Para obtener más información, consulte link:../s3-config/create-modify-bucket-policy-task.html["Modificar una política de bloques"].
. Verifique que un usuario del grupo LDAP pueda realizar las siguientes operaciones:
+
.. Configure la clave de acceso en el cliente S3 en este formato
`"NTAPFASTBIND" + base64-encode(user-name:password)`: Ejemplo `"NTAPFASTBIND"`: + base64-encode(ldapuser:password), lo que resulta en
`NTAPFASTBINDbGRhcHVzZXI6cGFzc3dvcmQ=`
+

NOTE: Es posible que el cliente S3 solicite una clave secreta. En ausencia de una clave secreta, se puede introducir cualquier contraseña de al menos 16 caracteres.

.. Realice operaciones S3 básicas desde el cliente S3 para el que el usuario tenga permisos.






==== Credenciales de Base64

La configuración predeterminada de ONTAP S3 excluye HTTP y utiliza exclusivamente HTTPS y una conexión de seguridad de la capa de transporte (TLS). ONTAP puede generar certificados autofirmados, pero la práctica recomendada es usar certificados de una entidad de certificación (CA) de terceros. Cuando utiliza certificados de CA, se crea una relación de confianza entre las aplicaciones cliente y el servidor de almacén de objetos de ONTAP.

Tenga en cuenta que las credenciales codificadas con Base64 se descodifican fácilmente. El uso de HTTPS evitará que los rastreadores de paquetes man-in-the-middle capturen las credenciales codificadas.

No utilice el modo de enlace rápido LDAP para la autenticación al crear direcciones URL prefirmadas. La autenticación se basa exclusivamente en la clave de acceso Base64 que se incluye en la URL prefirmada. El nombre de usuario y la contraseña se revelarán a cualquiera que decodifique la clave de acceso Base64.



=== El método de autenticación es nsswitch y LDAP está habilitado, por ejemplo

[listing]
----
$curl -siku <user>:<user_password> -X POST https://<LIF_IP_Address>/api/protocols/s3/services/<SVM_UUID>/users -d {"comment":"<S3_user_name>", "name":<user>,"<key_time_to_live>":"PT6H3M"}'
----

NOTE: Dirija la API al LIF de gestión del clúster, no al LIF de datos de la SVM. Si desea permitir que los usuarios generen sus propias claves, debe agregar permisos HTTP a su rol para usar curl. Este permiso se suma a los permisos de la API S3.



== Configure el acceso S3 para los servidores Active Directory o CIFS

Si el grupo nasgroup especificado en la sentencia de política bucket o los usuarios que forman parte del grupo nasgroup no tienen UID ni GID definidos, las búsquedas fallan cuando no se encuentran estos atributos. Active Directory utiliza SID, no UID. Si las entradas de SID no pueden asignarse a UID, se deben llevar los datos necesarios a ONTAP.

Para ello, utilice link:../authentication/enable-ad-users-groups-access-cluster-svm-task.html["creación de directorio activo de vserver"]para que la SVM pueda autenticarse con Active Directory y obtenga la información de usuario y grupo necesaria.

De forma alternativa, utilice link:../authentication/enable-ad-users-groups-access-cluster-svm-task.html["vserver cifs create"] para crear un servidor SMB en un dominio de Active Directory.

Para evitar fallos de consulta, NetApp recomienda utilizar dominios de confianza para la autorización de recursos en formato UPN: `nasgroup/group@trusted_domain.com`



=== Genere claves cuando el método de autenticación sea dominio y los dominios de confianza estén configurados en Active Directory

Utilice el `s3/services/<svm_uuid>/users` punto final con los usuarios especificados en formato UPN. Ejemplo:

[listing]
----
$curl -siku FQDN\\user:<user_password> -X POST https://<LIF_IP_Address>/api/protocols/s3/services/<SVM_UUID>/users -d {"comment":"<S3_user_name>", "name":<user@fqdn>,"<key_time_to_live>":"PT6H3M"}'
----

NOTE: Dirija la API al LIF de gestión del clúster, no al LIF de datos de la SVM. Si desea permitir que los usuarios generen sus propias claves, debe agregar permisos HTTP a su rol para usar curl. Este permiso se suma a los permisos de la API S3.



=== Genere claves cuando el método de autenticación sea dominio y no haya dominios de confianza

Esta acción es posible cuando LDAP está deshabilitado o cuando los usuarios que no son POSIX no han configurado UID y GID. Ejemplo:

[listing]
----
$curl -siku FQDN\\user:<user_password> -X POST https://<LIF_IP_Address>/api/protocols/s3/services/<SVM_UUID>/users -d {"comment":"<S3_user_name>", "name":<user[@fqdn]>,"<key_time_to_live>":"PT6H3M"}'
----

NOTE: Dirija la API al LIF de gestión del clúster, no al LIF de datos de la SVM. Si desea permitir que los usuarios generen sus propias claves, debe agregar permisos HTTP a su rol para usar curl. Este permiso se suma a los permisos de la API S3. Solo es necesario agregar el valor de dominio opcional (@fqdn) a un nombre de usuario si no hay dominios de confianza.
