---
permalink: s3-config/create-install-ca-certificate-svm-task.html 
sidebar: sidebar 
keywords: create, install, ca certificate, svm 
summary: 'Se requiere un certificado de la entidad de certificación (CA) para habilitar el tráfico HTTPS desde clientes S3 a la SVM habilitada para S3.' 
---
= Cree e instale un certificado de CA en una SVM habilitada para ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los clientes S3 requieren un certificado de autoridad de certificación (CA) para enviar tráfico HTTPS al SVM habilitado para S3.  Los certificados CA crean una relación de confianza entre las aplicaciones cliente y el servidor de almacenamiento de objetos ONTAP .  Debe instalar un certificado CA en ONTAP antes de usarlo como almacén de objetos accesible para clientes remotos.

.Acerca de esta tarea
Aunque es posible configurar un servidor S3 para que use únicamente HTTP y, aunque es posible configurar clientes sin requisitos de certificado de CA, es una práctica recomendada proteger el tráfico HTTPS a servidores ONTAP S3 con un certificado de CA.

Un certificado de CA no es necesario para un caso de uso de organización en niveles local, donde el tráfico de IP pasa únicamente por las LIF del clúster.

Las instrucciones de este procedimiento crearán e instalarán un certificado autofirmado de ONTAP. Aunque ONTAP puede generar certificados autofirmados, se recomienda utilizar certificados firmados de una entidad de certificación de terceros. Consulte la documentación de autenticación de administrador para obtener más información.

link:../authentication/index.html["Autenticación de administrador y RBAC"]

Obtenga más información sobre `security certificate` las opciones de configuración adicionales en la link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+certificate["Referencia de comandos del ONTAP"^]sección .

.Pasos
. Cree un certificado digital autofirmado:
+
`security certificate create -vserver _svm_name_ -type root-ca -common-name _ca_cert_name_`

+
 `-type root-ca`La opción crea e instala un certificado digital autofirmado para firmar otros certificados actuando como una entidad de certificación (CA).

+
 `-common-name`La opción crea el nombre de la entidad de certificación (CA) de SVM y se utilizará al generar el nombre completo del certificado.

+
El tamaño predeterminado del certificado es de 2048 bits.

+
Ejemplo

+
[listing]
----
cluster-1::> security certificate create -vserver svm1.example.com -type root-ca -common-name svm1_ca

The certificate's generated name for reference: svm1_ca_159D1587CE21E9D4_svm1_ca
----
+
Cuando se muestre el nombre generado del certificado; asegúrese de guardarlo para pasos posteriores de este procedimiento.

+
Obtenga más información sobre `security certificate create` en el link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-create.html["Referencia de comandos del ONTAP"^].

. Genere una solicitud de firma de certificación:
+
`security certificate generate-csr -common-name _s3_server_name_ [additional_options]`

+
 `-common-name`El parámetro de la solicitud de firma debe ser el nombre del servidor S3 (FQDN).

+
Puede proporcionar la ubicación y otra información detallada sobre la SVM si lo desea.

+
El `-dns-name` Los clientes a menudo requieren este parámetro para especificar la extensión de nombre alternativo del sujeto, que proporciona una lista de nombres DNS.

+
El `-ipaddr` Los clientes a menudo requieren este parámetro para especificar la extensión del nombre alternativo del sujeto, que proporciona una lista de direcciones IP.

+
Se le solicitará que conserve una copia de su solicitud de certificado y la clave privada para futuras consultas.

+
Obtenga más información sobre `security certificate generate-csr` en el link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-generate-csr.html["Referencia de comandos del ONTAP"^].

. Firme la CSR con SVM_CA para generar el certificado de S3 Server:
+
`security certificate sign -vserver _svm_name_ -ca _ca_cert_name_ -ca-serial _ca_cert_serial_number_ [additional_options]`

+
Escriba las opciones de comando que ha utilizado en pasos anteriores:

+
** `-ca` -- El nombre común de la CA que ingresó en el Paso 1.
** `-ca-serial` -- El número de serie de CA del paso 1. Por ejemplo, si el nombre del certificado de CA es svm1_CA_159D1587CE21E9D4_svm1_ca, el número de serie es 159D1587CE21E9D4.
+
De forma predeterminada, el certificado firmado caducará en 365 días. Puede seleccionar otro valor y especificar otros detalles de firma.

+
Cuando se le solicite, copie e introduzca la cadena de solicitud de certificado que guardó en el paso 2.

+
Se muestra un certificado firmado; guárdelo para un uso posterior.



. Instale el certificado firmado en la SVM habilitada para S3:
+
`security certificate install -type server -vserver _svm_name_`

+
Cuando se le solicite, introduzca el certificado y la clave privada.

+
Puede introducir certificados intermedios si desea una cadena de certificados.

+
Cuando se muestren la clave privada y el certificado digital firmado por CA, guárdelos para referencia futura.

. Obtenga el certificado de clave pública:
+
`security certificate show -vserver _svm_name_ -common-name _ca_cert_name_ -type root-ca -instance`

+
Guarde el certificado de clave pública para la configuración posterior del cliente.

+
Ejemplo

+
[listing]
----
cluster-1::> security certificate show -vserver svm1.example.com -common-name svm1_ca -type root-ca  -instance

                      Name of Vserver: svm1.example.com
           FQDN or Custom Common Name: svm1_ca
         Serial Number of Certificate: 159D1587CE21E9D4
                Certificate Authority: svm1_ca
                  Type of Certificate: root-ca
     (DEPRECATED)-Certificate Subtype: -
              Unique Certificate Name: svm1_ca_159D1587CE21E9D4_svm1_ca
Size of Requested Certificate in Bits: 2048
               Certificate Start Date: Thu May 09 10:58:39 2020
          Certificate Expiration Date: Fri May 08 10:58:39 2021
               Public Key Certificate: -----BEGIN CERTIFICATE-----
MIIDZ ...==
-----END CERTIFICATE-----
                         Country Name: US
               State or Province Name:
                        Locality Name:
                    Organization Name:
                    Organization Unit:
Contact Administrator's Email Address:
                             Protocol: SSL
                     Hashing Function: SHA256
              Self-Signed Certificate: true
       Is System Internal Certificate: false
----


.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["instalación del certificado de seguridad"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-show.html["Mostrar certificado de seguridad"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-sign.html["signo de certificado de seguridad"^]

