---
permalink: s3-config/create-bucket-task.html 
sidebar: sidebar 
keywords: s3, bucket, system manager, 
summary: Los objetos S3 se conservan en _buckets_--no están anidados como archivos dentro de un directorio dentro de otros directorios. 
---
= Crear un bucket
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los objetos S3 se conservan en _buckets_--no están anidados como archivos dentro de un directorio dentro de otros directorios.

.Antes de empezar
Debe haber una SVM que contenga un servidor S3.

.Acerca de esta tarea
Para la CLI, cuando crea un bloque, tiene dos opciones de aprovisionamiento:

* Dejar a ONTAP Select los agregados subyacentes y los componentes de FlexGroup (predeterminado)
+
** ONTAP crea y configura un volumen de FlexGroup para el primer bloque seleccionando automáticamente los agregados. Seleccionará automáticamente el nivel de servicio más alto disponible para su plataforma, o bien se puede especificar el nivel de servicio de almacenamiento. Todos los bloques adicionales que añada más adelante en la SVM tendrán el mismo volumen de FlexGroup subyacente.
** También puede especificar si el bloque se utilizará para la organización en niveles, en cuyo caso ONTAP intentará seleccionar medios de bajo coste con un rendimiento óptimo para los datos organizados en niveles.


* Puede seleccionar los agregados subyacentes y los componentes de FlexGroup (requiere opciones de comandos de privilegios avanzados).
+
** Tiene la opción de seleccionar manualmente los agregados en los que se debe crear el bloque y el volumen de FlexGroup que contiene; a continuación, se especifica el número de componentes en cada agregado. Al añadir cubos adicionales:
+
*** Si especifica agregados y componentes para un bloque nuevo, se creará una FlexGroup nueva para el bloque nuevo.
*** Si no se especifican agregados y componentes para un bloque nuevo, el nuevo bloque se añadirá a una FlexGroup existente.
Consulte xref:../flexgroup/index.html[Gestión de volúmenes de FlexGroup] si quiere más información.
+
Cuando se especifican agregados y componentes al crear un bloque, no se aplican grupos de políticas de calidad de servicio, predeterminados ni personalizados. Puede hacerlo más tarde con el `vserver object-store-server bucket modify` comando.







*Nota:* Si está sirviendo cubos de Cloud Volumes ONTAP, debe utilizar el procedimiento CLI. Se recomienda seleccionar manualmente los agregados subyacentes para garantizar que solo utilicen un nodo. El uso de agregados de ambos nodos puede afectar al rendimiento, ya que los nodos se encuentran en zonas de disponibilidad separadas geográficamente y, por lo tanto, pueden estar expuestos a problemas de latencia.

Los niveles de servicio de almacenamiento son grupos de políticas de calidad de servicio (QoS) adaptativos predefinidos, con niveles _Value_, _Performance_ y _Extreme_ predeterminados. En lugar de uno de los niveles de servicio de almacenamiento predeterminados, también puede definir un grupo de políticas de calidad de servicio personalizado y aplicarlo a un bloque.

A partir de ONTAP 9.8, cuando se aprovisiona el almacenamiento, la calidad de servicio se habilita de forma predeterminada. Puede deshabilitar la calidad de servicio o seleccionar una política de calidad de servicio personalizada durante el proceso de aprovisionamiento o más adelante.

link:storage-service-definitions-reference.html["Definiciones de servicios de almacenamiento"]

Si va a configurar la organización en niveles de la capacidad local, debe crear bloques y usuarios en una SVM de datos, no en la SVM del sistema donde se encuentra el servidor S3.

Para el acceso de cliente remoto, debe configurar buckets en una máquina virtual de almacenamiento habilitada para S3. Si crea un bloque en una máquina virtual de almacenamiento que no tiene la función S3, solo estará disponible para la organización en niveles local.

link:../performance-admin/index.html["Gestión del rendimiento"]

Consulte `vserver object-store-server bucket` páginas de manual para opciones de visualización y configuración adicionales.



== Proceso para crear cubos

[role="tabbed-block"]
====
.CLI
--
. Si piensa seleccionar agregados y componentes de FlexGroup por su cuenta, establezca el nivel de privilegio en Advanced (de lo contrario, el nivel de privilegio de administrador es suficiente): `set -privilege advanced`
. Crear un bloque:
+
`vserver object-store-server bucket create -vserver _svm_name_ -bucket _bucket_name_ [-size integer[KB|MB|GB|TB|PB]] [-comment text] [additional_options]`

+
El nombre de la SVM puede ser una SVM o una `Cluster` (El nombre de SVM del sistema) si va a configurar la organización en niveles local.

+
Si no especifica ninguna opción, ONTAP crea un bloque de 5 GB con el nivel de servicio establecido en el nivel más alto disponible para su sistema.

+
Si desea que ONTAP cree un bloque según el rendimiento o el uso, utilice una de las siguientes opciones:

+
** nivel de servicio
+
Incluya el `-storage-service-level` opción con uno de los siguientes valores: `value`, `performance`, o. `extreme`.

** Organización en niveles
+
Incluya el `-used-as-capacity-tier true` opción.



+
Si desea especificar los agregados en los que se creará el volumen de FlexGroup subyacente, utilice las siguientes opciones:

+
** La `-aggr-list` El parámetro especifica la lista de agregados que se usarán para los componentes de volumen de FlexGroup.
+
Cada entrada de la lista crea un componente en el agregado especificado. Puede especificar un agregado varias veces para que se creen varios componentes en el agregado.

+
Para obtener un rendimiento coherente en todo el volumen FlexGroup, todos los agregados deben usar las mismas configuraciones de tipo de disco y grupo RAID.

** La `-aggr-list-multiplier` parámetro especifica la cantidad de veces que se debe iterar sobre los agregados que se enumeran con el `-aggr-list` Parámetro cuando se crea un volumen de FlexGroup.
+
El valor predeterminado de `-aggr-list-multiplier` el parámetro es 4.



. Añada un grupo de políticas QoS si es necesario:
+
`vserver object-store-server bucket modify -bucket _bucket_name_ -qos-policy-group _qos_policy_group_`

. Verificar creación de bloques:
+
`vserver object-store-server bucket show [-instance]`



.Ejemplo
En el siguiente ejemplo se crea un bucket para SVM vs1 de tamaño 1 TB y se especifica el agregado:

[listing]
----
cluster-1::*> vserver object-store-server bucket create -vserver svm1.example.com -bucket testbucket -aggr-list aggr1 -size 1TB
----
--
.System Manager
--
. Añadir un nuevo bloque en una máquina virtual de almacenamiento habilitada para S3.
+
.. Haga clic en *almacenamiento > Cuchos* y, a continuación, haga clic en *Agregar*.
.. Introduzca un nombre, seleccione la máquina virtual de almacenamiento e introduzca un tamaño.
+
*** Si hace clic en *Guardar* en este punto, se crea un bloque con estos valores predeterminados:
+
**** No se concede acceso a ningún usuario al bloque a menos que ninguna política de grupo esté ya en vigor.
+

NOTE: No se debe usar el usuario raíz de S3 para gestionar el almacenamiento de objetos ONTAP y compartir sus permisos, ya que tiene acceso ilimitado al almacén de objetos. En su lugar, cree un usuario o grupo con privilegios administrativos que asigne.

**** Un nivel de calidad de servicio (rendimiento) que es el más alto disponible para su sistema.


*** Puede hacer clic en *más opciones* para configurar los permisos de usuario y el nivel de rendimiento al configurar el bloque, o puede modificar esta configuración más tarde.
+
**** Debe haber creado usuarios y grupos antes de utilizar *más opciones* para configurar sus permisos.
**** Si tiene la intención de utilizar el almacén de objetos S3 para la organización en niveles de FabricPool, considere la posibilidad de seleccionar *utilizar para la organización en niveles* (utilizar medios de bajo coste con un rendimiento óptimo para los datos organizados en niveles) en lugar de un nivel de servicio de rendimiento.






. En aplicaciones de cliente S3, otro sistema ONTAP o una aplicación de terceros externa, verifique el acceso al nuevo bloque introduciendo lo siguiente:
+
** El certificado de CA de servidor S3.
** Clave secreta y clave de acceso del usuario.
** El nombre FQDN del servidor S3 y el nombre de bloque.




--
====