---
permalink: s3-config/generate-access-keys-api.html 
sidebar: sidebar 
keywords: generate, ldap, s3, access keys, secret keys using API 
summary: Los usuarios de S3 pueden regenerar las claves para acceder a clientes de S3 mediante la API. 
---
= Habilite LDAP o usuarios de dominio para generar sus propias claves de acceso de ONTAP S3
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.14.1, como administrador de ONTAP, puede crear roles personalizados y concederles a grupos de dominio locales o a grupos de protocolo ligero de acceso a directorios (LDAP), de modo que los usuarios que pertenecen a esos grupos puedan generar sus propias claves secretas y de acceso para el acceso de clientes S3.

Debe realizar algunos pasos de configuración en la máquina virtual de almacenamiento para poder crear y asignar el rol personalizado al usuario que llama a la API para generar claves de acceso.


NOTE: Si LDAP está deshabilitado, puede link:configure-access-ldap.html["Configurar servicios de directorio externos para el acceso a ONTAP S3"] para permitir a los usuarios generar claves de acceso.

.Antes de empezar
Asegúrese de lo siguiente:

. Se creó una máquina virtual de almacenamiento habilitada para S3 que contiene un servidor S3. Consulte link:../s3-config/create-svm-s3-task.html["Cree una SVM para S3"].
. Se ha creado un bloque en esa máquina virtual de almacenamiento. Consulte link:../s3-config/create-bucket-task.html["Crear un bucket"].
. DNS está configurado en la máquina virtual de almacenamiento. Consulte link:../networking/configure_dns_services_auto.html["Configure los servicios DNS"].
. Hay un certificado de entidad de certificación raíz (CA) autofirmado del servidor LDAP instalado en la máquina virtual de almacenamiento. Consulte link:../nfs-config/install-self-signed-root-ca-certificate-svm-task.html["Instalar certificados CA raíz autofirmados en la SVM"].
. Se configura un cliente LDAP con TLS habilitado en la máquina virtual de almacenamiento. Consulte link:../nfs-config/create-ldap-client-config-task.html["Crear configuraciones de cliente LDAP para el acceso NFS de ONTAP"].
. Asocie la configuración del cliente al Vserver. Consulte link:../nfs-config/enable-ldap-svms-task.html["Asociar configuraciones de cliente LDAP con SVM NFS de ONTAP"]. Obtenga más información sobre `vserver services name-service ldap create` en el link:https://docs.netapp.com/us-en/ontap-cli//vserver-services-name-service-ldap-create.html["Referencia de comandos del ONTAP"^].
. Si utiliza una máquina virtual de almacenamiento de datos, cree una interfaz de red de gestión (LIF) y en la máquina virtual, así como una política de servicio para la LIF. Obtenga más información sobre `network interface create` y `network interface service-policy create` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["Referencia de comandos del ONTAP"^].




== Configurar usuarios para la generación de claves de acceso

.Pasos
[role="tabbed-block"]
====
.Usuarios de LDAP
--
. Especifique LDAP como la base de datos del servicio _name_ de la máquina virtual de almacenamiento para el grupo y la contraseña a LDAP:
+
[source, cli]
----
ns-switch modify -vserver <vserver-name> -database group -sources files,ldap
ns-switch modify -vserver <vserver-name> -database passwd -sources files,ldap
----
+
Obtenga más información sobre `vserver services name-service ns-switch modify` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-services-name-service-ns-switch-modify.html["Referencia de comandos del ONTAP"^].

. Crear un rol personalizado con acceso al punto final de la API REST DE S3 usuarios:
`security login rest-role create -vserver <vserver-name> -role <custom-role-name> -api "/api/protocols/s3/services/*/users" -access <access-type>` En este ejemplo, el `s3-role` rol se genera para los usuarios de la VM de almacenamiento `svm-1` , a los que se otorgan todos los derechos de acceso, lectura, creación y actualización.
+
[listing]
----
security login rest-role create -vserver svm-1 -role s3role -api "/api/protocols/s3/services/*/users" -access all
----
+
Obtenga más información sobre `security login rest-role create` en el link:https://docs.netapp.com/us-en/ontap-cli/security-login-rest-role-create.html["Referencia de comandos del ONTAP"^].

. Cree un grupo de usuarios LDAP con el  `security login` comando y agregue el nuevo rol personalizado para acceder al punto final de la API REST del usuario S3. Obtenga más información sobre  `security login create` en el link:https://docs.netapp.com/us-en/ontap-cli//security-login-create.html["Referencia de comandos del ONTAP"^] .
+
[source, cli]
----
security login create -user-or-group-name <ldap-group-name> -application http -authentication-method nsswitch -role <custom-role-name> -is-ns-switch-group yes
----
+
En este ejemplo, el grupo LDAP `ldap-group-1` se crea en `svm-1`y `s3role` se agrega el rol personalizado para acceder al punto final de la API, junto con la activación del acceso LDAP en el modo de enlace rápido.

+
[listing]
----
security login create -user-or-group-name ldap-group-1 -application http -authentication-method nsswitch -role s3role -is-ns-switch-group yes -second-authentication-method none -vserver svm-1 -is-ldap-fastbind yes
----
+
Para obtener más información, consulte link:../nfs-admin/ldap-fast-bind-nsswitch-authentication-task.html["Utilice el enlace rápido LDAP para la autenticación nsswitch para SVM NFS de ONTAP"].

+
Obtenga más información sobre `security login create` en el link:https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["Referencia de comandos del ONTAP"^].



Agregar el rol personalizado al grupo LDAP permite a los usuarios de ese grupo un acceso limitado a ONTAP  `/api/protocols/s3/services/{svm.uuid}/users` Punto final. Al invocar la API, los usuarios del grupo LDAP pueden generar sus propias claves de acceso y secretas para acceder al cliente S3. Pueden generar las claves solo para ellos mismos y no para otros usuarios.

--
.Usuarios del dominio
--
. Cree un rol personalizado con acceso al punto final de la API REST del usuario S3:


[source, cli]
----
security login rest-role create -vserver <vserver-name> -role <custom-role-name> -api "/api/protocols/s3/services/*/users" -access <access-type>
----
En este ejemplo, el  `s3-role` Se genera un rol para los usuarios en la máquina virtual de almacenamiento  `svm-1` , al que se le conceden todos los derechos de acceso, lectura, creación y actualización.

[listing]
----
security login rest-role create -vserver svm-1 -role s3role -api "/api/protocols/s3/services/*/users" -access all
----
Obtenga más información sobre `security login rest-role create` en el link:https://docs.netapp.com/us-en/ontap-cli/security-login-rest-role-create.html["Referencia de comandos del ONTAP"^].

. Cree un grupo de usuarios de dominio con el  `security login` comando y agregue el nuevo rol personalizado para acceder al punto final de la API REST del usuario S3. Obtenga más información sobre  `security login create` en el link:https://docs.netapp.com/us-en/ontap-cli//security-login-create.html["Referencia de comandos del ONTAP"^] .
+
[source, cli]
----
security login create -vserver <vserver-name> -user-or-group-name domain\<group-name> -application http -authentication-method domain -role <custom-role-name>
----
+
En este ejemplo, el grupo de dominio  `domain\group1` se crea en  `svm-1` , y el rol personalizado  `s3role` Se agrega para acceder al punto final de la API.

+
[listing]
----
security login create -user-or-group-name domain\group1 -application http -authentication-method domain -role s3role -vserver svm-1
----
+
Obtenga más información sobre `security login create` en el link:https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["Referencia de comandos del ONTAP"^].



Agregar el rol personalizado al grupo de dominio permite a los usuarios de ese grupo un acceso limitado a ONTAP  `/api/protocols/s3/services/{svm.uuid}/users` Punto final. Al invocar la API, los usuarios del grupo de dominio pueden generar sus propias claves de acceso y secretas para acceder al cliente S3. Pueden generar las claves solo para ellos mismos y no para otros usuarios.

--
====


== Como usuario S3 o LDAP, genere sus propias claves de acceso

A partir de ONTAP 9.14.1, puede generar sus propias claves de acceso y secretas para acceder a clientes S3, si su administrador le ha otorgado el rol para generar sus propias claves. Puede generar claves únicamente para usted mediante el siguiente extremo de la API REST DE ONTAP.

.Crear un usuario S3 y generar claves
Esta llamada a la API REST utiliza el siguiente método y punto de conexión. Para obtener más información sobre este punto de conexión, consulte la referencia.  https://docs.netapp.com/us-en/ontap-automation/reference/api_reference.html#access-a-copy-of-the-ontap-rest-api-reference-documentation["Documentación de API"] .

[cols="25,75"]
|===
| Método HTTP | Ruta 


| PUBLICAR | /api/protocols/s3/services/{svm.uid}/usuarios 
|===
Para los usuarios del dominio, utilice el siguiente formato para el nombre de usuario S3:  `user@fqdn` , dónde  `fqdn` es el nombre de dominio completo del dominio.

.Ejemplo de curl
[source, curl]
----
curl
--request POST \
--location "https://$FQDN_IP /api/protocols/s3/services/{svm.uuid}/users " \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
--data '{"name":"user1@example.com"}'
----
.Ejemplo de resultado JSON
[listing]
----
{
  "records": [
    {
      "access_key": "4KX07KF7ML8YNWY01JWG",
      "_links": {
        "next": {
          "href": "/api/resourcelink"
        },
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "name": "user1@example.com",
      "secret_key": "<secret_key_value>"
    }
  ],
  "num_records": "1"
}

----
.Regenerar claves para un usuario de S3
Si ya existe un usuario de S3, puede regenerar sus claves de acceso y secretas. Esta llamada a la API REST utiliza el siguiente método y punto de conexión.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| PARCHE | /api/protocolos/s3/servicios/{svm.uuid}/usuarios/{nombre} 
|===
.Ejemplo de curl
[source, curl]
----
curl
--request PATCH \
--location "https://$FQDN_IP /api/protocols/s3/services/{svm.uuid}/users/{name} " \
--include \
--header "Authorization: Basic $BASIC_AUTH" \
--data '{"regenerate_keys":"True"}'
----
.Ejemplo de resultado JSON
[listing]
----
{
  "records": [
    {
      "access_key": "DX12U609DMRVD8U30Z1M",
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "name": "user1@example.com",
      "secret_key": "<secret_key_value>"
    }
  ],
  "num_records": "1"
}

----