---
permalink: s3-config/generate-access-keys-api.html 
sidebar: sidebar 
keywords: generate, ldap, s3, access keys, secret keys using API 
summary: Los usuarios de S3 pueden regenerar las claves para acceder a clientes de S3 mediante la API. 
---
= Habilite LDAP o usuarios de dominio para generar sus propias claves de acceso de ONTAP S3
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.14.1, como administrador de ONTAP, puede crear roles personalizados y concederles a grupos de dominio locales o a grupos de protocolo ligero de acceso a directorios (LDAP), de modo que los usuarios que pertenecen a esos grupos puedan generar sus propias claves secretas y de acceso para el acceso de clientes S3.

Debe realizar algunos pasos de configuración en la máquina virtual de almacenamiento para poder crear y asignar el rol personalizado al usuario que llama a la API para generar claves de acceso.


NOTE: Si LDAP está deshabilitado, puede usar link:../smb-config/create-server-active-directory-domain-task.html["Active Directory y SMB con autenticación basada en dominio"] para generar claves de acceso.

.Antes de empezar
Asegúrese de lo siguiente:

. Se creó una máquina virtual de almacenamiento habilitada para S3 que contiene un servidor S3. Consulte link:../s3-config/create-svm-s3-task.html["Cree una SVM para S3"].
. Se ha creado un bloque en esa máquina virtual de almacenamiento. Consulte link:../s3-config/create-bucket-task.html["Crear un bucket"].
. DNS está configurado en la máquina virtual de almacenamiento. Consulte link:../networking/configure_dns_services_manual.html["Configure los servicios DNS"].
. Hay un certificado de entidad de certificación raíz (CA) autofirmado del servidor LDAP instalado en la máquina virtual de almacenamiento. Consulte link:../nfs-config/install-self-signed-root-ca-certificate-svm-task.html["Instale el certificado de CA raíz autofirmado en la SVM"].
. Se configura un cliente LDAP con TLS habilitado en la máquina virtual de almacenamiento. Consulte link:../nfs-config/create-ldap-client-config-task.html["Cree una configuración de cliente LDAP"].
. Asocie la configuración del cliente al Vserver. Consulte link:../nfs-config/enable-ldap-svms-task.html["Asocie la configuración del cliente LDAP con las SVM"]. Obtenga más información sobre `vserver services name-service ldap create` en el link:https://docs.netapp.com/us-en/ontap-cli//vserver-services-name-service-ldap-create.html["Referencia de comandos de la ONTAP"^].
. Si utiliza una máquina virtual de almacenamiento de datos, cree una interfaz de red de gestión (LIF) y en la máquina virtual, así como una política de servicio para la LIF. Obtenga más información acerca de[`network interface create` los comandos ^] y[`network interface service-policy create`^] en la referencia de comandos de la ONTAP.




== Configurar usuarios para la generación de claves de acceso

. Especifique LDAP como la base de datos del servicio _name_ de la máquina virtual de almacenamiento para el grupo y la contraseña a LDAP:
+
[listing]
----
ns-switch modify -vserver <vserver-name> -database group -sources files,ldap
ns-switch modify -vserver <vserver-name> -database passwd -sources files,ldap
----
+
Obtenga más información sobre `vserver services name-service ns-switch modify` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-services-name-service-ns-switch-modify.html["Referencia de comandos de la ONTAP"^].

. Cree un rol personalizado con acceso al extremo de la API de REST DE S3 usuarios:
`security login rest-role create -vserver <vserver-name> -role <custom-role-name> -api "/api/protocols/s3/services/*/users" -access <access-type>`
En este ejemplo, la `s3-role` Se genera el rol para los usuarios en la máquina virtual de almacenamiento `svm-1`, a los que se otorgan todos los derechos de acceso, leer, crear y actualizar.
+
[listing]
----
security login rest-role create -vserver svm-1 -role s3role -api "/api/protocols/s3/services/*/users" -access all
----
+
Obtenga más información sobre `security login rest-role create` en el link:https://docs.netapp.com/us-en/ontap-cli/security-login-rest-role-create.html["Referencia de comandos de la ONTAP"^].

. Cree un grupo de usuarios LDAP con el comando security login y añada el nuevo rol personalizado para acceder al punto final de la API DE REST DE usuarios de S3. Obtenga más información sobre `security login create` en el link:https://docs.netapp.com/us-en/ontap-cli//security-login-create.html["Referencia de comandos de la ONTAP"^].
+
[listing]
----
security login create -user-or-group-name <ldap-group-name> -application http -authentication-method nsswitch -role <custom-role-name> -is-ns-switch-group yes
----
+
En este ejemplo, el grupo LDAP `ldap-group-1` se crea en `svm-1`, y el rol personalizado `s3role` Se ha añadido a él para acceder al punto final de la API, junto con la habilitación del acceso LDAP en el modo de enlace rápido.

+
[listing]
----
security login create -user-or-group-name ldap-group-1 -application http -authentication-method nsswitch -role s3role -is-ns-switch-group yes -second-authentication-method none -vserver svm-1 -is-ldap-fastbind yes
----
+
Para obtener más información, consulte link:../nfs-admin/ldap-fast-bind-nsswitch-authentication-task.html["Utilice el enlace rápido LDAP para la autenticación nsswitch"].



Al agregar el rol personalizado al dominio o grupo LDAP, los usuarios de ese grupo tendrán acceso limitado a la ONTAP `/api/protocols/s3/services/{svm.uuid}/users` extremo. Al invocar la API, los usuarios del grupo de dominio o LDAP pueden generar su propio acceso y claves secretas para acceder al cliente S3. Pueden generar las claves solo para ellos mismos y no para otros usuarios.



== Como usuario S3 o LDAP, genere sus propias claves de acceso

A partir de ONTAP 9.14.1, puede generar sus propias claves de acceso y secretas para acceder a clientes S3, si su administrador le ha otorgado el rol para generar sus propias claves. Puede generar claves únicamente para usted mediante el siguiente extremo de la API REST DE ONTAP.

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo. Para obtener información sobre los otros métodos de este punto final, consulte la referencia https://docs.netapp.com/us-en/ontap-automation/reference/api_reference.html#access-a-copy-of-the-ontap-rest-api-reference-documentation["Documentación de API"].

[cols="25,75"]
|===
| Método HTTP | Ruta 


| PUBLICAR | /api/protocols/s3/services/{svm.uid}/usuarios 
|===
.Ejemplo de curl
[source, curl]
----
curl
--request POST \
--location "https://$FQDN_IP /api/protocols/s3/services/{svm.uuid}/users " \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
--data '{"name":"_name_"}'
----
.Ejemplo de resultado JSON
[listing]
----
{
  "records": [
    {
      "access_key": "Pz3SB54G2B_6dsXQPrA5HrTPcf478qoAW6_Xx6qyqZ948AgZ_7YfCf_9nO87YoZmskxx3cq41U2JAH2M3_fs321B4rkzS3a_oC5_8u7D8j_45N8OsBCBPWGD_1d_ccfq",
      "_links": {
        "next": {
          "href": "/api/resourcelink"
        },
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "name": "user-1",
      "secret_key": "A20_tDhC_cux2C2BmtL45bXB_a_Q65c_96FsAcOdo14Az8V31jBKDTc0uCL62Bh559gPB8s9rrn0868QrF38_1dsV2u1_9H2tSf3qQ5xp9NT259C6z_GiZQ883Qn63X1"
    }
  ],
  "num_records": "1"
}

----