---
permalink: s3-config/ontap-version-support-s3-concept.html 
sidebar: sidebar 
keywords: ontap, version, support, s3, object, storage, AWS S3, Azure S3, cloud volumes ontap, aws, azure 
summary: ONTAP es compatible con el almacenamiento de objetos S3 para entornos locales que comienzan con ONTAP 9.8. Cloud Volumes ONTAP admite el almacenamiento de objetos S3 para entornos cloud que empiezan por ONTAP 9.9.1. 
---
= Compatibilidad de versiones de ONTAP para el almacenamiento de objetos S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El almacenamiento de objetos S3 es compatible con todas las plataformas AFF, FAS y ONTAP Select, utilizando ONTAP 9,8 y versiones posteriores.

Como con otros protocolos como FC, iSCSI, NFS, NVMe_oF y SMB, S3 Requiere la instalación de una licencia antes de poder utilizarla en ONTAP. La licencia de S3 es una licencia sin coste, pero debe instalarse en sistemas que actualicen a ONTAP 9,8. La licencia S3 puede descargarse desde el link:https://mysupport.netapp.com/site/systems/master-license-keys/ontaps3["Claves de licencia principales"^] sitio de soporte de NetApp.

Los nuevos sistemas ONTAP 9,8 y posteriores tienen la licencia S3 preinstalada.



== Cloud Volumes ONTAP

ONTAP S3 está configurado y funciona igual en Cloud Volumes ONTAP que en entornos locales, con una excepción:

* Cuando cree buckets en Cloud Volumes ONTAP, debe utilizar el procedimiento de la CLI para asegurarse de que el volumen de FlexGroup subyacente solo utilice agregados de un único nodo. El uso de agregados de varios nodos afectará al rendimiento, ya que estos estarán en zonas de disponibilidad separadas geográficamente y serán susceptibles a problemas de latencia.


|===
| Proveedor de cloud | Versión de ONTAP 


| Azure | ONTAP 9.9.1 y versiones posteriores 


| AWS | ONTAP 9.11.0 y versiones posteriores 


| Google Cloud | ONTAP 9.12.1 y versiones posteriores 
|===


== Amazon FSX para ONTAP de NetApp

El almacenamiento de objetos S3 es compatible con servicios de Amazon FSx para NetApp mediante ONTAP 9,11 y versiones posteriores.



== Soporte de S3 con MetroCluster

A partir de ONTAP 9.14.1, puede habilitar un servidor de almacenamiento de objetos S3 en una SVM en un agregado reflejado en configuraciones IP y FC de MetroCluster.

A partir de ONTAP 9.12.1, se puede habilitar un servidor de almacenamiento de objetos S3 en una SVM en un agregado no reflejado en una configuración IP de MetroCluster. Para obtener más información sobre las limitaciones de los agregados no reflejados en las configuraciones IP de MetroCluster, consulte link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/considerations_unmirrored_aggrs.html["Consideraciones sobre los agregados no reflejados"^].



== Vista previa pública de S3 en ONTAP 9.7

En ONTAP 9.7, el almacenamiento de objetos S3 se introdujo como una vista previa pública. Esta versión no estaba destinada a entornos de producción y ya no se actualizará a partir de ONTAP 9.8. Solo ONTAP 9.8 y las versiones posteriores admiten el almacenamiento de objetos S3 en entornos de producción.

Los bloques de S3 creados con la vista previa pública de 9.7 pueden usarse en ONTAP 9.8 y versiones posteriores, pero no pueden aprovechar las mejoras de funciones. Si ha creado bloques con la vista previa pública de 9.7, debe migrar el contenido de esos bloques a 9.8 bloques para garantizar el soporte de la función, la seguridad y las mejoras de rendimiento.
