---
permalink: s3-config/storage-service-definitions-reference.html 
sidebar: sidebar 
keywords: storage, service, definitions 
summary: ONTAP incluye servicios de almacenamiento predefinidos que están asignados a factores mínimos de rendimiento correspondientes. 
---
= Niveles de servicio de almacenamiento S3 de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP incluye servicios de almacenamiento predefinidos que están asignados a factores mínimos de rendimiento correspondientes.

El conjunto real de servicios de almacenamiento disponibles en un clúster o SVM está determinado por el tipo de almacenamiento que compone un agregado en la SVM.

En la siguiente tabla se muestra cómo se asignan los factores mínimos de rendimiento a los servicios de almacenamiento predefinidos:

[cols="6*"]
|===
| Servicio de almacenamiento | IOPS (SLA) esperada | Pico de IOPS (SLO) | IOPS de volumen mínimo | Latencia estimada | ¿Se espera que las IOPS se apliquen? 


 a| 
valor
 a| 
128 $ por TB
 a| 
512 $ por TB
 a| 
75
 a| 
17 ms
 a| 
En AFF: Sí

En caso contrario: No



 a| 
rendimiento
 a| 
2048 $ por TB
 a| 
4096 $ por TB
 a| 
500
 a| 
2 ms
 a| 
Sí



 a| 
extremo
 a| 
6144 $ por TB
 a| 
12288 $ por TB
 a| 
1000
 a| 
1 ms
 a| 
Sí

|===
En la siguiente tabla se define el nivel de servicio de almacenamiento disponible para cada tipo de medios o nodo:

[cols="2*"]
|===
| Medios o nodo | Nivel de servicio de almacenamiento disponible 


 a| 
Disco
 a| 
valor



 a| 
Disco de máquina virtual
 a| 
valor



 a| 
LUN de FlexArray
 a| 
valor



 a| 
Híbrido
 a| 
valor



 a| 
Flash con optimización de la capacidad
 a| 
valor



 a| 
Unidad de estado sólido (SSD): No AFF
 a| 
valor



 a| 
Flash optimizado para el rendimiento - SSD (AFF)
 a| 
extremo, rendimiento, valor

|===