---
permalink: snaplock/snaplock-apis-reference.html 
sidebar: sidebar 
keywords: snaplock, api, zephyr, xml, scripts, workflow 
summary: Puede utilizar las API de Zephyr para integrar la funcionalidad de SnapLock en scripts o automatización de flujos de trabajo. Las API utilizan mensajería XML a través de HTTP, HTTPS y DCE/RPC de Windows. 
---
= API de SnapLock
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar las API de Zephyr para integrar la funcionalidad de SnapLock en scripts o automatización de flujos de trabajo. Las API utilizan mensajería XML a través de HTTP, HTTPS y DCE/RPC de Windows. Obtenga más información en el link:https://docs.netapp.com/us-en/ontap-automation/["Documentación de automatización de ONTAP"^].



== archivo-huella-abortar

Anular una operación de huellas digitales de archivo.



== volcado de huellas digitales de archivo

Mostrar información de huellas digitales del archivo.



== file-fingerprint-get-iter

Muestra el estado de las operaciones de huella digital de archivos.



== inicio de la huella digital de archivo

Genere una huella digital de archivo.



== snaplock-archive-vserver-log

Archive el archivo de registro de auditoría activo.



== snaplock-create-vserver-log

Cree una configuración de registro de auditoría para una SVM.



== snaplock-delete-vserver-log

Eliminar una configuración de registro de auditoría para una SVM.



== snaplock-file-privileged-delete

Ejecute una operación de eliminación privilegiada.



== snaplock-get-file-retention

Obtenga el período de retención de un archivo.



== snaplock-get-node-compliance-clock

Obtenga la fecha y la hora de la instancia de ComplianceClock del nodo.



== snaplock-get-vserver-activo-log-files-iter

Mostrar el estado de los archivos de registro activos.



== snaplock-get-vserver-log-iter

Muestre la configuración del registro de auditoría.



== snaplock-modify-vserver-log

Modifique la configuración del registro de auditoría para una SVM.



== retención de conjuntos de archivos de snaplock

Establezca el tiempo de retención de un archivo.



== snaplock-set-node-compliance-clock

Establezca la fecha y la hora de la instancia de ComplianceClock del nodo.



== snaplock-volume-set-privileged-delete

Establezca la opción Privileged-delete en un volumen SnapLock Enterprise.



== volume-get-snaplock-attrs

Obtenga los atributos de un volumen de SnapLock.



== volume-set-snaplock-attrs

Configure los atributos de un volumen SnapLock.
