---
permalink: nfs-trunking/adapt-exports-overview.html 
sidebar: sidebar 
keywords: NFS, servers, network, NFS trunking, adapt, single-path 
summary: 'Puede adaptar una exportación NFS de ruta única existente (no troncalizada) para utilizar la conexión de enlaces.' 
---
= Visión general de la adaptación de exportaciones de una ruta de acceso única
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede adaptar una exportación NFSv4,1 de ruta única existente (no troncalizada) para utilizar troncalización. Los clientes compatibles con trunking pueden aprovechar el rendimiento mejorado en cuanto se activa la troncalización en el servidor, siempre y cuando se cumplan los requisitos previos del servidor y del cliente.

La adaptación de una exportación de ruta única para la conexión de enlaces le permite mantener conjuntos de datos exportados en sus volúmenes y SVM existentes. Para ello, debe habilitar la conexión troncal en el servidor NFS, actualizar la configuración de redes y exportación y volver a montar el recurso compartido exportado en los clientes.

La activación de la conexión troncal tiene el efecto de reiniciar el servidor. Luego, los clientes de VMware deben volver a montar los almacenes de datos exportados; los clientes Linux deben volver a montar los volúmenes exportados con el `max_connect` opción.
