---
permalink: nfs-trunking/client-mount-task.html 
sidebar: sidebar 
keywords: NFS, servers, network, NFS trunking, data shares, Linux, VMware, mounts 
summary: Los clientes de Linux y VMware compatibles con la conexión de enlaces pueden montar volúmenes o recursos compartidos de datos desde un servidor NFS de ONTAP que esté habilitado para la conexión de enlaces. 
---
= Montaje de volúmenes de ONTAP o recursos compartidos de datos para la conexión de enlaces NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los clientes de Linux y VMware compatibles con la conexión de enlaces pueden montar volúmenes o recursos compartidos de datos desde un servidor ONTAP NFSv4,1 que esté habilitado para la conexión de enlaces.

Descubra link:index.html#supported-clients["clientes admitidos"].

[role="tabbed-block"]
====
.Requisitos del cliente Linux
--
Si utiliza ONTAP 9.16.1 o posterior y Red Hat Enterprise Linux versión 8,7 o posterior (para RHEL 8) o 9,2 o posterior (para RHEL 9) como cliente Linux, solo se necesita un punto de montaje para el grupo de enlaces. Monte los volúmenes exportados con este comando con `trunkdiscovery` la opción:

[source, cli]
----
mount <lif_ip>:<volume_name> </mount_path> -o trunkdiscovery,vers=4.1
----
De lo contrario, se necesita un punto de montaje independiente para cada conexión del grupo de troncalización. Monte el volumen exportado con comandos similares a los siguientes, con la `max_connect` opción:

[source, cli]
----
mount <lif1_ip>:<volume_name> </mount_path1> -o vers=4.1,max_connect=16
----
[source, cli]
----
mount <lif2_ip>:<volume_name> </mount_path2> -o vers=4.1,max_connect=16
----
La versión (`vers`) el valor debe ser `4.1` o posterior.

La `max_connect` el valor corresponde al número de conexiones del grupo de troncalización.

--
.Requisitos del cliente de VMware
--
Se necesita una sentencia mount que incluya una dirección IP para cada conexión del grupo de enlaces.

Monte el almacén de datos exportado con un comando similar al siguiente:

`#esxcli storage nfs41 -H lif1_ip, lif2_ip -s /mnt/sh are1 -v nfs41share`

La `-H` los valores corresponden a las conexiones del grupo de troncalización.

--
====