---
permalink: nfs-trunking/enable-server-task.html 
sidebar: sidebar 
keywords: NFS, servers, enable, NFS, trunking, enabled, NAS, svm, 
summary: La conexión de enlaces debe estar explícitamente habilitada en servidores NFS que ejecuten NFSv4,1 y posteriores. NFSv4,1 y las versiones posteriores se habilitan de forma predeterminada cuando se crean servidores NFS. 
---
= Habilite la conexión troncal en un servidor NFS de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La conexión troncal debe estar explícitamente habilitada en los servidores NFS. NFSv4,1 está habilitado de forma predeterminada cuando se crean servidores NFS.

Después de activar la conexión troncal, verifique que los siguientes servicios estén configurados según sea necesario.

* link:../nfs-config/configure-dns-host-name-resolution-task.html["DNS"]
* link:../nfs-config/using-ldap-concept.html["LDAP"]
* link:../nfs-config/kerberos-nfs-strong-security-concept.html["Kerberos"]


.Pasos
. Active la conexión troncal y asegúrese de que NFSv4,1 está activado:
+
`vserver nfs create -vserver _svm_name_ -v4.1 enabled -v4.1-trunking enabled`

. Compruebe que NFS se está ejecutando:
`vserver nfs status -vserver _svm_name_`
. Compruebe que NFS está configurado como se desea:
+
`vserver nfs show -vserver _svm_name_`

+
Más información sobre link:../nfs-config/create-server-task.html["Configuración del servidor NFS."].. Si ofrece servicio a clientes de Windows desde esta SVM, mueva los recursos compartidos y elimine el servidor.
`vserver cifs show -vserver _svm_name_`

+
+
`vserver cifs delete -vserver _svm_name_`


