---
permalink: nfs-trunking/prepare-network-task.html 
sidebar: sidebar 
keywords: NFS, servers, network, prepare, NFS trunking, LIF, trunking group, NIC 
summary: Para aprovechar la conexión de enlaces NFSv4,1, los LIF de un grupo de enlaces deben residir en el mismo nodo y tener puertos de inicio en el mismo nodo. 
---
= Prepare la red para la conexión de enlaces NFS de ONTAP
:allow-uri-read: 


[role="lead"]
Para aprovechar la conexión de enlaces NFSv4,1, los LIF de un grupo de enlaces deben residir en el mismo nodo y tener puertos de inicio en el mismo nodo. Las LIF deben estar configuradas en un grupo de conmutación por error del mismo nodo.

.Acerca de esta tarea
Una asignación uno a uno de LIF y NIC proporciona la mayor ganancia de rendimiento, pero no es necesaria para permitir la conexión de enlaces. Tener al menos dos NIC instaladas puede ofrecer un beneficio de rendimiento, pero no es necesario.

Todas las LIF del grupo de enlaces deben pertenecer al mismo grupo de conmutación al nodo de respaldo. Tenga en cuenta que cuando las LIF están configuradas en un grupo de conmutación por error en el mismo nodo, una recuperación tras fallos de controladora de ese nodo puede provocar que las LIF se desconecten. Si las LIF no están configuradas en un grupo de recuperación tras fallos en el mismo nodo y la recuperación tras fallos a otro nodo, la conexión de enlaces ya no funcionará.

Debe ajustar el grupo de conmutación por error de troncalización cada vez que agregue o elimine conexiones (y NIC subyacentes) de un grupo de conmutación por error.

.Antes de empezar
* Debe conocer los nombres de puerto asociados a las NIC para crear un grupo de conmutación por error.
* Los puertos deben estar todos en el mismo nodo.


.Pasos
. Compruebe los nombres y el estado de los puertos de red que desea utilizar:
+
[source, cli]
----
network port show
----
. Cree el grupo de failover:
+
`network interface failover-groups create -vserver <svm_name> -failover-group <failover_group_name> -targets <ports_list>`

+

NOTE: No es un requisito tener un grupo de recuperación tras fallos, pero es muy recomendable.

+
** `<svm_name>` Es el nombre de la SVM que contiene el servidor NFS.
** `<ports_list>` es la lista de puertos que se agregarán al grupo de failover.
+
Los puertos se agregan en el formato `<node_name>:<port_number>`, por ejemplo `node1:e0c`: .

+
El siguiente comando crea el grupo de conmutación al nodo de respaldo FG3 para SVM VS1 y añade tres puertos:

+
`network interface failover-groups create -vserver vs1 -failover-group fg3 -targets cluster1-01:e0c,cluster1-01:e0d,cluster1-01:e0e`

+
Más información acerca de link:../networking/configure_failover_groups_and_policies_for_lifs_overview.html["grupos de conmutación por error."]

+
Obtenga más información sobre `network interface failover-groups create` en el link:https://docs.netapp.com/us-en/ontap-cli/network-interface-failover-groups-create.html["Referencia de comandos del ONTAP"^].



. Si es necesario, cree LIF para los miembros del grupo de enlaces:
+
`network interface create -vserver <svm_name> -lif <lif_name> -home-node <node_name> -home-port <port_name> -address <IP_address> -netmask <IP_address> [-service-policy <policy>] [-auto-revert <true|false>]`

+
** `-home-node` - El nodo al que regresa la LIF cuando se ejecuta el comando network interface revert en la LIF.
+
También puede especificar si el LIF debe volver automáticamente al nodo de inicio y al puerto de inicio con `-auto-revert` la opción.

** `-home-port` Es el puerto físico o lógico al que devuelve la LIF cuando el comando de reversión de la interfaz de red se ejecuta en la LIF.
** Puede especificar una dirección IP con las `-address` `-netmask` opciones y, no con `-subnet` la opción.
** Al asignar direcciones IP, es posible que deba configurar una ruta predeterminada a una puerta de enlace si hay clientes o controladores de dominio en una subred IP diferente. Obtenga más información sobre `network route create` y cómo crear una ruta estática dentro de una SVM en el link:https://docs.netapp.com/us-en/ontap-cli/network-route-create.html["Referencia de comandos del ONTAP"^].
** `-service-policy` - La política de servicio para la LIF. Si no se especifica ninguna política, se asignará automáticamente una política predeterminada. Utilice `network interface service-policy show` el comando para revisar las políticas de servicio disponibles.
** `-auto-revert` - Especificar si una LIF de datos se revierte automáticamente a su nodo de inicio en circunstancias como el inicio, cambios en el estado de la base de datos de administración, o cuando se realiza la conexión de red. La configuración predeterminada es false, pero puede establecerla en true en función de las políticas de gestión de red del entorno.
+
Repita este paso para cada LIF del grupo de enlaces.

+
El siguiente comando crea `lif-A` para la SVM `vs1`, en el puerto `e0c` del nodo `cluster1_01`:

+
`network interface create -vserver vs1 -lif lif-A -service-policy default-intercluster -home-node cluster1_01 -home-port e0c -address 192.0.2.0`

+
Más información acerca de link:../networking/create_lifs.html["Creación de LIF."]



. Comprobar que se han creado las LIF:
+
[source, cli]
----
network interface show
----
. Compruebe que se pueda acceder a la dirección IP configurada:
+
[cols="25,75"]
|===
| Para verificar una... | Usar... 


| Dirección IPv4 | `network ping` 


| Dirección IPv6 | `network ping6` 
|===


.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/network-ping.html["ping de red"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["interfaz de red"^]
* link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["muestra el puerto de red"^]

