---
permalink: cloud/file-sharing-nfs-smb-concept.html 
sidebar: sidebar 
keywords: file sharing, nfs, smb 
summary: Los protocolos NFS y SMBprotocols se utilizan para hacer que los recursos compartidos y los archivos estén disponibles para las aplicaciones cliente a través de una red. Cloud Volumes ONTAP le permite proporcionar archivos desde un cloud público mediante uno o ambos protocolos. 
---
= Uso compartido de archivos con NFS y SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los protocolos NFS y SMB se utilizan para hacer que los recursos compartidos y los archivos estén disponibles para las aplicaciones cliente en una red. Cloud Volumes ONTAP le permite proporcionar archivos desde un cloud público mediante uno o ambos protocolos.

Si decide mover toda una carga de trabajo al cloud, Cloud Volumes ONTAP permite que su aplicación funcione con el almacenamiento en el cloud exactamente como lo hace en las instalaciones. No es necesario cambiar su aplicación y, si decide cambiar a un proveedor de cloud diferente, no tendrá que preocuparse por el bloqueo del proveedor. Los mismos comandos y scripts que se utilizan para gestionar los servicios de archivos en las instalaciones funcionan en el cloud.

En el cloud, es posible escalar recursos compartidos de archivos rápidamente, añadiendo o quitando instancias de almacenamiento y computación, o ajustando el nivel de servicio según sea necesario para responder a los cambios en la demanda de los clientes sin incurrir en gastos de capital. Cuantos más recursos utilice, más pagará, pero solo cuando use los recursos.

La tecnología SnapMirror de NetApp mueve y sincroniza sus datos de archivos entre su sistema ONTAP en las instalaciones y Cloud Volumes ONTAP. Puede mover los datos fácilmente desde y hacia el cloud, o entre proveedores de cloud.

.Información relacionada
https://["BlueXP: Aprovisionamiento de almacenamiento"]

https://["Gestionar volúmenes para Azure NetApp Files"]

https://["Gestionar Cloud Volumes Service para AWS"]
