---
permalink: cloud/high-availability-concept.html 
sidebar: sidebar 
keywords: high availability 
summary: En un centro de datos en las instalaciones, los nodos físicos están configurados en pares de alta disponibilidad para tolerancia a fallos y operaciones no disruptivas. Si un nodo falla o si necesita desconectar un nodo para realizar un mantenimiento rutinario, su partner toma el control de su almacenamiento y sigue sirviendo datos desde él. 
---
= Alta disponibilidad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En un centro de datos en las instalaciones, los nodos físicos están configurados en pares de alta disponibilidad para tolerancia a fallos y operaciones no disruptivas. Si un nodo falla o si necesita desconectar un nodo para realizar un mantenimiento rutinario, su partner toma el control de su almacenamiento y sigue sirviendo datos desde él.

En un entorno de cloud, puede crear un par de alta disponibilidad de instancias de Cloud Volumes ONTAP para la misma tolerancia a fallos y las mismas operaciones no disruptivas que un par de alta disponibilidad en las instalaciones. Estos objetivos de recuperación están disponibles con los pares de alta disponibilidad en el cloud:

* El objetivo de punto de recuperación (RPO) es 0 segundos. Sus datos son coherentes transcionalmente sin pérdida de datos.
* El objetivo de tiempo de recuperación (RTO) es de 60 segundos. En el caso de que se produzca una interrupción del servicio, los datos deben estar disponibles en 60 segundos o menos.


Cada proveedor de cloud ofrece sus propias opciones de configuración y arquitectura de alta disponibilidad. Para Cloud Volumes Service, la alta disponibilidad está garantizada en el acuerdo de servicio.

.Información relacionada
https://docs.netapp.com/us-en/occm/concept_ha.html["Pares de alta disponibilidad en AWS"]

https://docs.netapp.com/us-en/occm/concept_ha_azure.html["Pares de alta disponibilidad en Azure"]
