---
permalink: cloud/index.html 
sidebar: sidebar 
keywords: azure netapp volumes, overview, decide, ontap, cloud, administration, on-premises 
summary: Los administradores de sistemas ONTAP en las instalaciones pueden empezar a usar “el cloud”. Las funciones de ONTAP se comparan con los productos y funciones equivalentes en el cloud. 
---
= ONTAP y la información general sobre el cloud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los administradores de sistemas ONTAP en las instalaciones pueden empezar a utilizar «'el cloud». Las funciones de ONTAP se comparan con los productos y funciones equivalentes en el cloud.

Si ya está familiarizado con ONTAP pero no está tanto con los productos basados en la nube, la siguiente información le ayuda a comprender lo que puede hacer en la nube y le señala a otros recursos para descubrir cómo:

* Cloud Volumes ONTAP
+
Un dispositivo de almacenamiento exclusivamente de software que ejecuta el software de gestión de datos ONTAP en el cloud.

* Servicios de volumen en cloud
+
Servicios de archivos nativos de cloud que proporcionan almacenamiento de archivos medido para volúmenes NAS. Se ofrecen tres opciones:

+
** Azure NetApp Files
** Amazon FSX para ONTAP
** Cloud Volumes Service para Google Cloud




.Información relacionada
Tanto si es nuevo en estos productos cloud como si ya está familiarizado con ellos, puede obtener más información en https://www.netapp.com/support-and-training/documentation/["Documentación de productos de NetApp"^].
