---
permalink: cloud/manage-ontap-concept.html 
sidebar: sidebar 
keywords: manage, ontap, cloud 
summary: 'Tanto si usa ONTAP en su propio centro de datos como en el cloud, usará las mismas interfaces para gestionar su almacenamiento. Esto significa que ya sabe cómo gestionar ONTAP en el cloud. Además, NetApp BlueXP es una interfaz gráfica moderna y fácil de usar para poner en marcha y empezar a utilizar Cloud Volumes ONTAP. Hay situaciones en las que es necesario realizar una gestión avanzada de Cloud Volumes ONTAP o Cloud Volumes Service. Para hacerlo, puede usar System Manager, la interfaz de línea de comandos (CLI) o las API DE REST.' 
---
= Gestione ONTAP en el cloud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tanto si usa ONTAP en su propio centro de datos como en el cloud, usará las mismas interfaces para gestionar su almacenamiento. Esto significa que ya sabe cómo gestionar ONTAP en el cloud. Además, NetApp BlueXP es una interfaz gráfica moderna y fácil de usar para poner en marcha y empezar a utilizar Cloud Volumes ONTAP. Hay situaciones en las que es necesario realizar una gestión avanzada de Cloud Volumes ONTAP o Cloud Volumes Service. Para hacerlo, puede usar System Manager, la interfaz de línea de comandos (CLI) o las API DE REST.

*El Administrador del sistema* se ejecuta en el sistema Cloud Volumes ONTAP o Cloud Volumes Service, lo que le permite realizar tareas de administración.

*La CLI de ONTAP* le permite ejecutar todos los comandos administrativos y es una buena opción para tareas avanzadas o si se siente más cómodo utilizando la CLI. Se conecta a la interfaz de línea de comandos mediante Secure Shell (SSH).

*Las API REST de ONTAP* le permiten crear y administrar volúmenes en la nube y desarrollar secuencias de comandos y herramientas de aprovisionamiento. Las funcionalidades ONTAP disponibles mediante la interfaz de usuario web también se encuentran disponibles mediante API DE REST. En algunas situaciones, esta interfaz programática es más útil, especialmente para los desarrolladores porque pueden automatizar procesos que implican operaciones de BlueXP.

.Información relacionada
https://["Conectando a Cloud Volumes ONTAP"]

https://["Automatización de cloud con Cloud Volumes ONTAP y REST"]

https://["API DE REST de BlueXP"]
