---
permalink: flexcache/delete-relationship-task.html 
sidebar: sidebar 
keywords: deleting, flexcache, relationship 
summary: Es posible eliminar una relación de FlexCache y el volumen de FlexCache si ya no se requiere el volumen de FlexCache. 
---
= Elimine las relaciones de ONTAP FlexCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible eliminar una relación de FlexCache y el volumen de FlexCache si ya no se requiere el volumen de FlexCache.

.Antes de empezar
Si tienes la escritura en reversión de FlexCache activada, debes desactivarla antes de poder eliminar un volumen FlexCache. Consulta link:../flexcache-writeback/flexcache-writeback-enable-task.html#disable-write-back-on-a-flexcache-volume["Deshabilite la operación de escritura en un volumen FlexCache"].

.Pasos
. Desde el clúster que tiene el volumen de FlexCache, desconecte el volumen FlexCache:
+
`volume offline -vserver svm_name -volume volume_name`

. Elimine el volumen FlexCache:
+
`volume flexcache delete -vserver svm_name -volume volume_name`

+
Los detalles de la relación de FlexCache se eliminarán del volumen de origen y del volumen de FlexCache.


