---
permalink: flexcache/supported-unsupported-features-concept.html 
sidebar: sidebar 
keywords: supported, unsupported, features, flexcache, volumes 
summary: Las funciones y los protocolos compatibles para los volúmenes de origen de FlexCache y los volúmenes FlexCache varían. 
---
= Funciones compatibles y no compatibles para volúmenes ONTAP FlexCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9,5, se pueden configurar volúmenes de FlexCache. Los volúmenes FlexVol se admiten como volúmenes de origen, y los volúmenes FlexGroup se admiten como volúmenes FlexCache. A partir de ONTAP 9,7, tanto los volúmenes FlexVol como FlexGroup se admiten como volúmenes de origen. Las funciones y los protocolos admitidos para el volumen de origen y el volumen FlexCache varían.


NOTE: Los volúmenes de caché y los volúmenes de origen pueden interoperar siempre que ambos se ejecuten en una versión compatible de ONTAP. Tenga en cuenta que las funciones solo son compatibles cuando tanto la caché como el origen se ejecutan al menos con la versión de ONTAP en la que se introdujo la compatibilidad o con una versión posterior de ONTAP.



== Compatibilidad con versiones de ONTAP entre volúmenes de FlexCache y volúmenes de origen

La versión de ONTAP recomendada compatible entre el volumen de origen y el volumen de caché no es más de cuatro versiones anteriores o cuatro versiones posteriores. Por ejemplo, si la caché utiliza ONTAP 9.14.1, la versión más antigua que puede utilizar el origen es ONTAP 9.10.1.



== Protocolos compatibles

|===


| Protocolo | ¿Admitido en el volumen de origen? | ¿Compatible con el volumen FlexCache? 


 a| 
NFSv3
 a| 
Sí
 a| 
Sí



 a| 
NFSv4
 a| 
Sí

Para acceder a los volúmenes de caché que usan el protocolo NFSv4.x, tanto los clústeres de origen como los de caché deben usar ONTAP 9.10.1 o una versión posterior. El clúster de origen y el clúster FlexCache pueden tener versiones de ONTAP diferentes, pero ambas deben ser ONTAP 9.10,1 y versiones posteriores. Por ejemplo, el origen puede tener ONTAP 9.10,1 y la caché puede tener ONTAP 9.11,1.
 a| 
Sí

Compatible a partir de ONTAP 9.10.1.

Para acceder a los volúmenes de caché que usan el protocolo NFSv4.x, tanto los clústeres de origen como los de caché deben usar ONTAP 9.10.1 o una versión posterior. El clúster de origen y el clúster FlexCache pueden tener versiones de ONTAP diferentes, pero ambas deben ser ONTAP 9.10,1 y versiones posteriores. Por ejemplo, el origen puede tener ONTAP 9.10,1 y la caché puede tener ONTAP 9.11,1.



 a| 
NFSv4.2
 a| 
Sí
 a| 
No



 a| 
SMB
 a| 
Sí
 a| 
Sí

Compatible a partir de ONTAP 9,8.

|===


== Funciones admitidas

|===


| Función | ¿Admitido en el volumen de origen? | ¿Compatible con el volumen FlexCache? 


 a| 
Protección autónoma contra ransomware
 a| 
Sí

Compatible con volúmenes de origen FlexVol que comienzan por ONTAP 9.10,1, y compatibles con volúmenes de origen FlexGroup que comienzan por ONTAP 9.13,1. Consulte link:../anti-ransomware/use-cases-restrictions-concept.html#unsupported-configurations["Casos de uso y consideraciones sobre la protección de Ransomware autónoma"].
 a| 
No



 a| 
Antivirus
 a| 
Sí

Compatible a partir de ONTAP 9,7.
 a| 
No aplicable

Si configura el análisis antivirus en el origen, no es necesario en la caché. El análisis antivirus de origen detecta archivos infectados por virus antes de que se realicen las escrituras, independientemente del origen de escritura. Para obtener más información sobre el uso de análisis antivirus con FlexCache, consulte la https://www.netapp.com/media/7336-tr4743.pdf["Informe técnico de FlexCache con ONTAP"^].



 a| 
Auditoría
 a| 
Sí

Compatible a partir de ONTAP 9,7. Puede auditar los eventos de acceso a archivos NFS en las relaciones de FlexCache mediante la auditoría nativa de ONTAP. Para obtener más información, consulte xref:audit-flexcache-volumes-concept.adoc[Consideraciones para auditar volúmenes de FlexCache]
 a| 
Sí

Compatible a partir de ONTAP 9,7. Puede auditar los eventos de acceso a archivos NFS en las relaciones de FlexCache mediante la auditoría nativa de ONTAP. Para obtener más información, consulte xref:audit-flexcache-volumes-concept.adoc[Consideraciones para auditar volúmenes de FlexCache]



 a| 
Cloud Volumes ONTAP
 a| 
Sí

Compatible a partir de ONTAP 9,6
 a| 
Sí

Compatible a partir de ONTAP 9,6



 a| 
Compactación
 a| 
Sí

Compatible a partir de ONTAP 9,6
 a| 
Sí

Compatible a partir de ONTAP 9,7



 a| 
Compresión
 a| 
Sí

Compatible a partir de ONTAP 9,6
 a| 
Sí

Compatible a partir de ONTAP 9,6



 a| 
Deduplicación
 a| 
Sí
 a| 
Sí

Los volúmenes FlexCache son compatibles con la deduplicación en línea desde ONTAP 9.6. La deduplicación entre volúmenes se admite en volúmenes FlexCache que comienzan con ONTAP 9.7.



 a| 
FabricPool
 a| 
Sí
 a| 
Sí

Compatible a partir de ONTAP 9,7


NOTE: Puede crear un volumen FlexCache como caché para un volumen de origen que tenga habilitada la organización en niveles de FabricPool , pero el volumen FlexCache en sí no puede organizarse en niveles.



 a| 
DR de FlexCache
 a| 
Sí
 a| 
Sí

Compatible desde ONTAP 9.9.1, con protocolo NFSv3, solo. Los volúmenes de FlexCache deben estar en SVM independientes o en clústeres separados.



 a| 
Volumen FlexGroup
 a| 
Sí

Compatible a partir de ONTAP 9,7
 a| 
Sí



 a| 
Volumen FlexVol
 a| 
Sí
 a| 
No



 a| 
FPolicy
 a| 
Sí

Compatible a partir de ONTAP 9,7
 a| 
Sí

Compatible con NFS desde ONTAP 9,7. Compatible con el bloque de mensajes del servidor que empieza con ONTAP 9.14.1.



 a| 
Configuración de MetroCluster
 a| 
Sí

Compatible a partir de ONTAP 9,7
 a| 
Sí

Compatible a partir de ONTAP 9,7



 a| 
Transferencia de datos descargados (ODX) de Microsoft
 a| 
Sí
 a| 
No



 a| 
Cifrado de agregados de NetApp (NAE)
 a| 
Sí

Compatible a partir de ONTAP 9,6
 a| 
Sí

Compatible a partir de ONTAP 9,6



 a| 
Cifrado de volúmenes de NetApp (NVE)
 a| 
Sí

Compatible a partir de ONTAP 9,6
 a| 
Sí

Compatible a partir de ONTAP 9,6



 a| 
Bloque NAS de ONTAP S3
 a| 
Sí

Compatible a partir de ONTAP 9.12.1
 a| 
No



 a| 
Calidad de servicio
 a| 
Sí
 a| 
Sí


NOTE: La calidad de servicio en el nivel de archivo no se admite para los volúmenes FlexCache.



 a| 
Qtrees
 a| 
Sí

A partir de ONTAP 9,6, se pueden crear y modificar qtrees. Los qtrees creados en el origen pueden accederse en la caché.
 a| 
No



 a| 
Cuotas
 a| 
Sí

A partir de ONTAP 9,6, la aplicación de cuotas de los volúmenes de origen FlexCache se admite para usuarios, grupos y qtrees.
 a| 
No

En el modo de escritura FlexCache (el modo predeterminado), las escrituras en la caché se reenvían al volumen de origen. Las cuotas se aplican en el origen.


NOTE: A partir de ONTAP 9.6, se admite la cuota remota (rquota) en los volúmenes FlexCache.



 a| 
Notificación de cambio de SMB
 a| 
Sí
 a| 
Sí

A partir de ONTAP 9.14.1, Notificar cambios de SMB es compatible en la caché.



 a| 
Volúmenes de SnapLock
 a| 
No
 a| 
No



 a| 
Relaciones asincrónicas de SnapMirror*
 a| 
Sí
 a| 
No



 a| 
 a| 
*Orígenes de FlexCache:

* Es posible tener un volumen de FlexCache a partir de un FlexVol de origen
* Es posible tener un volumen de FlexCache a partir de un FlexGroup de origen
* Puede tener un volumen de FlexCache desde un volumen primario de origen en una relación de SnapMirror.
* A partir de ONTAP 9.8, un volumen secundario de SnapMirror puede ser un volumen de origen de FlexCache. El volumen secundario de SnapMirror debe estar inactivo sin actualizaciones activas de SnapMirror; de lo contrario, se producirá un error en la creación de FlexCache.




 a| 
Relaciones síncronas de SnapMirror
 a| 
No
 a| 
No



 a| 
SnapRestore
 a| 
Sí
 a| 
No



 a| 
Snapshot
 a| 
Sí
 a| 
No



 a| 
Configuración de recuperación ante desastres de SVM
 a| 
Sí

Compatible a partir de ONTAP 9.5. El SVM principal de una relación SVM DR puede tener el volumen de origen; sin embargo, si está ejecutando una versión de ONTAP anterior a ONTAP 9.18.1, cuando se interrumpe la relación SVM DR, la relación FlexCache se debe volver a crear con un nuevo volumen de origen.

A partir de ONTAP 9.18.1, cuando una SVM de origen conmuta por error, los cachés cambian automáticamente al origen en el sitio de recuperación ante desastres. Se eliminan los pasos de recuperación manual.

xref:create-volume-task.adoc[Obtenga información sobre cómo crear volúmenes FlexCache .]
 a| 
No

Puede tener volúmenes FlexCache en SVM primarias, pero no en SVM secundarias. Cualquier volumen FlexCache de la SVM principal no se replica como parte de la relación de recuperación ante desastres de SVM.



 a| 
Protección de acceso a nivel de almacenamiento (SLAG)
 a| 
No
 a| 
No



 a| 
Aprovisionamiento ligero
 a| 
Sí
 a| 
Sí

Compatible a partir de ONTAP 9,7



 a| 
Clonado de volúmenes
 a| 
Sí

Se admite la clonado de un volumen de origen y de los archivos en el volumen de origen a partir de ONTAP 9.6.
 a| 
No



 a| 
Movimiento de volúmenes
 a| 
Sí
 a| 
Sí (solo para componentes de volumen)

ONTAP 9,6 y versiones posteriores admiten el movimiento de constituyentes de volúmenes de un volumen FlexCache.



 a| 
Realojamiento de volúmenes
 a| 
No
 a| 
No



 a| 
API de vStorage para integración de cabinas (VAAI)
 a| 
Sí
 a| 
No

|===

NOTE: En las versiones de ONTAP 9 anteriores a la 9.5, los volúmenes FlexVol de origen solo pueden proporcionar datos a volúmenes FlexCache creados en sistemas que ejecutan Data ONTAP 8.2.x en 7-Mode. A partir de ONTAP 9.5, los volúmenes FlexVol de origen también pueden proporcionar datos a FlexCache Volumes en sistemas ONTAP 9. Para obtener más información sobre la migración de FlexCache de 7-Mode a ONTAP 9 FlexCache, consulte link:https://www.netapp.com/pdf.html?item=/media/7336-tr4743pdf.pdf["Informe técnico de NetApp 4743: FlexCache en ONTAP"^].
