---
permalink: flexcache/supported-unsupported-features-concept.html 
sidebar: sidebar 
keywords: supported, unsupported, features, flexcache, volumes 
summary: Debe conocer las funciones compatibles con los volúmenes de FlexCache y sus volúmenes de origen. 
---
= Funciones compatibles y no compatibles para volúmenes de FlexCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe conocer las funciones compatibles con los volúmenes de FlexCache y sus volúmenes de origen.

|===


| Función | ¿Admitido en el volumen de origen? | ¿Compatible con el volumen FlexCache? 


 a| 
Protección autónoma contra ransomware
 a| 
Sí

Para los volúmenes de origen de FlexVol que comienzan con ONTAP 9.10.1, no se admiten los volúmenes de origen de FlexGroup.
 a| 
No



 a| 
Antivirus
 a| 
Sí

Compatible a partir de ONTAP 9.7
 a| 
No aplicable



 a| 
Auditoría
 a| 
Sí

Compatible a partir de ONTAP 9,7.
Puede auditar los eventos de acceso a archivos NFS en las relaciones de FlexCache mediante la auditoría nativa de ONTAP.
Para obtener más información, consulte xref:audit-flexcache-volumes-concept.adoc[Consideraciones para auditar volúmenes de FlexCache]
 a| 
Sí

Compatible a partir de ONTAP 9,7.
Puede auditar los eventos de acceso a archivos NFS en las relaciones de FlexCache mediante la auditoría nativa de ONTAP.
Para obtener más información, consulte xref:audit-flexcache-volumes-concept.adoc[Consideraciones para auditar volúmenes de FlexCache]



 a| 
Cloud Volumes ONTAP
 a| 
Sí

Compatible a partir de ONTAP 9,6
 a| 
Sí

Compatible a partir de ONTAP 9,6



 a| 
Compactación
 a| 
Sí

Compatible a partir de ONTAP 9,6
 a| 
Sí

Compatible a partir de ONTAP 9.7



 a| 
Compresión
 a| 
Sí

Compatible a partir de ONTAP 9,6
 a| 
Sí

Compatible a partir de ONTAP 9,6



 a| 
Deduplicación
 a| 
Sí
 a| 
Sí

Los volúmenes FlexCache son compatibles con la deduplicación en línea desde ONTAP 9.6. La deduplicación entre volúmenes se admite en volúmenes FlexCache que comienzan con ONTAP 9.7.



 a| 
FabricPool
 a| 
Sí
 a| 
Sí

Compatible a partir de ONTAP 9.7



 a| 
DR de FlexCache
 a| 
Sí
 a| 
Sí

Compatible desde ONTAP 9.9.1, con protocolo NFSv3, solo. Los volúmenes de FlexCache deben estar en SVM independientes o en clústeres separados.



 a| 
Volumen FlexGroup
 a| 
Sí

Compatible a partir de ONTAP 9.7
 a| 
Sí



 a| 
Volumen FlexVol
 a| 
Sí
 a| 
No



 a| 
FPolicy
 a| 
Sí

Compatible a partir de ONTAP 9.7
 a| 
Sí

Compatible con NFS desde ONTAP 9,7.
Compatible con el bloque de mensajes del servidor que empieza con ONTAP 9.14.1.



 a| 
Configuración de MetroCluster
 a| 
Sí

Compatible a partir de ONTAP 9.7
 a| 
Sí

Compatible a partir de ONTAP 9.7



 a| 
Transferencia de datos descargados (ODX) de Microsoft
 a| 
Sí
 a| 
No



 a| 
Cifrado de agregados de NetApp (NAE)
 a| 
Sí

Compatible a partir de ONTAP 9,6
 a| 
Sí

Compatible a partir de ONTAP 9,6



 a| 
Cifrado de volúmenes de NetApp (NVE)
 a| 
Sí

Compatible a partir de ONTAP 9,6
 a| 
Sí

Compatible a partir de ONTAP 9,6



 a| 
NFSv3
 a| 
Sí
 a| 
Sí



 a| 
NFSv4
 a| 
Sí

Para acceder a los volúmenes de caché que usan el protocolo NFSv4.x, tanto los clústeres de origen como los de caché deben usar ONTAP 9.10.1 o una versión posterior. El clúster de origen y el clúster FlexCache pueden tener versiones de ONTAP diferentes, pero ambas deben ser ONTAP 9.10.1 y versiones posteriores. Por ejemplo, el origen puede tener ONTAP 9.10.1 y la caché puede tener ONTAP 9.11.1.
 a| 
Sí

Compatible a partir de ONTAP 9.10.1.

Para acceder a los volúmenes de caché que usan el protocolo NFSv4.x, tanto los clústeres de origen como los de caché deben usar ONTAP 9.10.1 o una versión posterior. El clúster de origen y el clúster FlexCache pueden tener versiones de ONTAP diferentes, pero ambas deben ser ONTAP 9.10.1 y versiones posteriores. Por ejemplo, el origen puede tener ONTAP 9.10.1 y la caché puede tener ONTAP 9.11.1.



 a| 
NFSv4,2
 a| 
Sí
 a| 
No



 a| 
ONTAP S3
 a| 
Sí
 a| 
No



 a| 
Calidad de servicio
 a| 
Sí
 a| 
Sí


NOTE: La calidad de servicio en el nivel de archivo no se admite para los volúmenes FlexCache.



 a| 
Qtrees
 a| 
Sí. A partir de ONTAP 9,6, se pueden crear y modificar qtrees. Los qtrees creados en el origen pueden accederse en la caché.
 a| 
No



 a| 
Cuotas
 a| 
Sí. A partir de ONTAP 9,6, la aplicación de cuotas de los volúmenes de origen FlexCache se admite para usuarios y grupos.
 a| 
No En el modo de escritura FlexCache (el modo predeterminado), las escrituras en la caché se reenvían al volumen de origen. Las cuotas se aplican en el origen.


NOTE: A partir de ONTAP 9.6, se admite la cuota remota (rquota) en los volúmenes FlexCache.



 a| 
SMB
 a| 
Sí
 a| 
Sí

Compatible a partir de ONTAP 9.8.



 a| 
Notificación de cambio de SMB
 a| 
Sí
 a| 
No



 a| 
Volúmenes de SnapLock
 a| 
No
 a| 
No



 a| 
Relaciones asíncronas de SnapMirror*
 a| 
Sí
 a| 
No



 a| 
 a| 
*Orígenes de FlexCache:

* Es posible tener un volumen de FlexCache a partir de un FlexVol de origen
* Es posible tener un volumen de FlexCache a partir de un FlexGroup de origen
* Puede tener un volumen de FlexCache desde un volumen primario de origen en una relación de SnapMirror.
* A partir de ONTAP 9.8, un volumen secundario de SnapMirror puede ser un volumen de origen de FlexCache.




 a| 
Relaciones de SnapMirror Synchronous
 a| 
No
 a| 
No



 a| 
SnapRestore
 a| 
Sí
 a| 
No



 a| 
Copias Snapshot
 a| 
Sí
 a| 
No



 a| 
Configuración de recuperación ante desastres de SVM
 a| 
Sí

Con compatibilidad a partir con ONTAP 9.5. La SVM principal de una relación de recuperación ante desastres de SVM puede tener el volumen de origen; no obstante, si la relación de recuperación ante desastres de SVM está rota, debe volver a crearse la relación de FlexCache con un nuevo volumen de origen.
 a| 
No

Puede tener volúmenes FlexCache en SVM primarias, pero no en SVM secundarias. Cualquier volumen FlexCache de la SVM principal no se replica como parte de la relación de recuperación ante desastres de SVM.



 a| 
Protección de acceso a nivel de almacenamiento (ESCORIA)
 a| 
No
 a| 
No



 a| 
Aprovisionamiento ligero
 a| 
Sí
 a| 
Sí

Compatible a partir de ONTAP 9.7



 a| 
Clonado de volúmenes
 a| 
Sí

Se admite la clonado de un volumen de origen y de los archivos en el volumen de origen a partir de ONTAP 9.6.
 a| 
No



 a| 
Movimiento de volúmenes
 a| 
Sí
 a| 
Sí (solo para componentes de volumen)

ONTAP 9.6 admite la transferencia de componentes de volumen de un volumen FlexCache en adelante.



 a| 
Realojamiento de volúmenes
 a| 
No
 a| 
No



 a| 
API de vStorage para integración de cabinas (VAAI)
 a| 
Sí
 a| 
No

|===