---
permalink: flexcache/synchronize-properties-origin-volume-task.html 
sidebar: sidebar 
keywords: synchronizing, properties, flexcache, volume, origin 
summary: Algunas de las propiedades de volumen del volumen FlexCache siempre deben sincronizarse con las del volumen de origen. Si las propiedades de volumen de un volumen FlexCache no pueden sincronizarse automáticamente después de que se modifican las propiedades del volumen de origen, se pueden sincronizar manualmente las propiedades. 
---
= Sincronice las propiedades de un volumen ONTAP FlexCache desde un volumen de origen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Algunas de las propiedades de volumen del volumen FlexCache siempre deben sincronizarse con las del volumen de origen. Si las propiedades de volumen de un volumen FlexCache no pueden sincronizarse automáticamente después de que se modifican las propiedades del volumen de origen, se pueden sincronizar manualmente las propiedades.

.Acerca de esta tarea
Las siguientes propiedades de volumen de un volumen FlexCache siempre deben sincronizarse con las del volumen de origen:

* Estilo de seguridad (`-security-style`)
* Nombre del volumen (`-volume-name`)
* Tamaño máximo de directorio (`-maxdir-size`)
* Lectura mínima anticipada (`-min-readahead`)


.Paso
. En el volumen FlexCache, sincronice las propiedades del volumen:
+
`volume flexcache sync-properties -vserver svm_name -volume flexcache_volume`

+
[listing]
----
cluster1::> volume flexcache sync-properties -vserver vs1 -volume fc1
----

