---
permalink: volumes/assign-volume-efficiency-policy-task.html 
sidebar: sidebar 
keywords: assign, volume efficiency policy, volume 
summary: Puede asignar una política de eficiencia a un volumen para ejecutar una operación de deduplicación o compresión de datos mediante el comando volume Efficiency modify. 
---
= Asignar una política de eficiencia de volumen a un volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede asignar una política de eficiencia a un volumen para ejecutar operaciones de deduplicación o compresión de datos mediante la `volume efficiency modify` comando.

.Antes de empezar
Asegúrese de que usted link:create-efficiency-policy-task.html["cree la política de eficiencia del volumen"] antes de asignarlo a un volumen.

.Acerca de esta tarea
Si se asigna una política de eficiencia a un volumen secundario SnapVault, solo se tiene en cuenta el atributo de prioridad de eficiencia del volumen al ejecutar operaciones de eficiencia del volumen. Las programaciones de tareas se ignoran y la operación de deduplicación se ejecuta cuando se realizan actualizaciones incrementales en el volumen secundario de SnapVault.

.Paso
. Utilice la `volume efficiency modify` comando para asignar una política a un volumen.


.Ejemplo
El siguiente comando asigna la política de eficiencia del volumen llamada `new_policy` al volumen `VolA`:

`volume efficiency modify -vserver vs1 -volume VolA -policy new_policy`
