---
permalink: volumes/autoshrink-snapshot-copy-deletion-concept.html 
sidebar: sidebar 
keywords: how, autoshrink functionality, interacts with, snapshot copy, deletion 
summary: Dado que la funcionalidad de reducción automática reduce el tamaño de un volumen FlexVol, también puede afectar al eliminación automática de las copias snapshot para volúmenes. 
---
= Cómo interactúa la funcionalidad de autorreducción con la eliminación de copias snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dado que la funcionalidad de reducción automática reduce el tamaño de un volumen FlexVol, también puede afectar al eliminación automática de las copias snapshot para volúmenes.

La funcionalidad de autorreducción interactúa con la eliminación automática de copias Snapshot de volumen de las siguientes maneras:

* Si ambos `grow_shrink` El modo autosize y la eliminación automática de copias snapshot se habilitan cuando el tamaño de un volumen reduce, puede activar la eliminación automática de copias snapshot.
+
Esto es así porque la reserva de Snapshot se basa en un porcentaje del tamaño del volumen (5 % de forma predeterminada), y ese porcentaje ahora se basa en un tamaño de volumen más pequeño. Esto puede provocar que las copias Snapshot se salgan de la reserva y se eliminen automáticamente.

* Si la `grow_shrink` El modo autosize está habilitado y puede eliminar manualmente una copia snapshot; puede que se active una reducción de volumen automática.

