---
permalink: volumes/change-efficiency-mode-task.html 
sidebar: sidebar 
keywords: storage, efficiency, mode, change, efficient, default, volume 
summary: 'Puede cambiar el modo de eficiencia del almacenamiento de un volumen de AFF `default` de a `efficient`, o bien establecer un modo de eficiencia cuando la eficiencia del volumen ya no está configurada.' 
---
= Cambiar el modo de eficiencia del volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.10,1, los modos de eficiencia de almacenamiento en el nivel de volumen _default_ y _efficient_ solo son compatibles con sistemas AFF. Estos modos proporcionan una opción entre compresión de archivo (predeterminado), que es el modo predeterminado cuando se crean nuevos volúmenes AFF, o la eficiencia del almacenamiento sensible a la temperatura (eficiente), que permite una eficiencia del almacenamiento sensible a la temperatura. Puede usar el `volume efficiency modify` comando para cambiar el modo de eficiencia de almacenamiento de un volumen de AFF de `default` a `efficient`, o bien se puede establecer un modo de eficiencia cuando la eficiencia del volumen aún no esté configurada.

.Pasos
. Cambie el modo de eficiencia de volumen:
+
[listing]
----
volume efficiency modify -vserver <vserver name> -volume <volume name> -storage-efficiency-mode <default|efficient>
----


Obtenga más información sobre `volume efficiency modify` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["Referencia de comandos de la ONTAP"^].
