---
permalink: volumes/change-inactive-data-threshold-task.html 
sidebar: sidebar 
keywords: storage, efficiency, temperature, change, efficient, default, threshold, inactive, compression, cold data, frequency 
summary: Puede cambiar la frecuencia con la que ONTAP realiza un análisis de datos fríos modificando el umbral de frío en los volúmenes mediante la eficiencia del almacenamiento sensible a la temperatura. 
---
= Cambie el umbral de compresión de datos inactivos del volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede cambiar la frecuencia con la que ONTAP realiza un análisis de datos fríos modificando el umbral de frío en los volúmenes mediante la eficiencia del almacenamiento sensible a la temperatura.

.Antes de empezar
Debe ser administrador de clústeres o de SVM y utilizar el nivel de privilegios avanzado de interfaz de línea de comandos de ONTAP.

.Acerca de esta tarea
El umbral de frialdad puede ser de 1 a 60 días. El umbral predeterminado es de 14 días.

.Pasos
. Establezca el nivel de privilegio:
+
`set -privilege advanced`

. Modificar la compresión de datos inactivos en un volumen:
+
`volume efficiency inactive-data-compression modify -vserver <vserver_name> -volume <volume_name> -threshold-days <integer>`



Consulte la página de manual para obtener información adicional acerca de link:https://docs.netapp.com/us-en/ontap-cli-9141/volume-efficiency-inactive-data-compression-modify.html#description["modificar la compresión de datos inactivos"].
