---
permalink: volumes/change-efficiency-mode-task.html 
sidebar: sidebar 
keywords: storage, efficiency, mode, change, efficient, default 
summary: 'Puede utilizar el `volume efficiency modify` Comando para cambiar el modo de eficiencia del almacenamiento definido en un volumen AFF. Puede cambiar el modo desde `default` para `efficient` también puede establecer un modo de eficiencia cuando todavía no esté configurada la eficiencia del volumen.' 
---
= Cambiar el modo de eficiencia del volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.10.1, se introducen dos modos de eficiencia de almacenamiento a nivel de volumen solo para sistemas AFF, _default_ y _efficient_. Los dos modos proporcionan una opción entre compresión de archivo (predeterminado), que es el modo predeterminado cuando se crean nuevos volúmenes AFF, o la eficiencia del almacenamiento sensible a la temperatura (eficiente), que permite una eficiencia del almacenamiento sensible a la temperatura. Puede utilizar el `volume efficiency modify` Comando para cambiar el modo de eficiencia del almacenamiento definido en un volumen AFF. Puede cambiar el modo desde `default` para `efficient` también puede establecer un modo de eficiencia cuando todavía no esté configurada la eficiencia del volumen.

.Pasos
. Cambie el modo de eficiencia de volumen:
+
`volume efficiency modify -vserver <vserver name> -volume <volume name> -storage-efficiency-mode <default|efficient>`


