---
permalink: volumes/change-maximum-number-files-allowed-concept.html 
sidebar: sidebar 
keywords: considerations, changing, maximum number of files, allowed, flexvol volume, maximum, files, file 
summary: Los volúmenes FlexVol tienen un número máximo de archivos que pueden contener. Puede cambiar este máximo, pero tenga en cuenta cómo afecta esto al volumen. 
---
= La cantidad máxima de archivos permitidos para volúmenes FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los volúmenes FlexVol tienen un número máximo de archivos que pueden contener. Es posible cambiar este máximo, pero antes de hacerlo, debe comprender cómo este cambio afecta al volumen.

Si los datos requieren un gran número de archivos o directorios muy grandes, puede ampliar la capacidad de archivos o directorios de ONTAP. Sin embargo, debe comprender las limitaciones y advertencias a la hora de hacerlo antes de continuar.

El número de archivos que puede contener un volumen está determinado por la cantidad de inodos que tiene. Un _inode_ es una estructura de datos que contiene información acerca de los archivos. Los volúmenes tienen inodos tanto privados como públicos. Los inodos públicos se utilizan para archivos visibles para el usuario; los inodos privados se utilizan para archivos que ONTAP utiliza internamente. Solo se puede cambiar el número máximo de inodos públicos de un volumen. No puede afectar el número de inodos privados.

ONTAP establece automáticamente el número máximo de inodos públicos de un volumen recién creado en función del tamaño del volumen: 1 inodo por 32 KB de tamaño del volumen. Cuando aumenta el tamaño de un volumen, ya sea directamente por un administrador o de forma automática por medio de ONTAP mediante la función de dimensionamiento automático, ONTAP también aumenta (si es necesario) el número máximo de inodos públicos, de modo que hay al menos 1 inodo por cada 32 KB de tamaño de volumen, Hasta que el volumen alcance aproximadamente 680 GB.

En versiones de ONTAP anteriores a 9.13.1, aumentar el volumen a más de 680 GB no da como resultado automáticamente más inodos, ya que ONTAP no crea automáticamente más de 22.369.621 inodos. Si necesita más archivos que el número predeterminado para cualquier volumen de tamaño, puede usar el comando volume modify para aumentar la cantidad máxima de inodos del volumen.

A partir de ONTAP 9.13.1, el número máximo de inodos sigue creciendo de modo que hay un inodo por 32 KB de espacio de volumen incluso si el volumen es mayor que 680 GB. Este crecimiento continúa hasta que el volumen alcanza el inode máximo de 2.147.483.632.

También puede disminuir el número máximo de inodos públicos. Al disminuir el número de inodos públicos, _not_ cambia la cantidad de espacio asignado a inodes, pero reduce la cantidad máxima de espacio que puede consumir el archivo de inode público. Una vez asignado espacio para inodos, el volumen no volverá nunca a devolverlo. Por lo tanto, la reducción del número máximo de inodos por debajo del número de inodos asignados actualmente no devuelve el espacio utilizado por los inodos asignados.

.Más información
* xref:display-file-inode-usage-task.html[Determine el uso de archivos e inodo para un volumen]

