---
permalink: volumes/checkpoints-resume-efficiency-operation-concept.html 
sidebar: sidebar 
keywords: efficiency operation checkpoints, use, resume, efficiency, operation, checkpoint 
summary: Los puntos de control se utilizan internamente para registrar el proceso de una operación de eficiencia. Cuando se detiene una operación de eficiencia por cualquier motivo y existen datos de punto de control, la operación de eficiencia puede reanudarse desde el último archivo de punto de control. 
---
= Puntos de control y operaciones de eficiencia
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los puntos de control se utilizan internamente para registrar el proceso de ejecución de una operación de eficiencia. Cuando una operación de eficiencia se detiene por cualquier motivo (como la detención del sistema, la interrupción del sistema, el reinicio o porque se detuvo o falló la última operación de eficiencia) y existen datos de punto de comprobación, la operación de eficiencia puede reanudarse desde el archivo de punto de comprobación más reciente.

Se ha creado un punto de comprobación:

* en cada etapa o subetapa de la operación
* cuando ejecute el `sis stop` comando
* cuando caduque la duración


Obtenga más información sobre los comandos descritos en este procedimiento en el link:https://docs.netapp.com/us-en/ontap-cli/["Referencia de comandos de la ONTAP"^].
