---
permalink: volumes/commands-manage-qtrees-reference.html 
sidebar: sidebar 
keywords: commands for, managing, configuring, qtrees, manage, command, configure 
summary: Puede gestionar y configurar qtrees mediante comandos ONTAP específicos. 
---
= Comandos para gestionar y configurar qtrees
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede gestionar y configurar qtrees mediante comandos ONTAP específicos. En función de lo que tenga que hacer, puede utilizar los siguientes comandos para gestionar y configurar qtrees:

|===


| Si desea... | Se usa este comando... 


 a| 
Cree un qtree
 a| 
`volume qtree create`



 a| 
Mostrar una lista filtrada de qtrees
 a| 
`volume qtree show`



 a| 
Eliminar un qtree
 a| 
`volume qtree delete`


NOTE: El comando Qtree `volume qtree delete` fallará a menos que el qtree esté vacío o el `-force true` se agrega el indicador.



 a| 
Modificar los permisos UNIX de un qtree
 a| 
`volume qtree modify -unix-permissions`



 a| 
Modifique la configuración de los bloqueos oportunistas CIFS de un qtree
 a| 
`volume qtree oplocks`



 a| 
Modificar la configuración de seguridad de un qtree
 a| 
`volume qtree security`



 a| 
Cambie el nombre a un qtree
 a| 
`volume qtree rename`



 a| 
Mostrar las estadísticas de un qtree
 a| 
`volume qtree statistics`



 a| 
Restablecer las estadísticas de un qtree
 a| 
`volume qtree statistics -reset`

|===
[NOTE]
====
La `volume rehost` el comando puede provocar errores en otras operaciones administrativas simultáneas dirigidas a ese volumen.

====