---
permalink: volumes/commands-manage-quota-rules-policies-reference.html 
sidebar: sidebar 
keywords: commands to, manage, quota rules, quota policies 
summary: Se pueden utilizar los comandos de regla de política de cuota de volumen para configurar las reglas de cuota y utilizar los comandos de directiva de cuota de volumen y algunos comandos Vserver para configurar las políticas de cuota. 
---
= Comandos para gestionar reglas de cuota y directivas de cuota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `volume quota policy rule` comandos para configurar las reglas de cuota y utilizar `volume quota policy` comandos y algunos `vserver` comandos para configurar las directivas de cuota.


NOTE: Los siguientes comandos solo se pueden ejecutar en volúmenes de FlexVol.



== Comandos para administrar reglas de cuota

[cols="2*"]
|===
| Si desea... | Se usa este comando... 


 a| 
Cree una nueva regla de cuota
 a| 
`volume quota policy rule create`



 a| 
Eliminar una regla de cuota existente
 a| 
`volume quota policy rule delete`



 a| 
Modifique una regla de cuota existente
 a| 
`volume quota policy rule modify`



 a| 
Muestra información acerca de las reglas de cuota configuradas
 a| 
`volume quota policy rule show`

|===


== Comandos para gestionar políticas de cuotas

[cols="2*"]
|===
| Si desea... | Se usa este comando... 


 a| 
Duplique una política de cuota y las reglas de cuota que contiene
 a| 
`volume quota policy copy`



 a| 
Cree una nueva política de cuota en blanco
 a| 
`volume quota policy create`



 a| 
Eliminar una política de cuotas existente que no está asignada actualmente a una máquina virtual de almacenamiento (SVM)
 a| 
`volume quota policy delete`



 a| 
Cambiar el nombre de una política de cuota
 a| 
`volume quota policy rename`



 a| 
Mostrar información sobre las políticas de cuota
 a| 
`volume quota policy show`



 a| 
Asigne una política de cuotas a una SVM
 a| 
`vserver modify -quota-policy _policy_name_`



 a| 
Muestre el nombre de la política de cuotas asignada a una SVM
 a| 
`vserver show`

|===
Consulte link:https://docs.netapp.com/us-en/ontap-cli-9121["Referencia de comandos de la ONTAP"^] para cada comando para obtener más información.
