---
permalink: volumes/commands-manage-flexvol-volumes-reference.html 
sidebar: sidebar 
keywords: commands for, managing, flexvol, volumes, manage 
summary: Hay comandos específicos para gestionar los volúmenes de FlexVol mediante la interfaz de línea de comandos de ONTAP. 
---
= Comandos para gestionar volúmenes de FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay comandos específicos para gestionar los volúmenes de FlexVol mediante la interfaz de línea de comandos de ONTAP.

[cols="2*"]
|===
| Si desea... | Se usa este comando... 


 a| 
Coloque un volumen en línea
 a| 
`volume online`



 a| 
Cambiar el tamaño de un volumen
 a| 
`volume size`



 a| 
Determine el agregado asociado de un volumen
 a| 
`volume show`



 a| 
Determinar el agregado asociado para todos los volúmenes en una máquina virtual de almacenamiento (SVM)
 a| 
`volume show -vserver -fields aggregate`



 a| 
Determine el formato de un volumen
 a| 
`volume show -fields block-type`



 a| 
Monte un volumen en otro volumen mediante una unión
 a| 
`volume mount`



 a| 
Ponga un volumen en estado restringido
 a| 
`volume restrict`



 a| 
Cambiar el nombre de un volumen
 a| 
`volume rename`



 a| 
Desconectar un volumen
 a| 
`volume offline`

|===
Consulte la página de manual de cada comando para obtener más información.
