---
permalink: volumes/configure-automatic-grow-shrink-size-task.html 
sidebar: sidebar 
keywords: configure, volumes, automatically, grow, shrink, size 
summary: Puede configurar volúmenes FlexVol para que crezcan y reduzcan automáticamente en función del espacio que necesite actualmente. El crecimiento automático ayuda a evitar que un volumen se quede sin espacio si el agregado puede suministrar más espacio. La reducción automática evita que un volumen sea mayor de lo necesario y libera espacio en el agregado para que lo usen otros volúmenes. 
---
= Configure los volúmenes para que aumenten y reduzcan su tamaño automáticamente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar volúmenes FlexVol para que crezcan y reduzcan automáticamente en función del espacio que necesite actualmente. El crecimiento automático ayuda a evitar que un volumen se quede sin espacio si el agregado puede suministrar más espacio. La reducción automática evita que un volumen sea mayor de lo necesario y libera espacio en el agregado para que lo usen otros volúmenes.

.Lo que necesitará
El volumen FlexVol debe estar en línea.

.Acerca de esta tarea
La autoreducción sólo se puede utilizar en combinación con el crecimiento automático para satisfacer las cambiantes demandas de espacio y no está disponible solo. Cuando se habilita la función de reducción automática, ONTAP gestiona automáticamente el comportamiento de reducción de un volumen para evitar un bucle interminable de acciones de autocrecimiento y autoreducción.

A medida que crece un volumen, es posible que el número máximo de archivos que puede contener se aumente automáticamente. Cuando un volumen se reduce, el número máximo de archivos que puede contener no cambia y un volumen no se puede reducir automáticamente por debajo del tamaño correspondiente a su número máximo actual de archivos. Por este motivo, es posible que no sea posible reducir de forma automática un volumen hasta su tamaño original.

De forma predeterminada, el tamaño máximo que puede crecer un volumen es del 120 % del tamaño en el cual se habilita el crecimiento automático. Si es necesario asegurarse de que el volumen pueda crecer para ser mayor que dicho, debe configurar el tamaño máximo para el volumen según corresponda.

.Paso
. Configure el volumen para que crezca y reduzca su tamaño automáticamente:
+
`volume autosize -vserver vserver_namevol_name -mode grow_shrink`

+
El siguiente comando habilita los cambios de tamaño automáticos para un volumen denominado test2. El volumen se configura para comenzar a reducir cuando está lleno al 60 %. Los valores predeterminados se utilizan para cuándo comenzará a crecer y su tamaño máximo.

+
[listing]
----
cluster1::> volume autosize -vserver vs2 test2 -shrink-threshold-percent 60
vol autosize: Flexible volume "vs2:test2" autosize settings UPDATED.

Volume modify successful on volume: test2
----

