---
permalink: volumes/configure-flexvol-delete-flexclone-files-luns-task.html 
sidebar: sidebar 
keywords: configure, flexvol volume, automatically, delete, flexclone files, flexclone luns, flexvol, volume, automatic, file, autodelete 
summary: Puede habilitar una FlexVol volume para eliminar automáticamente los archivos FlexClone y LUN de FlexClone cuando el espacio libre del volumen disminuya por debajo de un umbral concreto. 
---
= Configurar un volumen FlexVol para que elimine automáticamente archivos FlexClone y LUN FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar un volumen para que comience a eliminar automáticamente archivos FlexClone y LUN FlexClone cuando el espacio libre en el volumen disminuya por debajo de un valor de umbral determinado y deje de eliminar automáticamente clones cuando se reclame una cantidad de espacio libre objetivo en el volumen. Aunque, no puede especificar el valor de umbral que inicia la eliminación automática de clones, puede especificar si un clon es apto para su eliminación y puede especificar la cantidad de espacio libre objetivo para un volumen.

Un volumen elimina automáticamente los archivos FlexClone y las LUN FlexClone cuando el espacio libre en el volumen disminuye por debajo de un umbral determinado y cuando se cumplen los siguientes requisitos:

* La función de eliminación automática está habilitada para el volumen que contiene los archivos FlexClone y las LUN FlexClone.
+
Puede habilitar la funcionalidad de eliminación automática para una FlexVol volume mediante `volume snapshot autodelete modify` el comando. Debe establecer `-trigger` el parámetro en `volume` o `snap_reserve` para que un volumen elimine automáticamente los archivos FlexClone y LUN de FlexClone.

* La función de eliminación automática está activada para los archivos de FlexClone y las LUN de FlexClone.
+
Puede habilitar la eliminación automática para un archivo de FlexClone o LUN de FlexClone mediante `file clone create` el comando con `-autodelete` el parámetro. Como resultado, puede conservar algunos archivos FlexClone y LUN FlexClone deshabilitando la eliminación automática de los clones y asegurándose de que otras opciones de configuración del volumen no anulen la configuración del clon.



.Antes de empezar
* El volumen FlexVol debe contener archivos FlexClone y LUN FlexClone, y estar en línea.
* El volumen FlexVol no debe ser un volumen de solo lectura.


.Pasos
. Habilite la eliminación automática de archivos FlexClone y LUN de FlexClone en la FlexVol volume mediante `volume snapshot autodelete modify` el comando. Obtenga más información sobre `volume snapshot autodelete modify` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-autodelete-modify.html["Referencia de comandos del ONTAP"^].
+
** Para el `-trigger` parámetro, puede especificar `volume` o `snap_reserve`.
** Para el `-destroy-list` parámetro, siempre debe especificar `lun_clone,file_clone` independientemente de si quiere eliminar solo un tipo de clon. El siguiente ejemplo muestra cómo puede habilitar volume vol1 para activar la eliminación automática de archivos FlexClone y LUN de FlexClone para la reclamación de espacio hasta que el 25% del volumen esté compuesto por espacio libre:
+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs1 -volume vol1 -enabled true -commitment disrupt -trigger volume -target-free-space 25 -destroy-list lun_clone,file_clone

Volume modify successful on volume:vol1
----
+
[NOTE]
====
Al habilitar la eliminación automática de los volúmenes de FlexVol, si se establece el valor del `-commitment` parámetro en `destroy`, todos los archivos de FlexClone y LUN de FlexClone con `-autodelete` el parámetro establecido en `true` Se pueden eliminar cuando el espacio libre del volumen disminuye por debajo del valor de umbral especificado. Sin embargo, los archivos FlexClone y las LUN de FlexClone con el `-autodelete` parámetro establecido en `false` no se eliminarán.

====


. Compruebe que la eliminación automática de los archivos FlexClone y LUN de FlexClone está habilitada en FlexVol volume mediante `volume snapshot autodelete show` el comando. Obtenga más información sobre `volume snapshot autodelete show` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-autodelete-show.html["Referencia de comandos del ONTAP"^].
+
El siguiente ejemplo muestra que el volumen vol1 está activado para la eliminación automática de archivos FlexClone y LUN FlexClone:

+
[listing]
----
cluster1::> volume snapshot autodelete show -vserver vs1 -volume vol1

         Vserver Name: vs1
          Volume Name: vol1
          Enabled: true
           Commitment: disrupt
         Defer Delete: user_created
         Delete Order: oldest_first
  Defer Delete Prefix: (not specified)
    Target Free Space: 25%
              Trigger: volume
     *Destroy List: lun_clone,file_clone*
Is Constituent Volume: false
----
. Asegúrese de que la eliminación automática esté habilitada para los archivos de FlexClone y las LUN FlexClone del volumen que desea eliminar siguiendo estos pasos:
+
.. Habilite la eliminación automática de un archivo de FlexClone o LUN de FlexClone determinado mediante `volume file clone autodelete` el comando. Obtenga más información sobre `volume file clone autodelete` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-file-clone-autodelete.html["Referencia de comandos del ONTAP"^].
+
Puede forzar la eliminación automática de un archivo FlexClone o LUN de FlexClone específico mediante `volume file clone autodelete` el comando con `-force` el parámetro.

+
El ejemplo siguiente muestra que la eliminación automática de la LUN de FlexClone lun1_clone contenida en el volumen vol1 está habilitada:

+
[listing]
----
cluster1::> volume file clone autodelete -vserver vs1 -clone-path /vol/vol1/lun1_clone -enabled true
----
+
Puede activar la eliminación automática cuando crea archivos FlexClone y LUN de FlexClone.

.. Compruebe que el archivo FlexClone o el LUN de FlexClone estén habilitados para la eliminación automática mediante `volume file clone show-autodelete` el comando. Obtenga más información sobre `volume file clone show-autodelete` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-file-clone-show-autodelete.html["Referencia de comandos del ONTAP"^].
+
El ejemplo siguiente muestra que la LUN de FlexClone lun1_clone está habilitada para eliminación automática:

+
[listing]
----
cluster1::> volume file clone show-autodelete -vserver vs1 -clone-path vol/vol1/lun1_clone
Vserver Name: vs1
Clone Path: vol/vol1/lun1_clone
**Autodelete Enabled: true**
----


+
Obtenga más información sobre los comandos descritos en este procedimiento en el link:https://docs.netapp.com/us-en/ontap-cli/["Referencia de comandos del ONTAP"^].


