---
permalink: volumes/convert-directory-qtree-task.html 
sidebar: sidebar 
keywords: convert, directory, qtree 
summary: Si tiene un directorio en el raíz de una FlexVol volume que desea convertir en un qtree, debe migrar los datos incluidos en el directorio a un nuevo qtree con el mismo nombre. 
---
= Convertir un directorio en un qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si dispone de un directorio en el directorio raíz de una FlexVol volume que desea convertir en un qtree, debe migrar los datos incluidos en el directorio a un nuevo qtree con el mismo nombre usando la aplicación cliente.

.Acerca de esta tarea
Los pasos que se deben seguir para convertir un directorio en un qtree dependen del cliente que se use. El siguiente proceso describe las tareas generales que debe completar.

.Antes de empezar
No puede eliminar un directorio si está asociado a un recurso compartido de CIFS existente.

.Pasos
. Cambie el nombre del directorio que se va a convertir en qtree.
. Cree un nuevo qtree con el nombre de directorio original.
. Utilice la aplicación cliente para mover el contenido del directorio al nuevo qtree.
. Elimine el directorio ahora vacío.

