---
permalink: volumes/create-flexclone-file-flexclone-lun-task.html 
sidebar: sidebar 
keywords: create, flexclone file, flexclone lun, efficient, clone 
summary: Puede crear clones de archivos y LUN en un uso eficiente del espacio y el tiempo en volúmenes de FlexVol o FlexClone. 
---
= Cree un archivo FlexClone o una LUN de FlexClone en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear clones de archivos y LUN presentes en los volúmenes FlexVol o FlexClone con gestión eficiente del espacio y con gestión eficiente del tiempo mediante el `volume file clone create` comando.

.Antes de empezar
* Debe instalar la licencia de FlexClone en el clúster. Esta licencia se incluye con link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"].
* Si se utilizan varios rangos de bloques para la clonación de LUN secundarias o la clonación de archivos secundarios, los números de bloque no deben solaparse.
* Si está creando una subLUN o un subarchivo en volúmenes con compresión adaptativa activada, los rangos de bloques no deben estar mal alineados.
+
Esto significa que el número de bloque inicial de origen y el número de bloque inicial de destino deben estar alineados o impares.



.Acerca de esta tarea
Según los privilegios asignados por el administrador del clúster, un administrador de SVM puede crear archivos FlexClone y LUN FlexClone.

Puede especificar la configuración de eliminación automática para archivos FlexClone y LUN FlexClone al crear y modificar clones. De forma predeterminada, la configuración de eliminación automática está desactivada.

Puede sobrescribir un archivo FlexClone o una LUN FlexClone existente al crear un clon mediante la `volume file clone create` con el `-overwrite-destination` parámetro.

Cuando el nodo alcanza su carga de división máxima, el nodo deja de aceptar temporalmente solicitudes para crear archivos FlexClone y LUN FlexClone, y emite un `EBUSY` mensaje de error. Cuando la carga de división del nodo está por debajo del máximo, el nodo acepta solicitudes para crear archivos FlexClone y LUN FlexClone de nuevo. Debe esperar hasta que el nodo tenga capacidad para crear los clones antes de volver a intentar crear la solicitud.

La LUN FlexClone hereda el atributo de reservas de espacio de la LUN principal. Un LUN FlexClone con reserva de espacio requiere tanto espacio como la LUN principal con reserva de espacio. Si la LUN FlexClone no está reservada para el espacio, el volumen debe tener espacio suficiente para acomodar los cambios en el clon.

.Pasos
. Si va a clonar una LUN, compruebe que la LUN no esté asignada ni en la que se esté escribiendo.
. Cree el archivo o LUN de FlexClone:
+
`volume file clone create -vserver _vserver_name_ -volume _volume_name_ -source-path _source_path_ -destination-path _destination_path_`

+
El siguiente ejemplo muestra cómo puede crear un archivo FlexClone archivo1_clone del archivo primario file1_source en el volumen vol1:

+
[listing]
----
cluster1::> volume file clone create -vserver vs0 -volume vol1 -source-path /file1_source -destination-path /file1_clone
----
+
Obtenga más información sobre `volume file clone create` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-file-clone-create.html["Referencia de comandos de la ONTAP"^].





== Crear LUN de FlexClone a partir de una snapshot en un volumen

Se puede usar una snapshot en su volumen para crear copias FlexClone de sus LUN. Las copias FlexClone de las LUN son legibles y editables.

.Antes de empezar
Debe instalar una licencia de FlexClone. Esta licencia se incluye con link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"].

.Acerca de esta tarea
La LUN FlexClone hereda el atributo de reservas de espacio de la LUN principal. Un LUN FlexClone con reserva de espacio requiere tanto espacio como la LUN principal con reserva de espacio. Si la LUN FlexClone no está reservada para el espacio, el volumen debe tener espacio suficiente para acomodar los cambios en el clon.

.Pasos
. Compruebe que la LUN no está asignada ni se está escribiendo en.
. Cree una copia Snapshot del volumen que contiene las LUN:
+
`volume snapshot create -vserver _vserver_name_ -volume _volume_name_ -snapshot _snapshot_name_`

+
Debe crear una snapshot (la snapshot de respaldo) de la LUN que desee clonar.

. Cree la LUN de FlexClone a partir de la snapshot:
+
`volume file clone create -vserver _vserver_name_ -volume _volume_name_ -source-path _source_path_ -snapshot-name _snapshot_name_ -destination-path _destination_path_`

+
Si necesita que la LUN de FlexClone esté disponible para su eliminación automática, tendrá que incluir `-autodelete true`. Si crea este LUN FlexClone en un volumen mediante el aprovisionamiento semi-grueso, debe habilitar la eliminación automática para todas las LUN de FlexClone.

. Compruebe que la LUN de FlexClone es correcta:
+
`lun show -vserver _vserver_name_`

+
[listing]
----

Vserver Path                      State    Mapped    Type     Size
------- ----------------------    -------- --------- -------- -------
vs1     /vol/vol1/lun1_clone      online   unmapped windows   47.07MB
vs1     /vol/vol1/lun1_snap_clone online   unmapped windows   47.07MB
----

