---
permalink: volumes/create-flexclone-snapmirror-concept.html 
sidebar: sidebar 
keywords: considerations, creating, flexclone volume, from snapmirror, source, destination, volume, flexclone, snapmirror, future 
summary: Es posible crear un volumen de FlexClone a partir del volumen de origen o de destino de una relación de SnapMirror existente, pero hacerlo puede afectar a las operaciones de replicación futuras de SnapMirror. 
---
= Consideraciones que tener en cuenta para crear un volumen FlexClone a partir de un volumen de origen o de destino de SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se puede crear un volumen FlexClone desde el volumen de origen o de destino en una relación de SnapMirror para volúmenes existente. No obstante, al hacerlo se podría provocar que las operaciones futuras de replicación de SnapMirror no se completasen correctamente.

Es posible que la replicación no funcione porque cuando se crea el volumen de FlexClone, es posible que se bloquee una copia Snapshot que utiliza SnapMirror. Si esto sucede, SnapMirror detiene la replicación en el volumen de destino hasta que el volumen FlexClone se destruya o se separe de su principal. Existen dos opciones para solucionar este problema:

* Si necesita el volumen FlexClone temporalmente y puede acomodar una parada temporal de la replicación de SnapMirror, puede crear el volumen FlexClone y eliminarlo o dividirlo en su principal cuando sea posible.
+
La replicación de SnapMirror continúa normalmente cuando el volumen FlexClone se elimina o se divide de su principal.

* Si no es aceptable una interrupción temporal de la replicación de SnapMirror, se puede crear una instantánea en el volumen de origen de SnapMirror y utilizarla para crear el volumen de FlexClone. (Si crea el volumen FlexClone a partir del volumen de destino, debe esperar hasta que esa snapshot se replique en el volumen de destino de SnapMirror).
+
Este método de crear una copia Snapshot en el volumen de origen de SnapMirror permite crear el clon sin bloquear una copia Snapshot que utiliza SnapMirror.


