---
permalink: volumes/create-flexclone-file-flexclone-lun-task.html 
sidebar: sidebar 
keywords: create, flexclone file, flexclone lun 
summary: Puede crear clones de archivos y LUN presentes en los volúmenes FlexVol o FlexClone con gestión eficiente del espacio y con gestión eficiente del tiempo mediante el comando volume file clone create. 
---
= Cree un archivo FlexClone o una LUN FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear clones de archivos y LUN presentes en los volúmenes FlexVol o FlexClone con gestión eficiente del espacio y con gestión eficiente del tiempo mediante el `volume file clone create` comando.

.Lo que necesitará
* Debe instalar la licencia de FlexClone en el clúster. Esta licencia se incluye con link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"].
* Si se utilizan varios rangos de bloques para la clonación de LUN secundarias o la clonación de archivos secundarios, los números de bloque no deben solaparse.
* Si está creando una subLUN o un subarchivo en volúmenes con compresión adaptativa activada, los rangos de bloques no deben estar mal alineados.
+
Esto significa que el número de bloque inicial de origen y el número de bloque inicial de destino deben estar alineados o impares.



.Acerca de esta tarea
Según los privilegios asignados por el administrador del clúster, un administrador de SVM puede crear archivos FlexClone y LUN FlexClone.

Puede especificar la configuración de eliminación automática para archivos FlexClone y LUN FlexClone al crear y modificar clones. De forma predeterminada, la configuración de eliminación automática está desactivada.

Puede sobrescribir un archivo FlexClone o una LUN FlexClone existente al crear un clon mediante la `volume file clone create` con el `-overwrite-destination` parámetro.

Cuando el nodo alcanza su carga de división máxima, el nodo deja de aceptar temporalmente solicitudes para crear archivos FlexClone y LUN FlexClone, y emite un `EBUSY` mensaje de error. Cuando la carga de división del nodo está por debajo del máximo, el nodo acepta solicitudes para crear archivos FlexClone y LUN FlexClone de nuevo. Debe esperar hasta que el nodo tenga capacidad para crear los clones antes de volver a intentar crear la solicitud.

.Pasos
. Cree un archivo FlexClone o una LUN FlexClone mediante el `volume file clone create` comando.
+
El siguiente ejemplo muestra cómo puede crear un archivo FlexClone archivo1_clone del archivo primario file1_source en el volumen vol1:

+
[listing]
----
cluster1::> volume file clone create -vserver vs0 -volume vol1 -source-path /file1_source -destination-path /file1_clone
----
+
Para obtener más información acerca de cómo utilizar este comando, consulte las páginas man.



.Información relacionada
link:../concepts/manual-pages.html["Referencia de comandos de la ONTAP"]
