---
permalink: volumes/deduplication-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: how, deduplication, works, flexclone files, fexclone luns 
summary: Puede utilizar de manera eficiente el espacio de almacenamiento físico de los bloques de datos creando un archivo FlexClone o una LUN FlexClone del archivo principal y la LUN principal en un volumen habilitado para la deduplicación. 
---
= Cómo funciona la deduplicación con archivos FlexClone y LUN FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar de manera eficiente el espacio de almacenamiento físico de los bloques de datos creando un archivo FlexClone o una LUN FlexClone del archivo principal y la LUN principal en un volumen habilitado para la deduplicación.

La deduplicación también utiliza el mecanismo de uso compartido de bloques utilizado por archivos y LUN FlexClone. Puede maximizar el ahorro de espacio en un volumen de FlexVol activando la deduplicación en el volumen y, a continuación, clonando el volumen en el que se ha activado la deduplicación.

[NOTE]
====
Al ejecutar el `sis undo` Comando en un volumen habilitado para la deduplicación, no puede crear archivos FlexClone ni LUN FlexClone de los archivos principales ni las LUN principales que residen en dicho volumen.

====