---
permalink: volumes/deduplication-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: deduplication, flexclone files, flexclone luns, files, luns, flexclone, efficiency, efficient, blocks, block 
summary: Puede mejorar la eficiencia del espacio de almacenamiento físico creando un archivo FlexClone o un LUN FlexClone del archivo principal y un LUN primario en un volumen con deduplicación habilitada. 
---
= Deduplicación con archivos FlexClone y LUN de FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar de manera eficiente el espacio de almacenamiento físico de los bloques de datos creando un archivo FlexClone o una LUN FlexClone del archivo principal y la LUN principal en un volumen habilitado para la deduplicación.

La deduplicación también utiliza el mecanismo de uso compartido de bloques utilizado por archivos y LUN FlexClone. Puede maximizar el ahorro de espacio en un volumen de FlexVol activando la deduplicación en el volumen y, a continuación, clonando el volumen en el que se ha activado la deduplicación.

[NOTE]
====
Al ejecutar el `sis undo` Comando en un volumen habilitado para la deduplicación, no puede crear archivos FlexClone ni LUN FlexClone de los archivos principales ni las LUN principales que residen en dicho volumen.

====
Obtenga más información sobre los comandos descritos en este procedimiento en el link:https://docs.netapp.com/us-en/ontap-cli/["Referencia de comandos de la ONTAP"^].
