---
permalink: volumes/deduplication-data-compression-efficiency-concept.html 
sidebar: sidebar 
keywords: use, deduplication, data compression, and data compaction. increase, storage efficiency 
summary: Puede ejecutar la deduplicación, la compresión y la compactación de datos de forma conjunta o de forma independiente para lograr un ahorro de espacio óptimo en un volumen de FlexVol. La deduplicación elimina los bloques de datos duplicados. La compresión de datos comprime los bloques de datos para reducir la cantidad de almacenamiento físico necesaria. La compactación de datos almacena más datos en menos espacio para aumentar la eficiencia del almacenamiento. 
---
= Utilice la deduplicación, la compresión y la compactación de datos para aumentar la información general de la eficiencia del almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ejecutar la deduplicación, la compresión y la compactación de datos de forma conjunta o de forma independiente para lograr un ahorro de espacio óptimo en un volumen de FlexVol. La deduplicación elimina los bloques de datos duplicados. La compresión de datos comprime los bloques de datos para reducir la cantidad de almacenamiento físico necesaria. La compactación de datos almacena más datos en menos espacio para aumentar la eficiencia del almacenamiento.

[NOTE]
====
A partir de ONTAP 9.2, todas las funciones de eficiencia del almacenamiento en línea, como la deduplicación inline y la compresión inline, se habilitan de forma predeterminada en los volúmenes AFF.

====