---
permalink: volumes/deduplication-data-compression-efficiency-concept.html 
sidebar: sidebar 
keywords: deduplication, data compression, data compaction, increase, storage efficiency, efficiency, efficient 
summary: Puede usar la deduplicación, la compresión de datos y la compactación de datos de forma conjunta o independiente para conseguir un ahorro de espacio óptimo en una FlexVol volume. 
---
= Deduplicación, compresión de datos, compactación de datos y eficiencia del almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ejecutar la deduplicación, la compresión y la compactación de datos de forma conjunta o de forma independiente para lograr un ahorro de espacio óptimo en un volumen de FlexVol. La deduplicación elimina los bloques de datos duplicados. La compresión de datos comprime los bloques de datos para reducir la cantidad de almacenamiento físico necesaria. La compactación de datos almacena más datos en menos espacio para aumentar la eficiencia del almacenamiento.

[NOTE]
====
Todas las funciones de eficiencia de almacenamiento en línea, como la deduplicación en línea y la compresión en línea, están habilitadas de forma predeterminada en los volúmenes AFF .

====