---
permalink: volumes/default-quotas-concept.html 
sidebar: sidebar 
keywords: default quotas, quotas, quota, default 
summary: Puede utilizar cuotas predeterminadas para aplicar una cuota a todas las instancias de un determinado tipo de cuota. Las cuotas predeterminadas también permiten modificar las cuotas fácilmente. 
---
= Cómo funcionan las cuotas predeterminadas
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar cuotas predeterminadas para aplicar una cuota a todas las instancias de un determinado tipo de cuota. Por ejemplo, una cuota de usuario predeterminada afecta a todos los usuarios del sistema para el volumen o qtree de FlexVol especificado. Además, las cuotas predeterminadas le permiten modificar fácilmente sus cuotas.

Puede utilizar cuotas predeterminadas para aplicar automáticamente un límite a un gran conjunto de destinos de cuota sin tener que crear cuotas independientes para cada destino. Por ejemplo, si desea limitar la mayoría de los usuarios a 10 GB de espacio en disco, puede especificar una cuota de usuario predeterminada de 10 GB de espacio en disco en lugar de crear una cuota para cada usuario. Si tiene usuarios específicos para los que desea aplicar un límite diferente, puede crear cuotas explícitas para esos usuarios. (Cuotas explícitas --cuotas con un destino o lista de destinos específicos--anulan las cuotas predeterminadas.)

Además, las cuotas predeterminadas le permiten utilizar el cambio de tamaño en lugar de la reinicialización cuando desea que los cambios de cuota surtan efecto. Por ejemplo, si se agrega una cuota de usuario explícita a un volumen que ya tiene una cuota de usuario predeterminada, se puede activar la nueva cuota mediante el cambio de tamaño.

Las cuotas predeterminadas se pueden aplicar a los tres tipos de destino de cuota (usuarios, grupos y qtrees).

Las cuotas predeterminadas no tienen necesariamente límites especificados; una cuota predeterminada puede ser una cuota de seguimiento.

Una cuota se indica mediante un destino que es una cadena vacía ("") o un asterisco (*), según el contexto:

* Cuando se crea una cuota mediante `volume quota policy rule create` comando, establecer el `-target` el parámetro de una cadena vacía ("") crea una cuota predeterminada.
* En la `volume quota policy rule create` comando, el `-qtree` parámetro especifica el nombre del qtree al que se aplica la regla de cuota. Este parámetro no se aplica a las reglas de tipo de árbol. Para las reglas de tipo de usuario o grupo en el nivel de volumen, este parámetro debe contener "".
* En el resultado del `volume quota policy rule show` comando, aparece una cuota predeterminada con una cadena vacía ("") como destino.
* En el resultado del `volume quota report` Comando, aparece una cuota predeterminada con un asterisco (*) como ID y especificador de cuota.




== Ejemplo de cuota de usuario predeterminada

La siguiente regla de cuota utiliza una cuota de usuario predeterminada para aplicar un límite de 50 MB a cada usuario para vol1:

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target "" -qtree "" -disk-limit 50m

cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -          -
----
Si algún usuario del sistema introduce un comando que haría que los datos del usuario tomaran más de 50 MB en vol1 (por ejemplo, escribir en un archivo desde un editor), el comando falla.
