---
permalink: volumes/delete-snapshot-copies-automatic-task.html 
sidebar: sidebar 
keywords: delete, snapshot, copies, automatically, flexclone luns 
summary: Puede definir y habilitar una política para eliminar automáticamente copias Snapshot y LUN FlexClone. La eliminación automática de copias Snapshot y LUN de FlexClone puede ayudarle a gestionar la utilización del espacio. 
---
= Elimine copias Snapshot automáticamente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede definir y habilitar una política para eliminar automáticamente copias Snapshot y LUN FlexClone. La eliminación automática de copias Snapshot y LUN de FlexClone puede ayudarle a gestionar la utilización del espacio.

.Acerca de esta tarea
Puede eliminar automáticamente copias Snapshot de volúmenes de lectura y escritura y LUN FlexClone de volúmenes principales de lectura y escritura. No puede configurar la eliminación automática de las copias Snapshot de volúmenes de solo lectura, por ejemplo, volúmenes de destino de SnapMirror.

.Paso
. Defina y habilite una política para eliminar automáticamente copias de Snapshot mediante el `volume snapshot autodelete modify` comando.
+
Consulte `volume snapshot autodelete modify` manual para obtener información acerca de los parámetros que se pueden utilizar con este comando para definir una directiva que se ajuste a sus necesidades.

+
El siguiente comando permite eliminar automáticamente las copias Snapshot y establece el activador en `snap_reserve` Para el volumen vol3, que forma parte de la máquina virtual de almacenamiento (SVM) de vs0.example.com:

+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs0.example.com
-volume vol3 -enabled true -trigger snap_reserve
----
+
El siguiente comando permite la eliminación automática de las copias Snapshot y de las LUN FlexClone marcadas para la eliminación automática del volumen vol3, que forma parte de la máquina virtual de almacenamiento (SVM) vs0.example.com:

+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs0.example.com
-volume vol3 -enabled true -trigger volume -commitment try -delete-order
oldest_first -destroy-list lun_clone,file_clone
----
+
[NOTE]
====
Las copias Snapshot a nivel de agregado funcionan de forma diferente que las copias Snapshot a nivel de volumen y ONTAP las gestiona automáticamente. La opción para eliminar las copias Snapshot del agregado está siempre habilitada y ayuda a gestionar el uso de espacio.

Si el parámetro trigger está establecido en `snap_reserve` En el caso de un agregado, las copias de Snapshot se mantienen hasta que el espacio reservado supera el umbral de capacidad. Por lo tanto, aunque el parámetro trigger no esté establecido en `snap_reserve`, El espacio utilizado por la copia Snapshot en el comando se mostrará como `0` Dado que estas copias Snapshot se eliminan automáticamente. Además, el espacio utilizado por las copias Snapshot en un agregado se considera libre y se incluye en el parámetro de espacio disponible del comando.

====

