---
permalink: volumes/delete-flexvol-task.html 
sidebar: sidebar 
keywords: delete, flexvol volume, flexvol, volume 
summary: Puede usar la CLI de ONTAP para eliminar una FlexVol volume que ya no sea necesaria. 
---
= Eliminar un volumen de FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible eliminar un volumen de FlexVol que ya no sea necesario.

.Antes de empezar
Ninguna aplicación debe estar accediendo a los datos del volumen que desea eliminar.

[NOTE]
====
Si elimina un volumen por accidente, consulte el artículo de la Base de conocimientos link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_Volume_Recovery_Queue["Cómo usar la cola de recuperación de volúmenes"^].

====
.Pasos
. Si el volumen se montó, desmontarlo:
+
`volume unmount -vserver vserver_name -volume volume_name`

. Si el volumen forma parte de una relación de SnapMirror, elimine la relación mediante `snapmirror delete` el comando.
. Si el volumen está en línea, desconecte el volumen:
+
`volume offline -vserver vserver_name volume_name`

. Elimine el volumen:
+
`volume delete -vserver vserver_name volume_name`





== Resultado

Se elimina el volumen, junto con cualquier qtrees y políticas de cuotas asociadas.

.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/volume-unmount.html["desmonte el volumen"]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["snapmirror elimina"]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-offline.html["volumen sin conexión"]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-delete.html["eliminar el volumen"]

