---
permalink: volumes/delete-flexvol-task.html 
sidebar: sidebar 
keywords: delete, flexvol volume 
summary: Es posible eliminar un volumen de FlexVol que ya no se requiera o que contenga datos dañados. 
---
= Eliminar un volumen de FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible eliminar un volumen de FlexVol que ya no se requiera o que contenga datos dañados.

.Lo que necesitará
Ninguna aplicación debe estar accediendo a los datos del volumen que desea eliminar.

[NOTE]
====
Si elimina por error un volumen, consulte el artículo de la base de conocimientos link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_Volume_Recovery_Queue["Cómo usar la cola de recuperación de volúmenes"^].

====
.Pasos
. Si el volumen se montó, desmontarlo:
+
`volume unmount -vserver vserver_name -volume volume_name`

. Si el volumen forma parte de una relación de SnapMirror, elimine la relación mediante el `snapmirror delete` comando.
. Si el volumen está en línea, desconecte el volumen:
+
`volume offline -vserver vserver_name volume_name`

. Elimine el volumen:
+
`volume delete -vserver vserver_name volume_name`





== Resultado

Se elimina el volumen, junto con cualquier qtrees y políticas de cuotas asociadas.
