---
permalink: volumes/determine-space-usage-volume-aggregate-concept.html 
sidebar: sidebar 
keywords: determine, space usage, volume, aggregate 
summary: 'Al habilitar una función en ONTAP, es posible que consuma espacio que no conoce ni más espacio del esperado. ONTAP le ayuda a determinar cómo se consume el espacio proporcionando tres perspectivas desde las cuales ver el espacio: El volumen, la huella de un volumen dentro del agregado y el agregado.' 
---
= Determine el uso del espacio en un volumen o un agregado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al habilitar una función en ONTAP, es posible que consuma espacio que no conoce ni más espacio del esperado. ONTAP le ayuda a determinar cómo se consume el espacio proporcionando tres perspectivas desde las cuales ver espacio: El volumen, la huella de un volumen dentro del agregado y el agregado.

Un volumen puede quedarse sin espacio debido al consumo de espacio o al espacio insuficiente en el volumen, agregado o una combinación de ambos. Al ver un desglose orientado a las funciones del uso del espacio desde diferentes perspectivas, puede evaluar qué funciones desea ajustar o desactivar, o bien realizar otras acciones (como aumentar el tamaño del agregado o del volumen).

Puede ver los detalles del uso del espacio desde cualquiera de estas perspectivas:

* El uso de espacio del volumen
+
Desde esta perspectiva, se ofrecen detalles sobre el uso de espacio en el volumen, incluido el uso por parte de las copias Snapshot.

+
Para ver el uso de espacio de un volumen, se usa la `volume show-space` comando.

* La huella del volumen dentro del agregado
+
En esta perspectiva, se proporciona información detallada acerca de la cantidad de espacio que cada volumen utiliza en el agregado que contiene, incluidos los metadatos del volumen.

+
Puede ver la huella de un volumen con el agregado mediante el `volume show-footprint` comando.

* Uso de espacio del agregado
+
Esta perspectiva incluye los totales del espacio físico utilizado por el volumen de todos los volúmenes contenidos en el agregado, el espacio reservado para las copias Snapshot agregadas y otros metadatos agregados.

+
WAFL reserva el 10% del espacio total en disco para el rendimiento y los metadatos a nivel de agregado. El espacio utilizado para mantener los volúmenes del agregado sale de la reserva de WAFL y no se puede cambiar.

+
A partir de ONTAP 9.12.1 y versiones posteriores, en las plataformas All Flash FAS (AFF) y FAS500f, la reserva de WAFL para agregados superiores a 30 TB se reduce de un 10 % a un 5 %, de modo que se aumenta el espacio útil del agregado.

+
Puede ver el uso de espacio del agregado mediante la `storage aggregate show-space` comando.



Ciertas funciones, como los respaldos en cinta y la deduplicación, usan espacio para los metadatos tanto del volumen como directamente desde el agregado. Estas funciones muestran un uso de espacio diferente entre las perspectivas de espacio del volumen y la huella del volumen.

.Información relacionada
link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Space_Usage["Artículo basado en conocimientos: Uso del espacio"]

link:https://www.netapp.com/blog/free-up-storage-capacity-upgrade-ontap/["Libere hasta un 5 % de su capacidad de almacenamiento actualizando a ONTAP 9.12.1"]
