---
permalink: volumes/determine-space-usage-volume-aggregate-concept.html 
sidebar: sidebar 
keywords: determine, space usage, volume, aggregate 
summary: ONTAP le ayuda a determinar el consumo de espacio en función del volumen, la huella de un volumen dentro del agregado y el agregado. 
---
= Determine el uso de espacio de un volumen o agregado en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En algunos casos, habilitar una función en ONTAP podría consumir más espacio del esperado. ONTAP le ayuda a determinar cómo se consume el espacio proporcionando tres perspectivas desde las cuales ver espacio: El volumen, la huella de un volumen dentro del agregado y el agregado.



== Consulta de la asignación de espacio

Un volumen puede quedarse sin espacio debido al consumo de espacio o al espacio insuficiente en el volumen, agregado o una combinación de ambos. Al ver un desglose orientado a las características del uso de espacio desde diferentes perspectivas, puede evaluar qué características puede que desee ajustar o desactivar, o si debe realizar otra acción (como aumentar el tamaño del agregado o volumen).

Puede ver los detalles del uso del espacio desde cualquiera de estas perspectivas:

* El uso de espacio del volumen
+
Esta perspectiva proporciona detalles sobre el uso del espacio dentro del volumen, incluido el uso por parte de las copias Snapshot.

+
Use `volume show-space` el comando para ver el uso del espacio de un volumen.

+
Obtenga más información sobre `volume show-space` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-show-space.html["Referencia de comandos del ONTAP"^].

+
A partir de ONTAP 9.14,1, en los volúmenes con xref:enable-temperature-sensitive-efficiency-concept.html[Eficiencia del almacenamiento sensible a la temperatura (TSSE)] habilitado, la cantidad de espacio utilizado en el volumen informado por el `volume show-space -physical used` comando incluye el ahorro de espacio obtenido como resultado del TSSE.

* La huella del volumen dentro del agregado
+
En esta perspectiva, se proporciona información detallada acerca de la cantidad de espacio que cada volumen utiliza en el agregado que contiene, incluidos los metadatos del volumen.

+
Use `volume show-footprint` el comando para ver la huella de un volumen con el agregado.

+
Obtenga más información sobre `volume show-footprint` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-show-footprint.html["Referencia de comandos del ONTAP"^].

* Uso de espacio del agregado
+
Esta perspectiva incluye los totales de las huellas de volumen de todos los volúmenes contenidos en el agregado, el espacio reservado para las snapshots de agregado y otros metadatos de agregados.

+
WAFL reserva el 10% del espacio total en disco para el rendimiento y los metadatos a nivel de agregado. El espacio utilizado para mantener los volúmenes del agregado sale de la reserva de WAFL y no se puede cambiar.

+
A partir de la versión 9.12.1 de ONTAP, la reserva de WAFL para agregados superiores a 30TB TB se ha reducido del 10 % al 5 % para las plataformas AFF y para las plataformas FAS500f. A partir de ONTAP 9.14.1, esta misma reducción se aplica a los agregados en todas las plataformas de FAS, lo que da como resultado un 5 % más de espacio utilizable en los agregados.

+
Use `storage aggregate show-space` el comando para ver el uso de espacio del agregado.

+
Obtenga más información sobre `storage aggregate show-space` en el link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-space.html["Referencia de comandos del ONTAP"^].



Ciertas funciones, como los respaldos en cinta y la deduplicación, usan espacio para los metadatos tanto del volumen como directamente desde el agregado. Estas funciones muestran un uso de espacio diferente entre las perspectivas de espacio del volumen y la huella del volumen.

.Información relacionada
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Space_Usage["Artículo de la base de conocimientos: Uso del espacio"^]
* link:https://www.netapp.com/blog/free-up-storage-capacity-upgrade-ontap/["Libere hasta un 5 % de su capacidad de almacenamiento actualizando a ONTAP 9.12.1"^]




== Informes de métricas de datos y metadatos de volumen

Históricamente, varias de las métricas de espacio del volumen han informado de los datos totales consumidos como una combinación de dos métricas: Los metadatos y los datos del usuario. A partir de ONTAP 9.15.1, las métricas de metadatos y datos de usuario se informan por separado. Se han introducido dos nuevos contadores de metadatos para admitir esto:

* metadatos totales
+
Este contador proporciona el tamaño total de metadatos dentro del volumen. No incluye los metadatos del volumen residente del agregado. La generación de informes por separado ayuda a determinar los datos lógicos asignados por el usuario.

* huella de metadatos total
+
Este contador es la suma de los metadatos residentes del volumen y los metadatos del volumen residente agregado. Proporciona la huella total de metadatos del volumen dentro del agregado. Informar por separado ayuda a determinar los datos físicos asignados por el usuario.



Además, se han actualizado varios contadores existentes para eliminar el componente de metadatos y presentar solo los datos del usuario:

* Datos de usuarios
* Huella de datos de volumen


Estos cambios proporcionan una vista más precisa de los datos consumidos por el usuario. Esto ofrece varias ventajas, incluida la capacidad de tomar decisiones más precisas sobre el pago por uso.
