---
permalink: volumes/disable-deduplication-volume-task.html 
sidebar: sidebar 
keywords: disabling, deduplication, volume 
summary: Puede deshabilitar la deduplicación postprocesamiento y la deduplicación en línea de forma independiente en un volumen. 
---
= Desactivar la deduplicación en un volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede deshabilitar la deduplicación postprocesamiento y la deduplicación en línea de forma independiente en un volumen.

.Antes de empezar
Detenga todas las operaciones de eficiencia de volumen que estén actualmente activas en el volumen: `volume efficiency stop`

Obtenga más información sobre `volume efficiency stop` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-stop.html["Referencia de comandos del ONTAP"^].

.Acerca de esta tarea
Si ha habilitado la compresión de datos en el volumen, ejecutar `volume efficiency off` el comando deshabilita la compresión de datos. Obtenga más información sobre `volume efficiency off` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-off.html["Referencia de comandos del ONTAP"^].

.Opciones
* Use el `volume efficiency off` comando para deshabilitar la deduplicación postprocesamiento y la deduplicación inline.
+
El siguiente comando deshabilita la deduplicación postprocesamiento y la deduplicación en línea en el volumen Vola:

+
`volume efficiency off -vserver vs1 -volume VolA`

* Use `volume efficiency modify` el comando con `-policy` la opción configurada para `inline only` deshabilitar la deduplicación postprocesamiento, pero la deduplicación inline permanece habilitada.
+
El siguiente comando deshabilita la deduplicación postprocesamiento, pero la deduplicación inline permanece habilitada en el volumen Vola:

+
`volume efficiency modify -vserver vs1 -volume VolA -policy inline-only`

* Utilice `volume efficiency modify` el comando con `-inline-deduplication` la opción configurada para `false` deshabilitar solo la deduplicación en línea.
+
El siguiente comando deshabilita solo la deduplicación en línea en el volumen Vola:

+
`volume efficiency modify -vserver vs1 -volume VolA -inline-deduplication false`

+
Obtenga más información sobre `volume efficiency modify` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["Referencia de comandos del ONTAP"^].


