---
permalink: volumes/display-file-inode-usage-task.html 
sidebar: sidebar 
keywords: display, file, inode, usage 
summary: 'Los volúmenes FlexVol tienen un número máximo de archivos que pueden contener. Saber cuántos archivos contiene sus volúmenes le ayuda a determinar si necesita aumentar el número de inodos (públicos) de sus volúmenes para evitar que estos puedan alcanzar su límite máximo de archivos.' 
---
= Muestra el uso de archivos o inodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los volúmenes FlexVol tienen un número máximo de archivos que pueden contener. Saber cuántos archivos contiene sus volúmenes le ayuda a determinar si necesita aumentar el número de inodos (públicos) de sus volúmenes para evitar que estos puedan alcanzar su límite máximo de archivos.

.Acerca de esta tarea
Los inodos públicos pueden ser libres (no están asociados a un archivo) o utilizados (señalan a un archivo). El número de inodos libres de un volumen es el número total de inodos del volumen menos el número de inodos usados (el número de archivos).

Si existen recursos compartidos a nivel de qtree y volumen en el mismo pool FlexVol o SCVMM, los qtrees aparecen como directorios en el recurso compartido de FlexVol. Por lo tanto, debe tener cuidado de no eliminarlos accidentalmente.

.Paso
. Para mostrar el uso de nodos de información de un volumen, introduzca el siguiente comando:
+
[source, cli]
----
volume show -vserver <SVM_name> -volume <volume_name> -fields files
----


.Ejemplo
[listing]
----
cluster1::*> volume show -vserver vs1 -volume vol1 -fields files
Vserver Name: vs1
Files Used (for user-visible data): 98
----