---
permalink: volumes/du-command-space-usage-concept.html 
sidebar: sidebar 
keywords: how, du command, accounts for, space usage 
summary: Cuando ejecuta el comando du para comprobar el uso de espacio en disco de un volumen de qtree o FlexVol montado en un cliente UNIX, el valor de uso puede ser superior al valor que muestra un informe de cuota para el qtree o el volumen. 
---
= Cómo el comando du tiene en cuenta el uso del espacio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando ejecute el `du` Comando para comprobar el uso del espacio en disco de un volumen de qtree o FlexVol montado en un cliente UNIX, puede que el valor de uso sea superior al valor que se muestra en un informe de cuota para el qtree o volumen.

El resultado del `du` el comando contiene el uso de espacio combinado de todos los archivos a través del árbol de directorios que comienza en el nivel del directorio en el que se emite el comando. Porque el valor de uso que muestra `du` el comando también incluye los bloques de datos de los directorios, es superior al valor mostrado por un informe de cuota.

.Ejemplo de la diferencia entre el uso de espacio contabilizado por el comando du y un informe de cuota
En el siguiente informe de cuotas se muestra un límite de 10 MB para un primer trimestre de qtree:

[listing]
----

                                      ----Disk----  ----Files-----   Quota
  Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
  -------  --------  ------  -------  -----  -----  ------  ------   ---------
  vol1     q1          tree    user1   10MB   10MB       1       -   q1

...
----
En el siguiente ejemplo, el uso de espacio en disco como resultado del `du` el comando muestra un valor mayor que supera el límite de cuota:

[listing]
----
[user1@lin-sys1 q1]$ du -sh
**11M**     q1
----