---
permalink: volumes/enable-storage-efficiency-visualization-concept.html 
sidebar: sidebar 
keywords: storage, efficiency, visualization, storage aggregate 
summary: Muestre diferentes vistas de la eficiencia del almacenamiento de todos los agregados del sistema. 
---
= Visualización de la eficiencia del almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilice `storage aggregate show-efficiency` el comando para mostrar información sobre la eficiencia del almacenamiento de todos los agregados del sistema. Obtenga más información sobre `storage aggregate show-efficiency` en el link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-efficiency.html["Referencia de comandos de la ONTAP"^].

La `storage aggregate show-efficiency` el comando tiene tres vistas diferentes que se pueden invocar pasando opciones de comando.



== Vista predeterminada

La vista predeterminada muestra la relación general de cada uno de los agregados.

`cluster1::> storage aggregate show-efficiency`



== Vista detallada

Invoque la vista detallada con el `-details` opción de comando. Esta vista muestra lo siguiente:

* Tasa de eficiencia general para cada uno de los agregados.
* Ratio general sin instantáneas.
* División de la proporción entre las siguientes tecnologías de eficiencia: Deduplicación de volúmenes, compresión de volúmenes, snapshots, clones, compactación de datos y deduplicación inline de agregados.


`cluster1::> storage aggregate show-efficiency -details`



== Vista avanzada

La vista avanzada es similar a la vista detallada y muestra detalles utilizados tanto lógicos como físicos.

Este comando se debe ejecutar en el nivel de privilegios avanzados. Cambie a privilegios avanzados mediante el `set -privilege advanced` comando.

El símbolo del sistema cambia a. `cluster::*>`.

`cluster1::> set -privilege advanced`

Invoque la vista avanzada con `-advanced` opción de comando.

`cluster1::*> storage aggregate show-efficiency -advanced`

Para ver las relaciones de un único agregado, invoque individualmente el `-aggregate _aggregate_name_` comando. Este comando puede ejecutarse en el nivel admin, como también en el nivel de privilegios avanzados.

`cluster1::> storage aggregate show-efficiency -aggregate aggr1`

Obtenga más información sobre `set -privilege advanced` en el link:https://docs.netapp.com/us-en/ontap-cli/set.html["Referencia de comandos de la ONTAP"^].
