---
permalink: volumes/enable-inline-data-compaction-fas-systems-task.html 
sidebar: sidebar 
keywords: enable, inline, data compaction, fas systems, hdd aggregate, volume efficiency 
summary: 'Habilite la compactación de datos inline en sistemas FAS con agregados de Flash Pool (híbrido) o agregados de HDD a nivel del volumen o del agregado.' 
---
= Habilite la compactación de datos inline para sistemas de FAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar la compactación de datos inline en sistemas FAS con agregados de Flash Pool (híbridos) o agregados de HDD en el nivel del volumen mediante el comando cluster shell. `volume efficiency` La compactación de datos está deshabilitada de forma predeterminada para volúmenes creados en sistemas FAS.

.Acerca de esta tarea
Para habilitar la compactación de datos inline en un volumen, su `-space-guarantee` opción debe establecerse en `none`. Al habilitar la compactación de datos en un volumen en un agregado de HDD, se utilizan recursos de CPU adicionales.

.Pasos
. Cambie al nivel de privilegio avanzado:
+
[source, cli]
----
set -privilege advanced
----
. Compruebe el estado de compactación de datos de los volúmenes y agregados del nodo deseado:
+
[source, cli]
----
volume efficiency show -volume <volume_name>
----
. Habilitar compactación de datos en el volumen:
+
[source, cli]
----
volume efficiency modify -volume <volume_name> -data-compaction true
----
+
[NOTE]
====
Si se establece la compactación de datos en `false` tanto para un agregado o para un volumen, la compactación fallará. Habilitar la compactación no compacta los datos existentes; solo se compactan las nuevas escrituras en el sistema. El `volume efficiency start` comando contiene más información sobre cómo compactar datos existentes. Para obtener más información, consulte la https://docs.netapp.com/us-en/ontap-cli["Referencia de comandos de la ONTAP"^].

====
. Consulte las estadísticas de compactación:
+
[source, cli]
----
volume efficiency show -volume <volume_name>
----

