---
permalink: volumes/enable-large-vol-file-support-task.html 
sidebar: sidebar 
keywords: create, modify, volume, large file, large volume 
summary: Es posible habilitar compatibilidad para volúmenes y archivos de gran tamaño al crear un volumen nuevo o modificar un volumen existente. 
---
= Habilite el soporte de grandes volúmenes y archivos de gran tamaño
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.12.1 P2, puede crear un nuevo volumen o modificar un volumen existente para permitir la compatibilidad con un tamaño de volumen máximo de 300TB TB y un tamaño máximo de archivo (LUN) de 128TB TB.

.Antes de empezar
* ONTAP 9.12.1 P2 o posterior se instala en el clúster.
* Si habilita la compatibilidad con volúmenes grandes en el clúster de origen en una relación de SnapMirror, debe tener ONTAP 9.12.1 P2 o una versión posterior instalada en el clúster que aloja el volumen de origen y el clúster que aloja el volumen de destino.
* Es un administrador de clústeres o de SVM.




== Cree un nuevo volumen

.Paso
. Cree un volumen con compatibilidad de grandes volúmenes y archivos habilitada:
+
[source, cli]
----
volume create -vserver _svm_name_ -volume _volume_name_ -aggregate _aggregate_name_ -is-large-size-enabled true
----


.Ejemplo
En el siguiente ejemplo, se crea un nuevo volumen con compatibilidad con volúmenes grandes y tamaño de archivo habilitada.

[listing]
----
volume create -vserver vs1 -volume big_vol1 -aggregate aggr1 -is-large-size-enabled true
----


== Modifique un volumen existente

.Paso
. Modifique un volumen para habilitar el soporte de archivos y volúmenes grandes:
+
[source, cli]
----
volume modify -vserver _svm_name_ -volume _volume_name_ -is-large-size-enabled true
----


.Ejemplo
En el siguiente ejemplo se modifica un volumen existente para admitir volúmenes y tamaños de archivo grandes.

[listing]
----
volume modify -vserver vs2 -volume data_vol -is-large-size-enabled true
----
.Información relacionada
* link:https://docs.netapp.com/us-en/ontap/volumes/create-volume-task.html["Cree un volumen"]
* link:https://docs.netapp.com/us-en/ontap-cli-9141/["Referencia de comandos"]

