---
permalink: volumes/enforced-quotas-differ-configured-concept.html 
sidebar: sidebar 
keywords: why, enforced, quotas, differ, configured, quotas 
summary: Las cuotas forzadas difieren de las configuradas porque las cuotas derivadas se aplican sin ser configuradas, pero las cuotas configuradas se aplican sólo después de inicializarse correctamente. La comprensión de estas diferencias puede ayudarle a comparar las cuotas impuestas que se muestran en los informes de cuotas con las cuotas configuradas. 
---
= El motivo por el que las cuotas impuestas difieren de las cuotas configuradas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las cuotas forzadas difieren de las configuradas porque las cuotas derivadas se aplican sin ser configuradas, pero las cuotas configuradas se aplican sólo después de inicializarse correctamente. La comprensión de estas diferencias puede ayudarle a comparar las cuotas impuestas que se muestran en los informes de cuotas con las cuotas configuradas.

Las cuotas forzadas, que aparecen en los informes de cuotas, pueden diferir de las reglas de cuota configuradas por los siguientes motivos:

* Las cuotas derivadas se aplican sin estar configuradas como reglas de cuota; ONTAP crea cuotas derivadas automáticamente en respuesta a las cuotas predeterminadas.
* Es posible que las cuotas no se hayan reinicializado en un volumen después de configurar las reglas de cuota.
* Es posible que se hayan producido errores cuando se inicializaron las cuotas en un volumen.

