---
permalink: volumes/features-supported-volume-rehost-concept.html 
sidebar: sidebar 
keywords: features, do not support, volume rehost 
summary: Hay ciertas funciones que no admiten la realojamiento de volúmenes. 
---
= Funciones que no admiten la realojamiento de volúmenes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay ciertas funciones que no admiten la realojamiento de volúmenes.

Las siguientes funciones no admiten la realojamiento de volúmenes:

* DR DE SVM
* Configuraciones de MetroCluster
* Volúmenes de SnapLock
* Volúmenes de cifrado de volúmenes de NetApp (NVE) (en versiones de ONTAP anteriores a 9,8)
+
En las versiones de ONTAP anteriores a 9,8, debe anular el cifrado del volumen antes de volver a alojarlo. Las claves de cifrado de volúmenes dependen de las claves de SVM. Si se mueve un volumen a otra SVM y está habilitada la configuración de claves multitenant en la SVM de origen o de destino, las claves de SVM y el volumen no coincidirán.

+
A partir de ONTAP 9,8, se puede realojar un volumen con NVE.

* Volúmenes de FlexGroup
* Clonar volúmenes

