---
permalink: volumes/flexclone-files-luns-efficient-copies-concept.html 
sidebar: sidebar 
keywords: use, flexclone files, flexclone luns, create, efficient, copies, files, luns 
summary: Los archivos FlexClone y las LUN FlexClone son clones editables y con gestión eficiente del espacio de los archivos principales y LUN principales. 
---
= Información general sobre el uso de archivos FlexClone y LUN de FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los archivos FlexClone y las LUN de FlexClone son clones que permiten escritura y gestión eficiente del espacio de los archivos principales y las LUN principales, y ayudan a utilizar con eficiencia el espacio del agregado físico. Los archivos FlexClone y las LUN FlexClone solo se admiten para volúmenes FlexVol.

Los archivos FlexClone y LUN de FlexClone usan el 0,4 % de su tamaño para almacenar los metadatos. Los clones comparten los bloques de datos de sus archivos principales y las LUN principales y ocupan un espacio de almacenamiento mínimo hasta que los clientes escriben los datos nuevos en el archivo principal o la LUN o en el clon.

Los clientes pueden realizar todas las operaciones de archivos y LUN en las entidades principal y clonado.

Puede utilizar varios métodos para eliminar archivos FlexClone y LUN FlexClone.
