---
permalink: volumes/full-quota-reinitialization-required-concept.html 
sidebar: sidebar 
keywords: when, full, quota, reinitialization, required 
summary: Aunque el cambio de tamaño de las cuotas es más rápido, debe volver a inicializar todas las cuotas si realiza algunos cambios pequeños o extensos en las cuotas. 
---
= Cuando se requiere una reinicialización completa de la cuota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aunque el cambio de tamaño de las cuotas es más rápido, debe volver a inicializar todas las cuotas si realiza algunos cambios pequeños o extensos en las cuotas.

Es necesaria una reinicialización completa de la cuota en las siguientes circunstancias:

* Se crea una cuota para un destino que no tiene previamente una cuota.
* Se cambia la asignación de usuarios en la `usermap.cfg` Y utiliza la entrada QUOTA_PERFORM_USER_MAPPING en el archivo Quotas.
* Se cambia el estilo de seguridad de un qtree de UNIX a mixto o NTFS.
* Se cambia el estilo de seguridad de un qtree de NTFS o mixto a UNIX.
* Se quitan usuarios de un destino de cuota con varios usuarios o se agregan usuarios a un destino que ya tiene varios usuarios.
* Usted realiza cambios extensos en sus cuotas.


.Ejemplo de cambios de cuotas que requieren inicialización
Supongamos que tiene un volumen que contiene tres qtrees y que las únicas cuotas del volumen son tres cuotas de árbol. Decide realizar los siguientes cambios:

* Agregue un qtree nuevo y cree una nueva cuota de árbol para él.
* Añada una cuota de usuario predeterminada para el volumen.


Ambos cambios requieren una inicialización de cuota completa. El redimensionamiento no hace que las cuotas sean efectivas.
