---
permalink: volumes/logical-space-enforcement-concept.html 
sidebar: sidebar 
keywords: what, logical, space, enforcement, does 
summary: Cuando habilita el cumplimiento de espacio lógico en ONTAP 9 Intersight 5 y versiones posteriores, se notifica a los usuarios cuando un volumen está lleno o casi lleno. 
---
= Cumplimiento del espacio lógico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La aplicación del espacio lógico garantiza que se notifique a los usuarios cuando un volumen está lleno o casi lleno. Cuando se habilita la aplicación de espacio lógico en ONTAP 9.5 y versiones posteriores, ONTAP cuenta los bloques lógicos utilizados en un volumen para determinar la cantidad de espacio que aún está disponible en ese volumen. Si no hay espacio disponible en un volumen, el sistema devuelve un mensaje de error de ENOSPC (sin espacio).

La aplicación lógica del espacio devuelve tres tipos de alertas para informarle acerca del espacio disponible en un volumen:

* `Monitor.vol.full.inc.sav`: Esta alerta se activa cuando se ha utilizado el 98% del espacio lógico del volumen.
* `Monitor.vol.nearFull.inc.sav`: Esta alerta se activa cuando se ha utilizado el 95% del espacio lógico del volumen.
* `Vol.log.overalloc.inc.sav`: Esta alerta se activa cuando el espacio lógico utilizado en el volumen es mayor que el tamaño total del volumen.
+
Esta alerta indica que añadir al tamaño del volumen puede no crear espacio disponible, ya que dicho espacio ya estará consumido por bloques lógicos asignados en exceso.



[NOTE]
====
El total (espacio lógico) debe ser igual al espacio aprovisionado excluyendo la reserva de instantáneas del volumen con el cumplimiento del espacio lógico.

====
Para obtener más información, consulte link:../volumes/configure-automatic-provide-space-when-full-task.html["Configurar volúmenes para que proporcionen automáticamente más espacio cuando estén llenos"].
