---
permalink: volumes/methods-delete-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: methods, delete, flexclone, files, flexclone luns 
summary: Comprenda qué métodos están disponibles para eliminar archivos FlexClone y LUN de FlexClone. 
---
= Métodos para eliminar archivos FlexClone y LUN FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar varios métodos para eliminar archivos FlexClone y LUN FlexClone. Comprender qué métodos están disponibles le permite planificar cómo gestionar clones.

Puede utilizar los siguientes métodos para eliminar archivos de FlexClone y LUN de FlexClone:

* Es posible configurar un volumen de FlexVol para eliminar automáticamente clones con la eliminación automática habilitada cuando el espacio libre de un volumen de FlexVol disminuye por debajo de un umbral en particular.
* Puede configurar clientes para eliminar clones mediante el SDK de gestión de NetApp.
* Puede utilizar los clientes para eliminar clones mediante los protocolos NAS y SAN.
+
El método de eliminación más lento se habilita de forma predeterminada porque este método no utiliza el SDK de gestión de NetApp. Sin embargo, puede configurar el sistema para que utilice el método de eliminación más rápido al eliminar archivos FlexClone mediante `volume file clone deletion` los comandos.


