---
permalink: volumes/methods-copying-volume-concept.html 
sidebar: sidebar 
keywords: methods to, copy, volume 
summary: El método que se utiliza para copiar un volumen depende de la ubicación de agregado y si desea conservar snapshots del volumen original. 
---
= Métodos para copiar un volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El método que se utiliza para copiar un volumen depende de si se va a copiar en el mismo agregado o en otro y de si se desean conservar Snapshot del volumen original. El copiado de un volumen crea una copia independiente de un volumen que se puede usar para pruebas y otros fines.

En la siguiente tabla se enumeran las características de la copia y los métodos utilizados para crear dicha copia.

[cols="2*"]
|===
| Si desea copiar un volumen... | Entonces, el método que usa es... 


 a| 
Dentro del mismo agregado y no se desean copiar snapshots del volumen original.
 a| 
Creación de un volumen FlexClone del volumen original.



 a| 
En otro agregado y no se desean copiar copias de Snapshot del volumen original.
 a| 
Crear un volumen FlexClone del volumen original y, a continuación, mover el volumen a otro agregado mediante el `volume move` comando.



 a| 
En otro agregado y conserve todas las copias de Snapshot del volumen original.
 a| 
Replicar el volumen original mediante SnapMirror y, a continuación, dividir la relación de SnapMirror para hacer una copia de volumen de lectura/escritura.

|===