---
permalink: volumes/move-between-secondary-adaptive-compression-task.html 
sidebar: sidebar 
keywords: move, secondary compression, adaptive compression 
summary: Puede cambiar entre la compresión secundaria y la compresión adaptativa en función de la cantidad de lecturas de datos. 
---
= Cambie entre la compresión secundaria y la compresión adaptativa
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede cambiar entre la compresión secundaria y la compresión adaptativa en función de la cantidad de lecturas de datos. Es preferible realizar la compresión adaptativa cuando hay un gran volumen de lecturas aleatorias en el sistema y se requiere un mayor rendimiento. Se recomienda la compresión secundaria cuando los datos se escriben de forma secuencial y se requieren mayores ahorros en la compresión.

.Acerca de esta tarea
El tipo de compresión predeterminado se selecciona según los agregados y la plataforma.

.Pasos
. Desactive la eficiencia en el volumen:
+
`volume efficiency off`

+
Por ejemplo, el siguiente comando deshabilita la eficiencia en el volumen vol1:

+
`volume efficiency off -vserver vs1 -volume vol1`

. Cambie al nivel de privilegio avanzado:
+
`set -privilege advanced`

. Descomprimir los datos comprimidos:
+
`volume efficiency undo`

+
Por ejemplo, el siguiente comando descomprime los datos comprimidos en el volumen vol1:

+
`volume efficiency undo -vserver vs1 -volume vol1 -compression true`

+
[NOTE]
====
Debe verificar que dispone de espacio suficiente en el volumen para acomodar los datos descomprimidos.

====
. Cambie al nivel de privilegio de administrador:
+
`set -privilege admin`

. Verificar que el estado de la operación está inactivo:
+
`volume efficiency show`

+
Por ejemplo, el siguiente comando muestra el estado de una operación de eficiencia en el volumen vol1:

+
`volume efficiency show -vserver vs1 -volume vol1`

. Habilite la eficiencia para el volumen:
+
`volume efficiency on` Por ejemplo, el siguiente comando habilita la eficiencia en el volumen vol1:

+
`volume efficiency on -vserver vs1 -volume vol1`

. Habilite la compresión de datos y, a continuación, establezca el tipo de compresión:
+
`volume efficiency modify`

+
Por ejemplo, el siguiente comando habilita la compresión de datos y establece el tipo de compresión como compresión secundaria en el volumen vol1:

+
`volume efficiency modify -vserver vs1 -volume vol1 -compression true -compression-type secondary`

+
[NOTE]
====
Este paso solo habilita la compresión secundaria en el volumen, mientras que los datos del volumen no se comprimen.

** Para comprimir los datos existentes en sistemas AFF, debe ejecutar el análisis de compresión en segundo plano.
** Para comprimir los datos existentes en agregados de Flash Pool o agregados de HDD, debe ejecutar la compresión en segundo plano.


====
. Opcional: Habilitar la compresión en línea:
+
`volume efficiency modify`

+
Por ejemplo, el siguiente comando habilita la compresión en línea en el volumen vol1:

+
`volume efficiency modify -vserver vs1 -volume vol1 -inline-compression true`


