---
permalink: volumes/overview-quota-process-concept.html 
sidebar: sidebar 
keywords: overview, quota, process 
summary: Las cuotas pueden ser suaves o duras. Las cuotas blandas hacen que ONTAP envíe una notificación cuando se superen los límites especificados y las cuotas rígidas evitan que una operación de escritura tenga éxito cuando se superen los límites especificados. 
---
= Proceso de cuotas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las cuotas proporcionan una forma de restringir o realizar un seguimiento del espacio en disco y del número de archivos que usan los usuarios, grupos o qtrees. Las cuotas se aplican a un volumen o qtree de FlexVol concreto.

Las cuotas pueden ser suaves o duras. Las cuotas blandas hacen que ONTAP envíe una notificación cuando se superen los límites especificados y las cuotas rígidas evitan que una operación de escritura tenga éxito cuando se superen los límites especificados.

Cuando ONTAP recibe una solicitud de un usuario o grupo de usuarios para escribir en un volumen de FlexVol, comprueba si se activan las cuotas en ese volumen para el usuario o el grupo de usuarios y determina lo siguiente:

* Si se alcanzará el límite rígido
+
En caso afirmativo, la operación de escritura falla cuando se alcanza el límite rígido y se envía la notificación de cuota dura.

* Si se incumplido el límite blando
+
Si la respuesta es sí, la operación de escritura se realiza correctamente cuando se cumple el límite de software y se envía la notificación de cuota de software.

* Si una operación de escritura no superará el límite de software
+
Si la respuesta es sí, la operación de escritura es correcta y no se envía ninguna notificación.


