---
permalink: volumes/quotas-concept.html 
sidebar: sidebar 
keywords: why use quotas, quota benefits 
summary: Es posible usar cuotas para gestionar y supervisar el uso de los recursos con volúmenes de FlexVol. 
---
= Ventajas del uso de cuotas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible usar cuotas para gestionar y supervisar el uso de los recursos con volúmenes de FlexVol.

La definición de cuotas ofrece varias ventajas. Puede utilizar las cuotas predeterminadas, explícitas, derivadas y de seguimiento para gestionar el uso del disco de la forma más eficaz posible.

.Limite el consumo de recursos
Puede limitar la cantidad de espacio en disco o la cantidad de archivos que utiliza un usuario o grupo, o que contiene un qtree.

.Realice un seguimiento del uso de recursos
Se puede realizar un seguimiento de la cantidad de espacio en disco o el número de archivos que utiliza un usuario, grupo o qtree sin fijar un límite.

.Notificar a los usuarios
Las notificaciones se pueden generar cuando el uso de recursos alcanza niveles específicos. Esto avisa a los usuarios cuando su uso del disco o del archivo es demasiado alto.
