---
permalink: volumes/quotas-applied-root-user-concept.html 
sidebar: sidebar 
keywords: quotas applied, root user 
summary: 'El usuario raíz (UID=0) en los clientes UNIX está sujeto a cuotas de árbol, pero no a cuotas de usuario o grupo. Esto permite que el usuario raíz realice acciones en nombre de otros usuarios que de otro modo serían evitados por una cuota.' 
---
= Cómo se aplican las cuotas al usuario raíz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El usuario raíz (UID=0) en los clientes UNIX está sujeto a cuotas de árbol, pero no a cuotas de usuario o grupo. Esto permite que el usuario raíz realice acciones en nombre de otros usuarios que de otro modo serían evitados por una cuota.

Cuando el usuario root realiza un cambio de propiedad de archivo o directorio u otra operación (como el `chown` comando unix) en nombre de un usuario con menos Privileges, ONTAP comprueba las cuotas en función del nuevo propietario, pero no informa de errores ni detiene la operación, incluso si se superan las restricciones de cuota dura del nuevo propietario. Esto puede ser útil cuando una acción administrativa, como la recuperación de datos perdidos, resulta en exceder temporalmente las cuotas.

[NOTE]
====
Sin embargo, una vez realizada la transferencia de propiedad, un sistema cliente informará de un error de espacio en disco si el usuario intenta asignar más espacio en disco mientras se supera la cuota.

====
.Información relacionada
* link:../volumes/quotas-applied-concept.html["Cómo se aplican las cuotas"]
* link:../volumes/quotas-applied-users-multiple-ids-concept.html["Cómo se aplican las cuotas a los usuarios con múltiples ID"]

