---
permalink: volumes/quotas-activated-concept.html 
sidebar: sidebar 
keywords: quotas, how quotas are activated, quota activation 
summary: Para que surtan efecto, deben activarse nuevas cuotas y cambios en las cuotas existentes. La activación se realiza a nivel de volumen. Saber cómo funciona la activación de cuotas puede ayudarle a administrar sus cuotas con menos interrupciones. 
---
= Descripción general de cómo se activan las cuotas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para que surtan efecto, deben activarse nuevas cuotas y cambios en las cuotas existentes. La activación se realiza a nivel de volumen. Saber cómo funciona la activación de cuotas puede ayudarle a administrar sus cuotas con menos interrupciones.

Las cuotas se activan mediante _inicializando_ (activándolas) o _redimensionamiento_. La desactivación de cuotas y su activación se denomina reinicialización.

La duración del proceso de activación y su impacto en la aplicación de las cuotas depende del tipo de activación:

* El proceso de inicialización incluye dos partes: A `quota on` trabajo y un análisis de cuota del sistema de archivos completo del volumen. La exploración comienza después de la `quota on` el trabajo se completa correctamente. El análisis de cuotas puede tardar algún tiempo; cuantos más archivos tenga el volumen, más tiempo tardará. Hasta que finalice la exploración, la activación de cuota no se completa y las cuotas no se aplican.
* El proceso de cambio de tamaño solo implica un `quota resize` trabajo. El cambio de tamaño requiere menos tiempo que una inicialización de cuota porque no implica una exploración de cuota. Durante el proceso de cambio de tamaño, las cuotas se siguen aplicando.


De forma predeterminada, la `quota on` y.. `quota resize` los trabajos se ejecutan en segundo plano, lo que permite utilizar otros comandos al mismo tiempo.

Los errores y advertencias del proceso de activación se envían al sistema de administración de eventos. Si utiliza la `-foreground` con el `volume quota on` o. `volume quota resize` comandos, el comando no devuelve hasta que el trabajo se completa; esto es útil si se está reinicializando desde un script. Para mostrar más adelante los errores y advertencias, puede utilizar la `volume quota show` con el `-instance` parámetro.

La activación de la cuota permanece en paradas y reinicios. El proceso de activación de cuotas no afecta a la disponibilidad de los datos del sistema de almacenamiento.

.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-on.html["cuota de volumen activada"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-resize.html["cambio de tamaño de la cuota de volumen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-show.html["se muestra la cuota de volumen"^]

