---
permalink: volumes/quota-rules-policies-enforced-quotas-concept.html 
sidebar: sidebar 
keywords: what are, quota rules, quota policies, quotas 
summary: 'Las cuotas se definen en reglas de cuotas específicas de los volúmenes de FlexVol. Estas reglas de cuota se recogen en una política de cuotas de una máquina virtual de almacenamiento (SVM) y, a continuación, se activan en cada volumen del SVM.' 
---
= Qué son las reglas de cuotas, las políticas de cuotas y las cuotas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las cuotas se definen en reglas de cuotas específicas de los volúmenes de FlexVol. Estas reglas de cuota se recogen en una política de cuotas de una máquina virtual de almacenamiento (SVM) y, a continuación, se activan en cada volumen del SVM.

Una regla de cuota siempre es específica de un volumen. Las reglas de cuota no tienen efecto hasta que se activan las cuotas en el volumen definido en la regla de cuota.

Una política de cuota es una colección de reglas de cuota para todos los volúmenes de una SVM. Las políticas de cuotas no se comparten entre las SVM. Una SVM puede tener hasta cinco políticas de cuota, lo que le permite tener copias de backup de políticas de cuotas. Se asigna una política de cuota a una SVM en cualquier momento.

Una cuota es la restricción real que ONTAP impone o el seguimiento real que ONTAP realiza. Una regla de cuota siempre da como resultado al menos una cuota y podría dar lugar a muchas cuotas derivadas adicionales. La lista completa de cuotas forzadas sólo es visible en los informes de cuotas.

La activación es el proceso de activación de ONTAP para crear cuotas impuestas a partir del conjunto actual de reglas de cuotas en la política de cuotas asignada. La activación se produce volumen por volumen. La primera activación de cuotas en un volumen se denomina inicialización. Las activaciones posteriores se denominan reinicialización o cambio de tamaño, según el alcance de los cambios.

[NOTE]
====
Cuando se inicializa o cambia el tamaño de las cuotas en un volumen, se activan las reglas de cuota en la política de cuotas que está actualmente asignada a la SVM.

====