---
permalink: volumes/quotas-special-windows-groups-concept.html 
sidebar: sidebar 
keywords: how quotas work, special windows groups 
summary: Hay varios grupos especiales de Windows que procesan cuotas de forma diferente a otros grupos de Windows. Debe comprender cómo se aplican las cuotas a estos grupos especiales. 
---
= Cómo funcionan las cuotas con grupos especiales de Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay varios grupos especiales de Windows que procesan cuotas de forma diferente a otros grupos de Windows. Debe comprender cómo se aplican las cuotas a estos grupos especiales.

[NOTE]
====
ONTAP no admite cuotas de grupos basadas en los ID de grupos de Windows. Si especifica un identificador de grupo de Windows como destino de cuota, la cuota se considera una cuota de usuario.

====
.Todos
Cuando el destino de cuota es el grupo Todos, un archivo con una ACL que muestra el propietario Todos se cuenta bajo el SID para Todos.

.BUILTIN\Administrators
Cuando el destino de cuota es el grupo BUILTIN\Administrators, la entrada se considera una cuota de usuario y se utiliza solo para el seguimiento. No puede imponer restricciones a BUILTIN\Administrators. Si un miembro de BUILTIN\Administrators crea un archivo, el archivo es propiedad de BUILTIN\Administrators y se cuenta bajo el SID para BUILTIN\Administrators (no el SID personal del usuario).
