---
permalink: volumes/quota-reports-policy-rule-show-command-concept.html 
sidebar: sidebar 
keywords: when to use, volume quota policy rule show, volume quota report, commands 
summary: '"mostrar regla de política de cuota de volumen" muestra rápidamente las reglas de cuota configuradas mientras que el "informe de cuota de volumen" muestra las cuotas aplicadas y el uso de recursos.' 
---
= Cuándo se deben usar los comandos show de la regla de política de cuota de volumen y los comandos volume quota report
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aunque ambos comandos muestran información acerca de las cuotas, el `volume quota policy rule show` muestra rápidamente las reglas de cuota configuradas mientras `volume quota report` comando, que consume más tiempo y recursos, muestra las cuotas forzadas y el uso de recursos.

La `volume quota policy rule show` el comando es útil con los siguientes fines:

* Compruebe la configuración de las reglas de cuota antes de activarlas
+
Este comando muestra todas las reglas de cuota configuradas independientemente de si se han inicializado o cambiado el tamaño de las cuotas.

* Vea rápidamente las reglas de cuotas sin afectar a los recursos del sistema
+
Como no muestra el uso de disco y archivo, este comando no consume tanto recursos como un informe de cuota.

* Muestra las reglas de cuotas en una política de cuotas que no está asignada a la SVM.


Obtenga más información sobre `volume quota policy rule show` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-policy-rule-show.html["Referencia de comandos de la ONTAP"^].

La `volume quota report` el comando es útil con los siguientes fines:

* Ver cuotas forzadas, incluidas las cuotas derivadas
* Vea el espacio en disco y el número de archivos utilizados por cada cuota en efecto, incluidos los destinos afectados por las cuotas derivadas
+
(Para las cuotas predeterminadas, el uso aparece como "0" porque se realiza un seguimiento del uso con respecto a la cuota derivada resultante).

* Determine qué límites de cuota afectan al momento en que se permitirá la escritura en un archivo
+
Añada el `-path` parámetro de la `volume quota report` comando.



[NOTE]
====
El informe de cuotas es una operación que requiere muchos recursos. Si la ejecuta en muchos volúmenes de FlexVol en el clúster, es posible que tarde mucho tiempo en completarse. Una forma más eficaz sería ver el informe de cuotas de un volumen concreto de una SVM.

====
Obtenga más información sobre `volume quota report` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-report.html["Referencia de comandos de la ONTAP"^].
