---
permalink: volumes/quotas-applied-concept.html 
sidebar: sidebar 
keywords: quotas, how quotas are applied 
summary: Comprender cómo se aplican las cuotas le permite configurar las cuotas correctamente y definir los límites esperados. 
---
= Cómo se aplican las cuotas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Comprender cómo se aplican las cuotas le permite configurar las cuotas correctamente y definir los límites esperados.

Cada vez que se intenta crear un archivo o escribir datos en un archivo de un volumen de FlexVol con cuotas habilitadas, se comprueban los límites de cuotas antes del avance de la operación. Si la operación supera el límite de disco o el límite de archivos, se impedirá la operación.

Los límites de cuota se comprueban en el siguiente orden:

. La cuota de árbol para ese qtree (esta comprobación no es relevante si el archivo se está creando o escribiendo en qtree0).
. La cuota de usuario del usuario al que pertenece el archivo en el volumen
. La cuota de grupo del grupo al que pertenece el archivo en el volumen
. La cuota de usuario del usuario al que pertenece el archivo en el qtree (esta comprobación no es relevante si el archivo se crea o se escribe en qtree0).
. La cuota de grupo del grupo al que pertenece el archivo en el qtree (esta comprobación no es relevante si el archivo se crea o se escribe en qtree0).


Puede que la cuota con el límite más pequeño no sea la que se supere primero. Por ejemplo, si una cuota de usuario para el volumen vol1 es 100 GB, Además, la cuota de usuario para el segundo qtree que contiene el volumen vol1 es de 20 GB. Se podría llegar al límite de volumen primero si ese usuario ya ha escrito más de 80 GB de datos en el volumen vol1 (pero fuera del segundo trimestre del qtree).

.Información relacionada
* link:../volumes/quotas-applied-root-user-concept.html["Cómo se aplican las cuotas al usuario raíz"]
* link:../volumes/quotas-applied-users-multiple-ids-concept.html["Cómo se aplican las cuotas a los usuarios con múltiples ID"]

