---
permalink: volumes/quotas-applied-users-multiple-ids-concept.html 
sidebar: sidebar 
keywords: how, quotas are applied, users, multiple ids 
summary: Un usuario puede estar representado por varios ID. Puede configurar una única cuota de usuario para dicho usuario especificando una lista de ID como destino de cuota. Un archivo que pertenece a cualquiera de estos ID está sujeto a la restricción de la cuota de usuario. 
---
= Cómo se aplican las cuotas a los usuarios con múltiples ID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un usuario puede estar representado por varios ID. Puede configurar una única cuota de usuario para dicho usuario especificando una lista de ID como destino de cuota. Un archivo que pertenece a cualquiera de estos ID está sujeto a la restricción de la cuota de usuario.

Supongamos que un usuario tiene el UID de UNIX 20 y los Id corp\john_smith de Windows y engineering\jsmith. Para este usuario, puede especificar una cuota en la que el destino de cuota sea una lista de UID e Id. De Windows. Cuando este usuario escribe en el sistema de almacenamiento, se aplica la cuota especificada, independientemente de si la escritura se origina en UID 20, corp\john_smith o engineering\jsmith.

[NOTE]
====
Las entradas de archivos de cuota independientes se consideran destinos independientes, incluso si los ID pertenecen al mismo usuario. Por ejemplo, para el mismo usuario puede especificar una cuota que limite el UID 20 a 1 GB de espacio en disco y otra cuota que limita corp\john_smith a 2 GB de espacio en disco, aunque ambos ID representen al mismo usuario. ONTAP aplica cuotas a UID 20 y corp\john_smith por separado.

En este caso, no se aplican límites a engineering\jsmith, aunque se aplican límites a los demás ID utilizados por el mismo usuario.

====