---
permalink: volumes/recommended-volume-lun-config-combinations-concept.html 
sidebar: sidebar 
keywords: recommended, volume, file, lun configuration, combinations 
summary: Existen combinaciones específicas de configuraciones de volumen y archivo de FlexVol o LUN que puede utilizar, en función de sus requisitos de aplicación y administración. Comprender los beneficios y los costos de estas combinaciones puede ayudarlo a determinar la combinación adecuada de configuración de volúmenes y LUN para su entorno. 
---
= Información general de las combinaciones de configuración de volúmenes y archivos o LUN recomendadas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existen combinaciones específicas de configuraciones de volumen y archivo de FlexVol o LUN que puede utilizar, en función de sus requisitos de aplicación y administración. Comprender los beneficios y los costos de estas combinaciones puede ayudarlo a determinar la combinación adecuada de configuración de volúmenes y LUN para su entorno.

Se recomiendan las siguientes combinaciones de configuración de volúmenes y LUN:

* Archivos reservados de espacio o LUN con aprovisionamiento de volumen grueso
* Archivos sin espacio reservado o LUN con thin provisioning de volumen
* Archivos reservados de espacio o LUN con aprovisionamiento de volumen grueso


Puede utilizar thin provisioning SCSI en sus LUN junto con cualquiera de estas combinaciones de configuración.



== Archivos reservados de espacio o LUN con aprovisionamiento de volumen grueso

*Beneficios:*

* Se garantizan todas las operaciones de escritura en los archivos con espacio reservado; no se producen errores debido a la falta de espacio.
* No existen restricciones sobre las tecnologías de eficiencia del almacenamiento y protección de datos en el volumen.


*Costos y limitaciones:*

* Debe reservar espacio suficiente desde el agregado hacia delante para admitir el volumen considerablemente aprovisionado.
* El espacio es igual al doble del tamaño de la LUN se asigna desde el volumen en el momento de creación de la LUN.




== Archivos sin espacio reservado o LUN con thin provisioning de volumen

*Beneficios:*

* No existen restricciones sobre las tecnologías de eficiencia del almacenamiento y protección de datos en el volumen.
* El espacio se asigna solo como se utiliza.


*Costos y restricciones:*

* No se garantizan las operaciones de escritura; pueden fallar si el volumen se queda sin espacio libre.
* Debe gestionar eficazmente el espacio libre del agregado para evitar que el agregado se quede sin espacio libre.




== Archivos reservados de espacio o LUN con aprovisionamiento de volumen grueso

*Beneficios:*

Se reserva menos espacio inicial que para el aprovisionamiento de volúmenes gruesos y se ofrece una garantía de escritura de mejor esfuerzo.

*Costos y restricciones:*

* Las operaciones de escritura pueden fallar con esta opción.
+
Puede mitigar este riesgo equilibrando correctamente el espacio libre en el volumen frente a la volatilidad de los datos.

* No puede confiar en la retención de objetos de protección de datos como copias Snapshot, archivos FlexClone y LUN.
* No se pueden utilizar funcionalidades de eficiencia del almacenamiento con uso compartido de bloques de ONTAP que no se pueden eliminar automáticamente, incluida la deduplicación, la compresión y la descarga ODX/copia.

