---
permalink: volumes/rehost-volume-another-svm-task.html 
sidebar: sidebar 
keywords: rehost, volume, from one SVM to another SVM 
summary: Una operación de realojamiento de volúmenes permite reasignar un volumen NAS o SAN de una SVM a otra SVM sin necesidad de una copia SnapMirror. 
---
= Prepárese para realojar un volumen de una SVM a otra
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una operación de realojamiento de volúmenes permite reasignar un volumen NAS o SAN de una SVM a otra SVM sin necesidad de una copia SnapMirror. El procedimiento exacto de rehost depende del protocolo de acceso de cliente utilizado y del tipo de volumen. El realojamiento de volúmenes es una operación disruptiva para el acceso a datos y la gestión de volúmenes.

Para poder volver a alojar un volumen de una SVM a otra, deben cumplirse las siguientes condiciones:

* El volumen debe estar en línea.
* Protocolo SAN o NAS
+
Para el protocolo NAS, el volumen debe estar desmontado.

* Si el volumen está en una relación de SnapMirror, debe eliminarse o romperse la relación antes de volver a alojar el volumen.
+
Es posible volver a sincronizar la relación de SnapMirror una vez que la operación de realojamiento del volumen.


