---
permalink: volumes/rehost-volume-another-svm-task.html 
sidebar: sidebar 
keywords: rehost, volume, from one SVM to another SVM 
summary: 'El realojamiento de volúmenes le permite reasignar volúmenes NAS o SAN de una máquina virtual de almacenamiento (SVM, antes denominada Vserver) a otra SVM sin necesidad de realizar una copia SnapMirror. Los procedimientos de realojamiento de volúmenes dependen del tipo de protocolo y el tipo de volumen. El realojamiento de volúmenes es una operación disruptiva para el acceso a datos y la gestión de volúmenes.' 
---
= Vuelva a alojar un volumen de una SVM a otra información general de SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El realojamiento de volúmenes le permite reasignar volúmenes NAS o SAN de una máquina virtual de almacenamiento (SVM, antes denominada Vserver) a otra SVM sin necesidad de realizar una copia SnapMirror. Los procedimientos de realojamiento de volúmenes dependen del tipo de protocolo y el tipo de volumen. El realojamiento de volúmenes es una operación disruptiva para el acceso a datos y la gestión de volúmenes.

.Antes de empezar
Se deben cumplir varias condiciones para poder volver a alojar un volumen de una SVM a otra:

* El volumen debe estar en línea.
* Protocolos: SAN o NAS
+
Para el protocolo NAS, el volumen debe estar desmontado.

* Si el volumen está en una relación de SnapMirror, debe eliminarse o romperse la relación antes de volver a alojar el volumen.
+
Es posible volver a sincronizar la relación de SnapMirror una vez que la operación de realojamiento del volumen.


