---
permalink: volumes/reinitialize-quotas-after-changes-task.html 
sidebar: sidebar 
keywords: reinitialize, quotas, after making, extensive, changes 
summary: Después de realizar cambios importantes en las definiciones de cuotas existentes, debe volver a inicializar las cuotas en todos los volúmenes afectados. 
---
= Reinicializar las cuotas después de realizar cambios extensos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de realizar cambios importantes en las definiciones de cuotas existentes, debe volver a inicializar las cuotas en todos los volúmenes afectados. Un ejemplo de este tipo de cambio es agregar o suprimir cuotas para destinos que no tienen cuotas aplicadas.

.Acerca de esta tarea
Tiene una máquina virtual de almacenamiento (SVM) con cuotas forzadas y desea realizar cambios que requieran una reinicialización completa de las cuotas.

.Pasos
. Utilice `vserver show` el comando con `-instance` el parámetro para determinar el nombre de la política que está actualmente asignada a la SVM.
. Modifique las reglas de cuota realizando cualquiera de las siguientes acciones:
+
[cols="2*"]
|===
| Si desea... | Realice lo siguiente... 


 a| 
Crear nuevas reglas de cuota
 a| 
Utilice `volume quota policy rule create` el comando



 a| 
Modifique la configuración de las reglas de cuota existentes
 a| 
Utilice `volume quota policy rule modify` el comando



 a| 
Eliminar reglas de cuota existentes
 a| 
Utilice `volume quota policy rule delete` el comando

|===
. Utilice `volume quota policy rule show` el comando para comprobar que las reglas de cuota están configuradas correctamente.
. Vuelva a inicializar las cuotas en cada volumen en el que haya modificado las cuotas desactivando las cuotas y, a continuación, activando las cuotas para dichos volúmenes.
+
.. Utilice `volume quota off` el comando en cada volumen afectado para desactivar las cuotas en ese volumen.
.. Utilice `volume quota on` el comando en cada volumen afectado para activar cuotas en ese volumen.
+
[NOTE]
====
Debe asegurarse de esperar unos cinco minutos para volver a activar las cuotas en cada volumen afectado, ya que intentar activarlas casi de inmediato después de ejecutar el `volume quota off` comando puede generar errores.

Como alternativa, es posible ejecutar los comandos para volver a inicializar las cuotas de un volumen desde el nodo que contiene el volumen en particular.

====
+
Puede supervisar el proceso de inicialización de cualquiera de las siguientes maneras:

+
*** Cuando utilice el `volume quota on` comando, puede agregar el `-foreground` parámetro para ejecutar la cuota en el trabajo en primer plano. (De forma predeterminada, el trabajo se ejecuta en segundo plano).
+
Cuando el trabajo se ejecuta en segundo plano, puede supervisar su progreso con el `job show` comando.

*** Puede utilizar `volume quota show` el comando para supervisar el estado de la inicialización de cuota.




. Utilice el `volume quota show -instance` comando para comprobar si hay errores de inicialización, como reglas de cuota que no se han podido inicializar.
. Utilice `volume quota report` el comando para mostrar un informe de cuotas de modo que pueda asegurarse de que las cuotas aplicadas coincidan con sus expectativas.


.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/vserver-show.html["se muestra vserver"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+quota+policy+rule["regla de política de cuota de volumen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+quota["cuota de volumen"^]
* link:https://docs.netapp.com/us-en/ontap-cli/job-show.html["exposición de trabajos"^]

