---
permalink: volumes/relocate-root-volumes-new-aggregates-task.html 
sidebar: sidebar 
keywords: relocate, root volumes, new aggregates 
summary: El procedimiento de reemplazo raíz migra el agregado raíz actual a otro conjunto de discos sin interrupciones. 
---
= Reubicar un volumen raíz a nuevos agregados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El procedimiento de reemplazo raíz migra el agregado raíz actual a otro conjunto de discos sin interrupciones. Es posible que deba realizarlo como parte de un proceso de reemplazo de disco o de mantenimiento preventivo.

.Acerca de esta tarea
Puede cambiar la ubicación del volumen raíz a un nuevo agregado en las siguientes situaciones:

* Cuando los agregados raíz no se encuentran en el disco que prefiere
* Cuando desee reorganizar los discos conectados al nodo
* Cuando realice el reemplazo de una bandeja de bandejas de discos EOS


.Pasos
. Reubicar el agregado raíz:
+
`system node migrate-root -node node_name -disklist disk_list -raid-type raid_type`

+
** *-nodo*
+
Especifica el nodo que posee el agregado raíz que desea migrar.

** *-disklist*
+
Especifica la lista de discos en los que se creará el nuevo agregado raíz. Todos los discos deben ser repuestos y ser propiedad del mismo nodo. El número mínimo de discos necesario depende del tipo de RAID.

** *-raid-type*
+
Especifica el tipo de RAID del agregado raíz. El valor predeterminado es `raid-dp`. Este es el único tipo admitido en el modo avanzado.



. Supervise el progreso del trabajo:
+
`job show -id jobid -instance`



.Resultados
Si todas las comprobaciones previas se realizan correctamente, el comando inicia un trabajo de reemplazo de volumen raíz y sale del mismo.
