---
permalink: volumes/run-efficiency-operations-manual-task.html 
sidebar: sidebar 
keywords: starting deduplication manually, starting data compression manually, efficiency, run 
summary: Puede ejecutar operaciones de eficiencia manualmente en un volumen con el comando volume Efficiency start. 
---
= Ejecute operaciones de eficiencia manualmente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ejecutar operaciones de eficiencia manualmente en un volumen mediante el `volume efficiency start` comando.

.Lo que necesitará
Según la operación de eficiencia que desee ejecutar manualmente, debe tener activada la deduplicación o tanto la compresión de datos como la deduplicación en un volumen.

.Acerca de esta tarea
Si se activan la deduplicación y la compresión de datos en un volumen, la compresión de datos se ejecuta inicialmente, seguida por la deduplicación.

La deduplicación es un proceso en segundo plano que consume recursos del sistema mientras se está ejecutando. Si los datos no cambian con frecuencia en un volumen, es mejor ejecutar la deduplicación con menos frecuencia. Varias operaciones de deduplicación simultáneas que se ejecutan en un sistema de almacenamiento, generan un mayor consumo de recursos del sistema.

Puede ejecutar un máximo de ocho operaciones simultáneas de deduplicación o compresión de datos por nodo. Si se programa alguna operación de mayor eficiencia, las operaciones se pondrán en cola.

.Paso
. Utilice la `volume efficiency start` comando para iniciar la operación de eficiencia en un volumen.


.Ejemplo
El siguiente comando permite iniciar manualmente solo la deduplicación o la compresión de datos seguida de la deduplicación en el volumen Vola:

`volume efficiency start -vserver vs1 -volume VolA`
