---
permalink: volumes/run-efficiency-operations-depending-new-data-task.html 
sidebar: sidebar 
keywords: run deduplication based on new data, run data compression based on new data, efficiency operation, written 
summary: 'Es posible modificar la programación de las operaciones de eficiencia para ejecutar la deduplicación o la compresión de datos cuando la cantidad de bloques nuevos escritos en el volumen después de que la operación de eficiencia anterior (realizada manualmente o programada) supere un porcentaje de umbral especificado.' 
---
= Ejecute operaciones de eficiencia en función de la cantidad de datos nuevos escritos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible modificar la programación de las operaciones de eficiencia para ejecutar la deduplicación o la compresión de datos cuando la cantidad de bloques nuevos escritos en el volumen después de que la operación de eficiencia anterior (realizada manualmente o programada) supere un porcentaje de umbral especificado.

.Acerca de esta tarea
Si la `schedule` opción establecida en `auto`, la operación de eficacia programada se ejecuta cuando la cantidad de datos nuevos supera el porcentaje especificado. El valor del umbral predeterminado es de 20 %. Este valor de umbral es el porcentaje del número total de bloques ya procesados por la operación de eficiencia.

.Paso
. Utilice la `volume efficiency modify` con el `auto@num` opción para modificar el valor del porcentaje del umbral.
+
`num` es un número de dos dígitos para especificar el porcentaje.



.Ejemplo
El siguiente comando modifica el valor del porcentaje del umbral al 30 % para el volumen Vola:

`volume efficiency modify -vserver vs1 -volume -VolA -schedule auto@30`
