---
permalink: volumes/run-efficiency-operations-manual-task.html 
sidebar: sidebar 
keywords: starting deduplication manually, starting data compression manually, efficiency, run, sequential packing 
summary: Las operaciones de eficiencia se pueden ejecutar de forma manual en un volumen. Puede hacerlo cuando la programación de operaciones de eficiencia no sea apropiada. 
---
= Ejecute una operación de eficiencia manualmente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las operaciones de eficiencia se pueden ejecutar de forma manual en un volumen. Puede hacerlo cuando la programación de operaciones de eficiencia no sea apropiada.

.Antes de empezar
Según la operación de eficiencia que desee ejecutar manualmente, debe tener activada la deduplicación o tanto la compresión de datos como la deduplicación en un volumen.

.Acerca de esta tarea
Esta operación se lleva a cabo con `volume efficiency start` el comando. Cuando se activa la eficiencia de almacenamiento sensible a la temperatura en un volumen, se ejecuta inicialmente la deduplicación y, a continuación, la compresión de datos.

La deduplicación es un proceso en segundo plano que consume recursos del sistema mientras se está ejecutando. Si los datos no cambian con frecuencia en un volumen, es mejor ejecutar la deduplicación con menos frecuencia. Varias operaciones de deduplicación simultáneas que se ejecutan en un sistema de almacenamiento, generan un mayor consumo de recursos del sistema.

Puede ejecutar un máximo de ocho operaciones simultáneas de deduplicación o compresión de datos por nodo. Si se programa alguna operación de mayor eficiencia, las operaciones se pondrán en cola.

A partir de ONTAP 9.13.1, si la eficiencia de almacenamiento sensible a la temperatura está habilitada en un volumen, puede ejecutar la eficiencia del volumen en los datos existentes para aprovechar el empaquetado secuencial y mejorar aún más la eficiencia del almacenamiento.



== Ejecute la eficiencia manualmente

.Pasos
. Inicie la operación de eficiencia en un volumen: `volume efficiency start`


.Ejemplo
+ El siguiente comando le permite iniciar manualmente solo la deduplicación o la deduplicación seguida de compresión lógica y compresión de contenedores en el volumen Vola

+

[listing]
----
volume efficiency start -vserver vs1 -volume VolA
----


== Volver a comprimir datos existentes

Para aprovechar el paquete de datos secuencial introducido en ONTAP 9.13.1 en volúmenes con eficiencia de almacenamiento sensible a la temperatura habilitada, puede volver a montar los datos existentes. Para utilizar este comando, debe estar en modo de privilegio avanzado.

.Pasos
. Establezca el nivel de privilegio: `set -privilege advanced`
. Volver a comprimir datos existentes: `volume efficiency inactive-data-compression start -vserver _vserver_name_ -volume _volume_name_ -scan-mode extended_recompression`


.Ejemplo
[listing]
----
volume efficiency inactive-data-compression start -vserver vs1 -volume vol1 -scan-mode extended_recompression
----
.Información relacionada
* link:run-efficiency-operations-manual-existing-data-task.html["Ejecute operaciones de eficiencia manualmente en datos existentes"]

