---
permalink: volumes/run-efficiency-operations-manual-existing-data-task.html 
sidebar: sidebar 
keywords: run, efficiency, operations, manually, existing, data 
summary: Puede ejecutar las operaciones de eficiencia manualmente en los datos que hay en volúmenes de eficiencia del almacenamiento sin sensibilidad a la temperatura antes de habilitar la deduplicación, la compresión de datos o la compactación de datos con versiones de ONTAP anteriores a ONTAP 9.8. Se pueden ejecutar estas operaciones mediante el comando volume Efficiency start -scan-old-data. 
---
= Ejecute operaciones de eficiencia manualmente en datos existentes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ejecutar las operaciones de eficiencia manualmente en los datos que hay en volúmenes de eficiencia del almacenamiento sin sensibilidad a la temperatura antes de habilitar la deduplicación, la compresión de datos o la compactación de datos con versiones de ONTAP anteriores a ONTAP 9.8. Puede ejecutar estas operaciones mediante la `volume efficiency start -scan-old-data` comando.

.Acerca de esta tarea
 `-compression`La opción no funciona con `-scan-old-data` volúmenes de eficiencia de almacenamiento sensibles a la temperatura. La compresión de datos inactivos se ejecuta automáticamente en los datos preexistentes para los volúmenes de eficiencia del almacenamiento sensibles a la temperatura en ONTAP 9,8 y versiones posteriores.

Si solo activa la deduplicación en un volumen, la deduplicación se ejecuta en los datos. Si habilita la deduplicación, la compresión de datos y la compactación de datos en un volumen, primero se ejecuta la compresión de datos, seguida de la deduplicación y la compactación de datos.

Al ejecutar la compresión de datos en los datos existentes, de forma predeterminada, la operación de compresión de datos omite los bloques de datos compartidos por la deduplicación y los bloques de datos que quedan bloqueados por las copias Snapshot. Si decide ejecutar compresión de datos en bloques compartidos, la optimización se desactiva y se captura la información de huella digital para compartirla de nuevo. Es posible cambiar el comportamiento predeterminado de la compresión de datos al comprimir los datos existentes.

Puede ejecutar un máximo de ocho operaciones de deduplicación, compresión de datos o compactación de datos simultáneamente por nodo. Las operaciones restantes se ponen en cola.

[NOTE]
====
La compresión de postprocesamiento no se ejecuta en plataformas AFF. Se genera un mensaje de EMS para informarle de que esta operación se ha omitido.

====
.Paso
. Utilice la `volume efficiency start -scan-old-data` comando para ejecutar manualmente la deduplicación, la compresión o la compactación de datos en los datos existentes.
+
El siguiente comando permite ejecutar estas operaciones manualmente en los datos existentes en el volumen Vola:

+
`volume efficiency start -vserver vs1 -volume VolA -scan-old-data true [-compression | -dedupe | -compaction ] true`


