---
permalink: volumes/san-volumes-concept.html 
sidebar: sidebar 
keywords: understand, san volumes 
summary: Conocer opciones básicas para el aprovisionamiento de volúmenes de SAN y cómo cada opción gestiona los requisitos de espacio de volúmenes y de espacio para las tecnologías de uso compartido de bloques de ONTAP. 
---
= Información general sobre aprovisionamiento de volúmenes SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ofrece varias opciones básicas para el aprovisionamiento de volúmenes de SAN. Cada opción utiliza un método diferente para gestionar los requisitos de espacio de volumen y espacio para las tecnologías de uso compartido de bloques de ONTAP. Debe comprender cómo funciona cada opción de aprovisionamiento para poder elegir la mejor opción para su entorno.

[TIP]
====
No se recomienda colocar los LUN de SAN y recursos compartidos NAS en el mismo FlexVol volume. En su lugar, debería aprovisionar volúmenes FlexVol independientes para los LUN de SAN y los recursos compartidos NAS. De este modo, se simplifica la gestión y las puestas en marcha de replicación. También es paralelo a la forma en que los volúmenes FlexVol son compatibles en Active IQ Unified Manager (anteriormente OnCommand Unified Manager).

====


== Aprovisionamiento ligero para volúmenes

Cuando se crea un volumen con Thin Provisioning, ONTAP no reserva ningún espacio adicional cuando se crea el volumen. A medida que se escriben datos en el volumen, el volumen solicita el almacenamiento que necesita del agregado para acomodar la operación de escritura. El uso de volúmenes con aprovisionamiento ligero le permite comprometer en exceso su agregado, lo que introduce la posibilidad de que el volumen no pueda asegurar el espacio que necesita cuando el agregado se queda sin espacio libre.

Para crear una FlexVol volume con thin provisioning, se debe establecer `-space-guarantee` la opción en `none`.



== Aprovisionamiento grueso para volúmenes

Cuando se crea un volumen con aprovisionamiento grueso, ONTAP reserva suficiente almacenamiento del agregado para garantizar que cualquier bloque del volumen se pueda escribir en cualquier momento. Cuando configura un volumen para utilizar este tipo de aprovisionamiento, puede emplear cualquiera de las funcionalidades de eficiencia del almacenamiento de ONTAP, como la compresión y la deduplicación, para compensar los mayores requisitos de almacenamiento inicial.

Puede crear un FlexVol volume con aprovisionamiento grueso definiendo su `-space-slo` opción (objetivo de nivel de servicio) en `thick`.



== Aprovisionamiento para volúmenes semigruesos

Cuando se crea un volumen que utiliza aprovisionamiento grueso, ONTAP establece un espacio de almacenamiento aparte del agregado para tener en cuenta el tamaño del volumen. Si el volumen se está quedando sin espacio libre porque las tecnologías de uso compartido de bloques utilizan los bloques, ONTAP se esfuerza por eliminar los objetos de datos de protección (snapshots y archivos de FlexClone y LUN) para liberar el espacio que conservan. Siempre que ONTAP pueda eliminar los objetos de datos de protección con la rapidez suficiente como para responder al ritmo del espacio requerido para las sobrescrituras, las operaciones de escritura siguen teniendo éxito. Esto se denomina «mejor esfuerzo».

[NOTE]
====
No puede emplear tecnologías de eficiencia del almacenamiento como deduplicación, compresión y compactación en un volumen que utiliza aprovisionamiento de grosor medio.

====
Puede crear una FlexVol volume con aprovisionamiento semigrueso estableciendo su `-space-slo` opción (objetivo de nivel de servicio) en `semi-thick`.



== Utilice con archivos y LUN reservados en el espacio

Un archivo o LUN con reserva de espacio es uno para el cual se asigna el almacenamiento cuando se crea. Históricamente, NetApp ha utilizado el término «LUN aprovisionada mediante thin provisioning» para indicar una LUN para la que se ha deshabilitado la reserva de espacio (LUN sin reservar espacio).

[NOTE]
====
Los archivos sin espacio reservado no se denominan normalmente «ficheros con thin provisioning».

====
En la tabla siguiente se resumen las principales diferencias en cómo pueden utilizarse las tres opciones de aprovisionamiento de volúmenes con archivos y LUN con espacio reservado:

[cols="5*"]
|===
| Aprovisionamiento de volúmenes | Reserva de espacio de archivos/LUN | Sobrescrituras | Datos de protección 2 | Eficiencia del almacenamiento 3 


 a| 
Grueso
 a| 
Compatible
 a| 
Garantizado 1
 a| 
Garantizado
 a| 
Compatible



 a| 
Fino
 a| 
Sin efecto
 a| 
Ninguno
 a| 
Garantizado
 a| 
Compatible



 a| 
Semi-grueso
 a| 
Compatible
 a| 
Mejor esfuerzo 1
 a| 
El mejor esfuerzo
 a| 
No admitido

|===
*Notas*

. La capacidad para garantizar sobrescrituras o proporcionar una garantía de sobrescritura de mejor esfuerzo requiere que la reserva de espacio esté habilitada en la LUN o el archivo.
. Los datos de protección incluyen snapshots y archivos FlexClone y LUN marcados para su eliminación automática (clones de backup).
. La eficiencia del almacenamiento incluye deduplicación, compresión, cualquier archivo FlexClone y LUN no marcados para su eliminación automática (clones activos), y subarchivos FlexClone (utilizados para la descarga de copia).




== Compatibilidad con LUN aprovisionados mediante thin provisioning de SCSI

ONTAP admite LUN T10 SCSI con thin provisioning, así como LUN con thin provisioning de NetApp. El thin provisioning SCSI T10 permite que las aplicaciones host admitan funciones SCSI como la reclamación de espacio de LUN y las funcionalidades de supervisión de espacio de LUN para entornos de bloques. El thin provisioning SCSI T10 debe ser compatible con su software host SCSI.

 `space-allocation`La configuración de ONTAP se utiliza para habilitar/deshabilitar la compatibilidad con thin provisioning de T10 en una LUN. Se utiliza `space-allocation enable` la configuración ONTAP para habilitar el thin provisioning de SCSI T10 en una LUN.

 `[-space-allocation {enabled|disabled}]`El comando en el Manual de referencia de comandos de ONTAP tiene más información para habilitar/deshabilitar la compatibilidad con thin provisioning de T10 y habilitar thin provisioning de SCSI T10 en una LUN.

.Información relacionada
* https://docs.netapp.com/us-en/ontap-cli["Referencia de comandos del ONTAP"^]

