---
permalink: volumes/setup-quotas-svm-task.html 
sidebar: sidebar 
keywords: set up, quotas on svm 
summary: 'Para configurar cuotas en una nueva máquina virtual de almacenamiento (SVM, antes conocida como Vserver), debe crear una política de cuotas, agregar reglas de política de cuotas a la política, asignar la política a la SVM e inicializar cuotas en cada volumen FlexVol de la SVM.' 
---
= Configurar cuotas en un SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para configurar cuotas en una nueva máquina virtual de almacenamiento (SVM, antes conocida como Vserver), debe crear una política de cuotas, agregar reglas de política de cuotas a la política, asignar la política a la SVM e inicializar cuotas en cada volumen FlexVol de la SVM.

.Pasos
. Utilice la `vserver show` con el `-instance` Opción para mostrar el nombre de la política de cuota predeterminada que se creó automáticamente al crear la SVM.
+
Si no se especificó un nombre cuando se creó la SVM, el nombre es "predeterminado". También puede utilizar el `vserver quota policy rename` para asignar un nombre a la directiva predeterminada.

+
[NOTE]
====
También puede crear una nueva directiva con el `volume quota policy create` comando.

====
. Utilice la `volume quota policy rule create` Comando para crear _any_ de las siguientes reglas de cuota para cada volumen de la SVM:
+
** Reglas de cuota predeterminadas para todos los usuarios
** Reglas de cuota explícitas para usuarios específicos
** Reglas de cuota predeterminadas para todos los grupos
** Reglas explícitas de cuotas para grupos específicos
** Reglas de cuota predeterminadas para todos los qtrees
** Reglas de cuota explícitas para qtrees específicos


. Utilice la `volume quota policy rule show` comando para comprobar que las reglas de cuota están configuradas correctamente.
. Si está trabajando en una nueva directiva, utilice la `vserver modify` Comando para asignar la nueva política a la SVM.
. Utilice la `volume quota on` Comando para inicializar las cuotas de cada volumen en la SVM.
+
Puede supervisar el proceso de inicialización de las siguientes maneras:

+
** Cuando utilice la `volume quota on` puede agregar el `-foreground` parámetro para ejecutar la cuota en el trabajo en primer plano. (De forma predeterminada, el trabajo se ejecuta en segundo plano).
+
Cuando el trabajo se ejecuta en segundo plano, puede supervisar su progreso mediante el `job show` comando.

** Puede utilizar el `volume quota show` comando para supervisar el estado de inicialización de la cuota.


. Utilice la `volume quota show -instance` comando para comprobar si hay errores de inicialización, como reglas de cuota que no se han podido inicializar.
. Utilice la `volume quota report` comando para mostrar un informe de cuotas de forma que pueda garantizar que las cuotas forzadas se ajustan a sus expectativas.

