---
permalink: volumes/snapshot-copies-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: how, snapshot copies, work, flexclone files, flexclone luns 
summary: Comprender la sinergia entre snapshots y archivos FlexClone y LUN de FlexClone, así como ciertas restricciones. 
---
= Cómo funcionan las instantáneas con archivos FlexClone y LUN de FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existe una sinergia entre las snapshots y los archivos FlexClone y las LUN de FlexClone. Si trabaja con estas tecnologías, debe tener en cuenta lo que es posible, así como las restricciones pertinentes.

.Creación de archivos y LUN FlexClone
Es posible crear un archivo FlexClone o un LUN de FlexClone a partir de una snapshot existente. La copia se basa en los archivos principales y en LUN principales contenidos en una FlexVol volume.

.Eliminar una copia de Snapshot
No puede eliminar manualmente una snapshot de la que se están creando archivos de FlexClone o LUN de FlexClone. La instantánea permanecerá bloqueada hasta que se complete el proceso de uso compartido de bloques en segundo plano. Si intenta eliminar una instantánea bloqueada, el sistema muestra un mensaje pidiéndole que vuelva a intentar la operación después de cierto tiempo. En este caso, debe continuar intentando volver a intentar la operación de eliminación. Podrá eliminar la instantánea una vez que se haya compartido el bloque.
