---
permalink: volumes/snapshot-copies-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: how, snapshot copies, work, flexclone files, flexclone luns 
summary: Puede crear archivos FlexClone y LUN FlexClone a partir de una copia snapshot existente de los archivos principales y LUN principales contenidos en un volumen FlexVol. 
---
= Cómo funcionan las copias snapshot con archivos FlexClone y LUN FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear archivos FlexClone y LUN FlexClone a partir de una copia snapshot existente de los archivos principales y LUN principales contenidos en un volumen FlexVol.

Sin embargo, no puede eliminar manualmente una copia snapshot desde la que se crean los archivos FlexClone o las LUN FlexClone hasta que finalice el proceso de uso compartido de bloques entre las entidades principal y clonado. La copia Snapshot permanece bloqueada hasta que se completa el proceso de uso compartido de bloques, lo que se produce en segundo plano. Por lo tanto, cuando se intenta eliminar una copia Snapshot bloqueada, el sistema muestra un mensaje en el que se le solicita volver a intentar la operación después de un tiempo. En esta situación, si desea eliminar manualmente la copia de Snapshot particular, debe seguir reintentando la operación de eliminación para que la copia de Snapshot se elimine una vez que se haya completado el uso compartido de bloque.
