---
permalink: volumes/space-reserved-luns-thick-provisioned-concept.html 
sidebar: sidebar 
keywords: configuration, settings, space-reserved, files, luns with thick-provisioned volumes 
summary: La configuración basada en volúmenes de aprovisionamiento grueso proporciona eficiencias de almacenamiento y no requiere que supervise activamente el espacio libre. 
---
= Opción de configuración para archivos reservados espacio o LUN con volúmenes aprovisionados con thick-Provisioning
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existen diferentes combinaciones de configuración de configuraciones de FlexVol volume y de archivo o LUN que puede utilizar. Esta combinación basada en volúmenes de aprovisionamiento grueso ofrece la posibilidad de utilizar tecnologías de eficiencia de almacenamiento y no requiere que supervise activamente el espacio libre, ya que se asigna suficiente espacio de antemano.

Las siguientes opciones de configuración son necesarias para configurar un archivo o LUN con espacio reservado en un volumen mediante el aprovisionamiento grueso:

[cols="2*"]
|===
| Ajuste del volumen | Valor 


 a| 
Garantizado
 a| 
Volumen



 a| 
Reserva fraccionaria
 a| 
100



 a| 
Reserva de Snapshot
 a| 
Cualquiera



 a| 
Eliminación automática de Snapshot
 a| 
Opcional



 a| 
Crecimiento automático
 a| 
Opcional; si está habilitado, el espacio libre del agregado debe supervisarse de forma activa.

|===
[cols="2*"]
|===
| Configuración de archivo o LUN | Valor 


 a| 
Reserva de espacio
 a| 
Activado

|===
.Información relacionada
* link:recommended-volume-lun-config-combinations-concept.html["Información general de las combinaciones de configuración de volúmenes y archivos o LUN recomendadas"]

