---
permalink: volumes/specify-windows-users-quotas-concept.html 
sidebar: sidebar 
keywords: how to, specify, windows users, for quotas 
summary: 'Puede especificar un usuario de Windows para una cuota utilizando uno de tres formatos: El nombre de Windows en formato anterior a Windows 2000, el SID o un archivo o directorio propiedad del SID del usuario.' 
---
= Cómo se especifican usuarios de Windows para las cuotas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede especificar un usuario de Windows para una cuota utilizando uno de tres formatos: El nombre de Windows en formato anterior a Windows 2000, el SID o un archivo o directorio propiedad del SID del usuario.

Para especificar un usuario de Windows para una cuota, puede utilizar uno de los siguientes formatos:

* El nombre de Windows en formato anterior a Windows 2000.
* El identificador de seguridad (SID), tal como muestra Windows en formato de texto, como S-1-5-32-544.
* Nombre de un archivo o directorio que tiene una ACL propiedad del SID de ese usuario.
+
[NOTE]
====
Si especifica un nombre de archivo o directorio, debe seleccionar un archivo o directorio que durará tanto como la cuenta de usuario permanezca en el sistema.

Para que ONTAP obtenga el SID de la ACL, la ACL debe ser válida.

Si el archivo o directorio existe en un qtree de estilo UNIX o si el sistema de almacenamiento utiliza el modo UNIX para la autenticación de usuarios, ONTAP aplica la cuota de usuario al usuario cuyo *UID*, no SID, coincide con el del archivo o directorio.

La especificación de un nombre de archivo o directorio para identificar a un usuario para una cuota no hace que ONTAP aplique una cuota a ese archivo o directorio.

====

