---
permalink: volumes/storage-limits-reference.html 
sidebar: sidebar 
keywords: storage limits 
summary: Hay límites para los objetos de almacenamiento que debe tener en cuenta a la hora de planificar y gestionar su arquitectura de almacenamiento. 
---
= Límites de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay límites para los objetos de almacenamiento que debe tener en cuenta a la hora de planificar y gestionar su arquitectura de almacenamiento.

Los límites a menudo dependen de la plataforma. Consulte la link:https://hwu.netapp.com/["Hardware Universe"^] para conocer los límites de su configuración específica.

Los límites se enumeran en las siguientes secciones:

* <<vollimits>>
* <<flexclone>>


Los límites de almacenamiento para Cloud Volumes ONTAP se documentan en la link:https://docs.netapp.com/us-en/cloud-volumes-ontap/["Notas de la versión de Cloud Volumes ONTAP"^].



== Límites de volumen

[cols="4*"]
|===
| Objeto de almacenamiento | Límite | Almacenamiento nativo | Cabinas de almacenamiento 


 a| 
*LUN de matriz*
 a| 
Tamaño mínimo del volumen raíz
 a| 
N.A.
 a| 
Depende del modelo



 a| 
*Archivos*
 a| 
Tamaño máximo
 a| 
16 TB
 a| 
16 TB



 a| 
Máximo por volumen 3
 a| 
Depende del tamaño del volumen, hasta 2000 millones
 a| 
Depende del tamaño del volumen, hasta 2000 millones



 a| 
*Volúmenes FlexClone*
 a| 
Profundidad de clonación jerárquica 4
 a| 
499
 a| 
499



 a| 
*Volúmenes FlexVol*
 a| 
Máximo por nodo 1
 a| 
Depende del modelo
 a| 
Depende del modelo



 a| 
Máximo por nodo por SVM 5
 a| 
Depende del modelo
 a| 
Depende del modelo



 a| 
Tamaño mínimo
 a| 
20 MB
 a| 
20 MB



 a| 
Tamaño máximo 1
 a| 
Depende del modelo
 a| 
Depende del modelo



 a| 
*Volúmenes FlexVol para cargas de trabajo primarias*
 a| 
Máximo por nodo 2
 a| 
Depende del modelo
 a| 
Depende del modelo



 a| 
*Volúmenes raíz FlexVol*
 a| 
Tamaño mínimo 1
 a| 
Depende del modelo
 a| 
Depende del modelo



 a| 
*LUN*
 a| 
Máximo por nodo 5
 a| 
Depende del modelo
 a| 
Depende del modelo



 a| 
Máximo por clúster 5
 a| 
Depende del modelo
 a| 
Depende del modelo



 a| 
Máximo por volumen 5
 a| 
Depende del modelo
 a| 
Depende del modelo



 a| 
Tamaño máximo
 a| 
16 TB
 a| 
16 TB



 a| 
*Qtrees*
 a| 
Máximo por volumen FlexVol
 a| 
4,995
 a| 
4,995



 a| 
*Copias Snapshot*
 a| 
Máximo por volumen 6
 a| 
255/1023
 a| 
255/1023



 a| 
*Volúmenes*
 a| 
Máximo por clúster para NAS
 a| 
12.000
 a| 
12.000



 a| 
Máximo por clúster con protocolos SAN configurados
 a| 
Depende del modelo
 a| 
Depende del modelo

|===
*Notas:*

. En ONTAP 9.3 y versiones anteriores, un volumen puede contener hasta 255 copias snapshot. A partir de la versión 9.4 de ONTAP, un volumen puede contener hasta 1023 copias snapshot.
. A partir de ONTAP 9.7, el número máximo admitido de volúmenes FlexVol en plataformas AFF con al menos 128 GB de memoria aumentó a 2,500 volúmenes FlexVol por nodo; sin embargo, solo 1,000 volúmenes por nodo pueden estar activos (cargas de trabajo principales) a la vez.
+
Para obtener información específica sobre la plataforma y detalles de soporte más recientes, consulte https://hwu.netapp.com/["Hardware Universe"^].

. 2 mil millones = 2 × 10 9
. La profundidad máxima de una jerarquía anidada de volúmenes FlexClone que se pueden crear a partir de un único volumen de FlexVol.
. Este límite se aplica solo en entornos SAN.
+
link:../san-config/index.html["CONFIGURACIÓN DE SAN"]

. Puede utilizar una puesta en marcha en cascada de SnapMirror para aumentar este límite.




== Límites de archivos y LUN de FlexClone

[cols="3*"]
|===
| Límite | Almacenamiento nativo | Cabinas de almacenamiento 


 a| 
**Máximo por archivo o LUN** 1
 a| 
32.767
 a| 
32.767



 a| 
*Máximo total de datos compartidos por volumen FlexVol*
 a| 
640 TB
 a| 
640 TB

|===
*Nota:*

. Si intenta crear más de 32,767 clones, ONTAP crea automáticamente una nueva copia física del archivo principal o LUN.
+
Este límite puede ser menor para volúmenes FlexVol que utilizan deduplicación.



.Información relacionada
https://www.netapp.com/cloud-services/cloud-manager/documentation/["Busque las notas de la versión de Cloud Volumes ONTAP"]
