---
permalink: volumes/track-quotas-concept.html 
sidebar: sidebar 
keywords: how, you, use, tracking, quotas 
summary: El seguimiento de las cuotas genera informes de uso de disco y archivo y no limita el uso de recursos. Cuando se utilizan las cuotas de seguimiento, la modificación de los valores de cuota resulta menos disruptiva, ya que puede cambiar el tamaño de las cuotas en lugar de desactivarlas y volver a ponerlas. 
---
= Cómo se utilizan las cuotas de seguimiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El seguimiento de las cuotas genera informes de uso de disco y archivo y no limita el uso de recursos. Cuando se utilizan las cuotas de seguimiento, la modificación de los valores de cuota resulta menos disruptiva, ya que puede cambiar el tamaño de las cuotas en lugar de desactivarlas y volver a ponerlas.

Para crear una cuota de seguimiento, se omiten los parámetros límite de disco y límite de archivos. Esto indica a ONTAP que supervise el uso de discos y archivos para ese destino a ese nivel (volumen o qtree) sin imponer límites. Las cuotas de seguimiento se indican en la salida de `show` comandos y el informe de cuotas con un guión ("-") para todos los límites.

También puede especificar una cuota de seguimiento _default_, que se aplica a todas las instancias del destino. Las cuotas de seguimiento predeterminadas le permiten realizar un seguimiento del uso de todas las instancias de un tipo de cuota (por ejemplo, todos los qtrees o todos los usuarios). Además, le permiten utilizar el cambio de tamaño en lugar de la reinicialización cuando desea que los cambios de cuota surtan efecto.

.Ejemplos
El siguiente archivo de cuotas muestra el seguimiento de las cuotas vigentes para un usuario, grupo y qtree específicos:

[listing]
----

#Quota target   type           disk files thold sdisk sfile
#-----------    ----           ---- ----- ----- ----- -----
kjones          user@/vol/vol1    -  -
eng1            group@/vol/vol1   -  -
proj1           tree@/vol/vol1    -  -
----
El siguiente archivo Quotas contiene las tres cuotas de seguimiento predeterminadas posibles (usuarios, grupos y qtrees):

[listing]
----

#Quota target   type           disk  files thold sdisk sfile
#-----------    ----           ----  ----- ----- ----- -----
*               user@/vol/vol1    -   -
*               group@/vol/vol1   -   -
*               tree@/vol/vol1    -   -
----