---
permalink: volumes/tree-quotas-concept.html 
sidebar: sidebar 
keywords: how, tree, quotas, work 
summary: Puede crear una cuota con un qtree como destino para limitar el tamaño del qtree de destino. Estas cuotas también se denominan cuotas de árbol. 
---
= Conoce las cuotas de árbol de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear una cuota con un qtree como destino para limitar el tamaño del qtree de destino. Estas cuotas también se denominan _tree Quotas_.


NOTE: También puede crear cuotas de usuario y de grupo para un qtree concreto. Además, las cuotas de un volumen FlexVol a veces son heredadas por los qtrees que contiene ese volumen.

Cuando se aplica una cuota a un qtree, el resultado es similar a una partición de disco, excepto que se puede cambiar el tamaño máximo del qtree en cualquier momento si se cambia la cuota. Cuando se aplica una cuota de árbol, ONTAP limita el espacio en disco y el número de archivos en el qtree, independientemente de sus propietarios. Ningún usuario, incluidos root y miembros del grupo BUILTIN\Administrators, puede escribir en el qtree si la operación de escritura hace que se supere la cuota de árbol.

El tamaño de la cuota no garantiza ninguna cantidad específica de espacio disponible. El tamaño de la cuota puede ser mayor que la cantidad de espacio libre disponible para el qtree. Puede usar el `volume quota report` comando para determinar la cantidad real de espacio disponible en el qtree.

Obtenga más información sobre `volume quota report` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-report.html["Referencia de comandos del ONTAP"^].



[[learn-how-ontap-user-and-group-quotas-work-with-qtrees]]
== Aprende cómo funcionan las cuotas de usuario y de grupo de ONTAP con qtrees

Las cuotas de árbol limitan el tamaño general del qtree. Para evitar que usuarios o grupos individuales consuman todo el qtree, debe especificar una cuota de usuario o de grupo para ese qtree.

.Ejemplo de cuota de usuario en un qtree
[%collapsible]
====
Supongamos que tiene las siguientes reglas de cuota:

[listing]
----
cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -       45MB
user   jsmith    ""      off          80MB        -       -        -       75MB
----
Observarás que un determinado usuario, kjones, está ocupando demasiado espacio en un qtree crítico, proj1, que reside en vol1. Puede restringir el espacio de este usuario agregando la siguiente regla de cuota:

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target "kjones" -qtree "proj1" -disk-limit 20m -threshold 15m

cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -       45MB
user   jsmith    ""      off          80MB        -       -        -       75MB
user   kjones    proj1   off          20MB        -       -        -       15MB
----
====


[[learn-how-default-tree-quotas-on-an-ontap-flexvol-volume-create-derived-tree-quotas]]
== Aprende cómo las cuotas de árbol predeterminadas en un volumen ONTAP FlexVol crean cuotas de árbol derivadas

Cuando se crea una cuota de árbol predeterminada en un volumen de FlexVol, las cuotas de árbol derivadas correspondientes se crean automáticamente para cada qtree de ese volumen.

Estas cuotas de árbol derivadas tienen los mismos límites que la cuota de árbol predeterminada. Si no existen cuotas adicionales, los límites tienen los siguientes efectos:

* Los usuarios pueden utilizar tanto espacio en un qtree como se asignan para todo el volumen (siempre y cuando no hayan superado el límite del volumen utilizando el espacio en la raíz u otro qtree).
* Cada uno de los qtrees puede crecer para consumir el volumen completo.


La existencia de una cuota de árbol predeterminada en un volumen sigue afectando a todos los qtrees nuevos que se agregan al volumen. Cada vez que se crea un qtree nuevo, también se crea una cuota de árbol derivada.

Al igual que todas las cuotas derivadas, las cuotas de árbol derivadas muestran los siguientes comportamientos:

* Sólo se crean si el destino no tiene una cuota explícita.
* Aparecen en los informes de cuotas, pero no aparecen cuando se muestran las reglas de cuotas con el `volume quota policy rule show` comando. Obtenga más información sobre `volume quota policy rule show` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-policy-rule-show.html["Referencia de comandos del ONTAP"^].


.Ejemplo de cuotas de árbol derivadas
[%collapsible]
====
Tiene un volumen con tres qtrees (proyecto 1, proyecto 2 y proyecto 3) y la única cuota de árbol es una cuota explícita en el qtree del proyecto 1 que limita su tamaño de disco a 10 GB. Si crea una cuota de árbol predeterminada en el volumen y reinicializa cuotas en el volumen, el informe de cuota ahora contiene cuatro cuotas de árbol:

[listing]
----
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1     proj1     tree    1           0B   10GB       1       -   proj1
vol1               tree    *           0B   20GB       0       -   *
vol1     proj2     tree    2           0B   20GB       1       -   proj2
vol1     proj3     tree    3           0B   20GB       1       -   proj3
...
----
La primera línea muestra la cuota explícita original en el qtree del proyecto 1. Esta cuota permanece sin cambios.

La segunda línea muestra la nueva cuota de árbol predeterminada en el volumen. El especificador de cuota asterisco (*) indica que es una cuota predeterminada. Esta cuota es el resultado de la regla de cuota que ha creado.

Las dos últimas líneas muestran nuevas cuotas de árboles derivadas para los qtrees proja2 y proy3. ONTAP creó automáticamente estas cuotas como resultado de la cuota de árbol predeterminada en el volumen. Estas cuotas de árbol derivadas tienen el mismo límite de disco de 20 GB que la cuota de árbol predeterminada del volumen. ONTAP no creó una cuota de árbol derivada para el qtree del proyecto 1 porque el qtree del proyecto 1 ya tenía una cuota explícita.

====


[[learn-how-default-user-quotas-on-an-ontap-flexvol-volume-affect-quotas-for-qtrees]]
== Descubre cómo las cuotas de usuario por defecto en un volumen ONTAP FlexVol afectan las cuotas para qtrees

Si se define una cuota de usuario predeterminada para un volumen de FlexVol, se crea automáticamente una cuota de usuario predeterminada para cada qtree contenido en ese volumen para el que existe una cuota de árbol explícita o derivada.

Si ya existe una cuota de usuario predeterminada en el qtree, no se verá afectada cuando se crea la cuota de usuario predeterminada en el volumen.

Las cuotas de usuario predeterminadas que se crean automáticamente en los qtrees tienen los mismos límites que la cuota de usuario predeterminada que se crea para el volumen.

Una cuota de usuario explícita para un qtree anula (sustituye los límites aplicados por) la cuota de usuario predeterminada creada automáticamente, del mismo modo que anula una cuota de usuario predeterminada en ese qtree que creó un administrador.
