---
permalink: volumes/tree-quotas-concept.html 
sidebar: sidebar 
keywords: how, tree, quotas, work 
summary: Puede crear una cuota con un qtree como destino para limitar el tamaño del qtree de destino. Estas cuotas también se denominan cuotas de árbol. 
---
= Descripción general de cómo funcionan las cuotas de árbol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear una cuota con un qtree como destino para limitar el tamaño del qtree de destino. Estas cuotas también se denominan _tree Quotas_.

Cuando se aplica una cuota a un qtree, el resultado es similar a una partición de disco, excepto que se puede cambiar el tamaño máximo del qtree en cualquier momento si se cambia la cuota. Cuando se aplica una cuota de árbol, ONTAP limita el espacio en disco y el número de archivos en el qtree, independientemente de sus propietarios. Ningún usuario, incluidos root y miembros del grupo BUILTIN\Administrators, puede escribir en el qtree si la operación de escritura hace que se supere la cuota de árbol.

[NOTE]
====
El tamaño de la cuota no garantiza ninguna cantidad específica de espacio disponible. El tamaño de la cuota puede ser mayor que la cantidad de espacio libre disponible para el qtree. Puede utilizar el `volume quota report` comando para determinar la cantidad real de espacio disponible en el qtree.

====