---
permalink: volumes/view-status-efficiency-operations-task.html 
sidebar: sidebar 
keywords: efficiency, operation, status, view 
summary: Puede ver si la deduplicación o la compresión de datos están habilitadas en un volumen. También puede ver el estado, la condición, el tipo de compresión y el progreso de las operaciones de eficiencia de un volumen mediante el comando volume Efficiency show. 
---
= Ver el estado de las operaciones de eficiencia
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ver si la deduplicación o la compresión de datos están habilitadas en un volumen. También puede ver el estado, la condición, el tipo de compresión y el progreso de las operaciones de eficiencia de un volumen mediante el `volume efficiency show` comando.

.Paso
. Utilice la `volume efficiency show` comando para ver el estado de una operación de eficiencia en un volumen.
+
El siguiente comando muestra el estado de una operación de eficiencia en el volumen Vola al que se le ha asignado el tipo de compresión adaptativa:

+
`volume efficiency show -instance -vserver vs1 -volume VolA`

+
Si la operación de eficiencia está activada en el volumen de Vola y la operación está inactiva, puede ver lo siguiente en el resultado del sistema:

+
[listing]
----
cluster1::> volume efficiency show -vserver vs1 -volume VolA

  Vserver Name: vs1
   Volume Name: VolA
   Volume Path: /vol/VolA
         State: Enabled
        Status: Idle
      Progress: Idle for 00:03:20
----

