---
permalink: volumes/view-efficiency-space-savings-task.html 
sidebar: sidebar 
keywords: view space savings deduplication, view space savings data compression, view space savings 
summary: Ver el ahorro de espacio logrado a través de la deduplicación y la compresión de datos en un volumen como parte de la planificación de la capacidad o para otros fines. 
---
= Ver el ahorro de espacio eficiente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ver la cantidad de ahorro de espacio que se consigue gracias a la deduplicación y la compresión de datos en un volumen. Puede hacerlo para evaluar la efectividad de sus procesos administrativos o como parte de la planificación de la capacidad.

.Acerca de esta tarea
Debe utilizar el comando `volume show` para mostrar el ahorro de espacio de un volumen. Tenga en cuenta que el ahorro de espacio en copias de Snapshot no se incluye al calcular el ahorro de espacio que se ha logrado en un volumen. El uso de la deduplicación no afecta a las cuotas de volumen. Las cuotas se informan a nivel lógico y no se modifican.

.Pasos
. Utilice la `volume show` comando para ver el ahorro de espacio que se consigue en un volumen mediante la deduplicación y la compresión de datos.


.Ejemplo
El siguiente comando le permite ver el ahorro de espacio conseguido usando la deduplicación y la compresión de datos en el volumen Vola: `volume show -vserver vs1 -volume VolA`

[listing]
----
cluster1::> volume show -vserver vs1 -volume VolA

                                 Vserver Name: vs1
                                  Volume Name: VolA
																											...
            Space Saved by Storage Efficiency: 115812B
       Percentage Saved by Storage Efficiency: 97%
                 Space Saved by Deduplication: 13728B
            Percentage Saved by Deduplication: 81%
                Space Shared by Deduplication: 1028B
                   Space Saved by Compression: 102084B
        Percentage Space Saved by Compression: 97%
																											...
----