---
permalink: encryption-at-rest/assign-fips-140-2-authentication-key-task.html 
sidebar: sidebar 
keywords: assigning, fips 140-2, authentication key, fips drive 
summary: Es posible utilizar el comando Storage Encryption Disk modify con la opción -fips-key-id para asignar una clave de autenticación FIPS 140-2 a una unidad FIPS. Los nodos de clúster utilizan esta clave para las operaciones de unidad distintas del acceso a los datos, como evitar ataques de denegación de servicio en la unidad. 
---
= Asigne una clave de autenticación FIPS 140-2 a una unidad FIPS con ONTAP
:allow-uri-read: 


[role="lead"]
Puede utilizar el `storage encryption disk modify` con el `-fips-key-id` Opción para asignar una clave de autenticación FIPS 140-2 a una unidad FIPS. Los nodos de clúster utilizan esta clave para las operaciones de unidad distintas del acceso a los datos, como evitar ataques de denegación de servicio en la unidad.

.Acerca de esta tarea
Es posible que la configuración de seguridad requiera el uso de claves diferentes para la autenticación de datos y la autenticación FIPS 140-2-2. Si no es así, puede usar la misma clave de autenticación para el cumplimiento de FIPS que se usa para acceder a los datos.

Este procedimiento no causa interrupciones.

.Antes de empezar
El firmware de la unidad debe ser compatible con el cumplimiento de normativas FIPS 140-2-2. La link:https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^] contiene información sobre las versiones de firmware de la unidad admitidas.

.Pasos
. Primero debe asegurarse de que ha asignado una clave de autenticación de datos. Esto se puede hacer utilizando un xref:assign-authentication-keys-seds-external-task.html[gestor de claves externas] o una xref:assign-authentication-keys-seds-onboard-task.html[gestión de claves incorporada]. Compruebe que la clave está asignada con el comando `storage encryption disk show`.
. Asigne una clave de autenticación FIPS 140-2 a SED:
+
`storage encryption disk modify -disk _disk_id_ -fips-key-id _fips_authentication_key_id_`

+
Puede utilizar el `security key-manager query` Comando para ver los ID clave.

+
[source]
----
cluster1::> storage encryption disk modify -disk 2.10.* -fips-key-id <id_value>

Info: Starting modify on 14 disks.
      View the status of the operation by using the
      storage encryption disk show-status command.
----
. Compruebe que se ha asignado la clave de autenticación:
+
`storage encryption disk show -fips`

+
Obtenga más información sobre `storage encryption disk show` en el link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["Referencia de comandos de la ONTAP"^].

+
[listing]
----
cluster1::> storage encryption disk show -fips
Disk    Mode FIPS-Compliance Key ID
------  ---- ----------------------------------------------------------------
2.10.0  full <id_value>
2.10.1  full <id_value>
[...]
----

