---
permalink: encryption-at-rest/before-configuring-concept.html 
sidebar: sidebar 
keywords: collect, network, information, ontap 9.2, earlier 
summary: Si utiliza ONTAP 9.2 o una versión anterior, debe rellenar la hoja de datos de configuración de red antes de habilitar la gestión de claves externas. 
---
= Recopilar información de red en ONTAP 9.2 y versiones anteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si utiliza ONTAP 9.2 o una versión anterior, debe rellenar la hoja de datos de configuración de red antes de habilitar la gestión de claves externas.

[NOTE]
====
A partir de ONTAP 9.3, el sistema detecta automáticamente toda la información de red necesaria.

====
[cols="35,35,30"]
|===


| Elemento | Notas | Valor 


 a| 
Nombre de la interfaz de red de gestión de claves
 a| 
 a| 



 a| 
Dirección IP de la interfaz de red de gestión de claves
 a| 
Dirección IP de LIF de gestión de nodos, en formato IPv4 o IPv6
 a| 



 a| 
Longitud del prefijo de red IPv6 de la interfaz de red de gestión de claves
 a| 
Si utiliza IPv6, la longitud del prefijo de red IPv6
 a| 



 a| 
Máscara de subred de la interfaz de red de gestión de claves
 a| 
 a| 



 a| 
Dirección IP de puerta de enlace de la interfaz de red de gestión de claves
 a| 
 a| 



 a| 
La dirección IPv6 de la interfaz de red del clúster
 a| 
Solo es obligatorio si se utiliza IPv6 para la interfaz de red de gestión de claves
 a| 



 a| 
Número de puerto para cada servidor KMIP
 a| 
Opcional. El número de puerto debe ser el mismo para todos los servidores KMIP. Si no proporciona un número de puerto, se establece de forma predeterminada en el puerto 5696, que es el puerto asignado por Internet Numbers Authority (IANA) para KMIP.
 a| 



 a| 
Nombre de etiqueta de clave
 a| 
Opcional. El nombre de etiqueta de clave se utiliza para identificar todas las claves que pertenecen a un nodo. El nombre de etiqueta de clave predeterminado es el nombre del nodo.
 a| 

|===
.Información relacionada
https://["Informe técnico de NetApp 3954: Requisitos y procedimientos previos a la instalación de cifrado del almacenamiento de NetApp para IBM Tivoli Lifetime Key Manager"^]

https://["Informe técnico de NetApp 4074: Requisitos y procedimientos previos a la instalación de cifrado del almacenamiento de NetApp para SafeNet KeySecure"^]
