---
permalink: encryption-at-rest/change-key-management-passphrase-task.html 
sidebar: sidebar 
keywords: changing, onboard, key, management, passphrase 
summary: Una práctica recomendada para la seguridad es cambiar periódicamente la clave de acceso de gestión de claves incorporada. Debe copiar la nueva clave de gestión integrada en una ubicación segura fuera del sistema de almacenamiento para usarla en el futuro. 
---
= Cambie la clave de acceso para la gestión de claves incorporada con ONTAP
:allow-uri-read: 


[role="lead"]
Una práctica recomendada para la seguridad es cambiar periódicamente la clave de acceso de gestión de claves incorporada. Debe copiar la nueva clave de gestión integrada en una ubicación segura fuera del sistema de almacenamiento para usarla en el futuro.

.Antes de empezar
* Debe ser un administrador de clúster o de SVM para ejecutar esta tarea.
* Se requieren privilegios avanzados para esta tarea.


.Pasos
. Cambie al nivel de privilegio avanzado:
+
`set -privilege advanced`

. Cambie la clave de acceso de gestión de claves incorporada:
+
[cols="25,75"]
|===


| Para esta versión de ONTAP... | Se usa este comando... 


 a| 
ONTAP 9,6 y versiones posteriores
 a| 
`security key-manager onboard update-passphrase`



 a| 
ONTAP 9,5 y anteriores
 a| 
`security key-manager update-passphrase`

|===
+
Obtenga más información sobre `security key-manager update-passphrase` en el link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-update-passphrase.html["Referencia de comandos del ONTAP"^].

+
El siguiente comando ONTAP 9.6 permite cambiar la clave de acceso de gestión de claves incorporada para `cluster1`:

+
[listing]
----
clusterl::> security key-manager onboard update-passphrase
Warning: This command will reconfigure the cluster passphrase for onboard key management for Vserver "cluster1".
Do you want to continue? {y|n}: y
Enter current passphrase:
Enter new passphrase:
----
. Introduzca `y` en el símbolo del sistema para cambiar la clave de acceso de gestión de claves incorporada.
. Introduzca la frase de contraseña actual en la solicitud de contraseña actual.
. En la nueva solicitud de frase de contraseña, introduzca una frase de paso entre 32 y 256 caracteres, o bien, para "'cc-mode'", una frase de paso entre 64 y 256 caracteres.
+
Si la frase de paso "'cc-mode'" especificada es menor de 64 caracteres, hay un retraso de cinco segundos antes de que la operación de configuración del gestor de claves vuelva a mostrar la indicación de contraseña.

. En la solicitud de confirmación de contraseña, vuelva a introducir la frase de contraseña.


.Después de terminar
En un entorno de MetroCluster, debe actualizar la clave de acceso en el clúster de partners:

* En ONTAP 9, 5 y anterior, debe ejecutar `security key-manager update-passphrase` con la misma clave de acceso en el clúster del partner.
* En ONTAP 9 E.6 y versiones posteriores, se le pedirá que ejecute `security key-manager onboard sync` con la misma clave de acceso en el clúster de partners.


Debe copiar la clave de gestión integrada en una ubicación segura fuera del sistema de almacenamiento para usarla en el futuro.

Debe realizar un backup manual de la información de gestión de claves siempre que se cambie la clave de acceso de gestión de claves incorporada.

link:backup-key-management-information-manual-task.html["Realizar un backup manual de la información de gestión de claves incorporada"]
