---
permalink: encryption-at-rest/cluster-version-support-nve-task.html 
sidebar: sidebar 
keywords: determining, whether, cluster, version, supports, nve 
summary: Debe determinar si la versión de clúster es compatible con NVE antes de instalar la licencia. Puede utilizar el comando version para determinar la versión del clúster. 
---
= Determine si la versión del clúster es compatible con NVE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe determinar si la versión de clúster es compatible con NVE antes de instalar la licencia. Puede utilizar el `version` comando para determinar la versión del clúster.

.Acerca de esta tarea
La versión del clúster es la versión más baja de ONTAP que se ejecuta en cualquier nodo del clúster.

.Paso
. Determine si la versión de clúster es compatible con NVE:
+
`version -v`

+
NVE no es compatible si el resultado del comando muestra el texto «'1Ono-DARE» (del cifrado «no de datos en reposo») o si utiliza una plataforma que no aparezca en la link:configure-netapp-volume-encryption-concept.html#support-details["Detalles de soporte"].

+
El siguiente comando determina si se admite NVE a. `cluster1`.

+
[listing]
----
cluster1::> version -v
NetApp Release 9.1.0: Tue May 10 19:30:23 UTC 2016 <1Ono-DARE>
----
+
El resultado de `1Ono-DARE` Indica que la versión del clúster no es compatible con NVE.


