---
permalink: encryption-at-rest/configure-external-key-management-overview-concept.html 
sidebar: sidebar 
keywords: external key management, kmip, configure 
summary: 'Puede usar uno o varios servidores de gestión de claves externos para proteger las claves que utiliza el clúster para acceder a los datos cifrados. Un servidor de gestión de claves externo es un sistema de terceros en el entorno de almacenamiento que proporciona claves a los nodos mediante el protocolo de interoperabilidad de gestión de claves (KMIP).' 
---
= Configure información general sobre la gestión de claves externas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar uno o varios servidores de gestión de claves externos para proteger las claves que utiliza el clúster para acceder a los datos cifrados. Un servidor de gestión de claves externo es un sistema de terceros en el entorno de almacenamiento que proporciona claves a los nodos mediante el protocolo de interoperabilidad de gestión de claves (KMIP).


NOTE: Para ONTAP 9.1 y versiones anteriores, las LIF de gestión de nodos se deben asignar a los puertos que están configurados con el rol de gestión de nodos antes de poder usar el gestor de claves externo.

El cifrado de volúmenes de NetApp (NVE) es compatible con el gestor de claves incorporado en ONTAP 9.1 y versiones posteriores. A partir de ONTAP 9.3, NVE admite la gestión de claves externas (KMIP) y el gestor de claves incorporado. A partir de ONTAP 9.10.1, puede utilizar xref:manage-keys-azure-google-task.html[Azure Key Vault o el servicio de Google Cloud Key Manager] Para proteger las claves NVE. A partir de ONTAP 9.11.1, es posible configurar varios administradores de claves externos en un clúster de. Consulte xref:configure-cluster-key-server-task.html[Configurar servidores de claves en cluster.]
