---
permalink: encryption-at-rest/create-authentication-keys-96-later-task.html 
sidebar: sidebar 
keywords: creating, authentication keys, ontap 9.6, later 
summary: Es posible usar el comando Security key-Manager key create para crear las claves de autenticación de un nodo y almacenarlos en los servidores KMIP configurados. 
---
= Cree claves de autenticación en ONTAP 9.6 y versiones posteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `security key-manager key create` Comando para crear las claves de autenticación de un nodo y almacenarlas en los servidores KMIP configurados.

.Acerca de esta tarea
Si la configuración de seguridad requiere el uso de claves diferentes para la autenticación de datos y la autenticación FIPS 140-2-2, debe crear una clave independiente para cada una. Si este no es el caso, puede usar la misma clave de autenticación para el cumplimiento de FIPS que utiliza para el acceso a los datos.

ONTAP crea claves de autenticación para todos los nodos del clúster.

* Este comando no es compatible cuando el gestor de claves incorporado está habilitado. Sin embargo, se crean automáticamente dos claves de autenticación cuando se habilita el gestor de claves incorporado. Las teclas se pueden ver con el siguiente comando:
+
`security key-manager key query -key-type NSE-AK`

* Recibe una advertencia si los servidores de gestión de claves configurados ya almacenan más de 128 claves de autenticación.
* Puede utilizar el `security key-manager key delete` comando para eliminar las claves no utilizadas. La `security key-manager key delete` El comando falla si ONTAP utiliza actualmente la clave proporcionada. (Debe tener privilegios superiores a «'admin'» para utilizar este comando).
+
[NOTE]
====
En un entorno de MetroCluster, antes de eliminar una clave, debe asegurarse de que la clave no se esté utilizando en el clúster de partners. Puede utilizar los siguientes comandos en el clúster de partners para comprobar que la clave no esté en uso:

** `storage encryption disk show -data-key-id _key-id_`
** `storage encryption disk show -fips-key-id _key-id_`


====


.Antes de empezar
Para realizar esta tarea, debe ser un administrador de clústeres.

.Pasos
. Cree las claves de autenticación para los nodos del clúster:
+
`security key-manager key create -key-tag passphrase_label -prompt-for-key true|false`

+
[NOTE]
====
Al establecer esta configuración `prompt-for-key=true`, el sistema solicita al administrador del clúster que la clave de acceso se use al autenticar las unidades cifradas. De lo contrario, el sistema genera automáticamente una frase de acceso de 32 bytes. El `security key-manager key create` comando reemplaza `security key-manager create-key` el comando. Obtenga más información sobre `security key-manager key create` en el link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-create.html?q=security+key-manager+key+create["Referencia de comandos de la ONTAP"^].

====
+
En el siguiente ejemplo se crean las claves de autenticación para `cluster1`, generar automáticamente una frase de paso de 32 bytes:

+
[listing]
----
cluster1::> security key-manager key create
Key ID: 000000000000000002000000000001006268333f870860128fbe17d393e5083b0000000000000000
----
. Compruebe que se han creado las claves de autenticación:
+
`security key-manager key query -node node`

+
[NOTE]
====
El `security key-manager key query` comando reemplaza `security key-manager query key` el comando. Obtenga más información sobre `security key-manager key query` en el link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-query.html["Referencia de comandos de la ONTAP"^]. El ID de clave que se muestra en el resultado es un identificador que se utiliza para hacer referencia a la clave de autenticación. No es la clave de autenticación real ni la clave de cifrado de datos.

====
+
El ejemplo siguiente verifica para qué se han creado claves de autenticación `cluster1`:

+
[listing]
----
cluster1::> security key-manager key query
       Vserver: cluster1
   Key Manager: external
          Node: node1

Key Tag                               Key Type  Restored
------------------------------------  --------  --------
node1                                 NSE-AK    yes
    Key ID: 000000000000000002000000000001000c11b3863f78c2273343d7ec5a67762e0000000000000000
node1                                 NSE-AK    yes
    Key ID: 000000000000000002000000000001006f4e2513353a674305872a4c9f3bf7970000000000000000

       Vserver: cluster1
   Key Manager: external
          Node: node2

Key Tag                               Key Type  Restored
------------------------------------  --------  --------
node2                                 NSE-AK    yes
    Key ID: 000000000000000002000000000001000c11b3863f78c2273343d7ec5a67762e0000000000000000
node2                                 NSE-AK    yes
    Key ID: 000000000000000002000000000001006f4e2513353a674305872a4c9f3bf7970000000000000000
----

