---
permalink: encryption-at-rest/data-seds-inaccessible-concept.html 
sidebar: sidebar 
keywords: making, data, fips, drive, sed, inaccessible 
summary: Si desea que los datos de una unidad FIPS o SED sean inaccesibles de forma permanente, pero si mantiene el espacio sin utilizar de la unidad disponible para los nuevos datos, puede desinfectar el disco. Si desea que los datos no se puedan acceder a ellos de forma permanente y no es necesario volver a utilizar la unidad, es posible destruirlos. 
---
= Hacer datos en una unidad FIPS o información general inaccesible de SED
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea que los datos de una unidad FIPS o SED sean inaccesibles permanentemente, pero mantenga el espacio no utilizado de la unidad disponible para los nuevos datos, puede desinfectar el disco. Si desea que los datos no se puedan acceder a ellos de forma permanente y no es necesario volver a utilizar la unidad, es posible destruirlos.

* El saneamiento de disco
+
Cuando se limpia una unidad de autocifrado, el sistema cambia la clave de cifrado de disco a un nuevo valor aleatorio, restablece el estado de bloqueo de encendido a FALSE y establece el ID de clave en un valor predeterminado, es decir, el ID seguro de fabricante 0x0 (unidades SAS) o una clave nula (unidades NVMe). Si lo hace, los datos del disco son inaccesibles y es imposible recuperarlos. Puede reutilizar discos sanitizados como discos de repuesto no ceros.

* Destrucción de discos
+
Cuando destruye una unidad FIPS o SED, el sistema establece la clave de cifrado del disco en un valor aleatorio desconocido y bloquea el disco de forma irreversible. De este modo, el disco se vuelve inutilizable de forma permanente y los datos del mismo no se podrán acceder de forma permanente.



Puede desinfectar o destruir unidades de autocifrado individuales o todas las unidades de autocifrado de un nodo.
