---
permalink: encryption-at-rest/delete-key-management-database-task.html 
sidebar: sidebar 
keywords: transitioning, onboard key management, external key management 
summary: Si desea cambiar a la gestión de claves incorporada desde la gestión de claves externas, debe eliminar la configuración de gestión de claves externa para poder habilitar la gestión de claves incorporada. 
---
= Transición a la gestión de claves incorporada desde la gestión de claves externas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea cambiar a la gestión de claves incorporada desde la gestión de claves externas, debe eliminar la configuración de gestión de claves externa para poder habilitar la gestión de claves incorporada.

.Antes de empezar
* Para el cifrado basado en hardware, debe restablecer las claves de datos de todas las unidades FIPS o SED a su valor predeterminado.
+
link:return-seds-unprotected-mode-task.html["Devolver una unidad FIPS o SED al modo sin protección"]

* Eliminó todas las conexiones del administrador de claves externo.
+
link:remove-external-key-server-93-later-task.html["Eliminación de una conexión de administrador de claves externo"]

* Para realizar esta tarea, debe ser un administrador de clústeres.




== Procedimiento

[role="tabbed-block"]
====
.ONTAP 9.6 y posteriores
--
. Cambie al nivel de privilegio avanzado:
+
`set -privilege advanced`

. Utilizar el comando:
+
`security key-manager external disable -vserver _admin_SVM_`

+

NOTE: En un entorno de MetroCluster, debe repetir el comando en ambos clústeres para la SVM de administrador.



--
.ONTAP 9.5 y anteriores
--
Utilizar el comando:
`security key-manager delete-kmip-config`

--
====