---
permalink: encryption-at-rest/delete-encrypted-volume-task.html 
sidebar: sidebar 
keywords: deleting, encrypted, volume 
summary: Puede usar el comando volume delete para eliminar un volumen cifrado. 
---
= Elimine un volumen cifrado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `volume delete` comando para eliminar un volumen cifrado.

.Lo que necesitará
* Debe ser un administrador de clústeres para realizar esta tarea o un administrador de SVM a quien el administrador de clúster haya delegado esta autoridad.
+
link:delegate-volume-encryption-svm-administrator-task.html["Delegar la autoridad para ejecutar el comando volume move"]

* El volumen debe estar fuera de línea.


.Paso
. Elimine un volumen cifrado:
+
`volume delete -vserver SVM_name -volume volume_name`

+
Para obtener una sintaxis de comando completa, consulte la página de manual del comando.

+
El siguiente comando elimina un volumen cifrado denominado `vol1`:

+
[listing]
----
cluster1::> volume delete -vserver vs1 -volume vol1
----
+
Introduzca `yes` cuando se le solicite que confirme la eliminación.

+
El sistema elimina la clave de cifrado del volumen después de 24 horas.

+
Uso `volume delete` con la `-force true` opción para eliminar un volumen y destruir inmediatamente la clave de cifrado correspondiente. Este comando requiere privilegios avanzados. Para obtener más información, consulte la página man.



.Después de terminar
Puede utilizar el `volume recovery-queue` comando para recuperar un volumen eliminado durante el período de retención después de emitir el `volume delete` comando:

`volume recovery-queue SVM_name -volume volume_name`

https://["Cómo usar la función Volume Recovery"]
