---
permalink: encryption-at-rest/delete-key-management-database-task.html 
sidebar: sidebar 
keywords: transitioning, onboard key management, external key management 
summary: Si desea cambiar a la gestión de claves incorporada desde la gestión de claves externas, debe eliminar la configuración de gestión de claves externa para poder habilitar la gestión de claves incorporada. 
---
= Cambiar de la gestión de claves externa a la gestión de claves integrada de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para cambiar a la administración de claves integrada, elimine la configuración de administración de claves externa antes de habilitar la administración de claves integrada.

.Antes de empezar
* Para el cifrado basado en hardware, debe restablecer las claves de datos de todas las unidades FIPS o SED a su valor predeterminado.
+
link:return-seds-unprotected-mode-task.html["Devolver una unidad FIPS o SED al modo sin protección"]

* Eliminó todas las conexiones del administrador de claves externo.
+
link:remove-external-key-server-93-later-task.html["Eliminación de una conexión de administrador de claves externo"]

* Para realizar esta tarea, debe ser un administrador de clústeres.


.Pasos
Los pasos para realizar la transición de la gestión de claves dependen de la versión de ONTAP que esté utilizando.

[role="tabbed-block"]
====
.ONTAP 9,6 y versiones posteriores
--
. Cambie al nivel de privilegio avanzado:
+
`set -privilege advanced`

. Utilizar el comando:
+
`security key-manager external disable -vserver _admin_SVM_`

+

NOTE: En un entorno de MetroCluster, debe repetir el comando en ambos clústeres para la SVM de administrador.



Obtenga más información sobre `security key-manager external disable` en ellink:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-disable.html["Referencia de comandos del ONTAP"^] .

--
.ONTAP 9,5 y anteriores
--
Utilice el comando:
`security key-manager delete-kmip-config`

Obtenga más información sobre `security key-manager delete-kmip-config` en ellink:https://docs.netapp.com/us-en/ontap-cli-9161/security-key-manager-delete-kmip-config.html["Referencia de comandos del ONTAP"^] .

--
====
.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-disable.html["Desactivación externa del administrador de claves de seguridad"^]

