---
permalink: encryption-at-rest/disable-encryption-by-default-97-higher-task.html 
sidebar: sidebar 
keywords: disabling, encryption, default, ontap 9.7, later 
summary: 'A partir de ONTAP 9.7, el cifrado de volúmenes y agregados se habilita de forma predeterminada si se dispone de una licencia de cifrado de volúmenes (ve) y se usa un gestor de claves incorporado o externo. Puede deshabilitar el cifrado de forma predeterminada si es necesario.' 
---
= Desactive el cifrado de forma predeterminada
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.7, el cifrado de volúmenes y agregados se habilita de forma predeterminada si se dispone de una licencia de cifrado de volúmenes (ve) y se usa un gestor de claves incorporado o externo. Si es necesario, puede deshabilitar el cifrado de forma predeterminada en todo el clúster.

.Antes de empezar
Debe ser un administrador de clústeres para realizar esta tarea o un administrador de SVM a quien el administrador de clúster haya delegado esta autoridad.

.Paso
. Para deshabilitar el cifrado de forma predeterminada para todo el clúster en ONTAP 9.7 o posterior, ejecute el siguiente comando:
+
`options -option-name encryption.data_at_rest_encryption.disable_by_default -option-value on`


