---
permalink: encryption-at-rest/enable-exernal-key-management-95-earlier-hw-task.html 
sidebar: sidebar 
keywords: enabling, external key management, ontap 9.5, earlier 
summary: Puede utilizar uno o varios servidores KMIP para proteger las claves que utiliza el clúster para acceder a los datos cifrados. Se pueden conectar hasta cuatro servidores KMIP a un nodo. Se recomienda un mínimo de dos servidores para la redundancia y la recuperación ante desastres. 
---
= Habilitar la administración de claves externas para el cifrado basado en hardware en ONTAP 9.5 y versiones anteriores
:allow-uri-read: 


[role="lead"]
Puede utilizar uno o varios servidores KMIP para proteger las claves que utiliza el clúster para acceder a los datos cifrados. Se pueden conectar hasta cuatro servidores KMIP a un nodo. Se recomienda un mínimo de dos servidores para la redundancia y la recuperación ante desastres.

.Acerca de esta tarea
ONTAP configura la conectividad de los servidores KMIP para todos los nodos del clúster.

.Antes de empezar
* Deben haberse instalado el cliente KMIP SSL y los certificados de servidor.
* Para realizar esta tarea, debe ser un administrador de clústeres.
* Debe configurar el entorno de MetroCluster antes de configurar un gestor de claves externo.
* En un entorno MetroCluster, debe instalar el mismo certificado SSL KMIP en ambos clústeres.


.Pasos
. Configure la conectividad de Key Manager para los nodos del clúster:
+
`security key-manager setup`

+
Se inicia la configuración del gestor de claves.

+

NOTE: En un entorno de MetroCluster, debe ejecutar este comando en ambos clústeres. Obtenga más información sobre `security key-manager setup` en el link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-setup.html["Referencia de comandos del ONTAP"^].

. Introduzca la respuesta adecuada en cada solicitud.
. Añadir un servidor KMIP:
+
`security key-manager add -address key_management_server_ipaddress`

+
[listing]
----
clusterl::> security key-manager add -address 20.1.1.1
----
+

NOTE: En un entorno de MetroCluster, debe ejecutar este comando en ambos clústeres.

. Añada un servidor KMIP adicional para redundancia:
+
`security key-manager add -address key_management_server_ipaddress`

+
[listing]
----
clusterl::> security key-manager add -address 20.1.1.2
----
+

NOTE: En un entorno de MetroCluster, debe ejecutar este comando en ambos clústeres.

. Compruebe que todos los servidores KMIP configurados están conectados:
+
`security key-manager show -status`

+
Obtenga más información sobre los comandos descritos en este procedimiento en el link:https://docs.netapp.com/us-en/ontap-cli/["Referencia de comandos del ONTAP"^].

+
[listing]
----
cluster1::> security key-manager show -status

Node            Port      Registered Key Manager  Status
--------------  ----      ----------------------  ---------------
cluster1-01     5696      20.1.1.1                available
cluster1-01     5696      20.1.1.2                available
cluster1-02     5696      20.1.1.1                available
cluster1-02     5696      20.1.1.2                available
----
. Opcionalmente, convierta volúmenes de texto sin formato en volúmenes cifrados.
+
`volume encryption conversion start`

+
Debe haber configurado completamente un gestor de claves externo para poder convertir los volúmenes. En un entorno MetroCluster, debe configurarse un gestor de claves externo en ambos sitios.


