---
permalink: encryption-at-rest/enable-onboard-key-management-95-earlier-nve-task.html 
sidebar: sidebar 
keywords: enabling, onboard key management, ontap 9.5, earlier, nve 
summary: Puede usar el administrador de claves incorporado para proteger las claves que el clúster utiliza para acceder a los datos cifrados. Debe habilitar el gestor de claves incorporado en cada clúster que acceda a un volumen cifrado o un disco de autocifrado. 
---
= Habilitar la administración de claves integrada para NVE en ONTAP 9.5 y versiones anteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar el administrador de claves incorporado para proteger las claves que el clúster utiliza para acceder a los datos cifrados. Debe habilitar el gestor de claves incorporado en cada clúster que acceda a un volumen cifrado o un disco de autocifrado.

.Acerca de esta tarea
Debe ejecutar `security key-manager setup` el comando cada vez que añade un nodo al clúster.

Si tiene una configuración de MetroCluster, revise las siguientes directrices:

* En ONTAP 9.5, debe ejecutarse `security key-manager setup` en el clúster local y `security key-manager setup -sync-metrocluster-config yes` en el clúster remoto, con la misma clave de acceso en cada uno.
* Antes de usar ONTAP 9.5, debe ejecutarse `security key-manager setup` en el clúster local, esperar aproximadamente 20 segundos y, luego, ejecutarse `security key-manager setup` en el clúster remoto, usando la misma clave de acceso en cada uno.


De forma predeterminada, no es necesario introducir la clave de acceso del administrador de claves cuando se reinicia un nodo. A partir de ONTAP 9.4, puede usar la `-enable-cc-mode yes` opción para solicitar que los usuarios introduzcan la frase de acceso después de reiniciar.

Para NVE, si establece `-enable-cc-mode yes`, los volúmenes que cree con los `volume create` `volume move start` comandos y se cifran automáticamente. Para `volume create`, no es necesario especificar `-encrypt true`. Para `volume move start`, no es necesario especificar `-encrypt-destination true`.


NOTE: Después de un intento de clave de acceso con errores, debe reiniciar el nodo de nuevo.

.Antes de empezar
* Si utiliza NSE o NVE con un servidor de administración de claves externo (KMIP), elimine la base de datos del administrador de claves externo.
+
link:delete-key-management-database-task.html["Transición a la gestión de claves incorporada desde la gestión de claves externas"]

* Para realizar esta tarea, debe ser un administrador de clústeres.
* Configure el entorno MetroCluster antes de configurar el Administrador de claves integrado.


.Pasos
. Inicie la configuración del gestor de claves:
+
`security key-manager setup -enable-cc-mode yes|no`

+
[NOTE]
====
A partir de ONTAP 9.4, puede usar la `-enable-cc-mode yes` opción para solicitar que los usuarios introduzcan la frase de contraseña del administrador de claves después de un reinicio. Para NVE, si establece `-enable-cc-mode yes`, los volúmenes que cree con los `volume create` `volume move start` comandos y se cifran automáticamente.

====
+
En el siguiente ejemplo, se inicia la configuración del gestor de claves en cluster1 sin necesidad de introducir la clave de acceso después de cada reinicio:

+
[listing]
----
cluster1::> security key-manager setup
Welcome to the key manager setup wizard, which will lead you through
the steps to add boot information.

...

Would you like to use onboard key-management? {yes, no} [yes]:
Enter the cluster-wide passphrase:    <32..256 ASCII characters long text>
Reenter the cluster-wide passphrase:    <32..256 ASCII characters long text>
----
. Introduzca `yes` en el aviso para configurar la gestión de claves incorporada.
. En el indicador de frase de contraseña, introduzca una frase de paso entre 32 y 256 caracteres, o bien, para "'cc-mode'", una frase de paso entre 64 y 256 caracteres.
+
[NOTE]
====
Si la frase de paso "'cc-mode'" especificada es menor de 64 caracteres, hay un retraso de cinco segundos antes de que la operación de configuración del gestor de claves vuelva a mostrar la indicación de contraseña.

====
. En la solicitud de confirmación de contraseña, vuelva a introducir la frase de contraseña.
. Compruebe que las claves estén configuradas para todos los nodos:
+
`security key-manager show-key-store`

+
[listing]
----
cluster1::> security key-manager show-key-store

Node: node1
Key Store: onboard
Key ID                                                           Used By
---------------------------------------------------------------- --------
<id_value> NSE-AK
<id_value> NSE-AK

Node: node2
Key Store: onboard
Key ID                                                           Used By
---------------------------------------------------------------- --------
<id_value> NSE-AK
<id_value> NSE-AK
----
+
Obtenga más información sobre `security key-manager show-key-store` en ellink:https://docs.netapp.com/us-en/ontap-cli-9161/security-key-manager-show-key-store.html["Referencia de comandos del ONTAP"^] .

. Opcionalmente, convierta volúmenes de texto sin formato en volúmenes cifrados.
+
`volume encryption conversion start`

+
Configure el administrador de claves integrado antes de convertir volúmenes.  En entornos MetroCluster , configúrelo en ambos sitios.



.Después de terminar
Copie la clave de acceso en una ubicación segura fuera del sistema de almacenamiento para usarla en el futuro.

Cuando configure la frase de contraseña del Onboard Key Manager, haga una copia de seguridad de la información en una ubicación segura fuera del sistema de almacenamiento en caso de desastre. Verlink:backup-key-management-information-manual-task.html["Realice un backup manual de la información de gestión de claves incorporada"] .

.Información relacionada
* link:backup-key-management-information-manual-task.html["Realice un backup manual de la información de gestión de claves incorporada"]
* link:delete-key-management-database-task.html["Transición a la gestión de claves incorporada desde la gestión de claves externas"]
* link:https://docs.netapp.com/us-en/ontap-cli-9161/security-key-manager-show-key-store.html["administrador de claves de seguridad mostrar almacén de claves"^]

