---
permalink: encryption-at-rest/enable-cluster-fips-compliant-mode-task.html 
sidebar: sidebar 
keywords: enabling, cluster-wide, fips-compliant mode, kmip, server, connections 
summary: Puede utilizar el comando Security config modify con la opción -is-fips-enabled para habilitar el modo compatible con FIPS en todo el clúster para los datos en tránsito. Al hacerlo, obliga al clúster a usar OpenSSL en modo FIPS al conectarse a servidores KMIP. 
---
= Habilite el modo compatible con FIPS en todo el clúster para conexiones de servidor KMIP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `security config modify` con el -`is-fips-enabled` Opción de habilitar el modo compatible con FIPS en todo el clúster para los datos que están en movimiento. Al hacerlo, obliga al clúster a usar OpenSSL en modo FIPS al conectarse a servidores KMIP.

.Antes de empezar
* La controladora de almacenamiento debe configurarse en modo conforme a FIPS.
* Todos los servidores KMIP deben ser compatibles con TLSv1.2. El sistema requiere TLSv1.2 para completar la conexión con el servidor KMIP cuando se habilita el modo compatible con FIPS en todo el clúster.


.Acerca de esta tarea
Cuando habilita el modo compatible con FIPS en todo el clúster, el clúster utilizará únicamente paquetes de cifrado validados TLS1.2 y FIPS. El modo compatible con FIPS para todo el clúster está deshabilitado de forma predeterminada.

Debe reiniciar los nodos del clúster de forma manual después de modificar la configuración de seguridad de todo el clúster.

.Pasos
. Configure el nivel de privilegio en Advanced:
+
`set -privilege advanced`

. Compruebe que TLSv1.2 es compatible:
+
`security config show -supported-protocols`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
[listing]
----
cluster1::> security config show
          Cluster                                              Cluster Security
Interface FIPS Mode  Supported Protocols     Supported Ciphers Config Ready
--------- ---------- ----------------------- ----------------- ----------------
SSL       false      TLSv1.2, TLSv1.1, TLSv1 ALL:!LOW:         yes
                                             !aNULL:!EXP:
                                             !eNULL
----
. Habilite el modo compatible con FIPS para todo el clúster:
+
`security config modify -is-fips-enabled true -interface SSL`

+
Para obtener una sintaxis de comando completa, consulte la página man.

. Reiniciar nodos del clúster de forma manual.
. Compruebe que el modo compatible con FIPS en todo el clúster esté habilitado:
+
`security config show`

+
[listing]
----
cluster1::> security config show
          Cluster                                              Cluster Security
Interface FIPS Mode  Supported Protocols     Supported Ciphers Config Ready
--------- ---------- ----------------------- ----------------- ----------------
SSL       true       TLSv1.2, TLSv1.1        ALL:!LOW:         yes
                                             !aNULL:!EXP:
                                             !eNULL:!RC4
----

