---
permalink: encryption-at-rest/enable-encryption-new-volume-task.html 
sidebar: sidebar 
keywords: encryption, new volume, NAE, NVE, volume create 
summary: Puede usar el comando volume create para habilitar el cifrado en un volumen nuevo. 
---
= Habilite el cifrado en un nuevo volumen en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar `volume create` el comando para habilitar el cifrado en un volumen nuevo.

.Acerca de esta tarea
Puede cifrar volúmenes con el cifrado de volúmenes de NetApp (NVE) y, para comenzar con ONTAP 9.6, el cifrado de agregados de NetApp (NAE). Para obtener más información sobre NAE y NVE, consulte xref:configure-netapp-volume-encryption-concept.html[información general de cifrado de volúmenes]el .

Obtenga más información sobre los comandos descritos en este procedimiento en el link:https://docs.netapp.com/us-en/ontap-cli/["Referencia de comandos del ONTAP"^].

El procedimiento para habilitar el cifrado en un nuevo volumen en ONTAP varía en función de la versión de ONTAP que esté usando y su configuración específica:

* A partir de ONTAP 9.4, si se habilita `cc-mode` al configurar el Administrador de claves integrado, los volúmenes que se crean con el `volume create` comando se cifran automáticamente, independientemente de si se especifica o no `-encrypt true` .
* En ONTAP 9.6 y versiones anteriores, debe utilizar `-encrypt true` `volume create` los comandos WITH para activar el cifrado (siempre que no se haya activado `cc-mode`).
* Si desea crear un volumen NAE en ONTAP 9.6, debe habilitar NAE en el nivel de agregado. Consulte xref:enable-aggregate-level-encryption-nve-license-task.html[Habilite el cifrado a nivel de agregado con la licencia ve]para obtener más detalles sobre esta tarea.
* A partir de ONTAP 9.7, los volúmenes recién creados se cifran de forma predeterminada cuando se cuenta con link:../encryption-at-rest/install-license-task.html["LICENCIA VE"]la gestión de claves externa o incorporada. De forma predeterminada, los nuevos volúmenes que se crean en un agregado de NAE serán del tipo NAE en lugar de NVE.
+
** En ONTAP 9 Intersight 7 y versiones posteriores, si agrega `-encrypt true` al `volume create` comando para crear un volumen en un agregado de NAE, el volumen tendrá cifrado NVE en lugar de NAE. Todos los volúmenes de un agregado de NAE deben estar cifrados con NVE o NAE.





NOTE: No se admiten los volúmenes de texto sin formato en los agregados de NAE.

.Pasos
. Cree un volumen nuevo y especifique si el cifrado está habilitado en el volumen. Si el nuevo volumen se encuentra en un agregado de NAE, de forma predeterminada el volumen será un volumen de NAE:
+
[cols="25,75"]
|===


| Para crear... | Se usa este comando... 


 a| 
Un volumen de NAE
 a| 
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_`



 a| 
Un volumen de NVE
 a| 
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_ -encrypt true` +


NOTE: En ONTAP 9, etc. 6 y versiones anteriores, donde no se admite NAE, `-encrypt true` especifica que el volumen debe cifrarse con NVE. En ONTAP 9, 7 y versiones posteriores, en las que se crean volúmenes en agregados de NAE, `-encrypt true` se anula el tipo de cifrado predeterminado de NAE para crear un volumen de NVE.



 a| 
Un volumen de texto sin formato
 a| 
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_ -encrypt false`

|===
+
Obtenga más información sobre `volume create` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["Referencia de comandos del ONTAP"^].

. Compruebe que los volúmenes estén habilitados para el cifrado:
+
`volume show -is-encrypted true`

+
Obtenga más información sobre `volume show` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html["Referencia de comandos del ONTAP"^].



.Resultado
Si utiliza un servidor KMIP para almacenar las claves de cifrado de un nodo, ONTAP "inserta automáticamente" una clave de cifrado en el servidor cuando se cifra un volumen.
