---
permalink: encryption-at-rest/enable-external-key-management-96-later-hw-task.html 
sidebar: sidebar 
keywords: enabling, external key management, ontap 9.6, later, hw-based 
summary: Puede utilizar uno o varios servidores KMIP para proteger las claves que utiliza el clúster para acceder a los datos cifrados. Se pueden conectar hasta cuatro servidores KMIP a un nodo. Se recomienda un mínimo de dos servidores para la redundancia y la recuperación ante desastres. 
---
= Habilitar la administración de claves externas para el cifrado basado en hardware en ONTAP 9.6 y versiones posteriores
:allow-uri-read: 


[role="lead"]
Puede utilizar uno o varios servidores KMIP para proteger las claves que utiliza el clúster para acceder a los datos cifrados. Se pueden conectar hasta cuatro servidores KMIP a un nodo. Se recomienda un mínimo de dos servidores para la redundancia y la recuperación ante desastres.

A partir de ONTAP 9.11.1, puede agregar hasta 3 servidores de claves secundarios por servidor de claves primario para crear un servidor de claves en clúster. Para obtener más información, consulte xref:configure-cluster-key-server-task.html[Configurar servidores de claves externas en cluster].

.Antes de empezar
* Deben haberse instalado el cliente KMIP SSL y los certificados de servidor.
* Para realizar esta tarea, debe ser un administrador de clústeres.
* Debe configurar el entorno de MetroCluster antes de configurar un gestor de claves externo.
* En un entorno MetroCluster, debe instalar el mismo certificado SSL KMIP en ambos clústeres.


.Pasos
. Configure la conectividad del gestor de claves para el clúster:
+
`+security key-manager external enable -vserver admin_SVM -key-servers host_name|IP_address:port,... -client-cert client_certificate -server-ca-cert server_CA_certificates+`

+
[NOTE]
====
** El `security key-manager external enable` comando reemplaza `security key-manager setup` el comando. Es posible ejecutar `security key-manager external modify` el comando para cambiar la configuración de gestión de claves externas. Obtenga más información sobre `security key-manager external enable` en el link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-enable.html["Referencia de comandos del ONTAP"^].
** En un entorno MetroCluster, si se configura la gestión de claves externa para la SVM de administrador, debe repetir `security key-manager external enable` el comando en el clúster de socios.


====
+
El siguiente comando habilita la gestión de claves externas `cluster1` con tres servidores de claves externos. El primer servidor de claves se especifica mediante su nombre de host y puerto, el segundo se especifica mediante una dirección IP y el puerto predeterminado, y el tercero se especifica mediante una dirección IPv6 y un puerto:

+
[listing]
----
clusterl::> security key-manager external enable -key-servers ks1.local:15696,10.0.0.10,[fd20:8b1e:b255:814e:32bd:f35c:832c:5a09]:1234 -client-cert AdminVserverClientCert -server-ca-certs AdminVserverServerCaCert
----
. Compruebe que todos los servidores KMIP configurados están conectados:
+
`security key-manager external show-status -node node_name -vserver SVM -key-server host_name|IP_address:port -key-server-status available|not-responding|unknown`

+
[NOTE]
====
El `security key-manager external show-status` comando reemplaza `security key-manager show -status` el comando. Obtenga más información sobre `security key-manager external show-status` en el link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-show-status.html["Referencia de comandos del ONTAP"^].

====
+
[listing]
----
cluster1::> security key-manager external show-status

Node  Vserver  Key Server                                     Status
----  -------  ---------------------------------------        -------------
node1
      cluster1
               10.0.0.10:5696                                 available
               fd20:8b1e:b255:814e:32bd:f35c:832c:5a09:1234   available
               ks1.local:15696                                available
node2
      cluster1
               10.0.0.10:5696                                 available
               fd20:8b1e:b255:814e:32bd:f35c:832c:5a09:1234   available
               ks1.local:15696                                available

6 entries were displayed.
----


.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-setup.html["configuración del administrador de claves de seguridad"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+key-manager+external["administrador de claves de seguridad externo"^]

