---
permalink: encryption-at-rest/encrypt-existing-volume-task.html 
sidebar: sidebar 
keywords: enabling, encryption, existing, volume, volume move start, command, volume encryption conversion start 
summary: Puede utilizar cualquiera de estos dos métodos para habilitar el cifrado en un volumen existente, utilizando el comando volume move start o el comando volume encryption conversion start. 
---
= Habilite el cifrado en un volumen existente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `volume move start` `volume encryption conversion start` comando o el comando para habilitar el cifrado en un volumen existente.

.Acerca de esta tarea
Puedes utilizar el  `volume encryption conversion start` Comando para habilitar el cifrado de un volumen existente "in situ", sin tener que moverlo a otra ubicación. Alternativamente, puede usar el comando  `volume move start` dominio.



== Habilite el cifrado en un volumen existente con el comando volume Encryption conversion start

Puedes utilizar el  `volume encryption conversion start` comando para habilitar el cifrado de un volumen existente "en su lugar", sin tener que mover el volumen a una ubicación diferente.

Después de iniciar una operación de conversión, debe completarse. Si se encuentra con un problema de rendimiento durante la operación, puede ejecutar `volume encryption conversion pause` el comando para pausar la operación y el `volume encryption conversion resume` comando para reanudarla.


NOTE: No se puede usar `volume encryption conversion start` para convertir un volumen de SnapLock.

.Pasos
. Habilitar el cifrado en un volumen existente:
+
`volume encryption conversion start -vserver SVM_name -volume volume_name`

+
Obtenga más información sobre `volume encryption conversion start` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-encryption-conversion-start.html["Referencia de comandos del ONTAP"^].

+
El siguiente comando habilita el cifrado en el volumen existente `vol1` :

+
[listing]
----
cluster1::> volume encryption conversion start -vserver vs1 -volume vol1
----
+
El sistema crea una clave de cifrado para el volumen. Los datos del volumen se cifran.

. Compruebe el estado de la operación de conversión:
+
`volume encryption conversion show`

+
Obtenga más información sobre `volume encryption conversion show` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-encryption-conversion-show.html["Referencia de comandos del ONTAP"^].

+
El siguiente comando muestra el estado de la operación de conversión:

+
[listing]
----
cluster1::> volume encryption conversion show

Vserver   Volume   Start Time           Status
-------   ------   ------------------   ---------------------------
vs1       vol1     9/18/2017 17:51:41   Phase 2 of 2 is in progress.
----
. Cuando finalice la operación de conversión, compruebe que el volumen esté habilitado para el cifrado:
+
`volume show -is-encrypted true`

+
Obtenga más información sobre `volume show` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html["Referencia de comandos del ONTAP"^].

+
El siguiente comando muestra los volúmenes cifrados en `cluster1`:

+
[listing]
----
cluster1::> volume show -is-encrypted true

Vserver  Volume  Aggregate  State  Type  Size  Available  Used
-------  ------  ---------  -----  ----  -----  --------- ----
vs1      vol1    aggr2     online    RW  200GB    160.0GB  20%
----


.Resultado
Si utiliza un servidor KMIP para almacenar las claves de cifrado de un nodo, ONTAP inserta automáticamente una clave de cifrado en el servidor al cifrar un volumen.



== Habilite el cifrado en un volumen existente con el comando volume Move start

Puede usar el `volume move start` comando para habilitar el cifrado mediante la transferencia de un volumen existente. Se puede usar el mismo agregado o uno diferente.

.Acerca de esta tarea
* A partir de ONTAP 9.8, se puede usar `volume move start` para habilitar el cifrado en un volumen SnapLock o FlexGroup.
* A partir de ONTAP 9.4, si habilita «`cc-mode`» al configurar el Administrador de claves integrado, los volúmenes que cree con el `volume move start` comando se cifran automáticamente. No es necesario especificar `-encrypt-destination true`.
* A partir de ONTAP 9.6, puede utilizar el cifrado a nivel de agregado con el fin de asignar claves al agregado que contiene para mover los volúmenes. Un volumen cifrado con una clave única se denomina _NVE volume_ (lo que significa que utiliza cifrado de volúmenes de NetApp). Un volumen cifrado con una clave de nivel de agregado se denomina _NAE volume_ (para el cifrado de agregados de NetApp). No se admiten los volúmenes de texto sin formato en los agregados de NAE.
* A partir de ONTAP 9.14.1, se puede cifrar un volumen raíz de SVM con NVE. Para obtener más información, consulte xref:configure-nve-svm-root-task.html[Configure el cifrado de volúmenes NetApp en un volumen raíz de SVM].


.Antes de empezar
Debe ser un administrador de clústeres para realizar esta tarea o un administrador de SVM a quien el administrador de clúster haya delegado esta autoridad.

link:delegate-volume-encryption-svm-administrator-task.html["Delegar la autoridad para ejecutar el comando volume move"]

.Pasos
. Mueva un volumen existente y especifique si el cifrado está habilitado en el volumen:
+
[cols="35,65"]
|===


| Para convertir... | Se usa este comando... 


 a| 
Un volumen de texto sin formato a un volumen NVE
 a| 
`volume move start -vserver _SVM_name_ -volume _volume_name_ -destination-aggregate _aggregate_name_ -encrypt-destination true`



 a| 
Un volumen NVE o un volumen sin texto en un volumen NAE (suponiendo que se habilite el cifrado a nivel de agregado en el destino)
 a| 
`volume move start -vserver _SVM_name_ -volume _volume_name_ -destination-aggregate _aggregate_name_ -encrypt-with-aggr-key true`



 a| 
Un volumen NAE a un volumen NVE
 a| 
`volume move start -vserver _SVM_name_ -volume _volume_name_ -destination-aggregate _aggregate_name_ -encrypt-with-aggr-key false`



 a| 
Un volumen NAE a un volumen de texto sin texto
 a| 
`volume move start -vserver _SVM_name_ -volume _volume_name_ -destination-aggregate _aggregate_name_ -encrypt-destination false -encrypt-with-aggr-key false`



 a| 
Un volumen NVE a un volumen de texto sin texto
 a| 
`volume move start -vserver _SVM_name_ -volume _volume_name_ -destination-aggregate _aggregate_name_ -encrypt-destination false`

|===
+
Obtenga más información sobre `volume move start` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-move-start.html["Referencia de comandos del ONTAP"^].

+
El siguiente comando convierte un volumen de texto sin formato denominado `vol1` en un volumen NVE:

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr2 -encrypt-destination true
----
+
Suponiendo que el cifrado a nivel de agregado está habilitado en el destino, el siguiente comando convierte un volumen NVE o de texto sin formato denominado `vol1` en un volumen NAE:

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr2 -encrypt-with-aggr-key true
----
+
El siguiente comando convierte un volumen de NAE llamado `vol2` en un volumen NVE:

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol2 -destination-aggregate aggr2 -encrypt-with-aggr-key false
----
+
El siguiente comando convierte un volumen NAE denominado `vol2` en un volumen de texto sin formato:

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol2 -destination-aggregate aggr2 -encrypt-destination false -encrypt-with-aggr-key false
----
+
El siguiente comando convierte un volumen NVE llamado `vol2` en un volumen de texto sin formato:

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol2 -destination-aggregate aggr2 -encrypt-destination false
----
. Vea el tipo de cifrado de volúmenes de clúster:
+
`volume show -fields encryption-type none|volume|aggregate`

+
 `encryption-type`El campo está disponible en ONTAP 9.6 y posterior.

+
Obtenga más información sobre `volume show` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html["Referencia de comandos del ONTAP"^].

+
El siguiente comando muestra el tipo de cifrado de los volúmenes en `cluster2`:

+
[listing]
----
cluster2::> volume show -fields encryption-type

vserver  volume  encryption-type
-------  ------  ---------------
vs1      vol1    none
vs2      vol2    volume
vs3      vol3    aggregate
----
. Compruebe que los volúmenes estén habilitados para el cifrado:
+
`volume show -is-encrypted true`

+
Obtenga más información sobre `volume show` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html["Referencia de comandos del ONTAP"^].

+
El siguiente comando muestra los volúmenes cifrados en `cluster2`:

+
[listing]
----
cluster2::> volume show -is-encrypted true

Vserver  Volume  Aggregate  State  Type  Size  Available  Used
-------  ------  ---------  -----  ----  -----  --------- ----
vs1      vol1    aggr2     online    RW  200GB    160.0GB  20%
----


.Resultado
Si utiliza un servidor KMIP para almacenar las claves de cifrado de un nodo, ONTAP inserta automáticamente una clave de cifrado en el servidor cuando se cifra un volumen.
