---
permalink: encryption-at-rest/encrypt-existing-volume-task.html 
sidebar: sidebar 
keywords: enabling, encryption, existing, volume, volume move start, command 
summary: Puede usar el comando volume move start para habilitar el cifrado mediante la transferencia de un volumen existente. Debe usar movimiento de volúmenes a partir de ONTAP 9.2 y versiones anteriores. Se puede usar el mismo agregado o uno diferente. 
---
= Habilite el cifrado en un volumen existente con el comando volume Move start
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `volume move start` comando para habilitar el cifrado mediante el movimiento de un volumen existente. Debe usar `volume move start` En ONTAP 9.2 y anteriores. Se puede usar el mismo agregado o uno diferente.

.Lo que necesitará
Debe ser un administrador de clústeres para realizar esta tarea o un administrador de SVM a quien el administrador de clúster haya delegado esta autoridad.

link:delegate-volume-encryption-svm-administrator-task.html["Delegar la autoridad para ejecutar el comando volume move"]

.Acerca de esta tarea
A partir de ONTAP 9.8, se puede utilizar `volume move start` Para habilitar el cifrado en un volumen de SnapLock o FlexGroup.

A partir de ONTAP 9.4, si activa "'cc-mode'" cuando configura el Administrador de claves incorporado, los volúmenes que crea con el `volume move start` el comando se cifra automáticamente. No es necesario que especifique `-encrypt-destination true`.

A partir de ONTAP 9.6, puede utilizar el cifrado a nivel de agregado con el fin de asignar claves al agregado que contiene para mover los volúmenes. Un volumen cifrado con una clave única se denomina _NVE volume_. Un volumen cifrado con una clave de nivel de agregado se denomina _NAE volume_ (para el cifrado de agregados de NetApp). No se admiten los volúmenes de texto sin formato en los agregados de NAE.

.Pasos
. Mueva un volumen existente y especifique si el cifrado está habilitado en el volumen:
+
[cols="35,65"]
|===


| Para convertir... | Se usa este comando... 


 a| 
Un volumen de texto sin formato a un volumen NVE
 a| 
`volume move start -vserver SVM_name -volume volume_name -destination-aggregate aggregate_name -encrypt-destination true`



 a| 
Un volumen NVE o un volumen sin texto en un volumen NAE (suponiendo que se habilite el cifrado a nivel de agregado en el destino)
 a| 
`volume move start -vserver SVM_name -volume volume_name -destination-aggregate aggregate_name -encrypt-with-aggr-key true`



 a| 
Un volumen NAE a un volumen NVE
 a| 
`volume move start -vserver SVM_name -volume volume_name -destination-aggregate aggregate_name -encrypt-with-aggr-key false`



 a| 
Volumen NAE a un volumen de texto sin formato
 a| 
`volume move start -vserver SVM_name -volume volume_name -destination-aggregate aggregate_name -encrypt-destination false -encrypt-with-aggr-key false`



 a| 
Un volumen NVE a un volumen de texto sin texto
 a| 
`volume move start -vserver SVM_name -volume volume_name -destination-aggregate aggregate_name -encrypt-destination false`

|===
+
Para obtener una sintaxis de comando completa, consulte la página de manual del comando.

+
El siguiente comando convierte un volumen de texto sin formato denominado `vol1` Para un volumen NVE:

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr2 -encrypt-destination true
----
+
Si asumimos que el cifrado a nivel de agregado está habilitado en el destino, el siguiente comando convierte un volumen NVE o de texto sin formato denominado `vol1` A un volumen de NAE:

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr2 -encrypt-with-aggr-key true
----
+
El siguiente comando convierte un volumen NAE llamado `vol2` Para un volumen NVE:

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol2 -destination-aggregate aggr2 -encrypt-with-aggr-key false
----
+
El siguiente comando convierte un volumen NAE llamado `vol2` a un volumen de texto sin formato:

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol2 -destination-aggregate aggr2 -encrypt-destination false -encrypt-with-aggr-key false
----
+
El siguiente comando convierte un volumen de NVE llamado `vol2` a un volumen de texto sin formato:

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol2 -destination-aggregate aggr2 -encrypt-destination false
----
. Vea el tipo de cifrado de volúmenes de clúster:
+
`volume show -fields encryption-type none|volume|aggregate`

+
La `encryption-type` Campo está disponible en ONTAP 9.6 y versiones posteriores.

+
Para obtener una sintaxis de comando completa, consulte la página de manual del comando.

+
El siguiente comando muestra el tipo de cifrado de volúmenes en `cluster2`:

+
[listing]
----
cluster2::> volume show -fields encryption-type

vserver  volume  encryption-type
-------  ------  ---------------
vs1      vol1    none
vs2      vol2    volume
vs3      vol3    aggregate
----
. Compruebe que los volúmenes estén habilitados para el cifrado:
+
`volume show -is-encrypted true`

+
Para obtener una sintaxis de comando completa, consulte la página de manual del comando.

+
El siguiente comando muestra los volúmenes cifrados en `cluster2`:

+
[listing]
----
cluster2::> volume show -is-encrypted true

Vserver  Volume  Aggregate  State  Type  Size  Available  Used
-------  ------  ---------  -----  ----  -----  --------- ----
vs1      vol1    aggr2     online    RW  200GB    160.0GB  20%
----


.Resultado
Si utiliza un servidor KMIP para almacenar las claves de cifrado de un nodo, ONTAP inserta automáticamente una clave de cifrado en el servidor al cifrar un volumen.
