---
permalink: encryption-at-rest/modify-external-key-server-96-later-task.html 
sidebar: sidebar 
keywords: modifying, external key management, server, properties 
summary: A partir de ONTAP 9.6, es posible usar el comando Security Key Manager external modify-Server para cambiar el tiempo de espera de I/o y el nombre de usuario de un servidor de gestión de claves externo. 
---
= Modificar las propiedades del servidor de administración de claves externas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.6, es posible usar `security key-manager external modify-server` el comando para cambiar el tiempo de espera de I/O y el nombre de usuario de un servidor de gestión de claves externo.

.Antes de empezar
* Debe ser un administrador de clúster o de SVM para ejecutar esta tarea.
* Se requieren privilegios avanzados para esta tarea.
* En un entorno de MetroCluster, debe repetir estos pasos en ambos clústeres para la SVM de administrador.


.Pasos
. En el sistema de almacenamiento, cambie al nivel de privilegio avanzado:
+
`set -privilege advanced`

. Modifique las propiedades del servidor de administración de claves externo para el clúster:
+
`security key-manager external modify-server -vserver admin_SVM -key-server host_name|IP_address:port,... -timeout 0...60 -username user_name`

+
[NOTE]
====
** El valor de tiempo de espera es el tiempo que tarda en establecerse la conexión con el servidor KMIP, expresado en segundos. Si especificas 0, no hay tiempo de espera y la solicitud de conexión puede esperar indefinidamente. Si especificas cualquier valor entre 1 y 60, la solicitud de conexión caduca si no se puede crear una conexión con el servidor de claves KMIP dentro del número de segundos especificado.
** Si modificas el nombre de usuario, se te pedirá que introduzcas una nueva contraseña.
** Si ejecutas el comando en la línea de comandos de inicio de sesión del clúster, `_admin_SVM_` por defecto se establece el SVM de administración del clúster actual. Debes ser el administrador del clúster para modificar las propiedades del servidor gestor de claves externo.


====
+
El siguiente comando cambia el valor de tiempo de espera a 45 segundos para el `cluster1` servidor de gestión de claves externo que escucha en el puerto predeterminado 5696:

+
[listing]
----
clusterl::> security key-manager external modify-server -vserver cluster1 -key-server ks1.local -timeout 45
----
. Modifica las propiedades del servidor del gestor de claves externo para un SVM:
+
`security key-manager external modify-server -vserver SVM -key-server host_name|IP_address:port,... -timeout 0...60 -username user_name`

+
[NOTE]
====
** El valor de tiempo de espera es el tiempo que tarda en establecerse la conexión con el servidor KMIP, expresado en segundos. Si especificas 0, no hay tiempo de espera y la solicitud de conexión puede esperar indefinidamente. Si especificas cualquier valor entre 1 y 60, la solicitud de conexión caduca si no se puede crear una conexión con el servidor de claves KMIP dentro del número de segundos especificado.
** Si modificas el nombre de usuario, se te pedirá que introduzcas una nueva contraseña.
** Si ejecutas el comando en la línea de comandos de inicio de sesión de SVM, `_SVM_` se establece por defecto en el SVM actual. Debes ser el administrador del clúster o del SVM para modificar las propiedades del servidor de gestor de claves externo.


====
+
El siguiente comando cambia el nombre de usuario y la contraseña `svm1` del servidor de gestión de claves externo que escucha en el puerto predeterminado 5696:

+
[listing]
----
svml::> security key-manager external modify-server -vserver svm11 -key-server ks1.local -username svm1user
Enter the password:
Reenter the password:
----
. Repita el último paso para todas las SVM adicionales.


.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-modify-server.html["administrador de claves de seguridad servidor de modificación externo"^]

