---
permalink: encryption-at-rest/move-encrypted-volume-task.html 
sidebar: sidebar 
keywords: moving, encrypted, volume 
summary: Es posible usar el comando volume move start para mover un volumen cifrado. El volumen movido puede residir en el mismo agregado o en otra diferente. 
---
= Mueva un volumen cifrado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `volume move start` comando para mover un volumen cifrado. El volumen movido puede residir en el mismo agregado o en otra diferente.

.Lo que necesitará
Debe ser un administrador de clústeres para realizar esta tarea o un administrador de SVM a quien el administrador de clúster haya delegado esta autoridad.

link:delegate-volume-encryption-svm-administrator-task.html["Delegar la autoridad para ejecutar el comando volume move"]

.Acerca de esta tarea
El movimiento generará un error si el nodo de destino o el volumen de destino no admiten el cifrado de volúmenes.

La `-encrypt-destination` opción para `volume move start` el valor predeterminado es true para los volúmenes cifrados. Si se requiere que se especifique explícitamente que no se desea cifrar el volumen de destino, se garantiza que no se descifren accidentalmente los datos del volumen.

.Pasos
. Mueva un volumen de cifrado existente y deje los datos en el volumen cifrado:
+
`volume move start -vserver SVM_name -volume volume_name -destination-aggregate aggregate_name`

+
Para obtener una sintaxis de comando completa, consulte la página de manual del comando.

+
El siguiente comando mueve un volumen existente llamado `vol1` al agregado de destino `aggr3` y deja los datos del volumen cifrados:

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr3
----
. Compruebe que el volumen esté habilitado para el cifrado:
+
`volume show -is-encrypted true`

+
Para obtener una sintaxis de comando completa, consulte la página de manual del comando.

+
El siguiente comando muestra los volúmenes cifrados en `cluster1`:

+
[listing]
----
cluster1::> volume show -is-encrypted true

Vserver  Volume  Aggregate  State  Type  Size  Available  Used
-------  ------  ---------  -----  ----  -----  --------- ----
vs1      vol1    aggr3     online    RW  200GB    160.0GB  20%
----

