---
permalink: encryption-at-rest/purge-data-encrypted-asynchronous-snapmirror-task.html 
sidebar: sidebar 
keywords: securely, purging, scrub, data, encrypted, volume, nve, netapp, volume encryption, snapmirror, asynchronous 
summary: 'A partir de ONTAP 9.8, puede utilizar la purga segura para "limpiar" datos sin interrupciones en volúmenes habilitados para NVE con una relación asíncrona de SnapMirror.' 
---
= Purgue los datos de forma segura en un volumen cifrado con una relación de SnapMirror asíncrono
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.8, puede utilizar una purga segura para datos «crub» sin interrupciones en volúmenes habilitados para NVE con una relación asíncrona de SnapMirror.

.Antes de empezar
* Para realizar esta tarea, debe ser un administrador de clústeres.
* Se requieren privilegios avanzados para esta tarea.


.Acerca de esta tarea
La purga segura puede tardar de varios minutos a varias horas en completarse, dependiendo de la cantidad de datos de los archivos eliminados. Puede utilizar el `volume encryption secure-purge show` comando para ver el estado de la operación. Puede utilizar el `volume encryption secure-purge abort` comando para finalizar la operación.


NOTE: Para realizar una purga segura en un host SAN, debe eliminar todo el LUN que contiene los archivos que desea purgar, o debe poder perforar agujeros en la LUN para los bloques que pertenecen a los archivos que desea purgar. Si no puede eliminar la LUN, o el sistema operativo del host no admite orificios de perforación en la LUN, no puede realizar una purga segura.

.Pasos
. En el sistema de almacenamiento, cambie al nivel de privilegio avanzado:
+
`set -privilege advanced`

. Elimine los archivos o la LUN que desea purgar de forma segura.
+
** En un cliente NAS, elimine los archivos que desea purgar de forma segura.
** En un host SAN, elimine la LUN que desea purgar o perforar agujeros en la LUN de los bloques que pertenecen a los archivos que desea purgar.


. Prepare el volumen de destino en la relación asíncrona para que se purgue de forma segura:
+
`volume encryption secure-purge start -vserver _SVM_name_ -volume _volume_name_ -prepare true`

+
Repita este paso con cada volumen de la relación de SnapMirror asíncrono.

. Si los archivos que desea purgar de forma segura están en las copias snapshot, elimine las copias snapshot:
+
`snapshot delete -vserver _SVM_name_ -volume _volume_name_ -snapshot`

. Si los archivos que desea purgar de forma segura están en las copias snapshot básicas, haga lo siguiente:
+
.. Cree una copia Snapshot en el volumen de destino en la relación de SnapMirror asíncrono:
+
`volume snapshot create -snapshot snapshot_name -vserver _SVM_name_ -volume _volume_name_`

.. Actualización de SnapMirror para hacer avanzar la copia snapshot básica:
+
`snapmirror update -source-snapshot _snapshot_name_ -destination-path _destination_path_`

+
Repita este paso con cada volumen de la relación de SnapMirror asíncrono.

.. Repita los pasos (a) y (b) igual al número de copias Snapshot base y una.
+
Por ejemplo, si tiene dos copias Snapshot base, deberá repetir los pasos (a) y (b) tres veces.

.. Compruebe que la copia Snapshot básica está presente:
 +
`snapshot show -vserver _SVM_name_ -volume _volume_name_`
.. Elimine la copia Snapshot básica:
 +
`snapshot delete -vserver _svm_name_ -volume _volume_name_ -snapshot snapshot`


. Elimine de forma segura los archivos eliminados:
+
`volume encryption secure-purge start -vserver _svm_name_ -volume _volume_name_`

+
Repita este paso con cada volumen de la relación de SnapMirror asíncrono.

+
El siguiente comando purga de forma segura los archivos eliminados de «'vol1'» de la SVM «'vs1'»:

+
[listing]
----
cluster1::> volume encryption secure-purge start -vserver vs1 -volume vol1
----
. Compruebe el estado de la operación de purga segura:
+
`volume encryption secure-purge show`


