---
permalink: encryption-at-rest/purge-data-encrypted-volume-without-snapmirror-task.html 
sidebar: sidebar 
keywords: secure, purge, scrub, data, encrypted, volume, nve, netapp, volume, encryption, snapmirror 
summary: 'A partir de ONTAP 9.4, puede utilizar la purga segura para "borrar" datos sin interrupciones en los volúmenes habilitados para NVE.' 
---
= Borrar datos de un volumen ONTAP cifrado sin una relación SnapMirror
:allow-uri-read: 


[role="lead"]
A partir de ONTAP 9.4, puede utilizar la purga segura para obtener datos «crub» sin interrupciones en volúmenes con NVE habilitado.

.Acerca de esta tarea
La purga segura puede tardar de varios minutos a varias horas en completarse, dependiendo de la cantidad de datos de los archivos eliminados. Puede usar `volume encryption secure-purge show` el comando para ver el estado de la operación. Puede usar `volume encryption secure-purge abort` el comando para finalizar la operación.


NOTE: Para realizar una purga segura en un host SAN, debe eliminar todo el LUN que contiene los archivos que desea purgar, o debe poder perforar agujeros en la LUN para los bloques que pertenecen a los archivos que desea purgar. Si no puede eliminar la LUN, o el sistema operativo del host no admite orificios de perforación en la LUN, no puede realizar una purga segura.

.Antes de empezar
* Para realizar esta tarea, debe ser un administrador de clústeres.
* Se requieren privilegios avanzados para esta tarea.


.Pasos
. Elimine los archivos o la LUN que desea purgar de forma segura.
+
** En un cliente NAS, elimine los archivos que desea purgar de forma segura.
** En un host SAN, elimine la LUN que desea purgar o perforar agujeros en la LUN de los bloques que pertenecen a los archivos que desea purgar.


. En el sistema de almacenamiento, cambie al nivel de privilegio avanzado:
+
`set -privilege advanced`

. Si los archivos que desea purgar de forma segura están en instantáneas, elimine las instantáneas:
+
`snapshot delete -vserver _SVM_name_ -volume _volume_name_ -snapshot`

. Elimine de forma segura los archivos eliminados:
+
`volume encryption secure-purge start -vserver _SVM_name_ -volume _volume_name_`

+
El siguiente comando purga de forma segura los archivos eliminados en `vol1` la SVM``vs1``:

+
[listing]
----
cluster1::> volume encryption secure-purge start -vserver vs1 -volume vol1
----
. Compruebe el estado de la operación de purga segura:
+
`volume encryption secure-purge show`


