---
permalink: encryption-at-rest/purge-data-encrypted-volume-synchronous-snapmirror-task.html 
sidebar: sidebar 
keywords: secure, purge, scrub, data, encrypted, volume, nve, netapp, volume encryption, snapmirror, synchronous 
summary: A partir de ONTAP 9.8, puede usar la purga segura para «depurar» datos sin interrupciones en los volúmenes con NVE habilitados con una relación síncrona de SnapMirror. 
---
= Eliminar datos de un volumen ONTAP cifrado con una relación sincrónica de SnapMirror
:allow-uri-read: 


[role="lead"]
A partir de ONTAP 9.8, puede utilizar una purga segura para «depurar» datos sin interrupciones en los volúmenes con NVE habilitados con una relación síncrona de SnapMirror.

.Acerca de esta tarea
Una purga segura puede tardar de varios minutos a varias horas en completarse, dependiendo de la cantidad de datos de los archivos eliminados. Puede usar `volume encryption secure-purge show` el comando para ver el estado de la operación. Puede usar `volume encryption secure-purge abort` el comando para finalizar la operación.


NOTE: Para realizar una purga segura en un host SAN, debe eliminar todo el LUN que contiene los archivos que desea purgar, o debe poder perforar agujeros en la LUN para los bloques que pertenecen a los archivos que desea purgar. Si no puede eliminar la LUN, o el sistema operativo del host no admite orificios de perforación en la LUN, no puede realizar una purga segura.

.Antes de empezar
* Para realizar esta tarea, debe ser un administrador de clústeres.
* Se requieren privilegios avanzados para esta tarea.


.Pasos
. En el sistema de almacenamiento, cambie al nivel de privilegio avanzado:
+
`set -privilege advanced`

. Elimine los archivos o la LUN que desea purgar de forma segura.
+
** En un cliente NAS, elimine los archivos que desea purgar de forma segura.
** En un host SAN, elimine la LUN que desea purgar o perforar agujeros en la LUN de los bloques que pertenecen a los archivos que desea purgar.


. Prepare el volumen de destino en la relación asíncrona para que se purgue de forma segura:
+
`volume encryption secure-purge start -vserver <SVM_name> -volume <volume_name> -prepare true`

+
Repita este paso para el otro volumen de la relación síncrona de SnapMirror.

. Si los archivos que desea purgar de forma segura están en instantáneas, elimine las instantáneas:
+
`snapshot delete -vserver <SVM_name> -volume <volume_name> -snapshot <snapshot>`

. Si el archivo de depuración segura está en las instantáneas base o comunes, actualice SnapMirror para mover la instantánea común hacia delante:
+
`snapmirror update -source-snapshot <snapshot_name> -destination-path <destination_path>`

+
Hay dos instantáneas comunes, por lo que este comando debe emitirse dos veces.

. Si el archivo de purga segura se encuentra en la snapshot coherente con las aplicaciones, elimine la snapshot de ambos volúmenes en la relación síncrona de SnapMirror:
+
`snapshot delete -vserver <SVM_name> -volume <volume_name> -snapshot <snapshot>`

+
Ejecute este paso en ambos volúmenes.

. Elimine de forma segura los archivos eliminados:
+
`volume encryption secure-purge start -vserver <SVM_name> -volume <volume_name>`

+
Repita este paso en cada volumen de la relación síncrona de SnapMirror.

+
El siguiente comando purga de forma segura los archivos eliminados en «'vol1'» en la SVM «'vs1'».

+
[listing]
----
cluster1::> volume encryption secure-purge start -vserver vs1 -volume vol1
----
. Compruebe el estado de la operación de purga segura:
+
`volume encryption secure-purge show`


