---
permalink: encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html 
sidebar: sidebar 
keywords: restoring, onboard, key management encryption 
summary: En ocasiones, es posible que deba restaurar una clave de cifrado de gestión de claves incorporada. Una vez que haya verificado que es necesario restaurar una clave, puede configurar el gestor de claves incorporado para restaurar la clave. 
---
= Restaure las claves de cifrado de gestión de claves incorporadas en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ocasionalmente, es posible que necesite restaurar una clave de cifrado de administración de claves incorporada.  Una vez que haya verificado que es necesario restaurar una clave, puede configurar el Administrador de claves integrado para restaurar la clave. El procedimiento que sigue para restaurar sus claves de cifrado de administración de claves integrado varía según su versión de ONTAP.

.Antes de empezar
* Elimina la base de datos del administrador de claves externo si usas NSE con un servidor KMIP externo. Para más detalles, consultelink:delete-key-management-database-task.html["Transición de la gestión de claves externa a la gestión de claves integrada de ONTAP"] .
* Para realizar esta tarea, debe ser un administrador de clústeres.



NOTE: Si utiliza NSE en un sistema con un módulo Flash Cache, también debe habilitar NVE o NAE. NSe no cifra los datos que residen en el módulo de Flash Cache.



== ONTAP 9,6 y versiones posteriores


IMPORTANT: Si ejecuta ONTAP 9,8 o una versión posterior y el volumen raíz está cifrado, siga el procedimiento para <<ontap-9-8>>.

. Compruebe que la clave debe restaurarse: +
`security key-manager key query -node _node_`
+
Obtenga más información sobre `security key-manager key query` en el link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-query.html["Referencia de comandos del ONTAP"^].

. Restaurar la clave: +
`security key-manager onboard sync`
+
Obtenga más información sobre `security key-manager onboard sync` en el link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-sync.html["Referencia de comandos del ONTAP"^].

. En la solicitud de contraseña, introduzca la clave de acceso de gestión de claves incorporada para el clúster.




== ONTAP 9,8 o posterior con un volumen raíz cifrado

Si ejecuta ONTAP 9.8 y versiones posteriores y el volumen raíz está cifrado, debe configurar una clave de recuperación de gestión de claves incorporada con el menú de arranque. Este proceso también es necesario si realiza un reemplazo del soporte de arranque.

. Inicie el nodo en el menú de inicio y seleccione la opción `(10) Set onboard key management recovery secrets`.
. Introduzca `y` para utilizar esta opción.
. En el aviso de, introduzca la clave de acceso de gestión de claves incorporada para el clúster.
. En el aviso, introduzca los datos de la clave de backup.
+
Después de ingresar los datos de la clave de respaldo, el nodo regresa al menú de arranque.

. En el menú de inicio, seleccione Opción `(1) Normal Boot`.




== ONTAP 9,5 y anteriores

. Compruebe que la clave debe restaurarse: +
`security key-manager key show`
. Restaurar la clave: +
`security key-manager setup -node _node_`
+
Obtenga más información sobre `security key-manager setup` en ellink:https://docs.netapp.com/us-en/ontap-cli-9161/security-key-manager-setup.html["Referencia de comandos del ONTAP"^] .

. En la solicitud de contraseña, introduzca la clave de acceso de gestión de claves incorporada para el clúster.

