---
permalink: encryption-at-rest/restore-external-encryption-keys-93-later-task.html 
sidebar: sidebar 
keywords: restoring, external key management, encryption keys 
summary: 'Puede restaurar manualmente las claves de cifrado de gestión de claves externas y "pularlas" en un nodo diferente. Tal vez desee hacer esto si va a reiniciar un nodo que estaba inactivo temporalmente cuando creó las claves para el clúster.' 
---
= Restaurar claves de cifrado de administración de claves externas de ONTAP
:allow-uri-read: 


[role="lead"]
Puede restaurar manualmente claves de cifrado de gestión de claves externas e insertarlas en otro nodo. Tal vez desee hacer esto si va a reiniciar un nodo que estaba inactivo temporalmente cuando creó las claves para el clúster.

.Acerca de esta tarea
En ONTAP 9.6 y posterior, puede utilizar el `security key-manager key query -node node_name` comando para verificar si su clave necesita ser restaurada.

En ONTAP 9, 5 y anteriores, puede utilizar el `security key-manager key show` comando para verificar si su clave necesita ser restaurada.


NOTE: Si utiliza NSE en un sistema con un módulo Flash Cache, también debe habilitar NVE o NAE. NSe no cifra los datos que residen en el módulo de Flash Cache.

Obtenga más información sobre `security key-manager key query` en el link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-query.html["Referencia de comandos del ONTAP"^].

.Antes de empezar
Debe ser un administrador de clúster o de SVM para ejecutar esta tarea.

.Pasos
. Si ejecuta ONTAP 9.8 o una versión posterior y el volumen raíz está cifrado, haga lo siguiente:
+
Si está ejecutando ONTAP 9.7 o una versión anterior, o si está ejecutando ONTAP 9.8 o una versión posterior y el volumen raíz no está cifrado, omita este paso.

+
.. Establezca los arranques: + +
`setenv kmip.init.ipaddr <ip-address>`
`setenv kmip.init.netmask <netmask>` + +
`setenv kmip.init.gateway <gateway>` + +
`setenv kmip.init.interface e0M`
`boot_ontap`
.. Inicie el nodo en el menú de inicio y seleccione la opción `(11) Configure node for external key management`.
.. Siga las instrucciones para introducir el certificado de gestión.
+
Una vez introducida toda la información del certificado de gestión, el sistema vuelve al menú de arranque.

.. En el menú de inicio, seleccione Opción `(1) Normal Boot`.


. Restaure la clave:
+
[cols="35,65"]
|===


| Para esta versión de ONTAP... | Se usa este comando... 


 a| 
ONTAP 9,6 y versiones posteriores
 a| 
`security key-manager external restore -vserver SVM -node node -key-server host_name|IP_address:port -key-id key_id -key-tag key_tag`



 a| 
ONTAP 9,5 y anteriores
 a| 
`security key-manager restore -node node -address IP_address -key-id key_id -key-tag key_tag`

|===
+
[NOTE]
====
`node` por defecto en todos los nodos.

Este comando no es compatible cuando la gestión de claves incorporada está habilitada.

====
+
El siguiente comando de la ONTAP 9.6 restaura las claves de autenticación de gestión de claves externa en todos los nodos `cluster1` de :

+
[listing]
----
clusterl::> security key-manager external restore
----


.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-restore.html["Restauración externa del administrador de claves de seguridad"^]

