---
permalink: encryption-at-rest/transition-external-key-from-onboard-key-task.html 
sidebar: sidebar 
keywords: transitioning, external key management, onboard key management 
summary: Si desea cambiar a la gestión de claves externas desde la gestión de claves incorporada, debe eliminar la configuración de gestión de claves incorporada para poder habilitar la gestión de claves externas. 
---
= Transición a la gestión de claves externas desde la gestión de claves incorporada
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea cambiar a la gestión de claves externas desde la gestión de claves incorporada, debe eliminar la configuración de gestión de claves incorporada para poder habilitar la gestión de claves externas.

.Antes de empezar
* Para el cifrado basado en hardware, debe restablecer las claves de datos de todas las unidades FIPS o SED a su valor predeterminado.
+
link:return-seds-unprotected-mode-task.html["Devolver una unidad FIPS o SED al modo sin protección"]

* Para el cifrado basado en software, debe descifrar todos los volúmenes.
+
link:unencrypt-volume-data-task.html["Descifrar los datos de volúmenes"]

* Para realizar esta tarea, debe ser un administrador de clústeres.


.Paso
. Elimine la configuración integrada de gestión de claves para un clúster:
+
[cols="35,65"]
|===


| Para esta versión de ONTAP... | Se usa este comando... 


 a| 
ONTAP 9.6 y posteriores
 a| 
`security key-manager onboard disable -vserver SVM`



 a| 
ONTAP 9,5 y anteriores
 a| 
`security key-manager delete-key-database`

|===


Para obtener una sintaxis completa del comando, consulte link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Páginas de manual de ONTAP"].
