---
permalink: s3-multiprotocol/create-nas-bucket-task.html 
sidebar: sidebar 
keywords: s3, svm, bucket, object, server, versioning, protocol, filesystems, nas, directories 
summary: Un bloque NAS de S3 es una asignación entre un nombre de bloque de S3 y una ruta NAS. 
---
= Crear un depósito NAS de ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un bucket NAS de S3 es una asignación entre el nombre de un bucket de S3 y una ruta NAS. Los buckets NAS de S3 permiten proporcionar acceso S3 a cualquier parte de un espacio de nombres SVM que tenga volúmenes y una estructura de directorios existentes.

.Antes de empezar
* Un servidor de objetos S3 está configurado en una SVM que contiene datos NAS.
* Los datos del NAS se ajustan a la link:nas-data-requirements-client-access-reference.html["Requisitos para el acceso de clientes S3"].


.Acerca de esta tarea
Puede configurar cubos NAS de S3 para especificar cualquier conjunto de archivos y directorios dentro del directorio raíz de la SVM.

También puede establecer políticas de bloques que permitan o inpermitan el acceso a datos NAS en función de cualquier combinación de estos parámetros:

* Archivos y directorios
* Permisos de usuario y grupo
* S3 operaciones


Por ejemplo, podrías querer configurar una política de bucket que otorgue acceso de solo lectura a los datos a un gran grupo de usuarios y otra política de bucket que permita a un grupo limitado realizar operaciones en un subconjunto de esos datos.

A partir de ONTAP 9.18.1, puedes crear buckets NAS que permiten que las aplicaciones accedan a los datos en los volúmenes de FlexCache usando el protocolo S3. Todos los nodos del clúster deben estar ejecutando ONTAP 9.18.1 o una versión posterior. Antes de que puedas acceder a un volumen de FlexCache usando el protocolo S3, debes configurar la opción `-is-s3-enabled` en `true` link:../flexcache/create-volume-task.html["en el FlexCache volumen"]. El parámetro está configurado en `false` por defecto.

A partir de ONTAP 9.17.1, puede vincular directamente un bucket NAS de S3 a un volumen en lugar de a la ruta de unión. De forma predeterminada, un bucket S3 en un volumen NAS se asocia a una ruta de unión, que un administrador de ONTAP puede modificar en cualquier momento. Estos cambios pueden interrumpir las operaciones del bucket S3. A partir de ONTAP 9.17.1, puede usar  `-is-nas-path-mutable false` opción con el  `vserver object-store-server bucket create` Comando en la CLI de ONTAP para habilitar la vinculación del depósito NAS de S3 a un volumen. De forma predeterminada,  `-is-nas-path-mutable` está configurado para  `true` .

Dado que los "buckets" de S3 NAS son asignaciones y no buckets de S3, las siguientes propiedades de los buckets de S3 estándar no se aplican a los buckets de S3 NAS.

* *Aggr-list \ aggr-list-multiplicador \ Storage-service-level \ volume \ size \ exclude-aggr-list \ qos-policy-group* + no se crean volúmenes ni qtree al configurar cubos NAS S3.
* *role \ is -protected \ is -protected-on-ontap \ is -protected-on-cloud* + Los buckets NAS de S3 no están protegidos ni reflejados mediante SnapMirror S3, sino que utilizan la protección SnapMirror normal disponible en granularidad de volumen.
* *Versioning-state* + los volúmenes NAS suelen tener tecnología de instantáneas disponible para guardar diferentes versiones. Sin embargo, el control de versiones no está disponible actualmente en bloques NAS de S3.
* *Las estadísticas lógicas usadas \ object-count* + equivalentes están disponibles para los volúmenes NAS a través de los comandos de volumen.
* *objetos multiparte* + A partir de ONTAP 9.16.1, los objetos multiparte se admiten en los depósitos NAS de S3 cuando link:../flexgroup/enable-adv-capacity-flexgroup-task.html["equilibrado de capacidad avanzado"] Está habilitado en el volumen FlexGroup subyacente. El balanceo de capacidad avanzado solo se puede habilitar en volúmenes FlexGroup . No se puede habilitar en volúmenes FlexVol .


.Pasos
Puede utilizar el Administrador del sistema o la CLI de ONTAP para crear un depósito NAS.

[role="tabbed-block"]
====
.System Manager
--
Agrega un nuevo bucket S3 NAS en una máquina virtual de almacenamiento habilitada para NAS.

. Haga clic en *almacenamiento > Cuchos* y, a continuación, haga clic en *Agregar*.
. Introduzca un nombre para el bloque NAS de S3 y seleccione la máquina virtual de almacenamiento, no introduzca un tamaño y, a continuación, haga clic en *más opciones*.
. Introduzca un nombre de ruta válido o haga clic en examinar para seleccionar de una lista de nombres de ruta válidos. + cuando se introduce un nombre de ruta válido, las opciones que no son relevantes para la configuración de NAS S3 están ocultas.
. Si ya ha asignado usuarios S3 a usuarios NAS y ha creado grupos, puede configurar sus permisos y, a continuación, hacer clic en *Guardar*. + antes de configurar permisos en este paso, debe haber asignado usuarios de S3 a usuarios NAS.


De lo contrario, haga clic en *Guardar* para completar la configuración de bloque NAS S3.

--
.CLI
--
. Cree un depósito NAS S3 en una SVM que contenga sistemas de archivos NAS. + 
`vserver object-store-server bucket create -vserver <svm_name> -bucket <bucket_name> -type nas -nas-path <junction_path> -is-nas-path-mutable true|false [-comment <text>]`
+
Ejemplo 1: Crear un depósito NAS S3

+
`cluster1::> vserver object-store-server bucket create -bucket testbucket -type nas -path /vol1`

+
Ejemplo 2: Crear un depósito NAS S3 y vincularlo a un volumen

+
`vserver object-store-server bucket create -vserver vs1 -bucket nasbucket1 -type nas -nas-path /pathA/dir1 -is-nas-path-mutable false`



--
====