---
permalink: s3-multiprotocol/index.html 
sidebar: sidebar 
keywords: multiprotocol, s3, configuration, overview, nfs, smb, multipart 
summary: A partir de ONTAP 9.12.1, puede permitir que los clientes que ejecutan el protocolo S3 accedan a los mismos datos que los clientes que utilizan los protocolos NFS y SMB sin necesidad de volver a formatear. 
---
= Compatibilidad multiprotocolo de S3 en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.12.1, puede permitir que los clientes que ejecutan el protocolo S3 accedan a los mismos datos que los clientes que utilizan los protocolos NFS y SMB sin necesidad de volver a formatear. Esta funcionalidad permite seguir proporcionando datos de NAS a los clientes NAS, a la vez que presenta datos de objetos a clientes S3 que ejecutan aplicaciones S3 (como la minería de datos y la inteligencia artificial).

La funcionalidad multiprotocolo de S3 aborda dos casos prácticos:

. Acceso a los datos NAS existentes mediante clientes S3
+
Si sus datos existentes se crearon con clientes NAS tradicionales (NFS o SMB) y están ubicados en volúmenes NAS (volúmenes FlexVol o FlexGroup), ahora puede utilizar herramientas de análisis en clientes S3 para acceder a estos datos.

. Almacenamiento back-end para clientes modernos capaces de realizar I/o mediante protocolos NAS y S3
+
Ahora puede proporcionar acceso integrado para aplicaciones como Spark y Kafka que pueden leer y escribir los mismos datos utilizando los protocolos NAS y S3.





== Funcionamiento del soporte multiprotocolo de S3

La compatibilidad multiprotocolo de ONTAP le permite presentar el mismo conjunto de datos como una jerarquía de archivos o como objetos en un bloque. Para ello, ONTAP crea “bloques NAS de S3” que permiten a los clientes de S3 crear, leer, eliminar y enumerar archivos en un almacenamiento NAS usando solicitudes de objetos de S3. Esta asignación se ajusta a la configuración de seguridad NAS, observando los permisos de acceso a archivos y directorios, así como escribiendo en la pista de auditoría de seguridad según sea necesario.

Esta asignación se logra presentando una jerarquía de directorios NAS especificada como bloque de S3. Cada archivo de la jerarquía de directorio se representa como un objeto S3 cuyo nombre es relativo del directorio asignado hacia abajo, con límites de directorio representados por el carácter de barra diagonal ('/').

Los usuarios S3 definidos por ONTAP pueden acceder a este almacenamiento, según lo establecido por las políticas de buckets definidas para el bucket que se asigna al directorio NAS. Para que esto sea posible, deben definirse las asignaciones entre los usuarios de S3 y los usuarios SMB/NFS. Las credenciales del usuario SMB/NFS se utilizarán para la comprobación de permisos NAS y se incluirán en los registros de auditoría resultantes de estos accesos.

Cuando los clientes SMB o NFS lo crean, un archivo se coloca inmediatamente en un directorio y, por lo tanto, es visible para los clientes antes de escribir ningún dato en él. Los clientes S3 esperan una semántica diferente, en la que el nuevo objeto no esté visible en el espacio de nombres hasta que todos sus datos se hayan escrito. Esta asignación de S3 a almacenamiento NAS crea archivos mediante la semántica de S3, y mantiene los archivos invisibles de forma externa hasta que finaliza el comando de creación de S3.



== Protección de datos para bloques NAS de S3

Los “bloques” NAS de S3 son simplemente asignaciones de datos NAS para clientes de S3, no son bloques S3 estándar. Por lo tanto, no es necesario proteger buckets NAS de S3 utilizando la funcionalidad de NetApp SnapMirror S3. En su lugar, puede proteger volúmenes que contengan bloques NAS de S3 MB mediante la replicación de volúmenes asíncrona de SnapMirror. No se admite la recuperación ante desastres síncrona o máquina virtual de almacenamiento de SnapMirror.

A partir de la versión 9.14.1 de ONTAP, los buckets NAS de S3 se admiten en agregados reflejados y no reflejados para las configuraciones de MetroCluster IP y FC.

Obtenga más información link:../data-protection/snapmirror-disaster-recovery-concept.html#data-protection-relationships["SnapMirror asíncrono"]sobre .



== Auditoría de bloques NAS de S3

Dado que los bloques NAS de S3 no son bloques S3 convencionales, la auditoría de S3 no se puede configurar para auditar el acceso entre ellos. Más información sobre link:../s3-audit/index.html["Auditoría de S3"].

No obstante, los archivos y directorios NAS que se asignan en bloques NAS de S3 pueden auditarse para eventos de acceso mediante procedimientos de auditoría ONTAP convencionales. Por lo tanto, las operaciones de S3 pueden activar eventos de auditoría de NAS, con las siguientes excepciones:

* Si la configuración de la política de S3 (grupo o política de bloques) deniega el acceso del cliente S3, no se inicia la auditoría de NAS para el evento. Esto se debe a que se comprueban los permisos de S3 antes de poder realizar comprobaciones de auditoría de SVM.
* Si el archivo de destino de una solicitud Get de S3 tiene un tamaño 0, se devuelve 0 contenido a la solicitud Get y el acceso de lectura no se registra.
* Si el archivo de destino de una solicitud Get de S3 se encuentra en una carpeta para la que el usuario no tiene permisos de recorrido, el intento de acceso falla y el evento no se registra.


Obtenga más información link:../nas-audit/index.html["Auditoría de eventos NAS en SVM"]sobre .



== Carga de varias partes de objeto

A partir de ONTAP 9.16.1, la carga de varias partes de objetos es compatible en bloques NAS de S3 cuando link:../flexgroup/enable-adv-capacity-flexgroup-task.html["equilibrado de capacidad avanzado"] se habilita en el volumen FlexGroup subyacente.

La carga de varias partes de objetos en el almacenamiento de archivos NAS permite a un cliente de protocolo S3 cargar un objeto grande como piezas más pequeñas. La carga de varias partes de objetos tiene las siguientes ventajas:

* Permite cargar objetos en paralelo.
* En caso de que se produzca un error de carga o una pausa, solo se deberán cargar las piezas que aún no se hayan cargado. No es necesario reiniciar la carga del objeto completo.
* Si el tamaño del objeto no se conoce por adelantado (por ejemplo, cuando todavía se escribe un objeto grande), los clientes pueden comenzar a cargar partes del objeto inmediatamente y completar la carga después de que se haya creado todo el objeto.



NOTE: Los objetos con varias partes en bloques NAS de S3 deben alinearse con tamaños de pieza de 1MB. Por ejemplo, una pieza puede ser 4MB o 4GB o un tamaño similar. Una pieza no puede utilizar tamaños de subMB, como 4,5MB o 4000,5MB.

La carga de varias partes admite las siguientes S3 acciones:

* AbortMultipartUpload
* CompleteMultipartUpload
* CreateMultipartUpload
* ListMultipartUpload
* UploadPart



NOTE: LA OBTENCIÓN por número de pieza («PARTNUMBER=xx») no es compatible con los bloques NAS S3. En su lugar, se devolverá el objeto completo.



== Interoperabilidad con S3 y NAS

Los bloques NAS de ONTAP S3 admiten las funcionalidades estándar de NAS y S3, a excepción de las enumeradas aquí.



=== La funcionalidad NAS no es compatible actualmente con bloques NAS de S3

Nivel de capacidad de FabricPool:: S3 Los bloques NAS no pueden configurarse como nivel de capacidad para FabricPool.




=== Acciones y funcionalidad de S3 no admitidas actualmente por buckets NAS de S3

Acciones::
+
--
* ByPassGovernanceRetention
* CopyObject
* DeleteBucketLifecycleConfiguration
* GetBucketLifecycleConfiguration
* GetBucketObjectLockConfiguration
* GetBucketVersioning
* GetObjectRetention
* Control de versiones de lista
* ListObjectVersions
* PutBucketLifecycleConfiguration
* PutBucketVersioning
* PutObjectLockConfiguration
* PutObjectRetention


--



NOTE: Estas acciones de S3 no son compatibles específicamente cuando se utiliza S3 en bloques de NAS de S3. Cuando se utilizan cubos S3 nativos, estas acciones son link:../s3-config/ontap-s3-supported-actions-reference.html["compatible con normalidad"].

Metadatos de usuario de AWS::
+
--
* Para ONTAP 9.15.1 y versiones anteriores, los pares clave-valores recibidos como parte de los metadatos del usuario S3 no se almacenan en el disco junto con los datos de los objetos.
* Para ONTAP 9.15.1 y versiones anteriores, se ignoran los encabezados de solicitud con el prefijo “x-amz-meta”.


--
Etiquetas de AWS::
+
--
* Para ONTAP 9.15.1 y versiones anteriores en las solicitudes PUT y Multipart Initiate, se ignoran las cabeceras con el prefijo «x-amz-tagging».
* Para ONTAP 9.15.1 y versiones anteriores, las solicitudes de actualización de etiquetas en un archivo existente (solicitudes PUT, GET y Delete con la cadena de consulta de etiquetado) se rechazan con un error.


--
Creación de versiones:: No es posible especificar el control de versiones en la configuración de asignación de bloques.
+
--
* Las solicitudes que incluyen especificaciones de versión no nulas (el ID de versión=cadena de consulta xyz) reciben respuestas de error.
* Las solicitudes que afectan al estado de control de versiones de un bloque se rechazan con errores.


--

