---
permalink: ndmp/enable-node-scoped-ndmp-cluster-task.html 
sidebar: sidebar 
keywords: enable, node, scope, ndmp, cluster 
summary: Puede configurar NDMP de ámbito del nodo habilitando NDMP en el clúster y el servicio NDMP de ámbito del nodo en todos los nodos del clúster. También debe configurar el usuario raíz para NDMP al habilitar el servicio NDMP. 
---
= Habilitar NDMP con alcance de nodo en el clúster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede realizar backups de volúmenes alojados en un único nodo. Para ello, active el NDMP de ámbito del nodo, lo que habilita el servicio NDMP y configura una LIF para la conexión de datos y control. Esto puede hacerse para todos los nodos del clúster.


NOTE: NDMP de ámbito del nodo está obsoleto en ONTAP 9.

.Acerca de esta tarea
Cuando se utiliza NDMP en el modo de alcance del nodo, la autenticación debe configurarse por nodo. Para obtener más información, consulte link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/NDMP/How_to_configure_NDMP_authentication_in_the_%E2%80%98node-scope%E2%80%99_mode["El artículo de la base de conocimientos "Cómo configurar la autenticación NDMP en el modo de alcance de nodo""^].

.Pasos
. Habilitar modo NDMP de ámbito de nodo:
+
[source, cli]
----
cluster1::> system services ndmp node-scope-mode on
----
+
NDMP node-scope-mode está activado.

. Habilite el servicio NDMP en todos los nodos del clúster:
+
Si utiliza el comodín "'*'", se habilita el servicio NDMP en todos los nodos al mismo tiempo.

+
Debe especificar una contraseña para la autenticación de la conexión NDMP mediante la aplicación de backup.

+
[source, cli]
----
cluster1::> system services ndmp on -node *
----
+
[listing]
----
Please enter password:
Confirm password:
2 entries were modified.
----
. Deshabilite `-clear-text` la opción de comunicación segura de la contraseña NDMP:
+
Usando la*`" disables the `-clear-text` opción comodín '` en todos los nodos al mismo tiempo.

+
[source, cli]
----
cluster1::> system services ndmp modify -node * -clear-text false
----
. Compruebe que el servicio NDMP está activado y que la `-clear-text` opción está desactivada:
+
[source, cli]
----
cluster1::> system services ndmp show
----
+
[listing]
----
Node                  Enabled   Clear text  User Id
--------------------- --------- ----------- ---------
cluster1-1            true      false        root
cluster1-2            true      false        root
2 entries were displayed.
----

