---
permalink: ndmp/enable-tape-reservations-task.html 
sidebar: sidebar 
keywords: enable, tape, reservation 
summary: Debe asegurarse de que las unidades de cinta estén reservadas para que las aplicaciones de backup las operaciones de backup de NDMP. 
---
= Activar reservas de cinta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe asegurarse de que las unidades de cinta estén reservadas para que las aplicaciones de backup las operaciones de backup de NDMP.

.Acerca de esta tarea
La configuración de las reservas varía en diferentes aplicaciones de backup, y esta configuración debe coincidir con la aplicación de backup y los nodos o servidores que utilizan las mismas unidades. Consulte la documentación del proveedor de la aplicación de backup para obtener los ajustes de reserva correctos.

.Pasos
. Habilite las reservas mediante el `options -option-name tape.reservations -option-value persistent` comando.
+
El siguiente comando habilita las reservas con `persistent` valor:

+
[listing]
----
cluster1::> options -option-name tape.reservations -option-value persistent
2 entries were modified.
----
. Compruebe que las reservas estén habilitadas en todos los nodos mediante el `options tape.reservations` y, a continuación, revise el resultado.
+
[listing]
----
cluster1::> options tape.reservations

cluster1-1
    tape.reservations                 persistent

cluster1-2
    tape.reservations                 persistent
2 entries were displayed.
----

