---
permalink: ndmp/index.html 
sidebar: sidebar 
keywords: decide, ndmp, configuration, network, data, management, protocol, backup, back up 
summary: 'Puede configurar rápidamente un clúster ONTAP 9 para utilizar el protocolo de gestión de datos de red (NDMP) con el fin de realizar backups de los datos directamente en cinta mediante una aplicación de backup de terceros.' 
---
= Información general de la configuración de NDMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar rápidamente un clúster ONTAP 9 para utilizar el protocolo de gestión de datos de red (NDMP) con el fin de realizar backups de los datos directamente en cinta mediante una aplicación de backup de terceros.

Si la aplicación de backup admite Cluster Aware Backup (CAB), puede configurar NDMP como _SVM-scoped_ o _node-scoped_:

* Con el ámbito de SVM en el nivel del clúster (SVM de administrador), puede realizar backup de todos los volúmenes alojados en diferentes nodos del clúster. Siempre que sea posible, se recomienda utilizar NDMP con ámbito SVM.
* NDMP de ámbito de nodo le permite realizar backup de todos los volúmenes alojados en ese nodo.


Si la aplicación de backup no admite CAB, debe utilizar NDMP de ámbito de nodo.

El protocolo NDMP de ámbito SVM y el de ámbito de nodo son mutuamente exclusivos; no se pueden configurar en el mismo clúster.


NOTE: NDMP de ámbito del nodo está obsoleto en ONTAP 9.

Más información sobre link:../tape-backup/cluster-aware-backup-extension-concept.html["Respaldo para clúster (CAB)"].

Antes de configurar NDMP, compruebe lo siguiente:

* Tiene una aplicación de copia de seguridad de terceros (también llamada aplicación de administración de datos o DMA).
* Es un administrador de clúster.
* Se instalan dispositivos de cinta y un servidor multimedia opcional.
* Los dispositivos de cinta están conectados al clúster a través de un switch Fibre Channel (FC) o conectados localmente.
* Al menos un dispositivo de cinta tiene un número de unidad lógica (LUN) de 0.

