---
permalink: consistency-groups/clone-task.html 
sidebar: sidebar 
keywords: consistency groups, consistency group, clone 
summary: A partir de ONTAP 9.12.1, puede clonar un grupo de consistencia para crear una copia de la configuración del grupo de consistencia y los volúmenes junto con su contenido. 
---
= Clonar un grupo de consistencia
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.12.1, puede clonar un grupo de consistencia para crear una copia de un grupo de consistencia y su contenido. La clonación de un grupo de coherencia crea una copia de la configuración del grupo de coherencia, sus metadatos, como el tipo de aplicación, y todos los volúmenes y su contenido, como archivos, directorios, LUN o espacios de nombres NVMe.

Al clonar un grupo de consistencia, puede clonarlo con su configuración actual, pero con el contenido del volumen como son o basado en una snapshot de grupo de consistencia existente.

La clonación de un grupo de consistencia solo se admite para todo el grupo de consistencia. No puede clonar un grupo de consistencia secundario individual en una relación jerárquica: Solo se puede clonar la configuración completa del grupo de consistencia.

Cuando clona un grupo de consistencia, no se clonan los siguientes componentes:

* Grupos de iniciadores
* Mapas de LUN
* Subsistemas NVMe
* Asignaciones del subsistema de espacio de nombres de NVMe


Cuando se clona un grupo de coherencia, ONTAP no creará recursos compartidos de SMB para los volúmenes clonados si no se especifica un nombre de recurso compartido. Los grupos de consistencia clonados no se montan si no se especifica una ruta de unión. Si intenta clonar un grupo de consistencia basado en una snapshot que no refleja la configuración actual del grupo de consistencia, se producirá un error en la operación.

Después de clonar un grupo de consistencia, debe realizar la operación de asignación adecuada. Consulte xref:../task_san_map_igroups_to_multiple_luns.html[Asigne iGroups a varias LUN] o. xref:../san-admin/map-nvme-namespace-subsystem-task.html[Asignar un espacio de nombres NVMe a un subsistema] si quiere más información.

No se admite la clonado de un grupo de consistencia en una relación de continuidad empresarial de SnapMirror o con ningún volumen de DP asociado.

.Pasos
. Seleccione *almacenamiento > grupos de consistencia*.
. Seleccione el grupo de consistencia que desea clonar en el menú *Grupo de consistencia*.
. En la parte superior derecha de la página de descripción general del grupo de consistencia, seleccione *Clonar*.
. Introduzca un nombre para el nuevo grupo de consistencia clonado o acepte el nombre predeterminado.
+
.. Elija si desea habilitar link:../concepts/thin-provisioning-concept.html["*Thin Provisioning*"^].
.. Elija *Split Clone* si desea disociar el grupo de consistencia de su origen y asignar espacio en disco adicional para el grupo de consistencia clonado.


. Para clonar el grupo de consistencia en su estado actual, elija *Agregar una nueva copia Snapshot*.
+
Para clonar el grupo de consistencia basado en una instantánea, seleccione *utilizar una copia Snapshot* existente. Si selecciona esta opción, se abrirá un nuevo submenú. Elija la copia de Snapshot que desea usar como base para la operación de clonado.

. Seleccione *Clonar*.
. Vuelva al menú *Grupo de consistencia* para confirmar que el grupo de consistencia ha sido clonado.

