---
permalink: consistency-groups/configure-hierarchy-task.html 
sidebar: sidebar 
keywords: consistency groups, application protection, parent, child, hierarchy 
summary: Cree un grupo de consistencia jerárquico para la gestión y protección de datos de grandes cargas de trabajo de aplicaciones. 
---
= Configurar un grupo de consistencia jerárquico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si la carga de trabajo de su aplicación está compuesta por más de un subconjunto de volúmenes, donde cada subconjunto es coherente en sus propios volúmenes asociados, ONTAP permite crear un grupo de consistencia jerárquico.

Los grupos de consistencia jerárquicos tienen un primario que puede incluir hasta cinco grupos de consistencia individuales. Los grupos de coherencia jerárquicos pueden admitir diferentes políticas Snapshot locales en grupos de coherencia o volúmenes individuales. Si utiliza una política de continuidad de negocio de SnapMirror remota (SM-BC), que se aplicará a todo el grupo de consistencia jerárquico (principal y secundario).

Para obtener información sobre los límites de objetos en los grupos de consistencia, consulte xref:limits.html[Límites de objetos para los grupos de consistencia].



== Cree un grupo de consistencia jerárquico con nuevas LUN

Al crear un grupo de consistencia jerárquico, puede rellenarlo con nuevas LUN.

.Pasos
. Seleccione *almacenamiento > grupos de consistencia*.
. Seleccione *+Agregar* y, a continuación, *usando nuevas LUN*.
. Asigne un nombre al grupo de consistencia. Designe el número de LUN y la capacidad por LUN.
+
.. **Tipo de aplicación**: Si está utilizando ONTAP 9.12.1 o posterior, seleccione un tipo de aplicación. Si no se selecciona ningún valor, se asignará al grupo de consistencia el tipo de **Other** de forma predeterminada. Obtenga más información sobre la coherencia de etiquetado en xref:index.html#application-and-component-tags[Etiquetas de aplicaciones y componentes]. Si planea crear una relación SM-BC, debe utilizar *otros*.


. Seleccione el sistema operativo del host y el formato de LUN. Introduzca la información del iniciador del host.
. Para configurar políticas de protección, agregue un grupo de consistencia secundario o muestre más opciones acerca de los iniciadores de host, seleccione *más opciones*.
. Para agregar un grupo de consistencia hijo, seleccione *+Agregar grupo de consistencia hijo*.
. Seleccione el nivel de rendimiento, el número de LUN y la capacidad por LUN. Designe el sistema operativo del host, el formato de LUN y seleccione un iGroup del host nuevo o existente.
. *Opcional*: Seleccione una directiva de instantánea local.
. Repita desde un máximo de cinco grupos de consistencia secundarios.
. Seleccione *Guardar*.
. Para confirmar que se ha creado el grupo de coherencia, vuelva al menú del grupo de consistencia principal, donde aparecerá una vez que se complete el trabajo de ONTAP. Si establece una directiva de protección, mire bajo la directiva apropiada, remota o local, que debe mostrar un escudo verde con una Marca de verificación en ella.




== Cree un grupo de coherencia jerárquico con volúmenes existentes

Se pueden organizar los volúmenes existentes en un grupo de coherencia jerárquico.

.Pasos
. Seleccione *almacenamiento > grupos de consistencia*.
. Seleccione *+Agregar* y *utilizando volúmenes existentes*.
. Seleccione la máquina virtual de almacenamiento.
. Seleccione los volúmenes existentes que desea incluir. Solo se podrá seleccionar los volúmenes que todavía no sean parte de un grupo de coherencia.
. Para agregar un grupo de consistencia hijo, seleccione *+Agregar grupo de consistencia hijo*. Cree los grupos de consistencia necesarios, que se nombrarán automáticamente.
+
.. **Tipo de componente**: Si está utilizando ONTAP 9.12.1 o posterior, seleccione un tipo de componente de "datos", "registros" u "otro". Si no se selecciona ningún valor, se asignará al grupo de consistencia el tipo de **Other** de forma predeterminada. Obtenga más información sobre la coherencia de etiquetado en xref:index.html#application-and-component-tags[Etiquetas de aplicaciones y componentes]. Si planea crear una relación SM-BC, debe utilizar *otros*.


. Asigne volúmenes existentes a cada grupo de coherencia.
. *Opcional*: Seleccione una política de instantánea local.
. Repita desde un máximo de cinco grupos de consistencia secundarios.
. Seleccione *Guardar*.
. Para confirmar que se ha creado el grupo de coherencia, vuelva al menú del grupo de consistencia principal, donde aparecerá una vez que se complete el trabajo de ONTAP. Si ha elegido una política de protección, confirme que se ha configurado correctamente seleccionando su grupo de consistencia en el menú; en el tipo de política correspondiente, verá un escudo verde con una Marca de verificación en el interior de la misma.

