---
sidebar: sidebar 
permalink: concept_dp_overview.html 
keywords: netapp, ontap, protection, overview, data, protect, loss, backup, back up, types, mirror, vault, snapmirror, snapvault, SVM, storage VM, LIF, network interface, intercluster, single file snap restore, metrocluster, sfsr, disaster recovery, SnapMirror, protection policy, vault relationship, mirror relationship, relationship, snapshot, Snapshot copy, policy, schedule, replica, standards compliance, vault, default protection policy, asynchronous policy, synchronous policy, custom policy 
summary: Proteja sus datos mediante la creación y la gestión de copias Snapshot, reflejos, almacenes y relaciones de mirroring y almacén. 
---
= Información general sobre la protección de datos con System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Los temas de esta sección muestran cómo configurar y gestionar la protección de datos con System Manager en ONTAP 9.7 y versiones posteriores.

Si utiliza System Manager en ONTAP 9.7 o una versión anterior, consulte link:https://docs.netapp.com/us-en/ontap-sm-classic/index.html["Documentación clásica de System Manager de ONTAP"^]

Proteja sus datos mediante la creación y la gestión de copias Snapshot, reflejos, almacenes y relaciones de mirroring y almacén.

_SnapMirror_ es la tecnología de recuperación ante desastres diseñada para la conmutación al nodo de respaldo del almacenamiento principal al secundario en un sitio geográficamente remoto. Como su nombre indica, SnapMirror crea una réplica, o réplica, de sus datos de trabajo en almacenamiento secundario desde la cual puede seguir proporcionando datos en caso de catástrofe en el centro principal.

Un _vault_ está diseñado para la replicación de copias snapshot disco a disco con el fin de cumplir con los estándares y otros fines relacionados con la gobernanza. A diferencia de la relación de SnapMirror, en la que el destino normalmente solo contiene las copias Snapshot que actualmente se encuentran en el volumen de origen, un destino de almacén normalmente conserva las copias Snapshot puntuales creadas durante un período mucho más largo.

A partir de ONTAP 9.10.1, se pueden crear relaciones de protección de datos entre bloques de S3 mediante SnapMirror S3. Los bloques de destino pueden estar en sistemas ONTAP locales o remotos, o en sistemas que no sean ONTAP, como StorageGRID y AWS. Para obtener más información, consulte link:s3-snapmirror/index.html["Información general de SnapMirror de S3"].
