---
permalink: insights-configure-native-fpolicy-task.html 
sidebar: sidebar 
keywords: system manager, fpolicy, file extensions, native, best practice, best practise, configure, disallow 
summary: A partir de ONTAP 9.11.1, cuando recibe un informe del administrador del sistema que sugiere implementar FPolicy nativa, puede configurarla en sus máquinas virtuales y volúmenes de almacenamiento.  
---
= Configurar FPolicy nativa
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partir de ONTAP 9.11.1, cuando recibe un informe del administrador del sistema que sugiere implementar FPolicy nativa, puede configurarla en sus máquinas virtuales y volúmenes de almacenamiento.

.Antes de empezar
Al acceder a System Manager Insights, en *Aplicar prácticas recomendadas*, es posible que reciba un mensaje que indique que FPolicy nativo no está configurado.

Para obtener más información sobre los tipos de configuración de FPolicy, consulte link:./nas-audit/fpolicy-config-types-concept.html["Tipos de configuración de FPolicy"].

.Pasos
. En System Manager, haga clic en *Insights* en la columna de navegación de la izquierda.
. En *Aplicar las mejores prácticas*, localice *La FPolicy nativa no está configurada*.
. Lea el siguiente mensaje antes de tomar medidas:
+
[IMPORTANT]
====
*Las extensiones de bloqueo pueden dar lugar a resultados inesperados.* A partir de ONTAP 9.11.1, puedes habilitar FPolicy nativa para VM de almacenamiento usando System Manager.
Con el modo nativo de FPolicy, puede permitir o rechazar extensiones de archivo específicas. System Manager recomienda más de 3000 extensiones de archivos no permitidas que se hayan usado en ataques anteriores de ransomware.  Algunas de estas extensiones pueden ser utilizadas por archivos legítimos en su entorno y bloquearlas puede dar lugar a problemas inesperados.

Por lo tanto, se recomienda encarecidamente que modifique la lista de extensiones para satisfacer las necesidades de su entorno. Consulte https://kb.netapp.com/onprem/ontap/da/NAS/How_to_remove_a_file_extension_from_a_native_FPolicy_configuration_created_by_System_Manager_using_System_Manager_to_recreate_the_policy["Cómo quitar una extensión de archivo de una configuración nativa de FPolicy creada por System Manager con System Manager para volver a crear la política"^].

====
. Haga clic en *Fix*.
. Seleccione las máquinas virtuales de almacenamiento a las que desea aplicar la FPolicy nativa.
. Para cada máquina virtual de almacenamiento, seleccione los volúmenes que recibirán la FPolicy nativa.
. Haga clic en *Configurar*.

