---
settings:
  name: ONTAP 9
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  search: ontap, ontap-metrocluster, ontap-sm-classic, ontap-fli, ontap-automation,
    ontap-cli-9131
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de ONTAP
    url: "/index.html"
  - title: Notas de la versi칩n
    url: "/release-notes.html"
  - title: Integraci칩n de System Manager con BlueXP
    url: "/sysmgr-integration-bluexp-concept.html"
  - section: introduction-concepts
  - section: setup-upgrade
  - section: cluster-admin
  - section: volume-admin
  - section: network-management
  - section: nas-management
  - section: san-management
  - section: object-storage-management
  - section: security-encryption
  - section: data-protection-disaster-recovery
  - section: event-performance-monitoring
  - title: P치ginas de manual de ONTAP
    url: "/concepts/manual-pages.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
  sidebar_label: Documentaci칩n de productos All ONTAP
