---
sidebar: sidebar 
permalink: task_metrocluster_troubleshooting.html 
keywords: system manager, troubleshoot, error, event, problem, metrocluster, maintenance, fix, correction, health, check 
summary: Puede cambiar de un sitio de MetroCluster a otro para realizar tareas de mantenimiento o recuperación de un problema. 
---
= Solucionar problemas relacionados con la configuración de MetroCluster IP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
A partir de ONTAP 9.8, System Manager supervisa el estado de las configuraciones de MetroCluster IP y ayuda a identificar y corregir los problemas que pueden ocurrir.



== Descripción general de la comprobación del estado de MetroCluster

System Manager comprueba periódicamente el estado de la configuración de MetroCluster IP. Cuando ve la sección MetroCluster en la Consola, normalmente el mensaje es "los sistemas MetroCluster están en buen estado".

Sin embargo, cuando se produce un problema, el mensaje mostrará el número de eventos. Puede hacer clic en ese mensaje y ver los resultados de la comprobación de estado de los siguientes componentes:

* Nodo
* Interfaz de red
* Nivel (almacenamiento)
* Clúster
* Conexión
* Volumen
* Replicación de la configuración


La columna *Estado* identifica qué componentes tienen problemas, y la columna *Detalles* sugiere cómo corregir el problema.



== Resolución de problemas de MetroCluster

.Pasos
. En System Manager, seleccione *Panel*.
. En la sección *MetroCluster*, observe el mensaje.
+
.. Si el mensaje indica que la configuración de MetroCluster es correcta y que las conexiones entre los clústeres y el Mediador ONTAP están en buen estado (se muestra con marcas de comprobación), no tiene problemas para corregir.
.. Si el mensaje enumera el número de eventos o las conexiones han caído (se muestra con una "X"), continúe con el paso siguiente.


. Haga clic en el mensaje que muestra el número de eventos.
+
Aparecerá el Informe de estado de MetroCluster.

. Solucione los problemas que aparecen en el informe con las sugerencias de la columna *Detalles*.
. Una vez corregidos todos los problemas, haga clic en *comprobar estado de MetroCluster*.
+

NOTE: La comprobación del estado de MetroCluster utiliza una cantidad intensiva de recursos, por lo que se recomienda realizar todas las tareas de solución de problemas antes de ejecutar la comprobación.

+
La comprobación del estado de MetroCluster se ejecuta en segundo plano. Puede trabajar en otras tareas mientras espera a que finalice.


