---
sidebar: sidebar 
permalink: task_nas_provision_nfs_vmware.html 
keywords: netapp, ontap, provisioning, nas, vmware, datastores, nfs, provision, using, ontap tools for vmware vsphere, esxi, host, vcenter, server 
summary: Antes de usar ONTAP tools for VMware vSphere para aprovisionar volúmenes NFS en un sistema de almacenamiento basado en ONTAP para hosts ESXi, habilita NFS usando System Manager para ONTAP 9.7 o versiones posteriores. 
---
= Aprovisione almacenamiento NFS para almacenes de datos de VMware con ONTAP System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Antes de usar ONTAP tools for VMware vSphere para aprovisionar volúmenes NFS en un sistema de almacenamiento basado en ONTAP para hosts ESXi, habilita NFS usando System Manager para ONTAP 9.7 o versiones posteriores.

Después de crear un link:task_nas_enable_linux_nfs.html["Máquina virtual de almacenamiento compatible con NFS"] en System Manager, luego aprovisionas volúmenes NFS y gestionas almacenes de datos usando ONTAP tools for VMware vSphere.

Asegúrate de consultar la  https://imt.netapp.com/matrix/["Matriz de interoperabilidad de NetApp"^] para comprobar la compatibilidad entre tu versión actual de ONTAP y las versiones de ONTAP tools for VMware vSphere.

Para configurar el acceso NFS de los hosts ESXi a los almacenes de datos mediante System Manager Classic (para ONTAP 9.7 y versiones anteriores), consulta https://docs.netapp.com/us-en/ontap-system-manager-classic/nfs-config-esxi/index.html["Descripción general de la configuración de NFS para ESXi"^]

Para obtener más información, consulta https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597: VMware vSphere para ONTAP"^] y https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/["Documentación de las herramientas de ONTAP para VMware vSphere"^].
