---
sidebar: sidebar 
permalink: task_san_configure_protection_for_business_continuity.html 
keywords: netapp, ontap, System Manager, LUNs, source cluster, protect, protection, storage VM, volume, volumes, source, destination, cluster, IOPS activity 
summary: Configurar la protección para la continuidad empresarial implica seleccionar LUN en el clúster de origen de ONTAP y añadirlas a un grupo de consistencia. Abra System Manager desde un explorador del clúster de origen para comenzar a configurar la protección para la continuidad empresarial. 
---
= Configure la protección para la continuidad del negocio
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Configurar la protección para la continuidad empresarial implica seleccionar LUN en el clúster de origen de ONTAP y añadirlas a un grupo de consistencia. Abra System Manager desde un explorador del clúster de origen para comenzar a configurar la protección para la continuidad empresarial.

Este flujo de trabajo está diseñado para ONTAP 9.8 y 9.9. A partir de ONTAP 9.10.1, se recomienda empezar por crear un grupo de coherencia y luego usar SM-BC como protección remota.



== Acerca de esta tarea

* Los LUN deben residir en el mismo equipo virtual de almacenamiento.
* Los LUN pueden residir en distintos volúmenes.
* Los clústeres de origen y destino no pueden ser los mismos.
* El espacio IP predeterminado es necesario por SM-BC para las relaciones de paridad de clústeres. No se admite el espacio IP personalizado.


.Pasos
. Seleccione las LUN que desea proteger y agréguelas a un grupo de protección: *Protección > Descripción general > Protección para la continuidad del negocio > Protección de LUN*.
. Seleccione una o más LUN para proteger en el clúster de origen.
. Seleccione el clúster y la SVM de destino.
. *La opción inicializar relación* está seleccionada de forma predeterminada. Haga clic en *Guardar* para comenzar la protección.
. Vaya a *Consola > rendimiento* para verificar la actividad de IOPS de las LUN.
. En el clúster de destino, utilice System Manager para comprobar que la protección de la relación de continuidad de negocio está sincronizada: *Protección > Relaciones*.

