---
sidebar: sidebar 
permalink: task_admin_monitor_risks.html 
keywords: system manager, monitor, risk, risks, suggestion, suggestions, mitigate, digital advisor, active iq, category, categories, mitigation, impact, impacts, corrections, corrective action, corrective actions, acknowledge risk, dismiss, undismiss, restore, unacknowledge 
summary: Mediante System Manager con ONTAP 9.10,0 o posterior, puede supervisar los riesgos que informa el asesor digital. 
---
= Control de riesgos
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partir de ONTAP 9.10,0, puede usar System Manager para supervisar los riesgos que informa el asesor digital de Active IQ (también conocido como asesor digital). A partir de ONTAP 9.10.1, puede usar System Manager para reconocer también los riesgos.

El asesor digital de NetApp informa sobre oportunidades para reducir el riesgo y mejorar el rendimiento y la eficiencia de su entorno de almacenamiento. Con System Manager, puede obtener información sobre los riesgos que informa el asesor digital y obtener inteligencia procesable que le ayuda a administrar el almacenamiento y lograr una mayor disponibilidad, una seguridad mejorada y un mejor rendimiento del almacenamiento.



== Enlace a su cuenta del asesor digital

Para recibir información sobre los riesgos del asesor digital, primero debe vincular a su cuenta de asesor digital de System Manager.

.Pasos
. En System Manager, haga clic en *clúster > Configuración*.
. En *Registro de Active IQ*, haga clic en *Registro*.
. Introduzca sus credenciales para el asesor digital.
. Una vez autenticadas las credenciales, haga clic en *Confirmar para vincular Active IQ con System Manager*.




== Ver el número de riesgos

A partir de ONTAP 9.10,0, puede ver desde la consola de System Manager la cantidad de riesgos que notifica el asesor digital.

.Antes de empezar
Debe establecer una conexión entre System Manager y su cuenta del asesor digital. Consulte <<link_active_iq,Enlace a su cuenta del asesor digital>>.

.Pasos
. En System Manager, haga clic en *Panel*.
. En la sección *Salud*, vea el número de riesgos reportados.
+

NOTE: Puede ver información más detallada sobre cada riesgo haciendo clic en el mensaje que muestra el número de riesgos. Consulte <<view_risk_details,Consulte detalles de riesgos>>.





== Consulte detalles de riesgos

A partir de ONTAP 9.10,0, puede ver desde System Manager cómo se clasifican los riesgos del asesor digital por áreas de impacto. También puede ver información detallada sobre cada riesgo notificado, su impacto potencial en el sistema y las acciones correctivas que puede tomar.

.Antes de empezar
Debe establecer una conexión entre System Manager y su cuenta del asesor digital. Consulte <<link_active_iq,Enlace a su cuenta del asesor digital>>.

.Pasos
. Haga clic en *Eventos > todos los eventos*.
. En la sección *Descripción general*, en *Sugerencias* de Active IQ, vea el número de riesgos en cada categoría de área de impacto. Las categorías de riesgo incluyen:
+
** Rendimiento y eficiencia
** Disponibilidad y protección
** Capacidad
** Configuración
** Seguridad


. Haga clic en la ficha *Sugerencias* de Active IQ para ver información sobre cada riesgo, incluidos los siguientes:
+
** Nivel de impacto en el sistema
** Categoría del riesgo
** Nodos afectados
** Tipo de mitigación necesaria
** Acciones correctivas que puede tomar






== Reconocer riesgos

A partir de ONTAP 9.10.1, puede usar System Manager para reconocer cualquiera de los riesgos abiertos.

.Pasos
. En System Manager, visualice la lista de riesgos realizando el procedimiento en <<view_risk_details,Consulte detalles de riesgos>>.
. Haga clic en el nombre de riesgo de un riesgo abierto que desee reconocer.
. Introduzca información en los siguientes campos:
+
** Recordatorio (fecha)
** Justificación
** Comentarios


. Haga clic en *acuse de recibo*.
+

NOTE: Después de reconocer un riesgo, el cambio tarda unos minutos en reflejarse en la lista de sugerencias del asesor digital.





== No reconocer riesgos

A partir de ONTAP 9.10.1, puede usar System Manager para anular el reconocimiento de cualquier riesgo que anteriormente se hubiera reconocido.

.Pasos
. En System Manager, visualice la lista de riesgos realizando el procedimiento en <<view_risk_details,Consulte detalles de riesgos>>.
. Haga clic en el nombre de riesgo de un riesgo reconocido que desea no reconocer.
. Introduzca información en los siguientes campos:
+
** Justificación
** Comentarios


. Haga clic en *no confirmar*.
+

NOTE: Después de que no reconozca un riesgo, el cambio tarda unos minutos en reflejarse en la lista de sugerencias del asesor digital.


