---
sidebar: sidebar 
permalink: task_cp_monitor_cluster_performance_ci.html 
keywords: netapp, ontap, cluster, performance, monitor, monitoring, headroom, cpu, cpus, Cloud Insights, troubleshoot, optimize, private data center, Kafka, MongoDB, Nginx, Active IQ Unified Manager, cluster performance, monitor performance 
summary: Con Cloud Insights, puede supervisar, solucionar problemas y optimizar todos los recursos, incluidos los clouds públicos y los centros de datos privados. 
---
= Supervise el rendimiento del clúster con Cloud Insights
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Cloud Insights de NetApp es una herramienta de supervisión que le ofrece visibilidad de toda su infraestructura. Con Cloud Insights, puede supervisar, solucionar problemas y optimizar todos los recursos, incluidos los clouds públicos y los centros de datos privados.



== Cloud Insights se presenta en dos ediciones

La edición básica de Cloud Insights está diseñada específicamente para supervisar y optimizar sus activos de Data Fabric de NetApp. Proporciona análisis avanzados para las conexiones entre todos los recursos de NetApp, incluidos HCI y All Flash FAS (AFF) en el entorno de forma gratuita.

Cloud Insights Standard Edition no solo se centra en componentes de infraestructura habilitados para Data Fabric de NetApp, sino también en entornos de varios proveedores y clouds. Con sus capacidades enriquecidas, usted puede acceder al apoyo para más de 100 servicios y recursos.

En el mundo actual, donde los recursos están en juego desde los centros de datos locales hasta varios clouds públicos, es fundamental tener una imagen completa desde la propia aplicación hasta el disco de back-end de la cabina de almacenamiento. El soporte adicional para la supervisión de aplicaciones (como Kafka, MongoDB y Nginx) le proporciona la información y el conocimiento que necesita para operar al nivel óptimo de utilización, así como con el búfer de riesgo perfecto.

Ambas ediciones (Basic y Standard) pueden integrarse con Active IQ Unified Manager de NetApp. Los clientes que utilicen Active IQ Unified Manager podrán ver la información de unión en la interfaz de usuario de Cloud Insights. Las notificaciones publicadas en Active IQ Unified Manager no se pasan por alto y ahora pueden estar relacionadas con eventos en Cloud Insights. En otras palabras, obtienes lo mejor de ambos mundos.



== Supervisión, solución de problemas y optimización de todos los recursos

Cloud Insights le ayuda a reducir significativamente el tiempo necesario para resolver problemas y evitar que afecten a los usuarios finales.  También le ayuda a reducir los costes de infraestructura del cloud.  Su exposición a las amenazas internas se reduce al proteger sus datos con una inteligencia práctica.

Cloud Insights le ofrece visibilidad de toda su infraestructura híbrida en un mismo lugar, desde el cloud público hasta su centro de datos.  Puede crear instantáneamente paneles relevantes que se puedan personalizar según sus necesidades específicas. También puedes crear alertas específicas y condicionales que sean específicas y relevantes para las necesidades de tu organización.

La detección avanzada de anomalías le ayuda a corregir problemas de forma proactiva antes de que surjan.  Puede ver automáticamente la contención y degradación de los recursos para restaurar rápidamente las cargas de trabajo afectadas.  La solución de problemas va más rápido con la jerarquía automatizada de relaciones entre los distintos componentes de la pila.

Puede identificar los recursos no utilizados o abandonados en todo su entorno, lo que le ayudará a descubrir oportunidades para dimensionar adecuadamente la infraestructura y optimizar el gasto completo.

Cloud Insights visualiza la topología de su sistema para entender su arquitectura de Kubernetes. Puede supervisar el estado de los clústeres de Kubernetes, incluidos qué nodos tienen problemas y ampliar cuando observe un problema.

Cloud Insights le ayuda a proteger los datos de la organización frente a un uso inadecuado por parte de usuarios malintencionados o en riesgo mediante el aprendizaje automático avanzado y la detección de anomalías que le proporciona inteligencia procesable sobre amenazas internas.

Cloud Insights le ayuda a visualizar métricas de Kubernetes para que pueda comprender por completo las relaciones entre los pods, los nodos y los clústeres. Podrá evaluar el estado de un clúster o un módulo de trabajo, así como la carga que está procesando actualmente, lo que le permite tomar el control del clúster K8S y controlar tanto el estado como el coste de la implementación.
