---
sidebar: sidebar 
permalink: task_cp_monitor_cluster_performance_um.html 
keywords: netapp, ontap, cluster, performance, monitor, monitoring, unified manager, active IQ, headroom, cpu, cpus, latency, maximize availability, AFF storage, FAS storage, scalability, supportability, support, security, data management 
summary: Active IQ Unified Manager de NetApp le ayuda a simplificar la gestión del sistema y a supervisar el estado del almacenamiento. 
---
= Supervise el rendimiento del clúster con ONTAP Unified Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Con Active IQ Unified Manager, puede maximizar la disponibilidad y mantener el control de su infraestructura de almacenamiento AFF y FAS de NetApp para disfrutar de una mayor escalabilidad, compatibilidad, rendimiento y seguridad.

Active IQ Unified Manager supervisa de forma continua el estado del sistema y envía alertas, para que su organización pueda liberar recursos del personal DE TECNOLOGÍA. Puede ver al instante el estado de su almacenamiento desde un único panel y abordar rápidamente problemas mediante acciones recomendadas.

La gestión de datos se simplifica porque puede detectar, supervisar y recibir notificaciones para gestionar el almacenamiento de forma proactiva y resolver los problemas con rapidez. La eficiencia de administración ha mejorado porque puede supervisar petabytes de datos desde una única consola y gestionar sus datos a escala.

Con Active IQ Unified Manager, puede mantener el ritmo de las fluctuaciones en las demandas del negocio y optimizar el rendimiento mediante datos del rendimiento y análisis avanzados. Las funciones de generación de informes permiten acceder a informes estándar o crear informes operativos personalizados que satisfagan las necesidades específicas de su empresa.

Enlaces relacionados:

* link:https://docs.netapp.com/us-en/active-iq-unified-manager/storage-mgmt/concept_introduction_to_unified_manager.html["Obtenga más información acerca de Active IQ Unified Manager"^]
* link:https://docs.netapp.com/us-en/active-iq-unified-manager/install-vapp/qsg-vapp.html["Comienza a usar Active IQ Unified Manager para VMware"^]
* link:https://docs.netapp.com/us-en/active-iq-unified-manager/install-linux/qsg-linux.html["Comience con Active IQ Unified Manager para Linus"^]
* link:https://docs.netapp.com/us-en/active-iq-unified-manager/install-windows/qsg-windows.html["Comience a usar Active IQ Unified Manager para Windows"^]

