---
sidebar: sidebar 
permalink: task_nvme_provision_suse_linux.html 
keywords: netapp, ontap, nvme, SUSE, linux, servers, Provision NVMe storage, namespace, SCSI disk service 
summary: Cree espacios de nombres para proporcionar almacenamiento para un servidor SUSE Linux mediante el protocolo NVMe. Los espacios de nombres aparecen en Linux como dispositivos de disco SCSI. 
---
= Aprovisione el almacenamiento NVMe para SUSE Linux
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Cree espacios de nombres para proporcionar almacenamiento para un servidor SUSE Linux mediante el protocolo NVMe. Los espacios de nombres aparecen en Linux como dispositivos de disco SCSI.

Este procedimiento crea nuevos espacios de nombres en una máquina virtual de almacenamiento existente. La máquina virtual de almacenamiento debe configurarse para NVMe, y ya se debe configurar el transporte FC o TCP.

A partir de ONTAP 9.8, cuando se aprovisiona el almacenamiento, la calidad de servicio se habilita de forma predeterminada. Puede deshabilitar la calidad de servicio o seleccionar una política de calidad de servicio personalizada durante el proceso de aprovisionamiento o más adelante.

.Pasos
[role="tabbed-block"]
====
.System Manager
--
Cree espacios de nombres para ofrecer almacenamiento con el protocolo NVMe con ONTAP System Manager (9.7 y versiones posteriores).

. En System Manager, haga clic en *almacenamiento > espacios de nombres NVMe* y, a continuación, haga clic en *Agregar*.
+
.. Si necesita crear un subsistema nuevo, haga clic en *más opciones*.
.. Si está ejecutando ONTAP 9.8 o posterior y desea desactivar QoS o elegir una directiva de QoS personalizada, haga clic en *más opciones* y, a continuación, en *almacenamiento y optimización* seleccione *nivel de servicio de rendimiento*.




. Dividir los switches de FC en zonas mediante WWPN. Use una zona por iniciador e incluya todos los puertos de destino en cada zona.
. En el servidor Linux, descubra los nuevos espacios de nombres.
. Inicialice el espacio de nombres y formatee el sistema de archivos.
. Comprobar que el servidor Linux puede escribir y leer datos en el espacio de nombres.


--
.CLI
--
Cree espacios de nombres para ofrecer almacenamiento mediante el protocolo NVMe con la interfaz de línea de comandos de ONTAP.

Este procedimiento crea un espacio de nombres y un subsistema NVMe en una máquina virtual de almacenamiento existente que ya se configuró para el protocolo NVMe y luego asigna el espacio de nombres al subsistema para permitir el acceso a los datos desde el sistema host.

Si necesita configurar la máquina virtual de almacenamiento para NVMe, consulte link:san-admin/configure-svm-nvme-task.html["Configure una SVM para NVMe"].

.Pasos
. Compruebe que la SVM esté configurada para NVMe:
+
`vserver show -vserver _SVM_name_ -fields allowed-protocols`

+
`NVMe` debe aparecer debajo de la `allowed-protocols` columna.

. Cree el espacio de nombres NVMe:
+
`vserver nvme namespace create -vserver _SVM_name_ -path _path_ -size _size_of_namespace_ -ostype _OS_type_`

. Cree el subsistema NVMe:
+
`vserver nvme subsystem create -vserver _SVM_name_ -subsystem _name_of_subsystem_ -ostype _OS_type_`

+
El nombre del subsistema NVMe distingue mayúsculas de minúsculas. Debe contener de 1 a 96 caracteres. Se permiten caracteres especiales.

. Compruebe que se ha creado el subsistema:
+
`vserver nvme subsystem show -vserver _SVM_name_`

+
La `nvme` el subsistema debe aparecer debajo de `Subsystem` columna.

. Obtenga el NQN del host.
. Añada el NQN del host al subsistema:
+
`vserver nvme subsystem host add -vserver _SVM_name_ -subsystem _subsystem_name_ -host-nqn _Host_NQN_:subsystem._subsystem_name_`

. Asigne el espacio de nombres al subsistema:
+
`vserver nvme subsystem map add -vserver _SVM_name_ -subsystem _subsystem_name_ -path _path_`

+
Un espacio de nombres solo se puede asignar a un subsistema único.

. Compruebe que el espacio de nombres está asignado al subsistema:
+
`vserver nvme namespace show -vserver _SVM_name_ -instance`

+
El subsistema debe aparecer como `Attached subsystem`.



--
====