---
sidebar: sidebar 
permalink: task_cp_id_hot_objects.html 
keywords: netapp, ontap, cluster, performance, identify, hot, volumes, objects, hot volumes, hot data, headroom, frequently accessed volumes, frequently accessed data, IOPS, latency, throughput, accelerate cluster performance, improve performance, cluster performance 
summary: 'Puede acelerar el rendimiento de su clúster identificando los volúmenes a los que se accede con frecuencia (volúmenes activos) y los datos (objetos activos).' 
---
= Identifique volúmenes activos y otros objetos
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Acelere el rendimiento de su clúster identificando los volúmenes a los que se accede con frecuencia (volúmenes activos) y los datos (objetos activos).


NOTE: A partir de ONTAP 9.10.1, puede usar la función Seguimiento de actividades de Análisis del sistema de archivos para supervisar los objetos activos de un volumen. A partir de ONTAP 9.13.1, el seguimiento de la actividad se amplía hasta el alcance de SVM. Para obtener más información, consulte xref:./file-system-analytics/activity-tracking-task.html[Activar seguimiento de actividad].

.Pasos
. Haga clic en *almacenamiento > volúmenes*.
. Filtre las columnas IOPS, latencia y rendimiento para ver los volúmenes y los datos a los que se accede con frecuencia.

