---
sidebar: sidebar 
permalink: task_san_provision_vmware.html 
keywords: 'netapp, ontap, SAN, provisioning, provision, vmware, datastore, add lun, create, fc, iscsi, zone switches, storage, esxi host, Virtual Storage Console (VSC), vmware, vsphere' 
summary: 'Cree LUN para proporcionar almacenamiento para un host ESXi mediante el protocolo SAN FC o iSCSI con ONTAP System Manager (9.7 y versiones posteriores). Los LUN aparecen como discos en el host ESXi.' 
---
= Aprovisionar almacenamiento SAN para almacenes de datos de VMware
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Este procedimiento crea nuevas LUN en una máquina virtual de almacenamiento existente que ya tiene configurado el protocolo FC o iSCSI.

Si necesita crear una máquina virtual de almacenamiento nueva y configurar el protocolo FC o iSCSI, consulte link:san-admin/configure-svm-fc-task.html["Configure una SVM para FC"] o. link:san-admin/configure-svm-iscsi-task.html["Configure una SVM para iSCSI"].


NOTE: El acceso asimétrico de unidad lógica (ALUA, Asymmetric Logical Unit Access) siempre está habilitado durante la creación de una LUN. No se puede cambiar la configuración de ALUA.

A partir de ONTAP 9.8, cuando se aprovisiona el almacenamiento, la calidad de servicio se habilita de forma predeterminada. Puede deshabilitar la calidad de servicio o seleccionar una política de calidad de servicio personalizada durante el proceso de aprovisionamiento o más adelante.

Una vez completado este procedimiento, puede gestionar almacenes de datos de VMware con Virtual Storage Console (VSC) para VMware vSphere. A partir de VSC 7.0, VSC forma parte del https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["Herramientas de ONTAP para el dispositivo virtual de VMware vSphere"^], Que incluye las funcionalidades VSC, vStorage APIs for Storage Awareness (VASA) Provider y Storage Replication Adapter (SRA) para VMware vSphere.

Asegúrese de comprobar el https://imt.netapp.com/matrix/["Matriz de interoperabilidad de NetApp"^] Para confirmar la compatibilidad entre sus versiones actuales de ONTAP y VSC.

Para obtener más información, consulte https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597: VMware vSphere para ONTAP"^] Y la documentación de su versión de VSC.

[role="tabbed-block"]
====
.System Manager
--
Cree LUN para proporcionar almacenamiento con System Manager para ONTAP 9.7 o posterior.

Los LUN aparecen como discos en el host ESXi.

Para configurar el acceso de protocolo SAN para hosts ESXi a almacenes de datos mediante System Manager Classic (para ONTAP 9.7 y versiones anteriores), consulte los temas siguientes:

* https://docs.netapp.com/us-en/ontap-sm-classic/fc-config-esxi/index.html["Información general sobre la configuración de FC para ESXi mediante VSC"^]
* https://docs.netapp.com/us-en/ontap-sm-classic/iscsi-config-esxi/index.html["Información general sobre la configuración de iSCSI para ESXi mediante VSC"^]



NOTE: El acceso asimétrico de unidad lógica (ALUA, Asymmetric Logical Unit Access) siempre está habilitado durante la creación de una LUN. No se puede cambiar la configuración de ALUA.

.Pasos
. En System Manager, haga clic en *almacenamiento > LUN* y, a continuación, haga clic en *Agregar*.
. Introduzca la información necesaria para crear la LUN.
. Puede hacer clic en *más opciones* para realizar cualquiera de las siguientes acciones, dependiendo de su versión de ONTAP.
+
[cols="80,20"]
|===


| Opción | Disponible empezando por 


 a| 
** Asigne una política de calidad de servicio a las LUN en lugar de al volumen principal
+
*** *Más opciones > almacenamiento y optimización*
*** Seleccione *nivel de servicio de rendimiento*.
*** Para aplicar la política QoS a LUN individuales en lugar de todo el volumen, seleccione *aplicar estos límites de rendimiento a cada LUN*.
+
De forma predeterminada, los límites de rendimiento se aplican a nivel de volumen.




| ONTAP 9.10.1 


 a| 
** Cree un nuevo iGroup mediante los iGroups existentes
+
*** *Más Opciones > INFORMACIÓN de HOST*
*** Seleccione *Nuevo iGroup utilizando los iGroups existentes*.
+
*NOTA*: El tipo de SO para un igroup que contiene otros grupos de iniciadores no se puede cambiar después de que se haya creado.




| ONTAP 9.9.1 


 a| 
** Añada una descripción a su igroup o iniciador de host
+
La descripción sirve como alias del igroup o el iniciador del host.

+
*** *Más Opciones > INFORMACIÓN de HOST*



| ONTAP 9.9.1 


 a| 
** Cree el LUN en un volumen existente
+
De manera predeterminada, se crea un nuevo LUN en un volumen nuevo.

+
*** *Más Opciones > Agregar LUN*
*** Seleccione *Grupo de LUN*.



| ONTAP 9.9.1 


 a| 
** Deshabilite QoS o elija una política de calidad de servicio personalizada
+
*** *Más opciones > almacenamiento y optimización*
*** Seleccione *nivel de servicio de rendimiento*.
+
*NOTA*: En ONTAP 9.9.1 y posterior, si selecciona una política de QoS personalizada, también puede seleccionar la colocación manual en un nivel local específico.




| ONTAP 9.8 
|===


. Para FC, dividir los switches de FC en zonas mediante WWPN. Use una zona por iniciador e incluya todos los puertos de destino en cada zona.
. Utilice Virtual Storage Console (VSC) para VMware vSphere a fin de detectar e inicializar la LUN.
. Compruebe que los hosts ESXi pueden escribir y leer datos en la LUN.


--
.CLI
--
Cree LUN para proporcionar almacenamiento con la CLI de ONTAP.

. Utilice la `system license show` Comando para verificar que tiene una licencia para FC o iSCSI.
+
`system license show`

+
[listing]
----

Package           Type    Description           Expiration
 ----------------- ------- --------------------- --------------------
 Base              site    Cluster Base License  -
 NFS               site    NFS License           -
 CIFS              site    CIFS License          -
 iSCSI             site    iSCSI License         -
 FCP               site    FCP License           -
----
. Si no tiene una licencia para FC o iSCSI, utilice `license add` comando.
+
`license add -license-code _your_license_code_`

. Habilite el servicio de protocolo en la SVM:
+
*Para iSCSI:* `vserver iscsi create -vserver _vserver_name_ -target-alias _vserver_name_`

+
*Para FC:* `vserver fcp create -vserver _vserver_name_ -status-admin up`

. Cree dos LIF para las SVM en cada nodo:
+
`network interface create -vserver _vserver_name_ -lif _lif_name_ -role data -data-protocol iscsi|fc -home-node _node_name_ -home-port _port_name_ -address _ip_address_ -netmask netmask`

+
NetApp admite un mínimo de un LIF iSCSI o FC por nodo para cada SVM que sirve datos. Sin embargo, se necesitan dos LIF por nodo para redundancia.

. Compruebe que sus LIF se han creado y que su estado operativo es `online`:
+
`network interface show -vserver _vserver_name_ _lif_name_`

. Cree sus LUN:
+
`lun create -vserver vserver_name -volume _volume_name_ -lun _lun_name_ -size _lun_size_ -ostype linux -space-reserve enabled|disabled`

+
El nombre de la LUN no puede superar los 255 caracteres y no puede contener espacios.

+

NOTE: La opción NVFAIL se habilita automáticamente cuando se crea una LUN en un volumen.

. Cree sus iGroups:
+
`igroup create -vserver _vserver_name_ -igroup _igroup_name_ -protocol fcp|iscsi|mixed -ostype linux -initiator _initiator_name_`

. Asigne sus LUN a iGroups:
+
`lun mapping create -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -igroup _igroup_name_`

. Compruebe que sus LUN están configuradas correctamente:
+
`lun show -vserver _vserver_name_`

. link:san-admin/create-port-sets-binding-igroups-task.html["Cree un conjunto de puertos y enlace a un igroup"] (opcional).
. Siga los pasos de la documentación de host para habilitar el acceso en bloque en los hosts específicos.
. Use las utilidades de host para completar la asignación de FC o iSCSI y para detectar las LUN en el host.


--
====
.Información relacionada
https://docs.netapp.com/us-en/ontap-sanhost/index.html["Configuración de host SAN ONTAP"]
link:./san-admin/index.html["Información general sobre la administración de SAN"]
https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["Consulte y gestione los iGroups SAN en System Manager"]
http://www.netapp.com/us/media/tr-4017.pdf["Informe técnico de NetApp 4017: Prácticas recomendadas de SAN Fibre Channel"]
