---
sidebar: sidebar 
permalink: task_nas_provision_flexgroup.html 
keywords: netapp, ontap, provision, provisioning, nas, large file systems, using, FlexGroup, windows, servers, cifs, smb, FlexVol volume limits, load distribution, work load, workload, balancing, data 
summary: 'Un volumen FlexGroup es un contenedor NAS escalable que ofrece alto rendimiento junto con la distribución automática de la carga. Los volúmenes FlexGroup proporcionan una enorme capacidad (en petabytes), que supera considerablemente los límites de los volúmenes FlexVol, sin añadir gastos generales de gestión.' 
---
= Aprovisione almacenamiento NAS para sistemas de archivos de gran tamaño con volúmenes FlexGroup
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Un volumen FlexGroup es un contenedor NAS escalable que ofrece alto rendimiento junto con la distribución automática de la carga. Los volúmenes FlexGroup proporcionan una enorme capacidad (en petabytes), que supera considerablemente los límites de los volúmenes FlexVol, sin añadir gastos generales de gestión.

Los temas de esta sección muestran la forma de gestionar volúmenes de FlexGroup con System Manager en ONTAP 9.7 y versiones posteriores. Si utiliza la versión clásica de System Manager (disponible solo en ONTAP 9.7 y versiones anteriores), consulte este tema:

* https://docs.netapp.com/us-en/ontap-system-manager-classic/online-help-96-97/task_creating_flexgroup_volumes.html["Cree volúmenes de FlexGroup"^]


A partir de ONTAP 9.9.1, se admiten relaciones de ventilador de SnapMirror de dos o más volúmenes FlexGroup, con un máximo de ocho patas de ventilador. System Manager no admite relaciones de volúmenes de FlexGroup en cascada de SnapMirror.

ONTAP selecciona automáticamente los niveles locales necesarios para crear el volumen FlexGroup.

A partir de ONTAP 9.8, cuando se aprovisiona el almacenamiento, la calidad de servicio se habilita de forma predeterminada. Puede deshabilitar la QoS, o seleccionar una política de calidad de servicio personalizada durante el proceso de aprovisionamiento o posteriormente.

.Pasos
. Haga clic en *almacenamiento > volúmenes*.
. Haga clic en *Agregar*.
. Haga clic en *más opciones* y seleccione *distribuir datos de volumen en el clúster*.
+

NOTE: Si está ejecutando ONTAP 9,8 o posterior y desea deshabilitar QoS o elegir una política de QoS personalizada, haga clic en *Más opciones* y, a continuación, en *Almacenamiento y optimización*, seleccione *Nivel de servicio de rendimiento*.





== Vídeos



=== Cree y gestione un volumen de FlexGroup

video::gB-yF1UTv2I[youtube,width=848,height=480]


== Volúmenes FlexGroup: Haga más con menos

video::0B4nlChf0b4[youtube,width=848,height=480]