---
sidebar: sidebar 
permalink: task_nas_provision_nfs_vmware.html 
keywords: netapp, ontap, provisioning, nas, vmware, datastores, nfs, provision, using, virtual storage console for vmware vsphere, vsc, esxi, host, vcenter, server 
summary: 'Antes de usar Virtual Storage Console para VMware vSphere (VSC) para aprovisionar volúmenes NFS en un sistema de almacenamiento basado en ONTAP para hosts ESXi, habilite NFS mediante System Manager para ONTAP 9.7 o una versión posterior.' 
---
= Aprovisione almacenamiento NFS para almacenes de datos de VMware
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Antes de usar Virtual Storage Console para VMware vSphere (VSC) para aprovisionar volúmenes NFS en un sistema de almacenamiento basado en ONTAP para hosts ESXi, habilite NFS mediante System Manager para ONTAP 9.7 o una versión posterior.

Después de crear un link:task_nas_enable_linux_nfs.html["Máquina virtual de almacenamiento compatible con NFS"] En System Manager, entonces debe aprovisionar volúmenes de NFS y gestionar almacenes de datos mediante VSC.

A partir de VSC 7.0, VSC forma parte del https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["Herramientas de ONTAP para el dispositivo virtual de VMware vSphere"^], Que incluye las funcionalidades VSC, vStorage APIs for Storage Awareness (VASA) Provider y Storage Replication Adapter (SRA) para VMware vSphere.

Asegúrese de comprobar el https://imt.netapp.com/matrix/["Matriz de interoperabilidad de NetApp"^] Para confirmar la compatibilidad entre sus versiones actuales de ONTAP y VSC.

Para configurar el acceso NFS para hosts ESXi a almacenes de datos con System Manager Classic (para ONTAP 9.7 y versiones anteriores), consulte https://docs.netapp.com/us-en/ontap-sm-classic/nfs-config-esxi/index.html["Información general sobre la configuración de NFS para ESXi mediante VSC"^]

Para obtener más información, consulte https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597: VMware vSphere para ONTAP"^] Y la documentación de su versión de VSC.
