---
permalink: element-replication/create-replication-relationship-task.html 
sidebar: sidebar 
keywords: create, relationship, element, source, ontap, destination 
summary: SnapMirror se puede usar para replicar copias de Snapshot de un volumen de Element en un sistema de destino de ONTAP. En caso de desastre en el sitio de Element, puede seguir prestando servicio a los clientes desde el sistema ONTAP y, a continuación, reactivar el volumen de origen de Element cuando el servicio se restaure. 
---
= Crear una relación desde un origen de elemento a un destino de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La relación entre el volumen de origen del almacenamiento primario y el volumen de destino del almacenamiento secundario se denomina _relación de protección de datos_. Puede utilizar el `snapmirror create` Comando para crear una relación de protección de datos desde un origen de elemento a un destino de ONTAP, o desde un origen de ONTAP a un destino de Element.

SnapMirror se puede usar para replicar copias de Snapshot de un volumen de Element en un sistema de destino de ONTAP. En caso de desastre en el sitio de Element, puede seguir prestando servicio a los clientes desde el sistema ONTAP y, a continuación, reactivar el volumen de origen de Element cuando el servicio se restaure.

.Antes de empezar
* ONTAP debe haber accesible desde el nodo Element que contiene el volumen que se va a replicar.
* El volumen de Element debe estar habilitado para la replicación de SnapMirror.
* Si utiliza el tipo de política «mirror-vault», debe haber configurado una etiqueta de SnapMirror para que se repliquen las copias Snapshot de Element.
+
[NOTE]
====
Es posible realizar esta tarea únicamente en la interfaz de usuario web del software Element. Para obtener más información, consulte https://["Documentación de Element"].

====


.Acerca de esta tarea
Debe especificar la ruta de origen del elemento en el formulario `_hostip:_/lun/_name_`, donde «'lun'» es la cadena real «'lun'» y. `name` Es el nombre del volumen de Element.

Un volumen de Element es aproximadamente equivalente a una LUN de ONTAP. SnapMirror crea un LUN con el nombre del volumen de Element cuando se inicializa una relación de protección de datos entre el software Element y ONTAP. SnapMirror replica datos a una LUN existente si la LUN cumple con los requisitos para replicar del software Element en ONTAP.

Las reglas de replicación son las siguientes:

* Un volumen de ONTAP puede contener datos solo de un volumen de Element.
* No es posible replicar datos desde un volumen de ONTAP en varios volúmenes de Element.


En ONTAP 9.3 y versiones anteriores, los volúmenes de destino pueden contener hasta 251 copias Snapshot. A partir de la versión 9.4 de ONTAP, un volumen de destino puede contener hasta 1019 copias snapshot.

.Paso
. A partir del clúster de destino, cree una relación de replicación desde un origen de Element en un destino de ONTAP:
+
`snapmirror create -source-path _hostip:_/lun/name -destination-path _SVM:volume_|_cluster://SVM/volume_ -type XDP -schedule schedule -policy _policy_`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
En el siguiente ejemplo se crea una relación de recuperación ante desastres de SnapMirror con los valores predeterminados `MirrorLatest` política:

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorLatest
----
+
En el ejemplo siguiente se crea una relación de replicación unificada con la opción predeterminada `MirrorAndVault` política:

+
[listing]
----
cluster_dst:> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorAndVault
----
+
En el siguiente ejemplo se crea una relación de replicación unificada mediante `Unified7year` política:

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy Unified7year
----
+
En el siguiente ejemplo se crea una relación de replicación unificada mediante el método personalizado `my_unified` política:

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy my_unified
----


.Después de terminar
Utilice la `snapmirror show` Comando para verificar que la relación de SnapMirror se ha creado. Para obtener una sintaxis de comando completa, consulte la página man.
