---
permalink: element-replication/define-rule-policy-task.html 
sidebar: sidebar 
keywords: define, rule, policy 
summary: Para las directivas personalizadas con el tipo de política “mirror-vault”, debe definir al menos una regla que determine qué copias Snapshot se transfieren durante la inicialización y la actualización. También puede definir reglas para las políticas predeterminadas con el tipo de política “mirror-vault”. 
---
= Defina una regla para una política
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En el caso de las directivas personalizadas con el tipo de política «mirror-vault», debe definir al menos una regla que determine las copias snapshot que se transfieren durante la inicialización y la actualización. También puede definir reglas para las políticas predeterminadas con el tipo de política «mirror-vault».

.Acerca de esta tarea
Todas las normas que tengan el tipo de política «espejo» deben tener una regla que especifique las copias snapshot que desea replicar. La regla «'bimensual'», por ejemplo, indica que sólo deben replicarse las copias snapshot asignadas a la etiqueta «'bimensual'» de SnapMirror. La etiqueta de SnapMirror se asigna al configurar copias de Snapshot de Element.

Cada tipo de política está asociado a una o más reglas definidas por el sistema. Estas reglas se asignan automáticamente a una directiva cuando se especifica su tipo de directiva. La siguiente tabla muestra las reglas definidas por el sistema.

|===


| Regla definida por el sistema | Se utiliza en tipos de políticas | Resultado 


 a| 
sm_creado
 a| 
reflejo asíncrono, reflejo de almacenes
 a| 
Una copia Snapshot creada por SnapMirror se transfiere tras la inicialización y la actualización.



 a| 
todos los días
 a| 
mirror-vault
 a| 
Las nuevas copias snapshot del origen con la etiqueta de SnapMirror «día» se transfieren durante la inicialización y actualización.



 a| 
semanal
 a| 
mirror-vault
 a| 
Al inicializar y actualizar, se transfieren las nuevas copias snapshot del origen con la etiqueta de SnapMirror «'Weekly».



 a| 
mensual
 a| 
mirror-vault
 a| 
Las nuevas copias snapshot en el origen con la etiqueta de SnapMirror «mensual» se transfieren durante la inicialización y actualización.

|===
Puede especificar reglas adicionales según sea necesario, para directivas predeterminadas o personalizadas. Por ejemplo:

* Para el valor predeterminado `MirrorAndVault` Política puede crear una regla llamada «bimensual» para hacer coincidir las copias Snapshot de la fuente con la etiqueta «bimensual» de SnapMirror.
* En el caso de una política personalizada con el tipo de política «mercado de productos vault», puede crear una regla llamada «bisemanal» para hacer coincidir las copias Snapshot del origen con la etiqueta de SnapMirror «bisemanales».


.Paso
. Definir una regla para una directiva:
+
`snapmirror policy add-rule -vserver _SVM_ -policy _policy_for_rule_ -snapmirror-label _snapmirror-label_ -keep _retention_count_`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
En el siguiente ejemplo, se añade una regla con la etiqueta de SnapMirror `bi-monthly` al valor predeterminado `MirrorAndVault` política:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy MirrorAndVault -snapmirror-label bi-monthly -keep 6
----
+
En el siguiente ejemplo, se añade una regla con la etiqueta de SnapMirror `bi-weekly` al personalizado `my_snapvault` política:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy my_snapvault -snapmirror-label bi-weekly -keep 26
----
+
En el siguiente ejemplo, se añade una regla con la etiqueta de SnapMirror `app_consistent` al personalizado `Sync` política:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy Sync -snapmirror-label app_consistent -keep 1
----
+
Luego, puede replicar las copias Snapshot del clúster de origen que coincidan con esta etiqueta de SnapMirror:

+
[listing]
----
cluster_src::> snapshot create -vserver vs1 -volume vol1 -snapshot snapshot1 -snapmirror-label app_consistent
----

