---
permalink: element-replication/make-destination-volume-writeable-task.html 
sidebar: sidebar 
keywords: make, destination, volume, write 
summary: Debe hacer que el volumen de destino sea editable, para poder proporcionar datos del volumen a los clientes. Puede utilizar el comando snapmirror QUIESCE para detener las transferencias programadas al destino, el comando snapmirror abort para detener las transferencias continuas y el comando snapmirror break para hacer que el destino sea editable. 
---
= Haga que el volumen de destino sea modificable
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando el desastre deshabilita el sitio principal para una relación de recuperación ante desastres de SnapMirror, puede proporcionar datos del volumen de destino con una interrupción mínima. Se puede reactivar el volumen de origen cuando el servicio se restaura en el sitio primario.

Debe hacer que el volumen de destino sea editable, para poder proporcionar datos del volumen a los clientes. Puede utilizar el `snapmirror quiesce` comando para detener las transferencias programadas al destino, el `snapmirror abort` comando para detener las transferencias continuas y el `snapmirror break` comando para hacer que el destino sea editable.

.Acerca de esta tarea
Debe especificar la ruta de origen del elemento en el formulario `_hostip:_/lun/_name_`, donde «'lun'» es la cadena real «'lun'» y. `name` Es el nombre del volumen de Element.

.Pasos
. Detenga las transferencias programadas al destino:
+
`snapmirror quiesce -source-path _hostip:_/lun/_name_ -destination-path _SVM:volume_|_cluster://SVM/volume_`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
El siguiente ejemplo detiene las transferencias programadas entre el volumen de origen `0005` En la dirección IP 10.0.0.11 y el volumen de destino `volA_dst` encendido `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----
. Detenga las transferencias continuas al destino:
+
`snapmirror abort -source-path _hostip:_/lun/_name_ -destination-path _SVM:volume_|_cluster://SVM/volume_`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
El siguiente ejemplo detiene las transferencias continuas entre el volumen de origen `0005` En la dirección IP 10.0.0.11 y el volumen de destino `volA_dst` encendido `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror abort -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----
. Rompa la relación de recuperación ante desastres de SnapMirror:
+
`snapmirror break -source-path _hostip:_/lun/_name_ -destination-path _SVM:volume_|_cluster://SVM/volume_`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
En el siguiente ejemplo, se rompe la relación entre el volumen de origen `0005` En la dirección IP 10.0.0.11 y el volumen de destino `volA_dst` encendido `svm_backup` y el volumen de destino `volA_dst` encendido `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror break -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----

