---
permalink: tape-backup/access-event-log-files-backup-restore-operations-task.html 
sidebar: sidebar 
keywords: access, event, log, files, rdfile, nodeshell, tap, backup, monitor, restore, operations 
summary: Puede acceder a los archivos de registro de eventos para las operaciones de copia de seguridad y restauración en cinta en el directorio /etc/log/ mediante el comando rdfile en el Nodesinfierno. Es posible ver estos archivos de registro de eventos para supervisar las operaciones de backup a cinta y restauración. 
---
= Acceda a los archivos de registro de eventos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible acceder a los archivos de registro de eventos para las operaciones de backup a cinta y restauración en la `/etc/log/` mediante el directorio `rdfile` orden en el nodesinfierno. Es posible ver estos archivos de registro de eventos para supervisar las operaciones de backup a cinta y restauración.

.Acerca de esta tarea
Con configuraciones adicionales, como una función de control de acceso con acceso al `spi` servicio web o una cuenta de usuario configurada con `http` método de acceso, también puede utilizar un explorador web para acceder a estos archivos de registro.

.Pasos
. Para acceder a nodeshell, introduzca el siguiente comando:
+
`*node run -node _node_name_*`

+
`node_name` es el nombre del nodo.

. Para acceder a los archivos del registro de eventos para las operaciones de backup a cinta y restauración, escriba el siguiente comando:
+
`*rdfile /etc/log/backup*`



.Información relacionada
link:../system-admin/index.html["Administración del sistema"]

link:../concepts/index.html["Conceptos de ONTAP"]
