---
permalink: tape-backup/assign-tape-aliases-task.html 
sidebar: sidebar 
keywords: assign, tape, aliases, device, identification, drive, medium, changer, logical, names, backup 
summary: Para facilitar la identificación del dispositivo, puede asignar alias de cinta a una unidad de cinta o a un cambiador de medios. Los alias proporcionan una correspondencia entre los nombres lógicos de los dispositivos de copia de seguridad y un nombre asignado permanentemente a la unidad de cinta o al cambiador de medios. 
---
= Asignar alias de cinta a una unidad de cinta o cambiador de medios para la copia de seguridad en cinta ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para facilitar la identificación del dispositivo, puede asignar alias de cinta a una unidad de cinta o a un cambiador de medios. Los alias proporcionan una correspondencia entre los nombres lógicos de los dispositivos de copia de seguridad y un nombre asignado permanentemente a la unidad de cinta o al cambiador de medios.

.Pasos
. Asigne un alias a una unidad de cinta o a un cambiador de medios mediante el `storage tape alias set` comando.
+
Obtenga más información sobre `storage tape alias set` en el link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-alias-set.html["Referencia de comandos del ONTAP"^].

+
Puede ver la información del número de serie (SN) sobre las unidades de cinta mediante el `system node hardware tape drive show` comando y sobre las bibliotecas de cintas mediante los `system node hardware tape library show` comandos.

+
El siguiente comando establece un nombre de alias en una unidad de cinta con el número de serie SN[123456]L4 conectado al nodo, cluster1-01:

+
[listing]
----
cluster-01::> storage tape alias set  -node cluster-01 -name st3 -mapping SN[123456]L4
----
+
El siguiente comando establece un nombre de alias en un cambiador de medios con el número de serie SN[65432] conectado al nodo, cluster1-01:

+
[listing]
----
cluster-01::> storage tape alias set  -node cluster-01 -name mc1 -mapping SN[65432]
----


.Información relacionada
* xref:assign-tape-aliases-concept.adoc[Qué es el solapamiento de cinta]
* xref:remove-tape-aliases-task.adoc[Eliminación de alias de cinta]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-alias-set.html["conjunto de alias de cinta de almacenamiento"^]

