---
permalink: tape-backup/before-restoring-data-concept.html 
sidebar: sidebar 
keywords: considerations, restore, file, data, original, path, destination, operation, required, space 
summary: Puede restaurar los datos de los que se ha realizado una copia de seguridad en su ruta original o en otro destino. Si va a restaurar datos con un backup en otro destino, debe preparar el destino para la operación de restauración. 
---
= Consideraciones que tener en cuenta antes de restaurar datos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede restaurar los datos de los que se ha realizado una copia de seguridad en su ruta original o en otro destino. Si va a restaurar datos con un backup en otro destino, debe preparar el destino para la operación de restauración.

Antes de restaurar datos en su ruta original o en un destino diferente, debe disponer de la siguiente información y cumplir los requisitos siguientes:

* El nivel de la restauración
* La ruta a la que se van a restaurar los datos
* El factor de bloqueo utilizado durante el backup
* Si realiza una restauración incremental, todas las cintas deben estar en la cadena de backup
* Una unidad de cinta disponible y compatible con la cinta a restaurar


Antes de restaurar los datos en otro destino, debe ejecutar las operaciones siguientes:

* Si va a restaurar un volumen, debe crear un volumen nuevo.
* Si va a restaurar un qtree o un directorio, debe cambiar el nombre de los archivos que probablemente tengan los mismos nombres que los archivos que va a restaurar.


[NOTE]
====
En ONTAP 9, los nombres de qtree admiten el formato Unicode. Las versiones anteriores de ONTAP no admiten este formato. Si un qtree con nombres Unicode en ONTAP 9 se copia en una versión anterior de ONTAP mediante `ndmpcopy` O mediante la restauración desde una imagen de copia de seguridad en una cinta, el qtree se restaura como un directorio normal y no como un qtree con formato Unicode.

====
[NOTE]
====
Si un archivo restaurado tiene el mismo nombre que un archivo existente, el archivo existente se sobrescribe con el archivo restaurado. Sin embargo, los directorios no se sobrescriben.

====
Para cambiar el nombre de un archivo, directorio o qtree durante la restauración sin usar DAR, debe configurar la variable de entorno DE EXTRACCIÓN en `E`.



== Espacio requerido en el sistema de almacenamiento de destino

Necesita aproximadamente 100 MB de espacio en el sistema de almacenamiento de destino que la cantidad de datos que se van a restaurar.

[NOTE]
====
La operación de restauración comprueba la disponibilidad de espacio de los volúmenes y de nodos de información en el volumen de destino cuando se inicia la operación de restauración. Establecer la variable de entorno FORCE a. `Y` hace que la operación de restauración omita las comprobaciones del espacio del volumen y de la disponibilidad de nodos de información en la ruta de destino. Si no hay suficiente espacio o inodos disponibles en el volumen de destino, la operación de restauración recupera la cantidad de datos permitidos por el espacio del volumen de destino y la disponibilidad del inodo. La operación de restauración se detiene cuando no queda más espacio del volumen o inodos.

====