---
permalink: tape-backup/commands-verify-library-connections-reference.html 
sidebar: sidebar 
keywords: commands, verify, tape, library, connections, storage, system 
summary: Puede ver información acerca de la ruta de conexión entre un sistema de almacenamiento y una configuración de biblioteca de cintas conectada al sistema de almacenamiento. Puede utilizar esta información para verificar la ruta de conexión a la configuración de la biblioteca de cintas o para solucionar problemas relacionados con las rutas de conexión. 
---
= Comandos para verificar las conexiones de la biblioteca de cintas en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ver información acerca de la ruta de conexión entre un sistema de almacenamiento y una configuración de biblioteca de cintas conectada al sistema de almacenamiento. Puede utilizar esta información para verificar la ruta de conexión a la configuración de la biblioteca de cintas o para solucionar problemas relacionados con las rutas de conexión.

Puede ver los siguientes detalles de la biblioteca de cintas para verificar las conexiones de la biblioteca de cintas después de agregar o crear una biblioteca de cintas nueva, o después de restaurar una ruta de acceso fallida en una ruta única o acceso multivía a una biblioteca de cintas. También puede utilizar esta información al solucionar errores relacionados con la ruta de acceso o si el acceso a una biblioteca de cintas falla.

* Nodo al que está conectada la biblioteca de cintas
* ID del dispositivo
* Ruta NDMP
* Nombre de la biblioteca de cintas
* ID de puerto de destino e puerto de iniciador
* Acceso de ruta única o multivía a una biblioteca de cintas para cada puerto iniciador FC o de destino
* Detalles de la integridad de los datos relacionados con la ruta, como «'errores de ruta'» y «'Manual de ruta'».
* Los grupos LUN y el número de LUN


|===
| Si desea... | Se usa este comando... 


 a| 
Ver información sobre una biblioteca de cintas en un clúster
 a| 
`system node hardware tape library show`



 a| 
Ver información de ruta de una biblioteca de cintas
 a| 
`storage tape library path show`



 a| 
Vea la información de ruta de una biblioteca de cintas para cada puerto iniciador
 a| 
`storage tape library path show-by-initiator`



 a| 
Vea la información de conectividad entre una biblioteca de cinta de almacenamiento y un clúster
 a| 
`storage tape library config show`

|===
Obtenga más información sobre `storage tape library` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+tape+library["Referencia de comandos de la ONTAP"^].
