---
permalink: tape-backup/common-ndmp-topologies-reference.html 
sidebar: sidebar 
keywords: ndmp, tape, backup, topologies, storage, system, local, data, server 
summary: 'NDMP admite una serie de topologías y configuraciones entre aplicaciones de backup y sistemas de almacenamiento u otros servidores NDMP que proporcionan datos (sistemas de archivos) y servicios de cinta.' 
---
= Topologías habituales de backup en cinta NDMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NDMP admite una serie de topologías y configuraciones entre aplicaciones de backup y sistemas de almacenamiento u otros servidores NDMP que proporcionan datos (sistemas de archivos) y servicios de cinta.



== Del sistema de almacenamiento a la cinta local

En la configuración más simple, una aplicación de copia de seguridad realiza una copia de seguridad de los datos de un sistema de almacenamiento a un subsistema de cinta conectado al sistema de almacenamiento. La conexión de control NDMP existe en el límite de la red. La conexión de datos NDMP que existe dentro del sistema de almacenamiento entre los servicios de datos y cinta se denomina configuración local NDMP.



== Sistema de almacenamiento a cinta conectado a otro sistema de almacenamiento

Una aplicación de backup también puede realizar backups de datos de un sistema de almacenamiento en una librería de cintas (un cambiador medio con una o varias unidades de cinta) conectada a otro sistema de almacenamiento. En este caso, la conexión de datos NDMP entre los servicios de datos y la cinta se proporciona mediante una conexión de red TCP o TCP/IPv6. Esto se denomina configuración de sistema de almacenamiento triple NDMP.



== Librería de cintas conectada a la red y del sistema de almacenamiento

Las bibliotecas de cinta compatibles con NDMP proporcionan una variación de la configuración triple. En este caso, la biblioteca de cintas se conecta directamente a la red TCP/IP y se comunica con la aplicación de backup y el sistema de almacenamiento a través de un servidor NDMP interno.



== Almacenamiento del sistema al servidor de datos, a cinta o servidor de datos al sistema de almacenamiento a cinta

NDMP también admite configuraciones triples de sistemas de almacenamiento para servidores de datos y sistemas de datos-servidor-almacenamiento, aunque estas variantes se implementan menos en gran medida. El sistema de almacenamiento al servidor permite realizar backups de los datos del sistema de almacenamiento en una biblioteca de cintas conectada al host de aplicaciones de backup o a otro sistema servidor de datos. La configuración de servidor a sistema de almacenamiento permite realizar copias de seguridad de los datos del servidor en una biblioteca de cintas conectada al sistema de almacenamiento.
