---
permalink: tape-backup/configure-multipath-access-concept.html 
sidebar: sidebar 
keywords: considerations, configuring, multipath, tape, access 
summary: Puede configurar dos rutas desde el sistema de almacenamiento para acceder a las unidades de cinta de una biblioteca de cintas. Si falla una ruta, el sistema de almacenamiento puede utilizar las otras rutas para acceder a las unidades de cinta sin tener que reparar inmediatamente la ruta con error. Esto garantiza que se puedan reiniciar las operaciones de cinta. 
---
= Consideraciones al configurar el acceso a cinta multiruta de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar dos rutas desde el sistema de almacenamiento para acceder a las unidades de cinta de una biblioteca de cintas. Si falla una ruta, el sistema de almacenamiento puede utilizar las otras rutas para acceder a las unidades de cinta sin tener que reparar inmediatamente la ruta con error. Esto garantiza que se puedan reiniciar las operaciones de cinta.

Al configurar el acceso a cinta multivía desde el sistema de almacenamiento, debe tener en cuenta lo siguiente:

* En bibliotecas de cintas que admiten la asignación de LUN, para acceder de varias rutas a un grupo LUN, la asignación de LUN debe ser simétrica en cada ruta.
+
Las unidades de cinta e intercambiadores de medios se asignan a grupos de LUN (conjunto de LUN que comparten el mismo conjunto de rutas del iniciador) en una biblioteca de cintas. Todas las unidades de cinta de un grupo LUN deben estar disponibles para las operaciones de backup y restauración en todas las rutas múltiples.

* Se puede configurar un máximo de dos rutas desde el sistema de almacenamiento para acceder a las unidades de cinta de una biblioteca de cintas.
* El acceso a cinta multivía es compatible con el equilibrio de carga. El equilibrio de carga está deshabilitado de forma predeterminada.


En el ejemplo siguiente, el sistema de almacenamiento accede al grupo LUN 0 a través de dos rutas de iniciador: 0b y 0d. En estas dos rutas, el grupo de LUN tiene el mismo número de LUN, 0 y el número de LUN, 5. El sistema de almacenamiento accede al grupo LUN 1 a través de solo una ruta de iniciador, 3d.

[listing]
----

STSW-3070-2_cluster::> storage tape library config show

Node                    LUN Group   LUN Count  Library Name  Library Target Port  Initiator
----------------------- ----------- ---------- ------------- -------------------- -----
STSW-3070-2_cluster-01        0      5         IBM 3573-TL_1  510a09800000412d     0b
                                                                                  	0d
                              1      2         IBM 3573-TL_2  50050763124b4d6f     3d

3 entries were displayed
----
.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-library-config-show.html["Mostrar configuración de la biblioteca de cintas de almacenamiento"^]

