---
permalink: tape-backup/could-not-initialize-media-reference.html 
sidebar: sidebar 
keywords: initiate, media, error, corrective, action, fix, problem, tape, drive, corrupt, damaged, backup, active, io, thread 
summary: No se pudo inicializar el medio. 
---
= No se pudo inicializar el medio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
* *Mensaje*
+
`Could not initialize media`

* *Causa*
+
Puede obtener este error por uno de los siguientes motivos:

+
** La unidad de cinta utilizada para la copia de seguridad está dañada o dañada.
** La cinta no contiene la copia de seguridad completa o está dañada.
** El número máximo de subprocesos de E/S de cinta local activos está actualmente en uso.
+
Puede tener un máximo de 16 unidades de cinta locales activas.



* *Acción Correctiva*
+
** Si la unidad de cinta está dañada o dañada, vuelva a intentar la operación con una unidad de cinta válida.
** Si la cinta no contiene la copia de seguridad completa o está dañada, no podrá realizar la operación de restauración.
** Si no hay recursos de cinta disponibles, espere a que finalicen algunos de los trabajos de backup o restauración y vuelva a intentar la operación.



