---
permalink: tape-backup/data-backup-dump-concept.html 
sidebar: sidebar 
keywords: dump, engine, flexvol, volumes, backup, recovery, snapshot, copy, tape, device 
summary: Dump es una solución de copia de seguridad y recuperación basada en instantáneas de ONTAP que le ayuda a realizar copias de seguridad de archivos y directorios desde una instantánea a un dispositivo de cinta y restaurar los datos de los que se ha realizado la copia de seguridad en un sistema de almacenamiento. 
---
= Acerca del motor de volcado para volúmenes FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dump es una solución de copia de seguridad y recuperación basada en instantáneas de ONTAP que le ayuda a realizar copias de seguridad de archivos y directorios desde una instantánea a un dispositivo de cinta y restaurar los datos de los que se ha realizado la copia de seguridad en un sistema de almacenamiento.

Puede realizar una copia de seguridad de los datos del sistema de archivos, como directorios, archivos y su configuración de seguridad asociada, en un dispositivo de cinta mediante la copia de seguridad de volcado. Puede realizar backup de un volumen completo, de un qtree completo o de un subárbol que no sea ni un volumen completo ni un qtree completo.

Puede realizar un backup o una restauración de volcado utilizando aplicaciones de backup compatibles con NDMP.

Al realizar una copia de seguridad de volcado, puede especificar la instantánea que se utilizará para una copia de seguridad. Si no se especifica una instantánea para la copia de seguridad, el motor de volcado crea una instantánea para la copia de seguridad. Una vez finalizada la operación de copia de seguridad, el motor de volcado elimina esta instantánea.

Puede realizar copias de seguridad de nivel 0, incrementales o diferenciales en cinta utilizando el motor de descarga.

[NOTE]
====
Después de revertir a una versión anterior a Data ONTAP 8.3, debe ejecutar una operación de backup base antes de realizar una operación de backup incremental.

====
.Información relacionada
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ug-rdg/home.html["Actualización, reversión o degradación"]
