---
permalink: tape-backup/dump-snapmirror-single-file-lun-restore-concept.html 
sidebar: sidebar 
keywords: dump, works, snapmirror, single, file, lun, restore, operation 
summary: Antes de realizar operaciones de volcado de backup o restauración en un volumen en el que se restaura un solo archivo o LUN mediante la tecnología SnapMirror, debe entender cómo funcionan las operaciones de volcado con una sola operación de restauración de archivos o LUN. 
---
= Cómo funciona el volcado con una restauración de un solo archivo o LUN de ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de realizar operaciones de volcado de backup o restauración en un volumen en el que se restaura un solo archivo o LUN mediante la tecnología SnapMirror, debe entender cómo funcionan las operaciones de volcado con una sola operación de restauración de archivos o LUN.

Durante una operación de restauración de un único archivo o LUN de SnapMirror, las I/o del cliente están restringidas en el archivo o LUN que se van a restaurar. Cuando la operación de restauración de archivos o LUN individuales finaliza, se elimina la restricción de I/o del archivo o LUN. Si se realiza un backup de volcado en un volumen para el que se restaura un solo archivo o LUN, el archivo o el LUN que tiene restricción de I/o del cliente no se incluye en el backup de volcado. En una operación de copia de seguridad posterior, se realiza una copia de seguridad de este archivo o LUN en cinta después de eliminar la restricción de E/S.

No se puede realizar una restauración de volcado y una operación de restauración de archivos o LUN de SnapMirror simultáneamente en el mismo volumen.
