---
permalink: tape-backup/dump-backup-restore-operations-mcc-config-concept.html 
sidebar: sidebar 
keywords: dump, backup, restore, opartion, metrocluster, configuration, switchback, switchover 
summary: Antes de llevar a cabo operaciones de backup de volcado y restauración en una configuración de MetroCluster, debe comprender cómo se ven afectadas las operaciones de volcado cuando se produzca una operación de conmutación de sitios o conmutación de estado. 
---
= Cómo las operaciones de volcado de backup y restauración se ven afectadas por las configuraciones de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de llevar a cabo operaciones de backup de volcado y restauración en una configuración de MetroCluster, debe comprender cómo se ven afectadas las operaciones de volcado cuando se produzca una operación de conmutación de sitios o conmutación de estado.



== Operación de copia de seguridad o restauración de volcado seguida de la conmutación

Considere dos clústeres: El clúster 1 y el clúster 2. Durante una operación de backup de volcado o restauración en el clúster 1, si se inicia una conmutación por error desde el clúster 1 al clúster 2, se produce lo siguiente:

* Si el valor de `override-vetoes` la opción es `false`, a continuación, se cancela la operación de switchover y continúa la operación de copia de seguridad o restauración.
* Si el valor de la opción es `true`, la operación de copia de seguridad de volcado o restauración se cancela y la operación de switchover continúa.




== Operación de copia de seguridad o restauración de volcado seguida de una conmutación de estado

Una conmutación de sitios se realiza desde el clúster 1 al clúster 2 y se inicia una operación de backup de volcado o restauración en el clúster 2. La operación de volcado realiza un backup o restaura un volumen ubicado en el clúster 2. En este punto, si se inicia una conmutación de estado del clúster 2 al clúster 1, sucede lo siguiente:

* Si el valor de `override-vetoes` la opción es `false`, a continuación, la conmutación de regreso se cancela y la operación de copia de seguridad o restauración continúa.
* Si el valor de la opción es `true`, a continuación, la operación de copia de seguridad o restauración se cancela y la conmutación de regreso continúa.




== La operación de backup o restauración de volcado se inició durante una conmutación de sitios o una conmutación de estado

Durante una conmutación de sitios del clúster 1 al clúster 2, si se inicia una operación de backup de volcado o restauración en el clúster 1, las operaciones de backup o restauración fallan y la conmutación continúa.

Durante una conmutación de estado del clúster 2 al clúster 1, si se inicia una operación de backup o restauración de volcado desde el clúster 2, la operación de backup o restauración dará error y esta continuará.
