---
permalink: tape-backup/failed-to-initialize-restore-stream-reference.html 
sidebar: sidebar 
keywords: failed, initialize, restore, stream, smtape, tape, block, factor, corrupt, damaged, wrong 
summary: Error al inicializar el flujo de restauración. 
---
= Error al inicializar el flujo de restauración
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
* *Mensaje*
+
`Failed to initialize restore stream`

* *Causa*
+
Puede obtener este mensaje de error por uno de los siguientes motivos:

+
** La imagen de copia de seguridad no es de SMTape.
** El factor de bloqueo de cinta especificado es incorrecto.
** La cinta está dañada o dañada.
** Se ha cargado una cinta incorrecta para la restauración.


* *Acción Correctiva*
+
** Si la imagen de copia de seguridad no es de SMTape, vuelva a intentar la operación con una cinta que tenga la copia de seguridad de SMTape.
** Si el factor de bloqueo es incorrecto, especifique el factor de bloqueo correcto y vuelva a intentar la operación.
** Si la cinta está dañada, no podrá realizar la operación de restauración.
** Si se carga la cinta incorrecta, vuelva a intentar la operación con la cinta correcta.



