---
permalink: tape-backup/generate-ndmp-password-users-task.html 
sidebar: sidebar 
keywords: generate, ndmp, specific, password, user, svm, storage, virtual, machine, login 
summary: 'En el modo NDMP de la máquina virtual de almacenamiento (SVM), debe generar una contraseña para un ID de usuario específico. La contraseña generada se basa en la contraseña de inicio de sesión real para el usuario NDMP. Si cambia la contraseña de inicio de sesión real, deberá generar de nuevo la contraseña específica de NDMP.' 
---
= Generar una contraseña específica de NDMP para los usuarios de ONTAP NDMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En el modo NDMP de la máquina virtual de almacenamiento (SVM), debe generar una contraseña para un ID de usuario específico. La contraseña generada se basa en la contraseña de inicio de sesión real para el usuario NDMP. Si cambia la contraseña de inicio de sesión real, deberá generar de nuevo la contraseña específica de NDMP.

.Pasos
. Utilice `vserver services ndmp generate-password` el comando para generar una contraseña específica de NDMP.
+
Puede utilizar esta contraseña en cualquier operación NDMP actual o futura que requiera la introducción de la contraseña.

+
[NOTE]
====
Desde el contexto de la máquina virtual de almacenamiento (SVM, antes denominada Vserver), puede generar contraseñas de NDMP para usuarios que solo pertenecen a esa SVM.

====
+
El ejemplo siguiente muestra cómo generar una contraseña específica de NDMP para un ID de usuario usuario1:

+
[listing]
----

cluster1::vserver services ndmp> generate-password -vserver vs1 -user user1

Vserver: vs1
User: user1
Password: jWZiNt57huPOoD8d
----
. Si cambia la contraseña a su cuenta de sistema de almacenamiento normal, repita este procedimiento para obtener su nueva contraseña específica de NDMP.

