---
permalink: tape-backup/index.html 
sidebar: sidebar 
keywords: tape, backup, flexvol, volumes, overview, ndmp, network, data, management, protocol, sump, smtape 
summary: ONTAP es compatible con los procesos de backup y restauración a cinta mediante el protocolo de gestión de datos de red. 
---
= Obtenga información sobre la copia de seguridad en cinta de los volúmenes ONTAP FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP es compatible con los procesos de backup y restauración a cinta mediante el protocolo de gestión de datos de red (NDMP). NDMP le permite realizar backups de datos en sistemas de almacenamiento directamente en cinta, lo cual resulta en un uso más eficiente del ancho de banda de la red. ONTAP es compatible con los motores de volcado y SMTape para backups a cinta.

Puede realizar backups o restauraciones de volcado o SMTape mediante aplicaciones de backup compatibles con NDMP. Solo se admite la versión 4 de NDMP.



== Copia de seguridad en cinta mediante volcado

Dump es una copia de seguridad basada en instantáneas en la que se realizan copias de seguridad de los datos del sistema de archivos en cinta. El motor de volcado ONTAP realiza copias de seguridad de los archivos, directorios y la información de la lista de control de acceso (ACL) aplicable a la cinta. Puede realizar un backup de un volumen completo, de un qtree completo o de un subárbol que no sea un volumen completo o un qtree completo. El volcado admite copias de seguridad de línea base, diferencial e incrementales.



== Backup en cinta con SMTape

SMTape es una solución de recuperación ante desastres basada en Snapshot de ONTAP que realiza backups de bloques de datos a cinta. Puede usar SMTape para realizar backups de volúmenes a las cintas. Sin embargo, no puede realizar un backup en el nivel qtree o subárbol. SMTape admite copias de seguridad de línea base, diferenciales e incrementales.

A partir de ONTAP 9.13.1, el backup en cinta con SMTape es compatible con xref:../snapmirror-active-sync/interoperability-reference.html[SnapMirror síncrono activo].
