---
permalink: tape-backup/manage-node-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: manage, node, scope, ndmp, mode, flexvol, volume, command, option, backup, restore 
summary: Puede administrar NDMP en el nivel de nodo mediante los comandos y las opciones de NDMP. Las opciones de NDMP se pueden modificar mediante el comando options. Es necesario usar credenciales específicas de NDMP para acceder a un sistema de almacenamiento a fin de ejecutar operaciones de backup y restauración a cinta. 
---
= Obtenga información sobre cómo administrar el modo NDMP con ámbito de nodo de ONTAP para volúmenes FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede administrar NDMP en el nivel de nodo mediante los comandos y las opciones de NDMP. Puede modificar las opciones de NDMP mediante `options` el comando. Es necesario usar credenciales específicas de NDMP para acceder a un sistema de almacenamiento a fin de ejecutar operaciones de backup y restauración a cinta.

Obtenga más información sobre `options` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=options["Referencia de comandos del ONTAP"^].



== Comandos para administrar el modo NDMP con ámbito de nodo de ONTAP

Puede usar `system services ndmp` los comandos para gestionar NDMP a nivel de nodo. Algunos de estos comandos quedan obsoletos y se quitarán en una versión principal futura.

Puede utilizar los siguientes comandos NDMP solamente en el nivel de privilegio avanzado:

* `system services ndmp service terminate`
* `system services ndmp service start`
* `system services ndmp service stop`
* `system services ndmp log start`
* `system services ndmp log stop`


|===
| Si desea... | Se usa este comando... 


 a| 
Active el servicio NDMP
 a| 
`system services ndmp on`*



 a| 
Desactive el servicio NDMP
 a| 
`system services ndmp off`*



 a| 
Mostrar la configuración de NDMP
 a| 
`system services ndmp show`*



 a| 
Modifique la configuración de NDMP
 a| 
`system services ndmp modify`*



 a| 
Muestra la versión predeterminada de NDMP
 a| 
`system services ndmp version`*



 a| 
Mostrar la configuración del servicio NDMP
 a| 
`system services ndmp service show`



 a| 
Modifique la configuración del servicio NDMP
 a| 
`system services ndmp service modify`



 a| 
Mostrar todas las sesiones de NDMP
 a| 
`system services ndmp status`



 a| 
Mostrar información detallada acerca de todas las sesiones NDMP
 a| 
`system services ndmp probe`



 a| 
Finalice la sesión NDMP especificada
 a| 
`system services ndmp kill`



 a| 
Finalice todas las sesiones NDMP
 a| 
`system services ndmp kill-all`



 a| 
Cambie la contraseña NDMP
 a| 
`system services ndmp password`*



 a| 
Habilite el modo de NDMP de ámbito del nodo
 a| 
`system services ndmp node-scope-mode on`*



 a| 
Deshabilite el modo NDMP de ámbito del nodo
 a| 
`system services ndmp node-scope-mode off`*



 a| 
Muestra el estado del modo NDMP de ámbito del nodo
 a| 
`system services ndmp node-scope-mode status`*



 a| 
Cierre todas las sesiones NDMP con fuerza
 a| 
`system services ndmp service terminate`



 a| 
Inicie el demonio del servicio NDMP
 a| 
`system services ndmp service start`



 a| 
Detenga el demonio del servicio NDMP
 a| 
`system services ndmp service stop`



 a| 
Inicie el registro para la sesión NDMP especificada
 a| 
`system services ndmp log start`*



 a| 
Detenga el registro de la sesión NDMP especificada
 a| 
`system services ndmp log stop`*

|===
* Estos comandos quedaron obsoletos y se quitarán en una versión principal futura.


Obtenga más información sobre `system services ndmp` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+services+ndmp["Referencia de comandos del ONTAP"^].



== Autenticación de usuario en un modo NDMP de ámbito de nodo

En el modo NDMP de ámbito del nodo, debe utilizar credenciales específicas de NDMP para acceder a un sistema de almacenamiento a fin de realizar operaciones de backup y restauración a cinta.

El ID de usuario predeterminado es "'root'". Antes de usar NDMP en un nodo, debe asegurarse de cambiar la contraseña de NDMP predeterminada asociada con el usuario NDMP. También es posible cambiar el ID de usuario predeterminado de NDMP.

.Información relacionada
xref:commands-manage-node-scoped-ndmp-reference.adoc[Comandos para gestionar el modo NDMP de ámbito de nodo]

xref:node-scoped-ndmp-mode-concept.adoc[Lo que es el modo NDMP de ámbito del nodo]
