---
permalink: tape-backup/manage-svm-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: manage, svm, scope, ndmp, flexvol, volumes, vserver, modify 
summary: Puede gestionar NDMP por SVM usando las opciones y los comandos de NDMP. Puede modificar las opciones NDMP mediante el comando vserver Services ndmp modify. En el modo NDMP con ámbito SVM, la autenticación del usuario está integrada con el mecanismo de control de acceso basado en roles. 
---
= Gestione la información general sobre el modo NDMP de ámbito SVM para FlexVol Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede gestionar NDMP por SVM usando las opciones y los comandos de NDMP. Las opciones de NDMP se pueden modificar mediante el `vserver services ndmp modify` comando. En el modo NDMP con ámbito SVM, la autenticación del usuario está integrada con el mecanismo de control de acceso basado en roles.

Puede agregar NDMP a la lista de protocolos permitidos o no permitidos utilizando el `vserver modify` comando. De forma predeterminada, NDMP se encuentra en la lista de protocolos permitidos. Si se agrega NDMP a la lista de protocolos no permitidos, no se podrán establecer sesiones NDMP.

Puede controlar el tipo de LIF en el que se establece una conexión de datos NDMP mediante el `-preferred-interface-role` opción. Durante una conexión de datos NDMP, NDMP elige una dirección IP que pertenece al tipo de LIF tal como especifica esta opción. Si las direcciones IP no pertenecen a ninguno de estos tipos de LIF, no se puede establecer la conexión de datos NDMP. Para obtener más información acerca de `-preferred-interface-role` consulte las páginas man.

Para obtener más información acerca de `vserver services ndmp modify` consulte las páginas de manual.

.Información relacionada
xref:commands-manage-svm-scoped-ndmp-reference.adoc[Comandos para gestionar el modo NDMP con ámbito de la SVM]

xref:cluster-aware-backup-extension-concept.adoc[Qué hace la extensión Cluster Aware Backup]

link:../concepts/index.html["Conceptos de ONTAP"]

xref:svm-scoped-ndmp-mode-concept.adoc[Qué es el modo NDMP con ámbito SVM]

link:../system-admin/index.html["Administración del sistema"]
