---
permalink: tape-backup/manage-svm-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: manage, svm, scope, ndmp, flexvol, volumes, vserver, modify 
summary: Puede gestionar NDMP por SVM usando las opciones y los comandos de NDMP. Puede modificar las opciones NDMP mediante el comando vserver Services ndmp modify. En el modo NDMP con ámbito SVM, la autenticación del usuario está integrada con el mecanismo de control de acceso basado en roles. 
---
= Obtenga información sobre cómo administrar el modo NDMP con ámbito SVM de ONTAP para volúmenes FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede gestionar NDMP por SVM usando las opciones y los comandos de NDMP. Puede modificar las opciones de NDMP mediante `vserver services ndmp modify` el comando. En el modo NDMP con ámbito SVM, la autenticación del usuario está integrada con el mecanismo de control de acceso basado en roles.

Puede agregar NDMP en la lista de protocolos permitidos o no permitidos mediante `vserver modify` el comando. De forma predeterminada, NDMP se encuentra en la lista de protocolos permitidos. Si se agrega NDMP a la lista de protocolos no permitidos, no se podrán establecer sesiones NDMP.

Puede controlar el tipo de LIF en el que se establece una conexión de datos NDMP mediante `-preferred-interface-role` la opción. Durante una conexión de datos NDMP, NDMP elige una dirección IP que pertenece al tipo de LIF tal como especifica esta opción. Si las direcciones IP no pertenecen a ninguno de estos tipos de LIF, no se puede establecer la conexión de datos NDMP. Obtenga más información sobre `vserver services ndmp modify` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-services-ndmp-modify.html["Referencia de comandos del ONTAP"^].



== Comandos para administrar el modo NDMP con ámbito SVM de ONTAP

Puede utilizar `vserver services ndmp` los comandos para gestionar NDMP en cada máquina virtual de almacenamiento (SVM, antes denominada Vserver).

|===
| Si desea... | Se usa este comando... 


 a| 
Active el servicio NDMP
 a| 
`vserver services ndmp on`

[NOTE]
====
El servicio NDMP siempre debe estar habilitado en todos los nodos de un clúster. Puede habilitar el servicio NDMP en un nodo mediante `system services ndmp on` el comando. De manera predeterminada, el servicio NDMP siempre está habilitado en un nodo.

====


 a| 
Desactive el servicio NDMP
 a| 
`vserver services ndmp off`



 a| 
Mostrar la configuración de NDMP
 a| 
`vserver services ndmp show`



 a| 
Modifique la configuración de NDMP
 a| 
`vserver services ndmp modify`



 a| 
Muestra la versión NDMP predeterminada
 a| 
`vserver services ndmp version`



 a| 
Mostrar todas las sesiones de NDMP
 a| 
`vserver services ndmp status`



 a| 
Mostrar información detallada acerca de todas las sesiones NDMP
 a| 
`vserver services ndmp probe`



 a| 
Terminar una sesión NDMP especificada
 a| 
`vserver services ndmp kill`



 a| 
Finalice todas las sesiones NDMP
 a| 
`vserver services ndmp kill-all`



 a| 
Genere la contraseña NDMP
 a| 
`vserver services ndmp generate-password`



 a| 
Mostrar el estado de la extensión NDMP
 a| 
`vserver services ndmp extensions show`

Este comando solo está disponible en el nivel de privilegios avanzado.



 a| 
Modifique el estado de la extensión NDMP (enable o disable)
 a| 
`vserver services ndmp extensions modify`

Este comando solo está disponible en el nivel de privilegios avanzado.



 a| 
Inicie el registro para la sesión NDMP especificada
 a| 
`vserver services ndmp log start`

Este comando solo está disponible en el nivel de privilegios avanzado.



 a| 
Detenga el registro de la sesión NDMP especificada
 a| 
`vserver services ndmp log stop`

Este comando solo está disponible en el nivel de privilegios avanzado.

|===
Obtenga más información sobre `vserver services ndmp` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+ndmp["Referencia de comandos del ONTAP"^].

.Información relacionada
xref:commands-manage-svm-scoped-ndmp-reference.adoc[Comandos para gestionar el modo NDMP con ámbito de la SVM]

xref:cluster-aware-backup-extension-concept.adoc[Qué hace la extensión Cluster Aware Backup]

xref:svm-scoped-ndmp-mode-concept.adoc[Qué es el modo NDMP con ámbito SVM]

link:../system-admin/index.html["Administración del sistema"]
