---
permalink: tape-backup/ndmp-management-flexgroup-concept.html 
sidebar: sidebar 
keywords: understand, ndmp, flexgroup, volume, flexvol 
summary: A partir de ONTAP 9.7, NDMP es compatible con los volúmenes FlexGroup. 
---
= Obtenga información sobre la compatibilidad de NDMP con volúmenes ONTAP FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.7, NDMP es compatible con los volúmenes FlexGroup.

A partir de ONTAP 9.7, se admite el comando ndmpcopy para la transferencia de datos entre volúmenes FlexVol y FlexGroup.

Si se revierte de ONTAP 9.7 a una versión anterior, la información de transferencia incremental de las transferencias anteriores no se conserva y, por lo tanto, se debe realizar una copia básica después de revertir.

A partir de ONTAP 9.8, las siguientes funciones NDMP son compatibles con los volúmenes FlexGroup:

* El mensaje NDMP_SNAP_RECOVER de la clase de extensión 0x2050 se puede utilizar para recuperar archivos individuales de un volumen FlexGroup.
* Se admite la extensión de backup NDMP restartable (RBE) para los volúmenes de FlexGroup.
* Las variables de entorno EXCLUDE y MULTI_SUBTREE_NAMES son compatibles con los volúmenes FlexGroup.

