---
permalink: tape-backup/ndmp-extensions-supported-reference.html 
sidebar: sidebar 
keywords: ndmp, extensions, supported, ontap, v4, protocols, core, modify, extension 
summary: NDMP v4 proporciona un mecanismo para crear extensiones de protocolo NDMP v4 sin tener que modificar el protocolo NDMP v4 de núcleo. Debe conocer las extensiones de NDMP v4 compatibles con ONTAP. 
---
= Extensiones NDMP compatibles con ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NDMP v4 proporciona un mecanismo para crear extensiones de protocolo NDMP v4 sin tener que modificar el protocolo NDMP v4 de núcleo. Debe conocer las extensiones de NDMP v4 compatibles con ONTAP.

Las siguientes extensiones de NDMP v4 son compatibles con ONTAP:

* Respaldo para clúster (CAB)
+
[NOTE]
====
Esta extensión solo es compatible con el modo NDMP con el ámbito de la SVM.

====
* Extensión de dirección de conexión (cae) para compatibilidad con IPv6
* Clase de extensión 0x2050
+
Esta extensión admite operaciones de backup reiniciables y extensiones de administración de Snapshot.

+
[NOTE]
====
El `NDMP_SNAP_RECOVER` mensaje, que forma parte de las extensiones de gestión de Snapshot, se usa para iniciar una operación de recuperación y para transferir los datos recuperados de un snapshot local a una ubicación de sistema de archivos local. En ONTAP, este mensaje solo permite la recuperación de volúmenes y archivos normales.

El `NDMP_SNAP_DIR_LIST` mensaje le permite explorar las snapshots de un volumen. Si se realiza una operación no disruptiva mientras hay una operación de exploración en curso, la aplicación de backup debe volver a iniciar la operación de exploración.

====
* Extensión de copia de seguridad reiniciable NDMP
+
Puede utilizar la funcionalidad de extensión de backup reiniciable (RBE) de NDMP para reiniciar un backup desde un punto de control conocido en el flujo de datos antes del fallo.


