---
permalink: tape-backup/ndmp-modes-concept.html 
sidebar: sidebar 
keywords: ndmp, mode, operation, backup, restore, node, level, svm 
summary: 'Puede optar por realizar operaciones de backup y restauración a cinta, ya sea en el nivel de nodo o en el nivel de la máquina virtual de almacenamiento (SVM). Para ejecutar estas operaciones correctamente en el nivel de SVM, el servicio NDMP debe estar habilitado en la SVM.' 
---
= Conozca los modos de funcionamiento de ONTAP NDMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede optar por realizar operaciones de backup y restauración a cinta, ya sea en el nivel de nodo o en el nivel de la máquina virtual de almacenamiento (SVM). Para ejecutar estas operaciones correctamente en el nivel de SVM, el servicio NDMP debe estar habilitado en la SVM.

Si actualiza de Data ONTAP 8.2 a Data ONTAP 8.3, seguirá reteniendo el modo de funcionamiento NDMP usado en 8.2 después de la actualización de 8.2 a 8.3.

Si instala un clúster nuevo con Data ONTAP 8.2 o posterior, NDMP se encuentra en el modo NDMP de ámbito SVM de manera predeterminada. Para realizar operaciones de backup y restauración de cinta en el modo de NDMP de ámbito del nodo, debe habilitar explícitamente el modo de NDMP de ámbito del nodo.



== Obtenga información sobre el modo NDMP de ONTAP con ámbito de nodo

En el modo NDMP de ámbito del nodo, puede realizar operaciones de backup y restauración a cinta en el nivel del nodo. Se seguirá reteniendo el modo de funcionamiento NDMP usado en Data ONTAP 8.2 después de la actualización de 8.2 a 8.3.

En el modo NDMP de ámbito del nodo, puede realizar operaciones de backup y restauración de cinta en un nodo que posea el volumen. Para realizar estas operaciones, debe establecer conexiones de control NDMP en una LIF alojada en el nodo propietario de los dispositivos de volumen o cinta.

[NOTE]
====
Este modo quedó obsoleto y se quitará en un lanzamiento principal futuro.

====


== Obtenga información sobre el modo NDMP de ONTAP con ámbito SVM

Se pueden ejecutar operaciones de backup y restauración de cinta en el nivel de máquina virtual de almacenamiento (SVM) correctamente si el servicio NDMP está habilitado en la SVM. Puede realizar backups y restauraciones de todos los volúmenes alojados en diferentes nodos en la SVM de un clúster si la aplicación de backup admite la extensión CAB.

Se puede establecer una conexión de control NDMP en diferentes tipos de LIF. En el modo NDMP con ámbito SVM, estas LIF pertenecen a la SVM de datos o a la SVM de administrador. La conexión puede establecerse en un LIF solo si el servicio NDMP está habilitado en la SVM propietaria de este LIF.

Una LIF de datos pertenece a la SVM de datos y la LIF entre clústeres, la LIF de gestión de nodos y la LIF de gestión de clúster pertenecen a la SVM de administrador.

En el modo NDMP de ámbito SVM, la disponibilidad de volúmenes y dispositivos de cinta para operaciones de backup y restauración depende del tipo de LIF en el que se establezca la conexión de control NDMP y el estado de la extensión CAB. Si su aplicación de backup admite la extensión CAB y un volumen y el dispositivo de cinta comparten la misma afinidad, la aplicación de backup puede realizar una operación de backup o restauración local, en lugar de una operación de backup o restauración triple.

.Información relacionada
xref:commands-manage-node-scoped-ndmp-reference.adoc[Comandos para gestionar el modo NDMP de ámbito de nodo]
