---
permalink: tape-backup/physical-path-names-concept.html 
sidebar: sidebar 
keywords: physical, path, names, ppn, numerical, address, tape, drive, electrical 
summary: 'Los nombres de rutas físicas (PNP) son las secuencias de direcciones numéricas que ONTAP asigna a unidades de cinta y bibliotecas de cintas basadas en el adaptador o switch SCSI-2/3 (ubicación específica) que están conectados al sistema de almacenamiento. Los PPNS también se conocen como nombres eléctricos.' 
---
= Qué son los nombres de ruta física
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los nombres de rutas físicas (PNP) son las secuencias de direcciones numéricas que ONTAP asigna a unidades de cinta y bibliotecas de cintas basadas en el adaptador o switch SCSI-2/3 (ubicación específica) que están conectados al sistema de almacenamiento. Los PPNS también se conocen como nombres eléctricos.

Los PPNS de los dispositivos de conexión directa utilizan el siguiente formato `host_adapter`: . `device_id_lun`

[NOTE]
====
El valor de LUN se muestra solo para dispositivos de cambio de cinta y medio cuyos valores de LUN no son cero; es decir, si el valor de LUN es cero, `lun` no se muestra la parte de PPN.

====
Por ejemplo, PPN 8.6 indica que el número de adaptador de host es 8, el ID de dispositivo es 6 y el número de unidad lógica (LUN) es 0.

Los dispositivos de cinta SAS también son dispositivos de conexión directa. Por ejemplo, el PPN 5c.4 indica que en un sistema de almacenamiento, el SAS HBA está conectado en la ranura 5, la cinta SAS está conectada al puerto C del SAS HBA y el identificador de dispositivo es 4.

Los PPNS de los dispositivos conectados por switch Fibre Channel utilizan el siguiente formato `switch:port_id`: . `device_id_lun`

Por ejemplo, el PPN MY_SWITCH:5.3L2 indica que la unidad de cinta conectada al puerto 5 de un switch llamado MY_SWITCH está establecida con el ID de dispositivo 3 y tiene el LUN 2.

La unidad determina el LUN (número de unidad lógica). Fibre Channel, bibliotecas y unidades de cinta SCSI, así como discos, tienen VPN.

Los PPNS de unidades de cinta y bibliotecas no cambian a menos que cambie el nombre del conmutador, se mueva la unidad de cinta o la biblioteca o se reconfigure la unidad de cinta o la biblioteca. Los PPNS permanecen sin cambios después del reinicio. Por ejemplo, si se retira una unidad de cinta denominada MY_SWITCH:5.3L2 y SE conecta una nueva unidad de cinta con el mismo ID de dispositivo y LUN al puerto 5 del conmutador MY_SWITCH, se podrá acceder a la nueva unidad de cinta mediante MY_SWITCH:5.3L2.
