---
permalink: tape-backup/qualify-new-drive-dynamically-concept.html 
sidebar: sidebar 
keywords: storage, system, qualifies, new, tape, drive, dynamically 
summary: El sistema de almacenamiento califica una unidad de cinta de forma dinámica emparejando su ID de proveedor y su ID de producto con la información contenida en la tabla de calificación de cinta. 
---
= Cómo el sistema de almacenamiento ONTAP califica dinámicamente una unidad de cinta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El sistema de almacenamiento califica una unidad de cinta de forma dinámica emparejando su ID de proveedor y su ID de producto con la información contenida en la tabla de calificación de cinta.

Cuando conecta una unidad de cinta al sistema de almacenamiento, busca una identificación del proveedor y una coincidencia de ID de producto entre la información obtenida durante la detección de cinta y la información de la tabla de calificación de cinta interna. Si el sistema de almacenamiento detecta una coincidencia, Marca la unidad de cinta como cualificada y puede acceder a la unidad de cinta. Si el sistema de almacenamiento no encuentra una coincidencia, la unidad de cinta permanece en estado no cualificado y no se accede a ella.
