---
permalink: tape-backup/remove-tape-aliases-task.html 
sidebar: sidebar 
keywords: remove, tape, aliases, clear, command, drive, medium, changer 
summary: Puede eliminar alias utilizando el comando clear de alias de cinta de almacenamiento cuando ya no se necesiten alias persistentes para una unidad de cinta o un cambiador de medios. 
---
= Elimine los alias de cinta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede eliminar alias utilizando `storage tape alias clear` comando cuando ya no se necesitan alias persistentes para una unidad de cinta o un cambiador de medios.

.Pasos
. Retire un alias de una unidad de cinta o de un cambiador de medios mediante el `storage tape alias clear` comando.
+
Para obtener más información acerca de este comando, consulte las páginas man.

+
El siguiente comando elimina los alias de todas las unidades de cinta especificando el ámbito de la operación de alias Clear `tape`:

+
[listing]
----
cluster-01::>storage tape alias clear -node cluster-01 -clear-scope tape
----


.Después de terminar
Si va a realizar una operación de backup o restauración de cinta mediante NDMP, después de eliminar un alias de una unidad de cinta o un cambiador de medios, debe asignar un nuevo nombre de alias a la unidad de cinta o al cambiador de medios para continuar accediendo al dispositivo de cinta.

.Información relacionada
xref:assign-tape-aliases-concept.adoc[Qué es el solapamiento de cinta]

xref:assign-tape-aliases-task.adoc[Asignación de alias de cinta]
