---
permalink: tape-backup/scalability-limits-smtape-sessions-reference.html 
sidebar: sidebar 
keywords: scalability, limits, smtap, backup, restore, session, ndmp, cli, tape, seeding, system, memory 
summary: 'Al ejecutar operaciones de backup y restauración de SMTape mediante NDMP o interfaz de línea de comandos (propagación de cintas), debe tener en cuenta la cantidad máxima de sesiones de backup y restauración de SMTape que pueden realizarse de manera simultánea en sistemas de almacenamiento con diferentes capacidades de memoria del sistema. Este número máximo depende de la memoria del sistema de un sistema de almacenamiento.' 
---
= Límites de escalabilidad para las sesiones de backup y restauración de SMTape
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al ejecutar operaciones de backup y restauración de SMTape mediante NDMP o interfaz de línea de comandos (propagación de cintas), debe tener en cuenta la cantidad máxima de sesiones de backup y restauración de SMTape que pueden realizarse de manera simultánea en sistemas de almacenamiento con diferentes capacidades de memoria del sistema. Este número máximo depende de la memoria del sistema de un sistema de almacenamiento.

[NOTE]
====
Los límites de escalabilidad de las sesiones de backup y restauración de SMTape son diferentes de los límites de sesiones de NDMP y los límites de sesiones de volcado.

====
|===
| Memoria del sistema de almacenamiento | Cantidad total de sesiones de backup y restauración de SMTape 


 a| 
Menos de 16 GB
 a| 
6



 a| 
Mayor o igual que 16 GB pero menor que 24 GB
 a| 
16



 a| 
Mayor o igual que 24 GB
 a| 
32

|===
Puede obtener la memoria del sistema del sistema de almacenamiento mediante el `sysconfig -a` comando (disponible a través del nodeshell). Para obtener más información acerca de cómo utilizar este comando, consulte las páginas man.

.Información relacionada
xref:scalability-limits-ndmp-sessions-reference.adoc[Límites de escalabilidad para sesiones NDMP]

xref:scalability-limits-dump-backup-restore-sessions-concept.adoc[Límites de escalabilidad para sesiones de backup y restauración de volcado]
