---
permalink: tape-backup/scalability-limits-dump-backup-restore-sessions-concept.html 
sidebar: sidebar 
keywords: scalability, limites, dump, backup, restore, sessions, maximum, memory, capacities, storage, system 
summary: Es necesario conocer la cantidad máxima de sesiones de backup y restauración de volcado que se pueden ejecutar simultáneamente en sistemas de almacenamiento de diferentes capacidades de memoria del sistema. Este número máximo depende de la memoria del sistema de un sistema de almacenamiento. 
---
= Límites de escalabilidad para sesiones de copia de seguridad y restauración de volcado de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es necesario conocer la cantidad máxima de sesiones de backup y restauración de volcado que se pueden ejecutar simultáneamente en sistemas de almacenamiento de diferentes capacidades de memoria del sistema. Este número máximo depende de la memoria del sistema de un sistema de almacenamiento.

Los límites mencionados en la tabla siguiente son para el motor de descarga o restauración. Los límites mencionados en los límites de escalabilidad para las sesiones NDMP son para el servidor NDMP, que son más altos que los límites del motor.

|===
| Memoria del sistema de un sistema de almacenamiento | Cantidad total de sesiones de backup y restauración de volcado 


 a| 
Menos de 16 GB
 a| 
4



 a| 
Mayor o igual que 16 GB pero menor que 24 GB
 a| 
16



 a| 
Mayor o igual que 24 GB
 a| 
32

|===
[NOTE]
====
Si se utiliza `ndmpcopy` el comando para copiar datos dentro de los sistemas de almacenamiento, se establecen dos sesiones NDMP: Una para el backup de volcado y otra para la restauración de volcado.

====
Puede obtener la memoria del sistema de su sistema de almacenamiento mediante `sysconfig -a` el comando (disponible en el infierno de nodo). Obtenga más información sobre `sysconfig -a` en el link:https://docs.netapp.com/us-en/ontap-cli/system-node-run.html["Referencia de comandos del ONTAP"^].

.Información relacionada
xref:scalability-limits-ndmp-sessions-reference.adoc[Límites de escalabilidad para sesiones NDMP]
