---
permalink: tape-backup/smtape-volume-move-concept.html 
sidebar: sidebar 
keywords: smtape, backup, operation, volume, move, cutover, phase 
summary: Las operaciones de backup de SMTape y las operaciones de movimiento de volúmenes se pueden ejecutar en paralelo hasta que el sistema de almacenamiento intente la fase final de la transición. Una vez pasada esta fase, no se pueden ejecutar nuevas operaciones de backup de SMTape en el volumen que se va a mover. No obstante, las operaciones actuales siguen en ejecución hasta que se complete. 
---
= Funcionamiento de SMTape con el movimiento de volúmenes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las operaciones de backup de SMTape y las operaciones de movimiento de volúmenes se pueden ejecutar en paralelo hasta que el sistema de almacenamiento intente la fase final de la transición. Una vez pasada esta fase, no se pueden ejecutar nuevas operaciones de backup de SMTape en el volumen que se va a mover. No obstante, las operaciones actuales siguen en ejecución hasta que se complete.

Antes de iniciar la fase de transición de un volumen, la operación de movimiento de volúmenes comprueba las operaciones de backup de SMTape activas en el mismo volumen. Si hay operaciones de backup de SMTape activas, la operación de movimiento de volúmenes pasa al estado de transposición diferida y permite que se completen las operaciones de backup de SMTape. Una vez completadas estas operaciones de backup, debe reiniciar manualmente la operación de movimiento de volúmenes.

Si la aplicación de backup admite la extensión CAB, puede seguir realizando operaciones incrementales de backup y restauración de cinta en volúmenes de lectura/escritura y solo lectura sin tener que reconfigurar las políticas de backup.

No se pueden ejecutar las operaciones de restauración básica y movimiento de volúmenes de forma simultánea; sin embargo, la restauración incremental puede ejecutarse en paralelo con las operaciones de movimiento de volúmenes, con un comportamiento similar al de las operaciones de backup de SMTape durante las operaciones de movimiento de volúmenes.
