---
permalink: tape-backup/snapshot-copies-during-smtape-backup-concept.html 
sidebar: sidebar 
keywords: snapshot, copy, smtape, backup, baseline, incremental, snapmirror 
summary: Debe comprender cómo se usan las snapshots durante un backup de referencia de SMTape y un backup incremental. También hay que tener en cuenta al realizar un backup con SMTape. 
---
= Utilizar snapshots durante la copia de seguridad de SMTape
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe comprender cómo se usan las snapshots durante un backup de referencia de SMTape y un backup incremental. También hay que tener en cuenta al realizar un backup con SMTape.



== Backup de línea de base

Al realizar un backup de línea base, es posible especificar el nombre de la snapshot que se copiará en cinta. Si no se especifica ninguna instantánea, según el tipo de acceso del volumen (lectura/escritura o solo lectura), se crea automáticamente una instantánea o se utilizan instantáneas existentes. Cuando se especifica una instantánea para la copia de seguridad, también se realiza una copia de seguridad de todas las instantáneas anteriores a la instantánea especificada en cinta.

Si no se especifica una snapshot para el backup, se producirá lo siguiente:

* Para un volumen de lectura/escritura, se crea automáticamente una copia Snapshot.
+
La copia Snapshot recién creada y todas las instantáneas más antiguas se realizan backups en cinta.

* Para un volumen de solo lectura, se realizan backups en cinta de todas las copias Snapshot, incluida la última.
+
No se realiza un backup de las copias de Snapshot nuevas que se creen después de iniciar el backup.





== Backup incremental

Para las operaciones de backup diferenciales o incrementales de SMTape, las aplicaciones de backup compatibles con NDMP crean y gestionan las copias snapshot.

Siempre debe especificar una snapshot mientras realiza una operación de backup incremental. Para que la operación de backup incremental se realice correctamente, la snapshot de backup realizada durante la operación de backup anterior (base de referencia o incremental) debe estar en el volumen desde el que se realiza el backup. Para asegurarse de utilizar esta instantánea con backup, debe tener en cuenta la política de Snapshot asignada en este volumen al configurar la política de backup.



== Consideraciones sobre backups de SMTape en destinos de SnapMirror

* Una relación de mirroring de protección de datos crea snapshots temporales en el volumen de destino para la replicación.
+
No se deben usar estas snapshots para la copia de seguridad de SMTape.

* Si se produce una actualización de SnapMirror en un volumen de destino en una relación de reflejo de protección de datos durante una operación de backup de SMTape en el mismo volumen, no debe eliminarse en el volumen de origen la copia de Snapshot del backup de SMTape.
+
Durante la operación de backup, SMTape bloquea la snapshot en el volumen de destino y, si se elimina la snapshot correspondiente en el volumen de origen, se producirá un error en la operación de actualización de SnapMirror subsiguiente.

* No se deben usar estas snapshots durante un backup incremental.

