---
permalink: tape-backup/supported-number-simultaneous-tape-devices-concept.html 
sidebar: sidebar 
keywords: supported, number, simultaneoud, tape, devices, fibre, channel, scsi, sas, attachments, router, devices 
summary: 'ONTAP admite un máximo de 64 conexiones simultáneas de unidad de cinta, 16 cambiadores de soporte y 16 dispositivos de puente o router para cada sistema de almacenamiento (por nodo) en cualquier combinación de conexiones Fibre Channel, SCSI o SAS.' 
---
= Compatible con el número de dispositivos de cinta simultáneos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP admite un máximo de 64 conexiones simultáneas de unidad de cinta, 16 cambiadores de soporte y 16 dispositivos de puente o router para cada sistema de almacenamiento (por nodo) en cualquier combinación de conexiones Fibre Channel, SCSI o SAS.

Las unidades de cinta o los cambiadores de medios pueden ser dispositivos en bibliotecas de cintas físicas o virtuales o dispositivos independientes.

[NOTE]
====
Aunque un sistema de almacenamiento puede detectar 64 conexiones a unidades de cinta, la cantidad máxima de sesiones de backup y restauración que pueden realizarse de forma simultánea depende de los límites de escalabilidad del motor de backup.

====
.Información relacionada
xref:scalability-limits-dump-backup-restore-sessions-concept.adoc[Límites de escalabilidad para sesiones de backup y restauración de volcado]
