---
permalink: tape-backup/tape-seeding-concept.html 
sidebar: sidebar 
keywords: tape, seeding, smtape, functionality, destination, flexvol, data, protection, mirror 
summary: La propagación de cintas es una funcionalidad SMTape que ayuda a inicializar un volumen de FlexVol de destino en una relación de mirroring de protección de datos. 
---
= Qué es la siembra de cintas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La propagación de cintas es una funcionalidad SMTape que ayuda a inicializar un volumen de FlexVol de destino en una relación de mirroring de protección de datos.

La propagación de cintas permite establecer una relación de mirroring para la protección de datos entre un sistema de origen y un sistema de destino a través de una conexión de ancho de banda bajo.

El mirroring incremental de las copias Snapshot del origen al destino es factible gracias a una conexión de ancho de banda bajo. Sin embargo, un mirroring inicial de la copia Snapshot base demora mucho tiempo en una conexión de ancho de banda bajo. En estos casos, se puede realizar un backup de SMTape del volumen de origen a una cinta y usar la cinta para transferir la copia Snapshot básica inicial al destino. A continuación, puede configurar las actualizaciones incrementales de SnapMirror en el sistema de destino mediante la conexión con un ancho de banda bajo.

.Información relacionada
link:../concepts/index.html["Conceptos de ONTAP"]
