---
permalink: tape-backup/transfer-data-ndmpcopy-task.html 
sidebar: sidebar 
keywords: transfer, data, ndmpcopy, incremental, full, qtree, directory, files, v4, ndmp 
summary: El comando ndmpcopy transfiere los datos entre los sistemas de almacenamiento compatibles con NDMP v4. Puede realizar transferencias de datos completas e incrementales. Puede transferir volúmenes completos o parciales, qtrees, directorios o archivos individuales. 
---
= Transfiera los datos utilizando la descripción general de ndmpcopy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `ndmpcopy` Nodesinfierno Command transfiere datos entre sistemas de almacenamiento que admiten NDMP v4. Puede realizar transferencias de datos completas e incrementales. Puede transferir volúmenes completos o parciales, qtrees, directorios o archivos individuales.

.Acerca de esta tarea
Gracias al uso de ONTAP 8.x y versiones anteriores, las transferencias incrementales están limitadas a un máximo de dos niveles (uno completo y hasta dos backups incrementales).

A partir de ONTAP 9.0 y versiones posteriores, las transferencias incrementales están limitadas a un máximo de nueve niveles (uno completo y hasta nueve backups incrementales).

Puede ejecutar `ndmpcopy` en la línea de comandos nodesinfierno de los sistemas de almacenamiento de origen y destino, o un sistema de almacenamiento que no es el origen ni el destino de la transferencia de datos. También puede ejecutar `ndmpcopy` en un único sistema de almacenamiento que sea el origen y el destino de la transferencia de datos.

Las direcciones IPv4 o IPv6 de los sistemas de almacenamiento de origen y destino en el `ndmpcopy` comando. El formato de ruta es `/vserver_name/volume_name \[path\]`.

.Pasos
. Active el servicio NDMP en los sistemas de almacenamiento de origen y destino:
+
|===


| Si realiza transferencia de datos en el origen o el destino en... | Usar el siguiente comando... 


 a| 
Modo de NDMP con ámbito SVM
 a| 
`vserver services ndmp on`

[NOTE]
====
Para la autenticación NDMP en la SVM de administrador, la cuenta de usuario es `admin` y el rol de usuario es `admin` o. `backup`. En la SVM de datos, la cuenta de usuario es `vsadmin` y el rol de usuario es `vsadmin` o. `vsadmin-backup` función.

====


 a| 
Modo de NDMP con ámbito del nodo
 a| 
`system services ndmp on`

|===
. Transferir datos dentro de un sistema de almacenamiento o entre sistemas de almacenamiento mediante el `ndmpcopy` mando en el nodesinfierno:
+
`*::> system node run -node <node_name> < ndmpcopy [options] source_IP:source_path destination_IP:destination_path [-mcs {inet|inet6}] [-mcd {inet|inet6}] [-md {inet|inet6}]*`

+
[NOTE]
====
Los nombres DNS no son compatibles con ndmpcopy. Debe proporcionar la dirección IP del origen y del destino. La dirección de bucle invertido (127.0.0.1) no es compatible con la dirección IP de origen ni con la dirección IP de destino.

====
+
** La `ndmpcopy` command determina el modo de dirección para las conexiones de control de la siguiente manera:
+
*** El modo de dirección para la conexión de control corresponde a la dirección IP proporcionada.
*** Puede anular estas reglas mediante el `-mcs` y.. `-mcd` opciones.


** Si el origen o el destino son el sistema ONTAP, entonces según el modo NDMP (ámbito del nodo o ámbito de la SVM), utilice una dirección IP que permita el acceso al volumen de destino.
** `source_path` y.. `destination_path` son los nombres de ruta absolutos hasta el nivel granular de volumen, qtree, directorio o archivo.
** `-mcs` especifica el modo de direccionamiento preferido para la conexión de control al sistema de almacenamiento de origen.
+
`inet` Indica un modo de dirección IPv4 y. `inet6` Indica un modo de dirección IPv6.

** `-mcd` especifica el modo de direccionamiento preferido para la conexión de control al sistema de almacenamiento de destino.
+
`inet` Indica un modo de dirección IPv4 y. `inet6` Indica un modo de dirección IPv6.

** `-md` especifica el modo de direccionamiento preferido para transferencias de datos entre los sistemas de almacenamiento de origen y destino.
+
`inet` Indica un modo de dirección IPv4 y. `inet6` Indica un modo de dirección IPv6.

+
Si no utiliza la `-md` en la `ndmpcopy` comando, el modo de direccionamiento de la conexión de datos se determina de la siguiente manera:

+
*** Si alguna de las direcciones especificadas para las conexiones de control es una dirección IPv6, el modo de dirección para la conexión de datos es IPv6.
*** Si las dos direcciones especificadas para las conexiones de control son direcciones IPv4, el `ndmpcopy` En primer lugar, Command intenta utilizar un modo de dirección IPv6 para la conexión de datos.
+
Si no es así, el comando utiliza un modo de dirección IPv4.

+
[NOTE]
====
Una dirección IPv6, si se especifica, debe escribirse entre corchetes.

====
+
Este comando de ejemplo migra datos de una ruta de acceso de origen (`source_path`) a una ruta de destino (`destination_path`).

+
[listing]
----
> ndmpcopy -sa admin:<ndmp_password> -da admin:<ndmp_password>
 -st md5 -dt md5 192.0.2.129:/<src_svm>/<src_vol> 192.0.2.131:/<dst_svm>/<dst_vol>
----
+
Este comando de ejemplo establece explícitamente las conexiones de control y la conexión de datos para utilizar el modo de dirección IPv6:

+
[listing]
----
> ndmpcopy -sa admin:<ndmp_password> -da admin:<ndmp_password> -st md5 -dt md5 -mcs inet6 -mcd inet6 -md
 inet6 [2001:0db8:1:1:209:6bff:feae:6d67]:/<src_svm>/<src_vol> [2001:0ec9:1:1:200:7cgg:gfdf:7e78]:/<dst_svm>/<dst_vol>
----





