---
permalink: tape-backup/user-authentication-svm-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: user, authentication, svm, ndmp, node, vsadmin, backup, role, storage, virutal, machine, user 
summary: 'En el modo NDMP de la máquina virtual de almacenamiento (SVM), la autenticación de usuario NDMP está integrada con el control de acceso basado en roles. En el contexto de la SVM, el usuario NDMP debe tener el rol "vsadmin" o "vsadmin-backup". En un contexto de clúster, el usuario NDMP debe tener el rol “admin” o “backup”.' 
---
= Autenticación de usuarios de ONTAP en el modo NDMP con ámbito SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En el modo NDMP de la máquina virtual de almacenamiento (SVM), la autenticación de usuario NDMP está integrada con el control de acceso basado en roles. En el contexto de la SVM, el usuario NDMP debe tener el rol "'vsadmin'" o "'vsadmin-backup'". En un contexto de cluster, el usuario NDMP debe tener el rol «'admin'» o «'backup'».

Además de estas funciones predefinidas, una cuenta de usuario asociada a una función personalizada también puede utilizarse para la autenticación NDMP siempre y cuando la función personalizada tenga la carpeta «'vserver Services ndmp'» en su directorio de comandos y el nivel de acceso de la carpeta no sea «'none'». En este modo, debe generar una contraseña NDMP para una cuenta de usuario determinada, que se crea mediante el control de acceso basado en roles. Los usuarios de clúster con un rol de administrador o backup pueden acceder a una LIF de gestión de nodos, una LIF de gestión de clústeres o una LIF de interconexión de clústeres. Los usuarios de un rol de vsadmin o de vsadmin pueden acceder solo a la LIF de datos para esa SVM. Por lo tanto, según la función de un usuario, la disponibilidad de volúmenes y dispositivos de cinta para las operaciones de backup y restauración varía.

Este modo también admite la autenticación de usuario para usuarios NIS y LDAP. Por lo tanto, los usuarios NIS y LDAP pueden acceder a varias SVM con un ID de usuario y una contraseña comunes. Sin embargo, la autenticación NDMP no admite usuarios de Active Directory.

En este modo, una cuenta de usuario debe estar asociada a la aplicación SSH y al método de autenticación «'Contraseña de usuario'».

.Información relacionada
xref:commands-manage-svm-scoped-ndmp-reference.adoc[Comandos para gestionar el modo NDMP con ámbito de la SVM]

link:../system-admin/index.html["Administración del sistema"]
