---
permalink: software_setup/convert-ipv4-to-ipv6-task.html 
sidebar: sidebar 
keywords: software, setup, ontap, covert, converting, ipv4, ipv6 
summary: A partir de ONTAP 9.13.1, puede asignar direcciones IPv6 para las LIF de gestión en plataformas A800 y FAS8700.  Para versiones de ONTAP anteriores a 9.13.1, para versión 9.13.1 y versiones posteriores en otras plataformas, debe asignar direcciones IPv4 para las LIF de gestión y después convertir direcciones IPv6 tras completar la configuración del clúster. 
---
= Convierta las LIF de gestión de IPv4 a IPv6
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.13.1, se pueden asignar direcciones IPv6 a las LIF de administración en plataformas A800 y FAS8700 durante la configuración inicial del clúster.  Para versiones de ONTAP anteriores a 9.13.1, o para 9.13.1 o versiones posteriores en otras plataformas, primero debe asignar direcciones IPv4 a las LIF de gestión y, a continuación, convertir en direcciones IPv6 una vez completada la configuración del clúster.

.Pasos
. Habilite IPv6 para el clúster:
+
[source, cli]
----
network options ipv6 modify -enable true
----
. Establecer privilegio en avanzado:
+
[source, cli]
----
set priv advanced
----
. Vea la lista de prefijos de RA aprendidos en varias interfaces:
+
[source, cli]
----
network ndp prefix show
----
. Cree una LIF de gestión IPv6:
+
Utilice el formato `prefix::id` En el parámetro address para construir la dirección IPv6 manualmente.

+
[source, cli]
----
network interface create -vserver <svm_name> -lif <LIF> -home-node <home_node> -home-port <home_port> -address <IPv6prefix::id> -netmask-length <netmask_length> -failover-policy <policy> -service-policy <service_policy> -auto-revert true
----
. Compruebe que la LIF se ha creado:
+
[source, cli]
----
network interface show
----
. Compruebe que se pueda acceder a la dirección IP configurada:
+
[source, cli]
----
network ping6
----
. Marcar el LIF IPv4 como inactivo de forma administrativa:
+
[source, cli]
----
network interface modify -vserver <svm_name> -lif <lif_name> -status-admin down
----
. Elimine la LIF de gestión de IPv4:
+
[source, cli]
----
network interface delete -vserver <svm_name> -lif <lif_name>
----
. Confirmar que se ha eliminado el LIF de gestión de IPv4:
+
[source, cli]
----
network interface show
----

