---
permalink: software_setup/task_configure_important_ems_events_to_forward_notifications_to_a_syslog_server.html 
sidebar: sidebar 
keywords: ontap, software, setup, configure, important,ems, events, forward, notifications, syslog, server 
summary: Para registrar las notificaciones de los eventos más graves en un servidor de syslog, debe configurar EMS para reenviar las notificaciones de los eventos que representan actividades importantes. 
---
= Configure eventos de EMS importantes para reenviar notificaciones a un servidor de syslog
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para registrar las notificaciones de los eventos más graves en un servidor de syslog, debe configurar EMS para reenviar las notificaciones de los eventos que representan actividades importantes.

El DNS debe haberse configurado en el clúster para resolver el nombre del servidor de syslog.

Si el entorno no contiene un servidor de syslog para las notificaciones de eventos, primero debe crear uno. Si el entorno ya contiene un servidor de syslog para registrar eventos de otros sistemas, se recomienda usarlo para las notificaciones de eventos importantes.

Puede realizar esta tarea en cualquier momento que el clúster esté en ejecución. Para ello, introduzca los comandos en la línea de comandos de ONTAP.

. Cree un destino de servidor de syslog para los eventos importantes:
+
`event notification destination create -name syslog-ems -syslog syslog-server-address`

. Configure los eventos importantes de manera que reenvíen notificaciones al servidor de syslog:
+
`event notification create -filter-name important-events -destinations syslog-ems`


