---
permalink: software_setup/task_check_cluster_with_config_advisor.html 
sidebar: sidebar 
keywords: ontap, software, setup, check, cluster, active iq, config, advisor 
summary: Después de haber Unido todos los nodos al nuevo clúster, debe ejecutar Active IQ Config Advisor para validar su configuración y comprobar si hay errores de configuración comunes. 
---
= Compruebe su clúster con Active IQ Config Advisor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de haber Unido todos los nodos al nuevo clúster, debe ejecutar Active IQ Config Advisor para validar su configuración y comprobar si hay errores de configuración comunes.

Config Advisor es una aplicación basada en web que instala en su portátil, máquina virtual o servidor, y funciona en plataformas Windows, Linux y Mac.

Config Advisor ejecuta una serie de comandos para validar la instalación y comprobar el estado general de la configuración, incluido el clúster y los switches de almacenamiento.

. Descargue e instale Active IQ Config Advisor.
+
link:https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]

. Inicie Active IQ y configure una frase de contraseña cuando se le solicite.
. Revise su configuración y haga clic en *Guardar*.
. En la página *objetivos*, haga clic en *validación posterior a la implementación de ONTAP*.
. Seleccione el modo guiado o experto.
+
Si elige el modo guiado, los conmutadores conectados se detectan automáticamente.

. Introduzca las credenciales del clúster.
. (Opcional) haga clic en *validación de formulario*.
. Para comenzar a recopilar datos, haga clic en *Guardar y evaluar*.
. Después de completar la recopilación de datos, en *Monitor de trabajo > acciones*, vea los datos recopilados haciendo clic en el icono *Vista de datos* y vea los resultados haciendo clic en el icono *resultados*.
. Resuelva los problemas identificados por Config Advisor.

