---
permalink: software_setup/task_join_remaining_nodes_to_the_cluster.html 
sidebar: sidebar 
keywords: ontap, software, setup, join, remaining, nodes, cluster, HA, high availability, autosupport 
summary: Después de crear un nuevo clúster, debe usar el Asistente de configuración de clúster para unir los nodos restantes al clúster de uno en uno. El asistente le ayuda a configurar la interfaz de gestión de nodos de cada nodo. 
---
= Una los nodos restantes al clúster en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de crear un nuevo clúster, debe usar el Asistente de configuración de clúster para unir los nodos restantes al clúster de uno en uno. El asistente le permite configurar la interfaz de gestión de nodos de cada nodo.


NOTE: Este procedimiento se aplica a los sistemas FAS, AFF y ASA actuales. Si tiene un sistema ASA R2 (ASA A1K, ASA A70 o ASA A90), siga link:https://docs.netapp.com/us-en/asa-r2/install-setup/initialize-ontap-cluster.html["estos pasos"^]Use System Manager para configurar un clúster de ONTAP. Los sistemas R2 de ASA ofrecen una experiencia de ONTAP simplificada específica para clientes de SAN.

Cuando se unen dos nodos en un clúster, se crea un par de alta disponibilidad (ha). Si se une a 4 nodos, se crean dos pares de alta disponibilidad. Para obtener más información acerca de alta disponibilidad, consulte link:../high-availability/index.html["Obtenga más información sobre ha"].

Solo puede unir un nodo a la vez al clúster. Tras comenzar a unir un nodo al clúster, debe completar la operación de unión de ese nodo y el nodo debe formar parte del clúster antes de poder unir el siguiente nodo.

*Mejor práctica:* Si tiene un sistema FAS2720 con 24 o menos unidades NL-SAS, debe verificar que el valor predeterminado de la configuración de almacenamiento es activo/pasivo para optimizar el rendimiento. Para obtener más información, consulte la documentación de link:../disks-aggregates/setup-active-passive-config-root-data-task.html["configuración activo-pasivo en nodos mediante la creación de particiones de datos raíz"].

. Inicie sesión en el nodo que planea unir en el clúster.
+
El asistente de configuración de clúster se inicia en la consola.

+
[listing]
----
Welcome to the cluster setup wizard....
----
. Reconozca la declaración de AutoSupport.
+

NOTE: AutoSupport está habilitado de forma predeterminada.

+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
. Siga las instrucciones que aparecen en pantalla para asignar una dirección IP al nodo.
+
A partir de ONTAP 9.13.1, puede asignar direcciones IPv6 para las LIF de gestión en plataformas A800 y FAS8700. Para versiones de ONTAP anteriores a 9.13.1, o para 9.13.1 o versiones posteriores en otras plataformas, debe asignar direcciones IPv4 para las LIF de gestión y, después, convertirlas a IPv6 tras completar la configuración del clúster.

. Pulse *Intro* para continuar.
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
----
. Una el nodo al clúster: `join`
. Siga las instrucciones que aparecen en pantalla para configurar el nodo y unirlo al clúster.
. Tras completar la configuración, compruebe que el nodo esté en buen estado y que pueda participar en el clúster: `cluster show`
+
En el siguiente ejemplo se muestra un clúster después de unirle el segundo nodo (cluster1-02):

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
cluster1-01           true    true
cluster1-02           true    true
----
+
Puede acceder al Asistente de configuración de clúster para cambiar cualquiera de los valores introducidos para la SVM de administrador o la SVM de nodo mediante el comando cluster setup.

. Repita esta acción para cada uno de los nodos restantes.


.Después de terminar
Si es necesario, link:convert-ipv4-to-ipv6-task.html["Convertir de IPv4 a IPv6"].
