---
permalink: software_setup/task_create_the_cluster_on_the_first_node.html 
sidebar: sidebar 
keywords: ontap, software, setup, create, cluster, first, node, autosupport, CLI 
summary: 'Utilice el Asistente de configuración de clúster para crear el clúster en el primer nodo. El asistente le permite configurar la red del clústeres que conecta los nodos, crear la máquina virtual de almacenamiento (SVM) de administrador de clústeres, añadir las claves de licencia de funciones y crear la interfaz de gestión de nodos para el primer nodo.' 
---
= Cree el clúster en el primer nodo en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilice el Asistente de configuración de clúster para crear el clúster en el primer nodo. El asistente le permite configurar la red del clústeres que conecta los nodos, crear la máquina virtual de almacenamiento (SVM) de administrador de clústeres, añadir las claves de licencia de funciones y crear la interfaz de gestión de nodos para el primer nodo.


NOTE: Este procedimiento se aplica a los sistemas FAS, AFF y ASA actuales. Si tiene un sistema ASA R2 (ASA A1K, ASA A70 o ASA A90), siga link:https://docs.netapp.com/us-en/asa-r2/install-setup/initialize-ontap-cluster.html["estos pasos"^]Use System Manager para configurar un clúster de ONTAP. Los sistemas R2 de ASA ofrecen una experiencia de ONTAP simplificada específica para clientes de SAN.

.Antes de empezar
* Debe haber instalado, cableado y encendido el nuevo sistema de almacenamiento de acuerdo con las instrucciones de instalación y configuración de su modelo de plataforma.
Consulte https://docs.netapp.com/us-en/ontap-systems/index.html["Documentación de AFF y FAS"^].
* Las interfaces de red de clúster se deben configurar en cada nodo del clúster para la comunicación dentro del clúster.
* Si va a configurar IPv6 en su clúster, IPv6 debe configurarse en la controladora de gestión base (BMC) para poder acceder al sistema mediante SSH.


.Pasos
. Encienda todos los nodos que va a añadir al clúster. Esto es necesario para habilitar la detección para la configuración del clúster.
. Conéctese a la consola del primer nodo.
+
El nodo arranca y, a continuación, se inicia el Asistente de configuración de clúster en la consola.

+
[listing]
----
Welcome to the cluster setup wizard....
----
. Reconozca la declaración de AutoSupport.
+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
+

NOTE: AutoSupport está habilitado de forma predeterminada.

. Siga las instrucciones que aparecen en pantalla para asignar una dirección IP al nodo.
+
A partir de ONTAP 9.13.1, puede asignar direcciones IPv6 para las LIF de gestión en plataformas A800 y FAS8700. Para versiones de ONTAP anteriores a 9.13.1, o para 9.13.1 o versiones posteriores en otras plataformas, debe asignar direcciones IPv4 para las LIF de gestión y, después, convertirlas a IPv6 tras completar la configuración del clúster.

. Pulse *Intro* para continuar.
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
----
. Cree un nuevo clúster: `create`
. Acepte los valores predeterminados del sistema o introduzca sus propios valores.
. Una vez completada la configuración, inicie sesión en el clúster y compruebe que el clúster esté activo y que el primer nodo esté en buen estado. Para ello, introduzca el comando de la CLI de ONTAP: `cluster show`
+
El siguiente ejemplo muestra un clúster en el que el primer nodo (cluster1-01) está en buen estado y puede participar:

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
cluster1-01           true    true
----
+
Puede acceder al Asistente de configuración de clúster para cambiar cualquiera de los valores introducidos para la SVM de administrador o la SVM de nodo mediante el `cluster setup` comando.



.Después de terminar
Si es necesario, link:convert-ipv4-to-ipv6-task.html["Convertir de IPv4 a IPv6"].
