---
permalink: software_setup/task_create_the_cluster_on_the_first_node.html 
sidebar: sidebar 
keywords: ontap, software, setup, create, cluster, first, node, autosupport, CLI 
summary: 'Utilice el Asistente de configuración de clúster para crear el clúster en el primer nodo. El asistente le permite configurar la red del clústeres que conecta los nodos \(si el clúster consta de dos o más nodos\), crear la máquina virtual de almacenamiento \(SVM\) de administrador de clústeres, añadir las claves de licencia de funciones y crear la interfaz de gestión de nodos para el primer nodo.' 
---
= Cree el clúster en el primer nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilice el Asistente de configuración de clúster para crear el clúster en el primer nodo. El asistente le permite configurar la red del clústeres que conecta los nodos, crear la máquina virtual de almacenamiento (SVM) de administrador de clústeres, añadir las claves de licencia de funciones y crear la interfaz de gestión de nodos para el primer nodo.

. Encienda todos los nodos que va a añadir al clúster. Esto es necesario para habilitar la detección para la configuración del clúster.
. Conéctese a la consola del primer nodo.
+
El nodo arranca y, a continuación, se inicia el Asistente de configuración de clúster en la consola.

+
[listing]
----
Welcome to the cluster setup wizard....
----
. Reconozca la declaración de AutoSupport.
+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
+

NOTE: AutoSupport está habilitado de forma predeterminada.

. Siga las instrucciones que aparecen en pantalla para asignar una dirección IP al nodo.
. Si está utilizando el asistente de la GUI para realizar la configuración, siga las instrucciones para completar el proceso en su navegador web. Si está utilizando el asistente de la CLI para realizar la configuración, presione Entrar para continuar.
+
[listing]
----
Use your web browser to complete cluster setup by accessing
https://10.63.11.29

Otherwise, press Enter to complete cluster setup using the
command line interface:

Do you want to create a new cluster or join an existing cluster? {create, join}:
----
. Cree un nuevo clúster: `create`
. Acepte los valores predeterminados del sistema o introduzca sus propios valores.
. Una vez completada la configuración, inicie sesión en el clúster y compruebe que el clúster esté activo y que el primer nodo esté en buen estado. Para ello, introduzca el comando de la CLI de ONTAP: `cluster show`
+
El siguiente ejemplo muestra un clúster en el que el primer nodo (cluster1-01) está en buen estado y puede participar:

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
cluster1-01           true    true
----
+
Puede acceder al Asistente de configuración de clúster para cambiar cualquiera de los valores introducidos para la SVM de administrador o la SVM de nodo mediante el `cluster setup` comando.


