---
permalink: software_setup/task_decide_where_to_send_important_event_notifications.html 
sidebar: sidebar 
keywords: ontap, software, setup, decide, where, send, important, event, notifications 
summary: Antes de configurar las notificaciones de eventos de EMS importantes, debe decidir si desea enviar las notificaciones a una dirección de correo electrónico, a un servidor de syslog o a un host de capturas de SNMP. 
---
= Decida dónde enviar notificaciones de eventos importantes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de configurar las notificaciones de eventos de EMS importantes, debe decidir si desea enviar las notificaciones a una dirección de correo electrónico, a un servidor de syslog o a un host de capturas de SNMP.

Si el entorno ya contiene un servidor de syslog para añadir los eventos registrados de otros sistemas, como servidores y aplicaciones, resulta más fácil utilizar el mismo servidor de syslog para enviar las notificaciones de eventos importantes de sistemas de almacenamiento.

Si el entorno no contiene ningún servidor de syslog, resulta más fácil usar un correo electrónico para enviar las notificaciones de eventos importantes.

Si ya ha reenviado notificaciones de eventos a un host de capturas de SNMP, es posible que desee supervisar dicho host de capturas para buscar eventos importantes.

* Configure EMS para que envíe notificaciones de eventos.
+
[cols="2*"]
|===
| Si desea que... | Consulte... 


 a| 
EMS envíe notificaciones de eventos importantes a una dirección de correo electrónico
 a| 
xref:task_configure_important_ems_events_to_send_email_notifications.html[Configuración de eventos de EMS importantes para enviar notificaciones por correo electrónico]



 a| 
EMS reenvíe notificaciones de eventos importantes a un servidor de syslog
 a| 
xref:task_configure_important_ems_events_to_forward_notifications_to_a_syslog_server.html[Configuración de eventos de EMS importantes para reenviar notificaciones a un servidor de syslog]



 a| 
EMS reenvíe notificaciones de eventos a un host de capturas de SNMP
 a| 
xref:task_configure_snmp_traphosts_to_receive_event_notifications.html[Configuración de los hosts de capturas de SNMP para recibir notificaciones de eventos]

|===

