---
permalink: asa/overview.html 
sidebar: sidebar 
keywords: all san array, asa, san, array, software, configuration, configure, configuring, setup, set up, limitations, restrictions, nvme, mcc ip, persistent ports, host, settings, utilities, ways to identify 
summary: Siga los siguientes procedimientos para configurar una cabina All SAN mediante System Manager. 
---
= Información general de la configuración de software de la cabina All SAN
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Las cabinas ALL SAN (ASAS) de NetApp están disponibles a partir de ONTAP 9.7.  ASAS son soluciones all-flash solo SAN creadas sobre las plataformas probadas de AFF de NetApp.

Las plataformas ASA utilizan activo-activo simétrico para la multivía. Todas las rutas son activas/optimizadas de modo que, en caso de conmutación al nodo de respaldo del almacenamiento, el host no necesita esperar a que se produzca la transición ALUA de las rutas de conmutación al nodo de respaldo para reanudar las operaciones de I/O. Esto reduce el tiempo de recuperación tras fallos.

La compatibilidad de ASA con nodos y protocolos SAN por clúster varía en función de su versión de ONTAP.

[cols="3*"]
|===


| Iniciando con ONTAP... | Compatibilidad con protocolos | N.o máx. De nodos por clúster 


| 9.12.1  a| 
* NVMe
* FC
* ISCSI

| 12 


| 9.9.1  a| 
* NVMe
* FC
* ISCSI

| 4 


| 9,7  a| 
* FC
* ISCSI

| 4 
|===


== Configure un ASA

Todas las matrices SAN (ASA) siguen el mismo procedimiento de configuración que los sistemas no ASA.

System Manager le guía por los procedimientos necesarios para inicializar su clúster, crear un nivel local, configurar protocolos y aprovisionar almacenamiento para su ASA. Consulte los pasos a. xref:../software_setup/concept_decide_whether_to_use_ontap_cli.html[Configure ONTAP].



== Configuración y utilidades del host ASA

La configuración del host para configurar todas las cabinas SAN (ASAS) es la misma que la de todos los demás hosts SAN.

Puede descargar la link:https://mysupport.netapp.com/NOW/cgi-bin/software["Software Host Utilities de NetApp"^] para los hosts específicos del sitio de soporte.



== Formas de identificar un sistema ASA

Puede identificar un sistema ASA mediante System Manager o mediante la interfaz de línea de comandos (CLI) de ONTAP.

En el panel de control de System Manager, haga clic en *clúster > Descripción general* y, a continuación, seleccione el nodo del sistema. El *PERSONALITY* se muestra como *matriz All SAN*.

Desde la CLI, puede utilizar el `san config show` comando. El valor de la "cabina All SAN" vuelve igual de cierto en los sistemas ASA.

.Información relacionada
* link:https://www.netapp.com/pdf.html?item=/media/85671-tr-4968.pdf["Informe técnico 4968: Integridad y disponibilidad de datos de las cabinas All-SAN de NetApp"^]
* link:http://www.netapp.com/us/media/tr-4080.pdf["Informe técnico 4080: Mejores prácticas para ONTAP con SAN escalable 9"^]

