---
permalink: asa/support-limitations.html 
sidebar: sidebar 
keywords: all flash san array, asa, san, array, software, configuration, configure, configuring, setup, set up, limitations, restrictions, nvme, mcc ip, persistent ports, host, settings, utilities, ways to identify 
summary: 'Los límites de configuración y la compatibilidad de las cabinas All Flash SAN (ASA) varían según la versión de ONTAP.' 
---
= Límites de configuración y compatibilidad de cabinas All Flash SAN
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Los límites de configuración y la compatibilidad de las cabinas All Flash SAN (ASA) varían según la versión de ONTAP.

Los detalles más actuales sobre los límites de configuración admitidos están disponibles en link:https://hwu.netapp.com/["Hardware Universe de NetApp"^].



== Nodos y protocolos SAN por clúster

La compatibilidad de ASA con los protocolos SAN y los nodos por clúster es la siguiente:

[cols="3*"]
|===


| Iniciando con ONTAP... | Compatibilidad con protocolos | N.o máx. De nodos por clúster 


| 9.12.1  a| 
* NVMe (compatible con configuraciones IP de MetroCluster de 4 nodos y configuraciones IP distintas de MetroCluster)
* FC
* ISCSI

| 12 


| 9.9.1  a| 
* NVMe (compatible con configuraciones IP que no sean de MetroCluster)
* FC
* ISCSI

 a| 
* 12 nodos (para configuraciones IP que no sean de MetroCluser)
* 8 nodos (para configuraciones IP de MetroCluster)




| 9,7  a| 
* FC
* ISCSI

| 4 
|===


== Compatibilidad con puertos persistentes

A partir de ONTAP 9,8, los puertos persistentes se habilitan de forma predeterminada en las cabinas all-flash SAN (ASAS) que se configuran para usar el protocolo FC. Los puertos persistentes solo están disponibles para FC y requieren pertenencia a una zona identificada por nombre de puerto WWPN.

Los puertos persistentes reducen el impacto de las tomas de control al crear un LIF en la sombra en el puerto físico correspondiente del partner de alta disponibilidad. Cuando se toma el control de un nodo, el LIF de respaldo del nodo del partner asume la identidad del LIF original, incluida la WWPNe. Antes de que el estado de la ruta al nodo tomado en defectuoso, la LIF redundante aparece como una ruta activa/optimizada para la pila MPIO del host y se cambia la I/O. De este modo, se reduce el trastorno de I/o porque el host siempre ve el mismo número de rutas al destino, incluso durante las operaciones de conmutación al nodo de respaldo del almacenamiento.

Para los puertos persistentes, las siguientes características de puerto FCP deben ser idénticas en el par de alta disponibilidad:

* Números de puertos FCP
* Nombres de puerto FCP
* Velocidades de puerto FCP
* División en zonas basada en WWPN de LIF FCP


Si alguna de estas características no es idéntica en la pareja de alta disponibilidad, se genera el siguiente mensaje de EMS:

`EMS : scsiblade.lif.persistent.ports.fcp.init.error`

Para obtener más información sobre los puertos persistentes, consulte link:http://www.netapp.com/us/media/tr-4080.pdf["Informe técnico de NetApp 4080: Prácticas recomendadas para SAN moderno"^].
