---
sidebar: sidebar 
permalink: high-availability/halt-reboot-node-wo-takeover-task.html 
keywords: high availability pair, hair, inhibit-takeover, reboot, epsilon, HA 
summary: Detuvo o reiniciar un nodo en un clúster de dos nodos sin iniciar la toma de control cuando realiza determinado mantenimiento de hardware en un nodo o una bandeja y desea limitar el tiempo de inactividad manteniendo el nodo del partner en funcionamiento. o cuando hay problemas que impiden la toma de control manual y desea mantener los agregados del nodo asociado en funcionamiento y sirviendo datos. Además, si el soporte técnico le ayuda a solucionar problemas, es posible que tenga que realizar este procedimiento como parte de dichos esfuerzos. 
---
= Detener o reiniciar los nodos ONTAP sin iniciar la toma de control en clústeres de dos nodos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Detuvo o reiniciar un nodo en un clúster de dos nodos sin iniciar la toma de control cuando realiza determinado mantenimiento de hardware en un nodo o una bandeja y desea limitar el tiempo de inactividad manteniendo el nodo del partner en funcionamiento. o cuando hay problemas que impiden la toma de control manual y desea mantener los agregados del nodo asociado en funcionamiento y sirviendo datos. Además, si el soporte técnico le ayuda a solucionar problemas, es posible que tenga que realizar este procedimiento como parte de dichos esfuerzos.

.Acerca de esta tarea
* Antes de inhibir la toma de control (con `-inhibit-takeover true` el parámetro), se deshabilita la alta disponibilidad del clúster.


[CAUTION]
====
* En un clúster de dos nodos, el clúster de alta disponibilidad garantiza que se produzca un error en un nodo que no deshabilite el clúster. Sin embargo, si no deshabilita la HA del clúster antes de usar el  `-inhibit-takeover true` parámetro, ambos nodos dejan de servir datos.
* Si intenta detener o reiniciar un nodo antes de deshabilitar la alta disponibilidad del clúster, ONTAP emite una advertencia y le indica que debe deshabilitar la alta disponibilidad del clúster.


====
* Migra LIF (interfaces lógicas) al nodo del partner que desea mantener en línea.
* Si en el nodo que va a detener o reiniciar hay agregados que desea conservar, los mueve al nodo que desea permanecer en línea.


.Pasos
. Verifica que ambos nodos están sanos:
+
[source, cli]
----
cluster show
----
+
En ambos nodos, `true` aparece en la `Health` columna.

+
[listing]
----
cluster::> cluster show
Node         Health  Eligibility
------------ ------- ------------
node1        true     true
node2        true     true
----
+
Obtenga más información sobre `cluster show` en el link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["Referencia de comandos del ONTAP"^].

. Migra todas las LIF del nodo que vas a detener o reiniciar al nodo asociado:
+
[source, cli]
----
network interface migrate-all -node <node_name>
----
+
Obtenga más información sobre `network interface migrate-all` en el link:https://docs.netapp.com/us-en/ontap-cli/network-interface-migrate-all.html["Referencia de comandos del ONTAP"^].

. Si hay agregados en el nodo que vas a detener o reiniciar y que quieres mantener en línea cuando el nodo esté caído, reubícalos en el nodo asociado.
+
.. Muestra los agregados en el nodo que vas a detener o reiniciar:
+
[source, cli]
----
storage aggregates show -node <node_name>
----
+
Por ejemplo, el nodo 1 es el nodo que se detuvo o reiniciando:

+
[listing]
----
cluster::> storage aggregates show -node node1
Aggregate  Size  Available  Used%  State  #Vols   Nodes   RAID  Status
---------  ----  ---------  -----  -----  -----   -----   ----  ------
aggr0_node_1_0
           744.9GB   32.68GB   96% online       2 node1    raid_dp,
                                                                normal
aggr1       2.91TB    2.62TB   10% online       8 node1    raid_dp,
                                                                normal
aggr2
            4.36TB    3.74TB   14% online      12 node1    raid_dp,
                                                                normal
test2_aggr  2.18TB    2.18TB    0% online       7 node1    raid_dp,
                                                                normal
4 entries were displayed.
----
.. Mueve los agregados al nodo asociado:
+
[source, cli]
----
storage aggregate relocation start -node <node_name> -destination <node_name> -aggregate-list <aggregate_name>
----
+
Por ejemplo, los agregados aggr1, aggr2 y test2_aggr se están moviendo del nodo 1 al nodo 2:

+
`storage aggregate relocation start -node _node1_ -destination _node2_ -aggregate-list _aggr1_,_aggr2_,_test2_aggr_`



. Desactiva HA de clúster:
+
[source, cli]
----
cluster ha modify -configured false
----
+
Cuando la HA del clúster está desactivada, epsilon se mueve automáticamente al nodo 1. La salida de retorno confirma que la HA está desactivada: `Notice: HA is disabled`

+

NOTE: Esta operación no deshabilita la conmutación al nodo de respaldo del almacenamiento.

. Si el nodo que se va a detener o reiniciar es el nodo 1, mueve epsilon al nodo 2:
+
.. Configure el nivel de privilegio en Advanced:
+
[source, cli]
----
set -privilege advanced
----
.. Verifica que el nodo 2 está sano y es elegible para epsilon:
+
[source, cli]
----
cluster show
----
.. Elimina epsilon del nodo 1:
+
[source, cli]
----
cluster modify -node <node1_name> -epsilon false
----
.. Asigna epsilon al nodo 2:
+
[source, cli]
----
cluster modify -node <node2_name> -epsilon true
----
.. Verifica que epsilon está en el nodo 2:
+
[source, cli]
----
cluster show
----


. Detén o reinicia e inhibe la toma de control del nodo de destino:
+
[cols="1h,1h"]
|===


 a| 
Detén el nodo sin iniciar la toma de control:
 a| 
[source, cli]
----
system node halt -node _node_name_ -inhibit-takeover true
----


 a| 
Reinicia el nodo sin iniciar la toma de control:
 a| 
[source, cli]
----
system node reboot -node _node_name_ -inhibit-takeover true
----
|===
+

NOTE: En la salida del comando, verá una advertencia que le preguntará si desea continuar, introduzca `y`.

. Verifica que el nodo que sigue en línea está en un estado saludable (mientras el compañero está caído):
+
[source, cli]
----
cluster show
----
+
Para el nodo en línea, `true` aparece en la `Health` columna.

+

NOTE: En la salida del comando, verás una advertencia de que la HA de clúster no está configurada. Puedes ignorar la advertencia.

. Realice las acciones que le requerían para detener o reiniciar el nodo.
. Arranca el nodo offline desde el prompt LOADER:
+
[source, cli]
----
boot_ontap
----
. Verifica que ambos nodos están sanos:
+
[source, cli]
----
cluster show
----
+
En ambos nodos, `true` aparece en la `Health` columna.

+

NOTE: En el resultado del comando, verá una advertencia de que alta disponibilidad del clúster no está configurado. Puede ignorar la advertencia en este momento.

. Vuelve a activar la HA del clúster:
+
[source, cli]
----
cluster ha modify -configured true
----
. Si antes en este procedimiento reubicastes los agregados al nodo asociado, muévelos de vuelta a su nodo de origen.
+
[source, cli]
----
storage aggregate relocation start -node <node_name> -destination <node_name> -aggregate-list <aggregate_name>
----
+
Por ejemplo, los agregados aggr1, aggr2 y test2_aggr se están moviendo del nodo node2 al nodo node1:
`storage aggregate relocation start -node _node2_ -destination _node1_ -aggregate-list _aggr1_,_aggr2_,_test2_aggr_`

. Revertir los LIF a sus puertos raíz:
+
.. Ver los LIF que no están en casa:
+
[source, cli]
----
network interface show -is-home false
----
+
Obtenga más información sobre `network interface show` en el link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["Referencia de comandos del ONTAP"^].

.. Si hay LIF sin hogar que no se migraron desde el nodo inactivo, compruebe que es seguro moverlas antes de revertir.
.. Si es seguro hacerlo, revierte todos los LIF a su hogar.
+
[source, cli]
----
 network interface revert *
----
+
Obtenga más información sobre `network interface revert` en el link:https://docs.netapp.com/us-en/ontap-cli/network-interface-revert.html["Referencia de comandos del ONTAP"^].





.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-ha-modify.html["modificación de alta disponibilidad del clúster"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-relocation-start.html["Inicio de la reubicación del agregado de almacenamiento"^]

