---
permalink: nas-audit/additional-information-reference.html 
sidebar: sidebar 
keywords: additional information 
summary: Una vez que haya probado correctamente el acceso al cliente SMB, puede ejecutar la configuración avanzada de SMB o añadir acceso SAN. Una vez que haya probado correctamente el acceso al cliente NFS, puede ejecutar una configuración de NFS avanzada o añadir acceso SAN. Una vez completado el acceso al protocolo, debe proteger el volumen raíz de la SVM. 
---
= Dónde encontrar información adicional
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una vez que haya probado correctamente el acceso al cliente SMB, puede ejecutar la configuración avanzada de SMB o añadir acceso SAN. Una vez que haya probado correctamente el acceso al cliente NFS, puede ejecutar una configuración de NFS avanzada o añadir acceso SAN. Una vez completado el acceso al protocolo, debe proteger el volumen raíz de la SVM.



== Configuración de SMB

Puede configurar el acceso SMB además utilizando lo siguiente:

* link:../smb-admin/index.html["Gestión de SMB"]
+
Describe cómo configurar y gestionar el acceso a archivos mediante el protocolo SMB.

* https://www.netapp.com/us/media/tr-4191.pdf["Informe técnico de NetApp 4191: Guía de mejores prácticas para servicios de archivos de Windows para Clustered Data ONTAP 8.2"]
+
Proporciona una breve descripción general de la implementación de SMB y otras funciones de servicios de archivos Windows con recomendaciones e información básica sobre solución de problemas para ONTAP.

* https://www.netapp.com/us/media/tr-3740.pdf["Informe técnico de NetApp 3740: Protocolo CIFS de última generación de SMB 2 en Data ONTAP"]
+
Describe las funciones de SMB 2, los detalles de configuración y su implementación en ONTAP.





== Configuración de NFS

Puede configurar el acceso NFS de forma adicional utilizando lo siguiente:

* link:../nfs-admin/index.html["Gestión de NFS"]
+
Describe cómo configurar y gestionar el acceso a archivos mediante el protocolo NFS.

* https://www.netapp.com/us/media/tr-4067.pdf["Informe técnico de NetApp 4067: Guía de prácticas recomendadas e implementación de NFS"^]
+
Sirve de guía de funcionamiento de NFSv3 y NFSv4 y ofrece una descripción general del sistema operativo de ONTAP haciendo hincapié en NFSv4.

* https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["Informe técnico de NetApp 4668: Guía de prácticas recomendadas de servicios de nombres"^]
+
Proporciona una lista completa de prácticas recomendadas, límites, recomendaciones y consideraciones a la hora de configurar archivos de LDAP, NIS, DNS y usuarios locales y de grupos para fines de autenticación.

* https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf["Informe técnico de NetApp 4616: Kerberos de NFS en ONTAP con Microsoft Active Directory"]
* https://www.netapp.com/pdf.html?item=/media/19423-tr-4835.pdf["Informe técnico de NetApp 4835: Cómo configurar LDAP en ONTAP"]
* https://www.netapp.com/us/media/tr-3580.pdf["Informe técnico de NetApp 3580: Guía de mejoras y prácticas recomendadas de NFSv4: Implementación de Data ONTAP"]
+
Describe las prácticas recomendadas que se deben seguir mientras implementa componentes de NFSv4 en clientes AIX, Linux o Solaris conectados a sistemas que ejecutan ONTAP.





== Protección de volúmenes raíz

Después de configurar los protocolos en la SVM, debe asegurarse de que su volumen raíz esté protegido:

* link:../data-protection/index.html["Protección de datos"]
+
Describe cómo crear un reflejo de uso compartido de carga para proteger el volumen raíz de SVM, que es una práctica recomendada por NetApp para SVM habilitadas para NAS. También describe cómo recuperarse rápidamente de fallos o pérdidas de volúmenes mediante la promoción del volumen raíz de SVM desde un reflejo de uso compartido de carga.


