---
permalink: nas-audit/basic-auditing-concept.html 
sidebar: sidebar 
keywords: basic audit concepts 
summary: Para comprender la auditoría en ONTAP, debe conocer algunos conceptos básicos de auditoría. 
---
= Conceptos básicos de auditoría
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para comprender la auditoría en ONTAP, debe conocer algunos conceptos básicos de auditoría.

* *Archivos de ensayo*
+
Los archivos binarios intermedios en nodos individuales en los que se almacenan los registros de auditoría antes de la consolidación y la conversión. Los archivos de almacenamiento provisional se encuentran en volúmenes de almacenamiento provisional.

* *Volumen de estadificación*
+
Un volumen dedicado creado por ONTAP para almacenar archivos provisional. Hay un volumen de almacenamiento provisional por agregado. Todas las máquinas virtuales de almacenamiento (SVM) habilitadas para auditoría comparten los volúmenes de almacenamiento para almacenar registros de auditoría de acceso a los datos de los volúmenes de datos de ese agregado en particular. Los registros de auditoría de cada SVM se almacenan en un directorio independiente dentro del volumen provisional.

+
Los administradores de clúster pueden ver información sobre la configuración provisional de los volúmenes, pero no se permite la mayoría de las demás operaciones de volumen. Solo ONTAP puede crear volúmenes de almacenamiento provisional. ONTAP asigna automáticamente un nombre a la configuración provisional de los volúmenes. Todos los nombres de volúmenes de almacenamiento provisional comienzan por `MDV_aud_` Seguido del UUID del agregado que contiene ese volumen de almacenamiento provisional (por ejemplo: `MDV_aud_1d0131843d4811e296fc123478563412`.)

* *Volúmenes del sistema*
+
Un volumen FlexVol que contiene metadatos especiales, como metadatos para registros de auditoría de servicios de archivos. La SVM de administrador es propietaria de los volúmenes de sistemas, que son visibles en el clúster. El almacenamiento provisional de volúmenes es un tipo de volumen del sistema.

* *Tarea de consolidación*
+
Tarea que se crea al activar la auditoría. Esta tarea de larga ejecución en cada SVM toma los registros de auditoría de archivos staging en los nodos miembros de la SVM. Esta tarea fusiona los registros de auditoría en orden cronológico ordenado y los convierte a continuación en un formato de registro de eventos legible para el usuario especificado en la configuración de auditoría, ya sea en el formato de archivo EVTX o XML. Los registros de eventos convertidos se almacenan en el directorio del registro de eventos de auditoría especificado en la configuración de auditoría de SVM.


