---
permalink: nas-audit/configure-fpolicy-ssl-connections-concept.html 
sidebar: sidebar 
keywords: additional information, configure, fpolicy, external engines, ssl authenticated, connections 
summary: Debe conocer alguna información adicional si desea configurar el motor externo de FPolicy para usar SSL al conectarse a los servidores de FPolicy. 
---
= Información adicional sobre la configuración de motores externos de FPolicy para usar conexiones autenticadas SSL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe conocer alguna información adicional si desea configurar el motor externo de FPolicy para usar SSL al conectarse a los servidores de FPolicy.



== Autenticación de servidor SSL

Si decide configurar el motor externo de FPolicy para la autenticación del servidor SSL, antes de crear el motor externo, debe instalar el certificado público de la entidad de certificación (CA) que firmó el certificado de servidor FPolicy.



== Autenticación mutua

Si configura motores externos de FPolicy para utilizar autenticación mutua de SSL al conectar LIF de datos de máquinas virtuales de almacenamiento (SVM) a servidores FPolicy externos, antes de crear el motor externo, Debe instalar el certificado público de la CA que firmó el certificado de servidor FPolicy junto con el certificado público y el archivo de claves para la autenticación de la SVM. No elimine este certificado mientras ninguna política de FPolicy esté utilizando el certificado instalado.

Si el certificado se elimina mientras FPolicy lo utiliza para autenticación mutua al conectarse a un servidor de FPolicy externo, no podrá volver a habilitar una política de FPolicy deshabilitada que utilice ese certificado. No se puede volver a habilitar la política de FPolicy en esta situación aunque se cree e instale un nuevo certificado con las mismas configuraciones en la SVM.

Si el certificado se ha eliminado, deberá instalar un nuevo certificado, crear nuevos motores externos de FPolicy que utilicen el nuevo certificado y asociar los nuevos motores externos a la política de FPolicy que desee volver a habilitar modificando la directiva de FPolicy.



== Instalar certificados para SSL

El certificado público de la CA que se utiliza para firmar el certificado de servidor FPolicy se instala mediante `security certificate install` el comando con el `-type` parámetro establecido en `client-ca`. La clave privada y el certificado público requeridos para la autenticación de la SVM se instala mediante `security certificate install` el comando con `-type` el parámetro establecido en `server`.
