---
permalink: nas-audit/configure-auditing-unix-security-files-directories-task.html 
sidebar: sidebar 
keywords: configure, audit, unix security style files, directories 
summary: Para configurar la auditoría de directorios y archivos de estilo de seguridad de UNIX, debe añadir ACE de auditoría a NFSv4.x ACL. Esto le permite supervisar determinados eventos de acceso a archivos y directorios de NFS con fines de seguridad. 
---
= Configurar la auditoría de ONTAP para los archivos y directorios de estilo de seguridad de UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para configurar la auditoría de directorios y archivos de estilo de seguridad de UNIX, debe añadir ACE de auditoría a NFSv4.x ACL. Esto le permite supervisar determinados eventos de acceso a archivos y directorios de NFS con fines de seguridad.

.Acerca de esta tarea
Para NFSv4.x, tanto los valores ACs discrecionales como los del sistema se almacenan en la misma ACL. No se almacenan en DACL y SACL independientes. Por lo tanto, debe tener cuidado al agregar ACE de auditoría a una ACL existente para evitar sobrescribir y perder una ACL existente. El orden en el que se agregan los ACE de auditoría a una ACL existente no importa.

.Pasos
. Recupere la ACL existente para el archivo o directorio mediante `nfs4_getfacl` el comando o equivalente.
+
Obtenga más información sobre la manipulación de ACL en el link:https://docs.netapp.com/us-en/ontap-cli/["Referencia de comandos del ONTAP"^].

. Añada las ACE de auditoría deseadas.
. Aplique la ACL actualizada al archivo o directorio mediante `nfs4_setfacl` el comando o equivalente.

