---
permalink: nas-audit/create-fpolicy-event-task.html 
sidebar: sidebar 
keywords: creating, fpolicy event 
summary: Como parte de la creación de una configuración de políticas de FPolicy, debe crear un evento FPolicy. El evento se asocia a la política de FPolicy cuando se cree. Un evento define qué protocolo supervisar y qué eventos de acceso a archivos supervisar y filtrar. 
---
= Cree el evento FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Como parte de la creación de una configuración de políticas de FPolicy, debe crear un evento FPolicy. El evento se asocia a la política de FPolicy cuando se cree. Un evento define qué protocolo supervisar y qué eventos de acceso a archivos supervisar y filtrar.

.Antes de empezar
Debe completar el evento de FPolicy link:https://docs.netapp.com/us-en/ontap/nas-audit/fpolicy-event-config-worksheet-reference.html["hoja de trabajo"].



== Cree el evento FPolicy

. Cree el evento FPolicy mediante `vserver fpolicy policy event create` comando.
+
`vserver fpolicy policy event create -vserver vs1.example.com -event-name event1 -protocol cifs -file-operations open,close,read,write`

. Verifique la configuración del evento FPolicy mediante `vserver fpolicy policy event show` comando.
+
`vserver fpolicy policy event show -vserver vs1.example.com`

+
[listing]
----

                  Event               File                    Is Volume
Vserver           Name      Protocols Operations    Filters   Operation
---------------   --------- --------- ------------- --------- ------------
vs1.example.com   event1    cifs      open, close,  -         false
                                      read, write
----




== Cree los eventos de acceso denegado a FPolicy

A partir de ONTAP 9.13.1, los usuarios pueden recibir notificaciones por operaciones de archivos fallidas debido a la falta de permisos. Estas notificaciones son valiosas para la seguridad, la protección contra el ransomware y la gobernanza.

. Cree el evento FPolicy mediante `vserver fpolicy policy event create` comando.
+
`vserver fpolicy policy event create -vserver vs1.example.com -event-name event1 -protocol cifs -monitor-fileop-failure true -file-operations open`


