---
permalink: nas-audit/create-fpolicy-policy-task.html 
sidebar: sidebar 
keywords: create, fpolicy, policy 
summary: 'Cuando crea la política de FPolicy, debe asociar un motor externo y uno o varios eventos a la política. La directiva también especifica si es necesario realizar un tramado obligatorio, si los servidores FPolicy tienen un acceso privilegiado a los datos en la máquina virtual de almacenamiento (SVM) y si está habilitada la lectura paso a través para archivos sin conexión.' 
---
= Cree la política FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando crea la política de FPolicy, debe asociar un motor externo y uno o varios eventos a la política. La directiva también especifica si es necesario realizar un tramado obligatorio, si los servidores FPolicy tienen un acceso privilegiado a los datos en la máquina virtual de almacenamiento (SVM) y si está habilitada la lectura paso a través para archivos sin conexión.

.Antes de empezar
* Debe rellenar la hoja de trabajo de la política FPolicy.
* Si planea configurar la directiva para que utilice servidores FPolicy, el motor externo debe existir.
* Debe existir al menos un evento FPolicy que planifique para asociar a la política de FPolicy.
* Si desea configurar el acceso a datos con privilegios, debe existir un servidor SMB en la SVM.
* Para configurar un almacén persistente para una política, el tipo de motor debe ser *asincrónico* y la política debe ser *no obligatoria*.
+
Para obtener más información, consulte link:create-persistent-stores.html["Crear almacenes persistentes"].



.Pasos
. Cree la política de FPolicy:
+
`vserver fpolicy policy create -vserver-name vserver_name -policy-name policy_name -engine engine_name -events event_name, [-persistent-store PS_name] [-is-mandatory {true|false}] [-allow-privileged-access {yes|no}] [-privileged-user-name domain\user_name] [-is-passthrough-read-enabled {true|false}]`

+
** Puede añadir uno o varios eventos a la política de FPolicy.
** De forma predeterminada, la selección obligatoria está activada.
** Si desea permitir el acceso con privilegios definiendo el `-allow-privileged-access` parámetro en `yes`, también debe configurar un nombre de usuario con privilegios para el acceso con privilegios.
** Si desea configurar passthrough-read definiendo el `-is-passthrough-read-enabled` parámetro en `true`, también debe configurar el acceso a datos con privilegios.
+
El siguiente comando crea una política denominada «'poly1'» que tiene asociado el evento denominado «'event1'» y el motor externo denominado «'motor1'». Esta política utiliza valores predeterminados en la configuración de la política:
`vserver fpolicy policy create -vserver vs1.example.com -policy-name policy1 -events event1 -engine engine1`

+
El siguiente comando crea una política denominada «'policy 2» que tiene asociado el evento denominado «'event2'» y el motor externo denominado «'motor2'». Esta directiva está configurada para utilizar acceso privilegiado utilizando el nombre de usuario especificado. La lectura PassThrough está habilitada:

+
`vserver fpolicy policy create -vserver vs1.example.com -policy-name policy2 -events event2 -engine engine2 -allow-privileged-access yes ‑privileged-user-name example\archive_acct -is-passthrough-read-enabled true`

+
El siguiente comando crea una política denominada «'native1'» que tiene asociado el evento denominado «'event3'». Esta directiva utiliza el motor nativo y utiliza valores predeterminados en la configuración de directivas:

+
`vserver fpolicy policy create -vserver vs1.example.com -policy-name native1 -events event3 -engine native`



. Verifique la configuración de la política de FPolicy mediante `vserver fpolicy policy show` el comando.
+
El siguiente comando muestra información acerca de las tres políticas de FPolicy configuradas, incluida la siguiente información:

+
** La SVM asociada a la política
** El motor externo asociado a la directiva
** Los eventos asociados a la política
** Si es necesario realizar una selección obligatoria
** Indica si se necesita acceso con privilegios
`vserver fpolicy policy show`


+
[listing]
----

   Vserver       Policy     Events    Engine    Is Mandatory  Privileged
                 Name                                         Access
--------------   ---------  --------- --------- ------------  -----------
vs1.example.com  policy1    event1    engine1   true          no
vs1.example.com  policy2    event2    engine2   true          yes
vs1.example.com  native1    event3    native    true          no
----

