---
permalink: nas-audit/delete-security-trace-records-task.html 
sidebar: sidebar 
keywords: delete, security trace records 
summary: Después de terminar de utilizar un registro de seguimiento de filtro para verificar la seguridad de acceso a archivos o para solucionar problemas de acceso de clientes SMB o NFS, puede eliminar el registro de seguimiento de seguridad del registro de seguimiento de seguridad. 
---
= Eliminar registros de rastreo de seguridad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de terminar de utilizar un registro de seguimiento de filtro para verificar la seguridad de acceso a archivos o para solucionar problemas de acceso de clientes SMB o NFS, puede eliminar el registro de seguimiento de seguridad del registro de seguimiento de seguridad.

.Acerca de esta tarea
Para poder eliminar un registro de seguimiento de seguridad, debe conocer el número de secuencia del registro.

[NOTE]
====
Cada máquina virtual de almacenamiento (SVM) puede almacenar un máximo de 128 registros de seguimiento. Si se alcanza el máximo en la SVM, los registros de seguimiento más antiguos se eliminan automáticamente a medida que se añaden otros nuevos. Si no desea eliminar manualmente los registros de seguimiento de esta SVM, es posible eliminar automáticamente ONTAP los resultados de rastros más antiguos después de alcanzar el máximo para hacer espacio para nuevos resultados.

====
.Pasos
. Identifique el número de secuencia del registro que desea eliminar:
+
`vserver security trace trace-result show -vserver vserver_name -instance`

. Elimine el registro de seguimiento de seguridad:
+
`vserver security trace trace-result delete -node node_name -vserver vserver_name -seqnum integer`

+
`vserver security trace trace-result delete -vserver vs1 -node node1 -seqnum 999`

+
** `-node` `node_name` es el nombre del nodo de clúster en el que se produjo el evento de seguimiento de permisos que desea eliminar.
+
Este es un parámetro obligatorio.

** `-vserver` `vserver_name` Es el nombre de la SVM donde se produjo el evento de seguimiento de permisos que desea eliminar.
+
Este es un parámetro obligatorio.

** `-seqnum` `integer` es el número de secuencia del evento de registro que se desea eliminar.
+
Este es un parámetro obligatorio.




