---
permalink: nas-audit/determine-complete-path-audited-object-task.html 
sidebar: sidebar 
keywords: determine, complete path, audited object 
summary: 'La ruta de acceso del objeto impresa en la etiqueta <ObjectName> de un registro de auditoría contiene el nombre del volumen (entre paréntesis) y la ruta relativa desde la raíz del volumen que contiene. Si desea determinar la ruta completa del objeto auditado, incluida la ruta de unión, hay algunos pasos que debe seguir.' 
---
= Determine la ruta de acceso completa al objeto auditado ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ruta del objeto impresa en `<ObjectName>` la etiqueta de un registro de auditoría contiene el nombre del volumen (entre paréntesis) y la ruta relativa desde la raíz del volumen que contiene. Si desea determinar la ruta completa del objeto auditado, incluida la ruta de unión, hay algunos pasos que debe seguir.

.Pasos
. Para determinar el nombre del volumen y la ruta relativa al objeto auditado, consulte la `<ObjectName>` etiquete el evento de auditoría.
+
En este ejemplo, el nombre del volumen es "data1" y la ruta relativa al archivo es `/dir1/file.txt`:

+
`<Data Name="ObjectName">` `(data1);/dir1/file.txt` `</Data>`

. Con el nombre del volumen determinado en el paso anterior, determine cuál es la ruta de unión para el volumen que contiene el objeto auditado:
+
En este ejemplo, el nombre del volumen es "data1" y la ruta de unión del volumen que contiene el objeto auditado es `/data/data1`:

+
`volume show -junction -volume data1`

+
[listing]
----

                                Junction                    Junction
Vserver   Volume       Language Active    Junction Path     Path Source
--------- ------------ -------- --------  ----------------- -----------
vs1       data1        en_US.UTF-8
                                true      /data/data1       RW_volume
----
. Determine la ruta completa al objeto auditado anexando la ruta relativa que se encuentra en `<ObjectName>` etiquete la ruta de unión para el volumen.
+
En este ejemplo, la ruta de unión para el volumen:

+
`/data/data1/dir1/file.text`


