---
permalink: nas-audit/disconnect-from-external-fpolicy-servers-task.html 
sidebar: sidebar 
keywords: disconnect, external fpolicy servers 
summary: Es posible que deba desconectarse manualmente de un servidor de FPolicy externo. Esto puede ser aconsejable si el servidor FPolicy tiene problemas con el procesamiento de solicitudes de notificación o si necesita realizar tareas de mantenimiento en el servidor FPolicy. 
---
= Desconéctese de los servidores externos de FPolicy en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que deba desconectarse manualmente de un servidor de FPolicy externo. Esto puede ser aconsejable si el servidor FPolicy tiene problemas con el procesamiento de solicitudes de notificación o si necesita realizar tareas de mantenimiento en el servidor FPolicy.

.Pasos
. Desconecte del servidor FPolicy externo mediante `vserver fpolicy engine-disconnect` comando.
+
Obtenga más información sobre `vserver fpolicy engine-disconnect` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-fpolicy-engine-disconnect.html["Referencia de comandos de la ONTAP"^].

. Compruebe que el servidor FPolicy externo esté desconectado mediante el `vserver fpolicy show-engine` comando.
+
Obtenga más información sobre `vserver fpolicy show-engine` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-fpolicy-show-engine.html["Referencia de comandos de la ONTAP"^].


