---
permalink: nas-audit/display-enabled-fpolicy-policies-task.html 
sidebar: sidebar 
keywords: display, information, enabled fpolicy policies 
summary: 'Puede mostrar información acerca de las políticas de FPolicy habilitadas para determinar qué motor externo de FPolicy se ha configurado para utilizar, cuál es la prioridad de la política y a qué máquina virtual de almacenamiento (SVM) está asociada la política de FPolicy.' 
---
= Muestra información acerca de las políticas de FPolicy habilitadas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede mostrar información acerca de las políticas de FPolicy habilitadas para determinar qué motor externo de FPolicy se ha configurado para utilizar, cuál es la prioridad de la política y a qué máquina virtual de almacenamiento (SVM) está asociada la política de FPolicy.

.Acerca de esta tarea
Si no especifica ningún parámetro, el comando muestra la siguiente información:

* Nombre de SVM
* Nombre de la política
* Prioridad en materia de políticas


Puede utilizar parámetros de comando para filtrar el resultado del comando por criterios especificados.

.Paso
. Muestre información sobre las políticas de FPolicy habilitadas mediante el comando correspondiente:
+
[cols="35,65"]
|===


| Si desea mostrar información sobre las políticas habilitadas... | Introduzca el comando... 


 a| 
En el clúster
 a| 
`vserver fpolicy show-enabled`



 a| 
En una SVM especificada
 a| 
`vserver fpolicy show-enabled -vserver vserver_name`



 a| 
Con el nombre de la política especificada
 a| 
`vserver fpolicy show-enabled -policy-name policy_name`



 a| 
Con el número de secuencia especificado
 a| 
`vserver fpolicy show-enabled -priority integer`

|===


.Ejemplo
En el siguiente ejemplo se muestra la información acerca de las políticas de FPolicy habilitadas en el clúster:

[listing]
----
cluster1::> vserver fpolicy show-enabled
Vserver                 Policy Name               Priority

----------------------- ------------------------- ----------
vs1.example.com         pol_native                native
vs1.example.com         pol_native2               native
vs1.example.com         pol1                      2
vs1.example.com         pol2                      4
----