---
permalink: nas-audit/display-audit-policies-windows-security-tab-task.html 
sidebar: sidebar 
keywords: display, information, audit policies, windows security tab 
summary: Puede mostrar información acerca de las directivas de auditoría que se han aplicado a archivos y directorios mediante la ficha Seguridad de la ventana Propiedades de Windows. Este es el mismo método utilizado para los datos que se encuentran en un servidor de Windows, con el que los clientes pueden utilizar la misma interfaz gráfica de usuario que están acostumbrados a utilizar. 
---
= Para ver la información de la política de auditoría de ONTAP, acceda a la pestaña Seguridad de Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede mostrar información acerca de las directivas de auditoría que se han aplicado a archivos y directorios mediante la ficha Seguridad de la ventana Propiedades de Windows. Este es el mismo método utilizado para los datos que se encuentran en un servidor de Windows, con el que los clientes pueden utilizar la misma interfaz gráfica de usuario que están acostumbrados a utilizar.

.Acerca de esta tarea
La visualización de información acerca de las directivas de auditoría aplicadas a archivos y directorios permite verificar que se han establecido las listas de control de acceso del sistema (SACL) adecuadas en archivos y carpetas especificados.

Para mostrar información acerca de SACL que se han aplicado a archivos y carpetas NTFS, lleve a cabo los siguientes pasos en un host de Windows.

.Pasos
. En el menú *Herramientas* del Explorador de Windows, seleccione *asignar unidad de red*.
. Complete el cuadro de diálogo *asignar unidad de red*:
+
.. Seleccione una letra *Unidad*.
.. En el cuadro *carpeta*, escriba la dirección IP o el nombre del servidor SMB de la máquina virtual de almacenamiento (SVM) que contiene el recurso compartido que contiene tanto los datos que desea auditar como el nombre del recurso compartido.
+
Si el nombre de su servidor SMB es '`SMB_SERVER`' y su recurso compartido se llama ''hare1'', debe ingresar `\\SMB_SERVER\share1`.

+
[NOTE]
====
Puede especificar la dirección IP de la interfaz de datos para el servidor SMB en lugar del nombre del servidor SMB.

====
.. Haga clic en *Finalizar*.


+
La unidad seleccionada está montada y lista con la ventana del Explorador de Windows que muestra archivos y carpetas contenidos en el recurso compartido.

. Seleccione el archivo o directorio para el que se muestra información de auditoría.
. Haga clic con el botón derecho del ratón en el archivo o directorio y seleccione *Propiedades*.
. Seleccione la ficha *Seguridad*.
. Haga clic en *Avanzado*.
. Seleccione la ficha *Auditoría*.
. Haga clic en *continuar*.
+
Se abre el cuadro Auditoría. El cuadro *Entradas de auditoría* muestra un resumen de los usuarios y grupos que tienen SACL aplicados a ellos.

. En el cuadro *Entradas de auditoría*, seleccione el usuario o grupo cuyas entradas de SACL desee mostrar.
. Haga clic en *Editar*.
+
Se abre el cuadro Entrada de auditoría para <object>.

. En el cuadro *Access*, vea las SACL actuales que se aplican al objeto seleccionado.
. Haga clic en *Cancelar* para cerrar el cuadro *Entrada de auditoría para <object>*.
. Haga clic en *Cancelar* para cerrar el cuadro *Auditoría*.

