---
permalink: nas-audit/display-fpolicy-passthrough-read-connection-task.html 
sidebar: sidebar 
keywords: display, information, fpolicy, passthrough-read, connection status 
summary: 'Es posible mostrar información acerca del estado de conexión de lectura directa de FPolicy en los servidores FPolicy externos (servidores FPolicy) para el clúster o para una máquina virtual de almacenamiento (SVM) especificada. Esta información puede ayudarle a determinar qué servidores de FPolicy tienen conexiones de datos de lectura directa y para los que se ha desconectado los servidores de FPolicy.' 
---
= Muestra información acerca del estado de conexión de lectura de paso a través de FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible mostrar información acerca del estado de conexión de lectura directa de FPolicy en los servidores FPolicy externos (servidores FPolicy) para el clúster o para una máquina virtual de almacenamiento (SVM) especificada. Esta información puede ayudarle a determinar qué servidores de FPolicy tienen conexiones de datos de lectura directa y para los que se ha desconectado los servidores de FPolicy.

.Acerca de esta tarea
Si no especifica ningún parámetro, el comando muestra la siguiente información:

* Nombre de SVM
* Nombre de la política de FPolicy
* Nombre del nodo
* Dirección IP del servidor FPolicy
* Estado de conexión de lectura directa de FPolicy


Además de mostrar información acerca de las conexiones de FPolicy en el clúster o una SVM específica, puede usar parámetros de comandos para filtrar el resultado del comando según otros criterios.

Puede especificar el `-instance` parámetro para mostrar información detallada de las políticas mostradas. De forma alternativa, puede utilizar la `-fields` parámetro para mostrar solo los campos indicados en el resultado del comando. Puede entrar `?` después del `-fields` parámetro para averiguar qué campos se pueden utilizar.

.Paso
. Mostrar información filtrada acerca del estado de conexión entre el nodo y el servidor FPolicy mediante el comando correspondiente:
+
[cols="35,65"]
|===


| Si desea mostrar información sobre el estado de la conexión acerca de... | Introduzca el comando... 


 a| 
El estado de la conexión de lectura directa de FPolicy para el clúster
 a| 
`vserver fpolicy show-passthrough-read-connection`



 a| 
El estado de conexión de lectura directa de FPolicy para una SVM especificada
 a| 
`vserver fpolicy show-passthrough-read-connection -vserver vserver_name`



 a| 
Estado de conexión de lectura directa de FPolicy para una política especificada
 a| 
`vserver fpolicy show-passthrough-read-connection -policy-name policy_name`



 a| 
El estado de conexión de lectura directa de FPolicy detallado para una política especificada
 a| 
`vserver fpolicy show-passthrough-read-connection -policy-name policy_name -instance`



 a| 
El estado de conexión de lectura directa de FPolicy correspondiente al estado especificado
 a| 
`vserver fpolicy show-passthrough-read-connection -policy-name policy_name -server-status status` El estado del servidor puede ser uno de los siguientes:

** `connected`
** `disconnected`


|===


.Ejemplo
El siguiente comando muestra información acerca de las conexiones de lectura de paso a través de todos los servidores FPolicy del clúster:

[listing]
----
cluster1::> vserver fpolicy show-passthrough-read-connection
                                            FPolicy           Server
Vserver          Policy Name   Node         Server            Status
---------------  ------------- ------------ ----------------- --------------
vs2.example.com  pol_cifs_2    FPolicy-01   2.2.2.2           disconnected
vs1.example.com  pol_cifs_1    FPolicy-01   1.1.1.1           connected
----
El siguiente comando muestra información detallada acerca de las conexiones de lectura a través de paso desde los servidores FPolicy configurados en la política "'pol_cifs_1'":

[listing]
----
cluster1::> vserver fpolicy show-passthrough-read-connection -policy-name pol_cifs_1 -instance

                                             Node: FPolicy-01
                                          Vserver: vs1.example.com
                                           Policy: pol_cifs_1
                                           Server: 1.1.1.1
                Session ID of the Control Channel: 8cef052e-2502-11e3-88d4-123478563412
                                    Server Status: connected
      Time Passthrough Read Channel was Connected: 9/24/2013 10:17:45
   Time Passthrough Read Channel was Disconnected: -
Reason for Passthrough Read Channel Disconnection: none
----