---
permalink: nas-audit/enable-fpolicy-policy-task.html 
sidebar: sidebar 
keywords: enable, fpolicy policy 
summary: Después de configurar una configuración de políticas de FPolicy, debe habilitar la política de FPolicy. Al habilitar la directiva, se establece su prioridad e inicia la supervisión del acceso a los archivos de la directiva. 
---
= Habilitar políticas de ONTAP FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de configurar una configuración de políticas de FPolicy, debe habilitar la política de FPolicy. Al habilitar la directiva, se establece su prioridad e inicia la supervisión del acceso a los archivos de la directiva.

.Antes de empezar
La política de FPolicy debe existir con un motor externo asociado (si la política se configura para utilizar servidores de FPolicy externos) y debe tener al menos un evento de FPolicy asociado. El alcance de la política de FPolicy debe existir y debe asignarse a la política de FPolicy.

.Acerca de esta tarea
La prioridad se utiliza cuando se habilitan varias políticas en la máquina virtual de almacenamiento (SVM) y se ha suscrito más de una directiva al mismo evento de acceso a archivos. Las directivas que utilizan la configuración del motor nativo tienen una prioridad mayor que las directivas para cualquier otro motor, independientemente del número de secuencia que se les haya asignado al habilitar la política.

[NOTE]
====
No se puede habilitar una política en la SVM de administrador.

====
.Pasos
. Habilite la política de FPolicy mediante `vserver fpolicy enable` el comando.
+
`vserver fpolicy enable -vserver-name vs1.example.com -policy-name policy1 -sequence-number 1`

. Compruebe que la política de FPolicy esté habilitada mediante `vserver fpolicy show` el comando.
+
`vserver fpolicy show -vserver vs1.example.com`

+
[listing]
----

                                   Sequence
Vserver          Policy Name         Number  Status   Engine
---------------  ----------------- --------  -------- ---------
vs1.example.com  policy1                  1  on       engine1
----

