---
permalink: nas-audit/enable-disable-auditing-svms-task.html 
sidebar: sidebar 
keywords: enable, disable, audit, svms 
summary: 'Puede habilitar o deshabilitar la auditoría en máquinas virtuales de almacenamiento (SVM). Puede que desee detener temporalmente la auditoría de archivos y directorios desactivando la auditoría. Puede habilitar la auditoría en cualquier momento (si existe una configuración de auditoría).' 
---
= Habilite y deshabilite la auditoría en las SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar o deshabilitar la auditoría en máquinas virtuales de almacenamiento (SVM). Puede que desee detener temporalmente la auditoría de archivos y directorios desactivando la auditoría. Puede habilitar la auditoría en cualquier momento (si existe una configuración de auditoría).

.Lo que necesitará
Antes de habilitar la auditoría en la SVM, debe haber ya una configuración de auditoría de la SVM.

.Acerca de esta tarea
La desactivación de la auditoría no elimina la configuración de auditoría.

.Pasos
. Ejecute el comando correspondiente:
+
[cols="35,65"]
|===


| Si desea que la auditoría sea... | Introduzca el comando... 


 a| 
Activado
 a| 
`vserver audit enable -vserver vserver_name`



 a| 
Deshabilitado
 a| 
`vserver audit disable -vserver vserver_name`

|===
. Compruebe que la auditoría está en el estado deseado:
+
`vserver audit show -vserver vserver_name`



.Ejemplos
En el siguiente ejemplo, se habilita la auditoría para SVM vs1:

[listing]
----
cluster1::> vserver audit enable -vserver vs1

cluster1::> vserver audit show -vserver vs1

                             Vserver: vs1
                      Auditing state: true
                Log Destination Path: /audit_log
       Categories of Events to Audit: file-ops, cifs-logon-logoff
                          Log Format: evtx
                 Log File Size Limit: 100MB
        Log Rotation Schedule: Month: -
  Log Rotation Schedule: Day of Week: -
          Log Rotation Schedule: Day: -
         Log Rotation Schedule: Hour: -
       Log Rotation Schedule: Minute: -
                  Rotation Schedules: -
            Log Files Rotation Limit: 10
----
En el siguiente ejemplo, se deshabilita la auditoría para SVM vs1:

[listing]
----
cluster1::> vserver audit disable -vserver vs1

                             Vserver: vs1
                      Auditing state: false
                Log Destination Path: /audit_log
       Categories of Events to Audit: file-ops, cifs-logon-logoff
                          Log Format: evtx
                 Log File Size Limit: 100MB
        Log Rotation Schedule: Month: -
  Log Rotation Schedule: Day of Week: -
          Log Rotation Schedule: Day: -
         Log Rotation Schedule: Hour: -
       Log Rotation Schedule: Minute: -
                  Rotation Schedules: -
            Log Files Rotation Limit: 10
----