---
permalink: nas-audit/enable-disable-fpolicy-policies-task.html 
sidebar: sidebar 
keywords: enable, disable, fpolicy policies 
summary: Es posible habilitar las políticas de FPolicy una vez completada la configuración. Al habilitar la directiva, se establece su prioridad e inicia la supervisión del acceso a los archivos de la directiva. Puede deshabilitar las políticas de FPolicy si desea detener la supervisión de acceso a los archivos para la política. 
---
= Habilite o deshabilite políticas de FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible habilitar las políticas de FPolicy una vez completada la configuración. Al habilitar la directiva, se establece su prioridad e inicia la supervisión del acceso a los archivos de la directiva. Puede deshabilitar las políticas de FPolicy si desea detener la supervisión de acceso a los archivos para la política.

.Antes de empezar
Antes de habilitar las políticas de FPolicy, debe completar la configuración de FPolicy.

.Acerca de esta tarea
* La prioridad se utiliza cuando se habilitan varias políticas en la máquina virtual de almacenamiento (SVM) y se ha suscrito más de una directiva al mismo evento de acceso a archivos.
* Las directivas que utilizan la configuración del motor nativo tienen una prioridad mayor que las directivas para cualquier otro motor, independientemente del número de secuencia que se les haya asignado al habilitar la política.
* Si desea cambiar la prioridad de una política de FPolicy, debe deshabilitar la política y volver a habilitarla mediante el nuevo número de secuencia.


.Paso
. Ejecute la acción adecuada:
+
[cols="35,65"]
|===


| Si desea... | Introduzca el siguiente comando... 


 a| 
Habilite una política de FPolicy
 a| 
`vserver fpolicy enable -vserver-name vserver_name -policy-name policy_name -sequence-number integer`



 a| 
Deshabilite una política de FPolicy
 a| 
`vserver fpolicy disable -vserver-name vserver_name -policy-name policy_name`

|===

