---
permalink: nas-audit/enable-audit-svm-task.html 
sidebar: sidebar 
keywords: enable, audit, svm 
summary: Después de terminar de configurar la configuración de auditoría, debe habilitar la auditoría en la máquina virtual de almacenamiento. 
---
= Habilite la auditoría en la SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de terminar de configurar la auditoría, debe habilitar la auditoría en la máquina virtual de almacenamiento (SVM).

.Antes de empezar
La configuración de auditoría de SVM ya debe existir.

.Acerca de esta tarea
Cuando se inicia por primera vez una configuración de descarte de ID de recuperación de desastres de SVM (una vez finalizada la inicialización de SnapMirror) y la SVM tiene una configuración de auditoría, ONTAP deshabilita automáticamente la configuración de auditoría. La auditoría se deshabilita en la SVM de solo lectura para evitar que los volúmenes provisionales se llenen. Solo puede habilitar la auditoría después de que se rompa la relación de SnapMirror y de que la SVM sea de lectura y escritura.

.Pasos
. Habilitar la auditoría en la SVM:
+
`vserver audit enable -vserver vserver_name`

+
`vserver audit enable -vserver vs1`



.Información relacionada
* link:create-auditing-config-task.html["Cree la configuración de auditoría"]
* link:verify-auditing-config-task.html["Compruebe la configuración de auditoría"]

