---
permalink: nas-audit/fpolicy-services-svm-namespaces-concept.html 
sidebar: sidebar 
keywords: fpolicy, services, work, svm, namespaces 
summary: 'ONTAP proporciona un espacio de nombres de máquina virtual de almacenamiento unificado (SVM). Los volúmenes del clúster se unen entre sí por uniones para proporcionar un único sistema de archivos lógico. El servidor FPolicy conoce la topología de espacio de nombres y proporciona servicios FPolicy en todo el espacio de nombres.' 
---
= Cómo funcionan los servicios de FPolicy en espacios de nombres de SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP proporciona un espacio de nombres de máquina virtual de almacenamiento unificado (SVM). Los volúmenes del clúster se unen entre sí por uniones para proporcionar un único sistema de archivos lógico. El servidor FPolicy conoce la topología de espacio de nombres y proporciona servicios FPolicy en todo el espacio de nombres.

El espacio de nombres es específico de la SVM y está contenido en ella; por lo tanto, solo se puede ver el espacio de nombres desde el contexto de la SVM. Los espacios de nombres tienen las siguientes características:

* Existe un espacio de nombres único en cada SVM, donde la raíz del espacio de nombres es el volumen raíz, representado en el espacio de nombres como barra diagonal (/).
* Todos los demás volúmenes tienen puntos de unión por debajo de la raíz (/).
* Las uniones del volumen son transparentes para los clientes.
* Una única exportación de NFS puede proporcionar acceso al espacio de nombres completo; de lo contrario, las políticas de exportación pueden exportar volúmenes específicos.
* Los recursos compartidos de SMB se pueden crear en el volumen o en qtrees dentro del volumen, o en cualquier directorio dentro del espacio de nombres.
* La arquitectura de espacio de nombres es flexible.
+
A continuación se muestran ejemplos de arquitecturas de espacios de nombres típicas:

+
** Un espacio de nombres con una única sucursal fuera de la raíz
** Un espacio de nombres con varias sucursales fuera de la raíz
** Un espacio de nombres con varios volúmenes sin ramificar de la raíz



