---
permalink: nas-audit/fpolicy-scope-config-native-engine-concept.html 
sidebar: sidebar 
keywords: requirement, fpolicy, scope, configurations, policy, native engine 
summary: Si configura la política de FPolicy para utilizar el motor nativo, hay un requisito específico para definir el ámbito de FPolicy configurado para la política. 
---
= Requisito para las configuraciones de alcance de FPolicy si la política de FPolicy utiliza el motor nativo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si configura la política de FPolicy para utilizar el motor nativo, hay un requisito específico para definir el ámbito de FPolicy configurado para la política.

El alcance de FPolicy define los límites en los que se aplica la política de FPolicy, por ejemplo, si se aplica a volúmenes o recursos compartidos especificados. Hay una serie de parámetros que restringen aún más el ámbito al que se aplica la política de FPolicy. Uno de estos parámetros, `-is-file-extension-check-on-directories-enabled`, especifica si se comprueban las extensiones de archivo en los directorios. El valor predeterminado es `false`, lo que significa que las extensiones de archivo de los directorios no están marcadas.

Cuando se habilita una política de FPolicy que utilice el motor nativo en un recurso compartido o volumen y en la `-is-file-extension-check-on-directories-enabled` el parámetro se establece en `false` para el ámbito de la directiva, se deniega el acceso al directorio. Con esta configuración, dado que las extensiones de archivo no se comprueban en busca de directorios, cualquier operación de directorio se deniega si está dentro del ámbito de la directiva.

Para garantizar que el acceso al directorio se realice correctamente al utilizar el motor nativo, debe configurar el `-is-file-extension-check-on-directories-enabled parameter` para `true` al crear el ámbito.

Con este parámetro establecido en `true`, Las comprobaciones de extensión se realizan para las operaciones de directorio y la decisión de permitir o denegar el acceso se toma en función de las extensiones incluidas o excluidas en la configuración del ámbito de FPolicy.
