---
permalink: nas-audit/fpolicy-policy-worksheet-reference.html 
sidebar: sidebar 
keywords: complete, fpolicy, policy, worksheet 
summary: Puede utilizar esta hoja de trabajo para registrar los valores que necesita durante el proceso de configuración de directivas de FPolicy. 
---
= Complete la hoja de trabajo de la política de FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar esta hoja de trabajo para registrar los valores que necesita durante el proceso de configuración de directivas de FPolicy. Debe registrar si desea incluir cada configuración de parámetros en la configuración de políticas de FPolicy y, a continuación, registrar el valor para los parámetros que desea incluir.

[cols="50,25,25"]
|===


| Tipo de información | Incluya | Sus valores 


 a| 
El nombre de la máquina virtual de almacenamiento (SVM)
 a| 
Sí
 a| 



 a| 
Nombre de la política
 a| 
Sí
 a| 



 a| 
Nombres de eventos
 a| 
Sí
 a| 



 a| 
Almacenamiento persistente
 a| 
 a| 



 a| 
Nombre del motor externo
 a| 
 a| 



 a| 
¿Es obligatorio realizar pruebas de detección?
 a| 
 a| 



 a| 
Permitir acceso privilegiado
 a| 
 a| 



 a| 
Nombre de usuario privilegiado
 a| 
 a| 



 a| 
¿Está habilitada la lectura PassThrough?
 a| 
 a| 

|===