---
permalink: nas-audit/fpolicy-scope-config-native-engine-concept.html 
sidebar: sidebar 
keywords: requirement, fpolicy, scope, configurations, policy, native engine 
summary: Si configura la política de FPolicy para utilizar el motor nativo, hay un requisito específico para definir el ámbito de FPolicy configurado para la política. 
---
= Requisito para las configuraciones del alcance de FPolicy de ONTAP si la política de FPolicy utiliza el motor nativo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si configura la política de FPolicy para utilizar el motor nativo, hay un requisito específico para definir el ámbito de FPolicy configurado para la política.

El alcance de FPolicy define los límites en los que se aplica la política de FPolicy, por ejemplo, si se aplica a volúmenes o recursos compartidos especificados. Hay una serie de parámetros que restringen aún más el ámbito al que se aplica la política de FPolicy. Uno de estos parámetros `-is-file-extension-check-on-directories-enabled`, , especifica si se deben comprobar las extensiones de archivo en los directorios. El valor por defecto es `false`, lo que significa que no se comprueban las extensiones de archivo de los directorios.

Cuando se habilita una política de FPolicy que utiliza el motor nativo en un recurso compartido o volumen y el `-is-file-extension-check-on-directories-enabled` parámetro se establece en `false` para el ámbito de la política, se deniega el acceso a directorios. Con esta configuración, dado que las extensiones de archivo no se comprueban en busca de directorios, cualquier operación de directorio se deniega si está dentro del ámbito de la directiva.

Para garantizar que el acceso al directorio se realice correctamente al utilizar el motor nativo, debe definir el `-is-file-extension-check-on-directories-enabled parameter` en `true` al crear el ámbito.

Con este parámetro definido en `true`, se realizan comprobaciones de extensión para las operaciones de directorio y la decisión de permitir o denegar el acceso se toma en función de las extensiones incluidas o excluidas en la configuración de ámbito de FPolicy.
