---
permalink: nas-audit/fpolicy-credentials-privileged-data-access-concept.html 
sidebar: sidebar 
keywords: fpolicy, connection, credentials, privileged data access channels 
summary: El servidor FPolicy realiza conexiones de acceso a datos con privilegios a nodos del clúster mediante una credencial de usuario de Windows específica que se guarda con la configuración de FPolicy. SMB es el único protocolo compatible para hacer una conexión con un canal de acceso a datos privilegiado. 
---
= Cómo se utilizan las credenciales de conexión de FPolicy con canales de acceso a datos con privilegios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El servidor FPolicy realiza conexiones de acceso a datos con privilegios a nodos del clúster mediante una credencial de usuario de Windows específica que se guarda con la configuración de FPolicy. SMB es el único protocolo compatible para hacer una conexión con un canal de acceso a datos privilegiado.

Si el servidor FPolicy requiere acceso a datos con privilegios, deben cumplirse las siguientes condiciones:

* Debe habilitarse una licencia para SMB en el clúster.
* El servidor FPolicy debe ejecutarse con las credenciales configuradas en la configuración de FPolicy.


Al realizar una conexión de canal de datos, FPolicy utiliza la credencial para el nombre de usuario de Windows especificado. El acceso a los datos se realiza a través del recurso compartido ONTAP_ADMIN$ del administrador.
