---
permalink: nas-audit/fpolicy-external-fpolicy-servers-concept.html 
sidebar: sidebar 
keywords: fpolicy, works, external fpolicy servers 
summary: 'Una vez que se configura y se habilita FPolicy en la máquina virtual de almacenamiento (SVM), FPolicy se ejecuta en todos los nodos en los que participa la SVM. FPolicy es responsable de establecer y mantener conexiones con servidores FPolicy externos (servidores FPolicy), para el procesamiento de notificaciones y para gestionar mensajes de notificación hacia y desde los servidores FPolicy.' 
---
= Cómo funciona FPolicy con información general sobre servidores de FPolicy externos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una vez que se configura y se habilita FPolicy en la máquina virtual de almacenamiento (SVM), FPolicy se ejecuta en todos los nodos en los que participa la SVM. FPolicy es responsable de establecer y mantener conexiones con servidores FPolicy externos (servidores FPolicy), para el procesamiento de notificaciones y para gestionar mensajes de notificación hacia y desde los servidores FPolicy.

Además, como parte de la gestión de conexiones, FPolicy tiene las siguientes responsabilidades:

* Garantiza que la notificación de archivo fluya a través del LIF correcto hacia el servidor FPolicy.
* Garantiza que cuando varios servidores FPolicy están asociados a una política, el equilibrio de carga se lleva a cabo al enviar notificaciones a los servidores de FPolicy.
* Intenta restablecer la conexión cuando se interrumpe una conexión con un servidor FPolicy.
* Envía las notificaciones a los servidores de FPolicy a través de una sesión autenticada.
* Gestiona la conexión de datos de lectura directa establecida por el servidor FPolicy para atender las solicitudes del cliente cuando está habilitada la lectura de pasarela.

