---
permalink: nas-audit/interpret-security-trace-results-concept.html 
sidebar: sidebar 
keywords: interpret, security trace, results 
summary: Los resultados del seguimiento de seguridad proporcionan el motivo por el que se permitía o denegaba una solicitud. Salida muestra el resultado como una combinación de la razón por la que se permite o deniega el acceso y la ubicación dentro de la ruta de comprobación de acceso en la que se permite o se deniega el acceso. Puede utilizar los resultados para aislar e identificar por qué se permiten o no acciones. 
---
= Interpretar los resultados de las trazas de seguridad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los resultados del seguimiento de seguridad proporcionan el motivo por el que se permitía o denegaba una solicitud. Salida muestra el resultado como una combinación de la razón por la que se permite o deniega el acceso y la ubicación dentro de la ruta de comprobación de acceso en la que se permite o se deniega el acceso. Puede utilizar los resultados para aislar e identificar por qué se permiten o no acciones.



== Búsqueda de información acerca de las listas de tipos de resultados y detalles de filtro

Puede encontrar las listas de tipos de resultados y los detalles de filtro que se pueden incluir en los resultados del rastreo de seguridad en el `vserver security trace trace-result show` comando. Obtenga más información sobre `vserver security trace trace-result show` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-security-trace-trace-result-show.html["Referencia de comandos del ONTAP"^].

.Ejemplo de salida del `Reason` campo en un `Allow` tipo de resultado
A continuación se muestra un ejemplo de la salida del `Reason` campo que aparece en el registro de resultados de rastreo en un `Allow` tipo de resultado:

[listing]
----
Access is allowed because SMB implicit permission grants requested
access while opening existing file or directory.
----
[listing]
----
Access is allowed because NFS implicit permission grants requested
access while opening existing file or directory.
----
.Ejemplo de salida del `Reason` campo en un `Allow` tipo de resultado
A continuación se muestra un ejemplo de la salida del `Reason` campo que aparece en el registro de resultados de rastreo en un `Deny` tipo de resultado:

[listing]
----
Access is denied. The requested permissions are not granted by the
ACE while checking for child-delete access on the parent.
----
.Ejemplo de salida del `Filter details` campo
A continuación se muestra un ejemplo de la salida del `Filter details` campo del registro de resultados de rastreo, que muestra el estilo de seguridad efectivo del sistema de archivos que contiene archivos y carpetas que coinciden con los criterios de filtro:

[listing]
----
Security Style: MIXED and ACL
----