---
permalink: nas-audit/manage-file-share-event-concept.html 
sidebar: sidebar 
keywords: manage, file-share, event 
summary: 'Cuando se configura un evento de recurso compartido de archivos para una máquina virtual de almacenamiento (SVM) y se habilita una auditoría, se generan eventos de auditoría. Los eventos de uso compartido de archivos se generan cuando se modifica el recurso compartido de red CIFS mediante comandos relacionados con los recursos compartidos de Vserver cifs.' 
---
= Gestione eventos de ONTAP de recursos compartidos de archivos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se configura un evento de recurso compartido de archivos para una máquina virtual de almacenamiento (SVM) y se habilita una auditoría, se generan eventos de auditoría. Los eventos de uso compartido de archivos se generan cuando se modifica el recurso compartido de red SMB mediante `vserver cifs share` comandos relacionados.

Los eventos de uso compartido de archivos con los id de evento 5142, 5143 y 5144 se generan cuando se añade, se modifica o se elimina un recurso compartido de red de SMB para la SVM. La configuración de recursos compartidos de red de SMB se modifica con `cifs share access control create|modify|delete` los comandos.

En el siguiente ejemplo, se muestra un evento de recurso compartido de archivos con el ID 5143 que se genera cuando se crea un objeto compartido denominado 'audit_dest':

[listing]
----
netapp-clus1::*> cifs share create -share-name audit_dest -path /audit_dest
- System
  - Provider
   [ Name]  NetApp-Security-Auditing
   [ Guid]  {3CB2A168-FE19-4A4E-BDAD-DCF422F13473}
   EventID 5142
   EventName Share Object Added
   ...
   ...
  ShareName audit_dest
  SharePath /audit_dest
  ShareProperties oplocks;browsable;changenotify;show-previous-versions;
  SD O:BAG:S-1-5-21-2447422786-1297661003-4197201688-513D:(A;;FA;;;WD)
----