---
permalink: nas-audit/manage-user-account-event-concept.html 
sidebar: sidebar 
keywords: manage, user-account, event 
summary: 'Cuando se configura un evento de cuenta de usuario para una máquina virtual de almacenamiento (SVM) y se habilita una auditoría, se generan eventos de auditoría.' 
---
= Gestione eventos de ONTAP de la cuenta de usuario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se configura un evento de cuenta de usuario para una máquina virtual de almacenamiento (SVM) y se habilita una auditoría, se generan eventos de auditoría.

Los eventos de cuenta de usuario con los id de evento 4720, 4722, 4724, 4725, 4726, 4738, y 4781 se generan cuando se crea o se elimina un usuario local de SMB o NFS del sistema, se habilita la cuenta de usuario local, se deshabilita o se modifica, y se restablece o se cambia la contraseña de usuario local de SMB. Los eventos de la cuenta de usuario se generan cuando se modifica una cuenta de usuario mediante `vserver cifs users-and-groups _<local user>_` y.. `vserver services name-service _<unix user>_` comandos.

En el siguiente ejemplo, se muestra un evento de cuenta de usuario con el ID 4720 generado cuando se crea un usuario de SMB local:

[listing]
----
netapp-clus1::*> vserver cifs users-and-groups local-user create -user-name testuser -is-account-disabled false -vserver vserver_1
Enter the password:
Confirm the password:

- System
  - Provider
   [ Name]  NetApp-Security-Auditing
   [ Guid]  {3CB2A168-FE19-4A4E-BDAD-DCF422F13473}
   EventID 4720
   EventName Local Cifs User Created
   ...
   ...
  TargetUserName testuser
  TargetDomainName NETAPP-CLUS1
  TargetSid S-1-5-21-2447422786-1297661003-4197201688-1003
  TargetType CIFS
  DisplayName testuser
  PasswordLastSet 1472662216
  AccountExpires NO
  PrimaryGroupId 513
  UserAccountControl %%0200
  SidHistory ~
  PrivilegeList ~
----
En el siguiente ejemplo se muestra un evento de cuenta de usuario con el ID 4781 generado, cuando se cambia el nombre de usuario de SMB local creado en el ejemplo anterior:

[listing]
----
 netapp-clus1::*> vserver cifs users-and-groups local-user rename -user-name testuser -new-user-name testuser1
- System
  - Provider
   [ Name]  NetApp-Security-Auditing
   [ Guid]  {3CB2A168-FE19-4A4E-BDAD-DCF422F13473}
   EventID 4781
   EventName Local Cifs User Renamed
   ...
   ...
  OldTargetUserName testuser
  NewTargetUserName testuser1
  TargetDomainName NETAPP-CLUS1
  TargetSid S-1-5-21-2447422786-1297661003-4197201688-1000
  TargetType CIFS
  SidHistory ~
  PrivilegeList ~
----