---
permalink: nas-audit/manual-rotate-audit-event-logs-task.html 
sidebar: sidebar 
keywords: manually, rotate, audit event logs 
summary: 'Para poder ver los registros de eventos de auditoría, los registros deben convertirse en formatos legibles por el usuario. Si desea ver los registros de eventos de una máquina virtual de almacenamiento (SVM) específica antes de que ONTAP gire automáticamente el registro, puede rotar manualmente los registros de eventos de auditoría en una SVM.' 
---
= Gire manualmente los registros de eventos de auditoría
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para poder ver los registros de eventos de auditoría, los registros deben convertirse en formatos legibles por el usuario. Si desea ver los registros de eventos de una máquina virtual de almacenamiento (SVM) específica antes de que ONTAP gire automáticamente el registro, puede rotar manualmente los registros de eventos de auditoría en una SVM.

.Paso
. Gire los registros de eventos de auditoría mediante `vserver audit rotate-log` comando.
+
`vserver audit rotate-log -vserver vs1`

+
El registro de eventos de auditoría se guarda en el directorio del registro de eventos de auditoría de SVM con el formato especificado por la configuración de auditoría (`XML` o. `EVTX`), y se puede ver utilizando la aplicación apropiada.


