---
permalink: nas-audit/persistent-stores.html 
sidebar: sidebar 
keywords: overview, persistent store, fpolicy 
summary: A partir de ONTAP 9.14.1, FPolicy permite configurar un almacén persistente para capturar eventos de acceso a archivos para políticas asíncronas no obligatorias en la SVM. Los almacenes persistentes pueden ayudar a desacoplar el procesamiento de I/O del cliente del procesamiento de notificaciones de FPolicy para reducir la latencia del cliente. No se admiten configuraciones obligatorias síncronas y asíncronas. 
---
= Almacenes persistentes de ONTAP FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los almacenes persistentes pueden ayudar a desacoplar el procesamiento de I/O del cliente del procesamiento de notificaciones de FPolicy para reducir la latencia del cliente. A partir de ONTAP 9.14.1, puede configurar un almacén persistente de FPolicy para capturar eventos de acceso a archivos para políticas asíncronas no obligatorias en la SVM. No se admiten las configuraciones síncronas (obligatorias o no obligatorias) y asíncronas obligatorias.

Esta función solo está disponible en el modo externo de FPolicy. La aplicación asociada que utilice necesita admitir esta función. Debe trabajar con su partner para garantizar que esta configuración de FPolicy sea compatible.

A partir de ONTAP 9.15.1, se simplifica la configuración de almacén persistente de FPolicy. El `persistent-store create` comando automatiza la creación de volúmenes para la SVM y configura el volumen con prácticas recomendadas de almacenamiento persistente.

Para obtener más información sobre las mejores prácticas de almacén persistente, consulte link:requirements-best-practices-fpolicy-concept.html["Requisitos, consideraciones y prácticas recomendadas para configurar FPolicy"].

Para obtener información sobre cómo agregar almacenes persistentes, consulte link:create-persistent-stores.html["Crear almacenes persistentes"].
