---
permalink: nas-audit/supported-file-operation-filter-fpolicy-nfsv3-concept.html 
sidebar: sidebar 
keywords: ontap 9, supported file operation, filter combinations, fpolicy, monitor, nfsv3 
summary: Cuando configura su evento de FPolicy, debe tener en cuenta que solo ciertas combinaciones de operaciones y filtros son compatibles para supervisar las operaciones de acceso a archivos NFSv3. 
---
= Operaciones de archivos admitidas y combinaciones de filtros que FPolicy puede supervisar para NFSv3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando configura su evento de FPolicy, debe tener en cuenta que solo ciertas combinaciones de operaciones y filtros son compatibles para supervisar las operaciones de acceso a archivos NFSv3.

La lista de operaciones de archivos y combinaciones de filtros admitidas para la supervisión de FPolicy de los eventos de acceso a archivos NFSv3 se proporciona en la siguiente tabla:

[cols="30,70"]
|===


| Operaciones de archivos admitidas | Filtros compatibles 


 a| 
cree
 a| 
bit sin conexión



 a| 
create_dir
 a| 
Actualmente no hay ningún filtro compatible con esta operación de archivo.



 a| 
eliminar
 a| 
bit sin conexión



 a| 
delete_dir
 a| 
Actualmente no hay ningún filtro compatible con esta operación de archivo.



 a| 
enlace
 a| 
bit sin conexión



 a| 
búsqueda
 a| 
bit sin conexión, exclude-dir



 a| 
lea
 a| 
bit sin conexión, primera lectura



 a| 
escritura
 a| 
sin conexión-bit, primera escritura, escritura-con-cambio de tamaño



 a| 
cambiar el nombre
 a| 
bit sin conexión



 a| 
dir_renombrar
 a| 
Actualmente no hay ningún filtro compatible con esta operación de archivo.



 a| 
setattr
 a| 
offline-bit, setattr_with_owner_change, setattr_with_group_change, setattr_with_mode_change, setattr_with_modify_time_change, setattr_with_access_time_change, setattr_with_size_change, exclude_directory



 a| 
enlace simbólico
 a| 
bit sin conexión

|===
A partir de ONTAP 9.13.1, los usuarios pueden recibir notificaciones por operaciones de archivos fallidas debido a la falta de permisos. En la siguiente tabla se proporciona la lista de combinaciones de acceso admitido denegado y filtros para la supervisión de FPolicy de eventos de acceso a archivos NFSv3:

[cols="30,70"]
|===


| Se admite la operación de archivo denegado de acceso | Filtros compatibles 


 a| 
acceso
 a| 
NA



 a| 
cree
 a| 
NA



 a| 
create_dir
 a| 
NA



 a| 
eliminar
 a| 
NA



 a| 
delete_dir
 a| 
NA



 a| 
enlace
 a| 
NA



 a| 
lea
 a| 
NA



 a| 
cambiar el nombre
 a| 
NA



 a| 
dir_renombrar
 a| 
NA



 a| 
setattr
 a| 
NA



 a| 
escritura
 a| 
NA

|===