---
permalink: nas-audit/supported-file-operation-filter-fpolicy-smb-concept.html 
sidebar: sidebar 
keywords: list, supported file operation, filter combinations, fpolicy, monitor, smb 
summary: Al configurar el evento de FPolicy, debe tener en cuenta que solo ciertas combinaciones de operaciones y filtros de archivos son compatibles para supervisar las operaciones de acceso a archivos SMB. 
---
= Combinaciones de filtros y operaciones de archivos compatibles que ONTAP FPolicy supervisa para SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al configurar el evento de FPolicy, debe tener en cuenta que solo ciertas combinaciones de operaciones y filtros de archivos son compatibles para supervisar las operaciones de acceso a archivos SMB.

La lista de operaciones de archivos y combinaciones de filtros admitidas para la supervisión de FPolicy de los eventos de acceso a archivos SMB se proporciona en la siguiente tabla:

[cols="30,70"]
|===


| Operaciones de archivos admitidas | Filtros compatibles 


 a| 
cierre
 a| 
anuncios de monitor, bit sin conexión, primer plano con modificación, primer plano sin modificación, primer plano con lectura, excluir directorio



 a| 
cree
 a| 
anuncios de monitores, bits sin conexión



 a| 
create_dir
 a| 
Actualmente no hay ningún filtro compatible con esta operación de archivo.



 a| 
eliminar
 a| 
anuncios de monitores, bits sin conexión



 a| 
delete_dir
 a| 
Actualmente no hay ningún filtro compatible con esta operación de archivo.



 a| 
getattr
 a| 
bit sin conexión, exclude-dir



 a| 
abierto
 a| 
anuncios de monitores, bits sin conexión, intento de borrado, intento de escritura abierta, dir de exclusión



 a| 
lea
 a| 
anuncios de monitores, bits sin conexión, primera lectura



 a| 
escritura
 a| 
anuncios de monitor, bits sin conexión, primera escritura, escritura con cambio de tamaño



 a| 
cambiar el nombre
 a| 
anuncios de monitores, bits sin conexión



 a| 
dir_renombrar
 a| 
Actualmente no hay ningún filtro compatible con esta operación de archivo.



 a| 
setattr
 a| 
anuncios de monitor, offline-bit, setattr_with_owner_change, setattr_with_group_change, setattr_with_mode_change, setattr_with_sacl_change, setattr_with_dacl_change, setattr_with_modify_time_change, setattr_with_access_time_change, setattr_with_time_change, setattr_with_size_change, setattr_with_asition_size_change, exclude_directory

|===
A partir de ONTAP 9.13.1, los usuarios pueden recibir notificaciones por operaciones de archivos fallidas debido a la falta de permisos. En la siguiente tabla se proporciona la lista de combinaciones de acceso admitido denegado y filtros para la supervisión de FPolicy de los eventos de acceso a archivos SMB:

[cols="30,70"]
|===


| Se admite la operación de archivo denegado de acceso | Filtros compatibles 


 a| 
abierto
 a| 
NA

|===