---
permalink: nas-audit/supported-file-operation-filter-fpolicy-nfsv4-concept.html 
sidebar: sidebar 
keywords: ontap 9, supported file operation, filter combinations, fpolicy, monitor, nfsv4 
summary: Al configurar el evento de FPolicy, tiene que tener en cuenta que solo admite ciertas combinaciones de operaciones y filtros para supervisar las operaciones de acceso a archivos NFSv4. 
---
= Combinaciones de operación de archivos y filtro admitidas que FPolicy puede supervisar para NFSv4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al configurar el evento de FPolicy, tiene que tener en cuenta que solo admite ciertas combinaciones de operaciones y filtros para supervisar las operaciones de acceso a archivos NFSv4.

La lista de operaciones de archivos y combinaciones de filtros admitidas para la supervisión de FPolicy de los eventos de acceso a archivos NFSv4 se proporciona en la siguiente tabla:

[cols="30,70"]
|===


| Operaciones de archivos admitidas | Filtros compatibles 


 a| 
cierre
 a| 
fuera de línea, directorio de exclusión



 a| 
cree
 a| 
bit sin conexión



 a| 
create_dir
 a| 
Actualmente no hay ningún filtro compatible con esta operación de archivo.



 a| 
eliminar
 a| 
bit sin conexión



 a| 
delete_dir
 a| 
Actualmente no hay ningún filtro compatible con esta operación de archivo.



 a| 
getattr
 a| 
fuera de línea, directorio de exclusión



 a| 
enlace
 a| 
bit sin conexión



 a| 
búsqueda
 a| 
fuera de línea, directorio de exclusión



 a| 
abierto
 a| 
fuera de línea, directorio de exclusión



 a| 
lea
 a| 
bit sin conexión, primera lectura



 a| 
escritura
 a| 
sin conexión-bit, primera escritura, escritura-con-cambio de tamaño



 a| 
cambiar el nombre
 a| 
bit sin conexión



 a| 
dir_renombrar
 a| 
Actualmente no hay ningún filtro compatible con esta operación de archivo.



 a| 
setattr
 a| 
offline-bit, setattr_with_owner_change, setattr_with_group_change, setattr_with_mode_change, setattr_with_sacl_change, setattr_with_dacl_change, setattr_with_modify_time_change, setattr_with_access_time_change, setattr_with_size_change, exclude_directory



 a| 
enlace simbólico
 a| 
bit sin conexión

|===