---
permalink: san-config/commands-manage-fc-adapters-reference.html 
sidebar: sidebar 
keywords: commands, managing, fc adapters 
summary: Puede usar comandos FC para gestionar adaptadores de destino FC, adaptadores de iniciador FC y adaptadores de FC integrados para su controladora de almacenamiento. Los mismos comandos se utilizan para gestionar adaptadores de FC para el protocolo FC y el protocolo FC-NVMe. 
---
= Comandos para gestionar adaptadores de FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar comandos FC para gestionar adaptadores de destino FC, adaptadores de iniciador FC y adaptadores de FC integrados para su controladora de almacenamiento. Los mismos comandos se utilizan para gestionar adaptadores de FC para el protocolo FC y el protocolo FC-NVMe.

Los comandos de adaptador del iniciador de FC solo funcionan en el nivel del nodo. Debe utilizar el `run -node _node_name_` Antes de poder utilizar los comandos del adaptador del iniciador de FC.



== Comandos para gestionar los adaptadores de destino de FC

[cols="2*"]
|===
| Si desea... | Se usa este comando... 


 a| 
Muestra información del adaptador de FC en un nodo
 a| 
`network fcp adapter show`



 a| 
Modifique los parámetros del adaptador de destino FC
 a| 
`network fcp adapter modify`



 a| 
Muestra información sobre el tráfico del protocolo FC
 a| 
`run -node _node_name_ sysstat -f`



 a| 
Muestra el tiempo que se ha ejecutado el protocolo FC
 a| 
`run -node _node_name_ uptime`



 a| 
Mostrar la configuración y el estado del adaptador
 a| 
`run -node _node_name_ sysconfig -v _adapter_`



 a| 
Compruebe qué tarjetas de expansión están instaladas y si hay algún error de configuración
 a| 
`run -node _node_name_ sysconfig -ac`



 a| 
Ver una página de manual de un comando
 a| 
`man command_name`

|===


== Comandos para gestionar los adaptadores de iniciador de FC

[cols="2*"]
|===
| Si desea... | Se usa este comando... 


 a| 
Muestra información de todos los iniciadores y sus adaptadores en un nodo
 a| 
`run -node _node_name_ storage show adapter`



 a| 
Mostrar la configuración y el estado del adaptador
 a| 
`run -node _node_name_ sysconfig -v _adapter_`



 a| 
Compruebe qué tarjetas de expansión están instaladas y si hay algún error de configuración
 a| 
`run -node _node_name_ sysconfig -ac`

|===


== Comandos para gestionar los adaptadores de FC internos

[cols="2*"]
|===
| Si desea... | Se usa este comando... 


 a| 
Muestra el estado de los puertos FC internos
 a| 
`system node hardware unified-connect show`

|===
Obtenga más información sobre los comandos descritos en este procedimiento en el link:https://docs.netapp.com/us-en/ontap-cli/["Referencia de comandos de la ONTAP"^].
