---
permalink: san-config/determine-supported-nodes-task.html 
sidebar: sidebar 
keywords: determine, number, supported, nodes, san configurations 
summary: El número de nodos por clúster que admite ONTAP varía en función de la versión de ONTAP, los modelos de controladora de almacenamiento del clúster y el protocolo de los nodos del clúster. 
---
= Determinar el número de nodos compatibles para las configuraciones SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El número de nodos por clúster que admite ONTAP varía en función de la versión de ONTAP, los modelos de controladora de almacenamiento del clúster y el protocolo de los nodos del clúster.

.Acerca de esta tarea
Si alguno de los nodos del clúster está configurado para FC, FC-NVMe, FCoE o iSCSI, ese clúster se limita a los límites de nodos SAN. Los límites de nodos basados en las controladoras de su clúster se enumeran en _Hardware Universe_.

.Pasos
. Vaya a. https://hwu.netapp.com["Hardware Universe de NetApp"^].
. Haga clic en *plataformas* en la parte superior izquierda (junto al botón *Inicio*) y seleccione el tipo de plataforma.
. Seleccione la casilla de verificación junto a su versión de ONTAP.
+
Se mostrará una nueva columna para que pueda elegir sus plataformas.

. Active las casillas junto a las plataformas utilizadas en su solución.
. Anule la selección de la casilla de verificación *Seleccionar todo* en la columna *Seleccionar las especificaciones*.
. Active la casilla de verificación *nodos máximos por clúster (NAS/SAN)*.
. Haga clic en *Mostrar resultados*.


.Información relacionada
https://hwu.netapp.com["Hardware Universe de NetApp"^]
