---
permalink: san-config/fc-config-concept.html 
sidebar: sidebar 
keywords: considerations, fc, configurations 
summary: Al configurar la configuración de FC, debe ser consciente de varios aspectos. 
---
= Consideraciones sobre la información general de las configuraciones de FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al configurar la configuración de FC, debe ser consciente de varios aspectos.

* Puede configurar su configuración FC con nodos únicos o pares de alta disponibilidad por medio de una estructura única o estructura múltiple.
* Debe configurar dos LIF de datos FC por nodo.
+
Esto genera redundancia y protege contra la pérdida de acceso a los datos.

* Debe configurar un LIF de gestión para cada máquina virtual de almacenamiento (SVM) compatible con SAN.
* Varios hosts y diferentes sistemas operativos, como Windows, Linux o UNIX, pueden acceder a la solución de almacenamiento al mismo tiempo.
+
Los hosts requieren que se instale y configure una solución multivía compatible. En la matriz de interoperabilidad, se pueden verificar los sistemas operativos y las soluciones multivía compatibles.

* ONTAP admite soluciones de uno, dos o varios nodos conectadas a varias estructuras DE almacenamiento físicamente independientes; se recomiendan un mínimo de dos para las soluciones SAN.
+
Esto proporciona redundancia en las capas de estructura y sistema de almacenamiento. La redundancia es especialmente importante, ya que estas capas suelen admitir muchos hosts.

* No se admite el uso de estructuras heterogéneas de switches FC, a excepción de los switches blade integrados.
+
Las excepciones específicas se enumeran en la matriz de interoperabilidad.

* Las estructuras en cascada, malla parcial, malla completa, núcleo-borde y director son métodos estándar en el sector para conectar switches FC a una estructura, y todos son compatibles.
+
Una estructura puede estar compuesta por uno o varios switches y las controladoras de almacenamiento se pueden conectar a varios switches.



.Información relacionada
https://["Herramienta de matriz de interoperabilidad de NetApp"^]
