---
permalink: san-config/fc-fcoe-supported-hop-counts.html 
sidebar: sidebar 
keywords: fcoe, supported, hop, count 
summary: 'El número máximo de saltos de Fibre Channel over Ethernet (FCoE) admitidos entre un host y el sistema de almacenamiento depende del proveedor de switches y de la compatibilidad del sistema de almacenamiento para las configuraciones FCoE.' 
---
= Número máximo de saltos de FC y FCoE admitidos en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los saltos son el número de switches presentes en la ruta que va del iniciador (host) al destino (sistema de almacenamiento). El número máximo de saltos de FC admitidos entre un host y el sistema de almacenamiento varía según el proveedor de switch.

La documentación de Cisco Systems también se refiere a este valor como el _diameter de LA estructura SAN_.

Para FCoE, puede tener switches FCoE conectados a switches FC. Para las conexiones FCoE integrales, los switches FCoE deben ejecutar una versión de firmware que admita enlaces entre switches Ethernet (ISL).

[cols="2*"]
|===
| Cambiar proveedor | Número de saltos admitidos 


 a| 
Brocade
 a| 
* 7 para FC
* 5 para FCoE




 a| 
Cisco
 a| 
* 7 para FC
* Hasta 3 switches pueden ser switches FCoE.


|===