---
permalink: san-config/fc-nvme-config-concept.html 
sidebar: sidebar 
keywords: considerations, fc-nvme, configurations 
summary: 'A partir de ONTAP 9.4, el protocolo de memoria no volátil rápida (NVMe) está disponible para entornos SAN. FC-NVMe permite ejecutar NVMe sobre una red FC existente con un sistema AFF. FC-NVMe utiliza la misma práctica de configuración física y división en zonas que las redes FC tradicionales pero permite un mayor ancho de banda, un aumento de IOPS y una latencia reducida que FC-SCSI.' 
---
= Consideraciones sobre las configuraciones FC-NVMe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9,4, el link:https://docs.netapp.com/us-en/ontap/san-admin/manage-nvme-concept.html["Memoria no volátil rápida (NVMe)"] el protocolo está disponible para los entornos SAN. FC-NVMe utiliza la misma práctica de configuración física y división en zonas que las redes FC tradicionales pero permite un mayor ancho de banda, un aumento de IOPS y una latencia reducida que FC-SCSI.

La compatibilidad con el protocolo NVMe-of varía según la plataforma y la configuración. Para obtener detalles sobre su configuración específica, consulte link:https://imt.netapp.com/matrix/["Herramienta de matriz de interoperabilidad de NetApp"].

Debe tener en cuenta lo siguiente al configurar FC-NVMe en el clúster.

* A partir de ONTAP 9.12.1, las configuraciones IP de MetroCluster de 4 nodos son compatibles con NVMe/FC.
+
** Las configuraciones de MetroCluster no son compatibles con NVMe/TCP.
** Las configuraciones de MetroCluster no son compatibles con NVMe antes de la versión 9.12.1.


* Puede configurar su configuración FC-NVMe con nodos únicos o pares de alta disponibilidad mediante una única estructura o estructura múltiple.
* FC-NVMe puede ser el único protocolo de datos en las LIF de datos.
* Debe configurar una LIF de gestión para cada SVM compatible con SAN.
* No se admite el uso de estructuras heterogéneas de switches FC, a excepción de los switches blade integrados.
+
Las excepciones específicas se enumeran en la link:https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^].

* Las estructuras en cascada, malla parcial, malla completa, núcleo-borde y director son métodos estándar en el sector para conectar switches FC a una estructura, y todos son compatibles.
+
Una estructura puede estar compuesta por uno o varios switches y las controladoras de almacenamiento se pueden conectar a varios switches.



.Información relacionada
* link:https://docs.netapp.com/us-en/ontap/nvme/support-limitations.html["Compatibilidad y limitaciones de NVMe"]
* http://www.netapp.com/us/media/tr-4684.pdf["Informe técnico de NetApp 4684: Implementación y configuración de San modernas con NVMe/FC"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/How_to_configure_and_Connect_SUSE_Enterprise_Linux_to_ONTAP_NVMe%2F%2FFC_namespaces["Cómo configurar y conectar SUSE Enterprise Linux en espacios de nombres ONTAP NVMe/FC"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Licensing_information_for_NVMe_protocol_on_ONTAP["Información de gestión de licencias para el protocolo NVMe en ONTAP"]

