---
permalink: san-config/fc-switch-config-limits-reference.html 
sidebar: sidebar 
keywords: fc, switch, configuration, limits 
summary: Los switches de Fibre Channel tienen límites máximos de configuración, incluyendo el número de inicios de sesión compatibles por puerto, grupo de puertos, blade y switch. Los proveedores de switch documentan sus propios límites. 
---
= Límites de configuración de switch de FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los switches de Fibre Channel tienen límites máximos de configuración, incluyendo el número de inicios de sesión compatibles por puerto, grupo de puertos, blade y switch. Los proveedores de switch documentan sus propios límites.

Cada interfaz lógica de FC (LIF) se registra en un puerto del switch de FC. El número total de inicios de sesión desde un único destino en el nodo es igual al número de LIF más un inicio de sesión para el puerto físico subyacente. No supere los límites de configuración del proveedor del switch para inicios de sesión u otros valores de configuración. Esto también contiene true para los iniciadores que se utilizan en el lado del host en entornos virtualizados con NPIV habilitado. No supere los límites de configuración del proveedor del switch para inicios de sesión para el destino o los iniciadores que se están utilizando en la solución.



== Límites del switch Brocade

Encontrará los límites de configuración de los switches Brocade en las _Brocade Scalability Guidelines_.



== Límites de switches de Cisco Systems

Puede encontrar los límites de configuración para switches de Cisco en la http://["Límites de configuración de Cisco"] Guía para su versión del software de switch de Cisco.
