---
permalink: san-config/fc-target-port-supported-speeds-reference.html 
sidebar: sidebar 
keywords: fc, target, port, supported, speeds 
summary: Los puertos de destino FC pueden configurarse para que funcionen a diferentes velocidades. Debe configurar la velocidad del puerto de destino para que coincida con la velocidad del dispositivo al que se conecta. Todos los puertos de destino utilizados por un host determinado deben configurarse con la misma velocidad. 
---
= Velocidades admitidas en el puerto de destino FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los puertos de destino FC pueden configurarse para que funcionen a diferentes velocidades. Debe configurar la velocidad del puerto de destino para que coincida con la velocidad del dispositivo al que se conecta. Todos los puertos de destino utilizados por un host determinado deben configurarse con la misma velocidad.

Los puertos de destino FC se pueden utilizar para las configuraciones FC-NVMe exactamente del mismo modo que se utilizan para las configuraciones FC.

Debe configurar la velocidad del puerto de destino para que coincida con la velocidad del dispositivo al que se conecta en vez de utilizar la autonegociación. Un puerto configurado para la autonegociación puede tardar más en volver a conectarse después de una toma de control/devolución u otra interrupción.

Puede configurar los puertos internos y los adaptadores de expansión para que se ejecuten a la velocidad siguiente. Cada controladora y puerto del adaptador de expansión se pueden configurar de forma individual para diferentes velocidades según sea necesario.

[cols="4*"]
|===
| Puertos de 4 GB | Puertos de 8 GB | Puertos de 16 GB | Puertos de 32 GB 


 a| 
* 4 GB
* 2 GB
* 1 GB

 a| 
* 8 GB
* 4 GB
* 2 GB

 a| 
* 16 GB
* 8 GB
* 4 GB

 a| 
* 32 GB
* 16 GB
* 8 GB


|===
[NOTE]
====
Los puertos UTA2 pueden utilizar un adaptador SFP+ de 8 GB para admitir velocidades de 8, 4 y 2 GB, si fuera necesario.

====