---
permalink: san-config/fcoe-initiator-target-combinations-reference.html 
sidebar: sidebar 
keywords: fcoe, initiator, target, combinations 
summary: Se admiten ciertas combinaciones de iniciadores y destinos FC tradicionales y FCoE. 
---
= ONTAP admitía combinaciones de iniciadores FCoE y puertos de destino
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se admiten ciertas combinaciones de iniciadores y destinos FC tradicionales y FCoE.



== Iniciadores FCoE

Es posible utilizar iniciadores de FCoE en equipos host con destinos FCoE y FC tradicionales en controladoras de almacenamiento. El iniciador FCoE del host debe conectarse a un switch FCoE DCB (Data Center Bridging); no se admite la conexión directa a un destino.

En la siguiente tabla se enumeran las combinaciones compatibles:

[cols="3*"]
|===
| Iniciador | Destino | Compatible? 


 a| 
FC
 a| 
FC
 a| 
Sí



 a| 
FC
 a| 
FCoE
 a| 
Sí



 a| 
FCoE
 a| 
FC
 a| 
Sí



 a| 
FCoE
 a| 
FCoE
 a| 
Sí

|===


== Destinos FCoE

Puede combinar puertos de destino FCoE con puertos FC de 4 GB, 8 GB o 16 GB en la controladora de almacenamiento, independientemente de si los puertos FC son adaptadores de destino adicionales o puertos integrados. Puede tener adaptadores de destino FCoE y FC en la misma controladora de almacenamiento.

[NOTE]
====
Aún se aplican las reglas para combinar los puertos FC internos y de ampliación.

====