---
permalink: san-config/fibre-channel-fcoe-zoning-concept.html 
sidebar: sidebar 
keywords: fibre, channel, fcoe zoning 
summary: Una zona FC, FC-NVMe o FCoE es una agrupación lógica de uno o varios puertos dentro de una estructura. Para que los dispositivos puedan verse entre sí, conectarse, crear sesiones entre sí y comunicarse, ambos puertos necesitan tener una pertenencia a una zona común. Se recomienda la división en zonas de un solo iniciador. 
---
= Información general sobre la división en zonas de Fibre Channel y FCoE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una zona FC, FC-NVMe o FCoE es una agrupación lógica de uno o varios puertos dentro de una estructura. Para que los dispositivos puedan verse entre sí, conectarse, crear sesiones entre sí y comunicarse, ambos puertos deben ser miembros de la misma zona.

La división en zonas aumenta la seguridad al limitar el acceso y la conectividad a los puntos finales que comparten una zona común. Los puertos que no están en la misma zona no pueden comunicarse entre sí. Esto reduce o elimina _crosstalk_ entre los HBA del iniciador. Si se producen problemas de conectividad, la división en zonas ayuda a aislar los problemas en un conjunto de puertos específico, lo que reduce el tiempo de resolución.

La división en zonas reduce el número de rutas disponibles a un puerto determinado y reduce el número de rutas entre un host y el sistema de almacenamiento. Por ejemplo, algunas soluciones multivía del SO del host tienen limitado el número de rutas que pueden gestionar. La división en zonas puede reducir el número de rutas visibles para el host, de modo que las rutas al host no superen el máximo permitido por el sistema operativo del host.



== División en zonas basada en World Wide Name

La división en zonas basada en nombre WWN especifica el nombre WWN de los miembros que se incluirán en la zona. Aunque es posible aplicar la división en zonas de nombre de nodo WWNN con algunos proveedores de switch, cuando se divide en zonas en ONTAP, debe utilizar la división en zonas de nombre de puerto WWPN.

Es necesario dividir en zonas de WWPN para definir correctamente un puerto específico y utilizar NPIV de forma efectiva. Los switches FC se deben dividir mediante los WWPN de las interfaces lógicas (LIF) de destino, no los WWPN de los puertos físicos del nodo. Los WWPN de los puertos físicos comienzan por «'50» y los WWPN de las LIF empiezan por «'20».

La división en zonas de nombres de puerto WWPN aporta flexibilidad porque el acceso no está determinado por el lugar físico de conexión entre el dispositivo y la estructura. Puede mover un cable de un puerto a otro sin tener que configurar las zonas de nuevo.
