---
permalink: san-config/individual-zones-reference.html 
sidebar: sidebar 
keywords: individual zones 
summary: En la configuración recomendada de la división por zonas, hay un iniciador de host por zona. La zona consta de un puerto de iniciador de host y uno o varios LIF de destino en los nodos de almacenamiento que proporcionan acceso a las LUN hasta el número deseado de rutas por destino. Esto significa que los hosts que acceden a los mismos nodos no pueden ver los puertos del otro, pero cada iniciador puede acceder a cualquier nodo. 
---
= Zonas individuales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En la configuración recomendada de la división por zonas, hay un iniciador de host por zona. La zona consta de un puerto de iniciador de host y uno o varios LIF de destino en los nodos de almacenamiento que proporcionan acceso a las LUN hasta el número deseado de rutas por destino. Esto significa que los hosts que acceden a los mismos nodos no pueden ver los puertos del otro, pero cada iniciador puede acceder a cualquier nodo.

Debería añadir todas las LIF de la máquina virtual de almacenamiento (SVM) a la zona con el iniciador del host. Esto le permite mover volúmenes o LUN sin editar sus zonas existentes ni crear zonas nuevas.

Para las rutas Fibre Channel a los nodos que ejecutan ONTAP, asegúrese de que sus switches se dividen mediante los WWPN de las interfaces lógicas (LIF) objetivo, no los WWPN de los puertos físicos en el nodo. Los WWPN de los puertos físicos comienzan por «'50» y los WWPN de las LIF empiezan por «'20».
