---
permalink: san-config/iscsi-config-concept.html 
sidebar: sidebar 
keywords: considerations, iscsi, configurations 
summary: Debe tener en cuenta varias cosas al configurar la configuración de iSCSI. 
---
= Consideraciones sobre la información general de las configuraciones de iSCSI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe tener en cuenta varias cosas al configurar la configuración de iSCSI.

* Puede configurar iSCSI con nodos individuales o con parejas de alta disponibilidad.
+
La conexión directa o el uso de switches Ethernet es compatible con la conectividad. Debe crear LIF para ambos tipos de conectividad

* Debe configurar un LIF de gestión para cada máquina virtual de almacenamiento (SVM) compatible con SAN.
* La asignación selectiva de LUN (SLM) limita las rutas que se utilizan para acceder a los LUN propiedad de un par de alta disponibilidad.
+
Este es el comportamiento predeterminado para las LUN creadas con versiones ONTAP.

* Las parejas DE ALTA DISPONIBILIDAD se definen como nodos de generación de informes para las rutas Active/Optimized y Active/no optimizadas que el host utilizará para acceder a las LUN mediante ALUA.
* Se recomienda que todas las SVM en configuraciones ISCSI tengan un mínimo de dos LIF por nodo en redes Ethernet independientes para proporcionar redundancia y MPIO en varias rutas.
* Debe crear una o varias rutas iSCSI desde cada nodo de una pareja de ha, utilizando interfaces lógicas (LIF) para permitir el acceso a las LUN a las que presta servicio el par de alta disponibilidad.
+
Si falla un nodo, los LIF no migran ni asumen las direcciones IP del nodo del compañero que ha fallado. En su lugar, el software MPIO, mediante ALUA en el host, es responsable de seleccionar las rutas adecuadas para el acceso de las LUN a través de LIF.

* Las VLAN ofrecen ventajas específicas, como mayor seguridad y fiabilidad de red mejorada que se recomienda aprovechar en iSCSI.

