---
permalink: san-config/manage-systems-fc-adapters-concept.html 
sidebar: sidebar 
keywords: manage, systems with fc adapters 
summary: Hay comandos disponibles para gestionar los adaptadores FC integrados y las tarjetas adaptadoras FC. Estos comandos se pueden utilizar para configurar el modo del adaptador, mostrar información del adaptador y cambiar la velocidad. 
---
= Información general sobre la gestión de sistemas con adaptadores de FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay comandos disponibles para gestionar los adaptadores FC integrados y las tarjetas adaptadoras FC. Estos comandos se pueden utilizar para configurar el modo del adaptador, mostrar información del adaptador y cambiar la velocidad.

La mayoría de los sistemas de almacenamiento tienen adaptadores FC integrados que se pueden configurar como iniciadores o destinos. También puede utilizar tarjetas adaptadoras de FC configuradas como iniciadores o destinos. Los iniciadores se conectan a las bandejas de discos del back-end y posiblemente a cabinas de almacenamiento externas (FlexArray). Los destinos se conectan solo a switches FC.  Tanto los puertos HBA de destino FC como la velocidad del puerto del switch deben configurarse con el mismo valor y no deben configurarse en modo automático.
