---
permalink: san-config/multipathing-software-required-concept.html 
sidebar: sidebar 
keywords: when, host, multipathing, software, required 
summary: 'Si hay más de una ruta desde las interfaces lógicas (LIF) de la máquina virtual de almacenamiento hasta la estructura, se requiere un software multivía. Se requiere un software multivía en el host siempre que el host pueda acceder a una LUN a través de más de una ruta.' 
---
= Cuando se requiere un software multivía para el host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si hay más de una ruta desde las interfaces lógicas (LIF) de la máquina virtual de almacenamiento hasta la estructura, se requiere un software multivía. Se requiere un software multivía en el host siempre que el host pueda acceder a una LUN a través de más de una ruta.

El software multivía presenta un disco único al sistema operativo para todas las rutas que se dirigen a una LUN. Sin un software multivía, el sistema operativo trataría cada una de las partes como un disco independiente, lo cual provocaría daños en los datos.

Se considera que su solución tiene varias rutas si dispone de alguna de las siguientes opciones:

* Un único puerto iniciador del host conectando varios LIF SAN en la SVM
* Varios puertos de iniciador conectando a un único LIF SAN en la SVM
* Varios puertos de iniciador conectando varios LIF SAN en la SVM


Se recomienda el software multivía en configuraciones de alta disponibilidad. Además de la asignación selectiva de LUN, se recomienda usar la división en zonas o los conjuntos de puertos de switch FC para limitar las rutas utilizadas para acceder a las LUN.

El software multivía también se conoce como software MPIO (I/o multivía).
