---
permalink: san-config/world-wide-name-based-zoning-concept.html 
sidebar: sidebar 
keywords: world, wide, name-based, zoning 
summary: La división en zonas basada en nombre WWN especifica el nombre WWN de los miembros que se incluirán en la zona. Al dividir en zonas en ONTAP, debe usar la división en zonas de nombre de puerto WWPN. 
---
= División en zonas basada en World Wide Name
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La división en zonas basada en nombre WWN especifica el nombre WWN de los miembros que se incluirán en la zona. Al dividir en zonas en ONTAP, debe usar la división en zonas de nombre de puerto WWPN.

La división en zonas de nombres de puerto WWPN aporta flexibilidad porque el acceso no está determinado por el lugar físico de conexión entre el dispositivo y la estructura. Puede mover un cable de un puerto a otro sin tener que configurar las zonas de nuevo.

Para las rutas Fibre Channel a controladoras de almacenamiento que ejecutan ONTAP, asegúrese de que sus switches se dividen mediante los WWPN de las interfaces lógicas (LIF) objetivo, no los WWPN de los puertos físicos en el nodo. Para obtener más información acerca de las LIF, consulte la _Guía de gestión de redes ONTAP_.

link:../networking/networking_reference.html["Gestión de redes"]
