---
permalink: san-config/zoning-restrictions-cisco-fc-fcoe-switches-reference.html 
sidebar: sidebar 
keywords: zoning, restrictions, for cisco, fc, fcoe, switches 
summary: Cuando se usan switches Fibre Channel y FCoE de Cisco, una única zona estructural no debe contener más de un LIF de destino para el mismo puerto físico. Si hay varias LIF en el mismo puerto en la misma zona, es posible que los puertos LIF no puedan recuperarse de una pérdida de conexión. 
---
= Restricciones de división en zonas para switches Cisco FC y FCoE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se usan switches Fibre Channel y FCoE de Cisco, una única zona estructural no debe contener más de un LIF de destino para el mismo puerto físico. Si hay varias LIF en el mismo puerto en la misma zona, es posible que los puertos LIF no puedan recuperarse de una pérdida de conexión.

Los switches FC normales se utilizan para el protocolo FC-NVMe exactamente del mismo modo que se utilizan para el protocolo FC.

* Varios LIF para los protocolos FC y FCoE, pueden compartir puertos físicos en un nodo siempre y cuando se encuentren en zonas diferentes.
* FC-NVMe y FCoE no pueden compartir el mismo puerto físico.
* FC y FC-NVMe pueden compartir el mismo puerto físico de 32 GB.
* Los switches FC y FCoE de Cisco requieren que cada LIF de un puerto dado esté en una zona separada de los otros LIF de ese puerto.
* Una sola zona puede tener tanto LIF FC como FCoE. Una zona puede contener un LIF de todos los puertos de destino del clúster, pero tenga cuidado de no superar los límites de ruta del host y verificar la configuración de SLM.
* Los LIF de diferentes puertos físicos pueden estar en la misma zona.
* Los switches de Cisco requieren que se separen las LIF.
+
Aunque no es necesario, se recomienda separar las LIF para todos los switches


