---
permalink: upgrade/concept_upgrade_requirements_for_snapmirror.html 
sidebar: sidebar 
keywords: ontap, upgrade, requirements, snapmirror 
summary: Debe realizar ciertas tareas para actualizar correctamente un clúster que ejecuta SnapMirror. 
---
= Requisitos de actualización de SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe realizar ciertas tareas para actualizar correctamente un clúster que ejecuta SnapMirror.

* Si va a actualizar clústeres con relaciones de DP SnapMirror, debe actualizar los nodos/clústeres de destino antes de actualizar los nodos/clústeres de origen.
* Antes de actualizar un clúster que ejecuta SnapMirror, las operaciones de SnapMirror deben ponerse en modo inactivo para cada nodo que contiene volúmenes de destino, y cada SVM con una relación entre iguales debe tener un nombre único en los clústeres.
+
Para evitar que las transferencias de SnapMirror fallen, debe suspender las operaciones de SnapMirror y, en algunos casos, actualizar los nodos de destino antes de actualizar los nodos de origen. En la siguiente tabla se describen las dos opciones para suspender operaciones de SnapMirror.

+
[cols="3*"]
|===
| Opción | Descripción | ¿Actualizar nodos de destino antes de los nodos de origen? 


 a| 
Suspender las operaciones de SnapMirror durante la NDU (actualización no disruptiva).
 a| 
El método más sencillo de actualización en un entorno de SnapMirror es suspender todas las operaciones de SnapMirror, llevar a cabo la actualización y, a continuación, reanudar las operaciones de SnapMirror. No obstante, no se realizarán transferencias de SnapMirror durante toda la NDU. Debe usar este método si el clúster contiene nodos que están reflejando volúmenes entre sí.
 a| 
No, los nodos se pueden actualizar en cualquier orden.



 a| 
Suspender las operaciones de SnapMirror de un volumen de destino a la vez.
 a| 
Puede suspender las transferencias de SnapMirror para un volumen de destino en concreto, actualizar el nodo (o par de alta disponibilidad) que contiene el volumen de destino, actualizar el nodo (o el par de alta disponibilidad) que contiene el volumen de origen y, a continuación, reanudar las transferencias de SnapMirror para el volumen de destino. Con este método, las transferencias de SnapMirror para los demás volúmenes de destino pueden continuar mientras se actualizan los nodos que contienen los volúmenes de destino y origen originales.
 a| 
Sí.

|===


Las relaciones entre iguales de SVM requieren que los nombres de SVM sean únicos en todos los clústeres. Es la mejor práctica nombrar a las SVM con un único nombre de dominio completamente cualificado (FQDN), por ejemplo, "dataVerser.HQ" o "mirrorVserver.Offsite". El uso del estilo de nomenclatura FQDN hace que sea mucho más fácil asegurarse de que la singularidad.

.Información relacionada
link:../concepts/index.html["Conceptos de ONTAP"]
