---
permalink: upgrade/concept_when_you_need_to_update_the_disk_qualification_package.html 
sidebar: sidebar 
keywords: upgrade, ontap, dqp, disk, qualification, package 
summary: 'El paquete de cualificación de disco (DQP) añade compatibilidad total con las unidades recién cualificadas. Antes de actualizar el firmware de la unidad o añadir nuevos tipos o tamaños de unidad a un clúster, debe actualizar el DQP. Una práctica recomendada es actualizar también el DQP regularmente; por ejemplo, cada trimestre o semestral.' 
---
= Actualice el paquete de cualificación de disco
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada actualización del paquete de cualificación de disco de ONTAP (DQP) añade compatibilidad total con las unidades recién cualificadas.

El DQP contiene los parámetros adecuados para la interacción ONTAP con todas las unidades recién cualificadas. Si ejecuta una versión de ONTAP con un DQP que no contiene información para una unidad recién cualificada, ONTAP no tendrá la información para configurar correctamente la unidad.

Una buena práctica es también actualizar el DQP cada trimestre, y al menos dos veces al año.  Debe descargar e instalar el DQP en las siguientes situaciones.

* Siempre que actualice a una versión nueva de ONTAP.
+
El DQP no se actualiza como parte de una actualización de ONTAP.

* Cuando se añade un tamaño o un tipo de unidad nuevo al nodo
+
Por ejemplo, si ya tiene unidades de 1 TB y añade unidades de 2 TB, debe comprobar la actualización más reciente del DQP.

* Cada vez que se actualiza el firmware de disco
* Siempre que estén disponibles los archivos DQP o firmware de disco más nuevos


.Información relacionada
* https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip["Descargas de NetApp: Paquete de cualificación de disco"^]
* https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Descargas de NetApp: Firmware de la unidad de disco"]

