---
permalink: upgrade/concept_mixed_version_requirements.html 
sidebar: sidebar 
keywords: ontap, upgrade, mixed, version, clusters, mixed-version nodes, requirements 
summary: Un clúster de ONTAP de versión mixta consta de nodos que ejecutan dos versiones principales de ONTAP diferentes, como ONTAP 9,8 y 9.12.1. Los clústeres de ONTAP de versiones mixtas solo son compatibles con NetApp en situaciones específicas. 
---
= Clústeres de ONTAP de versión mixta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un clúster de ONTAP de versión mixta consta de nodos que ejecutan dos versiones principales de ONTAP diferentes durante un tiempo limitado.  Por ejemplo, si un clúster consta de nodos que ejecutan ONTAP 9,8 y 9.12.1, el clúster es un clúster de versiones mixtas.  De igual forma, un clúster en el que nodos ejecuten ONTAP 9.9.1 y 9.13.1 sería un clúster de versiones mixtas.  NetApp admite clústeres ONTAP de versión mixta durante períodos limitados y en situaciones específicas.

A continuación se muestran los casos más comunes en los que un clúster de ONTAP tendrá una versión mixta:

* Actualizaciones del software ONTAP en grandes clústeres
* Es necesario actualizar el software ONTAP cuando piensa añadir nodos nuevos a un clúster


La información se aplica a las versiones de ONTAP que admiten sistemas de plataformas NetApp, como los sistemas A-Series y C-Series de AFF, ASA, FAS y C-Series. La información no se aplica a las versiones de cloud de ONTAP (9.x.0) como 9.12.0.



== Requisitos para clústeres de ONTAP de versión mixta

Si su clúster tiene que introducir una versión mixta de ONTAP, debe conocer los requisitos y las restricciones importantes.

* No puede haber más de dos versiones principales de ONTAP diferentes en un clúster en un momento dado. Los clústeres que tienen nodos en ejecución con niveles de revisión P o D diferentes de la misma versión de ONTAP, como ONTAP 9,9.1P1 y 9,9.1P5, no se consideran clústeres de ONTAP de versiones mixtas.
* Mientras el clúster tiene una versión mixta, no debe introducir ningún comando que modifique la operación o la configuración del clúster, excepto los necesarios para la actualización o el proceso de migración de datos.  Por ejemplo, no deben realizarse actividades como la migración LIF, las operaciones planificadas de conmutación por error de almacenamiento o la creación o destrucción de objetos a gran escala hasta que hayan finalizado la actualización y la migración de datos.
* Para un funcionamiento óptimo del clúster, la cantidad de tiempo que el clúster tenga el estado de versión mixta debe ser lo más breve posible.  La cantidad máxima de tiempo que puede permanecer un clúster en una versión mixta depende de la versión de ONTAP más baja del clúster.
+
[cols="2*"]
|===
| Si la versión más baja de ONTAP que se ejecuta en el clúster de versiones mixtas es: | A continuación, puede permanecer en un estado de versión mixta durante un máximo de 


| ONTAP 9,8 o superior | 90 días 


| ONTAP 9,7 o inferior | 7 días 
|===
* A partir de ONTAP 9,8, un clúster de ONTAP de versión mixta puede abarcar un máximo de 5 versiones principales. Por ejemplo, un clúster ONTAP de versión mixta podría tener nodos que ejecuten ONTAP 9,8 y 9.12.1, o bien podría tener nodos que ejecuten ONTAP 9.9.1 y 9.13.1. No se admitiría un clúster de versión mixta de ONTAP con nodos que ejecutan ONTAP 9,8 y 9.13.1, porque un clúster de versión mixta abarca 6 versiones principales.




== Actualización de la versión de ONTAP de un clúster de gran tamaño

Una situación en la que se puede introducir un estado en un clúster de versiones mixtas implica actualizar la versión ONTAP de un clúster con varios nodos para aprovechar las funciones disponibles en versiones posteriores de ONTAP 9. Cuando necesite actualizar la versión de ONTAP de un clúster más grande, deberá introducir un estado de clúster de versiones mixtas durante un período de tiempo a medida que actualice cada nodo del clúster.



== Añadir nodos nuevos al clúster

Otra situación para introducir un estado de cluster de versiones mixtas implica la adición de nuevos nodos al clúster. Es posible añadir nodos nuevos al clúster para expandir su capacidad, o es posible añadir nodos nuevos como parte del proceso de reemplazar por completo las controladoras. En cualquier caso, debe habilitar la migración de sus datos desde controladoras existentes a los nodos nuevos en el sistema nuevo.

Si piensa agregar nodos nuevos al clúster y esos nodos requieren una versión mínima de ONTAP que sea posterior a la versión que se está ejecutando actualmente en el clúster, debe realizar las actualizaciones de software compatibles de los nodos existentes del clúster antes de agregar los nodos nuevos.

Lo ideal sería que actualizara todos los nodos existentes a la versión mínima de ONTAP que requieran los nodos que planea agregar al clúster. Sin embargo, si esto no es posible porque algunos de sus nodos existentes no son compatibles con la versión posterior de ONTAP, deberá introducir un estado de versión mixta durante una cantidad limitada de tiempo como parte del proceso de actualización. Si tiene nodos que no admiten la versión mínima de ONTAP requerida por las controladoras nuevas, debe hacer lo siguiente:

. link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_methods.html["Renovar"] Los nodos que no admiten la versión mínima de ONTAP requerida por las nuevas controladoras hasta la versión máxima de ONTAP que admiten.
+
Por ejemplo, si tiene un sistema FAS8000 con ONTAP 9,5 y va a añadir una nueva plataforma C-Series con ONTAP 9.12.1, debería actualizar su sistema FAS8000 a ONTAP 9,8 (que es la versión máxima de ONTAP que admite).

. Añada los nodos nuevos al clúster.
+
Use el clúster de comandos de ONTAP `add-node -allow-mixed-version-join` en el nivel de privilegio avanzado para unir los nuevos nodos.

. link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-create-aggregate-move-volumes.html["Migrar los datos"] De cualquier nodo que no se pueda actualizar a un nodo que ejecute la versión superior de ONTAP.
. link:https://docs.netapp.com/us-en/ontap/system-admin/remov-nodes-cluster-concept.html["Quite los nodos no compatibles del clúster"^].
. link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_methods.html["Renovar"] los nodos restantes del clúster a la misma versión de los nuevos nodos.
+
De manera opcional, actualice el clúster completo (incluidos los nodos nuevos) al link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU2["última versión de parche recomendada"] De la versión de ONTAP que se ejecuta en los nodos nuevos.



Para obtener más información sobre la migración de datos, consulte:

* link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-create-aggregate-move-volumes.html["Cree un agregado y mueva volúmenes a los nuevos nodos"^]
* link:https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html#setting-up-new-iscsi-connections["Configuración de nuevas conexiones iSCSI para movimientos de volúmenes SAN"^]
* link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/encrypt-existing-volume-task.html["Movimiento de volúmenes con cifrado"^]

