---
permalink: upgrade/concept_how_firmware_is_updated_during_upgrade.html 
sidebar: sidebar 
keywords: ontap, upgrade, how, firmware, updated, during 
summary: No es necesario actualizar el firmware antes de realizar una actualización de ONTAP.  El firmware del clúster se incluye en el paquete de actualización de ONTAP y se instala como parte del proceso de actualización. 
---
= Reinicie el SP o BMC para preparar la actualización del firmware durante una actualización de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
No es necesario actualizar manualmente el firmware antes de proceder con una actualización de ONTAP.  El firmware del clúster se incluye con el paquete de actualización de ONTAP y se copia en el dispositivo de arranque de cada nodo.  El nuevo firmware se instala como parte del proceso de actualización.

El firmware de los siguientes componentes se actualiza automáticamente si la versión del clúster es más antigua que el firmware que se incluye con el paquete de actualización de ONTAP:

* BIOS/CARGADOR
* Service Processor (SP) o controlador de gestión de placa base (BMC)
* Bandeja de almacenamiento
* Disco
* Flash Cache


Para prepararse para una actualización fluida, debe reiniciar el SP o BMC antes de que comience la actualización.

.Paso
. Reinicie el SP o BMC antes de realizar la actualización:
+
[source, cli]
----
system service-processor reboot-sp -node node_name
----
+
Solo reinicie un SP o BMC a la vez.  Espere a que el SP o BMC reiniciado recicle por completo antes de reiniciar el siguiente.



También puede hacerlo link:../update/firmware-task.html["actualice el firmware manualmente"] Entre actualizaciones de ONTAP.  Si tiene Active IQ, puede link:https://activeiq.netapp.com/system-firmware/["Consulte la lista de versiones de firmware incluidas actualmente en la imagen ONTAP"^].

Las versiones actualizadas del firmware están disponibles de la siguiente manera:

* link:https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["Firmware del sistema (BIOS, BMC, SP)"^]
* link:https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Firmware de la bandeja"^]
* link:https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Firmware de disco y caché flash"^]

