---
permalink: upgrade/concept_upgrade_methods.html 
sidebar: sidebar 
keywords: upgrade, methods, andu, ndu, automated, automatic, system manager, cli, nondisruptive, disruptive 
summary: 'El método que utilice para actualizar depende de la configuración. Si está disponible, la actualización automatizada no disruptiva (ANDU) mediante System Manager es el método preferido.' 
---
= ¿Qué método de actualización debo usar?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El método que utilice para la actualización: No disruptivo, no disruptivas, automatizada o manual, depende de su configuración. Si está disponible, la actualización automatizada no disruptiva (ANDU) mediante System Manager es el método preferido.

*Las actualizaciones sin interrupciones* + las actualizaciones sin interrupciones aprovechan la tecnología de recuperación tras fallos de alta disponibilidad (ha) de ONTAP para garantizar que los clústeres sigan sirviendo datos durante la actualización. Existen dos tipos de procesos de actualización no disruptivos.

* _Batch_ actualiza + en una actualización por lotes, el clúster se divide en varios lotes, cada uno de los cuales contiene varios pares ha. En el primer lote, se actualizan la mitad de los nodos, seguidos por sus partners de alta disponibilidad. A continuación, el proceso se repite secuencialmente para los lotes restantes.
* _Rolling_ actualizaciones + en una actualización gradual, un nodo se desconecta y se actualiza mientras su partner asume el control del almacenamiento. Una vez que finaliza la actualización del nodo, el nodo del partner devuelve el control al nodo original y se repite el proceso, esta vez en el nodo del partner. Cada par de alta disponibilidad adicional se actualiza en secuencia hasta que todos los pares de alta disponibilidad ejecutan la versión de destino. + *Nota:* el término _Rolling Upgrade_ se utiliza frecuentemente en el sector del software para actualizaciones de software que no causan interrupciones en el servicio y por lo tanto es a menudo sinónimo de "actualización no disruptiva". En las actualizaciones de ONTAP 9, una _Rolling update_ es uno de los procesos que se pueden utilizar para realizar actualizaciones sin interrupciones.


Las actualizaciones no disruptivas se pueden realizar mediante un método _automatizó_ o _manual_.

* *Actualización automatizada sin interrupciones (ANDU)*
+
** Cuando un administrador inicia UN ANDU, ONTAP instala automáticamente la imagen ONTAP de destino en cada nodo, valida los componentes del clúster para garantizar que el clúster se pueda actualizar sin interrupciones y, a continuación, ejecuta una actualización por lotes o en segundo plano.
+
*** Las actualizaciones por lotes son el valor predeterminado para clústeres de 8 nodos o más.
*** La implementación de actualizaciones es la opción predeterminada para clústeres con menos de 8 nodos. También se puede seleccionar explícitamente la implementación de actualizaciones para clústeres con 8 nodos o más.


** UN ANDU puede ejecutarse mediante System Manager o la interfaz de línea de comandos (CLI) de ONTAP. Si está disponible para su configuración, ANDU con System Manager es el método de actualización recomendado.


* *Actualización manual no disruptiva*
+
** Un administrador debe confirmar de forma manual la disposición para actualizar los componentes del clúster en cada nodo y, a continuación, realizar manualmente los pasos del proceso de actualización en primer plano.
** Las actualizaciones manuales no disruptivas se ejecutan mediante la interfaz de línea de comandos de ONTAP.
** Sólo debe utilizar un método manual si ANDU no es compatible con su configuración.




*Actualizaciones disruptivas* + en una actualización disruptiva, la recuperación tras fallos del almacenamiento está desactivada para cada par de alta disponibilidad y, a continuación, cada nodo se reinicia de uno en uno. Las actualizaciones con interrupciones se pueden realizar más rápidamente que las actualizaciones no disruptivas y requieren menos pasos para completarse. Sin embargo, no se debe realizar una actualización disruptiva a menos que se pueda desconectar el clúster durante la actualización. Si trabaja en un entorno SAN, debe estar preparado para apagar o suspender todos los clientes SAN antes de realizar una actualización disruptiva. Las actualizaciones disruptivas se realizan mediante la interfaz de línea de comandos de ONTAP.



== Métodos para configuraciones que no sean de MetroCluster

Los clústeres con 2 o más nodos pueden usar cualquiera de los siguientes métodos de actualización, que se enumeran por orden de uso recomendado.

* xref:task_upgrade_andu_sm.html[Automatización no disruptiva gracias a System Manager]
* xref:task_upgrade_andu_cli.html[Automatización no disruptiva gracias a la interfaz de línea de comandos]
* xref:task_upgrade_nondisruptive_manual_cli.html[Manual no disruptivo, mediante la interfaz de línea de comandos]
* xref:task_updating_an_ontap_cluster_disruptively.html[Interrupción manual con CLI]


Los clústeres de un solo nodo deben usar uno de los métodos disruptivos, aunque se recomienda el método automatizado.

* xref:task_upgrade_disruptive_automated_cli.html[Interrupciones automáticas gracias al uso de la interfaz de línea de comandos]
* xref:task_updating_an_ontap_cluster_disruptively.html[Interrupción manual con CLI]




== Métodos para configuraciones de MetroCluster

Los métodos de actualización disponibles para cada configuración se enumeran por orden de uso recomendado.

[cols="3*"]
|===
| Versión de ONTAP | Número de nodos | Método de actualización 


| 9.3 o posterior | 2,4  a| 
* xref:task_upgrade_andu_sm.html[Automatización no disruptiva gracias a System Manager]
* xref:task_upgrade_andu_cli.html[Automatización no disruptiva gracias a la interfaz de línea de comandos]
* xref:task_updating_an_ontap_cluster_disruptively.html[Interrupción manual con CLI]




| 9.3 o posterior | 8  a| 
* xref:task_upgrade_andu_cli.html[Automatización no disruptiva gracias a la interfaz de línea de comandos]
* xref:task_updating_a_four_or_eight_node_mcc.html[Manual no disruptivo, mediante la interfaz de línea de comandos]
* xref:task_updating_an_ontap_cluster_disruptively.html[Interrupción manual con CLI]




| 9.2 o anterior | 2  a| 
* xref:task_updating_a_two_node_metrocluster_configuration_in_ontap_9_2_and_earlier.html[Manual no disruptivo (para clústeres de 2 nodos) mediante la CLI]
* xref:task_updating_an_ontap_cluster_disruptively.html[Interrupción manual con CLI]




| 9.2 o anterior | 4, 8  a| 
* xref:task_updating_a_four_or_eight_node_mcc.html[Manual no disruptivo, mediante la interfaz de línea de comandos]
* xref:task_updating_an_ontap_cluster_disruptively.html[Interrupción manual con CLI]




| 9.0 o posterior | 4, 8 (sólo parche) | xref:task_upgrade_andu_sm.html[Automatización no disruptiva gracias a System Manager] 


| 9.2 o anterior | 2, 4, 8 (sólo parche) | xref:task_upgrade_andu_sm.html[Automatización no disruptiva gracias a System Manager] 
|===