---
permalink: upgrade/confirm-configuration.html 
sidebar: sidebar 
keywords: ontap, upgrade, before, confirm, configuration, hardware, cluster management switches, metrocluster ip switches, san, target, release 
summary: Antes de actualizar ONTAP, debe confirmar que la configuración de hardware es compatible con la versión de destino. 
---
= Confirme la compatibilidad de ONTAP para la configuración de hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de actualizar ONTAP, debe confirmar que la configuración de hardware es compatible con la versión de ONTAP de destino.



== Todas las configuraciones

Uso https://hwu.netapp.com["Hardware Universe de NetApp"^] Para confirmar que la plataforma de hardware, el clúster y los switches de administración son compatibles con la versión de ONTAP de destino.  El clúster y los switches de administración incluyen los switches de red de clúster (NX-OS), los switches de red de gestión (IOS) y el archivo de configuración de referencia (RCF).  Si el clúster y los switches de gestión son compatibles, pero no ejecutan las versiones mínimas de software necesarias para la versión ONTAP de destino, actualice los switches a versiones de software compatibles.

* https://mysupport.netapp.com/site/info/broadcom-cluster-switch["Descargas de NetApp: Switches de clúster de Broadcom"^]
* https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Descargas de NetApp: Switches Ethernet de Cisco"^]
* https://mysupport.netapp.com/site/info/netapp-cluster-switch["Descargas de NetApp: Switches de clúster de NetApp"^]



NOTE: Si necesita actualizar los switches, NetApp recomienda primero completar la actualización del software de ONTAP y, a continuación, realizar la actualización del software de los switches.



== Configuraciones de MetroCluster

Antes de actualizar ONTAP, si tiene una configuración de MetroCluster, utilice el https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^] Para confirmar que los switches IP de MetroCluster son compatibles con la versión de ONTAP de destino.



== Configuraciones SAN

Antes de actualizar ONTAP, si el clúster está configurado para SAN, utilice https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^] Para confirmar que la configuración de SAN es totalmente compatible.

Deben ser compatibles todos los componentes DE SAN, como la versión de software de la ONTAP de destino, el sistema operativo host y las revisiones, el software de utilidades del host requerido, el software multivía y los controladores y el firmware de adaptadores.
