---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: upgrade overview, upgrade, digital advisor, summary, upgrade ontap, upgrading ontap, upgrade, upgrading, ontap, software, on-premise, prepare, preparation, major upgrade, minor upgrade, patch upgrade, upgrade assistance, upgrade help, upgrade technical support 
summary: Una actualización de ONTAP le permite aprovechar las características nuevas y mejoradas. Siga los pasos recomendados para prepararse para la actualización antes de comenzar. 
---
= Información general de la actualización de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al actualizar el software ONTAP, puede aprovechar las nuevas y mejoradas funciones de ONTAP que le ayudarán a reducir costes, acelerar las cargas de trabajo críticas, mejorar la seguridad y ampliar el alcance de la protección de datos disponible para su organización.

Una importante actualización de ONTAP consiste en pasar de una versión con números ONTAP inferiores a superiores. Un ejemplo sería una actualización de su clúster de ONTAP 9,8 a ONTAP 9.12.1.  Una actualización menor (o un parche) consiste en pasar de una versión de ONTAP inferior a una versión de ONTAP superior dentro de la misma versión numerada. Un ejemplo sería una actualización de su clúster de ONTAP 9.12.1P1 a 9.12.1P4.

Para comenzar, debería link:prepare.html["prepare la actualización"]. Si tienes un contrato activo de SupportEdge para el Asesor Digital de Active IQ (también conocido como Asesor Digital), deberías link:create-upgrade-plan.html["Planifique la actualización con el asesor de actualizaciones"]. El asesor de actualizaciones ofrece inteligencia que le ayuda a minimizar la incertidumbre y el riesgo al evaluar su clúster y crear un plan de actualización específico de su configuración.

Después de prepararse para la actualización, se recomienda realizar las actualizaciones con link:task_upgrade_andu_sm.html["Actualización automatizada y no disruptiva (ANDU) de System Manager"].  ANDU aprovecha la tecnología de conmutación al nodo de respaldo de alta disponibilidad de ONTAP para garantizar que los clústeres siguen sirviendo datos sin interrupciones durante la actualización.


NOTE: A partir de ONTAP 9.12.1, System Manager está totalmente integrado con BlueXP. Si BlueXP está configurado en tu sistema, puedes actualizarlo a través del entorno de trabajo de BlueXP.

Si necesita ayuda para actualizar su software ONTAP, los servicios profesionales de NetApp ofrecen un link:https://www.netapp.com/pdf.html?item=/media/8144-sd-managed-upgrade-service.pdf["Servicio de renovación gestionada"^]. Si está interesado en usar este servicio, póngase en contacto con su representante de ventas de NetApp o con link:https://www.netapp.com/forms/sales-contact/["Envíe el formulario de consulta de ventas de NetApp"^]. El Servicio de Actualización Gestionada, así como otros tipos de soporte de actualización están disponibles para los clientes con link:https://www.netapp.com/pdf.html?item=/media/8845-supportedge-expert-service.pdf["Servicios de SupportEdge Expert"^] sin coste adicional.
