---
permalink: upgrade/prepare.html 
sidebar: sidebar 
keywords: upgrade, ontap, prepare, digital advisor, preparation, before you upgrade, plan, upgrade overview, upgrade summary 
summary: La preparación de una actualización de ONTAP le ayuda a identificar y mitigar los riesgos o los bloqueadores de actualización y a tener en cuenta las consideraciones especiales aplicables a su configuración. 
---
= Prepárese para actualizar el software de ONTAP sin el Asesor de actualizaciones
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prepararse correctamente para una actualización de software de ONTAP le ayuda a identificar y reducir los posibles riesgos o bloqueadores de actualización antes de iniciar el proceso de actualización. Durante la preparación de la actualización, también puede identificar cualquier consideración especial que deba tener en cuenta antes de la actualización. Por ejemplo, si se habilita el modo FIPS SSL en su clúster y las cuentas de administrador utilizan claves públicas SSH para la autenticación, debe verificar que el algoritmo de clave de host sea compatible con la versión de ONTAP de destino.

Si tiene un contrato activo de SupportEdge para link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["Asesor digital"^], link:create-upgrade-plan.html["Planifique la actualización con el asesor de actualizaciones"]. Si no tiene acceso al asesor digital de Active IQ (también conocido como asesor digital), debería hacer lo siguiente para prepararse para una actualización de ONTAP.

. link:choose-target-version.html["Elija la versión de ONTAP objetivo"].
. Revise las secciones _Upgrade Precautions_ y _Known Problems and Limits_ en link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notas de la versión de ONTAP 9"]Para la versión de destino.
+
_Advertencias de actualización_ Describa los posibles problemas que debe tener en cuenta antes de actualizar. _Problemas y limitaciones conocidos_ Describe un comportamiento del sistema potencialmente inesperado que puede experimentar después de actualizar.

+
Debe iniciar sesión con su cuenta de NetApp o crear una cuenta para acceder a las Notas de la versión.

. link:confirm-configuration.html["Confirme la compatibilidad de ONTAP para la configuración de hardware"].
+
La plataforma de hardware, los switches de administración de clústeres y los switches IP de MetroCluster deben admitir la versión de destino. Si el clúster está configurado para SAN, la configuración de SAN debe ser totalmente compatible.

. link:task_check_for_common_configuration_errors_using_config_advisor.html["Utilice Active IQ Config Advisor para verificar que no haya errores de configuración comunes."]
. Revise los ONTAP compatibles link:concept_upgrade_paths.html#supported-upgrade-paths["rutas de actualización"]para determinar si puede realizar una actualización directa o si es necesario completar la actualización por etapas.
. link:task_verifying_the_lif_failover_configuration.html["Compruebe la configuración de recuperación tras fallos de LIF"].
+
Antes de realizar una actualización, tiene que verificar que las políticas de conmutación por error del clúster y los grupos de conmutación por error están configurados correctamente.

. link:concept_verify_svm_routing.html["Compruebe la configuración de enrutamiento de la SVM"].
. link:special-considerations.html["Verificar consideraciones especiales"] para el clúster.
+
Si existen ciertas configuraciones en el clúster, debe realizar ciertas acciones específicas antes de iniciar una actualización de software de ONTAP.

. link:reboot-sp-bmc.html["Reinicie el SP o BMC"].

