---
permalink: upgrade/remove-ems-lif-service-task.html 
sidebar: sidebar 
keywords: ontap, upgrade, after, post, ems, event, management, system, lifs, messages, not, delivered 
summary: Después de actualizar de ONTAP 9.7 o anterior a 9.8 o posterior, si está usando EMS es posible que deba eliminar el servicio EMS LIF de ciertas políticas de servicio de red. 
---
= Elimine el servicio LIF de EMS de las políticas de servicio de red tras una actualización de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si tiene mensajes del Sistema de gestión de eventos (EMS) configurados antes de actualizar de ONTAP 9.7 o anterior a ONTAP 9.8 o posterior, después de la actualización es posible que sus mensajes EMS no se entreguen.

Durante la actualización,  `management-ems` , que es el servicio EMS LIF, se agrega a todas las políticas de servicio existentes en las SVM de administración. Esto permite enviar mensajes EMS desde cualquiera de los LIF asociados a las políticas de servicio. Si la LIF seleccionada no tiene accesibilidad al destino de notificaciones de eventos, el mensaje no se entrega.

Para evitar esto, después de la actualización debe eliminar el servicio EMS LIF de las políticas de servicio de red que no brindan accesibilidad al destino.

link:../networking/lifs_and_service_policies96.html#service-policies-for-system-svms["Obtenga más información sobre los LIF y las políticas de servicio de ONTAP"].

.Pasos
. Identifique los LIF y las políticas de servicio de red asociadas a través de las cuales se pueden enviar mensajes EMS:
+
[source, cli]
----
network interface show -fields service-policy -services management-ems
----
+
[listing]
----
vserver        lif            service-policy
-------------- ------------   ------------------
cluster-1      cluster_mgmt   default-management
cluster-1      node1-mgmt     default-management
cluster-1      node2-mgmt     default-management
cluster-1      inter_cluster  default-intercluster
4 entries were displayed.
----
. Compruebe cada LIF para obtener conectividad con el destino EMS:
+
[source, cli]
----
network ping -lif <lif_name> -vserver <svm_name> -destination <destination_address>
----
+
Realice esto en cada nodo.

+
.Ejemplos
[listing]
----
cluster-1::> network ping -lif node1-mgmt -vserver cluster-1 -destination 10.10.10.10
10.10.10.10 is alive

cluster-1::> network ping -lif inter_cluster -vserver cluster-1 -destination 10.10.10.10
no answer from 10.10.10.10
----
. Introduzca el nivel de privilegio avanzado:
+
[source, cli]
----
set advanced
----
. Para los LIF que no tienen accesibilidad, elimine el  `management-ems` Servicio LIF de las políticas de servicio correspondientes:
+
[source, cli]
----
network interface service-policy remove-service -vserver <svm_name> -policy <service_policy_name> -service management-ems
----
+
Obtenga más información sobre `network interface service-policy remove-service` en el link:https://docs.netapp.com/us-en/ontap-cli/network-interface-service-policy-remove-service.html["Referencia de comandos del ONTAP"^].

. Compruebe que el LIF de ems de gestión solo esté asociado a las LIF que proporcionan accesibilidad al destino de EMS:
+
[source, cli]
----
network interface show -fields service-policy -services management-ems
----

