---
sidebar: sidebar 
permalink: upgrade/resume-upgrade-after-andu-error.html 
keywords: netapp, ontap, automate, automatic, automated, upgrade, nondisruptive, nondisruptively, non-disruptive update, nondisruptive upgrade, upgrade a cluster, shift workload between clusters, hardware platform, configuration, software image, update, update ONTAP, update software, ndu 
summary: Si una actualización automática del software ONTAP se detiene debido a un error, debe resolver el error y, a continuación, continuar con la actualización. 
---
= Reanude la actualización del software ONTAP tras un error en el proceso de actualización automatizada
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si una actualización automática del software ONTAP se detiene debido a un error, debe resolver el error y, a continuación, continuar con la actualización.  Una vez resuelto el error, puede optar por continuar con el proceso de actualización automatizada o completar manualmente el proceso de actualización. Si decide continuar con la actualización automatizada, no realice ninguno de los pasos de actualización de forma manual.

.Pasos
[role="tabbed-block"]
====
.System Manager
--
. Según la versión de ONTAP que esté ejecutando, realice uno de los pasos siguientes:
+
|===


| Si está ejecutando... | Realice lo siguiente... 


 a| 
ONTAP 9,8 o posterior
 a| 
Haga clic en *Cluster* > *Overview*



 a| 
ONTAP 9,7, 9,6 o 9,5
 a| 
Haga clic en *Configuración* > *clúster* > *Actualizar*.



 a| 
ONTAP 9.4 o anterior
 a| 
** Haga clic en *Configuración* > *actualización de clúster*.
** En la esquina derecha del panel *Descripción general*, haz clic en los tres puntos verticales azules y selecciona *Actualización de ONTAP*.


|===
. Continúe la actualización automatizada o cancele la actualización y continúe manualmente.
+
|===


| Si desea... | Realice lo siguiente... 


 a| 
Reanude la actualización automatizada
 a| 
Haga clic en *Reanudar*.



 a| 
Cancele la actualización automatizada y continúe manualmente
 a| 
Haga clic en *Cancelar*.

|===


--
.CLI
--
. Vea el error de actualización:
+
[source, cli]
----
cluster image show-update-progress
----
. Resuelva el error.
. Reanude la actualización:
+
|===


| Si desea... | Introduzca el siguiente comando... 


 a| 
Reanude la actualización automatizada
 a| 
[source, cli]
----
cluster image resume-update
----


 a| 
Cancele la actualización automatizada y continúe manualmente
 a| 
[source, cli]
----
cluster image cancel-update
----
|===


--
====
.Después de terminar
link:task_what_to_do_after_upgrade.html["Realice las comprobaciones posteriores a la actualización"].
