---
permalink: upgrade/task_updating_an_ontap_cluster_disruptively.html 
sidebar: sidebar 
keywords: ontap, upgrade, disruptively 
summary: 'Si puede desconectar el clúster para actualizar a una nueva versión de ONTAP, puede utilizar el método de actualización disruptiva. Este método tiene varios pasos: Deshabilitar la conmutación por error de almacenamiento para cada pareja de alta disponibilidad, reiniciar cada nodo del clúster y, a continuación, volver a habilitar la conmutación por error del almacenamiento.' 
---
= Actualización manual disruptiva mediante la CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si puede desconectar el clúster para actualizar a una nueva versión de ONTAP, puede utilizar el método de actualización disruptiva. Este método tiene varios pasos: Deshabilitar la conmutación por error de almacenamiento para cada pareja de alta disponibilidad, reiniciar cada nodo del clúster y, a continuación, volver a habilitar la conmutación por error del almacenamiento.

* Debe haber satisfecho los requisitos de preparación.
+
En concreto, debe descargar e instalar la imagen de software mediante el procedimiento link:task_download_and_install_ontap_software_image.html#for-manual-upgrades["para actualizaciones manuales"].

* Si opera en un entorno SAN, todos los clientes SAN deben cerrarse o suspenderse hasta que se complete la actualización.
+
Si los clientes SAN no se apagan o suspenden antes de una actualización disruptiva , los sistemas de archivos cliente y las aplicaciones sufren errores que pueden requerir recuperación manual una vez completada la actualización.



En una actualización disruptiva, se requiere un tiempo de inactividad porque la conmutación por error de almacenamiento está deshabilitada para cada par de alta disponibilidad y se actualiza cada nodo. Cuando se deshabilita la conmutación al respaldo de almacenamiento, cada nodo se comporta como un clúster de un solo nodo; es decir, los servicios del sistema asociados con el nodo se interrumpen mientras se tarda en reiniciar el sistema.

. Establezca el nivel de privilegio de admin en Advanced, introduciendo *y* cuando se le solicite continuar: `set -privilege advanced`
+
El aviso avanzado (`*>`) aparece.

. Establezca la nueva imagen del software ONTAP como la imagen predeterminada: `system image modify {-node * -iscurrent false} -isdefault true`
+
Este comando utiliza una consulta ampliada para cambiar la imagen de software de ONTAP de destino (que se instala como imagen alternativa) y que sea la imagen predeterminada de cada nodo.

. Compruebe que la nueva imagen del software ONTAP está configurada como la imagen predeterminada: `system image show`
+
En el ejemplo siguiente, la imagen 2 es la nueva versión de ONTAP y se establece como la imagen predeterminada en ambos nodos:

+
[listing]
----
cluster1::*> system image show
                 Is      Is                Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------- -------------------
node0
         image1  false   true    X.X.X     MM/DD/YYYY TIME
         image2  true    false   Y.Y.Y     MM/DD/YYYY TIME
node1
         image1  false   true    X.X.X     MM/DD/YYYY TIME
         image2  true    false   Y.Y.Y     MM/DD/YYYY TIME
4 entries were displayed.
----
. Realice uno de los siguientes pasos:
+
[cols="2*"]
|===
| Si el clúster consta de... | Realice lo siguiente... 


 a| 
Un nodo
 a| 
Continúe con el próximo paso.



 a| 
Dos nodos
 a| 
.. Deshabilite alta disponibilidad del clúster: `cluster ha modify -configured false`
+
Introduzca `y` para continuar cuando se le solicite.

.. Desactive la conmutación por error del almacenamiento para el par de alta disponibilidad: `storage failover modify -node * -enabled false`




 a| 
Más de dos nodos
 a| 
Deshabilite la recuperación tras fallos del almacenamiento para cada pareja de alta disponibilidad del clúster: `storage failover modify -node * -enabled false`

|===
. Reiniciar un nodo en el clúster: `system node reboot -node nodename -ignore-quorum-warnings`
+

IMPORTANT: No reinicie más de un nodo a la vez.

+
El nodo arranca la nueva imagen de ONTAP. Aparece la solicitud de inicio de sesión de ONTAP, que indica que el proceso de reinicio ha finalizado.

. Después de que el nodo o el conjunto de nodos se haya reiniciado con la nueva imagen ONTAP, establezca el nivel de privilegio en AVANZADO: `set -privilege advanced`
+
Introduzca *y* cuando se le solicite continuar

. Confirme que el nuevo software se está ejecutando: `system node image show`
+
En el siguiente ejemplo, image1 es la nueva versión de ONTAP y se establece como la versión actual del nodo 0:

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. Compruebe que la actualización se haya realizado correctamente:
+
.. Configure el nivel de privilegio en Advanced: `set -privilege advanced`
.. Compruebe que el estado de la actualización se haya completado para cada nodo: `system node upgrade-revert show -node nodename`
+
El estado debe aparecer como completo.

+
Si el estado es no completo, link:http://mysupport.netapp.com/["Comuníquese con el soporte de NetApp"] inmediatamente.

.. Vuelva al nivel de privilegio de administrador: `set -privilege admin`


. Repita los pasos 2 a 7 para cada nodo adicional.
. Si el clúster consta de dos o más nodos, habilite la conmutación por error del almacenamiento para cada pareja de alta disponibilidad del clúster: `storage failover modify -node * -enabled true`
. Si el clúster consta de solo dos nodos, habilite la alta disponibilidad de los clústeres: `cluster ha modify -configured true`

