---
permalink: upgrade/task_verify_cluster_after_upgrade.html 
sidebar: sidebar 
keywords: ontap, upgrade, upgrade, verify, status, health, post, after 
summary: Después de actualizar ONTAP, compruebe la versión del clúster, el estado del clúster y el estado del almacenamiento. En el caso de configuraciones de FC de MetroCluster, compruebe que la conmutación de sitios automática no planificada está habilitada. 
---
= Compruebe el clúster después de actualizar ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de actualizar ONTAP, compruebe la versión del clúster, el estado del clúster y el estado del almacenamiento. Para configuraciones de FC de MetroCluster, compruebe también que el clúster esté habilitado para la conmutación de sitios automática no planificada.



== Comprobar la versión del clúster

Una vez que se hayan actualizado todos los pares de HA, debe usar el comando version para verificar que todos los nodos estén ejecutando la versión de destino.

La versión del clúster es la versión más baja de ONTAP que se ejecuta en cualquier nodo del clúster. Si la versión del clúster no es la versión de ONTAP de destino, puede actualizar el clúster.

. Compruebe que la versión del clúster es la versión de ONTAP de destino:
+
[source, cli]
----
version
----
. Si la versión del clúster no es la versión de ONTAP de destino, debe comprobar el estado de actualización de todos los nodos:
+
[source, cli]
----
system node upgrade-revert show
----




== Compruebe el estado del clúster

Después de actualizar un clúster, debe comprobar que los nodos estén en buen estado y que sean elegibles para participar en el clúster, y que el clúster esté en quórum.

. Compruebe que los nodos del clúster estén en línea y que puedan participar en el clúster:
+
[source, cli]
----
cluster show
----
+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
node0                 true    true
node1                 true    true
----
+
Si alguno de los nodos no es saludable o no apto, compruebe los registros de EMS en busca de errores y realice acciones correctivas.

. Configure el nivel de privilegio en Advanced:
+
[source, cli]
----
set -privilege advanced
----
. Verifique los detalles de configuración de cada proceso RDB.
+
** Las épocas de la base de datos relacional y la base de datos deben coincidir para cada nodo.
** El maestro de quórum por anillo debe ser el mismo para todos los nodos.
+
Tenga en cuenta que cada anillo puede tener un maestro de quórum diferente.

+
|===


| Para mostrar este proceso RDB: | Introduzca este comando... 


 a| 
Aplicación de gestión
 a| 
`cluster ring show -unitname mgmt`



 a| 
Base de datos de ubicación del volumen
 a| 
`cluster ring show -unitname vldb`



 a| 
Administrador de interfaz virtual
 a| 
`cluster ring show -unitname vifmgr`



 a| 
Daemon de gestión de SAN
 a| 
`cluster ring show -unitname bcomd`

|===
+
Obtenga más información sobre `cluster ring show` en el link:https://docs.netapp.com/us-en/ontap-cli/cluster-ring-show.html["Referencia de comandos del ONTAP"^].

+
Este ejemplo muestra el proceso de la base de datos de ubicación del volumen:



+
[listing]
----
cluster1::*> cluster ring show -unitname vldb
Node      UnitName Epoch    DB Epoch DB Trnxs Master    Online
--------- -------- -------- -------- -------- --------- ---------
node0     vldb     154      154      14847    node0     master
node1     vldb     154      154      14847    node0     secondary
node2     vldb     154      154      14847    node0     secondary
node3     vldb     154      154      14847    node0     secondary
4 entries were displayed.
----
. Si va a trabajar en un entorno SAN, compruebe que cada nodo se encuentra en quórum DE SAN:
+
[source, cli]
----
cluster kernel-service show
----
+
[listing]
----
cluster1::*> cluster kernel-service show
Master            Cluster           Quorum        Availability  Operational
Node              Node              Status        Status        Status
----------------- ----------------- ------------- ------------- -------------
cluster1-01       cluster1-01       in-quorum     true          operational
                  cluster1-02       in-quorum     true          operational
2 entries were displayed.
----


.Información relacionada
link:../system-admin/index.html["Administración del sistema"]



== Verifique que la conmutación de sitios automática no planificada está habilitada (solo configuraciones de MetroCluster FC).

Si el clúster está en una configuración de MetroCluster FC, debe verificar que la conmutación automática no planificada esté habilitada después de actualizar ONTAP.

Si está utilizando una configuración IP de MetroCluster, omita este procedimiento.

.Pasos
. Compruebe si la conmutación automática no planificada está habilitada:
+
[source, cli]
----
metrocluster show
----
+
Si la conmutación automática no planificada está habilitada, aparecerá la siguiente instrucción en el resultado del comando:

+
[listing]
----
AUSO Failure Domain  auso-on-cluster-disaster
----
. Si la sentencia no aparece, active una conmutación automática no planificada:
+
[source, cli]
----
metrocluster modify -auto-switchover-failure-domain auso-on-cluster-disaster
----
. Compruebe que se ha activado un switchover no planificado automático:
+
[source, cli]
----
metrocluster show
----


.Información relacionada
link:../disks-aggregates/index.html["Gestión de discos y agregados"]
