---
permalink: upgrade/task_verifying_that_the_netgroup_file_is_present_on_all_nodes.html 
sidebar: sidebar 
keywords: ontap, upgrade, verifying, verify, netgroup file, present, nodes 
summary: 'Si ha cargado grupos de red en máquinas virtuales de almacenamiento \(SVM\), antes de actualizar o revertir, debe comprobar que el archivo de grupo de red esté presente en cada nodo. Un archivo de netgroup que falta en un nodo puede provocar un error en la actualización o la reversión.' 
---
= Compruebe que el archivo netgroup está presente en todos los nodos antes de actualizar o revertir ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de actualizar o revertir ONTAP, si ha cargado netgroups en máquinas virtuales de almacenamiento (SVM), debe verificar que el archivo netgroup esté presente en cada nodo. Un archivo de netgroup que falta en un nodo puede provocar un error en la actualización o la reversión.

.Pasos
. Configure el nivel de privilegio en Advanced:
+
[source, cli]
----
set -privilege advanced
----
. Muestre el estado del grupo de red para cada SVM:
+
[source, cli]
----
vserver services netgroup status
----
. Compruebe que, en cada SVM, cada nodo muestra el mismo valor hash de archivo netgroup:
+
[source, cli]
----
vserver services name-service netgroup status
----
+
De ser así, puede omitir el siguiente paso y continuar con la actualización o la reversión. De lo contrario, continúe con el siguiente paso.

. En cualquier nodo del clúster, cargue manualmente el archivo netgroup:
+
[source, cli]
----
vserver services netgroup load -vserver vserver_name -source uri
----
+
Este comando descarga el archivo netgroup en todos los nodos. Si ya existe un archivo de netgroup en un nodo, se sobrescribe.



.Información relacionada
link:../nfs-config/work-netgroups-task.html["Trabajar con netgroups"]
