---
permalink: upgrade/task_preparing_snapmirror_relationships_for_a_nondisruptive_upgrade_or_downgrade.html 
sidebar: sidebar 
keywords: ontap, upgrade, snapmirror, operations, quisce 
summary: Se recomienda poner en modo inactivo las operaciones de SnapMirror antes de realizar una actualización no disruptiva de ONTAP. 
---
= Preparar las relaciones de SnapMirror para una actualización de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de actualizar ONTAP en un clúster que ejecuta SnapMirror, las operaciones de SnapMirror deben permanecer en modo inactivo para cada nodo que contenga volúmenes de destino y cada SVM entre iguales debe tener un nombre único en los clústeres. Es mejor usar un nombre de dominio completo (FQDN) único para cada SVM, por ejemplo, “dataVerser.hq” o “irrorVserver.Offsite”.

También debe tener en cuenta que si va a actualizar clústeres con relaciones de SnapMirror de DP, debe actualizar los nodos de destino antes de actualizar los nodos de origen.



== Desactive las operaciones de SnapMirror antes de actualizar ONTAP

Para evitar que se produzcan errores en las transferencias de SnapMirror, debe desactivar las operaciones de SnapMirror. También puede desactivar las transferencias de SnapMirror en un volumen de destino concreto y actualizar el nodo de destino propietario antes de actualizar los nodos de origen, de modo que las transferencias de SnapMirror para todos los demás volúmenes de destino puedan continuar. En la siguiente tabla se describen las dos opciones para suspender operaciones de SnapMirror.

[cols="3*"]
|===
| Opción | Descripción | ¿Actualizar nodos de destino antes de los nodos de origen? 


 a| 
Suspender las operaciones de SnapMirror durante la NDU (actualización no disruptiva).
 a| 
El método más sencillo de actualización en un entorno de SnapMirror es suspender todas las operaciones de SnapMirror, llevar a cabo la actualización y, a continuación, reanudar las operaciones de SnapMirror. No obstante, no se realizarán transferencias de SnapMirror durante toda la NDU. Debe usar este método si el clúster contiene nodos que están reflejando volúmenes entre sí.
 a| 
No, los nodos se pueden actualizar en cualquier orden.



 a| 
Suspender las operaciones de SnapMirror de un volumen de destino a la vez.
 a| 
Puede suspender las transferencias de SnapMirror para un volumen de destino en concreto, actualizar el nodo (o par de alta disponibilidad) que contiene el volumen de destino, actualizar el nodo (o el par de alta disponibilidad) que contiene el volumen de origen y, a continuación, reanudar las transferencias de SnapMirror para el volumen de destino. Con este método, las transferencias de SnapMirror para los demás volúmenes de destino pueden continuar mientras se actualizan los nodos que contienen los volúmenes de destino y origen originales.
 a| 
Sí.

|===
.Pasos
. Determine la ruta de destino para cada relación de SnapMirror:
+
[source, cli]
----
snapmirror show
----
. Para cada volumen de destino, suspenda las futuras transferencias de SnapMirror:
+
[source, cli]
----
snapmirror quiesce -destination-path destination
----
+
Si no hay transferencias activas para la relación de SnapMirror, este comando establece su estado en "Quiesced". Si la relación tiene transferencias activas, el estado se establece en "Quiring" hasta que se completa la transferencia y, a continuación, el estado se convierte en "Quiesced".

+
En este ejemplo, se realizan transferencias relacionadas con el volumen de destino "vol1" de "SVMvs0.example.com":

+
[listing]
----
cluster1::> snapmirror quiesce -destination-path vs0.example.com:vol1
----
. Compruebe que todas las relaciones de SnapMirror se ponen en modo inactivo:
+
`snapmirror show -status !Quiesced`

+
Este comando muestra cualquier relación de SnapMirror que se _no_ en modo inactivo.

+
Este ejemplo muestra que todas las relaciones de SnapMirror se ponen en modo inactivo:

+
[listing]
----
cluster1::> snapmirror show -status !Quiesced
There are no entries matching your query.
----
. Si actualmente se está transfiriendo alguna de las relaciones de SnapMirror, realice una de las siguientes opciones:
+
[cols="2*"]
|===
| Opción | Descripción 


 a| 
Espere a que las transferencias finalicen antes de realizar la actualización de ONTAP.
 a| 
Después de que cada transferencia termina, la relación cambia al estado "Quiesced".



 a| 
Detenga las transferencias:

`snapmirror abort -destination-path destination -h`

*Nota:* debe utilizar el `-foreground true` parámetro si va a terminar las transferencias de reflejos con uso compartido de carga.
 a| 
Este comando detiene la transferencia de SnapMirror y restaura el volumen de destino a la última copia de Snapshot que se transfirió correctamente. La relación se establece en el estado "Quiesced".

|===

