---
permalink: upgrade/task_plan_without_upgrade_advisor.html 
sidebar: sidebar 
keywords: ontap, upgrade, plan, planning, upgrade, manually, manual 
summary: Se recomienda utilizar el asesor de actualizaciones de Active IQ para planificar la actualización. Si no tiene un contrato de SupportEdge activo para Active IQ, debe realizar las comprobaciones necesarias antes de la actualización y crear su propio plan de actualización. 
---
= Planifique la actualización sin el asesor de actualizaciones
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se recomienda utilizar el Asesor de actualizaciones en link:https://aiq.netapp.com/["Active IQ"^] para planificar la actualización. Si no tiene una activa link:https://www.netapp.com/us/services/support-edge.aspx["SupportEdge"] Contrato para Active IQ, debe realizar las comprobaciones necesarias previas a la actualización y crear su propio plan de actualización.



== ¿Cuánto tiempo tardará mi actualización?

Debe planificar al menos 30 minutos para completar los pasos preparatorios, 60 minutos para actualizar cada par de alta disponibilidad y al menos 30 minutos para completar los pasos posteriores a la actualización.


NOTE: Si utiliza el cifrado de NetApp con un servidor de gestión de claves externo y el protocolo de interoperabilidad de gestión de claves (KMIP), debería esperar que la actualización de cada pareja de alta disponibilidad tenga más de una hora.

Nuestras directrices sobre la duración de la actualización se basan en configuraciones y cargas de trabajo típicas. Puede usar estas directrices para estimar el tiempo que se necesita para realizar una actualización no disruptiva en su entorno. No obstante, la duración real del proceso de actualización dependerá de su entorno individual y de la cantidad de nodos.
