---
permalink: upgrade/task_configuring_ldap_clients_to_use_tls_for_highest_security.html 
sidebar: sidebar 
keywords: ontap, upgrade, configuring, configure, ldap, clients, servers, tls, security 
summary: Antes de actualizar a la versión ONTAP de destino, debe configurar clientes LDAP mediante SSLv3 para que las comunicaciones seguras con servidores LDAP puedan usar TLS. SSL no estará disponible después de la actualización. 
---
= Configure los clientes LDAP para que utilicen TLS para obtener la mayor seguridad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de actualizar a la versión ONTAP de destino, debe configurar clientes LDAP mediante SSLv3 para que las comunicaciones seguras con servidores LDAP puedan usar TLS. SSL no estará disponible después de la actualización.

De forma predeterminada, las comunicaciones LDAP entre las aplicaciones cliente y servidor no están cifradas. Debe desactivar el uso de SSL e imponer el uso de TLS.

. Compruebe que los servidores LDAP del entorno son compatibles con TLS.
+
Si no lo hacen, no continúe. Debe actualizar los servidores LDAP a una versión compatible con TLS.

. Compruebe qué configuraciones del cliente LDAP de ONTAP tienen LDAP sobre SSL/TLS habilitado: `vserver services name-service ldap client show`
+
Si no hay ninguno, puede omitir los pasos restantes. Sin embargo, debe considerar utilizar LDAP sobre TLS para mejorar la seguridad.

. Para cada configuración de cliente LDAP, desactivar SSL para que aplique el uso de TLS: `vserver services name-service ldap client modify -vserver vserver_name -client-config ldap_client_config_name -allow-ssl false`
. Compruebe que ya no se permite el uso de SSL en ningún cliente LDAP: `vserver services name-service ldap client show`


.Información relacionada
link:../nfs-admin/index.html["Gestión de NFS"]
