---
permalink: upgrade/task_verifying_the_san_configuration.html 
sidebar: sidebar 
keywords: ontap, upgrade, verify, verifying, san, configuration 
summary: Antes de actualizar un clúster SAN, debe comprobar que cada host esté configurado con el número correcto de rutas directas e indirectas y que cada host esté conectado a las LIF correctas. 
---
= Compruebe la configuración del host SAN antes de actualizar ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La actualización de ONTAP en un entorno SAN cambia qué rutas son directas. Antes de actualizar un clúster SAN, debe comprobar que cada host esté configurado con el número correcto de rutas directas e indirectas y que cada host esté conectado a las LIF correctas.

.Pasos
. En cada host, compruebe que se haya configurado un número suficiente de rutas directas e indirectas y que cada ruta esté activa.
+
Cada host debe tener una ruta a cada nodo del clúster.

. Compruebe que cada host está conectado a una LIF en cada nodo.
+
Debe registrar la lista de iniciadores para la comparación después de la actualización. Si ejecuta ONTAP 9.11.1 o una versión posterior, use System Manager para ver el estado de conexión, ya que muestra mucho más clara que la interfaz de línea de comandos.

+
[role="tabbed-block"]
====
.System Manager
--
.. En el Administrador del sistema, haga clic en *hosts > grupos de iniciadores DE SAN*.
+
La página muestra una lista de iGroups. Si la lista es grande, puede ver páginas adicionales de la lista haciendo clic en los números de página en la esquina inferior derecha de la página.

+
Las columnas muestran información diversa sobre los iGroups. A partir de 9.11.1, también se muestra el estado de conexión del igroup. Pase el ratón sobre las alertas de estado para ver detalles.



--
.CLI
--
** Mostrar iniciadores de iSCSI:
+
[source, cli]
----
iscsi initiator show -fields igroup,initiator-name,tpgroup
----
** Mostrar iniciadores de FC:
+
[source, cli]
----
fcp initiator show -fields igroup,wwpn,lif
----


--
====

