---
permalink: upgrade/task_verifying_the_san_configuration.html 
sidebar: sidebar 
keywords: ontap, upgrade, verify, verifying, san, configuration 
summary: Antes de actualizar un clúster SAN, debe comprobar que cada host esté configurado con el número correcto de rutas directas e indirectas y que cada host esté conectado a las LIF correctas. 
---
= Compruebe la configuración del host SAN antes de actualizar ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La actualización de ONTAP en un entorno SAN cambia qué rutas son directas. Antes de actualizar un clúster SAN, debe comprobar que cada host esté configurado con el número correcto de rutas directas e indirectas y que cada host esté conectado a las LIF correctas.

.Pasos
. En cada host, compruebe que se haya configurado un número suficiente de rutas directas e indirectas y que cada ruta esté activa.
+
Cada host debe tener una ruta a cada nodo del clúster.

. Compruebe que cada host está conectado a una LIF en cada nodo.
+
Debe registrar la lista de iniciadores para la comparación después de la actualización.

+
[cols="2*"]
|===
| Durante... | Introduzca... 


 a| 
ISCSI
 a| 
`iscsi initiator show -fields igroup,initiator-name,tpgroup`



 a| 
FC
 a| 
`fcp initiator show -fields igroup,wwpn,lif`

|===

