---
permalink: upgrade/task_setting_the_desired_nt_acl_permissions_display_level_for_nfs_clients.html 
sidebar: sidebar 
keywords: ontap, upgrade, setting, set, desired, nt, acl, permissions, display, level, nfs, clients 
summary: Después de actualizar desde ONTAP 8.3.0, el manejo predeterminado para mostrar permisos ACL de NT a clientes NFS ha cambiado. Compruebe el ajuste y cámbielo a la configuración deseada para su entorno si es necesario. Esta tarea no se aplica si se va a actualizar desde ONTAP 8.3.1 o una versión posterior. 
---
= Establecer el nivel de visualización de los permisos de ACL de NT deseados para los clientes NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de actualizar desde ONTAP 8.3.0, el manejo predeterminado para mostrar permisos ACL de NT a clientes NFS ha cambiado. Compruebe el ajuste y cámbielo a la configuración deseada para su entorno si es necesario. Esta tarea no se aplica si se va a actualizar desde ONTAP 8.3.1 o una versión posterior.

En entornos multiprotocolo, ONTAP muestra a los clientes NFS los permisos de los archivos y directorios de seguridad NTFS basados en el acceso concedido por la ACL de NT a cualquier usuario. En ONTAP 8.3.0, ONTAP muestra de forma predeterminada a los clientes NFS el permiso basado en el acceso máximo concedido por la ACL de NT. Después de actualizar, la configuración predeterminada cambia a los permisos de visualización basados en el acceso mínimo concedido por la ACL de NT. Este cambio se aplica a máquinas virtuales de almacenamiento (SVM) nuevas y existentes.

. Configure el nivel de privilegio en Advanced: `set -privilege advanced`
. Compruebe la configuración para mostrar los permisos ACL de NT para los clientes NFS: `vserver nfs show -vserver vserver_name -fields ntacl-display-permissive-perms`
+
Después de actualizar desde 8.3.0, el valor de este nuevo parámetro está deshabilitado, lo que significa que ONTAP muestra los permisos mínimos.

. Si prefiere mostrar el número máximo de permisos, cambie la configuración de forma individual para cada SVM según lo desee: `vserver nfs modify -vserver vserver_name -ntacl-display-permissive-perms enabled`
. Compruebe que el cambio surta efecto: `vserver nfs show -vserver vserver_name -fields ntacl-display-permissive-perms`
. Vuelva al nivel de privilegio de administrador: `set -privilege admin`

