---
permalink: upgrade/task_verifying_the_san_configuration_after_an_upgrade.html 
sidebar: sidebar 
keywords: ontap, upgrade, post, after, san, verify 
summary: Tras una actualización de ONTAP, en un entorno SAN, compruebe que cada iniciador que estaba conectado a una LIF antes de que la actualización se haya vuelto a conectar correctamente a la LIF 
---
= Comprobar la configuración DE SAN tras una actualización
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tras una actualización de ONTAP, en un entorno SAN, debe verificar que cada iniciador que esté conectado a una LIF antes de que la actualización se haya reconectado correctamente a la LIF.

. Compruebe que cada iniciador está conectado a la LIF correcta.
+
Debe comparar la lista de iniciadores con la lista que ha realizado durante la preparación de la actualización. Si ejecuta ONTAP 9.11.1 o una versión posterior, use System Manager para ver el estado de conexión, ya que muestra mucho más clara que la interfaz de línea de comandos.

+
[role="tabbed-block"]
====
.System Manager
--
.. En el Administrador del sistema, haga clic en *hosts > grupos de iniciadores DE SAN*.
+
La página muestra una lista de iGroups. Si la lista es grande, puede ver páginas adicionales de la lista haciendo clic en los números de página en la esquina inferior derecha de la página.

+
Las columnas muestran información diversa sobre los iGroups. A partir de 9.11.1, también se muestra el estado de conexión del igroup. Pase el ratón sobre las alertas de estado para ver detalles.



--
.CLI
--
** Mostrar iniciadores de iSCSI:
+
[source, cli]
----
iscsi initiator show -fields igroup,initiator-name,tpgroup
----
** Mostrar iniciadores de FC:
+
[source, cli]
----
fcp initiator show -fields igroup,wwpn,lif
----


--
====

