---
permalink: upgrade/task_preparing_to_upgrade_nodes_using_netapp_storage_encryption_with_external_key_management_servers.html 
sidebar: sidebar 
keywords: ontap, upgrade, prepare, preparing, nodes, netapp, storage, encryption, nse, external, key management, servers 
summary: Si utiliza el cifrado de almacenamiento de NetApp en ONTAP 9,2 o una versión anterior y actualiza a 9,3 o una versión posterior, elimine las conexiones del servidor de gestión de claves externo antes de la actualización. 
---
= Elimine las conexiones del servidor de gestión de claves externo existentes antes de actualizar ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de actualizar ONTAP, si ejecuta ONTAP 9,2 o una versión anterior con el cifrado de almacenamiento de NetApp (NSE) y se actualiza a ONTAP 9,3 o posterior, debe utilizar la interfaz de línea de comandos (CLI) para eliminar cualquier conexión existente del servidor de gestión de claves externa (KMIP).

.Pasos
. Compruebe que las unidades NSE estén desbloqueadas, abiertas y configuradas con el ID seguro de fabricación predeterminado 0x0:
+
[source, cli]
----
storage encryption disk show -disk *
----
. Entre en el modo de privilegio avanzado:
+
[source, cli]
----
set -privilege advanced
----
. Utilice el ID seguro de fabricación predeterminado 0x0 para asignar la clave FIPS a los discos de cifrado automático (SED):
+
[source, cli]
----
storage encryption disk modify -fips-key-id 0x0 -disk *
----
. Compruebe que se haya completado la asignación de la clave FIPS a todos los discos:
+
[source, cli]
----
storage encryption disk show-status
----
. Verifique que el *mode* para todos los discos esté configurado en data
+
[source, cli]
----
storage encryption disk show
----
. Vea los servidores KMIP configurados:
+
[source, cli]
----
security key-manager show
----
. Elimine los servidores KMIP configurados:
+
[source, cli]
----
security key-manager delete -address <kmip_ip_address>
----
. Elimine la configuración del gestor de claves externo:
+
[source, cli]
----
security key-manager delete-kmip-config
----
+

NOTE: Este paso no quita los certificados de NSE.



.El futuro
Una vez completada la actualización, debe hacerlo xref:task_reconfiguring_kmip_servers_connections_after_upgrading_to_ontap_9_3_or_later.adoc[Vuelva a configurar las conexiones del servidor KMIP].
