---
permalink: upgrade/task_verifying_the_networking_and_storage_status_for_metrocluster_post_upgrade.html 
sidebar: sidebar 
keywords: ontap, post, after, upgrade, verify, network, networking, storage, status, metrocluster, mcc 
summary: Después de realizar una actualización en una configuración de MetroCluster, compruebe el estado de las LIF, los agregados y los volúmenes de cada clúster. 
---
= Comprobar el estado de red y almacenamiento de las configuraciones de MetroCluster tras una actualización de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de actualizar un clúster de ONTAP en una configuración de MetroCluster, debe comprobar el estado de las LIF, los agregados y los volúmenes de cada clúster.

. Compruebe el estado de la LIF:
+
[source, cli]
----
network interface show
----
+
En un funcionamiento normal, los LIF de las SVM de origen deben tener el estado de administrador de en activo y estar ubicados en sus nodos raíz. Los LIF para las SVM de destino no necesitan estar en marcha o ubicados en sus nodos iniciales. Sin embargo, todos los LIF tienen el estado de administrador activo, pero no es necesario que estén ubicados en sus nodos iniciales.

+
[listing]
----
cluster1::> network interface show
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            cluster1-a1_clus1
                         up/up    192.0.2.1/24       cluster1-01
                                                                   e2a     true
            cluster1-a1_clus2
                         up/up    192.0.2.2/24       cluster1-01
                                                                   e2b     true


cluster1-01
            clus_mgmt    up/up    198.51.100.1/24    cluster1-01
                                                                   e3a     true
            cluster1-a1_inet4_intercluster1
                         up/up    198.51.100.2/24    cluster1-01
                                                                   e3c     true
            ...

27 entries were displayed.
----
. Compruebe el estado de los agregados:
+
[source, cli]
----
storage aggregate show -state !online
----
+
Este comando muestra todos los agregados que _not_ están en línea. En el funcionamiento normal, todos los agregados ubicados en el sitio local deben estar en línea. Sin embargo, si la configuración de MetroCluster está de conmutación, los agregados raíz del sitio de recuperación ante desastres pueden estar sin conexión.

+
Este ejemplo muestra un clúster en funcionamiento normal:

+
[listing]
----
cluster1::> storage aggregate show -state !online
There are no entries matching your query.
----
+
Este ejemplo muestra un clúster con conmutación de sitios, en el que los agregados raíz del sitio de recuperación ante desastres están sin conexión:

+
[listing]
----
cluster1::> storage aggregate show -state !online
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
aggr0_b1
                0B        0B    0% offline      0 cluster2-01      raid_dp,
                                                                   mirror
                                                                   degraded
aggr0_b2
                0B        0B    0% offline      0 cluster2-02      raid_dp,
                                                                   mirror
                                                                   degraded
2 entries were displayed.
----
. Compruebe el estado de los volúmenes:
+
[source, cli]
----
volume show -state !online
----
+
Este comando muestra los volúmenes que _not_ están en línea.

+
Si la configuración de MetroCluster tiene un funcionamiento normal (no está en estado de conmutación por sitios), el resultado debe mostrar todos los volúmenes que pertenecen a las SVM secundarias del clúster (los que tienen el nombre de SVM anexado con "-mc").

+
Esos volúmenes solo entran en línea en caso de que se produzca un cambio.

+
Este ejemplo muestra un clúster con un funcionamiento normal, en el cual los volúmenes del sitio de recuperación ante desastres no están en línea.

+
[listing]
----
cluster1::> volume show -state !online
  (volume show)
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vs2-mc    vol1         aggr1_b1     -          RW            -          -     -
vs2-mc    root_vs2     aggr0_b1     -          RW            -          -     -
vs2-mc    vol2         aggr1_b1     -          RW            -          -     -
vs2-mc    vol3         aggr1_b1     -          RW            -          -     -
vs2-mc    vol4         aggr1_b1     -          RW            -          -     -
5 entries were displayed.
----
. Compruebe que no haya volúmenes incoherentes:
+
[source, cli]
----
volume show -is-inconsistent true
----
+
Ver ellink:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Volume_Showing_WAFL_Inconsistent["Base de conocimientos de NetApp : Volumen que muestra WAFL inconsistente"^] sobre cómo abordar los volúmenes inconsistentes.


