---
sidebar: sidebar 
permalink: upgrade/task_upgrade_disruptive_automated_cli.html 
keywords: netapp, ontap, upgrade, nondisruptive, nondisruptively, non-disruptive update, nondisruptive upgrade, upgrade a cluster, shift workload between clusters, hardware platform, configuration, software image, update, update ONTAP, update software, ndu 
summary: A partir de ONTAP 9,2, se puede usar la interfaz de línea de comandos de ONTAP para realizar una actualización automatizada de un clúster de un solo nodo. Los clústeres de un solo nodo carecen de redundancia, por lo que las actualizaciones son disruptivas. 
---
= Actualización de ONTAP disruptiva automatizada (solo clúster de un solo nodo)
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partir de ONTAP 9,2, se puede usar la interfaz de línea de comandos de ONTAP para realizar una actualización automatizada de un clúster de un solo nodo. Como los clústeres de un solo nodo carecen de redundancia, las actualizaciones son siempre disruptivas. Las actualizaciones disruptivas no pueden llevarse a cabo mediante System Manager.

* Debe haber realizado una actualización satisfecha link:prepare.html["preparación"] requisitos.


.Pasos
. Elimine el paquete de software de ONTAP anterior:
+
[source, cli]
----
cluster image package delete -version previous_package_version
----
. Descargue el paquete de software de ONTAP de destino:
+
[source, cli]
----
cluster image package get -url location
----
+
[listing]
----
cluster1::> cluster image package get -url http://www.example.com/software/9.7/image.tgz

Package download completed.
Package processing completed.
----
. Compruebe que el paquete de software esté disponible en el repositorio del paquete de clúster:
+
[source, cli]
----
cluster image package show-repository
----
+
[listing]
----
cluster1::> cluster image package show-repository
Package Version  Package Build Time
---------------- ------------------
9.7              M/DD/YYYY 10:32:15
----
. Compruebe que el clúster esté listo para actualizarse:
+
[source, cli]
----
cluster image validate -version package_version_number
----
+
[listing]
----
cluster1::> cluster image validate -version 9.7

WARNING: There are additional manual upgrade validation checks that must be performed after these automated validation checks have completed...
----
. Supervise el progreso de la validación:
+
[source, cli]
----
cluster image show-update-progress
----
. Complete todas las acciones necesarias identificadas por la validación.
. Opcionalmente, genere un cálculo de actualización de software:
+
[source, cli]
----
cluster image update -version package_version_number -estimate-only
----
+
El cálculo aproximado de actualización de software muestra detalles sobre cada componente que se va a actualizar y la duración estimada de la actualización.

. Realice la actualización de software:
+
[source, cli]
----
cluster image update -version package_version_number
----
+

NOTE: Si se encuentra un problema, la actualización se detiene y le solicita que realice una acción correctiva. Puede utilizar el comando cluster image show-update-progress para ver detalles sobre cualquier problema y el progreso de la actualización. Una vez que corrija el problema, puede reanudar la actualización mediante el comando cluster image resume-update.

. Muestre el progreso de la actualización del clúster:
+
[source, cli]
----
cluster image show-update-progress
----
+
El nodo se reinicia como parte de la actualización y no se puede acceder a él mientras se reinicia.

. Activar una notificación:
+
[source, cli]
----
autosupport invoke -node * -type all -message "Finishing_Upgrade"
----
+
Si el clúster no está configurado para enviar mensajes, se guardará localmente una copia de la notificación.


