---
permalink: performance-admin/adaptive-qos-policy-groups-task.html 
sidebar: sidebar 
keywords: use, adaptive, qos, policy, groups 
summary: Puede usar un grupo de políticas de calidad de servicio adaptativo para escalar automáticamente un techo o un tamaño de piso a volumen, y mantener la ratio de IOPS a TB|GB a medida que cambie el tamaño del volumen. Esto es una ventaja importante si gestiona cientos o miles de cargas de trabajo en una puesta en marcha grande. 
---
= Utilice grupos de políticas de calidad de servicio adaptativos en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar un grupo de políticas _Adaptive QoS_ para escalar automáticamente un techo o un tamaño de piso a volumen y mantener la ratio de IOPS en TB|GB a medida que cambie el tamaño del volumen. Esto es una ventaja importante si gestiona cientos o miles de cargas de trabajo en una puesta en marcha grande.

.Antes de empezar
* Debe ejecutar ONTAP 9,3 o una versión posterior. Los grupos de políticas de calidad de servicio adaptativa están disponibles a partir de ONTAP 9.3.
* Para crear un grupo de políticas, debe ser un administrador de clústeres.


.Acerca de esta tarea
Un objeto de almacenamiento puede ser miembro de un grupo de políticas adaptables o de un grupo de políticas no adaptativas, pero no ambos. La SVM del objeto de almacenamiento y la política deben ser iguales. El objeto de almacenamiento debe estar en línea.

Los grupos de políticas de calidad de servicio adaptativos siempre no son compartidos: El techo o el piso de rendimiento definidos se aplican a la carga de trabajo de cada miembro de forma individual.

La relación de límites de rendimiento con el tamaño de objeto de almacenamiento se determina por la interacción de los siguientes campos:

* `expected-iops` Es el valor mínimo esperado de IOPS por TB|GB asignado.
+
[NOTE]
====
 `expected-iops` Solo está garantizado en plataformas AFF. `expected-iops` Está garantizado para FabricPool solo si la política de organización en niveles está establecida en «ninguno» y no hay bloques en la nube. `expected-iops` Está garantizada para volúmenes que no están en una relación síncrona de SnapMirror.

====
* `peak-iops` Es la tasa máxima de IOPS posible por TB|GB asignado o utilizado.
* `expected-iops-allocation` especifica si se utiliza el espacio asignado (el valor predeterminado) o el espacio utilizado para expected-iops.
+
[NOTE]
====
`expected-iops-allocation` Está disponible en ONTAP 9, 5 y posterior. No es compatible con ONTAP 9.4 y versiones anteriores.

====
* `peak-iops-allocation` especifica si se utiliza el espacio asignado o el espacio utilizado (el valor por defecto) para `peak-iops`.
*  `absolute-min-iops` Es el número mínimo absoluto de IOPS. Puede utilizar este campo con objetos de almacenamiento muy pequeños. Sustituye tanto `peak-iops` y/o `expected-iops` cuando `absolute-min-iops` es mayor que el calculado `expected-iops`.
+
Por ejemplo, si establece `expected-iops` en 1.000 IOPS/TB y el tamaño del volumen es inferior a 1 GB, el calculado `expected-iops` será un IOP fraccionario. El calculado `peak-iops` será una fracción aún más pequeña. Puede evitarlo estableciendo `absolute-min-iops` un valor realista.

* `block-size` Especifica el tamaño del bloque de I/O de la aplicación. El valor predeterminado es 32K. Los valores válidos son 8K, 16K, 32K, 64K, CUALQUIERA. CUALQUIER significa que no se aplica el tamaño de los bloques.


Existen tres grupos de políticas de calidad de servicio adaptativas predeterminados disponibles, como se muestra en la siguiente tabla. Puede aplicar estos grupos de políticas directamente a un volumen.

|===


| Grupo de políticas predeterminado | Tasa prevista de IOPS/TB | Pico de IOPS/TB | IOPS mín. Absoluto 


 a| 
`extreme`
 a| 
6.144
 a| 
12.288
 a| 
1000



 a| 
`performance`
 a| 
2.048
 a| 
4.096
 a| 
500



 a| 
`value`
 a| 
128
 a| 
512
 a| 
75

|===
No puede asignar un objeto de almacenamiento a un grupo de políticas si su objeto que contiene o sus objetos secundarios pertenecen a un grupo de políticas. En la siguiente tabla se enumeran las restricciones.

|===
| Si asigna... | No puede asignar... 


 a| 
SVM a un grupo de políticas
 a| 
Todos los objetos de almacenamiento que contiene la SVM a un grupo de políticas



 a| 
Del volumen a un grupo de políticas
 a| 
El volumen que contiene la SVM o cualquier LUN secundario a un grupo de políticas



 a| 
LUN a un grupo de políticas
 a| 
El volumen o la SVM que contiene el LUN a un grupo de políticas



 a| 
Archivo a un grupo de políticas
 a| 
El volumen o la SVM del archivo a un grupo de políticas

|===
.Pasos
. Cree un grupo de políticas de calidad de servicio adaptativo:
+
`qos adaptive-policy-group create -policy group _policy_group_ -vserver _SVM_ -expected-iops _number_of_iops_/TB|GB -peak-iops _number_of_iops_/TB|GB -expected-iops-allocation-space|used-space -peak-iops-allocation allocated-space|used-space -absolute-min-iops _number_of_iops_ -block-size 8K|16K|32K|64K|ANY`

+
Obtenga más información sobre `qos adaptive-policy-group create` en el link:https://docs.netapp.com/us-en/ontap-cli/qos-adaptive-policy-group-create.html["Referencia de comandos del ONTAP"^].

+
[NOTE]
====
`-expected-iops-allocation` Y `-block-size` está disponible en ONTAP 9, 5 y posterior. Estas opciones no son compatibles con ONTAP 9.4 y versiones anteriores.

====
+
El siguiente comando crea un grupo de políticas de calidad de servicio adaptativa `adpg-app1` con `-expected-iops` un establecido en 300 IOPS/TB, `-peak-iops` se `-peak-iops-allocation` establece en 1.000 IOPS/TB, se establece en `used-space`y `-absolute-min-iops` se establece en 50 IOPS:

+
[listing]
----
cluster1::> qos adaptive-policy-group create -policy group adpg-app1 -vserver vs2 -expected-iops 300iops/tb -peak-iops 1000iops/TB -peak-iops-allocation used-space -absolute-min-iops 50iops
----
. Aplique un grupo de políticas de calidad de servicio adaptable a un volumen:
+
`volume create -vserver SVM -volume _volume_ -aggregate _aggregate_ -size _number_of_ TB|GB -qos-adaptive-policy-group _policy_group_`

+
Obtenga más información sobre `volume create` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["Referencia de comandos del ONTAP"^].

+
El siguiente comando aplica un grupo de políticas de calidad de servicio adaptativas `adpg-app1` al `app1` volumen :

+
[listing]
----
cluster1::> volume create -vserver vs1 -volume app1 -aggregate aggr1 -size 2TB -qos-adaptive-policy-group adpg-app1
----
+
Los siguientes comandos aplican el grupo de políticas de calidad de servicio adaptativa predeterminado `extreme` al volumen nuevo `app4` y al volumen existente `app5`. El techo de rendimiento definido para el grupo de políticas se aplica a los volúmenes `app4` y `app5` de forma individual:

+
[listing]
----
cluster1::> volume create -vserver vs4 -volume app4 -aggregate aggr4 -size 2TB -qos-adaptive-policy-group extreme
----
+
[listing]
----
cluster1::> volume modify -vserver vs5 -volume app5 -qos-adaptive-policy-group extreme
----

