---
permalink: performance-admin/check-iscsi-tcp-read-write-size-task.html 
sidebar: sidebar 
keywords: check, iscsi, tcp, read, write, size 
summary: Para iSCSI, es posible comprobar el tamaño de lectura o escritura de TCP para determinar si la configuración de tamaño está creando un problema de rendimiento. Si el tamaño es el origen de un problema, puede corregirlo. 
---
= Compruebe el tamaño de lectura/escritura del TCP de iSCSI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para iSCSI, es posible comprobar el tamaño de lectura/escritura de TCP para determinar si la configuración de tamaño está creando un problema de rendimiento. Si el tamaño es el origen de un problema, puede corregirlo.

.Antes de empezar
Para esta tarea, se requieren comandos de nivel de privilegio avanzado.

.Pasos
. Cambie al nivel de privilegio avanzado:
+
`set -privilege advanced`

. Compruebe la configuración del tamaño de la ventana TCP:
+
`vserver iscsi show -vserv,er _vserver_name_ -instance`

. Modifique la configuración del tamaño de la ventana TCP:
+
`vserver iscsi modify -vserver _vserver_name_ -tcp-window-size _integer_`

. Devolver al privilegio administrativo:
+
`set -privilege admin`



.Ejemplo
En el ejemplo siguiente se cambia el tamaño de la ventana TCP de `SVM1` a 131.400 bytes:

[listing]
----
cluster1::*> vserver iscsi modify -vserver vs1 -tcp-window-size 131400
----