---
permalink: performance-admin/check-nfs-tcp-read-write-size-task.html 
sidebar: sidebar 
keywords: check, nfs, tcp, maximum, transfer, size 
summary: Para NFS, puede comprobar si el tamaño máximo de transferencia TCP para lecturas y escrituras puede estar provocando un problema de rendimiento. Si cree que el tamaño ralentiza el rendimiento, puede aumentarlo. 
---
= Compruebe el tamaño máximo de transferencia de TCP de NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para NFS, puede comprobar si el tamaño máximo de transferencia TCP para lecturas y escrituras puede estar provocando un problema de rendimiento. Si cree que el tamaño ralentiza el rendimiento, puede aumentarlo.

.Antes de empezar
* Para realizar esta tarea, debe tener privilegios de administrador de clúster.
* Para esta tarea, debe utilizar comandos de nivel de privilegio avanzado.


.Pasos
. Cambie al nivel de privilegio avanzado:
+
`set -privilege advanced`

. Compruebe el tamaño máximo de transferencia TCP:
+
`vserver nfs show -vserver _vserver_name_ -instance`

. Si el tamaño máximo de transferencia del TCP es demasiado pequeño, aumente el tamaño:
+
`vserver nfs modify -vserver _vserver_name_ -tcp-max-xfer-size _integer_`

. Volver al nivel de privilegio administrativo:
+
`set -privilege admin`



.Ejemplo
En el ejemplo siguiente se cambia el tamaño de transferencia máximo `SVM1` de TCP de a 1048576:

[listing]
----
cluster1::*> vserver nfs modify -vserver SVM1 -tcp-max-xfer-size 1048576
----