---
permalink: performance-admin/check-fc-adapter-port-speed-task.html 
sidebar: sidebar 
keywords: check, fc, adapter, port, speed 
summary: La velocidad del puerto de destino del adaptador debe coincidir con la velocidad del dispositivo al que se conecta, para optimizar el rendimiento. Si el puerto está definido en autonegociación, puede tardar más en reconectar después de una toma de control y devolución u otra interrupción. 
---
= Verifique la velocidad del puerto del adaptador ONTAP FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La velocidad del puerto de destino del adaptador debe coincidir con la velocidad del dispositivo al que se conecta, para optimizar el rendimiento. Si el puerto está definido en autonegociación, puede tardar más en reconectar después de una toma de control y devolución u otra interrupción.

.Antes de empezar
Todos los LIF que utilizan este adaptador como puerto de inicio deben estar desconectados.

.Pasos
. Desconectar el adaptador:
+
`network fcp adapter modify -node _nodename_ -adapter _adapter_ -state _down_`

+
Obtenga más información sobre `network fcp adapter modify` en el link:https://docs.netapp.com/us-en/ontap-cli/network-fcp-adapter-modify.html["Referencia de comandos del ONTAP"^].

. Compruebe la velocidad máxima del adaptador de puerto:
+
`fcp adapter show -instance`

+
Obtenga más información sobre `fcp adapter show` en el link:https://docs.netapp.com/us-en/ontap-cli/network-fcp-adapter-show.html["Referencia de comandos del ONTAP"^].

. Cambie la velocidad del puerto, si es necesario:
+
`network fcp adapter modify -node _nodename_ -adapter _adapter_ -speed {1|2|4|8|10|16|auto}`

. Conectar el adaptador:
+
`network fcp adapter modify -node _nodename_ -adapter _adapter_ -state up`

. Conectar todas las LIF del adaptador:
+
`network interface modify -vserver * -lif * { -home-node node1 -home-port e0c } -status-admin up`

+
Obtenga más información sobre `network interface modify` en el link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["Referencia de comandos del ONTAP"^].



.Ejemplo
En el siguiente ejemplo se cambia la velocidad del puerto del adaptador `0d` `node1` a 2 Gbps:

[listing]
----
cluster1::> network fcp adapter modify -node node1 -adapter 0d -speed 2
----