---
permalink: performance-admin/configure-alert-settings-task.html 
sidebar: sidebar 
keywords: configure, alert, settings, 
summary: Es posible especificar qué eventos de Active IQ Unified Manager desencadenan las alertas, los destinatarios de correo electrónico para esas alertas y la frecuencia de las alertas. 
---
= Configure los ajustes de alerta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible especificar qué eventos de Active IQ Unified Manager desencadenan las alertas, los destinatarios de correo electrónico para esas alertas y la frecuencia de las alertas.

.Lo que necesitará
Debe tener la función Administrador de aplicaciones.

.Acerca de esta tarea
Puede configurar ajustes de alerta únicos para los siguientes tipos de eventos de rendimiento:

* Eventos críticos desencadenados por infracciones de umbrales definidos por el usuario
* Eventos de advertencia provocados por infracciones de umbrales definidos por el usuario, umbrales definidos por el sistema o umbrales dinámicos


De manera predeterminada, las alertas por correo electrónico se envían a los usuarios administradores de Unified Manager para todos los eventos nuevos. Es posible que se envíen alertas por correo electrónico a otros usuarios con la adición de las direcciones de correo electrónico de esos usuarios.

[NOTE]
====
Para deshabilitar el envío de alertas para determinados tipos de eventos, debe desactivar todas las casillas de comprobación de una categoría de eventos. Esta acción no detiene que los eventos aparezcan en la interfaz de usuario.

====
.Pasos
. En el panel de navegación izquierdo, seleccione *Administración de almacenamiento* > *Configuración de alertas*.
+
Aparecerá la página Configuración de alertas.

. Haga clic en *Agregar* y configure los valores adecuados para cada uno de los tipos de evento.
+
Para que se envíen alertas de correo electrónico a varios usuarios, introduzca una coma entre cada dirección de correo electrónico.

. Haga clic en *Guardar*.

