---
permalink: performance-admin/identify-most-active-instance-task.html 
sidebar: sidebar 
keywords: identify, high-traffic, clients files 
summary: Puede utilizar la tecnología ONTAP Active Objects para identificar clientes o archivos que son responsables de una cantidad desproporcionadamente grande del tráfico del clúster. Cuando haya identificado estos archivos o clientes «principales», podrá reequilibrar las cargas de trabajo del clúster o realizar otros pasos para resolver el problema. 
---
= Identifique ficheros o clientes con un gran tráfico en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar la tecnología ONTAP Active Objects para identificar clientes o archivos que son responsables de una cantidad desproporcionadamente grande del tráfico del clúster. Cuando haya identificado estos archivos o clientes «principales», podrá reequilibrar las cargas de trabajo del clúster o realizar otros pasos para resolver el problema.

.Lo que necesitará
Para realizar esta tarea, debe ser un administrador de clústeres.

.Pasos
. Vea los principales clientes que acceden al clúster:
+
`statistics top client show -node _node_name_ -sort-key _sort_column_ -interval _seconds_between_updates_ -iterations _iterations_ -max _number_of_instances_`

+
Obtenga más información sobre `statistics top client show` en el link:https://docs.netapp.com/us-en/ontap-cli/statistics-top-client-show.html["Referencia de comandos de la ONTAP"^].

+
El siguiente comando muestra los principales clientes que acceden `cluster1`:

+
[listing]
----
cluster1::> statistics top client show

cluster1 : 3/23/2016 17:59:10


                                               *Total
        Client Vserver           Node Protocol    Ops
-------------- ------- -------------- -------- ------
172.17.180.170     vs4 siderop1-vsim4      nfs    668
172.17.180.169     vs3 siderop1-vsim3      nfs    337
172.17.180.171     vs3 siderop1-vsim3      nfs    142
172.17.180.170     vs3 siderop1-vsim3      nfs    137
172.17.180.123     vs3 siderop1-vsim3      nfs    137
172.17.180.171     vs4 siderop1-vsim4      nfs     95
172.17.180.169     vs4 siderop1-vsim4      nfs     92
172.17.180.123     vs4 siderop1-vsim4      nfs     92
172.17.180.153     vs3 siderop1-vsim3      nfs      0
----
. Vea los archivos principales a los que se accede en el clúster:
+
`statistics top file show -node _node_name_ -sort-key _sort_column_ -interval _seconds_between_updates_ -iterations _iterations_ -max _number_of_instances_`

+
Obtenga más información sobre `statistics top file show` en el link:https://docs.netapp.com/us-en/ontap-cli/statistics-top-file-show.html["Referencia de comandos de la ONTAP"^].

+
El siguiente comando muestra los principales archivos en los que se puede acceder `cluster1`:

+
[listing]
----
cluster1::> statistics top file show

cluster1 : 3/23/2016 17:59:10

					              *Total
                    File Volume Vserver          Node    Ops
------------------------ ------ ------- -------------- ------
/vol/vol1/vm170-read.dat   vol1     vs4 siderop1-vsim4     22
/vol/vol1/vm69-write.dat   vol1     vs3 siderop1-vsim3      6
     /vol/vol2/vm171.dat   vol2     vs3 siderop1-vsim3      2
     /vol/vol2/vm169.dat   vol2     vs3 siderop1-vsim3      2
      /vol/vol2/p123.dat   vol2     vs4 siderop1-vsim4      2
      /vol/vol2/p123.dat   vol2     vs3 siderop1-vsim3      2
     /vol/vol1/vm171.dat   vol1     vs4 siderop1-vsim4      2
     /vol/vol1/vm169.dat   vol1     vs4 siderop1-vsim4      2
     /vol/vol1/vm169.dat   vol1     vs4 siderop1-vsim3      2
      /vol/vol1/p123.dat   vol1     vs4 siderop1-vsim4      2
----

