---
permalink: performance-admin/policy-group-assignment-restrictions.html 
sidebar: sidebar 
keywords: use, adaptive, qos, policy, groups 
summary: Puede usar un grupo de políticas de calidad de servicio adaptativo para escalar automáticamente un techo o un tamaño de piso a volumen, y mantener la ratio de IOPS a TB|GB a medida que cambie el tamaño del volumen. Esto es una ventaja importante si gestiona cientos o miles de cargas de trabajo en una puesta en marcha grande. 
---
= Restricciones de asignación de grupos de políticas de QoS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.18.1, puede usar políticas QoS anidadas, que permiten asignar grupos de políticas tanto al objeto contenedor, como un SVM, como a su objeto hijo, como un volumen.  En un entorno multiusuario, las políticas QoS anidadas permiten a los administradores subdividir los límites QoS en las SVM entre los volúmenes y qtrees dentro de la SVM, y proporcionar la capacidad de equilibrar los recursos de almacenamiento en los entornos informáticos, al tiempo que permiten priorizar las cargas de trabajo críticas para la misión.

Las políticas QoS anidadas son compatibles con los siguientes pares de objetos:

* SVM y volúmenes FlexVol o FlexGroup contenidos por el SVM.
* Volúmenes FlexVol o FlexGroup y qtrees dentro de los volúmenes.


Para políticas QoS anidadas, se utiliza la política aplicable más restrictiva.

La siguiente tabla enumera las restricciones.

|===
| Si asigna... | Entonces no puedes asignarlo a un grupo de políticas... 


 a| 
SVM a un grupo de políticas
 a| 
Cualquier objeto de almacenamiento contenido por la SVM.


NOTE: Si está ejecutando ONTAP 9.18.1, los volúmenes FlexVol y FlexGroup contenidos en las SVM _pueden_ asignarse a un grupo de políticas.



 a| 
Del volumen a un grupo de políticas
 a| 
La SVM que contiene el volumen o cualquier LUN hijo.


NOTE: Si está ejecutando ONTAP 9.18.1 o posterior, el SVM que contiene el volumen _puede_ asignarse a un grupo de políticas.  Además, se pueden asignar qtrees en volúmenes FlexVol o FlexGroup .



 a| 
LUN a un grupo de políticas
 a| 
El volumen o SVM que contiene las LUN



 a| 
Archivo a un grupo de políticas
 a| 
El volumen o SVM que contiene el archivo

|===