---
permalink: performance-admin/verify-environment-supported-task.html 
sidebar: sidebar 
keywords: verify, vmware, environment, supported 
summary: Para instalar Active IQ Unified Manager correctamente, debe comprobar que el entorno de VMware cumple con los requisitos necesarios. 
---
= Verificar los requisitos del entorno de VMware para ONTAP Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalar Active IQ Unified Manager correctamente, debe comprobar que el entorno de VMware cumple con los requisitos necesarios.

.Pasos
. Compruebe que su infraestructura VMware cumple los requisitos de tamaño para la instalación de Unified Manager.
. Vaya a https://mysupport.netapp.com/matrix["Matriz de interoperabilidad"^] para comprobar que es compatible con una combinación de los siguientes componentes:
+
** Versión de ONTAP
** Versión del sistema operativo ESXi
** La versión de VMware vCenter Server
** Versión de VMware Tools
** Tipo y versión del navegador


+
[NOTE]
====
La matriz de interoperabilidad enumera las configuraciones compatibles para Unified Manager.

====
. Haga clic en el nombre de la configuración seleccionada.
+
Los detalles de esa configuración se muestran en la ventana Detalles de configuración.

. Revise la información en las siguientes pestañas:
+
** Notas
+
Enumera las alertas e información importantes que son específicas de su configuración.

** Políticas y directrices
+
Proporciona directrices generales para todas las configuraciones.




