---
permalink: performance-admin/weekly-monthly-performance-trends-identify-issues-task.html 
sidebar: sidebar 
keywords: Use, weekly, monthly, performance, trends, identify, issues 
summary: La identificación de las tendencias de rendimiento puede ayudarle a identificar si el clúster se está utilizando en exceso o está infrautilizado mediante el análisis de latencia de volumen. Puede seguir pasos similares para identificar cuellos de botella en la CPU, la red u otros sistemas. 
---
= Utilice las tendencias de rendimiento semanales y mensuales de ONTAP Active IQ Unified Manager para identificar problemas de rendimiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La identificación de las tendencias de rendimiento puede ayudarle a identificar si el clúster se está utilizando en exceso o está infrautilizado mediante el análisis de latencia de volumen. Puede seguir pasos similares para identificar cuellos de botella en la CPU, la red u otros sistemas.

.Pasos
. Localice el volumen que sospecha está infrautilizado o en exceso.
. En la ficha *Detalles de volumen*, haga clic en *30 d* para mostrar los datos históricos.
. En el menú desplegable "Break down data by", seleccione *latencia* y, a continuación, haga clic en *Enviar*.
. Anule la selección de *agregado* en el gráfico de comparación de componentes del clúster y, a continuación, compare la latencia del clúster con el gráfico de latencia del volumen.
. Seleccione *agregado* y anule la selección de todos los demás componentes del gráfico de comparación de componentes del clúster y, a continuación, compare la latencia de agregado con el gráfico de latencia de volumen.
. Compare el gráfico de latencia de lecturas/escrituras con el gráfico de latencia de volúmenes.
. Determine si las cargas de aplicaciones cliente han causado una contención de carga de trabajo y reequilibrio de cargas de trabajo según sea necesario.
. Determine si el agregado está sobrecargado y causa contención y reequilibre las cargas de trabajo según sea necesario.

