---
permalink: performance-admin/worksheet-reference.html 
sidebar: sidebar 
keywords: active iq unified manager, worksheet 
summary: Antes de instalar, configurar y conectar Active IQ Unified Manager, debe tener disponible información específica acerca de su entorno. Puede registrar la información en la hoja de cálculo. 
---
= Hoja de cálculo de Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar, configurar y conectar Active IQ Unified Manager, debe tener disponible información específica acerca de su entorno. Puede registrar la información en la hoja de cálculo.



== Información de instalación de Unified Manager

|===


| Máquina virtual en la que se ha puesto en marcha el software | Su valor 


 a| 
Dirección IP del servidor ESXi
 a| 



 a| 
Nombre de dominio completo del host
 a| 



 a| 
Dirección IP del host
 a| 



 a| 
Máscara de red
 a| 



 a| 
Dirección IP de la pasarela
 a| 



 a| 
Dirección DNS principal
 a| 



 a| 
Dirección DNS secundaria
 a| 



 a| 
Buscar dominios
 a| 



 a| 
Nombre de usuario de mantenimiento
 a| 



 a| 
Contraseña de usuario de mantenimiento
 a| 

|===


== Información de configuración de Unified Manager

|===


| Ajuste | Su valor 


 a| 
Dirección de correo electrónico del usuario de mantenimiento
 a| 



 a| 
Servidor NTP
 a| 



 a| 
Nombre de host o dirección IP del servidor SMTP
 a| 



 a| 
Nombre de usuario SMTP
 a| 



 a| 
Contraseña SMTP
 a| 



 a| 
Puerto predeterminado SMTP
 a| 
25 (valor predeterminado)



 a| 
Correo electrónico desde el cual se envían notificaciones de alerta
 a| 



 a| 
Nombre distintivo de enlace LDAP
 a| 



 a| 
Contraseña de enlace LDAP
 a| 



 a| 
Nombre del administrador de Active Directory
 a| 



 a| 
Contraseña de Active Directory
 a| 



 a| 
Nombre distintivo de la base del servidor de autenticación
 a| 



 a| 
Nombre de host o dirección IP del servidor de autenticación
 a| 

|===


== Información del clúster

Capture la siguiente información para cada clúster en Unified Manager.

|===


| Clúster 1 de N | Su valor 


 a| 
El nombre de host o la dirección IP de administración del clúster
 a| 



 a| 
Nombre de usuario del administrador ONTAP


NOTE: Debe haber asignado el rol de administrador.
 a| 



 a| 
Contraseña del administrador de ONTAP
 a| 



 a| 
Protocolo (HTTP o HTTPS)
 a| 

|===
.Información relacionada
link:../authentication/index.html["Autenticación de administrador y RBAC"]
