---
permalink: peering/index.html 
sidebar: sidebar 
keywords: decide, cluster, svm, peering, peer, relationships, source, destination, svm, storage, virtual, machines 
summary: 'Puede crear una relación entre iguales de clústeres de origen y de destino, y entre máquinas virtuales de almacenamiento (SVM) de origen y de destino.' 
---
= Información general sobre relaciones entre iguales de clústeres y SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear una relación entre iguales de clústeres de origen y de destino, y entre máquinas virtuales de almacenamiento (SVM) de origen y de destino. Debe crear relaciones entre iguales entre estas entidades antes de poder replicar copias de Snapshot con SnapMirror.

ONTAP 9.3 ofrece mejoras que simplifican la forma de configurar relaciones entre iguales entre clústeres y SVM. Los procedimientos de paridad de clústeres y SVM están disponibles para todas las versiones de ONTAP 9. Debe utilizar el procedimiento adecuado para su versión de ONTAP.

Los procedimientos se realizan mediante la interfaz de línea de comandos (CLI), no con System Manager ni con una herramienta de secuencias de comandos automatizadas.
