---
permalink: peering/peering-basics-concept.html 
sidebar: sidebar 
keywords: peer, basics 
summary: 'Los clústeres y las SVM en relaciones entre iguales se comunican a través de la red de interconexión de clústeres mediante interfaces lógicas de interconexión de clústeres (LIF). Una LIF de interconexión de clústeres es una LIF que admite el servicio de interfaz de red «núcleo entre clústeres» y se crea normalmente con la normativa de servicio de interfaz de red «predeterminada entre clústeres». Debe crear LIF de interconexión de clústeres en cada nodo en los clústeres que se van a establecer una relación entre iguales.' 
---
= Conceptos básicos de peering
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe crear _peer Relationships_ entre los clústeres de origen y de destino, y entre las SVM de origen y de destino antes de poder replicar copias de Snapshot con SnapMirror. Una relación de paridad define las conexiones de red que permiten que clústeres y SVM intercambien datos de forma segura.

Los clústeres y las SVM en relaciones entre iguales se comunican a través de la red de interconexión de clústeres mediante las interfaces lógicas de interconexión de clústeres (LIF)._ una LIF de interconexión de clústeres es una LIF compatible con el servicio de interfaz de red «núcleo entre clústeres» y normalmente se crea mediante la política de servicio de interfaz de red de «interconexión de clústeres predeterminada». Debe crear LIF de interconexión de clústeres en cada nodo en los clústeres que se van a establecer una relación entre iguales.

Las LIF de interconexión de clústeres utilizan las rutas que pertenecen a la SVM del sistema a la que se han asignado. ONTAP crea automáticamente una SVM del sistema para las comunicaciones a nivel de clúster dentro de un espacio IP.

Se admiten topologías en cascada y distribución ramificada. En una topología en cascada, solo necesita crear redes de interconexión de clústeres entre los clústeres principal y secundario, y entre los clústeres secundario y terciario. No es necesario crear una red de interconexión de clústeres entre el clúster principal y el terciario.

[NOTE]
====
Es posible (pero no aconsejable) que un administrador elimine el servicio interclúster-core de la directiva de servicio de interconexión de clústeres predeterminada. Si esto sucede, las LIF creadas con «interconexión de clústeres predeterminada» no serán realmente LIF de interconexión de clústeres. Para confirmar que la política de servicio de interconexión de clústeres predeterminada contiene el servicio principal entre clústeres, utilice el siguiente comando:

`network interface service-policy show -policy default-intercluster`

====