---
permalink: peering/remove-snapmirror-encryption-existing-relationship-task.html 
sidebar: sidebar 
keywords: remove, cluster, peering, encryption, existing, peer, relationship 
summary: De forma predeterminada, el cifrado de paridad de clústeres está habilitado en todas las relaciones entre iguales creadas en ONTAP 9.6 o posterior. Si no desea utilizar el cifrado para las comunicaciones entre clústeres entre iguales, puede deshabilitarlo. 
---
= Quite el cifrado de paridad de clústeres de una relación de paridad existente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
De forma predeterminada, el cifrado de paridad de clústeres está habilitado en todas las relaciones entre iguales creadas en ONTAP 9.6 o posterior. Si no desea utilizar el cifrado para las comunicaciones entre clústeres entre iguales, puede deshabilitarlo.

.Pasos
. En el clúster de destino, modifique las comunicaciones con el clúster de origen para interrumpir el uso del cifrado de interconexión de clústeres :
+
** Para eliminar el cifrado, pero mantener la autenticación, introduzca:
+
[source, cli]
----
cluster peer modify _source_cluster_ -auth-status-admin use-authentication -encryption-protocol-proposed none
----
** Para eliminar el cifrado y la autenticación, introduzca:
+
[source, cli]
----
cluster peer modify _source_cluster_ -auth-status no-authentication
----


. Cuando se le solicite, introduzca una frase de contraseña.
. En el clúster de origen, deshabilite el cifrado para la comunicación con el clúster de destino:
+
** Para eliminar el cifrado, pero mantener la autenticación, introduzca:
+
[source, cli]
----
cluster peer modify _destination_cluster_ -auth-status-admin use-authentication -encryption-protocol-proposed none
----
** Para eliminar el cifrado y la autenticación, introduzca:
+
[source, cli]
----
cluster peer modify _destination_cluster_ -auth-status no-authentication
----


. Cuando se le solicite, escriba la misma clave de acceso introducida en el clúster de destino.

