---
permalink: san-admin/backup-lun-host-backup-system-task.html 
sidebar: sidebar 
keywords: back up, lun, through, host, backup, system 
summary: Es posible usar un LUN clonado a partir de una snapshot como datos de origen para el sistema de backup del host. 
---
= Use un sistema de backup host para proteger una LUN en el sistema de almacenamiento ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible usar un LUN clonado a partir de una snapshot como datos de origen para el sistema de backup del host.

.Antes de empezar
Un LUN de producción debe existir y estar mapeado a un igroup que incluya el WWPN o el nombre de nodo iniciador del servidor de aplicaciones. El LUN también debe estar formateado y accesible para el host.

.Pasos
. Guarde el contenido de los búferes del sistema de archivos del host en el disco.
+
Puedes usar el comando proporcionado por tu sistema operativo host. También puedes optar por hacer que este paso sea parte de tu script de preprocesamiento de backup SAN.

. Crear una copia Snapshot de la LUN de producción.
+
[source, cli]
----
volume snapshot create -vserver <SVM_name> -volume <volume_name> -snapshot <snapshot> -comment <comment> -foreground false
----
. Crear un clon de la LUN de producción.
+
[source, cli]
----
volume file clone create -vserver <SMV_name> -volume <volume> -source-path <path> -snapshot-name <snapshot> -destination-path <destination_path>
----
. Cree un igroup que incluya el nombre de puerto WWPN del servidor de respaldo.
+
[source, cli]
----
lun igroup create -vserver <SVM_name> -igroup <igroup> -protocol <protocol> -ostype <os_type> -initiator <initiator>
----
. Asigne el clon de LUN que creó en el paso 3 al host de backup.
+
[source, cli]
----
lun mapping create -vserver <SVM_name> -volume <volume_name> -lun <lun_name> -igroup <igroup>
----
+
Puede optar por hacer que este paso forme parte de la secuencia de comandos de posprocesamiento de su aplicación DE backup SAN.

. Desde el host, detectar el nuevo LUN y hacer que el sistema de archivos esté disponible para el host.
+
Puede optar por hacer que este paso forme parte de la secuencia de comandos de posprocesamiento de su aplicación DE backup SAN.

. Realice un backup de los datos del clon LUN desde el host de backup a cinta con la aplicación de backup SAN.
. Desconectar el clon de la LUN.
+
[source, cli]
----
lun modify -vserver <SVM_name> -path <path> -state offline
----
. Quite el clon de la LUN.
+
[source, cli]
----
lun delete -vserver <SVM_name> -volume <volume> -lun <lun_name>
----
. Elimine la instantánea.
+
[source, cli]
----
volume snapshot delete -vserver <SVM_name> -volume <volume> -snapshot <snapshot>
----

