---
permalink: san-admin/clone-luns-active-volume-task.html 
sidebar: sidebar 
keywords: clone, luns, active, volume 
summary: Para crear copias de sus LUN, debe clonar las LUN en el volumen activo. Estas LUN FlexClone son copias legibles y editables de las LUN originales en el volumen activo. 
---
= Clonar las LUN de un volumen activo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para crear copias de sus LUN, debe clonar las LUN en el volumen activo. Estas LUN FlexClone son copias legibles y editables de las LUN originales en el volumen activo.


NOTE: Este procedimiento se aplica a los sistemas FAS, AFF y ASA actuales. Si tiene un sistema ASA R2 (ASA A1K, ASA A70 o ASA A90), después de link:https://docs.netapp.com/us-en/asa-r2/manage-data/data-cloning.html["estos pasos"^]clonar datos. Los sistemas R2 de ASA ofrecen una experiencia de ONTAP simplificada específica para clientes de SAN.

.Lo que necesitará
Debe instalar una licencia de FlexClone. Esta licencia se incluye con link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"].

.Acerca de esta tarea
Un LUN FlexClone con reserva de espacio requiere tanto espacio como la LUN principal con reserva de espacio. Si la LUN FlexClone no está reservada para el espacio, debe asegurarse de que el volumen tenga suficiente espacio para acomodar los cambios en la LUN FlexClone.

.Pasos
. Debe haber verificado que las LUN no están asignadas a un igroup o que se escriben en antes de crear el clon.
. Utilice la `lun show` Comando para comprobar que la LUN existe.
+
`lun show -vserver vs1`

+
[listing]
----
Vserver  Path              State     Mapped    Type     Size
-------- ----------------- --------- --------- -------- -------
vs1      /vol/vol1/lun1    online   unmapped  windows  47.07MB
----
. Utilice la `volume file clone create` Comando para crear la LUN FlexClone.
+
`volume file clone create -vserver vs1 -volume vol1 -source-path lun1 -destination-path/lun1_clone`

+
Si necesita que la LUN de FlexClone esté disponible para su eliminación automática, tendrá que incluir `-autodelete true`. Si crea este LUN FlexClone en un volumen mediante el aprovisionamiento semi-grueso, debe habilitar la eliminación automática para todas las LUN de FlexClone.

. Utilice la `lun show` Comando para verificar que ha creado una LUN.
+
`lun show -vserver vs1`

+
[listing]
----

Vserver  Path                    State    Mapped   Type     Size
-------- ----------------------- -------- -------- -------- ------
vs1      /vol/volX/lun1          online   unmapped windows  47.07MB
vs1      /vol/volX/lun1_clone    online   unmapped windows  47.07MB
----

