---
permalink: san-admin/configure-network-best-performance-task.html 
sidebar: sidebar 
keywords: configure, your, network, best, performance 
summary: Las redes Ethernet varían en gran medida en cuanto al rendimiento. Se puede maximizar el rendimiento de la red utilizada para iSCSI mediante la selección de valores de configuración específicos. 
---
= Configure su red para obtener el mejor rendimiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las redes Ethernet varían en gran medida en cuanto al rendimiento. Se puede maximizar el rendimiento de la red utilizada para iSCSI mediante la selección de valores de configuración específicos.

.Pasos
. Conecte los puertos de host y de almacenamiento a la misma red.
+
Se recomienda conectarse a los mismos conmutadores. No se debe usar el enrutamiento.

. Seleccione los puertos de mayor velocidad disponibles y dedicarlos a iSCSI.
+
Los puertos de 10 GbE son los mejores. Los puertos de 1 GbE son el mínimo.

. Desactive el control de flujo Ethernet para todos los puertos.
+
Debería ver link:../networking/networking_reference.html["Gestión de redes"] Para utilizar la CLI para configurar el control de flujo del puerto Ethernet.

. Habilitar tramas gigantes (normalmente MTU de 9000).
+
Todos los dispositivos de la ruta de datos, incluidos los iniciadores, los destinos y los switches, deben admitir tramas gigantes. De lo contrario, al habilitar tramas gigantes se reduce realmente el rendimiento de red considerablemente.


