---
permalink: san-admin/configure-nvme-lif-task.html 
sidebar: sidebar 
keywords: configure, nvme, lif 
summary: Deben satisfacerse ciertos requisitos al configurar las LIF de NVMe. 
---
= Configure un LIF NVMe en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Deben satisfacerse ciertos requisitos al configurar las LIF de NVMe.

.Antes de empezar
El adaptador de FC en el que se crea la LIF debe admitir NVMe. Los adaptadores admitidos se enumeran en https://hwu.netapp.com["Hardware Universe"^].

.Acerca de esta tarea
A partir de ONTAP 9.12.1 y versiones posteriores, puede configurar dos LIF NVMe por nodo en un máximo de 12 nodos. En ONTAP 9.11.1 y versiones anteriores, puede configurar dos LIF NVMe por nodo en un máximo de dos nodos.

Se aplican las siguientes reglas al crear una LIF NVMe:

* NVMe puede ser el único protocolo de datos en las LIF de datos.
* Debe configurar una LIF de gestión para cada SVM que sea compatible con SAN.
* Para ONTAP 9,5 y versiones posteriores, debe configurar un LIF NVMe en el nodo que contiene el espacio de nombres y en el partner de alta disponibilidad del nodo.
* Solo para ONTAP 9.4:
+
** Las LIF y los espacios de nombres de NVMe deben alojarse en el mismo nodo.
** Solo se puede configurar un LIF de datos NVMe por SVM.




.Pasos
. Cree la LIF:
+
[source, cli]
----
network interface create -vserver <SVM_name> -lif <LIF_name> -role <LIF_role> -data-protocol {fc-nvme|nvme-tcp} -home-node <home_node> -home-port <home_port>
----
+

NOTE: NVME/TCP está disponible a partir de ONTAP 9.10.1 y versiones posteriores.

. Compruebe que la LIF se ha creado:
+
[source, cli]
----
network interface show -vserver <SVM_name>
----


Después de la creación, las LIF NVMe/TCP reciben la detección en el puerto 8009.

.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["interfaz de red"^]

