---
permalink: san-admin/configure-switches-fcoe-task.html 
sidebar: sidebar 
keywords: configure, switches, fcoe 
summary: Debe configurar los switches de FCoE para que el servicio FC pueda ejecutarse en la infraestructura Ethernet existente. 
---
= Configurar los switches para FCoE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar los switches de FCoE para que el servicio FC pueda ejecutarse en la infraestructura Ethernet existente.

.Lo que necesitará
* Debe ser compatible con la configuración SAN.
+
Para obtener más información acerca de las configuraciones admitidas, consulte https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^].

* Se debe instalar un adaptador de objetivo unificado (UTA) en el sistema de almacenamiento.
+
Si utiliza un UTA2, debe configurarse en `cna` modo.

* Se debe instalar un adaptador de red convergente (CNA) en el host.


.Pasos
. Use la documentación de su switch para configurar los switches para FCoE.
. Compruebe que los ajustes de DCB para cada nodo del cluster se han configurado correctamente.
+
[source, cli]
----
run -node node1 -command dcb show
----
+
Los ajustes de DCB se configuran en el switch. Si los ajustes no son correctos, consulte la documentación del switch.

. Compruebe que el inicio de sesión FCoE funciona cuando el estado en línea del puerto de destino de FC es `true`.
+
[source, cli]
----
fcp adapter show -fields node,adapter,status,state,speed,fabric-established,physical-protocol
----
+
Si el estado en línea del puerto de destino FC es `false`, consulte la documentación del conmutador.



.Información relacionada
* https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^]
* http://www.netapp.com/us/media/tr-3800.pdf["Informe técnico de NetApp 3800: Guía de implementación integral de Fibre Channel sobre Ethernet (FCoE)"^]
* http://www.cisco.com/en/US/products/ps5989/products_installation_and_configuration_guides_list.html["Guías de configuración de software de Cisco MDS 9000 NX-OS y SAN-OS"]
* http://www.brocade.com/products/all/index.page["Productos Brocade"]

