---
permalink: san-admin/copy-luns-concept.html 
sidebar: sidebar 
keywords: considerations, copying, luns, before 
summary: Debe ser consciente de ciertas cosas antes de copiar una LUN. 
---
= Qué debe saber antes de copiar las LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe ser consciente de ciertas cosas antes de copiar una LUN.

Los administradores de clúster pueden copiar una LUN en las máquinas virtuales de almacenamiento (SVM) del clúster mediante `lun copy` el comando. Los administradores de clústeres deben establecer la relación entre iguales de máquinas virtuales de almacenamiento (SVM) mediante `vserver peer create` el comando antes de llevar a cabo una operación de copia de LUN entre SVM. Debe haber suficiente espacio en el volumen de origen para un clon SIS.

Las LUN de las snapshots se pueden usar como LUN de origen `lun copy` del comando. Cuando copia una LUN mediante `lun copy` el comando, la copia LUN está disponible inmediatamente para acceso de lectura y escritura. La LUN de origen no se modifica por la creación de una copia LUN. Tanto la LUN de origen como la copia LUN existen como LUN únicas con diferentes números de serie de LUN. Los cambios realizados en la LUN de origen no se reflejan en la copia LUN, y los cambios realizados en la copia LUN no se reflejan en la LUN de origen. La asignación de la LUN de origen no se copia en la nueva LUN; es necesario asignar la copia LUN.

La protección de datos mediante copias Snapshot se produce a nivel de volumen. Por lo tanto, si copia una LUN en un volumen distinto del volumen de la LUN de origen, la LUN de destino cae en el esquema de protección de datos del volumen de destino. Si no hay copias de Snapshot establecidas para el volumen de destino, no se crean Snapshot de la copia de LUN.

La copia de LUN es una operación no disruptiva.

No se pueden copiar los siguientes tipos de LUN:

* LUN creada a partir de un archivo
* Una LUN con el estado NVFAIL
* LUN en una relación de uso compartido de carga
* LUN de clase de extremo de protocolo


Obtenga más información sobre `lun copy` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=lun+copy["Referencia de comandos del ONTAP"^].
