---
permalink: san-admin/edit-lun-qos-policy-task.html 
sidebar: sidebar 
keywords: system manager, san, lun, qos, group, policy, quality, service, edit, editing, update, updating, change, changing 
summary: 'A partir de ONTAP 9.10.1, puede usar System Manager para asignar o quitar políticas de calidad de servicio (QoS) en varias LUN a la vez.' 
---
= Editar el grupo de políticas de calidad de servicio de la LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.10.1, puede usar System Manager para asignar o quitar políticas de calidad de servicio (QoS) en varias LUN a la vez.


NOTE: Si se asigna la política de calidad de servicio en el nivel del volumen, se debe cambiar en el nivel del volumen. Solo puede editar la política de calidad de servicio en el nivel de LUN si originalmente se asignó en el nivel de LUN.

.Pasos
. En System Manager, haga clic en *almacenamiento > LUN*.
. Seleccione la LUN o los LUN que desee editar.
+
Si edita más de una LUN a la vez, las LUN deben pertenecer a la misma máquina virtual de almacenamiento (SVM). Si selecciona los LUN que no pertenecen a la misma SVM, no se muestra la opción para editar el grupo de políticas de calidad de servicio.

. Haga clic en *más* y seleccione *Editar grupo de políticas QoS*.

