---
permalink: san-admin/flexclone-luns-protect-your-data-concept.html 
sidebar: sidebar 
keywords: use, flexclone, luns, protect, your, data 
summary: Una LUN de FlexClone es una copia editable de un momento específico de otra LUN en un volumen activo o en una copia de Snapshot. El clon y su primario se pueden modificar de forma independiente sin que se vean afectados. 
---
= Proteja sus datos con las LUN de ONTAP FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una LUN de FlexClone es una copia editable de un momento específico de otra LUN en un volumen activo o en una copia de Snapshot. El clon y su primario se pueden modificar de forma independiente sin que se vean afectados.

Puede utilizar las LUN FlexClone para crear varias copias de lectura/escritura de una LUN.

.Motivos para crear LUN de FlexClone
* Debe crear una copia temporal de una LUN para fines de pruebas.
* Debe realizar una copia de sus datos disponibles a usuarios adicionales sin tener que darles acceso a los datos de producción.
* Desea crear un clon de una base de datos para operaciones de manipulación y proyección, al mismo tiempo que se conservan los datos originales sin alterarlos.
* Quieres acceder a un subconjunto específico de los datos de un LUN (un volumen lógico específico o un sistema de archivos en un grupo de volúmenes, o un archivo específico o un conjunto de archivos en un sistema de archivos) y copiarlo al LUN original, sin restaurar el resto de los datos en el LUN original. Esto funciona en sistemas operativos que admiten montar un LUN y un clon del LUN al mismo tiempo.
* Necesita varios hosts DE arranque SAN con el mismo sistema operativo.


Una LUN FlexClone comparte espacio inicialmente con su LUN principal. De forma predeterminada, la LUN FlexClone hereda el atributo de espacio reservado de la LUN principal. Por ejemplo, si la LUN principal no está reservada a espacio, la LUN FlexClone también está sin la reserva de espacio de forma predeterminada. Sin embargo, puede crear una LUN FlexClone sin reservar espacio desde un elemento principal que es una LUN con reserva de espacio.

Cuando se clona una LUN, el uso compartido de bloques se realiza en segundo plano y no se puede crear una snapshot de volumen hasta que finalice el uso compartido de bloques.

Debe configurar el volumen para habilitar la función de eliminación automática de LUN de FlexClone con `volume snapshot autodelete modify` el comando. De lo contrario, si desea que las LUN de FlexClone se eliminen automáticamente pero el volumen no está configurado para la eliminación automática de FlexClone, no se elimina ninguna de las LUN de FlexClone.

Al crear una LUN de FlexClone, la función de eliminación automática de la LUN de FlexClone está deshabilitada de manera predeterminada. Debe habilitarla manualmente en cada LUN de FlexClone antes de que esa LUN de FlexClone se pueda eliminar de forma automática. Si utiliza aprovisionamiento de volúmenes semigruesos y desea obtener la garantía de escritura «mejor esfuerzo» proporcionada por esta opción, debe poner a disposición LUN de _all_ FlexClone para su eliminación automática.

[NOTE]
====
Cuando se crea una LUN de FlexClone a partir de una copia Snapshot, la LUN se divide automáticamente de la snapshot mediante un proceso de segundo plano con gestión eficiente del espacio, de modo que la LUN no continúe dependiendo de la snapshot o consuma espacio adicional. Si esta división en segundo plano no se ha completado y esta snapshot se elimina automáticamente, esa LUN de FlexClone se elimina incluso si ha deshabilitado la función de eliminación automática de FlexClone para esa LUN de FlexClone. Cuando la división en segundo plano ha finalizado, la LUN de FlexClone no se elimina ni siquiera si esa snapshot se ha eliminado.

====
.Información relacionada
* link:../volumes/create-flexclone-file-flexclone-lun-task.html["Cree una LUN de FlexClone"]
* link:../volumes/configure-flexvol-delete-flexclone-files-luns-task.html["Configure una FlexVol volume para eliminar automáticamente LUN de FlexClone"]
* link:../volumes/prevent-flexclone-file-lun-automatic-deleted-task.html["Evite que se elimine automáticamente una LUN de FlexClone"]

