---
permalink: san-admin/flexvol-reclaim-free-space-autodelete-concept.html 
sidebar: sidebar 
keywords: how, flexvol, volume, reclaim, free, space, autodelete, setting 
summary: Puede activar la configuración de eliminación automática de un volumen FlexVol para eliminar automáticamente archivos FlexClone y LUN FlexClone. Al habilitar la eliminación automática, se puede recuperar una cantidad de espacio libre objetivo en el volumen cuando un volumen está casi lleno. 
---
= Cómo un volumen de FlexVol puede reclamar espacio libre con la configuración de eliminación automática
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede activar la configuración de eliminación automática de un volumen FlexVol para eliminar automáticamente archivos FlexClone y LUN FlexClone. Al habilitar la eliminación automática, se puede recuperar una cantidad de espacio libre objetivo en el volumen cuando un volumen está casi lleno.

Puede configurar un volumen para que comience a eliminar automáticamente archivos FlexClone y LUN FlexClone cuando el espacio libre en el volumen disminuya por debajo de un valor de umbral determinado y deje de eliminar automáticamente clones cuando se reclame una cantidad de espacio libre objetivo en el volumen. Aunque, no puede especificar el valor de umbral que inicia la eliminación automática de clones, puede especificar si un clon es apto para su eliminación y puede especificar la cantidad de espacio libre objetivo para un volumen.

Un volumen elimina automáticamente los archivos FlexClone y las LUN FlexClone cuando el espacio libre en el volumen disminuye por debajo de un umbral determinado y cuando se cumplen los siguientes requisitos:

* La función de eliminación automática está habilitada para el volumen que contiene los archivos FlexClone y las LUN FlexClone.
+
Para habilitar la funcionalidad de eliminación automática para un volumen de FlexVol, se puede usar la `volume snapshot autodelete modify` comando. Debe configurar el `-trigger` parámetro a. `volume` o. `snap_reserve` Para que un volumen elimine automáticamente archivos FlexClone y LUN FlexClone.

* La función de eliminación automática está activada para los archivos de FlexClone y las LUN de FlexClone.
+
Puede activar la eliminación automática para un archivo FlexClone o una LUN FlexClone mediante el `file clone create` con el `-autodelete` parámetro. Como resultado, puede conservar algunos archivos FlexClone y LUN FlexClone deshabilitando la eliminación automática de los clones y asegurándose de que otras opciones de configuración del volumen no anulen la configuración del clon.


