---
permalink: san-admin/host-side-management-concept.html 
sidebar: sidebar 
keywords: understand, host-side, space, management 
summary: En un entorno con thin provisioning, la gestión del espacio del host completa el proceso de gestión del espacio desde el sistema de almacenamiento que se ha liberado en el sistema de ficheros host. 
---
= Gestión del espacio del host DE SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En un entorno con thin provisioning, la gestión del espacio del host completa el proceso de gestión del espacio desde el sistema de almacenamiento que se ha liberado en el sistema de ficheros host.

El sistema de archivos de host contiene metadatos para realizar un seguimiento de los bloques disponibles para almacenar datos nuevos y qué bloques contienen datos válidos que no deben sobrescribirse. Estos metadatos se almacenan en el LUN. Cuando se elimina un archivo en el sistema de archivos host, los metadatos del sistema de archivos se actualizan para marcar los bloques del archivo como espacio libre. El espacio libre total del sistema de archivos se vuelve a calcular para incluir los bloques recién liberados. Para el sistema de almacenamiento, estas actualizaciones de metadatos no aparecen diferentes de cualquier otra escritura que realice el host. Por lo tanto, el sistema de almacenamiento no es consciente de que se han producido eliminaciones.

Esto crea una discrepancia entre la cantidad de espacio libre notificada por el host y la cantidad de espacio libre notificada por el sistema de almacenamiento subyacente. Por ejemplo, suponga que tiene un LUN de 200 GB recién aprovisionado asignado al host mediante el sistema de almacenamiento. Tanto el host como el sistema de almacenamiento informan de 200 GB de espacio libre. Luego, el host escribe 100 GB de datos. En este momento, tanto el host como el sistema de almacenamiento informan de 100 GB de espacio usado y 100 GB de espacio no utilizado.

A continuación, elimina 50 GB de datos del host. En este momento, su host informará de 50 GB de espacio usado y 150 GB de espacio no utilizado. Sin embargo, el sistema de almacenamiento informará de 100 GB de espacio usado y 100 GB de espacio sin utilizar.

La gestión del espacio en el host utiliza diversos métodos para conciliar la diferencia de espacio entre el host y el sistema de almacenamiento.



== Gestión de hosts simplificada con SnapCenter

Es posible utilizar el software SnapCenter para simplificar algunas de las tareas de gestión y protección de datos asociadas con el almacenamiento iSCSI y FC. SnapCenter es un paquete de gestión opcional para los hosts Windows y UNIX.

Puede utilizar el software SnapCenter para crear fácilmente discos virtuales a partir de pools de almacenamiento que pueden distribuirse entre varios sistemas de almacenamiento y para automatizar las tareas de aprovisionamiento del almacenamiento y simplificar el proceso de creación de copias Snapshot y clones a partir de copias Snapshot consistentes con los datos del host.

Consulte la documentación de productos de NetApp para obtener más información acerca de https://docs.netapp.com/us-en/snapcenter/index.html["SnapCenter"].

.Enlaces relacionados
link:enable-space-allocation-scsi-thin-provisioned-luns-task.html["Activar la asignación de espacio para LUN con Thin Provisioning de SCSI"]
