---
permalink: san-admin/igroups-concept.html 
sidebar: sidebar 
keywords: understand, igroups 
summary: Los iGroups son tablas de nombres de WWPN de host de protocolo FC o de nodos de host iSCSI. Puede definir iGroups y asignarlas a LUN para controlar qué iniciadores tienen acceso a las LUN. 
---
= Acerca de iGroups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los iGroups son tablas de nombres de WWPN de host de protocolo FC o de nodos de host iSCSI. Puede definir iGroups y asignarlas a LUN para controlar qué iniciadores tienen acceso a las LUN.

Generalmente, desea que todos los puertos de iniciador o iniciadores de software del host tengan acceso a una LUN. Si utiliza software multivía o tiene hosts en clúster, cada puerto iniciador o iniciador de software de cada host en clúster necesita rutas redundantes a la misma LUN.

Es posible crear iGroups para especificar qué iniciadores tienen acceso a las LUN antes o después de crear las LUN, pero debe crear iGroups antes de poder asignar una LUN a un igroup.

Los iGroups pueden tener varios iniciadores, y varios iGroups pueden tener el mismo iniciador. Sin embargo, no puede asignar una LUN a varios iGroups que tengan el mismo iniciador. Un iniciador no puede ser miembro de iGroups de tipos de configuración distintos.
