---
permalink: san-admin/iscsi-endpoint-isolation-concept.html 
sidebar: sidebar 
keywords: iscsi, endpoint, isolation, add, remove, initiator, address, range 
summary: A partir de la versión 9.1 de ONTAP se mejoraron los comandos de seguridad iSCSI existentes para aceptar un rango de direcciones IP o varias direcciones IP. 
---
= Aislamiento de extremos iSCSI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de la versión 9.1 de ONTAP se mejoraron los comandos de seguridad iSCSI existentes para aceptar un rango de direcciones IP o varias direcciones IP.

Todos los iniciadores de iSCSI deben proporcionar direcciones IP de origen al establecer una sesión o conexión con un destino. Esta nueva funcionalidad evita que un iniciador inicie sesión en el clúster si la dirección IP de origen no es compatible o desconocida, lo cual proporciona un esquema de identificación único. Los iniciadores originados por una dirección IP no compatible o desconocida serán rechazados su inicio de sesión en la capa de sesión iSCSI, lo que impide que el iniciador acceda a cualquier LUN o volumen del clúster.

Implemente esta nueva funcionalidad con dos comandos nuevos para ayudar a gestionar entradas preexistentes.



== Añada un rango de direcciones del iniciador

Mejore la gestión de seguridad del iniciador de iSCSI añadiendo un rango de direcciones IP o varias direcciones IP con el `vserver iscsi security add-initiator-address-range` comando.

`cluster1::> vserver iscsi security add-initiator-address-range`



== Quite el rango de direcciones del iniciador

Quite un rango de direcciones IP o varias direcciones IP con el `vserver iscsi security remove-initiator-address-range` comando.

`cluster1::> vserver iscsi security remove-initiator-address-range`
