---
permalink: san-admin/lif-movement-concept.html 
sidebar: sidebar 
keywords: considerations, san, lif, movement 
summary: Solo debe realizar un movimiento LIF si está cambiando el contenido del clúster, por ejemplo, agregar nodos al clúster o eliminar nodos del clúster. Si realiza un movimiento de LIF, no necesita volver a crear una zona de la estructura de FC ni crear nuevas sesiones iSCSI entre los hosts conectados del clúster y la nueva interfaz de destino. 
---
= Qué debe saber antes de mover una LIF SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Solo debe realizar un movimiento LIF si está cambiando el contenido del clúster, por ejemplo, agregar nodos al clúster o eliminar nodos del clúster. Si realiza un movimiento de LIF, no necesita volver a crear una zona de la estructura de FC ni crear nuevas sesiones iSCSI entre los hosts conectados del clúster y la nueva interfaz de destino.

No puede mover un LIF DE SAN mediante el `network interface move` comando. El movimiento de LIF DE SAN debe realizarse desconectando el LIF, trasladando el LIF a otro nodo o puerto raíz y, a continuación, volviendo a conectarlo en su nueva ubicación. El acceso asimétrico de Unidad lógica (ALUA, Asymmetric Logical Unit Access) proporciona rutas redundantes y selección automática de rutas como parte de cualquier solución SAN de ONTAP. Por lo tanto, no se produce ninguna interrupción de I/o cuando se desconecta el LIF para dicho movimiento. El host simplemente reintenta y, a continuación, mueve I/o a otra LIF.

Con el movimiento LIF, puede hacer lo siguiente de forma no disruptiva:

* Sustituya un par de alta disponibilidad de un clúster por un par de alta disponibilidad actualizado de manera que los hosts que acceden a los datos de las LUN sean transparentes
* Actualizar una tarjeta de interfaz de destino
* Traslade los recursos de una máquina virtual de almacenamiento (SVM) de un conjunto de nodos de un clúster a otro conjunto de nodos del clúster

