---
permalink: san-admin/manage-lifs-all-san-protocols-concept.html 
sidebar: sidebar 
keywords: manage, lifs, san protocols 
summary: Los LIF están conectados a los hosts SAN. Pueden eliminarse de los conjuntos de puertos, moverse a diferentes nodos dentro de una máquina virtual de almacenamiento y borrarse. 
---
= Conoce las LIF de ONTAP para entornos SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los LUNs y namespaces de tu sistema ONTAP se encuentran dentro de las máquinas virtuales de almacenamiento (SVMs). Las interfaces de red (LIFs) permiten que tus clientes SAN se conecten a una SVM y accedan a los datos de los LUNs y namespaces que contiene.

* Debes configurar un LIF de gestión para cada máquina virtual de almacenamiento (SVM) que admita SAN.
* Puedes configurar dos LIF por nodo, uno para cada fabric que uses con FC y para separar las redes Ethernet para iSCSI.
* Se admite la conexión directa o el uso de conmutadores Ethernet para la conectividad. Debes configurar las LIF para ambos tipos de conectividad.


Aprende a link:../networking/create_a_lif.html["Cree una LIF"]

.Información relacionada
* link:../networking/configure_lifs_cluster_administrators_only_overview.html["Más información sobre la configuración del LIF"]
* link:multipath-automatic-lif-failover-support.html["Conoce el soporte para la conmutación por error automática de LIF de SAN"].

