---
permalink: san-admin/manage-lifs-all-san-protocols-concept.html 
sidebar: sidebar 
keywords: manage, lifs, san protocols 
summary: 'Los LIF están conectados a los hosts SAN. Pueden eliminarse de conjuntos de puertos, moverse a diferentes nodos dentro de una máquina virtual de almacenamiento (SVM) y eliminarse.' 
---
= Administre LIF para todos los protocolos SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe crear una o varias rutas iSCSI desde cada nodo de una pareja de ha, utilizando interfaces lógicas (LIF) para permitir el acceso a las LUN a las que presta servicio el par de alta disponibilidad.  Debe configurar un LIF de gestión para cada máquina virtual de almacenamiento (SVM) compatible con SAN.

Si falla un nodo, los LIF no migran ni asumen las direcciones IP del nodo del compañero que ha fallado. En su lugar, el software MPIO, mediante ALUA en el host, es responsable de seleccionar las rutas adecuadas para el acceso de las LUN a través de LIF.

Una vez creadas las LIF, pueden eliminarse de conjuntos de puertos, moverse a diferentes nodos en una máquina virtual de almacenamiento (SVM) y eliminarse.

.Información relacionada
link:../networking/configure_lifs_@cluster_administrators_only@_overview.html#lif-failover-and-giveback["Configurar LIF overveiw"]
link:../networking/create_a_lif.html["Cree una LIF"]
