---
permalink: san-admin/map-nvme-namespace-subsystem-task.html 
sidebar: sidebar 
keywords: map, nvme, namespace, subsystem 
summary: Debe asignar un espacio de nombres a un subsistema cuando utilice NVMe. 
---
= Asignar un espacio de nombres NVMe a un subsistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La asignación de un espacio de nombres NVMe a un subsistema permite el acceso a los datos desde el host.  Es posible asignar un espacio de nombres NVMe a un subsistema al aprovisionar almacenamiento, o bien puede hacerlo después de que se ha aprovisionado el almacenamiento.

A partir de ONTAP 9.14.1, puede priorizar la asignación de recursos para hosts específicos. De forma predeterminada, cuando se añade un host al subsistema NVMe, se da prioridad regular. Puede usar la interfaz de línea de comandos (CLI) de ONTAP para cambiar manualmente la prioridad predeterminada de regular a alta.  Los hosts a los que se asigna una prioridad alta se asignan números de colas de I/O de mayor tamaño y profundidades de cola.


NOTE: Si desea dar una prioridad alta a un host que se añadió a un subsistema en ONTAP 9.13.1 o versiones anteriores, puede xref:../nvme/change-host-priority-nvme-task.html[cambie la prioridad del host].

.Antes de empezar
El espacio de nombres y el subsistema ya deben crearse. Si necesita crear un espacio de nombres y un subsistema, consulte link:create-nvme-namespace-subsystem-task.html["Aprovisione el almacenamiento NVMe"].

.Pasos
. Obtenga el NQN del host.
. Añada el NQN del host al subsistema:
+
[source, cli]
----
vserver nvme subsystem host add -vserver <SVM_name> -subsystem <subsystem_name> -host-nqn <Host_NQN_:subsystem._subsystem_name>
----
+
Si desea cambiar la prioridad predeterminada del host de regular a alta, use la `-priority high` opción. Esta opción está disponible a partir de ONTAP 9.14.1. Obtenga más información sobre `vserver nvme subsystem host add` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-subsystem-host-add.html["Referencia de comandos de la ONTAP"^].

. Asigne el espacio de nombres al subsistema:
+
[source, cli]
----
vserver nvme subsystem map add -vserver <SVM_name> -subsystem <subsystem_name> -path <path>
----
+
Un espacio de nombres solo se puede asignar a un subsistema único. Obtenga más información sobre `vserver nvme subsystem map add` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-subsystem-map-add.html["Referencia de comandos de la ONTAP"^].

. Compruebe que el espacio de nombres está asignado al subsistema:
+
[source, cli]
----
vserver nvme namespace show -vserver <SVM_name> -instance
----
+
El subsistema debe aparecer como el `Attached subsystem`. Obtenga más información sobre `vserver nvme namespace show` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-namespace-show.html["Referencia de comandos de la ONTAP"^].


