---
permalink: san-admin/microsoft-offloaded-data-transfer-odx-concept.html 
sidebar: sidebar 
keywords: microsoft, offloaded, data, transfer, odx 
summary: 'La transferencia de datos descargados (ODX) de Microsoft, también conocida como descarga de copias, permite transferir datos directamente dentro de un dispositivo de almacenamiento o entre dispositivos de almacenamiento compatibles sin transferir los datos a través del equipo host.' 
---
= Información general sobre la transferencia de datos descargados (ODX) de Microsoft
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La transferencia de datos descargados (ODX) de Microsoft, también conocida como _copy fload_, permite transferir datos directamente dentro de un dispositivo de almacenamiento o entre dispositivos de almacenamiento compatibles sin transferir los datos a través del equipo host.

ONTAP admite ODX para los protocolos SMB Y SAN.

En las transferencias de archivos que no tienen ODX, los datos se leen del origen y se transfieren por la red al host. El host transfiere los datos a través de la red al destino. En la transferencia de archivos ODX, los datos se copian directamente del origen al destino sin pasar por el host.

Dado que las copias de ODX descargados se realizan directamente entre el origen y el destino, se obtienen importantes ventajas en cuanto al rendimiento, incluidos un tiempo de copia más rápido, un uso reducido de la CPU y la memoria en el cliente y una reducción del uso del ancho de banda de I/o de la red.

Para entornos SAN, ODX solo está disponible cuando es compatible tanto con el host como con el sistema de almacenamiento. Los equipos cliente compatibles con ODX y que tengan habilitada ODX automáticamente y de forma transparente utilizan la transferencia de archivos descargados cuando se mueven o copian archivos. ODX se utiliza independientemente de si arrastra y suelta archivos a través del Explorador de Windows o utiliza comandos de copia de archivos de la línea de comandos, o si una aplicación cliente inicia solicitudes de copia de archivos.
