---
permalink: san-admin/prerequisites-setup-luns-concept.html 
sidebar: sidebar 
keywords: prerequisites, setting up, luns 
summary: La configuración de LUN implica crear una LUN, crear un igroup y asignar la LUN al igroup. El sistema debe cumplir con ciertos requisitos previos antes de poder configurar las LUN. 
---
= Requisitos del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La configuración de LUN implica crear una LUN, crear un igroup y asignar la LUN al igroup. El sistema debe cumplir con ciertos requisitos previos antes de poder configurar las LUN.

* La matriz de interoperabilidad debe incluir la configuración DE SAN como compatible.
* Su entorno SAN debe cumplir con los límites de configuración de la controladora y el host de SAN especificados en https://hwu.netapp.com["NetApp Hardware Universe"^] para la versión del software ONTAP.
* Se debe instalar una versión compatible de Host Utilities.
+
La documentación de Host Utilities proporciona más información.

* Debe tener LIF SAN en el nodo propietario de LUN y el partner de alta disponibilidad del nodo propietario.


.Información relacionada
* https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^]
* https://docs.netapp.com/us-en/ontap-sanhost/index.html["Configuración de host SAN ONTAP"]
* https://www.netapp.com/pdf.html?item=/media/19680-tr-4017.pdf["Informe técnico de NetApp 4017: Prácticas recomendadas de SAN Fibre Channel"^]

