---
permalink: san-admin/remove-lif-from-portset-task.html 
sidebar: sidebar 
keywords: remove, san, lif, port, set 
summary: Si la LIF que desea eliminar o mover está en un conjunto de puertos, debe quitar la LIF del conjunto de puertos antes de poder eliminar o mover la LIF. 
---
= Quite una LIF DE SAN de un conjunto de puertos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si la LIF que desea eliminar o mover está en un conjunto de puertos, debe quitar la LIF del conjunto de puertos antes de poder eliminar o mover la LIF.

.Acerca de esta tarea
Debe realizar el Paso 1 del siguiente procedimiento sólo si hay un LIF en el conjunto de puertos. No puede quitar la última LIF de un conjunto de puertos si el conjunto de puertos está vinculado a un iGroup. De lo contrario, puede empezar con Paso 2 si hay varias LIF en el conjunto de puertos.

.Pasos
. Si solo hay una LIF en el conjunto de puertos, utilice `lun igroup unbind` el comando para desvincular el conjunto de puertos del iGroup.
+
[NOTE]
====
Cuando se desvincula un iGroup de un conjunto de puertos, todos los iniciadores del iGroup tienen acceso a todas las LUN de destino asignadas al iGroup en todas las interfaces de red.

====
+
`cluster1::>lun igroup unbind -vserver vs1 -igroup ig1`

+
Obtenga más información sobre `lun igroup unbind` en el link:https://docs.netapp.com/us-en/ontap-cli/lun-igroup-unbind.html["Referencia de comandos del ONTAP"^].

. Utilice `lun portset remove` el comando para eliminar la LIF del conjunto de puertos.
+
`cluster1::> port set remove -vserver vs1 -portset ps1 -port-name lif1`

+
Obtenga más información sobre `lun portset remove` en el link:https://docs.netapp.com/us-en/ontap-cli/lun-portset-remove.html["Referencia de comandos del ONTAP"^].


