---
permalink: san-admin/requirements-odx-concept.html 
sidebar: sidebar 
keywords: microsoft Offloaded Data Transfer, using, odx 
summary: Si planea utilizar ODX para descargas de copias, debe estar familiarizado con las consideraciones de compatibilidad de volúmenes, los requisitos del sistema y los requisitos de funcionalidad de software. 
---
= Requisitos para usar ODX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si planea utilizar ODX para descargas de copias, debe estar familiarizado con las consideraciones de compatibilidad de volúmenes, los requisitos del sistema y los requisitos de funcionalidad de software.

Para utilizar ODX, el sistema debe tener lo siguiente:

* ONTAP
+
ODX se habilita automáticamente en las versiones compatibles de ONTAP.

* Volumen de origen mínimo de 2 GB
+
Para obtener un rendimiento óptimo, el volumen de origen debe ser mayor que 260 GB.

* Deduplicación
+
ODX utiliza la deduplicación como parte del proceso de copia. Si no desea la deduplicación en la SVM, debe deshabilitar ODX en esa SVM.

* Compatibilidad con ODX en el cliente Windows
+
Windows Server 2012 o posterior admite ODX y Windows 8 o versiones posteriores. La matriz de interoperabilidad contiene la información más reciente sobre los clientes Windows compatibles.

+
https://["Herramienta de matriz de interoperabilidad de NetApp"^]

* Compatibilidad con aplicaciones de copia para ODX
+
La aplicación que realiza la transferencia de datos debe ser compatible con ODX. Las operaciones de aplicaciones compatibles con ODX incluyen lo siguiente:

+
** Las operaciones de gestión de Hyper-V, como la creación y conversión de discos duros virtuales (VHD), la gestión de copias Snapshot y la copia de archivos entre máquinas virtuales
** Operaciones del Explorador de Windows
** Comandos de copia de Windows PowerShell
** Comandos de copia del símbolo del sistema de Windows la biblioteca de Microsoft TechNet contiene más información acerca de las aplicaciones ODX admitidas en servidores y clientes de Windows.


* Si se utilizan volúmenes comprimidos, el tamaño del grupo de compresión debe ser de 8 KB.
+
No se admite el tamaño del grupo de compresión de 32 KB.



ODX no funciona con los siguientes tipos de volúmenes:

* Volúmenes de origen con capacidades inferiores a 2 GB
* Volúmenes de solo lectura
* link:../flexcache/supported-unsupported-features-concept.html["Volúmenes de FlexCache"]
* link:../san-admin/san-volumes-concept.html#semi-thick-provisioning-for-volumes["Volúmenes semigruesos aprovisionados"]

