---
permalink: san-admin/restore-all-luns-volume-snapshot-copy-task.html 
sidebar: sidebar 
keywords: restore, all, luns in a volume, from, snapshot copy 
summary: Se puede usar el comando volume snapshot restore para restaurar todos los LUN de un volumen especificado a partir de una snapshot. 
---
= Restaure todas las LUN de un volumen a partir de una copia de Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar `volume snapshot restore` el comando para restaurar todas las LUN de un volumen especificado a partir de una copia de Snapshot.

.Pasos
. Desde el host, detenga todo el acceso del host a las LUN.
+
El uso de SnapRestore sin detener todo el acceso de host a las LUN del volumen puede provocar daños en los datos y errores del sistema.

. Desmonte las LUN de ese host para que el host no pueda acceder a las LUN.
. Desasigne sus LUN:
+
`lun mapping delete -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -igroup _igroup_name_`

. Determine la Snapshot en la que desea restaurar el volumen:
+
`volume snapshot show -vserver _vserver_name_ -volume _volume_name_`

. Cambie la configuración de privilegios a avanzada:
+
`set -privilege advanced`

. Restaure sus datos:
+
`volume snapshot restore -vserver _vserver_name_ -volume _volume_name_ -snapshot _snapshot_name_`

. Siga las instrucciones que aparecen en pantalla.
. Reasigne sus LUN:
+
`lun mapping create -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -igroup _igroup_name_`

. Compruebe que sus LUN están en línea:
+
`lun show -vserver _vserver_name_ -path _lun_path_ -fields state`

. Si sus LUN no están en línea, conectarlos:
+
`lun modify -vserver _vserver_name_ -path _lun_path_ -state online`

. Cambie la configuración de privilegio a admin:
+
`set -privilege admin`

. Desde el host, vuelva a montar las LUN.
. Desde el host, reinicie el acceso a sus LUN.

