---
permalink: san-admin/restore-single-lun-snapvault-backup-task.html 
sidebar: sidebar 
keywords: ontap 9.2, restore, single, lun, snapvault backup 
summary: Es posible restaurar un solo LUN a una nueva ubicación o a la ubicación original. Es posible restaurar desde cualquier copia de Snapshot del volumen secundario de SnapVault. Para restaurar la LUN en la ubicación original, primero debe restaurarla en una nueva ubicación y, a continuación, copiarla. 
---
= Restaurar una única LUN a partir de un backup de ONTAP SnapVault
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible restaurar un solo LUN a una nueva ubicación o a la ubicación original. Es posible restaurar desde cualquier copia de Snapshot del volumen secundario de SnapVault. Para restaurar la LUN en la ubicación original, primero debe restaurarla en una nueva ubicación y, a continuación, copiarla.

.Antes de empezar
* Debe inicializarse la relación de SnapVault, y el volumen secundario de SnapVault debe contener una Snapshot adecuada para la restauración.
* La máquina virtual de almacenamiento (SVM) que contiene el volumen secundario de SnapVault debe tener una o más LIF con el protocolo SAN deseado a los que se puede acceder desde el host que se utiliza para acceder a la copia de LUN.
* Los iGroups ya deben existir en la SVM de SnapVault.


.Acerca de esta tarea
El proceso incluye la creación de un clon de volumen de lectura/escritura desde una copia Snapshot del volumen secundario de SnapVault. Puede utilizar la LUN directamente desde el clon, o bien puede copiar de nuevo el contenido de la LUN a su ubicación original.

La LUN del clon tiene una ruta y un número de serie diferentes a la LUN original. No se conservan las reservas persistentes.

.Pasos
. Verificar el volumen secundario que contiene el backup de SnapVault.
+
[source, cli]
----
snapmirror show
----
+
[listing]
----
cluster::> snapmirror show

Source         Dest     Mirror  Relation  Total             Last
Path     Type  Path     State   Status    Progress  Healthy Updated
-------- ---- --------- ------- --------- --------- ------- -------
vserverA:srcvolA
         XDP  vserverB:dstvolB
                        Snapmirrored
                                Idle       -         true    -
----
. Identificar la snapshot a partir de la que desea restaurar la LUN.
+
[source, cli]
----
volume snapshot show
----
+
[listing]
----
cluster::> volume snapshot show

Vserver  Volume  Snapshot               State Size   Total% Used%
-------- ------- ---------------------- ----- ------ ------ -----
vserverB
         dstvolB
                 snap2.2013-02-10_0010  valid  124KB     0%    0%
                 snap1.2013-02-10_0015 valid  112KB     0%    0%
                 snap2.2013-02-11_0010  valid  164KB     0%    0%
----
. Cree un clon de lectura y escritura desde la snapshot que desee
+
[source, cli]
----
volume clone create -vserver <SVM_name> -flexclone <flexclone_name> -type <type> -parent-volume <parent_volume_name> -parent-snapshot <snapshot_name>
----
+
El clon de volumen se crea en el mismo agregado que el backup de SnapVault. Debe haber suficiente espacio en el agregado para almacenar el clon.

+
[listing]
----
cluster::> volume clone create -vserver vserverB
  -flexclone dstvolB_clone -type RW -parent-volume dstvolB
  -parent-snapshot daily.2013-02-10_0010
[Job 108] Job succeeded: Successful
----
. Enumere las LUN del clon de volumen.
+
[source, cli]
----
lun show -vserver <SVM_name> -volume <flexclone_volume_name>
----
+
[listing]
----
cluster::> lun show -vserver vserverB -volume dstvolB_clone

Vserver   Path                      State   Mapped   Type
--------- ------------------------  ------- -------- --------
vserverB  /vol/dstvolB_clone/lun_A  online  unmapped windows
vserverB  /vol/dstvolB_clone/lun_B  online  unmapped windows
vserverB  /vol/dstvolB_clone/lun_C  online  unmapped windows

3 entries were displayed.
----
+
Obtenga más información sobre `lun show` en el link:https://docs.netapp.com/us-en/ontap-cli/lun-show.html["Referencia de comandos de la ONTAP"^].

. Si el igroup del host deseado no existe ya en la SVM que contiene el backup de SnapVault, cree un igroup.
+
[source, cli]
----
igroup create -vserver <SVM_name> -igroup <igroup_name> -protocol <protocol> -ostype <os_type> -initiator <initiator_name>
----
+
En este ejemplo, se crea un igroup para un host Windows que utiliza el protocolo iSCSI:

+
[listing]
----
cluster::> igroup create -vserver vserverB -igroup temp_igroup
  -protocol iscsi -ostype windows
  -initiator iqn.1991-05.com.microsoft:hostA
----
. Asigne la copia LUN deseada al igroup.
+
[source, cli]
----
lun mapping create -vserver <SVM_name> -path <lun_path> -igroup <igroup_name>
----
+
[listing]
----
cluster::> lun mapping create -vserver vserverB
  -path /vol/dstvolB_clone/lun_C -igroup temp_igroup
----
+
Obtenga más información sobre `lun mapping create` en el link:https://docs.netapp.com/us-en/ontap-cli/lun-mapping-create.html["Referencia de comandos de la ONTAP"^].

. Conecte el host a la LUN y acceda al contenido de la LUN, según lo desee.
+
La LUN es de lectura y escritura y se puede utilizar en lugar de la LUN original. Dado que el número de serie de la LUN es diferente, el host lo interpreta como un LUN diferente al original.

. Use un programa de copia en el host para copiar el contenido de la LUN nuevamente en la LUN original.

