---
permalink: san-admin/san-config-mcc-concept.html 
sidebar: sidebar 
keywords: metrocluster environments, considerations, san configuration, metrocluster, environments, san, configurations, cisco switch, brocade switch, 
summary: Debe tener en cuenta determinados aspectos que se deben tener en cuenta al utilizar configuraciones DE SAN en un entorno de MetroCluster. 
---
= Configuraciones SAN admitidas en un entorno ONTAP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe tener en cuenta determinados aspectos que se deben tener en cuenta al utilizar configuraciones DE SAN en un entorno de MetroCluster.

* Las configuraciones de MetroCluster no son compatibles con las configuraciones VSAN «enrutadas» de estructura FC de interfaz.
* A partir de ONTAP 9.15.1, las configuraciones de IP de MetroCluster de cuatro nodos son compatibles con NVMe/TCP.
* A partir de ONTAP 9.12.1, las configuraciones IP de MetroCluster de cuatro nodos son compatibles con NVMe/FC. Las configuraciones de MetroCluster no son compatibles con redes NVMe front-end antes de ONTAP 9.12.1.
* La configuración de MetroCluster admite otros protocolos SAN, como iSCSI, FC y FCoE.
* Al usar las configuraciones del cliente SAN, debe comprobar si se incluye alguna consideraciones especiales para las configuraciones de MetroCluster en las notas que se proporcionan en la link:https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^] (IMT).
* Los sistemas operativos y las aplicaciones deben proporcionar una resiliencia de I/o de 120 segundos para admitir la conmutación por cierre automática no planificada de MetroCluster y la conmutación de sitios iniciada por tiebreaker o de Mediator.
* Las configuraciones de MetroCluster utilizan los mismos WWNN y WWPN en ambos lados de la estructura FC de front-end.


.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html["Comprender la protección de datos y la recuperación ante desastres de MetroCluster"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/What_are_AIX_Host_support_considerations_in_a_MetroCluster_configuration%3F["Artículo de la base de conocimientos: ¿Cuáles son las consideraciones de compatibilidad del host AIX en una configuración de MetroCluster?"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/Solaris_host_support_considerations_in_a_MetroCluster_configuration["Artículo de la base de conocimientos: Consideraciones de compatibilidad del host Solaris en una configuración de MetroCluster"^]

