---
permalink: san-admin/selective-lun-map-concept.html 
sidebar: sidebar 
keywords: select, selective, lun, map, slm, enabled, modify, reporting, nodes, list 
summary: 'La asignación selectiva de LUN (SLM) reduce el número de rutas desde el host hacia el LUN. Con SLM, cuando se crea una nueva asignación de LUN, el LUN solo se puede acceder a través de las rutas del nodo al que pertenece la LUN y su partner de alta disponibilidad.' 
---
= Información general sobre asignación de LUN selectiva
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La asignación selectiva de LUN (SLM) reduce el número de rutas desde el host hacia el LUN. Con SLM, cuando se crea una nueva asignación de LUN, el LUN solo se puede acceder a través de las rutas del nodo al que pertenece la LUN y su partner de alta disponibilidad.

SLM permite gestionar un solo igroup por host y también admite operaciones de movimiento de LUN no disruptivas que no requieren manipulación del conjunto de puertos o reasignación de LUN.

Los conjuntos de puertos se pueden utilizar con SLM de la misma forma que en versiones anteriores de ONTAP para restringir aún más el acceso de ciertos destinos a ciertos iniciadores. Cuando se utiliza SLM con conjuntos de puertos, se podrá acceder a los LUN en el conjunto de puertos del nodo que posee la LUN y en el partner de alta disponibilidad de ese nodo.

SLM está habilitado de forma predeterminada en todos los mapas de LUN nuevos.



== Determinar si SLM está habilitado en una asignación de LUN

Si su entorno tiene una combinación de LUN creadas en ONTAP y LUN transferidos de versiones anteriores, es posible que deba determinar si la asignación selectiva de LUN (SLM) está habilitada en un LUN específico.

Puede utilizar la información que se muestra en el resultado del `lun mapping show -fields reporting-nodes, node` Comando para determinar si SLM está habilitado en la asignación de LUN. Si SLM no está habilitado, se muestra “-” en las celdas bajo la columna “nodos de portabilidad” de la salida del comando. Si SLM está habilitado, la lista de nodos que se muestran bajo la columna ''nodos'' se duplica en la columna ''nodos de portabilidad''.



== Modifique la lista nodos de informes de SLM

Si mueve un LUN o un volumen que contiene LUN a otra pareja de alta disponibilidad (ha) dentro del mismo clúster, debe modificar la lista de nodos de generación de informes de asignación de LUN selectiva (SLM) antes de iniciar el movimiento para garantizar que se mantengan las rutas de LUN activas y optimizadas.

.Pasos
. Añada el nodo de destino y su nodo asociado a la lista Reporting-Nodes del volumen o del agregado:
+
`lun mapping add-reporting-nodes -vserver _vserver_name_ -path _lun_path_ -igroup _igroup_name_ [-destination-aggregate _aggregate_name_|-destination-volume _volume_name_]`

+
Si tiene una convención de nomenclatura coherente, puede modificar varias asignaciones de LUN al mismo tiempo mediante `_igroup_prefix*_` en lugar de `_igroup_name_`.

. Vuelva a analizar el host para detectar las rutas recién añadidas.
. Si el sistema operativo lo requiere, añada las rutas nuevas a la configuración de I/o de red multivía (MPIO).
. Ejecute el comando para la operación de movimiento necesaria y espere a que finalice la operación.
. Compruebe que se está prestando servicio a E/S a través de la ruta activa/optimizada:
+
`lun mapping show -fields reporting-nodes`

. Elimine el propietario anterior de la LUN y su nodo asociado de la lista de nodos de generación de informes:
+
`lun mapping remove-reporting-nodes -vserver _vserver_name_ -path _lun_path_ -igroup _igroup_name_ -remote-nodes`

. Compruebe que la LUN se ha eliminado del mapa de LUN existente:
+
`lun mapping show -fields reporting-nodes`

. Elimine las entradas obsoletas del dispositivo para el sistema operativo host.
. Si es necesario, cambie los archivos de configuración de accesos múltiples.
. Vuelva a analizar el host para verificar la eliminación de las rutas antiguas. +
Consulte la documentación del host para ver los pasos específicos para volver a analizar los hosts.

