---
permalink: san-admin/volume-config-options-concept.html 
sidebar: sidebar 
keywords: san, volume, configuration, options 
summary: Debe configurar varias opciones en el volumen que contiene el LUN. La manera en que establece las opciones de volumen determina la cantidad de espacio disponible para las LUN del volumen. 
---
= Opciones de configuración de volúmenes SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar varias opciones en el volumen que contiene el LUN. La manera en que establece las opciones de volumen determina la cantidad de espacio disponible para las LUN del volumen.



== Crecimiento automático

Puede activar o desactivar Autofila. Si se habilita esta función, el crecimiento automático permite que ONTAP aumente automáticamente el tamaño del volumen hasta un tamaño máximo que se determine previamente. Debe haber espacio disponible en el agregado contenedor para admitir el crecimiento automático del volumen. Por lo tanto, si se habilita el crecimiento automático, se debe supervisar el espacio libre en el agregado que contiene y agregar más cuando se necesite.

No se puede activar el crecimiento automático para admitir la creación de snapshots. Si se intenta crear una Snapshot y no hay espacio suficiente en el volumen, se produce un error en la creación de la snapshot, incluso con crecimiento automático habilitado.

Si se deshabilita el crecimiento automático, el tamaño del volumen seguirá siendo el mismo.



== Autohrink

Puede activar o desactivar la función de reducción automática. Si lo habilita, la función de reducción automática permite a ONTAP reducir automáticamente el tamaño total de un volumen cuando la cantidad de espacio consumido en el volumen disminuye un umbral predeterminado. Esto aumenta la eficiencia de almacenamiento al activar los volúmenes para liberar automáticamente espacio libre no utilizado.



== Eliminación automática de Snapshot

la función autodelete de Snapshot elimina automáticamente Snapshot cuando se produce alguna de las siguientes situaciones:

* El volumen está casi lleno.
* El espacio de la reserva de instantáneas está casi lleno.
* El espacio de reserva de sobrescritura está lleno.


Se puede configurar la eliminación automática de snapshots para eliminar las snapshots de las más antiguas a las más recientes, o de las más recientes a las más antiguas. la eliminación automática de snapshots no elimina las snapshots vinculadas a las snapshots en volúmenes o LUN clonados.

Si el volumen necesita espacio adicional y habilitó el crecimiento automático y la eliminación automática de Snapshot, de forma predeterminada, ONTAP intenta adquirir el espacio necesario activando primero el crecimiento automático. Si no se adquiere espacio suficiente a través del crecimiento automático, se activa la eliminación automática de snapshots.



== Reserva de Snapshot

La reserva de snapshots define la cantidad de espacio en el volumen reservado para las snapshots. El espacio asignado a la reserva de instantáneas no se puede utilizar para ningún otro propósito. Si se utiliza todo el espacio asignado para la reserva de instantáneas, las instantáneas comienzan a consumir espacio adicional en el volumen.
