---
permalink: san-admin/volume-config-options-concept.html 
sidebar: sidebar 
keywords: san, volume, configuration, options 
summary: Debe configurar varias opciones en el volumen que contiene el LUN. La manera en que establece las opciones de volumen determina la cantidad de espacio disponible para las LUN del volumen. 
---
= Opciones de configuración de volúmenes SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar varias opciones en el volumen que contiene el LUN. La manera en que establece las opciones de volumen determina la cantidad de espacio disponible para las LUN del volumen.



== Crecimiento automático

Puede activar o desactivar Autofila. Si se habilita esta función, el crecimiento automático permite que ONTAP aumente automáticamente el tamaño del volumen hasta un tamaño máximo que se determine previamente. Debe haber espacio disponible en el agregado contenedor para admitir el crecimiento automático del volumen. Por lo tanto, si se habilita el crecimiento automático, se debe supervisar el espacio libre en el agregado que contiene y agregar más cuando se necesite.

No se puede activar el crecimiento automático para admitir la creación de copias Snapshot. Si se intenta crear una copia de Snapshot y hay espacio insuficiente en el volumen, se produce un error en la creación de Snapshot, incluso con el crecimiento automático habilitado.

Si se deshabilita el crecimiento automático, el tamaño del volumen seguirá siendo el mismo.



== Autohrink

Puede activar o desactivar la función de reducción automática. Si lo habilita, la función de reducción automática permite a ONTAP reducir automáticamente el tamaño total de un volumen cuando la cantidad de espacio consumido en el volumen disminuye un umbral predeterminado. Esto aumenta la eficiencia de almacenamiento al activar los volúmenes para liberar automáticamente espacio libre no utilizado.



== Eliminación automática de Snapshot

La eliminación automática de Snapshot elimina automáticamente las copias Snapshot si se produce alguna de las siguientes situaciones:

* El volumen está casi lleno.
* El espacio de reserva de Snapshot está casi lleno.
* El espacio de reserva de sobrescritura está lleno.


Es posible configurar la eliminación automática de Snapshot para eliminar copias de Snapshot de las más antiguas a las más nuevas, o de las más nuevas a las más antiguas. La eliminación automática de Snapshot no elimina las copias de Snapshot vinculadas a las copias de Snapshot en volúmenes o LUN clonados.

Si el volumen necesita espacio adicional y se habilitó el crecimiento automático y la eliminación automática de Snapshot, de manera predeterminada, ONTAP intenta adquirir el espacio necesario mediante la activación del crecimiento automático por primera vez. Si no se adquiere suficiente espacio a través del crecimiento automático, se activa la eliminación automática de Snapshot.



== Reserva de Snapshot

La reserva de Snapshot define la cantidad de espacio en el volumen reservado para las copias de Snapshot. El espacio asignado a la reserva de Snapshot no se puede utilizar con ningún otro fin. Si se utiliza todo el espacio asignado a la reserva de Snapshot, las copias snapshot empiezan a consumir espacio adicional en el volumen.
