---
permalink: smb-config/commands-manage-ntp-servers-reference.html 
sidebar: sidebar 
keywords: ontap, network, time, protocol, ntp, version, support, ntpv3, symmetric, authentication, sha, security, commands for managing symmetric authentication on ntp servers 
summary: 'A partir de ONTAP 9.5, se admite la versión 3 del protocolo de tiempo de redes (NTP). NTPv3 incluye autenticación simétrica mediante claves SHA-1 que aumenta la seguridad de la red.' 
---
= Comandos para gestionar la autenticación simétrica en servidores NTP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.5, se admite la versión 3 del protocolo de tiempo de redes (NTP). NTPv3 incluye autenticación simétrica mediante claves SHA-1 que aumenta la seguridad de la red.

|===
| Para hacer esto... | Se usa este comando... 


 a| 
Configure un servidor NTP sin autenticación simétrica
 a| 
`cluster time-service ntp server create` `-server` `server_name`



 a| 
Configure un servidor NTP con autenticación simétrica
 a| 
`cluster time-service ntp server create` `-server` `server_ip_address` `-key-id` `key_id`



 a| 
Habilitar autenticación simétrica para un servidor NTP existente se puede modificar el servidor NTP existente para habilitar la autenticación agregando el Id. De clave requerido
 a| 
`cluster time-service ntp server modify` `-server` `server_name` `-key-id` `key_id`



 a| 
Configure una clave NTP compartida
 a| 
`cluster time-service ntp key create` `-id` `shared_key_id` `-type` `shared_key_type` `-value` `shared_key_value`

[NOTE]
====
Las claves compartidas se refieren a un ID. El ID, su tipo y el valor deben ser idénticos tanto en el nodo como en el servidor NTP

====


 a| 
Configure un servidor NTP con un ID de clave desconocido
 a| 
`cluster time-service ntp server create` `-server` `server_name` `-key-id` `key_id`



 a| 
Configure un servidor con un ID de clave no configurado en el servidor NTP.
 a| 
`cluster time-service ntp server create` `-server` `server_name` `-key-id` `key_id`

[NOTE]
====
El ID de clave, el tipo y el valor deben ser idénticos al ID de clave, el tipo y el valor configurados en el servidor NTP.

====


 a| 
Deshabilitar la autenticación simétrica
 a| 
`cluster time-service ntp server modify` `-server` `server_name` `-authentication disabled`

|===