---
permalink: smb-config/configure-client-access-shared-storage-concept.html 
sidebar: sidebar 
keywords: smb, client, access, storage, svm, create, volume, qtree, container, modify, share, file, permission, test, configure smb client access to shared storage 
summary: Para proporcionar acceso al cliente SMB al almacenamiento compartido en una SVM, debe crear un volumen o qtree para proporcionar un contenedor de almacenamiento y, a continuación, crear o modificar un recurso compartido para ese contenedor. Luego, puede configurar los permisos de recursos compartidos y archivos, y probar el acceso desde sistemas cliente. 
---
= Configure el acceso de clientes SMB al almacenamiento compartido
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para proporcionar acceso al cliente SMB al almacenamiento compartido en una SVM, debe crear un volumen o qtree para proporcionar un contenedor de almacenamiento y, a continuación, crear o modificar un recurso compartido para ese contenedor. Luego, puede configurar los permisos de recursos compartidos y archivos, y probar el acceso desde sistemas cliente.

.Antes de empezar
* El bloque de mensajes del servidor debe estar configurado por completo en la SVM.
* Se debe completar cualquier actualización de la configuración de los servicios de nombres.
* Cualquier adición o modificación a una configuración de dominio o grupo de trabajo de Active Directory debe estar completa.

