---
permalink: smb-config/create-local-groups-task.html 
sidebar: sidebar 
keywords: create, local, group, authorize, authorizing, access, data, associate, svm, smb, connection, assign, privilege, define, right, capabilities, capability, member, create local groups 
summary: Es posible crear grupos locales que se puedan utilizar para autorizar el acceso a los datos asociados con la SVM a través de una conexión de SMB. También puede asignar privilegios que definen los derechos de usuario o las capacidades que tiene un miembro del grupo. 
---
= Crear grupos locales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible crear grupos locales que se puedan utilizar para autorizar el acceso a los datos asociados con la SVM a través de una conexión de SMB. También puede asignar privilegios que definen los derechos de usuario o las capacidades que tiene un miembro del grupo.

.Acerca de esta tarea
La funcionalidad de grupo local se habilita de forma predeterminada cuando se crea la SVM.

Cuando se crea un grupo local, debe especificar un nombre para el grupo y debe especificar la SVM con la que desea asociar el grupo. Puede especificar un nombre de grupo con o sin el nombre de dominio local y, opcionalmente, puede especificar una descripción para el grupo local. No puede agregar un grupo local a otro grupo local.

La `vserver cifs users-and-groups local-group` las páginas de manual contienen detalles sobre parámetros opcionales y requisitos de nomenclatura.

.Pasos
. Cree el grupo local: `vserver cifs users-and-groups local-group create -vserver vserver_name -group-name group_name`
+
El siguiente parámetro opcional puede ser útil:

+
** `-description`
+
Una descripción para el grupo local.



. Compruebe que el grupo se ha creado correctamente: `vserver cifs users-and-groups local-group show -vserver vserver_name`


.Ejemplo
En el siguiente ejemplo se crea un grupo local "MB_SERVER01\engineering" asociado con SVM vs1:

[listing]
----
cluster1::> vserver cifs users-and-groups local-group create -vserver vs1.example.com -group-name SMB_SERVER01\engineering

cluster1::> vserver cifs users-and-groups local-group show -vserver vs1.example.com
Vserver          Group Name                   Description
---------------- ---------------------------- ----------------------------
vs1.example.com  BUILTIN\Administrators       Built-in Administrators group
vs1.example.com  BUILTIN\Backup Operators     Backup Operators group
vs1.example.com  BUILTIN\Power Users          Restricted administrative privileges
vs1.example.com  BUILTIN\Users                All users
vs1.example.com  SMB_SERVER01\engineering
vs1.example.com  SMB_SERVER01\sales
----
.Después de terminar
Debe agregar miembros al nuevo grupo.
