---
permalink: smb-config/create-volume-task.html 
sidebar: sidebar 
keywords: create, volume, junction, point, properties, property, command, create a volume 
summary: Puede crear un volumen y especificar su punto de unión y otras propiedades mediante el comando volume create. 
---
= Cree volúmenes de bloque de mensajes del servidor de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear un volumen y especificar su punto de unión y otras propiedades mediante `volume create` el comando.

.Acerca de esta tarea
Un volumen debe incluir una _ruta de unión_ para que sus datos estén disponibles para los clientes. Puede especificar la ruta de unión cuando cree un nuevo volumen. Si crea un volumen sin especificar una ruta de unión, debe _mount_ el volumen en el espacio de nombres de la SVM con `volume mount` el comando.

.Antes de empezar
* SMB debe estar configurado y en ejecución.
* El estilo de seguridad de la SVM debe ser NTFS.
* A partir de ONTAP 9.13.1, se pueden crear volúmenes con análisis de capacidad y seguimiento de actividades habilitados. Para activar la capacidad o el seguimiento de actividad, ejecute el `volume create` comando con `-analytics-state` o `-activity-tracking-state` establezca en `on`.
+
Para obtener más información sobre el análisis de capacidad y el seguimiento de actividades, consulte https://docs.netapp.com/us-en/ontap/task_nas_file_system_analytics_enable.html["Active File System Analytics"]. Obtenga más información sobre `volume create` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["Referencia de comandos del ONTAP"^].



.Pasos
. Cree el volumen con un punto de unión: `volume create -vserver _svm_name_ -volume _volume_name_ -aggregate _aggregate_name_ -size {integer[KB|MB|GB|TB|PB]} -security-style ntfs -junction-path _junction_path_]`
+
Las opciones para `-junction-path` son las siguientes:

+
** Directamente bajo raíz, por ejemplo, `/new_vol`
+
Puede crear un nuevo volumen y especificar que se monte directamente en el volumen raíz de SVM.

** En un directorio existente, por ejemplo, `/existing_dir/new_vol`
+
Puede crear un nuevo volumen y especificar que se monte en un volumen existente (en una jerarquía existente), expresado como un directorio.



+
Si desea crear un volumen en un nuevo directorio (en una jerarquía nueva en un volumen nuevo), por ejemplo, `/new_dir/new_vol`, primero debe crear un volumen primario nuevo que esté unido al volumen raíz de la SVM. A continuación, creará el nuevo volumen secundario en la ruta de unión del nuevo volumen principal (nuevo directorio).

. Compruebe que el volumen se creó con el punto de unión deseado: `volume show -vserver _svm_name_ -volume _volume_name_ -junction`


.Ejemplos
El siguiente comando crea un nuevo volumen denominado user1 en la SVM vs1.example.com y el agregado aggr1. El nuevo volumen está disponible en `/users`. El tamaño del volumen es de 750 GB y su garantía de volumen es del tipo volumen (de forma predeterminada).

[listing]
----
cluster1::> volume create -vserver vs1.example.com -volume users -aggregate aggr1 -size 750g -junction-path /users
[Job 1642] Job succeeded: Successful

cluster1::> volume show -vserver vs1.example.com -volume users -junction
                          Junction                 Junction
Vserver           Volume  Active   Junction Path   Path Source
----------------- ------- -------- --------------- -----------
vs1.example.com   users1  true     /users          RW_volume
----
El siguiente comando crea un nuevo volumen denominado «'home4'» en la SVM»'vs1.example.com`" y el agregado «'aggr1'». El directorio `/eng/` ya existe en el espacio de nombres para la SVM de VS1, y el nuevo volumen está disponible en `/eng/home`, que se convierte en el directorio inicial del `/eng/` espacio de nombres. El volumen tiene un tamaño de 750 GB y su garantía de volumen es de tipo `volume` (de forma predeterminada).

[listing]
----
cluster1::> volume create -vserver vs1.example.com -volume home4 -aggregate aggr1 -size 750g -junction-path /eng/home
[Job 1642] Job succeeded: Successful

cluster1::> volume show -vserver vs1.example.com -volume home4 -junction
                         Junction                 Junction
Vserver          Volume  Active   Junction Path   Path Source
---------------- ------- -------- --------------- -----------
vs1.example.com  home4   true     /eng/home       RW_volume
----