---
permalink: smb-config/requirements-create-share-concept.html 
sidebar: sidebar 
keywords: creating, create, smb, share, requirement, path, properties, property, home, directories, directory, requirements and considerations for creating an smb share 
summary: Antes de crear un recurso compartido SMB, debe comprender los requisitos para las rutas de acceso compartidas y las propiedades compartidas, especialmente para los directorios iniciales. 
---
= Requisitos y consideraciones al crear recursos compartidos SMB de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de crear un recurso compartido SMB, debe comprender los requisitos para las rutas de acceso compartidas y las propiedades compartidas, especialmente para los directorios iniciales.

La creación de un recurso compartido de SMB implica especificar una estructura de ruta de directorio (mediante `-path` la opción del `vserver cifs share create` comando) a la que accederán los clientes. La ruta de directorio corresponde a la ruta de unión para un volumen o qtree que ha creado en el espacio de nombres de la SVM. Debe haber la ruta de directorio y la ruta de unión correspondiente antes de crear el recurso compartido.

Las rutas de recursos compartidos tienen los siguientes requisitos:

* Un nombre de ruta de acceso de directorio puede tener hasta 255 caracteres.
* Si hay un espacio en el nombre de la ruta de acceso, toda la cadena se debe poner entre comillas (por ejemplo, `"/new volume/mount here"`).
* Si la ruta UNC (`\\servername\sharename\filepath`) del recurso compartido contiene más de 256 caracteres (excluyendo el ''\'' inicial en la ruta UNC), entonces la pestaña *Seguridad* en el cuadro Propiedades de Windows no estará disponible.
+
Se trata de un problema del cliente Windows y no de un problema de ONTAP. Para evitar este problema, no cree recursos compartidos con rutas UNC con más de 256 caracteres.



Se pueden cambiar los valores predeterminados de las propiedades compartidas:

* Las propiedades iniciales por defecto para todos los recursos compartidos son `oplocks`, , `browsable` `changenotify` y `show-previous-versions`.
* Es opcional especificar propiedades de recurso compartido al crear un recurso compartido.
+
Sin embargo, si especifica propiedades de recurso compartido al crear el recurso compartido, no se utilizan los valores predeterminados. Si utiliza `-share-properties` el parámetro al crear un recurso compartido, debe especificar todas las propiedades de recurso compartido que desea aplicar al recurso compartido mediante una lista delimitada por comas.

* Para designar un recurso compartido de directorio principal, utilice la `homedirectory` propiedad.
+
Esta función permite configurar un recurso compartido que se asigna a directorios diferentes en función del usuario que se conecta a él y un conjunto de variables. En lugar de tener que crear recursos compartidos independientes para cada usuario, puede configurar un solo recurso compartido con varios parámetros del directorio inicial para definir la relación de un usuario entre un punto de entrada (el recurso compartido) y su directorio inicial (un directorio en la SVM).

+
[NOTE]
====
No puede agregar ni quitar esta propiedad después de crear el recurso compartido.

====


Los recursos compartidos del directorio inicial tienen los siguientes requisitos:

* Antes de crear directorios iniciales SMB, debe añadir al menos una ruta de búsqueda del directorio inicial mediante `vserver cifs home-directory search-path add` el comando.
* Los recursos compartidos del directorio inicial especificados por el valor de `homedirectory` en el `-share-properties` parámetro deben incluir `%w` la variable dinámica (nombre de usuario de Windows) en el nombre del recurso compartido.
+
El nombre del recurso compartido puede contener además la `%d` variable dinámica (nombre de dominio) (por ejemplo, `%d/%w`) o una parte estática en el nombre del recurso compartido (por ejemplo, `home1_%w`).

* Si los administradores o usuarios utilizan el recurso compartido para conectarse a los directorios principales de otros usuarios (mediante las opciones del `vserver cifs home-directory modify` comando), el patrón de nombre de recurso compartido dinámico debe ir precedido por una tilde (`~`).


Obtenga más información sobre `vserver cifs share` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs+share["Referencia de comandos del ONTAP"^].

.Información relacionada
* link:../smb-admin/index.html["Gestión de SMB"]

