---
permalink: smb-config/verify-user-access-task.html 
sidebar: sidebar 
keywords: test, user, configure, access, smb, share, file, contain, verify user access 
summary: Debe probar que los usuarios configurados pueden acceder al recurso compartido de SMB y a los archivos que contiene. 
---
= Compruebe el acceso al recurso compartido del usuario SMB de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe probar que los usuarios configurados pueden acceder al recurso compartido de SMB y a los archivos que contiene.

.Pasos
. En un cliente Windows, inicie sesión como uno de los usuarios que ahora tiene acceso al recurso compartido.
. En el menú *Herramientas* del Explorador de Windows, seleccione *asignar unidad de red*.
. Complete el cuadro *Unidad de red de mapas*:
+
.. Seleccione una letra *Unidad*.
.. En el cuadro *carpeta*, escriba el nombre del recurso compartido que proporcionará a los usuarios.
+
Si el nombre de su servidor SMB es SMB_SERVER01 y su recurso compartido se denomina «`share1`», debe introducir `\\SMB_SERVER01\share1`.

.. Haga clic en *Finalizar*.


+
La unidad seleccionada está montada y lista con la ventana del Explorador de Windows que muestra archivos y carpetas contenidos en el recurso compartido.

. Cree un archivo de prueba, compruebe que existe, escriba texto y quite el archivo de prueba.

