---
permalink: smb-config/verify-client-access-task.html 
sidebar: sidebar 
keywords: verify, configure, smb, correct, access, writing, write, data, share, server, name, netbios, alias, verify smb client access 
summary: Debe verificar si ha configurado SMB correctamente accediendo y escribiendo los datos en el recurso compartido. Debe probar el acceso utilizando el nombre del servidor SMB y todos los alias NetBIOS. 
---
= Compruebe el acceso del cliente SMB de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe verificar si ha configurado SMB correctamente accediendo y escribiendo los datos en el recurso compartido. Debe probar el acceso utilizando el nombre del servidor SMB y todos los alias NetBIOS.

.Pasos
. Inicie sesión en un cliente Windows.
. Probar el acceso mediante el nombre del servidor SMB:
+
.. En el Explorador de Windows, asigne una unidad al recurso compartido en el siguiente formato: `\⁠\\SMB_Server_Name\Share_Name`
+
Si la asignación no se realiza correctamente, es posible que la asignación DNS aún no se haya propagado por toda la red. Debe probar el acceso más adelante con el nombre del servidor SMB.

+
Si el servidor SMB se llama vs1.example.com y el recurso compartido se llama share1, debe introducir lo siguiente: `\⁠\vs0.example.com\SHARE1`

.. En la unidad recién creada, cree un archivo de prueba y, a continuación, elimine el archivo.


+
Verificó el acceso de escritura al recurso compartido mediante el nombre del servidor SMB.

. Repita el paso 2 para cualquier alias NetBIOS.

