---
permalink: disks-aggregates/assign-aggregates-svms-task.html 
sidebar: sidebar 
keywords: assign, aggregate, local tier, svm, storage vm, vserver 
summary: 'Si asigna uno o varios niveles locales a una  máquina virtual de almacenamiento (máquina virtual de almacenamiento o SVM, anteriormente conocida como Vserver), únicamente podrá utilizar los niveles locales para contener volúmenes para esa SVM. A.' 
---
= Asignar niveles locales de ONTAP a máquinas virtuales de almacenamiento (SVM)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si asigna uno o varios niveles locales a una máquina virtual de almacenamiento (máquina virtual de almacenamiento o SVM, anteriormente conocida como Vserver), solo se pueden utilizar los niveles locales para contener volúmenes para esa máquina virtual de almacenamiento (SVM).


NOTE: Antes de ONTAP 9,7, System Manager utiliza el término _aggregate_ para describir un _nivel local_. Independientemente de la versión de ONTAP, la interfaz de línea de comandos de ONTAP utiliza el término _aggregate_. Para obtener más información sobre los niveles locales, consulte link:../disks-aggregates/index.html["Discos y niveles locales"].

.Antes de empezar
La máquina virtual de almacenamiento y los niveles locales que desea asignar a esa máquina virtual de almacenamiento ya deben existir.

.Acerca de esta tarea
La asignación de niveles locales a sus máquinas virtuales de almacenamiento le ayuda a mantener sus máquinas virtuales de almacenamiento aisladas entre sí; esto es especialmente importante en un entorno multi-tenancy.

.Pasos
. Compruebe la lista de niveles locales ya asignados a la SVM:
+
`vserver show -fields aggr-list`

+
Se muestran los niveles locales actualmente asignados a la SVM. Si no hay niveles locales asignados, `-` se muestra.

. Agregue o elimine niveles locales asignados, según sus requisitos:
+
|===


| Si desea... | Se usa este comando... 


 a| 
Asigne niveles locales adicionales
 a| 
`vserver add-aggregates`



 a| 
Anular la asignación de niveles locales
 a| 
`vserver remove-aggregates`

|===
+
Los niveles locales mostrados se asignan a la SVM o se eliminan de ella. Si la SVM ya tiene volúmenes que utilizan un agregado que no está asignado a la SVM, se muestra un mensaje de advertencia pero el comando se ha completado correctamente. Los niveles locales que ya se asignaron a la SVM y que no se nombraron en el comando no se ven afectados.



.Ejemplo
En el ejemplo siguiente, los niveles locales aggr1 y aggr2 se asignan a SVM svm1:

`vserver add-aggregates -vserver svm1 -aggregates aggr1,aggr2`
