---
permalink: disks-aggregates/commands-display-storage-shelves-reference.html 
sidebar: sidebar 
keywords: commands, display, information, storage, shelves 
summary: El comando Storage shelf show se utiliza para mostrar información de configuración y errores de las bandejas de discos. 
---
= Comandos de la ONTAP para mostrar información sobre las bandejas de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El `storage shelf show` comando se utiliza para mostrar información de configuración y errores de las bandejas de discos.

|===
| Si desea mostrar... | Se usa este comando... 


 a| 
Información general sobre la configuración de bandejas y el estado del hardware
 a| 
`storage shelf show`



 a| 
Información detallada de una bandeja específica, incluido el ID de pila
 a| 
`storage shelf show -shelf`



 a| 
Sin resolver, el cliente puede actuar, errores por bandeja
 a| 
`storage shelf show -errors`



 a| 
Información sobre la bahía
 a| 
`storage shelf show -bay`



 a| 
Información sobre la conectividad
 a| 
`storage shelf show -connectivity`



 a| 
Información de refrigeración, incluidos los sensores de temperatura y los ventiladores de refrigeración
 a| 
`storage shelf show -cooling`



 a| 
Información sobre los módulos de E/S.
 a| 
`storage shelf show -module`



 a| 
Información del puerto
 a| 
`storage shelf show -port`



 a| 
Información de alimentación, incluidas las fuentes de alimentación (unidades de alimentación), los sensores de corriente y los sensores de tensión
 a| 
`storage shelf show -power`

|===
.Información relacionada
* https://docs.netapp.com/us-en/ontap-cli["Referencia de comandos del ONTAP"^]

