---
permalink: disks-aggregates/configure-auto-assignment-disk-ownership-task.html 
sidebar: sidebar 
keywords: change, modify, automatic, assignment, disk ownership 
summary: Se puede usar el comando Storage disk option modify para seleccionar una política no predeterminada que asigne automáticamente propiedad de disco o para deshabilitar la asignación automática de propiedad de disco. 
---
= Cambie la configuración de la asignación automática de propiedad de disco
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `storage disk option modify` comando para seleccionar una política no predeterminada para la asignación automática de propiedad de disco o para deshabilitar la asignación automática de propiedad de disco.

Descubra link:disk-autoassignment-policy-concept.html["asignación automática de propiedad de disco"].

.Acerca de esta tarea
Si tiene una pareja de alta disponibilidad con solo DS460C bandejas, la política de asignación automática predeterminada es de medio cajón. No es posible cambiar a una política no predeterminada (bahía, bandeja, pila).

.Pasos
. Modificar la asignación automática de discos:
+
.. Si desea seleccionar una política no predeterminada, introduzca:
+
`storage disk option modify -autoassign-policy _autoassign_policy_ -node _node_name_`

+
*** Uso `stack` como la `_autoassign_policy_` para configurar la propiedad automática a nivel de pila o bucle.
*** Uso `shelf` como la `_autoassign_policy_` para configurar la propiedad automática en el nivel de bandeja.
*** Uso `bay` como la `_autoassign_policy_` para configurar la propiedad automática a nivel de bahía.


.. Si desea deshabilitar la asignación automática de propiedad de disco, introduzca:
+
`storage disk option modify -autoassign off -node _node_name_`



. Compruebe la configuración de asignación automática de los discos:
+
`storage disk option show`

+
[listing]
----
cluster1::> storage disk option show

Node           BKg. FW. Upd.  Auto Copy     Auto Assign    Auto
                                                           Assign Policy
-------------  -------------  ------------  -------------  --------
cluster1-1     on             on            on             default
cluster1-2     on             on            on             default
----

