---
permalink: disks-aggregates/convert-raid-dp-tec-task.html 
sidebar: sidebar 
keywords: convert, raid-dp, raid-tec, raid policy 
summary: Si desea disfrutar de la protección añadida de la triple paridad, puede convertir de RAID-DP a RAID-TEC. RAID-TEC se recomienda si el tamaño de los discos utilizados en el nivel local es superior a 4 TiB. 
---
= Convertir de ONTAP RAID-DP a RAID-TEC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea disfrutar de la protección añadida de la triple paridad, puede convertir de RAID-DP a RAID-TEC. RAID-TEC se recomienda si el tamaño de los discos utilizados en el nivel local es superior a 4 TiB.


NOTE: Antes de ONTAP 9,7, System Manager utiliza el término _aggregate_ para describir un _nivel local_. Independientemente de la versión de ONTAP, la interfaz de línea de comandos de ONTAP utiliza el término _aggregate_. Para obtener más información sobre los niveles locales, consulte link:../disks-aggregates/index.html["Discos y niveles locales"].

.Antes de empezar
El nivel local que se va a convertir debe tener un mínimo de siete discos.

.Acerca de esta tarea
* Los niveles locales de la unidad de disco duro (HDD) pueden convertirse de RAID-DP a RAID-TEC. Esto incluye niveles de HDD en niveles locales de Flash Pool.


.Proceso para flashpools/agregados híbridos donde se debe usar -disktype para cambiar cada tipo de disco
[-T, -disktype {ATA | BSAS | FCAL | FSAS | LUN | MSATA | SAS | SSD | VMDISK | SSD-NVM | SSD-CAP | SSD-ZNS | VMLUN | VMLUN-SSD}] - tipo de disco

Este parámetro especifica el tipo de disco de los grupos RAID que se van a modificar. En caso de Flash Pool, especifica el nivel HDD o el nivel SSD. Si el nivel HDD está compuesto por más de un tipo de disco, especificar cualquiera de los tipos de disco en uso hace que se modifique ese nivel. Si el tipo RAID agregado actual es mixed_raid_type, este parámetro es obligatorio.

.Pasos
. Compruebe que el nivel local esté en línea y que tenga un mínimo de seis discos:
+
`storage aggregate show-status -aggregate _aggregate_name_`

. Convertir el nivel local de RAID-DP a RAID-TEC:
+
`storage aggregate modify -aggregate _aggregate_name_ -raidtype raid_tec`

. Compruebe que la política de RAID de nivel local es RAID-TEC:
+
`storage aggregate show _aggregate_name_`



.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html["modificar agregado de almacenamiento"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-status.html["estado del agregado de almacenamiento"^]

