---
permalink: disks-aggregates/determine-impact-cache-size-adding-ssds-task.html 
sidebar: sidebar 
keywords: determine, impact, cache, size, ssds, storage pool 
summary: 'Si se añaden unidades SSD a un pool de almacenamiento, se superará el límite de caché del modelo de la plataforma, ONTAP no asigna la capacidad recién añadida a ningún nivel local de Flash Pool (agregados). Esto puede hacer que parte o la totalidad de la capacidad recién añadida no estén disponibles para su uso.' 
---
= Determine el impacto en el tamaño de la caché de añadir SSD a un pool de almacenamiento SSD
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si se añaden SSD a un pool de almacenamiento, se superará el límite de caché del modelo de la plataforma, ONTAP no asigna la capacidad recién añadida a ningún nivel local de Flash Pool (agregados). Esto puede hacer que parte o la totalidad de la capacidad recién añadida no estén disponibles para su uso.

.Acerca de esta tarea
Cuando se añaden SSD a un pool de almacenamiento SSD con unidades de asignación ya asignadas a los niveles locales de Flash Pool (agregados), se aumenta el tamaño de la caché de cada uno de esos niveles locales y la caché total del sistema. Si ninguna de las unidades de asignación del pool de almacenamiento se asignó, la adición de SSD a ese pool de almacenamiento no afecta al tamaño de la caché SSD hasta que una o más unidades de asignación se asignan a una caché.

.Pasos
. Determine el tamaño utilizable de los SSD que va a añadir al pool de almacenamiento:
+
`storage disk show _disk_name_ -fields usable-size`

. Determine cuántas unidades de asignación quedan sin asignar para el pool de almacenamiento:
+
`storage pool show-available-capacity _sp_name_`

+
Se muestran todas las unidades de asignación no asignados del grupo de almacenamiento.

. Calcule la cantidad de caché que se agregará aplicando la siguiente fórmula:
+
( 4 -- número de unidades de asignación sin asignar) × 25% × tamaño utilizable × número de SSD


