---
permalink: disks-aggregates/determine-flash-pool-aggregate-ssd-storage-task.html 
sidebar: sidebar 
keywords: determine, flash pool, aggregate, local tier, ssd storage pool 
summary: El nivel local de Flash Pool se gestiona de forma diferente cuando se utilizan pools de almacenamiento SSD para proporcionar la caché que cuando se utilizan SSD discretos. 
---
= Determinar si un nivel local Flash Pool de ONTAP utiliza un pool de almacenamiento SSD
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar un nivel local de Flash Pool añadiendo una o varias unidades de asignación de un pool de almacenamiento de SSD a un nivel local de HDD existente.


NOTE: Antes de ONTAP 9,7, System Manager utiliza el término _aggregate_ para describir un _nivel local_. Independientemente de la versión de ONTAP, la interfaz de línea de comandos de ONTAP utiliza el término _aggregate_. Para obtener más información sobre los niveles locales, consulte link:../disks-aggregates/index.html["Discos y niveles locales"].

Los niveles locales de Flash Pool se gestionan de manera diferente cuando utilizan pools de almacenamiento SSD para proporcionar su caché que cuando utilizan SSD independientes.

.Paso
. Mostrar las unidades del nivel local por grupo RAID:
+
`storage aggregate show-status _aggr_name_`

+
Si el nivel local utiliza uno o más pools de almacenamiento SSD, el valor de `Position` la columna de los grupos RAID de SSD se muestra como `Shared`y el nombre del pool de almacenamiento se muestra junto al nombre del grupo RAID.


