---
permalink: disks-aggregates/determine-modify-caching-policy-flash-pool-task.html 
sidebar: sidebar 
keywords: modify, cache, policy, flash pool, aggregate, local tier 
summary: Se pueden asignar políticas de retención de caché a los volúmenes en los niveles locales de Flash Pool para determinar cuánto tiempo permanecen los datos del volumen en la caché Flash Pool. Sin embargo, en algunos casos, cambiar la política de retención de caché puede no afectar la cantidad de tiempo que permanecen los datos del volumen en la caché. 
---
= Determine si se modifica la política de almacenamiento en caché de ONTAP de los niveles locales de Flash Pool
:allow-uri-read: 


[role="lead"]
Se pueden asignar políticas de retención de caché a los volúmenes en los niveles locales de Flash Pool para determinar cuánto tiempo permanecen los datos del volumen en la caché Flash Pool. Sin embargo, en algunos casos, cambiar la política de retención de caché puede no afectar la cantidad de tiempo que permanecen los datos del volumen en la caché.

.Acerca de esta tarea
Si los datos cumplen alguna de las siguientes condiciones, es posible que el cambio de la política de retención de caché no afecte:

* La carga de trabajo es secuencial.
* Su carga de trabajo no releer los bloques aleatorios almacenados en caché en las unidades de estado sólido (SSD).
* El tamaño de la caché del volumen es demasiado pequeño.


.Pasos
Los siguientes pasos comprueban las condiciones que deben cumplir los datos. La tarea debe realizarse mediante la interfaz de línea de comandos en modo de privilegios avanzado.

. Use la interfaz de línea de comandos para ver el volumen de carga de trabajo:
+
`statistics start -object workload_volume`

. Determine el patrón de carga de trabajo del volumen:
+
`statistics show -object workload_volume -instance _volume-workload_ -counter sequential_reads`

. Determine la tasa de aciertos del volumen:
+
`statistics show -object wafl_hya_vvol -instance _volume_ -counter read_ops_replaced_pwercent|wc_write_blks_overwritten_percent`

. Determine `Cacheable Read` el y `Project Cache Alloc` del volumen:
+
`system node run -node node_name wafl awa start _aggr_name_`

. Mostrar el resumen de AWA:
+
`system node run -node node_name wafl awa print _aggr_name_`

. Compare la tasa de aciertos del volumen con `Cacheable Read` la .
+
Si la tasa de aciertos del volumen es superior a `Cacheable Read` , la carga de trabajo no vuelve a leer los bloques aleatorios almacenados en caché en los SSD.

. Compare el tamaño de caché actual del volumen con el `Project Cache Alloc`.
+
Si el tamaño de caché actual del volumen es mayor que `Project Cache Alloc` , el tamaño de la caché del volumen es demasiado pequeño.



.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/statistics-show.html["Las estadísticas muestran"^]

