---
permalink: disks-aggregates/fast-zeroing-drives-concept.html 
sidebar: sidebar 
keywords: fast, zero, drives 
summary: En los sistemas recién instalados con ONTAP 9.4 o posterior y los sistemas reinicializados con ONTAP 9.4 o posterior, se utiliza _fast Zero_ para poner a cero unidades. 
---
= Puesta a cero rápida de las unidades
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En los sistemas recién instalados con ONTAP 9.4 o posterior y los sistemas reinicializados con ONTAP 9.4 o posterior, se utiliza _fast Zero_ para poner a cero unidades.

Con _FAST puesta a cero_, las unidades se ponen a cero en segundos. Esta acción se realiza automáticamente antes del aprovisionamiento y reduce en gran medida el tiempo necesario para inicializar el sistema, crear agregados o expandir los agregados cuando se añaden unidades de repuesto.

_Fast puesta a cero_ es compatible tanto con SSD como con HDD.


NOTE: _La puesta a cero rápida_ no es compatible con los sistemas actualizados desde ONTAP 9.3 o versiones anteriores. ONTAP 9.4 o posterior debe estar recién instalado o el sistema debe ser reinicializado. En ONTAP 9.3 y versiones anteriores, ONTAP también pone a cero automáticamente las unidades, pero el proceso tarda más tiempo.

Si necesita poner a cero una unidad manualmente, puede usar uno de los siguientes métodos. En ONTAP 9.4 y versiones posteriores, la puesta a cero manual de una unidad también tarda solo segundos.

[role="tabbed-block"]
====
.Comando de la CLI
--
*Utilice un comando CLI para unidades FAST-Zero*

.Acerca de esta tarea
Se requieren privilegios de administrador para usar este comando.

.Pasos
. Introduzca el comando CLI:
+
`storage disk zerospares`



--
.Opciones del menú de inicio
--
*Seleccione las opciones del menú de inicio a unidades FAST-Zero*

.Acerca de esta tarea
* La mejora de puesta a cero rápida no admite sistemas actualizados desde una versión anterior a ONTAP 9.4.
* Si algún nodo del clúster contiene un nivel local (agregado) con unidades a cero rápido, no puede revertir el clúster a ONTAP 9.2 o una versión anterior.


.Pasos
. En el menú de inicio, seleccione una de las siguientes opciones:
+
** (4) limpiar la configuración e inicializar todos los discos
** (9a) desparticionar todos los discos y eliminar su información de propiedad
** (9b) limpiar la configuración e inicializar el nodo con discos completos




--
====