---
permalink: disks-aggregates/flash-pool-aggregate-caching-policies-concept.html 
sidebar: sidebar 
keywords: cache, flash pool, policy, local tier, aggregate 
summary: Las políticas de almacenamiento en caché se aplican a volúmenes que residen en niveles locales de Flash Pool. Debe comprender el funcionamiento de las políticas de almacenamiento en caché antes de cambiarlas. 
---
= Políticas de almacenamiento en caché de nivel local Flash Pool ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las políticas de almacenamiento en caché para los volúmenes de un nivel local de Flash Pool le permiten poner en marcha Flash como caché de alto rendimiento para los conjuntos de datos de trabajo, al tiempo que se utilizan HDD de menor coste para los datos a los que se accede con menos frecuencia. Si va a proporcionar caché a dos o más niveles locales de Flash Pool, debe usar la partición de SSD de Flash Pool para compartir SSD en los niveles locales de Flash Pool.

Las políticas de almacenamiento en caché se aplican a volúmenes que residen en niveles locales de Flash Pool. Debe comprender el funcionamiento de las políticas de almacenamiento en caché antes de cambiarlas.

En la mayoría de los casos, la política de almacenamiento en caché predeterminada de `auto` es la mejor política de almacenamiento en caché a utilizar. La política de almacenamiento en caché solo se debe cambiar si otra política proporciona un mejor rendimiento para su carga de trabajo. La configuración de una normativa de almacenamiento en caché errónea puede degradar de manera considerable el rendimiento del volumen; la degradación del rendimiento puede aumentar de forma gradual con el tiempo.

Las políticas de almacenamiento en caché combinan una política de almacenamiento en caché de lectura y una política de almacenamiento en caché de escritura. El nombre de la política concatena los nombres de la política de almacenamiento en caché de lectura y la política de almacenamiento en caché de escritura, separados por un guión. Si no hay ningún guión en el nombre de la política, la política de almacenamiento en caché de escritura es `none`, excepto para `auto` la política.

Las políticas de almacenamiento en caché de lectura optimizan para el rendimiento de lectura futuro al colocar una copia de los datos en la caché además de los datos almacenados en HDD. Para las políticas de almacenamiento en caché de lectura que insertan datos en la caché para operaciones de escritura, la caché funciona como una caché _write-through_.

Los datos insertados en la caché utilizando la política de almacenamiento en caché de escritura solo existen en la caché; no se copian en las HDD. La caché de Flash Pool está protegida por RAID. Al habilitar el almacenamiento en caché de escritura, los datos de las operaciones de escritura están disponibles para las lecturas desde la caché inmediatamente, mientras se posponen la escritura de los datos en las unidades de disco duro hasta que envejecen en la caché.

Si mueve un volumen de un nivel local de Flash Pool a un nivel local de un único nivel, perderá su política de almacenamiento en caché; si más adelante lo vuelve a mover a un nivel local de Flash Pool, se le asignará la política de almacenamiento en caché predeterminada de `auto`. Si mueve un volumen entre dos nivel local de Flash Pool, se conserva la política de almacenamiento en caché.



== Cambiar una política de almacenamiento en caché

Puede usar la CLI para cambiar la política de almacenamiento en caché de un volumen que reside en un nivel local de Flash Pool mediante el `-caching-policy` parámetro con `volume create` el comando.

Cuando se crea un volumen en un nivel local de Flash Pool, de forma predeterminada, la `auto` política de almacenamiento en caché se asigna al volumen.
