---
permalink: disks-aggregates/hot-spare-disks-work-concept.html 
sidebar: sidebar 
keywords: hot, spare disks, work 
summary: Un disco de repuesto activo es un disco que está asignado a un sistema de almacenamiento y está listo para su uso, pero no lo está utilizando un grupo RAID y no contiene ningún dato. 
---
= Cómo funcionan los discos de repuesto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un disco de repuesto activo es un disco que está asignado a un sistema de almacenamiento y está listo para su uso, pero no lo está utilizando un grupo RAID y no contiene ningún dato.

Si se produce un fallo de disco dentro de un grupo RAID, el disco de repuesto activo se asigna automáticamente al grupo RAID para sustituir los discos que han fallado. Los datos del disco con error se reconstruyen en el disco de repuesto en segundo plano desde el disco de paridad RAID. La actividad de reconstrucción se registra en la `/etc/message` Se envía un archivo y un mensaje AutoSupport.

Si el disco de repuesto activo disponible no tiene el mismo tamaño que el disco que ha fallado, se elige un disco del siguiente tamaño mayor y, a continuación, se reducirá para que coincida con el tamaño del disco que va a sustituir.



== Requisitos de repuesto para el disco portador de varios discos

Mantener el número correcto de repuestos para los discos en portadores de discos es fundamental para optimizar la redundancia de almacenamiento y minimizar el tiempo que ONTAP debe dedicar a copiar discos para lograr una distribución óptima de los discos.

Debe mantener un mínimo de dos piezas de repuesto para los discos portadores de varios discos en todo momento. Para admitir el uso del centro de mantenimiento y evitar problemas causados por varios fallos de disco simultáneos, debe mantener al menos cuatro repuestos en caliente para que el funcionamiento siempre sea estable y sustituir los discos con fallos con prontitud.

Si dos discos fallan al mismo tiempo con solo dos piezas de repuesto disponibles, es posible que ONTAP no pueda cambiar el contenido del disco con fallo y la relación de posición del portador con los discos de repuesto. Este escenario se denomina un punto muerto. Si esto sucede, se le notificarán mediante mensajes de EMS y AutoSupport. Cuando los operadores de sustitución estén disponibles, debe seguir las instrucciones proporcionadas por los mensajes EMS. Para obtener información acerca de mí, consulte el artículo de la base de conocimientos link:++https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/Draft_-_RAID_Layout_Cannot_Be_Autocorrected_-_AutoSupport_message++["El diseño RAID no se puede autoCorrectar - mensaje AutoSupport"]
