---
permalink: disks-aggregates/remove-failed-disk-task.html 
sidebar: sidebar 
keywords: remove, fail, disk 
summary: ONTAP ya no considera un disco completamente fallido como un disco utilizable y puede desconectar inmediatamente el disco de la bandeja de discos. Sin embargo, debería dejar un disco parcialmente fallido conectado lo suficiente como para que finalice el proceso de recuperación de RAID rápida. 
---
= Elimine un disco ONTAP con fallos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un disco que ha fallado completamente ya no tiene en cuenta ONTAP como un disco utilizable y puede desconectar inmediatamente el disco de la bandeja de discos. Sin embargo, debería dejar un disco parcialmente fallido conectado lo suficiente como para que finalice el proceso de recuperación de RAID rápida.

.Acerca de esta tarea
Si va a quitar un disco porque ha fallado o porque está produciendo mensajes de error excesivos, no debe volver a utilizar el disco en este o cualquier otro sistema de almacenamiento.

.Pasos
. Utilice la interfaz de línea de comandos para encontrar el ID del disco con errores:
+
`storage disk show -broken`

+
Si el disco no aparece en la lista de discos con errores, puede que haya fallado parcialmente, con una recuperación de RAID rápida en proceso. En este caso, debe esperar hasta que el disco esté presente en la lista de discos defectuosos (lo que significa que el proceso de recuperación rápida de RAID está completo) antes de quitar el disco.

. Determine la ubicación física del disco que desea quitar:
+
`storage disk set-led -action on -disk _disk_name_ 2`

+
El LED de fallo de la parte frontal del disco se ilumina.

. Quite el disco de la bandeja de discos siguiendo las instrucciones de la guía de hardware para su modelo de bandeja de discos.


.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-set-led.html["conjunto de discos de almacenamiento dirigido"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-show.html["Mostrar disco de almacenamiento"^]

