---
permalink: disks-aggregates/sanitize-disk-maintenance-mode-task.html 
sidebar: sidebar 
keywords: sanitize, disk, maintenance mode, nodeshell, node shell, sanitization 
summary: A partir de ONTAP 9.6, puede realizar un saneamiento de disco en modo de mantenimiento. Esto le permite eliminar datos de un disco o un conjunto de discos en sistemas retirados del servicio o inoperables para que los datos nunca puedan recuperarse. 
---
= Saneamiento de un disco ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El saneamiento de un disco le permite eliminar datos de un disco o un conjunto de discos en sistemas retirados del servicio o inoperables para que los datos nunca puedan recuperarse.

Existen dos métodos para desinfectar discos utilizando la CLI:

.Desinfecte un disco con los comandos &#8220;modo de mantenimiento&#8221;
[%collapsible]
====
A partir de ONTAP 9.6, puede realizar un saneamiento de disco en modo de mantenimiento.

.Antes de empezar
* Los discos no pueden ser discos de autocifrado (SED).
+
Debe utilizar `storage encryption disk sanitize` el comando para desinfectar un SED.

+
link:../encryption-at-rest/index.html["Cifrado de datos en reposo"]

+
Obtenga más información sobre `storage encryption disk sanitize` en el link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-sanitize.html["Referencia de comandos del ONTAP"^].



.Pasos
. Arranque en modo de mantenimiento.
+
.. Para salir del shell actual, introduzca `halt`.
+
Aparece el aviso del CARGADOR.

.. Introduzca el modo de mantenimiento `boot_ontap maint` .
+
Después de ver alguna información, se muestra el símbolo del sistema del modo de mantenimiento.



. Si los discos que desea desinfectar se crean particiones, desparticionar cada disco:
+

NOTE: El comando para desparticionar un disco solo está disponible en el nivel de diagnóstico y debe ejecutarse únicamente bajo la supervisión del soporte de NetApp . Se recomienda encarecidamente que se comunique con el soporte técnico de NetApp antes de continuar. También puedes consultar ellink:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_unpartition_a_spare_drive_in_ONTAP["Base de conocimientos de NetApp : Cómo desparticionar una unidad de repuesto en ONTAP"^]

+
`disk unpartition <disk_name>`

. Desinfecte los discos especificados:
+
`disk sanitize start [-p <pattern1>|-r [-p <pattern2>|-r [-p <pattern3>|-r]]] [-c <cycle_count>] <disk_list>`

+

NOTE: No apague el nodo, interrumpa la conectividad de almacenamiento ni elimine los discos de destino mientras se está saneando. Si se interrumpe la operación durante la fase de formateo, se debe reiniciar la fase de formateo y se debe permitir que finalice antes de que los discos se sanearan y estén listos para ser devueltos al pool de reserva. Si necesita cancelar el proceso de saneamiento, puede hacerlo con el `disk sanitize abort` comando. Si los discos especificados se están sometiendo a la fase de formateo del saneamiento, la interrupción no se producirá hasta que se complete la fase.

+
 `-p` `<pattern1>` `-p` `<pattern2>` `-p` `<pattern3>` especifica un ciclo de uno a tres patrones de sobrescritura de bytes hexadecimales definidos por el usuario que se pueden aplicar sucesivamente a los discos que se están saneando. El patrón predeterminado son tres pasadas, usando 0x55 para la primera pasada, 0xaa para la segunda pasada y 0x3c para la tercera pasada.

+
`-r` reemplaza una sobrescritura con patrones por una sobrescritura aleatoria para cualquiera o todas las pasadas.

+
`-c` `<cycle_count>` especifica el número de veces que se aplican los patrones de sobrescritura especificados. El valor predeterminado es un ciclo. El valor máximo es siete ciclos.

+
`<disk_list>` Especifica una lista separada por espacios de los ID de los discos de repuesto que se van a sanear.

. Si lo desea, compruebe el estado del proceso de saneamiento de disco:
+
`disk sanitize status [<disk_list>]`

. Una vez completado el proceso de saneamiento, devuelva los discos al estado de reserva de cada disco:
+
`disk sanitize release <disk_name>`

. Salga del modo de mantenimiento.


====
.Desinfecte un disco con y#8220;nodeshell&#8221; comandos (todas las versiones de ONTAP 9)
[%collapsible]
====
Una vez habilitada la función de saneamiento de disco con comandos nodeshell en un nodo, no se puede deshabilitar.

.Antes de empezar
* Los discos deben ser discos de repuesto; deben ser propiedad de un nodo, pero no se deben utilizar en un nivel local.
+
Si los discos están particionados, ninguna partición puede estar en uso en un nivel local.

* Los discos no pueden ser discos de autocifrado (SED).
+
Debe utilizar `storage encryption disk sanitize` el comando para desinfectar un SED.

+
link:../encryption-at-rest/index.html["Cifrado de datos en reposo"]

* Los discos no pueden formar parte de una agrupación de almacenamiento.


.Pasos
. Si los discos que desea desinfectar se crean particiones, desparticionar cada disco:
+
--

NOTE: El comando para desparticionar un disco solo está disponible en el nivel de diagnóstico y debe ejecutarse únicamente bajo la supervisión del soporte de NetApp . **Se recomienda encarecidamente que se comunique con el soporte de NetApp antes de continuar.** También puedes consultar ellink:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_unpartition_a_spare_drive_in_ONTAP["Base de conocimientos de NetApp : Cómo desparticionar una unidad de repuesto en ONTAP"^] .

--
+
`disk unpartition <disk_name>`

. Introduzca el nodo que posee los discos que desea desinfectar:
+
`system node run -node <node_name>`

. Habilitar el saneamiento de disco:
+
`options licensed_feature.disk_sanitization.enable on`

+
Se le pide que confirme el comando porque es irreversible.

. Cambie al nivel de privilegio avanzado de Nodesinfierno:
+
`priv set advanced`

. Desinfecte los discos especificados:
+
`disk sanitize start [-p <pattern1>|-r [-p <pattern2>|-r [-p <pattern3>|-r]]] [-c <cycle_count>] <disk_list>`

+

NOTE: No apague el nodo, interrumpa la conectividad de almacenamiento ni elimine los discos de destino mientras se está saneando. Si se interrumpe la operación durante la fase de formateo, se debe reiniciar la fase de formateo y se debe permitir que finalice antes de que los discos se sanearan y estén listos para ser devueltos al pool de reserva. Si necesita anular el proceso de saneamiento, puede hacerlo mediante el comando Disk sanitize abort. Si los discos especificados se están sometiendo a la fase de formateo del saneamiento, la interrupción no se producirá hasta que se complete la fase.

+
`-p <pattern1> -p <pattern2> -p <pattern3>` especifica un ciclo de uno a tres patrones de sobrescritura de bytes hexadecimales definidos por el usuario que se pueden aplicar sucesivamente a los discos que se están saneando. El patrón predeterminado son tres pasadas, usando 0x55 para la primera pasada, 0xaa para la segunda pasada y 0x3c para la tercera pasada.

+
`-r` reemplaza una sobrescritura con patrones por una sobrescritura aleatoria para cualquiera o todas las pasadas.

+
`-c <cycle_count>` especifica el número de veces que se aplican los patrones de sobrescritura especificados.

+
El valor predeterminado es un ciclo. El valor máximo es siete ciclos.

+
`<disk_list>` Especifica una lista separada por espacios de los ID de los discos de repuesto que se van a sanear.

. Si desea comprobar el estado del proceso de saneamiento de disco:
+
`disk sanitize status [<disk_list>]`

. Una vez finalizado el proceso de saneamiento, devuelva los discos a estado de repuesto:
+
`disk sanitize release <disk_name>`

. Volver al nivel de privilegios de administración nodesinfierno:
+
`priv set admin`

. Volver a la CLI de ONTAP:
+
`exit`

. Determine si todos los discos se han devuelto al estado de repuesto:
+
`storage aggregate show-spare-disks`

+
[cols="1,2"]
|===


| Si... | Realice lo siguiente... 


| Todos los discos sanitizados se enumeran como repuestos | Ha terminado. Los discos se sanean y están en estado de repuesto. 


| Algunos de los discos sanitizados no aparecen como repuestos  a| 
Complete los siguientes pasos:

.. Entre en el modo de privilegio avanzado:
+
`set -privilege advanced`

.. Asigne los discos sanitizados sin asignar al nodo adecuado para cada disco:
+
`storage disk assign -disk <disk_name> -owner <node_name>`

.. Devuelva los discos al estado de repuesto de cada disco:
+
`storage disk unfail -disk <disk_name> -s -q`

.. Volver al modo administrativo:
+
`set -privilege admin`



|===
+
Obtenga más información sobre `storage aggregate show-spare-disks` en el link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-spare-disks.html["Referencia de comandos del ONTAP"^].



====
.Resultado
Los discos especificados están sancionados y designados como piezas de repuesto. Los números de serie de los discos higienizados se escriben en `/etc/log/sanitized_disks`.

Los registros de saneamiento de los discos especificados, que muestran lo que se ha completado en cada disco, se escriben en `/mroot/etc/log/sanitization.log`.

.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+aggregate+show["imagen del agregado de almacenamiento"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-assign.html["asignación de disco de almacenamiento"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-unfail.html["El disco de almacenamiento no falla"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-sanitize.html["Cifrado de almacenamiento, desinfección de disco"^]

