---
permalink: disks-aggregates/sanitization-tips-concept.html 
sidebar: sidebar 
keywords: disk, disk sanitization, local tier, aggregate, sensitive data, sanitize 
summary: Si vas a crear o realizar una copia de seguridad de niveles locales para contener datos que podrían necesitar ser saneados, seguir algunas sencillas directrices reducirá el tiempo necesario para desinfectar los datos. 
---
= Consejos para crear y realizar backups de niveles locales de ONTAP que contienen los datos que se van a sanear
:allow-uri-read: 


[role="lead"]
Si vas a crear o realizar una copia de seguridad de niveles locales para contener datos que podrían necesitar ser saneados, seguir algunas sencillas directrices reducirá el tiempo necesario para desinfectar los datos.

* Asegúrese de que los niveles locales que contienen datos confidenciales no sean mayores de lo que necesitan.
+
Si son más grandes de lo necesario, el saneamiento requiere más tiempo, espacio en disco y ancho de banda.

* Al realizar un backup de niveles locales que contengan datos confidenciales, se debe evitar realizar un backup del nivel local que también contenga grandes cantidades de datos no confidenciales.
+
De este modo se reducen los recursos necesarios para mover datos no confidenciales antes de sanitizar datos confidenciales.


