---
permalink: disks-aggregates/update-disk-qualification-package-concept.html 
sidebar: sidebar 
keywords: update, desk, qualification, package 
summary: 'El paquete de cualificación de disco (DQP) añade compatibilidad total con las unidades recién cualificadas. Antes de actualizar el firmware de la unidad o añadir nuevos tipos o tamaños de unidad a un clúster, debe actualizar el DQP. Una práctica recomendada es actualizar también el DQP regularmente; por ejemplo, cada trimestre o semestral.' 
---
= Cuando necesite actualizar el paquete de cualificación de disco
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El paquete de cualificación de disco (DQP) añade compatibilidad total con las unidades recién cualificadas. Antes de actualizar el firmware de la unidad o añadir nuevos tipos o tamaños de unidad a un clúster, debe actualizar el DQP. Una práctica recomendada es actualizar también el DQP regularmente; por ejemplo, cada trimestre o semestral.

Debe descargar e instalar el DQP en las siguientes situaciones:

* Cuando se añade un tamaño o un tipo de unidad nuevo al nodo
+
Por ejemplo, si ya tiene unidades de 1 TB y añade unidades de 2 TB, debe comprobar la actualización más reciente del DQP.

* Cada vez que se actualiza el firmware de disco
* Siempre que estén disponibles los archivos DQP o firmware de disco más nuevos
* Siempre que actualice a una versión nueva de ONTAP.
+
El DQP no se actualiza como parte de una actualización de ONTAP.



.Información relacionada
https://["Descargas de NetApp: Paquete de cualificación de disco"^]

https://["Descargas de NetApp: Firmware de la unidad de disco"^]
