---
permalink: flexgroup/aggregate-space-requirements-concept.html 
sidebar: sidebar 
keywords: guideline, aggregate, space, provision, flexgroup, volume 
summary: Debe conocer las consideraciones y los requisitos a la hora de seleccionar los agregados para aprovisionar un volumen de FlexGroup. 
---
= Directrices para el espacio de agregado al aprovisionar un volumen de FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe conocer las consideraciones y los requisitos a la hora de seleccionar los agregados para aprovisionar un volumen de FlexGroup.

Debe tener en cuenta las siguientes directrices al crear un volumen de FlexGroup para obtener los mejores resultados de rendimiento con un volumen de FlexGroup:

* Un volumen de FlexGroup debe abarcar únicamente agregados que utilicen sistemas de hardware idénticos.
+
El uso de sistemas de hardware idénticos ayuda a proporcionar un rendimiento previsible en todo el volumen de FlexGroup.

* Un volumen FlexGroup debe abarcar agregados con el mismo tipo de disco y la misma configuración de grupo RAID.
+
Para lograr un rendimiento consistente, debe asegurarse de que todos los agregados estén compuestos por SSD, todos los HDD o todos los agregados híbridos. Además, los agregados deben tener la misma cantidad de unidades y de grupos RAID en el volumen FlexGroup.

* Un volumen de FlexGroup puede abarcar partes de un clúster.
+
No es necesario configurar un volumen FlexGroup para abarcar todo el clúster, pero al hacerlo se puede sacar mayor partido a los recursos de hardware disponibles.

* Al crear un volumen de FlexGroup, es mejor que los agregados en los que se ha puesto en marcha el volumen FlexGroup tengan las siguientes características:
+
** Debe haber aproximadamente la misma cantidad de espacio libre en varios agregados, sobre todo cuando se utiliza thin provisioning.
** Se debe reservar aproximadamente el 3 % del espacio libre para los metadatos del agregado después de crear el volumen de FlexGroup.


* Para los sistemas FAS, se recomienda tener dos agregados por nodo y, para los sistemas AFF, debe tener un agregado por nodo para el volumen FlexGroup.
* Para cada volumen de FlexGroup, debe crear al menos ocho componentes que se distribuyan en dos o más agregados en los sistemas de FAS, y en uno o más agregados en los sistemas de AFF.


.Información relacionada
http://["Informe técnico de NetApp 4571: Prácticas recomendadas y guía de implementación de FlexGroup de NetApp"^]
