---
permalink: flexgroup/convert-flexvol-svm-dr-relationship-task.html 
sidebar: sidebar 
keywords: convert, flexvol, flexgroup, svm-dr 
summary: A partir de ONTAP 9.10.1, es posible convertir un volumen FlexVol en un volumen FlexGroup en un origen de SVM-DR. 
---
= Convierta volúmenes de ONTAP FlexVol en volúmenes FlexGroup en una relación SVM-DR
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.10.1, es posible convertir un volumen FlexVol en un volumen FlexGroup en un origen de SVM-DR.

.Antes de empezar
* El volumen FlexVol que se está convirtiendo debe estar en línea.
* Las operaciones y configuraciones del volumen FlexVol deben ser compatibles con el proceso de conversión.
+
Se genera un mensaje de error si el volumen FlexVol tiene alguna incompatibilidad y se cancela la conversión de volumen. Puede tomar acciones correctivas y volver a intentar la conversión. Para obtener información detallada, consulte link:convert-flexvol-concept.html["Consideraciones sobre la conversión de volúmenes de FlexVol en volúmenes de FlexGroup"]



.Pasos
. Inicio de sesión mediante el modo de privilegio avanzado: `set -privilege advanced`
. En el destino, actualice la relación SVM-DR:
+
[source, cli]
----
snapmirror update -destination-path <destination_svm_name>: -source-path <source_svm_name>:
----
+
[NOTE]
====
Debe introducir dos puntos (:) después del nombre de la SVM en la `-destination-path` opción.

====
. Asegúrese de que la relación SVM-DR esté en estado de SnapMirred y no esté desdividida:
+
[source, cli]
----
snapmirror show
----
. En la SVM de destino, compruebe que el volumen de FlexVol esté listo para la conversión:
+
[source, cli]
----
volume conversion start -vserver <svm_name> -volume <vol_name> -check-only true
----
+
Si este comando genera errores distintos a "éste es un volumen SVMDR de destino", puede tomar la acción correctiva adecuada, ejecutar el comando de nuevo y continuar con la conversión.

. En el destino, deshabilite las transferencias en la relación SVM-DR:
+
[source, cli]
----
snapmirror quiesce -destination-path <dest_svm>:
----
+
[NOTE]
====
Debe introducir dos puntos (:) después del nombre de la SVM en la `-destination-path` opción.

====
. En el clúster de origen, inicie la conversión:
+
[source, cli]
----
volume conversion start -vserver <svm_name> -volume <vol_name>
----
. Compruebe que la conversión se ha realizado correctamente:
+
[source, cli]
----
volume show <vol_name> -fields volume-style-extended,state
----
+
[listing]
----
cluster-1::*> volume show my_volume -fields volume-style-extended,state

vserver  volume     state    volume-style-extended
-------  ---------  ------   ---------------------
vs0      my_volume  online   flexgroup
----
. Desde el clúster de destino, reanude las transferencias para la relación:
+
[source, cli]
----
snapmirror resume -destination-path <dest_svm>:
----
+
[NOTE]
====
Debe introducir dos puntos (:) después del nombre de la SVM en la `-destination-path` opción.

====
. Desde el clúster de destino, realice una actualización para propagar la conversión al destino:
+
[source, cli]
----
snapmirror update -destination-path <dest_svm>:
----
+
[NOTE]
====
Debe introducir dos puntos (:) después del nombre de la SVM en la `-destination-path` opción.

====
. Asegúrese de que la relación SVM-DR esté en estado de SnapMirred y no se rompa:
+
[source, cli]
----
snapmirror show
----
. Asegúrese de que la conversión se ha realizado en el destino:
+
[source, cli]
----
volume show <vol_name> -fields volume-style-extended,state
----
+
[listing]
----
cluster-2::*> volume show my_volume -fields volume-style-extended,state

vserver  volume     state   volume-style-extended
-------  -------    ------  ---------------------
vs0_dst  my_volume  online  flexgroup
----


.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resume.html["currículum de Snapmirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["Snapmirror en reposo"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["espectáculo de Snapmirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["actualización de SnapMirror"^]

