---
permalink: flexgroup/create-qtrees-task.html 
sidebar: sidebar 
keywords: create, qtrees, flexgroup, volume, flex group, segment, smb oplock, 
summary: A partir de ONTAP 9.3, se pueden crear qtrees con los volúmenes de FlexGroup. Los qtrees permiten dividir los volúmenes de FlexGroup en segmentos más pequeños que puede gestionar individualmente. 
---
= Crear qtrees con volúmenes de FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.3, se pueden crear qtrees con los volúmenes de FlexGroup. Los qtrees permiten dividir los volúmenes de FlexGroup en segmentos más pequeños que puede gestionar individualmente.

.Acerca de esta tarea
* Si desea revertir a ONTAP 9.2 o una versión anterior y si ha creado uno o más qtrees en el volumen FlexGroup o ha modificado los atributos (estilo de seguridad y bloqueos oportunistas SMB) del qtree predeterminado, Debe eliminar todos los qtrees no predeterminados y, a continuación, deshabilitar la funcionalidad Qtree de cada volumen de FlexGroup antes de revertir a ONTAP 9.2 o anterior.
+
link:../revert/task_disabling_qtrees_in_flexgroup_volumes_before_reverting.html["Deshabilite la funcionalidad Qtree en volúmenes FlexGroup antes de revertir"].

* Si el volumen de FlexGroup de origen tiene qtrees en una relación de SnapMirror, el clúster de destino debe ejecutar ONTAP 9.3 o una versión posterior (una versión del software ONTAP que admite qtrees).
* A partir de la versión 9.5 de ONTAP, se admiten las estadísticas de qtree para volúmenes FlexGroup.


.Pasos
. Cree un qtree en el volumen de FlexGroup: `volume qtree create -vserver vserver_name -volume volume_name -qtree qtree name`
+
Puede especificar de forma opcional el estilo de seguridad, los bloqueos oportunistas SMB, los permisos de UNIX y la política de exportación del qtree.

+
[listing]
----
cluster1::> volume qtree create -vserver vs0 -volume fg1 -qtree qtree1 -security-style mixed
----


.Información relacionada
link:../volumes/index.html["Gestión de almacenamiento lógico"]
