---
permalink: flexgroup/create-task.html 
sidebar: sidebar 
keywords: create, flexgroup, volume, flex group, aggregate, fabricpool, fabric pool 
summary: 'Puede crear un volumen de FlexGroup seleccionando manualmente los niveles locales (agregados) donde se creará el volumen FlexGroup y, a continuación, especificando la cantidad de volúmenes miembro en cada nivel local.' 
---
= Cree Volúmenes ONTAP FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear un volumen de FlexGroup seleccionando manualmente los niveles locales (agregados) donde se debe crear el volumen FlexGroup y, a continuación, especificando la cantidad de volúmenes miembro (componentes) en cada nivel local.

Como alternativa, puede elegir que ONTAP link:provision-automatically-task.html["aprovisionamiento automático"]sea el volumen de FlexGroup seleccionando los niveles locales y permitiendo que ONTAP establezca la cantidad de volúmenes miembro según las prácticas recomendadas para optimizar el rendimiento y la capacidad.

.Acerca de esta tarea
Debe conocer el espacio necesario en los niveles locales para crear un volumen de FlexGroup.

Debe tener en cuenta las siguientes directrices al crear un volumen de FlexGroup para obtener los mejores resultados de rendimiento con un volumen de FlexGroup:

* Un volumen FlexGroup debe utilizar niveles locales en sistemas de hardware idénticos.
+
El uso de sistemas de hardware idénticos ayuda a proporcionar un rendimiento previsible en todo el volumen de FlexGroup.

* Un volumen FlexGroup debe abarcar los niveles locales utilizando el mismo tipo de disco y configuraciones de grupos RAID.
+
Para obtener un rendimiento consistente, debe asegurarse de que todos los niveles locales están hechos de todos los discos SSD, todos los HDD o niveles locales All Flash Pool (híbrido). Además, los niveles locales deben tener el mismo número de unidades y grupos RAID en el volumen FlexGroup.

* Un volumen de FlexGroup puede abarcar partes de un clúster.
+
No es necesario configurar un volumen FlexGroup para abarcar todo el clúster, pero al hacerlo se puede sacar mayor partido a los recursos de hardware disponibles.

* Al crear un volumen de FlexGroup, es mejor que los niveles locales en los que se implementa el volumen de FlexGroup tengan las siguientes características:
+
** Aproximadamente la misma cantidad de espacio libre debería estar disponible en varios niveles locales, especialmente cuando se utiliza thin provisioning.
** Aproximadamente el 3 % del espacio libre se debe reservar para metadatos del nivel local después de la creación del volumen FlexGroup.


* Para los sistemas FAS, es mejor tener dos niveles locales por nodo y para los sistemas AFF, debe tener un nivel local por nodo para el volumen FlexGroup.
* Para cada volumen FlexGroup, debe crear al menos ocho volúmenes miembro distribuidos en dos o más niveles locales en los sistemas FAS y en uno o más niveles locales en los sistemas AFF.


.Antes de empezar
* A partir de ONTAP 9.13.1, se pueden crear volúmenes con análisis de capacidad y seguimiento de actividades habilitados. Para activar la capacidad o el seguimiento de actividad, ejecute el `volume create` comando con `-analytics-state` o `-activity-tracking-state` establezca en `on`.
+
Para obtener más información sobre el análisis de capacidad y el seguimiento de actividades, consulte https://docs.netapp.com/us-en/ontap/task_nas_file_system_analytics_enable.html["Active File System Analytics"]. Obtenga más información sobre `volume create` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["Referencia de comandos de la ONTAP"^].



.Pasos
. Cree el volumen de FlexGroup: `volume create -vserver svm_name -volume flexgroup_name -aggr-list aggr1,aggr2,.. -aggr-list-multiplier constituents_per_aggr -size fg_size [–encrypt true] [-qos-policy-group qos_policy_group_name] [-granular-data advanced]`
+
**  `-aggr-list`El parámetro especifica la lista de niveles locales que se usarán para los volúmenes miembro de FlexGroup.
+
Para obtener un rendimiento consistente en el volumen FlexGroup, todos los niveles locales deben usar el mismo tipo de disco y las mismas configuraciones de grupo RAID.

**  `-aggr-list-multiplier`El parámetro especifica la cantidad de volúmenes miembro que se crearán en cada nivel local que se indica con el `-aggr-list` parámetro.
+
El valor predeterminado de `-aggr-list-multiplier` el parámetro es 4.

** La `size` El parámetro especifica el tamaño del volumen FlexGroup en KB, MB, GB, TB o PB.
** A partir de ONTAP 9.16.1, se puede habilitar link:../enable-adv-capacity-flexgroup-task.html["equilibrado de capacidad avanzado"] (`-granular-data advanced` en la interfaz de línea de comandos para escribir datos en varios volúmenes miembro de FlexGroup cuando los archivos tienen más de 10GB TB.
** A partir de ONTAP 9,5, se pueden crear volúmenes FlexGroup mediante niveles locales con FabricPool habilitado.
+
Para crear un volumen FlexGroup para FabricPool, todos los niveles locales especificados con `-aggr-list` el parámetro deben tener FabricPool habilitado. La garantía de volumen siempre debe establecerse en `none` cuando se utiliza FabricPool. También puede especificar la política de organización en niveles y el período de refrigeración mínimo del volumen de FlexGroup.

+
xref:../disks-aggregates/index.html[Gestión de discos y agregados]

** A partir de ONTAP 9.4, se pueden especificar pisos de rendimiento (calidad de servicio mínima) y calidad de servicio adaptativa para los volúmenes FlexGroup.
+
link:../performance-admin/index.html["Gestión del rendimiento"]

** A partir de ONTAP 9.3, puede especificar un techo de rendimiento (QoS máx.) para los volúmenes FlexGroup, que limita los recursos de rendimiento que puede consumir el volumen FlexGroup.
** A partir de ONTAP 9.2, puede configurar el `-encrypt` parámetro a. `true` Si desea habilitar el cifrado en el volumen de FlexGroup.
+
Para crear un volumen cifrado, debe haber instalado la licencia de cifrado de volúmenes y el gestor de claves.

+
[NOTE]
====
Debe habilitar el cifrado en volúmenes de FlexGroup en el momento de su creación. No puede habilitar el cifrado en volúmenes de FlexGroup existentes.

====
+
link:../encryption-at-rest/index.html["Cifrado de datos en reposo"]



+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg2 -aggr-list aggr1,aggr2,aggr3,aggr1 -aggr-list-multiplier 2 -size 500TB

Warning: A FlexGroup "fg2" will be created with the following number of constituents of size 62.50TB: 8.
Do you want to continue? {y|n}: y

[Job 43] Job succeeded: Successful
----


En el ejemplo anterior, si desea crear el volumen FlexGroup para FabricPool, todos los niveles locales (aggr1, aggr2 y aggr3) deben tener FabricPool habilitado. Monte el volumen FlexGroup con una ruta de unión: `volume mount -vserver vserver_name -volume vol_name -junction-path junction_path`

[listing]
----
cluster1::> volume mount -vserver vs0 -volume fg2 -junction-path /fg
----
.Después de terminar
Debe montar el volumen FlexGroup desde el cliente.

Si ejecuta ONTAP 9.6 o una versión anterior y si la máquina virtual de almacenamiento (SVM) tiene configuradas NFSv3 y NFSv4, es posible que se produzca un error en el montaje del volumen FlexGroup del cliente. En estos casos, debe especificar explícitamente la versión de NFS al montar el volumen de FlexGroup desde el cliente.

[listing]
----
# mount -t nfs -o vers=3 192.53.19.64:/fg /mnt/fg2
# ls /mnt/fg2
file1  file2
----
.Información relacionada
https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["Informe técnico de NetApp 4571: Prácticas recomendadas y guía de implementación de FlexGroup de NetApp"^]
