---
permalink: flexgroup/create-snapmirror-cascade-fanout-reference.html 
sidebar: sidebar 
keywords: consider, create, snapmirror, cascade, fanout, relationship, flexgroup 
summary: Existen consideraciones y limitaciones de compatibilidad que debe tener en cuenta al crear relaciones en cascada y con ventilador de SnapMirror para volúmenes FlexGroup. 
---
= Consideraciones que tener en cuenta para crear relaciones de SnapMirror en cascada y fanout para FlexGroups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existen consideraciones y limitaciones de compatibilidad que debe tener en cuenta al crear relaciones en cascada y con ventilador de SnapMirror para volúmenes FlexGroup.



== Consideraciones que tener en cuenta para crear relaciones en cascada

* Cada relación puede ser una relación entre clústeres o entre clústeres.
* Todos los tipos de normativas asíncronas, incluidos los duplicados asíncronos, los almacenes de reflejos y los almacenes, se admiten en ambas relaciones.
* Solo se admiten las políticas de reflejo asíncrono "MirrorAllSnapshots" y no "MirrorLatest".
* Se admiten actualizaciones simultáneas de relaciones XDP en cascada.
* Admite la extracción de A a B y B a C y la resincronización de A a C o la resincronización de C a A.
* Los volúmenes de FlexGroup a y B también admiten fanout cuando todos los nodos ejecutan ONTAP 9.9.1 o una versión posterior.
* Se admiten las operaciones de restauración de volúmenes FlexGroup B o C.
* Las transferencias en las relaciones de FlexGroup no son compatibles mientras el destino es el origen de una relación de restauración.
* El destino de una restauración de FlexGroup no puede ser el destino de ninguna otra relación de FlexGroup.
* Las operaciones de restauración de archivos de FlexGroup tienen las mismas restricciones que las operaciones normales de restauración de FlexGroup.
* Todos los nodos del clúster donde residen los volúmenes de FlexGroup B y C deben ejecutar ONTAP 9.9.1 o una versión posterior.
* Se admite toda la funcionalidad de expansión automática y expansión.
* En una configuración en cascada como A B a C, si A B y B a C tienen un número distinto de relaciones SnapMirror constituyentes, la operación de anulación del origen no es compatible con la relación de SnapMirror de B a C.
* System Manager no admite relaciones en cascada en ONTAP 9.9.1.
* Al convertir una relación De FlexVol A B a C en una relación de FlexGroup, primero debe convertir la B a C hop.
* Todas las configuraciones en cascada de FlexGroup para relaciones con tipos de política compatibles con REST también son compatibles con las API DE REST en configuraciones de FlexGroup en cascada.
* Al igual que sucede con las relaciones de FlexVol, la configuración en cascada de FlexGroup no es compatible con la `snapmirror protect` comando.




== Consideraciones para crear relaciones de fanout

* Se admiten dos o más relaciones de fanout de FlexGroup; por ejemplo, A a B, A C, con un máximo de 8 patas de fanout.
* Cada relación puede ser entre clústeres o dentro del clúster.
* Se admiten actualizaciones simultáneas para las dos relaciones.
* Se admite toda la funcionalidad de expansión automática y expansión.
* Si las patas de fanout de la relación tienen un número diferente de relaciones SnapMirror constituyentes, la operación de anulación del origen no se admite en las relaciones De La A a la B y De La A a a la C.
* Todos los nodos del clúster donde residen los FlexGroups de origen y destino deben ejecutar ONTAP 9.9.1 o una versión posterior.
* Todos los tipos de políticas asíncronas compatibles actualmente con SnapMirror de FlexGroup se admiten en las relaciones de ventilador.
* Es posible realizar operaciones de restauración de B a C FlexGroups.
* Todas las configuraciones de fanout con tipos de políticas compatibles con REST también son compatibles con las API DE REST en configuraciones de fanout de FlexGroup.

