---
permalink: flexgroup/create-snapvault-relationship-task.html 
sidebar: sidebar 
keywords: create, snapvault, relationship, flexgroup, volumes 
summary: Puede configurar una relación de SnapVault y asignar una política de SnapVault a la relación para crear un backup de SnapVault. 
---
= Crear relaciones de SnapVault para volúmenes de ONTAP FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar una relación de SnapVault y asignar una política de SnapVault a la relación para crear un backup de SnapVault.

.Antes de empezar
Debe tener en cuenta las consideraciones que se deben tener en cuenta para crear una relación de SnapVault para los volúmenes de FlexGroup.

.Pasos
. Cree un volumen FlexGroup de destino del tipo `DP` que tenga la misma cantidad de componentes que el volumen FlexGroup de origen:
+
.. En el clúster de origen, determine la cantidad de componentes en el volumen FlexGroup de origen: `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster1::> volume show  -volume src* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vss       src          -            online     RW         400TB   172.86GB  56%
vss       src__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vss       src__0002    aggr1        online     RW         25TB    10.86TB   56%
vss       src__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vss       src__0004    aggr1        online     RW         25TB    10.73TB   57%
vss       src__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vss       src__0006    aggr1        online     RW         25TB    10.64TB   57%
vss       src__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----
.. Desde el clúster de destino, cree un volumen FlexGroup de destino de tipo `DP` con la misma cantidad de componentes que el volumen FlexGroup de origen.
+
[listing]
----
cluster2::> volume create -vserver vsd -aggr-list aggr1,aggr2 -aggr-list-multiplier 8 -size 400TB -type DP dst

Warning: The FlexGroup volume "dst" will be created with the following number of constituents of size 25TB: 16.
Do you want to continue? {y|n}: y
[Job 766] Job succeeded: Successful
----
.. En el clúster de destino, compruebe la cantidad de componentes en el volumen de FlexGroup de destino: `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster2::> volume show  -volume dst* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vsd       dst          -            online     RW         400TB   172.86GB  56%
vsd       dst__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vsd       dst__0002    aggr1        online     RW         25TB    10.86TB   56%
vsd       dst__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vsd       dst__0004    aggr1        online     RW         25TB    10.73TB   57%
vsd       dst__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vsd       dst__0006    aggr1        online     RW         25TB    10.64TB   57%
vsd       dst__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----


. Crear un programa de trabajo: `job schedule cron create -name job_name -month month -dayofweek day_of_week -day day_of_month -hour hour -minute minute`
+
Para `-month` `-dayofweek` , y `-hour`, puede especificar `all` que se ejecute el trabajo cada mes, día de la semana y hora, respectivamente.

+
El siguiente ejemplo crea una programación de trabajo llamada `my_weekly` que se ejecuta los sábados a las 3:00 a.m.:

+
[listing]
----
cluster1::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----
. Cree una política de SnapVault y, a continuación, defina una regla para la política de SnapVault:
+
.. Cree una política de tipo personalizada `vault` para la relación de SnapVault: `snapmirror policy create -vserver svm_name -policy policy_name -type vault`
.. Defina una regla para la política de SnapVault que determine qué instantáneas se transfieren durante las operaciones de inicialización y actualización: `snapmirror policy add-rule -vserver svm_name -policy policy_for_rule - snapmirror-label snapmirror-label -keep retention_count -schedule schedule`


+
Si no crea una política personalizada, debe especificar `XDPDefault` la política para las relaciones de SnapVault.

. Crear una relación de SnapVault: `snapmirror create -source-path src_svm:src_flexgroup -destination-path dest_svm:dest_flexgroup -type XDP -schedule schedule_name -policy XDPDefault`
+
En ONTAP 9, 4 y anteriores, si la política no se especifica con el `snapmirror create` comando, la `MirrorAllSnapshots` política se utiliza de forma predeterminada. En ONTAP 9.5, si la política no se especifica con `snapmirror create` el comando, `MirrorAndVault` se utiliza de forma predeterminada.

+
[listing]
----
cluster2::> snapmirror create -source-path vss:srcFG -destination-path vsd:dstFG -type XDP -schedule Daily -policy XDPDefault
----
. Desde el clúster de destino, inicialice la relación de SnapVault realizando una transferencia básica: `snapmirror initialize -destination-path dest_svm:dest_flexgroup`
+
[listing]
----
cluster2::> snapmirror initialize -destination-path vsd:dst
Operation is queued: snapmirror initialize of destination "vsd:dst".
----

