---
permalink: flexgroup/disable-svm-protection-task.html 
sidebar: sidebar 
keywords: disable, SVM, protection, flexgroup, volume 
summary: Cuando la Marca SVM DR se establece como protegida en un volumen FlexGroup, puede configurar el indicador como desprotegido para deshabilitar la protección de recuperación ante desastres de SVM en un volumen FlexGroup. 
---
= Deshabilite la protección de SVM en un volumen de ONTAP FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando la Marca SVM DR se establece en `protected` En un volumen FlexGroup, puede configurar el indicador como desprotegido para deshabilitar la recuperación ante desastres de SVM `protection` En un volumen de FlexGroup.

.Antes de empezar
* La relación de recuperación ante desastres de SVM entre el volumen primario y el secundario está en buen estado.
* El parámetro de protección DR de SVM se ha establecido en `protected`.


.Pasos
. Deshabilite la protección mediante `volume modify` comando para cambiar el `vserver-dr-protection` Parámetro del volumen de FlexGroup a. `unprotected`.
+
[listing]
----
cluster2::> volume modify -vserver vs1 -volume fg_src -vserver-dr-protection unprotected
[Job 5384] Job is queued: Modify fg_src.
[Job 5384] Steps completed: 4 of 4.
cluster2::>
----
. Actualice la SVM en el sitio secundario: `snapmirror update -destination-path destination_svm_name: -source-path Source_svm_name:`
. Compruebe que la relación de SnapMirror funciona correctamente: `snapmirror show`
. Compruebe que la relación de SnapMirror de FlexGroup se ha eliminado: `snapmirror show -expand`

