---
permalink: flexgroup/fabricpool-aggregates-existing-volumes-task.html 
sidebar: sidebar 
keywords: aggregate, fabricpool, flexgroup, volume 
summary: A partir de ONTAP 9.5, FabricPool es compatible con FlexGroup Volumes. Si desea usar agregados en FabricPool para los volúmenes de FlexGroup existentes, puede convertir los agregados en los que reside el volumen de FlexGroup en agregados en FabricPool o migrar los componentes de volumen de FlexGroup a agregados en FabricPool. 
---
= Utilice agregados en FabricPool para volúmenes ONTAP FlexGroup existentes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.5, FabricPool es compatible con FlexGroup Volumes. Si desea usar agregados en FabricPool para los volúmenes de FlexGroup existentes, puede convertir los agregados en los que reside el volumen de FlexGroup en agregados en FabricPool o migrar los componentes de volumen de FlexGroup a agregados en FabricPool.

.Antes de empezar
* El volumen FlexGroup debe tener la garantía de espacio establecida en `none`.
* Si desea convertir los agregados en los que reside el volumen de FlexGroup en agregados en FabricPool, los agregados deben usar todos los discos SSD.


.Acerca de esta tarea
Si un volumen de FlexGroup existente reside en agregados que no forman parte de SSD, debe migrar los componentes del volumen FlexGroup a agregados en FabricPool.

.Opciones
* Para convertir los agregados en los que el volumen de FlexGroup reside en agregados en FabricPool, realice los siguientes pasos:
+
.. Establezca la política de organización en niveles en el volumen de FlexGroup existente: `volume modify -volume flexgroup_name -tiering-policy [auto|snapshot|none|backup]`
+
[listing]
----
cluster-2::> volume modify -volume fg1 -tiering-policy auto
----
.. Identifique los agregados en los que reside el volumen de FlexGroup: `volume show -volume flexgroup_name -fields aggr-list`
+
[listing]
----
cluster-2::> volume show -volume fg1 -fields aggr-list
vserver volume aggr-list
------- ------ -----------
vs1     fg1    aggr1,aggr3
----
.. Adjunte un almacén de objetos a cada agregado que aparece en la lista de agregados: `storage aggregate object-store attach -aggregate aggregate name -name object-store-name -allow-flexgroup true`
+
Debe asociar todos los agregados a un almacén de objetos.



+
[listing]
----
cluster-2::> storage aggregate object-store attach -aggregate aggr1 -object-store-name Amazon01B1
----
* Para migrar los componentes de volumen de FlexGroup a agregados en FabricPool, realice los pasos siguientes:
+
.. Establezca la política de organización en niveles en el volumen de FlexGroup existente: `volume modify -volume flexgroup_name -tiering-policy [auto|snapshot|none|backup]`
+
[listing]
----
cluster-2::> volume modify -volume fg1 -tiering-policy auto
----
.. Mueva cada componente del volumen FlexGroup a un agregado de FabricPool en el mismo clúster: `volume move start -volume constituent-volume -destination-aggregate FabricPool_aggregate -allow-mixed-aggr-types true`
+
Debe mover todos los componentes de volúmenes de FlexGroup a agregados en FabricPool (en caso de que los componentes de volumen FlexGroup estén en tipos de agregado mixtos) y garantizar que todos los componentes se equilibren entre los nodos del clúster.

+
[listing]
----
cluster-2::> volume move start -volume fg1_001 -destination-aggregate FP_aggr1 -allow-mixed-aggr-types true
----




.Información relacionada
link:../disks-aggregates/index.html["Gestión de discos y agregados"]
