---
permalink: flexgroup/index.html 
sidebar: sidebar 
keywords: decide, scalability, performance, flexgroup, volumes, scalability, performance 
summary: Puede configurar, gestionar y proteger volúmenes de FlexGroup para garantizar la escalabilidad y el rendimiento. Un volumen FlexGroup es un volumen de escalado horizontal que ofrece alto rendimiento junto con la distribución automática de la carga. 
---
= Información general de gestión de volúmenes de FlexGroup con la interfaz de línea de comandos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar, gestionar y proteger volúmenes de FlexGroup para garantizar la escalabilidad y el rendimiento. Un volumen FlexGroup es un volumen de escalado horizontal que ofrece alto rendimiento junto con la distribución automática de la carga.

Puede configurar los volúmenes FlexGroup si se cumplen las siguientes condiciones:

* Quiere utilizar las prácticas recomendadas, no explorar todas las opciones disponibles.
* Tiene privilegios de administrador de clúster, no de administrador de SVM.



NOTE: A partir de ONTAP 9,5, las instancias de FlexGroup reemplazan a los Infinite Volume, que no son compatibles con ONTAP 9,5 o versiones posteriores.

Consulte link:supported-unsupported-config-concept.html["Configuraciones compatibles y no compatibles para volúmenes FlexGroup"] si quiere más información.

.Información relacionada
La información conceptual sobre los volúmenes de FlexVol se aplica a los volúmenes de FlexGroup. La información sobre FlexVol Volumes y la tecnología ONTAP está disponible en la biblioteca de referencia de ONTAP y en los informes técnicos (TRS).
