---
permalink: flexgroup/provision-automatically-task.html 
sidebar: sidebar 
keywords: provision, flexgroup, volume, automatic, create, flex group, aggregate, space 
summary: 'Al crear un volumen de FlexGroup, puede elegir que ONTAP aprovisione el volumen de FlexGroup seleccionando automáticamente los niveles locales (agregados). Los niveles locales se seleccionan en función de las prácticas recomendadas para lograr un rendimiento óptimo.' 
---
= Aprovisione automáticamente un volumen ONTAP FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando crea un volumen de FlexGroup, puede elegir que ONTAP aprovisione automáticamente el volumen de FlexGroup seleccionando los niveles locales subyacentes (agregados). Los niveles locales se seleccionan según las mejores prácticas para obtener un rendimiento y una capacidad óptimos.

.Antes de empezar
Cada nodo del clúster debe tener al menos un nivel local.

[NOTE]
====
Cuando se crea un volumen FlexGroup que organizará datos inactivos en niveles, cada nodo debe tener al menos un nivel local con la función FabricPool habilitada.

====
.Acerca de esta tarea
ONTAP selecciona dos niveles locales con la mayor cantidad de espacio utilizable en cada nodo para crear el volumen de FlexGroup. Si no hay dos niveles locales disponibles, ONTAP selecciona un nivel local por nodo para crear el volumen FlexGroup.

A partir de ONTAP 9.15.1, cuando se aprovisiona automáticamente un volumen de FlexGroup, ONTAP utiliza la colocación equilibrada para elegir los niveles locales y el diseño de volúmenes miembro (constituyentes) de FlexGroup. Uno de los aspectos de la infraestructura empresarial es que limita el sobreaprovisionamiento de niveles locales al crear volúmenes FlexGroup «ninguno» garantizados (con thin provisioning). El tamaño del volumen FlexGroup general está limitado por la cantidad de espacio libre en el nivel local, aunque el límite es superior al para los volúmenes FlexGroup garantizados (con aprovisionamiento grueso) del volumen. Cuando se crea un volumen de FlexGroup con API de REST o `auto-provision-as` con la interfaz de línea de comandos de ONTAP, se puede producir un error de aprovisionamiento debido a que el espacio es insuficiente debido a este límite. Para evitar esto, puede crear volúmenes de FlexGroup más pequeños o mediante link:create-task.html["Creación de un volumen FlexGroup y selección manual de los niveles locales"] el `aggr-list` parámetro.

.Pasos
. Aprovisione el volumen FlexGroup:
+
`volume create -vserver svm_name -volume fg_vol_name –auto-provision-as flexgroup -size fg_size [–encrypt true] [-qos-policy-group qos_policy_group_name] [-support-tiering true] [-granular-data advanced]`

+
A partir de ONTAP 9.16.1, se puede habilitar link:enable-adv-capacity-flexgroup-task.html["equilibrado de capacidad avanzado"] (`-granular-data advanced` en la interfaz de línea de comandos para escribir datos en varios volúmenes miembro de FlexGroup cuando los archivos tienen más de 10GB TB.

+
A partir de ONTAP 9,5, se pueden crear volúmenes de FlexGroup en niveles locales con FabricPool habilitado. Para aprovisionar automáticamente un volumen FlexGroup en niveles locales con FabricPool habilitado, se debe establecer `-support-tiering` el parámetro en `true`. La garantía de volumen siempre debe establecerse en `none` para FabricPool. También puede especificar la política de organización en niveles y el período de refrigeración mínimo del volumen de FlexGroup.

+
link:../disks-aggregates/index.html["Gestión de discos y agregados"]

+
Puede especificar un techo de rendimiento (QoS máx.) para los volúmenes de FlexGroup. Esto limita los recursos de rendimiento que el volumen FlexGroup puede consumir. A partir de ONTAP 9.4, se pueden especificar pisos de rendimiento (calidad de servicio mínima) y calidad de servicio adaptativa para los volúmenes FlexGroup.

+
link:../performance-admin/index.html["Gestión del rendimiento"]

+
Puede establecer `-encrypt` el parámetro en `true` si desea habilitar el cifrado en el volumen FlexGroup. Para crear un volumen cifrado, debe haber instalado la licencia de cifrado de volúmenes y el gestor de claves.

+

NOTE: Debe habilitar el cifrado en volúmenes de FlexGroup en el momento de su creación. No puede habilitar el cifrado en volúmenes de FlexGroup existentes.

+
link:../encryption-at-rest/index.html["Cifrado de datos en reposo"]

+
La `size` El parámetro especifica el tamaño del volumen FlexGroup en KB, MB, GB, TB o PB.

+
En el ejemplo siguiente se muestra cómo aprovisionar un volumen FlexGroup de 400 TB:

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
El siguiente ejemplo muestra cómo crear un grupo de políticas de calidad de servicio para techo de rendimiento y cómo se aplica a un volumen de FlexGroup:

+
[listing]
----
cluster1::> qos policy-group create -policy group pg-vs1 -vserver vs1 -max-throughput 5000iops
----
+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -qos-policy-group pg-vs1
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
En el ejemplo siguiente se muestra cómo aprovisionar un volumen FlexGroup de tamaño 400 TB en niveles locales con FabricPool habilitado:

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -support-tiering true -tiering-policy auto
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
El volumen FlexGroup se crea con ocho volúmenes miembro en cada nodo del clúster. Los volúmenes miembro se distribuyen de igual forma entre los dos niveles locales más grandes en cada nodo.

+
De manera predeterminada, se crea el volumen FlexGroup con la `volume` Configuración de garantía de espacio excepto en sistemas AFF. Para los sistemas AFF, el volumen FlexGroup se crea de forma predeterminada con la `none` garantía de espacio.

. Monte el volumen FlexGroup en una ruta de unión:
+
`volume mount -vserver vserver_name -volume vol_name -junction-path junction_path`

+
[listing]
----
cluster1::> volume mount -vserver vs0 -volume fg2 -junction-path /fg2
----


.Después de terminar
Debe montar el volumen FlexGroup desde el cliente.

Si ejecuta ONTAP 9.6 o una versión anterior y si la máquina virtual de almacenamiento (SVM) tiene configuradas NFSv3 y NFSv4, es posible que se produzca un error en el montaje del volumen FlexGroup del cliente. En estos casos, debe especificar explícitamente la versión de NFS al montar el volumen de FlexGroup desde el cliente.

[listing]
----
# mount -t nfs -o vers=3 192.53.19.64:/fg2 /mnt/fg2
# ls /mnt/fg2
file1  file2
----