---
permalink: flexgroup/provision-automatically-task.html 
sidebar: sidebar 
keywords: provision, flexgroup, volume, automatic, create, flex group, aggregate, space 
summary: Puede aprovisionar automáticamente un volumen de FlexGroup. ONTAP crea y configura un volumen de FlexGroup seleccionando automáticamente los agregados. Los agregados se seleccionan según las prácticas recomendadas para un rendimiento óptimo. 
---
= Aprovisionar automáticamente un volumen FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede aprovisionar automáticamente un volumen de FlexGroup. ONTAP crea y configura un volumen de FlexGroup seleccionando automáticamente los agregados. Los agregados se seleccionan según las prácticas recomendadas para un rendimiento óptimo.

.Antes de empezar
Cada nodo del clúster debe tener al menos un agregado.

[NOTE]
====
Para crear un volumen de FlexGroup para FabricPool en ONTAP 9.5, cada nodo debe tener al menos un agregado que sea FabricPool.

====
.Acerca de esta tarea
ONTAP selecciona dos agregados con la mayor cantidad de espacio útil de cada nodo para crear el volumen FlexGroup. Si no hay dos agregados disponibles, ONTAP selecciona un agregado por nodo para crear el volumen FlexGroup.

A partir de ONTAP 9.15.1, cuando se aprovisiona automáticamente un volumen de FlexGroup, ONTAP usa aprovisionamiento de colocación equilibrada para garantizar que haya espacio suficiente para la garantía de espacio. Cuando se crea un volumen de FlexGroup con las API de REST o `auto-provision-as` Con la CLI de ONTAP, se puede producir un error en el aprovisionamiento debido a la aplicación de la garantía de espacio. Puede evitarlo creando volúmenes de FlexGroup más pequeños, o mediante link:create-task.html["Creación de un volumen FlexGroup y selección manual de los agregados"] con el `aggr-list` parámetro.

.Pasos
. Aprovisione el volumen FlexGroup:
+
|===


| Si está usando... | Se usa este comando... 


 a| 
ONTAP 9,2 o posterior
 a| 
`volume create -vserver svm_name -volume fg_vol_name –auto-provision-as flexgroup -size fg_size [–encrypt true] [-qos-policy-group qos_policy_group_name] [-support-tiering true]`

A partir de ONTAP 9.5, se pueden crear volúmenes de FlexGroup para FabricPool. Para aprovisionar automáticamente un volumen de FlexGroup en FabricPool, debe configurar el `-support-tiering` parámetro a. `true`. La garantía de volumen siempre debe configurarse en `none` Para FabricPool. También puede especificar la política de organización en niveles y el período de refrigeración mínimo del volumen de FlexGroup.

link:../disks-aggregates/index.html["Gestión de discos y agregados"]

A partir de ONTAP 9.3, puede especificar un techo de rendimiento (QoS máx.) para los volúmenes FlexGroup, que limita los recursos de rendimiento que puede consumir el volumen FlexGroup. A partir de ONTAP 9.4, se pueden especificar pisos de rendimiento (calidad de servicio mínima) y calidad de servicio adaptativa para los volúmenes FlexGroup.

link:../performance-admin/index.html["Gestión del rendimiento"]

A partir de ONTAP 9.2, puede configurar el `-encrypt` parámetro a. `true` Si desea habilitar el cifrado en el volumen de FlexGroup. Para crear un volumen cifrado, debe haber instalado la licencia de cifrado de volúmenes y el gestor de claves.


NOTE: Debe habilitar el cifrado en volúmenes de FlexGroup en el momento de su creación. No puede habilitar el cifrado en volúmenes de FlexGroup existentes.

link:../encryption-at-rest/index.html["Cifrado de datos en reposo"]



 a| 
ONTAP 9,1
 a| 
`volume flexgroup deploy -vserver svm_name -size fg_size`

|===
+
La `size` El parámetro especifica el tamaño del volumen FlexGroup en KB, MB, GB, TB o PB.

+
El ejemplo siguiente muestra cómo aprovisionar un volumen FlexGroup de tamaño 400 TB en ONTAP 9.2:

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
El siguiente ejemplo muestra cómo crear un grupo de políticas de calidad de servicio para techo de rendimiento y cómo se aplica a un volumen de FlexGroup:

+
[listing]
----
cluster1::> qos policy-group create -policy group pg-vs1 -vserver vs1 -max-throughput 5000iops
----
+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -qos-policy-group pg-vs1
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
El ejemplo siguiente muestra cómo aprovisionar un volumen FlexGroup de tamaño 400 TB en agregados en FabricPool en ONTAP 9.5:

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -support-tiering true -tiering-policy auto
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
El volumen FlexGroup se crea con ocho componentes en cada nodo del clúster. Los componentes se distribuyen por igual entre los dos agregados de mayor tamaño de cada nodo.

+
De manera predeterminada, se crea el volumen FlexGroup con la `volume` Configuración de garantía de espacio excepto en sistemas AFF. Para los sistemas AFF, el volumen FlexGroup se crea de forma predeterminada con la `none` garantía de espacio.

. Monte el volumen FlexGroup en una ruta de unión: `volume mount -vserver vserver_name -volume vol_name -junction-path junction_path`
+
[listing]
----
cluster1::> volume mount -vserver vs0 -volume fg2 -junction-path /fg2
----


.Después de terminar
Debe montar el volumen FlexGroup desde el cliente.

Si ejecuta ONTAP 9.6 o una versión anterior y si la máquina virtual de almacenamiento (SVM) tiene configuradas NFSv3 y NFSv4, es posible que se produzca un error en el montaje del volumen FlexGroup del cliente. En estos casos, debe especificar explícitamente la versión de NFS al montar el volumen de FlexGroup desde el cliente.

[listing]
----
# mount -t nfs -o vers=3 192.53.19.64:/fg2 /mnt/fg2
# ls /mnt/fg2
file1  file2
----