---
permalink: flexgroup/shrink-flexgroup-volume-task.html 
sidebar: sidebar 
keywords: reduce, size, flexgroup, volume, flex group, resize, shrink, shrinking, autosize 
summary: A partir de ONTAP 9.6, puede cambiar el tamaño de un volumen FlexGroup a un valor inferior al tamaño actual para liberar el espacio no utilizado del volumen. Cuando se reduce el tamaño de un volumen de FlexGroup, ONTAP cambia automáticamente el tamaño de todos los componentes de FlexGroup. 
---
= Reduzca el tamaño de un volumen de FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.6, puede cambiar el tamaño de un volumen FlexGroup a un valor inferior al tamaño actual para liberar el espacio no utilizado del volumen. Cuando se reduce el tamaño de un volumen de FlexGroup, ONTAP cambia automáticamente el tamaño de todos los componentes de FlexGroup.

.Paso
. Reduzca el tamaño del volumen de FlexGroup: `volume size -vserver vserver_name -volume fg_name -size new_size`
+
`new_size` Es el tamaño del volumen de FlexGroup. Es posible especificar un valor inferior al tamaño actual o un valor negativo mediante el cual se reduce el tamaño actual del volumen de FlexGroup.

+
[NOTE]
====
Si se habilita la reducción automática para el volumen (`volume autosize` comando), el valor mínimo de autosize se establece en el nuevo tamaño del volumen.

====
+
[listing]
----
cluster1::> volume size -vserver svm1 -volume volX -size 10TB
----
+
[listing]
----
cluster1::> volume size -vserver svm1 -volume volX -size -5TB
----

