---
permalink: flexgroup/shrink-flexgroup-volume-task.html 
sidebar: sidebar 
keywords: reduce, size, flexgroup, volume, flex group, resize, shrink, shrinking, autosize 
summary: A partir de ONTAP 9.6, puede cambiar el tamaño de un volumen FlexGroup a un valor inferior al tamaño actual para liberar el espacio no utilizado del volumen. Cuando se reduce el tamaño de un volumen de FlexGroup, ONTAP cambia automáticamente el tamaño de todos los componentes de FlexGroup. 
---
= Reduzca el tamaño de un volumen ONTAP FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.6, puede cambiar el tamaño de un volumen FlexGroup a un valor inferior al tamaño actual para liberar el espacio no utilizado del volumen. Cuando se reduce el tamaño de un volumen de FlexGroup, ONTAP cambia automáticamente el tamaño de todos los componentes de FlexGroup.

.Paso
. Compruebe el tamaño actual del volumen de FlexGroup: "Volume size -vserver _vserver_NAME_ -volume _fg_NAME_"
. Reduzca el tamaño del volumen de FlexGroup: `volume size -vserver _vserver_name_ -volume _fg_name_ _new_size_`
+
Al especificar el nuevo tamaño, se puede especificar un valor inferior al tamaño actual o un valor negativo mediante el signo menos (-) por el que se reduce el tamaño actual del volumen FlexGroup.

+
[NOTE]
====
Si se habilita la reducción automática para el volumen (`volume autosize` comando), el valor mínimo de autosize se establece en el nuevo tamaño del volumen.

====
+
En el siguiente ejemplo, se muestra el tamaño de volumen actual del volumen de FlexGroup denominado Volx y se cambia el tamaño del volumen a 10 TB:

+
[listing]
----
cluster1::> volume size -vserver svm1 -volume volX
(volume size)
vol size: FlexGroup volume 'svm1:volX' has size 15TB.

cluster1::> volume size -vserver svm1 -volume volX 10TB
(volume size)
vol size: FlexGroup volume 'svm1:volX' size set to 10TB.
----
+
En el siguiente ejemplo, se muestra el tamaño actual del volumen del volumen FlexGroup denominado Volx y se reduce el tamaño del volumen en 5 TB:

+
[listing]
----
cluster1::> volume size -vserver svm1 -volume volX
(volume size)
vol size: FlexGroup volume 'svm1:volX' has size 15TB.

cluster1::> volume size -vserver svm1 -volume volX -5TB
(volume size)
vol size: FlexGroup volume 'svm1:volX' size set to 10TB.
----

