---
permalink: flexgroup/snapvault-backup-concept.html 
sidebar: sidebar 
keywords: consider, create, snapvault, backup, relation, unified, data, protection, flexgroup, volume 
summary: Debe tener en cuenta las consideraciones que se deben tener en cuenta para crear una relación de backup de SnapVault y una relación de protección de datos unificada para los volúmenes FlexGroup. 
---
= Consideraciones para crear una relación de backup de SnapVault y una relación de protección de datos unificada para volúmenes de ONTAP FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe tener en cuenta las consideraciones que se deben tener en cuenta para crear una relación de backup de SnapVault y una relación de protección de datos unificada para los volúmenes FlexGroup.

* Puede volver a sincronizar una relación de backup de SnapVault y una relación de protección de datos unificada mediante `-preserve` la opción que permite conservar copias de Snapshot en el volumen de destino más recientes que la snapshot común más reciente.
* La retención a largo plazo no es compatible con los volúmenes de FlexGroup.
+
La retención a largo plazo permite crear Snapshot directamente en el volumen de destino sin necesidad de almacenar las snapshots en el volumen de origen.

* La `snapshot` comando `expiry-time` FlexGroup Volumes no admite la opción.
* No se puede configurar la eficiencia de almacenamiento en el volumen FlexGroup de destino de una relación de backup de SnapVault y una relación de protección de datos unificada.
* No es posible cambiar el nombre de snapshots de una relación de backup de SnapVault y de protección de datos unificada para volúmenes de FlexGroup.
* Un volumen FlexGroup puede ser el volumen de origen de una sola relación de backup o restauración.
+
Un volumen de FlexGroup no puede ser el origen de dos relaciones de SnapVault, dos relaciones de restauración o una relación de backup de SnapVault y una relación de restauración.

* Si elimina una copia de Snapshot en el volumen de FlexGroup de origen y se vuelve a crear una copia de Snapshot con el mismo nombre, la próxima transferencia de la actualización al volumen de FlexGroup de destino generará un error si el volumen de destino tiene una copia de Snapshot con el mismo nombre.
+
Esto se debe a que no se puede cambiar el nombre de las copias de Snapshot para volúmenes de FlexGroup.


