---
permalink: flexcache-writeback/flexcache-write-back-prerequisites.html 
sidebar: sidebar 
keywords: tr-4743, flexcache writeback, flexcache write-back, prerequisites, technical report, netapp tr, ontap tr 
summary: Antes de implementar FlexCache en modo de escritura, asegúrese de que ha cumplido estos requisitos de software, licencias y configuración del sistema. 
---
= Requisitos previos de reescritura de ONTAP FlexCache
:allow-uri-read: 


[role="lead"]
Antes de implementar FlexCache en modo de escritura, asegúrese de cumplir estos requisitos de rendimiento, software, licencia y configuración del sistema.



== CPU y memoria

Cada nodo del clúster de origen debe tener al menos 128GB GB de RAM y 20 CPU para absorber los mensajes de reescritura iniciados por las cachés habilitadas de reescritura. Esto es el equivalente a un A400 o superior. Si el clúster de origen sirve como origen para varios FlexCaches con escritura, necesitará más CPU y RAM.


CAUTION: El uso de un origen infradimensionado para una carga de trabajo puede tener impactos profundos sobre el rendimiento de la caché de retroescritura habilitada o el origen.



== Versión de ONTAP

* El origen *_debe_* ejecutar ONTAP 9.15.1 o posterior.
* Cualquier clúster de caché que necesite funcionar en modo de escritura *_MUST_* ejecute ONTAP 9.15.1 o posterior.
* Cualquier clúster de almacenamiento en caché que no necesite funcionar en modo de escritura puede ejecutar cualquier versión de ONTAP compatible de forma general.




== Licencia

FlexCache, incluido el modo de operación de escritura, se incluye con la compra de ONTAP. No se necesita ninguna licencia adicional.



== Interconexión

* Los clústeres de origen y de caché deben estar link:../flexcache-writeback/flexcache-writeback-enable-task.html["con relación de paridad del clúster"]
* Las máquinas virtuales de servidor (SVM) en el clúster de origen y de caché deben tener link:../flexcache-writeback/flexcache-writeback-enable-task.html["vserver con relaciones entre iguales"] la opción FlexCache.



NOTE: No es necesario conectar un cluster de caché a otro cluster de caché. Tampoco es necesario conectar una SVM de caché a otra SVM de caché.
