---
sidebar: sidebar 
permalink: smbc/smbc_admin_performing_a_planned_failover.html 
keywords: SM-BC, SMBC, testing failover, planned failover, maintenance, Mediator, quorum 
summary: Es posible realizar una conmutación al respaldo planificada para probar la configuración de recuperación ante desastres o para realizar tareas de mantenimiento en el clúster principal. 
---
= Realizar una conmutación al respaldo planificada
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En una conmutación al respaldo planificada, debe cambiar los roles de los clústeres primario y secundario, de modo que el clúster secundario asuma el control del clúster principal. Durante una conmutación por error, lo que normalmente funciona el clúster secundario procesa las solicitudes de entrada y salida localmente sin interrumpir las operaciones del cliente.

Quizás desee realizar una conmutación al respaldo planificada para probar el estado de la configuración de recuperación de desastres o realizar tareas de mantenimiento del clúster principal.

.Acerca de esta tarea
El administrador del clúster secundario inicia una conmutación al respaldo planificada. La operación requiere cambiar los roles primario y secundario de manera que el clúster secundario asuma el control del primario. Después, el nuevo clúster principal puede comenzar a procesar solicitudes de entrada y salida de forma local sin interrumpir las operaciones del cliente.

.Antes de empezar
* La relación SM-BC debe estar sincronizada.
* No puede iniciar una conmutación al respaldo planificada cuando hay una operación no disruptiva en proceso. Las operaciones no disruptivas incluyen movimientos de volúmenes, reubicaciones de agregaciones y recuperación tras fallos de almacenamiento.
* El mediador ONTAP debe estar configurado, conectado y en quórum.


.Pasos
Puede realizar una conmutación al respaldo planificada con la interfaz de línea de comandos de ONTAP o System Manager.

[role="tabbed-block"]
====
.CLI de ONTAP
--
. Desde el clúster de destino, inicie la operación de conmutación por error:
+
`destination::>snapmirror failover start -destination-path   vs1_dst:/cg/cg_dst`

. Supervise el progreso de la conmutación por error:
+
`destination::>snapmirror failover show`

. Una vez finalizada la operación de conmutación por error, puede supervisar el estado de la relación de protección de SnapMirror síncrono desde el destino:
+
`destination::>snapmirror show`



--
.System Manager
--
. En System Manager, seleccione **Protección > Descripción general > Relaciones**.
. Identifique la relación de SM-BC que desea conmutar al nodo de respaldo. Junto a su nombre, seleccione la `...` Junto al nombre de la relación, luego seleccione **Failover**.
. Para supervisar el estado de la conmutación por error, utilice `snapmirror failover show` En la CLI de ONTAP.


--
====