---
sidebar: sidebar 
permalink: smbc/smbc_plan_preparing_to_use_the_ontap_mediator.html 
keywords: SM-BC, Mediator, network configuration, prerequisites 
summary: El Mediador ONTAP establece un quórum para los clústeres de ONTAP en una relación de SM-BC y coordina la recuperación automatizada tras fallos durante un fallo. 
---
= Prepárese para usar el Mediador ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El Mediador ONTAP establece un quórum para los clústeres de ONTAP en una relación de SM-BC. Coordina la conmutación automática al nodo de respaldo cuando se detecta un fallo y ayuda a evitar situaciones de cerebro dividido cuando cada clúster intenta establecer el control simultáneamente como el clúster principal.



== Requisitos previos para el Mediador ONTAP

El Mediador ONTAP incluye su propio conjunto de requisitos previos. Debe cumplir con estos requisitos previos antes de instalar el mediador. Para obtener más información, consulte link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["Prepare la instalación del servicio Mediador ONTAP"^].



== Configuración de red

De forma predeterminada, el Mediador ONTAP proporciona servicio a través del puerto TCP 31784. Debe asegurarse de que el puerto 31784 esté abierto y disponible entre los clústeres de ONTAP y el mediador.
