---
sidebar: sidebar 
permalink: smbc/smbc_plan_preparing_to_use_the_ontap_cli.html 
keywords: SM-BC, SMBC, preparing, ONTAP, CLI, commands 
summary: Debería estar familiarizado con los siguientes comandos al implementar la solución de continuidad empresarial de SnapMirror mediante la interfaz de línea de comandos de ONTAP. 
---
= Prepare el uso de la CLI de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Debería estar familiarizado con los siguientes comandos al implementar la solución de continuidad empresarial de SnapMirror mediante la interfaz de línea de comandos de ONTAP.


NOTE: SM-BC no admite `snapmirror quiesce` y.. `snapmirror resume` comandos para relaciones con una política de sincronización activa.

Para obtener más información sobre los siguientes comandos de la ONTAP, consulte https://docs.netapp.com/ontap-9/index.jsp["Documentación de NetApp: ONTAP 9"^].

|===
| Comando | Descripción 


| crear lun igroup | Cree un igroup en un clúster 


| mapa de lun | Asigne una LUN a un igroup 


| muestra de lun | Mostrar una lista de LUN 


| snapmirror create | Crear una nueva relación de SnapMirror 


| inicializar snapmirror | Inicialice un grupo de consistencia de SM-BC 


| actualización de snapmirror | Inicia una operación de creación de Snapshot común 


| de snapmirror | Mostrar una lista de relaciones de SnapMirror 


| recuperación tras fallos de snapmirror | Inicie una operación de conmutación al respaldo planificada 


| resincronización de snapmirror | Inicie una operación de resincronización 


| snapmirror elimina | Eliminar una relación de SnapMirror 


| versión de snapmirror | Quitar la información de origen de una relación de SnapMirror 


| archivo de restauración de snapshots de volumen | Disponible con SM-BC a partir de ONTAP 9.11.1, xref:../data-protection/restore-single-file-snapshot-task.html[Restaurar un solo archivo o LUN] 
|===