---
sidebar: sidebar 
permalink: smbc/smbc_install_confirm_ontap_cluster.html 
keywords: SM-BC, SMBC, ONTAP, cluster, configure, peering, volume, SVM, SAN, LIFs, map, igroup, discover 
summary: Debe asegurarse de que los clústeres de origen y destino estén configurados correctamente. 
---
= Instale el Servicio Mediador ONTAP y confirme la configuración del clúster ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Debe asegurarse de que los clústeres de origen y destino estén configurados correctamente.

.Acerca de esta tarea
Continúe con cada uno de los pasos siguientes. Para cada paso, debe confirmar que se ha realizado la configuración específica. Utilice el enlace que se incluye después de cada paso para obtener más información según sea necesario.

.Pasos
. Instale el servicio Mediator de ONTAP antes de asegurarse de que los clústeres de origen y destino están configurados correctamente.
+
xref:../mediator/index.html[Servicio Mediador ONTAP]

. Confirme que existe una relación de paridad entre los clústeres.
+

NOTE: El espacio IP predeterminado es necesario por SM-BC para las relaciones de paridad de clústeres. No se admite el espacio IP personalizado.

+
xref:../task_dp_prepare_mirror.html[Configure las relaciones de paridad]

. Confirmar que las máquinas virtuales de almacenamiento se crean en cada clúster.
+
xref:../smb-config/create-svms-data-access-task.html[Creación de una SVM]

. Confirmar que existe una relación entre iguales entre las máquinas virtuales de almacenamiento en cada clúster.
+
xref:../peering/create-intercluster-svm-peer-relationship-93-later-task.html[Creación de una relación de paridad de SVM]

. Confirme que los volúmenes existen para sus LUN.
+
xref:../smb-config/create-volume-task.html[Creación de un volumen]

. Confirmar que se crea al menos un LIF SAN en cada nodo del clúster.
+
link:../san-admin/lifs-cluster-concept.html["Consideraciones para los LIF en un entorno SAN de clúster"]

+
link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/GUID-4B666C44-694A-48A3-B0A9-517FA7FD2502.html?cp=13_6_4_0["Crear una LIF"^]

. Confirmar que las LUN necesarias se han creado y asignado a igroup, que se utiliza para asignar LUN al iniciador en el host de la aplicación.
+
xref:../san-admin/create-luns-mapping-igroups-task.html[Cree LUN y asigne iGroups]

. Vuelva a analizar el host de la aplicación para detectar todos los LUN nuevos.

