---
sidebar: sidebar 
permalink: smbc/smbc_install_creating_a_consistency_group_relationship.html 
keywords: SM-BC, SMBC, consistency group, create, constituent 
summary: Debe crear un grupo de coherencia de SnapMirror que también establezca la relación del grupo de coherencia síncrono. 
---
= Cree una relación de grupo de coherencia
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Debe crear un grupo de coherencia de SM-BC que también establezca la relación del grupo de coherencia síncrono.


NOTE: Este flujo de trabajo se aplica a los usuarios de ONTAP 9.8 y 9.9.1. Si se usan estos comandos de la CLI de ONTAP a partir de ONTAP 9.10.1, aún funcionan para crear un grupo de consistencia, sin embargo, se recomienda que gestione los grupos de consistencia con System Manager o la API REST de ONTAP.

.Antes de empezar
Se aplican los siguientes requisitos previos y restricciones:

* Debe ser un administrador de clústeres o máquinas virtuales de almacenamiento
* Debe tener una licencia de SnapMirror Synchronous
* Los volúmenes de destino deben ser del tipo DP
* La máquina virtual de almacenamiento primaria y secundaria debe tener una relación entre iguales
* Todos los volúmenes constituyentes de un grupo de consistencia deben estar en una única máquina virtual de almacenamiento
* No se pueden establecer relaciones de grupos de consistencia de SM-BC entre clústeres de ASA y clústeres que no son ASA
* El nombre del grupo de consistencia debe ser único


.Acerca de esta tarea
Debe crear la relación del grupo de coherencia a partir del clúster de destino.  Puede asignar hasta 12 componentes mediante el `cg-item-mappings` parámetro en la `snapmirror create` comando.

.Pasos
. Cree un grupo de consistencia y una relación constituyente. En este ejemplo, se crean dos grupos de consistencia: cg_src con los volúmenes constituyentes vol1 y vol2, y cg_dist con los volúmenes constituyentes vol1_dr y vol2_dr.
+
`destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOver`


