---
permalink: s3-audit/modify-config-task.html 
sidebar: sidebar 
keywords: s3 audit, modify 
summary: Puede modificar los parámetros de auditoría de bloques individuales o la configuración de auditoría de todos los bloques seleccionados para la auditoría en la SVM. 
---
= Modificar una configuración de auditoría de ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede modificar los parámetros de auditoría de bloques individuales o la configuración de auditoría de todos los bloques seleccionados para la auditoría en la SVM.

[cols="2,4"]
|===
| Si desea modificar la configuración de auditoría para... | Introduzca... 


| Cucharones individuales | `vserver object-store-server audit event-selector modify -vserver _svm_name_ [-bucket _bucket_name_] [_parameters to modify_]` 


| Todos los bloques del SVM  a| 
`vserver object-store-server audit modify -vserver _svm_name_ [_parameters to modify_]`

|===
.Ejemplos
En el siguiente ejemplo se modifica una configuración de auditoría de bloque individual para auditar únicamente los eventos de acceso de sólo escritura:

[listing]
----
cluster1::> vserver object-store-server audit event-selector modify -vserver vs1 -bucket test-bucket -access write-only
----
En el siguiente ejemplo se modifica la configuración de auditoría de todos los bloques de la SVM para cambiar el límite de tamaño del registro a 10MB y para retener 3 archivos de registro antes de rotar.

[listing]
----
cluster1::> vserver object-store-server audit modify -vserver vs1 -rotate-size 10MB -rotate-limit 3
----