---
permalink: s3-audit/select-buckets-task.html 
sidebar: sidebar 
keywords: s3 audit, select, buckets 
summary: Debe especificar qué bloques se van a auditar en una SVM habilitada para auditoría. 
---
= Seleccione bloques para la auditoría de ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe especificar qué bloques se van a auditar en una SVM habilitada para auditoría.

.Antes de empezar
* Tiene una SVM habilitada para la auditoría S3.


.Acerca de esta tarea
Las configuraciones de auditoría de S3 se habilitan por SVM, pero debe seleccionar los bloques en las SVM que están habilitadas para auditoría. Si añade bloques a la SVM y desea que se auditen los nuevos bloques, debe seleccionarlos con este procedimiento. También puede tener bloques no auditados en una SVM habilitada para la auditoría de S3.

Las configuraciones de auditoría persisten para los depósitos hasta que se eliminan por el `vserver object-store-server audit event-selector delete` comando.

.Pasos
. Seleccione un bloque para la auditoría de S3:
+
[source, cli]
----
vserver object-store-server audit event-selector create -vserver <svm_name> -bucket <bucket_name> [[-access] {read-only|write-only|all}] [[-permission] {allow-only|deny-only|all}]
----
+
** `-access`: Especifica el tipo de acceso al evento que se va a auditar `read-only`: , `write-only` O `all` (el valor por defecto es `all`).
** `-permission`: Especifica el tipo de permiso de evento que se va a auditar `allow-only`: , `deny-only` O `all` (el valor por defecto es `all`).




.Ejemplo
En el siguiente ejemplo se crea una configuración de auditoría de bloques que solo registra los eventos permitidos con acceso de solo lectura:

`cluster1::> vserver object-store-server audit event-selector create -vserver vs1 -bucket test-bucket -access read-only -permission allow-only`
