---
permalink: abac/abac-overview.html 
sidebar: sidebar 
keywords: technical report, tr, abac, attribute, access control, attribute based, nfs, security labels, xattrs, nfs 4.2, nist, abac compliant, data management, role-based access control, rbac, policy enforcement point, pep, policy decision point, pdp 
summary: 'ONTAP, si se configura con las etiquetas de seguridad y los atributos extendidos (XATTRS) de NFS 4,2, se puede integrar con un software de control de acceso basado en roles (RBAC) y control de acceso basado en atributos (ABAC), que es una solución de gestión de datos compatible con NIST ABAC.' 
---
= Control de acceso basado en atributos con ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media


[role="lead"]
Puede implementar RBAC mejorado con atributos y control de acceso basado en atributos (ABAC) mediante ONTAP. ONTAP ofrece varios métodos que un cliente puede utilizar para conseguir ABAC a nivel de archivos, como NFS 4,2 y XATTRS mediante NFS y SMB/CIFS.

El control de acceso basado en atributos (ABAC) es un método sofisticado para administrar los derechos de acceso que tiene en cuenta los atributos del usuario, los atributos de los recursos y las condiciones ambientales. El Instituto Nacional de Estándares y Tecnología (NIST) ha establecido un estándar para ABAC, proporcionando un marco para su implementación segura y consistente.

A partir de ONTAP 9.12,1, puede configurar ONTAP con etiquetas de seguridad NFSv4,2 y atributos extendidos (XATTRS) para que se pueda integrar con una identidad de control de acceso basado en roles (RBAC) y control de acceso basado en atributos (ABAC). Esta integración permite a ONTAP acceder al software de control que se clasifica como una solución de gestión de datos compatible con NIST ABAC, que ofrece un enfoque sólido y avanzado para administrar los derechos de acceso en entornos complejos, incluidos el punto de aplicación de políticas (PEP), un punto de decisión de políticas (PDP) y políticas que consideran los atributos asociados con el usuario, el recurso y el entorno.

La integración de NetApp ONTAP con los atributos extendidos (XATTRS) y el software de control de acceso basado en atributos (ABAC) está en consonancia con las directrices establecidas en la Publicación especial del NIST 800-162, lo que garantiza el cumplimiento de los estándares del NIST para la implementación de ABAC. El uso de etiquetas de seguridad NFS 4,2 y XATTRS permite la asociación de atributos definidos por el usuario con archivos, cumpliendo con los requisitos del estándar NIST ABAC para considerar atributos de recursos en las decisiones de control de acceso. El PEP y el PDP del software ABAC se alinean con los requisitos del estándar NIST ABAC para estos componentes en el proceso de control de acceso. La capacidad de definir políticas complejas que tengan en cuenta varios atributos y condiciones se alinea con el requisito del estándar NIST ABAC para el control de acceso basado en políticas.

.Información relacionada
* link:../abac/abac-approaches.html["Aproximaciones a ABAC con ONTAP"]
* link:https://www.netapp.com/media/10720-tr-4067.pdf["NFS en NetApp ONTAP: Prácticas recomendadas y guía de implementación"^]
* Solicitud de comentarios (RFC)
+
** RFC 2203: Especificación del protocolo RPCSEC_GSS
** RFC 3530: Protocolo de sistema de archivos de red (NFS) versión 4



