---
sidebar: sidebar 
permalink: s3-snapmirror/index.html 
keywords: snapmirror s3 buckets, snapmirror buckets SVM, snapmirror s3 data protection, hybrid cloud bundle, snapmirror s3 relationship, VM peering, cluster and storage VM peering, Fan-in deployments, data protection, snapmirror s3 policy, peering 
summary: A partir de ONTAP 9.10.1, puede proteger bloques en almacenes de objetos de ONTAP S3 mediante las funciones de mirroring y backup de SnapMirror ya conocidas. 
---
= Información general de SnapMirror S3
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.10.1, puede proteger buckets en almacenes de objetos de ONTAP S3 mediante mirroring de SnapMirror y funcionalidad de backup. A diferencia de SnapMirror estándar, SnapMirror S3 permite el mirroring y los backups en destinos que no son de NetApp, como AWS S3.

SnapMirror S3 admite mirroring activo y niveles de backup de buckets S3 de ONTAP en los destinos siguientes:

[cols="50,25,25"]
|===
| Destino | ¿Admite los reflejos activos y la toma de control? | ¿Compatible con backup y restauración? 


 a| 
ONTAP S3

* Bloques en la misma SVM
* Los bloques de diferentes SVM en el mismo clúster
* Bloques en SVM en clústeres diferentes

| Sí | Sí 


| StorageGRID | No | Sí 


| AWS S3 | No | Sí 


| Cloud Volumes ONTAP para Azure | Sí | Sí 


| Cloud Volumes ONTAP para AWS | Sí | Sí 


| Cloud Volumes ONTAP para Google Cloud | Sí | Sí 
|===
Puede proteger bloques existentes en servidores ONTAP S3 o puede crear nuevos bloques con protección de datos habilitada de inmediato.



== Requisitos de SnapMirror S3

* Versión de ONTAP
+
ONTAP 9.10.1 o una versión posterior debe ejecutarse en clústeres de origen y de destino.

+

NOTE: SnapMirror S3 no es compatible con las configuraciones de MetroCluster.

* Licencia
+
Las siguientes licencias están disponibles en la link:../system-admin/manage-licenses-concept.html["ONTAP One"] Se requieren paquetes de software en los sistemas de origen y destino de ONTAP para proporcionar acceso a:

+
** Protocolo y almacenamiento ONTAP S3
** SnapMirror S3 para dirigirse a otros destinos de almacén de objetos NetApp (ONTAP S3, StorageGRID y Cloud Volumes ONTAP)
** SnapMirror S3 para dirigirse a almacenes de objetos de terceros, incluido AWS S3 (disponible en link:../data-protection/install-snapmirror-cloud-license-task.html["Paquete de compatibilidad de ONTAP One"])
** Si el clúster ejecuta ONTAP 9.10.1, se necesita unlink:../fabricpool/install-license-aws-azure-ibm-task.html["Licencia de FabricPool"].


* ONTAP S3
+
** Los servidores ONTAP S3 deben ejecutar SVM de origen y de destino.
** Se recomienda, pero no es obligatorio, que los certificados de CA para el acceso TLS estén instalados en sistemas que alojan servidores S3.
+
*** Los certificados de CA utilizados para firmar los certificados de los servidores S3 deben instalarse en la máquina virtual de almacenamiento de administración de los clústeres que alojan servidores S3.
*** Es posible usar un certificado de CA autofirmado o un certificado firmado por un proveedor de CA externo.
*** Si las máquinas virtuales de almacenamiento de origen o de destino no escuchan con HTTPS, no es necesario instalar certificados de CA.




* Relaciones entre iguales (para destinos de ONTAP S3)
+
** Las LIF de interconexión de clústeres deben configurarse (para destinos ONTAP remotos) y las LIF de interconexión de clústeres del clúster de origen y de destino pueden conectarse a las LIF de datos de servidor S3 de origen y de destino.
** Los clústeres de origen y destino tienen una relación entre iguales (para destinos de ONTAP remotos).
** Las máquinas virtuales de almacenamiento de origen y de destino tienen una relación entre iguales (para todos los destinos ONTAP).


* Política de SnapMirror
+
** Se requiere una política de SnapMirror específica de S3 para todas las relaciones de SnapMirror S3, pero puede usar la misma política para varias relaciones.
** Puede crear su propia directiva o aceptar la predeterminada *continua*, que incluye los siguientes valores:
+
*** Acelerador (límite superior de rendimiento/ancho de banda): Ilimitado.
*** Tiempo objetivo de punto de recuperación: 1 hora (3600 segundos).







NOTE: Debe tener en cuenta que, cuando hay dos buckets S3 en una relación de SnapMirror, si hay políticas de ciclo de vida configuradas de forma que la versión actual de un objeto caduque (se elimina), se replica la misma acción en el bloque del partner. Esto es así incluso si el bloque de partners es de solo lectura o pasivo.

* Claves de usuario raíz Se requieren claves de acceso de usuario raíz de la máquina virtual de almacenamiento para las relaciones de SnapMirror S3; ONTAP no las asigna de forma predeterminada. La primera vez que cree una relación de SnapMirror S3, debe verificar que las claves existan tanto en las máquinas virtuales de almacenamiento de origen como de destino y volver a generarlas si no las hacen. Si necesita volver a regenerarlos, debe asegurarse de que todos los clientes y todas las configuraciones del almacén de objetos de SnapMirror que utilicen el par de claves secreta y de acceso se actualicen con las nuevas claves.


Para obtener información sobre la configuración del servidor S3, consulte los temas siguientes:

* link:../task_object_provision_enable_s3_server.html["Habilite un servidor S3 en una máquina virtual de almacenamiento"]
* link:../s3-config/index.html["Acerca del proceso de configuración de ONTAP S3"]


Para obtener información acerca de la relación entre iguales de clústeres y máquinas virtuales de almacenamiento, consulte el tema siguiente:

* link:../task_dp_prepare_mirror.html["Preparación del mirroring y el almacenamiento (System Manager, pasos 1 a 6)"]
* link:../peering/index.html["Relaciones entre iguales de clústeres y SVM (CLI)"]




== Relaciones de SnapMirror admitidas

SnapMirror S3 admite relaciones ramificadas y en cascada. Para obtener una descripción general, consultelink:../data-protection/supported-deployment-config-concept.html["Puestas en marcha de protección de datos en cascada y distribución ramificada"].

SnapMirror S3 no admite puestas en marcha ramificadas (relaciones de protección de datos entre varios bloques de origen y un único bloque de destino). SnapMirror S3 puede admitir varios duplicados de bloque de varios clústeres en un único clúster secundario, pero cada bloque de origen debe tener su propio bloque de destino en el clúster secundario.



== Controle el acceso a S3 cucharones

Cuando se crean bloques nuevos, se puede controlar el acceso mediante la creación de usuarios y grupos.

Aunque SnapMirror S3 replica objetos del bloque de origen a un bloque de destino, no replica las políticas de grupo y bloque del almacén de objetos de origen al almacén de objetos de destino.

Los usuarios, las políticas de grupo, los permisos y los componentes similares deben estar configurados en el almacén de objetos de destino para que los clientes puedan acceder al bloque de destino durante un evento de conmutación por error.

Para obtener más información, consulte los siguientes temas:

* link:../task_object_provision_add_s3_users_groups.html["Añadir usuarios y grupos de S3 (System Manager)"]
* link:../s3-config/create-s3-user-task.html["Crear un usuario de S3 (CLI)"]
* link:../s3-config/create-modify-groups-task.html["Crear o modificar grupos S3 (CLI)"]




== Utilice el bloqueo de objetos y el control de versiones de S3 con SnapMirror S3

Puede utilizar SnapMirror S3 en bloques de ONTAP habilitados para bloqueo de objetos y control de versiones, con algunas consideraciones:

* Para replicar un depósito de origen con el bloqueo de objetos activado, el bloque de destino también debe tener el bloqueo de objetos activado. Además, tanto el origen como el destino deben tener el control de versiones activado. De este modo, se evitan los problemas de eliminación de mirroring en el depósito de destino cuando ambos bloques tienen políticas de retención predeterminadas diferentes.
* S3 SnapMirror no replica versiones históricas de los objetos. Sólo se replica la versión actual de un objeto.


Cuando los objetos Object Locked se duplican en un bucket de destino, mantienen su tiempo de retención original. Si se replican los objetos desbloqueados, adoptarán el período de retención predeterminado del depósito de destino. Por ejemplo:

* El período A tiene un período de retención predeterminado de 30 días y el período B tiene un período de retención predeterminado de 60 días. Los objetos replicados del cucharón A al cucharón B mantendrán su período de retención de 30 días, aunque sea inferior al período de retención predeterminado del cucharón B.
* El período A no tiene un período de retención predeterminado y el período B tiene un período de retención predeterminado de 60 días. Cuando los objetos desbloqueados se replican del cucharón A al cucharón B, adoptarán el período de retención de 60 días. Si un objeto se bloquea manualmente en el cucharón A, mantendrá su período de retención original cuando se replique en el cucharón B.
* El período A tiene un período de retención predeterminado de 30 días y el período B no tiene un período de retención predeterminado. Los objetos replicados del bloque A al bloque B mantendrán su período de retención de 30 días.

