---
permalink: nvme/setting-up-secure-authentication-nvme-tcp-task.html 
sidebar: sidebar 
keywords: manage, nvme, secure, authentication, tcp, dh-hmac-hcap, chap, setting up, set up 
summary: A partir de la versión 9.12.1 de ONTAP, se admite la autenticación bidireccional segura entre un host NVMe y la controladora con NVMe-TCP mediante el protocolo de autenticación DH-HMAC-CHAP.    
---
= Configure la autenticación segura a través de NVMe/TCP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de la versión 9.12.1 de ONTAP se admite la autenticación segura, bidireccional y unidireccional entre un host NVMe y la controladora mediante NVMe/TCP con el protocolo de autenticación DH-HMAC-CHAP.

Para configurar la autenticación segura, cada host o controladora debe estar asociado a una clave DH-HMAC-CHAP que es una combinación de NQN del host o la controladora NVMe y un secreto de autenticación configurado por el administrador.  Para que un host o una controladora NVMe autentique su par, debe conocer la clave asociada con el par.  SHA-256 es la función hash predeterminada y 2048 bits es el grupo DH predeterminado.

.Pasos
. Añada la autenticación DH-HMAC-CHAP al subsistema NVMe:
+
`vserver nvme subsystem host add -vserver _svm_name_ -subsystem _subsystem_ -host-nqn _host_nqn_ -dhchap-host-secret _authentication_host_secret_ -dhchap-controller-secret _authentication_controller_secret_ -dhchap-hash-function {sha-256|sha-512} -dhchap-group {none|2048-bit|3072-bit|4096-bit|6144-bit|8192-bit}`

. Compruebe que el protocolo de autenticación CHAP DH-HMAC se ha agregado al host:
+
`vserver nvme subsystem host show`

+
[listing]
----
  [ -dhchap-hash-function {sha-256|sha-512} ]  Authentication Hash Function
  [ -dhchap-group {none|2048-bit|3072-bit|4096-bit|6144-bit|8192-bit} ]
                                               Authentication Diffie-Hellman
                                               Group
  [ -dhchap-mode {none|unidirectional|bidirectional} ]
                                               Authentication Mode

----
. Compruebe que la autenticación CHAP DH-HMAC se ejecutó durante la creación de la controladora NVMe:
+
`vserver nvme subsystem controller show`

+
[listing]
----
 [ -dhchap-hash-function {sha-256|sha-512} ]  Authentication Hash Function
 [ -dhchap-group {none|2048-bit|3072-bit|4096-bit|6144-bit|8192-bit} ]
                                               Authentication Diffie-Hellman
                                               Group
 [ -dhchap-mode {none|unidirectional|bidirectional} ]
                                               Authentication Mode
----

