---
permalink: nvme/support-limitations.html 
sidebar: sidebar 
keywords: nvme, namespaces, considerations, provisioning 
summary: El soporte para NVMe varía en función de su versión de ONTAP, su plataforma y su configuración. 
---
= Configuración, compatibilidad y limitaciones de NVMe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9,4, el link:https://docs.netapp.com/us-en/ontap/san-admin/manage-nvme-concept.html["Memoria no volátil rápida (NVMe)"] el protocolo está disponible para los entornos SAN. FC-NVMe utiliza la misma práctica de configuración física y división en zonas que las redes FC tradicionales pero permite un mayor ancho de banda, un aumento de IOPS y una latencia reducida que FC-SCSI.

Las limitaciones y la compatibilidad de NVMe varían en función de la versión de ONTAP, su plataforma y la configuración. Para obtener detalles sobre su configuración específica, consulte link:https://imt.netapp.com/matrix/["Herramienta de matriz de interoperabilidad de NetApp"].



== Configuración

* Puede configurar su configuración NVMe con nodos únicos o parejas de alta disponibilidad mediante una única estructura o multiestructura.
* Debe configurar una LIF de gestión para cada SVM compatible con SAN.
* No se admite el uso de estructuras heterogéneas de switches FC, a excepción de los switches blade integrados.
+
Las excepciones específicas se enumeran en la link:https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^].

* Las estructuras en cascada, malla parcial, malla completa, núcleo-borde y director son métodos estándar en el sector para conectar switches FC a una estructura, y todos son compatibles.
+
Una estructura puede estar compuesta por uno o varios switches y las controladoras de almacenamiento se pueden conectar a varios switches.





== Funciones

Las siguientes funciones de NVMe se admiten según la versión de ONTAP.

[cols="2*"]
|===


| Iniciando con ONTAP... | Compatibilidad con NVMe 


| 9.12.1  a| 
Configuraciones IP de MetroCluster de 4 nodos en NVMe/FC.

* Las configuraciones de MetroCluster no son compatibles con NVMe antes de la versión 9.12.1.
* Las configuraciones de MetroCluster no son compatibles con NVMe/TCP.




| 9.10.1 | xref:../nvme/resize-namespace-task.html[Cambiar el tamaño de un espacio de nombres] 


| 9.9.1  a| 
* Los espacios de nombres y LUN coexisten en el mismo volumen.




| 9,8  a| 
* Coexistencia con protocolos
+
Pueden existir los protocolos SCSI, NAS y NVMe en la misma máquina virtual de almacenamiento (SVM).

+
Antes de ONTAP 9,8, NVMe puede ser el único protocolo en la SVM.
*





| 9,6  a| 
* bloques de 512 bytes y bloques de 4096 bytes para espacios de nombres
+
4096 es el valor predeterminado. 512 solo se debe utilizar si el sistema operativo del host no admite bloques de 4096 bytes.

* Movimiento de volúmenes con espacios de nombres asignados




| 9,5 | Conmutación/retorno al nodo primario de la pareja de HA de múltiples rutas. 
|===


== Protocolos

Se admiten los siguientes protocolos NVMe.

[cols="3*"]
|===


| Protocolo | Iniciando con ONTAP... | Permitido por... 


| TCP | 9.10.1 | Predeterminado 


| FC | 9,4 | Predeterminado 
|===
A partir de ONTAP 9,8, puede configurar los protocolos SCSI, NAS y NVMe en la misma máquina virtual de almacenamiento (SVM).
En ONTAP 9,7 y versiones anteriores, NVMe puede ser el único protocolo en la SVM.



== Plataformas y nodos por clúster

Los protocolos NVMe/FC y NVMe/TCP son compatibles de la siguiente manera.


NOTE: NVME/FC es compatible con las plataformas siguientes con HBA de FC de 32GB Gb.

[cols="3*"]
|===


| Iniciando con ONTAP... | Plataformas | N.o máx. De nodos por clúster 


| 9.12.1  a| 
* FAS
* AFF
* ASA

| 12 


| 9.9.1  a| 
* AFF
* ASA

| 4 


| 9,4 | Solo AFF | 4 
|===


== Espacios de nombres

Cuando trabaje con espacios de nombres de NVMe, debe tener en cuenta lo siguiente:

* Si pierde datos en una LUN, no se pueden restaurar desde un espacio de nombres o viceversa.
* La garantía de espacio para espacios de nombres es la misma que la garantía de espacio del volumen que contiene.
* No se puede crear un espacio de nombres en una transición de volúmenes desde Data ONTAP en 7-Mode.
* Los espacios de nombres no admiten lo siguiente:
+
** Cambio de nombre
** Movimiento entre volúmenes
** Copia entre volúmenes
** Copiar bajo demanda






== Limitaciones adicionales

.Las configuraciones de NVMe no admiten las siguientes funciones de ONTAP:
* Sincr
* Consola de almacenamiento virtual


.Lo siguiente solo se aplica a nodos que ejecutan ONTAP 9.4:
* Las LIF y los espacios de nombres de NVMe deben alojarse en el mismo nodo.
* Debe crearse el servicio NVMe antes de crear la LIF NVMe.


Consulte https://hwu.netapp.com["Hardware Universe de NetApp"^] Para ver una lista completa de límites de NVMe.

.Información relacionada
link:https://www.netapp.com/pdf.html?item=/media/10680-tr4080.pdf["Prácticas recomendadas para SAN modernas"]
