---
permalink: nvme/support-limitations.html 
sidebar: sidebar 
keywords: nvme, namespaces, considerations, provisioning 
summary: El soporte para NVMe varía en función de su versión de ONTAP, su plataforma y su configuración. 
---
= Compatibilidad y limitaciones de NVMe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las limitaciones y el soporte de NVMe varían en función de su versión de ONTAP, su plataforma y su configuración.



== Compatibilidad con protocolos

[cols="3*"]
|===


| Protocolo | Comenzando con ... | Permitido por... 


| TCP | ONTAP 9.10.1 | Predeterminado 


| FC | ONTAP 9.4 | Predeterminado 
|===


== Compatibilidad y limitaciones de plataformas y configuraciones

La compatibilidad con el protocolo NVMe-of varía según la plataforma y la configuración. Para obtener detalles sobre su configuración específica, consulte link:https://imt.netapp.com/matrix/["Herramienta de matriz de interoperabilidad de NetApp"].


NOTE: A partir de ONTAP 9.12.1, las configuraciones IP de MetroCluster de 4 nodos son compatibles con NVMe/FC. Las configuraciones de MetroCluster no son compatibles con NVMe antes de la versión 9.12.1.

[cols="2*"]
|===


| Iniciando con ONTAP... | Plataformas 


| 9.12.1  a| 
* FAS
* All Flash FAS (AFF)
* Plataformas de cabina All SAN (ASA)




| 9.9.1  a| 
* AFF
* ASA




| 9.4 | Solo plataformas AFF 
|===


== Compatibilidad y limitaciones con espacios de nombres

Para configurar el protocolo NVMe en el entorno SAN, debe configurar una SVM para NVMe, crear espacios de nombres y subsistemas, configurar una LIF NVMe/FC y, a continuación, asignar los espacios de nombres a los subsistemas. Cuando trabaje con espacios de nombres NVMe, debe tener en cuenta lo siguiente:

* A partir de ONTAP 9.10.1, usted puede xref:../nvme/resize-namespace-task.html[cambiar el tamaño de un espacio de nombres]. Las versiones anteriores a ONTAP 9.10.1 no admiten cambiar el tamaño de un espacio de nombres.
* A partir de ONTAP 9.6, los espacios de nombres admiten bloques de 512 bytes y bloques de 4096 bytes.
+
4096 es el valor predeterminado. 512 solo se debe utilizar si el sistema operativo del host no admite bloques de 4096 bytes.

* Si pierde datos en una LUN, no se pueden restaurar desde un espacio de nombres o viceversa.
* La garantía de espacio para espacios de nombres es la misma que la garantía de espacio del volumen que contiene.
* Los espacios de nombres no admiten lo siguiente:
+
** Cambio de nombre
+
No se puede cambiar el nombre a un espacio de nombres.

** Movimiento entre volúmenes
** Copia entre volúmenes



