= 
:allow-uri-read: 


.Lo que necesitará
* La hora debe sincronizarse en el servidor que crea los certificados, el servidor KMIP y el clúster.
* Debe haber obtenido el certificado de cliente SSL KMIP público para el clúster.
* Debe haber obtenido la clave privada asociada con el certificado de cliente SSL KMIP para el clúster.
+
El certificado de cliente SSL KMIP no debe estar protegido por contraseña.

* Debe haber obtenido el certificado público de SSL para la entidad de certificación (CA) raíz del servidor KMIP.
* En un entorno de MetroCluster, debe instalar el certificado SSL KMIP en ambos clústeres.


[NOTE]
====
Es posible instalar los certificados de cliente y de servidor en el servidor KMIP antes o después de instalar los certificados en el clúster.

====
.Acerca de esta tarea
En una pareja de alta disponibilidad, ambos nodos deben usar los mismos certificados KMIP públicos y privados. Si conecta varias parejas de alta disponibilidad con el mismo servidor KMIP, todos los nodos de las parejas de alta disponibilidad deben utilizar los mismos certificados KMIP públicos y privados.

.Pasos
. Instale los certificados de cliente SSL KMIP para el clúster:
+
`security certificate install -vserver admin_svm_name -type client`

+
Se le solicita que introduzca los certificados públicos y privados de SSL KMIP.

+
`cluster1::> security certificate install -vserver cluster1 -type client`

. Instale el certificado público SSL para la entidad de certificación (CA) raíz del servidor KMIP:
+
`security certificate install -vserver admin_svm_name -type server-ca`

+
`cluster1::> security certificate install -vserver cluster1 -type server-ca`


