= 
:allow-uri-read: 


Los clientes SMB que usan Windows pueden establecer un bit de solo lectura por archivo. Los clientes NFS no establecen un bit de solo lectura por archivo, ya que los clientes NFS no tienen ninguna operación de protocolo que utilice un bit de solo lectura por archivo.

ONTAP puede establecer un bit de solo lectura en un archivo cuando un cliente SMB que utiliza Windows crea ese archivo. ONTAP también puede establecer un bit de solo lectura cuando se comparte un archivo entre los clientes NFS y los clientes SMB. Parte del software, cuando lo utilizan los clientes NFS y clientes SMB, requiere que se habilite el bit de solo lectura.

Para que ONTAP mantenga los permisos de lectura y escritura adecuados en un archivo compartido entre clientes NFS y clientes SMB, trata el bit de solo lectura de acuerdo con las siguientes reglas:

* NFS trata cualquier archivo con el bit de solo lectura habilitado como si no tiene bits de permiso de escritura habilitados.
* Si un cliente NFS deshabilita todos los bits de permiso de escritura y al menos uno de esos bits se había habilitado anteriormente, ONTAP habilita el bit de solo lectura para ese archivo.
* Si un cliente NFS habilita algún bit de permiso de escritura, ONTAP deshabilita el bit de solo lectura para ese archivo.
* Si se habilita el bit de solo lectura de un archivo y un cliente NFS intenta detectar permisos para el archivo, los bits de permiso del archivo no se envían al cliente NFS; en su lugar, ONTAP envía los bits de permiso al cliente NFS con los bits de permiso de escritura enmascarados.
* Si se habilita el bit de solo lectura de un archivo y un cliente SMB deshabilita el bit de solo lectura, ONTAP habilita el bit de permiso de escritura del propietario para el archivo.
* Los archivos con el bit de sólo lectura activado sólo son grabables por raíz.


El bit de solo lectura interactúa con los bits de modo ACL y Unix de las siguientes maneras:

Cuando el bit de solo lectura está configurado en un archivo:

* No se realizan cambios en la ACL de ese archivo. Los clientes NFS verán la misma ACL que antes de configurar el bit de solo lectura.
* Se ignoran todos los bits del modo Unix que permiten acceso de escritura al archivo.
* Tanto los clientes NFS como SMB pueden leer el archivo, pero no pueden modificarlo.
* Las ACL y los bits de modo UNIX se ignoran en favor del bit de solo lectura. Esto significa que, incluso si la ACL permite el acceso de escritura, el bit de solo lectura impide las modificaciones.


Cuando el bit de solo lectura no está configurado en un archivo:

* ONTAP determina el acceso según los bits de modo ACL y UNIX.
+
** Si los bits del modo ACL o UNIX niegan el acceso de escritura, los clientes NFS y SMB no pueden modificar el archivo.
** Si ni los bits del modo ACL ni los del modo UNIX niegan el acceso de escritura, los clientes NFS y SMB pueden modificar el archivo.




[NOTE]
====
Los cambios en los permisos de archivo se aplican inmediatamente en los clientes SMB, pero es posible que no se apliquen de inmediato en los clientes NFS si el cliente NFS habilita el almacenamiento de atributos en caché.

====