= Requisitos
:allow-uri-read: 


[role="lead"]
TLS permite las comunicaciones de red cifradas con una seguridad equivalente y menor complejidad que Kerberos e IPsec. Como administrador, puede habilitar, configurar y deshabilitar TLS para brindar una fuerte seguridad con conexiones NFSv3 y NFSv4.x mediante System Manager, la interfaz de línea de comandos de ONTAP o la API DE REST DE ONTAP.


NOTE: NFS con TLS está disponible en ONTAP 9.15.1 como versión preliminar pública. Como oferta de vista previa, NFS sobre TLS no se admite en las cargas de trabajo de producción en ONTAP 9.15.1.

ONTAP utiliza TLS 1,3 para conexiones NFS over TLS.



== Requisitos

NFS a través de TLS requiere certificados X,509. Puede crear e instalar un certificado de servidor firmado por CA en el clúster de ONTAP o instalar un certificado que el servicio NFS utilice directamente. Sus certificados deben cumplir las siguientes directrices:

* El nombre común (CN) de cada certificado debe configurarse con el nombre de dominio completamente cualificado (FQDN) de la LIF de datos en la que se habilitará TLS.
* El nombre alternativo del asunto (SAN) de cada certificado debe configurarse con la dirección IP de la LIF de datos en la que se habilitará TLS. También puede añadir FQDN de la LIF de datos. Si se configuran tanto la dirección IP como el FQDN, los clientes NFS pueden conectarse mediante la dirección IP o el FQDN.
* Puede instalar varios certificados de servicio NFS para la misma LIF, pero solo se puede utilizar uno de ellos simultáneamente como parte de la configuración TLS de NFS.

