---
sidebar: sidebar 
permalink: networking/balance_network_loads_to_optimize_user_traffic_@cluster_administrators_only@_overview.html 
keywords: balance, balanced, load, utilization, usage, lif, port, cluster, performance 
summary: Configure el clúster para que sirva las solicitudes de cliente desde LIF cargadas correctamente. 
---
= Visión general de la red de balance
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede configurar su clúster para que sirva las solicitudes de cliente desde LIF cargadas correctamente. Esto da como resultado un uso más equilibrado de LIF y puertos, lo que a su vez permite un mejor rendimiento del clúster.

El equilibrio de carga de DNS ayuda a seleccionar una LIF de datos cargada correctamente y a equilibrar el tráfico de red de usuario en todos los puertos disponibles (físicos, grupos de interfaces y VLAN).

Con el equilibrio de carga de DNS, las LIF se asocian a la zona de equilibrio de carga de una SVM. Un servidor DNS de todo el sitio está configurado para reenviar todas las solicitudes de DNS y devolver el LIF menos cargado en función del tráfico de red y la disponibilidad de los recursos de puertos (uso de CPU, rendimiento, conexiones abiertas, etc.). El equilibrio de carga de DNS ofrece las siguientes ventajas:

* Las nuevas conexiones de clientes se equilibran entre los recursos disponibles.
* No es necesaria ninguna intervención manual para decidir qué LIF se usarán en el montaje de una SVM en particular.
* El equilibrio de carga de DNS admite NFSv3, NFSv4, NFSv4,1, SMB 2,0, SMB 2,1, SMB 3,0 y S3.

