---
sidebar: sidebar 
permalink: networking/change_the_mtu_value_for_ports_in_a_broadcast_domain.html 
keywords: modify, modifying, mtu, mtu_value, change, changing, broadcast, domain, ports, port, change the mtu value for ports in a broadcast domain 
summary: Modifique el valor MTU de un dominio de retransmisión para cambiar ese valor para todos los puertos del dominio de retransmisión 
---
= Cambie el valor de MTU para los puertos de un dominio de retransmisión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede modificar el valor MTU para un dominio de retransmisión para cambiar el valor de MTU para todos los puertos en ese dominio de retransmisión. Esto se puede hacer para admitir cambios de topología que se han realizado en la red.

.Antes de empezar
El valor de MTU debe coincidir con todos los dispositivos conectados a esa red de capa 2, excepto en el caso del puerto e0M que gestiona el tráfico de gestión.

.Acerca de esta tarea
Al cambiar el valor de MTU, se produce una breve interrupción en el tráfico de los puertos afectados. El sistema muestra un símbolo del sistema de que debe responder con y para hacer el cambio de la MTU.

.Paso
Cambie el valor de MTU para todos los puertos de un dominio de retransmisión:

....
network port broadcast-domain modify -broadcast-domain <broadcast_domain_name> -mtu <mtu_value> [-ipspace <ipspace_name>]
....
* `broadcast_domain` es el nombre del dominio de retransmisión.
* `mtu` Es el tamaño de MTU para paquetes IP; 1500 y 9000 son valores típicos.
* `ipspace` Es el nombre del espacio IP en el que reside el dominio de retransmisión. El espacio IP «predeterminado» se utiliza a menos que especifique un valor para esta opción. El siguiente comando cambia la MTU a 9000 para todos los puertos del dominio de broadcast bcast1:


....
network port broadcast-domain modify -broadcast-domain <Default-1> -mtu < 9000 >
Warning: Changing broadcast domain settings will cause a momentary data-serving interruption.
Do you want to continue? {y|n}: <y>
....