---
sidebar: sidebar 
permalink: networking/commands_for_managing_snmp.html 
keywords: snmp, traps, traphosts, trap, traphost, manage, managing, users, user, configure, configuring, modify, modifying, set, setting, event, command, system snmp, security, options -option-name snmp.enable -option-value on, options -option-name snmp.enable -option-value off, commands for managing snmp, commands for managing snmp v1, v2c, and v3 users, commands for providing contact and location information, commands for managing SNMP communities, command for displaying snmp option values, commands for managing snmp traps and traphosts, commands for managing events related to snmp traps, system snmp, security login create, security snmpusers and security login show -application snmp, security login create, security login delete, security snmpusers and security login show -application snmp, security login modify, system snmp contact, system snmp location, system snmp community add, system snmp community delete, system snmp community show, system snmp show 
summary: Gestionar SNMP, usuarios de SNMP, capturas, eventos de capturas y hosts de capturas 
---
= Comandos de ONTAP para gestionar SNMP, capturas y hosts de capturas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `system snmp` Comandos para gestionar SNMP, capturas y hosts de capturas. Puede utilizar el `security` Comandos para gestionar usuarios SNMP por SVM. Puede utilizar el `event` Comandos para gestionar eventos relacionados con capturas SNMP.



== Comandos para configurar SNMP

|===


| Si desea... | Se usa este comando... 


 a| 
Habilite SNMP en el clúster
 a| 
`options -option-name snmp.enable -option-value on`

Se debe permitir el servicio SNMP bajo la política del firewall de gestión (gestión). Puede verificar si se permite SNMP mediante el comando system Services firewall policy show.



 a| 
Deshabilite SNMP en el clúster
 a| 
`options -option-name snmp.enable -option-value off`

|===


== Comandos para gestionar usuarios de SNMP v1, v2c y v3

|===


| Si desea... | Se usa este comando... 


 a| 
Configurar usuarios SNMP
 a| 
`security login create`



 a| 
Mostrar usuarios SNMP
 a| 
`security snmpusers and security login show -application snmp`



 a| 
Eliminar usuarios SNMP
 a| 
`security login delete`



 a| 
Modifique el nombre de rol de control de acceso de un método de inicio de sesión para los usuarios SNMP
 a| 
`security login modify`

|===


== Comandos para proporcionar información de contacto y ubicación

|===


| Si desea... | Se usa este comando... 


 a| 
Mostrar o modificar los detalles de contacto del clúster
 a| 
`system snmp contact`



 a| 
Muestra o modifica los detalles de ubicación del clúster
 a| 
`system snmp location`

|===


== Comandos para gestionar comunidades SNMP

|===


| Si desea... | Se usa este comando... 


 a| 
Añada una comunidad de solo lectura (ro) para una SVM o para todas las SVM del clúster
 a| 
`system snmp community add`



 a| 
Elimine una comunidad o todas las comunidades
 a| 
`system snmp community delete`



 a| 
Mostrar la lista de todas las comunidades
 a| 
`system snmp community show`

|===
Dado que las SVM no forman parte del estándar SNMP, las consultas sobre los LIF de datos deben incluir el OID raíz de NetApp (1.3.6.1.4.1.789), por ejemplo, `snmpwalk -v 2c -c snmpNFS 10.238.19.14 1.3.6.1.4.1.789`.



== Comando para mostrar valores de opciones de SNMP

|===


| Si desea... | Se usa este comando... 


 a| 
Mostrar los valores actuales de todas las opciones de SNMP, incluido el contacto del clúster, la ubicación de contacto, si el clúster está configurado para enviar capturas, la lista de hosts de capturas y la lista de comunidades y el tipo de control de acceso
 a| 
`system snmp show`

|===


== Comandos para gestionar las capturas y los hosts de capturas de SNMP

|===


| Si desea... | Se usa este comando... 


 a| 
Habilite las capturas de SNMP que se envían desde el clúster
 a| 
`system snmp init -init 1`



 a| 
Deshabilite las capturas de SNMP enviadas desde el clúster
 a| 
`system snmp init -init 0`



 a| 
Añada un host de capturas que reciba notificaciones SNMP para eventos específicos en el clúster
 a| 
`system snmp traphost add`



 a| 
Eliminar un host de capturas
 a| 
`system snmp traphost delete`



 a| 
Mostrar la lista de hosts de capturas
 a| 
`system snmp traphost show`

|===


== Comandos para gestionar eventos relacionados con capturas SNMP

|===


| Si desea... | Se usa este comando... 


 a| 
Mostrar los eventos para los que se generan capturas SNMP (integradas)
 a| 
`event route show`

Utilice la `-snmp-support true` Parámetro para ver únicamente eventos relacionados con SNMP.

Utilice la `instance -messagename <message>` parámetro para ver una descripción detallada por qué podría haber ocurrido un evento y cualquier acción correctiva.

No se admite el enrutamiento de eventos de captura SNMP individuales a destinos de host de capturas específicos. Todos los eventos de captura SNMP se envían a todos los destinos de host de capturas.



 a| 
Mostrar una lista de registros del historial de capturas SNMP, que son notificaciones de eventos que se han enviado a capturas SNMP
 a| 
`event snmphistory show`



 a| 
Elimine un registro del historial de capturas SNMP
 a| 
`event snmphistory delete`

|===
.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+snmp["snmp del sistema"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security["seguridad"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=event["evento"^]

