---
sidebar: sidebar 
permalink: networking/commands_for_managing_failover_groups_and_policies.html 
keywords: manage, managing, failover, fail, over, group, policy, policies, groups, commands for managing failover groups and policies, network interface failover-groups, network interface modify, network interface failover-groups add-targets, network interface failover-groups remove-targets, network interface failover-groups modify, network interface modify -failover-group -failover-policy, network interface failover-groups show, rename, delete 
summary: Gestionar grupos de conmutación por error 
---
= Comandos de ONTAP para gestionar políticas y grupos de conmutación al nodo de respaldo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede utilizar `network interface failover-groups` los comandos para gestionar grupos de conmutación al nodo de respaldo. Utiliza `network interface modify` el comando para gestionar los grupos de conmutación al respaldo y las políticas de conmutación al respaldo que se aplican a una LIF.

|===


| Si desea... | Se usa este comando... 


 a| 
Agregar puertos de red a un grupo de recuperación tras fallos
 a| 
`network interface failover-groups add-targets`



 a| 
Quitar puertos de red de un grupo de recuperación tras fallos
 a| 
`network interface failover-groups remove-targets`



 a| 
Modifique los puertos de red de un grupo de conmutación por error
 a| 
`network interface failover-groups modify`



 a| 
Mostrar los grupos de conmutación por error actuales
 a| 
`network interface failover-groups show`



 a| 
Configurar la conmutación por error en una LIF
 a| 
`network interface modify -failover-group -failover-policy`



 a| 
Mostrar el grupo de conmutación por error y la política de conmutación por error que usa cada LIF
 a| 
`network interface show -fields failover-group, failover-policy`



 a| 
Cambiar el nombre de un grupo de conmutación por error
 a| 
`network interface failover-groups rename`



 a| 
Eliminar un grupo de recuperación tras fallos
 a| 
`network interface failover-groups delete`

|===

NOTE: Modificar un grupo de conmutación por error de forma que no proporcione un destino de conmutación por error válido para cualquier LIF del clúster puede provocar una interrupción del servicio cuando un LIF intenta conmutar por error.

.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["interfaz de red"^]

