---
sidebar: sidebar 
permalink: networking/commands_for_managing_firewall_service_and_policies.html 
keywords: manage, managing, firewall, fire, wall, service, policy, policies, commands for managing firewall service and policies, system services firewall, system services firewall policy, network interface modify, system services firewall modify, system services firewall show, system services firewall policy create, network interface modify -lif lifname -firewall-policy, system services firewall policy modify, system services firewall policy show, system services firewall policy clone, system services firewall policy delete 
summary: Gestione el servicio de firewall 
---
= Comandos de ONTAP para gestionar el servicio y las políticas del firewall
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `system services firewall` comandos para administrar el servicio de firewall, el `system services firewall policy` comandos para administrar las directivas de firewall y la `network interface modify` Comando para administrar la configuración del firewall de las LIF.

A partir de ONTAP 9.10.1:

* Las políticas de firewall quedan obsoletas y se reemplazan por las políticas de servicio de LIF. Anteriormente, el firewall incorporado se gestionaba mediante directivas de firewall. Esta funcionalidad ahora se logra usando una política de servicio de LIF.
* Todas las políticas de firewall están vacías y no abren ningún puerto en el firewall subyacente. En su lugar, se deben abrir todos los puertos con una política de servicio de LIF.
* No es necesario realizar ninguna acción después de una actualización a la versión 9.10.1 o posterior para pasar de políticas de firewall a políticas de servicio de LIF. El sistema crea automáticamente políticas de servicio de LIF coherentes con las políticas de firewall que se están usando en la versión anterior de ONTAP. Si utiliza scripts u otras herramientas que crean y gestionan políticas de firewall personalizadas, es posible que deba actualizar dichas secuencias de comandos para crear políticas de servicio personalizadas en su lugar.


Para obtener más información, consulte link:lifs_and_service_policies96.html["LIF y políticas de servicio en ONTAP 9.6 y posteriores"].

|===


| Si desea... | Se usa este comando... 


 a| 
Active o desactive el servicio de firewall
 a| 
`system services firewall modify`



 a| 
Muestra la configuración actual del servicio de firewall
 a| 
`system services firewall show`



 a| 
Cree una política de firewall o agregue un servicio a una política de firewall existente
 a| 
`system services firewall policy create`



 a| 
Aplique una política de firewall a una LIF
 a| 
`network interface modify -lif lifname -firewall-policy`



 a| 
Modifique las direcciones IP y las máscaras de red asociadas a una directiva de firewall
 a| 
`system services firewall policy modify`



 a| 
Mostrar información acerca de las políticas de firewall
 a| 
`system services firewall policy show`



 a| 
Cree una nueva directiva de firewall que sea una copia exacta de una directiva existente
 a| 
`system services firewall policy clone`



 a| 
Eliminar una política de firewall que no esté usando una LIF
 a| 
`system services firewall policy delete`

|===
Obtenga más información acerca de `system services firewall`, `system services firewall policy` y `network interface modify` en el link:https://docs.netapp.com/us-en/ontap-cli/["Referencia de comandos de la ONTAP"^].
