---
sidebar: sidebar 
permalink: networking/configure_dns_for_host-name_resolution.html 
keywords: configure, configuring, configuration, setup, set, setting, dns, local, remote, host, name, host-name, resolution, configure dns for host-name resolution, nsswitch.conf, configure an svm and data lifs for host-name resolution using an external dns server, vserver services name-service dns, vserver services name-service dns create, network interface modify -lif lifname -dns-zone, network interface create -lif lifname -dns-zone, vserver services name-service dns check, configure the name service switch table for host-name resolution 
summary: Use DNS para acceder a orígenes locales o remotos para obtener información del host 
---
= Configure el DNS para la resolución de nombre de host para la red ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se usa DNS para acceder a orígenes locales o remotos para obtener información del host. Debe configurar DNS para acceder a uno o ambos orígenes.

ONTAP debe ser capaz de buscar la información del host para proporcionar un acceso adecuado a los clientes. Es necesario configurar los servicios de nombre para permitir que ONTAP acceda a los servicios DNS locales o externos para obtener la información del host.

ONTAP almacena la información de configuración del servicio de nombres en una tabla que es el equivalente al `/etc/nsswitch.conf` archivo en sistemas UNIX.



== Configurar una SVM y LIF de datos para la resolución de nombres de host mediante un servidor DNS externo

Puede usar `vserver services name-service dns` el comando para habilitar DNS en una SVM y configurarlo para que utilice DNS para la resolución de nombre de host. Los nombres de host se resuelven mediante servidores DNS externos.

.Antes de empezar
Un servidor DNS para todo el sitio debe estar disponible para las búsquedas de nombre de host.

Debe configurar más de un servidor DNS para evitar un único punto de error. El `vserver services name-service dns create` comando emite una advertencia si se introduce solo un nombre de servidor DNS.

.Acerca de esta tarea
Consulte xref:configure_dynamic_dns_services.html[Configure los servicios DNS dinámicos] para obtener más información sobre la configuración del DNS dinámico en la máquina virtual de almacenamiento (SVM).

.Pasos
. Habilite DNS en la SVM:
+
....
vserver services name-service dns create -vserver <vserver_name> -domains <domain_name> -name-servers <ip_addresses> -state enabled
....
+
El siguiente comando habilita los servidores DNS externos en la SVM vs1:

+
....
vserver services name-service dns create -vserver vs1.example.com -domains example.com -name-servers 192.0.2.201,192.0.2.202 -state enabled
....
+

NOTE: El `vserver services name-service dns create` comando realiza una validación automática de la configuración y informa un mensaje de error si ONTAP no puede contactar con el servidor de nombres.

. Valide el estado de los servidores de nombres mediante `vserver services name-service dns check` el comando.
+
....
vserver services name-service dns check -vserver vs1.example.com
                                    Name Server
Vserver             Name Server     Status       Status Details
-------------       --------------- ------------ --------------------------
vs1.example.com     10.0.0.50       up           Response time (msec): 2
vs1.example.com     10.0.0.51       up           Response time (msec): 2
....


Para obtener información sobre las políticas de servicio relacionadas con DNS, consulte link:lifs_and_service_policies96.html["LIF y políticas de servicio en ONTAP 9.6 y posteriores"].



== Configure la tabla de switches de servicio de nombres para la resolución de nombres de host

Debe configurar correctamente la tabla del conmutador de servicio de nombres para permitir que ONTAP consulte el servicio de nombres local o externo a fin de recuperar la información del host.

.Antes de empezar
Debe haber decidido qué servicio de nombres debe utilizar para la asignación de hosts en el entorno.

.Pasos
. Agregue las entradas necesarias a la tabla de cambio de servicio de nombres:
+
....
vserver services name-service ns-switch modify -vserver <vserver_name> -database <database_name> -source <source_names>
....
. Compruebe que la tabla de cambio de servicio de nombres contiene las entradas esperadas en el orden deseado:
+
....
vserver services name-service ns-switch show -vserver <vserver_name>
....


.Ejemplo
En el siguiente ejemplo se modifica una entrada en la tabla del conmutador de servicio de nombres para SVM VS1 a fin de utilizar primero el archivo de hosts locales y, a continuación, un servidor DNS externo para resolver los nombres de host:

....
vserver services name-service ns-switch modify -vserver vs1 -database hosts -sources files,dns
....