---
sidebar: sidebar 
permalink: networking/configure_dynamic_dns_services.html 
keywords: dns, service, services, configuration, configure, configuring, set, up, setup, nfs, smb, cifs, active, directory, statistics, configure dns services for the svm before creating an nfs or smb server, ddns, vserver services name-service dns dynamic-update modify, vserver services name-service dns dynamic-update show 
summary: Configure los servicios DNS para la SVM antes de crear un servidor NFS o SMB 
---
= Configurar servicios DNS dinámicos para la red ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si desea que el servidor DNS integrado en Active Directory registre de forma dinámica los registros DNS de un servidor NFS o SMB en DNS, debe configurar el DNS dinámico (DDNS) en la SVM.

.Antes de empezar
Los servicios de nombres DNS deben configurarse en la SVM. Si utiliza DDNS seguro, debe usar servidores de nombres DNS integrados en Active Directory y debe haber creado un servidor NFS o SMB o una cuenta de Active Directory para la SVM.

.Acerca de esta tarea
El FQDN especificado debe ser único.


NOTE: Para evitar un error de configuración de un FQDN de SVM que no es compatible con las reglas RFC para las actualizaciones de DDNS, utilice un nombre FQDN que es compatible con RFC.

.Pasos
. Configure DDNS en la SVM:
+
`vserver services name-service dns dynamic-update modify -vserver _vserver_name_ -is- enabled _true_ [-use-secure {true|false} -vserver-fqdn _FQDN_used_for_DNS_updates_`

+
`vserver services name-service dns dynamic-update modify -vserver _vs1_ -is-enabled _true_ - use-secure _true_ -vserver-fqdn _vs1.example.com_`

+
Los asteriscos no se pueden utilizar como parte del FQDN personalizado. Por ejemplo: `*.netapp.com` no es válido.

. Compruebe que la configuración DDNS es correcta:
+
`vserver services name-service dns dynamic-update show`

+
....
Vserver  Is-Enabled Use-Secure Vserver FQDN      TTL
-------- ---------- ---------- ----------------- -------
vs1      true       true       vs1.example.com   24h
....

