---
sidebar: sidebar 
permalink: networking/configure_host-name_resolution_overview.html 
keywords: dns, translate, ddns, introduction, introducing, overview, configure host name resolution overview, translate host names 
summary: Traducir los nombres de host a direcciones IP numéricas 
---
= Obtenga información acerca de la resolución de nombres de host para la red ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP debe poder traducir los nombres de host a direcciones IP numéricas para proporcionar acceso a los clientes y acceder a los servicios. Debe configurar máquinas virtuales de almacenamiento (SVM) para que utilicen servicios de nombres locales o externos para resolver la información del host. ONTAP admite la configuración de un servidor DNS externo o la configuración del archivo de hosts locales para la resolución del nombre de host.

Cuando utiliza un servidor DNS externo, puede configurar el DNS dinámico (DDNS), que envía automáticamente información DNS nueva o modificada del sistema de almacenamiento al servidor DNS. Sin las actualizaciones dinámicas de DNS, debe agregar manualmente la información DNS (nombre DNS y dirección IP) a los servidores DNS identificados cuando se conecta un sistema nuevo o cuando cambie la información de DNS existente. Este proceso es lento y propenso a errores. Durante la recuperación ante desastres, la configuración manual puede provocar tiempos de inactividad prolongados.
