---
sidebar: sidebar 
permalink: networking/configure_network_ports_cluster_administrators_only_overview.html 
keywords: introducing, introduction, overview, network, port, port type, type, physical, interface group, vlan, vip, virtual, naming, convention, configure network ports overview, introducing physical and virtual network ports 
summary: Introducción de los puertos de red físicos y virtuales 
---
= Aprenda a configurar los puertos de red ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Los puertos son puertos físicos (NIC) o puertos virtualizados, como grupos de interfaces o VLAN.

Las redes de área local virtual (VLAN) y los grupos de interfaces constituyen los puertos virtuales. Los grupos de interfaces tratan varios puertos físicos como un único puerto, mientras que las VLAN subdividen un puerto físico en varios puertos lógicos distintos.

* Puertos físicos: Las LIF se pueden configurar directamente en puertos físicos.
* Grupo de interfaces: Agregado de puertos que contiene dos o más puertos físicos que actúan como un único puerto de enlace. Un grupo de interfaces puede ser de modo único, multimodo o multimodo dinámico.
* VLAN: Puerto lógico que recibe y envía tráfico etiquetado mediante VLAN (estándar IEEE 802.1Q). Las características del puerto VLAN incluyen el identificador de VLAN del puerto. Los puertos de puerto físico o de grupo de interfaces subyacentes se consideran puertos troncales VLAN y los puertos del switch conectados se deben configurar para que los identificadores de VLAN se queden troncales.
+
Los puertos de puerto físico o grupo de interfaces subyacentes de un puerto VLAN pueden seguir aumentando los LIF del host, que transmiten y reciben tráfico sin etiquetas.

* Puerto IP virtual (VIP): Puerto lógico que se utiliza como puerto raíz de un LIF VIP. El sistema crea los puertos VIP automáticamente y solo admite un número limitado de operaciones. Los puertos VIP son compatibles a partir de ONTAP 9.5.


La convención de nomenclatura de puertos es _enumeración_:

* El primer carácter describe el tipo de puerto.
"e" representa Ethernet.
* El segundo carácter indica la ranura numerada en la que se encuentra el adaptador de puerto.
* El tercer carácter indica la posición del puerto en un adaptador multipuerto.
"a" indica el primer puerto, "b" indica el segundo puerto, etc.


Por ejemplo: `e0b` Indica que un puerto Ethernet es el segundo puerto de la placa base del nodo.

Las VLAN deben nombrarse mediante la sintaxis `port_name-vlan-id`.

`port_name` especifica el puerto físico o el grupo de interfaces.

`vlan-id` Especifica la identificación de VLAN en la red. Por ejemplo: `e1c-80` Es un nombre de VLAN válido.
