---
sidebar: sidebar 
permalink: networking/configure_qos_marking_cluster_administrators_only_overview.html 
keywords: quality, service, qos, marking, network, traffic, DSCP, IP, IPspace, protocol, NFS, SMB, iSCSI, SnapMirror, NDMP, FTP, HTTP, HTTPS, SSH, Telnet, SNMP 
summary: El marcado QoS le ayuda a priorizar diferentes tipos de tráfico en función de las condiciones de la red para utilizar eficazmente los recursos de red. 
---
= Obtenga información sobre la calidad de servicio (QoS) de la red ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La marca de calidad de servicio (QoS) de la red le ayuda a priorizar diferentes tipos de tráfico en función de las condiciones de la red para utilizar eficazmente los recursos de la red. Puede establecer el valor de punto de código de servicios diferenciados (DSCP) de los paquetes IP salientes para los tipos de tráfico admitidos por espacio IP.



== Marcado DSCP para el cumplimiento de las UC

Puede habilitar el marcado de punto de código de servicios diferenciados (DSCP) en el tráfico de paquetes IP saliente (de salida) para un protocolo determinado con un código DSCP predeterminado o proporcionado por el usuario. El marcado DSCP es un mecanismo para clasificar y gestionar el tráfico de red y es un componente de la conformidad de Unified Capability (UC).

El marcado DSCP (también conocido como _QoS marking_ o _quality of service marking_) se habilita al proporcionar un valor de espacio IP, protocolo y DSCP. Los protocolos en los que se puede aplicar la Marca DSCP son NFS, SMB, iSCSI, SnapMirror, NDMP, FTP, HTTP/HTTPS, SSH, Telnet y SNMP.

Si no se proporciona un valor DSCP al habilitar el marcado DSCP para un protocolo determinado, se utiliza un valor predeterminado:

* El valor predeterminado para el tráfico y los protocolos de datos es 0x0A (10).
* El valor predeterminado para el tráfico y los protocolos de control es 0x30 (48).

