---
sidebar: sidebar 
permalink: networking/configure-backend-encryption.html 
keywords: cluster network, encryption, TLS, data-in-flight, backend network 
summary: Configurar los ajustes de cifrado de la red del clúster 
---
= Configurar el cifrado de red del clúster backend de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.18.1, puede configurar el cifrado de seguridad de la capa de transporte (TLS) para los datos en tránsito en la red del clúster de backend.  Este cifrado protege los datos de los clientes almacenados en ONTAP cuando se transmiten entre nodos ONTAP en la red del clúster de backend.

.Acerca de esta tarea
* El cifrado de red del clúster de backend está desactivado por defecto.
* Cuando el cifrado de la red del clúster de backend está habilitado, todos los datos del cliente almacenados en ONTAP se cifran cuando se transmiten entre los nodos ONTAP en la red del clúster de backend.  Parte del tráfico de red del clúster, como los datos de la ruta de control, no está cifrado.
* Por defecto, el cifrado de la red del clúster de backend utilizará certificados autogenerados para cada nodo del clúster.  Puede<<Gestionar certificados de cifrado de red de clúster>> en cada nodo se utilizará un certificado instalado personalizado.


.Antes de empezar
* Debes ser administrador de ONTAP en el `admin` Nivel de privilegios para realizar las siguientes tareas.
* Todos los nodos del clúster deben estar ejecutando ONTAP 9.18.1 o posterior para habilitar el cifrado de red del clúster de backend.




== Habilitar o deshabilitar el cifrado para la comunicación de red del clúster

.Pasos
. Consulte el estado actual del cifrado de la red del clúster:
+
[source, cli]
----
security cluster-network show
----
+
Este comando muestra el estado actual del cifrado de la red del clúster:

+
[source]
----
Cluster-1::*> security cluster-network show

Enabled: true

Mode: tls

Status: READY
----
. Habilitar o deshabilitar el cifrado de red del clúster de backend TLS:
+
[source, cli]
----
security cluster-network modify -enabled <true|false>
----
+
Este comando habilita o deshabilita la comunicación cifrada para los datos de clientes en tránsito en la red del clúster de backend.





== Gestionar certificados de cifrado de red de clúster

. Consulte la información actual del certificado de cifrado de la red del clúster:
+
[source, cli]
----
security cluster-network certificate show
----
+
Este comando muestra la información actual del certificado de cifrado de la red del clúster:

+
[source]
----
security cluster-network certificate show
Node                  Certificate Name                      CA
--------------------- -----------------------------------   --------------
node1                 -                                     Cluster-1_Root_CA
node2                 -                                     Cluster-1_Root_CA
node3                 google_issued_cert1                   Google_CA1
node4                 google_issued_cert2                   Google_CA1
----
+
Se muestran el certificado y el nombre de la autoridad certificadora (CA) para cada nodo del clúster.

. Modificar el certificado de cifrado de red del clúster para un nodo:
+
[source, cli]
----
security cluster-network certificate modify -node <node_name> -name <certificate_name>
----
+
Este comando modifica el certificado de cifrado de red del clúster para un nodo específico.  El certificado debe estar instalado y firmado por una CA instalada antes de ejecutar este comando.  Para obtener más información sobre la gestión de certificados, consultelink:../authentication/manage-certificates-sm-task.html["Gestione certificados de ONTAP con System Manager"] .  Si `-name` Si no se especifica, se utiliza el certificado predeterminado generado automáticamente.


