---
sidebar: sidebar 
permalink: networking/configure_ipspaces_@cluster_administrators_only@_overview.html 
keywords: ipspace, ipspaces, introduction, introducing, overview, ipv4, ipv6, routing, route, domain, configure ipspaces overview 
summary: 'Un espacio IP define un espacio de dirección IP diferente en el que residen las máquinas virtuales de almacenamiento (SVM)' 
---
= Descripción general
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Los espacios IP permiten configurar un único clúster ONTAP para que los clientes puedan acceder a él desde más de un dominio de red separado por administración, incluso si esos clientes utilizan el mismo rango de subred de direcciones IP. Esto permite la separación del tráfico de clientes para privacidad y seguridad.

Un espacio IP define un espacio de dirección IP diferente en el que residen las máquinas virtuales de almacenamiento (SVM). Los puertos y las direcciones IP definidos para un espacio IP solo se aplican dentro de ese espacio IP. Se mantiene una tabla de enrutamiento distinta para cada SVM dentro de un espacio IP; por lo tanto, no se produce ninguna ruta de tráfico entre SVM o entre espacio IP.


NOTE: Los espacios IP admiten direcciones IPv4 e IPv6 en sus dominios de enrutamiento.

Si gestiona almacenamiento para una única organización, no necesitará configurar espacios IP. Si va a gestionar almacenamiento para varias empresas en un único clúster de ONTAP y tiene la seguridad de que ninguno de sus clientes tiene configuraciones de red en conflicto, tampoco necesitará utilizar espacios IP. En muchos casos, el uso de máquinas virtuales de almacenamiento (SVM), con sus propias tablas de enrutamiento IP distintas, puede utilizarse para segregar configuraciones de red únicas en lugar de usar espacios IP.
