---
sidebar: sidebar 
permalink: networking/configure_broadcast_domains_@cluster_administrators_only@_overview.html 
keywords: broadcast, domain, overview, introduction, introducing, configure broadcast domains overview for ontap 9.8 and later, broadcast domains group network ports that belong to the same layer 2 network 
summary: Los dominios de difusión agrupan los puertos de red que pertenecen a la misma red de capa 2 
---
= Acerca de los dominios de retransmisión para ONTAP 9.8 y versiones posteriores
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Los dominios de difusión están destinados a agrupar puertos de red que pertenecen a la misma red de capa 2. Los puertos del grupo pueden usarse en una máquina virtual de almacenamiento (SVM) para el tráfico de datos o gestión.

Un dominio de retransmisión reside en un espacio IP. Durante la inicialización del clúster, el sistema crea dos dominios de retransmisión predeterminados:

* El dominio de retransmisión "predeterminado" contiene puertos que se encuentran en el espacio IP "predeterminado".
+
Estos puertos se utilizan principalmente para servir datos. Los puertos de gestión de clústeres y gestión de nodos también están en este dominio de retransmisión.

* El dominio de retransmisión "Cluster" contiene puertos que están en el espacio IP de "Cluster".
+
Estos puertos se utilizan para la comunicación del clúster e incluyen todos los puertos de clúster de todos los nodos del clúster.

+
El sistema crea dominios de retransmisión adicionales en el espacio IP predeterminado cuando sea necesario. El dominio de retransmisión "predeterminado" contiene el puerto raíz de la LIF de gestión, además de cualquier otro puerto que tenga acceso a ese puerto desde una nueva capa 2. Los dominios de retransmisión adicionales se denominan "default-1", "default-2", etc.


