---
sidebar: sidebar 
permalink: networking/configure_broadcast_domains_97_overview.html 
keywords: broadcast, domain, overview, introduction, introducing, configure broadcast domains overview for ontap 9.7 and earlier, broadcast domains group network ports that belong to the same layer 2 network 
summary: Los dominios de difusión agrupan los puertos de red que pertenecen a la misma red de capa 2 
---
= Información general sobre ONTAP 9.7 y versiones anteriores
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Los dominios de difusión están destinados a agrupar puertos de red que pertenecen a la misma red de capa 2. Los puertos del grupo pueden usarse en una máquina virtual de almacenamiento (SVM) para el tráfico de datos o gestión.

Un dominio de retransmisión reside en un espacio IP. Durante la inicialización del clúster, el sistema crea dos dominios de retransmisión predeterminados:

* El dominio de retransmisión predeterminado contiene puertos que se encuentran en el espacio IP predeterminado.
Estos puertos se utilizan principalmente para servir datos. Los puertos de gestión de clústeres y gestión de nodos también están en este dominio de retransmisión.
* El dominio de retransmisión del clúster contiene puertos que se encuentran en el espacio IP del clúster.
Estos puertos se utilizan para la comunicación del clúster e incluyen todos los puertos de clúster de todos los nodos del clúster.


Si ha creado espacios IP únicos para separar el tráfico de cliente, debe crear un dominio de retransmisión en cada uno de esos espacios IP.


NOTE: Cree un dominio de retransmisión para agrupar los puertos de red del clúster que pertenecen a la misma red de capa 2. Los puertos pueden entonces ser utilizados por las SVM.
