---
permalink: networking/convert_40gbe_nic_ports_into_multiple_10gbe_ports_for_10gbe_connectivity.html 
sidebar: sidebar 
keywords: configure, configuration, configuring, setup, setting, set, up, network, interface, card, nic, gigabit, ethernet, 40, 10, port, convert, convert 40gbe nic ports into multiple 10gbe ports for 10gbe connectivity 
summary: 'Es posible convertir las tarjetas de interfaz de red (NIC) X1144A-R6 40 GbE y X91440A-R6 para admitir cuatro puertos 10 GbE.' 
---
= Convertir puertos NIC de 40 GbE en varios puertos 10 GbE para la conectividad 10 GbE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible convertir las tarjetas de interfaz de red (NIC) X1144A-R6 40 GbE y X91440A-R6 para admitir cuatro puertos 10 GbE.

Si va a conectar una plataforma de hardware que admita una de estas NIC a un clúster que admita la interconexión de clúster 10 GbE y las conexiones de datos del cliente, la NIC debe convertirse para proporcionar las conexiones 10 GbE necesarias.

.Antes de empezar
Debe utilizar un cable de cable de conexión compatible.

.Acerca de esta tarea
Para obtener una lista completa de las plataformas compatibles con las NIC, consulte https://hwu.netapp.com/["Hardware Universe"^].


NOTE: En la NIC X1144A-R6, solo el puerto A puede convertirse para admitir las cuatro conexiones 10 GbE. Una vez convertido el puerto A, el puerto e no está disponible para su uso.

.Pasos
. Entre en el modo de mantenimiento.
. Convierta el NIC del soporte de 40 GbE al soporte de 10 GbE.
+
[listing]
----
nicadmin convert -m [40G | 10G] [port-name]
----
. Tras utilizar el comando convert, detenga el nodo.
. Instale o cambie el cable.
. Según el modelo de hardware, use el SP (Service Processor) o BMC (Baseboard Management Controller) para apagar y encender el nodo para que la conversión surta efecto.

