---
sidebar: sidebar 
permalink: networking/create_a_dns_load_balancing_zone.html 
keywords: create, creation, creating, add, adding, dns, naming, name, service, load, balancing, balance, zone, lif, create a dns load balancing zone, improve lif performance 
summary: Cree una zona de equilibrio de carga DNS para mejorar el rendimiento de la LIF 
---
= Cree zonas de equilibrio de carga DNS para la red de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede crear una zona de equilibrio de carga de DNS para facilitar la selección dinámica de una LIF en función de la carga, es decir, el número de clientes montados en una LIF. Puede crear una zona de equilibrio de carga mientras crea una LIF de datos.

.Antes de empezar
El transportista DNS del servidor DNS del sitio debe estar configurado para reenviar todas las solicitudes de la zona de equilibrio de carga a las LIF configuradas.

El artículo de la base de conocimientos link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_set_up_DNS_load_balancing_in_clustered_Data_ONTAP["Cómo configurar el equilibrio de carga de DNS en Cluster-Mode"^] En el sitio de soporte de NetApp contiene más información acerca de la configuración del equilibrio de carga de DNS mediante reenvío condicional.

.Acerca de esta tarea
* Cualquier LIF de datos puede responder a consultas DNS para un nombre de zona de equilibrio de carga DNS.
* Una zona de equilibrio de carga DNS debe tener un nombre único en el clúster y el nombre de la zona debe cumplir los siguientes requisitos:
+
** No debe superar los 256 caracteres.
** Debe incluir al menos un período.
** El primer carácter y el último no deben ser un punto ni ningún otro carácter especial.
** No puede incluir espacios entre caracteres.
** Cada etiqueta del nombre DNS no debe superar los 63 caracteres.
+
Una etiqueta es el texto que aparece antes o después del período. Por ejemplo, la zona DNS llamada storage.company.com tiene tres etiquetas.





.Paso
Utilice la `network interface create` con el `dns-zone` Opción para crear una zona de equilibrio de carga DNS.

Si ya existe la zona de equilibrio de carga, se agrega el LIF. Obtenga más información sobre los comandos descritos en este procedimiento en el link:https://docs.netapp.com/us-en/ontap-cli/["Referencia de comandos de la ONTAP"^].

En el siguiente ejemplo se muestra cómo crear una zona de equilibrio de carga DNS llamada storage.company.com durante la creación de la LIF `lif1`:

....
network interface create -vserver vs0 -lif lif1 -home-node node1
-home-port e0c -address 192.0.2.129 -netmask 255.255.255.128 -dns-zone storage.company.com
....