---
sidebar: sidebar 
permalink: networking/decide_whether_to_use_this_network_management_guide-manual.html 
keywords: ONTAP 9.0 - 9.7, CLI, decide, deciding, find, finding, decide whether to use this network management content, find the right network management, information 
summary: Este procedimiento describe el flujo de trabajo de conmutación al nodo de respaldo de ruta NAS para las versiones de ONTAP 9.0 a 9.7. 
---
= Decida si desea utilizar esta información de administración de red
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Este procedimiento describe el flujo de trabajo de conmutación al nodo de respaldo de ruta NAS para las versiones de ONTAP 9.0 a 9.7.

Debe utilizar este procedimiento en las siguientes circunstancias:

* Desea utilizar las prácticas recomendadas de conmutación por error de la ruta NAS en un flujo de trabajo que simplifique la configuración de red.
* Desea utilizar la CLI, no con System Manager.
* Va a configurar una red en un sistema nuevo que ejecute ONTAP 9.8 o una versión posterior.


Si ejecuta una versión de ONTAP posterior a 9.7, consulte:

* link:https://docs.netapp.com/us-en/ontap/networking/set_up_nas_path_failover_98_and_later_cli.html["ONTAP 9.8 y posterior flujo de trabajo de conmutación al nodo de respaldo de ruta de NAS"^]


Si desea ver más detalles de administración de la red, debe consultar:

* link:https://docs.netapp.com/us-en/ontap/networking-reference/index.html["Referencia de administración de redes de ONTAP 9"^]


Si desea utilizar System Manager para configurar la red para ONTAP 9.7 y versiones posteriores, debe seleccionar la siguiente documentación:

* link:https://docs.netapp.com/us-en/ontap/["Documentos de System Manager"^]


Si necesita información conceptual o de configuración adicional, debe elegir entre la siguiente documentación:

* Fondo conceptual para la configuración de red
+
** link:../concepts/index.html["Conceptos de ONTAP"^]


* Acceso a archivos NAS
+
** link:../nfs-admin/index.html["Gestión de NFS"^]
** link:../smb-admin/index.html["Gestión de SMB"^]


* Aprovisionamiento de hosts SAN
+
** link:../san-admin/index.html["Administración de SAN"^]


* Referencia de comandos
+
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Comandos de ONTAP 9"^]


* Informes técnicos (TRS), que incluyen información adicional sobre la tecnología ONTAP y la interacción con servicios externos
+
** http://www.netapp.com/us/media/tr-4182.pdf["Informe técnico de NetApp 4182: Consideraciones de diseño y prácticas recomendadas de almacenamiento Ethernet para las configuraciones de Data ONTAP en clúster"^]



