---
sidebar: sidebar 
permalink: networking/delete_a_broadcast_domain97.html 
keywords: 'delete, deleting, remove, removing, broadcast, domain, delete a broadcast domain, delete unnecessary broadcast domains; this moves associated ports to the "default" IPspace' 
summary: Elimine dominios de retransmisión innecesarios. De este modo, se mueven los puertos asociados al espacio IP «predeterminado» 
---
= Eliminar un dominio de retransmisión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si ya no necesita un dominio de retransmisión, puede eliminarlo. Esto mueve los puertos asociados a ese dominio de retransmisión al espacio IP "predeterminado".

.Antes de empezar
No debe haber subredes, interfaces de red ni SVM asociadas al dominio de retransmisión que desee eliminar.

.Acerca de esta tarea
* El dominio de retransmisión "Cluster" creado por el sistema no se puede eliminar.
* Cuando se elimina el dominio de retransmisión, se quitan todos los grupos de conmutación por error relacionados con el dominio de retransmisión.


.Paso
Eliminar un dominio de retransmisión:

....
network port broadcast-domain delete -broadcast-domain <broadcast_domain_name> [-ipspace <ipspace_name>]
....
El siguiente comando elimina el dominio de broadcast bcast1 en IPspace 1:

....
network port broadcast-domain delete -broadcast-domain <bcast1> -ipspace <ipspace1>
....