---
sidebar: sidebar 
permalink: networking/display_lif_information.html 
keywords: display, view, show, lif, logical, interface, display lif information, view detailed information about a lif to determine its configuration 
summary: Vea información detallada sobre una LIF para determinar su configuración 
---
= Mostrar la información de LIF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede ver información detallada sobre una LIF para determinar su configuración.

También puede que desee ver esta información para diagnosticar problemas básicos de LIF, como la comprobación de direcciones IP duplicadas o la comprobación de si el puerto de red pertenece a la subred correcta. Los administradores de máquinas virtuales de almacenamiento (SVM) solo pueden ver la información acerca de las LIF asociadas con la SVM.

.Acerca de esta tarea
Se muestra la siguiente información:

* La dirección IP asociada con la LIF
* Estado administrativo de la LIF
* Estado operativo de la LIF
+
El estado operativo de los LIF de datos viene determinado por el estado de la SVM con la que están asociadas los LIF de datos. Cuando se detiene la SVM, el estado operativo de la LIF cambia a inactivo. Cuando se inicia de nuevo la SVM, el estado operativo cambia a up

* Y el puerto en el que reside el LIF


Si los datos de un campo no están disponibles (por ejemplo, si no hay información de estado ampliada), el valor del campo se muestra como `-`.

.Paso
Muestra la información de la LIF mediante el comando network interface show.

Puede ver la información detallada de cada LIF especificando el parámetro -instance o obtener información específica especificando nombres de campo con el parámetro -fields.

El siguiente comando muestra información general acerca de todas las LIF de un clúster:

....
network interface show
           Logical    Status     Network          Current      Current Is
Vserver    Interface  Admin/Oper Address/Mask     Node         Port    Home
---------- ---------- ---------- ---------------- ------------ ------- ----
example
           lif1         up/up    192.0.2.129/22   node-01
                                                               e0d     false
node
           cluster_mgmt up/up    192.0.2.3/20     node-02
                                                               e0c     false
node-01
           clus1        up/up    192.0.2.65/18    node-01
                                                               e0a     true
           clus2        up/up    192.0.2.66/18    node-01
                                                               e0b     true
           mgmt1        up/up    192.0.2.1/20     node-01
                                                               e0c     true
node-02
           clus1        up/up    192.0.2.67/18    node-02
                                                               e0a     true
           clus2        up/up    192.0.2.68/18    node-02
                                                               e0b     true
           mgmt2        up/up    192.0.2.2/20     node-02
                                                               e0d     true
vs1
           d1           up/up    192.0.2.130/21   node-01
                                                               e0d     false
           d2           up/up    192.0.2.131/21   node-01
                                                               e0d     true
           data3        up/up    192.0.2.132/20   node-02
                                                               e0c     true
....
El siguiente comando muestra información detallada sobre una única LIF:

....
network interface show -lif data1 -instance

                    Vserver Name: vs1
          Logical Interface Name: data1
                            Role: data
                   Data Protocol: nfs,cifs
                       Home Node: node-01
                       Home Port: e0c
                    Current Node: node-03
                    Current Port: e0c
              Operational Status: up
                 Extended Status: -
                         Is Home: false
                 Network Address: 192.0.2.128
                         Netmask: 255.255.192.0
             Bits in the Netmask: 18
                 IPv4 Link Local: -
                     Subnet Name: -
           Administrative Status: up
                 Failover Policy: local-only
                 Firewall Policy: data
                     Auto Revert: false
   Fully Qualified DNS Zone Name: xxx.example.com
         DNS Query Listen Enable: false
             Failover Group Name: Default
                        FCP WWPN: -
                  Address family: ipv4
                         Comment: -
                  IPspace of LIF: Default
....