---
sidebar: sidebar 
permalink: networking/display_interface_group_information_cluster_administrators_only.html 
keywords: 'display, view, show, interface, group, information, display interface group information (cluster administrators only), verify interface group configuration, network port ifgrp show' 
summary: Verifique la configuración del grupo de interfaces 
---
= Mostrar información del grupo de interfaces (solo administradores de clúster)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede mostrar información sobre un grupo de interfaces para determinar su configuración.

.Acerca de esta tarea
Se muestra la siguiente información:

* Nodo en el que está ubicado el grupo de interfaces
* Lista de puertos de red que se incluyen en el grupo de interfaces
* Nombre del grupo de interfaces
* Función de distribución (MAC, IP, puerto o secuencial)
* La dirección Media Access Control (MAC) del grupo de interfaces
* Estado de la actividad portuaria; es decir, si todos los puertos agregados están activos (participación completa), si algunos están activos (participación parcial) o si ninguno está activo


.Paso
Se muestra información sobre los grupos de interfaces mediante el `network port ifgrp show` comando.

Puede mostrar información detallada de cada nodo especificando el `-instance` parámetro. Puede mostrar información específica especificando los nombres de campo mediante el `-fields` parámetro.

El siguiente comando muestra información sobre todos los grupos de interfaces del clúster:

....
network port ifgrp show
         Port     Distribution                    Active
Node     IfGrp    Function     MAC Address        Ports   Ports
-------- -------- ------------ -----------------  ------- --------
cluster-1-01
         a0a      ip           02:a0:98:06:10:b2  full    e7a, e7b
cluster-1-02
         a0a      sequential   02:a0:98:06:10:ca  full    e7a, e7b
cluster-1-03
         a0a      port         02:a0:98:08:5b:66  full    e7a, e7b
cluster-1-04
         a0a      mac          02:a0:98:08:61:4e  full    e7a, e7b
....
El siguiente comando muestra información detallada del grupo de interfaces de un solo nodo:

....
network port ifgrp show -instance -node cluster-1-01

                 Node: cluster-1-01
 Interface Group Name: a0a
Distribution Function: ip
        Create Policy: multimode
          MAC Address: 02:a0:98:06:10:b2
   Port Participation: full
        Network Ports: e7a, e7b
             Up Ports: e7a, e7b
           Down Ports: -
....