---
sidebar: sidebar 
permalink: networking/display_information_about_failover_groups.html 
keywords: display, view, show, failover, fail, over, groups, display information about failover groups, view information about failover groups, network interface failover-groups show, network interface failover-groups show, network interface show 
summary: Ver información acerca de los grupos de conmutación por error 
---
= Ver información sobre el grupo de conmutación por error de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede ver información acerca de los grupos de conmutación por error, incluida la lista de nodos y puertos de cada grupo de conmutación por error, tanto si la conmutación por error está habilitada como deshabilitada, así como el tipo de política de conmutación por error que se aplica a cada LIF.

.Pasos
. Muestre los puertos de destino de cada grupo de conmutación por error mediante el `network interface failover-groups show` comando.
+
El siguiente comando muestra información sobre todos los grupos de conmutación al nodo de respaldo en un clúster de dos nodos:

+
....
network interface failover-groups show
                              Failover
Vserver        Group          Targets
-------------- -------------- ---------------------------------
Cluster
               Cluster
                              cluster1-01:e0a, cluster1-01:e0b,
                              cluster1-02:e0a, cluster1-02:e0b
vs1
               Default
                              cluster1-01:e0c, cluster1-01:e0d,
                              cluster1-01:e0e, cluster1-02:e0c,
                              cluster1-02:e0d, cluster1-02:e0e
....
. Muestre los puertos de destino y el dominio de retransmisión para un grupo de conmutación al nodo de respaldo específico mediante el `network interface failover-groups show` comando.
+
El siguiente comando muestra información detallada acerca de los datos del grupo de conmutación al nodo de respaldo 12 para SVM vs4:

+
....
network interface failover-groups show -vserver vs4 -failover-group data12

       Vserver Name: vs4
Failover Group Name: data12
   Failover Targets: cluster1-01:e0f, cluster1-01:e0g, cluster1-02:e0f,
                     cluster1-02:e0g
   Broadcast Domain: Default
....
. Muestra la configuración de recuperación tras fallos utilizada por todas las LIF mediante el `network interface show` comando.
+
El siguiente comando muestra la política de conmutación por error y el grupo de conmutación por error que utiliza cada LIF:

+
....
network interface show -vserver * -lif * -fields failover-group,failover-policy
vserver   lif                 failover-policy        failover-group
--------  ------------------  ---------------------  --------------
Cluster   cluster1-01_clus_1  local-only             Cluster
Cluster   cluster1-01_clus_2  local-only             Cluster
Cluster   cluster1-02_clus_1  local-only             Cluster
Cluster   cluster1-02_clus_2  local-only             Cluster
cluster1  cluster_mgmt        broadcast-domain-wide  Default
cluster1  cluster1-01_mgmt1   local-only             Default
cluster1  cluster1-02_mgmt1   local-only             Default
vs1       data1               disabled               Default
vs3       data2               system-defined         group2
....

