---
sidebar: sidebar 
permalink: networking/display_network_connectivity_with_neighbor_discovery_protocols.html 
keywords: display, view, show, network, connectivity, neighbor, discovery, protocol, ndp, cdp, cisco, link, layer, lldp, display network connectivity with neighbor discovery protocols, use neighbor discovery protocols to view network connectivity between a pair of physical or virtual systems and their network interfaces, use cdp to detect network connectivity, considerations for using cdp, enable or disable cdp, view cdp neighbor information, example of showing and clearing statistics, use lldp to detect network connectivity, enable or disable lldp, view lldp neighbor information, adjust the interval for transmitting lldp advertisements 
summary: Utilice protocolos de detección de vecinos para ver la conectividad de red entre un par de sistemas físicos o virtuales y sus interfaces de red 
---
= Mostrar conectividad de red con protocolos de descubrimiento de vecinos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
En un centro de datos, puede utilizar protocolos de descubrimiento de vecinos para ver la conectividad de red entre un par de sistemas físicos o virtuales y sus interfaces de red. ONTAP admite dos protocolos de detección de vecinos: El protocolo de descubrimiento de Cisco (CDP) y el protocolo de detección de nivel de enlace (LLDP).

Los protocolos de detección de vecinos permiten detectar y ver automáticamente información sobre los dispositivos habilitados para protocolos conectados directamente en una red. Cada dispositivo anuncia la identificación, las capacidades y la información de conectividad. Esta información se transmite en tramas Ethernet a una dirección MAC de multidifusión y la reciben todos los dispositivos vecinos habilitados por protocolo.

Para que dos dispositivos se conviertan en vecinos, cada uno debe tener un protocolo activado y configurado correctamente. La funcionalidad del protocolo de detección se limita a redes conectadas directamente. Los vecinos pueden incluir dispositivos habilitados para protocolos, como switches, routers, puentes, etc. ONTAP admite dos protocolos de detección de vecinos, que se pueden utilizar por separado o juntos.

*Cisco Discovery Protocol (CDP)*

CDP es un protocolo de capa de enlace patentado desarrollado por Cisco Systems. Está habilitado de forma predeterminada en ONTAP para los puertos de clúster, pero debe habilitarse explícitamente para los puertos de datos.

*Protocolo de detección de nivel de enlace (LLDP)*

LLDP es un protocolo neutral en cuanto a proveedores especificado en el documento estándar IEEE 802.1AB. Debe habilitarse explícitamente para todos los puertos.
