---
sidebar: sidebar 
permalink: networking/display_ipspaces.html 
keywords: display, view, show, ipspace, display ipspaces, list the ipspaces and view ipspace information for the cluster 
summary: Enumere los espacios IP y la información sobre el espacio IP de la para el clúster 
---
= Mostrar espacios IP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede mostrar la lista de espacios IP que hay en un clúster y puede ver las máquinas virtuales de almacenamiento (SVM), los dominios de retransmisión y los puertos asignados a cada espacio IP.

.Paso
Muestre los espacios IP y las SVM en un clúster:

....
network ipspace show [-ipspace ipspace_name]
....
El siguiente comando muestra todos los espacios IP, las SVM y los dominios de retransmisión del clúster:

....
network ipspace show
IPspace        Vserver List             Broadcast Domains
-------------  -----------------------  -------------------
Cluster
               Cluster                  Cluster
Default
               vs1, cluster-1            Default
ipspace1
               vs3, vs4, ipspace1       bcast1
....
El siguiente comando muestra los nodos y puertos que forman parte del espacio IP ipspace1:

....
network ipspace show -ipspace ipspace1
IPspace name: ipspace1
Ports: cluster-1-01:e0c, cluster-1-01:e0d, cluster-1-01:e0e, cluster-1-02:e0c, cluster-1-02:e0d, cluster-1-02:e0e
Broadcast Domains: Default-1
Vservers: vs3, vs4, ipspace1
....