---
sidebar: sidebar 
permalink: networking/display_dns_domain_configurations.html 
keywords: display, view, show, dns, domain, configuration, verify, display dns domain configurations, verify dns domain configuration for one or more svms, vserver services name-service dns show 
summary: Verifique la configuración de dominio DNS para una o varias SVM 
---
= Ver la información de configuración del dominio DNS de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede mostrar la configuración de dominios DNS de una o varias máquinas virtuales de almacenamiento (SVM) en el clúster para verificar que está configurada correctamente.

.Paso
Ver las configuraciones de dominio DNS mediante `vserver services name-service dns show` comando.

El siguiente comando muestra las configuraciones de DNS de todas las SVM del clúster:

....
vserver services name-service dns show
                                                  Name
Vserver        State     Domains                  Servers
-------------- --------- ------------------------ -------------
cluster-1       enabled   xyz.company.com          192.56.0.129,
                                                  192.56.0.130
vs1            enabled   xyz.company.com          192.56.0.129,
                                                  192.56.0.130
vs2            enabled   xyz.company.com          192.56.0.129,
                                                  192.56.0.130
vs3            enabled   xyz.company.com          192.56.0.129,
                                                  192.56.0.130
....
El siguiente comando muestra información detallada de la configuración de DNS para SVM vs1:

....
vserver services name-service dns show -vserver vs1
               Vserver: vs1
               Domains: xyz.company.com
          Name Servers: 192.56.0.129, 192.56.0.130
    Enable/Disable DNS: enabled
        Timeout (secs): 2
      Maximum Attempts: 1
....