---
sidebar: sidebar 
permalink: networking/display_subnets.html 
keywords: display, view, show, subnet, display subnets, view the list of ip addresses that are allocated to each subnet within an ipspace 
summary: Consulte la lista de direcciones IP asignadas a cada subred dentro de un espacio IP 
---
= Mostrar subredes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede mostrar la lista de direcciones IP asignadas a cada subred dentro de un espacio IP. El resultado también muestra el número total de direcciones IP disponibles en cada subred y el número de direcciones que se están utilizando actualmente.

El procedimiento que siga depende de la interfaz que utilice: System Manager o CLI:

[role="tabbed-block"]
====
.System Manager
--
*A partir de ONTAP 9.12.0, puede utilizar el Administrador del sistema para mostrar subredes*

.Pasos
. Seleccione *Red > Descripción general > subredes*.
. Consulte la lista de subredes.


--
.CLI
--
*Utilice la CLI para mostrar subredes*

.Paso
Mostrar la lista de subredes y los intervalos de direcciones IP asociados que se utilizan en esas subredes:

....
network subnet show
....
El siguiente comando muestra las subredes y las propiedades de subred:

....
network subnet show

IPspace: Default
Subnet                 Broadcast               Avail/
Name   Subnet          Domain    Gateway       Total   Ranges
-----  --------------- --------- ------------ -------- -----------------------
sub1   192.0.2.0/24     bcast1   192.0.2.1     5/9     192.0.2.92-192.0.2.100
sub3   198.51.100.0/24  bcast3   198.51.100.1   3/3     198.51.100.7,198.51.100.9
....
--
====