---
sidebar: sidebar 
permalink: networking/how_dns_load_balancing_works.html 
keywords: introducing, introduction, overview, dns, naming, name, service, load, balance, balancing, performance, how dns load balancing works, introducing dns load balancing 
summary: Presentamos el balanceo de carga de DNS 
---
= Cómo funciona el equilibrio de carga de DNS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Los clientes montan una SVM especificando una dirección IP (asociada a una LIF) o un nombre de host (asociado a varias direcciones IP). De forma predeterminada, el servidor DNS de todo el sitio selecciona los LIF por turnos, lo que equilibra la carga de trabajo entre todos los LIF.

El equilibrio de carga por turnos puede sobrecargar algunos LIF, por lo que tiene la opción de utilizar una zona de equilibrio de carga DNS que gestiona la resolución de nombres de host en una SVM. Con una zona de equilibrio de carga DNS, se garantiza un mejor equilibrio de las conexiones de los nuevos clientes en los recursos disponibles, lo que mejora el rendimiento del clúster.

Una zona de equilibrio de carga DNS es un servidor DNS dentro del clúster que evalúa de forma dinámica la carga de todas las LIF y devuelve un LIF cargado correctamente. En una zona de equilibrio de carga, DNS asigna un peso (métrica), basado en la carga, a cada LIF.

A cada LIF se le asigna un peso en función de la carga de puertos y el uso de CPU de su nodo raíz. Las LIF que están en puertos menos cargados tienen una probabilidad mayor de ser devueltas en una consulta DNS. Los pesos también se pueden asignar manualmente.
