---
sidebar: sidebar 
permalink: networking/index.html 
keywords: ontap, 9, network, management, documentation, guide, ontap 9 network management documentation, welcome to the ontap 9 network management documentation portal 
summary: Bienvenido al portal de documentación de ONTAP 9 Network Management 
---
= Documentación de administración de redes de ONTAP 9
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
System Manager permite una visualización de redes enriquecida y la posibilidad de descargar datos consolidados sobre la red. Puede obtener más información en los siguientes temas:

* link:https://docs.netapp.com/us-en/ontap/concept_admin_viewing_managing_network.html["Vea y gestione su red"]
* link:https://docs.netapp.com/us-en/ontap/concept_admin_downloading_data_report.html["Descargue datos de red para la creación de informes"]


También puede configurar y gestionar la red con la CLI de ONTAP. La documentación de administración de red CLI de ONTAP 9 consta de tres áreas principales:

link:set_up_nas_path_failover_98_and_later_cli.html["Configure la conmutación al nodo de respaldo de la ruta NAS para ONTAP 9.8 y versiones posteriores"]

Aprenda a configurar la conmutación por error de rutas NAS mediante las prácticas recomendadas establecidas en ONTAP 9.8 y versiones posteriores

link:set_up_nas_path_failover_9_to_97_cli.html["Configure la conmutación al nodo de respaldo de la ruta NAS para ONTAP 9.7 y versiones anteriores"]

Aprenda a configurar la conmutación por error de rutas NAS mediante prácticas recomendadas establecidas en ONTAP 9.7 y versiones anteriores.

link:networking_reference.html["Referencia de red"]

En la documentación de referencia de redes se describe cómo configurar y gestionar puertos de red físicos y virtuales (VLAN y grupos de interfaces), LIF mediante IPv4 e IPv6, enrutamiento y servicios de resolución de hosts en clústeres; además, se optimiza el tráfico de red con el equilibrio de carga y se supervisa el clúster mediante SNMP. A menos que se indique lo contrario, esta información se aplica a todas las versiones de ONTAP 9.
