---
sidebar: sidebar 
permalink: networking/lif_compatibility_with_port_types.html 
keywords: lif, compatibility, port, types, lif compatibility with port types 
summary: Los LIF pueden tener características diferentes para admitir diferentes tipos de puertos 
---
= Compatibilidad de LIF con tipos de puertos
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Los LIF pueden tener características diferentes para admitir diferentes tipos de puertos.


NOTE: Cuando se configuran las LIF de interconexión de clústeres y gestión en la misma subred, es posible que el tráfico de gestión esté bloqueado por un firewall externo y que se produzca un error en las conexiones de AutoSupport y NTP. Puede recuperar el sistema ejecutando el `network interface modify -vserver _vserver name_ -lif _intercluster LIF_ -status-admin up|down` Comando para cambiar la LIF de interconexión de clústeres. Sin embargo, debe configurar la LIF entre clústeres y la LIF de gestión en subredes diferentes para evitar este problema.

[cols="30,70"]
|===


| LUN | Descripción 


| LIF de datos | Una LIF asociada con una máquina virtual de almacenamiento (SVM) y se utiliza para comunicarse con los clientes.
Puede tener varios LIF de datos en un puerto. Estas interfaces pueden migrar o realizar una conmutación al nodo de respaldo en todo el clúster. Puede modificar una LIF de datos para que sirva como LIF de gestión de SVM modificando su política de firewall en la gestión.

Las sesiones establecidas en servidores NIS, LDAP, Active Directory, WINS y DNS utilizan LIF de datos. 


| LIF de clúster | Una LIF que se utiliza para transportar tráfico dentro del clúster entre nodos de un clúster. Las LIF del clúster siempre se deben crear en los puertos del clúster.

Los LIF de clúster pueden conmutar por error entre los puertos de clúster del mismo nodo, pero no se pueden migrar ni realizar una conmutación por error a un nodo remoto. Cuando un nuevo nodo se une a un clúster, las direcciones IP se generan automáticamente. Sin embargo, si desea asignar direcciones IP manualmente a las LIF del clúster, debe asegurarse de que las nuevas direcciones IP se encuentren en el mismo rango de subred que las LIF del clúster existentes. 


| LIF de gestión de clústeres | LIF que proporciona una interfaz de gestión única para todo el clúster.

Un LIF de gestión de clústeres puede conmutar al respaldo a cualquier nodo del clúster. No puede conmutar al respaldo en los puertos de clústeres o de interconexión de clústeres 


| LIF entre clústeres | Un LIF que se utiliza para comunicación entre clústeres, backup y replicación. Antes de que se pueda establecer una relación de paridad de clústeres, debe crear una LIF de interconexión de clústeres en cada nodo del clúster.

Estos LIF solo pueden conmutar por error a los puertos del mismo nodo. No se pueden migrar ni realizar una conmutación por error a otro nodo del clúster. 


| LIF de gestión de nodos | Una LIF que proporciona una dirección IP dedicada para gestionar un nodo en particular en un clúster. Las LIF de gestión de nodos se crean en el momento de crear o unirse al clúster. Estas LIF se utilizan para el mantenimiento del sistema, por ejemplo, cuando un nodo se vuelve inaccesible desde el clúster. 


| LIF VIP | Una LIF VIP es cualquier LIF de datos creada en un puerto VIP. Para obtener más información, consulte link:https://docs.netapp.com/us-en/ontap/networking/configure_virtual_ip_@vip@_lifs.html["Configurar las LIF de IP virtual (VIP)"^]. 
|===