---
sidebar: sidebar 
permalink: networking/manage_the_hosts_table_@cluster_administrators_only@.html 
keywords: 'manage, managing, snmp, monitor, monitoring, troubleshooting, error detection, traps, hosts, host, table, add, modify, change, create, delete, remove, view, show, display, manage the hosts table (cluster administrators only, manage the host name entries in the hosts table of the admin svm, commands for managing local host-name entries, vserver services name-service dns hosts' 
summary: Gestione las entradas del nombre de host en la tabla hosts de la SVM de administrador 
---
= Gestionar la tabla hosts (solo administradores del clúster)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Un administrador de clúster puede añadir, modificar, eliminar y ver las entradas del nombre de host en la tabla hosts de la máquina virtual de almacenamiento (SVM) de administrador. Un administrador de SVM solo puede configurar las entradas del nombre de host para la SVM asignada.



== Comandos para gestionar entradas de nombre de host local

Puede utilizar el `vserver services name-service dns hosts` Comando para crear, modificar o eliminar entradas de la tabla de hosts DNS.

Cuando va a crear o modificar las entradas de nombre de host DNS, puede especificar varias direcciones de alias separadas por comas.

[cols="30,70"]
|===


| Si desea... | Se usa este comando... 


 a| 
Cree una entrada DNS host-name
 a| 
`vserver services name-service dns hosts create`



 a| 
Modifique una entrada de nombre de host DNS
 a| 
`vserver services name-service dns hosts modify`



 a| 
Eliminar una entrada de nombre de host DNS
 a| 
`vserver services name-service dns hosts delete`

|===
Para obtener más información, consulte http://["Comandos de ONTAP 9"^] para la `vserver services name-service dns hosts` comandos.
