---
sidebar: sidebar 
permalink: networking/manage_routing_in_an_svm_overview.html 
keywords: introducing, introduction, overview, route, routing, svm, storage, virtual, machine, network, path, overview, introducing routing tables and network paths 
summary: Introducción de tablas de enrutamiento y rutas de red 
---
= Obtenga información sobre el enrutamiento de SVM en la red ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La tabla de enrutamiento de una SVM determina la ruta de red que la SVM utiliza para comunicarse con un destino. Es importante comprender cómo funcionan las tablas de enrutamiento para evitar problemas de red antes de que ocurran.

Las reglas de enrutamiento son las siguientes:

* ONTAP enruta el tráfico por la ruta disponible más específica.
* ONTAP enruta el tráfico por una ruta de puerta de enlace predeterminada (con 0 bits de máscara de red) como último recurso, cuando no hay más rutas específicas disponibles.


En el caso de rutas con el mismo destino, máscara de red y métrica, no hay garantía de que el sistema utilice la misma ruta después de un reinicio o después de una actualización. Esto es especialmente un problema si ha configurado varias rutas predeterminadas.

Se recomienda configurar una sola ruta predeterminada para una SVM. Para evitar interrupciones, debe asegurarse de que la ruta predeterminada pueda llegar a cualquier dirección de red a la que no pueda acceder una ruta más específica. Para obtener más información, consultelink:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU134["Base de conocimientos de NetApp : SU134: El acceso a la red podría verse interrumpido por una configuración de enrutamiento incorrecta en ONTAP en clúster"^]
