---
sidebar: sidebar 
permalink: networking/merge_broadcast_domains.html 
keywords: merge, combine, broadcast, domain, reachability, merge broadcast domains, merge the ports from one broadcast domain into an existing broadcast domain 
summary: Fusionar los puertos de un dominio de difusión en un dominio de retransmisión existente 
---
= Combine dominios de retransmisión de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si se ha cambiado la posibilidad de recurrir a puertos de red, ya sea mediante una conectividad de red física o mediante una configuración de switch, y dos grupos de puertos de red previamente configurados en varios dominios de retransmisión ahora pueden volver a compartir, la fusión de dos dominios de difusión se puede utilizar para sincronizar la configuración de ONTAP con la topología de red física.


NOTE: El procedimiento para fusionar dominios de difusión es diferente en ONTAP 9,7 y versiones anteriores. Si necesita fusionar dominios de difusión en una red que ejecute ONTAP 9,7 y versiones anteriores, consulte link:https://docs.netapp.com/us-en/ontap-system-manager-classic/networking-bd/merge_broadcast_domains97.html["Fusionar dominios de retransmisión (ONTAP 9,7 o anterior)"^].

Para determinar si varios dominios de difusión pertenecen a un conjunto de accesibilidad, utilice el comando "Network Port Reachability show -details" y preste atención a qué puertos están configurados en otro dominio de difusión tienen realmente conectividad entre sí ("puertos inesperados"). Generalmente, la lista de puertos inesperados define el conjunto de puertos que se deben combinar en el dominio de retransmisión después de verificar que la configuración física y de switch es precisa.

.Paso
Fusionar los puertos de un dominio de difusión en un dominio de difusión existente:

....
network port broadcast-domain merge -ipspace <ipspace_name> -broadcast-domain <broadcast_domain_name> -into-broadcast-domain <broadcast_domain_name>
....
* `ipspace_name` es el nombre del espacio ip donde residen los dominios de difusión.
* `-broadcast-domain` es el nombre del dominio de difusión que se combinará.
* `-into-broadcast-domain` es el nombre del dominio de difusión que recibirá puertos adicionales.


.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/network-port-broadcast-domain-merge.html["puerto de red broadcast-domain-merge"^]

