---
sidebar: sidebar 
permalink: networking/modify_qos_marking_values.html 
keywords: change, changing, modify, modifying, qos, quality, service, marking, performance, modify qos marking values, change the qos marking values for different protocols, network qos-marking modify 
summary: Cambie los valores de marcado de QoS para diferentes protocolos 
---
= Modificar los valores de marca de QoS de la red ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede modificar los valores de marcado de calidad de servicio (QoS) de diferentes protocolos en cada espacio IP.

.Antes de empezar
Todos los nodos del clúster deben ejecutar la misma versión de ONTAP.

.Paso
Modifique los valores de marcado de QoS mediante el `network qos-marking modify` comando.

* La `–ipspace` El parámetro especifica el espacio IP para el que se va a modificar la entrada de marcado de QoS.
*  `–protocol`El parámetro especifica el protocolo para el que se va a modificar la entrada de marca QoS. Obtenga más información sobre `network qos-marking modify` los posibles valores del protocolo en el link:https://docs.netapp.com/us-en/ontap-cli/network-qos-marking-modify.html["Referencia de comandos de la ONTAP"^].
* La `–dscp` Parámetro especifica el valor de punto de código de servicios diferenciados (DSCP). Los valores posibles van de 0 a 63.
* La `-is-enabled` El parámetro se utiliza para habilitar o deshabilitar el marcado de calidad de servicio del protocolo especificado en el espacio IP que proporciona el `–ipspace` parámetro.


El siguiente comando habilita el marcado de calidad de servicio del protocolo NFS en el espacio IP predeterminado:

....
network qos-marking modify -ipspace Default -protocol NFS -is-enabled true
....
El siguiente comando establece el valor de DSCP en 20 para el protocolo NFS en el espacio IP predeterminado:

....
network qos-marking modify -ipspace Default -protocol NFS -dscp 20
....