---
sidebar: sidebar 
permalink: networking/modify_network_port_attributes.html 
keywords: change, changing, modify, modifying, network, port, attributes, modify network port attributes, change the autonegotiation, duplex, flow control, speed, and health settings of a physical network port 
summary: Cambie la configuración de autonegociación, doble, control de flujo, velocidad y estado de un puerto de red físico 
---
= Modifique los atributos de puerto de red
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede modificar la configuración de la autonegociación, el dúplex, el control de flujo, la velocidad y el estado de un puerto de red física.

.Antes de empezar
El puerto que desea modificar no debe estar alojando ningún LIF.

.Acerca de esta tarea
* No se recomienda modificar la configuración administrativa de las interfaces de red 100 GbE, 40 GbE, 10 GbE o 1 GbE.
+
Los valores configurados para el modo doble y la velocidad del puerto se denominan configuración administrativa. Según las limitaciones de la red, la configuración administrativa puede diferir de la configuración operativa (es decir, el modo doble y la velocidad que utiliza realmente el puerto).

* No se recomienda modificar la configuración administrativa de los puertos físicos subyacentes en un grupo de interfaces.
+
La `-up-admin` el parámetro (disponible en el nivel de privilegio avanzado) modifica la configuración administrativa del puerto.

* No se recomienda establecer el `-up-admin` Configuración de administración en FALSE para todos los puertos de un nodo, o para el puerto que aloja la última LIF de clúster operativo en un nodo.
* No se recomienda modificar el tamaño de MTU del puerto de gestión, `e0M`.
* El tamaño de MTU de un puerto en un dominio de retransmisión no se puede cambiar del valor MTU que se establece para el dominio de retransmisión.
* El tamaño de MTU de una VLAN no puede superar el valor del tamaño de MTU de su puerto base.


.Pasos
. Modifique los atributos de un puerto de red:
+
`network port modify`

. Puede ajustar la `-ignore-health-status` el campo a true para especificar que el sistema puede ignorar el estado del puerto de red de un puerto especificado.
+
El estado del puerto de red cambia automáticamente del estado degradado al correcto, y este puerto ahora se puede utilizar para alojar LIF. Debe establecer el control de flujo de los puertos del clúster a. `none`. De forma predeterminada, el control de flujo se establece en `full`.



El comando siguiente deshabilita el control de flujo en el puerto e0b estableciendo el control de flujo en none:

....
network port modify -node cluster-1-01 -port e0b -flowcontrol-admin none
....