---
sidebar: sidebar 
permalink: networking/recover_from_an_incorrectly_configured_cluster_lif.html 
keywords: misconfigured, misconfigurations, incorrect, incorrectly, switch, switches, switched, cable, physical, wiring, wired, reachability, port, cluster, ontap 9.8 and later, recover from an incorrectly configured cluster lif, how to identify and correct a cluster that has been misconfigured, cluster create, network port, reachability show -detail, reset the home port 
summary: Cómo identificar y corregir un clúster que se ha configurado incorrectamente 
---
= Recuperar un LIF de ONTAP configurado incorrectamente
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
No se puede crear un clúster cuando la red del clúster se cableado a un switch, pero no todos los puertos configurados en el espacio IP del clúster pueden llegar a los otros puertos configurados en el espacio IP del clúster.

.Acerca de esta tarea
En un clúster con switches, si está configurada una interfaz de red de clúster (LIF) en el puerto incorrecto o si hay un puerto de clúster conectado a la red incorrecta, `cluster create` el comando puede fallar con el siguiente error:

....
Not all local cluster ports have reachability to one another.
Use the "network port reachability show -detail" command for more details.
....
Obtenga más información sobre `cluster create` en el link:https://docs.netapp.com/us-en/ontap-cli/cluster-create.html["Referencia de comandos del ONTAP"^].

Los resultados `network port show` del comando podrían mostrar que se han agregado varios puertos al espacio IP del clúster porque están conectados a un puerto que está configurado con una LIF de clúster. Sin embargo, los resultados de la  `network port reachability show -detail` El comando revela qué puertos no tienen conectividad entre sí.

Obtenga más información sobre `network port show` en el link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["Referencia de comandos del ONTAP"^].

Para recuperar desde un LIF de clúster configurado en un puerto que no sea accesible a los otros puertos configurados con LIF del clúster, realice los pasos siguientes:

.Pasos
. Restablezca el puerto de inicio de la LIF del clúster en el puerto correcto:
+
....
network port modify -home-port
....
+
Obtenga más información sobre `network port modify` en el link:https://docs.netapp.com/us-en/ontap-cli/network-port-modify.html["Referencia de comandos del ONTAP"^].

. Quite los puertos que no tienen LIF del clúster configuradas en ellos desde el dominio de retransmisión del clúster:
+
....
network port broadcast-domain remove-ports
....
+
Obtenga más información sobre `network port broadcast-domain remove-ports` en el link:https://docs.netapp.com/us-en/ontap-cli/network-port-broadcast-domain-remove-ports.html["Referencia de comandos del ONTAP"^].

. Cree el clúster:
+
....
cluster create
....


.Resultado
Una vez finalizada la creación del clúster, el sistema detecta la configuración correcta y coloca los puertos en los dominios de retransmisión correctos.

.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/network-port-reachability-show.html["Mostrar la accesibilidad del puerto de red"^]

