---
sidebar: sidebar 
permalink: networking/snmp_traps.html 
keywords: snmp, trap, traphosts, asynchronous, notification, notify, alert, message, thresholds, failures, errors, fail, rfc 1215, built in, built-in, standard, snmp traps, use snmp traps to periodically check for operational thresholds or failures, standard snmp traps, system snmp authtrap, rfc 1215, coldstart, warmstart, linkdown, linkup, authenticationfailure, built-in snmp traps, traphost, diskfailedshutdown, cputoobusy, and volumenearlyfull 
summary: Utilice capturas SNMP para comprobar periódicamente si hay fallos o umbrales operativos 
---
= Capturas SNMP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las capturas SNMP capturan información de supervisión del sistema que se envía como una notificación asíncrona desde el agente SNMP al administrador SNMP.

Hay tres tipos de capturas SNMP: Estándar, integrado y definido por el usuario. ONTAP no admite capturas definidas por el usuario.

Una captura se puede utilizar para comprobar periódicamente si existen umbrales o errores operativos definidos en el MIB. Si se alcanza un umbral o se detecta un fallo, el agente SNMP envía un mensaje (captura) a los hosts de capturas para alertarlos del evento.


NOTE: ONTAP es compatible con las trampas SNMPv1 y, a partir de las trampas ONTAP 9.1 y SNMPv3. ONTAP no admite capturas SNMPv2c ni informa.



== Capturas SNMP estándar

Estos solapamientos se definen en RFC 1215. Hay cinco capturas SNMP estándar que son compatibles con ONTAP: Coldstart, warwStart, linkdown, linkup y authenticationFailure.


NOTE: La captura de autenticación por fallo está deshabilitada de forma predeterminada. Debe utilizar el `system snmp authtrap` comando para habilitar la captura. Para obtener más información, consulte las páginas de manual: http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Comandos de ONTAP 9"^]



== Capturas SNMP integradas

Las capturas integradas están predefinidas en ONTAP y se envían automáticamente a las estaciones de administración de red en la lista de capturas si se produce un evento. Estas capturas, como diskFailedShutdown, cpuTooBusy y volumeNearlyFull, se definen en la MIB personalizada.

Cada captura integrada se identifica mediante un código de captura único.
