---
sidebar: sidebar 
permalink: networking/split_broadcast_domains.html 
keywords: split, broadcast, domain, separate, splitting, separating, reachability, port, split a broadcast domain to synchronize the ontap configuration with the physical network topology, unreachable ports, broadcast-domain split, split broadcast domains 
summary: Divida un dominio de retransmisión para sincronizar la configuración de ONTAP 9.8 y posterior con la topología de red física 
---
= Divida los dominios de retransmisión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si la posibilidad de recurrir a un puerto de red ha cambiado, ya sea mediante la conectividad de red física o la configuración del switch. Además, un grupo de puertos de red previamente configurados en un único dominio de difusión se ha particionado en dos conjuntos diferentes de accesibilidad, puede dividir un dominio de difusión para sincronizar la configuración de ONTAP con la topología de red física.

Para determinar si un dominio de difusión de puerto de red se divide en más de un conjunto de accesibilidad, utilice `network port reachability show -details` Y preste atención a qué puertos no tienen conectividad entre sí ("puertos no accesibles"). Normalmente, la lista de puertos inaccesibles define el conjunto de puertos que se deben dividir en otro dominio de retransmisión, después de verificar que la configuración física y del switch es precisa.

.Paso
Divida un dominio de retransmisión en dos dominios de retransmisión:

....
network port broadcast-domain split -ipspace <ipspace_name> -broadcast-domain <broadcast_domain_name> -new-broadcast-domain <broadcast_domain_name> -ports <node:port,node:port>
....
* `ipspace_name` es el nombre del espacio ip donde reside el dominio de difusión.
* -`broadcast-domain` es el nombre del dominio de difusión que se dividirá.
* -`new-broadcast-domain` es el nombre del nuevo dominio de difusión que se creará.
* -`ports` es el nombre del nodo y el puerto que se añadirán al nuevo dominio de retransmisión.

