---
sidebar: sidebar 
permalink: networking/standard_properties_of_ipspaces.html 
keywords: standard, property, properties, ipspace, special, ipspaces, svm, cluster, default, understanding, cluster, initialization, initialized, introducing, introduction, overview, standard properties of ipspaces, introducing the default and cluster ipspaces created during cluster initialization, default ipspace, cluster ipspace, system svm 
summary: Presentamos los espacios IP predeterminados y del clúster que se crearon durante la inicialización del clúster 
---
= Propiedades estándar de los espacios IP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Los espacios IP especiales se crean de forma predeterminada cuando se crea por primera vez el clúster. Además, se crean máquinas virtuales de almacenamiento (SVM) especiales para cada espacio IP.

Cuando se inicializa el clúster, se crean dos espacios IP automáticamente:

* Espacio IP «predeterminado»
+
Este espacio IP es un contenedor de puertos, subredes y SVM que proporcionan datos. Si su configuración no necesita espacios IP separados para los clientes, todas las SVM se pueden crear en este espacio IP. Este espacio IP también contiene los puertos de gestión del clúster y de gestión de nodos.

* Espacio IP de «cluster»
+
Este espacio IP contiene todos los puertos del clúster de todos los nodos del clúster. Se crea automáticamente cuando se crea el clúster. Proporciona conectividad a la red de clústeres privada interna. A medida que más nodos se unen al clúster, los puertos del clúster de esos nodos se añaden al espacio IP «Cluster».



Hay una SVM del sistema para cada espacio IP. Cuando crea un espacio IP, se crea una SVM del sistema predeterminada del mismo nombre:

* La SVM del sistema para el espacio IP de «clúster» transporta tráfico de clústeres entre nodos de un clúster en la red de clúster privada interna.
+
Lo gestiona el administrador del clúster y tiene el nombre «Cluster».

* La SVM del sistema para el espacio IP «predeterminado» transporta el tráfico de gestión del clúster y los nodos, incluido el tráfico de interconexión de clústeres entre clústeres.
+
Lo gestiona el administrador del clúster y utiliza el mismo nombre que el clúster.

* La SVM del sistema para un espacio IP personalizado que crea transporta el tráfico de gestión de esa SVM.
+
El administrador del clúster lo gestiona y utiliza el mismo nombre que el espacio IP.



Puede haber una o varias SVM para los clientes en un espacio IP. Cada SVM del cliente tiene sus propios volúmenes de datos y configuraciones, y se administra independientemente de las otras SVM.
