---
permalink: concepts/application-aware-data-management-concept.html 
sidebar: sidebar 
keywords: application aware data management 
summary: La gestión de datos para aplicaciones permite describir la aplicación que se desea implementar a través de ONTAP en términos de aplicación, en lugar de en términos de almacenamiento. La aplicación puede configurarse y prepararse para servir datos rápidamente con entradas mínimas mediante System Manager y las API DE REST. 
---
= Gestión de datos para aplicaciones
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La gestión de datos para aplicaciones permite describir la aplicación que se desea implementar a través de ONTAP en términos de aplicación, en lugar de en términos de almacenamiento. La aplicación puede configurarse y prepararse para servir datos rápidamente con entradas mínimas mediante System Manager y las API DE REST.

La función de gestión de datos para aplicaciones ofrece una forma de configurar, gestionar y supervisar el almacenamiento en el nivel de aplicaciones individuales. Esta función incorpora las prácticas recomendadas relevantes de ONTAP para aprovisionar de forma óptima aplicaciones, con una colocación equilibrada de objetos de almacenamiento en función de los niveles de servicio de rendimiento deseados y los recursos disponibles del sistema.

La función de gestión de datos compatible con aplicaciones incluye un conjunto de plantillas de aplicación, con cada plantilla compuesta por un conjunto de parámetros que describen de forma colectiva la configuración de una aplicación. Estos parámetros, que a menudo se predefinen con valores predeterminados, definen las características que un administrador de aplicación podría especificar para aprovisionar almacenamiento en un sistema ONTAP, como el tamaño de la base de datos, los niveles de servicio, los elementos de acceso de protocolos como LIF, así como los criterios de protección local y los criterios de protección remota. ONTAP configura entidades de almacenamiento como, por ejemplo, LUN y volúmenes con los tamaños y niveles de servicio adecuados para la aplicación, basándose en los parámetros especificados.

Puede realizar las siguientes tareas para las aplicaciones:

* Cree aplicaciones mediante las plantillas de aplicación
* Gestione el almacenamiento asociado con las aplicaciones
* Modifique o elimine las aplicaciones
* Ver aplicaciones
* Gestionar snapshots de las aplicaciones
* Cree xref:../consistency-groups/index.html[grupos de consistencia] Para ofrecer funcionalidades de protección de datos seleccionando varios LUN en los mismos volúmenes o en diferentes volúmenes

