---
permalink: concepts/builtin-storage-efficiency-concept.html 
sidebar: sidebar 
keywords: storage efficiency, built-in, platform, controller, offload, aff a1k, aff a90, aff a70, fas90, fas70, aff a50, aff a30 
summary: La eficiencia del almacenamiento del procesador de descarga dedicado está habilitada de forma predeterminada en ciertas plataformas AFF y FAS . Estas plataformas no utilizan eficiencia de almacenamiento sensible a la temperatura.  La compresión comienza sin esperar a que los datos se enfríen y se realiza mediante un procesador de descarga dedicado. 
---
= Conozca la eficiencia del almacenamiento del procesador de descarga dedicado de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La eficiencia de almacenamiento del procesador de descarga dedicado realiza un empaquetado secuencial de bloques físicos contiguos y utiliza un procesador de descarga dedicado para la compresión de datos de 32k.  Con una compresión de 32k, el ahorro de espacio se realiza a nivel agregado, a diferencia de las plataformas que utilizan compresión adaptativa de 8k, donde el ahorro de espacio se realiza a nivel de volumen.  Las plataformas que utilizan un procesador de descarga dedicado para el almacenamiento eficiente no utilizan la eficiencia de almacenamiento sensible a la temperatura (TSSE), lo que significa que la compresión no se basa en datos fríos o calientes.  Esto se traduce en un ahorro de espacio inmediato sin afectar al rendimiento.

La eficiencia del almacenamiento del procesador de descarga dedicado está habilitada de forma predeterminada en las siguientes plataformas y versiones de ONTAP .


NOTE: La plataforma AFF A20 no admite la eficiencia de almacenamiento del procesador de descarga dedicado.  Para las plataformas AFF A20, los datos que se migran mediante la tecnología SnapMirror se convierten automáticamente a compresión en línea de 32k mediante la CPU principal.

[cols="2"]
|===
| Plataforma | Versión de ONTAP 


 a| 
* AFF A1K
* AFF A90
* AFF A70
* FAS90
* FAS70

| 9.15.1 o posterior 


 a| 
* AFF A50
* AFF A30

| 9.16.1 o posterior 
|===
Para las siguientes plataformas, la eficiencia del almacenamiento se habilita automáticamente y no requiere configuración.  Esto se aplica a todos los volúmenes de aprovisionamiento fino recién creados y a los datos existentes, incluidos los volúmenes trasladados desde otras plataformas.  La deduplicación está habilitada independientemente de la configuración de garantía de espacio.  Tanto la compresión como la compactación de datos requieren que la garantía de espacio se establezca en ninguna.  Los datos que se migran mediante la tecnología de movimiento de volumen o SnapMirror se convierten automáticamente a compresión en línea de 32k.

* AFF A1K
* AFF A90
* AFF A70
* AFF A50
* AFF A30


Para las siguientes plataformas, la eficiencia de almacenamiento está habilitada de manera predeterminada solo en volúmenes con aprovisionamiento fino existentes que tenían habilitada la eficiencia de almacenamiento antes de actualizar a ONTAP 9.15.1 o posterior.  Puede habilitar la eficiencia del almacenamiento en volúmenes recién creados mediante el método CLI o API REST.  Los datos que se migran mediante la tecnología de movimiento de volumen o SnapMirror se convierten a compresión en línea de 32k solo si la compresión estaba habilitada en la plataforma original.

* FAS90
* FAS70


Para obtener información sobre cómo actualizar un controlador a una de las plataformas compatibles, consulte la https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Documentación sobre actualización del hardware de ONTAP"^] .
