---
permalink: concepts/builtin-storage-efficiency-concept.html 
sidebar: sidebar 
keywords: storage efficiency, built-in, platform, controller, offload 
summary: A partir de ONTAP 9.15.1, la eficiencia del almacenamiento y la compactación de datos incorporadas se encuentran en las plataformas AFF A70, AFF A90 y AFF A1K. 
---
= Eficiencia del almacenamiento de CPU o procesador de descarga dedicado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.15,1, ONTAP proporciona eficiencia de almacenamiento y compactación de datos en plataformas AFF A70, AFF A90, AFF A1K, FAS70 y FAS90.

En función de la plataforma, se aplica lo siguiente al actualizar:

* La compresión se realiza usando la CPU principal o con un procesador de descarga dedicado.
* La eficiencia del almacenamiento se habilita de forma predeterminada en todos los volúmenes aprovisionados mediante thin provisioning o solo en los volúmenes existentes.
+
Para plataformas FF A70, AFF A90 o AFF A1K, la eficiencia del almacenamiento se activa automáticamente y no requiere configuración. Esto se aplica a todos los volúmenes con Thin-Provisioning recién creados y datos existentes, incluidos los volúmenes transferidos desde otras plataformas a una plataforma AFF A70, AFF A90 o AFF A1K.

+
Para una plataforma FAS70 o FAS90, la eficiencia del almacenamiento se activa de forma predeterminada solo en volúmenes Thin-Provisioning existentes que tenían activada la eficiencia del almacenamiento antes de la actualización. Es posible habilitar la eficiencia del almacenamiento en los volúmenes recién creados mediante el método API DE REST o la CLI.

* Los datos que se migran mediante Volume Move o tecnología SnapMirror se convierten automáticamente en compresión inline de 32k:
+
En el caso de una plataforma AFF A70, AFF A90 o AFF A1K, los datos se convierten automáticamente.

+
Para una plataforma FAS70 o FAS90, los datos se convierten únicamente si la compresión estaba activada en la plataforma original.



La eficiencia del almacenamiento sensible a la temperatura no se aplica en las plataformas AFF A70, AFF A90, AFF A1K, FAS70 y FAS90. La compresión no se basa en datos activos o inactivos en estas plataformas, por lo que la compresión se inicia sin esperar a que los datos dejen de estar inactivos.

La eficiencia del almacenamiento en las plataformas AFF A70, AFF A90, AFF A1K, FAS70 y FAS90 usa paquetes secuenciales de bloques físicos contiguos para mejorar aún más la eficiencia del almacenamiento para los datos comprimidos.

Para obtener información sobre la actualización de una controladora a un AFF A70, AFF A90, AFF A1K, FAS70 o FAS90, consulte el https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Documentación sobre actualización del hardware de ONTAP"^].
