---
permalink: concepts/builtin-storage-efficiency-concept.html 
sidebar: sidebar 
keywords: storage efficiency, built-in, platform, controller, offload 
summary: A partir de ONTAP 9.15.1, la eficiencia del almacenamiento y la compactación de datos incorporadas se encuentran en las plataformas AFF A70, AFF A90 y AFF A1K. 
---
= Eficiencia del almacenamiento de CPU o procesador de descarga dedicado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La eficiencia del almacenamiento de la CPU o del procesador de descarga dedicado está habilitada de manera predeterminada en ciertas plataformas AFF y FAS .  Estas plataformas no utilizan eficiencia de almacenamiento sensible a la temperatura.  La compresión comienza sin esperar a que los datos se enfríen y se realiza utilizando la CPU principal o un procesador de descarga dedicado.  Estas plataformas también utilizan el empaquetado secuencial de bloques físicos contiguos para mejorar aún más la eficiencia del almacenamiento de datos comprimidos.

La eficiencia del almacenamiento de la CPU o del procesador de descarga dedicado está disponible en las siguientes plataformas y versiones de ONTAP :

[cols="2"]
|===
| Plataforma | Versión de ONTAP 


 a| 
* AFF A1K
* AFF A90
* AFF A70
* FAS90
* FAS70

| 9.15.1 o posterior 


 a| 
* AFF A50
* AFF A30

| 9.16.1 o posterior 
|===

NOTE: Los datos que se migran mediante la tecnología SnapMirror se convierten automáticamente a compresión en línea de 32k en las plataformas AFF A20.  Sin embargo, la plataforma AFF A20 no admite la eficiencia del almacenamiento de la CPU ni del procesador de descarga dedicado.

Para las siguientes plataformas, la eficiencia del almacenamiento se habilita automáticamente y no requiere configuración.  Esto se aplica a todos los volúmenes de aprovisionamiento fino recién creados y a los datos existentes, incluidos los volúmenes trasladados desde otras plataformas.  La deduplicación está habilitada independientemente de la configuración de garantía de espacio.  Tanto la compresión como la compactación de datos requieren que la garantía de espacio se establezca en ninguna.  Los datos que se migran mediante la tecnología de movimiento de volumen o SnapMirror se convierten automáticamente a compresión en línea de 32k.

* AFF A1K
* AFF A90
* AFF A70
* AFF A50
* AFF A30


Para las siguientes plataformas, la eficiencia de almacenamiento está habilitada de manera predeterminada solo en volúmenes con aprovisionamiento fino existentes que tenían habilitada la eficiencia de almacenamiento antes de actualizar a ONTAP 9.15.1 o posterior.  Puede habilitar la eficiencia del almacenamiento en volúmenes recién creados mediante el método CLI o API REST.  Los datos que se migran mediante la tecnología de movimiento de volumen o SnapMirror se convierten a compresión en línea de 32k solo si la compresión estaba habilitada en la plataforma original.

* FAS90
* FAS70


Para obtener información sobre cómo actualizar un controlador a una de las plataformas compatibles, consulte la https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Documentación sobre actualización del hardware de ONTAP"^] .
