---
permalink: concepts/builtin-storage-efficiency-concept.html 
sidebar: sidebar 
keywords: storage efficiency, built-in, platform, controller, offload 
summary: A partir de ONTAP 9.15.1, la eficiencia del almacenamiento y la compactación de datos incorporadas se encuentran en las plataformas AFF A70, AFF A90 y AFF A1K. 
---
= Eficiencia del almacenamiento de CPU o procesador de descarga dedicado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.15.1, ONTAP proporciona eficiencia de almacenamiento y compactación de datos en plataformas AFF A70, AFF A90 y AFF A1K. Dependiendo de la plataforma, la compresión se realiza utilizando la CPU principal o con un procesador de descarga dedicado. La eficiencia del almacenamiento se activa de forma automática y no requiere configuración. La eficiencia del almacenamiento se habilita de forma predeterminada en los volúmenes aprovisionados recientemente creados y se aplica a los datos existentes, incluidos los volúmenes movidos desde otras plataformas a las plataformas AFF A70, AFF A90 o AFF A1K.

La eficiencia del almacenamiento sensible a la temperatura no se aplica en las plataformas AFF A70, AFF A90 y AFF A1K. La compresión no se basa en datos activos o inactivos en estas plataformas, por lo que la compresión se inicia sin esperar a que los datos dejen de estar inactivos.

La eficiencia del almacenamiento en las plataformas AFF A70, AFF A90 y AFF A1K usa paquetes secuenciales de bloques físicos contiguos para mejorar aún más la eficiencia del almacenamiento de los datos comprimidos.

Los datos que se migran a las plataformas AFF A70, AFF A90 o AFF A1K mediante movimiento de volúmenes o tecnología SnapMirror se convierten automáticamente a compresión inline de 32k:1. La eficiencia del almacenamiento para los datos migrados de una plataforma AFF A70, A90 o A1K a una plataforma anterior se transforma automáticamente en función de las funcionalidades de eficiencia de la plataforma de destino.

Para obtener información sobre la actualización de un controlador a un AFF A70, AFF A90 o AFF A1K, consulte el link:https://review.docs.netapp.com/us-en/ontap-systems-upgrade_restructure-sidebar/choose_controller_upgrade_procedure.html["Documentación sobre actualización del hardware de ONTAP"^].
