---
sidebar: sidebar 
permalink: concepts/capacity-measurements-in-sm-concept.html 
keywords: capacity, measurement, physical, logical, storage, used storage, local tier capacity, aggregate capacity, block, capacity concern, add capacity, volume, used capacity, available capacity, total capacity, inactive capacity, static insights, dynamic insights, snapshot copy, snapshot copies, inactive data, overprovision, overflows, snapshot copy policy, snapshot copy reserves, reserves, policy, top volumes 
summary: La capacidad del sistema se puede medir como el espacio físico o el espacio lógico. Las versiones recientes de System Manager utilizan mediciones de la capacidad física y lógica. 
---
= Mediciones de capacidad en System Manager
:allow-uri-read: 


[role="lead"]
La capacidad del sistema se puede medir como el espacio físico o el espacio lógico. Las versiones recientes de System Manager utilizan mediciones de la capacidad física y lógica.

Las diferencias entre las dos mediciones se explican en las siguientes descripciones:

* *Capacidad física*: El espacio físico se refiere a los bloques físicos de almacenamiento utilizados en el nivel de volumen o local. El valor de la capacidad física utilizada suele ser menor que el valor de la capacidad lógica utilizada debido a la reducción de datos de funciones de eficiencia del almacenamiento (como la deduplicación y la compresión).
* *Capacidad lógica*: El espacio lógico se refiere al espacio utilizable (los bloques lógicos) en un volumen o nivel local. El espacio lógico hace referencia a cómo se puede utilizar el espacio teórico, sin tener en cuenta los resultados de la deduplicación o la compresión. El valor del espacio lógico utilizado procede de la cantidad de espacio físico utilizado más el ahorro derivado de las funciones de eficiencia del almacenamiento (como la deduplicación y compresión) que se han configurado. Esta medición suele ser mayor que la capacidad física utilizada porque incluye copias Snapshot, clones y otros componentes, y no refleja la compresión de datos ni otras reducciones del espacio físico. Por lo tanto, la capacidad lógica total podría ser mayor que el espacio aprovisionado.



NOTE: En System Manager, las representaciones de capacidad no dan cuenta de las capacidades de niveles de almacenamiento raíz (agregado).

<<measurements-used-cap>>
<<cap-measurement-terms>>
<<cap-measurement-units>>

.Información adicional
Es posible supervisar la capacidad de un clúster, niveles locales y volúmenes en System Manager. Consulte link:../task_admin_monitor_capacity_in_sm.html["Supervise la capacidad en System Manager"].



== Mediciones de capacidad utilizada

Las mediciones de la capacidad utilizada se muestran de forma diferente según la versión de System Manager que se esté usando, como se explica en la siguiente tabla:

[cols="30,30,40"]
|===


| La versión de System Manager | Término utilizado para capacidad | El tipo de capacidad a la que se hace referencia 


 a| 
9.5 y 9.6 (vista clásica)
 a| 
Utilizado
 a| 
El espacio físico utilizado



 a| 
9.7 y 9.8
 a| 
Utilizado
 a| 
Espacio lógico utilizado (si se han habilitado las opciones de eficiencia del almacenamiento)



 a| 
9.9.1 y posterior
 a| 
Lógica utilizada
 a| 
Espacio lógico utilizado (si se han habilitado las opciones de eficiencia del almacenamiento)

|===


== Términos de medición de capacidad

Los siguientes términos se utilizan cuando se describe la capacidad:

* *Disponible*: Cantidad de espacio físico disponible en un nivel local que puede utilizarse para aprovisionar volúmenes.
* *Datos del cliente*: Cantidad de espacio utilizado por los datos del cliente (tanto físicos como lógicos).
* *Comprometido*: La cantidad de capacidad comprometida para un nivel local.
* *Reducción de datos*:
+
** *Total*: La proporción de todo el espacio lógico utilizado comparado con el espacio físico utilizado.
** *Sin copias Snapshot y clones*: La proporción de espacio lógico utilizado sólo por los datos del cliente en comparación con el espacio físico utilizado únicamente por los datos del cliente.


* *Uso lógico*: La cantidad de espacio utilizado sin tener en cuenta el espacio ahorrado por las características de eficiencia del almacenamiento.
* * % Lógico utilizado*: El porcentaje de la capacidad lógica utilizada actual en comparación con el tamaño aprovisionado, excluyendo las reservas Snapshot. Este valor puede ser mayor que el 100%, ya que incluye ahorros de eficiencia en el volumen.
* *Físico utilizado*: La cantidad de capacidad utilizada en los bloques físicos de un volumen o nivel local.
* *Uso físico %*: El porcentaje de capacidad utilizada en los bloques físicos de un volumen en comparación con el tamaño aprovisionado.
* *Reservado*: Cantidad de espacio reservado para volúmenes ya aprovisionados en un nivel local.
* *Usado y reservado*: La suma del espacio físico utilizado y reservado.




== Unidades de medida de capacidad

System Manager calcula la capacidad de almacenamiento en función de unidades binarias de 1024 (2 10) bytes. En ONTAP 9.10.0 y versiones anteriores, estas unidades se mostraron en System Manager como KB, MB, GB, TB y PB. A partir de ONTAP 9.10.1, se muestran en System Manager como KiB, MIB, GIB, TIB y PIB.


NOTE: Las unidades utilizadas en System Manager para el rendimiento siguen siendo KB/s, MB/s, GB/s, TB/s y PB/s en todas las versiones de ONTAP.

[cols="20,20,30,30"]
|===


| Unidad de capacidad mostrada en System Manager para ONTAP 9.10.0 y versiones anteriores | Unidad de capacidad mostrada en System Manager para ONTAP 9.10.1 y versiones posteriores | Cálculo | Valor en bytes 


 a| 
KB
 a| 
KiB
 a| 
1024
 a| 
1024 bytes



 a| 
MB
 a| 
MIB
 a| 
1024 * 1024
 a| 
1,048,576 bytes



 a| 
GB
 a| 
GIB
 a| 
1024 * 1024 * 1024
 a| 
1,073,741,824 bytes



 a| 
TB
 a| 
TIB
 a| 
1024 * 1024 * 1024 * 1024
 a| 
1,099,511,627,776 bytes



 a| 
PB
 a| 
PIB
 a| 
1024 * 1024 * 1024 * 1024 * 1024
 a| 
1,125,898,010,834,824 bytes

|===
.Información adicional:
link:../volumes/logical-space-reporting-enforcement-concept.html["Generación de informes sobre el espacio lógico y cumplimiento para volúmenes"]
