---
permalink: concepts/cloud-backup-support-traditional-backups-concept.html 
sidebar: sidebar 
keywords: cloud backup, support, traditional backups 
summary: Además de las relaciones de protección de datos de SnapMirror y SnapVault, que eran de disco a disco sólo para ONTAP 9,7 y versiones anteriores, ahora hay varias soluciones de backup que ofrecen una alternativa más económica para la retención de datos a largo plazo. 
---
= Backup en el cloud y compatibilidad con backups tradicionales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Además de las relaciones de protección de datos de SnapMirror y SnapVault, que eran de disco a disco sólo para ONTAP 9,7 y versiones anteriores, ahora hay varias soluciones de backup que ofrecen una alternativa más económica para la retención de datos a largo plazo.

Numerosas aplicaciones de protección de datos de terceros ofrecen backup tradicional para datos gestionados con ONTAP. Veeam, Veritas y CommVault, entre otros, ofrecen backup integrado para sistemas ONTAP.

A partir de ONTAP 9,8, el cloud de SnapMirror proporciona replicación asíncrona de snapshots desde instancias de ONTAP a extremos de almacenamiento de objetos. La replicación en el cloud de SnapMirror requiere una aplicación con licencia para la orquestación y la gestión de flujos de trabajo de protección de datos. Las relaciones de cloud de SnapMirror son compatibles con los sistemas ONTAP para seleccionar objetivos de almacenamiento de objetos —como AWS S3, Google Cloud Storage Platform o Microsoft Azure Blob Storage— que proporcionan una mayor eficiencia con el software de backup del proveedor. Póngase en contacto con su representante de NetApp para obtener una lista de aplicaciones certificadas y proveedores de almacenamiento de objetos compatibles.

Si está interesado en la protección de datos nativos del cloud, puede utilizar BlueXP para configurar las relaciones de SnapMirror o SnapVault entre volúmenes de las instalaciones y instancias de Cloud Volumes ONTAP en el cloud público.

BlueXP también ofrece copias de seguridad de instancias de Cloud Volumes ONTAP utilizando un modelo de software como servicio (SaaS). Los usuarios pueden realizar backups de sus instancias de Cloud Volumes ONTAP en un almacenamiento de objetos de cloud público conforme a la normativa S3 y S3 mediante el backup y la recuperación de datos de BlueXP .

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html["Documentación de Cloud Volumes ONTAP"^]

link:https://docs.netapp.com/us-en/bluexp-family/index.html["Documentación de BlueXP"^]

link:https://bluexp.netapp.com/["BlueXP de NetApp"^]
