---
permalink: concepts/cloud-backup-support-traditional-backups-concept.html 
sidebar: sidebar 
keywords: cloud backup, support, traditional backups 
summary: Además de las relaciones de protección de datos de SnapMirror y SnapVault, que antes solo eran de disco a disco, existen varias soluciones de backup que ofrecen una alternativa más económica para la retención de datos a largo plazo. 
---
= Backup en el cloud y compatibilidad con backups tradicionales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Además de las relaciones de protección de datos de SnapMirror y SnapVault, que antes solo eran de disco a disco, existen varias soluciones de backup que ofrecen una alternativa más económica para la retención de datos a largo plazo.

Numerosas aplicaciones de protección de datos de terceros ofrecen backup tradicional para datos gestionados con ONTAP. Veeam, Veritas y CommVault, entre otros, ofrecen backup integrado para sistemas ONTAP.

A partir de ONTAP 9.8, SnapMirror Cloud proporciona la replicación asíncrona de copias Snapshot de instancias de ONTAP a extremos de almacenamiento de objetos. La replicación cloud de SnapMirror requiere una aplicación con licencia para coordinar y gestionar los flujos de trabajo de protección de datos. Las relaciones de SnapMirror Cloud son compatibles con los sistemas de ONTAP para seleccionar objetivos de almacenamiento de objetos en las instalaciones y en el cloud público, incluidos AWS S3, Google Cloud Storage Platform o Microsoft Azure Blob Storage, lo que proporciona una eficiencia mejorada con el software de backup de proveedores. Póngase en contacto con su representante de NetApp para obtener una lista de aplicaciones certificadas y proveedores de almacenamiento de objetos compatibles.

Si está interesado en la protección de datos nativos del cloud, puede utilizar BlueXP para configurar las relaciones de SnapMirror o SnapVault entre volúmenes de las instalaciones y instancias de Cloud Volumes ONTAP en el cloud público.

BlueXP también ofrece copias de seguridad de instancias de Cloud Volumes ONTAP utilizando un modelo de software como servicio (SaaS). Los usuarios pueden realizar backups de sus instancias de Cloud Volumes ONTAP en un almacenamiento de objetos en cloud público compatible con S3 y S3 utilizando Cloud Backup que se encuentra en Cloud Central de NetApp.

https://["Recursos de documentación de Cloud Volumes ONTAP y BlueXP"]

https://["Cloud Central de NetApp"]
