---
permalink: concepts/index.html 
sidebar: sidebar 
keywords: decide, concepts, ontap, overview, data, management, cluster storage, high-availability, virtualization, protection, storage, efficiency, security 
summary: Los siguientes conceptos informan al software de gestión de datos ONTAP, incluido almacenamiento en clúster, alta disponibilidad, virtualización, protección de datos la eficiencia del almacenamiento y la seguridad. 
---
= Descripción general de conceptos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los siguientes conceptos informan al software de gestión de datos ONTAP, incluido almacenamiento en clúster, alta disponibilidad, virtualización, protección de datos la eficiencia del almacenamiento y la seguridad. Debe comprender toda la gama de funciones y ventajas de ONTAP antes de configurar la solución de almacenamiento.

Para obtener información adicional, consulte lo siguiente:

* link:../system-admin/index.html["Administración de clústeres y SVM"]
* link:../high-availability/index.html["Pares de alta disponibilidad"]
* link:../networking/index.html["Gestión de redes y LIF"]
* link:../disks-aggregates/index.html["Gestión de discos y agregados"]
* link:../volumes/index.html["FlexVol Volumes, tecnología FlexClone y funciones de eficiencia del almacenamiento"]
*link:../san-admin/provision-storage.html["Aprovisionamiento de hosts SAN"]
* Acceso a archivos NAS
+
** link:../nfs-admin/index.html["Gestión de NFS"]
** link:../smb-admin/index.html["Gestión de SMB"]


* link:../data-protection/index.html["Recuperación ante desastres y archivado"]

