---
permalink: concepts/insights-system-optimization-concept.html 
sidebar: sidebar 
keywords: system manager, optimize, optimise, optimization, optimisation, insight, cluster, system, analysis, analyze, perform, performing, performance, capacity, local tier, storage tier, telnet, remote shell, rsh, autosupport, auto support, auto-support, insecure protocol, login banner, log in banner, ssh, secure shell, cbc cipher, ntp server, admin user, administrative, user, best practice, practise, fabricpool, fabric pool, physical capacity, aggregate, cloud, snapshot, directories, directory, file, remote access, transport protocol, https, http, autogrow, auto grow, auto-grow, shrink, reduce, reduction, dismiss, undismiss, explore, fix, remove, replace, analytic, security, compliance, secure, comply, volume, applications, reclaim, space, full, provisioning, provisioned cluster, serial, port, node 
summary: Con System Manager, puede ver información que le ayuda a optimizar el rendimiento y la seguridad de su sistema. 
---
= Información de System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
A partir de ONTAP 9.11.1, System Manager muestra _insights_ que le ayudan a optimizar el rendimiento y la seguridad de su sistema.


NOTE: Para ver, personalizar y responder a los datos, consulte link:../insights-system-optimization-task.html["Obtenga información interna para ayudarle a optimizar su sistema"]



== Información de la capacidad

System Manager puede mostrar la siguiente información en respuesta a las condiciones de capacidad de su sistema:

[cols="15,15,20,50"]
|===


| Insight | Gravedad | Condición | Soluciones 


 a| 
El nivel local se está quedando sin capacidad física
 a| 
Solucione los riesgos
 a| 
Uno o más niveles locales están llenos al 95% y crecen rápidamente.
 a| 
*RECOMENDADO*: Realice una de las otras opciones.

*Otras opciones*:

* Borre la cola de recuperación del volumen.
* Habilite thin provisioning en volúmenes de thick provisioning para liberar el almacenamiento atrapado.
* Mueva volúmenes a otro nivel local.
* Elimine las copias Snapshot no necesarias.
* Elimine los directorios o los archivos que no sean necesarios en los volúmenes.
* Habilite Fabric Pool para organizar los datos en niveles en el cloud.




 a| 
La capacidad del volumen de FlexGroup desequilibrada
 a| 
Optimizar el almacenamiento
 a| 
Uno o varios volúmenes FlexGroup tienen una tasa alta de desequilibrio.
 a| 
*Recomendado*: Reequilibre los volúmenes de FlexGroup.



 a| 
La aplicación se está quedando sin espacio
 a| 
Necesita atención
 a| 
Los volúmenes que están llenos a más del 95 % no tienen crecimiento automático habilitado.
 a| 
*Recomendado*: Habilita el crecimiento automático hasta el 150% de la capacidad actual.

*Otras opciones*:

* Reclame espacio eliminando copias Snapshot.
* Cambie el tamaño de los volúmenes.
* Elimine directorios o archivos.


|===


== Información sobre seguridad

System Manager puede mostrar la siguiente información en respuesta a condiciones que podrían poner en peligro la seguridad de sus datos o del sistema.

[cols="15,15,20,50"]
|===


| Insight | Gravedad | Condición | Soluciones 


 a| 
Telnet está activado
 a| 
Mejor práctica
 a| 
Se debe utilizar Secure Shell (SSH) para un acceso remoto seguro.
 a| 
*Recomendado*: Desactiva Telnet y usa SSH para un acceso remoto seguro.



 a| 
Hay muy pocos servidores NTP configurados
 a| 
Mejor práctica
 a| 
El número de servidores configurados para NTP es inferior a 3.
 a| 
*Recomendado*: Agrega servidores NTP para que haya al menos 3.



 a| 
AutoSupport está utilizando un protocolo no seguro
 a| 
Mejor práctica
 a| 
AutoSupport no está configurado para comunicarse a través de HTTPS.
 a| 
*Recomendado*: Cambie el protocolo de transporte a HTTPS.



 a| 
El usuario administrador predeterminado no está bloqueado
 a| 
Mejor práctica
 a| 
Nadie ha iniciado sesión con una cuenta administrativa predeterminada (admin o diag), y estas cuentas no están bloqueadas.
 a| 
*Recomendado*: Bloquea las cuentas administrativas predeterminadas cuando no se estén utilizando.



 a| 
Los volúmenes no tienen políticas de Snapshot
 a| 
Necesita atención
 a| 
No hay una política de Snapshot adecuada anexada a uno o varios volúmenes.
 a| 
*Recomendado*: Adjunte una política de Snapshot a volúmenes que no tengan uno. De lo contrario, puede que, en caso de un ataque de ransomware, no sea posible recuperar datos de estos volúmenes.



 a| 
La eliminación automática de Snapshot está habilitada
 a| 
Necesita atención
 a| 
La eliminación automática de copias de Snapshot está habilitada para uno o varios volúmenes.
 a| 
*Recomendado*: Desactiva la eliminación automática de copias snapshot. De lo contrario, puede que, en caso de un ataque de ransomware, no sea posible recuperar datos de estos volúmenes.



 a| 
No se supervisan los volúmenes de ataques de ransomware
 a| 
Necesita atención
 a| 
Diversos volúmenes son compatibles con el anti-ransomware, pero aún no se ha configurado. De lo contrario, es posible que no note cuándo los volúmenes se están amenazando o bajo ataque.
 a| 
*Recomendado*: Habilitar anti-ransomware en los volúmenes.



 a| 
Las máquinas virtuales de almacenamiento no están configuradas para el ransomware
 a| 
Mejor práctica
 a| 
El anti-ransomware es compatible con diversas máquinas virtuales de almacenamiento, pero aún no se ha configurado.
 a| 
*Recomendado*: Habilitar anti-ransomware en las VM de almacenamiento. De lo contrario, es posible que no se dé cuenta de cuándo las máquinas virtuales de almacenamiento se ven amenazadas o sufren un ataque.



 a| 
FPolicy nativo no configurado
 a| 
Mejor práctica
 a| 
FPolicy no está establecido para máquinas virtuales de almacenamiento NAS.
 a| 
*Recomendado*: Configure FPolicy en VM de almacenamiento NAS para controlar las extensiones de archivo que se permiten o no se permiten escribir en los volúmenes del clúster.



 a| 
El modo activo no está habilitado para Anti-Ransomware
 a| 
Necesita atención
 a| 
Varios volúmenes completaron el modo de aprendizaje, pero el modo activo no está activado.
 a| 
*Recomendado*: Activa el modo activo para esos volúmenes.



 a| 
El banner de inicio de sesión no está configurado
 a| 
Mejor práctica
 a| 
Los mensajes de inicio de sesión no están configurados para el clúster ni para la máquina virtual de almacenamiento.
 a| 
*Recomendado*: Configure el banner de inicio de sesión para el clúster o la VM de almacenamiento y habilite el uso de la misma.



 a| 
Shell remoto (RSH) está activado
 a| 
Mejor práctica
 a| 
Se debe utilizar Secure Shell (SSH) para un acceso remoto seguro.
 a| 
*Recomendado*: Desactiva RSH y usa SSH para un acceso remoto seguro.



 a| 
Secure Shell (SSH) utiliza cifrados no seguros
 a| 
Mejor práctica
 a| 
La configuración actual utiliza cifrados de CBC no seguros.
 a| 
*Recomendado*: Eliminar los cifrados que tengan nombres que contengan “cbc”, como “ais128-cbc”, “AES192-cbc”, “AES256-cbc” y “3DES-cbc”.



 a| 
La FIPS global está desactivada
 a| 
Mejor práctica
 a| 
El cumplimiento de la normativa global FIPS 140-2 está desactivado.
 a| 
*Recomendado*: Habilite el cumplimiento de la norma FIPS 140-2 global.

|===


== Información de configuración

System Manager puede mostrar la siguiente información en respuesta a las dudas acerca de la configuración del sistema.

[cols="15,15,20,50"]
|===


| Insight | Gravedad | Condición | Soluciones 


 a| 
La actualización automática no está activada.
 a| 
Mejor práctica
 a| 
El CLUF no se ha aceptado para el clúster.
 a| 
*Recomendado*: Acepta el EULA para el clúster.



 a| 
La última actualización del firmware está disponible
 a| 
Mejor práctica
 a| 
Su sistema no dispone de la última actualización del firmware, lo que podría tener mejoras, parches de seguridad o nuevas funciones que ayuden a proteger el clúster para lograr un mejor rendimiento.
 a| 
*Recomendado*: Actualizar el firmware de ONTAP.



 a| 
Las notificaciones no están configuradas
 a| 
Mejor práctica
 a| 
Correo electrónico, WebHooks o el host de capturas de SNMP no está configurado para permitirle recibir notificaciones acerca de problemas con el clúster.
 a| 
*Recomendado*: Configurar notificaciones para el cluster.

|===