---
permalink: concepts/manual-pages.html 
sidebar: sidebar 
keywords: CLI commands, manual pages, volume create, volume modify, volume show, volume move, snapmirror show, snapmirror create, vserver create, network interface show, storage disk show, volume delete, man pages, cli comparison tool, cli diff 
summary: Las páginas manuales de ONTAP explican cómo usar los comandos de la CLI de ONTAP. Busque la referencia de comandos para la versión de ONTAP que está usando. 
---
= Referencia de comandos del ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para cada versión principal de ONTAP, se incluyen en link:https://docs.netapp.com/us-en/ontap-cli/["Referencia de comandos de la ONTAP"^]los comandos CLI más comunes (páginas del manual de ONTAP o páginas man). Estas referencias de comandos explican cómo utilizar los comandos CLI en cada versión de ONTAP

Las páginas man también están disponibles en la línea de comandos de ONTAP con el  `man` dominio. Obtenga más información sobre  `man` en el link:https://docs.netapp.com/us-en/ontap-cli/man.html["Referencia de comandos del ONTAP"^] .



== Referencias de comandos para versiones de soporte limitadas de ONTAP (solo PDF)

* link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2843631["ONTAP 9,4"^]




== Herramienta de comparación de CLI

Puede obtener información sobre los cambios en los comandos de la interfaz de línea de comandos (CLI) entre versiones de ONTAP mediante el link:https://mysupport.netapp.com/site/info/cli-comparison["Herramienta de comparación de CLI"^] en el sitio de soporte de NetApp.

.Información relacionada
* xref:../system-admin/command-line-interface-concept.html[Use la interfaz de línea de comandos de ONTAP]
* xref:../system-admin/methods-navigating-cli-command-directories-concept.html[Métodos para navegar por los directorios de comandos de la CLI]

