---
permalink: concepts/manual-pages.html 
sidebar: sidebar 
keywords: CLI commands, manual pages, volume create, volume modify, volume show, volume move, snapmirror show, snapmirror create, vserver create, network interface show, storage disk show, volume delete, man pages, cli comparison tool, cli diff 
summary: Las páginas manuales de ONTAP explican cómo usar los comandos de la CLI de ONTAP. Busque la referencia de comandos para la versión de ONTAP que está usando. 
---
= Referencia de comandos de la ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para cada versión principal de ONTAP, los comandos CLI disponibles con más frecuencia (páginas manuales de ONTAP o páginas de manual) se combinan en un _Command reference_. Estas referencias de comandos explican cómo utilizar los comandos de la CLI en cada versión de ONTAP. Las páginas de manual también están disponibles en la línea de comandos de la ONTAP con `man` el comando. Obtenga más información sobre `man` en el link:https://docs.netapp.com/us-en/ontap-cli/man.html["Referencia de comandos de la ONTAP"^].



== Referencias de comandos para versiones compatibles de ONTAP

* link:https://docs.netapp.com/us-en/ontap-cli/index.html["ONTAP 9.16.1"^]
* link:https://docs.netapp.com/us-en/ontap-cli-9151/index.html["ONTAP 9.15.1"^]
* link:https://docs.netapp.com/us-en/ontap-cli-9141/index.html["ONTAP 9.14.1"^]
* link:https://docs.netapp.com/us-en/ontap-cli-9131/index.html["ONTAP 9.13.1"^]
* link:https://docs.netapp.com/us-en/ontap-cli-9121/index.html["ONTAP 9.12.1"^]
* link:https://docs.netapp.com/us-en/ontap-cli-9111/index.html["ONTAP 9.11.1"^]
* link:https://docs.netapp.com/us-en/ontap-cli-9101/index.html["ONTAP 9.10.1"^]
* link:https://docs.netapp.com/us-en/ontap-cli-991/index.html["ONTAP 9.9.1"^]
* link:https://docs.netapp.com/us-en/ontap-cli-98/index.html["ONTAP 9,8"^]
* link:https://docs.netapp.com/us-en/ontap-cli-97/index.html["ONTAP 9,7"^]
* link:https://docs.netapp.com/us-en/ontap-cli-96/index.html["ONTAP 9,6"^]
* link:https://docs.netapp.com/us-en/ontap-cli-95/index.html["ONTAP 9,5"^]
* link:https://docs.netapp.com/us-en/ontap-cli-93/index.html["ONTAP 9,3"^]




== Referencias de comandos para versiones de soporte limitadas de ONTAP (solo PDF)

* link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2843631["ONTAP 9,4"^]




== Herramienta de comparación de CLI

Puede aprender acerca de los cambios en los comandos de la interfaz de línea de comandos (CLI) entre las versiones de ONTAP mediante la link:https://mysupport.netapp.com/site/info/cli-comparison["Herramienta de comparación de CLI"^] En el sitio de soporte de NetApp.

.Información relacionada
* xref:../system-admin/command-line-interface-concept.html[Use la interfaz de línea de comandos de ONTAP]
* xref:../system-admin/methods-navigating-cli-command-directories-concept.html[Métodos para navegar por los directorios de comandos de la CLI]

