---
permalink: concepts/rdma-concept.html 
sidebar: sidebar 
keywords: Remote Direct Memory Access, NFS over RDMA, RoCE, intercluster 
summary: 'La oferta de acceso directo a memoria remota (RDMA) de ONTAP admite cargas de trabajo sensibles a la latencia y de ancho de banda elevado. RDMA permite copiar los datos directamente entre la memoria del sistema de almacenamiento y la memoria del sistema host, evitando así las interrupciones de la CPU y la sobrecarga' 
---
= Descripción general de RDMA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La oferta de acceso directo a memoria remota (RDMA) de ONTAP admite cargas de trabajo sensibles a la latencia y de ancho de banda elevado. RDMA permite que los datos se copien directamente entre la memoria del sistema de almacenamiento y la memoria del sistema host, evitando así las interrupciones y gastos generales de la CPU.



== NFS sobre RDMA

A partir de ONTAP 9.10,1, puede configurar link:../nfs-rdma/index.html["NFS sobre RDMA"] para habilitar el uso del almacenamiento GPUDirect de NVIDIA para cargas de trabajo aceleradas por GPU en hosts con GPU de NVIDIA compatibles.


NOTE: RDMA no es compatible con el protocolo SMB.



== RDMA de interconexión en clúster

Cluster Interconnect RDMA reduce la latencia, reduce los tiempos de conmutación por error y acelera la comunicación entre nodos de un clúster.

A partir de ONTAP 9.10.1, la tecnología RDMA de interconexión de clústeres es compatible con algunos sistemas de hardware cuando se utilizan con NIC de clúster de X1151A. A partir de ONTAP 9.13.1, las NIC de X91153A también admiten RDMA de interconexión de clústeres. Consulte la tabla para saber qué sistemas son compatibles con las distintas versiones de ONTAP.

|===
| Sistemas | Versiones de ONTAP compatibles 


 a| 
* AFF A50
* AFF A30
* AFF A20
* AFF C80
* AFF C60
* AFF C30
* ASA A50
* ASA A30
* ASA A20

| ONTAP 9.16.1 y versiones posteriores 


 a| 
* AFF A1K
* AFF A90
* AFF A70
* ASA A1K
* ASA A90
* ASA A70
* FAS90
* FAS70

| ONTAP 9.15.1 y versiones posteriores 


 a| 
* AFF A900
* ASA A900
* FAS9500

| ONTAP 9.13.1 y versiones posteriores 


 a| 
* AFF A400
* ASA A400

| ONTAP 9.10.1 y versiones posteriores 
|===
Dada la configuración del sistema de almacenamiento adecuada, no se necesita configuración adicional para utilizar RDMA de Cluster Interconnect.
