---
permalink: concepts/rdma-concept.html 
sidebar: sidebar 
keywords: Remote Direct Memory Access, NFS over RDMA, RoCE, intercluster 
summary: La interconexión de clústeres de NFS sobre RDMA y RDMA utilizan RDMA para mejorar el rendimiento en cargas de trabajo de ancho de banda elevado. 
---
= Información general de RDMA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si tiene cargas de trabajo sensibles a la latencia o con un ancho de banda elevado, es posible que desee aprovechar las ofertas de acceso a memoria directa de lectura (RDMA) de ONTAP. RDMA permite que los datos se copien directamente entre la memoria del sistema de almacenamiento y la memoria del sistema host, evitando así las interrupciones y gastos generales de la CPU.



== NFS sobre RDMA

A partir de ONTAP 9.10.1, es posible configurar link:../nfs-rdma/index.html["NFS sobre RDMA"] Permitir el uso de NVIDIA GPUDirect Storage para cargas de trabajo aceleradas por GPU en hosts con GPU de NVIDIA compatibles.



== Interconexión de clústeres RDMA

A partir de ONTAP 9.10.1, ONTAP admite la interconexión de clústeres RDMA para usuarios de ONTAP con un sistema de almacenamiento A400 o ASA400 con NIC de clúster Pensando. La interconexión de clústeres RDMA reduce la latencia, reduce los tiempos de conmutación al nodo de respaldo y acelera la comunicación entre los nodos de un clúster. Dada la configuración adecuada del sistema de almacenamiento, no se necesita ninguna configuración adicional.
