---
permalink: concepts/storage-efficiency-overview.html 
sidebar: sidebar 
keywords: storage efficiency, storage efficiencies, storage efficiency technologies, space utilization, space savings, optimizing, space optimization, minimizing, wasted space, reducing, footprint, thin provisioning, deduplication, zero block, zero-block, inline, deduplication, background deduplication, postprocessing, post-processing, compression, compaction, flex-clone technologies 
summary: La eficiencia de almacenamiento mide qué eficacia utiliza un sistema de almacenamiento el espacio disponible al optimizar los recursos de almacenamiento, minimizar el espacio desperdiciado y reducir el espacio físico escrito de los datos. 
---
= Información general de la eficiencia del almacenamiento de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La eficiencia de almacenamiento mide qué eficacia utiliza un sistema de almacenamiento el espacio disponible al optimizar los recursos de almacenamiento, minimizar el espacio desperdiciado y reducir el espacio físico escrito de los datos. Una mayor eficacia de almacenamiento le permite almacenar la cantidad máxima de datos en el menor espacio posible y al menor coste posible. Por ejemplo, el uso de tecnologías de eficiencia del almacenamiento que detectan y eliminan los bloques de datos duplicados y los bloques de datos llenos de ceros reduce la cantidad general de almacenamiento físico que necesita y reduce el coste general.

ONTAP ofrece una amplia gama de tecnologías de eficiencia del almacenamiento que reducen la cantidad de almacenamiento en cloud o hardware físico que consumen sus datos y también producen importantes mejoras en el rendimiento del sistema, como lecturas más rápidas de datos, copias más rápidas de conjuntos de datos y un aprovisionamiento más rápido de máquinas virtuales.

.Las tecnologías de eficiencia de almacenamiento de ONTAP incluyen:
* *Thin Provisioning*
+
xref:thin-provisioning-concept.html[Aprovisionamiento ligero] Permite asignar almacenamiento en un volumen o LUN a medida que es necesario, en lugar de reservar con antelación. Esto reduce la cantidad de almacenamiento físico que necesita al permitirle sobreasignar sus volúmenes o LUN en función del uso potencial sin reservar espacio que no se esté utilizando actualmente.

* *Deduplicación*
+
xref:deduplication-concept.html[Deduplicación] reduce la cantidad de almacenamiento físico necesario para un volumen de tres maneras distintas.

+
** *Deduplicación de bloques cero*
+
La deduplicación de bloque cero detecta y elimina los bloques de datos llenos con todos los ceros y solo actualiza los metadatos. se ahorra entonces un 100% del espacio utilizado por bloques cero. La deduplicación de bloque cero está habilitada de forma predeterminada en todos los volúmenes deduplicados.

** *Desduplicación en línea*
+
La deduplicación inline detecta los bloques de datos duplicados y los reemplaza con referencias a un bloque compartido único antes de escribir los datos en el disco. La deduplicación en línea acelera el aprovisionamiento de las máquinas virtuales entre un 20 % y un 30 %. En función de su versión de ONTAP y de su plataforma, la deduplicación inline está disponible en el nivel del volumen o el agregado. Está activado de forma predeterminada en los sistemas AFF y ASA. Debe habilitar la deduplicación inline manualmente en sistemas FAS.

** *Deduplicación de fondo*
+
La deduplicación en segundo plano también detecta los bloques de datos duplicados y los sustituye con referencias a un bloque compartido único, pero mejora aún más la eficiencia del almacenamiento, ya que lo hace después de escribir los datos en el disco. Puede configurar la deduplicación en segundo plano para que se ejecute cuando se cumplan determinados criterios en el sistema de almacenamiento. Por ejemplo, puede activar la deduplicación en segundo plano cuando el volumen alcanza un 10% de utilización. También puede activar manualmente la deduplicación en segundo plano o configurarla para que se ejecute en una programación específica. Está activado de forma predeterminada en los sistemas AFF y ASA. Debe habilitar manualmente la deduplicación en segundo plano en sistemas FAS.



+
Es compatible con la deduplicación en volúmenes y entre volúmenes dentro de un agregado. Las lecturas de datos deduplicados normalmente no conllevan cargos por el rendimiento.

* *Compresión*
+
xref:compression-concept.html[Compresión] reduce la cantidad de almacenamiento físico necesario para un volumen combinando bloques de datos en grupos de compresión, cada uno de los cuales se almacena como un único bloque. Cuando se recibe una solicitud de lectura o sobrescritura, sólo se lee un pequeño grupo de bloques, no el archivo completo. Este proceso optimiza el rendimiento de lectura y sobrescritura y permite una mayor escalabilidad del tamaño de los archivos que se van a comprimir.

+
La compresión se puede ejecutar online o postprocesamiento. La compresión en línea proporciona un ahorro de espacio inmediato al comprimir los datos de la memoria antes de escribirse en el disco. La compresión de postprocesamiento escribe en primer lugar los bloques en el disco sin comprimir y a continuación comprime los datos en un momento programado. Está activado de forma predeterminada en los sistemas AFA. Debe activar manualmente la compresión en todos los demás sistemas.

* *Compacción*
+
La compactación reduce la cantidad de almacenamiento físico necesario para un volumen, tomando fragmentos de datos almacenados en bloques de 4 KB, pero con un tamaño inferior a 4 KB y combinándolos en un único bloque. La compactación se produce mientras los datos siguen en la memoria, por lo que nunca se consume espacio innecesario en los discos. Está activado de forma predeterminada en los sistemas AFF y ASA. Debe habilitar la compactación manualmente en sistemas FAS.

* *Volúmenes FlexClone, archivos y LUN*
+
xref:flexclone-volumes-files-luns-concept.html[Tecnología FlexClone] Aprovecha los metadatos de las copias Snapshot para crear copias editables y puntuales de un volumen, archivo o LUN. Las copias comparten bloques de datos con sus principales, no consumen almacenamiento salvo lo necesario para los metadatos hasta que se escriban cambios en una copia o en su principal. Cuando se escribe un cambio, solo se almacena el delta.

+
Mientras que las copias de conjuntos de datos tradicionales pueden tardar en crearse en minutos o incluso horas, la tecnología FlexClone permite copiar incluso los conjuntos de datos más grandes casi al instante.

* * Eficiencia de almacenamiento sensible a la temperatura*
+
ONTAP ofrece link:../volumes/enable-temperature-sensitive-efficiency-concept.html["eficiencia del almacenamiento sensible a la temperatura"] beneficios al evaluar la frecuencia con la que se accede a los datos de su volumen y asignar esa frecuencia al grado de compresión aplicado a esos datos. En el caso de los datos fríos a los que se accede con poca frecuencia, se comprimen los bloques de datos más grandes. En el caso de los datos activos a los que se accede con frecuencia y que se sobrescriben con mayor frecuencia, se comprimen bloques de datos más pequeños, lo que hace que el proceso sea más eficiente.

+
La eficiencia del almacenamiento sensible a la temperatura (TSSE), presentada en ONTAP 9,8, se activa automáticamente en los volúmenes AFF con Thin Provisioning recién creados. No está activado en link:builtin-storage-efficiency-concept.html["Plataformas AFF A70, AFF A90 y AFF A1K"] los que se introducen en ONTAP 9.15.1, que utilizan un procesador de descarga de hardware.

* * Eficiencia de almacenamiento de CPU o procesador de descarga dedicado*
+
A partir de ONTAP 9.15.1,link:builtin-storage-efficiency-concept.html["Eficiencia del almacenamiento de CPU o procesador de descarga dedicado"] Se habilita automáticamente en ciertas plataformas AFF y FAS y no requiere configuración.  Estas plataformas no utilizan eficiencia de almacenamiento sensible a la temperatura.  La compresión comienza sin esperar a que los datos se enfríen y se realiza utilizando la CPU principal o un procesador de descarga dedicado.  Estas plataformas también utilizan el empaquetado secuencial de bloques físicos contiguos para mejorar aún más la eficiencia del almacenamiento de datos comprimidos.



Puede obtener el beneficio de estas tecnologías en sus operaciones diarias con el mínimo esfuerzo. Por ejemplo, suponga que necesita proporcionar a 5.000 usuarios almacenamiento para directorios iniciales y estima que el espacio máximo necesario para cualquier usuario es de 1 GB. Puede reservar un agregado de 5 TB por adelantado para satisfacer la necesidad total de almacenamiento potencial. Sin embargo, también sabe que los requisitos de capacidad del directorio inicial varían considerablemente en cada organización. En lugar de reservar 5 TB de espacio total para su organización, puede crear un agregado de 2 TB. Luego, puede utilizar thin provisioning para asignar nominalmente 1 GB de almacenamiento a cada usuario, pero para asignar el almacenamiento únicamente según sea necesario. Puede supervisar de forma activa el agregado a lo largo del tiempo y aumentar el tamaño físico real según sea necesario.

En otro ejemplo, supongamos que utiliza una infraestructura de puestos de trabajo virtuales (VDI) con una gran cantidad de datos duplicados en sus escritorios virtuales. La deduplicación reduce el uso del almacenamiento eliminando automáticamente los bloques de información duplicados en la infraestructura de puestos de trabajo virtuales y sustituyéndolos por un puntero al bloque original. Otras tecnologías de eficiencia del almacenamiento de ONTAP, como la compresión, también pueden ejecutarse en segundo plano sin su intervención.

La tecnología de creación de particiones de disco de ONTAP también permite una mayor eficiencia del almacenamiento. La tecnología de RAID DP ofrece protección frente a un fallo de dos discos sin sacrificar el rendimiento ni incrementar los gastos generales de mirroring de discos. La creación de particiones SSD avanzada con ONTAP 9 aumenta la capacidad de uso en casi un 20 %.

NetApp proporciona las mismas funciones de eficiencia de almacenamiento que hay disponibles con ONTAP en las instalaciones en el cloud. Cuando migra datos desde el almacenamiento ONTAP on-premises a la nube, se conserva la eficiencia del almacenamiento existente. Por ejemplo, suponga que tiene una base de datos de SQL que contiene datos críticos para el negocio que desea pasar de un sistema local al cloud. Puede utilizar la replicación de datos en BlueXP  para migrar sus datos y, como parte del proceso de migración, puede habilitar la última política de Snapshot en las instalaciones en el cloud.
