---
sidebar: sidebar 
permalink: concepts/sysmgr-integration-console-concept.html 
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, netapp console, console, hybrid, cloud, dashboard, multicloud 
summary: Puede administrar ONTAP 9.10.1 y versiones posteriores mediante el Administrador del sistema en la consola de NetApp .  Esta integración le permite supervisar de manera eficiente su infraestructura híbrida multicloud mediante un plano de control unificado, al mismo tiempo que conserva la interfaz de usuario familiar de System Manager. 
---
= Integrar ONTAP System Manager con la consola de NetApp
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede administrar ONTAP 9.10.1 y versiones posteriores mediante el Administrador del sistema en la consola de NetApp .  Esta integración le permite supervisar de manera eficiente su infraestructura híbrida multicloud mediante un plano de control unificado, al mismo tiempo que conserva la interfaz de usuario familiar de System Manager.

La consola le permite crear y administrar almacenamiento en la nube (por ejemplo, Cloud Volumes ONTAP), utilizar servicios de datos de NetApp (por ejemplo, Cloud Backup) y controlar muchos dispositivos de almacenamiento locales y de borde.

La consola ofrece dos formas de descubrir y administrar sus clústeres:

* Descubrimiento directo para administración a través del Administrador del sistema (ONTAP 9.12.1 y posteriores)
* Descubrimiento a través de un agente de consola.


El agente de consola es un software instalado en su entorno.  Esto le permite acceder a funciones de administración a través de System Manager y acceder a los servicios en la nube de NetApp que brindan características como replicación de datos, respaldo y recuperación, clasificación de datos, niveles de datos y más.

Obtenga más información sobre link:https://docs.netapp.com/us-en/storage-management-ontap-onprem/index.html["Gestión de clústeres ONTAP locales mediante la consola de NetApp"^] .

.Pasos
. Inicie sesión en la consola de NetApp .
+
.. Si tiene un inicio de sesión de consola, úselo.
.. Si es su primera vez, seleccione Iniciar sesión con sus credenciales del sitio de soporte de NetApp e ingrese sus credenciales en la página de inicio de sesión de la consola.


. Descubra su clúster local en la consola mediante un agente de consola o descubrimiento directo. Obtenga más información sobre el enlace: https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html [descubrimiento de clústeres ONTAP locales^].
+
.. Aprenda a... link:https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-manage-ontap-direct.html["Administrar clústeres que se descubrieron directamente"^] .
.. Aprenda a... link:https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-manage-ontap-connector.html["Administrar clústeres que se descubrieron con un agente de consola"^] .


. Administre su clúster local mediante el Administrador del sistema.  En la página Sistemas de Mis entornos de trabajo, seleccione el clúster y haga clic en Administrador del sistema en la lista Servicios.
+
.. Obtenga más información sobre link:https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-manage-ontap-direct.html["gestión de clústeres que se descubrieron directamente"^] .
.. Aprenda a... link:https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-manage-ontap-connector.html["Administrar clústeres que se descubrieron con un agente de consola"^] .






== Consola de NetApp y ONTAP 9.12.1

Nota: Si está utilizando ONTAP 9.12.1, aparecerá un mensaje que le solicitará que pruebe la consola de NetApp .

+ Si el clúster tiene conectividad con la consola de NetApp , se muestra un mensaje de solicitud de inicio de sesión.

. Haga clic en *Continuar a la consola de NetApp * para seguir el enlace a la consola.
+

NOTE: Si la configuración de su sistema ha bloqueado redes externas, no podrá acceder a la Consola.  Para acceder a System Manager mediante la consola, debe asegurarse de que su sistema pueda acceder a la dirección "`cloudmanager.cloud.netapp.com`".  De lo contrario, cuando se le solicite, puede elegir utilizar la versión de System Manager que está instalada con su sistema ONTAP .

. En la página de inicio de sesión de la consola, seleccione *Iniciar sesión con sus credenciales del sitio de soporte de NetApp * e ingrese sus credenciales.
+
Si ya ha utilizado la consola y tiene un inicio de sesión con correo electrónico y contraseña, deberá continuar usando esa opción de inicio de sesión.

+
https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["Obtenga más información sobre cómo iniciar sesión en la consola de NetApp"^] .

. Si se le solicita, ingrese un nombre para su nueva cuenta de consola de NetApp .
+
En la mayoría de los casos, la consola crea automáticamente una cuenta para usted en función de los datos de su clúster.

. Introduzca las credenciales de administrador del clúster para el clúster.


.Resultado
Se mostrará el Administrador del sistema y ahora podrá administrar el clúster desde la Consola.



== Obtenga más información sobre la consola de NetApp

* https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["Descripción general de la consola de NetApp"^]
* https://docs.netapp.com/us-en/storage-management-ontap-onprem/index.html["Administre sus sistemas NetApp AFF y FAS a través de la consola NetApp"^]

