---
permalink: nfs-rdma/configure-nfs-task.html 
sidebar: sidebar 
keywords: networking, NFS over RDMA, NVIDIA, NFS, v4 grace period 
summary: En este artículo se explica un paso opcional para optimizar el rendimiento de NFS en comparación con RDMA. 
---
= Modifique la configuración NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En la mayoría de los casos, no es necesario modificar la configuración de máquina virtual de almacenamiento con NFS habilitado para NFS sobre RDMA.

Sin embargo, si tiene que enfrentarse a problemas relacionados con chips Mellanox y la migración de LIF, debe aumentar el período de gracia de bloqueo de NFSv4. De forma predeterminada, el período de gracia se establece en 45 segundos. A partir de ONTAP 9.10.1, el período de gracia tiene un valor máximo de 180 (segundos).

.Pasos
. Configure el nivel de privilegio en Advanced:
+
`set -privilege advanced`

. Introduzca el siguiente comando:
+
`vserver nfs modify -vserver _SVM_name_ -v4-grace-seconds _number_of_seconds_`



Para obtener más información sobre esta tarea, consulte xref:../nfs-admin/specify-nfsv4-locking-grace-period-task.adoc[Especifique el período de gracia de bloqueo de NFSv4 para las SVM de ONTAP].
