---
permalink: nfs-rdma/configure-nics-task.html 
sidebar: sidebar 
keywords: networking, NICs, NFS over RDMA, NVIDIA, NFS, system manager, ports, ethernet ports 
summary: En este artículo se explica cómo los procesos y los requisitos de la configuración del sistema cliente y de la plataforma de almacenamiento para que las NIC usen NFS sobre RDMA en ONTAP. 
---
= Configure las NIC para NFS a través de RDMA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS a través de RDMA requiere la configuración de NIC tanto para el sistema cliente como para la plataforma de almacenamiento.



== Configuración de la plataforma de almacenamiento

Para obtener información sobre el soporte RNIC de destino, consulte la https://hwu.netapp.com/["NetApp Hardware Universe"^].

Si se utiliza una configuración de alta disponibilidad (HA), ambos nodos deben usar la misma RNIC para admitir conmutación al nodo de respaldo RDMA. La NIC debe ser compatible con RoCE.

* A partir de ONTAP 9.10.1, es posible ver una lista de protocolos de descarga RDMA con el comando:
+
[source, cli]
----
network port show -rdma-protocols roce
----
+
Obtenga más información sobre `network port show` en el link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["Referencia de comandos del ONTAP"^].

* A partir de ONTAP 9.16.1, se recomienda utilizar el control de flujo de prioridad (PFC). Configure PFC con `network port modify` el comando:
+
[source, cli]
----
network port modify -node <nodename> -port <portname> -flowcontrol-admin pfc -pfc-queues-admin 3
----
* Antes de ONTAP 9.16.1, se recomienda utilizar el control de flujo global (GFC) predeterminado. Si se ha cambiado el ajuste de control de flujo, configure GFC con el `network port modify` comando:
+
[source, cli]
----
network port modify -node <nodename> -port <portname> -flowcontrol-admin full
----
+
Obtenga más información sobre `network port modify` en el link:https://docs.netapp.com/us-en/ontap-cli/network-port-modify.html["Referencia de comandos del ONTAP"^].





== Configuración del sistema cliente

Para obtener información sobre los sistemas operativos cliente compatibles para NFS a través de RDMA, consulte https://imt.netapp.com/matrix/["Matriz de interoperabilidad de NetApp (IMT)"^] el . Para obtener información sobre las RNIC compatibles con RoCE v2, consulte la documentación del proveedor de RNIC correspondiente.

Aunque el cliente y el servidor pueden conectarse directamente, se recomienda el uso de switches para mejorar el rendimiento de la conmutación por error.

El cliente, el servidor, los switches y todos los puertos de los switches deben configurarse con tramas gigantes. La configuración de control de flujo en los clientes y switches debe coincidir con la configuración de control de flujo de ONTAP. A partir de ONTAP 9.16.1, se recomienda habilitar y configurar el control de flujo de prioridad en ONTAP, los switches y los clientes. Antes de ONTAP 9.16.1, se recomienda utilizar el control de flujo global.

Después de confirmar esta configuración, puede montar la exportación NFS con RDMA.

[role="tabbed-block"]
====
.System Manager
--
Debe utilizar ONTAP 9.12.1 o una versión posterior para configurar interfaces de red con NFS a través de RDMA mediante System Manager.

.Pasos
. Compruebe si es compatible con RDMA. Vaya a *Red > puertos Ethernet* y seleccione el nodo apropiado en la vista de grupo. Al expandir el nodo, observe el campo *Protocolos RDMA* para un puerto determinado: El valor *RoCE* indica que RDMA es compatible; un guión (*-*) indica que no es compatible.
. Para agregar una VLAN, seleccione *+ VLAN*. Seleccione el nodo que corresponda. En el menú desplegable *Puerto*, los puertos disponibles muestran el texto *RoCE habilitado* si son compatibles con RDMA. No se muestra texto si no admiten RDMA.
. Siga el flujo de trabajo en xref:../task_nas_enable_linux_nfs.html[Almacenamiento NAS para servidores Linux mediante NFS] para configurar un nuevo servidor NFS.
+
Al agregar interfaces de red, tendrá la opción de seleccionar *utilizar puertos roce*. Seleccione esta opción para las interfaces de red que desee utilizar NFS a través de RDMA.



--
.CLI
--
. Compruebe si el acceso RDMA está habilitado en el servidor NFS con el comando:
+
`vserver nfs show-vserver <SVM_name>`

+
De forma predeterminada, `-rdma` debe estar activado. Si no lo está, habilite el acceso RDMA en el servidor NFS:

+
`vserver nfs modify -vserver <SVM_name> -rdma enabled`

. Monte el cliente a través de NFSv4.0 por RDMA:
+
.. La entrada del parámetro proto depende de la versión del protocolo IP del servidor. Si es IPv4, utilice `proto=rdma`. Si es IPv6, utilice `proto=rdma6`.
.. Especifique el puerto de destino NFS como `port=20049` en lugar del puerto estándar 2049:
+
`mount -o vers=4,minorversion=0,proto=rdma,port=20049 <Server_IP_address>:/<volume_path> <mount_point>`



. *OPCIONAL*: Si necesita desmontar el cliente, ejecute el comando `unmount <mount_path>`


--
====
.Más información
* xref:../nfs-config/create-server-task.html[Cree un servidor NFS]
* xref:../task_nas_enable_linux_nfs.html[Almacenamiento NAS para servidores Linux mediante NFS]

