---
permalink: nfs-rdma/index.html 
sidebar: sidebar 
keywords: NFS over RDMA, GPU, NVIDIA GDX 
summary: NFS a través de RDMA utiliza adaptadores con capacidad RDMA, lo que permite copiar datos directamente entre el almacenamiento y la memoria del sistema host sin interrupciones de la CPU ni gastos generales. 
---
= Obtenga información sobre NFS sobre RDMA en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS a través de RDMA utiliza adaptadores de red compatibles con RDMA, lo que permite copiar los datos directamente entre la memoria del sistema de almacenamiento y la memoria del sistema host, evitando así las interrupciones y los gastos generales de la CPU.

Las configuraciones de NFS sobre RDMA están diseñadas para clientes con cargas de trabajo sensibles a la latencia o de gran ancho de banda, como el aprendizaje automático y el análisis. NFS de ONTAP sobre RDMA puede utilizarse para cualquier carga de trabajo basada en NFS. Además, NVIDIA ha ampliado NFS a RDMA para permitir el almacenamiento directo GPU (GDS). GDS acelera aún más las cargas de trabajo habilitadas para GPU al omitir completamente la CPU y la memoria principal, mediante RDMA, que transfiere datos entre el sistema de almacenamiento y la memoria de la GPU directamente.

A partir de ONTAP 9.10.1, las configuraciones de NFS over RDMA son compatibles con el protocolo NFSv4,0. Las versiones posteriores de ONTAP introdujeron compatibilidad con versiones adicionales de NFS.

.Requisitos
* Asegúrese de ejecutar la versión correcta de ONTAP para la versión de NFS que desea utilizar.
+
[cols="2"]
|===
| Versión de NFS | Soporte de ONTAP 


| NFSv4,0 | ONTAP 9.10.1 y posteriores 


| NFSv4,1 | ONTAP 9.14.1 y versiones posteriores 


| NFSv3 | ONTAP 9.15.1 y versiones posteriores 
|===
+
** Es posible configurar NFS a través de RDMA con System Manager que empieza con ONTAP 9.12.1. En ONTAP 9.10.1 y 9.11.1, tiene que utilizar la CLI para configurar NFS sobre RDMA.


* Los dos nodos de la pareja de alta disponibilidad deben tener la misma versión.
* Las controladoras de los sistemas de almacenamiento deben admitir RDMA:
+
[cols="2"]
|===
| Iniciando con ONTAP... | Las siguientes controladoras admiten RDMA... 


| 9.10.1 y posterior  a| 
** AFF A400
** AFF A700
** AFF A800




| ONTAP 9.14.1 y versiones posteriores  a| 
** AFF C-Series
** AFF A900




| ONTAP 9.15.1 y versiones posteriores  a| 
** AFF A1K
** AFF A90
** AFF A70




| ONTAP 9.16.1 y versiones posteriores  a| 
** AFF A50
** AFF A30
** AFF A20


|===
* Deben configurarse los LIF de datos para que sean compatibles con RDMA.
* Para obtener información sobre el soporte RNIC de destino, consulte la https://hwu.netapp.com/["Hardware Universe de NetApp"^].
* Para obtener información sobre los sistemas operativos cliente compatibles para NFS a través de RDMA, consulte https://imt.netapp.com/matrix/["Matriz de interoperabilidad de NetApp (IMT)"^] el . Para obtener información sobre las RNIC compatibles con RoCE v2, consulte la documentación del proveedor de RNIC correspondiente.



NOTE: Los grupos de interfaces no son compatibles con NFS sobre RDMA.

.Siguientes pasos
* xref:./configure-nics-task.adoc[Configure las NIC para NFS a través de RDMA]
* xref:./configure-lifs-task.adoc[Configure LIF para NFS a través de RDMA]
* xref:./configure-nfs-task.adoc[Configuración de NFS para NFS sobre RDMA]


.Información relacionada
* link:../concepts/rdma-concept.html["RDMA"]
* xref:../nfs-trunking/index.html[Descripción general de trunking NFS]
* https://datatracker.ietf.org/doc/html/rfc7530["RFC 7530: Protocolo NFS versión 4"^]
* https://datatracker.ietf.org/doc/html/rfc8166["RFC 8166: Transporte de acceso directo a memoria remota para llamada de procedimiento remoto versión 1"^]
* https://datatracker.ietf.org/doc/html/rfc8167["RFC 8167: Llamada de procedimiento remoto bidireccional en transpuertos RPC a través de RDMA"^]
* https://datatracker.ietf.org/doc/html/rfc8267["RFC 8267: Enlace de capa superior de NFS a RPC-over-RDMA versión 1"^]

