---
permalink: error-messages/configure-snmp-traphosts-event-notifications-task.html 
sidebar: sidebar 
keywords: configuring, snmp, traphosts, receive, event notifications 
summary: Para recibir notificaciones de eventos en un host de capturas de SNMP, debe configurar un host de capturas. 
---
= Configure los hosts de capturas de SNMP para recibir notificaciones de eventos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para recibir notificaciones de eventos en un host de capturas de SNMP, debe configurar un host de capturas.

.Antes de empezar
* Se debe habilitar SNMP y las capturas de SNMP en el clúster.
+
[NOTE]
====
SNMP y las capturas de SNMP se habilitan de forma predeterminada.

====
* El DNS debe haberse configurado en el clúster para resolver los nombres de host de capturas.


.Acerca de esta tarea
Si no tiene un host de capturas de SNMP configurado para recibir notificaciones de eventos (capturas de SNMP), debe añadir uno.

Puede realizar esta tarea en cualquier momento que el clúster esté en ejecución. Para ello, introduzca los comandos en la línea de comandos de ONTAP.

.Paso
. Si su entorno no tiene un host de capturas de SNMP configurado para recibir notificaciones de eventos, añada uno:
+
`system snmp traphost add -peer-address _snmp_traphost_name_`

+
Todas las notificaciones de eventos que SNMP admite de forma predeterminada se reenvían al host de capturas de SNMP.


