---
permalink: nfs-admin/break-locks-task.html 
sidebar: sidebar 
keywords: breaking, locks 
summary: Cuando los bloqueos de archivos impiden que los clientes accedan a los archivos, puede mostrar información sobre los bloqueos retenidos actualmente y romperán bloqueos específicos. Entre los ejemplos de escenarios en los que es posible que necesite romper los bloqueos se incluyen las aplicaciones de depuración. 
---
= Bloqueos de ruptura
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando los bloqueos de archivos impiden que los clientes accedan a los archivos, puede mostrar información sobre los bloqueos retenidos actualmente y romperán bloqueos específicos. Entre los ejemplos de escenarios en los que es posible que necesite romper los bloqueos se incluyen las aplicaciones de depuración.

.Acerca de esta tarea
 `vserver locks break`El comando solo está disponible en el nivel de privilegios avanzado y superior. Obtenga más información sobre `vserver locks break` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-locks-break.html["Referencia de comandos del ONTAP"^].

.Pasos
. Para encontrar la información que necesita para romper un bloqueo, utilice el `vserver locks show` comando.
+
Obtenga más información sobre `vserver locks show` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-locks-show.html["Referencia de comandos del ONTAP"^].

. Configure el nivel de privilegio en Advanced:
+
`set -privilege advanced`

. Ejecute una de las siguientes acciones:
+
[cols="35,65"]
|===


| Si desea romper un bloqueo especificando... | Introduzca el comando... 


 a| 
El nombre de SVM, el nombre del volumen, el nombre de LIF y la ruta de archivo
 a| 
`vserver locks break -vserver vserver_name -volume volume_name -path path -lif lif`



 a| 
El ID del bloqueo
 a| 
`vserver locks break -lockid UUID`

|===
. Vuelva al nivel de privilegio de administrador:
+
`set -privilege admin`


