---
permalink: nfs-admin/commands-manage-name-service-switch-entries-reference.html 
sidebar: sidebar 
keywords: command, manage, name, service, switch, entry 
summary: Puede administrar las entradas del conmutador de servicios de nombres creando, visualizando, modificando y eliminando. 
---
= Comandos para gestionar entradas del switch de servicio de nombres en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede administrar las entradas del conmutador de servicios de nombres creando, visualizando, modificando y eliminando.

[cols="35,65"]
|===


| Si desea... | Se usa este comando... 


 a| 
Crear una entrada de conmutador de servicio de nombres
 a| 
`vserver services name-service ns-switch create`



 a| 
Mostrar las entradas del conmutador de servicio de nombres
 a| 
`vserver services name-service ns-switch show`



 a| 
Modificar una entrada de cambio de servicio de nombres
 a| 
`vserver services name-service ns-switch modify`



 a| 
Eliminar una entrada de cambio de servicio de nombres
 a| 
`vserver services name-service ns-switch delete`

|===
Obtenga más información sobre `vserver services name-service ns-switch` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+name-service+ns-switch["Referencia de comandos de la ONTAP"^].

.Información relacionada
https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["Informe técnico de NetApp 4668: Guía de prácticas recomendadas de servicios de nombres"^]
