---
permalink: nfs-admin/commands-manage-name-mappings-reference.html 
sidebar: sidebar 
keywords: command, mapping, name 
summary: Hay comandos de la ONTAP específicos para gestionar las asignaciones de nombres. 
---
= Comandos para gestionar las asignaciones de nombres en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay comandos de la ONTAP específicos para gestionar las asignaciones de nombres.

[cols="35,65"]
|===


| Si desea... | Se usa este comando... 


 a| 
Cree una asignación de nombres
 a| 
`vserver name-mapping create`



 a| 
Inserte una asignación de nombres en una posición específica
 a| 
`vserver name-mapping insert`



 a| 
Mostrar asignaciones de nombres
 a| 
`vserver name-mapping show`



 a| 
Intercambiar la posición de dos asignaciones DE nombre NOTA: No se permite un intercambio cuando se configura la asignación de nombres con una entrada de calificador ip.
 a| 
`vserver name-mapping swap`



 a| 
Modificar una asignación de nombres
 a| 
`vserver name-mapping modify`



 a| 
Eliminar una asignación de nombres
 a| 
`vserver name-mapping delete`



 a| 
Validar la asignación de nombre correcta
 a| 
`vserver security file-directory show-effective-permissions -vserver vs1 -win-user-name user1 -path / -share-name sh1`

|===
Obtenga más información sobre `vserver name-mapping` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+name-mapping["Referencia de comandos del ONTAP"^].
