---
permalink: nfs-admin/commands-manage-nis-domain-config-reference.html 
sidebar: sidebar 
keywords: command, manage, nis, domain, configuration 
summary: Hay comandos específicos de ONTAP para administrar configuraciones de dominio NIS. 
---
= Comandos para gestionar configuraciones de dominio NIS en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay comandos específicos de ONTAP para administrar configuraciones de dominio NIS.

[cols="35,65"]
|===


| Si desea... | Se usa este comando... 


 a| 
Cree una configuración de dominio NIS
 a| 
`vserver services name-service nis-domain create`



 a| 
Mostrar configuraciones de dominio NIS
 a| 
`vserver services name-service nis-domain show`



 a| 
Mostrar el estado de enlace de una configuración de dominio NIS
 a| 
`vserver services name-service nis-domain show-bound`



 a| 
Mostrar estadísticas NIS
 a| 
`vserver services name-service nis-domain show-statistics` Disponible a nivel de privilegio avanzado y superior.



 a| 
Borrar estadísticas de NIS
 a| 
`vserver services name-service nis-domain clear-statistics` Disponible a nivel de privilegio avanzado y superior.



 a| 
Modifique una configuración de dominio NIS
 a| 
`vserver services name-service nis-domain modify`



 a| 
Elimine una configuración de dominio NIS
 a| 
`vserver services name-service nis-domain delete`



 a| 
Habilite el almacenamiento en caché para búsquedas de netgroup-by-host
 a| 
`vserver services name-service nis-domain netgroup-database config modify` Disponible a nivel de privilegio avanzado y superior.

|===
Obtenga más información sobre `vserver services name-service nis-domain` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+name-service+nis-domain["Referencia de comandos de la ONTAP"^].
