---
permalink: nfs-admin/commands-manage-character-mappings-reference.html 
sidebar: sidebar 
keywords: command, manage, character, mapping, smb, file, name, translation 
summary: Puede gestionar la asignación de caracteres creando, modificando, mostrando información o eliminando asignaciones de caracteres de archivo utilizadas para la traducción del nombre del archivo SMB en volúmenes FlexVol. 
---
= Comandos para administrar las asignaciones de caracteres para la traducción de nombres de archivo SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede gestionar la asignación de caracteres creando, modificando, mostrando información o eliminando asignaciones de caracteres de archivo utilizadas para la traducción del nombre del archivo SMB en volúmenes FlexVol.

[cols="35,65"]
|===


| Si desea... | Se usa este comando... 


 a| 
Cree nuevas asignaciones de caracteres de archivo
 a| 
`vserver cifs character-mapping create`



 a| 
Mostrar información acerca de las asignaciones de caracteres de archivo
 a| 
`vserver cifs character-mapping show`



 a| 
Modifique las asignaciones de caracteres de archivo existentes
 a| 
`vserver cifs character-mapping modify`



 a| 
Eliminar asignaciones de caracteres de archivo
 a| 
`vserver cifs character-mapping delete`

|===
Para obtener más información, consulte la página de manual de cada comando.
