---
permalink: nfs-admin/commands-manage-ldap-client-schema-templates-reference.html 
sidebar: sidebar 
keywords: command, manage, ldap, client, schema, template 
summary: Hay comandos ONTAP específicos para administrar plantillas de esquema de cliente LDAP. 
---
= Comandos para administrar plantillas de esquema de cliente LDAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay comandos ONTAP específicos para administrar plantillas de esquema de cliente LDAP.

[NOTE]
====
Los administradores de SVM no pueden modificar ni eliminar esquemas de cliente LDAP que crearon los administradores de clúster.

====
[cols="35,65"]
|===


| Si desea... | Se usa este comando... 


 a| 
Copie una plantilla de esquema LDAP existente
 a| 
`vserver services name-service ldap client schema copy` Disponible a nivel de privilegio avanzado y superior.



 a| 
Mostrar plantillas de esquema LDAP
 a| 
`vserver services name-service ldap client schema show`



 a| 
Modificar una plantilla de esquema LDAP
 a| 
`vserver services name-service ldap client schema modify` Disponible a nivel de privilegio avanzado y superior.



 a| 
Eliminar una plantilla de esquema LDAP
 a| 
`vserver services name-service ldap client schema delete` Disponible a nivel de privilegio avanzado y superior.

|===
Consulte la página de manual de cada comando para obtener más información.
