---
permalink: nfs-admin/configure-time-to-live-cached-user-credentials-task.html 
sidebar: sidebar 
keywords: configure, time, live, cache, nfs, user, credential 
summary: 'Puede configurar el lapso en que ONTAP almacena credenciales para los usuarios NFS en su caché interna (tiempo de actividad o TTL) mediante la modificación del servidor NFS de la máquina virtual de almacenamiento (SVM). De este modo, puede solucionar algunos problemas relacionados con la alta carga de los servidores de nombres o con los cambios de las credenciales que afectan al acceso del usuario NFS.' 
---
= Configurar el tiempo de vida de las credenciales de usuario NFS almacenadas en caché para las SVM de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar el lapso en que ONTAP almacena credenciales para los usuarios NFS en su caché interna (tiempo de actividad o TTL) mediante la modificación del servidor NFS de la máquina virtual de almacenamiento (SVM). De este modo, puede solucionar algunos problemas relacionados con la alta carga de los servidores de nombres o con los cambios de las credenciales que afectan al acceso del usuario NFS.

.Acerca de esta tarea
Estos parámetros están disponibles en el nivel de privilegios avanzado.

.Pasos
. Configure el nivel de privilegio en Advanced:
+
`set -privilege advanced`

. Realice la acción deseada:
+
[cols="35,65"]
|===


| Si desea modificar el TTL para el almacenamiento en caché... | Usar el comando... 


 a| 
Credenciales positivas
 a| 
`vserver nfs modify -vserver vserver_name -cached-cred-positive-ttl time_to_live`

El TTL se mide en milisegundos. A partir de ONTAP 9.10.1 y versiones posteriores, el valor predeterminado es 1 hora (3.600.000 milisegundos). En ONTAP 9.9.1 y las versiones anteriores, el valor predeterminado es de 24 horas (86.400.000 milisegundos). El intervalo permitido para este valor es de 1 minuto (60000 milisegundos) a 7 días (604,800,000 milisegundos).



 a| 
Credenciales negativas
 a| 
`vserver nfs modify -vserver vserver_name -cached-cred-negative-ttl time_to_live`

El TTL se mide en milisegundos. El valor predeterminado es 2 horas (7.200.000 milisegundos). El intervalo permitido para este valor es de 1 minuto (60000 milisegundos) a 7 días (604,800,000 milisegundos).

|===
. Vuelva al nivel de privilegio de administrador:
+
`set -privilege admin`


