---
permalink: nfs-admin/control-root-user-access-ntfs-security-data-task.html 
sidebar: sidebar 
keywords: control, root, user, access, ntfs, security, style, data 
summary: 'Puede configurar ONTAP para permitir que los clientes NFS accedan a datos de estilo de seguridad NTFS y a clientes NTFS para acceder a los datos de estilo de seguridad NFS. Cuando se utiliza un estilo de seguridad NTFS en un almacén de datos NFS, se debe decidir cómo tratar el acceso por parte del usuario raíz y configurar la máquina virtual de almacenamiento (SVM) según corresponda.' 
---
= Controlar el acceso de usuario raíz a datos de estilo de seguridad NTFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar ONTAP para permitir que los clientes NFS accedan a datos de estilo de seguridad NTFS y a clientes NTFS para acceder a los datos de estilo de seguridad NFS. Cuando se utiliza un estilo de seguridad NTFS en un almacén de datos NFS, se debe decidir cómo tratar el acceso por parte del usuario raíz y configurar la máquina virtual de almacenamiento (SVM) según corresponda.

.Acerca de esta tarea
Cuando un usuario raíz accede a datos de estilo de seguridad NTFS, tiene dos opciones:

* Asignar el usuario raíz a un usuario de Windows como cualquier otro usuario NFS y gestionar el acceso según ACL de NTFS.
* Ignorar las ACL de NTFS y proporcionar acceso completo a la raíz.


.Pasos
. Configure el nivel de privilegio en Advanced:
+
`set -privilege advanced`

. Realice la acción deseada:
+
[cols="35,65"]
|===


| Si desea que el usuario raíz... | Introduzca el comando... 


 a| 
Estar asignado a un usuario de Windows
 a| 
`vserver nfs modify -vserver vserver_name -ignore-nt-acl-for-root disabled`



 a| 
Omitir la comprobación de ACL de NT
 a| 
`vserver nfs modify -vserver vserver_name -ignore-nt-acl-for-root enabled`

|===
+
De manera predeterminada, este parámetro está deshabilitado.

+
Si este parámetro está habilitado pero no hay ninguna asignación de nombres para el usuario raíz, ONTAP utiliza una credencial de administrador de SMB predeterminada para la auditoría.

. Vuelva al nivel de privilegio de administrador:
+
`set -privilege admin`


