---
permalink: nfs-admin/control-nfs-requests-nonreserved-ports-task.html 
sidebar: sidebar 
keywords: control, nfs, request, nonreserved, port 
summary: Puede rechazar las solicitudes de montaje de NFS de puertos no reservados habilitando la opción -Mount-rootonly. Para rechazar todas las solicitudes NFS de puertos no reservados, puede habilitar la opción -nfs-rootonly. 
---
= Controlar solicitudes NFS desde puertos no reservados para SVM de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede rechazar las solicitudes de montaje NFS desde puertos no reservados si habilita `-mount-rootonly` la opción. Para rechazar todas las solicitudes NFS de puertos no reservados, puede habilitar `-nfs-rootonly` la opción.

.Acerca de esta tarea
Por defecto, la opción `-mount-rootonly` es `enabled`.

Por defecto, la opción `-nfs-rootonly` es `disabled`.

Estas opciones no se aplican al procedimiento NULL.

.Paso
. Ejecute una de las siguientes acciones:
+
[cols="35,65"]
|===


| Si desea... | Introduzca el comando... 


 a| 
Permita las solicitudes de montaje NFS de puertos no reservados
 a| 
`vserver nfs modify -vserver vserver_name -mount-rootonly disabled`



 a| 
Rechace las solicitudes de montaje NFS de puertos no reservados
 a| 
`vserver nfs modify -vserver vserver_name -mount-rootonly enabled`



 a| 
Permita todas las solicitudes NFS de puertos no reservados
 a| 
`vserver nfs modify -vserver vserver_name -nfs-rootonly disabled`



 a| 
Rechace todas las solicitudes NFS de puertos no reservados
 a| 
`vserver nfs modify -vserver vserver_name -nfs-rootonly enabled`

|===

