---
permalink: nfs-admin/display-export-policy-netgroup-queue-cache-task.html 
sidebar: sidebar 
keywords: display, export, policy, netgroup, queue, cache 
summary: ONTAP utiliza la cola de netgroup al importar y resolver grupos de red y utiliza la caché de netgroup para almacenar la información resultante. Al solucionar problemas relacionados con el grupo de directivas de exportación, puede utilizar los comandos show de cola de grupos de red de directivas de exportación Vserver y show de caché de grupos de exportación de Vserver para mostrar el estado de la cola de netgroup y el contenido de la caché de netgroup. 
---
= Mostrar la cola y la caché del grupo de red de directivas de exportación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP utiliza la cola de netgroup al importar y resolver grupos de red y utiliza la caché de netgroup para almacenar la información resultante. Al solucionar problemas relacionados con el grupo de directivas de exportación, puede utilizar la `vserver export-policy netgroup queue show` y.. `vserver export-policy netgroup cache show` comandos para mostrar el estado de la cola de netgroup y el contenido de la caché de netgroup.

.Paso
. Ejecute una de las siguientes acciones:
+
[cols="20,80"]
|===


| Para mostrar el grupo de red de la directiva de exportación... | Introduzca el comando... 


 a| 
Cola
 a| 
`vserver export-policy netgroup queue show`



 a| 
Almacenamiento en caché
 a| 
`vserver export-policy netgroup cache show -vserver vserver_name`

|===
+
Consulte la página de manual de cada comando para obtener más información.


