---
permalink: nfs-admin/enable-disable-nfsv4-referrals-task.html 
sidebar: sidebar 
keywords:  
summary: 'Puede habilitar las referencias de NFSv4 en máquinas virtuales de almacenamiento \(SVM\) al habilitar las opciones -v4-fsid-change y -v4.0-remisiones o -v4.1-remisiones. La habilitación de las referencias A NFSV4 puede resultar en un acceso más rápido a los datos para los clientes de NFSv4 que admiten esta función.' 
---
= Habilite o deshabilite las referencias de NFSv4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar las referencias de NFSv4 en máquinas virtuales de almacenamiento (SVM) mediante las opciones `-v4-fsid-change` y.. ``-v4.0-referrals``o.. La habilitación de las referencias A NFSV4 puede resultar en un acceso más rápido a los datos para los clientes de NFSv4 que admiten esta función.

.Lo que necesitará
Si desea habilitar las referencias NFS, primero debe deshabilitar NFS paralelo. No puede habilitar ambos a la vez.

.Pasos
. Configure el nivel de privilegio en Advanced:
+
`set -privilege advanced`

. Ejecute una de las siguientes acciones:
+
[cols="35,65"]
|===


| Si desea... | Introduzca el comando... 


 a| 
Habilite las referencias de NFSv4
 a| 
`vserver nfs modify -vserver vserver_name -v4-fsid-change enabled` `vserver nfs modify -vserver vserver_name -v4.0-referrals enabled`



 a| 
Desactive las referencias a NFSv4
 a| 
`vserver nfs modify -vserver vserver_name -v4.0-referrals disabled`



 a| 
Habilite las referencias de NFSv4.1
 a| 
`vserver nfs modify -vserver vserver_name -v4-fsid-change enabled` `vserver nfs modify -vserver vserver_name -v4.1-referrals enabled`



 a| 
Deshabilitar las referencias de NFSv4.1
 a| 
`vserver nfs modify -vserver vserver_name -v4.1-referrals disabled`

|===
. Vuelva al nivel de privilegio de administrador:
+
`set -privilege admin`


