---
permalink: nfs-admin/enable-disable-nfsv4-acls-task.html 
sidebar: sidebar 
keywords: enable, disable, nfsv4, acls 
summary: Para habilitar o deshabilitar las ACL de NFSv4, puede modificar las opciones -v4.0-acl y -v4.1-acl. Estas opciones están desactivadas de forma predeterminada. 
---
= Habilite o deshabilite las ACL de NFSv4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para habilitar o deshabilitar las ACL de NFSv4, puede modificar las `-v4.0-acl` y.. `-v4.1-acl` opciones. Estas opciones están desactivadas de forma predeterminada.

.Acerca de esta tarea
La `-v4.0-acl` o. `-v4.1-acl` La opción controla la configuración y la visualización de ACL de NFSv4; no controla la aplicación de estas ACL para la comprobación de acceso.

.Paso
. Ejecute una de las siguientes acciones:
+
[cols="30,70"]
|===


| Si desea... | Realice lo siguiente... 


 a| 
Habilitar ACL de NFSv4.0
 a| 
Introduzca el siguiente comando:

`vserver nfs modify -vserver vserver_name -v4.0-acl enabled`



 a| 
Desactive las ACL de NFSv4.0
 a| 
Introduzca el siguiente comando:

`vserver nfs modify -vserver vserver_name -v4.0-acl disabled`



 a| 
Habilite las ACL de NFSv4.1
 a| 
Introduzca el siguiente comando:

`vserver nfs modify -vserver vserver_name -v4.1-acl enabled`



 a| 
Deshabilitar las ACL de NFSv4.1
 a| 
Introduzca el siguiente comando:

`vserver nfs modify -vserver vserver_name -v4.1-acl disabled`

|===

