---
permalink: nfs-admin/enable-disable-rquota-support-task.html 
sidebar: sidebar 
keywords: enable, disable, rquota, support 
summary: 'ONTAP admite la versión 1 del protocolo de cuota remota (rcupo v1). El protocolo rquota permite a los clientes NFS obtener información de cuotas para los usuarios desde una máquina remota. Puede habilitar rquota en máquinas virtuales de almacenamiento (SVM) mediante el comando vserver nfs modify.' 
---
= Activa o desactiva la compatibilidad con rquota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP admite la versión 1 del protocolo de cuota remota (rcupo v1). El protocolo rquota permite a los clientes NFS obtener información de cuotas para los usuarios desde una máquina remota. Puede habilitar rquota en máquinas virtuales de almacenamiento (SVM) mediante el `vserver nfs modify` comando.

.Acerca de esta tarea
De forma predeterminada, rquota está desactivado.

.Paso
. Ejecute una de las siguientes acciones:
+
[cols="2*"]
|===
| Si desea... | Introduzca el siguiente comando... 


 a| 
Habilite la compatibilidad de rquota para SVM
 a| 
`vserver nfs modify -vserver vserver_name -rquota enable`



 a| 
Deshabilite el soporte rquota para SVM
 a| 
`vserver nfs modify -vserver vserver_name -rquota disable`

|===
+
Para obtener más información acerca de las cuotas, consulte link:../volumes/index.html["Gestión de almacenamiento lógico"].


