---
permalink: nfs-admin/enable-disable-pnfs-task.html 
sidebar: sidebar 
keywords: enable, disable, pnfs 
summary: 'PNFs mejora el rendimiento al permitir que los clientes NFS realicen operaciones de lectura/escritura en dispositivos de almacenamiento directamente y en paralelo, evitando así el servidor NFS como un posible cuello de botella. Para habilitar o deshabilitar pNFS (Parallel NFS), puede modificar la opción -v4.1-pnfs.' 
---
= Habilitar o deshabilitar pNFS para SVM de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
PNFs mejora el rendimiento al permitir que los clientes NFS realicen operaciones de lectura/escritura en dispositivos de almacenamiento directamente y en paralelo, evitando así el servidor NFS como un posible cuello de botella. Para habilitar o deshabilitar pNFS (NFS paralelo), puede modificar `-v4.1-pnfs` la opción.

[cols="50,50"]
|===
| Si la versión de ONTAP es... | El valor predeterminado de pNFS es... 


| 9,8 o posterior | deshabilitado 


| 9,7 o anterior | activado 
|===
.Antes de empezar
Se requiere compatibilidad con NFSv4.1 para poder utilizar pNFS.

Si desea habilitar pNFS, primero debe deshabilitar las referencias NFS. No se pueden habilitar ambos a la vez.

Si utiliza pNFS con Kerberos en SVM, debe habilitar Kerberos en cada LIF de la SVM.

.Paso
. Ejecute una de las siguientes acciones:
+
[cols="2*"]
|===
| Si desea... | Introduzca el comando... 


 a| 
Habilite pNFS
 a| 
`vserver nfs modify -vserver vserver_name -v4.1-pnfs enabled`



 a| 
Deshabilite pNFS
 a| 
`vserver nfs modify -vserver vserver_name -v4.1-pnfs disabled`

|===


.Información relacionada
* xref:../nfs-trunking/index.html[Descripción general de trunking NFS]

