---
permalink: nfs-admin/enable-nfsv42-security-labels-task.html 
sidebar: sidebar 
keywords: enable, nfs, v4.2, security, label 
summary: A partir de ONTAP 9.9.1, se pueden habilitar las etiquetas de seguridad NFS. Están desactivadas de forma predeterminada. 
---
= Habilite etiquetas de seguridad de NFS v4.2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.9.1, se pueden habilitar las etiquetas de seguridad NFS. Están desactivadas de forma predeterminada.

.Acerca de esta tarea
Con etiquetas de seguridad NFS v4.2, los servidores NFS de ONTAP tienen en cuenta el control de acceso obligatorio (MAC), al almacenar y recuperar atributos sec_label enviados por los clientes.

Para obtener más información, consulte https://tools.ietf.org/html/rfc7204["RFC7240"]

[NOTE]
====
Las etiquetas de seguridad v4.2 de NFS no son compatibles actualmente con las operaciones de volcado NDMP. Si las etiquetas de seguridad se encuentran en archivos o directorios, el volcado falla.

====
.Pasos
. Cambie la configuración del privilegio a avanzado:
+
``set -privilege advanced``

. Habilitar etiquetas de seguridad:
+
``vserver nfs modify -vserver svm_name -v4.2-seclabel enabled``


