---
permalink: nfs-admin/flush-export-policy-caches-task.html 
sidebar: sidebar 
keywords: flush, export, policy, cache 
summary: 'Vaciado manual de las cachés de la política de exportación (vaciado de caché de política de exportación de Vserver) elimina la información potencialmente obsoleta y obliga a ONTAP a recuperar la información actual de los recursos externos adecuados. Esto puede ayudar a resolver diversos problemas relacionados con el acceso de clientes a exportaciones NFS.' 
---
= Volcar cachés de políticas de exportación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP usa varios cachés de políticas de exportación para almacenar información relacionada con las políticas de exportación para agilizar el acceso. Vaciar las cachés de política de exportación manualmente (`vserver export-policy cache flush`) Elimina la información potencialmente obsoleta y obliga a ONTAP a recuperar la información actual de los recursos externos correspondientes. Esto puede ayudar a resolver diversos problemas relacionados con el acceso de clientes a exportaciones NFS.

.Acerca de esta tarea
La información de la caché de la directiva de exportación puede quedar obsoleta por los siguientes motivos:

* Un cambio reciente en las reglas de política de exportación
* Un cambio reciente en los registros de nombres de host en servidores de nombres
* Un cambio reciente en las entradas de netgroup en los servidores de nombres
* Recuperación de una interrupción de la red que impidió que los grupos de red se cargaran por completo


.Pasos
. Si no se cuenta con la caché de servicio de nombres habilitada, realice una de las siguientes acciones en el modo de privilegio avanzado:
+
[cols="2*"]
|===
| Si quieres tirar la cadena... | Introduzca el comando... 


 a| 
Todas las cachés de directivas de exportación (excepto showmount)
 a| 
`vserver export-policy cache flush -vserver vserver_name`



 a| 
La política de exportación rige la caché de acceso
 a| 
`vserver export-policy cache flush -vserver vserver_name -cache access` Puede incluir el parámetro opcional `-node` para especificar el nodo en el que desea vaciar la caché de acceso.



 a| 
La caché de nombres del host
 a| 
`vserver export-policy cache flush -vserver vserver_name -cache host`



 a| 
La caché de netgroup
 a| 
`vserver export-policy cache flush -vserver vserver_name -cache netgroup` El procesamiento de netgroups requiere muchos recursos. Solo debe vaciar la caché de netgroup si intenta resolver un problema de acceso de cliente causado por un grupo de red obsoleto.



 a| 
La caché showmount
 a| 
`vserver export-policy cache flush -vserver vserver_name -cache showmount`

|===
. Si la caché del servicio de nombres está habilitada, realice una de las siguientes acciones:
+
[cols="2*"]
|===
| Si quieres tirar la cadena... | Introduzca el comando... 


 a| 
La política de exportación rige la caché de acceso
 a| 
`vserver export-policy cache flush -vserver vserver_name -cache access` Puede incluir el parámetro opcional `-node` para especificar el nodo en el que desea vaciar la caché de acceso.



 a| 
La caché de nombres del host
 a| 
`vserver services name-service cache hosts forward-lookup delete-all`



 a| 
La caché de netgroup
 a| 
`vserver services name-service cache netgroups ip-to-netgroup delete-all` `vserver services name-service cache netgroups members delete-all` El procesamiento de netgroups requiere muchos recursos. Solo debe vaciar la caché de netgroup si intenta resolver un problema de acceso de cliente causado por un grupo de red obsoleto.



 a| 
La caché showmount
 a| 
`vserver export-policy cache flush -vserver vserver_name -cache showmount`

|===

