---
permalink: nfs-admin/how-name-mappings-used-concept.html 
sidebar: sidebar 
keywords: configure, name, mapping 
summary: ONTAP utiliza la asignación de nombres para asignar identidades SMB a identidades UNIX, identidades Kerberos a identidades UNIX e identidades UNIX a identidades SMB. Necesita esta información para obtener credenciales de usuario y proporcionar un acceso adecuado a los archivos independientemente de si se están conectando desde un cliente NFS o un cliente SMB. 
---
= Configure la información general de asignaciones de nombres
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP utiliza la asignación de nombres para asignar identidades SMB a identidades UNIX, identidades Kerberos a identidades UNIX e identidades UNIX a identidades SMB. Necesita esta información para obtener credenciales de usuario y proporcionar un acceso adecuado a los archivos independientemente de si se están conectando desde un cliente NFS o un cliente SMB.

Existen dos excepciones en las que no es necesario utilizar la asignación de nombres:

* Configura un entorno UNIX puro y no planea usar el acceso SMB o el estilo de seguridad NTFS en los volúmenes.
* En su lugar, puede configurar el usuario predeterminado que se utilizará.
+
En este escenario, no es necesario asignar nombres porque en lugar de asignar cada credencial de cliente individual todas las credenciales de cliente se asignan al mismo usuario predeterminado.



Tenga en cuenta que sólo puede utilizar la asignación de nombres para usuarios, no para grupos.

Sin embargo, puede asignar un grupo de usuarios individuales a un usuario específico. Por ejemplo, puede asignar todos los usuarios de AD que comiencen o terminen con la palabra SALES a un usuario UNIX específico y al UID del usuario.
