---
permalink: nfs-admin/ldap-signing-sealing-concept.html 
sidebar: sidebar 
keywords: ldap, sign, seal, concept 
summary: 'A partir de ONTAP 9, puede configurar la firma y el sellado para habilitar la seguridad de la sesión LDAP en consultas a un servidor de Active Directory (AD). Debe configurar los ajustes de seguridad del servidor NFS en la máquina virtual de almacenamiento (SVM) para que se correspondan con los del servidor LDAP.' 
---
= Conceptos de firma y sellado LDAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9, puede configurar la firma y el sellado para habilitar la seguridad de la sesión LDAP en consultas a un servidor de Active Directory (AD). Debe configurar los ajustes de seguridad del servidor NFS en la máquina virtual de almacenamiento (SVM) para que se correspondan con los del servidor LDAP.

La firma comprueba la integridad de la carga de datos LDAP mediante una tecnología de clave secreta. El sellado cifra la carga de datos LDAP para impedir la transmisión de información confidencial en texto sin cifrar. Una opción _LDAP Security Level_ indica si es necesario firmar, firmar y sellar el tráfico LDAP o no. El valor predeterminado es `none`. prueba

La firma LDAP y el sellado en el tráfico SMB se habilitan en la SVM con el `-session-security-for-ad-ldap` de la `vserver cifs security modify` comando.
