---
permalink: nfs-admin/limitations-support-nfsv4-concept.html 
sidebar: sidebar 
keywords: limitation, ontap, support, nfsv4 
summary: Debe conocer varias limitaciones del soporte de ONTAP para NFSv4. 
---
= Limitaciones del soporte de ONTAP para NFSv4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe conocer varias limitaciones del soporte de ONTAP para NFSv4.

* La función de delegación no es compatible con todos los tipos de cliente.
* En ONTAP 9.4 y versiones anteriores, el sistema de almacenamiento rechaza los nombres con caracteres no ASCII en volúmenes distintos a UTF8.
+
En ONTAP 9.5 y versiones posteriores, los volúmenes creados con la configuración de idioma utf8mb4 y montados con NFS v4 ya no están sujetos a esta restricción.

* Todos los identificadores de archivos son persistentes; el servidor no proporciona identificadores de archivos volátiles.
* No se admiten la migración ni la replicación.
* Los clientes NFSv4 no son compatibles con los reflejos de uso compartido de carga de solo lectura.
+
ONTAP enruta los clientes NFSv4 al origen de la duplicación de uso compartido de la carga para obtener acceso directo de lectura y escritura.

* No se admiten los atributos con nombre.
* Se admiten todos los atributos recomendados, excepto los siguientes:
+
** `archive`
** `hidden`
** `homogeneous`
** `mimetype`
** `quota_avail_hard`
** `quota_avail_soft`
** `quota_used`
** `system`
** `time_backup`
+

NOTE: Aunque no admite los `quota*` atributos, ONTAP admite cuotas de usuarios y grupos a través del protocolo de banda lateral RQUOTA.




