---
permalink: nfs-admin/modify-maximum-ace-limit-nfsv4-acls-task.html 
sidebar: sidebar 
keywords:  
summary: Puede modificar el número máximo de ACE permitidos para cada ACL de NFSv4 modificando el parámetro -v4-acl-max-aces. De forma predeterminada, el límite se establece en 400 ACE para cada ACL. El aumento de este límite puede ayudar a garantizar una correcta migración de datos con ACL que contengan más de 400 ACE en sistemas de almacenamiento que ejecuten ONTAP. 
---
= Modifique el límite máximo de ACE para ACL de NFSv4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede modificar el número máximo de ACE permitidos para cada ACL de NFSv4 mediante la modificación del parámetro `-v4-acl-max-aces`. De forma predeterminada, el límite se establece en 400 ACE para cada ACL. El aumento de este límite puede ayudar a garantizar una correcta migración de datos con ACL que contengan más de 400 ACE en sistemas de almacenamiento que ejecuten ONTAP.

.Acerca de esta tarea
Si aumenta este límite, el rendimiento de los clientes que acceden a archivos con ACL de NFSv4.

.Pasos
. Configure el nivel de privilegio en Advanced:
+
`set -privilege advanced`

. Modifique el límite máximo de ACE para ACL de NFSv4:
+
`vserver nfs modify -v4-acl-max-aces max_ace_limit`

+
El rango válido de

+
`max_ace_limit` es `192` para `1024.`

. Vuelva al nivel de privilegio de administrador:
+
`set -privilege admin`


