---
permalink: nfs-admin/nfs-credential-cache-concept.html 
sidebar: sidebar 
keywords: nfs, credential, cache 
summary: Cuando un usuario de NFS solicita acceso a exportaciones NFS en el sistema de almacenamiento de, ONTAP debe recuperar las credenciales de usuario desde servidores de nombres externos o desde archivos locales para autenticar el usuario. ONTAP después almacena estas credenciales en la caché de credenciales internas para futuras referencias. Comprender el funcionamiento de la caché de credenciales NFS le permite manejar los posibles problemas de rendimiento y acceso. 
---
= Cómo funciona la caché de credenciales NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando un usuario de NFS solicita acceso a exportaciones NFS en el sistema de almacenamiento de, ONTAP debe recuperar las credenciales de usuario desde servidores de nombres externos o desde archivos locales para autenticar el usuario. ONTAP después almacena estas credenciales en la caché de credenciales internas para futuras referencias. Comprender el funcionamiento de la caché de credenciales NFS le permite manejar los posibles problemas de rendimiento y acceso.

Sin la caché de credenciales, ONTAP tendría que consultar los servicios de nombres cada vez que un usuario NFS solicitara acceso. En un sistema de almacenamiento de mucha actividad al que acceden muchos usuarios, se pueden producir rápidamente problemas de rendimiento graves, que provocan retrasos no deseados o incluso la denegación del acceso del cliente NFS.

Con la caché de credenciales, ONTAP recupera las credenciales de usuario y las almacena durante un periodo predeterminado de tiempo para obtener un acceso rápido y sencillo en caso de que el cliente NFS envíe otra solicitud. Este método ofrece las siguientes ventajas:

* Facilita la carga en el sistema de almacenamiento al manejar menos solicitudes a servidores de nombres externos (como NIS o LDAP).
* Facilita la carga de los servidores de nombres externos enviando menos solicitudes.
* Acelera el acceso del usuario al eliminar el tiempo de espera para obtener credenciales de fuentes externas antes de que el usuario pueda autenticarse.


ONTAP almacena las credenciales positivas y negativas en la caché de credenciales. Las credenciales positivas significan que el usuario se ha autenticado y se le ha concedido acceso. Las credenciales negativas indican que el usuario no se ha autenticado y se le ha denegado el acceso.

De forma predeterminada, ONTAP almacena credenciales positivas durante 24 horas, es decir, tras autenticar inicialmente al usuario, ONTAP utiliza las credenciales en caché para cualquier solicitud de acceso por parte de ese usuario durante 24 horas. Si el usuario solicita acceso después de 24 horas, el ciclo se vuelve a iniciar: ONTAP descarta las credenciales en caché y obtiene de nuevo las credenciales del origen del servicio de nombres adecuado. Si las credenciales cambiaron en el servidor de nombres durante las 24 horas anteriores, ONTAP almacenará las credenciales actualizadas para utilizarlas en las próximas 24 horas.

De forma predeterminada, ONTAP almacena credenciales negativas durante dos horas; es decir, después de denegar inicialmente el acceso a un usuario, ONTAP continúa negando cualquier solicitud de acceso por ese usuario durante dos horas. Si el usuario solicita acceso después de 2 horas, el ciclo se inicia de nuevo: ONTAP obtiene las credenciales de nuevo del origen de servicio de nombres apropiado. Si las credenciales cambiaron en el servidor de nombres durante las dos horas anteriores, ONTAP almacena en caché las credenciales actualizadas para utilizarlas en las siguientes dos horas.
