---
permalink: nfs-admin/nfs-client-authentication-concept.html 
sidebar: sidebar 
keywords: ontap, nfs, client, authentication 
summary: Los clientes de NFS deben autenticarse correctamente antes de poder acceder a los datos en la SVM. ONTAP autentica a los clientes al comprobar sus credenciales de UNIX con los servicios de nombres que se configuran. 
---
= Obtenga información sobre la autenticación ONTAP para clientes NAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los clientes de NFS deben autenticarse correctamente antes de poder acceder a los datos en la SVM. ONTAP autentica a los clientes al comprobar sus credenciales de UNIX con los servicios de nombres que se configuran.

Cuando un cliente NFS se conecta con la SVM, ONTAP obtiene las credenciales de UNIX del usuario comprobando diferentes servicios de nombre, en función de la configuración de los servicios de nombres de la SVM. ONTAP puede comprobar credenciales para cuentas UNIX locales, dominios NIS y dominios LDAP. Debe haber al menos uno de ellos configurado para que ONTAP pueda autenticar correctamente al usuario. Puede especificar varios servicios de nombres y el orden en el que ONTAP los busca.

En un entorno NFS puro con estilos de seguridad de volúmenes UNIX, esta configuración es suficiente para autenticar y proporcionar el acceso adecuado a los archivos para que los usuarios que se conecten desde un cliente NFS.

Si utiliza estilos de seguridad de volúmenes mixtos, NTFS o unificados, ONTAP debe obtener un nombre de usuario SMB para el usuario UNIX para la autenticación con un controlador de dominio de Windows. Esto puede suceder mediante la asignación de usuarios individuales mediante cuentas de UNIX locales o dominios LDAP, o bien mediante un usuario de SMB predeterminado. Puede especificar los servicios de nombres que ONTAP busca en qué orden, o bien especificar un usuario de SMB predeterminado.
