---
permalink: nfs-admin/nfsv40-functionality-supported-concept.html 
sidebar: sidebar 
keywords: nfsv4.0, functionality, support, ontap 
summary: ONTAP admite todas las funciones obligatorias de NFSv4.0 excepto los mecanismos de seguridad SPKM3 y LIPKEY. 
---
= Funcionalidad NFSv4.0 compatible con ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP admite todas las funciones obligatorias de NFSv4.0 excepto los mecanismos de seguridad SPKM3 y LIPKEY.

Se admiten las siguientes funciones DE NFSV4:

* *COMPUESTO*
+
Permite a un cliente solicitar varias operaciones de archivo en una única solicitud de llamada a procedimiento remoto (RPC).

* *Delegación de archivos*
+
Permite al servidor delegar el control de archivos en algunos tipos de clientes para el acceso de lectura y escritura.

* *Pseudofs*
+
Los servidores NFSv4 los utilizan para determinar los puntos de montaje del sistema de almacenamiento. No existe ningún protocolo de montaje en NFSv4.

* *Bloqueo*
+
Basado en arrendamiento. No hay protocolos NLM (Network Lock Manager) o NSM (Network Status Monitor) separados en NFSv4.



Para obtener más información acerca del protocolo NFSv4.0, consulte RFC 3530.
