---
permalink: nfs-admin/ontap-support-nfsv41-concept.html 
sidebar: sidebar 
keywords: ontap, support, nfsv4.1 
summary: A partir de ONTAP 9.8, la funcionalidad nconnect está disponible de forma predeterminada con NFSv4.1 habilitado. 
---
= Obtenga más información sobre la compatibilidad de ONTAP con NFSv4.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.8, la funcionalidad nconnect está disponible de forma predeterminada con NFSv4.1 habilitado.

En las implementaciones anteriores de clientes NFS solo se utiliza una única conexión TCP con un montaje. En ONTAP, una única conexión TCP puede convertirse en un cuello de botella que aumenta las IOPS.

nconnect mejora el rendimiento del cliente NFS al permitir múltiples conexiones TCP (hasta 16) para un solo montaje, lo que ayuda a superar el cuello de botella de rendimiento que puede ocurrir con una sola conexión TCP a medida que aumentan las IOPS.

NFSv4.1 está habilitado de forma predeterminada en ONTAP 9.9.1 y posteriores. En versiones anteriores, puede habilitarla especificando `-v4.1` la opción y configurándola en `enabled` al crear un servidor NFS en la máquina virtual de almacenamiento (SVM).

ONTAP no es compatible con las delegaciones a nivel de archivo y directorio de NFSv4.1.

.Información relacionada
link:nconnect-concept.html["Obtenga información sobre nconnect para el rendimiento de NFS"].
