---
permalink: nfs-admin/ontap-support-nfsv42-concept.html 
sidebar: sidebar 
keywords: ontap, support, nfsv4.2, MAC-labelled NFS, extended attributes, xattrs 
summary: A partir de ONTAP 9.8, se admite el protocolo NFSv4.2 para permitir el acceso a los clientes habilitados por NFSv4.2. 
---
= Compatibilidad con ONTAP para NFSv4.2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.8, se admite el protocolo NFSv4.2 para permitir el acceso a los clientes habilitados por NFSv4.2.

NFSv4.2 está habilitado de forma predeterminada en ONTAP 9.9.1 y posteriores. En ONTAP 9.8, puede activar v4.2 especificando el `-v4.1` y establecerla en `enabled` Al crear un servidor NFS en la máquina virtual de almacenamiento (SVM). Al habilitar NFSv4.1, los clientes también pueden utilizar las funciones de NFSv4.1 mientras están montados como v4.2.

Se admiten las siguientes características opcionales de NFSv4.2:

[cols="2*"]
|===
| Función | Compatible empezando por ... 


 a| 
El control de acceso obligatorio (MAC) tiene la etiqueta NFS
 a| 
ONTAP 9.9.1



 a| 
Atributos NFS extendidos
 a| 
ONTAP 9.12.1

|===
Otras características opcionales de NFSv4.2 se agregarán en una versión más reciente de ONTAP.



== Habilite etiquetas de seguridad de NFS v4.2

A partir de ONTAP 9.9.1, se pueden habilitar las etiquetas de seguridad NFS. Están desactivadas de forma predeterminada.

Con etiquetas de seguridad NFS v4.2, los servidores NFS de ONTAP tienen en cuenta el control de acceso obligatorio (MAC), al almacenar y recuperar atributos sec_label enviados por los clientes.

Para obtener más información, consulte link:https://tools.ietf.org/html/rfc7204["RFC 7240"^]

A partir de ONTAP 9.12.1, las etiquetas de seguridad v4.2 de NFS son compatibles con las operaciones de volcado NDMP. Si las etiquetas de seguridad se encuentran en archivos o directorios en versiones anteriores, el volcado falla.

.Pasos
. Cambie la configuración del privilegio a avanzado:
+
``set -privilege advanced``

. Habilitar etiquetas de seguridad:
+
``vserver nfs modify -vserver _svm_name_ -v4.2-seclabel enabled``





== Habilite atributos extendidos de NFS

A partir de ONTAP 9.12.1, los atributos extendidos de NFS (xattrs) están habilitados de forma predeterminada.

Los atributos extendidos son los atributos NFS estándar definidos por https://tools.ietf.org/html/rfc8276["RFC 8276"^] Y se habilita en los clientes NFS actuales. Pueden utilizarse para adjuntar metadatos definidos por el usuario a objetos del sistema de archivos y son interesantes en puestas en marcha de seguridad avanzadas.

Los atributos extendidos de NFS no se admiten actualmente para las operaciones de volcado de NDMP. Si se encuentran atributos extendidos en archivos o directorios, el volcado se realiza pero no realiza una copia de seguridad de los atributos extendidos en esos archivos o directorios.

Si necesita desactivar atributos extendidos, utilice ``vserver nfs modify -v4.2-xattrs disabled`` comando.
