---
permalink: nfs-admin/ontap-support-nfsv42-concept.html 
sidebar: sidebar 
keywords: ontap, support, nfsv4.2, MAC-labelled NFS, extended attributes, xattrs 
summary: A partir de ONTAP 9.8, se admite el protocolo NFSv4.2 para permitir el acceso a los clientes habilitados por NFSv4.2. 
---
= Obtenga más información sobre la compatibilidad de ONTAP con NFSv4.2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9,8, ONTAP admite el protocolo NFSv4,2 para permitir acceso a clientes habilitados para NFSv4,2.

NFSv4.2 está habilitado de forma predeterminada en ONTAP 9.9.1 y versiones posteriores.  En ONTAP 9.8, es necesario habilitar manualmente la versión 4.2 especificando el `-v4.2` opción y configurarla en `enabled` al crear un servidor NFS en la máquina virtual de almacenamiento (SVM).  Habilitar NFSv4.1 también permite a los clientes usar las características de NFSv4.1 mientras están montados como v4.2.

Las versiones sucesivas de ONTAP amplían la compatibilidad de NFSv4,2 funciones opcionales.

[cols="2*"]
|===
| Empezando por... | NFSv4,2 características opcionales incluyen... 


| ONTAP 9.12.1  a| 
* Atributos NFS extendidos
* Archivos dispersos
* Reservas de espacio




| ONTAP 9.9.1 | El control de acceso obligatorio (MAC) tiene la etiqueta NFS 
|===


== Etiquetas de seguridad de NFS v4,2

A partir de ONTAP 9.9.1, se pueden habilitar las etiquetas de seguridad NFS. Están desactivadas de forma predeterminada.

Con etiquetas de seguridad NFS v4.2, los servidores NFS de ONTAP tienen en cuenta el control de acceso obligatorio (MAC), al almacenar y recuperar atributos sec_label enviados por los clientes.

Para obtener más información, consulte link:https://tools.ietf.org/html/rfc7204["RFC 7240"^].

A partir de ONTAP 9.12.1, las etiquetas de seguridad v4.2 de NFS son compatibles con las operaciones de volcado NDMP. Si las etiquetas de seguridad se encuentran en archivos o directorios en versiones anteriores, el volcado falla.

.Pasos
. Cambie la configuración del privilegio a avanzado:
+
[source, cli]
----
set -privilege advanced
----
. Habilitar etiquetas de seguridad:
+
[source, cli]
----
vserver nfs modify -vserver <svm_name> -v4.2-seclabel enabled
----




== Atributos NFS extendidos

A partir de ONTAP 9.12.1, los atributos extendidos de NFS (xattrs) están habilitados de forma predeterminada.

Los atributos ampliados son atributos estándar de NFS definidos https://tools.ietf.org/html/rfc8276["RFC 8276"^] y activados en los clientes NFS modernos. Se pueden utilizar para adjuntar metadatos definidos por el usuario a objetos del sistema de archivos, y son de interés en implementaciones de seguridad avanzadas.

Los atributos extendidos de NFS no se admiten actualmente para las operaciones de volcado de NDMP. Si se encuentran atributos extendidos en archivos o directorios, el volcado se realiza pero no realiza una copia de seguridad de los atributos extendidos en esos archivos o directorios.

Si necesita deshabilitar los atributos ampliados, utilice `vserver nfs modify -v4.2-xattrs disabled` el comando.
