---
permalink: nfs-admin/setup-file-access-concept.html 
sidebar: sidebar 
keywords: setting, file, access, nfs 
summary: 'Debe completar una serie de pasos para permitir que los clientes accedan a archivos de máquinas virtuales de almacenamiento (SVM) mediante NFS. Existen algunos pasos adicionales que son opcionales en función de la configuración actual de su entorno.' 
---
= Configurar el acceso a archivos con la información general de NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe completar una serie de pasos para permitir que los clientes accedan a archivos de máquinas virtuales de almacenamiento (SVM) mediante NFS. Existen algunos pasos adicionales que son opcionales en función de la configuración actual de su entorno.

Para que los clientes puedan acceder a los archivos de las SVM mediante NFS, debe realizar las siguientes tareas:

. Habilite el protocolo NFS en la SVM.
+
Debe configurar la SVM para permitir el acceso a los datos desde clientes a través de NFS.

. Cree un servidor NFS en la SVM.
+
Un servidor NFS es una entidad lógica en la SVM que permite que la SVM sirva archivos a través de NFS. Debe crear el servidor NFS y especificar las versiones de protocolo NFS que desea permitir.

. Configure las políticas de exportación en la SVM.
+
Es necesario configurar las políticas de exportación para que los volúmenes y qtrees estén disponibles para los clientes.

. Configuración del servidor NFS con la seguridad y otras opciones adecuadas en función de la red y el entorno de almacenamiento.
+
Este paso puede incluir la configuración de Kerberos, LDAP, NIS, asignaciones de nombres y usuarios locales.


