---
permalink: nfs-admin/view-nfs-exports-svms-concept.html 
sidebar: sidebar 
keywords: enable, display, nfs, export, client 
summary: Los clientes NFS pueden utilizar el comando showmount -e para ver una lista de exportaciones disponibles en un servidor NFS de ONTAP. Esto puede ayudar a los usuarios a identificar el sistema de archivos que desean montar. 
---
= Habilitar la visualización de exportaciones en clientes NFS para SVM de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los clientes NFS pueden utilizar el `showmount -e` comando para ver una lista de exportaciones disponibles desde un servidor NFS de ONTAP. Esto puede ayudar a los usuarios a identificar el sistema de archivos que desean montar.

ONTAP permite que los clientes NFS vean la lista de exportaciones de forma predeterminada. En versiones anteriores, la `showmount` opción `vserver nfs modify` del comando debe habilitarse de forma explícita. Para ver la lista de exportación, debe habilitarse NFSv3 en la SVM.

.Ejemplo
El siguiente comando muestra la función showmount en la SVM denominada vs1:

[listing]
----
clusterl : : > vserver nfs show -vserver vs1 -fields showmount
vserver showmount
------- ---------
vs1    enabled
----
El siguiente comando ejecutado en un cliente NFS muestra la lista de exportaciones en un servidor NFS con la dirección IP 10.63.21.9:

[listing]
----
showmount -e 10.63.21.9
Export list for 10.63.21.9:
/unix        (everyone)
/unix/unixl  (everyone)
/unix/unix2  (everyone)
/            (everyone)
----