---
sidebar: sidebar 
permalink: anti-ransomware/enable-arp-ai-with-au.html 
keywords: ransomware, arp, enable, ai, automatic, update, upgrade, autonomous ransomware protection 
summary: A partir de ONTAP 9.16.1, habilite ARP/AI automáticamente para las instalaciones de FlexVol o habilítelo manualmente después de cumplir con los requisitos previos. 
---
= Habilitar ONTAP ARP/AI
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.16.1, ARP ha adoptado la Protección Autónoma contra Ransomware con Inteligencia Artificial (ARP/IA) para mejorar la detección y respuesta ante amenazas. Tras actualizar su clúster a ONTAP 9.17.1 para SAN u ONTAP 9.16.1 para NAS, ARP/IA se habilitará automáticamente para los volúmenes FlexVol si ARP ya está habilitado para dichos volúmenes. Si no ha habilitado ARP ni ONTAP link:../update/enable-automatic-updates-task.html["actualizaciones automáticas"] Para su clúster, debe seguir uno de los escenarios descritos en este procedimiento.


IMPORTANT: Antes de actualizar a una versión de ONTAP con soporte ARP/AI, link:../upgrade/arp-warning-clear.html["Cierre cualquier detección ARP existente"] .

.Antes de empezar
* Debe tener volúmenes FlexVol para usar ARP/AI. Si tiene volúmenes FlexGroup , el modelo ARP utilizado antes de ARP/AI seguirá funcionando después de actualizar a ONTAP 9.16.1 o posterior.



NOTE: (Solo entornos NAS) Al actualizar a ONTAP 9.16.1 o posterior, ARP se habilita y se activa automáticamente para cualquier instancia de ARP existente con volúmenes FlexVol . Dado que ARP/AI se entrena con un modelo de aprendizaje automático exhaustivo, ya no se requiere un período de aprendizaje. Cualquier período de aprendizaje que no se haya completado antes de la actualización finalizará automáticamente y los volúmenes pasarán a ARP/AI activo.

.Pasos
. Siga la situación específica de su configuración:
+
** *Solo entornos SAN*
+
*** *Para clústeres nuevos y existentes que ejecutan ONTAP 9.17.1 o posterior con volúmenes FlexVol *: cuando actualice o instale ONTAP 9.17.1 o posterior, debe link:enable-task.html["habilitar ARP"] en los volúmenes que desea proteger. Al habilitar ARP mediante el Administrador del Sistema o la CLI, la funcionalidad ARP/AI se habilita automáticamente. Una vez habilitada en un volumen SAN, link:respond-san-entropy-eval-period.html["ARP/AI monitorea los datos continuamente durante un período de evaluación"] para determinar si las cargas de trabajo son adecuadas para ARP y establecer un umbral de cifrado óptimo para la detección.


** *Solo entornos NAS*
+
*** *Para clusters nuevos que ejecuten ONTAP 9.16.1 o posterior con volúmenes FlexVol: link:enable-task.html["Active ARP"]. ARP no está habilitado de forma predeterminada. habilitarlo, la funcionalidad ARP/AI se habilita automáticamente en los volúmenes FlexVol que desee proteger.
*** *Para clústeres existentes actualizados recientemente a ONTAP 9.16.1 y versiones posteriores que tengan ARP habilitado*: No se requiere ninguna acción. ARP/AI se convierte automáticamente en el nuevo método ARP de protección contra amenazas en los volúmenes FlexVol que haya elegido proteger.
*** *Para clústeres existentes recientemente actualizados a ONTAP 9.16.1 y versiones posteriores que no tienen ARP habilitado*: link:enable-task.html["Active ARP"] . ARP/AI se convierte automáticamente en el nuevo método ARP de protección contra amenazas después de habilitar ARP.




. Una vez habilitado ARP/AI, decida si desea que se envíen e instalen actualizaciones de protección ARP/AI link:arp-ai-automatic-updates.html["automática o manualmente"] .


.Información relacionada
* link:arp-ai-automatic-updates.html["Actualice ARP/AI"]

