---
sidebar: sidebar 
permalink: anti-ransomware/enable-task.html 
keywords: anti-ransomware overview, ransomware, security, introduce, autotonomous, protection, arp, detection, threat, attack, suspect, what ontap anti-ransomware detects, entropy, abnormal volume activity, extension conformity, how to recover data in after a ransomware attack, ransomware protection strategy 
summary: 'La protección de ransomware autónoma (ARP) puede habilitarse en volúmenes nuevos o existentes. Primero se habilita ARP en el modo de aprendizaje, en el cual el sistema analiza la carga de trabajo para caracterizar el comportamiento normal y, a continuación, se cambia al modo activo en el que se Marca la actividad anormal para la evaluación.' 
---
= Habilite la protección de ransomware autónoma
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
A partir de ONTAP 9.10.1, la protección de ransomware autónoma (ARP) puede habilitarse en volúmenes nuevos o existentes. Primero debe habilitar ARP en el modo de aprendizaje, en el cual el sistema analiza la carga de trabajo para caracterizar el comportamiento normal. Puede habilitar ARP en un volumen existente, o bien crear un volumen nuevo y habilitar ARP desde el principio.

.Acerca de esta tarea
Siempre debe habilitar ARP inicialmente en modo de aprendizaje (o ejecución en seco). Si se inicia en modo activo, se pueden producir demasiados informes de falsos positivos.

Se recomienda que deje que ARP se ejecute en modo de aprendizaje durante un mínimo de 30 días. A partir de ONTAP 9.13.1, ARP determina automáticamente el intervalo óptimo del período de aprendizaje y automatiza el switch, que puede ocurrir antes de 30 días.

Para obtener más información, consulte link:index.html#learning-and-active-modes["Modos de aprendizaje y activos"].


NOTE: En los volúmenes existentes, los modos de aprendizaje y activo solo se aplican a datos recién escritos, no a datos que ya existan en el volumen. Los datos existentes no se analizan y analizan, ya que se asumen las características del tráfico de datos normal anterior según los nuevos datos una vez habilitado para ARP el volumen.

.Antes de empezar
* Debe tener una máquina virtual de almacenamiento habilitada para NFS o SMB (o ambos).
* La xref:index.html[licencia correcta] Debe estar instalado para la versión de ONTAP.
* Debe tener carga de trabajo NAS con clientes configurados.
* El volumen que desea configurar ARP On necesita estar protegido debe tener un activo link:../concepts/namespaces-junction-points-concept.html["ruta de unión"^].
* El volumen debe estar lleno por debajo del 100%.
* Se recomienda configurar el sistema EMS para enviar notificaciones por correo electrónico, que incluirán avisos de actividad ARP. Para obtener más información, consulte link:../error-messages/configure-ems-events-send-email-task.html["Configure eventos de EMS para que envíen notificaciones por correo electrónico"].
* A partir de ONTAP 9.13.1, se recomienda habilitar la verificación multiadministrador (MAV) para que se necesiten dos o más administradores de usuarios autenticados para la configuración de protección autónoma contra ransomware (ARP). Para obtener más información, consulte link:../multi-admin-verify/enable-disable-task.html["Habilite la verificación multiadministradora"^].


.Pasos
[role="tabbed-block"]
====
.System Manager
--
. Seleccione *Almacenamiento > Volúmenes* y, a continuación, seleccione el volumen que desea proteger.
. En la pestaña *Seguridad* de la vista general *Volúmenes*, selecciona *Estado* para cambiar de Desactivado a Activado en el modo de aprendizaje en la casilla *Anti-ransomware*.
. Cuando finalice el período de aprendizaje, cambie ARP al modo activo.
+

NOTE: A partir de ONTAP 9.13.1, ARP determina automáticamente el intervalo óptimo del período de aprendizaje y automatiza el switch. Puede hacerlo link:../anti-ransomware/enable-default-task.html["Deshabilite este ajuste en la máquina virtual de almacenamiento asociada"] si desea controlar el modo de aprendizaje al modo activo, cambie manualmente.

+
.. Selecciona *Almacenamiento > Volúmenes* y, a continuación, selecciona el volumen que esté listo para el modo activo.
.. En la pestaña *Seguridad* del resumen *Volúmenes*, selecciona *Cambiar* al modo activo en el cuadro Anti-ransomware.


. Puede verificar el estado ARP del volumen en la casilla *Anti-ransomware*.
+
Para mostrar el estado ARP para todos los volúmenes: En el panel *Volúmenes*, seleccione *Mostrar/Ocultar* y, a continuación, asegúrese de que el estado *Anti-ransomware* esté marcado.



--
.CLI
--
.Habilite ARP en un volumen existente
. Modifique un volumen existente para habilitar la protección contra ransomware en el modo de aprendizaje:
+
`security anti-ransomware volume dry-run -volume _vol_name_ -vserver _svm_name_`

+
También puedes habilitar una protección contra ransomware con el `volume modify` comando:

+
`volume modify -volume _vol_name_ -vserver _svm_name_ -anti-ransomware-state dry-run`

+
Si ha actualizado a ONTAP 9.13.1 o posterior, el aprendizaje adaptativo se activa para que el cambio al estado activo se realice automáticamente. Si no desea que este comportamiento se habilite automáticamente, cambie la configuración en el nivel de SVM en todos los volúmenes asociados:

+
`vserver modify _svm_name_ -anti-ransomware-auto-switch-from-learning-to-enabled false`

. Cuando el periodo de aprendizaje haya terminado, modifique el volumen protegido para cambiar al modo activo si no se ha realizado automáticamente:
+
`security anti-ransomware volume enable -volume _vol_name_ -vserver _svm_name_`

+
También se puede cambiar al modo activo con el comando modify volume:

+
`volume modify -volume _vol_name_ -vserver _svm_name_ -anti-ransomware-state active`

. Verifique el estado ARP del volumen.
+
`security anti-ransomware volume show`



.Habilite ARP en un nuevo volumen
. Crea un nuevo volumen con la protección antiransomware habilitada antes de aprovisionar los datos.
+
`volume create -volume _vol_name_ -vserver _svm_name_  -aggregate _aggr_name_ -size _nn_ -anti-ransomware-state dry-run -junction-path /_path_name_`

+
Si ha actualizado a ONTAP 9.13.1 o posterior, el aprendizaje adaptativo se activa para que el cambio al estado activo se realice automáticamente. Si no desea que este comportamiento se habilite automáticamente, cambie la configuración en el nivel de SVM en todos los volúmenes asociados:

+
`vserver modify _svm_name_ -anti-ransomware-auto-switch-from-learning-to-enabled false`

. Cuando el periodo de aprendizaje haya terminado, modifique el volumen protegido para cambiar al modo activo si no se ha realizado automáticamente:
+
`security anti-ransomware volume enable -volume _vol_name_ -vserver _svm_name_`

+
También se puede cambiar al modo activo con el comando modify volume:

+
`volume modify -volume _vol_name_ -vserver _svm_name_ -anti-ransomware-state active`

. Verifique el estado ARP del volumen.
+
`security anti-ransomware volume show`



--
====