---
sidebar: sidebar 
permalink: anti-ransomware/enable-arp-ai-with-au.html 
keywords: ransomware, arp, enable, ai, automatic, update, upgrade, autonomous ransomware protection 
summary: A partir de ONTAP 9.16,1, habilite automáticamente ARP/AI para instalaciones FlexVol con ARP habilitado o habilite manualmente después de cumplir los requisitos previos. 
---
= Active ARP/AI con actualización automática
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A partir de la versión ONTAP 9.16,1, ARP ha adoptado la protección autónoma frente a ransomware con inteligencia artificial (ARP/IA) para mejorar la detección y la respuesta de las amenazas. Después de actualizar el clúster a ONTAP 9.16,1, ARP/AI se habilitará automáticamente para los volúmenes FlexVol si ARP ya está habilitado para esos volúmenes. Si no ha habilitado ARP o no ha habilitado las actualizaciones automáticas para el clúster, debe seguir una de las situaciones descritas en este procedimiento.


IMPORTANT: Antes de actualizar a ONTAP 9.16,1, link:../upgrade/arp-warning-clear.html["Cierre cualquier detección ARP existente"].

.Antes de empezar
* Debe tener volúmenes de FlexVol para usar ARP/AI. Si tiene volúmenes FlexGroup, el modelo ARP utilizado antes de ARP/AI sigue funcionando después de actualizar a ONTAP 9.16,1.



NOTE: Cuando se actualiza a ONTAP 9.16,1, ARP se habilita automáticamente en modo activo para cualquier instancia existente de ARP con volúmenes de FlexVol. Debido a que ARP/AI se entrena en un modelo de aprendizaje automático extenso, ya no es necesario un período de aprendizaje. Los periodos de aprendizaje que no se hayan completado antes de la actualización finalizarán automáticamente y los volúmenes pasarán al modo activo.

.Pasos
. Siga la situación específica de su configuración:
+
** *Para nuevos clústeres que ejecutan ONTAP 9.16,1*: link:enable-task.html["Active ARP"]. ARP no está activado de forma predeterminada. Una vez que habilita ARP, la funcionalidad ARP/AI se habilita automáticamente en modo activo en los volúmenes que elige proteger.
** *Para los clústeres existentes recientemente actualizados a ONTAP 9.16,1 que tienen ARP habilitado*: No es necesario realizar ninguna acción. ARP/AI se convertirá automáticamente en el nuevo método ARP de protección contra amenazas en los volúmenes de FlexVol que hayas elegido proteger.
** *Para los clusters existentes recientemente actualizados a ONTAP 9.16,1 que no tienen ARP habilitado*: link:enable-task.html["Active ARP"]. ARP/AI se convertirá automáticamente en el nuevo método ARP de protección contra amenazas después de habilitar ARP.


. Después de habilitar ARP/AI, decida si desea que las actualizaciones de protección ARP/AI se entreguen e instalenlink:arp-ai-automatic-updates.html["automática o manualmente"].


.Información relacionada
* link:arp-ai-automatic-updates.html["Actualice ARP/AI"]

