---
sidebar: sidebar 
permalink: anti-ransomware/index.html 
keywords: ransomware, arp, autonomous protection, ai, arp ai, security, detect, detection, threat, attack, suspect, anti-ransomware, entropy, abnormal volume activity, antiransomware, extension conformity, ransomware protection strategy 
summary: La protección frente a ransomware autónoma utiliza análisis de carga de trabajo en entornos NAS para detectar y advertir sobre la actividad anormal que podría ser un ataque de ransomware. 
---
= Obtenga más información sobre la protección autónoma frente a ransomware de ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.10.1, la función de protección de ransomware autónoma (ARP) utiliza análisis de cargas de trabajo en entornos NAS (NFS y SMB) para detectar de forma proactiva y advertir sobre una actividad anormal que puede indicar un ataque de ransomware. Cuando se sospecha de un ataque, ARP también crea nuevas instantáneas, además de la protección existente que ofrecen las instantáneas programadas.



== Protección autónoma frente a ransomware con inteligencia artificial (ARP/AI)

A partir de ONTAP 9.16,1, ARP mejora la resiliencia cibernética al adoptar un modelo de aprendizaje automático para los análisis antiransomware que detecta formas de ransomware en constante evolución con una precisión del 99 %. El modelo de aprendizaje automático de ARP se entrena previamente en un gran conjunto de datos de archivos, tanto antes como después de un ataque simulado de ransomware. Esta formación intensiva en recursos se realiza fuera de ONTAP, pero el aprendizaje de esta formación se utiliza para el modelo dentro de ONTAP.

.Transición inmediata a la protección activa para ARP/AI con volúmenes FlexVol
Con los volúmenes ARP/AI y FlexVol, no hay <<Modos de aprendizaje y activos,período de aprendizaje>>. ARP/AI se activa y se activa inmediatamente después de la instalación o actualización a 9,16. Después de actualizar el clúster a ONTAP 9.16,1, ARP/AI se habilitará automáticamente para los volúmenes FlexVol nuevos y existentes, si ARP ya está habilitado para esos volúmenes.

link:enable-arp-ai-with-au.html["Más información sobre habilitar ARP/AI"]

.Actualizaciones automáticas ARP/AI
Para mantener una protección actualizada frente a las últimas amenazas de ransomware, ARP/AI ofrece actualizaciones automáticas frecuentes que se producen fuera de las cadencias habituales de actualizaciones y lanzamientos de ONTAP. Si lo ha hecholink:../update/enable-automatic-updates-task.html["actualizaciones automáticas activadas"], también podrá comenzar a recibir actualizaciones de seguridad automáticas a ARP/AI después de seleccionar actualizaciones automáticas para los archivos de seguridad. También puede elegir realizar estas actualizaciones manualmente y controlar cuándo se producen las actualizaciones.

A partir de ONTAP 9.16,1, las actualizaciones de seguridad para ARP/AI están disponibles con System Manager, además de las actualizaciones del sistema y del firmware.


IMPORTANT: La función ARP/AI actualmente solo admite NAS. Aunque la funcionalidad de actualización automática muestra la disponibilidad de nuevos archivos de seguridad para la implementación en System Manager, estas actualizaciones solo se aplican a la protección de cargas de trabajo de NAS.

link:arp-ai-automatic-updates.html["Obtenga más información sobre las actualizaciones ARP/AI"]



== Licencias y habilitación

El soporte ARP se incluye con el link:https://kb.netapp.com/onprem/ontap/os/ONTAP_9.10.1_and_later_licensing_overview["Licencia ONTAP ONE"^]. Si no tiene la licencia ONTAP One, hay otras licencias disponibles para usar ARP que varían en función de su versión de ONTAP.

[cols="2*"]
|===
| Lanzamientos de ONTAP | Licencia 


 a| 
ONTAP 9.11.1 y versiones posteriores
 a| 
Antiransomware



 a| 
ONTAP 9.10.1
 a| 
MT_EK_MGMT (gestión de claves multi-tenant)

|===
* Si va a actualizar de ONTAP 9.10,1 a ONTAP 9.11,1 o posterior y ARP ya está configurado en el sistema, no necesita instalar la nueva licencia Anti-ransomware. Para las nuevas configuraciones ARP, se requiere la nueva licencia.
* Si va a revertir de ONTAP 9.11.1 o posterior a ONTAP 9.10.1 y habilitó ARP con la licencia Anti-ransomware, verá un mensaje de advertencia y es posible que deba volver a configurar ARP.


link:../revert/anti-ransomware-license-task.html["Aprenda sobre cómo revertir ARP"].



== Estrategia de protección contra ransomware ONTAP

Una estrategia efectiva de detección de ransomware debe incluir más que una única capa de protección.

Una analogía sería las características de seguridad de un vehículo. No dependes de una sola característica, como un cinturón de seguridad, para protegerte por completo en caso de accidente. Las bolsas de aire, los frenos antibloqueo y la advertencia de colisión frontal son características de seguridad adicionales que conducirán a un resultado mucho mejor. La protección contra ransomware debe verse de la misma manera.

Si bien ONTAP incluye funciones como FPolicy, copias Snapshot, SnapLock y el asesor digital de Active IQ (también conocido como asesor digital) para ayudarle a proteger del ransomware, la siguiente información se centra en la función ARP integrada con funcionalidades de aprendizaje automático.

Para obtener más información sobre otras funciones antiransomware de ONTAP, consulte link:../ransomware-solutions/ransomware-overview.html["La cartera de protección de NetApp y ransomware"].



== Lo que ARP detecta

ARP está diseñado para proteger contra ataques de denegación de servicio en los que el atacante retiene datos hasta que se pague un rescate. ARP ofrece detección de ransomware en tiempo real basada en:

* Identificación de los datos entrantes como texto cifrado o sin formato.
* Análisis que detectan:
+
** **Entropía**: Una evaluación de la aleatoriedad de los datos en un archivo
** **Tipos de extensión de archivo**: Una extensión que no se ajusta al tipo de extensión normal
** **IOPS de archivo**: Un aumento en la actividad de volumen anormal con cifrado de datos (a partir de ONTAP 9.11.1)




ARP puede detectar la propagación de la mayoría de ataques de ransomware solo una pequeña cantidad de archivos se cifran, toman medidas automáticamente para proteger los datos y avisan de que se está produciendo un ataque sospechoso.


NOTE: Ningún sistema de detección o prevención de ransomware puede garantizar completamente la seguridad de un ataque de ransomware. Aunque es posible que un ataque no se detecte, ARP actúa como una capa adicional importante de defensa si el software antivirus no ha podido detectar una intrusión.



== Modos de aprendizaje y activos

Para todos los ARP que se ejecutan con ONTAP 9.10.1 a 9.15.1 y ARP que se usan para volúmenes FlexGroup con ONTAP 9.16.1, ARP tiene dos modos:

* *Modo de aprendizaje* (o modo “dry run”)
* *Modo activo* (o modo “habilitado”)



NOTE: Con ARP/AI a partir de ONTAP 9.16,1, no hay periodo de aprendizaje cuando ARP se utiliza con los volúmenes FlexVol. ARP/AI en volúmenes de FlexVol se habilita y se activa inmediatamente después de la instalación o actualización a 9.16.1. Si se utiliza ONTAP 9.16,1 y ARP con volúmenes FlexGroup, se sigue necesitando un período de aprendizaje antes de la transición al modo activo.

.Modo de aprendizaje
Para todo ARP que se ejecuta con ONTAP 9.10,1 a 9.15.1 y ARP que se usa para volúmenes FlexGroup con ONTAP 9.16,1, cuando se habilita ARP, se ejecuta en _learning mode_. En el modo de aprendizaje, el sistema ONTAP desarrolla un perfil de alerta basado en las áreas de análisis: Entropía, tipos de extensiones de archivos e IOPS de archivos. Después de ejecutar ARP en el modo de aprendizaje durante el tiempo suficiente para evaluar las características de la carga de trabajo, puede cambiar al modo activo y empezar a proteger los datos.

Se recomienda dejar ARP en modo de aprendizaje durante 30 días. A partir de ONTAP 9.13,1, ARP determina automáticamente el intervalo de aprendizaje óptimo y automatiza el switch, que puede ocurrir antes de 30 días.


TIP: El comando `security anti-ransomware volume workload-behavior show` muestra las extensiones de archivo que se han detectado en el volumen. Si ejecuta este comando al principio del modo de aprendizaje y muestra una representación precisa de los tipos de archivo, no debe utilizar esos datos como base para moverse al modo activo, ya que ONTAP sigue recopilando otras métricas.

.Modo activo
Para ARP que se ejecuta con ONTAP 9.10.1 a 9.15.1, ARP cambia a _modo activo_ después de completar el período de aprendizaje óptimo. Una vez que ARP ha cambiado al modo activo, ONTAP crea instantáneas ARP para proteger los datos si se detecta una amenaza.

En el modo activo, si una extensión de archivo se marca como anormal, debe evaluar la alerta. Puede actuar en la alerta para proteger sus datos o puede marcar la alerta como un falso positivo. Al marcar una alerta como falso positivo, se actualiza el perfil de alerta. Por ejemplo, si la alerta se activa con una nueva extensión de archivo y marca la alerta como un falso positivo, no recibirá una alerta la próxima vez que se observe la extensión de archivo.


NOTE: A partir de ONTAP 9.11.1, se pueden personalizar los parámetros de detección para ARP. Para obtener más información, consulte xref:manage-parameters-task.html[Administrar los parámetros de detección de ataques ARP].



== Evaluación de amenazas e instantáneas ARP

Cuando está activo y no está en modo de aprendizaje, ARP evalúa la probabilidad de amenaza en función de los datos entrantes medidos contra los análisis aprendidos. Se asigna una medición cuando ARP detecta una amenaza:

* *Bajo*: La detección más temprana de una anormalidad en el volumen (por ejemplo, se observa una nueva extensión de archivo en el volumen). Este nivel de detección solo está disponible en versiones anteriores a ONTAP 9.16,1 que no tienen ARP/AI.
* *Moderado*: Se observan múltiples archivos con la misma extensión de archivo Never-seen-before.
+
** En ONTAP 9.10.1, el umbral para escalar a moderado es de 100 archivos o más.
** A partir de ONTAP 9.11.1, la cantidad de archivo es modificable; su valor predeterminado es 20.




En un caso de amenaza baja, ONTAP detecta una anomalía y crea una copia Snapshot del volumen para crear el mejor punto de recuperación. ONTAP antepone el nombre de la instantánea ARP con `Anti-ransomware-backup` para que sea fácilmente identificable; por ejemplo, `Anti_ransomware_backup.2022-12-20_1248`.

La amenaza se escala a moderada después de que ONTAP ejecuta un informe de análisis para determinar si la anormalidad coincide con un perfil de ransomware. Cuando la probabilidad de ataque es moderada, ONTAP genera una notificación EMS que le solicita que evalúe la amenaza. ONTAP no envía alertas sobre amenazas bajas, sin embargo, a partir de ONTAP 9.14,1, puede xref:manage-parameters-task.html#modify-alerts[modificar la configuración de alertas]. Para obtener más información, consulte xref:respond-abnormal-task.html[Responda a actividades anormales].

Puede ver información sobre amenazas moderadas en la sección *Eventos* de System Manager o con `security anti-ransomware volume show` el comando. Los eventos de amenaza baja también se pueden ver con el `security anti-ransomware volume show` comando en versiones anteriores a ONTAP 9.16.1 que no tienen ARP/AI.

Las instantáneas de ARP individuales se conservan durante dos días. Si hay varias instantáneas ARP, se retienen durante cinco días de forma predeterminada. A partir de ONTAP 9.11.1, puede modificar la configuración de retención. Para obtener más información, consulte xref:modify-automatic-shapshot-options-task.html[Modifique las opciones de snapshots].



== Cómo recuperar los datos en ONTAP después de un ataque de ransomware

Cuando se sospecha de un ataque, el sistema realiza una instantánea del volumen en ese momento y bloquea esa copia. Si el ataque se confirma más tarde, el volumen se puede restaurar mediante la instantánea ARP.

Las instantáneas bloqueadas no se pueden eliminar por medios normales. Sin embargo, si más tarde decide marcar el ataque como un falso positivo, la copia bloqueada se eliminará.

Con el conocimiento de los ficheros afectados y el tiempo de ataque, es posible recuperar de forma selectiva los ficheros afectados de varias instantáneas, en lugar de simplemente revertir todo el volumen a una de las instantáneas.

De este modo, ARP se basa en la protección de datos ONTAP y la tecnología de recuperación ante desastres demostradas para responder a ataques de ransomware. Consulte los siguientes temas para obtener más información sobre cómo recuperar datos.

* link:../data-protection/restore-contents-volume-snapshot-task.html["Recuperar desde snapshots"]
* link:https://www.netapp.com/blog/smart-ransomware-recovery["Recuperación inteligente de ransomware"^]




== Protección con verificación multiadministrador para ARP

A partir de ONTAP 9.13.1, se recomienda habilitar la verificación multiadministrador (MAV) para que se necesiten dos o más administradores de usuarios autenticados para la configuración de protección autónoma contra ransomware (ARP). Para obtener más información, consulte link:../multi-admin-verify/enable-disable-task.html["Habilite la verificación multiadministradora"].
