---
sidebar: sidebar 
permalink: anti-ransomware/pause-task.html 
keywords: anti-ransomware, ransomware, pause, autonomous, protection, arp 
summary: 'Si espera eventos de carga de trabajo inusuales, puede suspender temporalmente y reanudar el análisis de la protección de ransomware autónoma (ARP) en cualquier momento.' 
---
= Detenga la protección de ransomware autónoma para excluir eventos de carga de trabajo del análisis
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Si espera eventos de carga de trabajo inusuales, puede suspender temporalmente y reanudar el análisis de la protección de ransomware autónoma (ARP) en cualquier momento.

.Lo que necesitará
* ARP se ejecuta en modo de aprendizaje o activo.


.Acerca de esta tarea
Durante una pausa de ARP, no se registran eventos ni se realiza ninguna acción para las nuevas escrituras. No obstante, la operación de análisis continúa para registros anteriores en segundo plano.


NOTE: No utilice la función antiransomware para pausar el análisis. Al hacerlo, se deshabilita ARP en el volumen y se pierde toda la información existente acerca del comportamiento de la carga de trabajo adquirida. Esto requeriría un reinicio del período de aprendizaje.

.Pasos
[role="tabbed-block"]
====
.System Manager
--
. Haga clic en *almacenamiento > volúmenes* y seleccione el volumen en el que desea pausar ARP.
. En la ficha Seguridad de la descripción general de volúmenes, haga clic en *Pausa anti-ransomware* en el cuadro *Anti-ransomware*.


--
.CLI
--
Poner en pausa ARP en un volumen:

`security anti-ransomware volume pause -vserver _svm_name_ -volume _vol_name_`

Para reanudar el procesamiento, utilice `resume` parámetro.

`security anti-ransomware volume resume -vserver _svm_name_ -volume _vol_name_`

--
====