---
sidebar: sidebar 
permalink: anti-ransomware/recover-data-task.html 
keywords: Restore data after an attack, anti-ransomware backup, restore data from snapshot copies, potential ransomware attack, ransomware attack, recovery snapshot copies are deleted, recover deleted snapshot copies, autonomous, ransomware, protection, arp 
summary: Las copias Snapshot denominadas Anti_ransomware_backup se crean cuando el ransomware detecta un ataque potencial. Puede restaurar datos desde estas copias antiransomware u otras copias de Snapshot. 
---
= Restaure los datos después de un ataque de ransomware
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Las copias Snapshot denominadas “Anti_ransomware_backup” se crean cuando la protección de ransomware autónoma (ARP) detecta un ataque potencial. Puede restaurar datos desde estas copias ARP o otras copias Snapshot.


NOTE: Si se produce un ataque de ransomware, consulte el artículo de la base de conocimientos link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Ransomware_prevention_and_recovery_in_ONTAP["Prevención y recuperación de ransomware en ONTAP"^] para obtener información adicional sobre la recuperación y la mitigación futura.

.Lo que necesitará
* ARP habilitado
* Se informa de ataques de ransomware potenciales


.Pasos
[role="tabbed-block"]
====
.System Manager
--
. Mostrar las copias Snapshot en volúmenes identificados en un ataque potencial: Haga clic en *almacenamiento > volúmenes*, seleccione el volumen y, a continuación, haga clic en la ficha copias Snapshot.
. Restaure las copias deseadas de acuerdo con estas instrucciones:link:../task_dp_recover_snapshot.html["Recuperar desde copias Snapshot"]


--
.CLI
--
. Mostrar las copias Snapshot en los volúmenes identificados con un posible ataque:
`volume snapshot show -vserver _svm_name_ -volume _vol_name_`
. Restaure las copias deseadas de acuerdo con estas instrucciones:link:../data-protection/restore-contents-volume-snapshot-task.html["Restaurar archivos desde copias snapshot"]


--
====