---
sidebar: sidebar 
permalink: anti-ransomware/use-cases-restrictions-concept.html 
keywords: anti-ransomware use cases and restrictions, anti-ransomware performance and frequency considerations, anti-ransomware workloads, anti-ransomware volume requirements, anti-ransomware performance, volumes, anti-ransomware encryption, anti-ransomware system configurations, autonomous ransomware protection, arp 
summary: En la versión actual, la protección contra ransomware es más adecuada en entornos NAS. En futuras versiones estará disponible compatibilidad con otros entornos. 
---
= Casos de uso y consideraciones sobre la protección de Ransomware autónoma
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Compatibilidad con plataformas de ONTAP:

* La función de protección de ransomware autónoma (ARP) está disponible para todos los sistemas de ONTAP en las instalaciones que empiezan con ONTAP 9.10.1.


Cargas de trabajo adecuadas:

* En almacenamiento NFS
* Directorios iniciales Windows o Linux
+
Debido a que los usuarios podían crear archivos con extensiones que no se detectaron en el período de aprendizaje, hay mayor posibilidad de falsos positivos en esta carga de trabajo.

* Imágenes y vídeo
+
Por ejemplo, registros de atención médica y datos de automatización de diseño electrónico (EDA).



A partir de ONTAP 9.12.1, ARP está disponible para estas configuraciones:

* Volúmenes protegidos con SnapMirror
* SVM protegidas con SnapMirror
* SVM habilitadas para migración (movilidad de datos de SVM)


Cargas de trabajo no adecuadas:

* Cargas de trabajo con una gran frecuencia de creación o eliminación de archivos (cientos de miles de archivos en solo unos segundos, por ejemplo, cargas de trabajo de prueba y desarrollo)
* ARP depende de la capacidad de reconocer un aumento inusual en la actividad de creación, cambio de nombre o eliminación de archivos. Si la aplicación en sí es el origen de la actividad del archivo, no se puede distinguir eficazmente de la actividad de ransomware
* Cargas de trabajo donde la aplicación o el host cifran los datos ARP depende de distinguir los datos entrantes como cifrados o no cifrados. Si la propia aplicación está cifrando los datos, se reduce la eficacia de la función. Sin embargo, la característica puede seguir funcionando según la actividad del archivo (eliminar, sobrescribir o crear, o crear o cambiar el nombre con una nueva extensión de archivo) y el tipo de archivo.


Configuraciones de sistema no compatibles:

* Entornos SAN
* Entornos ONTAP S3
* VMDK en NFS


Requisitos del volumen:

* Menos del 100% de su capacidad
* La ruta de unión debe estar activa


Tipos de volúmenes no compatibles:

* Volúmenes sin conexión
* Volúmenes restringidos
* Volúmenes de SnapLock
* Volúmenes FlexGroup (a partir de ONTAP 9.13.1, se admiten los volúmenes FlexGroup)
* Volúmenes FlexCache (ARP es compatible con los volúmenes FlexVol de origen, pero no con los volúmenes de caché)
* Volúmenes solo DE SAN
* Volúmenes de máquinas virtuales de almacenamiento detenidas
* Volúmenes raíz de equipos virtuales de almacenamiento




== Interoperabilidad de SnapMirror y ARP

A partir de ONTAP 9.12.1, ARP se admite en los volúmenes de destino de SnapMirror. Si un volumen de origen de SnapMirror tiene la función ARP habilitada, el volumen de destino de SnapMirror adquiere automáticamente el estado de configuración ARP (aprendizaje, habilitado, etc.), datos de entrenamiento ARP y Snapshot creadas con ARP del volumen de origen. No se requiere habilitación explícita.

Mientras que el volumen de destino consta de copias Snapshot de solo lectura (RO), no se realiza el procesamiento ARP en sus datos. Sin embargo, cuando el volumen de destino de SnapMirror se convierte en Read-write (RW), ARP se habilita automáticamente en el volumen de destino que se convierte en RW. El volumen de destino no requiere ningún procedimiento de aprendizaje adicional además de lo que ya se ha registrado en el volumen de origen.

En ONTAP 9.10.1 y 9.11.1, SnapMirror no transfiere el estado de configuración de ARP, los datos de formación y las copias Snapshot de los volúmenes de origen a destino. Por ello, cuando el volumen de destino de SnapMirror se convierte en RW, ARP en el volumen de destino debe habilitarse explícitamente en el modo de aprendizaje después de la conversión.



== Consideraciones de rendimiento y frecuencia de ARP

La función ARP puede tener un impacto mínimo en el rendimiento del sistema según se mide en el rendimiento y las IOPS máximas. El impacto de la función ARP depende en gran medida de las cargas de trabajo de volumen. Para la mayoría de las cargas de trabajo típicas o comunes, se recomiendan los siguientes límites de configuración:

[cols="30,20,30"]
|===
| Características de las cargas de trabajo | Límite de volúmenes recomendado por nodo | Degradación del rendimiento cuando se supera el límite de volumen por nodo pasada:[*] 


| Con una gran cantidad de lecturas o se pueden comprimir los datos. | 150 | 4 % del valor máximo de IOPS 


| Gran cantidad de escrituras y los datos no se pueden comprimir. | 60 | 10 % del valor máximo de IOPS 
|===
Aprobado:[*] el rendimiento del sistema no se degrada más allá de estos porcentajes, independientemente del número de volúmenes añadidos por encima de los límites recomendados.

Dado que los análisis de ARP se ejecutan en una secuencia priorizada, a medida que aumenta el número de volúmenes protegidos, el análisis se ejecutan en cada volumen con menos frecuencia.



== Cómo funcionan las copias Snapshot automáticas cuando se detecta ransomware

Para obtener el mejor punto de recuperación posible, ARP crea una copia Snapshot automática tan pronto como detecta una actividad anormal de los archivos. Sin embargo, ARP no Marca inmediatamente una alerta; más bien, el análisis debe ejecutarse y confirmar que la actividad sospechosa coincide con un perfil de ransomware antes de generar una alerta. Este proceso puede llevar hasta 60 minutos. Si el análisis determina que la actividad no es sospechosa, no se genera una alerta, pero la copia snapshot creada automáticamente permanece presente en el sistema de archivos durante un mínimo de dos días.

A partir de ONTAP 9.11.1, puede controlar el número y el período de retención de las copias ARP Snapshot que se generan automáticamente en respuesta a ataques sospechosos de ransomware. Aprenda cómo link:modify-automatic-shapshot-options-task.html["Modifique las opciones de las copias automáticas Snapshot"].



== Verificación multiadministradora con volúmenes protegidos con protección autónoma contra ransomware (ARP)

A partir de ONTAP 9.13.1, puede habilitar la verificación multiadministrador (MAV) para obtener seguridad adicional con ARP. MAV garantiza que al menos dos o más administradores autenticados deben desactivar ARP, pausar ARP o marcar un ataque sospechoso como falso positivo en un volumen protegido. Aprenda cómo link:../multi-admin-verify/enable-disable-task.html["Habilite MAV para volúmenes protegidos por ARP"^]. Deberá definir administradores para un grupo MAV y crear reglas MAV para el `security anti-ransomware volume disable`, `security anti-ransomware volume pause`, y. `security anti-ransomware volume attack clear-suspect` Comandos ARP que desea proteger. Cada administrador del grupo MAV debe aprobar cada nueva solicitud de regla y. link:../multi-admin-verify/enable-disable-task.html["Vuelva a agregar la regla MAV"^] Dentro de los ajustes de MAV.
