---
sidebar: sidebar 
permalink: snapmirror-active-sync/convert-relationships-task.html 
keywords: SM-BC, SMBC, convert, SnapMirror synchronous, zero RPO, zero recovery time objective, zero RTO, existing, snapmirror active sync 
summary: Realizar la conversión entre protección simétrica y asimétrica en su configuración de sincronización activa de SnapMirror. 
---
= Convertir el tipo de relación de sincronización activa de SnapMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.15.1, se puede convertir entre tipos de protección de sincronización activa de SnapMirror: De asimétrica a activo-activo simétrico y viceversa.



== Convertir a una relación activo-activo simétrica

Puede convertir una relación de sincronización activa de SnapMirror con una protección asimétrica para usar activo-activo simétrico.

.Antes de empezar
* Ambos clústeres deben ejecutar ONTAP 9.15.1 o una versión posterior.
* Las configuraciones activo-activo simétricas requieren `AutomatedFailoverDuplex` la política de protección. Alternativamente, usted puede xref:../data-protection/create-custom-replication-policy-concept.html[Crear una política de SnapMirror personalizada] siempre que el `-type` IS `automated-failover-duplex`.


[role="tabbed-block"]
====
.System Manager
--
.Pasos para una configuración uniforme
. Quite el igroup de destino:
+
.. En el clúster de destino, vaya a **Hosts** > **Grupos de iniciadores de SAN**.
.. Seleccione el igroup con la relación SnapMirror y, a continuación, **Eliminar**.
.. En el cuadro de diálogo, seleccione el cuadro **Desasignar las LUN asociadas** y luego **Eliminar**.


. Edite la relación de sincronización activa de SnapMirror.
+
.. Navegue hasta **Protección** > **Relaciones**.
.. Seleccione el menú de kabob junto a la relación que desea modificar y luego **Editar**.
.. Modifique la **Política de Protección** a AutomatedFailoverDuplex.
.. Al seleccionar `AutoMatedFailoverDuplex` se muestra un cuadro de diálogo para modificar la configuración de proximidad del host. Para los iniciadores, seleccione la opción apropiada para **Iniciador proximal a** y luego **Guardar**.
.. Selecciona **Guardar**.


. En el menú **Protección**, confirme que la operación se ha realizado correctamente cuando la relación se muestre como `InSync`.


.Pasos para una configuración no uniforme
. Quite el igroup de destino:
+
.. En el sitio secundario, vaya a **HOSTS** > **Grupos de iniciadores SAN**.
.. Seleccione el igroup con la relación SnapMirror y, a continuación, **Eliminar**.
.. En el cuadro de diálogo, seleccione el cuadro **Desasignar las LUN asociadas** y luego **Eliminar**.


. Cree un nuevo igroup:
+
.. En el menú **Grupos de iniciadores de SAN** del sitio de destino, seleccione **Agregar**.
.. Proporcione un **Nombre**, seleccione el **Sistema Operativo del Host** y, a continuación, elija **Miembros del Grupo Iniciador**.
.. Selecciona **Guardar**.


. Asigne el nuevo igroup a las LUN de destino.
+
.. Vaya a **Almacenamiento** > **LUN**.
.. Seleccione todas las LUN que desea asignar al igroup.
.. Seleccione **Más** y luego **Asignar a grupos de iniciadores**.


. Edite la relación de sincronización activa de SnapMirror.
+
.. Navegue hasta **Protección** > **Relaciones**.
.. Seleccione el menú de kabob junto a la relación que desea modificar y luego **Editar**.
.. Modifique la **Política de Protección** a AutomatedFailoverDuplex.
.. Al seleccionar AutoMatedFailoverDuplex, se inicia la opción de modificar la configuración de proximidad del host. Para los iniciadores, seleccione la opción apropiada para **Iniciador proximal a** y luego **Guardar**.
.. Selecciona **Guardar**.


. En el menú **Protección**, confirme que la operación se ha realizado correctamente cuando la relación se muestre como `InSync`.


--
.CLI
--
.Pasos para una configuración uniforme
. Modifique la política de SnapMirror de `AutomatedFailover` a `AutomatedFailoverDuplex`:
+
`snapmirror modify -destination-path <destination_path> -policy AutomatedFailoverDuplex`

. Al modificar la política se desencadena una resincronización. Espere a que la resincronización finalice y confirme que la relación es `Insync`:
+
`snapmirror show -destination-path <destination_path>`

. Si los hosts existentes son locales en el clúster primario, añada el host al segundo clúster y establezca la conectividad con el respectivo acceso a cada clúster.
. En el sitio secundario, elimine los mapas de LUN de los iGroups asociados con hosts remotos.
+

NOTE: Asegúrese de que el igroup no contiene mapas de LUN no replicadas.

+
`SiteB::> lun mapping delete -vserver <svm_name> -igroup <igroup> -path <>`

. En la ubicación principal, defina el nivel de privilegio en `advanced`:
+
`SiteA::> set -privilege advanced`

. Modifique la configuración del iniciador para los hosts existentes a fin de establecer la ruta proximal de los iniciadores en el clúster local.
+
`SiteA::*> igroup initiator add-proximal-vserver -vserver <svm_name> -initiator <host> -proximal-vserver <server>`

+

NOTE: Puede volver a establecer el nivel de privilegio en admin después de completar este paso.

. Añada un igroup y un iniciador nuevos para los hosts nuevos y configure la proximidad de host para la afinidad de host con su sitio local. Replicación de igroup ennable para replicar la configuración e invertir la localidad de host en el clúster remoto.
+
``
SiteA::> igroup modify -vserver vsA -igroup ig1 -replication-peer vsB
SiteA::> igroup initiator add-proximal-vserver -vserver vsA -initiator host2 -proximal-vserver vsB
``

. Detecte las rutas en los hosts y compruebe que los hosts tengan una ruta de activo/optimizada al LUN de almacenamiento desde el clúster preferido
. Ponga en marcha la aplicación y distribuya las cargas de trabajo de los equipos virtuales entre los clústeres.


.Pasos para una configuración no uniforme
. Modifique la política de SnapMirror de `AutomatedFailover` a `AutomatedFailoverDuplex`:
+
`snapmirror modify -destination-path <destination_path> -policy AutomatedFailoverDuplex`

. Al modificar la política se desencadena una resincronización. Espere a que la resincronización finalice y confirme que la relación es `Insync`:
+
`snapmirror show -destination-path <destination_path>`

. Si los hosts existentes son locales en el clúster primario, añada el host al segundo clúster y establezca la conectividad con el respectivo acceso a cada clúster.
. En el sitio secundario, añada un nuevo igroup e iniciador para los nuevos hosts y establezca la proximidad de host para la afinidad del host con su sitio local. Asigne las LUN al igroup.
+
``
SiteB::> igroup create -vserver <svm_name> -igroup <igroup>
SiteB::> igroup add -vserver <svm_name> -igroup  <igroup> -initiator <host_name>
SiteB::> lun mapping create -igroup  <igroup> -path <path_name>
``

. Detecte las rutas en los hosts y compruebe que los hosts tengan una ruta de activo/optimizada al LUN de almacenamiento desde el clúster preferido
. Ponga en marcha la aplicación y distribuya las cargas de trabajo de los equipos virtuales entre los clústeres.


--
====


== Convertir de activo/activo simétrico a una relación asimétrica

Si configuró una protección activo-activo simétrica, puede convertir la relación en protección asimétrica mediante la interfaz de línea de comandos de ONTAP.

.Pasos
. Mueva todas las cargas de trabajo de la máquina virtual al host local al clúster de origen.
. Quite la configuración del igroup para los hosts que no gestionan las instancias de la máquina virtual y, a continuación, modifique la configuración del igroup para finalizar la replicación de igroup.
+
`igroup modify -vserver <svm_name> -igroup <igroup> -replication-peer -`

. En el sitio secundario, desasigne las LUN.
+
`SiteB::> lun mapping delete -vserver <svm_name> -igroup <igroup> -path <>`

. En el sitio secundario, elimine la relación activo-activo simétrica.
+
`SiteB::> snapmirror delete -destination-path <destination_path>`

. En el sitio principal, libere la relación activo-activo simétrica.
`SiteA::> snapmirror release -destination-path <destination_path> -relationship-info-only true`
. Desde el sitio secundario, cree una relación con el mismo conjunto de volúmenes con `AutomatedFailover` la política para volver a sincronizar la relación.
+
``
SiteB::> snapmirror create -source-path <source_path> -destination-path <destination_path> -cg-item-mappings <source:@destination> -policy AutomatedFailover
SiteB::> snapmirror resync -destination-path vs1:/cg/cg1_dst -policy <policy_type>
``

+

NOTE: El grupo de coherencia en el sitio secundario debe link:../consistency-groups/delete-task.html["se debe eliminar"]volver a crear la relación. Los volúmenes de destino link:https://kb.netapp.com/onprem/ontap/dp/SnapMirror/How_to_change_a_volume_type_from_RW_to_DP["Se debe convertir a tipo DP"^]. Para convertir los volúmenes en DP, ejecute `snapmirror resync` el comando con una política `MirrorAndVault` que no sea-`AutomatedFailover`: , `MirrorAllSnapshots` O `Sync`.

. Confirme que la relación Mirror State es `Snapmirrored` el Estado de la relación es `Insync`.
+
`snapmirror show -destination-path _destination_path_`

. Vuelva a detectar las rutas desde el host.

