---
sidebar: sidebar 
permalink: snapmirror-active-sync/delete-fails-takeover-task.html 
keywords: troubleshooting, SM-BC, SMBC, SnapMirror, delete, takeover, consistency group, snapmirror active sync 
summary: 'Cuando ONTAP 9.9.1 está instalado en un clúster, al ejecutar el comando  `snapmirror delete` El comando falla cuando una relación de grupo de consistencia de sincronización activa de SnapMirror está en estado de toma de control.' 
---
= Se produce un error en la operación de eliminación de SnapMirror en estado de takover
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


.Tema:
[role="lead"]
Cuando ONTAP 9.9.1 está instalado en un clúster, al ejecutar el comando  `snapmirror delete` El comando falla cuando una relación de grupo de consistencia de sincronización activa de SnapMirror está en estado de toma de control.

....
C2_cluster::> snapmirror delete  vs1:/cg/dd

Error: command failed: RPC: Couldn't make connection
....
.Solución
Cuando los nodos en una relación de sincronización activa de SnapMirror están en estado de toma de control, realice la operación de eliminación y liberación de SnapMirror con la opción "-force" establecida en verdadera.

....
C2_cluster::> snapmirror delete  vs1:/cg/dd -force true

Warning: The relationship between source "vs0:/cg/ss" and destination
         "vs1:/cg/dd" will be deleted, however the items of the destination
         Consistency Group might not be made writable, deletable, or modifiable
         after the operation. Manual recovery might be required.
Do you want to continue? {y|n}: y
Operation succeeded: snapmirror delete for the relationship with destination "vs1:/cg/dd".
....
.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["snapmirror elimina"^]

