---
sidebar: sidebar 
permalink: snapmirror-active-sync/limits-reference.html 
keywords: SM-BC, SMBC, restrictions, consistency group, endpoint limits, solaris, aix, hp-ux, fanout, snapmirror active sync 
summary: Hay varias restricciones y limitaciones adicionales cuando se usa la sincronización activa de SnapMirror. 
---
= Límites de objetos para la sincronización activa de ONTAP SnapMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cuando se prepare para usar la sincronización activa de SnapMirror, tenga en cuenta los siguientes límites de objetos.



== Grupos de consistencia en un clúster

Los límites de grupos de consistencia de un clúster con sincronización activa de SnapMirror se calculan en función de las relaciones y dependen de la versión de ONTAP utilizada. Los límites son independientes de la plataforma.

|===
| Versión de ONTAP | Número máximo de relaciones 


| ONTAP 9.11.1 y versiones posteriores | 50* 


| ONTAP 9.10.1 | 20 


| ONTAP 9.9.1 | 5 
|===
{Asterisk} A partir de ONTAP 9.16.1, la sincronización activa de SnapMirror admite clústeres de cuatro nodos en configuraciones activo-activo simétricas. En un clúster de cuatro nodos, se admiten 100 grupos de consistencia.



== Volúmenes por grupo de coherencia

El número máximo de volúmenes por grupo de coherencia con la sincronización activa de SnapMirror es independiente de la plataforma.

|===
| Versión de ONTAP | Cantidad máxima de volúmenes admitidos en una relación de grupo de consistencia 


| ONTAP 9.15.1 y versiones posteriores | 80 


| ONTAP 9.10.1-9.14.1 | 16 


| ONTAP 9.9.1 | 12 
|===


== Volúmenes

Los límites de volúmenes en la sincronización activa de SnapMirror se calculan en función del número de extremos, no del número de relaciones. Un grupo de consistencia con 12 volúmenes contribuye con 12 extremos en el clúster primario y secundario. Tanto la sincronización activa de SnapMirror como las relaciones síncronas de SnapMirror contribuyen al número total de extremos.


IMPORTANT: Estos límites se aplican a los sistemas FAS, AFF y ASA . Si tiene un sistema ASA r2 (ASA A1K, ASA A90, ASA A70, ASA A50, ASA A30 o ASA A20), consulte link:https://docs.netapp.com/us-en/asa-r2/data-protection/manage-consistency-groups.html["Documentación de ASA r2"^] .

En la siguiente tabla se incluyen los puntos finales máximos por plataforma.

|===
| Plataforma 3+| Extremos por alta disponibilidad para sincronización activa de SnapMirror 3+| Extremos de sincronización activa de SnapMirror y sincronización general por alta disponibilidad 


|  | ONTAP 9.11.1 y versiones posteriores | ONTAP 9.10.1 | ONTAP 9.9.1 | ONTAP 9.11.1 y versiones posteriores | ONTAP 9.10.1 | ONTAP 9.9.1 


| AFF | 400* | 200 | 60 | 400 | 200 | 80 


| ASA | 400* | 200 | 60 | 400 | 200 | 80 
|===
{Asterisk} A partir de ONTAP 9.16.1, la sincronización activa de SnapMirror admite clústeres de cuatro nodos en configuraciones activo-activo simétricas. El límite total para un clúster de cuatro nodos es de 800 extremos.



== Límites DE objetos DE SAN

En la siguiente tabla se incluyen los límites de objetos SAN. Los límites se aplican independientemente de la plataforma.

|===
| Objeto en una relación de sincronización activa de SnapMirror | Cuente 


| LUN por volumen  a| 
* 256 (ONTAP 9.9.1 - ONTAP 9.15.0)
* 512 (ONTAP 9.15.1 y posterior)




| Número de LUN, espacios de nombres o unidades de almacenamiento únicos por solución de sincronización activa SnapMirror 2 x 2 | 4.096 


| Número de LUN, espacios de nombres o unidades de almacenamiento únicos por solución de sincronización activa SnapMirror 4 x 4 (disponible a partir de ONTAP 9.16.1) | 6.144 


| LIF por SVM (con al menos un volumen en una relación de sincronización activa de SnapMirror ) | 256 


| LIF entre clústeres por nodo | 4 


| LIF entre clústeres por clúster | 8 
|===


== Límites de objetos NVMe

A partir de ONTAP 9.17.1, la sincronización activa de SnapMirror es compatible con el protocolo NVMe. Los límites de objetos NVMe se incluyen en la siguiente tabla.

|===
| Máximo de objetos en una relación de sincronización activa de SnapMirror | Cuente 


| Número de mapas de espacios de nombres por nodo | 4K 


| Tamaño del clúster | 2 nodos 


| Número de grupos de consistencia por par de HA | 50 


| Número de volúmenes en un solo grupo de consistencia de sincronización activa de NVMe SnapMirror | 80 


| Número de volúmenes en un par HA | 400 


| Subsistemas NVMe por grupo de consistencia | 16 


| Mapas de espacios de nombres por grupo de consistencia | 256 
|===
.Información relacionada
* link:https://hwu.netapp.com/["Hardware Universe"^]
* link:../consistency-groups/limits.html["Límites del grupo de consistencia"^]

