---
sidebar: sidebar 
permalink: snapmirror-active-sync/mediator-install-task.html 
keywords: SM-BC, SMBC, cluster, peering, ONTAP Mediator, initialize, snapmirror active sync 
summary: La sincronización activa de SnapMirror requiere que instale e inicialice el Mediador de ONTAP y garantice una conexión de clústeres adecuada. 
---
= Configurar el mediador de ONTAP y los clústeres para la sincronización activa de snapmirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror, la sincronización activa utiliza clústeres con conexión entre iguales para garantizar que los datos estén disponibles en caso de conmutación por error. ONTAP Mediator es un recurso clave que garantiza la continuidad del negocio y supervisa el estado de cada clúster. Para configurar la sincronización activa de SnapMirror, primero debe instalar ONTAP Mediator y asegurarse de que los clústeres primario y secundario están configurados correctamente.

Una vez que haya instalado ONTAP Mediator y configurado los clústeres, debe hacerlo <<initialize-the-ontap-mediator>> Mediador ONTAP para su uso con sincronización activa de SnapMirror. Entonces debe hacerlo xref:../protect-task.html[Cree, inicialice y asigne el grupo de consistencia para la sincronización activa de SnapMirror].



== Mediador ONTAP

El mediador de ONTAP establece un quórum para los clústeres de ONTAP en una relación de sincronización activa de SnapMirror. Coordina la conmutación automática al nodo de respaldo cuando se detecta un fallo, al determinar qué clúster actúa como principal y garantizar que se sirven los datos a y desde el destino correcto.

.Requisitos previos para el Mediador ONTAP
* El Mediador ONTAP incluye su propio conjunto de requisitos previos. Debe cumplir con estos requisitos previos antes de instalar el mediador.
+
Para obtener más información, consulte link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["Prepare la instalación del servicio Mediador ONTAP"^].

* De forma predeterminada, el Mediador ONTAP proporciona servicio a través del puerto TCP 31784. Debe asegurarse de que el puerto 31784 esté abierto y disponible entre los clústeres de ONTAP y el mediador.




== Instale ONTAP Mediator y confirme la configuración del cluster

Continúe con cada uno de los pasos siguientes. Para cada paso, debe confirmar que se ha realizado la configuración específica. Utilice el enlace que se incluye después de cada paso para obtener más información según sea necesario.

.Pasos
. Instale el servicio Mediator de ONTAP antes de asegurarse de que los clústeres de origen y destino están configurados correctamente.
+
xref:../mediator/index.html[Prepárese para instalar o actualizar el servicio de Mediador de ONTAP]

. Confirme que existe una relación de paridad entre los clústeres.
+

NOTE: El espacio IP predeterminado es necesario en la sincronización activa de SnapMirror para las relaciones entre iguales de clústeres. No se admite un espacio IP personalizado.

+
xref:../task_dp_prepare_mirror.html[Configure las relaciones de paridad]

. Confirmar que las máquinas virtuales de almacenamiento se crean en cada clúster.
+
xref:../smb-config/create-svms-data-access-task.html[Creación de una SVM]

. Confirmar que existe una relación entre iguales entre las máquinas virtuales de almacenamiento en cada clúster.
+
xref:../peering/create-intercluster-svm-peer-relationship-93-later-task.html[Creación de una relación de paridad de SVM]

. Confirme que los volúmenes existen para sus LUN.
+
xref:../smb-config/create-volume-task.html[Creación de un volumen]

. Confirmar que se crea al menos un LIF SAN en cada nodo del clúster.
+
link:../san-admin/lifs-cluster-concept.html["Consideraciones para los LIF en un entorno SAN de clúster"]

+
link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/GUID-4B666C44-694A-48A3-B0A9-517FA7FD2502.html?cp=13_6_4_0["Crear una LIF"^]

. Confirmar que las LUN necesarias se crean y asignan a un igroup, que se utiliza para asignar las LUN al iniciador en el host de la aplicación.
+
xref:../san-admin/create-luns-mapping-igroups-task.html[Cree LUN y asigne iGroups]

. Vuelva a analizar el host de la aplicación para detectar todos los LUN nuevos.




== Inicialice el mediador de ONTAP para la sincronización activa de SnapMirror

Una vez que haya instalado ONTAP Mediator y confirmado la configuración del clúster, debe inicializar ONTAP Mediator para la supervisión del clúster. Puede inicializar ONTAP Mediator mediante System Manager o la CLI de ONTAP.

[role="tabbed-block"]
====
.System Manager
--
Con System Manager, puede configurar el servidor ONTAP Mediator para una conmutación automática al respaldo. También puede reemplazar SSL y CA autofirmados por el certificado SSL y CA validados de terceros si aún no lo ha hecho.


IMPORTANT: A partir de ONTAP 9,8 a 9.14.1, la sincronización activa de SnapMirror se conoce como continuidad del negocio de SnapMirror (SM-BC).

.Pasos
. Vaya a *Protección > Descripción general > Mediador > Configurar*.
. Seleccione *Agregar* e introduzca la siguiente información del servidor de ONTAP Mediator:
+
** Dirección IPv4
** Nombre de usuario
** Contraseña
** Certificado




--
.CLI
--
Puede inicializar el mediador de ONTAP desde el clúster primario o secundario mediante la CLI de ONTAP. Cuando emita el `mediator add` Comando en un clúster, el Mediador ONTAP se agrega automáticamente al otro clúster.

.Pasos
. Inicialice Mediator en uno de los grupos:
+
`snapmirror mediator add -mediator-address IP_Address -peer-cluster cluster_name -username user_name`

+
*ejemplo*

+
....
cluster1::> snapmirror mediator add -mediator-address 192.168.10.1 -peer-cluster cluster2 -username mediatoradmin
Notice: Enter the mediator password.

Enter the password: ******
Enter the password again: ******
....
. Compruebe el estado de la configuración del Mediator:
+
`snapmirror mediator show`

+
....
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
192.168.10.1     cluster-2        connected         true
....
+
`Quorum Status` Indica si las relaciones del grupo de coherencia SnapMirror se sincronizan con el mediador, un estado de `true` indica una sincronización correcta.



--
====