---
sidebar: sidebar 
permalink: snapmirror-active-sync/monitor-task.html 
keywords: SM-BC, SMBC, monitoring, Mediator status, EMS, errors, planned failover status, automatic unplanned failover status, , snapmirror active sync 
summary: Existen varios componentes y operaciones de sincronización activa de SnapMirror que puede supervisar. 
---
= Supervise las operaciones de sincronización activa de SnapMirror en ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede supervisar las siguientes operaciones de sincronización activa de SnapMirror para garantizar el estado de la configuración de sincronización activa de SnapMirror:

* Mediador ONTAP
* Operaciones de conmutación por error planificadas
* Operaciones automáticas de conmutación al respaldo no planificadas
* Disponibilidad de sincronización activa de SnapMirror



NOTE: A partir de ONTAP 9.15.1, System Manager muestra el estado de su relación de sincronización activa de SnapMirror en cualquier clúster. También puede supervisar el estado de los mediadores de ONTAP desde cualquier clúster en System Manager.



== Mediador ONTAP

Durante las operaciones normales, el estado Mediador de ONTAP debe estar conectado. Si está en cualquier otro estado, esto podría indicar una condición de error. Es posible revisar el link:https://docs.netapp.com/us-en/ontap-ems-9131/sm-mediator-events.html["Mensajes del sistema de gestión de eventos (EMS)"^] para determinar el error y las acciones correctivas adecuadas.



== Operaciones de conmutación por error planificadas

Puede supervisar el estado y el progreso de una operación de conmutación al respaldo planificada mediante `snapmirror failover show` el comando. Por ejemplo:

....
ClusterB::> snapmirror failover start -destination-path vs1:/cg/dcg1
....
Una vez finalizada la operación de conmutación por error, puede supervisar el estado de protección de SnapMirror desde el nuevo clúster de destino. Por ejemplo:

....
ClusterA::> snapmirror show
....
Consulte el link:https://docs.netapp.com/us-en/ontap-ems-9131/smbc-pfo-events.html["Referencia EMS"^] para obtener más información acerca de los mensajes de eventos y las acciones correctivas.



== Operaciones automáticas de conmutación al respaldo no planificadas

Durante una conmutación al respaldo automática no planificada, puede supervisar el estado de la operación con `snapmirror failover show` el comando.

....
ClusterB::> snapmirror failover show -instance
Start Time: 9/23/2020 22:03:29
         Source Path: vs1:/cg/scg3
    Destination Path: vs3:/cg/dcg3
     Failover Status: completed
        Error Reason:
            End Time: 9/23/2020 22:03:30
Primary Data Cluster: cluster-2
Last Progress Update: -
       Failover Type: unplanned
  Error Reason codes: -
....
Consulte el link:https://docs.netapp.com/us-en/ontap-ems-9131/smbc-aufo-events.html["Referencia EMS"^] para obtener más información acerca de los mensajes de eventos y las acciones correctivas.



== Disponibilidad de sincronización activa de SnapMirror

Puede comprobar la disponibilidad de la relación de sincronización activa de SnapMirror mediante una serie de comandos, ya sea en el clúster principal, el clúster secundario o en ambos.

Los comandos que utilice incluyen `snapmirror mediator show` el comando en el cluster primario y secundario para comprobar el estado de la conexión y del quórum, el `snapmirror show` comando y el `volume show` comando. Por ejemplo:

....
SMBC_A::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_B           connected         true

SMBC_B::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_A           connected         true

SMBC_B::*> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs0:/cg/cg1 XDP  vs1:/cg/cg1_dp Snapmirrored Insync -         true    -
vs0:vol1    XDP  vs1:vol1_dp  Snapmirrored Insync   -         true    -
2 entries were displayed.

SMBC_A::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1
vserver volume is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------ -------------- ------------------------ --------------
vs0     vol1   true           false                    Consensus

SMBC_B::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1_dp
vserver volume  is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------- -------------- ------------------------ --------------
vs1     vol1_dp false          true                     No-consensus
....
.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-failover-show.html["espectáculo de conmutación por error de SnapMirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-failover-start.html["inicio de conmutación por error de snapmirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-mediator-show.html["Programa de mediación de Snapmirror"^]

