---
sidebar: sidebar 
permalink: snapmirror-active-sync/troubleshoot-site-a-mediator-task.html 
keywords: SM-BC, SMBC, troubleshooting, connectivity, consensus, snapmirror active sync 
summary: Solución de problemas del enlace entre el sitio A y el mediador de ONTAP inactivo y el sitio B inactivo. 
---
= Enlace entre el sitio A y el mediador caído y el sitio B caído
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cuando use SnapMirror, puede perder conectividad entre ONTAP Mediator o los clústeres con conexión entre iguales. Puede diagnosticar el problema si se comprueba la conexión, la disponibilidad y el estado de consenso de las distintas partes de la relación de sincronización activa de SnapMirror y, a continuación, se reanuda la conexión forzosamente.

[cols="3"]
|===
| Qué comprobar | Comando CLI | Indicador 


| Mediador del Sitio A | `snapmirror mediator show` | El estado de conexión se muestra como `unreachable` 


| Conectividad del centro B. | `cluster peer show` | Disponibilidad se muestra como `unavailable` 


| El estado de consenso del volumen de sincronización activa de SnapMirror | `volume show _volume_name_ -fields smbc-consensus` | La `sm-bc consensus` se muestra el campo `Awaiting-consensus` 
|===
Para obtener información adicional acerca del diagnóstico y la resolución de este problema, consulte el artículo de la base de conocimientos link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/Link_between_Site_A_and_Mediator_down_and_Site_B_down_when_using_SM-BC["Enlace entre el sitio A y Mediator Down y el sitio B inactivo cuando se usa la sincronización activa de SnapMirror"^].

Obtenga más información sobre `cluster peer show` en el link:https://docs.netapp.com/us-en/ontap-cli/cluster-peer-show.html["Referencia de comandos de la ONTAP"^].
