---
permalink: smb-hyper-v-sql/configure-vss-shadow-copy-directory-depth-task.html 
sidebar: sidebar 
keywords: configure, vss, shadow, copy, directory, depth, hyper, v, smb, share 
summary: Opcionalmente, puede configurar la profundidad máxima de directorios dentro de recursos compartidos SMB en los que crear copias de sombra. Este parámetro resulta útil si desea controlar manualmente el nivel máximo de subdirectorios en los que ONTAP debe crear instantáneas. 
---
= Configurar la profundidad del directorio de copia de sombra de VSS (para Hyper-V mediante recursos compartidos de SMB)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Opcionalmente, puede configurar la profundidad máxima de directorios dentro de recursos compartidos SMB en los que crear copias de sombra. Este parámetro resulta útil si desea controlar manualmente el nivel máximo de subdirectorios en los que ONTAP debe crear instantáneas.

.Antes de empezar
La función de copia de sombra VSS debe estar activada.

.Acerca de esta tarea
El valor predeterminado es crear instantáneas para un máximo de cinco subdirectorios. Si el valor se establece en `0`, ONTAP crea instantáneas para todos los subdirectorios.

[NOTE]
====
Aunque puede especificar que la profundidad del directorio del conjunto de instantáneas incluya más de cinco subdirectorios o todos los subdirectorios, existe el requisito de Microsoft de que la creación del conjunto de instantáneas se lleve a cabo en 60 segundos. La creación del conjunto de instantáneas falla si no se puede completar en este momento. La profundidad del directorio de instantáneas que elija no debe hacer que el tiempo de creación supere el límite de tiempo.

====
.Pasos
. Configure el nivel de privilegio en Advanced:
+
`*set -privilege advanced*`

. Establezca la profundidad del directorio de copia de sombra VSS en el nivel deseado:
+
`*vserver cifs options modify -vserver _vserver_name_ -shadowcopy-dir-depth integer*`

+
`*vserver cifs options modify -vserver vs1 -shadowcopy-dir-depth 6*`

. Vuelva al nivel de privilegio de administrador:
+
`*set -privilege admin*`


