---
permalink: smb-hyper-v-sql/display-nondisruptive-status-health-task.html 
sidebar: sidebar 
keywords: display, nondisruptive, operation, status, system, health, monitor, cifs, ndo, alert 
summary: Puede usar los comandos de estado del sistema para mostrar información sobre el estado general del sistema del clúster y el estado del subsistema CIFS-NDO, para responder a alertas, configurar alertas futuras y para mostrar información sobre la configuración de la supervisión del estado. 
---
= Muestre el estado de funcionamiento no disruptivo mediante la supervisión del estado del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `system health` Comandos para mostrar información sobre el estado general del sistema del clúster y el estado del subsistema CIFS-NDO, para responder a las alertas, configurar alertas futuras y mostrar información sobre cómo se configura la supervisión del estado.

.Pasos
. Supervise el estado realizando la acción correspondiente:
+
|===
| Si desea mostrar... | Introduzca el comando... 


 a| 
El estado del sistema, que refleja el estado general de los monitores de estado individuales
 a| 
`*system health status show*`



 a| 
Información sobre el estado del subsistema CIFS-NDO
 a| 
`*system health subsystem show -subsystem CIFS-NDO -instance*`

|===
. Muestre información acerca de cómo se configura la supervisión de alertas CIFS-NDO mediante las acciones adecuadas:
+
|===
| Si desea mostrar información acerca de... | Introduzca el comando... 


 a| 
La configuración y el estado del monitor de estado del subsistema CIFS-NDO, como nodos supervisados, estado de inicialización y estado
 a| 
`*system health config show -subsystem CIFS-NDO*`



 a| 
Las alertas CIFS-NDO que un monitor de estado puede generar potencialmente
 a| 
`*system health alert definition show -subsystem CIFS-NDO*`



 a| 
Las políticas de supervisión del estado de CIFS-NDO, que determinan cuándo se generan las alertas
 a| 
`*system health policy definition show -monitor node-connect*`

|===
+
[NOTE]
====
Utilice la `-instance` parámetro para mostrar información detallada.

====


.Ejemplos
En el siguiente resultado se muestra información acerca del estado general del clúster y del subsistema CIFS-NDO:

[listing]
----
cluster1::> system health status show
Status
---------------
ok

cluster1::> system health subsystem show -instance -subsystem CIFS-NDO

                   Subsystem: CIFS-NDO
                      Health: ok
        Initialization State: initialized
Number of Outstanding Alerts: 0
 Number of Suppressed Alerts: 0
                        Node: node2
  Subsystem Refresh Interval: 5m
----
En el siguiente resultado, se muestra información detallada sobre la configuración y el estado del monitor de estado del subsistema CIFS-NDO:

[listing]
----
cluster1::> system health config show -subsystem CIFS-NDO -instance

                           Node: node1
                        Monitor: node-connect
                      Subsystem: SAS-connect, HA-health, CIFS-NDO
                         Health: ok
                Monitor Version: 2.0
            Policy File Version: 1.0
                        Context: node_context
                     Aggregator: system-connect
                       Resource: SasAdapter, SasDisk, SasShelf, HaNodePair,
                                 HaICMailbox, CifsNdoNode, CifsNdoNodeVserver
Subsystem Initialization Status: initialized
    Subordinate Policy Versions: 1.0 SAS, 1.0 SAS multiple adapters, 1.0, 1.0

                           Node: node2
                        Monitor: node-connect
                      Subsystem: SAS-connect, HA-health, CIFS-NDO
                         Health: ok
                Monitor Version: 2.0
            Policy File Version: 1.0
                        Context: node_context
                     Aggregator: system-connect
                       Resource: SasAdapter, SasDisk, SasShelf, HaNodePair,
                                 HaICMailbox, CifsNdoNode, CifsNdoNodeVserver
Subsystem Initialization Status: initialized
    Subordinate Policy Versions: 1.0 SAS, 1.0 SAS multiple adapters, 1.0, 1.0
----