---
permalink: smb-hyper-v-sql/licensing-requirements-concept.html 
sidebar: sidebar 
keywords: ontap, license, requirement, nondisruptive, hyper, v, smb, sql, server 
summary: Debe estar al tanto de determinados requisitos de ONTAP y licencia cuando cree soluciones de SQL Server o Hyper-V mediante SMB para realizar operaciones no disruptivas en SVM. 
---
= Requisitos de licencia y ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe estar al tanto de determinados requisitos de ONTAP y licencia cuando cree soluciones de SQL Server o Hyper-V mediante SMB para realizar operaciones no disruptivas en SVM.



== Requisitos de la versión de ONTAP

* Hyper-V mediante SMB
+
ONTAP admite operaciones no disruptivas en recursos compartidos SMB para Hyper-V que se ejecutan en Windows 2012 o posterior.

* SQL Server sobre SMB
+
ONTAP admite operaciones no disruptivas en recursos compartidos SMB para SQL Server 2012 o posterior que se ejecutan en Windows 2012 o posterior.



Para obtener la información más reciente sobre las versiones compatibles de ONTAP, Windows Server y SQL Server para realizar operaciones no disruptivas mediante recursos compartidos SMB, consulte la matriz de interoperabilidad.

https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^]



== Requisitos de licencia

Se requieren las siguientes licencias:

* CIFS
* FlexClone (solo para Hyper-V mediante SMB)
+
Esta licencia es necesaria si se usa VSS remoto para los backups. El servicio de copia de respaldo utiliza FlexClone para crear copias de un momento específico de los archivos que se usarán a la hora de crear un backup.

+
Una licencia de FlexClone es opcional si se utiliza un método de backup que no utiliza Remote VSS.



La licencia FlexClone se incluye en link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"]. Si no tiene ONTAP One, debe link:../system-admin/manage-license-task.html["verifique que las licencias necesarias estén instaladas"], y, si es necesario, link:../system-admin/install-license-task.html["instálelos"].
