---
permalink: smb-hyper-v-sql/nondisruptive-operations-glossary-concept.html 
sidebar: sidebar 
keywords: key, concepts, nondisruptive, operation, hyper, v, sql, server, smb, configure 
summary: 'Hay ciertos conceptos sobre las operaciones no disruptivas (NDO) que debe comprender antes de configurar la solución Hyper-V o SQL Server sobre SMB.' 
---
= Conceptos clave sobre las operaciones no disruptivas de Hyper-V y SQL Server sobre SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay ciertos conceptos sobre las operaciones no disruptivas (NDO) que debe comprender antes de configurar la solución Hyper-V o SQL Server sobre SMB.

* *Cuota continuamente disponible*
+
Un recurso compartido SMB 3.0 que tiene establecida la propiedad de recurso compartido disponible de forma continua. Los clientes que se conectan mediante recursos compartidos constantemente disponibles pueden sobrevivir a eventos disruptivos como la toma de control, la devolución y la reubicación de agregados.

* *Nodo*
+
Una única controladora que forma parte de un clúster. Para distinguir entre los dos nodos de un par SFO, un nodo se denomina a veces el _local node_ y el otro nodo se denomina a veces el _Partner node_ o _remote node_. El propietario principal del almacenamiento es el nodo local. El propietario secundario, que toma el control del almacenamiento cuando falla el propietario principal, es el nodo del partner. Cada nodo es el propietario principal de su almacenamiento y el propietario secundario para el almacenamiento de su partner.

* *Reubicación no disruptiva de agregados*
+
La capacidad de mover un agregado entre nodos de partner dentro de un par SFO en un clúster sin interrumpir las aplicaciones del cliente.

* *Recuperación tras fallos no disruptiva*
+
Consulte _takeover_.

* *Migración LIF no disruptiva*
+
La capacidad de realizar una migración LIF sin interrumpir las aplicaciones cliente que están conectadas al clúster a través de esa LIF. En el caso de las conexiones SMB, esto solo es posible para clientes que se conectan mediante SMB 2.0 o una versión posterior.

* *Operaciones no disruptivas*
+
La capacidad de realizar importantes operaciones de gestión y actualización de ONTAP, así como de resistir fallos de nodos sin interrumpir las aplicaciones cliente. Este término hace referencia a la colección de funciones de toma de control no disruptivas, actualización no disruptiva y migración en conjunto.

* *Actualización no disruptiva*
+
Posibilidad de actualizar el hardware o el software de los nodos sin interrumpir las aplicaciones.

* *Movimiento de volumen no disruptivo*
+
La capacidad de mover un volumen libremente por el clúster sin interrumpir las aplicaciones que estén utilizando el volumen. En el caso de las conexiones SMB, todas las versiones de SMB admiten movimientos de volúmenes no disruptivos.

* *Asas persistentes*
+
Propiedad de SMB 3.0 que permite la conexión disponible de forma continua para volver a conectarse con total transparencia al servidor CIFS en caso de desconexión. Al igual que sucede con las asas duraderas, el servidor CIFS mantiene las asas persistentes durante un período de tiempo tras la pérdida de la comunicación con el cliente conectado. Sin embargo, las asas persistentes tienen más resiliencia que las asas duraderas. Además de dar al cliente la posibilidad de recuperar el controlador en una ventana de 60 segundos después de volver a conectarse, el servidor CIFS niega el acceso a los demás clientes que soliciten acceso al archivo durante esa ventana de 60 segundos.

+
La información sobre las asas persistentes se refleja en el almacenamiento persistente del partner SFO, el cual permite a los clientes con asas persistentes desconectadas recuperar las asas duraderas tras un evento en el que el partner de SFO asume la propiedad del almacenamiento del nodo. Además de proporcionar operaciones no disruptivas en caso de movimiento de LIF (que gestiona mantenimiento duradero), las direcciones persistentes proporcionan operaciones no disruptivas para la toma de control, la devolución y la reubicación de agregados.

* *Retorno SFO*
+
Devolver agregados a sus ubicaciones principales al recuperarse de un evento de toma de control.

* *Par SFO*
+
Un par de nodos cuyas controladoras están configuradas para suministrar datos entre sí si uno de los dos nodos deja de funcionar. Según el modelo del sistema, ambas controladoras pueden estar en un solo chasis o las controladoras pueden estar en chasis separados. Conocido como par de alta disponibilidad en un clúster de dos nodos.

* *Adquisición*
+
Proceso por el que el partner toma el control del almacenamiento cuando falla el propietario principal de ese almacenamiento. En el contexto de la OFS, la conmutación por error y la toma de control son sinónimos.


