---
permalink: smb-hyper-v-sql/volume-config-worksheet-reference.html 
sidebar: sidebar 
keywords: complete, volume, configuration, worksheet, sql, server, hyper, v, smb, configuration 
summary: La hoja de trabajo proporciona una forma sencilla de registrar los valores que necesita al crear volúmenes para configuraciones de SQL Server y Hyper-V en SMB. 
---
= Complete la hoja de datos de configuración de volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La hoja de trabajo proporciona una forma sencilla de registrar los valores que necesita al crear volúmenes para configuraciones de SQL Server y Hyper-V en SMB.

Para cada volumen, debe especificar la siguiente información:

* El nombre de la máquina virtual de almacenamiento (SVM)
+
El nombre de SVM es el mismo para todos los volúmenes.

* Nombre del volumen
* Nombre del agregado
+
Puede crear volúmenes en agregados ubicados en cualquier nodo del clúster.

* Tamaño
* Ruta de unión


Debe tener en cuenta lo siguiente al crear volúmenes que se utilizan para almacenar datos del servidor de aplicaciones:

* Si el volumen raíz no tiene estilo de seguridad NTFS, se debe especificar el estilo de seguridad como NTFS al crear el volumen.
+
De forma predeterminada, los volúmenes heredan el estilo de seguridad del volumen raíz de la SVM.

* Los volúmenes se deben configurar con la garantía de espacio de volumen predeterminada.
* Opcionalmente, puede configurar la opción de gestión de espacio de autosize.
* Debe configurar la opción que determina la reserva de espacio de snapshot en `0`.
* Debe deshabilitarse la política de Snapshot aplicada al volumen.
+
Si está deshabilitada la política de snapshot de SVM, no es necesario especificar una política de snapshot para los volúmenes. Los volúmenes heredan la política de Snapshot para la SVM. Si la política de snapshots para la SVM no está deshabilitada y está configurada para crear Snapshot, debe especificar una política de Snapshot en el nivel del volumen, y esa política debe deshabilitarse. Los backups habilitados para el servicio de copia en la sombra y los backups de SQL Server gestionan la creación y la eliminación de instantáneas.

* No se pueden configurar los reflejos con uso compartido de carga para los volúmenes.


Las rutas de unión en las que tiene previsto crear recursos compartidos que utilicen los servidores de aplicaciones deben seleccionarse de forma que no haya volúmenes con conexiones por debajo del punto de entrada de recurso compartido.

Por ejemplo, si desea almacenar archivos de máquinas virtuales en cuatro volúmenes denominados «'vol1'», «'vol2'», «'vol3'» y «'vol4'», puede crear el espacio de nombres que se muestra en el ejemplo. A continuación, puede crear recursos compartidos para los servidores de aplicaciones en las siguientes rutas de acceso `/data1/vol1`: , `/data1/vol2` `/data2/vol3` , Y `/data2/vol4`.

[listing]
----

                     Junction                       Junction
Vserver Volume       Active   Junction Path         Path Source
------- ------------ -------- -------------------   -----------
vs1     data1         true     /data1               RW_volume
vs1     vol1          true     /data1/vol1          RW_volume
vs1     vol2          true     /data1/vol2          RW_volume
vs1     data2         true     /data2               RW_volume
vs1     vol3          true     /data2/vol3          RW_volume
vs1     vol4          true     /data2/vol4          RW_volume
----
|===
| Tipos de información | Valores 


 a| 
_Volume 1: Nombre del volumen, agregado, tamaño, ruta de unión_
 a| 



 a| 
_Volume 2: Nombre del volumen, agregado, tamaño, ruta de unión_
 a| 



 a| 
_Volume 3: Nombre del volumen, agregado, tamaño, ruta de unión_
 a| 



 a| 
_Volume 4: Nombre del volumen, agregado, tamaño, ruta de unión_
 a| 



 a| 
_Volume 5: Nombre del volumen, agregado, tamaño, ruta de unión_
 a| 



 a| 
_Volume 6: Nombre del volumen, agregado, tamaño, ruta de unión_
 a| 



 a| 
_Volúmenes adicionales: Nombre del volumen, agregado, tamaño, ruta de unión_
 a| 

|===