---
permalink: smb-hyper-v-sql/witness-protocol-transparent-failover-concept.html 
sidebar: sidebar 
keywords: witness, protocol, transparent, failover, lif, ca, share, client, smb, recovery 
summary: 'El protocolo Witness proporciona funcionalidades mejoradas de recuperación tras fallos de clientes para recursos compartidos de SMB 3.0 continuamente disponibles (recursos compartidos de CA). Witness facilita una conmutación al nodo de respaldo más rápida porque evita el período de recuperación tras fallos de LIF. Notifica a los servidores de aplicaciones cuando un nodo no está disponible sin tener que esperar a que se agote el tiempo de espera de la conexión SMB 3.0.' 
---
= Lo que hace el protocolo de testigos para mejorar una conmutación por error transparente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El protocolo Witness proporciona funcionalidades mejoradas de recuperación tras fallos de clientes para recursos compartidos de SMB 3.0 continuamente disponibles (recursos compartidos de CA). Witness facilita una conmutación al nodo de respaldo más rápida porque evita el período de recuperación tras fallos de LIF. Notifica a los servidores de aplicaciones cuando un nodo no está disponible sin tener que esperar a que se agote el tiempo de espera de la conexión SMB 3.0.

La conmutación por error es fluida, con aplicaciones que se ejecutan en el cliente no siendo consciente de que se ha producido una conmutación por error. Si no se dispone de un testigo, las operaciones de conmutación por error siguen teniendo éxito, pero la conmutación por error sin un testigo es menos eficiente.

Es posible realizar una conmutación por error mejorada con los siguientes requisitos:

* Solo se puede utilizar con servidores CIFS compatibles con SMB 3.0 que tengan habilitada SMB 3.0.
* Los recursos compartidos deben utilizar SMB 3.0 con la propiedad compartida de disponibilidad continua establecida.
* El partner SFO del nodo al que están conectados los servidores de aplicaciones debe tener al menos una LIF de datos operativos asignada a la máquina virtual de almacenamiento (SVM) que aloja datos de los servidores de aplicaciones.
+
[NOTE]
====
El protocolo de testigos funciona entre pares de SFO. Dado que las LIF pueden migrar a cualquier nodo del clúster, es posible que cualquier nodo deba ser el testigo de su partner SFO. El protocolo de observación no puede proporcionar una rápida conmutación por error de las conexiones SMB en un nodo determinado si la SVM que aloja datos de los servidores de aplicaciones no tiene una LIF de datos activa en el nodo del partner. Por lo tanto, cada nodo del clúster debe tener al menos una LIF de datos para cada SVM que aloje una de estas configuraciones.

====
* Los servidores de aplicación deben conectarse al servidor CIFS mediante el nombre del servidor CIFS que se almacena en DNS en lugar de utilizar direcciones IP de LIF individuales.

