---
sidebar: sidebar 
permalink: file-system-analytics/considerations-concept.html 
keywords: file system analytics, performance, SVM 
summary: File System Analytics está diseñado para proporcionar visibilidad en volúmenes con datos NAS activos. Existen restricciones y limitaciones en su uso. 
---
= Consideraciones sobre el análisis de sistemas de archivos de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe conocer ciertos límites de uso e impactos de rendimiento potenciales asociados con la implementación de los análisis del sistema de archivos.



== Relaciones protegidas por SVM

Si ha habilitado File System Analytics en los volúmenes que contienen SVM se encuentran en una relación de protección, los datos de análisis no se replican en la SVM de destino. Si la SVM de origen debe volver a sincronizarse en una operación de recuperación, debe volver a habilitar manualmente los análisis de los volúmenes deseados una vez que se recupera.



== Consideraciones de rendimiento

En algunos casos, la activación del análisis del sistema de archivos podría afectar negativamente al rendimiento durante la recopilación inicial de metadatos. Esto se suele ver en sistemas con un aprovechamiento máximo. Para evitar habilitar análisis en dichos sistemas, puede utilizar las herramientas de supervisión del rendimiento de System Manager de ONTAP.

Si experimenta un aumento notable en la latencia, consulte lalink:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/High_or_fluctuating_latency_after_turning_on_NetApp_ONTAP_File_System_Analytics["Base de conocimientos de NetApp : Latencia alta o fluctuante después de activar NetApp ONTAP File System Analytics"^] .



== Consideraciones sobre la adquisición

Cuando se habilita el análisis de capacidad, ONTAP realiza un análisis de inicialización para los análisis de capacidad. El análisis accede a los metadatos de todos los archivos de los volúmenes para los que están habilitados los análisis de capacidad. No se leen datos de archivos durante el análisis. A partir de ONTAP 9.14.1, puede realizar un seguimiento del progreso del análisis con la API de REST, en la pestaña **Explorer** del Administrador del sistema o con `volume analytics show` el comando de la CLI. Si hay un evento de limitación, ONTAP proporciona una notificación.

Al activar el análisis del sistema de archivos en un volumen, asegúrese de que al menos entre el 5 y el 8 por ciento del espacio disponible del volumen esté libre. Si el volumen tiene autosize habilitado, calcule el tamaño disponible en función del tamaño de crecimiento automático máximo. A partir de ONTAP 9.15.1, ONTAP presenta un mensaje de error si no hay suficiente espacio disponible al habilitar el análisis del sistema de archivos en un volumen.

Una vez que se completa el análisis, File System Analytics se actualiza continuamente en tiempo real a medida que cambia el sistema de archivos.

El tiempo necesario para la exploración es proporcional al número de directorios y archivos del volumen. Como el análisis recoge metadatos, el tamaño del archivo no afecta el tiempo de análisis.

Para obtener más información sobre la secuencia de inicialización, consulte link:https://www.netapp.com/pdf.html?item=/media/20707-tr-4867.pdf["TR-4867: Directrices de prácticas recomendadas para análisis de sistemas de archivos"^].



=== Mejores prácticas

Debe iniciar el análisis en los volúmenes que no comparten agregados. Puede ver qué agregados alojan actualmente los volúmenes con el comando:

`volume show -volume _comma-separated-list_of_volumes_ -fields aggr-list`

Mientras se ejecuta el análisis, los volúmenes siguen sirviendo al tráfico de cliente. Se recomienda iniciar la exploración durante los períodos en los que se anticipa un tráfico de cliente más bajo.

Si aumenta el tráfico del cliente, consumirá recursos del sistema y el análisis tardará más tiempo.

A partir de ONTAP 9.12.1, puede pausar la recogida de datos en System Manager y con la CLI de ONTAP.

* Si utiliza la CLI de ONTAP:
+
** Puede pausar la recopilación de datos con el comando: `volume analytics initialization pause -vserver _svm_name_ -volume _volume_name_`
** Una vez que el tráfico del cliente se ha ralentizado, puede reanudar la recopilación de datos con el comando: `volume analytics initialization resume -vserver _svm_name_ -volume _volume_name_`


* Si está utilizando System Manager, en la vista *Explorer* del menú de volumen, utilice los botones *Pausar la recopilación de datos* y *Reanudar la recopilación de datos* para administrar el escaneo.

