---
sidebar: sidebar 
permalink: file-system-analytics/considerations-concept.html 
keywords: file system analytics, performance, SVM 
summary: File System Analytics está diseñado para proporcionar visibilidad en volúmenes con datos NAS activos. Existen restricciones y limitaciones en su uso. 
---
= Consideraciones para el análisis del sistema de archivos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe conocer ciertos límites de uso e impactos de rendimiento potenciales asociados con la implementación de los análisis del sistema de archivos.



== Relaciones protegidas por SVM

Si ha habilitado File System Analytics en los volúmenes que contienen SVM se encuentran en una relación de protección, los datos de análisis no se replican en la SVM de destino. Si la SVM de origen debe volver a sincronizarse en una operación de recuperación, debe volver a habilitar manualmente los análisis de los volúmenes deseados una vez que se recupera.



== Consideraciones de rendimiento

En algunos casos, la activación del análisis del sistema de archivos podría afectar negativamente al rendimiento durante la recopilación inicial de metadatos. Esto se suele ver en sistemas con un aprovechamiento máximo. Para evitar habilitar análisis en dichos sistemas, puede utilizar las herramientas de supervisión del rendimiento de System Manager de ONTAP.

Si experimenta un aumento significativo en la latencia, consulte el artículo de la base de conocimientos link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/High_or_fluctuating_latency_after_turning_on_NetApp_ONTAP_File_System_Analytics["Una latencia elevada o fluctuante después de activar el análisis del sistema de archivos ONTAP de NetApp"^].
