---
permalink: antivirus/architecture-concept.html 
sidebar: sidebar 
keywords: antivirus, architecture 
summary: La arquitectura antivirus de NetApp consiste en el software del servidor Vscan y la configuración asociada. 
---
= Arquitectura de antivirus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La arquitectura antivirus de NetApp consiste en el software del servidor Vscan y la configuración asociada.



== Software de servidor VSCAN

Debe instalar este software en el servidor Vscan.

* *Conector antivirus ONTAP*
+
Se trata de un software proporcionado por NetApp que gestiona la comunicación de solicitudes de análisis y respuestas entre las SVM y el software antivirus. Puede ejecutarse en una máquina virtual, pero para obtener el mejor rendimiento, utilice una máquina física. Puede descargar este software desde el sitio de soporte de NetApp (requiere inicio de sesión).

* *Software antivirus*
+
Este es un software proporcionado por los socios que analiza los archivos en busca de virus u otro código malicioso. Al configurar el software, se especifican las acciones correctivas que se van a realizar en los archivos infectados.





== Configuración del software VSCAN

Debe configurar estos ajustes de software en el servidor Vscan.

* *Piscina del escáner*
+
Esta configuración define los servidores Vscan y los usuarios con privilegios que se pueden conectar a SVM. También define un período de tiempo de espera de solicitud de exploración, tras el cual la solicitud de exploración se envía a un servidor Vscan alternativo si hay uno disponible.

+
[NOTE]
====
Debe establecer el período de tiempo de espera en el software antivirus del servidor Vscan en cinco segundos menos que el período de tiempo de espera de solicitud de exploración del grupo de análisis. Esto evitará situaciones en las que el acceso al archivo se retrase o rechace por completo porque el período de tiempo de espera del software es mayor que el período de tiempo de espera de la solicitud de exploración.

====
* *Usuario privilegiado*
+
Este ajuste es una cuenta de usuario de dominio que un servidor Vscan utiliza para conectarse a la SVM. La cuenta debe existir en la lista de usuarios con privilegios del grupo de escáneres.

* *Directiva del escáner*
+
Esta configuración determina si un conjunto de escáneres está activo. Las políticas de escáner están definidas por el sistema, por lo que no puede crear políticas de escáner personalizadas. Solo estas tres políticas están disponibles:

+
** `Primary` especifica que el grupo de escáneres está activo.
** `Secondary` Especifica que el grupo de escáneres está activo, sólo cuando no hay ningún servidor Vscan conectado en el grupo de escáneres principal.
** `Idle` especifica que el grupo de escáneres está inactivo.


* *Política de acceso*
+
Esta configuración define el ámbito de una exploración en acceso. Puede especificar el tamaño máximo de archivo que se va a escanear, las extensiones de archivo y las rutas que se van a incluir en el escaneo, y las extensiones de archivo y las rutas de acceso que se van a excluir del escaneo.

+
De forma predeterminada, solo se analizan los volúmenes de lectura/escritura. Puede especificar filtros que permitan el análisis de volúmenes de sólo lectura o que restrinjan el análisis de archivos abiertos con el acceso de ejecución:

+
** `scan-ro-volume` permite analizar volúmenes de solo lectura.
** `scan-execute-access` restringe el escaneo a archivos abiertos con acceso de ejecución.
+
[NOTE]
====
“Ejecutar acceso” es diferente de “ejecutar permiso”. Un cliente dado tendrá “acceso de ejecución” en un archivo ejecutable solo si el archivo fue abierto con “intención de ejecución”.

====


+
Puede ajustar la `scan-mandatory` Opción de desactivar para especificar que se permite el acceso al archivo cuando no hay servidores Vscan disponibles para el análisis de virus. En el modo de acceso puede elegir entre estas dos opciones mutuamente excluyentes:

+
** Obligatorio: Con esta opción, Vscan intenta entregar la solicitud de escaneo al servidor hasta que caduque el período de tiempo de espera. Si el servidor no acepta la solicitud de escaneo, se rechaza la solicitud de acceso del cliente.
** No Obligatorio: Con esta opción, Vscan siempre permite el acceso del cliente, independientemente de que haya o no un servidor Vscan disponible para la detección de virus.


* *Tarea a petición*
+
Esta configuración define el ámbito de una exploración bajo demanda. Puede especificar el tamaño máximo de archivo que se va a escanear, las extensiones de archivo y las rutas que se van a incluir en el escaneo, y las extensiones de archivo y las rutas de acceso que se van a excluir del escaneo. Los archivos de los subdirectorios se analizan de forma predeterminada.

+
Utilice una programación cron para especificar cuándo se ejecuta la tarea. Puede utilizar el `vserver vscan on-demand-task run` comando para ejecutar la tarea de inmediato.

* *Perfil de operaciones de archivos Vscan (sólo escaneado en tiempo real)*
+
La `vscan-fileop-profile` parámetro para `vserver cifs share create` El comando define qué operaciones de archivos SMB desencadenan el análisis de virus. De manera predeterminada, el parámetro se establece en `standard`, Que es la mejor práctica de NetApp. Puede ajustar este parámetro como sea necesario al crear o modificar un recurso compartido de SMB:

+
** `no-scan` especifica que las exploraciones de virus nunca se activan para el recurso compartido.
** `standard` especifica que las operaciones de apertura, cierre y cambio de nombre activan los análisis de virus.
** `strict` especifica que las exploraciones de virus se activan mediante operaciones de apertura, lectura, cierre y cambio de nombre.
+
La `strict` profile proporciona una seguridad mejorada para situaciones en las que varios clientes acceden a un archivo simultáneamente. Si un cliente cierra un archivo después de escribir un virus y el mismo archivo permanece abierto en un segundo cliente, `strict` garantiza que una operación de lectura del segundo cliente active un análisis antes de cerrar el archivo.

+
Debe tener cuidado de restringir el `strict`` se accederá simultáneamente a los recursos compartidos que contengan archivos que prevé. Dado que este perfil genera más solicitudes de análisis, puede afectar al rendimiento.

** `writes-only` especifica que las exploraciones de virus se activan sólo cuando se cierran los archivos modificados.
+
Desde `writes-only` genera menos solicitudes de escaneo, normalmente mejora el rendimiento.

+
Si utiliza este perfil, el escáner debe estar configurado para eliminar o poner en cuarentena los archivos infectados que no se pueden reparar, por lo que no se puede acceder a ellos. Si, por ejemplo, un cliente cierra un archivo tras escribir un virus y el archivo no se repara, elimina ni pone en cuarentena, ningún cliente que acceda al archivo `without` escribir a él será infectado.





[NOTE]
====
Si una aplicación cliente realiza una operación de cambio de nombre, el archivo se cierra con el nuevo nombre y no se analiza. Si tales operaciones plantean un problema de seguridad en su entorno, debe utilizar el `standard` o. `strict` perfil.

====