---
permalink: antivirus/commands-manage-on-access-policies-reference.html 
sidebar: sidebar 
keywords: commands, manage, on-access, policies 
summary: Puede modificar, deshabilitar o eliminar una política de acceso. Puede ver un resumen y detalles de la política. 
---
= Comandos para gestionar políticas en acceso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede modificar, deshabilitar o eliminar una política de acceso. Puede ver un resumen y detalles de la política.

|===


| Si desea... | Introduzca el siguiente comando... 


 a| 
Modifique una política de acceso
 a| 
`vserver vscan on-access-policy modify`



 a| 
Deshabilitar una política de acceso
 a| 
`vserver vscan on-access-policy disable`



 a| 
Eliminar una política de acceso
 a| 
`vserver vscan on-access-policy delete`



 a| 
Consulte el resumen y los detalles de una política de acceso
 a| 
`vserver vscan on-access-policy show`



 a| 
Agregar a la lista de rutas de acceso que se van a excluir
 a| 
`vscan on-access-policy paths-to-exclude add`



 a| 
Eliminar de la lista de rutas de acceso que se van a excluir
 a| 
`vscan on-access-policy paths-to-exclude remove`



 a| 
Consulte la lista de rutas de acceso que desea excluir
 a| 
`vscan on-access-policy paths-to-exclude show`



 a| 
Agregar a la lista de extensiones de archivo que se van a excluir
 a| 
`vscan on-access-policy file-ext-to-exclude add`



 a| 
Eliminar de la lista de extensiones de archivo que se van a excluir
 a| 
`vscan on-access-policy file-ext-to-exclude remove`



 a| 
Consulte la lista de extensiones de archivo que se van a excluir
 a| 
`vscan on-access-policy file-ext-to-exclude show`



 a| 
Agregar a la lista de extensiones de archivo que se incluirán
 a| 
`vscan on-access-policy file-ext-to-include add`



 a| 
Eliminar de la lista de extensiones de archivo que se van a incluir
 a| 
`vscan on-access-policy file-ext-to-include remove`



 a| 
Consulte la lista de extensiones de archivo que se incluirán
 a| 
`vscan on-access-policy file-ext-to-include show`

|===
Para obtener más información sobre estos comandos, consulte las páginas man.
