---
permalink: antivirus/commands-view-vscan-server-reference.html 
sidebar: sidebar 
keywords: commands, view, vscan, server, connection, status 
summary: Puede utilizar los comandos show de estado de conexión de Vserver vscan para ver información resumida y detallada acerca del estado de conexión del servidor Vscan. 
---
= Comandos para ver el estado de conexión del servidor Vscan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `vserver vscan connection-status show` Comandos para ver información resumida y detallada acerca del estado de conexión del servidor Vscan.

|===
| Si desea... | Introduzca el siguiente comando... 


 a| 
Ver un resumen de las conexiones del servidor Vscan
 a| 
`vserver vscan connection-status show`



 a| 
Ver detalles de las conexiones del servidor Vscan
 a| 
`vserver vscan connection-status show-all`



 a| 
Ver detalles de los servidores Vscan conectados
 a| 
`vserver vscan connection-status show-connected`



 a| 
Ver detalles de los servidores Vscan disponibles que no están conectados
 a| 
`vserver vscan connection-status show-not-connected`

|===
Para obtener más información sobre estos comandos, consulte las páginas man.
