---
permalink: antivirus/configure-on-demand-scanning-concept.html 
sidebar: sidebar 
keywords: configure, on-demand, scan 
summary: Puede utilizar el análisis bajo demanda para comprobar los archivos en busca de virus de forma inmediata o programada. 
---
= Configurar la descripción general del análisis bajo demanda
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el análisis bajo demanda para comprobar los archivos en busca de virus de forma inmediata o programada.

Puede que desee ejecutar análisis sólo en horas de menor actividad, por ejemplo, o puede que desee analizar archivos muy grandes que se excluyeron de un análisis en tiempo real. Puede utilizar una programación cron para especificar cuándo se ejecuta la tarea.


NOTE: Para crear una tarea bajo demanda, debe haber al menos una política de acceso en curso activada. Puede ser la política predeterminada o un usuario creado en la política de acceso.

.Acerca de este tema
* Puede asignar una programación al crear una tarea.
* Solo se puede programar una tarea a la vez en un SVM.
* El análisis bajo demanda no admite el análisis de enlaces simbólicos o archivos de flujo.



NOTE: El análisis bajo demanda no admite el análisis de enlaces simbólicos o archivos de flujo.


NOTE: Para crear una tarea bajo demanda, debe haber al menos una política de acceso en curso activada. Puede ser la política predeterminada o un usuario creado en la política de acceso.
