---
permalink: antivirus/index.html 
sidebar: sidebar 
keywords: overview, antivirus, virus, viruses, configuration, overview, deciding, malicious code, scan, scanning, vscan, protect, data, on-access, on-demand 
summary: Puede utilizar los análisis de virus de NetApp, denominados Vscan, para proteger los datos de ser afectados por virus u otro código malicioso. 
---
= Información general de la configuración de antivirus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar los análisis de virus de NetApp, llamados _Vscan_, para proteger los datos de posibles riesgos de virus u otro código malicioso. Muestra cómo utilizar los análisis en el acceso para comprobar si hay virus cuando los clientes acceden a los archivos a través de SMB y cómo se utiliza el análisis bajo demanda para comprobar si hay virus inmediatamente o en una programación.

Puede trabajar con Vscan mediante la interfaz de línea de comandos (CLI) de ONTAP, no con System Manager ni con una herramienta de scripting automatizada. System Manager no admite VSCAN.

.Información relacionada
http://www.netapp.com/us/media/tr-4286.pdf["Informe técnico de NetApp 4286: Solución antivirus para Clustered Data ONTAP: McAfee"^]

http://www.netapp.com/us/media/tr-4304.pdf["Informe técnico de NetApp 4304: Solución antivirus para Symantec de Clustered Data ONTAP"^]

http://www.netapp.com/us/media/tr-4312.pdf["Informe técnico de NetApp 4312: Solución antivirus para Clustered Data ONTAP Trend Micro"^]
