---
permalink: antivirus/modify-vscan-file-profile-smb-share-task.html 
sidebar: sidebar 
keywords: modify, vscan, file-operations, profile, cifs share 
summary: 'El perfil _Vscan file-operations_ para un recurso compartido SMB define las operaciones en el recurso compartido que pueden activar el análisis. De manera predeterminada, el parámetro se establece en `standard`. Es posible ajustar el parámetro según sea necesario al crear o modificar un recurso compartido de SMB.' 
---
= Modifique el perfil de operaciones de archivos Vscan para un recurso compartido de SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El perfil _Vscan file-operations_ para un recurso compartido SMB define las operaciones en el recurso compartido que pueden activar el análisis. De manera predeterminada, el parámetro se establece en `standard`. Es posible ajustar el parámetro según sea necesario al crear o modificar un recurso compartido de SMB.

Consulte link:architecture-concept.html["Arquitectura de antivirus"] Sección para obtener detalles sobre _Vscan file-operations profile_.

[NOTE]
====
La detección de virus no se realiza en un recurso compartido de SMB que tenga el `continuously-available` parámetro establecido en `Yes`.

====
.Paso
. Modifique el valor del perfil de operaciones de archivo Vscan para un recurso compartido de SMB:
+
`vserver cifs share modify -vserver _data_SVM_ -share-name _share_ -path _share_path_ -vscan-fileop-profile no-scan|standard|strict|writes-only`

+
Para obtener una lista completa de las opciones, consulte la página de manual del comando.

+
El siguiente comando cambia el perfil de operaciones del archivo Vscan para un recurso compartido de SMB a. `strict`:

+
[listing]
----
cluster1::> vserver cifs share modify -vserver vs1 -share-name SALES_SHARE -path /sales -vscan-fileop-profile strict
----

