---
permalink: antivirus/reset-status-scanned-files-task.html 
sidebar: sidebar 
keywords: reset, status, scanned files 
summary: En ocasiones, es posible que desee restablecer el estado de análisis de los archivos analizados correctamente en una SVM mediante el comando vserver vscan reset para descartar la información almacenada en caché para los archivos. Es posible que desee utilizar este comando para reiniciar el procesamiento de análisis de virus en caso de un análisis mal configurado, por ejemplo. 
---
= Restablece el estado de los archivos capturados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En ocasiones, es posible que desee restablecer el estado de análisis de los archivos analizados correctamente en una SVM mediante el `vserver vscan reset` comando para descartar la información almacenada en caché para los archivos. Es posible que desee utilizar este comando para reiniciar el procesamiento de análisis de virus en caso de un análisis mal configurado, por ejemplo.

.Acerca de esta tarea
Después de ejecutar el `vserver vscan reset` comando, todos los archivos elegibles se analizarán la próxima vez que se acceda a ellos.

[NOTE]
====
Este comando puede afectar negativamente al rendimiento, dependiendo del número y el tamaño de los archivos que se van a volver a analizar.

====
.Antes de empezar
Se requieren privilegios avanzados para esta tarea.

.Pasos
. Cambie al nivel de privilegio avanzado:
+
`set -privilege advanced`

. Restablecer el estado de los archivos capturados:
+
`vserver vscan reset -vserver data_SVM`

+
El siguiente comando restablece el estado de los archivos capturados en `vs1` SVM:

+
[listing]
----
cluster1::> vserver vscan reset -vserver vs1
----

