---
permalink: antivirus/reset-status-scanned-files-task.html 
sidebar: sidebar 
keywords: reset, status, scanned files 
summary: En ocasiones, es posible que desee restablecer el estado de análisis de los archivos analizados correctamente en una SVM mediante el comando vserver vscan reset para descartar la información almacenada en caché para los archivos. Es posible que desee utilizar este comando para reiniciar el procesamiento de análisis de virus en caso de un análisis mal configurado, por ejemplo. 
---
= Restablecer el estado de los archivos escaneados por ONTAP Vscan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En ocasiones, es posible que desee restablecer el estado de análisis de los archivos analizados correctamente en una SVM mediante `vserver vscan reset` el uso del comando para descartar la información almacenada en caché de los archivos. Es posible que desee utilizar este comando para reiniciar el procesamiento de análisis de virus en caso de un análisis mal configurado, por ejemplo. Obtenga más información sobre `vserver vscan reset` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-reset.html["Referencia de comandos del ONTAP"^].

.Acerca de esta tarea
Después de ejecutar el `vserver vscan reset` comando, todos los archivos elegibles se analizarán la próxima vez que se acceda a ellos.

[NOTE]
====
Este comando puede afectar negativamente al rendimiento, dependiendo del número y el tamaño de los archivos que se van a volver a analizar.

====
.Antes de empezar
Se requieren privilegios avanzados para esta tarea.

.Pasos
. Cambie al nivel de privilegio avanzado:
+
`set -privilege advanced`

+
Obtenga más información sobre `set -privilege advanced` en el link:https://docs.netapp.com/us-en/ontap-cli/set.html["Referencia de comandos del ONTAP"^].

. Restablecer el estado de los archivos capturados:
+
`vserver vscan reset -vserver data_SVM`

+
El siguiente comando restablece el estado de los archivos analizados en la `vs1` SVM:

+
[listing]
----
cluster1::> vserver vscan reset -vserver vs1
----

