---
permalink: antivirus/schedule-on-demand-task-task.html 
sidebar: sidebar 
keywords: schedule, on-demand, task 
summary: Si ha creado una tarea bajo demanda sin asignar una programación, o si desea asignar una programación diferente a una tarea, puede utilizar el comando vserver vscan on-Demand-Task schedule para asignar una programación a la tarea. 
---
= Programar una tarea bajo demanda
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si ha creado una tarea a petición sin asignar una programación, o si desea asignar una programación diferente a una tarea, puede utilizar la `vserver vscan on-demand-task schedule` comando para asignar una programación a la tarea.

.Acerca de esta tarea
La programación asignada con `vserver vscan on-demand-task schedule` el comando anula una programación que ya se ha asignado con el `vserver vscan on-demand-task create` comando.

.Pasos
. Programar una tarea bajo demanda:
+
`vserver vscan on-demand-task schedule -vserver data_SVM -task-name task_name -schedule cron_schedule`

+
El siguiente comando programa una tarea en tiempo de acceso denominada `Task2` en la ``vs2``SVM:

+
[listing]
----
cluster1::> vserver vscan on-demand-task schedule -vserver vs2 -task-name Task2 -schedule daily
[Job 142]: Vscan On-Demand job is queued. Use the "job show -id 142" command to view the status.
----
+
[NOTE]
====
Puede utilizar el `job show` comando para ver el estado del trabajo. Puede utilizar el `job pause` y.. `job resume` comandos para pausar y reiniciar el trabajo o el `job stop` comando para finalizar el trabajo.

====
. Compruebe que la tarea bajo demanda se ha programado: `vserver vscan on-demand-task show -instance data_SVM -task-name task_name`
+
Para obtener una lista completa de las opciones, consulte la página de manual del comando.

+
El siguiente comando muestra los detalles de `Task 2` tarea:

+
[listing]
----
cluster1::> vserver vscan on-demand-task show -instance vs2 -task-name Task2

                           Vserver: vs2
                         Task Name: Task2
                List of Scan Paths: /vol1/, /vol2/cifs/
             Report Directory Path: /report
                      Job Schedule: daily
Max File Size Allowed for Scanning: 5GB
            File Paths Not to Scan: /vol1/cold-files/
       File Extensions Not to Scan: mp3, mp4
           File Extensions to Scan: vmdk, mp*
      Scan Files with No Extension: false
           Request Service Timeout: 5m
                    Cross Junction: true
               Directory Recursion: true
                     Scan Priority: low
                  Report Log Level: info
----


.Después de terminar
Debe habilitar el análisis en la SVM antes de que se ejecute la tarea programada.
