---
permalink: antivirus/troubleshoot-common-virus-scanning-issues-reference.html 
sidebar: sidebar 
keywords: troubleshooting, troubleshoot, virus scanning, vscan, monitoring, connection, connectivity 
summary: Una tabla que enumera los problemas comunes de detección de virus, sus posibles causas y formas de resolverlos. 
---
= Solucionar problemas de detección de virus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para los problemas comunes de detección de virus, existen posibles causas y formas de resolverlos. La detección de virus también se conoce como Vscan.

|===


| Problema | Cómo resolverlo 


 a| 
Los servidores Vscan no se pueden conectar
El sistema de almacenamiento Clustered ONTAP de NetApp.
 a| 
Compruebe si la configuración del conjunto de escáneres especifica el
Dirección IP del servidor VSCAN. Compruebe también si se permite
los usuarios con privilegios de la lista de grupos de escáneres están activos. Para comprobar el conjunto de escáneres, ejecute el `vserver vscan scanner-pool show` comando en el símbolo del sistema de almacenamiento.
Si los servidores Vscan siguen sin poder conectarse, es posible que haya un problema con la red.



 a| 
Los clientes observan una alta latencia
 a| 
Probablemente sea el momento de agregar más servidores Vscan al
conjunto de escáner.



 a| 
Se activan demasiadas adquisiciones
 a| 
Modifique el valor de `vscan-fileop-profile`
parámetro para restringir el número de operaciones de archivo
supervisado para detección de virus.



 a| 
Algunos archivos no se están escaneando.
 a| 
Compruebe la política de acceso. Es posible que el camino para
estos archivos se han agregado a la lista de exclusión de ruta o a la lista de exclusión de ruta
su tamaño supera el valor configurado para las exclusiones. Para
compruebe la política de acceso y ejecute el `vserver vscan
on-access-policy show` comando en el almacenamiento
símbolo del sistema.



 a| 
Se ha denegado el acceso al archivo.
 a| 
Compruebe si se ha especificado el ajuste obligatorio de adquisición
en la configuración de la política. Este valor deniega el acceso a los datos
Si no hay servidores Vscan conectados. Modifique la configuración como
apropiado.

|===