---
permalink: antivirus/vscan-server-install-config-concept.html 
sidebar: sidebar 
keywords: vscan, server installation, configuration 
summary: Debe configurar y configurar uno o más servidores Vscan para habilitar el análisis antivirus. 
---
= Instalación y configuración del servidor VSCAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar y configurar uno o más servidores Vscan para habilitar el análisis antivirus.

* Para instalar y configurar el software antivirus en el servidor, siga las instrucciones proporcionadas por su proveedor.
* Para instalar y configurar el conector antivirus de ONTAP, siga las instrucciones de `README.txt` archivo disponible en
https://mysupport.netapp.com/site/products/all/details/ontap-antivirus-connector/downloads-tab["Sitio de soporte de NetApp"].


[NOTE]
====
Para la recuperación ante desastres y las configuraciones de MetroCluster, debe configurar servidores Vscan independientes para los clústeres de ONTAP principal/local y secundario/asociado.

====


== Requisitos del software antivirus

* Para obtener información acerca de los requisitos de software antivirus, consulte la documentación del proveedor.
* Para obtener información acerca de los proveedores, software y versiones compatibles con Vscan, consulte
https://imt.netapp.com/matrix/["Herramienta de matriz de interoperabilidad de NetApp (IMT)"].




== Requisitos del conector antivirus de ONTAP

* Puede descargar este software de la
https://mysupport.netapp.com/site/products/all/details/ontap-antivirus-connector/downloads-tab/download/63048/1.0.6["Sitio de soporte de NetApp"] (requiere inicio de sesión).
* Para obtener información sobre la compatibilidad con versiones de software, consulte
https://imt.netapp.com/matrix/["Herramienta de matriz de interoperabilidad de NetApp (IMT)"].




== Requisitos de configuración del servidor VSCAN

* Debe instalar .NET 3,0 o posterior y debe habilitar SMB 2,0 en el servidor Vscan. En el caso de los servidores SMB con una política de exportación, debe agregar todos los servidores Vscan a la política.
* Puede instalar diferentes versiones del sistema operativo Windows Server en diferentes servidores Vscan de un clúster. Como mínimo, el conector antivirus ONTAP requiere Windows Server 2008.

