---
permalink: antivirus/vscan-server-connection-concept.html 
sidebar: sidebar 
keywords: potential connectivity, issues, involve, scan-mandatory, option 
summary: De forma predeterminada, la opción de análisis obligatorio para el análisis en tiempo real deniega el acceso a los archivos cuando una conexión de servidor Vscan no está disponible para el análisis. Aunque esta opción ofrece importantes funciones de seguridad, puede dar lugar a problemas en algunas situaciones. 
---
= Posibles problemas de conectividad relacionados con la opción de adquisición obligatoria
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `vserver vscan connection-status show` Comandos para ver información acerca de las conexiones del servidor Vscan que puede resultar útil para solucionar problemas de conectividad.

De forma predeterminada, la `scan-mandatory` La opción para el análisis en tiempo real deniega el acceso a archivos cuando no hay disponible una conexión de servidor Vscan para el análisis. Aunque esta opción ofrece importantes funciones de seguridad, puede dar lugar a problemas en algunas situaciones.

* Antes de habilitar el acceso de cliente, debe asegurarse de que al menos un servidor Vscan esté conectado a una SVM en cada nodo que tenga una LIF. Si necesita conectar servidores a las SVM después de habilitar el acceso de cliente, debe desactivar el `scan-mandatory` Opción en la SVM para asegurarse de que no se deniega el acceso al archivo porque no hay una conexión de servidor Vscan disponible. Puede volver a activar la opción después de haber conectado el servidor.
* Si un LIF de destino aloja todas las conexiones del servidor Vscan para una SVM, la conexión entre el servidor y la SVM se perderá si se migra el LIF. Para asegurarse de que no se deniega el acceso a los archivos porque no hay una conexión de servidor Vscan disponible, debe desactivar el `scan-mandatory` Opción antes de migrar la LIF. Puede volver a activar la opción después de migrar el LIF.


Cada SVM debe tener al menos dos servidores Vscan asignados. Se recomienda conectar los servidores Vscan al sistema de almacenamiento a través de una red diferente a la utilizada para el acceso de los clientes.
