---
permalink: revert/anti-ransomware-disable-san.html 
sidebar: sidebar 
keywords: revert, reverting, reversion, anti-ransomware, san, autonomous, protection, arp 
summary: Deshabilite ARP en los volúmenes SAN antes de volver a ONTAP 9.16.1 o anterior para evitar el consumo innecesario de CPU y espacio en disco. 
---
= Deshabilite la protección autónoma contra ransomware en volúmenes SAN antes de revertir desde ONTAP 9.17.1
:allow-uri-read: 


[role="lead"]
La función ARP de ONTAP para volúmenes SAN no es compatible con ONTAP 9.16.1 ni versiones anteriores. Se recomienda desactivar ARP en volúmenes SAN antes de revertir a ONTAP 9.16.1 o versiones anteriores para evitar que la función permanezca activa y utilice recursos de CPU y disco sin realizar ninguna detección en la versión revertida.

.Pasos
[role="tabbed-block"]
====
.System Manager
--
. Seleccione *Almacenamiento > Volúmenes* y, luego, seleccione el nombre del volumen.
. En la pestaña *Seguridad* de la descripción general de *Volúmenes*, seleccione *Estado* para cambiar de Habilitado a Deshabilitado.


--
.CLI
--
. Deshabilitar la protección contra ransomware en un volumen:
+
[source, cli]
----
security anti-ransomware volume disable -volume <vol_name> -vserver <svm_name>
----


--
====