---
permalink: revert/concept_revert_paths.html 
sidebar: sidebar 
keywords: ontap, downgrade, revert, paths 
summary: Puede revertir directamente el software de ONTAP a una versión anterior a la versión actual de ONTAP. No debe revertir a versiones de ONTAP no compatibles. 
---
= Rutas de reversión de ONTAP admitidas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede revertir directamente el software de ONTAP a solo una versión anterior a la versión actual de ONTAP. Por ejemplo, si está ejecutando 9.15.1, no puede revertir directamente a 9.13.1. Debe revertir a 9.14.1 y, a continuación, realizar una reversión independiente de 9.14.1 a 9.13.1.

No se admite la reversión a ONTAP 9,4 o una versión anterior. No debe revertir a versiones de ONTAP no compatibles.

Puede usar el `system image show` comando para determinar la versión de ONTAP que se ejecuta en cada nodo.

Las siguientes rutas de reversión admitidas solo hacen referencia a las versiones de ONTAP locales. Para obtener información sobre cómo revertir ONTAP en la nube, consulte https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html#reverting-or-downgrading["Revertir o degradar Cloud Volumes ONTAP"^].

[cols="2*"]
|===
| Puede revertir de... | Para... 


 a| 
ONTAP 9.18.1
| ONTAP 9.17.1 


 a| 
ONTAP 9.17.1
| ONTAP 9.16.1 


 a| 
ONTAP 9.16.1
| ONTAP 9.15.1 


 a| 
ONTAP 9.15.1
| ONTAP 9.14.1 


 a| 
ONTAP 9.14.1
| ONTAP 9.13.1 


 a| 
ONTAP 9.13.1
| ONTAP 9.12.1 


 a| 
ONTAP 9.12.1
| ONTAP 9.11.1 


 a| 
ONTAP 9.11.1
| ONTAP 9.10.1 


 a| 
ONTAP 9.10.1
| ONTAP 9.9.1 


 a| 
ONTAP 9.9.1
| ONTAP 9,8 


 a| 
ONTAP 9,8
| ONTAP 9,7 


 a| 
ONTAP 9,7
| ONTAP 9,6 


 a| 
ONTAP 9,6
| ONTAP 9,5 
|===