---
permalink: revert/concept_when_to_call_technical_support.html 
sidebar: sidebar 
keywords: ontap, downgrade, revert, paths 
summary: Es posible revertir sin ayuda en clústeres nuevos o de prueba.  Debe llamar al soporte técnico para revertir los clústeres de producción. 
---
= ¿Necesito soporte técnico para revertir?
:allow-uri-read: 


[role="lead"]
Es posible revertir sin ayuda en clústeres nuevos o de prueba.  Debe llamar al soporte técnico para revertir los clústeres de producción.  También debe llamar al soporte técnico si experimenta alguna de las siguientes situaciones:

* Está en un entorno de producción y la reversión falla o se encuentra con cualquier problema antes o después de la reversión, como:
+
** El proceso de reversión falla y no puede finalizar.
** El proceso de reversión finaliza, pero el clúster no se puede utilizar en un entorno de producción.
** El proceso de reversión se finaliza y el clúster se pone en producción, pero no está satisfecho con su comportamiento.


* Creó volúmenes en ONTAP 9.5 o una versión posterior y debe revertir a una versión anterior. Los volúmenes que utilizan compresión adaptativa deben descomprimidos antes de revertir.

