---
permalink: revert/remove-nas-bucket-task.html 
sidebar: sidebar 
keywords: s3, svm, bucket, object, server, filesystems, nas, directories, revert 
summary: Si ha configurado el acceso de cliente S3 para datos NAS y vuelve de ONTAP 9.12.1 o posterior a ONTAP 9.11.1 o anterior, debe eliminar la configuración de bloque NAS y debe eliminar cualquier usuario S3 a las asignaciones de nombre de usuario de Windows/Unix antes de revertir. 
---
= Elimine la configuración del cucharón NAS de S3 antes de volver de ONTAP 9.12.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si ha configurado el acceso de cliente S3 para los datos del NAS, debe utilizar la interfaz de línea de comandos (CLI) de ONTAP para eliminar la configuración del bucket del NAS y para eliminar cualquier asignación de nombres (usuarios S3 a usuarios de Windows o Unix) antes de revertir desde ONTAP 9.12.1.

.Acerca de esta tarea
Las siguientes tareas se completan en segundo plano durante el proceso de reversión.

* Quite todas las creaciones de objetos singleton completadas parcialmente (es decir, todas las entradas de directorios ocultos).
* Quite todos los directorios ocultos; puede haber uno en cada volumen al que se pueda acceder desde la raíz de la exportación asignada desde el bloque NAS de S3.
* Retire la tabla de carga.
* Elimine los valores de usuario predeterminados de unix-user y Windows-default para todos los servidores S3 configurados.


.Pasos
. Eliminar la configuración del bucket NAS de S3:
+
[source, cli]
----
vserver object-store-server bucket delete -vserver <svm_name> -bucket <s3_nas_bucket_name>
----
+
Obtenga más información sobre `vserver object-store-server bucket delete` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-object-store-server-bucket-delete.html["Referencia de comandos de la ONTAP"^].

. Eliminar asignaciones de nombres para UNIX:
+
[source, cli]
----
vserver name-mapping delete -vserver <svm_name> -direction s3-unix
----
+
Obtenga más información sobre `vserver name-mapping delete` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-name-mapping-delete.html["Referencia de comandos de la ONTAP"^].

. Eliminar asignaciones de nombres para Windows:
+
[source, cli]
----
vserver name-mapping delete -vserver <svm_name> -direction s3-win
----
. Quite los protocolos S3 de la SVM:
+
[source, cli]
----
vserver remove-protocols -vserver <svm_name> -protocols s3
----
+
Obtenga más información sobre `vserver remove-protocols` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-remove-protocols.html["Referencia de comandos de la ONTAP"^].


