---
permalink: revert/remove-nfs-trunking-task.html 
sidebar: sidebar 
keywords: nfsv4.1, trunking, revert 
summary: Si ha activado la conexión troncal para las conexiones de cliente y vuelve a una versión anterior a ONTAP 9.12.1, debe deshabilitar la conexión troncal en cualquier servidor NFSv4,1 antes de revertir. 
---
= Desactive la troncalización de sesión NFSv4,1 antes de revertir desde ONTAP 9.14.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si ha activado la conexión de enlaces para las conexiones de cliente, debe deshabilitar la conexión de enlaces en cualquier servidor NFSv4,1 antes de revertir desde ONTAP 9.14.1.

Cuando introduzca la `revert-to` comando, verá un mensaje de advertencia para informarle de que deshabilite la conexión troncal antes de continuar.

Después de volver a un ONTAP 9.13.1, los clientes que utilizan conexiones troncalizadas vuelven a utilizar una única conexión. El rendimiento de sus datos se verá afectado, pero no habrá interrupción. El comportamiento de reversión es el mismo que modificar la opción de Trunking NFSv4,1 para la SVM de enabled a disabled.

.Pasos
. Desactive la conexión troncal en el servidor NFSv4,1:
+
[source, cli]
----
vserver nfs modify -vserver _svm_name_ -v4.1-trunking disabled
----
. Compruebe que NFS está configurado como se desea:
+
[source, cli]
----
vserver nfs show -vserver _svm_name_
----

