---
permalink: revert/task_reverting_an_ontap_cluster.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, cluster 
summary: Para desconectar el clúster y volver a una versión ONTAP anterior, debe deshabilitar la conmutación por error del almacenamiento y los LIF de datos, abordar las condiciones previas para la reversión, revertir la configuración del clúster y del sistema de archivos en un nodo y, a continuación, repetir el proceso para cada nodo adicional del clúster. 
---
= Revertir un clúster de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Revertir un clúster ONTAP es disruptivo. Debe desconectar el clúster durante la reversión. No debe revertir un clúster de producción sin la ayuda del soporte técnico.

Para revertir un clúster nuevo o de prueba, debe deshabilitar la conmutación por error de almacenamiento y los LIF de datos y abordar las condiciones previas de la reversión; a continuación, debe revertir la configuración del clúster y del sistema de archivos de cada nodo del clúster.

.Antes de empezar.
* Debe haber completado el link:task_things_to_verify_before_revert.html["verificaciones previas a la reversión"].
* Debe haber completado el requisito link:concept_pre_revert_checks.html["Realiza comprobaciones previas para la versión específica de ONTAP"].




== Paso 1: Preparar el clúster para la reversión

Antes de revertir cualquiera de los nodos del clúster, debe verificar que su imagen ONTAP de destino esté instalada y debe deshabilitar todas las LIF de datos del clúster.

.Pasos
. Configure el nivel de privilegio en Advanced:
+
[source, cli]
----
set -privilege advanced
----
+
Introduzca *y* cuando se le solicite continuar.

. Compruebe que el software ONTAP de destino está instalado:
+
[source, cli]
----
system image show
----
+
El siguiente ejemplo muestra que se instala la versión 9.13.1 como imagen alternativa en ambos nodos:

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
node1
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
4 entries were displayed.
----
. Deshabilite todas las LIF de datos del clúster:
+
[source, cli]
----
network interface modify {-role data} -status-admin down
----
. Determinar si tiene relaciones de FlexCache entre clústeres:
+
[source, cli]
----
flexcache origin show-caches -relationship-type inter-cluster
----
. Si hay destellos entre clústeres, deshabilite los datos del clúster de caché:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -status-admin down
----




== Paso 2: Revertir los nodos del cluster

Para revertir su clúster, debe revertir el primer nodo de un par de alta disponibilidad y, a continuación, revertir el nodo del partner. A continuación, repita este proceso para cada pareja de alta disponibilidad del clúster hasta que se reviertan todos los nodos. Si tiene una configuración MetroCluster, debe repetir estos pasos para los dos clústeres de la configuración.

[role="tabbed-block"]
====
.4 nodos o más
--
.Pasos
. Inicie sesión en el nodo que desee revertir.
+
Para revertir un nodo, debe haber iniciado sesión en el clúster a través de la LIF de gestión del nodo del nodo.

. Deshabilite la recuperación tras fallos de almacenamiento para los nodos del par de alta disponibilidad:
+
[source, cli]
----
storage failover modify -node <nodename> -enabled false
----
+
Solo tiene que deshabilitar la conmutación por error del almacenamiento una vez para el par de alta disponibilidad. Cuando deshabilita la conmutación al respaldo de almacenamiento para un nodo, la conmutación al respaldo de almacenamiento también se deshabilita en el compañero de nodo.

. Establezca la imagen de software ONTAP de destino del nodo en ser la imagen predeterminada:
+
[source, cli]
----
system image modify -node <nodename> -image <target_image> -isdefault true
----
. Verifique que la imagen del software de ONTAP de destino se esté establecida como la imagen predeterminada del nodo que está revirtiendo:
+
[source, cli]
----
system image show
----
+
El siguiente ejemplo muestra que la versión 9.13.1 se establece como la imagen predeterminada en node0:

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  false   true    9.14.1      MM/DD/YYYY TIME
         image2  true    false   9.13.1      MM/DD/YYYY TIME
node1
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
4 entries were displayed.
----
. Compruebe que el nodo esté listo para la nueva versión:
+
[source, cli]
----
system node revert-to -node <nodename> -check-only true -version 9.x
----
+
 `check-only`El parámetro identifica todas las condiciones previas que deben solucionarse antes de revertir, como deshabilitar la política de Snapshot o eliminar copias Snapshot que se crearon después de actualizar a la versión posterior de ONTAP.

+
 `-version`La opción hace referencia a la versión de ONTAP a la que desea revertir. Por ejemplo, si va a revertir de 9.14.1 a 9.13.1, el valor correcto de la `-version` opción es 9.13.1.

. Revierte la configuración del clúster del nodo:
+
[source, cli]
----
system node revert-to -node <nodename> -version 9.x
----
+
La configuración del clúster se revierte y luego se cierra la sesión en el clustershell.

. Espere la solicitud de inicio de sesión; luego ingrese *No* cuando se le pregunte si desea iniciar sesión en el systemshell.
+
La solicitud de inicio de sesión puede tardar hasta 30 minutos o más en aparecer.

. Inicie sesión en el clustershell con admin.
. Cambia a la infierno:
+
[source, cli]
----
run -node <nodename>
----
+
Después de iniciar sesión de nuevo en el clustershell, puede tardar unos minutos antes de que esté listo para aceptar el comando nodeshell. Por lo tanto, si el comando falla, espere unos minutos y vuelva a intentarlo.

. Revierte la configuración del sistema de archivos del nodo:
+
[source, cli]
----
revert_to 9.x
----
+
Este comando verifica que la configuración del sistema de archivos del nodo está lista para revertirse y después lo revierte. Si se identifica alguna condición previa, debe solucionarla y luego volver a ejecutar `revert_to` el comando.

+

NOTE: El uso de una consola del sistema para supervisar el proceso de reversión muestra más detalles que los que se ven en el infierno.

+
Si se cumple LA FUNCIÓN AUTOBOOT, cuando el comando finaliza, el nodo se reiniciará en ONTAP.

+
Si AUTOBOOT es false, cuando finaliza el comando, se muestra el símbolo del sistema DE Loader. Introduzca `yes` para revertir y, a continuación, utilice `boot_ontap` para reiniciar manualmente el nodo.

. Cuando el nodo se haya reiniciado, confirme que el nuevo software está en ejecución:
+
[source, cli]
----
system node image show
----
+
En el siguiente ejemplo, image1 es la nueva versión de ONTAP y se establece como la versión actual del nodo 0:

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. Compruebe que el estado de reversión del nodo esté completo:
+
[source, cli]
----
system node upgrade-revert show -node <nodename>
----
+
El estado debe aparecer como Finalizado, No Necesario o No hay ninguna entrada de tabla devuelta.

. Repita estos pasos en el otro nodo del par de alta disponibilidad y repita estos pasos para cada par de alta disponibilidad adicional.
+
Si tiene una configuración MetroCluster, debe repetir estos pasos en ambos clústeres de la configuración

. Después de revertir todos los nodos, vuelva a habilitar la alta disponibilidad para el clúster:
+
[source, cli]
----
cluster ha modify -configured true
----


--
.Clúster de 2 nodos
--
. Inicie sesión en el nodo que desee revertir.
+
Para revertir un nodo, debe haber iniciado sesión en el clúster a través de la LIF de gestión del nodo del nodo.

. Deshabilite la alta disponibilidad en clúster:
+
[source, cli]
----
cluster ha modify -configured false
----
. Desactivar la recuperación tras fallos del almacenamiento:
+
[source, cli]
----
storage failover modify -node <nodename> -enabled false
----
+
Solo tiene que deshabilitar la conmutación por error del almacenamiento una vez para el par de alta disponibilidad. Cuando deshabilita la conmutación al respaldo de almacenamiento para un nodo, la conmutación al respaldo de almacenamiento también se deshabilita en el compañero de nodo.

. Establezca la imagen de software ONTAP de destino del nodo en ser la imagen predeterminada:
+
[source, cli]
----
system image modify -node <nodename> -image <target_image> -isdefault true
----
. Verifique que la imagen del software de ONTAP de destino se esté establecida como la imagen predeterminada del nodo que está revirtiendo:
+
[source, cli]
----
system image show
----
+
En el siguiente ejemplo, se muestra que la versión 9.1 se establece como la imagen predeterminada en el nodo 0:

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  false   true    9.2        MM/DD/YYYY TIME
         image2  true    false   9.1        MM/DD/YYYY TIME
node1
         image1  true    true    9.2        MM/DD/YYYY TIME
         image2  false   false   9.1        MM/DD/YYYY TIME
4 entries were displayed.
----
. Compruebe si el nodo está actualmente configurado con épsilon:
+
[source, cli]
----
cluster show -node <nodename>
----
+
En el siguiente ejemplo se muestra que el nodo está configurado con épsilon:

+
[listing]
----
cluster1::*> cluster show -node node1

          Node: node1
          UUID: 026efc12-ac1a-11e0-80ed-0f7eba8fc313
       Epsilon: true
   Eligibility: true
        Health: true
----
+
.. Si el nodo no está configurado con épsilon, márquelo como falso en el nodo para que se pueda transferir el valor épsilon al partner del nodo:
+
[source, cli]
----
cluster modify -node <nodename> -epsilon false
----
.. Transfiera el valor épsilon al partner del nodo marcando épsilon true en el nodo del partner:
+
[source, cli]
----
cluster modify -node <node_partner_name> -epsilon true
----


. Compruebe que el nodo esté listo para la nueva versión:
+
[source, cli]
----
system node revert-to -node <nodename> -check-only true -version 9.x
----
+
 `check-only`El parámetro identifica todas las condiciones que deben solucionarse antes de revertir, como deshabilitar la política de Snapshot o eliminar copias Snapshot que se crearon después de actualizar a la versión posterior de ONTAP.

. Revierte la configuración del clúster del nodo:
+
[source, cli]
----
system node revert-to -node <nodename> -version 9.x
----
+
 `-version`La opción hace referencia a la versión de ONTAP a la que desea revertir. Por ejemplo, si va a revertir de 9.14.1 a 9.13.1, el valor correcto de la `-version` opción es 9.13.1.

+
La configuración del clúster se revierte y luego se cierra la sesión en el clustershell.

. Espere la solicitud de inicio de sesión; a continuación, introduzca `No` cuando se le pregunte si desea iniciar sesión en el shell del sistema.
+
La solicitud de inicio de sesión puede tardar hasta 30 minutos o más en aparecer.

. Inicie sesión en el clustershell con admin.
. Cambia a la infierno:
+
[source, cli]
----
run -node <nodename>
----
+
Después de iniciar sesión de nuevo en el clustershell, puede tardar unos minutos antes de que esté listo para aceptar el comando nodeshell. Por lo tanto, si el comando falla, espere unos minutos y vuelva a intentarlo.

. Revierte la configuración del sistema de archivos del nodo:
+
[source, cli]
----
revert_to 9.x
----
+
Este comando verifica que la configuración del sistema de archivos del nodo está lista para revertirse y después lo revierte. Si se identifica alguna condición previa, debe solucionarla y luego volver a ejecutar `revert_to` el comando.

+

NOTE: El uso de una consola del sistema para supervisar el proceso de reversión muestra más detalles que los que se ven en el infierno.

+
Si se cumple LA FUNCIÓN AUTOBOOT, cuando el comando finaliza, el nodo se reiniciará en ONTAP.

+
Si el INICIO AUTOMÁTICO es falso, cuando el comando finaliza el símbolo del sistema del CARGADOR se muestra. Introduzca `yes` para revertir y después usarlo `boot_ontap` para reiniciar manualmente el nodo.

. Cuando el nodo se haya reiniciado, confirme que el nuevo software está en ejecución:
+
[source, cli]
----
system node image show
----
+
En el siguiente ejemplo, image1 es la nueva versión de ONTAP y se establece como la versión actual del nodo 0:

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. Compruebe que el estado de reversión sea Completado para el nodo:
+
[source, cli]
----
system node upgrade-revert show -node <nodename>
----
+
El estado debe aparecer como Finalizado, No Necesario o No hay ninguna entrada de tabla devuelta.

. Repita estos pasos en el otro nodo del par de alta disponibilidad.
. Después de revertir ambos nodos, vuelva a habilitar la alta disponibilidad para el clúster:
+
[source, cli]
----
cluster ha modify -configured true
----
. Vuelva a habilitar la recuperación tras fallos de almacenamiento en ambos nodos:
+
[source, cli]
----
storage failover modify -node <nodename> -enabled true
----


--
====