---
permalink: revert/task_quiesce_snapmirror_relationships_before_downgrade.html 
sidebar: sidebar 
keywords: ontap, downgrade, downgrading, snapmirror, operations, quisce 
summary: Se recomienda desactivar las operaciones de SnapMirror antes de realizar una degradación no disruptiva de ONTAP. 
---
= Desactive las relaciones de SnapMirror antes de la degradación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se recomienda desactivar las operaciones de SnapMirror antes de realizar una degradación de ONTAP.

. Utilice el comando snapmirror show para determinar la ruta de destino de cada relación de SnapMirror.
. Para cada volumen de destino, suspenda las futuras transferencias de SnapMirror: `snapmirror quiesce -destination-path destination`
+
Si no hay transferencias activas para la relación de SnapMirror, este comando establece su estado en Quiesced. Si la relación tiene transferencias activas, el estado se establece en inactivo hasta que se completa la transferencia y, a continuación, el estado se convierte en Quiesced.

+
En este ejemplo, se realizan transferencias relacionadas con el volumen de destino vol1 de SVMvs0.example.com:

+
[listing]
----
cluster1::> snapmirror quiesce -destination-path vs0.example.com:vol1
----
. Compruebe que todas las relaciones de SnapMirror se ponen en modo inactivo: `snapmirror show -status !Quiesced`
+
Este comando muestra cualquier relación de SnapMirror que se _no_ en modo inactivo.

+
Este ejemplo muestra que todas las relaciones de SnapMirror se ponen en modo inactivo:

+
[listing]
----
cluster1::> snapmirror show -status !Quiesced
There are no entries matching your query.
----
. Si actualmente se está transfiriendo alguna de las relaciones de SnapMirror, realice una de las siguientes opciones:
+
[cols="2*"]
|===
| Opción | Descripción 


 a| 
Espere a que las transferencias finalicen antes de ejecutar la degradación de ONTAP.
 a| 
Después de que se termina cada transferencia, la relación cambia al estado Quiesced.



 a| 
Detenga las transferencias: `snapmirror abort -destination-path destination -h` *Nota:* debe utilizar el parámetro -foreground true si va a cancelar las transferencias de espejo de reparto de carga.
 a| 
Este comando detiene la transferencia de SnapMirror y restaura el volumen de destino a la última copia de Snapshot que se transfirió correctamente. La relación se establece en el estado Quiesced.

|===

