---
permalink: revert/task_identifying_and_moving_cifs_servers_in_workgroup_mode.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, identifying, identify, move, moving, delete, deleting, cifs, servers, workgroup, mode, SMB 
summary: Antes de realizar una reversión, debe eliminar cualquier servidor SMB en modo de grupo de trabajo o moverlos a un dominio. El modo de grupo de trabajo no es compatible con las versiones de ONTAP anteriores a ONTAP 9. 
---
= Identificar y mover servidores SMB en modo de grupo de trabajo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de realizar una reversión, debe eliminar cualquier servidor SMB en modo de grupo de trabajo o moverlos a un dominio. El modo de grupo de trabajo no es compatible con las versiones de ONTAP anteriores a ONTAP 9.

. Identificar cualquier servidor SMB con un estilo de autenticación de grupo de trabajo: `vserver cifs show`
. Mueva o elimine los servidores identificados:
+
[cols="2*"]
|===
| Si va a... | A continuación, utilice este comando.... 


 a| 
Mover el servidor SMB del grupo de trabajo a un dominio de Active Directory:
 a| 
`vserver cifs modify -vserver _vserver_name_ -domain _domain_name_`



 a| 
Elimine el servidor SMB
 a| 
`vserver cifs delete -vserver vserver_name`

|===
. Si eliminó el servidor SMB, introduzca el nombre de usuario del dominio y la contraseña de usuario.


.Información relacionada
link:../smb-admin/index.html["Gestión de SMB"]
