---
permalink: revert/task_things_to_verify_before_revert.html 
sidebar: sidebar 
keywords: ontap, revert, reversion, reverting, downgrade, downgrading, preparation, pre-revert, checks, verification, cluster health, storage health, system time, jobs 
summary: Antes de revertir ONTAP, debe comprobar el estado del clúster, el estado del almacenamiento y la hora del sistema. También debe verificar que no existan trabajos en ejecución en el clúster. 
---
= Las verificaciones del sistema que se deben realizar antes de revertir un clúster de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de revertir un clúster de ONTAP, debe comprobar el estado del clúster, el estado del almacenamiento y la hora del sistema. También debe verificar que no existan trabajos en ejecución en el clúster.



== Compruebe el estado del clúster

Antes de revertir un clúster ONTAP, debe verificar que los nodos estén en buen estado y que puedan participar en el clúster y que el clúster esté en quórum.

.Pasos
. Compruebe que los nodos del clúster estén en línea y que puedan participar en el clúster:
+
[source, cli]
----
cluster show
----
+
En este ejemplo, todos los nodos están en buen estado y pueden participar en el clúster.

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
node0                 true    true
node1                 true    true
----
+
Si alguno de los nodos no es saludable o no apto, compruebe los registros de EMS en busca de errores y realice acciones correctivas.

. Configure el nivel de privilegio en Advanced:
+
[source, cli]
----
set -privilege advanced
----
+
Introduzca `y` para continuar.

. Verifique los detalles de configuración de cada proceso RDB.
+
** Las épocas de la base de datos relacional y la base de datos deben coincidir para cada nodo.
** El maestro de quórum por anillo debe ser el mismo para todos los nodos.
+
Tenga en cuenta que cada anillo puede tener un maestro de quórum diferente.

+
[cols="2*"]
|===
| Para mostrar este proceso RDB: | Introduzca este comando... 


 a| 
Aplicación de gestión
 a| 
[source, cli]
----
cluster ring show -unitname mgmt
----


 a| 
Base de datos de ubicación del volumen
 a| 
[source, cli]
----
cluster ring show -unitname vldb
----


 a| 
Administrador de interfaz virtual
 a| 
[source, cli]
----
cluster ring show -unitname vifmgr
----


 a| 
Daemon de gestión de SAN
 a| 
[source, cli]
----
cluster ring show -unitname bcomd
----
|===
+
Este ejemplo muestra el proceso de la base de datos de ubicación del volumen:

+
[listing]
----
cluster1::*> cluster ring show -unitname vldb
Node      UnitName Epoch    DB Epoch DB Trnxs Master    Online
--------- -------- -------- -------- -------- --------- ---------
node0     vldb     154      154      14847    node0     master
node1     vldb     154      154      14847    node0     secondary
node2     vldb     154      154      14847    node0     secondary
node3     vldb     154      154      14847    node0     secondary
4 entries were displayed.
----


. Vuelva al nivel de privilegio de administrador:
+
[source, cli]
----
set -privilege admin
----
. Si va a trabajar en un entorno SAN, compruebe que cada nodo se encuentra en quórum DE SAN:
+
[source, cli]
----
event log show  -severity informational -message-name scsiblade.*
----
+
El mensaje de evento scsiblade más reciente para cada nodo debe indicar que el scsi-blade está en quórum.

+
[listing]
----
cluster1::*> event log show  -severity informational -message-name scsiblade.*
Time             Node       Severity       Event
---------------  ---------- -------------- ---------------------------
MM/DD/YYYY TIME  node0      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
MM/DD/YYYY TIME  node1      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
----


.Información relacionada
link:../system-admin/index.html["Administración del sistema"]



== Comprobación del estado del almacenamiento

Antes de revertir un clúster de ONTAP, debe comprobar el estado de los discos, los agregados y los volúmenes.

.Pasos
. Compruebe el estado del disco:
+
[cols="2*"]
|===
| Para comprobar... | Realice lo siguiente... 


 a| 
Discos rotos
 a| 
.. Mostrar cualquier disco roto:
+
[source, cli]
----
storage disk show -state broken
----
.. Retire o sustituya los discos rotos.




 a| 
Discos sometidos a mantenimiento o reconstrucción
 a| 
.. Muestre cualquier disco en estado de mantenimiento, pendiente o reconstrucción:
+
[source, cli]
----
storage disk show -state maintenance|pending|reconstructing
----
.. Espere a que la operación de mantenimiento o reconstrucción finalice antes de continuar.


|===
. Compruebe que todos los agregados están en línea mostrando el estado de almacenamiento físico y lógico, incluidos los agregados de almacenamiento: +
+
[source, cli]
----
storage aggregate show -state !online
----
+
Este comando muestra los agregados que _not_ están en línea. Todos los agregados deben estar en línea antes y después de realizar una actualización o versión posterior principales.

+
[listing]
----
cluster1::> storage aggregate show -state !online
There are no entries matching your query.
----
. Verifique que todos los volúmenes estén en línea mostrando los volúmenes que _not_ en línea:
+
[source, cli]
----
volume show -state !online
----
+
Todos los volúmenes deben estar en línea antes y después de realizar una actualización o versión posterior principales.

+
[listing]
----
cluster1::> volume show -state !online
There are no entries matching your query.
----
. Compruebe que no haya volúmenes incoherentes:
+
[source, cli]
----
volume show -is-inconsistent true
----
+
Consulte el artículo de la base de conocimientos link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Volume_Showing_WAFL_Inconsistent["Volumen que muestra una incoherencia de WAFL"] sobre la forma de abordar los volúmenes incoherentes.



.Información relacionada
link:../disks-aggregates/index.html["Gestión de discos y agregados"]



== Compruebe la hora del sistema

Antes de revertir un clúster de ONTAP, debe comprobar que NTP esté configurado y que la hora esté sincronizada en todo el clúster.

.Pasos
. Compruebe que el clúster esté asociado con un servidor NTP:
+
[source, cli]
----
cluster time-service ntp server show
----
. Compruebe que cada nodo tiene la misma fecha y hora:
+
[source, cli]
----
cluster date show
----
+
[listing]
----
cluster1::> cluster date show
Node      Date                Timezone
--------- ------------------- -------------------------
node0     4/6/2013 20:54:38   GMT
node1     4/6/2013 20:54:38   GMT
node2     4/6/2013 20:54:38   GMT
node3     4/6/2013 20:54:38   GMT
4 entries were displayed.
----




== Compruebe que no hay trabajos en ejecución

Antes de revertir un clúster ONTAP, debe comprobar el estado de los trabajos del clúster. Si cualquier trabajo de agregado, volumen, NDMP (volcado o restauración) o Snapshot (como trabajos de creación, eliminación, movimiento, modificación, replicación y montaje) se está ejecutando o en cola, debe permitir que los trabajos se finalicen correctamente o detener las entradas en cola.

.Pasos
. Revise la lista de trabajos en ejecución o en cola de agregados, volúmenes o copias Snapshot:
+
[source, cli]
----
job show
----
+
En este ejemplo, hay dos trabajos en cola:

+
[listing]
----
cluster1::> job show
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
8629   Vol Reaper           cluster1   -              Queued
       Description: Vol Reaper Job
8630   Certificate Expiry Check
                            cluster1   -              Queued
       Description: Certificate Expiry Check
----
. Elimine cualquier trabajo que esté en ejecución o en cola de agregados, volúmenes o copias Snapshot:
+
[source, cli]
----
job delete -id <job_id>
----
. Compruebe que no haya trabajos de agregado, volumen ni Snapshot en ejecución ni en la cola:
+
[source, cli]
----
job show
----
+
En este ejemplo, se han eliminado todos los trabajos en ejecución y en cola:

+
[listing]
----
cluster1::> job show
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
9944   SnapMirrorDaemon_7_2147484678
                            cluster1   node1          Dormant
       Description: Snapmirror Daemon for 7_2147484678
18377  SnapMirror Service Job
                            cluster1   node0          Dormant
       Description: SnapMirror Service Job
2 entries were displayed
----

