---
permalink: revert/task_verify_health.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, downgrade, downgrading, verifying, verify, cluster, health 
summary: Después de revertir o degradar un clúster, debe comprobar que los nodos estén en buen estado y puedan participar en el clúster, así como que el clúster esté de quórum. 
---
= Verifique el estado del clúster y del almacenamiento después de la degradación o la reversión
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de degradar o revertir un clúster, debe comprobar que los nodos estén en buen estado y que puedan participar en el clúster, así como que el clúster esté de quórum. También debe verificar el estado de los discos, los agregados y los volúmenes.



== Compruebe el estado del clúster

. Compruebe que los nodos del clúster estén en línea y que puedan participar en el clúster: `cluster show`
+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
node0                 true    true
node1                 true    true
----
+
Si alguno de los nodos no es saludable o no apto, compruebe los registros de EMS en busca de errores y realice acciones correctivas.

. Establezca el nivel de privilegio en Advanced: +
`set -privilege advanced`
+
Introduzca `y` para continuar.

. Verifique los detalles de configuración de cada proceso RDB.
+
** Las épocas de la base de datos relacional y la base de datos deben coincidir para cada nodo.
** El maestro de quórum por anillo debe ser el mismo para todos los nodos.
+
Tenga en cuenta que cada anillo puede tener un maestro de quórum diferente.

+
[cols="2*"]
|===
| Para mostrar este proceso RDB: | Introduzca este comando... 


 a| 
Aplicación de gestión
 a| 
`cluster ring show -unitname mgmt`



 a| 
Base de datos de ubicación del volumen
 a| 
`cluster ring show -unitname vldb`



 a| 
Administrador de interfaz virtual
 a| 
`cluster ring show -unitname vifmgr`



 a| 
Daemon de gestión de SAN
 a| 
`cluster ring show -unitname bcomd`

|===
+
Este ejemplo muestra el proceso de la base de datos de ubicación del volumen:



+
[listing]
----
cluster1::*> cluster ring show -unitname vldb
Node      UnitName Epoch    DB Epoch DB Trnxs Master    Online
--------- -------- -------- -------- -------- --------- ---------
node0     vldb     154      154      14847    node0     master
node1     vldb     154      154      14847    node0     secondary
node2     vldb     154      154      14847    node0     secondary
node3     vldb     154      154      14847    node0     secondary
4 entries were displayed.
----
. Vuelva al nivel de privilegio de administrador: `set -privilege admin`
. Si va a trabajar en un entorno SAN, compruebe que cada nodo se encuentra en quórum DE SAN: `event log show  -severity informational -message-name scsiblade.*`
+
El mensaje de evento scsiblade más reciente para cada nodo debe indicar que el scsi-blade está en quórum.

+
[listing]
----
cluster1::*> event log show  -severity informational -message-name scsiblade.*
Time             Node       Severity       Event
---------------  ---------- -------------- ---------------------------
MM/DD/YYYY TIME  node0      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
MM/DD/YYYY TIME  node1      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
----


.Información relacionada
link:../system-admin/index.html["Administración del sistema"]



== Comprobación del estado del almacenamiento

Después de revertir o degradar un clúster, debe verificar el estado de los discos, agregados y volúmenes.

. Compruebe el estado del disco:
+
[cols="2*"]
|===
| Para comprobar... | Realice lo siguiente... 


 a| 
Discos rotos
 a| 
.. Mostrar cualquier disco roto: `storage disk show -state broken`
.. Retire o sustituya los discos rotos.




 a| 
Discos sometidos a mantenimiento o reconstrucción
 a| 
.. Muestre cualquier disco en estado de mantenimiento, pendiente o reconstrucción: `storage disk show -state maintenance|pending|reconstructing`
.. Espere a que la operación de mantenimiento o reconstrucción finalice antes de continuar.


|===
. Compruebe que todos los agregados están en línea mostrando el estado del almacenamiento físico y lógico, incluidos los agregados de almacenamiento: `storage aggregate show -state !online`
+
Este comando muestra los agregados que _not_ están en línea. Todos los agregados deben estar en línea antes y después de realizar una actualización o versión posterior principales.

+
[listing]
----
cluster1::> storage aggregate show -state !online
There are no entries matching your query.
----
. Verifique que todos los volúmenes estén en línea mostrando los volúmenes que _not_ en línea: `volume show -state !online`
+
Todos los volúmenes deben estar en línea antes y después de realizar una actualización o versión posterior principales.

+
[listing]
----
cluster1::> volume show -state !online
There are no entries matching your query.
----
. Compruebe que no haya volúmenes incoherentes: `volume show -is-inconsistent true`
+
Consulte el artículo de la base de conocimientos link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Volume_Showing_WAFL_Inconsistent["Volumen que muestra una incoherencia de WAFL"] sobre la forma de abordar los volúmenes incoherentes.



.Información relacionada
link:../disks-aggregates/index.html["Gestión de discos y agregados"]
