---
permalink: revert/task_enabling_and_reverting_lifs_to_home_ports_completing_post_reversion_tasks.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, downgrade, downgrading, enable, enabling, lifs, home, ports 
summary: Durante un reinicio, es posible que algunas LIF se hayan migrado a sus puertos de conmutación al respaldo asignados. Después de revertir un clúster, debe habilitar y revertir cualquier LIF que no esté en sus puertos iniciales. 
---
= Active y revierta las LIF a puertos domésticos después de una reversión de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durante un reinicio, es posible que algunas LIF se hayan migrado a sus puertos de conmutación al respaldo asignados. Después de revertir un clúster de ONTAP, debe habilitar y revertir cualquier LIF que no esté en sus puertos iniciales.

El comando network interface revert revierte una LIF que no está actualmente de su puerto de inicio a su puerto de inicio, siempre y cuando el puerto de inicio esté operativo. Cuando se crea la LIF, se especifica el puerto inicial de una LIF; puede determinar el puerto inicial de una LIF mediante el comando network interface show.

.Pasos
. Mostrar el estado de todas las LIF:
+
[source, cli]
----
network interface show
----
+
Este ejemplo muestra el estado de todas las LIF de una máquina virtual de almacenamiento (SVM).

+
[listing]
----
cluster1::> network interface show -vserver vs0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001    down/down  192.0.2.120/24     node0         e0e     true
            data002    down/down  192.0.2.121/24     node0         e0f     true
            data003    down/down  192.0.2.122/24     node0         e2a     true
            data004    down/down  192.0.2.123/24     node0         e2b     true
            data005    down/down  192.0.2.124/24     node0         e0e     false
            data006    down/down  192.0.2.125/24     node0         e0f     false
            data007    down/down  192.0.2.126/24     node0         e2a     false
            data008    down/down  192.0.2.127/24     node0         e2b     false
8 entries were displayed.
----
+
Si alguna LIF aparece con el estado Status Admin de down o with an is home status de false, continúe con el siguiente paso.

. Habilite las LIF de datos:
+
[source, cli]
----
network interface modify {-role data} -status-admin up
----
. Revertir los LIF a sus puertos raíz:
+
[source, cli]
----
network interface revert *
----
. Compruebe que todas las LIF se encuentran en sus puertos de inicio:
+
[source, cli]
----
network interface show
----
+
Este ejemplo muestra que todas las LIF para SVM vs0 están en sus puertos iniciales.

+
[listing]
----
cluster1::> network interface show -vserver vs0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001      up/up    192.0.2.120/24     node0         e0e     true
            data002      up/up    192.0.2.121/24     node0         e0f     true
            data003      up/up    192.0.2.122/24     node0         e2a     true
            data004      up/up    192.0.2.123/24     node0         e2b     true
            data005      up/up    192.0.2.124/24     node1         e0e     true
            data006      up/up    192.0.2.125/24     node1         e0f     true
            data007      up/up    192.0.2.126/24     node1         e2a     true
            data008      up/up    192.0.2.127/24     node1         e2b     true
8 entries were displayed.
----


.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["interfaz de red"^]

