---
permalink: smb-admin/add-home-directory-share-task.html 
sidebar: sidebar 
keywords: smb, home, directory, feature, add, property, share, properties, property, add a home directory share 
summary: Si desea utilizar la característica de directorio inicial SMB, debe agregar al menos un recurso compartido con la propiedad de directorio principal incluida en las propiedades de recurso compartido. 
---
= Agregar recursos compartidos del directorio de inicio SMB de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea utilizar la característica de directorio inicial SMB, debe agregar al menos un recurso compartido con la propiedad de directorio principal incluida en las propiedades de recurso compartido.

.Acerca de esta tarea
Puede crear un recurso compartido de directorio inicial en el momento de crear el recurso compartido mediante `vserver cifs share create` el comando, o bien puede cambiar un recurso compartido existente en un recurso compartido de directorio inicial en cualquier momento con `vserver cifs share modify` el comando.

Para crear un recurso compartido de directorio inicial, debe incluir `homedirectory` el valor en `-share-properties` la opción al crear o modificar un recurso compartido. Puede especificar el nombre de recurso compartido y la ruta de acceso compartida mediante variables que se amplían dinámicamente cuando los usuarios se conectan a sus directorios iniciales. Las variables disponibles que puede utilizar en la ruta de acceso son `%w`, `%d`, y `%u`, correspondientes al nombre de usuario de Windows, dominio y nombre de usuario UNIX asignado, respectivamente.

.Pasos
. Añadir un recurso compartido de directorio principal: +
`vserver cifs share create -vserver _vserver_name_ -share-name _share_name_ -path _path_ -share-properties homedirectory[,...]`
+
`-vserver` `vserver` Especifica la máquina virtual de almacenamiento (SVM) habilitada para CIFS en la que se añadirá la ruta de búsqueda.

+
`-share-name _share-name_` especifica el nombre del recurso compartido del directorio principal.

+
Además de contener una de las variables necesarias, si el nombre del recurso compartido contiene una de las cadenas literales `%w` , , `%u` o `%d`, debe preceder la cadena literal con un carácter % (porcentaje) para evitar que ONTAP trate la cadena literal como una variable (por ejemplo, `%%w`).

+
** El nombre del recurso compartido debe contener la `%w` `%u` variable o.
** El nombre del recurso compartido puede contener además la `%d` variable (por ejemplo, `%d`/`%w`) o una parte estática en el nombre del recurso compartido (por ejemplo, home1_/`%w`).
** Si los administradores utilizan el recurso compartido para conectarse a los directorios principales de otros usuarios o para permitir que los usuarios se conecten a los directorios principales de otros usuarios, el patrón de nombre de recurso compartido dinámico debe ir precedido de una tilde (~).
+
El `vserver cifs home-directory modify` se utiliza para activar este acceso estableciendo `-is-home-dirs-access-for-admin-enabled` la opción en `true`) o estableciendo la opción avanzada `-is-home-dirs-access-for-public-enabled` en `true`.



+
`-path` `path` especifica la ruta relativa al directorio raíz.



`-share-properties homedirectory[,...]` especifica las propiedades de recurso compartido para ese recurso compartido. Debe especificar `homedirectory` el valor. Puede especificar propiedades de recursos compartidos adicionales mediante una lista delimitada por comas.

. Compruebe que ha agregado correctamente el recurso compartido del directorio inicial mediante `vserver cifs share show` el comando.


.Ejemplo
El siguiente comando crea un recurso compartido de directorio raíz denominado `%w`. Las `oplocks` `browsable` `changenotify` propiedades , y share se establecen además de definir la `homedirectory` propiedad share.

[NOTE]
====
Este ejemplo no muestra el resultado de todos los recursos compartidos de la SVM. La salida está truncada.

====
[listing]
----
cluster1::> vserver cifs share create -vserver vs1 -share-name %w -path %w -share-properties oplocks,browsable,changenotify,homedirectory

vs1::> vserver cifs share show -vserver vs1
Vserver    Share    Path         Properties     Comment  ACL
---------- -------- ------------ -------------- -------- -----------
vs1        %w       %w           oplocks        -        Everyone / Full Control
                                 browsable
                                 changenotify
                                 homedirectory
----
.Información relacionada
* xref:add-home-directory-search-path-task.adoc[Agregar rutas de búsqueda del directorio de inicio]
* xref:requirements-automatic-node-referrals-concept.adoc[Requisitos y pautas para el uso de referencias automáticas de nodos en servidores]
* xref:manage-accessibility-users-home-directories-task.adoc[Administrar la accesibilidad a los directorios personales de los usuarios]

