---
permalink: smb-admin/add-home-directory-search-path-task.html 
sidebar: sidebar 
keywords: ontap, smb, directories, directory, add, path, add a home directory search path 
summary: Si desea utilizar directorios iniciales SMB de ONTAP, debe agregar al menos una ruta de búsqueda de directorio raíz. 
---
= Agregar rutas de búsqueda del directorio de inicio de ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea utilizar directorios iniciales SMB de ONTAP, debe agregar al menos una ruta de búsqueda de directorio raíz.

.Acerca de esta tarea
Puede agregar una ruta de búsqueda del directorio inicial utilizando `vserver cifs home-directory search-path add` el comando.

El `vserver cifs home-directory search-path add` comando comprueba la ruta especificada en la `-path` opción durante la ejecución del comando. Si la ruta especificada no existe, el comando genera un mensaje solicitando si desea continuar. Usted elige `y` o `n`. Si decide `y` continuar, ONTAP creará la ruta de búsqueda. Sin embargo, debe crear la estructura de directorios para poder utilizar la ruta de búsqueda en la configuración del directorio principal. Si elige no continuar, el comando falla; no se crea la ruta de búsqueda. A continuación, puede crear la estructura de directorios PATH y volver a ejecutar `vserver cifs home-directory search-path add` el comando.

.Pasos
. Agregar una ruta de búsqueda del directorio inicial: `vserver cifs home-directory search-path add -vserver vserver -path path`
. Compruebe que ha agregado correctamente la ruta de búsqueda mediante el `vserver cifs home-directory search-path show` comando.


.Ejemplo
En el siguiente ejemplo, se agrega la ruta `/home1` a la configuración del directorio inicial en la SVM VS1.

[listing]
----
cluster::> vserver cifs home-directory search-path add -vserver vs1 -path /home1

vs1::> vserver cifs home-directory search-path show
Vserver     Position Path
----------- -------- -----------------
vs1         1        /home1
----
En el siguiente ejemplo, se intenta añadir la ruta `/home2` a la configuración del directorio inicial en la SVM VS1. La ruta no existe. Se decide no continuar.

[listing]
----
cluster::> vserver cifs home-directory search-path add -vserver vs1 -path /home2
Warning: The specified path "/home2" does not exist in the namespace
         belonging to Vserver "vs1".
Do you want to continue? {y|n}: n
----
.Información relacionada
xref:add-home-directory-share-task.adoc[Agregar recursos compartidos del directorio de inicio]
