---
permalink: smb-admin/applying-group-policy-objects-concept.html 
sidebar: sidebar 
keywords: cifs, server, support, group, policy, object, gpo, set, rule, attribute, apply, computer, active, directory, environment, domain 
summary: 'El servidor SMB admite objetos de directiva de grupo (GPO), un conjunto de reglas conocidas como atributos de directiva de grupo que se aplican a equipos de un entorno de Active Directory. Puede utilizar los GPO para gestionar de forma centralizada la configuración de todas las máquinas virtuales de almacenamiento (SVM) del clúster que pertenece al mismo dominio de Active Directory.' 
---
= Aplicar objetos de directiva de grupo a la información general de los servidores SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El servidor SMB admite objetos de directiva de grupo (GPO), un conjunto de reglas conocidas como atributos de directiva de grupo_ que se aplican a equipos de un entorno de Active Directory. Puede utilizar los GPO para gestionar de forma centralizada la configuración de todas las máquinas virtuales de almacenamiento (SVM) del clúster que pertenece al mismo dominio de Active Directory.

Cuando se habilitan los GPO en el servidor SMB, ONTAP envía consultas LDAP al servidor de Active Directory que solicita información de GPO. Si hay definiciones de GPO aplicables al servidor SMB, el servidor Active Directory devuelve la siguiente información de GPO:

* Nombre de GPO
* Versión de GPO actual
* Ubicación de la definición de GPO
* Listas de UUID (identificadores universales únicos) para conjuntos de directivas de GPO


.Información relacionada
xref:secure-file-access-dynamic-access-control-concept.adoc[Protección del acceso a los archivos mediante el control de acceso dinámico (DAC)]

link:../nas-audit/index.html["Seguimiento de seguridad y auditoría de SMB y NFS"]
