---
permalink: smb-admin/authentication-access-security-concept.html 
sidebar: sidebar 
keywords: create, smb, connection, contain, svm, authenticate, domain, smb, server, support, authentication, method, ntlm, ntlmv1, ntlmv2, kerberos, default, method, user, ontap, how ontap handles smb client authentication 
summary: 'Antes de que los usuarios puedan crear conexiones SMB para acceder a los datos contenidos en la SVM, el dominio al que pertenece el servidor SMB debe autenticarse. El servidor SMB admite dos métodos de autenticación: Kerberos y NTLM (NTLMv1 o NTLMv2). Kerberos es el método predeterminado utilizado para autenticar usuarios de dominio.' 
---
= Obtenga más información sobre el manejo de la autenticación del cliente SMB de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de que los usuarios puedan crear conexiones SMB para acceder a los datos contenidos en la SVM, el dominio al que pertenece el servidor SMB debe autenticarse. El servidor SMB admite dos métodos de autenticación: Kerberos y NTLM (NTLMv1 o NTLMv2). Kerberos es el método predeterminado utilizado para autenticar usuarios de dominio.



== Autenticación Kerberos

ONTAP admite la autenticación Kerberos al crear sesiones SMB autenticadas.

Kerberos es el servicio de autenticación principal para Active Directory. El servidor Kerberos o el servicio de centro de distribución de claves Kerberos (KDC) almacena y recupera información acerca de los principios de seguridad en Active Directory. A diferencia del modelo NTLM, los clientes de Active Directory que deseen establecer una sesión con otro equipo, como el servidor SMB, póngase en contacto directamente con un KDC para obtener sus credenciales de sesión.



== Autenticación NTLM

La autenticación de clientes NTLM se realiza mediante un protocolo de respuesta a desafío basado en el conocimiento compartido de un secreto específico del usuario basado en una contraseña.

Si un usuario crea una conexión SMB con una cuenta de usuario local de Windows, el servidor SMB realiza la autenticación localmente con NTLMv2.
