---
permalink: smb-admin/branchcache-when-reverting-concept.html 
sidebar: sidebar 
keywords: revert, ontap, release, support, branchcache, what happens to branchcache when reverting 
summary: Es importante comprender lo que sucede al revertir ONTAP a una versión que no admite BranchCache. 
---
= Qué le sucede a BranchCache al revertir
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es importante comprender lo que sucede al revertir ONTAP a una versión que no admite BranchCache.

* Cuando revierte a una versión de ONTAP que no admite BranchCache, los recursos compartidos SMB no anuncian capacidades de BranchCache a los clientes habilitados para BranchCache; por lo tanto, los clientes no solicitan información hash.
+
En su lugar, solicitan el contenido real mediante las solicitudes de lectura SMB normales. En respuesta a la solicitud de contenido, el servidor SMB envía el contenido real almacenado en la máquina virtual de almacenamiento (SVM).

* Cuando un nodo que aloja un almacén hash se revierte a una versión que no admite BranchCache, el administrador de almacenamiento debe revertir manualmente la configuración de BranchCache mediante un comando que se imprime durante la reversión.
+
Este comando elimina la configuración y los hash de BranchCache.

+
Una vez finalizada la reversión, el administrador de almacenamiento puede eliminar manualmente el directorio que contenía el almacén hash, si lo desea.



.Información relacionada
xref:delete-branchcache-config-task.html[Eliminación de la configuración de BranchCache en las SVM]
