---
permalink: smb-admin/break-locks-task.html 
sidebar: sidebar 
keywords: file, lock, prevent, client, access, display, information, held, break, scenario, debug, application, break locks 
summary: Cuando los bloqueos de archivos impiden que los clientes accedan a los archivos, puede mostrar información sobre los bloqueos retenidos actualmente y romperán bloqueos específicos. Entre los ejemplos de escenarios en los que es posible que necesite romper los bloqueos se incluyen las aplicaciones de depuración. 
---
= Bloqueos de rotura
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando los bloqueos de archivos impiden que los clientes accedan a los archivos, puede mostrar información sobre los bloqueos retenidos actualmente y romperán bloqueos específicos. Entre los ejemplos de escenarios en los que es posible que necesite romper los bloqueos se incluyen las aplicaciones de depuración.

.Acerca de esta tarea
La `vserver locks break` el comando solo está disponible en el nivel de privilegios avanzado y superior. La página man del comando contiene información detallada.

.Pasos
. Para encontrar la información que necesita para romper un bloqueo, utilice `vserver locks show` comando.
+
La página man del comando contiene información detallada.

. Configure el nivel de privilegio en Advanced: `set -privilege advanced`
. Ejecute una de las siguientes acciones:
+
|===
| Si desea romper un bloqueo especificando... | Introduzca el comando... 


 a| 
El nombre de SVM, el nombre del volumen, el nombre de LIF y la ruta de archivo
 a| 
`vserver locks break -vserver vserver_name -volume volume_name -path path -lif lif`



 a| 
El ID del bloqueo
 a| 
`vserver locks break -lockid UUID`

|===
. Vuelva al nivel de privilegio de administrador: `set -privilege admin`

