---
permalink: smb-admin/builtin-groups-default-privileges-reference.html 
sidebar: sidebar 
keywords: assign, membership, local, user, domain, predefined, builtin, ontap, predefined builtin groups and default privileges 
summary: Puede asignar la pertenencia de un usuario local o un usuario de dominio a un conjunto predefinido de grupos BUILTIN proporcionados por ONTAP. Los grupos predefinidos tienen privilegios predefinidos asignados. 
---
= Grupos BUILTIN predefinidos y privilegios predeterminados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede asignar la pertenencia de un usuario local o un usuario de dominio a un conjunto predefinido de grupos BUILTIN proporcionados por ONTAP. Los grupos predefinidos tienen privilegios predefinidos asignados.

En la siguiente tabla se describen los grupos predefinidos:

|===
| Grupo BUILTIN predefinido | Privilegios predeterminados 


 a| 
``BUILTIN\Administrators``RID 544

Cuando se crea por primera vez, el local `Administrator` La cuenta, CON UN RID de 500, se hace automáticamente miembro de este grupo. Cuando la máquina virtual de almacenamiento (SVM) se une a un dominio, el `domain\Domain Admins` el grupo se agrega al grupo. Si la SVM sale del dominio, el `domain\Domain Admins` el grupo se elimina del grupo.
 a| 
* `SeBackupPrivilege`
* `SeRestorePrivilege`
* `SeSecurityPrivilege`
* `SeTakeOwnershipPrivilege`
* `SeChangeNotifyPrivilege`




 a| 
``BUILTIN\Power Users``RID 547

Cuando se crea por primera vez, este grupo no tiene miembros. Los miembros de este grupo tienen las siguientes características:

* Puede crear y administrar usuarios y grupos locales.
* No se pueden agregar a sí mismos ni a ningún otro objeto `BUILTIN\Administrators` grupo.

 a| 
`SeChangeNotifyPrivilege`



 a| 
``BUILTIN\Backup Operators``RID 551

Cuando se crea por primera vez, este grupo no tiene miembros. Los miembros de este grupo pueden anular los permisos de lectura y escritura en archivos o carpetas si se abren con la intención de copia de seguridad.
 a| 
* `SeBackupPrivilege`
* `SeRestorePrivilege`
* `SeChangeNotifyPrivilege`




 a| 
``BUILTIN\Users``RID 545

Cuando se crea por primera vez, este grupo no tiene ningún miembro (además del implícito `Authenticated Users` grupo especial). Cuando la SVM se une a un dominio, el `domain\Domain Users` el grupo se agrega a este grupo. Si la SVM sale del dominio, el `domain\Domain Users` el grupo se elimina de este grupo.
 a| 
`SeChangeNotifyPrivilege`



 a| 
``Everyone``SID S-1-1-0

Este grupo incluye a todos los usuarios, incluidos invitados (pero no usuarios anónimos). Este es un grupo implícito con una membresía implícita.
 a| 
`SeChangeNotifyPrivilege`

|===
.Información relacionada
xref:builtin-groups-local-administrator-account-concept.adoc[Directrices para el uso de grupos BUILTIN y la cuenta de administrador local]

xref:list-supported-privileges-reference.adoc[Lista de privilegios compatibles]

xref:configure-bypass-traverse-checking-concept.adoc[Configuración de la comprobación de recorrido de derivación]
