---
permalink: smb-admin/builtin-groups-local-administrator-account-concept.html 
sidebar: sidebar 
keywords: guideline, mind, builtin, group, local, administrator, account, delete, guidelines for using builtin groups and the local administrator account 
summary: Hay ciertas pautas que debe tener en cuenta cuando utilice los grupos BUILTIN y la cuenta de administrador local. Por ejemplo, puede cambiar el nombre de la cuenta de administrador local, pero no puede eliminar esta cuenta. 
---
= Obtenga información sobre los grupos BUILTIN y las cuentas de administrador local en los servidores SMB de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay ciertas pautas que debe tener en cuenta cuando utilice los grupos BUILTIN y la cuenta de administrador local. Por ejemplo, puede cambiar el nombre de la cuenta de administrador local, pero no puede eliminar esta cuenta.

* Se puede cambiar el nombre de la cuenta Administrador, pero no se puede eliminar.
* La cuenta de administrador no se puede quitar del grupo BUILTIN\Administrators.
* Se puede cambiar el nombre de los grupos INTEGRADOS, pero no se pueden eliminar.
+
Después de cambiar el nombre del grupo BUILTIN, se puede crear otro objeto local con el nombre bien conocido; sin embargo, al objeto se le asigna UN NUEVO RID.

* No hay una cuenta de invitado local.


.Información relacionada
xref:builtin-groups-default-privileges-reference.adoc[Grupos BUILTIN predefinidos y privilegios predeterminados]
