---
permalink: smb-admin/commands-manage-ntfs-smb.html 
sidebar: sidebar 
keywords: ontap, command, managing, manage, security, descriptor, create, modify, delete, display, information, commands for managing ntfs security descriptors 
summary: 'Usa comandos de ONTAP para crear, modificar, eliminar y mostrar información sobre descriptores de seguridad NTFS y entradas de control de acceso (ACE) en DACL y SACL. También puedes usar comandos de ONTAP para gestionar políticas de seguridad SMB, tareas de políticas y trabajos de políticas.' 
---
= Comandos de ONTAP para gestionar las políticas de seguridad NTFS y SMB y las entradas de control de acceso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Usa comandos de ONTAP para crear, modificar, eliminar y mostrar información sobre descriptores de seguridad NTFS y entradas de control de acceso (ACE) en DACL y SACL. También puedes usar comandos de ONTAP para gestionar políticas de seguridad SMB, tareas de políticas y trabajos de políticas.



[[ontap-commands-for-managing-ntfs-security-descriptors-on-smb-servers]]
== Comandos ONTAP para administrar descriptores de seguridad NTFS en servidores SMB

Existen comandos ONTAP específicos para administrar descriptores de seguridad. Puede crear, modificar, eliminar y mostrar información acerca de los descriptores de seguridad.

|===
| Si desea... | Se usa este comando... 


 a| 
Crear descriptores de seguridad NTFS
 a| 
`vserver security file-directory ntfs create`



 a| 
Modifique los descriptores de seguridad NTFS existentes
 a| 
`vserver security file-directory ntfs modify`



 a| 
Mostrar información acerca de los descriptores de seguridad NTFS existentes
 a| 
`vserver security file-directory ntfs show`



 a| 
Eliminar descriptores de seguridad NTFS
 a| 
`vserver security file-directory ntfs delete`

|===
Obtenga más información sobre `vserver security file-directory ntfs` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+ntfs["Referencia de comandos del ONTAP"^].



[[ontap-commands-for-managing-ntfs-dacl-access-control-entries-on-smb-servers]]
== Comandos ONTAP para administrar entradas de control de acceso DACL NTFS en servidores SMB

Hay comandos ONTAP específicos para administrar entradas de control de acceso DACL (ACE). Puede agregar ACE a DACL NTFS en cualquier momento. También puede administrar las DACL de NTFS existentes modificando, eliminando y mostrando información acerca de las ACE en las DACL.

|===
| Si desea... | Se usa este comando... 


 a| 
Cree ACE y agréguelos a DACL NTFS
 a| 
`vserver security file-directory ntfs dacl add`



 a| 
Modifique los ACE existentes en las DACL NTFS
 a| 
`vserver security file-directory ntfs dacl modify`



 a| 
Mostrar información acerca de los ACE existentes en las DACL NTFS
 a| 
`vserver security file-directory ntfs dacl show`



 a| 
Elimine los ACE existentes de las DACL NTFS
 a| 
`vserver security file-directory ntfs dacl remove`

|===
Obtenga más información sobre `vserver security file-directory ntfs dacl` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+ntfs+dacl["Referencia de comandos del ONTAP"^].



[[ontap-commands-for-managing-ntfs-sacl-access-control-entries-on-smb-servers]]
== Comandos ONTAP para administrar entradas de control de acceso SACL NTFS en servidores SMB

Hay comandos ONTAP específicos para administrar entradas de control de acceso SACL (ACE). Puede agregar ACE a SACL NTFS en cualquier momento. También puede administrar SACL NTFS existentes modificando, eliminando y mostrando información acerca de ACE en SACL.

|===
| Si desea... | Se usa este comando... 


 a| 
Cree ACE y agréguelos a SACL NTFS
 a| 
`vserver security file-directory ntfs sacl add`



 a| 
Modifique los ACE existentes en SACL NTFS
 a| 
`vserver security file-directory ntfs sacl modify`



 a| 
Muestra información acerca de los ACE existentes en SACL NTFS
 a| 
`vserver security file-directory ntfs sacl show`



 a| 
Elimine los ACE existentes de SACL NTFS
 a| 
`vserver security file-directory ntfs sacl remove`

|===
Obtenga más información sobre `vserver security file-directory ntfs sacl` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+ntfs+sacl["Referencia de comandos del ONTAP"^].



[[ontap-commands-for-managing-smb-security-policies]]
== Comandos de ONTAP para administrar políticas de seguridad SMB

Existen comandos ONTAP específicos para administrar las políticas de seguridad. Puede mostrar información acerca de las políticas y eliminarla. No puede modificar una política de seguridad.

|===
| Si desea... | Se usa este comando... 


 a| 
Cree políticas de seguridad
 a| 
`vserver security file-directory policy create`



 a| 
Mostrar información acerca de las directivas de seguridad
 a| 
`vserver security file-directory policy show`



 a| 
Eliminar políticas de seguridad
 a| 
`vserver security file-directory policy delete`

|===
Obtenga más información sobre `vserver security file-directory policy` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+policy["Referencia de comandos del ONTAP"^].



[[ontap-commands-for-managing-smb-security-policy-tasks]]
== Comandos ONTAP para administrar tareas de políticas de seguridad SMB

Hay comandos de ONTAP para añadir, modificar, quitar y mostrar información acerca de tareas de políticas de seguridad.

|===
| Si desea... | Se usa este comando... 


 a| 
Agregar tareas de directiva de seguridad
 a| 
`vserver security file-directory policy task add`



 a| 
Modifique las tareas de las políticas de seguridad
 a| 
`vserver security file-directory policy task modify`



 a| 
Muestra información acerca de las tareas de directiva de seguridad
 a| 
`vserver security file-directory policy task show`



 a| 
Quitar tareas de directiva de seguridad
 a| 
`vserver security file-directory policy task remove`

|===
Obtenga más información sobre `vserver security file-directory policy task` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+policy+task["Referencia de comandos del ONTAP"^].



[[ontap-commands-for-managing-smb-security-policy-jobs]]
== Comandos de ONTAP para administrar trabajos de políticas de seguridad de SMB

Hay comandos de la ONTAP para pausar, reanudar, detener y mostrar información acerca de los trabajos de políticas de seguridad.

|===
| Si desea... | Se usa este comando... 


 a| 
Pausar trabajos de directiva de seguridad
 a| 
`vserver security file-directory job pause ‑vserver vserver_name -id integer`



 a| 
Reanudar trabajos de directiva de seguridad
 a| 
`vserver security file-directory job resume ‑vserver vserver_name -id integer`



 a| 
Mostrar información sobre trabajos de directivas de seguridad
 a| 
`vserver security file-directory job show ‑vserver vserver_name` Puede determinar el ID de trabajo de un trabajo mediante este comando.



 a| 
Detener trabajos de directiva de seguridad
 a| 
`vserver security file-directory job stop ‑vserver vserver_name -id integer`

|===
Obtenga más información sobre `vserver security file-directory job` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+job["Referencia de comandos del ONTAP"^].
