---
permalink: smb-admin/commands-manage-ntfs-security-descriptors-reference.html 
sidebar: sidebar 
keywords: ontap, comand, managing, manage, security, descriptor, create, modify, delete, display, information, commands for managing ntfs security descriptors 
summary: Existen comandos ONTAP específicos para administrar descriptores de seguridad. Puede crear, modificar, eliminar y mostrar información acerca de los descriptores de seguridad. 
---
= Comandos ONTAP para administrar descriptores de seguridad NTFS en servidores SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existen comandos ONTAP específicos para administrar descriptores de seguridad. Puede crear, modificar, eliminar y mostrar información acerca de los descriptores de seguridad.

|===
| Si desea... | Se usa este comando... 


 a| 
Crear descriptores de seguridad NTFS
 a| 
`vserver security file-directory ntfs create`



 a| 
Modifique los descriptores de seguridad NTFS existentes
 a| 
`vserver security file-directory ntfs modify`



 a| 
Mostrar información acerca de los descriptores de seguridad NTFS existentes
 a| 
`vserver security file-directory ntfs show`



 a| 
Eliminar descriptores de seguridad NTFS
 a| 
`vserver security file-directory ntfs delete`

|===
Obtenga más información sobre `vserver security file-directory ntfs` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+ntfs["Referencia de comandos del ONTAP"^].
