---
permalink: smb-admin/commands-manage-shares-reference.html 
sidebar: sidebar 
keywords: vserver, cifs, properties, property, command, manage, smb, share, command for managing smb shares 
summary: Para gestionar los recursos compartidos de SMB se utilizan los comandos de propiedades compartidas de Vserver cifs y Vserver cifs sharp. 
---
= Comandos para gestionar recursos compartidos de SMB en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilice la `vserver cifs share` y.. `vserver cifs share properties` Comandos para gestionar los recursos compartidos de SMB.

|===
| Si desea... | Se usa este comando... 


 a| 
Cree un recurso compartido de SMB
 a| 
`vserver cifs share create`



 a| 
Mostrar los recursos compartidos de SMB
 a| 
`vserver cifs share show`



 a| 
Modificar un recurso compartido de SMB
 a| 
`vserver cifs share modify`



 a| 
Eliminar un recurso compartido de SMB
 a| 
`vserver cifs share delete`



 a| 
Agregar propiedades de recurso compartido a un recurso compartido existente
 a| 
`vserver cifs share properties add`



 a| 
Quitar propiedades de recurso compartido de un recurso compartido existente
 a| 
`vserver cifs share properties remove`



 a| 
Muestra información sobre las propiedades de uso compartido
 a| 
`vserver cifs share properties show`

|===
Obtenga más información sobre `vserver cifs` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs["Referencia de comandos de la ONTAP"^].
