---
permalink: smb-admin/commands-manage-security-policy-tasks-reference.html 
sidebar: sidebar 
keywords: ontap, command, add, modify, removing, remove, display, information, security, policy, task, commands for managing security policy tasks 
summary: Hay comandos de ONTAP para añadir, modificar, quitar y mostrar información acerca de tareas de políticas de seguridad. 
---
= Comandos para gestionar tareas de política de seguridad en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay comandos de ONTAP para añadir, modificar, quitar y mostrar información acerca de tareas de políticas de seguridad.

|===
| Si desea... | Se usa este comando... 


 a| 
Agregar tareas de directiva de seguridad
 a| 
`vserver security file-directory policy task add`



 a| 
Modifique las tareas de las políticas de seguridad
 a| 
`vserver security file-directory policy task modify`



 a| 
Muestra información acerca de las tareas de directiva de seguridad
 a| 
`vserver security file-directory policy task show`



 a| 
Quitar tareas de directiva de seguridad
 a| 
`vserver security file-directory policy task remove`

|===
Obtenga más información sobre `vserver security file-directory policy task` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+policy+task["Referencia de comandos de la ONTAP"^].
