---
permalink: smb-admin/commands-manage-character-mappings-file-name-reference.html 
sidebar: sidebar 
keywords: manage, character, mapping, creating, create, modify, information, deleting, delete, file, smb, translation, flexvol, volume, commands for managing character mappings for smb file name translation 
summary: Puede gestionar la asignación de caracteres creando, modificando, mostrando información o eliminando asignaciones de caracteres de archivo utilizadas para la traducción del nombre del archivo SMB en volúmenes FlexVol. 
---
= Comandos para gestionar asignaciones de caracteres para la traducción de nombres de archivo SMB en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede gestionar la asignación de caracteres creando, modificando, mostrando información o eliminando asignaciones de caracteres de archivo utilizadas para la traducción del nombre del archivo SMB en volúmenes FlexVol.

|===
| Si desea... | Se usa este comando... 


 a| 
Cree nuevas asignaciones de caracteres de archivo
 a| 
`vserver cifs character-mapping create`



 a| 
Mostrar información acerca de las asignaciones de caracteres de archivo
 a| 
`vserver cifs character-mapping show`



 a| 
Modifique las asignaciones de caracteres de archivo existentes
 a| 
`vserver cifs character-mapping modify`



 a| 
Eliminar asignaciones de caracteres de archivo
 a| 
`vserver cifs character-mapping delete`

|===
Obtenga más información sobre `vserver cifs character-mapping` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs+character-mapping["Referencia de comandos del ONTAP"^].

.Información relacionada
xref:configure-character-mappings-file-name-translation-task.adoc[Configuración de la asignación de caracteres para la traducción de nombres de archivo SMB en volúmenes]
