---
permalink: smb-admin/commands-manage-name-mappings-reference.html 
sidebar: sidebar 
keywords: ontap, command, managing, manage, name, mapping 
summary: Hay comandos de la ONTAP específicos para gestionar las asignaciones de nombres. 
---
= Comandos para gestionar las asignaciones de nombres
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay comandos de la ONTAP específicos para gestionar las asignaciones de nombres.

|===
| Si desea... | Se usa este comando... 


 a| 
Cree una asignación de nombres
 a| 
`vserver name-mapping create`



 a| 
Inserte una asignación de nombres en una posición específica
 a| 
`vserver name-mapping insert`



 a| 
Mostrar asignaciones de nombres
 a| 
`vserver name-mapping show`



 a| 
Cambie la posición de dos asignaciones de nombre

[NOTE]
====
No se permite un intercambio cuando se configura la asignación de nombres con una entrada de calificador ip.

==== a| 
`vserver name-mapping swap`



 a| 
Modificar una asignación de nombres
 a| 
`vserver name-mapping modify`



 a| 
Eliminar una asignación de nombres
 a| 
`vserver name-mapping delete`



 a| 
Validar la asignación de nombre correcta
 a| 
`vserver security file-directory show-effective-permissions -vserver vs1 -win-user-name user1 -path / -share-name sh1`

|===
Consulte la página de manual de cada comando para obtener más información.
