---
permalink: smb-admin/commands-manage-search-paths-reference.html 
sidebar: sidebar 
keywords: ontap, command, managing, manage, path, cifs, directory, configuration, add, remove, removing, display, information, search, path, changing, change, search, path, order, commands for managing search paths 
summary: Hay comandos ONTAP específicos para gestionar las rutas de búsqueda de las configuraciones de directorios iniciales de SMB. Por ejemplo, hay comandos para agregar, quitar y mostrar información acerca de las rutas de búsqueda. También hay un comando para cambiar el orden de la ruta de búsqueda. 
---
= Comandos para gestionar las rutas de búsqueda en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay comandos ONTAP específicos para gestionar las rutas de búsqueda de las configuraciones de directorios iniciales de SMB. Por ejemplo, hay comandos para agregar, quitar y mostrar información acerca de las rutas de búsqueda. También hay un comando para cambiar el orden de la ruta de búsqueda.

|===
| Si desea... | Se usa este comando... 


 a| 
Agregue una ruta de búsqueda
 a| 
`vserver cifs home-directory search-path add`



 a| 
Mostrar rutas de búsqueda
 a| 
`vserver cifs home-directory search-path show`



 a| 
Cambie el orden de la ruta de búsqueda
 a| 
`vserver cifs home-directory search-path reorder`



 a| 
Quitar una ruta de búsqueda
 a| 
`vserver cifs home-directory search-path remove`

|===
Obtenga más información sobre `vserver cifs home-directory search-path` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs+home-directory+search-path["Referencia de comandos del ONTAP"^].
