---
permalink: smb-admin/configure-security-styles-qtrees-task.html 
sidebar: sidebar 
keywords: configure, qtree, volume, security, style, permission, data, configure security styles on qtrees 
summary: El estilo de seguridad del volumen de qtrees se configura para determinar el tipo de permisos utilizados para los datos en qtrees. 
---
= Configure los estilos de seguridad de SMB en qtrees de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El estilo de seguridad del volumen de qtrees se configura para determinar el tipo de permisos utilizados para los datos en qtrees.

.Pasos
. Ejecute una de las siguientes acciones:
+
|===
| Si el qtree... | Usar el comando... 


 a| 
Aún no existe
 a| 
`volume qtree create` e incluya la `-security-style` parámetro para especificar el estilo de seguridad.



 a| 
Ya existe
 a| 
`volume qtree modify` e incluya la `-security-style` parámetro para especificar el estilo de seguridad.

|===
+
Las posibles opciones para el estilo de seguridad para qtrees son `unix`, `ntfs`, o. `mixed`.

+
Si no se especifica un estilo de seguridad al crear un qtree, el estilo de seguridad predeterminado es `mixed`.

+
Para obtener más información acerca de `volume qtree create` o. `volume qtree modify` comandos, consulte link:../volumes/index.html["Gestión de almacenamiento lógico"].

. Para ver la configuración, incluido el estilo de seguridad del qtree que ha creado, escriba el siguiente comando: `volume qtree show -qtree qtree_name -instance`

