---
permalink: smb-admin/configure-grant-unix-group-permission-users-task.html 
sidebar: sidebar 
keywords: configure, grant, group, permission, access, file, directories, directory, incoming, cifs, ownder, configure the grant unix group permission to smb users 
summary: Puede configurar esta opción para conceder permisos de grupo para tener acceso a archivos o directorios aunque el usuario SMB entrante no sea el propietario del archivo. 
---
= Configure el permiso para otorgar grupos UNIX a los usuarios SMB de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar esta opción para conceder permisos de grupo para tener acceso a archivos o directorios aunque el usuario SMB entrante no sea el propietario del archivo.

.Pasos
. Configure el nivel de privilegio en Advanced: `set -privilege advanced`
. Configure el permiso conceder grupo UNIX según corresponda:
+
|===
| Si desea | Introduzca el comando 


 a| 
Active el acceso a los archivos o directorios para obtener permisos de grupo incluso si el usuario no es el propietario del archivo
 a| 
`vserver cifs options modify –grant-unix-group-perms-to-others true`



 a| 
Desactive el acceso a los archivos o directorios para obtener permisos de grupo incluso si el usuario no es el propietario del archivo
 a| 
`vserver cifs options modify –grant-unix-group-perms-to-others false`

|===
. Compruebe que la opción está establecida en el valor deseado: `vserver cifs options show –fields grant-unix-group-perms-to-others`
. Vuelva al nivel de privilegio de administrador: `set -privilege admin`

