---
permalink: smb-admin/configure-folder-redirection-task.html 
sidebar: sidebar 
keywords: configure, folder, redirection, windows, properties, method, assistance, svm, administrator, configure folder redirection 
summary: Puede configurar la redirección de carpetas mediante la ventana Propiedades de Windows. La ventaja de utilizar este método es que el usuario de Windows puede configurar la redirección de carpetas sin la ayuda del administrador de SVM. 
---
= Configurar la redirección de carpetas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar la redirección de carpetas mediante la ventana Propiedades de Windows. La ventaja de utilizar este método es que el usuario de Windows puede configurar la redirección de carpetas sin la ayuda del administrador de SVM.

.Pasos
. En el Explorador de Windows, haga clic con el botón secundario en la carpeta que desea redirigir a un recurso compartido de red.
. Haga clic en *Propiedades*.
+
Se mostrarán las propiedades del recurso compartido seleccionado.

. En la ficha *acceso directo*, haga clic en *destino* y especifique la ruta de acceso a la ubicación de red en la que desea redirigir la carpeta seleccionada.
+
Por ejemplo, si desea redirigir una carpeta al `data` carpeta de un directorio principal al que está asignado `Q:\`, especifique `Q:\data` como destino.

. Haga clic en *Aceptar*.
+
Para obtener más información acerca de la configuración de carpetas sin conexión, consulte la Biblioteca de Microsoft TechNet.



.Información relacionada
http://technet.microsoft.com/en-us/library/["Biblioteca de Microsoft TechNet: technet.microsoft.com/en-us/library/"]
