---
permalink: smb-admin/configure-branchcache-enabled-shares-concept.html 
sidebar: sidebar 
keywords: configure, branchcache, smb server, office, enable, smb, share, content, client, configure branchache-enabled smb shares 
summary: Una vez que configura BranchCache en el servidor SMB y en la sucursal, puede habilitar BranchCache en recursos compartidos SMB que contienen contenido que desea permitir que los clientes de las sucursales se almacenan en caché. 
---
= Configure la información general de recursos compartidos SMB habilitados para BranchCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una vez que configura BranchCache en el servidor SMB y en la sucursal, puede habilitar BranchCache en recursos compartidos SMB que contienen contenido que desea permitir que los clientes de las sucursales se almacenan en caché.

El almacenamiento en caché de BranchCache puede habilitarse en todos los recursos compartidos de SMB en el servidor SMB o de recurso compartido por recurso.

* Si habilita BranchCache por recurso compartido, puede habilitar BranchCache a medida que crea el recurso compartido o modifica los recursos compartidos existentes.
+
Si habilita el almacenamiento en caché en un recurso compartido de SMB existente, ONTAP comienza a enviar hashes de computación y metadatos a clientes que soliciten contenido tan pronto como habilite BranchCache en ese recurso compartido.

* Todos los clientes que tengan una conexión SMB existente a un recurso compartido no obtienen compatibilidad con BranchCache si, a continuación, se habilita BranchCache en ese recurso compartido.
+
ONTAP anuncia el soporte de BranchCache para un recurso compartido en el momento de la configuración de la sesión del bloque de mensajes del servidor. Los clientes que ya han establecido sesiones cuando se habilita BranchCache deben desconectar y volver a conectarse para usar el contenido en caché para este recurso compartido.



[NOTE]
====
Si BranchCache en un recurso compartido de SMB se encuentra deshabilitado posteriormente, ONTAP deja de enviar metadatos al cliente solicitante. Un cliente que necesita datos lo recupera directamente del servidor de contenido (servidor SMB).

====