---
permalink: smb-admin/configure-security-styles-task.html 
sidebar: sidebar 
keywords: configure, flexvol, volume, security, style, type, permission, data, storage, virtual, machine, svm, configure security styles on flexvol volumes 
summary: 'El estilo de seguridad del volumen FlexVol se configura para determinar el tipo de permisos utilizados para los datos en volúmenes FlexVol de la máquina virtual de almacenamiento (SVM).' 
---
= Configure los estilos de seguridad de SMB en volúmenes de ONTAP FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El estilo de seguridad del volumen FlexVol se configura para determinar el tipo de permisos utilizados para los datos en volúmenes FlexVol de la máquina virtual de almacenamiento (SVM).

.Pasos
. Ejecute una de las siguientes acciones:
+
|===


| Si el volumen de FlexVol... | Usar el comando... 


 a| 
Aún no existe
 a| 
`volume create` e incluya el `-security-style` parámetro para especificar el estilo de seguridad.



 a| 
Ya existe
 a| 
`volume modify` e incluya el `-security-style` parámetro para especificar el estilo de seguridad.

|===
+
Las opciones posibles para el estilo de seguridad de FlexVol volume son `unix` `ntfs` , o `mixed`.

+
Si no se especifica un estilo de seguridad al crear un volumen FlexVol, el volumen hereda el estilo de seguridad del volumen raíz.

+
Para obtener más información acerca de los `volume create` `volume modify` comandos o, consulte link:../volumes/index.html["Gestión de almacenamiento lógico"].

. Para ver la configuración, incluido el estilo de seguridad del volumen FlexVol que se creó, escriba el siguiente comando:
+
`volume show -volume volume_name -instance`


