---
permalink: smb-admin/control-domain-controller-discovery-task.html 
sidebar: sidebar 
keywords: ontap, modify, default, process, domain, controller, dc, enable, limit, site, pool, performance, improvement, environment, manage, manage domain controller discovery 
summary: 'A partir de ONTAP 9.3, puede modificar el proceso predeterminado por el que se detectan los controladores de dominio (DC). Esto le permite limitar la detección a sus instalaciones o a un conjunto de centros de datos preferidos, lo que puede mejorar el rendimiento en función del entorno.' 
---
= Administrar la detección del controlador de dominio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.3, puede modificar el proceso predeterminado por el que se detectan los controladores de dominio (DC). Esto le permite limitar la detección a sus instalaciones o a un conjunto de centros de datos preferidos, lo que puede mejorar el rendimiento en función del entorno.

.Acerca de esta tarea
De forma predeterminada, el proceso de detección dinámica detecta todos los centros de datos disponibles, incluidos los centros de datos preferidos, todos los centros de datos del sitio local y todos los centros de datos remotos. Esta configuración puede provocar latencia en autenticación y acceder a recursos compartidos en determinados entornos. Si ya ha determinado el grupo de DC que desea utilizar o si los DC remotos son inadecuados o inaccesibles, puede cambiar el método de descubrimiento.

En ONTAP 9.3 y versiones posteriores, el `discovery-mode` parámetro de `cifs domain discovered-servers` comando permite seleccionar una de las siguientes opciones de detección:

* Se descubren todos los DC del dominio.
* Sólo se descubren los centros de datos del sitio local.
+
La `default-site` El parámetro del servidor SMB se puede definir para utilizar este modo con LIF que no están asignadas a un sitio en sites-and-services.

* No se realiza la detección del servidor, la configuración del servidor SMB depende únicamente de los centros de datos preferidos.
+
Para utilizar este modo, primero debe definir los DC preferidos para el servidor SMB.



.Paso
. Especifique la opción de detección deseada: `vserver cifs domain discovered-servers discovery-mode modify -vserver _vserver_name_ -mode {all|site|none}`
+
Opciones para `mode` parámetro:

+
** `all`
+
Descubrir todos los DC disponibles (predeterminado).

** `site`
+
Limite el descubrimiento de DC a su sitio.

** `none`
+
Utilice sólo los centros de datos preferidos y no realice la detección.




