---
permalink: smb-admin/create-security-policies-audit-task.html 
sidebar: sidebar 
keywords: creating, create, audit, policy, storage, virtual, machine, svm, configuring, configure, apply, acl, file, folder, act, container, task, entry, applied, apply, security, create security policies 
summary: 'Crear una política de auditoría para máquinas virtuales de almacenamiento (SVM) es el tercer paso a la hora de configurar y aplicar ACL a un archivo o una carpeta. Una directiva actúa como contenedor para varias tareas, donde cada tarea es una entrada única que se puede aplicar a archivos o carpetas. Posteriormente, puede agregar tareas a la directiva de seguridad.' 
---
= Cree políticas de seguridad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Crear una política de auditoría para máquinas virtuales de almacenamiento (SVM) es el tercer paso a la hora de configurar y aplicar ACL a un archivo o una carpeta. Una directiva actúa como contenedor para varias tareas, donde cada tarea es una entrada única que se puede aplicar a archivos o carpetas. Posteriormente, puede agregar tareas a la directiva de seguridad.

.Acerca de esta tarea
Las tareas que agrega a una directiva de seguridad contienen asociaciones entre el descriptor de seguridad NTFS y las rutas de acceso de archivos o carpetas. Por lo tanto, debe asociar la política de seguridad con cada máquina virtual de almacenamiento (SVM) (que contenga volúmenes de estilo de seguridad NTFS o volúmenes mixtos de estilo de seguridad).

.Pasos
. Cree una política de seguridad: `vserver security file-directory policy create -vserver vserver_name -policy-name policy_name`
+
`vserver security file-directory policy create -policy-name policy1 -vserver vs1`

. Compruebe la directiva de seguridad: `vserver security file-directory policy show`
+
[listing]
----

            vserver security file-directory policy show
               Vserver          Policy Name
             ------------     --------------
                 vs1              policy1
----

