---
permalink: smb-admin/create-snapshot-config-previous-versions-access-task.html 
sidebar: sidebar 
keywords: previous, version, functionality, available, client, access, snapshot, copies, copy, enable, snapshot, exist, configuration, requirement, create a snapshot configuration to enable previous versions access 
summary: La funcionalidad de versiones anteriores está siempre disponible, siempre y cuando exista acceso de los clientes a las copias Snapshot. Si la configuración de su copia Snapshot no cumple estos requisitos, puede crear una configuración de copia Snapshot que sí lo haga. 
---
= Cree una configuración de Snapshot para habilitar el acceso a versiones anteriores en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La funcionalidad de versiones anteriores está siempre disponible, siempre y cuando exista acceso de los clientes a las copias Snapshot. Si la configuración de su copia Snapshot no cumple estos requisitos, puede crear una configuración de copia Snapshot que sí lo haga.

.Pasos
. Si el volumen que contiene el recurso compartido al que desea permitir el acceso a versiones anteriores no tiene una política de Snapshot asociada, asocie una política de Snapshot al volumen y habilite esa política mediante el uso de `volume modify` comando.
+
Obtenga más información sobre `volume modify` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-modify.html["Referencia de comandos de la ONTAP"^].

. Habilite el acceso a las copias de Snapshot mediante el `volume modify` para establecer el `-snap-dir` opción a. `true`.
+
Obtenga más información sobre `volume modify` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-modify.html["Referencia de comandos de la ONTAP"^].

. Compruebe que se han habilitado las políticas de Snapshot y que el acceso a los directorios de Snapshot se habilita mediante el `volume show` y.. `volume snapshot policy show` comandos.
+
Obtenga más información sobre `volume show` y `volume snapshot policy show` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+show["Referencia de comandos de la ONTAP"^].

+
Para obtener más información sobre la configuración y gestión de políticas de Snapshot y programaciones de Snapshot, consulte link:../data-protection/index.html["Protección de datos"].



.Información relacionada
link:../data-protection/index.html["Protección de datos"]
