---
permalink: smb-admin/create-symbolic-link-mappings-task.html 
sidebar: sidebar 
keywords: create, mapping, unix, symbolic, link, smb, share, relative, symbol, refer, file, folder, relative, parent, absolute, create symbolic link mappings for smb shares 
summary: Puede crear asignaciones de enlaces simbólicos UNIX para los recursos compartidos de SMB. Puede crear un vínculo simbólico relativo, que hace referencia al archivo o la carpeta relativa a su carpeta principal, o bien puede crear un vínculo simbólico absoluto, que hace referencia al archivo o la carpeta utilizando una ruta absoluta. 
---
= Crear asignaciones de enlace simbólico para los recursos compartidos de SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear asignaciones de enlaces simbólicos UNIX para los recursos compartidos de SMB. Puede crear un vínculo simbólico relativo, que hace referencia al archivo o la carpeta relativa a su carpeta principal, o bien puede crear un vínculo simbólico absoluto, que hace referencia al archivo o la carpeta utilizando una ruta absoluta.

.Acerca de esta tarea
Los usuarios de Mac OS X no pueden acceder a Widelinks si utilizan SMB 2.x. Cuando un usuario intenta conectarse a un recurso compartido mediante widelinks desde un cliente Mac OS X, el intento falla. Sin embargo, puede utilizar widelinks con clientes Mac OS X si utiliza SMB 1.

.Pasos
. Para crear asignaciones de enlaces simbólicos para recursos compartidos de SMB: `vserver cifs symlink create -vserver virtual_server_name -unix-path path -share-name share_name -cifs-path path [-cifs-server server_name] [-locality {local|free|widelink}] [-home-directory {true|false}]`
+
`-vserver` `virtual_server_name` Especifica el nombre de la máquina virtual de almacenamiento (SVM).

+
`-unix-path` `path` Especifica la ruta UNIX. La ruta UNIX debe empezar por una barra diagonal (`/`) y debe terminar con una barra diagonal (`/`).

+
`-share-name` `share_name` Especifica el nombre del recurso compartido de SMB que se va a asignar.

+
`-cifs-path` `path` Especifica la ruta CIFS. La ruta CIFS debe comenzar con una barra diagonal (`/`) y debe terminar con una barra diagonal (`/`).

+
`-cifs-server` `server_name` Especifica el nombre del servidor CIFS. El nombre del servidor CIFS puede especificarse como un nombre DNS (por ejemplo, mynetwork.cifs.server.com), una dirección IP o un nombre NetBIOS. El nombre de NetBIOS se puede determinar mediante el `vserver cifs show` comando. Si no se especifica este parámetro opcional, el valor predeterminado es el nombre NetBIOS del servidor CIFS local.

+
`-locality`  `local`|`free`|`widelink`} especifica si se debe crear un enlace local, un enlace libre o un enlace simbólico amplio. Un enlace simbólico local se asigna al recurso compartido local de SMB. Un enlace simbólico gratuito puede asignar en cualquier parte del servidor SMB local. Un amplio enlace simbólico se asigna a cualquier recurso compartido de SMB en la red. Si no se especifica este parámetro opcional, el valor por defecto es `local`.

+
`-home-directory`  `true` `false`} especifica si el recurso compartido de destino es un directorio raíz. Aunque este parámetro sea opcional, debe definir este parámetro en `true` cuando el recurso compartido de destino esté configurado como directorio raíz. El valor predeterminado es `false`.



.Ejemplo
El siguiente comando crea una asignación de enlaces simbólicos en la SVM llamada vs1. Tiene la ruta UNIX `/src/` , el nombre compartido SMB '`SOURCE`', la ruta CIFS `/mycompany/source/` y la dirección IP del servidor CIFS 123.123.123.123, y es un enlace inalámbrico.

[listing]
----
cluster1::> vserver cifs symlink create -vserver vs1 -unix-path /src/ -share-name SOURCE -cifs-path "/mycompany/source/" -cifs-server 123.123.123.123 -locality widelink
----
.Información relacionada
xref:configure-unix-symbolic-link-support-shares-task.adoc[Configurar la compatibilidad de enlaces simbólicos UNIX en recursos compartidos de SMB]
