---
permalink: smb-admin/create-branchcache-enabled-share-task.html 
sidebar: sidebar 
keywords: enable, branchcache, smb, create, share, setting, property, create a bracnhcache-enabled smb share 
summary: Puede habilitar BranchCache en un recurso compartido de SMB cuando se crea el recurso compartido mediante la configuración de la propiedad compartido de branchcache. 
---
= Cree un recurso compartido de SMB habilitado para BranchCache en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar BranchCache en un recurso compartido de SMB cuando se crea el recurso compartido mediante la configuración `branchcache` de la propiedad de recurso compartido.

.Acerca de esta tarea
* Si se habilita BranchCache en el recurso compartido de SMB, el recurso compartido debe tener la configuración de los archivos sin conexión establecida en el almacenamiento manual en caché.
+
Esta es la configuración predeterminada cuando se crea un recurso compartido.

* También puede especificar parámetros de recurso compartido opcionales al crear el recurso compartido con BranchCache habilitado.
* Es posible establecer `branchcache` la propiedad en un recurso compartido aunque BranchCache no esté configurado y habilitado en la máquina virtual de almacenamiento (SVM).
+
Sin embargo, si desea que el recurso compartido ofrezca contenido en caché, debe configurar y habilitar BranchCache en la SVM.

* Dado que no hay propiedades de recurso compartido predeterminadas aplicadas al recurso compartido al utilizar el `-share-properties` parámetro, debe especificar todas las demás propiedades de recurso compartido que desee aplicar al recurso compartido además de la `branchcache` propiedad de recurso compartido mediante una lista delimitada por comas.
* Obtenga más información sobre `vserver cifs share create` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-create.html["Referencia de comandos del ONTAP"^].


.Paso
. Cree un recurso compartido de SMB habilitado para BranchCache: +
`vserver cifs share create -vserver _vserver_name_ -share-name _share_name_ -path _path_ -share-properties branchcache[,...]`
. Compruebe que la propiedad BranchCache Share esté configurada en el recurso compartido de SMB mediante `vserver cifs share show` el comando.


.Ejemplo
El siguiente comando crea un recurso compartido SMB habilitado para BranchCache llamado «data» con una ruta de acceso `/data` de en SVM VS1. De forma predeterminada, la configuración de archivos fuera de línea se establece en `manual`:

[listing]
----
cluster1::> vserver cifs share create -vserver vs1 -share-name data -path /data -share-properties branchcache,oplocks,browsable,changenotify

cluster1::> vserver cifs share show -vserver vs1 -share-name data
                      Vserver: vs1
                        Share: data
     CIFS Server NetBIOS Name: VS1
                         Path: /data
             Share Properties: branchcache
                               oplocks
                               browsable
                               changenotify
           Symlink Properties: enable
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: -
                  Volume Name: data
                Offline Files: manual
Vscan File-Operations Profile: standard
----
.Información relacionada
xref:disable-branchcache-single-share-task.adoc[Deshabilitar BranchCache en un único recurso compartido de SMB]
