---
permalink: smb-admin/create-home-directory-config-w-d-variables-task.html 
sidebar: sidebar 
keywords: 'create, home, directory, configuration, variable, user, connect, share, dynamic, create, share, %w, %d, create a home directory configuration using the %w and %d variables' 
summary: 'Puede crear una configuración de directorio principal utilizando las variables %w y %d. Los usuarios pueden conectarse a su propio recurso compartido mediante recursos compartidos creados dinámicamente.' 
---
= Cree configuraciones de directorio de inicio SMB de ONTAP utilizando las variables %w y %d
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear una configuración del directorio inicial mediante `%w` `%d` las variables y. Los usuarios pueden conectarse a su propio recurso compartido mediante recursos compartidos creados dinámicamente.

.Pasos
. Cree un qtree que contenga los directorios iniciales de usuario: `volume qtree create -vserver vserver_name -qtree-path qtree_path`
. Compruebe que el qtree esté utilizando el estilo de seguridad correcto: `volume qtree show`
. Si el qtree no está usando el estilo de seguridad deseado, cambie el estilo de seguridad con el `volume qtree security` comando.
. Añadir un recurso compartido de directorio inicial: `+vserver cifs share create -vserver vserver -share-name %w -path %d/%w -share-properties homedirectory\[,...\]+`
+
`-vserver` `vserver` Especifica la máquina virtual de almacenamiento (SVM) habilitada para CIFS en la que se añadirá la ruta de búsqueda.

+
`-share-name` `%w` especifica el nombre del recurso compartido del directorio principal. ONTAP crea dinámicamente el nombre del recurso compartido a medida que cada usuario se conecta a su directorio inicial. El nombre del recurso compartido tendrá el formato _Windows_USER_NAME_.

+
`-path` `%d/%w` especifica la ruta relativa al directorio raíz. La ruta relativa se crea dinámicamente a medida que cada usuario se conecta a su directorio principal y tendrá el formato _domain/Windows_user_name_.

+
`-share-properties homedirectory[,...]+` especifica las propiedades de recurso compartido para ese recurso compartido. Debe especificar `homedirectory` el valor. Puede especificar propiedades de recursos compartidos adicionales mediante una lista delimitada por comas.

. Compruebe que el recurso compartido tiene la configuración deseada con `vserver cifs share show` el comando.
. Agregar una ruta de búsqueda del directorio inicial: `vserver cifs home-directory search-path add -vserver vserver -path path`
+
`-vserver _vserver-name_` Especifica la SVM habilitada para CIFS en la que se añadirá la ruta de búsqueda.

+
`-path _path_` especifica la ruta de acceso absoluta del directorio a la ruta de búsqueda.

. Compruebe que ha agregado correctamente la ruta de búsqueda mediante el `vserver cifs home-directory search-path show` comando.
. Para los usuarios que dispongan de un directorio inicial, cree un directorio correspondiente en el qtree o en el volumen designado para que contengan directorios iniciales.
+
Por ejemplo, si creó un qtree con la ruta de `/vol/vol1/users` y el nombre de usuario cuyo directorio desea crear es mydomain\user1, debe crear un directorio con la ruta de acceso siguiente `/vol/vol1/users/mydomain/user1`: .

+
Si creaste un volumen llamado “home1” montado en `/home1`, crearías un directorio con la siguiente ruta: `/home1/mydomain/user1`.

. Compruebe que un usuario puede conectarse correctamente al recurso compartido principal mediante la asignación de una unidad o la conexión mediante la ruta UNC.
+
Por ejemplo, si el usuario mydomain\user1 desea conectarse al directorio creado en el Paso 8 que se encuentra en la SVM VS1, user1 se conectaría mediante la ruta UNC `\\vs1\user1` .



.Ejemplo
Los comandos del siguiente ejemplo crean una configuración de directorio inicial con los siguientes ajustes:

* El nombre del recurso compartido es %w.
* La ruta de acceso relativa al directorio principal es %d/%w.
* La ruta de búsqueda que se utiliza para contener los directorios raíz `/home1` , es un volumen configurado con estilo de seguridad NTFS.
* La configuración se crea en SVM vs1.


Puede utilizar este tipo de configuración de directorio inicial cuando los usuarios acceden a sus directorios iniciales desde hosts de Windows. También puede utilizar este tipo de configuración cuando los usuarios acceden a sus directorios iniciales desde hosts Windows y UNIX y el administrador del sistema de archivos utiliza usuarios y grupos basados en Windows para controlar el acceso al sistema de archivos.

[listing]
----
cluster::> vserver cifs share create -vserver vs1 -share-name %w -path %d/%w -share-properties oplocks,browsable,changenotify,homedirectory

cluster::> vserver cifs share show -vserver vs1 -share-name %w

                      Vserver: vs1
                        Share: %w
     CIFS Server NetBIOS Name: VS1
                         Path: %d/%w
             Share Properties: oplocks
                               browsable
                               changenotify
                               homedirectory
           Symlink Properties: enable
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: -
                  Volume Name: -
                Offline Files: manual
Vscan File-Operations Profile: standard

cluster::> vserver cifs home-directory search-path add -vserver vs1 ‑path /home1

cluster::> vserver cifs home-directory search-path show
Vserver     Position Path
----------- -------- -----------------
vs1         1        /home1
----
.Información relacionada
* xref:configure-home-directories-u-variable-task.adoc[Configure directorios iniciales utilizando la variable %u]
* xref:home-directory-config-concept.adoc[Obtenga más información sobre configuraciones adicionales del directorio de inicio]
* xref:display-user-home-directory-path-task.adoc[Mostrar información sobre las rutas del directorio de inicio del usuario]

