---
permalink: smb-admin/deploy-offline-files-concept.html 
sidebar: sidebar 
keywords: important, guideline, understand, deploy, offline, file, home, directory, share, showsnapshot, property, set, home, directories, directory, guidelines for deploying offline files 
summary: Hay algunas directrices importantes que debe entender al implementar archivos sin conexión en recursos compartidos de directorios iniciales que tienen la propiedad showsnapshot share establecida en directorios iniciales. 
---
= Directrices para implementar archivos sin conexión
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay algunas directrices importantes que debe entender al implementar archivos sin conexión en los recursos compartidos de directorios iniciales que tienen `showsnapshot` propiedad share establecida en directorios iniciales.

Si la `showsnapshot` La propiedad Share se establece en un recurso compartido de directorio principal que tiene configurados archivos sin conexión, los clientes de Windows almacenan en caché todas las copias Snapshot en la `~snapshot` en el directorio principal del usuario.

Los clientes de Windows almacenan en caché todas las copias Snapshot en el directorio inicial si se cumple alguna de las siguientes condiciones:

* El usuario hace que el directorio inicial esté disponible sin conexión desde el cliente.
+
El contenido del `~snapshot` la carpeta del directorio principal se incluye y se hace disponible sin conexión.

* El usuario configura la redirección de carpetas para redirigir una carpeta como, por ejemplo `My Documents` En la raíz de un directorio inicial que reside en el recurso compartido de servidor CIFS.
+
Es posible que algunos clientes de Windows hagan que la carpeta redirigida esté disponible sin conexión automáticamente. Si la carpeta se redirige a la raíz del directorio principal, el `~snapshot` la carpeta se incluye en el contenido sin conexión almacenado en caché.



[NOTE]
====
Los archivos sin conexión se despliegues donde `~snapshot` la carpeta se incluye en los archivos sin conexión se debe evitar. Las copias Snapshot en la `~snapshot` La carpeta contiene todos los datos del volumen en el punto en que ONTAP creó la copia Snapshot. Por tanto, cree una copia sin conexión de `~snapshot` la carpeta consume una cantidad significativa de almacenamiento local en el cliente, consume ancho de banda de red durante la sincronización de archivos sin conexión y aumenta el tiempo necesario para sincronizar archivos sin conexión.

====