---
permalink: smb-admin/determine-clients-connected-encrypted-task.html 
sidebar: sidebar 
keywords: display, information, connect, smb, session, determine, client, encrypt, smb, connection, helpful, determining, session, desire, security, setting, determine whether client are connected using encrypted smb sessions 
summary: Puede mostrar información sobre las sesiones SMB conectadas para determinar si los clientes están utilizando conexiones SMB cifradas. Esto puede resultar útil para determinar si las sesiones de cliente SMB se conectan con la configuración de seguridad deseada. 
---
= Determine si los clientes están conectados mediante sesiones SMB cifradas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede mostrar información sobre las sesiones SMB conectadas para determinar si los clientes están utilizando conexiones SMB cifradas. Esto puede resultar útil para determinar si las sesiones de cliente SMB se conectan con la configuración de seguridad deseada.

.Acerca de esta tarea
Las sesiones de clientes de SMB pueden tener uno de tres niveles de cifrado:

* `unencrypted`
+
La sesión SMB no está cifrada. No se configura ni el cifrado a nivel de equipo virtual de almacenamiento (SVM) ni el nivel de recurso compartido.

* `partially-encrypted`
+
El cifrado se inicia cuando se produce la conexión de árbol. Se configuró el cifrado a nivel de recurso compartido. El cifrado a nivel de SVM no está habilitado.

* `encrypted`
+
La sesión SMB está totalmente cifrada. El cifrado de la SVM está habilitado. Es posible que el cifrado de nivel de recurso compartido esté habilitado o no. La configuración de cifrado a nivel de SVM sustituye la configuración de cifrado a nivel de recurso compartido.



.Pasos
. Ejecute una de las siguientes acciones:
+
|===
| Si desea mostrar información acerca de... | Introduzca el comando... 


 a| 
Sesiones con una configuración de cifrado especificada para sesiones en una SVM especificada
 a| 
`vserver cifs session show -vserver _vserver_name_ {unencrypted|partially-encrypted|encrypted} -instance`



 a| 
La configuración de cifrado para un ID de sesión específico en una SVM especificada
 a| 
`vserver cifs session show -vserver _vserver_name_ -session-id _integer_ -instance`

|===


.Ejemplos
El siguiente comando muestra información detallada de la sesión, incluida la configuración de cifrado, en una sesión SMB con un ID de sesión de 2:

[listing]
----
cluster1::> vserver cifs session show -vserver vs1 -session-id 2 -instance
                        Node: node1
                     Vserver: vs1
                  Session ID: 2
               Connection ID: 3151274158
Incoming Data LIF IP Address: 10.2.1.1
                 Workstation: 10.1.1.2
    Authentication Mechanism: Kerberos
                Windows User: DOMAIN\joe
                   UNIX User: pcuser
                 Open Shares: 1
                  Open Files: 1
                  Open Other: 0
              Connected Time: 10m 43s
                   Idle Time: 1m 19s
            Protocol Version: SMB3
      Continuously Available: No
           Is Session Signed: true
       User Authenticated as: domain-user
                NetBIOS Name: CIFS_ALIAS1
       SMB Encryption Status: Unencrypted
----