---
permalink: smb-admin/determine-snapshot-copies-available-task.html 
sidebar: sidebar 
keywords: view, snapshot, copies, copy, previous, version, enable, policy, applied, apply, contain, share, previous, version, access, determine whether snapshot copies are available for previous versions use 
summary: Las snapshots se pueden ver en la pestaña Versiones anteriores solo si se aplica una política de Snapshot habilitada al volumen que contiene el recurso compartido y si la configuración del volumen permite el acceso a las instantáneas. Determinar la disponibilidad de instantáneas es útil cuando se ayuda a un usuario con acceso a versiones anteriores. 
---
= Determinar si las instantáneas SMB de ONTAP están disponibles para el uso de versiones anteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las snapshots se pueden ver en la pestaña Versiones anteriores solo si se aplica una política de Snapshot habilitada al volumen que contiene el recurso compartido y si la configuración del volumen permite el acceso a las instantáneas. Determinar la disponibilidad de instantáneas es útil cuando se ayuda a un usuario con acceso a versiones anteriores.

.Pasos
. Determine si el volumen en el que residen los datos compartidos tiene snapshots automáticas habilitadas y si los clientes tienen acceso a los directorios de snapshots: `volume show -vserver vserver-name -volume volume-name -fields vserver,volume,snapdir-access,snapshot-policy,snapshot-count`
+
La salida muestra qué política de instantáneas está asociada con el volumen, si el acceso al directorio de instantáneas del cliente está habilitado y el número de instantáneas disponibles.

. Determinar si la política de snapshots asociada está habilitada: `volume snapshot policy show -policy policy-name`
. Enumere las instantáneas disponibles: `volume snapshot show -volume volume_name`
+
Para obtener más información sobre la configuración y gestión de políticas de snapshot y programaciones de snapshot, consulte link:../data-protection/index.html["Protección de datos"].



.Ejemplo
El siguiente ejemplo muestra información sobre las políticas de instantáneas asociadas con el volumen denominado «ata1» que contiene los datos compartidos y las instantáneas disponibles en «ata1».

[listing]
----
cluster1::> volume show -vserver vs1 -volume data1 -fields vserver,volume,snapshot-policy,snapdir-access,snapshot-count
vserver  volume snapdir-access snapshot-policy snapshot-count
-------- ------ -------------- --------------- --------------
vs1      data1  true           default         10

cluster1::> volume snapshot policy show -policy default
Vserver: cluster1
                   Number of Is
Policy Name        Schedules Enabled Comment
------------------ --------- ------- ----------------------------------
default                    3 true    Default policy with hourly, daily & weekly schedules.
    Schedule         Count     Prefix                 SnapMirror Label
    ---------------- -----     ---------------------- -------------------
    hourly               6     hourly                 -
    daily                2     daily                  daily
    weekly               2     weekly                 weekly

cluster1::> volume snapshot show -volume data1
                                                             ---Blocks---
Vserver  Volume  Snapshot                  State        Size Total% Used%
-------- ------- ------------------------- -------- -------- ------ -----
vs1      data1
                 weekly.2012-12-16_0015    valid       408KB     0%    1%
                 daily.2012-12-22_0010     valid       420KB     0%    1%
                 daily.2012-12-23_0010     valid       192KB     0%    0%
                 weekly.2012-12-23_0015    valid       360KB     0%    1%
                 hourly.2012-12-23_1405    valid       196KB     0%    0%
                 hourly.2012-12-23_1505    valid       196KB     0%    0%
                 hourly.2012-12-23_1605    valid       212KB     0%    0%
                 hourly.2012-12-23_1705    valid       136KB     0%    0%
                 hourly.2012-12-23_1805    valid       200KB     0%    0%
                 hourly.2012-12-23_1905    valid       184KB     0%    0%
----
.Información relacionada
* xref:create-snapshot-config-previous-versions-access-task.adoc[Crear configuraciones de instantáneas para habilitar el acceso a versiones anteriores]
* link:../data-protection/index.html["Protección de datos"]

