---
permalink: smb-admin/display-file-security-unix-style-volumes-task.html 
sidebar: sidebar 
keywords: display, information, file, directory, security, unix, security-style, volume, style, effective, permission, applied, apply, owner, group, result, validate, configuration, troubleshoot, access, issues, display information about file security on unix security-style volumes 
summary: Puede mostrar información acerca de la seguridad de archivos y directorios en los volúmenes de estilo de seguridad de UNIX, incluidos los estilos de seguridad y los estilos de seguridad efectivos, los permisos que se aplican y la información acerca de los propietarios y grupos de UNIX. Puede utilizar los resultados para validar la configuración de seguridad o solucionar problemas de acceso a archivos. 
---
= Muestra información sobre la seguridad de archivos en volúmenes de estilo de seguridad UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede mostrar información acerca de la seguridad de archivos y directorios en los volúmenes de estilo de seguridad de UNIX, incluidos los estilos de seguridad y los estilos de seguridad efectivos, los permisos que se aplican y la información acerca de los propietarios y grupos de UNIX. Puede utilizar los resultados para validar la configuración de seguridad o solucionar problemas de acceso a archivos.

.Acerca de esta tarea
Debe proporcionar el nombre de la máquina virtual de almacenamiento (SVM) y la ruta a los datos cuyo archivo o información de seguridad de directorio desee mostrar. Puede mostrar el resultado en forma de resumen o como una lista detallada.

* Los volúmenes y qtrees de estilo de seguridad de UNIX solo utilizan permisos de archivos UNIX, ya sea bits de modo o ACL de NFSv4 al determinar los derechos de acceso a los archivos.
* La salida de ACL se muestra solo para los archivos y las carpetas con seguridad de NFSv4.
+
Este campo está vacío para archivos y directorios que utilizan la seguridad de UNIX que solo tienen aplicados permisos de bit de modo (sin ACL de NFSv4).

* Los campos de salida de propietario y grupo de la salida de ACL no se aplican en el caso de los descriptores de seguridad de NFSv4.
+
Sólo son significativos para los descriptores de seguridad NTFS.

* Como la seguridad de Access Guard de nivel de almacenamiento es compatible en un volumen o qtree UNIX si se configura un servidor CIFS en la SVM, la salida puede contener información acerca de la seguridad Storage-Level Access Guard aplicada al volumen o al qtree especificado en el `-path` parámetro.


.Paso
. Mostrar la configuración de seguridad de archivos y directorios con el nivel de detalle deseado:
+
|===
| Si desea mostrar información... | Introduzca el siguiente comando... 


 a| 
En forma de resumen
 a| 
`vserver security file-directory show -vserver _vserver_name_ -path _path_`



 a| 
Con detalle ampliado
 a| 
`vserver security file-directory show -vserver _vserver_name_ -path _path_ -expand-mask true`

|===


.Ejemplos
En el ejemplo siguiente se muestra la información de seguridad acerca de la ruta `/home` En SVM vs1:

[listing]
----
cluster1::> vserver security file-directory show -vserver vs1 -path /home

                                  Vserver: vs1
                                File Path: /home
                        File Inode Number: 9590
                           Security Style: unix
                          Effective Style: unix
                           DOS Attributes: 10
                   DOS Attributes in Text: ----D---
                  Expanded Dos Attributes: -
                             Unix User Id: 0
                            Unix Group Id: 1
                           Unix Mode Bits: 700
                   Unix Mode Bits in Text: rwx------
                                     ACLs: -
----
En el ejemplo siguiente se muestra la información de seguridad acerca de la ruta `/home` En SVM vs1 con una máscara expandida:

[listing]
----
cluster1::> vserver security file-directory show -vserver vs1 -path /home -expand-mask true

                                 Vserver: vs1
                               File Path: /home
                       File Inode Number: 9590
                          Security Style: unix
                         Effective Style: unix
                          DOS Attributes: 10
                  DOS Attributes in Text: ----D---
                 Expanded Dos Attributes: 0x10
                      ...0 .... .... .... = Offline
                      .... ..0. .... .... = Sparse
                      .... .... 0... .... = Normal
                      .... .... ..0. .... = Archive
                      .... .... ...1 .... = Directory
                      .... .... .... .0.. = System
                      .... .... .... ..0. = Hidden
                      .... .... .... ...0 = Read Only
                            Unix User Id: 0
                           Unix Group Id: 1
                          Unix Mode Bits: 700
                  Unix Mode Bits in Text: rwx------
                                    ACLs: -
----
.Información relacionada
xref:display-file-security-ntfs-style-volumes-task.adoc[Mostrar información acerca de la seguridad de archivos en volúmenes de estilo de seguridad NTFS]

xref:display-file-security-mixed-style-volumes-task.adoc[Mostrar información sobre la seguridad de archivos en volúmenes mixtos de estilo de seguridad]
