---
permalink: smb-admin/display-statistics-task.html 
sidebar: sidebar 
keywords: display, various, statistic, cifs, smb, audit, branchcache, has, monitor, performance, diagnose, issue 
summary: Puede mostrar varias estadísticas, incluidas estadísticas sobre CIFS y SMB, auditoría y hash de BranchCache, para supervisar el rendimiento y diagnosticar problemas. 
---
= Mostrar estadísticas de ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede mostrar varias estadísticas, incluidas estadísticas sobre CIFS y SMB, auditoría y hash de BranchCache, para supervisar el rendimiento y diagnosticar problemas.

.Antes de empezar
Debe haber recogido muestras de datos mediante los `statistics start` `statistics stop` comandos y antes de poder mostrar información sobre los objetos.

.Pasos
. Establezca el nivel de privilegio en avanzado: `set -privilege advanced`
. Ejecute una de las siguientes acciones:
+
|===
| Si desea mostrar estadísticas de... | Introduzca... 


 a| 
Todas las versiones de SMB
 a| 
`statistics show -object cifs`



 a| 
SMB 1,0
 a| 
`statistics show -object smb1`



 a| 
SMB 2.x y SMB 3.0
 a| 
`statistics show -object smb2`



 a| 
Subsistema CIFS del nodo
 a| 
`statistics show -object nblade_cifs`



 a| 
Auditoría multiprotocolo
 a| 
`statistics show -object audit_ng`



 a| 
Servicio hash de BranchCache
 a| 
`statistics show -object hashd`



 a| 
DNS dinámico
 a| 
`statistics show -object ddns_update`

|===
+
Obtenga más información sobre `statistics show` en el link:https://docs.netapp.com/us-en/ontap-cli/statistics-show.html["Referencia de comandos del ONTAP"^].

. Vuelva al nivel de privilegio de administrador: `set -privilege admin`


.Información relacionada
* xref:determine-statistics-objects-counters-available-task.adoc[Determinar qué estadísticas, objetos y contadores están disponibles en los servidores]
* xref:monitor-signed-session-statistics-task.adoc[Supervisar estadísticas de sesión firmada por SMB]
* xref:display-branchcache-statistics-task.adoc[Muestra las estadísticas de BranchCache]
* xref:statistics-monitor-automatic-node-referral-task.adoc[Utilice estadísticas para supervisar la actividad de referencia automática de nodos]
* link:../smb-hyper-v-sql/index.html["Configuración de SMB para Microsoft Hyper-V y SQL Server"]
* link:../performance-config/index.html["Configuración de supervisión del rendimiento"]

