---
permalink: smb-admin/display-types-users-connected-task.html 
sidebar: sidebar 
keywords: display, information, type, connect, smb, session, appropriate, type, storage, virtual, machine, svm 
summary: 'Puede ver información acerca del tipo de usuarios que están conectados en sesiones SMB. Esto puede ayudarle a asegurarse de que solo el tipo adecuado de usuario se conecte a través de sesiones SMB en la máquina virtual de almacenamiento (SVM).' 
---
= Muestra información sobre los tipos de usuarios que están conectados a través de sesiones SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ver información acerca del tipo de usuarios que están conectados en sesiones SMB. Esto puede ayudarle a asegurarse de que solo el tipo adecuado de usuario se conecte a través de sesiones SMB en la máquina virtual de almacenamiento (SVM).

.Acerca de esta tarea
Los siguientes tipos de usuarios pueden conectarse a través de sesiones SMB:

* `local-user`
+
Se autentica como usuario CIFS local

* `domain-user`
+
Autenticado como usuario de dominio (ya sea desde el dominio principal del servidor CIFS o desde un dominio de confianza)

* `guest-user`
+
Autenticado como usuario invitado

* `anonymous-user`
+
Autenticado como usuario anónimo o nulo



.Pasos
. Determinar qué tipo de usuario está conectado en una sesión SMB: `vserver cifs session show -vserver _vserver_name_ -windows-user _windows_user_name_ -fields windows-user,address,lif-address,user-type`
+
|===
| Si desea mostrar información sobre tipos de usuario para las sesiones establecidas... | Introduzca el siguiente comando... 


 a| 
Para todas las sesiones con un tipo de usuario especificado
 a| 
`vserver cifs session show -vserver _vserver_name_ -user-type {local-user|domain-user|guest-user|anonymous-user}`



 a| 
Para un usuario específico
 a| 
`vserver cifs session show -vserver _vserver_name_ -windows-user _windows_user_name_ -fields windows-user,address,lif-address,user-type`

|===


.Ejemplos
El siguiente comando muestra información de sesión sobre el tipo de usuario para las sesiones en SVM vs1 establecidas por el usuario "' iepubs\user1'":

[listing]
----
cluster1::> vserver cifs session show -vserver pub1 -windows-user iepubs\user1 -fields windows-user,address,lif-address,user-type
node      vserver session-id connection-id lif-address  address       windows-user         user-type
--------- ------- ---------- ------------- ------------ ------------- -------------------- -----------
pub1node1 pub1    1          3439441860    10.0.0.1     10.1.1.1      IEPUBS\user1         domain-user
----