---
permalink: smb-admin/display-discovered-trusted-domains-task.html 
sidebar: sidebar 
keywords: display, information, discover, trust, domain, cifs, server, home, contain, computer, trusted-domain, list, display information about discover trusted domains 
summary: Puede mostrar información acerca de los dominios de confianza detectados para el dominio principal del servidor CIFS, que es el dominio que contiene la cuenta de equipo del servidor CIFS. Esto puede ser útil si desea saber qué dominios de confianza se descubren y cómo se ordenan dentro de la lista de dominios de confianza detectados. 
---
= Mostrar información sobre los dominios SMB de ONTAP de confianza detectados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede mostrar información acerca de los dominios de confianza detectados para el dominio principal del servidor CIFS, que es el dominio que contiene la cuenta de equipo del servidor CIFS. Esto puede ser útil si desea saber qué dominios de confianza se descubren y cómo se ordenan dentro de la lista de dominios de confianza detectados.

.Acerca de esta tarea
Sólo se descubren los dominios con confianzas bidireccionales con el dominio principal. Dado que el controlador de dominio (DC) del dominio principal devuelve la lista de dominios de confianza en un orden determinado por el DC, no se puede predecir el orden de los dominios de la lista. Al mostrar la lista de dominios de confianza, puede determinar el orden de búsqueda para las búsquedas de asignación de nombres multidominio.

La información que se muestra sobre el dominio de confianza se agrupa por nodos y máquina virtual de almacenamiento (SVM).

.Paso
. Muestra información sobre los dominios de confianza detectados mediante `vserver cifs domain trusts show` el comando.
+
`vserver cifs domain trusts show -vserver vs1`

+
[listing]
----
   Node: node1
Vserver: vs1

Home Domain            Trusted Domain
---------------------  -----------------------------------
EXAMPLE.COM            CIFS1.EXAMPLE.COM,
                       CIFS2.EXAMPLE.COM
                       EXAMPLE.COM

   Node: node2
Vserver: vs1

Home Domain            Trusted Domain
---------------------  -----------------------------------
EXAMPLE.COM            CIFS1.EXAMPLE.COM,
                       CIFS2.EXAMPLE.COM
                       EXAMPLE.COM
----


.Información relacionada
xref:reset-rediscover-trusted-domains-task.adoc[Restablecer y volver a detectar dominios de confianza]
