---
permalink: smb-admin/display-privilege-overrides-task.html 
sidebar: sidebar 
keywords: display, information, custom, privilege, assign, domain, local, user, account, group, desire, right, applied, apply, display information about privilege overrides 
summary: Puede mostrar información acerca de los privilegios personalizados asignados a cuentas o grupos de usuarios locales o de dominio. Esta información le ayuda a determinar si se aplican los derechos de usuario deseados. 
---
= Muestra información acerca de anulaciones de privilegios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede mostrar información acerca de los privilegios personalizados asignados a cuentas o grupos de usuarios locales o de dominio. Esta información le ayuda a determinar si se aplican los derechos de usuario deseados.

.Paso
. Ejecute una de las siguientes acciones:
+
|===
| Si desea mostrar información acerca de... | Introduzca este comando... 


 a| 
Privilegios personalizados para todos los grupos y usuarios locales y de dominio en la máquina virtual de almacenamiento (SVM)
 a| 
`vserver cifs users-and-groups privilege show -vserver _vserver_name_`



 a| 
Privilegios personalizados para un dominio o un grupo y usuario local específicos de la SVM
 a| 
`vserver cifs users-and-groups privilege show -vserver _vserver_name_ -user-or-group-name _name_`

|===
+
Hay otros parámetros opcionales que puede elegir cuando ejecuta este comando. Consulte la página del manual para obtener más información.



.Ejemplo
El siguiente comando muestra todos los privilegios asociados explícitamente con los usuarios y grupos locales o de dominio para SVM vs1:

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver    User or Group Name     Privileges
--------- ---------------------   ---------------
vs1       BUILTIN\Administrators  SeTakeOwnershipPrivilege
                                  SeRestorePrivilege
vs1       CIFS_SERVER\sue         SeTcbPrivilege
                                  SeTakeOwnershipPrivilege
----