---
permalink: smb-admin/display-dynamic-access-control-security-task.html 
sidebar: sidebar 
keywords: display, information, dynamic, access, control, dac, security, ntfs, volume, data, effective, security, mix, security-stle, volume, conditional, ace, resource, central, access, policy, display information about dynamic access control security 
summary: 'Puede mostrar información acerca de la seguridad DAC (Dynamic Access Control) en volúmenes NTFS y en datos con seguridad efectiva NTFS en volúmenes mixtos de estilo de seguridad. Esto incluye información sobre ACE condicionales, ACE de recursos y ACE de políticas de acceso central. Puede utilizar los resultados para validar la configuración de seguridad o solucionar problemas de acceso a archivos.' 
---
= Mostrar información sobre la seguridad de DAC para servidores SMB de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede mostrar información acerca de la seguridad DAC (Dynamic Access Control) en volúmenes NTFS y en datos con seguridad efectiva NTFS en volúmenes mixtos de estilo de seguridad. Esto incluye información sobre ACE condicionales, ACE de recursos y ACE de políticas de acceso central. Puede utilizar los resultados para validar la configuración de seguridad o solucionar problemas de acceso a archivos.

.Acerca de esta tarea
Debe proporcionar el nombre de la máquina virtual de almacenamiento (SVM) y la ruta a los datos cuya información de seguridad de archivo o carpeta desee mostrar. Puede mostrar el resultado en forma de resumen o como una lista detallada.

.Paso
. Mostrar la configuración de seguridad de archivos y directorios con el nivel de detalle deseado:
+
|===
| Si desea mostrar información... | Introduzca el siguiente comando... 


 a| 
En forma de resumen
 a| 
`vserver security file-directory show -vserver vserver_name -path path`



 a| 
Con detalle ampliado
 a| 
`vserver security file-directory show -vserver vserver_name -path path -expand-mask true`



 a| 
Donde se muestra la salida con los SID de grupo y usuario
 a| 
`vserver security file-directory show -vserver vserver_name -path path -lookup-names false`



 a| 
Acerca de la seguridad de archivos y directorios para archivos y directorios en los que la máscara de bits hexadecimal se traduce al formato de texto
 a| 
`vserver security file-directory show -vserver vserver_name -path path -textual-mask true`

|===


.Ejemplos
En el siguiente ejemplo, se muestra información de seguridad de Control de acceso dinámico sobre la ruta de `/vol1` SVM VS1:

[listing]
----
cluster1::> vserver security file-directory show -vserver vs1 -path /vol1
                           Vserver: vs1
                         File Path: /vol1
                 File Inode Number: 112
                    Security Style: mixed
                   Effective Style: ntfs
                    DOS Attributes: 10
            DOS Attributes in Text: ----D---
            Expanded Dos Attribute: -
                      Unix User Id: 0
                     Unix Group Id: 1
                    Unix Mode Bits: 777
            Unix Mode Bits in Text: rwxrwxrwx
                              ACLs: NTFS Security Descriptor
                                    Control:0xbf14
                                    Owner:CIFS1\Administrator
                                    Group:CIFS1\Domain Admins
                                    SACL - ACEs
                                       ALL-Everyone-0xf01ff-OI|CI|SA|FA
                                       RESOURCE ATTRIBUTE-Everyone-0x0
                                         ("Department_MS",TS,0x10020,"Finance")
                                       POLICY ID-All resources - No Write-0x0-OI|CI
                                    DACL - ACEs
                                       ALLOW-CIFS1\Administrator-0x1f01ff-OI|CI
                                       ALLOW-Everyone-0x1f01ff-OI|CI
                                       ALLOW CALLBACK-DAC\user1-0x1200a9-OI|CI
                                         ((@User.department==@Resource.Department_MS&&@Resource.Impact_MS>1000)&&@Device.department==@Resource.Department_MS)
----
.Información relacionada
* xref:display-gpo-config-task.adoc[Mostrar información acerca de las configuraciones de GPO]
* xref:display-central-access-policies-task.adoc[Muestra información sobre las políticas de acceso central]
* xref:display-central-access-policy-rules-task.adoc[Muestra información acerca de las reglas de la política de acceso central]

