---
permalink: smb-admin/display-file-security-ntfs-style-volumes-task.html 
sidebar: sidebar 
keywords: display, information, file, directory, security, ntfs, security-style, volume, style, effective, permission, applied, apply, information, dos, attribute, result, validate, security, configuration, troubleshoot, issues, display information about file security on ntfs security-style volumes 
summary: Puede mostrar información acerca de la seguridad de archivos y directorios en volúmenes de estilo de seguridad NTFS, incluidos el estilo de seguridad y los estilos de seguridad efectivos, los permisos que se aplican e información acerca de los atributos dos. Puede utilizar los resultados para validar la configuración de seguridad o solucionar problemas de acceso a archivos. 
---
= Mostrar información sobre la seguridad de archivos SMB de ONTAP en volúmenes de estilo de seguridad NTFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede mostrar información acerca de la seguridad de archivos y directorios en volúmenes de estilo de seguridad NTFS, incluidos el estilo de seguridad y los estilos de seguridad efectivos, los permisos que se aplican e información acerca de los atributos dos. Puede utilizar los resultados para validar la configuración de seguridad o solucionar problemas de acceso a archivos.

.Acerca de esta tarea
Debe proporcionar el nombre de la máquina virtual de almacenamiento (SVM) y la ruta a los datos cuya información de seguridad de archivo o carpeta desee mostrar. Puede mostrar el resultado en forma de resumen o como una lista detallada.

* Debido a que los volúmenes y qtrees de estilo de seguridad NTFS utilizan sólo permisos de archivo NTFS y usuarios y grupos de Windows al determinar los derechos de acceso a archivos, los campos de salida relacionados con UNIX contienen información de permisos de archivo UNIX de sólo visualización.
* Se muestra la salida de ACL para archivos y carpetas con seguridad NTFS.
* Como la seguridad de Access Guard a nivel de almacenamiento se puede configurar en el volumen raíz o en el qtree, la salida de un volumen o una ruta de qtree en la que se configure la protección de acceso a nivel de almacenamiento puede mostrar tanto ACL de archivos normales como ACL de Storage-Level Access Guard.
* El resultado también muestra información acerca de los ACE de control de acceso dinámico si el Control de acceso dinámico está configurado para la ruta de acceso de archivo o directorio indicada.


.Paso
. Mostrar la configuración de seguridad de archivos y directorios con el nivel de detalle deseado:
+
|===
| Si desea mostrar información... | Introduzca el siguiente comando... 


 a| 
En forma de resumen
 a| 
`vserver security file-directory show -vserver _vserver_name_ -path _path_`



 a| 
Con detalle ampliado
 a| 
`vserver security file-directory show -vserver _vserver_name_ -path _path_ -expand-mask true`

|===


.Ejemplos
En el ejemplo siguiente se muestra información de seguridad sobre la ruta de `/vol4` SVM VS1:

[listing]
----
cluster::> vserver security file-directory show -vserver vs1 -path /vol4

                                 Vserver: vs1
                               File Path: /vol4
                       File Inode Number: 64
                          Security Style: ntfs
                         Effective Style: ntfs
                          DOS Attributes: 10
                  DOS Attributes in Text: ----D---
                 Expanded Dos Attributes: -
                            Unix User Id: 0
                           Unix Group Id: 0
                          Unix Mode Bits: 777
                  Unix Mode Bits in Text: rwxrwxrwx
                                    ACLs: NTFS Security Descriptor
                                          Control:0x8004
                                          Owner:BUILTIN\Administrators
                                          Group:BUILTIN\Administrators
                                          DACL - ACEs
                                          ALLOW-Everyone-0x1f01ff
                                          ALLOW-Everyone-0x10000000-OI|CI|IO
----
En el siguiente ejemplo, se muestra la información de seguridad con máscaras expandidas sobre la ruta de `/data/engineering` SVM VS1:

[listing]
----
cluster::> vserver security file-directory show -vserver vs1 -path -path /data/engineering -expand-mask true

                Vserver: vs1
              File Path: /data/engineering
      File Inode Number: 5544
         Security Style: ntfs
        Effective Style: ntfs
         DOS Attributes: 10
 DOS Attributes in Text: ----D---
Expanded Dos Attributes: 0x10
     ...0 .... .... .... = Offline
     .... ..0. .... .... = Sparse
     .... .... 0... .... = Normal
     .... .... ..0. .... = Archive
     .... .... ...1 .... = Directory
     .... .... .... .0.. = System
     .... .... .... ..0. = Hidden
     .... .... .... ...0 = Read Only
           Unix User Id: 0
          Unix Group Id: 0
         Unix Mode Bits: 777
 Unix Mode Bits in Text: rwxrwxrwx
                   ACLs: NTFS Security Descriptor
                         Control:0x8004

                             1... .... .... .... = Self Relative
                             .0.. .... .... .... = RM Control Valid
                             ..0. .... .... .... = SACL Protected
                             ...0 .... .... .... = DACL Protected
                             .... 0... .... .... = SACL Inherited
                             .... .0.. .... .... = DACL Inherited
                             .... ..0. .... .... = SACL Inherit Required
                             .... ...0 .... .... = DACL Inherit Required
                             .... .... ..0. .... = SACL Defaulted
                             .... .... ...0 .... = SACL Present
                             .... .... .... 0... = DACL Defaulted
                             .... .... .... .1.. = DACL Present
                             .... .... .... ..0. = Group Defaulted
                             .... .... .... ...0 = Owner Defaulted

                         Owner:BUILTIN\Administrators
                         Group:BUILTIN\Administrators
                         DACL - ACEs
                           ALLOW-Everyone-0x1f01ff
                             0... .... .... .... .... .... .... .... = Generic Read
                             .0.. .... .... .... .... .... .... .... = Generic Write
                             ..0. .... .... .... .... .... .... .... = Generic Execute
                             ...0 .... .... .... .... .... .... .... = Generic All
                             .... ...0 .... .... .... .... .... .... = System Security
                             .... .... ...1 .... .... .... .... .... = Synchronize
                             .... .... .... 1... .... .... .... .... = Write Owner
                             .... .... .... .1.. .... .... .... .... = Write DAC
                             .... .... .... ..1. .... .... .... .... = Read Control
                             .... .... .... ...1 .... .... .... .... = Delete
                             .... .... .... .... .... ...1 .... .... = Write Attributes
                             .... .... .... .... .... .... 1... .... = Read Attributes
                             .... .... .... .... .... .... .1.. .... = Delete Child
                             .... .... .... .... .... .... ..1. .... = Execute
                             .... .... .... .... .... .... ...1 .... = Write EA
                             .... .... .... .... .... .... .... 1... = Read EA
                             .... .... .... .... .... .... .... .1.. = Append
                             .... .... .... .... .... .... .... ..1. = Write
                             .... .... .... .... .... .... .... ...1 = Read

                           ALLOW-Everyone-0x10000000-OI|CI|IO
                             0... .... .... .... .... .... .... .... = Generic Read
                             .0.. .... .... .... .... .... .... .... = Generic Write
                             ..0. .... .... .... .... .... .... .... = Generic Execute
                             ...1 .... .... .... .... .... .... .... = Generic All
                             .... ...0 .... .... .... .... .... .... = System Security
                             .... .... ...0 .... .... .... .... .... = Synchronize
                             .... .... .... 0... .... .... .... .... = Write Owner
                             .... .... .... .0.. .... .... .... .... = Write DAC
                             .... .... .... ..0. .... .... .... .... = Read Control
                             .... .... .... ...0 .... .... .... .... = Delete
                             .... .... .... .... .... ...0 .... .... = Write Attributes
                             .... .... .... .... .... .... 0... .... = Read Attributes
                             .... .... .... .... .... .... .0.. .... = Delete Child
                             .... .... .... .... .... .... ..0. .... = Execute
                             .... .... .... .... .... .... ...0 .... = Write EA
                             .... .... .... .... .... .... .... 0... = Read EA
                             .... .... .... .... .... .... .... .0.. = Append
                             .... .... .... .... .... .... .... ..0. = Write
                             .... .... .... .... .... .... .... ...0 = Read
----
En el siguiente ejemplo, se muestra información de seguridad, incluida la información de seguridad de Storage-Level Access Guard, del volumen con la ruta `/datavol1` en SVM VS1:

[listing]
----
cluster::> vserver security file-directory show -vserver vs1 -path /datavol1

                Vserver: vs1
              File Path: /datavol1
      File Inode Number: 77
         Security Style: ntfs
        Effective Style: ntfs
         DOS Attributes: 10
 DOS Attributes in Text: ----D---
Expanded Dos Attributes: -
           Unix User Id: 0
          Unix Group Id: 0
         Unix Mode Bits: 777
 Unix Mode Bits in Text: rwxrwxrwx
                   ACLs: NTFS Security Descriptor
                         Control:0x8004
                         Owner:BUILTIN\Administrators
                         Group:BUILTIN\Administrators
                         DACL - ACEs
                           ALLOW-Everyone-0x1f01ff
                           ALLOW-Everyone-0x10000000-OI|CI|IO


                         Storage-Level Access Guard security
                         SACL (Applies to Directories):
                           AUDIT-EXAMPLE\Domain Users-0x120089-FA
                           AUDIT-EXAMPLE\engineering-0x1f01ff-SA
                         DACL (Applies to Directories):
                           ALLOW-EXAMPLE\Domain Users-0x120089
                           ALLOW-EXAMPLE\engineering-0x1f01ff
                           ALLOW-NT AUTHORITY\SYSTEM-0x1f01ff
                         SACL (Applies to Files):
                           AUDIT-EXAMPLE\Domain Users-0x120089-FA
                           AUDIT-EXAMPLE\engineering-0x1f01ff-SA
                         DACL (Applies to Files):
                           ALLOW-EXAMPLE\Domain Users-0x120089
                           ALLOW-EXAMPLE\engineering-0x1f01ff
                           ALLOW-NT AUTHORITY\SYSTEM-0x1f01ff
----
.Información relacionada
* xref:display-file-security-mixed-style-volumes-task.adoc[Muestra información sobre la seguridad de archivos en volúmenes mixtos de estilo de seguridad]
* xref:display-file-security-unix-style-volumes-task.adoc[Muestra información sobre la seguridad de archivos en volúmenes de estilo de seguridad UNIX]

