---
permalink: smb-admin/effective-slag-matrix-reference.html 
sidebar: sidebar 
keywords: configure, slag, volume, qtree, matrix, define, configuration, applicable, scenario, list, table, effective slag matrix 
summary: Puede configurar ESCORIA en un volumen, en un qtree o en ambos. La matriz DE ESCORIA define en qué volumen o qtree es la configuración DE ESCORIA aplicable en varios escenarios enumerados en la tabla. 
---
= Matriz de ESCORIA efectiva
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar ESCORIA en un volumen, en un qtree o en ambos. La matriz DE ESCORIA define en qué volumen o qtree es la configuración DE ESCORIA aplicable en varios escenarios enumerados en la tabla.

|===
|  | ESCORIA de volumen en un AFS | ESCORIA de volumen en una copia snapshot | ESCORIA Qtree en un AFS | ESCORIA de qtree en una copia snapshot 


 a| 
Acceso de volumen en un sistema de archivos de acceso (AFS)
 a| 
SÍ
 a| 
NO
 a| 
N.A.
 a| 
N.A.



 a| 
Acceso de volúmenes en una copia Snapshot
 a| 
SÍ
 a| 
NO
 a| 
N.A.
 a| 
N.A.



 a| 
Acceso Qtree en un AFS (cuando HAY ESCORIA en el qtree)
 a| 
NO
 a| 
NO
 a| 
SÍ
 a| 
NO



 a| 
Acceso Qtree en un AFS (cuando LA ESCORIA no está presente en qtree)
 a| 
SÍ
 a| 
NO
 a| 
NO
 a| 
NO



 a| 
Acceso de qtree en la copia snapshot (cuando HAY ESCORIA en el AFS de qtree)
 a| 
NO
 a| 
NO
 a| 
SÍ
 a| 
NO



 a| 
Acceso de qtree en la copia snapshot (cuando NO hay ESCORIA en el AFS para qtrees).
 a| 
SÍ
 a| 
NO
 a| 
NO
 a| 
NO

|===