---
permalink: smb-admin/enable-smb2-connections-domain-controllers-task.html 
sidebar: sidebar 
keywords: ontap, enable, smb, version, connect, domain, controller, default, smb2, enable smb2 connections to domain controllers 
summary: A partir de ONTAP 9.1, es posible habilitar SMB versión 2.0 para conectarse a un controlador de dominio. Hacerlo es necesario si ha deshabilitado SMB 1.0 en controladores de dominio. A partir de ONTAP 9.2, SMB2 está habilitado de forma predeterminada. 
---
= Habilite conexiones SMB2 a controladores de dominio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.1, es posible habilitar SMB versión 2.0 para conectarse a un controlador de dominio. Hacerlo es necesario si ha deshabilitado SMB 1.0 en controladores de dominio. A partir de ONTAP 9.2, SMB2 está habilitado de forma predeterminada.

.Acerca de esta tarea
La `smb2-enabled-for-dc-connections` Opción de comando habilita la opción predeterminada del sistema para la versión de ONTAP que está usando. El valor predeterminado del sistema para ONTAP 9.1 está habilitado para SMB 1.0 y deshabilitado para SMB 2.0. El valor predeterminado del sistema para ONTAP 9.2 está habilitado para SMB 1.0 y habilitado para SMB 2.0. Si la controladora de dominio no puede negociar inicialmente SMB 2.0, utiliza SMB 1.0.

SMB 1.0 puede deshabilitarse desde ONTAP a un controlador de dominio. En ONTAP 9.1, si se ha deshabilitado SMB 1.0, se debe habilitar SMB 2.0 para poder comunicarse con un controlador de dominio.

Más información sobre:

* link:../smb-config/verify-enabled-versions-task.html["Verificación de las versiones habilitadas del SMB"].
* link:supported-versions-functionality-concept.html["Funcionalidades y versiones de SMB compatibles"].


[NOTE]
====
Si `-smb1-enabled-for-dc-connections` se establece en `false` aunque `-smb1-enabled` se establece en `true`, ONTAP deniega las conexiones SMB 1.0 como cliente, pero continúa aceptando conexiones SMB 1.0 entrantes como servidor.

====
.Pasos
. Antes de cambiar la configuración de seguridad de SMB, compruebe qué versiones de SMB están habilitadas: `vserver cifs security show`
. Desplácese hacia abajo por la lista para ver las versiones de SMB.
. Ejecute el comando apropiado con el `smb2-enabled-for-dc-connections` opción.
+
|===
| Si desea que SMB2 sea... | Introduzca el comando... 


 a| 
Activado
 a| 
`vserver cifs security modify -vserver _vserver_name_ -smb2-enabled-for-dc-connections true`



 a| 
Deshabilitado
 a| 
`vserver cifs security modify -vserver _vserver_name_ -smb2-enabled-for-dc-connections false`

|===

