---
permalink: smb-admin/enable-disable-export-policies-task.html 
sidebar: sidebar 
keywords: enable, disable, export, policies, policy, smb, access, storage, virtual, machine, svm, control, resource, enable or disable export policies for smb access 
summary: 'Puede habilitar o deshabilitar las políticas de exportación para acceso de SMB en máquinas virtuales de almacenamiento (SVM). El uso de políticas de exportación para controlar el acceso de SMB a los recursos es opcional.' 
---
= Habilite o deshabilite las políticas de exportación para el acceso de SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar o deshabilitar las políticas de exportación para acceso de SMB en máquinas virtuales de almacenamiento (SVM). El uso de políticas de exportación para controlar el acceso de SMB a los recursos es opcional.

.Antes de empezar
A continuación, se muestran los requisitos para habilitar las políticas de exportación para SMB:

* El cliente debe tener un registro "'PTR'" en DNS antes de crear las reglas de exportación para ese cliente.
* Se necesita un conjunto adicional de registros «'A'» y «'PTR'» para los nombres de host si la SVM proporciona acceso a los clientes NFS y el nombre de host que desea utilizar para el acceso NFS es diferente al nombre del servidor CIFS.


.Acerca de esta tarea
Al configurar un nuevo servidor CIFS en la SVM, el uso de políticas de exportación para acceso de SMB está deshabilitado de forma predeterminada. Puede habilitar las políticas de exportación para el acceso de SMB si desea controlar el acceso en función del protocolo de autenticación o en direcciones IP de cliente o nombres de host. Es posible habilitar o deshabilitar las políticas de exportación para el acceso de SMB en cualquier momento.

.Pasos
. Configure el nivel de privilegio en Advanced: `set -privilege advanced`
. Habilite o deshabilite políticas de exportación:
+
** Habilitar políticas de exportación: `vserver cifs options modify -vserver _vserver_name_ -is-exportpolicy-enabled true`
** Desactivar las políticas de exportación: `vserver cifs options modify -vserver _vserver_name_ -is-exportpolicy-enabled false`


. Vuelva al nivel de privilegio de administrador: `set -privilege admin`


.Ejemplo
El siguiente ejemplo permite el uso de políticas de exportación para controlar el acceso de clientes SMB a los recursos en SVM vs1:

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -is-exportpolicy-enabled true

cluster1::*> set -privilege admin
----