---
permalink: smb-admin/enable-disable-access-based-enumeration-client-task.html 
sidebar: sidebar 
keywords: enable, disable, access-based, enumeration, abe, smb, share, windows, client, configure, setting, cifs, server, enable or disable access-based enumeration from a windows client 
summary: 'Puede habilitar o deshabilitar la enumeración basada en acceso (ABE) en recursos compartidos SMB desde un cliente Windows, que permite configurar esta configuración de recurso compartido sin tener que conectarse al servidor CIFS.' 
---
= Habilite o deshabilite la enumeración basada en acceso desde un cliente Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar o deshabilitar la enumeración basada en acceso (ABE) en recursos compartidos SMB desde un cliente Windows, que permite configurar esta configuración de recurso compartido sin tener que conectarse al servidor CIFS.


NOTE: La `abecmd` La utilidad no está disponible en las nuevas versiones de los clientes de Windows Server y Windows. Se lanzó como parte de Windows Server 2008. El soporte finalizó para Windows Server 2008 el 14 de enero de 2020.

.Pasos
. Desde un cliente Windows compatible con ABE, introduzca el siguiente comando: `abecmd [/enable | /disable] [/server CIFS_server_name] {/all | share_name}`
+
Para obtener más información acerca de `abecmd` Consulte la documentación del cliente de Windows.


