---
permalink: smb-admin/enable-disable-automatic-node-referrals-task.html 
sidebar: sidebar 
keywords: enable, smb, automatic, node, referral, client, access, performance, disable, ontap, enable or disable smb automatic node referrals 
summary: Puede habilitar las referencias de nodo automáticas para SMB para aumentar el rendimiento del acceso de los clientes SMB. Puede deshabilitar las referencias de nodo automáticas si no desea que ONTAP haga referencias a los clientes SMB. 
---
= Habilitar o deshabilitar las referencias automáticas de nodos de ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar las referencias de nodo automáticas para SMB para aumentar el rendimiento del acceso de los clientes SMB. Puede deshabilitar las referencias de nodo automáticas si no desea que ONTAP haga referencias a los clientes SMB.

.Antes de empezar
Debe configurarse y ejecutarse un servidor CIFS en la máquina virtual de almacenamiento (SVM).

.Acerca de esta tarea
La funcionalidad de referencias automáticas al nodo SMB está deshabilitada de manera predeterminada. Puede habilitar o deshabilitar esta funcionalidad en cada SVM, según sea necesario.

Esta opción está disponible en el nivel de privilegio avanzado.

.Pasos
. Establezca el nivel de privilegio en avanzado: `set -privilege advanced`
. Habilite o deshabilite las referencias de nodo automáticas para SMB según sea necesario:
+
|===
| Si desea que las referencias automáticas de nodo de SMB sean... | Introduzca el siguiente comando... 


 a| 
Activado
 a| 
`vserver cifs options modify -vserver vserver_name -is-referral-enabled true`



 a| 
Deshabilitado
 a| 
`vserver cifs options modify -vserver vserver_name -is-referral-enabled false`

|===
+
La configuración de la opción surte efecto para nuevas sesiones SMB. Los clientes con conexión existente pueden utilizar la referencia de nodo sólo cuando caduque el tiempo de espera de caché existente.

. Cambie al nivel de privilegio de administrador: `set -privilege admin`


.Información relacionada
xref:server-options-reference.adoc[Opciones disponibles del servidor SMB]
