---
permalink: smb-admin/enable-disable-oplocks-existing-shares-task.html 
sidebar: sidebar 
keywords: oplock, enable, smb, share, storage, virtual, machine, svm, default, circumstance, disable, alternative, enable or disable oplocks on existing smb shares 
summary: 'Los bloqueos oportunistas están habilitados en recursos compartidos de SMB en máquinas virtuales de almacenamiento (SVM) de forma predeterminada. En algunas circunstancias, puede que desee deshabilitar los bloqueos oportunistas; de forma alternativa, si ha deshabilitado los bloqueos oportunistas en un recurso compartido anteriormente, puede que desee volver a habilitar los bloqueos oportunistas.' 
---
= Habilite o deshabilite los bloqueos oportunistas en recursos compartidos de SMB de ONTAP existentes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los bloqueos oportunistas están habilitados en recursos compartidos de SMB en máquinas virtuales de almacenamiento (SVM) de forma predeterminada. En algunas circunstancias, puede que desee deshabilitar los bloqueos oportunistas; de forma alternativa, si ha deshabilitado los bloqueos oportunistas en un recurso compartido anteriormente, puede que desee volver a habilitar los bloqueos oportunistas.

.Acerca de esta tarea
Si los bloqueos oportunistas están habilitados en el volumen que contiene un recurso compartido, pero la propiedad de recurso compartido oplock de ese recurso compartido está deshabilitada, los bloqueos oportunistas se deshabilitan para ese recurso compartido. La deshabilitación de los bloqueos oportunistas en un recurso compartido tiene prioridad sobre el hecho de habilitar los bloqueos oportunistas en el volumen. Al deshabilitar los bloqueos oportunistas del recurso compartido, se deshabilitan los bloqueos oportunistas oportunistas de arrendamiento y oportunistas. Puede habilitar o deshabilitar los bloqueos oportunistas de los recursos compartidos existentes en cualquier momento.

.Paso
. Realice la acción correspondiente:
+
|===
| Si desea... | Realice lo siguiente... 


 a| 
Habilite los bloqueos oportunistas del recurso compartido modificando un recurso compartido existente
 a| 
Introduzca el siguiente comando: `vserver cifs share properties add -vserver _vserver_name_ -share-name share_name -share-properties oplocks`

[NOTE]
====
Puede especificar propiedades de recursos compartidos adicionales que desea agregar mediante una lista delimitada por comas.

====
Las propiedades recién agregadas se agregan a la lista existente de propiedades de recursos compartidos. Todas las propiedades de recurso compartido que haya especificado anteriormente permanecen vigentes.



 a| 
Deshabilite los bloqueos oportunistas de un recurso compartido modificando un recurso compartido existente
 a| 
Introduzca el siguiente comando: `vserver cifs share properties remove -vserver _vserver_name_ -share-name _share_name_ -share-properties oplocks`

[NOTE]
====
Puede especificar propiedades de recursos compartidos adicionales que desea quitar mediante una lista delimitada por comas.

====
Las propiedades de recursos compartidos que se quitan se eliminan de la lista existente de propiedades de recursos compartidos; sin embargo, las propiedades de recursos compartidos configuradas previamente que no se quitan permanecen vigentes.

|===


.Ejemplos
El siguiente comando habilita los bloqueos oportunistas del recurso compartido denominado «'Engineering» en la máquina virtual de almacenamiento (SVM, antes conocida como Vserver) vs1:

[listing]
----
cluster1::> vserver cifs share properties add -vserver vs1 -share-name Engineering -share-properties oplocks

cluster1::> vserver cifs share properties show
Vserver          Share            Properties
---------------- ---------------- -----------------
vs1              Engineering      oplocks
                                  browsable
                                  changenotify
                                  showsnapshot
----
El siguiente comando deshabilita los bloqueos oportunistas del recurso compartido denominado "'Engineering'" en SVM vs1:

[listing]
----
cluster1::> vserver cifs share properties remove -vserver vs1 -share-name Engineering -share-properties oplocks

cluster1::> vserver cifs share properties show
Vserver          Share            Properties
---------------- ---------------- -----------------
vs1              Engineering      browsable
                                  changenotify
                                  showsnapshot
----
.Información relacionada
* xref:enable-disable-oplocks-when-creating-shares-task.adoc[Habilite o deshabilite los bloqueos oportunistas al crear recursos compartidos de SMB]
* xref:monitor-oplock-status-task.adoc[Controlar el estado del plock]
* xref:add-remove-share-properties-existing-share-task.adoc[Agregar o eliminar propiedades de recursos compartidos en recursos compartidos existentes]

