---
permalink: smb-admin/enable-disable-ntfs-acls-unix-security-task.html 
sidebar: sidebar 
keywords: enable, disable, presentation, ntfs, acl, smb, client, unix, security-style, data, volume, enable or disable the presentation of ntfs acls for unix security-style data 
summary: 'Puede habilitar o deshabilitar la presentación de ACL NTFS a clientes SMB para datos de estilo de seguridad de UNIX (volúmenes de estilo de seguridad de UNIX y volúmenes mixtos de estilo de seguridad con seguridad efectiva de UNIX).' 
---
= Configure la presentación de ACL NTFS a los clientes SMB de ONTAP para datos de estilo de seguridad de UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar o deshabilitar la presentación de ACL NTFS a clientes SMB para datos de estilo de seguridad de UNIX (volúmenes de estilo de seguridad de UNIX y volúmenes mixtos de estilo de seguridad con seguridad efectiva de UNIX).

.Acerca de esta tarea
Si habilita esta opción, ONTAP presenta archivos y carpetas en volúmenes con un estilo de seguridad UNIX efectivo para los clientes de SMB como si tuviera ACL NTFS. Si deshabilita esta opción, los volúmenes se presentan como volúmenes FAT a los clientes de SMB. El valor predeterminado es presentar ACL de NTFS a los clientes de SMB.

.Pasos
. Establezca el nivel de privilegio en avanzado: `set -privilege advanced`
. Configure la opción UNIX NTFS ACL: `vserver cifs options modify -vserver _vserver_name_ -is-unix-nt-acl-enabled {true|false}`
. Compruebe que la opción está establecida en el valor deseado: `vserver cifs options show -vserver _vserver_name_`
. Vuelva al nivel de privilegio de administrador: `set -privilege admin`

