---
permalink: smb-admin/enable-branchcache-existing-share-task.html 
sidebar: sidebar 
keywords: enable, branchcache, exist, smb, share, add, share, property, exist, list, enable branchcache on an existing smb share 
summary: Puede habilitar BranchCache en un recurso compartido de SMB existente agregando la propiedad recurso compartido de branchcache a la lista existente de propiedades de recurso compartido. 
---
= Habilitar BranchCache en recursos compartidos SMB de ONTAP existentes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar BranchCache en un recurso compartido SMB existente agregando la `branchcache` propiedad de recurso compartido a la lista existente de propiedades de recurso compartido.

.Acerca de esta tarea
* Si se habilita BranchCache en el recurso compartido de SMB, el recurso compartido debe tener la configuración de los archivos sin conexión establecida en el almacenamiento manual en caché.
+
Si la opción de archivos sin conexión del recurso compartido existente no está establecida en almacenamiento en caché manual, debe configurarlo modificando el recurso compartido.

* Es posible establecer `branchcache` la propiedad en un recurso compartido aunque BranchCache no esté configurado y habilitado en la máquina virtual de almacenamiento (SVM).
+
Sin embargo, si desea que el recurso compartido ofrezca contenido en caché, debe configurar y habilitar BranchCache en la SVM.

* Al agregar `branchcache` la propiedad Compartir al recurso compartido, se conservan la configuración de recurso compartido existente y las propiedades de recurso compartido.
+
La propiedad share de BranchCache se agrega a la lista existente de propiedades compartidas. Obtenga más información sobre `vserver cifs share properties add` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-properties-add.html["Referencia de comandos del ONTAP"^].



.Pasos
. Si es necesario, configure el parámetro de recursos compartidos de archivos sin conexión para el almacenamiento en caché manual:
+
.. Determine cuál es el valor del recurso compartido de archivos sin conexión mediante el `vserver cifs share show` comando.
.. Si la configuración de archivos compartidos sin conexión no está establecida en manual, cámbiela al valor necesario: `vserver cifs share modify -vserver vserver_name -share-name share_name -offline-files manual`


. Habilitar BranchCache en un recurso compartido de SMB existente: `vserver cifs share properties add -vserver vserver_name -share-name share_name -share-properties branchcache`
. Compruebe que la propiedad de recurso compartido de BranchCache esté configurada en el recurso compartido de SMB: `vserver cifs share show -vserver vserver_name -share-name share_name`


.Ejemplo
El siguiente comando habilita BranchCache en un recurso compartido SMB existente denominado «dATA2» con una ruta de acceso `/data2` de en SVM VS1:

[listing]
----
cluster1::> vserver cifs share show -vserver vs1 -share-name data2

                      Vserver: vs1
                        Share: data2
     CIFS Server NetBIOS Name: VS1
                         Path: /data2
             Share Properties: oplocks
                               browsable
                               changenotify
                               showsnapshot
           Symlink Properties: -
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: 10s
                  Volume Name: -
                Offline Files: manual
Vscan File-Operations Profile: standard

cluster1::> vserver cifs share properties add  -vserver vs1 -share-name data2 -share-properties branchcache

cluster1::> vserver cifs share show -vserver vs1 -share-name data2

                      Vserver: vs1
                        Share: data2
     CIFS Server NetBIOS Name: VS1
                         Path: /data2
             Share Properties: oplocks
                               browsable
                               showsnapshot
                               changenotify
                               branchcache
           Symlink Properties: -
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: 10s
                  Volume Name: -
                Offline Files: manual
Vscan File-Operations Profile: standard
----
.Información relacionada
xref:add-remove-share-properties-existing-share-task.adoc[Agregar o quitar propiedades de recursos compartidos en un recurso compartido SMB existente]

xref:disable-branchcache-single-share-task.adoc[Deshabilitar BranchCache en un único recurso compartido de SMB]
