---
permalink: smb-admin/enable-disable-dynamic-access-control-task.html 
sidebar: sidebar 
keywords: option, enable, dynamic, access, control, dac, secure, object, cifs, server, disable, default, enable or disable dynamic access control 
summary: 'La opción que permite utilizar el control de acceso dinámico (DAC) para proteger objetos en el servidor CIFS está deshabilitada de forma predeterminada. Debe habilitar la opción si desea utilizar el control de acceso dinámico en el servidor CIFS. Si más adelante decide que no desea utilizar el control de acceso dinámico para proteger los objetos almacenados en el servidor CIFS, puede deshabilitar la opción.' 
---
= Active o desactive la descripción general de Dynamic Access Control
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La opción que permite utilizar el control de acceso dinámico (DAC) para proteger objetos en el servidor CIFS está deshabilitada de forma predeterminada. Debe habilitar la opción si desea utilizar el control de acceso dinámico en el servidor CIFS. Si más adelante decide que no desea utilizar el control de acceso dinámico para proteger los objetos almacenados en el servidor CIFS, puede deshabilitar la opción.

.Acerca de esta tarea
Una vez que el control de acceso dinámico está activado, el sistema de archivos puede contener ACL con entradas relacionadas con el control de acceso dinámico. Si el control de acceso dinámico está desactivado, se ignorarán las entradas actuales del control de acceso dinámico y no se permitirán las nuevas.

Esta opción solo está disponible en el nivel de privilegios avanzado.

.Paso
. Configure el nivel de privilegio en Advanced: `set -privilege advanced`
. Ejecute una de las siguientes acciones:
+
|===


| Si desea que el control de acceso dinámico sea... | Introduzca el comando... 


 a| 
Activado
 a| 
`vserver cifs options modify -vserver _vserver_name_ -is-dac-enabled true`



 a| 
Deshabilitado
 a| 
`vserver cifs options modify -vserver _vserver_name_ -is-dac-enabled false`

|===
. Devolver al nivel de privilegio del administrador: `set -privilege admin`


.Información relacionada
xref:configure-central-access-policies-secure-data-task.adoc[Configuración de políticas de acceso centrales para proteger los datos en servidores CIFS]
