---
permalink: smb-admin/enable-disable-gpo-support-task.html 
sidebar: sidebar 
keywords: enable, disable, group, policy, object, gpo, support, cifs, server, applicable, define, policy, organizational, unit, ou, enable or disable gpo support on a cifs server 
summary: 'Puede habilitar o deshabilitar la compatibilidad con objetos de directiva de grupo (GPO) en un servidor CIFS. Si habilita la compatibilidad de GPO en un servidor CIFS, los GPO aplicables definidos en la directiva de grupo, la directiva que se aplica a la unidad organizativa (OU) que contiene el objeto de equipo del servidor CIFS, se aplican al servidor CIFS.' 
---
= Habilitar o deshabilitar la compatibilidad de GPO en los servidores SMB de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar o deshabilitar la compatibilidad con objetos de directiva de grupo (GPO) en un servidor CIFS. Si habilita la compatibilidad de GPO en un servidor CIFS, los GPO aplicables definidos en la directiva de grupo (la directiva que se aplica a la unidad organizativa (OU) que contiene el objeto de equipo del servidor CIFS) se aplican al servidor CIFS.

[NOTE]
.Acerca de esta tarea
====
Los GPO no pueden habilitarse en servidores CIFS en modo de grupo de trabajo.

====
.Pasos
. Ejecute una de las siguientes acciones:
+
|===
| Si desea... | Introduzca el comando... 


 a| 
Habilite los GPO
 a| 
`vserver cifs group-policy modify -vserver _vserver_name_ -status enabled`



 a| 
Deshabilitar GPO
 a| 
`vserver cifs group-policy modify -vserver _vserver_name_ -status disabled`

|===
. Compruebe que la compatibilidad con GPO está en el estado deseado: `vserver cifs group-policy show -vserver +vserver_name_`
+
El estado de la directiva de grupo de los servidores CIFS en el modo de grupo se muestra como "desactivado".



.Ejemplo
En el siguiente ejemplo, se habilita la compatibilidad de GPO en máquinas virtuales de almacenamiento (SVM) vs1:

[listing]
----
cluster1::> vserver cifs group-policy modify -vserver vs1 -status enabled

cluster1::> vserver cifs group-policy show -vserver vs1

            Vserver: vs1
Group Policy Status: enabled
----
.Información relacionada
xref:supported-gpos-concept.adoc[Objetos de normativa de grupo compatibles]

xref:requirements-gpos-concept.adoc[Requisitos para el uso de GPO con su servidor CIFS]

xref:gpos-updated-server-concept.adoc[Cómo se actualizan los GPO en el servidor CIFS]

xref:manual-update-gpo-settings-task.adoc[Actualizar manualmente la configuración de GPO en el servidor CIFS]

xref:display-gpo-config-task.adoc[Mostrar información acerca de las configuraciones de GPO]
