---
permalink: smb-admin/enable-ldap-signing-sealing-task.html 
sidebar: sidebar 
keywords: cifs, server, sign, seal, secure, communication, active, directory, ldap, modify, security, setting, sign, seal, enable, enable ldap signing and sealing on the cifs server 
summary: Antes de que el servidor CIFS pueda utilizar la firma y el sellado para establecer una comunicación segura con un servidor LDAP de Active Directory, debe modificar la configuración de seguridad del servidor CIFS para habilitar la firma y el sellado LDAP. 
---
= Habilite la firma y el sellado LDAP en los servidores SMB de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de que el servidor CIFS pueda utilizar la firma y el sellado para establecer una comunicación segura con un servidor LDAP de Active Directory, debe modificar la configuración de seguridad del servidor CIFS para habilitar la firma y el sellado LDAP.

.Antes de empezar
Debe consultar al administrador del servidor AD para determinar los valores de configuración de seguridad adecuados.

.Pasos
. Configure las opciones de seguridad del servidor CIFS que permitan el tráfico firmado y sellado con servidores LDAP de Active Directory: `vserver cifs security modify -vserver _vserver_name_ -session-security-for-ad-ldap {none|sign|seal}`
+
Puede activar la firma (`sign`, integridad de datos), la firma y el sellado (`seal`, la integridad y el cifrado de los datos), o ninguno  `none`, sin firma ni sellado). El valor predeterminado es `none`.

. Compruebe que la configuración de seguridad de firma y sellado LDAP se ha definido correctamente: `vserver cifs security show -vserver _vserver_name_`
+
[NOTE]
====
Si la SVM utiliza el mismo servidor LDAP para consultar la asignación de nombres u otra información de UNIX, como usuarios, grupos y netgroups, debe habilitar la configuración correspondiente con `-session-security` la opción `vserver services name-service ldap client modify` del comando.

====

