---
permalink: smb-admin/enable-disable-local-user-accounts-task.html 
sidebar: sidebar 
keywords: enable, local, user, account, access, data, contain, storage, virtual, machine, svm, smb, connection, disable, enable or disable local user accounts 
summary: 'Es posible habilitar una cuenta de usuario local si desea que el usuario pueda acceder a los datos contenidos en la máquina virtual de almacenamiento (SVM) a través de una conexión de SMB. También puede deshabilitar una cuenta de usuario local si no desea que ese usuario acceda a los datos de SVM mediante SMB.' 
---
= Habilitar o deshabilitar cuentas de usuario SMB de ONTAP locales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible habilitar una cuenta de usuario local si desea que el usuario pueda acceder a los datos contenidos en la máquina virtual de almacenamiento (SVM) a través de una conexión de SMB. También puede deshabilitar una cuenta de usuario local si no desea que ese usuario acceda a los datos de SVM mediante SMB.

.Acerca de esta tarea
Para habilitar un usuario local, debe modificar la cuenta de usuario.

.Paso
. Ejecute la acción adecuada:
+
|===
| Si desea... | Introduzca el comando... 


 a| 
Habilite la cuenta de usuario
 a| 
`vserver cifs users-and-groups local-user modify ‑vserver _vserver_name_ -user-name _user_name_ -is-account-disabled false`



 a| 
Desactive la cuenta de usuario
 a| 
`vserver cifs users-and-groups local-user modify ‑vserver _vserver_name_ -user-name _user_name_ -is-account-disabled true`

|===

