---
permalink: smb-admin/enable-ipv6-task.html 
sidebar: sidebar 
keywords: ipv6, network, enable, cluster, setup, administrator, smb, enable ipv6 for smb, cluster administrator only 
summary: Las redes IPv6 no se habilitan durante la configuración del clúster. Un administrador de clúster debe habilitar IPv6 después de que la configuración del clúster se haya completado a fin de usar IPv6 para SMB. Cuando el administrador de clúster habilita IPv6, se habilita para todo el clúster. 
---
= Habilitar IPv6 para SMB (solo administradores de clúster)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las redes IPv6 no se habilitan durante la configuración del clúster. Un administrador de clúster debe habilitar IPv6 después de que la configuración del clúster se haya completado a fin de usar IPv6 para SMB. Cuando el administrador de clúster habilita IPv6, se habilita para todo el clúster.

.Paso
. Habilitar IPv6: `network options ipv6 modify -enabled true`
+
Para obtener más información acerca de cómo habilitar IPv6 en el clúster y configurar LIF IPv6, consulte _Network Management Guide_.

+
IPv6 está habilitado. Se pueden configurar LIF de datos IPv6 para el acceso SMB.



.Información relacionada
* xref:monitor-display-ipv6-sessions-task.adoc[Supervisar y mostrar información acerca de las sesiones SMB de IPv6]
* link:../networking/networking_reference.html["Visualice la red mediante System Manager"]
* link:https://docs.netapp.com/us-en/ontap-cli/network-options-ipv6-modify.html["opciones de red ipv6 modificar"^]

