---
permalink: smb-admin/folder-redirection-store-data-concept.html 
sidebar: sidebar 
keywords: ontap, support, microsoft, folder, redirection, enable, administrator, redirect, location, cifs, server, windows, client, store, smb, share, use folder redirection to store data on a cifs server 
summary: ONTAP admite la redirección de carpetas de Microsoft, lo que permite que los usuarios o administradores redirijan la ruta de una carpeta local a una ubicación en el servidor CIFS. Parece que si las carpetas redirigidas se almacenan en el cliente local de Windows, aunque los datos se almacenen en un recurso compartido de SMB. 
---
= Utilice la redirección de carpetas para almacenar los datos en una introducción al servidor SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP admite la redirección de carpetas de Microsoft, lo que permite que los usuarios o administradores redirijan la ruta de una carpeta local a una ubicación en el servidor CIFS. Parece que si las carpetas redirigidas se almacenan en el cliente local de Windows, aunque los datos se almacenen en un recurso compartido de SMB.

La redirección de carpetas está destinada principalmente a las empresas que ya han implementado directorios iniciales y que desean mantener la compatibilidad con su entorno de directorio raíz existente.

* `Documents`, , `Desktop` y `Start Menu` son ejemplos de carpetas que puede redirigir.
* Los usuarios pueden redirigir carpetas desde su cliente Windows.
* Los administradores pueden configurar y administrar centralmente la redirección de carpetas configurando GPO en Active Directory.
* Si los administradores han configurado perfiles de itinerancia, la redirección de carpetas permite a los administradores dividir los datos de usuario de los datos de perfil.
* Los administradores pueden usar la redirección de carpetas y los archivos sin conexión juntos para redirigir el almacenamiento de datos de carpetas locales al servidor CIFS, permitiendo a los usuarios almacenar el contenido en la memoria caché localmente.


.Información relacionada
xref:offline-files-allow-caching-concept.adoc[Uso de archivos sin conexión para permitir el almacenamiento en caché de archivos para su uso sin conexión]

xref:roaming-profiles-store-user-profiles-concept.adoc[Uso de perfiles de itinerancia para almacenar perfiles de usuario de forma centralizada en un servidor CIFS asociado con la SVM]
