---
permalink: smb-admin/home-directory-config-concept.html 
sidebar: sidebar 
keywords: create, additional, home, directory, configuration, variable, enable, customize, additional home directory configurations 
summary: 'Puede crear configuraciones adicionales de directorio principal utilizando las variables %w, %d y %u, lo que le permite personalizar la configuración del directorio principal para satisfacer sus necesidades.' 
---
= Configuraciones adicionales de directorio inicial
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear configuraciones de directorio raíz adicionales mediante las `%w` `%d` `%u` variables , y, lo que permite personalizar la configuración del directorio raíz para satisfacer sus necesidades.

Puede crear una serie de configuraciones de directorios iniciales mediante una combinación de variables y cadenas estáticas en los nombres de recursos compartidos y las rutas de búsqueda. En la siguiente tabla se muestran algunos ejemplos que ilustran cómo crear distintas configuraciones de directorio principal:

|===
| Rutas creadas cuando `/vol1/user` contiene directorios iniciales... | Compartir comando... 


 a| 
Para crear una ruta de acceso compartida `\\vs1\~win_username` que dirija al usuario a. `/vol1/user/win_username`
 a| 
`vserver cifs share create -share-name ~%w -path %w -share-properties oplocks,browsable,changenotify,homedirectory`



 a| 
Para crear una ruta de acceso compartida `\\vs1\win_username` que dirija al usuario a. `/vol1/user/domain/win_username`
 a| 
`vserver cifs share create -share-name %w -path %d/%w -share-properties oplocks,browsable,changenotify,homedirectory`



 a| 
Para crear una ruta de acceso compartida `\\vs1\win_username` que dirija al usuario a. `/vol1/user/unix_username`
 a| 
`vserver cifs share create -share-name %w -path %u -share-properties oplocks,browsable,changenotify,homedirectory`



 a| 
Para crear una ruta de acceso compartida `\\vs1\unix_username` que dirija al usuario a. `/vol1/user/unix_username`
 a| 
`vserver cifs share create -share-name %u -path %u -share-properties oplocks,browsable,changenotify,homedirectory`

|===