---
permalink: smb-admin/improve-microsoft-remote-copy-performance-concept.html 
sidebar: sidebar 
keywords: microsoft, offload, data, transfer, odx, copy, offload, enable, direct, compatible, computer, improve microsoft remote copy performance 
summary: 'La transferencia de datos descargados (ODX) de Microsoft, también conocida como descarga de copias, permite realizar transferencias directas de datos dentro de dispositivos de almacenamiento compatibles o entre ellos sin transferir los datos a través del equipo host.' 
---
= Mejorar el rendimiento de las copias remotas de Microsoft
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La transferencia de datos descargados (ODX) de Microsoft, también conocida como _copy fload_, permite transferir datos directamente dentro o entre dispositivos de almacenamiento compatibles sin transferir los datos a través del equipo host.

ONTAP admite ODX para los protocolos SMB Y SAN. El origen puede ser un servidor CIFS o una LUN; el destino puede ser un servidor CIFS o una LUN.

En las transferencias de archivos que no son ODX, los datos se leen del origen y se transfieren a través de la red al equipo cliente. El equipo cliente transfiere los datos a través de la red al destino. En resumen, el equipo cliente lee los datos del origen y los escribe en el destino. Con las transferencias de archivos ODX, los datos se copian directamente del origen al destino.

Dado que las copias descargados de ODX se realizan directamente entre el almacenamiento de origen y destino, se obtienen importantes ventajas en el rendimiento. Las ventajas en cuanto a rendimiento incluyen unos tiempos de copia más rápidos entre el origen y el destino, una menor utilización de recursos (CPU, memoria) en el cliente y una menor utilización de ancho de banda de I/o de la red.

En los entornos SMB, esta funcionalidad solo está disponible cuando el cliente y el servidor de almacenamiento admiten SMB 3.0 y la función ODX. En entornos SAN, esta funcionalidad solo está disponible cuando el cliente y el servidor de almacenamiento admiten la función ODX. Los equipos cliente compatibles con ODX y que tengan habilitada ODX automáticamente y de forma transparente utilizan la transferencia de archivos descargados cuando se mueven o copian archivos. ODX se utiliza independientemente de si arrastra y suelta archivos a través del Explorador de Windows, o si utiliza comandos de copia de archivos de la línea de comandos, o si una aplicación cliente inicia solicitudes de copia de archivos.

.Información relacionada
xref:improve-client-response-node-referrals-concept.adoc[Mejorar el tiempo de respuesta del cliente al proporcionar referencias automáticas a nodos SMB con ubicación automática]

link:../smb-hyper-v-sql/index.html["Configuración de SMB para Microsoft Hyper-V y SQL Server"]
