---
permalink: smb-admin/ipv6-connect-external-servers-concept.html 
sidebar: sidebar 
keywords: create, configuration, requirement, aware, cifs, server, ipv6, connection, external, server, how cifs servers use ipv6 to connect to external servers 
summary: Para crear una configuración que cumpla con sus requisitos, debe saber cómo usan IPv6 los servidores CIFS a la hora de realizar conexiones a servidores externos. 
---
= Descubra cómo los servidores SMB de ONTAP utilizan IPv6 para conectarse a servidores externos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para crear una configuración que cumpla con sus requisitos, debe saber cómo usan IPv6 los servidores CIFS a la hora de realizar conexiones a servidores externos.

* Selección de direcciones de origen
+
Si se intenta conectarse a un servidor externo, la dirección de origen seleccionada debe ser del mismo tipo que la dirección de destino. Por ejemplo, si se conecta a una dirección IPv6, la máquina virtual de almacenamiento (SVM) que aloja el servidor CIFS debe tener una LIF de datos o una LIF de gestión que tenga una dirección IPv6 que se usará como dirección de origen. Del mismo modo, si se conecta a una dirección IPv4, la SVM debe tener una LIF de datos o una LIF de gestión que tenga una dirección IPv4 que se usará como dirección de origen.

* Para los servidores detectados dinámicamente mediante DNS, la detección de servidores se realiza de la siguiente manera:
+
** Si IPv6 está deshabilitado en el clúster, solo se detectan direcciones de los servidores IPv4.
** Si IPv6 está habilitado en el clúster, se detectan tanto las direcciones de los servidores IPv4 como IPv6. Cualquiera de los dos tipos puede utilizarse en función de la idoneidad del servidor al que pertenece la dirección y de la disponibilidad de LIF de gestión o datos IPv6 o IPv4. La detección dinámica de servidores se utiliza para detectar controladores de dominio y sus servicios asociados, como LSA, NETLOGON, Kerberos y LDAP.


* Conectividad del servidor DNS
+
Si la SVM utiliza IPv6 al conectarse a un servidor DNS depende de la configuración de los servicios de nombres DNS. Si los servicios DNS se configuran para utilizar direcciones IPv6, las conexiones se realizan mediante IPv6. Si lo desea, la configuración de los servicios de nombres DNS puede utilizar direcciones IPv4 para que las conexiones con los servidores DNS sigan usando direcciones IPv4. Las combinaciones de direcciones IPv4 e IPv6 pueden especificarse al configurar los servicios de nombres DNS.

* Conectividad del servidor LDAP
+
Si la SVM utiliza IPv6 al conectarse a un servidor LDAP depende de la configuración del cliente LDAP. Si el cliente LDAP está configurado para usar direcciones IPv6, las conexiones se realizan mediante IPv6. Si lo desea, la configuración del cliente LDAP puede usar direcciones IPv4 a fin de que las conexiones con servidores LDAP sigan usando direcciones IPv4. Al configurar la configuración del cliente LDAP, se pueden especificar las combinaciones de direcciones IPv4 e IPv6.

+
[NOTE]
====
La configuración del cliente LDAP se utiliza al configurar LDAP para los servicios de nombre de usuario, grupo y grupo de redes de UNIX.

====
* Conectividad del servidor NIS
+
Si la SVM utiliza IPv6 al conectarse a un servidor NIS depende de la configuración de los servicios de nombres NIS. Si los servicios NIS se configuran para utilizar direcciones IPv6, las conexiones se realizan mediante IPv6. Si lo desea, la configuración de los servicios de nombres NIS puede utilizar direcciones IPv4 para que las conexiones con los servidores NIS sigan usando direcciones IPv4. Las combinaciones de direcciones IPv4 e IPv6 pueden especificarse al configurar los servicios de nombres NIS.

+
[NOTE]
====
Los servicios de nombres NIS se utilizan para almacenar y administrar objetos de usuario, grupo, grupo de red y nombre de host de UNIX.

====


.Información relacionada
xref:enable-ipv6-task.adoc[Habilitar IPv6 para SMB (solo administradores de clúster)]

xref:monitor-display-ipv6-sessions-task.adoc[Supervisar y mostrar información acerca de las sesiones SMB de IPv6]
