---
permalink: smb-admin/join-svm-active-directory-domain-task.html 
sidebar: sidebar 
keywords: join, storage, virtual, machine, svm, active, directory, domain, delete, deleting, exist, smb, cifs, server, modify, domain, vserver, cifs, rejoin, join a svm to an active directory domain 
summary: 'Puede unirse a una máquina virtual de almacenamiento (SVM) a un dominio de Active Directory sin eliminar el servidor SMB existente modificando el dominio mediante el comando vserver cifs modify. Puede volver a unirse al dominio actual o unirse a uno nuevo.' 
---
= Únase a las SVM de SMB de ONTAP a los dominios de Active Directory
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede unir una máquina virtual de almacenamiento (SVM) a un dominio de Active Directory sin eliminar el servidor SMB existente mediante la modificación del dominio con `vserver cifs modify` el comando. Puede volver a unirse al dominio actual o unirse a uno nuevo.

.Antes de empezar
* La SVM ya debe tener una configuración de DNS.
* La configuración de DNS para la SVM debe poder servir el dominio de destino.
+
Los servidores DNS deben contener los registros de ubicación de servicio (SRV) para el LDAP de dominio y los servidores del controlador de dominio.



.Acerca de esta tarea
* El estado administrativo del servidor CIFS debe estar configurado para `down` continuar con la modificación del dominio de Active Directory.
* Si el comando se completa correctamente, el estado administrativo se establece automáticamente en `up`. Obtenga más información sobre `up` en el link:https://docs.netapp.com/us-en/ontap-cli/up.html["Referencia de comandos del ONTAP"^].
* Al unirse a un dominio, este comando puede tardar varios minutos en completarse.


.Pasos
. Una la SVM al dominio del servidor CIFS: `vserver cifs modify -vserver _vserver_name_ -domain _domain_name_ -status-admin down`
+
Obtenga más información sobre `vserver cifs modify` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-modify.html["Referencia de comandos del ONTAP"^]. Si necesita reconfigurar DNS para el nuevo dominio, obtenga más información `vserver dns modify` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+dns+modify["Referencia de comandos del ONTAP"^].

+
Para crear una cuenta de máquina de Active Directory para el servidor SMB, debe proporcionar el nombre y la contraseña de una cuenta de Windows con suficiente Privileges para agregar equipos al `ou= _example_ ou` contenedor dentro del `_example_` dominio .com.

+
A partir de ONTAP 9.7, el administrador de AD puede proporcionarle un URI a un archivo keytab como alternativa a proporcionarle un nombre y una contraseña a una cuenta de Windows con privilegios. Cuando reciba el URI, inclúyalo en el `-keytab-uri` parámetro con `vserver cifs` los comandos.

. Compruebe que el servidor CIFS se encuentra en el dominio de Active Directory deseado: `vserver cifs show`


.Ejemplo
En el siguiente ejemplo, el servidor SMB «'CIFSSERVER1'» de la SVM vs1 se une al dominio example.com mediante la autenticación keytab:

[listing]
----

cluster1::> vserver cifs modify -vserver vs1 -domain example.com -status-admin down -keytab-uri http://admin.example.com/ontap1.keytab

cluster1::> vserver cifs show

          Server       Status       Domain/Workgroup  Authentication
Vserver   Name         Admin        Name              Style
--------- -----------  ---------    ----------------  --------------
vs1       CIFSSERVER1  up           EXAMPLE          domain
----