---
permalink: smb-admin/list-supported-privileges-reference.html 
sidebar: sidebar 
keywords: ontap, predefined, support, privilege, local, group, add, user, exist, domain, list of supported privileges 
summary: ONTAP tiene un conjunto predefinido de privilegios admitidos. Algunos grupos locales predefinidos tienen algunos de estos privilegios añadidos de forma predeterminada. También puede agregar o quitar privilegios de los grupos predefinidos o crear nuevos usuarios o grupos locales y agregar privilegios a los grupos que creó o a los usuarios y grupos de dominio existentes. 
---
= Lista de privilegios compatibles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tiene un conjunto predefinido de privilegios admitidos. Algunos grupos locales predefinidos tienen algunos de estos privilegios añadidos de forma predeterminada. También puede agregar o quitar privilegios de los grupos predefinidos o crear nuevos usuarios o grupos locales y agregar privilegios a los grupos que creó o a los usuarios y grupos de dominio existentes.

En la siguiente tabla se enumeran los privilegios admitidos en la máquina virtual de almacenamiento (SVM) y se proporciona una lista de los grupos BUILTIN con privilegios asignados:

|===
| Nombre del privilegio | Configuración de seguridad predeterminada | Descripción 


 a| 
`SeTcbPrivilege`
 a| 
Ninguno
 a| 
Actuar como parte del sistema operativo



 a| 
`SeBackupPrivilege`
 a| 
`BUILTIN\Administrators`, `BUILTIN\Backup Operators`
 a| 
Realice copias de seguridad de archivos y directorios, anulando cualquier ACL



 a| 
`SeRestorePrivilege`
 a| 
`BUILTIN\Administrators`, `BUILTIN\Backup Operators`
 a| 
Restaurar archivos y directorios, anulando cualquier ACL establecer cualquier SID de usuario o grupo válido como propietario del archivo



 a| 
`SeTakeOwnershipPrivilege`
 a| 
`BUILTIN\Administrators`
 a| 
Tomar posesión de archivos u otros objetos



 a| 
`SeSecurityPrivilege`
 a| 
`BUILTIN\Administrators`
 a| 
Gestionar auditosEsta incluye la visualización, el volcado y la eliminación del registro de seguridad.



 a| 
`SeChangeNotifyPrivilege`
 a| 
`BUILTIN\Administrators`, `BUILTIN\Backup Operators`, `BUILTIN\Power Users`, `BUILTIN\Users`, `Everyone`
 a| 
Omisión de comprobaciones de traveríalos usuarios con este privilegio no tienen permisos de recorrido (x) para recorrer carpetas, enlaces simbólicos o uniones.

|===
.Información relacionada
* xref:assign-privileges-concept.adoc[Asigne privilegios locales]
* xref:configure-bypass-traverse-checking-concept.adoc[Configuración de la comprobación de recorrido de derivación]

