---
permalink: smb-admin/local-users-groups-concepts-concept.html 
sidebar: sidebar 
keywords: local, user, group, basic, information, determine, determining, configure, environment, local users and groups concepts 
summary: Debe saber cuáles son los usuarios y grupos locales, así como alguna información básica sobre ellos, antes de determinar si configurar y utilizar usuarios y grupos locales en su entorno. 
---
= Obtenga información sobre los usuarios y grupos locales de ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe saber cuáles son los usuarios y grupos locales, así como alguna información básica sobre ellos, antes de determinar si configurar y utilizar usuarios y grupos locales en su entorno.

* *Usuario local*
+
Una cuenta de usuario con un identificador de seguridad único (SID) que solo tiene visibilidad en la máquina virtual de almacenamiento (SVM) donde se crea. Las cuentas de usuario local tienen un conjunto de atributos, incluidos el nombre de usuario y el SID. Una cuenta de usuario local autentica de forma local en el servidor CIFS mediante la autenticación NTLM.

+
Las cuentas de usuario tienen varios usos:

+
** Se utiliza para otorgar privilegios _User Rights Management_ a un usuario.
** Se usa para controlar el acceso a nivel de recurso compartido y de archivo a los recursos de archivos y carpetas que posee la SVM.


* *Grupo local*
+
Un grupo con un SID exclusivo tiene visibilidad solo en la SVM donde se crea. Los grupos contienen un conjunto de miembros. Los miembros pueden ser usuarios locales, usuarios de dominio, grupos de dominio y cuentas de equipos de dominio. Los grupos se pueden crear, modificar o eliminar.

+
Los grupos tienen varios usos:

+
** Se utiliza para otorgar privilegios _User Rights Management_ a sus miembros.
** Se usa para controlar el acceso a nivel de recurso compartido y de archivo a los recursos de archivos y carpetas que posee la SVM.


* *Dominio local*
+
Un dominio que tiene un alcance local, delimitado por la SVM. El nombre del dominio local es el nombre del servidor CIFS. Los usuarios y grupos locales se encuentran dentro del dominio local.

* *Identificador de seguridad (SID)*
+
Un SID es un valor numérico de longitud variable que identifica los principios de seguridad de estilo Windows. Por ejemplo, un SID típico toma la siguiente forma: S-1-5-21-3139654847-1303905135-2517279418-123456.

* *Autenticación NTLM*
+
Un método de seguridad de Microsoft Windows que se utiliza para autenticar usuarios en un servidor CIFS.

* *Base de datos replicada en cluster (RDB)*
+
Base de datos replicada con una instancia en cada nodo de un clúster. Los objetos de usuario local y de grupo se almacenan en el RDB.


