---
permalink: smb-admin/local-users-groups-when-deleting-servers-concept.html 
sidebar: sidebar 
keywords: default, set, local, user, group, cifs, server, associate, svm, administrator, create, delete, what happens to local users and groups when deleting cifs servers 
summary: 'El conjunto predeterminado de usuarios y grupos locales se crea cuando se crea un servidor CIFS y está asociado con las máquinas virtuales de almacenamiento (SVM) que alojan el servidor CIFS. Los administradores de SVM pueden crear usuarios y grupos locales en cualquier momento. Debe saber qué sucede con los usuarios locales y los grupos al eliminar el servidor CIFS.' 
---
= Lo que sucede a los usuarios locales y los grupos al eliminar servidores CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El conjunto predeterminado de usuarios y grupos locales se crea cuando se crea un servidor CIFS y está asociado con las máquinas virtuales de almacenamiento (SVM) que alojan el servidor CIFS. Los administradores de SVM pueden crear usuarios y grupos locales en cualquier momento. Debe saber qué sucede con los usuarios locales y los grupos al eliminar el servidor CIFS.

Los usuarios y grupos locales están asociados a las SVM; por lo tanto, no se eliminan cuando los servidores CIFS se eliminan debido a consideraciones de seguridad. Aunque los usuarios y grupos locales no se eliminan al eliminar el servidor CIFS, sí se ocultan. No se pueden ver ni gestionar usuarios y grupos locales hasta que se vuelva a crear un servidor CIFS en la SVM.

[NOTE]
====
El estado administrativo del servidor CIFS no afecta a la visibilidad de los grupos o usuarios locales.

====