---
permalink: smb-admin/manage-netbios-aliases-concept.html 
sidebar: sidebar 
keywords: netbios, alternative, name, smb, client, configuring, configure, consolidate, consolidating, data, original, file, server, manage netbios aliases for smb servers 
summary: Los alias NetBIOS son nombres alternativos para el servidor SMB que los clientes SMB pueden utilizar al conectarse con el servidor SMB. La configuración de alias NetBIOS para un servidor SMB puede ser útil cuando está consolidando datos de otros servidores de archivos en el servidor SMB y desea que el servidor SMB responda a los nombres de los servidores de archivos originales. 
---
= Obtenga información sobre la administración de alias de NetBIOS para servidores SMB de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los alias NetBIOS son nombres alternativos para el servidor SMB que los clientes SMB pueden utilizar al conectarse con el servidor SMB. La configuración de alias NetBIOS para un servidor SMB puede ser útil cuando está consolidando datos de otros servidores de archivos en el servidor SMB y desea que el servidor SMB responda a los nombres de los servidores de archivos originales.

Puede especificar una lista de alias NetBIOS cuando cree el servidor SMB o en cualquier momento después de crear el servidor SMB. Puede agregar o quitar alias NetBIOS de la lista en cualquier momento. Puede conectarse al servidor SMB utilizando cualquiera de los nombres de la lista de alias NetBIOS.

.Información relacionada
xref:display-netbios-over-tcp-connections-task.adoc[Visualización de información acerca de NetBIOS sobre conexiones TCP]
