---
permalink: smb-admin/manage-local-privileges.html 
sidebar: sidebar 
keywords: manage, right, user, local, domain, add, privilege, override, default, object, enhance, customize, user, group, add privileges to local or domain users or groups 
summary: Puede administrar los derechos de usuario para usuarios o grupos locales o de dominio mediante la adición de privilegios. Los privilegios agregados anulan los privilegios predeterminados asignados a cualquiera de estos objetos. Esto proporciona una seguridad mejorada al permitirle personalizar qué privilegios tiene un usuario o grupo. 
---
= Administrar privilegios a usuarios o grupos locales o de dominio de ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




[[add-privileges-to-ontap-smb-local-or-domain-users-or-groups]]
== Agregar privilegios a usuarios o grupos locales o de dominio de ONTAP SMB

Puede administrar los derechos de usuario para usuarios o grupos locales o de dominio mediante la adición de privilegios. Los privilegios agregados anulan los privilegios predeterminados asignados a cualquiera de estos objetos. Esto proporciona una seguridad mejorada al permitirle personalizar qué privilegios tiene un usuario o grupo.

.Antes de empezar
Debe haber ya el usuario o grupo local o de dominio al que se añadirán privilegios.

.Acerca de esta tarea
Al agregar un privilegio a un objeto se reemplazan los privilegios predeterminados para ese usuario o grupo. Al añadir un privilegio, no se quitan los privilegios añadidos anteriormente.

Debe tener en cuenta lo siguiente al agregar privilegios a usuarios o grupos locales o de dominio:

* Puede añadir uno o varios privilegios.
* Al agregar privilegios a un usuario o grupo de dominio, ONTAP puede validar el usuario o grupo de dominio poniéndose en contacto con el controlador de dominio.
+
Es posible que se produzca un error en el comando si ONTAP no puede comunicarse con la controladora de dominio.



.Pasos
. Añade uno o más privilegios a un usuario o grupo local o de dominio:
+
[source, cli]
----
vserver cifs users-and-groups privilege add-privilege -vserver <SVM_name> -user-or-group-name <name> -privileges <privilege>[,...]
----
. Verifica que los privilegios deseados se apliquen al objeto:
+
[source, cli]
----
vserver cifs users-and-groups privilege show -vserver <SVM_name> -user-or-group-name <name>
----


.Ejemplo
En el siguiente ejemplo, se añaden los privilegios «ShebPrivilege» y «SeeTakeOwnershipPrivilege» al usuario «'CIFS_SERVER\sue» en la máquina virtual de almacenamiento (SVM, antes denominada Vserver) vs1:

[listing]
----
cluster1::> vserver cifs users-and-groups privilege add-privilege -vserver vs1 -user-or-group-name CIFS_SERVER\sue -privileges SeTcbPrivilege,SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- ---------------
vs1       CIFS_SERVER\sue       SeTcbPrivilege
                                SeTakeOwnershipPrivilege
----


[[remove-privileges-from-ontap-smb-local-or-domain-users-or-groups]]
== Eliminar privilegios de usuarios o grupos locales o de dominio de ONTAP SMB

Puede administrar derechos de usuario para usuarios o grupos locales o de dominio eliminando privilegios. Esto proporciona una seguridad mejorada al permitirle personalizar los privilegios máximos que tienen los usuarios y los grupos.

.Antes de empezar
Debe haber ya el usuario o grupo local o de dominio del que se eliminarán los privilegios.

.Acerca de esta tarea
Al quitar privilegios de usuarios o grupos locales o de dominio, debe tener en cuenta lo siguiente:

* Puede eliminar uno o varios privilegios.
* Al eliminar privilegios de un usuario o grupo de dominio, ONTAP puede validar el usuario o grupo de dominio poniéndose en contacto con el controlador de dominio.
+
Es posible que se produzca un error en el comando si ONTAP no puede comunicarse con la controladora de dominio.



.Pasos
. Elimina uno o más privilegios de un usuario o grupo local o de dominio:
+
[source, cli]
----
vserver cifs users-and-groups privilege remove-privilege -vserver <SVM_name> -user-or-group-name <name> -privileges <privilege>[,...]
----
. Verifica que se hayan eliminado los privilegios deseados del objeto:
+
[source, cli]
----
vserver cifs users-and-groups privilege show -vserver <SVM_name> -user-or-group-name <name>
----


.Ejemplo
En el siguiente ejemplo se eliminan los privilegios «DeeTcbPrivilege» y «SeeTakeOwnershipPrivilege» del usuario «'CIFS_SERVER\sue» en la máquina virtual de almacenamiento (SVM, antes denominada Vserver) vs1:

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- ---------------
vs1       CIFS_SERVER\sue       SeTcbPrivilege
                                SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege remove-privilege -vserver vs1 -user-or-group-name CIFS_SERVER\sue -privileges SeTcbPrivilege,SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- -------------------
vs1       CIFS_SERVER\sue       -
----


[[reset-privileges-for-ontap-smb-local-or-domain-users-and-groups]]
== Restablecer privilegios para usuarios y grupos locales o de dominio de ONTAP SMB

Es posible restablecer privilegios para los grupos y usuarios locales o de dominio. Esto puede ser útil si ha realizado modificaciones a los privilegios de un usuario o grupo local o de dominio y esas modificaciones ya no se desean ni se necesitan.

.Acerca de esta tarea
Al restablecer los privilegios de un usuario o grupo local o de dominio, se quitan todas las entradas de privilegios de ese objeto.

.Pasos
. Restablece los privilegios de un usuario o grupo local o de dominio:
+
[source, cli]
----
vserver cifs users-and-groups privilege reset-privilege -vserver <SVM_name> -user-or-group-name <name>
----
. Verifica que se han restablecido los privilegios en el objeto:
+
[source, cli]
----
vserver cifs users-and-groups privilege show -vserver <SVM_name> -user-or-group-name <name>
----


.Ejemplos
En el siguiente ejemplo, se restablecen los privilegios para el usuario «'CIFS_SERVER\sue'» en la máquina virtual de almacenamiento (SVM, anteriormente conocida como Vserver) vs1. De forma predeterminada, los usuarios normales no tienen privilegios asociados a sus cuentas:

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show
Vserver   User or Group Name    Privileges
--------- --------------------- ---------------
vs1       CIFS_SERVER\sue       SeTcbPrivilege
                                SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege reset-privilege -vserver vs1 -user-or-group-name CIFS_SERVER\sue

cluster1::> vserver cifs users-and-groups privilege show
This table is currently empty.
----
En el ejemplo siguiente se restablecen los privilegios para el grupo "'BUILTIN\Administrators'", eliminando de forma efectiva la entrada de privilegios:

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show
Vserver   User or Group Name       Privileges
--------- ------------------------ -------------------
vs1       BUILTIN\Administrators   SeRestorePrivilege
                                   SeSecurityPrivilege
                                   SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege reset-privilege -vserver vs1 -user-or-group-name BUILTIN\Administrators

cluster1::> vserver cifs users-and-groups privilege show
This table is currently empty.
----


[[display-information-about-ontap-smb-privilege-overrides]]
== Mostrar información sobre las anulaciones de privilegios SMB de ONTAP

Puede mostrar información acerca de los privilegios personalizados asignados a cuentas o grupos de usuarios locales o de dominio. Esta información le ayuda a determinar si se aplican los derechos de usuario deseados.

.Paso
. Ejecute una de las siguientes acciones:
+
|===
| Si desea mostrar información acerca de... | Introduzca este comando... 


 a| 
Privilegios personalizados para todos los grupos y usuarios locales y de dominio en la máquina virtual de almacenamiento (SVM)
 a| 
`vserver cifs users-and-groups privilege show -vserver <SVM_name>`



 a| 
Privilegios personalizados para un dominio o un grupo y usuario local específicos de la SVM
 a| 
`vserver cifs users-and-groups privilege show -vserver <SVM_name> -user-or-group-name <name>`

|===
+
Hay otros parámetros opcionales que puede elegir cuando ejecuta este comando. Obtenga más información sobre `vserver cifs users-and-groups privilege show` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-users-and-groups-privilege-show.html["Referencia de comandos del ONTAP"^].



.Ejemplo
El siguiente comando muestra todos los privilegios asociados explícitamente con los usuarios y grupos locales o de dominio para SVM vs1:

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver    User or Group Name     Privileges
--------- ---------------------   ---------------
vs1       BUILTIN\Administrators  SeTakeOwnershipPrivilege
                                  SeRestorePrivilege
vs1       CIFS_SERVER\sue         SeTcbPrivilege
                                  SeTakeOwnershipPrivilege
----