---
permalink: smb-admin/map-administrators-group-root-task.html 
sidebar: sidebar 
keywords: cifs, client, environment, storage, virtual, machine, svm, multiprotocol, storage, system, windows, account, root, privilege, svm, sufficient, user, right, map the administrators group to root 
summary: 'Si solo tiene clientes CIFS en su entorno y su máquina virtual de almacenamiento (SVM) está configurada como un sistema de almacenamiento multiprotocolo, debe tener al menos una cuenta de Windows con privilegios raíz para acceder a los archivos en la SVM; De lo contrario, no puede gestionar la SVM porque no tiene suficientes derechos de usuario.' 
---
= Asigne los grupos de administrador a la raíz de SMB de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si solo tiene clientes CIFS en su entorno y su máquina virtual de almacenamiento (SVM) está configurada como un sistema de almacenamiento multiprotocolo, debe tener al menos una cuenta de Windows con privilegios raíz para acceder a los archivos en la SVM; De lo contrario, no puede gestionar la SVM porque no tiene suficientes derechos de usuario.

.Acerca de esta tarea
Si el sistema de almacenamiento se configuró como solo NTFS, `/etc` el directorio tiene una ACL en el nivel de archivos que permite que el grupo de administradores acceda a los archivos de configuración de ONTAP.

.Pasos
. Configure el nivel de privilegio en Advanced: `set -privilege advanced`
. Configure la opción del servidor CIFS que asigna el grupo de administradores a la raíz, según corresponda:
+
|===
| Si desea... | Realice lo siguiente... 


 a| 
Asigne los miembros del grupo de administradores a la raíz
 a| 
`vserver cifs options modify -vserver _vserver_name_ -is-admin-users-mapped-to-root-enabled true`     Todas las cuentas del grupo de administradores se consideran root, aunque no tenga `/etc/usermap.cfg` introduzca la asignación de las cuentas a root. Si crea un archivo utilizando una cuenta que pertenece al grupo de administradores, el archivo es propiedad de root cuando ve el archivo desde un cliente UNIX.



 a| 
Desactive la asignación de los miembros del grupo de administradores a la raíz
 a| 
`vserver cifs options modify -vserver _vserver_name_ -is-admin-users-mapped-to-root-enabled false`     Las cuentas del grupo de administradores ya no se asignan a la raíz. Sólo se puede asignar explícitamente un solo usuario a la raíz.

|===
. Compruebe que la opción está establecida en el valor deseado: `vserver cifs options show -vserver _vserver_name_`
. Vuelva al nivel de privilegio de administrador: `set -privilege admin`

