---
permalink: smb-admin/modify-dynamic-dns-domain-before-moving-server-task.html 
sidebar: sidebar 
keywords: active, directory-integrated, dns, server, dynamic, register, smb, server, record, modify, ddns, storage, virtual, machine, svm, modify the dynamic dns domain on the svm before moving the smb server 
summary: 'Si desea que el servidor DNS integrado en Active Directory registre dinámicamente los registros DNS del servidor SMB en DNS al mover el servidor SMB a otro dominio, debe modificar el DNS dinámico (DDNS) en la máquina virtual de almacenamiento (SVM) antes de mover el servidor SMB.' 
---
= Modifique el dominio DNS dinámico en la SVM antes de mover el servidor SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea que el servidor DNS integrado en Active Directory registre de forma dinámica los registros DNS del servidor SMB en DNS cuando mueve el servidor SMB a otro dominio, debe modificar el DNS dinámico (DDNS) en la máquina virtual de almacenamiento (SVM) antes de mover el servidor SMB.

.Antes de empezar
Los servicios de nombres DNS se deben modificar en la SVM para utilizar el dominio DNS que contiene los registros de ubicación del servicio para el nuevo dominio que contendrá la cuenta de equipo del servidor SMB. Si utiliza DDNS seguro, debe utilizar servidores de nombres DNS integrados en Active Directory.

.Acerca de esta tarea
Si bien DDNS (si se configura en la SVM) agrega automáticamente los registros DNS de las LIF de datos al dominio nuevo, los registros DNS del dominio original no se eliminan automáticamente del servidor DNS original. Debe eliminarlos manualmente.

Para completar las modificaciones de DDNS antes de mover el servidor SMB, consulte el siguiente tema:

https://docs.netapp.com/us-en/ontap/networking/configure_dynamic_dns_services.html["Configure los servicios DNS dinámicos"]
