---
permalink: smb-admin/monitor-security-policy-job-task.html 
sidebar: sidebar 
keywords: apply, security, policy, storage, virtual, machine, svm, monitor, progress, policy, job, ascertain, application, long-running, bulk, security, file, folder, monitor the security policy job 
summary: 'Al aplicar la política de seguridad a máquinas virtuales de almacenamiento (SVM), puede supervisar el progreso de la tarea supervisando el trabajo de la política de seguridad. Esto es útil si desea comprobar que la aplicación de la política de seguridad ha sido satisfactoria. Esto también resulta útil si tiene un trabajo de larga ejecución en el que está aplicando seguridad masiva a un gran número de archivos y carpetas.' 
---
= Supervise el trabajo de política de seguridad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al aplicar la política de seguridad a máquinas virtuales de almacenamiento (SVM), puede supervisar el progreso de la tarea supervisando el trabajo de la política de seguridad. Esto es útil si desea comprobar que la aplicación de la política de seguridad ha sido satisfactoria. Esto también resulta útil si tiene un trabajo de larga ejecución en el que está aplicando seguridad masiva a un gran número de archivos y carpetas.

.Acerca de esta tarea
Para mostrar información detallada sobre un trabajo de política de seguridad, debe usar `-instance` parámetro.

.Paso
. Supervise el trabajo de la política de seguridad: `vserver security file-directory job show -vserver vserver_name`
+
`vserver security file-directory job show -vserver vs1`

+
[listing]
----

Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
53322  Fsecurity Apply      vs1        node1          Success
       Description: File Directory Security Apply Job
----

