---
permalink: smb-admin/monitor-display-ipv6-sessions-task.html 
sidebar: sidebar 
keywords: monitor, display, information, smb, session, ipv6, determining, determine, monitor and display information about ipv6 smb sessions 
summary: Puede supervisar y mostrar información sobre las sesiones SMB conectadas mediante redes IPv6. Esta información es útil para determinar qué clientes se conectan mediante IPv6, así como otra información útil sobre las sesiones SMB de IPv6. 
---
= Supervisar y mostrar información acerca de las sesiones SMB de IPv6
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede supervisar y mostrar información sobre las sesiones SMB conectadas mediante redes IPv6. Esta información es útil para determinar qué clientes se conectan mediante IPv6, así como otra información útil sobre las sesiones SMB de IPv6.

.Paso
. Realice la acción deseada:
+
|===
| Si desea determinar si... | Introduzca el comando... 


 a| 
Las sesiones SMB a una máquina virtual de almacenamiento (SVM) se conectan mediante IPv6
 a| 
`vserver cifs session show -vserver _vserver_name_ -instance`



 a| 
IPv6 se utiliza para sesiones SMB a través de una dirección LIF especificada
 a| 
`vserver cifs session show -vserver _vserver_name_ -lif-address _LIF_IP_address_ -instance`

`_LIF_IP_address_` Es la dirección IPv6 de la LIF de datos.

|===

