---
permalink: smb-admin/network-protocol-support-requirements-concept.html 
sidebar: sidebar 
keywords: network, protocol, requirement, implement, ontap, branchcache, support, network protocol support requirement 
summary: Debe tener en cuenta los requisitos del protocolo de red para implementar BranchCache de ONTAP. 
---
= Requisitos de compatibilidad de protocolos de red
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe tener en cuenta los requisitos del protocolo de red para implementar BranchCache de ONTAP.

Puede implementar la función ONTAP BranchCache en redes IPv4 e IPv6 mediante SMB 2.1 o una versión posterior.

Todos los servidores CIFS y los equipos de oficinas remotas que participan en la implementación de BranchCache deben tener habilitado el protocolo SMB 2.1 o una versión posterior. SMB 2.1 tiene extensiones de protocolo que permiten que un cliente participe en un entorno de BranchCache. Esta es la versión mínima del protocolo SMB que ofrece compatibilidad con BranchCache. SMB 2.1 admite la versión de BranchCache, versión 1.

Si desea usar BranchCache versión 2, SMB 3.0 es la versión mínima admitida. Todos los servidores CIFS y los equipos de oficinas remotas que participan en una implementación de BranchCache 2 deben tener habilitado SMB 3.0 o una versión posterior.

Si tiene oficinas remotas en las que algunos clientes solo admiten SMB 2.1 y algunos de los clientes admiten SMB 3.0, puede implementar una configuración de BranchCache en el servidor CIFS que proporcione compatibilidad con el almacenamiento en caché tanto en BranchCache 1 como en BranchCache 2.

[NOTE]
====
Aunque la función Microsoft BranchCache admite el uso de los protocolos HTTP/HTTPS y SMB como protocolos de acceso a archivos, ONTAP BranchCache solo admite el uso de SMB.

====