---
permalink: smb-admin/offline-files-allow-caching-concept.html 
sidebar: sidebar 
keywords: ontap, support, microsoft, offline, file, feature, client-side, caching, cache, file, local, host, offline, disconnect, network, use offline files to allow caching of files for offline use 
summary: ONTAP admite la función Microsoft Offline Files, o el almacenamiento en caché en el cliente, que permite el almacenamiento en caché de los archivos en el host local para su uso sin conexión. Los usuarios pueden utilizar la funcionalidad de archivos sin conexión para seguir trabajando en archivos incluso cuando están desconectados de la red. 
---
= Obtenga información sobre el uso de archivos sin conexión para permitir el almacenamiento en caché de archivos SMB de ONTAP para su uso sin conexión
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP es compatible con la característica Archivos sin conexión de Microsoft, o con la función de almacenamiento en caché del cliente_, que permite almacenar los archivos en caché en el host local para su uso sin conexión. Los usuarios pueden utilizar la funcionalidad de archivos sin conexión para seguir trabajando en archivos incluso cuando están desconectados de la red.

Puede especificar si los documentos y programas de usuario de Windows se almacenan automáticamente en caché en un recurso compartido o si los archivos deben seleccionarse manualmente para almacenar en caché. El almacenamiento en caché manual está habilitado de forma predeterminada para nuevos recursos compartidos. Los archivos que están disponibles sin conexión se sincronizan con el disco local del cliente de Windows. La sincronización se produce cuando se restaura la conectividad de red a un recurso compartido de sistema de almacenamiento específico.

Puesto que los archivos y carpetas sin conexión conservan los mismos permisos de acceso que la versión de los archivos y carpetas guardados en el servidor CIFS, el usuario debe tener suficientes permisos en los archivos y carpetas guardados en el servidor CIFS para realizar acciones en los archivos y carpetas sin conexión.

Cuando el usuario y otra persona de la red realizan cambios en el mismo archivo, el usuario puede guardar la versión local del archivo en la red, conservar la otra versión o guardar ambas. Si el usuario conserva ambas versiones, se guarda localmente un nuevo archivo con los cambios del usuario local y el archivo almacenado en caché se sobrescribe con cambios de la versión del archivo guardado en el servidor CIFS.

Puede configurar archivos sin conexión de forma compartida mediante las opciones de configuración de recursos compartidos. Puede elegir una de las cuatro configuraciones de carpetas sin conexión al crear o modificar recursos compartidos:

* Sin almacenamiento en caché
+
Deshabilita el almacenamiento en caché en el cliente para el recurso compartido. Los archivos y carpetas no se almacenan automáticamente en caché local en clientes y los usuarios no pueden optar por almacenar en caché archivos o carpetas localmente.

* Almacenamiento en caché manual
+
Permite la selección manual de archivos para almacenar en caché en el recurso compartido. Esta es la configuración predeterminada. De forma predeterminada, no se almacenan en caché archivos ni carpetas en el cliente local. Los usuarios pueden elegir los archivos y carpetas que desean almacenar en caché localmente para utilizarlos sin conexión.

* Almacenamiento automático de documentos en caché
+
Permite que los documentos de usuario se almacenen automáticamente en caché en el recurso compartido. Sólo los archivos y carpetas a los que se tiene acceso se almacenan en caché localmente.

* Almacenamiento automático de programas en caché
+
Permite que los programas y los documentos de usuario se almacenen automáticamente en caché en el recurso compartido. Sólo los archivos, carpetas y programas a los que se tiene acceso se almacenan en caché localmente. Además, esta configuración permite al cliente ejecutar ejecutables almacenados localmente en caché incluso cuando se conecta a la red.



Para obtener más información acerca de la configuración de archivos sin conexión en servidores y clientes de Windows, consulte la biblioteca de Microsoft TechNet.

.Información relacionada
* xref:roaming-profiles-store-user-profiles-concept.adoc[Uso de perfiles de itinerancia para almacenar perfiles de usuario de forma centralizada en un servidor CIFS asociado con la SVM]
* xref:folder-redirection-store-data-concept.adoc[Aprenda a utilizar la redirección de carpetas para almacenar datos en servidores]
* xref:branchcache-cache-share-content-branch-office-concept.adoc[Obtenga información sobre cómo usar BranchCache para almacenar en caché contenido compartido en una sucursal]
* http://technet.microsoft.com/en-us/library/["Biblioteca de Microsoft TechNet: technet.microsoft.com/en-us/library/"]

