---
permalink: smb-admin/previous-versions-view-manage-snapshot-data-task.html 
sidebar: sidebar 
keywords: windows, client, machine, previous, version, tab, properties, restore, data, store, snapshot, copies, copy, storage, virtual, machine, svm, administrator, use the previous versions tab to view and manage snapshot copy data 
summary: 'Los usuarios de equipos cliente Windows pueden usar la pestaña versiones anteriores de la ventana Propiedades de Windows para restaurar los datos almacenados en copias Snapshot sin necesidad de implicar al administrador de máquinas virtuales de almacenamiento (SVM).' 
---
= Utilice la pestaña versiones anteriores para ver y gestionar datos de copias snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los usuarios de equipos cliente Windows pueden usar la pestaña versiones anteriores de la ventana Propiedades de Windows para restaurar los datos almacenados en copias Snapshot sin necesidad de implicar al administrador de máquinas virtuales de almacenamiento (SVM).

.Acerca de esta tarea
Solo puede usar la pestaña versiones anteriores para ver y gestionar los datos de las copias Snapshot de los datos almacenados en la SVM si el administrador ha habilitado copias Snapshot en el volumen que contiene el recurso compartido y si el administrador configura el recurso compartido para mostrar copias Snapshot.

.Pasos
. En el Explorador de Windows, muestre el contenido de la unidad asignada de los datos almacenados en el servidor CIFS.
. Haga clic con el botón derecho del ratón en el archivo o carpeta de la unidad de red asignada cuyas copias Snapshot desee ver o administrar.
. Haga clic en *Propiedades*.
+
Se muestran las propiedades del archivo o carpeta seleccionado.

. Haga clic en la ficha *versiones anteriores*.
+
En el cuadro versiones de carpeta se muestra una lista de las copias Snapshot disponibles del archivo o carpeta seleccionados. Las copias Snapshot mostradas se identifican mediante el prefijo del nombre de la copia Snapshot y la Marca de hora de creación.

. En el cuadro *versiones de carpeta:*, haga clic con el botón secundario del mouse (ratón) en la copia del archivo o carpeta que desee administrar.
. Ejecute la acción adecuada:
+
|===
| Si desea... | Haga lo siguiente... 


 a| 
Vea los datos de esa copia Snapshot
 a| 
Haga clic en *Abrir*.



 a| 
Cree una copia de los datos a partir de esa copia Snapshot
 a| 
Haga clic en *Copiar*.

|===
+
Los datos de las copias Snapshot son de solo lectura. Si desea realizar modificaciones en los archivos y carpetas enumerados en la ficha versiones anteriores, debe guardar una copia de los archivos y carpetas que desea modificar en una ubicación editable y realizar modificaciones en las copias.

. Después de terminar de administrar los datos de instantánea, cierre el cuadro de diálogo *Propiedades* haciendo clic en *Aceptar*.
+
Para obtener más información acerca de cómo utilizar la ficha versiones anteriores para ver y administrar datos de instantánea, consulte la biblioteca de Microsoft TechNet.



.Información relacionada
http://["Biblioteca de Microsoft TechNet: technet.microsoft.com/en-us/library/"]
