---
permalink: smb-admin/previous-versions-view-manage-snapshot-data-task.html 
sidebar: sidebar 
keywords: windows, client, machine, previous, version, tab, properties, restore, data, store, snapshot, copies, copy, storage, virtual, machine, svm, administrator, use the previous versions tab to view and manage snapshot copy data 
summary: 'Los usuarios de máquinas cliente Windows pueden usar la pestaña Versiones anteriores de la ventana Propiedades de Windows para restaurar los datos almacenados en snapshots sin necesidad de involucrar al administrador de máquinas virtuales de almacenamiento (SVM).' 
---
= Vea y administre datos de instantáneas de ONTAP SMB con la pestaña Versiones anteriores de Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los usuarios de máquinas cliente Windows pueden usar la pestaña Versiones anteriores de la ventana Propiedades de Windows para restaurar los datos almacenados en snapshots sin necesidad de involucrar al administrador de máquinas virtuales de almacenamiento (SVM).

.Acerca de esta tarea
Solo puede utilizar la pestaña Versiones anteriores para ver y gestionar datos en instantáneas de datos almacenados en la SVM si el administrador ha habilitado snapshots en el volumen que contiene el recurso compartido y si el administrador configura el recurso compartido para mostrar las snapshots.

.Pasos
. En el Explorador de Windows, muestre el contenido de la unidad asignada de los datos almacenados en el servidor CIFS.
. Haga clic con el botón derecho en el archivo o carpeta de la unidad de red asignada cuyas instantáneas desea ver o gestionar.
. Haga clic en *Propiedades*.
+
Se muestran las propiedades del archivo o carpeta seleccionado.

. Haga clic en la ficha *versiones anteriores*.
+
En el cuadro Versiones de carpeta se muestra una lista de instantáneas disponibles del archivo o carpeta seleccionado. Las copias de Snapshot enumeradas se identifican con el prefijo del nombre de la snapshot y la fecha/hora de creación.

. En el cuadro *versiones de carpeta:*, haga clic con el botón secundario del mouse (ratón) en la copia del archivo o carpeta que desee administrar.
. Ejecute la acción adecuada:
+
|===
| Si desea... | Haga lo siguiente... 


 a| 
Ver datos de esa instantánea
 a| 
Haga clic en *Abrir*.



 a| 
Cree una copia de datos a partir de esa instantánea
 a| 
Haga clic en *Copiar*.

|===
+
Los datos de las copias Snapshot son de solo lectura. Si desea realizar modificaciones en los archivos y carpetas enumerados en la ficha versiones anteriores, debe guardar una copia de los archivos y carpetas que desea modificar en una ubicación editable y realizar modificaciones en las copias.

. Cuando termine de administrar los datos de las instantáneas, cierre el cuadro de diálogo *Propiedades* haciendo clic en *Aceptar*.
+
Para obtener más información sobre el uso de la pestaña Versiones anteriores para ver y administrar datos de instantáneas, consulte la biblioteca de Microsoft TechNet.



.Información relacionada
http://technet.microsoft.com/en-us/library/["Biblioteca de Microsoft TechNet: technet.microsoft.com/en-us/library/"]
