---
permalink: smb-admin/provide-security-access-based-enumeration-task.html 
sidebar: sidebar 
keywords: access-based, enumeration, abe, enable, smb, share, user, folder, file, contain, within, share, individual, permission, restriction, resource, environment, provide folder security on shares with access-based enumeration 
summary: 'Cuando se habilita la enumeración basada en acceso (ABE) en un recurso compartido SMB, los usuarios que no tienen permiso para acceder a una carpeta o archivo contenido en el recurso compartido (ya sea mediante restricciones de permisos individuales o de grupo) no ven ese recurso compartido que se muestra en su entorno.' 
---
= Proporcionar seguridad de carpetas SMB de ONTAP en recursos compartidos con enumeración basada en acceso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se habilita la enumeración basada en acceso (ABE) en un recurso compartido SMB, los usuarios que no tienen permiso para acceder a una carpeta o archivo contenido en el recurso compartido (ya sea mediante restricciones de permisos individuales o de grupo) no ven el recurso compartido que se muestra en su entorno, aunque el recurso compartido en sí sigue siendo visible.

Las propiedades de uso compartido convencionales permiten especificar qué usuarios (individualmente o en grupos) tienen permiso para ver o modificar archivos o carpetas contenidos en el recurso compartido. Sin embargo, no le permiten controlar si las carpetas o archivos dentro del recurso compartido son visibles para los usuarios que no tienen permiso para tener acceso a ellos. Esto podría plantear problemas si los nombres de estas carpetas o archivos del recurso compartido describen información confidencial, como los nombres de los clientes o los productos en desarrollo.

La enumeración basada en acceso (ABE) amplía las propiedades de recursos compartidos para incluir la enumeración de archivos y carpetas dentro del recurso compartido. POR tanto, ABE permite filtrar la visualización de archivos y carpetas dentro del recurso compartido en función de los derechos de acceso del usuario. Es decir, el recurso compartido en sí sería visible para todos los usuarios, pero los archivos y carpetas dentro del recurso compartido podrían mostrarse u ocultarse de los usuarios designados. Además de proteger la información confidencial en su lugar de trabajo, ABE le permite simplificar la presentación de grandes estructuras de directorio en beneficio de los usuarios que no necesitan acceso a su gama completa de contenido. Por ejemplo, el recurso compartido en sí sería visible para todos los usuarios, pero los archivos y carpetas dentro del recurso compartido podrían mostrarse u ocultarse.

Obtenga más información link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Performance_impact_when_using_CIFS_Access_Based_Enumeration["Impacto sobre el rendimiento al utilizar la enumeración basada en SMB/CIFS Access"^]sobre .
