---
permalink: smb-admin/reasons-invalidates-branchcache-hashes-concept.html 
sidebar: sidebar 
keywords: understand, ontap, invalidate, hash, branchcache, configuration, share, reasons ontap invalidates branchcache hashes 
summary: Comprender los motivos por los que ONTAP invalida los hash puede ser útil a la hora de planificar la configuración de BranchCache. Puede ayudarle a decidir el modo operativo que debe configurar y a elegir en qué recursos compartidos desea habilitar BranchCache. 
---
= Razones por las que ONTAP invalida los hash de BranchCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Comprender los motivos por los que ONTAP invalida los hash puede ser útil a la hora de planificar la configuración de BranchCache. Puede ayudarle a decidir el modo operativo que debe configurar y a elegir en qué recursos compartidos desea habilitar BranchCache.

ONTAP debe gestionar los hash de BranchCache para garantizar que sean válidos. Si un hash no es válido, ONTAP invalida el hash y calcula un nuevo hash la próxima vez que se solicite el contenido, suponiendo que BranchCache siga estando habilitado.

ONTAP invalida los hash por los siguientes motivos:

* Se modifica la clave de servidor.
+
Si se modifica la clave del servidor, ONTAP invalida todos los hash del almacén hash.

* Un hash se vacía de la caché porque se alcanzó el tamaño máximo del almacén hash de BranchCache.
+
Se trata de un parámetro ajustable y puede modificarse para satisfacer sus requisitos empresariales.

* Un archivo se modifica mediante un acceso SMB o NFS.
* Un archivo para el que hay hash calculados se restaura con `snap restore` el comando.
* Un volumen que contiene recursos compartidos de SMB que tienen habilitada para BranchCache se restaura mediante `snap restore` el comando.

