---
permalink: smb-admin/recommendations-configure-signing-concept.html 
sidebar: sidebar 
keywords: configure, smb, sign, behavior, client, cifs, security, requirement, setting, configuring, configure, security, recommendations for configuring smb signing 
summary: Puede configurar un comportamiento de firma SMB entre clientes SMB y el servidor CIFS para satisfacer sus requisitos de seguridad. La configuración que elija al configurar la firma SMB en el servidor CIFS depende de cuáles sean sus requisitos de seguridad. 
---
= Recomendaciones de configuración de firma SMB de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar un comportamiento de firma SMB entre clientes SMB y el servidor CIFS para satisfacer sus requisitos de seguridad. La configuración que elija al configurar la firma SMB en el servidor CIFS depende de cuáles sean sus requisitos de seguridad.

Es posible configurar la firma SMB en el cliente o en el servidor CIFS. Tenga en cuenta las siguientes recomendaciones al configurar la firma SMB:

|===
| Si... | Recomendación... 


 a| 
Desea aumentar la seguridad de la comunicación entre el cliente y el servidor
 a| 
Haga que se requiera la firma SMB en el cliente al habilitar el `Require Option (Sign always)` configuración de seguridad en el cliente.



 a| 
Es conveniente que todo el tráfico de SMB esté firmado a una determinada máquina virtual de almacenamiento (SVM)
 a| 
Para requerir la firma SMB en el servidor CIFS, configure la configuración de seguridad para requerir la firma SMB.

|===
Consulte la documentación de Microsoft para obtener más información acerca de la configuración de la seguridad del cliente de Windows.
