---
permalink: smb-admin/requirements-ipv6-concept.html 
sidebar: sidebar 
keywords: ipv6, smb, cifs, server, version, ontap, smb, support, license, requirement, requirements for using ipv6 
summary: Antes de poder utilizar IPv6 en el servidor SMB, debe saber qué versiones de ONTAP y SMB admiten y cuáles son los requisitos de licencia. 
---
= Obtenga más información sobre los requisitos del bloque de mensajes del servidor de ONTAP para IPv6
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de poder utilizar IPv6 en el servidor SMB, debe saber qué versiones de ONTAP y SMB admiten y cuáles son los requisitos de licencia.



== Requisitos para la licencia de ONTAP

No se requiere ninguna licencia especial para IPv6 cuando SMB tiene licencia. La licencia SMB se incluye con link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"]. Si no tiene ONTAP One y la licencia no está instalada, póngase en contacto con su representante de ventas.



== Requisitos de la versión del protocolo SMB

* Para las SVM, ONTAP es compatible con IPv6 en todas las versiones del protocolo SMB.


[NOTE]
====
No se admite el servicio de nombres NetBIOS (NBNS) sobre IPv6.

====