---
permalink: smb-admin/requirements-microsoft-previous-versions-concept.html 
sidebar: sidebar 
keywords: version, cifs, server, ontap, smb, windows, client, support, snapshot, setting, requirement 
summary: Antes de poder utilizar las versiones anteriores con el servidor CIFS, debe conocer qué versiones de ONTAP y SMB, y qué clientes de Windows, admiten. También debe conocer el requisito de configuración de la snapshot. 
---
= Requisitos para usar versiones anteriores de Microsoft
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de poder utilizar las versiones anteriores con el servidor CIFS, debe conocer qué versiones de ONTAP y SMB, y qué clientes de Windows, admiten. También debe conocer el requisito de configuración de la snapshot.



== Requisitos de la versión de ONTAP

Admite versiones anteriores.



== Requisitos de la versión del protocolo SMB

Para las máquinas virtuales de almacenamiento (SVM), ONTAP admite las versiones anteriores de todas las versiones de SMB.



== Requisitos del cliente Windows

Para que un usuario pueda utilizar versiones anteriores para acceder a los datos en instantáneas, el cliente Windows debe admitir la función.

Para obtener la información más reciente sobre los clientes de Windows compatibles con versiones anteriores, consulte matriz de interoperabilidad.

https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^]



== Requisitos para la configuración de Snapshot

Para usar versiones anteriores para acceder a los datos de las snapshots, se debe asociar una política Snapshot habilitada al volumen que contiene los datos, los clientes deben poder acceder a los datos de las snapshots y deben existir snapshots.
