---
permalink: smb-admin/reset-rediscover-trusted-domains-task.html 
sidebar: sidebar 
keywords: force, rediscover, trust, domain, relationship, bidirectional, trust, home, cifs, server, computer, account, reset and rediscover trusted domains 
summary: Puede forzar la redetección de todos los dominios de confianza. Esto puede ser útil cuando los servidores de dominio de confianza no responden adecuadamente o las relaciones de confianza han cambiado. Sólo se detectan los dominios con una confianza bidireccional con el dominio principal, que es el dominio que contiene la cuenta de equipo del servidor CIFS. 
---
= Restablece y vuelve a detectar dominios SMB de ONTAP de confianza
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede forzar la redetección de todos los dominios de confianza. Esto puede ser útil cuando los servidores de dominio de confianza no responden adecuadamente o las relaciones de confianza han cambiado. Solo se detectan los dominios con una confianza bidireccional con el dominio principal, que es el dominio que contiene la cuenta de equipo del servidor CIFS.

A partir de ONTAP 9.13.1, cuando ONTAP vuelve a detectar dominios de confianza, también realiza la detección de sitios para esos dominios de confianza. ONTAP utiliza la información del sitio detectada para las búsquedas de controladores de dominio de los dominios de confianza. Esto ayuda a garantizar que las búsquedas DNS SRV utilicen la información de sitio correcta para los controladores de dominio de los dominios de confianza. Si falla la detección de sitios para un dominio de confianza, ONTAP utiliza el sitio predeterminado del servidor SMB.

.Paso
. Restablezca y vuelva a detectar dominios de confianza mediante el `vserver cifs domain trusts rediscover` comando.
+
`vserver cifs domain trusts rediscover -vserver vs1`



.Información relacionada
xref:display-discovered-trusted-domains-task.adoc[Muestra información sobre los dominios de confianza detectados]
