---
permalink: smb-admin/revert-dynamic-access-control-concept.html 
sidebar: sidebar 
keywords: aware, revert, version, ontap, support, dynamic, access, control, dac, revert considerations for dynamic access control 
summary: 'Debe ser consciente de lo que sucede al volver a una versión de ONTAP que no admite el control de acceso dinámico (DAC) y lo que debe hacer antes y después de revertir.' 
---
= Consideraciones de reversión para el control de acceso dinámico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe ser consciente de lo que sucede al volver a una versión de ONTAP que no admite el control de acceso dinámico (DAC) y lo que debe hacer antes y después de revertir.

Si desea revertir el clúster a una versión de ONTAP que no admite el control de acceso dinámico y que el control de acceso dinámico está habilitado en una o varias máquinas virtuales de almacenamiento (SVM), debe hacer lo siguiente antes de revertir:

* Debe deshabilitar el control de acceso dinámico en todas las SVM que tengan habilitado en el clúster.
* Debe modificar cualquier configuración de auditoría del clúster que contenga el `cap-staging` tipo de evento para utilizar únicamente la `file-op` tipo de evento.


Debe comprender y actuar sobre algunas consideraciones importantes de reversión para archivos y carpetas con los ACE de control de acceso dinámico:

* Si se revierte el clúster, los ACE existentes de Dynamic Access Control no se eliminan; sin embargo, se ignorarán en las comprobaciones de acceso a archivos.
* Dado que los ACE de control de acceso dinámico se ignoran después de la nueva versión, el acceso a los archivos cambiará en archivos con ACE de control de acceso dinámico.
+
Esto podría permitir a los usuarios acceder a los archivos que no podían obtener anteriormente o no tener acceso a los que podían acceder anteriormente.

* Debería aplicar ACE de control de acceso no dinámico a los archivos afectados para restaurar su nivel anterior de seguridad.
+
Esto puede hacerse antes de revertir o inmediatamente después de que finaliza la reversión.



[NOTE]
====
Puesto que los ACE de control dinámico de acceso se ignoran después de volver a verlos, no es necesario eliminarlos cuando se aplican los ACE de control de acceso no dinámico a los archivos afectados. Sin embargo, si lo desea, puede eliminarlos manualmente.

====