---
permalink: smb-admin/signing-multiple-data-lifs-concept.html 
sidebar: sidebar 
keywords: enable, disable, require, smb, sign, server, guideline, lifs, configuration, svm, guidelines for smb signing when multiple data lifs are configured 
summary: Si habilita o deshabilita la firma SMB requerida en el servidor SMB, debe tener en cuenta las directrices para varias configuraciones de LIF de datos para una SVM. 
---
= Obtenga información sobre la configuración de firma SMB de ONTAP para varias LIFS de datos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si habilita o deshabilita la firma SMB requerida en el servidor SMB, debe tener en cuenta las directrices para varias configuraciones de LIF de datos para una SVM.

Cuando configura un servidor SMB, puede haber varios LIF de datos configurados. Si es así, el servidor DNS contiene varias `A` entradas de registro para el servidor CIFS, todos utilizando el mismo nombre de host del servidor SMB, pero cada uno con una dirección IP exclusiva. Por ejemplo, un servidor SMB que tiene dos LIF de datos configuradas puede tener las siguientes `A` entradas de registro DNS:

[listing]
----
10.1.1.128 A VS1.IEPUB.LOCAL VS1
10.1.1.129 A VS1.IEPUB.LOCAL VS1
----
El comportamiento normal es que, al cambiar la configuración de firma SMB necesaria, solo las nuevas conexiones de clientes se ven afectadas por el cambio en la configuración de firma SMB. Sin embargo, hay una excepción a este comportamiento. Existe un caso en el que un cliente tiene una conexión existente con un recurso compartido y éste crea una nueva conexión con el mismo recurso compartido después de cambiar la configuración, manteniendo la conexión original. En este caso, tanto la conexión SMB nueva como la existente adoptan los nuevos requisitos de firma SMB.

Observe el siguiente ejemplo:

. CLIENT1 se conecta a un recurso compartido sin necesidad de firma SMB mediante la ruta de acceso `O:\`.
. El administrador de almacenamiento modifica la configuración del servidor SMB para requerir la firma SMB.
. CLIENT1 se conecta al mismo recurso compartido con la firma SMB necesaria mediante la ruta de acceso `S:\` (manteniendo la conexión mediante la ruta `O:\`).
. El resultado es que se utiliza la firma SMB cuando se accede a los datos `O:\` en `S:\` las unidades y.

