---
permalink: smb-admin/static-home-directory-share-names-upgrading-concept.html 
sidebar: sidebar 
keywords: static, home, directory, share, names, upgrading, upgrade 
summary: 'Los nombres de recursos compartidos del directorio inicial deben contener la variable dinámica %w o %u. Debe saber qué ocurre con los nombres de recursos compartidos de directorios iniciales estáticos existentes después de actualizar a una versión de ONTAP con el nuevo requisito.' 
---
= Obtenga información sobre qué sucede con los nombres de recursos compartidos del directorio de inicio SMB de ONTAP estático después de la actualización
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los nombres compartidos del directorio inicial deben contener `%w` `%u` la variable dinámica o la variable dinámica. Debe saber qué ocurre con los nombres de recursos compartidos de directorios iniciales estáticos existentes después de actualizar a una versión de ONTAP con el nuevo requisito.

Si la configuración del directorio raíz contiene nombres de recursos compartidos estáticos y se actualiza a ONTAP, los nombres de recursos compartidos de directorio raíz estáticos no se modifican y siguen siendo válidos. Sin embargo, no puede crear ningún recurso compartido nuevo del directorio inicial que no contenga `%w` `%u` la variable o.

Al requerir que se incluya una de estas variables en el nombre del recurso compartido del directorio principal del usuario se garantiza que cada nombre de recurso compartido sea único en la configuración del directorio principal. Si lo desea, puede cambiar los nombres compartidos del directorio principal estático por nombres que contengan la `%w` `%u` variable o.
