---
permalink: smb-admin/storage-system-provides-null-session-access-concept.html 
sidebar: sidebar 
keywords: null, session, share, require, authentication, client, ip, address, map, storage, system, how the storage system provides null session access 
summary: Debido a que los recursos compartidos de sesión nulos no requieren autenticación, los clientes que requieren acceso de sesión nulo deben tener sus direcciones IP asignadas en el sistema de almacenamiento. 
---
= Cómo el sistema de almacenamiento proporciona acceso nulo a una sesión
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debido a que los recursos compartidos de sesión nulos no requieren autenticación, los clientes que requieren acceso de sesión nulo deben tener sus direcciones IP asignadas en el sistema de almacenamiento.

De forma predeterminada, los clientes de sesión nula sin asignar pueden acceder a determinados servicios del sistema ONTAP, como la enumeración de recursos compartidos, pero se limitan a acceder a cualquier dato del sistema de almacenamiento.

[NOTE]
====
ONTAP admite los valores de configuración del Registro RestrictAnónimo de Windows con `–restrict-anonymous` opción. Esto permite controlar hasta qué punto los usuarios nulos no asignados pueden ver o acceder a los recursos del sistema. Por ejemplo, puede deshabilitar la enumeración de recursos compartidos y el acceso al recurso compartido IPC$ (recurso compartido de canalizaciones con nombre oculto). La `vserver cifs options modify` y.. `vserver cifs options show` las páginas de manual proporcionan más información sobre el `–restrict-anonymous` opción.

====
A menos que se configure lo contrario, un cliente que ejecute un proceso local que solicite acceso al sistema de almacenamiento a través de una sesión nula sólo es miembro de grupos no restrictivos, como «'todos'». Para limitar el acceso de sesión nulo a los recursos del sistema de almacenamiento seleccionados, es posible que desee crear un grupo al que pertenecen todos los clientes de sesión nulos; al crear este grupo se le permite restringir el acceso al sistema de almacenamiento y establecer permisos de recursos del sistema de almacenamiento que se aplican específicamente a clientes de sesión nulos.

ONTAP proporciona una sintaxis de asignación en `vserver name-mapping` El conjunto de comandos permite especificar la dirección IP de los clientes que pueden acceder a los recursos del sistema de almacenamiento mediante una sesión de usuario nula. Después de crear un grupo para usuarios nulos, puede especificar restricciones de acceso para los recursos del sistema de almacenamiento y permisos de recursos que se apliquen solo a sesiones nulas. El usuario nulo se identifica como inicio de sesión anónimo. Los usuarios nulos no tienen acceso a ningún directorio principal.

Todos los usuarios nulos que acceden al sistema de almacenamiento desde una dirección IP asignada se conceden permisos de usuario asignado. Considere las precauciones adecuadas para evitar el acceso no autorizado a sistemas de almacenamiento asignados con usuarios nulos. Para obtener la máxima protección, coloque el sistema de almacenamiento y todos los clientes que necesiten un acceso nulo al sistema de almacenamiento de usuarios en una red independiente, con el fin de eliminar la posibilidad de que se produzca una dirección IP «posing».

.Información relacionada
xref:configure-access-restrictions-anonymous-users-task.adoc[Configuración de restricciones de acceso para usuarios anónimos]
