---
permalink: smb-admin/supported-versions-functionality-concept.html 
sidebar: sidebar 
keywords: server, message, block, smb, remote, file-sharing, protocol, microsoft, windows, client, server, ontap, functionality, environment, supported smb versions and functionality 
summary: 'Server Message Block (SMB) es un protocolo de uso compartido de archivos remoto que utilizan los servidores y clientes de Microsoft Windows. Todas las versiones de SMB son compatibles. Debe verificar que el servidor SMB de ONTAP admite los clientes y la funcionalidad que se requieren en su entorno.' 
---
= Funcionalidades y versiones de SMB compatibles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Server Message Block (SMB) es un protocolo de uso compartido de archivos remoto que utilizan los servidores y clientes de Microsoft Windows. Todas las versiones de SMB son compatibles. Debe verificar que el servidor SMB de ONTAP admite los clientes y la funcionalidad que se requieren en su entorno.

La información más reciente sobre los clientes SMB y los controladores de dominio compatibles con ONTAP está disponible en _Interoperability Matrix Tool_.

SMB 2,0 y las versiones posteriores se habilitan de forma predeterminada para los servidores SMB de ONTAP, y se pueden habilitar o deshabilitar según sea necesario. SMB 1,0 puede habilitarse o deshabilitarse según sea necesario.

|===
| Funcionalidad de SMB 1.0: 4+| En estas versiones de ONTAP 9: 


 a| 
 a| 
9,0
 a| 
9,1
 a| 
9,2
 a| 
9,3 y posterior



 a| 
Está habilitado de forma predeterminada
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
No



 a| 
Se puede habilitar o deshabilitar
 a| 
No
 a| 
Sí*9.1 P8 o posterior requerido.
 a| 
Sí
 a| 
Sí

|===
[NOTE]
====
La configuración predeterminada de las conexiones SMB 1.0 y 2.0 con controladoras de dominio también depende de la versión ONTAP. Obtenga más información sobre `vserver cifs security modify` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-security-modify.html["Referencia de comandos de la ONTAP"^]. En el caso de entornos con servidores CIFS existentes que ejecuten SMB 1.0, debe migrar a una versión Lo antes posible. de SMB posterior con el fin de prepararse para las mejoras de seguridad y cumplimiento de normativas. Si quiere más información, póngase en contacto con su representante de NetApp.

====
La siguiente tabla muestra qué funciones de SMB son compatibles con cada versión de SMB. Algunas funciones de SMB se habilitan de forma predeterminada, por lo que algunas requieren más configuración.

|===
| *Esta funcionalidad:* | *Requiere activación:* 5+| *Es compatible con ONTAP 9 para estas versiones SMB:* 


 a| 
 a| 
 a| 
1,0
 a| 
2,0
 a| 
2,1
 a| 
3,0
 a| 
3.1.1



 a| 
Funcionalidad SMB 1.0 heredada
 a| 
 a| 
X
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
Asas duraderas
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
Operaciones compuestas
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
Operaciones asíncronas
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
Se han aumentado los tamaños de búfer de lectura y escritura
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
Mayor escalabilidad
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
Firma SMB
 a| 
X
 a| 
X
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
Formato de archivo de flujo de datos alternativo (ADS)
 a| 
X
 a| 
X
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
MTU grande (habilitada de forma predeterminada a partir de ONTAP 9.7)
 a| 
X
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X



 a| 
Bloqueos oportunistas del arrendamiento
 a| 
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X



 a| 
Recursos compartidos disponibles en todo momento
 a| 
X
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
Asas persistentes
 a| 
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
Testigo
 a| 
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
CIFRADO SMB: AES-128-CCM
 a| 
X
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
Escalado horizontal (necesario por los recursos compartidos de CA)
 a| 
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
Recuperación transparente tras fallas
 a| 
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
Multicanal de SMB (a partir de ONTAP 9.4)
 a| 
X
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
Integridad de la preautenticación
 a| 
 a| 
 a| 
 a| 
 a| 
 a| 
X



 a| 
Recuperación tras fallos de cliente de clúster v.2 (CCFv2)
 a| 
 a| 
 a| 
 a| 
 a| 
 a| 
X



 a| 
CIFRADO SMB: AES-128-GCM
 a| 
X
 a| 
 a| 
 a| 
 a| 
 a| 
X

|===
.Información relacionada
xref:signing-enhance-network-security-concept.adoc[Utilizar la firma SMB para mejorar la seguridad de la red]

xref:set-server-minimum-authentication-security-level-task.adoc[Configurar el nivel de seguridad de autenticación mínimo del servidor SMB]

xref:configure-required-encryption-concept.adoc[Configurar el cifrado SMB necesario en servidores SMB para las transferencias de datos a través de SMB]

https://mysupport.netapp.com/NOW/products/interoperability["Interoperabilidad de NetApp"^]
