---
permalink: smb-admin/support-branchcache-group-policy-objects-concept.html 
sidebar: sidebar 
keywords: ontap, branchcache, support, group, policy, object, gpo, centralize, management, configuration, parameter, hash, publication, support for branchcache group policy objects 
summary: ONTAP BranchCache proporciona compatibilidad con los objetos de directiva de grupo BranchCache, que permiten la gestión centralizada de determinados parámetros de configuración BranchCache. Existen dos GPO utilizados para BranchCache, el GPO de publicación de hash para BranchCache y el GPO de soporte de versión de hash para BranchCache. 
---
= Obtenga información sobre la compatibilidad de ONTAP SMB con los objetos de política de grupo de BranchCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BranchCache de ONTAP proporciona compatibilidad con objetos de directiva de grupo (GPO) de BranchCache, los cuales permiten una gestión centralizada para ciertos parámetros de configuración de BranchCache. Hay dos GPO utilizados para BranchCache, la publicación Hash para el GPO de BranchCache y la compatibilidad con versiones Hash para el GPO de BranchCache.

* *Publicación Hash para BranchCache GPO*
+
La publicación hash para GPO de BranchCache corresponde al `-operating-mode` parámetro. Cuando se producen actualizaciones de GPO, este valor se aplica a los objetos de máquinas virtuales de almacenamiento (SVM) contenidos en la unidad organizativa (OU) a la que se aplica la directiva de grupo.

* *Compatibilidad con la versión Hash para el GPO de BranchCache*
+
La compatibilidad de versiones hash para GPO de BranchCache corresponde al `-versions` parámetro. Cuando se producen actualizaciones de GPO, este valor se aplica a los objetos SVM incluidos en la unidad organizativa a la que se aplica la directiva de grupo.



.Información relacionada
xref:applying-group-policy-objects-concept.adoc[Obtenga información sobre cómo aplicar objetos de directiva de grupo a servidores SMB]
