---
permalink: smb-admin/view-shares-mmc-task.html 
sidebar: sidebar 
keywords: information, smb, share, svm, perform, management, task, microsoft, management, console, mmc, view, share, connect, svm, view information about smb shares using the mmc 
summary: 'Puede ver información sobre los recursos compartidos de SMB en la SVM y realizar algunas tareas de gestión con Microsoft Management Console (MMC). Antes de ver los recursos compartidos, tiene que conectar MMC a la SVM.' 
---
= Consulte información sobre los recursos compartidos de SMB mediante MMC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ver información sobre los recursos compartidos de SMB en la SVM y realizar algunas tareas de gestión con Microsoft Management Console (MMC). Antes de ver los recursos compartidos, tiene que conectar MMC a la SVM.

.Acerca de esta tarea
Puede realizar las siguientes tareas en recursos compartidos contenidos en las SVM mediante MMC:

* Ver recursos compartidos
* Ver sesiones activas
* Ver archivos abiertos
* Enumera la lista de sesiones, archivos y conexiones de árbol del sistema
* Cierre los archivos abiertos en el sistema
* Cierre las sesiones abiertas
* Cree/gestione recursos compartidos


[NOTE]
====
Las vistas que muestran las capacidades anteriores son específicas de los nodos y no del clúster. Por lo tanto, cuando utiliza MMC para conectarse al nombre de host del servidor SMB (es decir, cifs01.domain.local), se le enrutará, en función de cómo haya configurado DNS, a una única LIF dentro del clúster.

====
MMC para ONTAP no admite las siguientes funciones:

* Creación de nuevos usuarios/grupos locales
* Gestión/visualización de usuarios/grupos locales existentes
* Ver eventos o registros de rendimiento
* Reducida
* Servicios y aplicaciones


Es posible que tenga experiencia cuando no se admite la operación `remote procedure call failed` errores.

https://["Preguntas más frecuentes: Uso de MMC de Windows con ONTAP"]

.Pasos
. Para abrir la MMC de Administración de equipos en cualquier servidor de Windows, en *Panel de control*, seleccione *Herramientas administrativas* > *Administración de equipos*.
. Seleccione *Acción* > *conectar a otro ordenador*.
+
Aparece el cuadro de diálogo Seleccionar equipo.

. Escriba el nombre del sistema de almacenamiento o haga clic en *examinar* para buscar el sistema de almacenamiento.
. Haga clic en *Aceptar*.
+
MMC se conecta a SVM.

. En el panel de navegación, haga clic en *carpetas compartidas* > *recursos compartidos*.
+
Se muestra una lista de recursos compartidos de la SVM en el panel de visualización derecho.

. Para mostrar las propiedades de uso compartido de un recurso compartido, haga doble clic en él para abrir el cuadro de diálogo *Propiedades*.
. Si no puede conectarse al sistema de almacenamiento mediante MMC, puede agregar al usuario al grupo BUILTIN\Administrators o BUILTIN\Power Users mediante uno de los siguientes comandos del sistema de almacenamiento:
+
[listing]
----

cifs users-and-groups local-groups add-members -vserver <vserver_name> -group-name BUILTIN\Administrators -member-names <domainuser>

cifs users-and-groups local-groups add-members -vserver <vserver_name> -group-name "BUILTIN\Power Users" -member-names <domainuser>
----

