---
permalink: smb-admin/windows-hosts-version-requirements-concept.html 
sidebar: sidebar 
keywords: ontap, branch, office, windows, host, version, requirement, configure, branchcache, ontap and windows hosts version requirements 
summary: Los hosts de ONTAP y de oficina remota deben cumplir determinados requisitos de versión para poder configurar BranchCache. 
---
= Requisitos de la versión para hosts de ONTAP y Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los hosts de ONTAP y de oficina remota deben cumplir determinados requisitos de versión para poder configurar BranchCache.

Antes de configurar BranchCache, debe asegurarse de que la versión de ONTAP en el clúster y los clientes de la sucursal participantes sean compatibles con SMB 2.1 o una versión posterior y con la función de BranchCache. Si configura el modo de caché alojada, también debe asegurarse de que utiliza un host compatible para el servidor de caché.

BranchCache 1 es compatible con las siguientes versiones de ONTAP y hosts de Windows:

* Servidor de contenido: Máquina virtual de almacenamiento (SVM) con ONTAP
* Servidor de caché: Windows Server 2008 R2 o Windows Server 2012 o posterior
* Igual o cliente: Windows 7 Enterprise, Windows 7 Ultimate, Windows 8, Windows Server 2008 R2 o Windows Server 2012 o posterior


BranchCache 2 es compatible con las siguientes versiones de ONTAP y hosts de Windows:

* Servidor de contenido: SVM con ONTAP
* Servidor de caché: Windows Server 2012 o posterior
* Igual o cliente: Windows 8 o Windows Server 2012 o posterior


Para obtener la información más reciente sobre los clientes de Windows admiten BranchCache, consulte la matriz de interoperabilidad.

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"]
