---
permalink: svm-migrate/cancel-task.html 
sidebar: sidebar 
keywords: svm, migrate, cancel, abort 
summary: 'Si necesita cancelar una migración de SVM antes de que finalice, puede usar el `vserver migrate abort` comando. Solo es posible cancelar una migración de SVM cuando la operación se encuentra en estado de pausa o con errores. No es posible cancelar una migración de SVM cuando el estado es "transposición-iniciada" o una vez completada la transposición. No puede utilizar el `abort` Opción cuando hay una migración de SVM en curso.' 
---
= Cancele una migración de SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si necesita cancelar una migración de SVM antes de que finalice, puede usar el `vserver migrate abort` comando. Solo es posible cancelar una migración de SVM cuando la operación se encuentra en estado de pausa o con errores. No es posible cancelar una migración de SVM cuando el estado es "transposición-iniciada" o una vez completada la transposición. No puede utilizar el `abort` Opción cuando hay una migración de SVM en curso.

.Pasos
. Compruebe el estado de la migración:
+
`dest_cluster> vserver migrate show -vserver <vserver name>`

. Cancele la migración:
+
`dest_cluster> vserver migrate abort -vserver <vserver name>`

. Compruebe el progreso de la operación de cancelación:
+
`dest_cluster> vserver migrate show`

+
El estado de migración muestra migración-anulación mientras la operación de cancelación está en curso. Cuando se completa la operación de cancelación, el estado de migración no muestra nada.


