---
permalink: mediator/index.html 
sidebar: sidebar 
keywords: ontap mediator service, install requirements, mediator requirements 
summary: Para instalar el servicio Mediator de ONTAP, debe asegurarse de que se cumplen todos los requisitos previos, obtener el paquete de instalación y ejecutar el instalador en el host. 
---
= Prepárese para instalar o actualizar el servicio de Mediador de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalar el servicio ONTAP Mediator, debe asegurarse de que se cumplen todos los requisitos previos, obtener el paquete de instalación y ejecutar el instalador en el host. Este procedimiento se utiliza para una instalación o actualización de una instalación existente.

.Acerca de esta tarea
* A partir de ONTAP 9.7, puede utilizar cualquier versión de Mediator de ONTAP para supervisar una configuración IP de MetroCluster.
* A partir de ONTAP 9,8, puede usar cualquier versión de ONTAP Mediator para supervisar una relación de sincronización activa de SnapMirror.


.Antes de empezar
Debe cumplir con los siguientes requisitos previos.

[cols="30,70"]
|===


| Versión de ONTAP Mediator | Versiones de Linux compatibles 


 a| 
1,8
 a| 
* Red Hat Enterprise Linux: 8,6, 8,7, 8,8, 8,9, 8,10, 9,2, 9,3 y 9,4
* Rocky Linux 8 y 9




 a| 
1,7
 a| 
* Red Hat Enterprise Linux: 8,5, 8,6, 8,7, 8,8, 8,9, 9,0, 9,1, 9,2 y 9,3
* Rocky Linux 8 y 9




 a| 
1,6
 a| 
* Red Hat Enterprise Linux: 8,4, 8,5, 8,6, 8,7, 8,8, 9,0, 9,1, 9,2
* Rocky Linux 8 y 9




 a| 
1,5
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.1 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1,4
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.1 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1,3
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.1 8.2, 8.3
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1,2
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 8.1
* CentOS: 7.6, 7.7, 7.8


|===

NOTE: La versión del kernel debe coincidir con la versión del sistema operativo.

* instalación física de 64 bits o máquina virtual
* 8 GB DE MEMORIA RAM
* 1 GB de espacio en disco (utilizado para la instalación de aplicaciones, registros del servidor y la base de datos)
* Usuario: Acceso raíz


Cualquier paquete de biblioteca, excepto el núcleo, se puede actualizar de forma segura, pero es posible que sea necesario reiniciarlo para que se vea afectado dentro de la aplicación ONTAP Mediator.  Se recomienda una ventana de servicio cuando es necesario reiniciar.

Si instala el `yum-utils` paquete, puede utilizar el `needs-restarting` comando.

El núcleo central del núcleo se puede actualizar si se está actualizando a una versión que aún es compatible con la matriz de versiones de ONTAP Mediator. Un reinicio será obligatorio, por lo que se requiere una ventana de servicio.

El módulo del núcleo SCST debe desinstalarse antes del reinicio y, a continuación, volver a instalarse después del reinicio.


NOTE: No se admite la actualización a un núcleo más allá de la versión de SO admitida para la versión de ONTAP Mediator específica. (Esto probablemente indica que el módulo SCST probado no se compilará).



== Registre una clave de seguridad cuando el arranque seguro de UEFI esté habilitado

Si el inicio seguro de UEFI está activado, para instalar ONTAP Mediator, tendrá que registrar una clave de seguridad antes de que el servicio ONTAP Mediator pueda iniciarse. Para determinar si el sistema está habilitado para UEFI y Secure Boot está activado, realice los siguientes pasos:

.Pasos
. Si mokutil no está instalado, ejecute el siguiente comando:
+
`yum install mokutil`

. Para determinar si UEFI Secure Boot está habilitado en su sistema, ejecute el siguiente comando:
+
`mokutil --sb-state`

+
Los resultados muestran si UEFI Secure Boot está habilitado en este sistema.

+

NOTE: ONTAP Mediator 1.2.0 y las versiones anteriores no admiten este modo.





== Desactive UEFI Secure Boot

También puede optar por deshabilitar el arranque seguro de UEFI antes de instalar ONTAP Mediator.

.Pasos
. En la configuración del BIOS de la máquina física, desactive la opción «Arranque seguro UEFI».
. En la configuración de VMware para la máquina virtual, desactive la opción de inicio seguro para vSphere 6.x o la opción de arranque seguro para vSphere 7.x.

