---
permalink: mediator/index.html 
sidebar: sidebar 
keywords: ontap mediator service, install requirements, mediator requirements 
summary: Para instalar el servicio Mediator de ONTAP, debe asegurarse de que se cumplen todos los requisitos previos, obtener el paquete de instalación y ejecutar el instalador en el host. 
---
= Prepárese para instalar o actualizar el servicio de Mediador de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalar el servicio ONTAP Mediator, debe asegurarse de que se cumplen todos los requisitos previos, obtener el paquete de instalación y ejecutar el instalador en el host. Este procedimiento se utiliza para una instalación o actualización de una instalación existente.

* A partir de ONTAP 9.7, puede utilizar cualquier versión de Mediator de ONTAP para supervisar una configuración IP de MetroCluster.
* A partir de ONTAP 9,8, puede usar cualquier versión de ONTAP Mediator para supervisar una relación de sincronización activa de SnapMirror.




== Consideraciones sobre la instalación y la actualización

Revise las siguientes consideraciones antes de actualizar o instalar ONTAP Mediator.


CAUTION: ONTAP Mediator 1,8 y versiones anteriores no es compatible con el modo FIPS de Red Hat Enterprise Linux y no se puede instalar correctamente. Puede comprobar si el modo FIPS está habilitado mediante `fips-mode-setup --check` el comando. Puede deshabilitar el modo FIPS con `fips-modesetup --disable` el comando. Reinicie después de deshabilitar el modo FIPS para instalar correctamente ONTAP Mediator 1,8 o anterior.

* Debe actualizar ONTAP Mediator a la última versión disponible. Las versiones anteriores de ONTAP Mediator siguen siendo compatibles con todas las versiones de ONTAP, pero las versiones recientes incluyen parches de seguridad para todos los elementos de terceros.
* Cuando se actualiza a una nueva versión de ONTAP Mediator, el instalador se actualiza automáticamente a la versión de SCST recomendada a menos que haya disponible una versión superior. Para obtener instrucciones sobre la instalación manual de una versión SCST superior, consulte link:manage-task.html["Gestionar el servicio de Mediator"]. Para ver las versiones compatibles, consulte la link:whats-new-concept.html#scst-support-matrix["Matriz de soporte SCST"].
+

CAUTION: Si se produce un fallo de instalación, es posible que tenga que actualizar a una versión posterior de ONTAP Mediator.

* Si instala el `yum-utils` paquete, puede utilizar el `needs-restarting` comando.




=== Requisitos de SO

Su sistema operativo debe cumplir los siguientes requisitos:

* instalación física de 64 bits o máquina virtual
* 8 GB DE MEMORIA RAM
* 1 GB de espacio en disco (utilizado para la instalación de aplicaciones, registros del servidor y la base de datos)
* Usuario: Acceso raíz


La siguiente tabla muestra los sistemas operativos compatibles para cada versión de ONTAP Mediator.

[cols="30,70"]
|===


| Versión de ONTAP Mediator | Versiones de Linux compatibles 


 a| 
1,9
 a| 
* Red Hat Enterprise Linux
+
** Compatible: 8,4, 8,5, 8,6, 8,7, 8,9, 9,1 y 9,3 ^1^
** Recomendado: 8,8, 8,10, 9,0, 9,2, 9,4 y 9,5


* Rocky Linux 8 y 9




 a| 
1,8
 a| 
* Red Hat Enterprise Linux: 8,4, 8,5, 8,6, 8,7, 8,8, 8,9, 8,10, 9,0, 9,1, 9,2, 9,3 y 9,4
* Rocky Linux 8 y 9




 a| 
1,7
 a| 
* Red Hat Enterprise Linux: 8,4, 8,5, 8,6, 8,7, 8,8, 8,9, 9,0, 9,1, 9,2 y 9,3
* Rocky Linux 8 y 9




 a| 
1,6
 a| 
* Red Hat Enterprise Linux: 8,4, 8,5, 8,6, 8,7, 8,8, 9,0, 9,1, 9,2
* Rocky Linux 8 y 9




 a| 
1,5
 a| 
* Red Hat Enterprise Linux: 7,6, 7,7, 7,8, 7,9, 8,0, 8,1, 8,2, 8,3, 8,4 y 8,5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1,4
 a| 
* Red Hat Enterprise Linux: 7,6, 7,7, 7,8, 7,9, 8,0, 8,1, 8,2, 8,3, 8,4 y 8,5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1,3
 a| 
* Red Hat Enterprise Linux: 7,6, 7,7, 7,8, 7,9, 8,0, 8,1, 8,2, 8,3
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1,2
 a| 
* Red Hat Enterprise Linux: 7,6, 7,7, 7,8, 7,9, 8,0, 8,1
* CentOS: 7.6, 7.7, 7.8, 7.9


|===
. Compatible significa que RHEL ya no es compatible con esta versión, pero ONTAP Mediator puede seguir instalándose.




=== Consideraciones sobre la actualización del sistema operativo y compatibilidad de kernel

* Todos los paquetes de biblioteca, excepto el núcleo, se pueden actualizar de forma segura, pero puede que sea necesario reiniciar para aplicar los cambios dentro de la aplicación ONTAP Mediator. Se recomienda una ventana de servicio cuando es necesario reiniciar.
* Deberá mantener actualizado el kernel del sistema operativo. El núcleo del núcleo se puede actualizar a una versión enumerada como admitida en el link:whats-new-concept.html#scst-support-matrix["Matriz de versiones de ONTAP Mediator"]. Un reinicio es obligatorio, por lo que debe planificar una ventana de mantenimiento para la interrupción del servicio.
+
** Debe desinstalar el módulo del núcleo SCST antes de reiniciar y, a continuación, volver a instalarlo después.
** Debe tener una versión compatible de SCST lista para reinstalar antes de iniciar la actualización del sistema operativo del núcleo.




[NOTE]
====
* La versión del kernel debe coincidir con la versión del sistema operativo.
* No se admite la actualización a un núcleo más allá de la versión de SO admitida para la versión de ONTAP Mediator específica. (Esto probablemente indica que el módulo SCST probado no se compilará).


====


== Registre una clave de seguridad cuando el arranque seguro de UEFI esté habilitado

Para instalar ONTAP Mediator con arranque seguro UEFI habilitado, debe registrar una clave de seguridad antes de que el servicio pueda iniciarse. La clave se genera durante el paso de compilación de la instalación SCST y se guarda como un par de claves público-privado en su máquina. Utilice la `mokutil` utilidad para agregar la clave pública como una clave de propietario de la máquina (MOK) a su firmware UEFI, lo que permite que el sistema confíe y cargue el módulo firmado. Guarde la `mokutil` frase de contraseña en una ubicación segura, ya que es necesario al reiniciar el sistema para activar el MOK.

Para determinar si el sistema está habilitado para UEFI y Secure Boot está activado, realice los siguientes pasos:

.Pasos
.  `mokutil`Si no está instalado, ejecute el siguiente comando:
+
`yum install mokutil`

. Compruebe si UEFI Secure Boot está activado en su sistema:
+
`mokutil --sb-state`

+
Los resultados indican si UEFI Secure Boot está activado en este sistema.

+
[NOTE]
====
** Se le pedirá que cree una frase de acceso que debe almacenar en una ubicación segura. Necesitará esta frase de contraseña para habilitar la clave en el Administrador de inicio UEFI.
** ONTAP Mediator 1.2.0 y versiones anteriores no admiten este modo.


====
. Agregue la clave pública a la lista MOK:
+
`mokutil --import /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.der`

+

NOTE: Puede dejar la clave privada en su ubicación predeterminada o moverla a una ubicación segura. Sin embargo, la clave pública se debe mantener en su ubicación existente para que la utilice el gestor de arranque. Para obtener más información, consulte el siguiente archivo README.MODULE-SIGNING:

+
`[root@hostname ~]# ls /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/
README.module-signing  scst_module_key.der  scst_module_key.priv`

. Reinicie el host y utilice el UEFI Boot Manager de su dispositivo para aprobar el nuevo MOK. Necesitará la frase de acceso proporcionada para el `mokutil` paso 2.




== Desactive UEFI Secure Boot

También puede optar por deshabilitar el arranque seguro de UEFI antes de instalar ONTAP Mediator.

.Pasos
. En la configuración del BIOS de la máquina física, desactive la opción «Arranque seguro UEFI».
. En la configuración de VMware para la máquina virtual, desactive la opción de inicio seguro para vSphere 6.x o la opción de arranque seguro para vSphere 7.x.

