---
permalink: mediator/manage-task.html 
sidebar: sidebar 
keywords: mediator, username, password, change, uninstall 
summary: Después de instalar el servicio Mediator de ONTAP, es posible que desee cambiar el nombre de usuario o la contraseña. También puede desinstalar el servicio Mediator de ONTAP. 
---
= Gestione el servicio de mediación de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una vez instalado el servicio Mediador de ONTAP, puede cambiar el nombre de usuario o la contraseña. También puede desinstalar el servicio Mediator de ONTAP.



== Cambie el nombre de usuario

.Acerca de estas tareas
Esta tarea se realiza en el host Linux en el que está instalado el servicio Mediator de ONTAP.

Si no puede alcanzar este comando, puede que deba ejecutar el comando con la ruta completa como se muestra en el ejemplo siguiente:

`/usr/local/bin/mediator_username`

.Procedimiento
Cambie el nombre de usuario eligiendo una de las siguientes opciones:

* Ejecute el comando mediador_change_user y responda a las indicaciones como se muestra en el ejemplo siguiente:
+
....
 [root@mediator-host ~]# mediator_change_user
 Modify the Mediator API username by entering the following values:
     Mediator API User Name: mediatoradmin
                   Password:
 New Mediator API User Name: mediator
 The account username has been modified successfully.
 [root@mediator-host ~]#
....
* Ejecute el siguiente comando:
+
`MEDIATOR_USERNAME=mediator MEDIATOR_PASSWORD=mediator2 MEDIATOR_NEW_USERNAME=mediatoradmin mediator_change_user`

+
....
 [root@mediator-host ~]# MEDIATOR_USERNAME= mediator MEDIATOR_PASSWORD='mediator2' MEDIATOR_NEW_USERNAME= mediatoradmin mediator_change_user
 The account username has been modified successfully.
 [root@mediator-host ~]#
....




== Cambie la contraseña

.Acerca de esta tarea
Esta tarea se realiza en el host Linux en el que está instalado el servicio Mediator de ONTAP.

Si no puede alcanzar este comando, puede que deba ejecutar el comando con la ruta completa como se muestra en el ejemplo siguiente:

`/usr/local/bin/mediator_change_password`

.Procedimiento
Cambie la contraseña eligiendo una de las siguientes opciones:

* Ejecute el `mediator_change_password` y responda a las indicaciones como se muestra en el ejemplo siguiente:
+
....
 [root@mediator-host ~]# mediator_change_password
 Change the Mediator API password by entering the following values:
    Mediator API User Name: mediatoradmin
              Old Password:
              New Password:
          Confirm Password:
 The password has been updated successfully.
 [root@mediator-host ~]#
....
* Ejecute el siguiente comando:
+
`MEDIATOR_USERNAME= mediatoradmin MEDIATOR_PASSWORD=mediator1 MEDIATOR_NEW_PASSWORD=mediator2 mediator_change_password`

+
El ejemplo muestra que la contraseña se cambia de "mediator1" a "mediator2".

+
....
 [root@mediator-host ~]# MEDIATOR_USERNAME=mediatoradmin MEDIATOR_PASSWORD=mediator1 MEDIATOR_NEW_PASSWORD=mediator2 mediator_change_password
 The password has been updated successfully.
 [root@mediator-host ~]#
....




== Desinstale el servicio Mediator de ONTAP

.Antes de empezar
Si es necesario, puede eliminar el servicio Mediador ONTAP. El Mediador debe desconectarse de ONTAP antes de quitar el servicio Mediator.

.Acerca de esta tarea
Esta tarea se realiza en el host Linux en el que está instalado el servicio Mediator de ONTAP.

Si no puede alcanzar este comando, puede que deba ejecutar el comando con la ruta completa como se muestra en el ejemplo siguiente:

`/usr/local/bin/uninstall_ontap_mediator`

.Paso
. Desinstale el servicio Mediator de ONTAP:
+
`uninstall_ontap_mediator`

+
....
 [root@mediator-host ~]# uninstall_ontap_mediator

 ONTAP Mediator: Self Extracting Uninstaller

 + Removing ONTAP Mediator. (Log: /tmp/ontap_mediator.GmRGdA/uninstall_ontap_mediator/remove.log)
 + Remove successful.
 [root@mediator-host ~]#
....

