---
permalink: mediator/mediator-overview-concept.html 
sidebar: sidebar 
keywords: ontap mediator service, install requirements, mediator requirements 
summary: ONTAP Mediator proporciona varias funciones para las funciones de ONTAP. 
---
= Descripción general de ONTAP Mediator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El Mediador ONTAP proporciona varias funciones para las funciones de ONTAP:

* Proporciona un almacén persistente y cercado para metadatos de alta disponibilidad.
* Funciona como proxy ping para la vida útil de la controladora.
* Proporciona funcionalidad de consulta de estado de nodo síncrono para ayudar a determinar el quórum.


ONTAP Mediator proporciona dos servicios adicionales de systemctl:

* *`ontap_mediator.service`*
+
Mantiene el servidor API REST para gestionar las relaciones ONAP.

* *`mediator-scst.service`*
+
Controla el inicio y el apagado del módulo iSCSI (SCST).





== Herramientas proporcionadas para el administrador del sistema

Herramientas proporcionadas para el administrador del sistema:

* *`/usr/local/bin/mediator_change_password`*
+
Establece una nueva contraseña de API cuando se proporcionan el nombre de usuario y la contraseña actuales de la API.

* *`/usr/local/bin/mediator_change_user`*
+
Establece un nuevo nombre de usuario de API cuando se proporcionan el nombre de usuario y la contraseña actuales de la API.

* *`/usr/local/bin/mediator_generate_support_bundle`*
+
Genera un archivo tgz local con toda la información de soporte útil necesaria para la comunicación con el soporte al cliente de NetApp. Esto incluye la configuración de la aplicación, los registros y cierta información del sistema. Los paquetes se generan en el disco local y se pueden transferir manualmente, según sea necesario. Ubicación de almacenamiento: /Opt/netapp/data/support_bundles/

* *`/usr/local/bin/uninstall_ontap_mediator`*
+
Elimina el paquete ONTAP Mediator y el módulo del núcleo SCST. Esto incluye todos los datos de configuración, registros y buzón de correo.

* *`/usr/local/bin/mediator_unlock_user`*
+
Libera un bloqueo en la cuenta de usuario de la API si se alcanzó el límite de reintentos de autenticación. Esta función se utiliza para evitar la derivación de contraseña de fuerza bruta. Solicita al usuario el nombre de usuario y la contraseña correctos.

* *`/usr/local/bin/mediator_add_user`*
+
(Solo soporte) Se utiliza para agregar el usuario de la API durante la instalación.





== Notas especiales

ONTAP Mediator confía en SCST para proporcionar iSCSI (consulte. Este paquete es un módulo del núcleo que se compila durante la instalación específicamente para el núcleo. Es posible que cualquier actualización del núcleo requiera la reinstalación de SCST. Como alternativa, desinstale y vuelva a instalar ONTAP Mediator y, a continuación, vuelva a configurar la relación ONTAP.


NOTE: Cualquier actualización del kernel del sistema operativo del servidor se debe coordinar con una ventana de mantenimiento de ONTAP.
