---
permalink: mediator/verify-code-signature-task.html 
sidebar: sidebar 
keywords: mediator, new, release, update, install, verify, code, signature 
summary: Antes de instalar el paquete de instalación del Mediador, debe comprobar la firma del código del Mediador ONTAP. 
---
= Verifique la firma del código del Mediador ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp recomienda verificar la firma del código del mediador ONTAP antes de la instalación. Este paso es opcional.

.Antes de empezar
Asegúrese de que su sistema cumple con estos requisitos antes de verificar la firma de código del mediador ONTAP .

[NOTE]
====
* A partir del 15 de junio de 2025, no podrá instalar ni actualizar a ONTAP Mediator 1.9 ni 1.8 porque los certificados de verificación de firma de código han caducado. En su lugar, instale o actualice a ONTAP Mediator 1.11 o 1.10.
* Si el sistema no cumple con los siguientes requisitos, el proceso de verificación no es necesario y puede ir directamente a link:install-mediator-pkg-task.html["Instale el paquete de instalación del Mediador ONTAP"].


====
* versiones de openssl 1.0.2 a 3.0 para verificación básica
* la versión de openssl 1.1.0 o posterior para las operaciones de la Autoridad de fijación temporal (TSA)
* Acceso público a Internet para verificación OCSP


El paquete de descarga incluye los siguientes archivos:

[cols="50,50"]
|===


| Archivo | Descripción 


 a| 
`ONTAP-Mediator-production.pub`
 a| 
Clave pública utilizada para verificar la firma



 a| 
`csc-prod-chain-ONTAP-Mediator.pem`
 a| 
La cadena de confianza de CA de certificación pública



 a| 
`csc-prod-ONTAP-Mediator.pem`
 a| 
El certificado utilizado para generar la clave



 a| 
`ontap-mediator-1.11.0`
 a| 
El ejecutable de instalación del producto para la versión 1.11



 a| 
`ontap-mediator-1.11.0.sig`
 a| 
El SHA-256 hash, luego RSA-firmado usando la clave csc-prod, firma para el instalador



 a| 
`ontap-mediator-1.11.0.sig.tsr`
 a| 
La solicitud de revocación para el uso por parte de OCSCP para la firma del instalador



 a| 
`ontap-mediator-1.11.0.tsr`
 a| 
Archivo de solicitud de firma de marca de hora



 a| 
`tsa-prod-ONTAP-Mediator.pem`
 a| 
El certificado público para la TSR



 a| 
`tsa-prod-chain-ONTAP-Mediator.pem`
 a| 
El certificado público CA Chain para la TSR

|===
.Pasos
. Realice la comprobación de revocación `csc-prod-ONTAP-Mediator.pem` mediante el protocolo de estado de certificado en línea (OCSP).
+
.. Localice la URL OCSP del certificado.  Los certificados de desarrollador podrían no proporcionar un URI:
+
[listing]
----
openssl x509 -noout -ocsp_uri -in csc-prod-chain-ONTAP-Mediator.pem
----
.. Genere una solicitud OCSP para el certificado.
+
[listing]
----
openssl ocsp -issuer csc-prod-chain-ONTAP-Mediator.pem -CAfile csc-prod-chain-ONTAP-Mediator.pem -cert csc-prod-ONTAP-Mediator.pem  -reqout req.der
----
.. Conéctese al administrador de OCSP para enviar la solicitud OCSP:
+
[listing]
----
openssl ocsp -issuer csc-prod-chain-ONTAP-Mediator.pem -CAfile csc-prod-chain-ONTAP-Mediator.pem -cert csc-prod-ONTAP-Mediator.pem  -url ${ocsp_uri} -resp_text -respout resp.der -verify_other csc-prod-chain-ONTAP-Mediator.pem
----


. Verifique la cadena de confianza del CSC y las fechas de vencimiento con respecto al host local:
+
`openssl verify`

+

NOTE:  `openssl`La versión de LA RUTA DE ACCESO debe tener un valor válido `cert.pem` (no autofirmado).

+
[listing]
----
openssl verify -untrusted csc-prod-chain-ONTAP-Mediator.pem -CApath ${OPENSSLDIR} csc-prod-ONTAP-Mediator.pem  # Failure action: The Code-Signature-Check certificate has expired or is invalid. Download a newer version of the ONTAP Mediator.
openssl verify -untrusted tsa-prod-chain-ONTAP-Mediator.pem -CApath ${OPENSSLDIR} tsa-prod-ONTAP-Mediator.pem  # Failure action: The Time-Stamp certificate has expired or is invalid. Download a newer version of the ONTAP Mediator.
----
. Verifique el `ontap-mediator-1.11.0.sig.tsr` y `ontap-mediator-1.11.0.tsr` archivos que utilizan los certificados asociados:
+
[role="tabbed-block"]
====
.OpenSSL 3.x
--
`openssl ts -verify -data ontap-mediator-1.11.0.sig -in ontap-mediator-1.11.0.sig.tsr -CAfile tsa-prod-chain-ONTAP-Mediator.pem -untrusted tsa-prod-ONTAP-Mediator.pem`

--
.OpenSSL 1.x
--
`openssl ts -verify -data ontap-mediator-1.11.0 -in ontap-mediator-1.11.0.tsr -CAfile tsa-prod-chain-ONTAP-Mediator.pem -partial_chain`

--
====
+

NOTE: `.tsr`Los archivos contienen la marca de tiempo de la respuesta asociada con el instalador y la firma del código.  El procesamiento confirma que la marca de tiempo tiene una firma válida de la TSA y que su archivo de entrada no ha cambiado.  Tu máquina realiza la verificación localmente.  No necesitas acceder a los servidores de la TSA.

. Verificar firmas con respecto a la clave:
+
`openssl -dgst -verify`

+
[listing]
----
openssl dgst -sha256 -verify ONTAP-Mediator-production.pub -signature ontap-mediator-1.11.0.sig ontap-mediator-1.11.0
----

