---
sidebar: sidebar 
permalink: flexcache-hot-spot/flexcache-hotspot-remediation-overview.html 
keywords: hotspot, FlexCache, HDFA, problem, solution, ONTAP 
summary: Aprenda a corregir las zonas activas, un problema común con muchas cargas de trabajo de computación de alto rendimiento, como el renderizado de animación o EDA, con FlexCache. 
---
= Reparación de las detección en caliente de cargas de trabajo informáticas de alto rendimiento con ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un problema común con muchas cargas de trabajo de computación de alto rendimiento, como el renderizado de animación o EDA, es la detección en caliente. Hotspot es una situación que se produce cuando una parte específica del clúster o de la red experimenta una carga significativamente mayor en comparación con otras áreas, lo que provoca cuellos de botella en el rendimiento y reduce la eficiencia general debido al exceso de tráfico de datos concentrado en esa ubicación. Por ejemplo, un archivo, o varios archivos, tiene una gran demanda para el trabajo en ejecución, lo que provoca un cuello de botella en la CPU utilizada para atender solicitudes (a través de una afinidad de volumen) a ese archivo. FlexCache puede ayudar a reducir este cuello de botella, pero es necesario configurarlo de manera adecuada.

En esta documentación se explica cómo configurar FlexCache para corregir la detección directa.


NOTE: A partir de julio de 2024, el contenido de informes técnicos publicados anteriormente como archivos PDF se ha integrado con la documentación de los productos de ONTAP. El contenido del informe técnico sobre la corrección del punto de acceso de ONTAP es completamente nuevo a partir de la fecha de su publicación y no se produjo ningún formato anterior.



== Conceptos clave

A la hora de planificar la corrección de puntos de acceso, es importante comprender estos conceptos esenciales.

* *FlexCache de alta densidad (HDF)*: Un FlexCache que se condensa para abarcar tan pocos nodos como lo permitan los requisitos de capacidad de la caché
* *HDF Array (HDFA)*: Un grupo de HDFS que son cachés del mismo origen, distribuidos en todo el clúster
* *Inter-SVM HDFA*: Un HDF del HDFA por máquina virtual de servidor (SVM)
* *Intra-SVM HDFA*: Todo HDFS en el HDFA en una SVM
* *Tráfico Este-Oeste*: Tráfico de backend de cluster generado a partir del acceso indirecto a datos


.El futuro
* link:flexcache-hotspot-remediation-architecture.html["Aprende a diseñar una arquitectura con FlexCache de alta densidad para ayudar a corregir las zonas de detección activa"]
* link:flexcache-hotspot-remediation-hdfa-examples.html["Decidir la densidad de la cabina FlexCache"]
* link:flexcache-hotspot-remediation-intra-inter-svm-hdfa.html["Determine la densidad de su HDFS y decida si accederá a HDFS usando NFS con HDFA entre SVM y HDFA dentro de SVM"]
* link:flexcache-hotspot-remediation-ontap-config.html["Configura HDFA y los LIF de datos para aprovechar las ventajas de usar el almacenamiento en caché dentro del clúster con la configuración de ONTAP"]
* link:flexcache-hotspot-remediation-client-config.html["Aprenda a configurar clientes para distribuir conexiones NAS de ONTAP con la configuración del cliente"]

