---
permalink: update/enable-automatic-updates-task.html 
sidebar: sidebar 
keywords: ontap, enable, upgrade, update, automatic, automated, firmware, bmc, sp, system, timezone database, timezone 
summary: La habilitación de actualizaciones automáticas permite a ONTAP descargar e instalar actualizaciones de firmware y de base de datos de zona horaria sin su intervención. 
---
= Active las actualizaciones automáticas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.10.1, puede habilitar las actualizaciones automáticas para permitir que ONTAP descargue e instale actualizaciones de firmware sin la intervención del usuario.

A partir de ONTAP 9.13.1, estas actualizaciones automáticas también incluyen actualizaciones automáticas de la base de datos de zona horaria.

.Antes de empezar
Debe tener un derecho de soporte vigente. Esto se puede validar en el link:https://mysupport.netapp.com/site/["Sitio de soporte de NetApp"^] En la página *Detalles del sistema*.

.Acerca de esta tarea
Para habilitar las actualizaciones automáticas, primero debe habilitar AutoSupport con HTTPS.  Si AutoSupport no está habilitado en el clúster, o si AutoSupport está habilitado en el clúster con otro protocolo de transporte, tendrá la opción de habilitarla con HTTPS durante este procedimiento.

.Pasos
. En System Manager, haga clic en *Eventos*.
. En la sección *Overview*, junto a *Enable automatic update*, haz clic en *Actions>Enable*.
. Si no dispone de AutoSupport con HTTPS habilitado, seleccione para habilitarlo.
. Acepte los términos y condiciones y seleccione *Guardar*.


.Información relacionada
link:../system-admin/troubleshoot-autosupport-http-https-task.html["Solucione problemas de entrega de mensajes de AutoSupport a través de HTTP o HTTPS"]
