---
permalink: update/index.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, automatic, automated, firmware, bmc, sp, system, timezone database, timezone, security, arp 
summary: En función de la versión de ONTAP, puede activar las actualizaciones automáticas de firmware, sistema y seguridad. 
---
= Descripción general de las actualizaciones de firmware, sistema y seguridad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En función de la versión de ONTAP, puede activar las actualizaciones automáticas de firmware, sistema y seguridad.

[cols="25,75"]
|===
| Versión de ONTAP | Lo que se incluye en las actualizaciones automáticas 


| 9.16.1 y posterior  a| 
* Protección autónoma frente a ransomware con inteligencia artificial (ARP/AI)
* Base de datos de zona horaria de ONTAP
* Firmware de almacenamiento para dispositivos de almacenamiento, discos y bandejas de discos
* Firmware del SP/BMC para los procesadores de servicio y los módulos BMC




| 9.13.1 y posterior  a| 
* Base de datos de zona horaria de ONTAP
* Firmware de almacenamiento para dispositivos de almacenamiento, discos y bandejas de discos
* Firmware del SP/BMC para los procesadores de servicio y los módulos BMC




| 9.10.1 y posterior  a| 
* Firmware de almacenamiento para dispositivos de almacenamiento, discos y bandejas de discos
* Firmware del SP/BMC para los procesadores de servicio y los módulos BMC




| 9.9.1 y anteriores | No admitido 
|===
Si no hay una actualización automática disponible para su versión de ONTAP o si no tiene habilitadas las actualizaciones automáticas, puede realizar actualizaciones de firmware, base de datos de zona horaria y seguridad manualmente.

.Enlaces relacionados
* link:firmware-task.html["Aprenda a realizar actualizaciones de firmware manualmente"]
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_update_time_zone_information_in_ONTAP_9["Artículo de la base de conocimientos, Cómo actualizar la información de la zona horaria en ONTAP 9"^]
* link:../anti-ransomware/enable-arp-ai-with-au.html["Aprenda a realizar actualizaciones de seguridad manualmente"]




== Vídeo: Función de actualización automática del firmware

Echa un vistazo a la función de actualización automática de firmware disponible a partir de ONTAP 9.10.1.

video::GoABILT85hQ[youtube,width=848,height=480]