---
permalink: data-protection/configure-custom-snapshot-policies-concept.html 
sidebar: sidebar 
keywords: configure, custom, snapshot, policy 
summary: 'Una política de Snapshot define cómo el sistema crea copias Snapshot. La política especifica cuándo crear copias Snapshot, cuántas copias se retendrán y cómo nombrarlas. Por ejemplo, un sistema puede crear una copia snapshot todos los días a las 12:10 a.m., conservar las dos copias más recientes y nombrar las copias “Daily.timestamp”.' 
---
= Información general de configuración de políticas de Snapshot personalizadas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una _política de Snapshot_ define el modo en que el sistema crea copias Snapshot. La política especifica cuándo crear copias Snapshot, cuántas copias se retendrán y cómo nombrarlas. Por ejemplo, un sistema puede crear una copia Snapshot todos los días a las 12:10, conservar las dos copias más recientes y nombrar las copias "día a día.`_timestamp_`.'"

La política predeterminada de un volumen crea automáticamente copias de Snapshot en la siguiente programación, con las copias de Snapshot más antiguas eliminadas para hacer espacio para las copias más nuevas:

* Un máximo de seis copias Snapshot cada hora tardan cinco minutos.
* Un máximo de dos copias Snapshot diarias que se tomaban de lunes a sábado a las 10 minutos después de la medianoche.
* Un máximo de dos copias snapshot semanales cada domingo a las 15 minutos después de la medianoche.


A menos que especifique una política de Snapshot cuando crea un volumen, el volumen hereda la política de Snapshot asociada con su máquina virtual de almacenamiento (SVM).
