---
permalink: data-protection/configure-custom-snapshot-policies-concept.html 
sidebar: sidebar 
keywords: configure, custom, snapshot, policy 
summary: 'Una política de Snapshot define la forma en que el sistema crea copias de Snapshot. La política especifica cuándo crear snapshots, cuántas copias se conservan y cómo asignarles un nombre. Por ejemplo, un sistema puede crear una copia Snapshot cada día a las 12:10 a.m., conservar las dos copias más recientes y asignar el nombre a las copias como «daily.timestamp».' 
---
= Configure la visión general de las políticas de instantáneas personalizadas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A _snapshot policy_ define la forma en que el sistema crea instantáneas. La política especifica cuándo crear snapshots, cuántas copias se conservan y cómo asignarles un nombre. Por ejemplo, un sistema puede crear una copia Snapshot todos los días a las 12:10 a.m., conservar las dos copias más recientes y asignar el nombre a las copias «daaily.`_timestamp_`».

La política predeterminada para un volumen crea automáticamente Snapshot en la siguiente programación, con las copias de Snapshot más antiguas eliminadas para dejar espacio para copias más recientes:

* Un máximo de seis instantáneas cada hora tomadas cinco minutos más allá de la hora.
* Un máximo de dos instantáneas diarias tomadas de lunes a sábado a las 10 minutos después de la medianoche.
* Un máximo de dos instantáneas semanales tomadas cada domingo a las 15 minutos después de la medianoche.


A menos que se especifique una política de snapshot al crear un volumen, el volumen hereda la política de Snapshot asociada con la SVM que contiene la máquina virtual de almacenamiento (SVM).
