---
permalink: data-protection/convert-type-snapmirror-task.html 
sidebar: sidebar 
keywords: convert, snapmirror, relationship, asynchronous, synchronous, baseline, convert 
summary: A partir de ONTAP 9.5, se admite SnapMirror síncrono. Es posible convertir una relación asíncrona de SnapMirror en una relación síncrona de SnapMirror o viceversa sin realizar una transferencia completa. 
---
= Convertir el tipo de una relación de ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.5, se admite SnapMirror síncrono. Es posible convertir una relación asíncrona de SnapMirror en una relación síncrona de SnapMirror o viceversa sin realizar una transferencia completa.

.Acerca de esta tarea
No se puede convertir una relación asíncrona de SnapMirror en una relación síncrona de SnapMirror o viceversa cambiando la política de SnapMirror.

.Pasos
* *Convertir una relación asíncrona de SnapMirror a una relación síncrona de SnapMirror*
+
.. Desde el clúster de destino, elimine la relación asíncrona de SnapMirror:
+
`snapmirror delete -destination-path <SVM:volume>`

+
[listing]
----
cluster2::>snapmirror delete -destination-path vs1_dr:vol1
----
.. En el clúster de origen, libere la relación de SnapMirror sin eliminar las copias de Snapshot comunes:
+
`snapmirror release -relationship-info-only true -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster1::>snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----
.. Desde el clúster de destino, cree una relación síncrona de SnapMirror:
+
`snapmirror create -source-path _src_SVM:src_volume_ -destination-path <destination_SVM>:<destination_volume> -policy sync-mirror`

+
[listing]
----
cluster2::>snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy sync
----
.. Resincronice la relación síncrona de SnapMirror:
+
`snapmirror resync -destination-path <destination_SVM:destination_volume>`

+
[listing]
----
cluster2::>snapmirror resync -destination-path vs1_dr:vol1
----


* *Convertir una relación síncrona de SnapMirror a una relación asíncrona de SnapMirror*
+
.. Desde el clúster de destino, desactive la relación síncrona de SnapMirror existente:
+
`snapmirror quiesce -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror quiesce -destination-path vs1_dr:vol1
----
.. Desde el clúster de destino, elimine la relación asíncrona de SnapMirror:
+
`snapmirror delete -destination-path <SVM:volume>`

+
[listing]
----
cluster2::>snapmirror delete -destination-path vs1_dr:vol1
----
.. En el clúster de origen, libere la relación de SnapMirror sin eliminar las copias de Snapshot comunes:
+
`snapmirror release -relationship-info-only true -destination-path <destination_SVM:destination_volume>`

+
[listing]
----
cluster1::>snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----
.. Desde el clúster de destino, cree una relación asíncrona de SnapMirror:
+
`snapmirror create -source-path _src_SVM:src_volume_ -destination-path <destination_SVM:destination_volume> -policy MirrorAllSnapshots`

+
[listing]
----
cluster2::>snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy sync
----
.. Resincronice la relación síncrona de SnapMirror:
+
`snapmirror resync -destination-path <destination_SVM:destination_volume>`

+
[listing]
----
cluster2::>snapmirror resync -destination-path vs1_dr:vol1
----




.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["snapmirror create"^]

