---
permalink: data-protection/convert-snapmirror-version-flexible-task.html 
sidebar: sidebar 
keywords: convert, exist, dp-type, relationship, xdp 
summary: Puede convertir fácilmente una relación de tipo de DP existente a XDP para poder aprovechar las ventajas de la flexibilidad de versión de SnapMirror. 
---
= Convierta una relación de tipo DP existente a XDP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si actualiza a ONTAP 9.12.1 o una versión posterior, debe convertir las relaciones de tipo DP a XDP antes de realizar la actualización. ONTAP 9.12.1 y las versiones posteriores no admiten relaciones de tipo DP. Puede convertir fácilmente una relación de tipo de DP existente a XDP para poder aprovechar las ventajas de la flexibilidad de versión de SnapMirror.

.Acerca de esta tarea
* SnapMirror no convierte automáticamente las relaciones de tipo DP existentes a XDP. Para convertir la relación, debe romper y eliminar la relación existente, crear una nueva relación XDP y volver a sincronizar la relación. Para obtener información previa, consulte link:version-flexible-snapmirror-default-concept.html["XDP sustituye a DP como la opción predeterminada de SnapMirror"].
* Al planificar la conversión, tenga en cuenta que la preparación en segundo plano y la fase de almacenamiento de datos de una relación de SnapMirror para XDP pueden llevar mucho tiempo. No es poco frecuente ver la relación de SnapMirror que informa sobre el estado "preparación" para un periodo de tiempo prolongado.


[NOTE]
====
Después de convertir un tipo de relación de SnapMirror de DP a XDP, las configuraciones relacionadas con el espacio, como la configuración automática de tamaño y la garantía de espacio, ya no se replican en el destino.

====
.Pasos
. En el clúster de destino, compruebe que la relación SnapMirror sea del tipo DP, que el estado de mirroring sea en SnapMirror, que el estado de la relación sea inactivo y que la relación esté en buen estado:
+
[source, cli]
----
snapmirror show -destination-path _SVM:volume_|_cluster://SVM/volume_
----
+
En el siguiente ejemplo, se muestra el resultado de `snapmirror show` comando:

+
[listing]
----
cluster_dst::>snapmirror show -destination-path svm_backup:volA_dst

Source Path: svm1:volA
Destination Path: svm_backup:volA_dst
Relationship Type: DP
SnapMirror Schedule: -
Tries Limit: -
Throttle (KB/sec): unlimited
Mirror State: Snapmirrored
Relationship Status: Idle
Transfer Snapshot: -
Snapshot Progress: -
Total Progress: -
Snapshot Checkpoint: -
Newest Snapshot: snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
Newest Snapshot Timestamp: 06/27 10:00:55
Exported Snapshot: snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
Exported Snapshot Timestamp: 06/27 10:00:55
Healthy: true
----
+
[NOTE]
====
Puede que le resulte útil conservar una copia del `snapmirror show` salida de comando para realizar un seguimiento de la configuración de relaciones existente.

====
. En los volúmenes de origen y destino, asegúrese de que ambos volúmenes tengan una copia Snapshot común:
+
[source, cli]
----
volume snapshot show -vserver _SVM_ -volume _volume_
----
+
En el siguiente ejemplo se muestra el `volume snapshot show` salida para el zoco y los volúmenes de destino:

+
[listing]
----
cluster_src:> volume snapshot show -vserver vsm1 -volume volA
---Blocks---
Vserver Volume Snapshot State Size Total% Used%
-------- ------- ------------------------------- -------- -------- ------ -----
svm1 volA
weekly.2014-06-09_0736 valid 76KB 0% 28%
weekly.2014-06-16_1305 valid 80KB 0% 29%
daily.2014-06-26_0842 valid 76KB 0% 28%
hourly.2014-06-26_1205 valid 72KB 0% 27%
hourly.2014-06-26_1305 valid 72KB 0% 27%
hourly.2014-06-26_1405 valid 76KB 0% 28%
hourly.2014-06-26_1505 valid 72KB 0% 27%
hourly.2014-06-26_1605 valid 72KB 0% 27%
daily.2014-06-27_0921 valid 60KB 0% 24%
hourly.2014-06-27_0921 valid 76KB 0% 28%
snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
valid 44KB 0% 19%
11 entries were displayed.


cluster_dest:> volume snapshot show -vserver svm_backup -volume volA_dst
---Blocks---
Vserver Volume Snapshot State Size Total% Used%
-------- ------- ------------------------------- -------- -------- ------ -----
svm_backup volA_dst
weekly.2014-06-09_0736 valid 76KB 0% 30%
weekly.2014-06-16_1305 valid 80KB 0% 31%
daily.2014-06-26_0842 valid 76KB 0% 30%
hourly.2014-06-26_1205 valid 72KB 0% 29%
hourly.2014-06-26_1305 valid 72KB 0% 29%
hourly.2014-06-26_1405 valid 76KB 0% 30%
hourly.2014-06-26_1505 valid 72KB 0% 29%
hourly.2014-06-26_1605 valid 72KB 0% 29%
daily.2014-06-27_0921 valid 60KB 0% 25%
hourly.2014-06-27_0921 valid 76KB 0% 30%
snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
----
. Para garantizar que las actualizaciones programadas no se ejecuten durante la conversión, desactive la relación de tipo DP existente:
+
[source, cli]
----
snapmirror quiesce -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...
----
+
Para obtener una sintaxis completa del comando, consulte link:https://docs.netapp.com/us-en/ontap-cli-9131//snapmirror-quiesce.html["página de manual"^].

+
[NOTE]
====
Se debe ejecutar este comando desde la SVM de destino o el clúster de destino.

====
+
En el siguiente ejemplo, se pausa la relación entre el volumen de origen `volA` encendido `svm1` y el volumen de destino `volA_dst` encendido `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror quiesce -destination-path svm_backup:volA_dst
----
. Rompa la relación de tipo de DP existente:
+
[source, cli]
----
snapmirror break -destination-path _SVM:volume_|_cluster://SVM/volume_, ...
----
+
Para obtener una sintaxis completa del comando, consulte link:https://docs.netapp.com/us-en/ontap-cli-9131//snapmirror-break.html["página de manual"^].

+
[NOTE]
====
Se debe ejecutar este comando desde la SVM de destino o el clúster de destino.

====
+
En el siguiente ejemplo, se rompe la relación entre el volumen de origen `volA` encendido `svm1` y el volumen de destino `volA_dst` encendido `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror break -destination-path svm_backup:volA_dst
----
. Si la eliminación automática de las copias Snapshot está habilitada en el volumen de destino, desactívelo:
+
`volume snapshot autodelete modify -vserver _SVM_ -volume _volume_ -enabled false`

+
En el ejemplo siguiente se deshabilita la eliminación automática de copias Snapshot en el volumen de destino `volA_dst`:

+
[listing]
----
cluster_dst::> volume snapshot autodelete modify -vserver svm_backup -volume volA_dst -enabled false
----
. Elimine la relación de tipo de DP existente:
+
[source, cli]
----
snapmirror delete -destination-path _SVM:volume_|_cluster://SVM/volume_, ...
----
+
Para obtener una sintaxis completa del comando, consulte link:https://docs.netapp.com/us-en/ontap-cli-9131//snapmirror-delete.html["página de manual"^].

+
[NOTE]
====
Se debe ejecutar este comando desde la SVM de destino o el clúster de destino.

====
+
En el siguiente ejemplo, se elimina la relación entre el volumen de origen `volA` encendido `svm1` y el volumen de destino `volA_dst` encendido `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror delete -destination-path svm_backup:volA_dst
----
. Puede utilizar la salida que ha retenido de `snapmirror show` Comando para crear la nueva relación de tipo XDP:
+
[source, cli]
----
snapmirror create -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ... -type XDP -schedule _schedule_ -policy _policy_
----
+
La nueva relación debe usar el mismo volumen de origen y destino. Para obtener una sintaxis de comando completa, consulte la página man.

+
[NOTE]
====
Se debe ejecutar este comando desde la SVM de destino o el clúster de destino.

====
+
El siguiente ejemplo crea una relación de recuperación ante desastres de SnapMirror entre el volumen de origen `volA` encendido `svm1` y el volumen de destino `volA_dst` encendido `svm_backup` con el valor predeterminado `MirrorAllSnapshots` política:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1:volA -destination-path svm_backup:volA_dst
-type XDP -schedule my_daily -policy MirrorAllSnapshots
----
. Resincronización de los volúmenes de origen y destino:
+
[source, cli]
----
snapmirror resync -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...
----
+
Para mejorar el tiempo de resincronización, puede utilizar el `-quick-resync` opcional, pero debe tener en cuenta que se pueden perder ahorros en eficiencia del almacenamiento. Para obtener una sintaxis completa del comando, consulte la página man: link:https://docs.netapp.com/us-en/ontap-cli-9131/snapmirror-resync.html#parameters.html["Comando SnapMirror resync"^].

+
[NOTE]
====
Se debe ejecutar este comando desde la SVM de destino o el clúster de destino. Aunque la resincronización no requiere una transferencia básica, puede requerir mucho tiempo. Puede que desee ejecutar la resincronización en horas de menor actividad.

====
+
En el siguiente ejemplo, vuelva a establecer la relación entre el volumen de origen `volA` encendido `svm1` y el volumen de destino `volA_dst` encendido `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. Si ha deshabilitado la eliminación automática de copias Snapshot, vuelva a habilitarla:
+
[source, cli]
----
volume snapshot autodelete modify -vserver _SVM_ -volume _volume_ -enabled true
----


.Después de terminar
. Utilice la `snapmirror show` Comando para verificar que la relación de SnapMirror se ha creado.
. Una vez que el volumen de destino de SnapMirror XDP comienza a actualizar las copias snapshot tal como se define en la política de SnapMirror, utilice el resultado de `snapmirror list-destinations` Comando del clúster de origen para mostrar la nueva relación de XDP de SnapMirror.

