---
permalink: data-protection/convert-mode-snapmirror-synchronous-task.html 
sidebar: sidebar 
keywords: convert, mode, snapmirror, synchronous, relationship 
summary: A partir de ONTAP 9.5, se admiten las relaciones síncronas de SnapMirror. Puede convertir el modo de una relación síncrona de SnapMirror de StrictSync a Sync o viceversa. 
---
= Convierta el modo de una relación síncrona de ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.5, se admiten las relaciones síncronas de SnapMirror. Puede convertir el modo de una relación síncrona de SnapMirror de StrictSync a Sync o viceversa.

.Acerca de esta tarea
No puede modificar la política de una relación síncrona de SnapMirror para convertir su modo.

.Pasos
. Desde el clúster de destino, desactive la relación síncrona de SnapMirror existente:
+
`snapmirror quiesce -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror quiesce -destination-path vs1_dr:vol1
----
. Desde el clúster de destino, elimine la relación síncrona de SnapMirror existente:
+
`snapmirror delete -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror delete -destination-path vs1_dr:vol1
----
. En el clúster de origen, libere la relación de SnapMirror sin eliminar las copias de Snapshot comunes:
+
`snapmirror release -relationship-info-only true -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster1::> snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----
. Desde el clúster de destino, cree una relación síncrona de SnapMirror especificando el modo en el que desea convertir la relación síncrona de SnapMirror:
+
`snapmirror create -source-path vs1:vol1 -destination-path <destination_SVM>:<destination_volume> -policy Sync|StrictSync`

+
[listing]
----
cluster2::> snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy Sync
----
. En el clúster de destino, resincronice la relación SnapMirror:
+
`snapmirror resync -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror resync -destination-path vs1_dr:vol1
----


.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["snapmirror create"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["snapmirror elimina"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["Snapmirror en reposo"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["versión de snapmirror"^]

