---
permalink: data-protection/create-load-sharing-mirror-task.html 
sidebar: sidebar 
keywords: create, initialize, load-sharing, mirror, relationship 
summary: 'Debe crear un reflejo de uso compartido de carga (LSM) para cada volumen raíz del clúster. Puede crear el LSM en cualquier nodo distinto al que contiene el volumen raíz, como el nodo del partner en un par de alta disponibilidad o, preferiblemente, en un par de alta disponibilidad diferente. Para un clúster de dos nodos, debe crear el LSM en el compañero del nodo con el volumen raíz.' 
---
= Crear e inicializar relaciones de reflejos de uso compartido de carga de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe crear un reflejo de uso compartido de carga (LSM) para cada volumen raíz de SVM que sirva datos NAS en el clúster. En el caso de los clústeres formados por dos o más pares de alta disponibilidad, debe considerar los reflejos de uso compartido de carga de los volúmenes raíz de SVM para garantizar que los clientes sigan accesible el espacio de nombres en caso de que esto siga siendo
Los dos nodos de una pareja de alta disponibilidad fallan. Los reflejos de uso compartido de carga no son adecuados para clústeres que constan de una única pareja de alta disponibilidad.

.Acerca de esta tarea
Si crea un LSM en el mismo nodo y el nodo no está disponible, tendrá un único punto de error y no tendrá una segunda copia para garantizar que los datos sigan siendo accesibles para los clientes. Pero cuando crea el LSM en un nodo distinto al que contiene el volumen raíz o en un par de alta disponibilidad diferente, todavía se puede acceder a los datos en caso de una interrupción del servicio.

Por ejemplo, en un clúster de cuatro nodos con volumen raíz en tres nodos:

* Para el volumen raíz en el nodo 1 de alta disponibilidad, cree el LSM en el nodo 1 de alta disponibilidad 2 o el nodo 2 de alta disponibilidad.
* Para el volumen raíz en el nodo de alta disponibilidad 1 2, cree el LSM en el nodo de alta disponibilidad 2 1 o el nodo de alta disponibilidad 2.
* Para el volumen raíz en el nodo 1 de alta disponibilidad 2, cree el LSM en el nodo 1 de alta disponibilidad o el nodo 2 de alta disponibilidad 1.


.Pasos
. Crear un volumen de destino para el LSM:
+
[source, cli]
----
volume create -vserver <SVM> -volume <volume> -aggregate <aggregate> -type DP -size <size>
----
+
El tamaño del volumen de destino debe ser igual o mayor que el del volumen raíz.

+
Se recomienda nombrar el volumen raíz y el volumen de destino con sufijos, como `_root` y.. `_m1`.

+
Obtenga más información sobre `volume create` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["Referencia de comandos de la ONTAP"^].

+
En el siguiente ejemplo, se crea un volumen de reflejos de uso compartido de carga para el volumen raíz `svm1_root` pulg `cluster_src`:

+
[listing]
----
cluster_src:> volume create -vserver svm1 -volume svm1_m1 -aggregate aggr_1 -size 1gb -state online -type DP
----
. link:create-replication-job-schedule-task.html["Cree un programa de trabajo de replicaciones"].
. Crear una relación de mirroring de uso compartido de carga entre el volumen raíz de SVM y el volumen de destino para LSM:
+
[source, cli]
----
snapmirror create -source-path <SVM:volume> -destination-path <SVM:volume> -type LS -schedule <schedule>
----
+
Obtenga más información sobre `snapmirror create` en el link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["Referencia de comandos de la ONTAP"^].

+
En el siguiente ejemplo, se crea una relación de reflejo de uso compartido de la carga entre el volumen raíz `svm1_root` y el volumen reflejado de uso compartido de la carga `svm1_m1`:

+
[listing]
----
cluster_src::> snapmirror create -source-path svm1:svm1_root -destination-path svm1:svm1_m1 -type LS -schedule hourly
----
+
El atributo type del reflejo de carga compartida cambia de `DP` para `LS`.

. Inicialice el reflejo de uso compartido de carga:
+
[source, cli]
----
snapmirror initialize-ls-set -source-path <SVM:volume>
----
+
Obtenga más información sobre `snapmirror initialize` en el link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["Referencia de comandos de la ONTAP"^].

+
En el ejemplo siguiente se inicializa el reflejo de uso compartido de carga para el volumen raíz `svm1_root`:

+
[listing]
----
cluster_src::> snapmirror initialize-ls-set -source-path svm1:svm1_root
----

