---
permalink: data-protection/define-schedule-create-local-copy-destination-task.html 
sidebar: sidebar 
keywords: define, schedule, create, local copy, destination 
summary: Para las relaciones de SnapVault y de replicación unificada, puede protegerse contra la posibilidad de que una copia Snapshot actualizada se dañe al crear una copia de la última copia Snapshot transferida en el destino. Esta «copia local» se conserva independientemente de las reglas de retención en el origen, por lo que, aunque la copia Snapshot que originalmente transfirió SnapMirror ya no esté disponible en el origen, habrá una copia disponible en el destino. 
---
= Defina una programación para crear una copia local en el destino con ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para las relaciones de SnapVault y de replicación unificada, puede protegerse contra la posibilidad de que una copia Snapshot actualizada se dañe al crear una copia de la última copia Snapshot transferida en el destino. Esta «copia local» se conserva independientemente de las reglas de retención del origen, de modo que, aunque la copia Snapshot transferida mediante SnapMirror ya no esté disponible en el origen, dicha copia estará disponible en el destino.

.Acerca de esta tarea
Se especifica la programación para crear una copia local en el `-schedule` opción de `snapmirror policy add-rule` comando.

.Paso
. Definir una programación para crear una copia local en el destino:
+
`snapmirror policy add-rule -vserver _SVM_ -policy _policy_for_rule_ -snapmirror-label _snapmirror-label_ -schedule _schedule_`

+
Obtenga más información sobre `snapmirror policy add-rule` en el link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["Referencia de comandos de la ONTAP"^]. Para ver un ejemplo de cómo crear un programa de trabajo, consulte link:create-replication-job-schedule-task.html["Crear una programación de trabajo de replicación"].

+
En el ejemplo siguiente se añade una programación para crear una copia local en los valores predeterminados `MirrorAndVault` política:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy MirrorAndVault -snapmirror-label my_monthly -schedule my_monthly
----
+
En el siguiente ejemplo, se agrega una programación para crear una copia local en el personalizado `my_unified` política:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy my_unified -snapmirror-label my_monthly -schedule my_monthly
----

