---
permalink: data-protection/define-rule-policy-task.html 
sidebar: sidebar 
keywords: define, rule, policy, data protection 
summary: 'Para las políticas personalizadas con el tipo de política "vault" o "mirror-vault", debe definir al menos una regla que determine qué instantáneas se transfieren durante la inicialización y la actualización. También puede definir reglas para políticas predeterminadas con el tipo de política "vault" o "mirror-vault".' 
---
= Defina una regla para una política de ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para las políticas personalizadas con el `vault` tipo de política OR `mirror-vault`, debe definir al menos una regla que determine qué instantáneas se transfieren durante la inicialización y actualización. También puede definir reglas para políticas predeterminadas con el `vault` tipo de política o. `mirror-vault`

.Acerca de esta tarea
Cada política con el `vault` tipo de política OR `mirror-vault` debe tener una regla que especifique las instantáneas que se van a replicar. La regla `bi-monthly`, por ejemplo, indica que sólo se deben replicar las instantáneas asignadas a la etiqueta SnapMirror `bi-monthly`. La etiqueta de SnapMirror se especifica al configurar la política de Snapshot en el origen.

Cada tipo de política está asociado a una o más reglas definidas por el sistema. Estas reglas se asignan automáticamente a una directiva cuando se especifica su tipo de directiva. La siguiente tabla muestra las reglas definidas por el sistema.

[cols="3*"]
|===


| Regla definida por el sistema | Se utiliza en tipos de políticas | Resultado 


 a| 
sm_creado
 a| 
Reflejo asíncrono, reflejo-almacén, sincronización, StrictSync
 a| 
Una instantánea creada por SnapMirror se transfiere en el momento de la inicialización y la actualización.



 a| 
all_source_snapshots
 a| 
reflejo asíncrono
 a| 
Las nuevas instantáneas del origen se transfieren durante la inicialización y la actualización.



 a| 
todos los días
 a| 
almacén, reflejo-almacén
 a| 
Las nuevas instantáneas en el origen con la etiqueta SnapMirror `daily` se transfieren durante la inicialización y la actualización.



 a| 
semanal
 a| 
almacén, reflejo-almacén
 a| 
Las nuevas instantáneas en el origen con la etiqueta SnapMirror `weekly` se transfieren durante la inicialización y la actualización.



 a| 
mensual
 a| 
mirror-vault
 a| 
Las nuevas instantáneas en el origen con la etiqueta SnapMirror `monthly` se transfieren durante la inicialización y la actualización.



 a| 
coherente con la aplicación
 a| 
Sync, StrictSync
 a| 
Las copias Snapshot que tienen la etiqueta SnapMirror `app_consistent` en el origen se replican de forma síncrona en el destino. Compatible a partir de ONTAP 9,7.

|===
Excepto para el tipo de política «'duplicación asíncrona'», puede especificar reglas adicionales según sea necesario, para directivas predeterminadas o personalizadas. Por ejemplo:

* Para la política predeterminada `MirrorAndVault`, puede crear una regla llamada `bi-monthly` para que coincida con las instantáneas en el origen con `bi-monthly` la etiqueta SnapMirror.
* Para una política personalizada con el `mirror-vault` tipo de política, puede crear una regla llamada `bi-weekly` para hacer coincidir las instantáneas en el origen con `bi-weekly` la etiqueta SnapMirror.


.Paso
. Definir una regla para una directiva:
+
`snapmirror policy add-rule -vserver _SVM_ -policy _policy_for_rule_ -snapmirror-label _snapmirror-label_ -keep _retention_count_`

+
En el siguiente ejemplo, se agrega una regla con la etiqueta SnapMirror `bi-monthly` a la `MirrorAndVault` política predeterminada:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy MirrorAndVault -snapmirror-label bi-monthly -keep 6
----
+
En el siguiente ejemplo, se agrega una regla con la etiqueta SnapMirror `bi-weekly` a la `my_snapvault` política personalizada:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy my_snapvault -snapmirror-label bi-weekly -keep 26
----
+
En el siguiente ejemplo, se agrega una regla con la etiqueta SnapMirror `app_consistent` a la `Sync` política personalizada:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy Sync -snapmirror-label app_consistent -keep 1
----
+
Obtenga más información sobre `snapmirror policy add-rule` en el link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["Referencia de comandos del ONTAP"^].

+
Luego, es posible replicar copias de Snapshot del clúster de origen que coincidan con la siguiente etiqueta de SnapMirror:

+
[listing]
----
cluster_src::> snapshot create -vserver vs1 -volume vol1 -snapshot snapshot1 -snapmirror-label app_consistent
----

