---
permalink: data-protection/dpo-systems-feature-enhancements-reference.html 
sidebar: sidebar 
keywords: dpo, systems, feature, enhancements, snapmirror, dp optimized, optimised, backoff, back off, deduplication, deduplicate, snapshot blocks, donors, compact, flexvol, license 
summary: 'A partir de ONTAP 9.6, el número máximo de volúmenes FlexVol admitidos aumenta cuando se instala la licencia DP_Optimized (DPO). A partir de la versión 9,4 de ONTAP, los sistemas con licencia DPO admiten el respaldo de SnapMirror, la deduplicación en segundo plano entre volúmenes, el uso de bloques de instantáneas como donantes y la compactación.' 
---
= Los sistemas DPO ofrecen mejoras
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.6, el número máximo de volúmenes FlexVol admitidos aumenta cuando se instala la licencia DP_Optimized (DPO). A partir de la versión 9,4 de ONTAP, los sistemas con licencia DPO admiten el respaldo de SnapMirror, la deduplicación en segundo plano entre volúmenes, el uso de bloques de instantáneas como donantes y la compactación.

A partir de ONTAP 9.6, se ha incrementado el número máximo admitido de volúmenes FlexVol en sistemas secundarios o de protección de datos, lo que permite escalar hasta 2,500 volúmenes FlexVol por nodo o hasta 5,000 en modo de conmutación por error. El aumento de los volúmenes de FlexVol se habilita con el link:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html#data-protection-optimized-license["Licencia DP_Optimized (DPO)"]. A. link:https://docs.netapp.com/us-en/ontap/system-admin/manage-license-task.html#view-details-about-a-license["Licencia de SnapMirror"] también se requiere en los nodos de origen y destino.

A partir de ONTAP 9.4, se realizan las siguientes mejoras en las funciones de los sistemas DPO:

* Backoff de SnapMirror: En sistemas DPO, el tráfico de replicación tiene la misma prioridad que se da a las cargas de trabajo del cliente.
+
La funcionalidad de backup de SnapMirror está deshabilitada de forma predeterminada en los sistemas DPO.

* Deduplicación en segundo plano de volumen y deduplicación en segundo plano entre volúmenes: Se habilitan la deduplicación en segundo plano de volúmenes y la deduplicación en segundo plano entre volúmenes en sistemas DPO.
+
Puede ejecutar el `storage aggregate efficiency cross-volume-dedupe start -aggregate _aggregate_name_ -scan-old-data true` comando para deduplicar los datos existentes. La práctica recomendada es ejecutar el comando durante las horas de menor actividad para reducir el impacto en el rendimiento.

* Mayor ahorro al utilizar bloques de instantáneas como donadores: Los bloques de datos que no están disponibles en el sistema de archivos activos, pero atrapados en snapshots se usan como donadores para la deduplicación de volumen.
+
Los nuevos datos se pueden deduplicar con los datos atrapados en las copias snapshot, lo que también comparte eficazmente los bloques de copias snapshot. El mayor espacio donante permite un mayor ahorro, especialmente cuando el volumen tiene un gran número de instantáneas.

* Compactación: La compactación de datos está habilitada de forma predeterminada en los volúmenes DPO.

