---
permalink: data-protection/example-snapshot-copies-exceed-reserve-concept.html 
sidebar: sidebar 
keywords: delete, protected, files, less file space 
summary: Una copia snapshot señala a un bloque incluso después de eliminar el archivo que utilizó el bloque. Esto explica por qué una reserva de copia snapshot agotada puede dar lugar al resultado contrario-intuitivo en el que la eliminación de todo un sistema de archivos da como resultado menos espacio disponible que el sistema de archivos ocupado. 
---
= La eliminación de archivos protegidos puede reducir el espacio de archivos de lo esperado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una copia snapshot señala a un bloque incluso después de eliminar el archivo que utilizó el bloque. Esto explica por qué una reserva de copia snapshot agotada puede dar lugar al resultado contrario-intuitivo en el que la eliminación de todo un sistema de archivos da como resultado menos espacio disponible que el sistema de archivos ocupado.

Observe el siguiente ejemplo. Antes de eliminar cualquier archivo, el `df` el resultado del comando es el siguiente:

[listing]
----

Filesystem          kbytes  used    avail  capacity
/vol/vol0/          3000000 3000000 0       100%
/vol/vol0/.snapshot 1000000 500000  500000   50%
----
Tras eliminar todo el sistema de archivos y realizar una copia snapshot del volumen, la `df` el comando genera la siguiente salida:

[listing]
----

Filesystem          kbytes  used    avail  capacity
/vol/vol0/          3000000 2500000 500000   83%
/vol/vol0/.snapshot 1000000 3500000 0       350%
----
Tal y como se muestra en el resultado, ahora los 3 GB completos que utilizaba el sistema de archivos activo son utilizados por las copias snapshot, además de los 0.5 GB utilizados antes de la eliminación.

Como el espacio en disco utilizado por las copias snapshot supera ahora la reserva de copia snapshot, el desbordamiento de 2.5 GB de «píldoras» en el espacio reservado para los archivos activos, dejándole con 0.5 GB de espacio libre para los archivos en los que razonablemente se podrían haber esperado 3 GB.
