---
permalink: data-protection/example-snapshot-copies-exceed-reserve-concept.html 
sidebar: sidebar 
keywords: delete, protected, files, less file space 
summary: Una instantánea apunta a un bloque incluso después de eliminar el archivo que utilizó el bloque. Esto explica por qué una reserva de instantáneas agotada podría conducir a un resultado contraintuitivo en el que la eliminación de un sistema de archivos completo da como resultado menos espacio disponible que el sistema de archivos ocupado. 
---
= La eliminación de archivos protegidos puede reducir el espacio de archivos de lo esperado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una instantánea apunta a un bloque incluso después de eliminar el archivo que utilizó el bloque. Esto explica por qué una reserva de instantáneas agotada podría conducir a un resultado contraintuitivo en el que la eliminación de un sistema de archivos completo da como resultado menos espacio disponible que el sistema de archivos ocupado.

Observe el siguiente ejemplo. Antes de eliminar cualquier archivo, el `df` el resultado del comando es el siguiente:

[listing]
----

Filesystem          kbytes  used    avail  capacity
/vol/vol0/          3000000 3000000 0       100%
/vol/vol0/.snapshot 1000000 500000  500000   50%
----
Después de eliminar todo el sistema de archivos y hacer una instantánea del volumen, `df` el comando genera la siguiente salida:

[listing]
----

Filesystem          kbytes  used    avail  capacity
/vol/vol0/          3000000 2500000 500000   83%
/vol/vol0/.snapshot 1000000 3500000 0       350%
----
Como se muestra en la salida, los 3 GB completos utilizados anteriormente por el sistema de archivos activo ahora están siendo utilizados por las instantáneas, además de los 0,5 GB utilizados antes de la eliminación.

Debido a que el espacio en disco utilizado por las instantáneas ahora excede la reserva de instantáneas, el desbordamiento de 2,5 GB “pastillas” en el espacio reservado para los archivos activos, dejándole con 0,5 GB de espacio libre para los archivos donde razonablemente podría haber esperado 3 GB.
