---
permalink: data-protection/exclude-volumes-svm-replication-task.html 
sidebar: sidebar 
keywords: exclude, volumes, svm replication 
summary: De forma predeterminada, se replican todos los volúmenes de datos RW de la SVM de origen. Si no desea proteger todos los volúmenes de la SVM de origen, puede usar la opción -vserver-dr-protection unprotected del comando volume modify para excluir volúmenes de la replicación de SVM. 
---
= Excluye los volúmenes de una relación de recuperación ante desastres de SVM de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
De forma predeterminada, se replican todos los volúmenes de datos RW de la SVM de origen. Si no desea proteger todos los volúmenes de la SVM de origen, puede usar la `-vserver-dr-protection unprotected` opción de `volume modify` Comando para excluir volúmenes de la replicación de SVM.

.Pasos
. Excluya un volumen de la replicación SVM:
+
`volume modify -vserver _SVM_ -volume _volume_ -vserver-dr-protection unprotected`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
En el siguiente ejemplo, se excluye el volumen `volA_src` A partir de la replicación de SVM:

+
[listing]
----
cluster_src::> volume modify -vserver SVM1 -volume volA_src -vserver-dr-protection unprotected
----
+
Si más adelante desea incluir un volumen en la replicación de SVM que originalmente excluyó, ejecute el siguiente comando:

+
`volume modify -vserver _SVM_ -volume _volume_ -vserver-dr-protection protected`

+
En el siguiente ejemplo, se incluye el volumen `volA_src` En la replicación de SVM:

+
[listing]
----
cluster_src::> volume modify -vserver SVM1 -volume volA_src -vserver-dr-protection protected
----
. Cree e inicialice la relación de replicación de SVM como se describe en link:replicate-entire-svm-config-task.html["Replicar una configuración de SVM completa"].

