---
permalink: data-protection/exclude-network-name-service-svm-replication-task.html 
sidebar: sidebar 
keywords: exclude, network, name service, other settings, svm replication 
summary: Puede usar la opción -Identity-preserve false del comando snapmirror create para replicar solo los volúmenes y las configuraciones de seguridad de una SVM. También se conservan algunos ajustes de protocolo y servicio de nombres. 
---
= Excluya la red, el servicio de nombres y otras configuraciones de la replicación de SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `-identity-preserve false` opción de `snapmirror create` Comando para replicar solo los volúmenes y las configuraciones de seguridad de una SVM. También se conservan algunos ajustes de protocolo y servicio de nombres.

.Acerca de esta tarea
Para obtener una lista de los ajustes de protocolo y servicio de nombres conservados, consulte link:snapmirror-svm-replication-concept.html#configurations-replicated-in-svm-dr-relationships["Configuraciones replicadas en relaciones de recuperación ante desastres de SVM"].

Para obtener una sintaxis de comando completa, consulte la página man.

.Antes de empezar
Las SVM y los clústeres de origen y destino deben tener una relación entre iguales.

Para obtener más información, consulte link:../peering/create-cluster-relationship-93-later-task.html["Cree una relación de paridad entre clústeres"] y.. link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["Cree una relación de interconexión de clústeres entre iguales de SVM"].

.Pasos
. Cree una SVM de destino:
+
`vserver create -vserver _SVM_ -subtype dp-destination`

+
El nombre de SVM debe ser único en los clústeres de origen y destino.

+
En el ejemplo siguiente se crea una SVM de destino llamada `svm_backup`:

+
[listing]
----
cluster_dst:> vserver create -vserver svm_backup -subtype dp-destination
----
. En el clúster de destino, cree una relación entre iguales de SVM mediante el `vserver peer create` comando.
+
Para obtener más información, consulte link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["Cree una relación de interconexión de clústeres entre iguales de SVM"].

. Crear una programación de trabajo de replicación:
+
`job schedule cron create -name _job_name_ -month _month_ -dayofweek _day_of_week_ -day _day_of_month_ -hour _hour_ -minute _minute_`

+
Para `-month`, `-dayofweek`, y. `-hour`, puede especificar `all` para ejecutar el trabajo cada mes, día de la semana y hora, respectivamente.

+
[NOTE]
====
La programación mínima admitida (RPO) para volúmenes FlexVol en una relación de SnapMirror de SVM es de 15 minutos. La programación mínima admitida (RPO) para volúmenes FlexGroup en una relación de SnapMirror de SVM es de 30 minutos.

====
+
En el ejemplo siguiente se crea una programación de trabajo denominada `my_weekly` Es decir, los sábados a las 3:00 horas:

+
[listing]
----
cluster_dst::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----
. Cree una relación de replicación que excluya la red, el servicio de nombres y otras opciones de configuración:
+
`snapmirror create -source-path _SVM_: -destination-path _SVM_: -type DP|XDP -schedule schedule -policy policy -identity-preserve false`

+
[NOTE]
====
Después del nombre de la SVM en el, se deben introducir dos puntos (:) `-source-path` y.. `-destination-path` opciones. Vea los ejemplos a continuación.    Se debe ejecutar este comando desde la SVM de destino o el clúster de destino.

====
+
En el siguiente ejemplo se crea una relación de recuperación ante desastres de SnapMirror con los valores predeterminados `MirrorAllSnapshots` política. La relación excluye la red, el servicio de nombres y otras opciones de configuración de la replicación de SVM:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy MirrorAllSnapshots -identity-preserve false
----
+
En el ejemplo siguiente se crea una relación de replicación unificada con la opción predeterminada `MirrorAndVault` política. La relación excluye la red, el servicio de nombres y otras opciones de configuración:

+
[listing]
----
cluster_dst:> snapmirror create svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy MirrorAndVault -identity-preserve false
----
+
Suponiendo que ha creado una directiva personalizada con el tipo de directiva `async-mirror`, En el siguiente ejemplo se crea una relación de recuperación ante desastres de SnapMirror. La relación excluye la red, el servicio de nombres y otras opciones de configuración de la replicación de SVM:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy my_mirrored -identity-preserve false
----
+
Suponiendo que ha creado una directiva personalizada con el tipo de directiva `mirror-vault`, en el ejemplo siguiente se crea una relación de replicación unificada. La relación excluye la red, el servicio de nombres y otras opciones de configuración de la replicación de SVM:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy my_unified -identity-preserve false
----
. Detenga la SVM de destino:
+
`vserver stop`

+
`_SVM name_`

+
En el ejemplo siguiente se detiene una SVM de destino denominada dvs1:

+
[listing]
----
destination_cluster::> vserver stop -vserver dvs1
----
. Si utiliza SMB, también debe configurar un servidor SMB.
+
Consulte link:create-smb-server-task.html["Solo SMB: Crear un servidor SMB"].

. En la SVM de destino o el clúster de destino, inicialice la relación de replicación de SVM:
+
`snapmirror initialize -source-path _SVM_name_: -destination-path _SVM_name_:`



.Después de terminar
Es necesario configurar la red y los protocolos en la SVM de destino para acceder a los datos en caso de que se produzca un desastre.
