---
permalink: data-protection/initialize-replication-relationship-task.html 
sidebar: sidebar 
keywords: initialize, replication, relationship, snapmirror, snap mirror, synchronous, transfer, snapshot copy, 
summary: 'Para todos los tipos de relaciones, la inicialización realiza una transferencia básica: Realiza una copia Snapshot del volumen de origen y, a continuación, transfiere esa copia y todos los bloques de datos que hace referencia al volumen de destino. De lo contrario, el contenido de la transferencia depende de la política.' 
---
= Inicializar una relación de replicación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para todos los tipos de relaciones, la inicialización realiza una _transferencia_de base_: Realiza una copia Snapshot del volumen de origen y, a continuación, transfiere esa copia y todos los bloques de datos a los que hace referencia al volumen de destino. De lo contrario, el contenido de la transferencia depende de la política.

.Lo que necesitará
Las SVM y los clústeres de origen y destino deben tener una relación entre iguales.

link:../peering/index.html["Relaciones entre iguales de clústeres y SVM"]

.Acerca de esta tarea
La inicialización puede requerir mucho tiempo. Puede ser conveniente ejecutar la transferencia básica en horas de menor actividad.

A partir de ONTAP 9.5, se admiten las relaciones síncronas de SnapMirror.

.Paso
. Inicializar una relación de replicación:
+
`snapmirror initialize -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ...`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
[NOTE]
====
Se debe ejecutar este comando desde la SVM de destino o el clúster de destino.

====
+
En el siguiente ejemplo, se inicializa la relación entre el volumen de origen `volA` encendido `svm1` y el volumen de destino `volA_dst` encendido `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror initialize -source-path svm1:volA -destination-path svm_backup:volA_dst
----

