---
permalink: data-protection/make-destination-volume-writeable-task.html 
sidebar: sidebar 
keywords: destination, volume, writeable, write, serve data, snapmirror, quiesce, pause, abort, transfers 
summary: Debe hacer que el volumen de destino sea editable, para poder proporcionar datos del volumen a los clientes. Puede utilizar el comando snapmirror QUIESCE para detener las transferencias programadas al destino, el comando snapmirror abort para detener las transferencias continuas y el comando snapmirror break para hacer que el destino sea editable. 
---
= Haga que el volumen de destino sea modificable
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe hacer que el volumen de destino sea editable, para poder proporcionar datos del volumen a los clientes. Puede utilizar el `snapmirror quiesce` comando para detener las transferencias programadas al destino, el `snapmirror abort` comando para detener las transferencias continuas y el `snapmirror break` comando para hacer que el destino sea editable.

.Acerca de esta tarea
Debe realizar esta tarea desde la SVM de destino o el clúster de destino.

.Pasos
. Detenga las transferencias programadas al destino:
+
`snapmirror quiesce -source-path _SVM:volume|cluster://SVM/volume_, ... -destination-path _SVM:volume|cluster://SVM/volume_, ...`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
El siguiente ejemplo detiene las transferencias programadas entre el volumen de origen `volA` encendido `svm1` y el volumen de destino `volA_dst` encendido `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. Detenga las transferencias continuas al destino:
+
`snapmirror abort -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
[NOTE]
====
Este paso no es necesario para relaciones de SnapMirror síncrono (se admite a partir de ONTAP 9.5).

====
+
El siguiente ejemplo detiene las transferencias continuas entre el volumen de origen `volA` encendido `svm1` y el volumen de destino `volA_dst` encendido `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror abort -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. Rompa la relación de recuperación ante desastres de SnapMirror:
+
`snapmirror break -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
En el siguiente ejemplo, se rompe la relación entre el volumen de origen `volA` encendido `svm1` y el volumen de destino `volA_dst` encendido `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm1:volA -destination-path svm_backup:volA_dst
----




== Otras maneras de hacerlo en ONTAP

[cols="2"]
|===
| Para ejecutar estas tareas con... | Ver este contenido... 


| System Manager rediseñado (disponible con ONTAP 9.7 y versiones posteriores) | link:https://docs.netapp.com/us-en/ontap/task_dp_serve_data_from_destination.html["Sirva datos desde un destino de SnapMirror"^] 


| System Manager Classic (disponible con ONTAP 9.7 y versiones anteriores) | link:https://docs.netapp.com/us-en/ontap-sm-classic/volume-disaster-recovery/index.html["Información general sobre la recuperación ante desastres de volúmenes"^] 
|===