---
permalink: data-protection/manage-local-snapshot-copies-concept.html 
sidebar: sidebar 
keywords: manage, local, snapshot, copy, storage, performance overhead, copies, image, restore, flexvol, flexgroup 
summary: Una copia Snapshot es una imagen de un momento específico de solo lectura de un volumen. La imagen consume un espacio de almacenamiento mínimo y apenas supone una sobrecarga de rendimiento, ya que sólo registra los cambios realizados en los archivos desde la última copia Snapshot. 
---
= Descripción general de la gestión de instantáneas locales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una _snapshot_ es una imagen puntual de solo lectura de un volumen. La imagen consume un espacio de almacenamiento mínimo y apenas supone una sobrecarga de rendimiento, ya que sólo registra los cambios realizados en los archivos desde la última copia Snapshot.

Puede utilizar una instantánea para restaurar todo el contenido de un volumen o para recuperar archivos o LUN individuales. Las instantáneas se almacenan en el directorio del volumen. `.snapshot`

En ONTAP 9,3 y versiones anteriores, un volumen puede contener hasta 255 copias de Snapshot. En ONTAP 9,4 y versiones posteriores, una FlexVol volume puede contener hasta 1023 copias de Snapshot.

[NOTE]
====
A partir de ONTAP 9,8, los volúmenes FlexGroup pueden contener 1023 snapshots. Para obtener más información, consulte link:../flexgroup/protect-snapshot-copies-task.html["Proteger los volúmenes de FlexGroup mediante snapshots"].

====