---
permalink: data-protection/manage-snapmirror-root-volume-replication-concept.html 
sidebar: sidebar 
keywords: manage, snapmirror, root volume , replication 
summary: 'Cada SVM en un entorno NAS tiene un espacio de nombres único. El volumen raíz de la SVM es el punto de entrada a esta jerarquía de espacio de nombres. Para clústeres formados por dos o más pares de HA, deberías considerar los mirrors de carga compartida (LSM) del volumen raíz de la SVM para asegurarte de que el espacio de nombres siga siendo accesible para los clientes si ambos nodos de un par de HA fallan.' 
---
= Obtenga más información sobre la replicación de volúmenes raíz de ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada SVM en un entorno NAS tiene un espacio de nombres único. El volumen raíz de la SVM es el punto de entrada a esta jerarquía de espacio de nombres. Para clústeres formados por dos o más pares de HA, deberías considerar los mirrors de carga compartida (LSM) del volumen raíz de la SVM para asegurarte de que el espacio de nombres siga siendo accesible para los clientes en caso de que ambos nodos de un par de HA fallen. Los mirrors de carga compartida no son adecuados para clústeres formados por un solo par de HA y no son adecuados para un entorno MetroCluster.

* A partir de ONTAP 9.1, las réplicas de carga compartida han quedado obsoletas para los volúmenes de datos y solo son compatibles con los volúmenes raíz de SVM.
* Los espejos de carga compartida de SnapMirror solo pueden admitir clientes NAS (CIFS/NFSv3). Los espejos de carga compartida no admiten clientes NFSv4 ni conexiones de protocolo de cliente SAN (FC, FCoE o iSCSI). Sin embargo, NFSv4 y los espejos de carga compartida pueden coexistir en el mismo entorno.

