---
permalink: data-protection/manage-local-snapshot-copies-concept.html 
sidebar: sidebar 
keywords: manage, local, snapshot, copy, storage, performance overhead, copies, image, restore, flexvol, flexgroup 
summary: Una copia Snapshot es una imagen puntual de solo lectura de un volumen. La imagen consume un espacio de almacenamiento mínimo y tiene una sobrecarga del rendimiento mínima, ya que solo registra los cambios realizados en los archivos desde la última copia Snapshot. 
---
= Información general sobre la gestión de copias Snapshot locales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una _Snapshot copy_ es una imagen puntual de solo lectura de un volumen. La imagen consume un espacio de almacenamiento mínimo y tiene una sobrecarga del rendimiento mínima, ya que solo registra los cambios realizados en los archivos desde la última copia Snapshot.

Puede usar una copia Snapshot para restaurar el contenido completo de un volumen o para recuperar archivos o LUN individuales. Las copias Snapshot se almacenan en el directorio `.snapshot` en el volumen.

En ONTAP 9.3 y versiones anteriores, un volumen puede contener hasta 255 copias snapshot. A partir de la versión 9.4 de ONTAP, un volumen de FlexVol puede contener hasta 1023 copias snapshot.

[NOTE]
====
A partir de ONTAP 9.8, los volúmenes FlexGroup pueden contener 1023 copias snapshot. Para obtener más información, consulte link:../flexgroup/protect-snapshot-copies-task.html["Protección de volúmenes de FlexGroup mediante copias de Snapshot"].

====