---
permalink: data-protection/path-name-pattern-matching-concept.html 
sidebar: sidebar 
keywords: path, pattern, matching 
summary: Puede utilizar la coincidencia de patrones para especificar las rutas de origen y destino en comandos de snapmirror. 
---
= Utilizar coincidencia de patrón de nombre de ruta de acceso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar la coincidencia de patrones para especificar las rutas de origen y destino en `snapmirror` comandos.

 `snapmirror` los comandos utilizan nombres de ruta completos con el siguiente formato: `vserver:volume`. No se puede introducir el nombre de la SVM para abreviar el nombre de la ruta de acceso. Si lo hace, el `snapmirror` El comando asume el contexto de SVM local del usuario.

Suponiendo que la SVM se denomine «'vserver1'» y que el volumen se llama «'vol1'», el nombre de ruta completo es `vserver1:vol1`.

Puede utilizar el asterisco (*) en las rutas de acceso como comodín para seleccionar nombres de ruta de acceso coincidentes y completos. En la siguiente tabla, se proporcionan ejemplos del uso del comodín para seleccionar un rango de volúmenes.

[cols="2*"]
|===


 a| 
`*`
 a| 
Coincide con todas las rutas.



 a| 
`vs*`
 a| 
Coincide con todas las SVM y los volúmenes con nombres de SVM que comienzan con `vs`.



 a| 
`*:*src*`
 a| 
Coincide con todas las SVM con los nombres de los volúmenes que contienen `src` texto.



 a| 
`*:vol*`
 a| 
Coincide con todas las SVM con nombres de volúmenes que comienzan con `vol`.

|===
[listing]
----
vs1::> snapmirror show -destination-path *:*dest*
                                                                                Progress
Source              Destination  Mirror        Relationship  Total              Last
Path          Type  Path         State         Status        Progress   Healthy Updated
------------- ---- ------------ ------------- -------------- ---------- ------- --------
vs1:sm_src2
              DP   vs2:sm_dest1
                                Snapmirrored  Idle           -          true    -
----
Obtenga más información sobre los comandos descritos en este procedimiento en el link:https://docs.netapp.com/us-en/ontap-cli/["Referencia de comandos de la ONTAP"^].
