---
permalink: data-protection/preserve-snapshot-copy-primary-source-volume-task.html 
sidebar: sidebar 
keywords: ensure, snapshot, copy, mirror-vault, deployment 
summary: Se puede usar el comando SnapMirror snapshot-owner create para conservar una Snapshot con etiqueta en el secundario en una implementación de reflejo-almacén. Al hacerlo, se garantiza que exista una instantánea común para la actualización de la relación de almacén. 
---
= Asegúrese de una instantánea común en una implementación de mirror-vault de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes utilizar el  `snapmirror snapshot-owner create` Comando para conservar una instantánea etiquetada en el almacén secundario en una implementación de bóveda reflejada. Esto garantiza que exista una instantánea común para la actualización de la relación entre bóvedas.

.Acerca de esta tarea
Si utiliza una combinación de replicación ramificada entre reflejo y almacén o implementación en cascada, debe tener en cuenta que las actualizaciones generarán errores si no existe una snapshot común en los volúmenes de origen y de destino.

Esto nunca es un problema de la relación de reflejo en una implementación ramificada reflejo-almacén o en cascada, ya que SnapMirror siempre crea una copia Snapshot del volumen de origen antes de llevar a cabo la actualización.

Sin embargo, puede ser un problema para la relación de almacén, ya que SnapMirror no crea una copia Snapshot del volumen de origen cuando actualiza una relación de almacén. Debe utilizar `snapmirror snapshot-owner create` para asegurarse de que hay al menos una instantánea común tanto en el origen como en el destino de la relación de almacén. link:supported-deployment-config-concept.html["Obtenga más información sobre la distribución ramificada y las puestas en marcha en cascada de la protección de datos"].

.Pasos
. En el volumen de origen, asigne un propietario a la snapshot etiquetada que desea conservar:
+
`snapmirror snapshot-owner create -vserver <SVM> -volume <volume> -snapshot <snapshot> -owner <owner>`

+
En el siguiente ejemplo se asigna `ApplicationA` como propietario de `snap1` la copia de Snapshot:

+
[listing]
----
clust1::> snapmirror snapshot-owner create -vserver vs1 -volume vol1
-snapshot snap1 -owner ApplicationA
----
+
Obtenga más información sobre  `snapmirror snapshot-owner create` en el link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-snapshot-owner-create.html["Referencia de comandos del ONTAP"^] .

. Actualice la relación de reflejo, tal como se describe en link:update-replication-relationship-manual-task.html["Actualizar manualmente una relación de replicación"].
+
También puede esperar a la actualización programada de la relación de reflejo.

. Transfiera la instantánea etiquetada al destino del almacén:
+
`snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ... -source-snapshot snapshot`

+
En el siguiente ejemplo se transfiere la `snap1` copia de Snapshot::
+
--
[listing]
----
clust1::> snapmirror update -vserver vs1 -volume vol1
-source-snapshot snap1
----
La instantánea etiquetada se conservará cuando se actualice la relación de almacén.

Obtenga más información sobre `snapmirror update` en el link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["Referencia de comandos del ONTAP"^].

--


. En el volumen de origen, quite el propietario de la snapshot etiquetada:
+
`snapmirror snapshot-owner delete -vserver _SVM_ -volume _volume_ -snapshot _snapshot_ -owner _owner_`

+
Los siguientes ejemplos eliminan `ApplicationA` como propietario de `snap1` la instantánea:

+
[listing]
----
clust1::> snapmirror snapshot-owner delete -vserver vs1 -volume vol1
-snapshot snap1 -owner ApplicationA
----
+
Obtenga más información sobre `snapmirror snapshot-owner delete` en el link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-snapshot-owner-delete.html["Referencia de comandos del ONTAP"^].


