---
permalink: data-protection/preserve-snapshot-copy-primary-source-volume-task.html 
sidebar: sidebar 
keywords: ensure, snapshot, copy, mirror-vault, deployment 
summary: Puede utilizar el comando snapmirror snapshot-owner create para conservar una copia snapshot etiquetada en el secundario en una puesta en marcha de mirroring-almacén. Al hacerlo se garantiza que exista una copia snapshot común para la actualización de la relación de almacén. 
---
= Garantice una copia Snapshot común en una instalación de mirror-vault
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `snapmirror snapshot-owner create` Comando para conservar una copia Snapshot etiquetada en el secundario en una implementación de reflejo-almacén. Al hacerlo se garantiza que exista una copia snapshot común para la actualización de la relación de almacén.

.Acerca de esta tarea
Si utiliza una combinación de ventilador-almacén de reflejos o puesta en marcha en cascada, debe tener en cuenta que fallarán las actualizaciones si no existe una copia snapshot común en los volúmenes de origen y destino.

Esto no supone ningún problema en la relación de mirroring en una puesta en marcha en cascada o en distribución ramificada-vault, ya que SnapMirror siempre crea una copia snapshot del volumen de origen antes de realizar la actualización.

Puede ser un problema en la relación de almacén, sin embargo, ya que SnapMirror no crea una copia Snapshot del volumen de origen al actualizar una relación de almacén. Debe utilizar el `snapmirror snapshot-owner create` Para garantizar que hay al menos una copia Snapshot común en el origen y el destino de la relación del almacén.

.Pasos
. En el volumen de origen, asigne un propietario a la copia Snapshot etiquetada que desea conservar:
+
`snapmirror snapshot-owner create -vserver <SVM> -volume <volume> -snapshot <snapshot> -owner <owner>`

+
El ejemplo siguiente asigna `ApplicationA` como propietario del `snap1` Copia Snapshot:

+
[listing]
----
clust1::> snapmirror snapshot-owner create -vserver vs1 -volume vol1
-snapshot snap1 -owner ApplicationA
----
. Actualice la relación de reflejo, como se describe en link:update-replication-relationship-manual-task.html["Actualizar manualmente una relación de replicación"].
+
También puede esperar a la actualización programada de la relación de reflejo.

. Transfiera la copia Snapshot etiquetada como al destino de almacén:
+
`snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ... -source-snapshot snapshot`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
En el siguiente ejemplo se transfiere el `snap1` Copia Snapshot::
+
--
[listing]
----
clust1::> snapmirror update -vserver vs1 -volume vol1
-source-snapshot snap1
----
La copia snapshot etiquetada se conservará cuando se actualice la relación de almacén.

--


. En el volumen de origen, quite el propietario de la copia Snapshot etiquetada:
+
`snapmirror snapshot-owner delete -vserver _SVM_ -volume _volume_ -snapshot _snapshot_ -owner _owner_`

+
Los ejemplos siguientes eliminan `ApplicationA` como propietario del `snap1` Copia Snapshot:

+
[listing]
----
clust1::> snapmirror snapshot-owner delete -vserver vs1 -volume vol1
-snapshot snap1 -owner ApplicationA
----

