---
permalink: data-protection/replicate-entire-svm-config-task.html 
sidebar: sidebar 
keywords: replicate, entire, svm, storage vm, disaster, protection, configuration, snapmirror, snap mirror, replication, mirror vault policy, snapshot 
summary: 'Puede crear una relación de recuperación ante desastres (DR de SVM) para replicar una configuración de SVM a otra. En caso de desastre en el sitio principal, puede activar rápidamente la SVM de destino.' 
---
= Replicación de una configuración completa de SVM de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear una relación de recuperación ante desastres (DR de SVM) para replicar una configuración de SVM a otra. En caso de desastre en el sitio principal, puede activar rápidamente la SVM de destino.

.Antes de empezar
Las SVM y los clústeres de origen y destino deben tener una relación entre iguales. Para obtener más información, consulte link:../peering/create-cluster-relationship-93-later-task.html["Cree una relación de paridad entre clústeres"] y link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["Cree una relación de interconexión de clústeres entre iguales de SVM"].

Obtenga más información sobre los comandos descritos en este procedimiento en el link:https://docs.netapp.com/us-en/ontap-cli/["Referencia de comandos del ONTAP"^].

.Acerca de esta tarea
Este flujo de trabajo supone que ya está usando una directiva predeterminada o una directiva de replicación personalizada.

A partir de ONTAP 9,9.1, cuando se utiliza la política de reflejo-almacén, se pueden crear distintas políticas de Snapshot en la SVM de origen y destino, y las snapshots del destino no se sobrescriben en el origen. Para obtener más información, consulte link:snapmirror-svm-replication-concept.html["Replicación de SVM de SnapMirror"].

Complete este procedimiento desde el destino. Si necesita crear una nueva política de protección, por ejemplo, cuando su VM de almacenamiento de origen tiene SMB configurado, debe crear la política y usar la opción *Identity preserve*. Para obtener más información, consulte link:create-custom-replication-policy-concept.html["Cree políticas de protección de datos personalizadas"].

.Pasos
Puede realizar esta tarea desde System Manager o la CLI de ONTAP.

[role="tabbed-block"]
====
.System Manager
--
. En el clúster de destino, haga clic en *Protección > Relaciones*.
. En *Relaciones*, haz clic en *Proteger* y elige *Storage VMs (DR)*.
. Seleccione una política de protección. Si creó una política de protección personalizada, selecciónela, elija el clúster de origen y la máquina virtual de almacenamiento que desea replicar. También puede crear una máquina virtual de almacenamiento de destino introduciendo un nuevo nombre de máquina virtual de almacenamiento.
. Si lo desea, cambie la configuración de destino para sustituir la conservación de identidad e incluir o excluir interfaces y protocolos de red.
. Haga clic en *Guardar*.


--
.CLI
--
. Cree una SVM de destino:
+
[source, cli]
----
vserver create -vserver <SVM_name> -subtype dp-destination
----
+
El nombre de SVM debe ser único en los clústeres de origen y destino.

+
En el ejemplo siguiente se crea una SVM de destino llamada `svm_backup`:

+
[listing]
----
cluster_dst:> vserver create -vserver svm_backup -subtype dp-destination
----
+
Obtenga más información sobre `vserver create` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-create.html["Referencia de comandos del ONTAP"^].

. Desde el clúster de destino, cree una relación entre iguales de SVM mediante `vserver peer create` el comando.
+
Para obtener más información, consulte link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["Cree una relación de interconexión de clústeres entre iguales de SVM"].

+
Obtenga más información sobre `vserver peer create` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-peer-create.html["Referencia de comandos del ONTAP"^].

. Crear una programación de trabajo de replicación:
+
[source, cli]
----
job schedule cron create -name <job_name> -month <month> -dayofweek <day_of_week> -day <day_of_month> -hour <hour> -minute <minute>
----
+
Para `-month` `-dayofweek` , y `-hour`, puede especificar `all` que se ejecute el trabajo cada mes, día de la semana y hora, respectivamente.

+

NOTE: La programación mínima admitida (RPO) para volúmenes FlexVol en una relación de SnapMirror de SVM es de 15 minutos. La programación mínima admitida (RPO) para volúmenes FlexGroup en una relación de SnapMirror de SVM es de 30 minutos.

+
El siguiente ejemplo crea una programación de trabajo llamada `my_weekly` que se ejecuta los sábados a las 3:00 a.m.:

+
[listing]
----
cluster_dst::> job schedule cron create -name my_weekly -dayofweek saturday -hour 3 -minute 0
----
+
Obtenga más información sobre `job schedule cron create` en el link:https://docs.netapp.com/us-en/ontap-cli/job-schedule-cron-create.html["Referencia de comandos del ONTAP"^].

. A partir de la SVM de destino o el clúster de destino, cree una relación de replicación:
+
[source, cli]
----
snapmirror create -source-path <SVM_name>: -destination-path <SVM_name>: -type <DP|XDP> -schedule <schedule> -policy <policy> -identity-preserve true
----
+

NOTE: Debe introducir dos puntos (:) después del nombre de la SVM en las `-source-path` `-destination-path` opciones y.

+
En el ejemplo siguiente se crea una relación de recuperación ante desastres de SnapMirror con la `MirrorAllSnapshots` política predeterminada:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy MirrorAllSnapshots -identity-preserve true
----
+
En el siguiente ejemplo, se crea una relación de replicación unificada mediante la `MirrorAndVault` política predeterminada:

+
[listing]
----
cluster_dst:> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy MirrorAndVault -identity-preserve true
----
+
Suponiendo que ha creado una política personalizada con el tipo de política `async-mirror` , en el siguiente ejemplo se crea una relación de DR de SnapMirror:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy my_mirrored -identity-preserve true
----
+
Suponiendo que ha creado una política personalizada con el tipo de política `mirror-vault` , en el siguiente ejemplo se crea una relación de replicación unificada:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy my_unified -identity-preserve true
----
+
Obtenga más información sobre `snapmirror create` en el link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["Referencia de comandos del ONTAP"^].

. Detenga la SVM de destino:
+
[source, cli]
----
vserver stop -vserver <SVM_name>
----
+
En el ejemplo siguiente se detiene una SVM de destino llamada svm_backup:

+
[listing]
----
cluster_dst::> vserver stop -vserver svm_backup
----
+
Obtenga más información sobre `vserver stop` en el link:https://docs.netapp.com/us-en/ontap-cli/vserver-stop.html["Referencia de comandos del ONTAP"^].

. En la SVM de destino o el clúster de destino, inicialice la relación de replicación de SVM:
+
[source, cli]
----
snapmirror initialize -source-path <SVM_name>: -destination-path <SVM_name>:
----
+

NOTE: Debe introducir dos puntos (:) después del nombre de la SVM en las `-source-path` `-destination-path` opciones y.

+
En el ejemplo siguiente, se inicializa la relación entre la SVM de origen y `svm1` la SVM de destino, `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror initialize -source-path svm1: -destination-path svm_backup:
----
+
Obtenga más información sobre `snapmirror initialize` en el link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["Referencia de comandos del ONTAP"^].



--
====