---
permalink: data-protection/restore-contents-volume-snapshot-task.html 
sidebar: sidebar 
keywords: restore, contents, volume, snapshot copy 
summary: Es posible usar el comando volume snapshot restore para restaurar el contenido de un volumen desde una copia Snapshot. 
---
= Restaure el contenido de un volumen de una copia Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `volume snapshot restore` Comando para restaurar el contenido de un volumen desde una copia Snapshot.

.Acerca de esta tarea
Si el volumen tiene relaciones de SnapMirror, replique manualmente todas las copias de reflejo del volumen inmediatamente después de restaurar desde una copia de Snapshot. Si no lo hace, puede provocar copias reflejadas inutilizables que se deban eliminar y volver a crear.

.Pasos
. Enumere las copias Snapshot en un volumen:
+
`volume snapshot show -vserver _SVM_ -volume _volume_`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
El ejemplo siguiente muestra las copias Snapshot en `vol1`:

+
[listing]
----

clus1::> volume snapshot show -vserver vs1 -volume vol1

Vserver Volume Snapshot                State    Size  Total% Used%
------- ------ ---------- ----------- ------   -----  ------ -----
vs1	 vol1   hourly.2013-01-25_0005  valid   224KB     0%    0%
               daily.2013-01-25_0010   valid   92KB      0%    0%
               hourly.2013-01-25_0105  valid   228KB     0%    0%
               hourly.2013-01-25_0205  valid   236KB     0%    0%
               hourly.2013-01-25_0305  valid   244KB     0%    0%
               hourly.2013-01-25_0405  valid   244KB     0%    0%
               hourly.2013-01-25_0505  valid   244KB     0%    0%

7 entries were displayed.
----
. Restaure el contenido de un volumen de una copia Snapshot:
+
`volume snapshot restore -vserver _SVM_ -volume _volume_ -snapshot _snapshot_`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
En el ejemplo siguiente se restaura el contenido de `vol1`:

+
[listing]
----
cluster1::> volume snapshot restore -vserver vs0 -volume vol1 -snapshot daily.2013-01-25_0010
----

