---
permalink: data-protection/restore-single-file-snapshot-task.html 
sidebar: sidebar 
keywords: restore, single file, snapshot copy 
summary: Es posible utilizar el comando restore-file de snapshots de volumen para restaurar un solo archivo o LUN desde una copia Snapshot. Es posible restaurar el archivo a otra ubicación en el volumen primario de lectura y escritura si no desea reemplazar un archivo existente. 
---
= Restaure un solo archivo de una copia Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `volume snapshot restore-file` Comando para restaurar un solo archivo o LUN desde una copia Snapshot. Es posible restaurar el archivo a otra ubicación en el volumen primario de lectura y escritura si no desea reemplazar un archivo existente.

.Acerca de esta tarea
Si va a restaurar una LUN existente, se crea un clon de LUN y se realiza un backup en forma de copia Snapshot. Durante la operación de restauración, puede leer la LUN y escribir en ella.

Los archivos con flujos se restauran de forma predeterminada.

.Pasos
. Enumere las copias Snapshot en un volumen:
+
`volume snapshot show -vserver _SVM_ -volume _volume_`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
El ejemplo siguiente muestra las copias Snapshot en `vol1`:

+
[listing]
----

clus1::> volume snapshot show -vserver vs1 -volume vol1

Vserver Volume Snapshot                State    Size  Total% Used%
------- ------ ---------- ----------- ------   -----  ------ -----
vs1	 vol1   hourly.2013-01-25_0005  valid   224KB     0%    0%
               daily.2013-01-25_0010   valid   92KB      0%    0%
               hourly.2013-01-25_0105  valid   228KB     0%    0%
               hourly.2013-01-25_0205  valid   236KB     0%    0%
               hourly.2013-01-25_0305  valid   244KB     0%    0%
               hourly.2013-01-25_0405  valid   244KB     0%    0%
               hourly.2013-01-25_0505  valid   244KB     0%    0%

7 entries were displayed.
----
. Restaurar un archivo desde una copia Snapshot:
+
`volume snapshot restore-file -vserver _SVM_ -volume _volume_ -snapshot _snapshot_ -path _file_path_ -restore-path _destination_path_`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
En el siguiente ejemplo se restaura el archivo `myfile.txt`:

+
[listing]
----
cluster1::> volume snapshot restore-file -vserver vs0 -volume vol1 -snapshot daily.2013-01-25_0010 -path /myfile.txt
----

