---
permalink: data-protection/restore-part-file-snapshot-task.html 
sidebar: sidebar 
keywords: restore, part, file, snapshot copy 
summary: Puede utilizar el comando volume snapshot partial-restore-file para restaurar un rango de datos desde una snapshot a una LUN o un archivo de contenedor NFS o SMB, suponiendo que se conoce el desplazamiento de bytes de inicio de los datos y el recuento de bytes. Este comando puede usarse para restaurar una de las bases de datos en un host que almacena varias bases de datos en el mismo LUN. 
---
= Restaurar parte de un archivo a partir de una instantánea de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar `volume snapshot partial-restore-file` el comando para restaurar un rango de datos desde una snapshot a una LUN o a un archivo de contenedor NFS o SMB, suponiendo que se conoce el desplazamiento de bytes de inicio de los datos y el número de bytes. Este comando puede usarse para restaurar una de las bases de datos en un host que almacena varias bases de datos en el mismo LUN.

A partir de ONTAP 9.12.1, está disponible la restauración parcial para los volúmenes que usan xref:../snapmirror-active-sync/index.html[SnapMirror síncrono activo].

.Pasos
. Enumere las snapshots en un volumen:
+
`volume snapshot show -vserver _SVM_ -volume _volume_`

+
Obtenga más información sobre `volume snapshot show` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-show.html["Referencia de comandos del ONTAP"^].

+
En el siguiente ejemplo se muestran las instantáneas en `vol1`:

+
[listing]
----

clus1::> volume snapshot show -vserver vs1 -volume vol1

Vserver Volume Snapshot                State    Size  Total% Used%
------- ------ ---------- ----------- ------   -----  ------ -----
vs1	    vol1   hourly.2013-01-25_0005  valid   224KB     0%    0%
               daily.2013-01-25_0010   valid   92KB      0%    0%
               hourly.2013-01-25_0105  valid   228KB     0%    0%
               hourly.2013-01-25_0205  valid   236KB     0%    0%
               hourly.2013-01-25_0305  valid   244KB     0%    0%
               hourly.2013-01-25_0405  valid   244KB     0%    0%
               hourly.2013-01-25_0505  valid   244KB     0%    0%

7 entries were displayed.
----
. Restaurar parte de un archivo a partir de una instantánea:
+
`volume snapshot partial-restore-file -vserver _SVM_ -volume _volume_ -snapshot _snapshot_ -path _file_path_ -start-byte _starting_byte_ -byte-count _byte_count_`

+
El desplazamiento de bytes de inicio y el número de bytes deben ser múltiplos de 4,096.

+
El siguiente ejemplo restaura los primeros 4.096 bytes del archivo `myfile.txt`:

+
[listing]
----
cluster1::> volume snapshot partial-restore-file -vserver vs0 -volume vol1 -snapshot daily.2013-01-25_0010 -path /myfile.txt -start-byte 0 -byte-count 4096
----

