---
permalink: data-protection/snapmirror-unified-replication-concept.html 
sidebar: sidebar 
keywords: snapmirror, unified, replication 
summary: La replicación unificada de SnapMirror le permite configurar la recuperación ante desastres y el archivado en el mismo volumen de destino. Cuando la replicación unificada es apropiada, ofrece ventajas en la reducción de la cantidad de almacenamiento secundario que se necesita, lo que limita el número de transferencias básicas y reduce el tráfico de red. 
---
= Conceptos básicos de la replicación unificada de SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror _Unified replication_ permite configurar la recuperación ante desastres y el archivado en el mismo volumen de destino. Cuando la replicación unificada es apropiada, ofrece ventajas en la reducción de la cantidad de almacenamiento secundario que se necesita, lo que limita el número de transferencias básicas y reduce el tráfico de red.



== Cómo se inicializan las relaciones de protección de datos unificadas

Al igual que sucede con SnapMirror, la protección de datos unificada realiza una transferencia de referencia la primera vez que se invoca. La política de SnapMirror para la relación define el contenido de la línea de base y cualquier actualización.

Una transferencia completa con la política de protección de datos unificada predeterminada `MirrorAndVault` realiza una copia Snapshot del volumen de origen y, a continuación, transfiere dicha copia y los bloques de datos a los que hace referencia al volumen de destino. Al igual que el archivado de almacenes, la protección de datos unificada no incluye copias Snapshot más antiguas como referencia.



== Cómo se actualizan las relaciones de protección de datos unificadas

En cada actualización de la `MirrorAndVault` política, SnapMirror crea una instantánea del volumen de origen y transfiere esa instantánea y cualquier instantánea que se haya realizado desde la última actualización, siempre y cuando tengan etiquetas que coincidan con las definidas en las reglas de política de instantáneas. En el siguiente resultado del `snapmirror policy show` comando para la `MirrorAndVault` política, tenga en cuenta lo siguiente:

* `Create Snapshot` Es '`verdadero'', lo que indica que `MirrorAndVault` crea una instantánea cuando SnapMirror actualiza la relación.
* `MirrorAndVault` Tiene reglas “sm_created”, “daaily” y “weekly”, que indican que tanto la instantánea creada por SnapMirror como las instantáneas con etiquetas coincidentes en el origen se transfieren cuando SnapMirror actualiza la relación.


[listing]
----
cluster_dst::> snapmirror policy show -policy MirrorAndVault -instance

                     Vserver: vs0
      SnapMirror Policy Name: MirrorAndVault
      SnapMirror Policy Type: mirror-vault
                Policy Owner: cluster-admin
                 Tries Limit: 8
           Transfer Priority: normal
   Ignore accesstime Enabled: false
     Transfer Restartability: always
 Network Compression Enabled: false
             Create Snapshot: true
                     Comment: A unified SnapMirror synchronous and SnapVault policy for
                              mirroring the latest file system and daily and weekly snapshots.
       Total Number of Rules: 3
                  Total Keep: 59
                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              sm_created              1  false       0 -        -
                              daily                   7  false       0 -        -
                              weekly                 52  false       0 -        -
----


== Política Unified7year

La política preconfigurada `Unified7year` funciona exactamente de la misma manera que `MirrorAndVault`, excepto que una cuarta regla transfiere instantáneas mensuales y las conserva durante siete años.

[listing]
----

                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              sm_created              1  false       0 -        -
                              daily                   7  false       0 -        -
                              weekly                 52  false       0 -        -
                              monthly                84  false       0 -        -
----


== Proporcionar protección frente a una posible corrupción de datos

La replicación unificada limita el contenido de la transferencia completa a la snapshot creada por SnapMirror durante la inicialización. En cada actualización, SnapMirror crea otra instantánea del origen y transfiere esa instantánea y cualquier instantánea nueva que tenga etiquetas que coincidan con las etiquetas definidas en las reglas de política de instantáneas.

Puede protegerse contra la posibilidad de que una snapshot actualizada esté dañada creando una copia de la última snapshot transferida en el destino. Esta «copia local» se conserva con independencia de las reglas de retención en el origen, de modo que incluso si la instantánea originalmente transferida por SnapMirror ya no está disponible en el origen, una copia de ella estará disponible en el destino.



== Cuándo utilizar la replicación de datos unificada

Debe sopesar las ventajas que supone mantener una copia completa frente a las ventajas que ofrece la replicación unificada para reducir la cantidad de almacenamiento secundario, limitar el número de transferencias básicas y reducir el tráfico de red.

El factor clave para determinar la idoneidad de la replicación unificada es la tasa de cambio del sistema de archivos activo. Un reflejo tradicional es posible que resulte más adecuado para un volumen que contiene instantáneas cada hora de registros de transacciones de base de datos, por ejemplo.
