---
permalink: data-protection/snapshot-copies-work-concept.html 
sidebar: sidebar 
keywords: restore, file, snapshot copy, nfs, cifs, smb, client 
summary: Un usuario en un cliente de NFS o SMB puede restaurar un archivo directamente desde una snapshot sin la intervención de un administrador del sistema de almacenamiento. 
---
= Restaure un archivo desde una snapshot de ONTAP en un cliente de NFS o SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un usuario en un cliente de NFS o SMB puede restaurar un archivo directamente desde una snapshot sin la intervención de un administrador del sistema de almacenamiento.

Todos los directorios del sistema de archivos contienen un subdirectorio denominado `.snapshot` accesible para los usuarios de NFS y SMB. El `.snapshot` subdirectorio contiene subdirectorios correspondientes a las instantáneas del volumen:

....
$ ls .snapshot
daily.2017-05-14_0013/              hourly.2017-05-15_1106/
daily.2017-05-15_0012/              hourly.2017-05-15_1206/
hourly.2017-05-15_1006/             hourly.2017-05-15_1306/
....
Cada subdirectorio contiene los archivos a los que hace referencia la instantánea. Si los usuarios eliminan o sobrescriben accidentalmente un archivo, pueden restaurarlo en el directorio principal de lectura y escritura copiando el archivo del subdirectorio de instantáneas al directorio de lectura y escritura:

....
$ ls my.txt
ls: my.txt: No such file or directory
$ ls .snapshot
daily.2017-05-14_0013/              hourly.2017-05-15_1106/
daily.2017-05-15_0012/              hourly.2017-05-15_1206/
hourly.2017-05-15_1006/             hourly.2017-05-15_1306/
$ ls .snapshot/hourly.2017-05-15_1306/my.txt
my.txt
$ cp .snapshot/hourly.2017-05-15_1306/my.txt .
$ ls my.txt
my.txt
....