---
permalink: data-protection/snapmirror-global-throttling-concept.html 
sidebar: sidebar 
keywords: using snapmirror, global, throttling 
summary: La limitación de red global está disponible para todas las transferencias de SnapMirror y SnapVault a nivel de nodo. 
---
= Utilice la limitación global de ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La limitación de red global está disponible para todas las transferencias de SnapMirror y SnapVault a nivel de nodo.

.Acerca de esta tarea
La limitación global de SnapMirror restringe el ancho de banda utilizado por transferencias entrantes o salientes de SnapMirror y SnapVault. La restricción se aplica en todo el clúster en todos los nodos del clúster.

Por ejemplo, si el acelerador saliente está establecido en 100 Mbps, cada nodo del clúster tendrá el ancho de banda saliente establecido en 100 Mbps. Si la regulación global está deshabilitada, se desactiva en todos los nodos.

Aunque las velocidades de transferencia de datos a menudo se expresan en bits por segundo (bps), los valores del acelerador deben introducirse en kilobytes por segundo (kbps).

[NOTE]
====
En ONTAP 9.9,1 y versiones anteriores, el acelerador no afecta a `volume move` las transferencias ni a las transferencias de reflejos de uso compartido de carga. A partir de ONTAP 9.10.0, puede especificar una opción para acelerar una operación de movimiento de volumen. Para obtener más información, consulte link:https://kb.netapp.com/on-prem/ontap/Perf/Perf-KBs/How_to_throttle_volume_move_in_ONTAP_9.10_or_later["Cómo acelerar el movimiento del volumen en ONTAP 9,10 y posteriores"^].

====
La limitación global funciona con la función acelerador por relación para transferencias de SnapMirror y SnapVault. El acelerador por relación se aplica hasta que el ancho de banda combinado de las transferencias por relación supere el valor de la aceleración global, después de lo cual se aplica la aceleración global. Un valor de acelerador `0` implica que la regulación global está desactivada.

[NOTE]
====
La limitación global de SnapMirror no afecta a las relaciones síncronas de SnapMirror cuando están sincronizadas. Sin embargo, el acelerador afecta a las relaciones síncronas de SnapMirror cuando realizan una fase de transferencia asíncrona, como una operación de inicialización o después de un evento no sincronizado. Por este motivo, no se recomienda habilitar la limitación global con relaciones síncronas de SnapMirror.

====
.Pasos
. Habilitar la limitación global:
+
`options -option-name replication.throttle.enable on|off`

+
El siguiente ejemplo muestra cómo activar la limitación global de SnapMirror en `cluster_dst`:

+
[listing]
----
cluster_dst::> options -option-name replication.throttle.enable on
----
. Especifique el ancho de banda total máximo utilizado por las transferencias entrantes en el clúster de destino:
+
`options -option-name replication.throttle.incoming.max_kbs <KBps>`

+
El ancho de banda mínimo recomendado es de 4 kilobytes por segundo (kbps) y el máximo es de hasta 2 terabytes por segundo (Tbps). El valor por defecto de esta opción es `unlimited`, lo que significa que no hay límite en el ancho de banda total utilizado.

+
El siguiente ejemplo muestra cómo establecer el ancho de banda total máximo utilizado por las transferencias entrantes a 100 megabits por segundo (Mbps):

+
[listing]
----
cluster_dst::> options -option-name replication.throttle.incoming.max_kbs 12500
----
+
[NOTE]
====
100 megabits por segundo (Mbps) = 12500 kilobytes por segundo (kbps)

====
. Especifique el ancho de banda total máximo que utilizan las transferencias salientes en el clúster de origen:
+
`options -option-name replication.throttle.outgoing.max_kbs <KBps>`

+
El ancho de banda mínimo recomendado del acelerador es de 4 kbps y el máximo es de 2 TB/s. El valor por defecto de esta opción es `unlimited`, lo que significa que no hay límite en el ancho de banda total utilizado. Los valores de los parámetros están en kilobytes por segundo (kbps).

+
En el siguiente ejemplo se muestra cómo establecer el ancho de banda total máximo utilizado por las transferencias salientes en 100 Mbps:

+
[listing]
----
cluster_src::> options -option-name replication.throttle.outgoing.max_kbs 12500
----

