---
permalink: data-protection/update-load-sharing-mirror-set-task.html 
sidebar: sidebar 
keywords: update, loaad-sharing, mirror, relationship, LSM, manual update 
summary: 'Las relaciones de mirroring (LSM) de uso compartido de carga se actualizan automáticamente para los volúmenes raíz de SVM después de montar o desmontar un volumen en la SVM, y durante esta `volume create` operaciones que incluyen la "opción de la ruta de unión". Puede actualizar manualmente una relación LSM si desea actualizarla antes de la siguiente actualización programada.' 
---
= Actualizar una relación de reflejo de carga compartida
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las relaciones de reflejos de uso compartido de carga (LSM) se actualizan automáticamente para los volúmenes raíz de SVM después de montar o desmontar un volumen en la SVM, y durante `volume create` las operaciones que incluyen la `junction-path` opción. Puede actualizar manualmente una relación LSM si desea actualizarla antes de la siguiente actualización programada.

Las relaciones de reflejos de uso compartido de carga se actualizan automáticamente en las siguientes circunstancias:

* Ha llegado el momento de realizar una actualización programada
* Se realiza una operación de montaje o desmontaje en un volumen del volumen raíz de la SVM
* A. `volume create` se emite el comando que incluye la `juntion-path` opción


.Paso
. Actualice manualmente una relación de reflejo de carga compartida:
+
Antes de ejecutar este comando, debe sustituir las variables entre paréntesis angulares por los valores requeridos.

+
[source, cli]
----
snapmirror update-ls-set -source-path <SVM:volume>
----
+
En el siguiente ejemplo se actualiza la relación de reflejo de uso compartido de carga para el volumen raíz `svm1_root`:

+
[listing]
----
cluster_src::> snapmirror update-ls-set -source-path svm1:svm1_root
----


Obtenga más información sobre `volume create` en el link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["Referencia de comandos de la ONTAP"^].
