---
permalink: data-protection/version-flexible-snapmirror-default-concept.html 
sidebar: sidebar 
keywords: xdp, replace, dp, snapmirror, default, snap mirror, data protection, replication, replicate, snap lock, snaplock 
summary: 'A partir de ONTAP 9.3, el modo de protección de datos ampliada (XDP) de SnapMirror sustituye al modo de protección de datos (DP) de SnapMirror como valor predeterminado.' 
---
= XDP sustituye a DP como la opción predeterminada de SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.3, el modo de protección de datos ampliada (XDP) de SnapMirror sustituye al modo de protección de datos (DP) de SnapMirror como valor predeterminado.

Antes de actualizar a ONTAP 9.12.1, debe convertir las relaciones de tipo DP existentes a XDP antes de poder actualizar a ONTAP 9.12.1 y versiones posteriores. Para obtener más información, consulte link:convert-snapmirror-version-flexible-task.html["Convierta una relación de tipo DP existente a XDP"].

Hasta ONTAP 9.3, SnapMirror invocado en modo DP y SnapMirror invocado en modo XDP utilizaba distintos motores de replicación, con distintos enfoques respecto a la dependencia de versión:

* SnapMirror que se invoca en el modo DP utilizaba un motor de replicación _version-dependent_ en el que la versión de ONTAP debía ser la misma en el almacenamiento primario y secundario:
+
[listing]
----
cluster_dst::>  snapmirror create -type DP -source-path ... -destination-path ...
----
* SnapMirror, al que se invocó en el modo XDP, utilizó un motor de replicación de _version-flexible_ que admitía diferentes versiones de ONTAP en el almacenamiento primario y secundario:
+
[listing]
----
cluster_dst::>  snapmirror create -type XDP -source-path ... -destination-path ...
----


Las importantes ventajas de SnapMirror, que ofrece una versión flexible, superan la ligera ventaja del rendimiento de la replicación obtenido con el modo basado en la versión. Por este motivo, a partir de ONTAP 9.3, se ha creado el modo XDP como nuevo valor predeterminado, y cualquier invocación del modo DP en la línea de comandos o en scripts nuevos o existentes se convierte automáticamente al modo XDP.

Las relaciones existentes no se ven afectadas. Si una relación ya es del tipo DP, seguirá siendo del tipo DP. A partir de ONTAP 9.5, MirrorAndVault es la nueva política predeterminada cuando no se especifica ningún modo de protección de datos o cuando se especifica el modo XDP como tipo de relación. La siguiente tabla muestra el comportamiento que puede esperar.

[cols="3*"]
|===


| Si especifica... | El tipo es... | La política predeterminada (si no se especifica una política) es... 


 a| 
PROTECCIÓN DE DATOS
 a| 
XDP
 a| 
MirrorAllSnapshots (recuperación ante desastres de SnapMirror)



 a| 
Nada
 a| 
XDP
 a| 
MirrorAndVault (replicación unificada)



 a| 
XDP
 a| 
XDP
 a| 
MirrorAndVault (replicación unificada)

|===
Como se muestra en la tabla, las directivas predeterminadas asignadas a XDP en circunstancias diferentes garantizan que la conversión mantenga la equivalencia funcional de los tipos antiguos. Por supuesto, puede utilizar diferentes políticas según sea necesario, incluidas las políticas para la replicación unificada:

[cols="3*"]
|===


| Si especifica... | Y la política es... | El resultado es... 


 a| 
PROTECCIÓN DE DATOS
 a| 
MirrorAllSnapshots
 a| 
Recuperación ante desastres de SnapMirror



 a| 
XDPDefault
 a| 
SnapVault



 a| 
Reflejo de AndVault
 a| 
Replicación unificada



 a| 
XDP
 a| 
MirrorAllSnapshots
 a| 
Recuperación ante desastres de SnapMirror



 a| 
XDPDefault
 a| 
SnapVault



 a| 
Reflejo de AndVault
 a| 
Replicación unificada

|===
Las únicas excepciones a la conversión son las siguientes:

* Las relaciones de protección de datos de SVM siguen siendo las predeterminadas para el modo DP en ONTAP 9.3 y versiones anteriores.
+
A partir de ONTAP 9.4, las relaciones de protección de datos de la SVM se establecen en el modo XDP de manera predeterminada.

* Las relaciones de protección de datos con uso compartido de carga de volumen raíz continúan hasta los valores predeterminados en el modo DP.
* Las relaciones de protección de datos de SnapLock continúan en el modo DP de ONTAP 9.4 y versiones anteriores.
+
A partir de ONTAP 9.5, las relaciones de protección de datos de SnapLock se establecen en el modo XDP de manera predeterminada.

* Las invocaciones explícitas de DP siguen en el modo DP de forma predeterminada si establece la siguiente opción para todo el clúster:
+
[listing]
----
options replication.create_data_protection_rels.enable on
----
+
Esta opción se ignora si no invoca explícitamente DP.


