---
permalink: data-protection/workloads-strictsync-sync-policies-concept.html 
sidebar: sidebar 
keywords: understand, workloads, support, strictsync, policy, strict sync, policies, snapmirror, snap mirror, cifs, vmware, eda, synchronous, fc, iscsi, nvme, nfsv3, nfsv4 
summary: 'Las políticas de StrictSync y Sync admiten todas las aplicaciones basadas en LUN con los protocolos FC, iSCSI y FC-NVMe, así como los protocolos NFSv3 y NFSv4 para aplicaciones empresariales como bases de datos, VMware, Quota, SMB, etc. A partir de ONTAP 9.6, SnapMirror síncrono se puede usar para servicios de archivos empresariales, como la automatización de diseño electrónico (EDA), los directorios iniciales y las cargas de trabajo de la compilación de software.' 
---
= Obtenga información sobre las cargas de trabajo admitidas por las políticas StrictSync y Sync de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las políticas de StrictSync y Sync admiten todas las aplicaciones basadas en LUN con los protocolos FC, iSCSI y FC-NVMe, así como los protocolos NFSv3 y NFSv4 para aplicaciones empresariales como bases de datos, VMware, Quota, SMB, etc. A partir de ONTAP 9.6, SnapMirror síncrono se puede usar para servicios de archivos empresariales, como la automatización de diseño electrónico (EDA), los directorios iniciales y las cargas de trabajo de la compilación de software.

En ONTAP 9.5, para una política de sincronización, debe tener en cuenta algunos aspectos importantes a la vez que selecciona las cargas de trabajo NFSv3 o NFSv4. No se tiene en cuenta la cantidad de datos que realizan las operaciones de lectura o escritura por parte de las cargas de trabajo, ya que la política de sincronización puede gestionar cargas de trabajo de lectura o escritura elevadas. En ONTAP 9.5, las cargas de trabajo que tienen una creación de archivos, una creación de directorios, cambios de permisos de archivos o cambios de permisos de directorio pueden no ser adecuadas (estas se denominan cargas de trabajo con metadatos elevados). Un ejemplo típico de una carga de trabajo con metadatos altos es una carga de trabajo de DevOps en la que se crean varios archivos de prueba, se ejecuta la automatización y se eliminan los archivos. Otro ejemplo es la carga de trabajo de compilación paralela que genera varios archivos temporales durante la compilación. El impacto de una tasa alta de la actividad de metadatos de escritura es que puede provocar que la sincronización entre los reflejos se rompa temporalmente, lo que bloquea la I/o de lectura y escritura del cliente.

A partir de ONTAP 9.6, estas limitaciones se eliminan y SnapMirror síncrono puede usarse para cargas de trabajo de servicios de archivos empresariales que incluyen entornos multiusuario, como directorios iniciales y cargas de trabajo de creación de software.

.Información relacionada
https://www.netapp.com/pdf.html?item=/media/17174-tr4733pdf.pdf["Configuración síncrona y prácticas recomendadas de SnapMirror"^]
