---
permalink: release-notes/release-support-reference.html 
sidebar: sidebar 
keywords: release notes, release support, support levels 
summary: Obtenga más información sobre las nuevas funcionalidades disponibles en ONTAP 9. 
---
= Compatibilidad con la versión ONTAP 9
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir del lanzamiento de ONTAP 9,8, NetApp ofrece lanzamientos de ONTAP dos veces al año. Si bien los planes pueden modificarse, el objetivo es ofrecer nuevos lanzamientos de ONTAP en el segundo y cuarto trimestre de cada año. Utilice esta información para planificar el período de tiempo de su actualización para aprovechar la última versión de ONTAP.

[cols="50,50"]
|===
| Versión | Fecha de lanzamiento 


 a| 
9.17.1
 a| 
julio de 2025



 a| 
9.16.1
 a| 
Enero de 2025



 a| 
9.15.1
 a| 
Julio de 2024



 a| 
9.14.1
 a| 
Enero de 2024



 a| 
9.13.1
 a| 
Junio de 2023



 a| 
9.12.1
 a| 
Febrero de 2023



 a| 
9.11.1
 a| 
Julio de 2022



 a| 
9.10.1
 a| 
Enero de 2022



 a| 
9.9.1
 a| 
Junio de 2021



 a| 

NOTE: Si ejecuta una versión de ONTAP anterior a la 9,10.1, es probable que cuente con soporte limitado o soporte de autoservicio. Considere la posibilidad de actualizar a versiones con soporte completo. Puede verificar el nivel de soporte para su versión de ONTAP en el https://mysupport.netapp.com/site/info/version-support#ontap_svst["Sitio de soporte de NetApp"^].

|===


== Niveles de soporte

El nivel de soporte disponible para una versión específica de ONTAP varía en función de cuándo se lanzó el software.

[cols="20,10,10,10,10,10,10,10,10"]
|===
| Nivel de soporte 3+| Soporte completo 2+| Soporte limitado 3+| Soporte de autoservicio 


 a| 
Año
 a| 
1
 a| 
2
 a| 
3
 a| 
4
 a| 
5
 a| 
6
 a| 
7
 a| 
8



 a| 
Acceso a la documentación en línea
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



 a| 
Soporte técnico
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
 a| 
 a| 



 a| 
Análisis de las causas subyacentes
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
 a| 
 a| 



 a| 
Descargas de software de
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
 a| 
 a| 



 a| 
Actualizaciones de servicio (versiones de parches [P-releases])
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
 a| 
 a| 
 a| 
 a| 



 a| 
Alertas sobre vulnerabilidades
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
 a| 
 a| 
 a| 
 a| 

|===
Para actualizar a la última versión de ONTAP, consulte xref:../upgrade/prepare.html[Actualice a la última versión de ONTAP] y. xref:../upgrade/when-to-upgrade.html[¿Cuándo debo actualizar ONTAP?]
