---
permalink: release-notes/whats-new-9151.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.15.1' 
summary: Obtenga más información sobre las nuevas funcionalidades disponibles en ONTAP 9.15.1. 
---
= Novedades en ONTAP 9.15.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Obtenga más información sobre las nuevas funcionalidades disponibles en ONTAP 9.15.1.

Para obtener información detallada sobre problemas conocidos, limitaciones y precauciones de actualización en versiones recientes de ONTAP 9, consulte la https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notas de la versión de ONTAP 9"^]. Debe iniciar sesión con su cuenta de NetApp o crear una cuenta para acceder a las Notas de la versión.

Obtenga más información sobre las novedades y mejoras https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["Funciones de ONTAP MetroCluster"^].

Obtenga más información sobre el soporte nuevo y mejorado para https://docs.netapp.com/us-en/ontap-systems/whats-new.html["Plataformas FAS, ASA, AFF y switches compatibles"^].

Obtenga información sobre las actualizaciones de la https://docs.netapp.com/us-en/ontap-automation/whats_new.html["API REST de ONTAP"^].

Para actualizar a la última versión de ONTAP, consulte link:../upgrade/create-upgrade-plan.html["Prepárese para actualizar ONTAP"].



== Protección de datos

[cols="30%,70%"]
|===
| Actualizar | Descripción 


 a| 
xref:../smb-admin/windows-backup-symlinks.html[Aplicaciones de backup de Windows y symlinks de tipo Unix]
 a| 
Cuando una aplicación de copia de seguridad de Windows encuentra un enlace simbólico de estilo Unix (symlink), se sigue el enlace y ONTAP devuelve los datos reales y se realiza una copia de seguridad. A partir de ONTAP 9.15.1, también tiene la opción de hacer una copia de seguridad del symlink en sí mismo en lugar de los datos a los que apunta. Esto puede ofrecer varios beneficios, como un mejor rendimiento de sus aplicaciones de backup. Es posible habilitar la función mediante la interfaz de línea de comandos de ONTAP o la API DE REST.



 a| 
xref:../snapmirror-active-sync/index.html[La sincronización activa de SnapMirror admite puestas en marcha activo-activo simétricas]
 a| 
La sincronización activa de SnapMirror (anteriormente, SnapMirror Business Continuity) ahora admite implementaciones activo-activo simétricas, lo que permite realizar operaciones de I/O de lectura y escritura desde ambas copias de un LUN protegido con replicación síncrona bidireccional.



 a| 
Se aumentó el límite para volúmenes de un grupo de consistencia utilizando SnapMirror asíncrono
 a| 
Los grupos de consistencia que utilizan la protección asíncrona de SnapMirror ahora admiten hasta 80 volúmenes en el grupo de coherencia.



 a| 
xref:../consistency-groups/configure-task.html[Compatibilidad con el nivel de privilegio de administrador para operaciones de API de REST y CLI con grupos de coherencia]
 a| 
Las operaciones de CLI y API DE REST para grupos de consistencia ahora se admiten en el nivel de privilegio administrativo.



 a| 
xref:../concepts/ontap-and-vmware.html[Reservas persistentes para volúmenes virtuales de VMware con clustering de conmutación al nodo de respaldo de Windows Server]
 a| 
ONTAP admite actualmente volúmenes virtuales de VMware (vVols), así como reservas persistentes con LUN tradicionales. A partir de ONTAP 9.15.1, también puede crear una reserva persistente con un VVol. La compatibilidad con esta función se implementa en Herramientas de ONTAP para VMware vSphere 9. Solo se admite en un clúster de conmutación al nodo de respaldo de Windows Server (WSFC), que es un grupo de máquinas virtuales de Windows en clúster.

|===


== Seguridad

[cols="30%,70%"]
|===
| Actualizar | Descripción 


 a| 
xref:../nas-audit/create-persistent-stores.html[Creación y configuración simplificadas de almacén persistente FPolicy]
 a| 
Puede crear el almacén persistente de FPolicy y automatizar su creación y configuración de volúmenes al mismo tiempo mediante el `persistent-store create` comando.

Mejorado `persistent-store create` el comando también permite utilizar el parámetro autosize-mode, que permite que el volumen aumente o reduzca su tamaño en respuesta a la cantidad de espacio utilizado.



 a| 
xref:../nfs-rdma/index.html[Compatibilidad con NFSv3 con RDMA]
 a| 
Las configuraciones de NFS sobre RDMA ahora admiten NFSv3.



 a| 
xref:../nas-audit/supported-file-operation-filter-fpolicy-nfsv4-concept.html[FPolicy es compatible con el protocolo NFS 4,1]
 a| 
FPolicy es compatible con el protocolo NFS 4,1.



 a| 
xref:../nas-audit/plan-fpolicy-external-engine-config-concept.html[Soporte de formato de motor Protobuf para FPolicy]
 a| 
Protobuf es el mecanismo de Google neutral en el lenguaje para serializar datos estructurados. Es más pequeño, más rápido y más simple en comparación con XML, lo que ayuda a mejorar el rendimiento de FPolicy.

Puede utilizar el formato de motor externo protobuf. Cuando se establece en protobuf, los mensajes de notificación se codifican en formato binario utilizando Google Protobuf. Antes de configurar el formato de motor externo en protobuf, asegúrese de que el servidor FPolicy también admita la deserialización de protobuf.



 a| 
xref:../authentication/dynamic-authorization-overview.html[Autorización dinámica para conexiones SSH]
 a| 
ONTAP 9.15.1 proporciona el marco inicial para la autorización dinámica, que proporciona una seguridad mejorada para la gestión del sistema ONTAP, ya que le permite asignar una puntuación de confianza de seguridad a los usuarios administradores y desafiarlos con comprobaciones de autorización adicionales cuando su actividad parece sospechosa.  Puede utilizar la autorización dinámica como parte de una arquitectura de seguridad de confianza cero centrada en los datos.



 a| 
Compatibilidad con TLS 1,3 para almacenamiento S3, FlexCache y cifrado de relación entre iguales de clústeres
 a| 
Desde ONTAP 9.11.1 se admite TLS 1,3 para el acceso de gestión, pero ahora es compatible con ONTAP 9.15.1 para el almacenamiento S3, FlexCache y cifrado de paridad de clústeres. Algunas aplicaciones, como FabricPool, el almacenamiento de Microsoft Azure Page Blobs y SnapMirror Cloud, siguen estando limitadas al uso de TLS 1,2 para la versión 9.15.1.



 a| 
xref:../nfs-admin/tls-nfs-strong-security-concept.html[Compatibilidad de TLS para conexiones NFS]
 a| 
NFS con TLS está disponible en ONTAP 9.15.1 como versión preliminar pública. Como oferta de vista previa, NFS sobre TLS no se admite en las cargas de trabajo de producción en ONTAP 9.15.1.

NFS a través de TLS proporciona cifrado en tránsito de los datos del dispositivo de almacenamiento al cliente. TLS es más reciente y conveniente que Kerberos, lo que permite una configuración y una administración más sencillas.



 a| 
xref:../multi-admin-verify/index.html#rule-protected-commands[Conjunto elegible de comandos protegidos por reglas ampliado para la verificación multiadministrador]
 a| 
Los administradores pueden crear reglas de verificación de varios administradores para proteger la configuración de clústeres, la eliminación de LUN, la configuración del sistema, la configuración de seguridad para IPsec y SAML, las operaciones de copias Snapshot de volúmenes, la configuración de vServer y otros comandos.



 a| 
xref:../system-admin/requirements-autosupport-reference.html[Entrega de mensajes de AutoSupport mediante SMTP con TLS]
 a| 
Aunque el transporte recomendado de mensajes de AutoSupport a NetApp es HTTPS, también ha estado disponible SMTP sin cifrar. Con ONTAP 9.15.1, los clientes ahora tienen la opción de usar TLS con SMTP. El protocolo SMTPS establece un canal de transporte seguro mediante el cifrado del tráfico de correo electrónico, así como las credenciales opcionales del servidor de correo electrónico. Se utiliza TLS explícito, por lo que TLS se activa después de crear la conexión TCP. Si se envían copias de los mensajes a direcciones de correo electrónico locales, se utiliza la misma configuración.

|===


== Eficiencia del almacenamiento

[cols="30%,70%"]
|===
| Actualizar | Descripción 


 a| 
xref:../volumes/determine-space-usage-volume-aggregate-concept.html[Cambios en los informes de métricas de espacio de volumen]
 a| 
Se han introducido dos contadores nuevos que muestran solo los metadatos que se están usando. Además, varios de los contadores existentes se han ajustado para eliminar los metadatos y mostrar solo los datos del usuario. Juntos, estos cambios proporcionan una visión más clara de las métricas separadas en los dos tipos de datos. Los clientes pueden utilizar estos contadores para implementar modelos de pago por uso más precisos descontando los metadatos del total y solo teniendo en cuenta los datos reales del usuario.



 a| 
xref:../concepts/builtin-storage-efficiency-concept.html[Eficiencia del almacenamiento con CPU o procesador de descarga dedicado]
 a| 
ONTAP proporciona eficiencia del almacenamiento y compactación de datos en plataformas AFF A70, AFF A90 y AFF A1K. Dependiendo de la plataforma, la compresión se realiza utilizando la CPU principal o con un procesador de descarga dedicado. La eficiencia del almacenamiento se activa de forma automática y no requiere configuración.

|===


== Mejoras de administración de recursos de almacenamiento

[cols="30%,70%"]
|===
| Actualizar | Descripción 


 a| 
xref:../flexcache-writeback/flexcache-writeback-enable-task.html[Compatibilidad con reescritura de FlexCache]
 a| 
Cuando se habilita la retroescritura en el volumen de caché, las solicitudes de escritura se envían a la caché local en lugar de al volumen de origen, lo que proporciona mejor rendimiento en entornos informáticos perimetrales y caché con cargas de trabajo con gran carga de escritura.



 a| 
xref:../task_nas_file_system_analytics_enable.html[Mejora del rendimiento para el análisis de sistemas de archivos]
 a| 
ONTAP aplica que del 5 al 8 % de la capacidad de un volumen debe estar libre al habilitar el análisis del sistema de archivos, lo que mitiga los posibles problemas de rendimiento en volúmenes y análisis del sistema de archivos.



 a| 
Claves de cifrado de volúmenes FlexClone
 a| 
A un volumen FlexClone se le asigna una clave de cifrado dedicada independiente de la clave de cifrado (host) del volumen FlexVol.

|===


== System Manager

[cols="30%,70%"]
|===
| Actualizar | Descripción 


 a| 
xref:../snaplock/commit-snapshot-copies-worm-concept.html[Compatibilidad con System Manager para configurar relaciones de almacén de SnapLock]
 a| 
Las relaciones de almacén de SnapLock se pueden configurar mediante System Manager cuando el origen y el destino ejecutan ONTAP 9.15.1 o una versión posterior.



 a| 
xref:../task_cp_dashboard_tour.html[Mejoras en el rendimiento del panel de System Manager]
 a| 
La información de las vistas Estado, Capacidad, Red y Rendimiento de la consola de System Manager incluye descripciones más completas, incluidas mejoras de las métricas de rendimiento que ayudan a identificar y solucionar problemas de latencia o rendimiento.

|===


== Renovar

[cols="30%,70%"]
|===
| Actualizar | Descripción 


 a| 
xref:../upgrade/automated-upgrade-task.html[Soporte para la migración de LIF al nodo de partner de alta disponibilidad durante las actualizaciones automatizadas no disruptivas]
 a| 
Si la migración de LIF al otro grupo de lotes falla durante una actualización no disruptiva automática, las LIF se migran al nodo del partner de alta disponibilidad en el mismo grupo de lotes.

|===