---
permalink: fabricpool/commands-manage-aggregates-reference.html 
sidebar: sidebar 
keywords: commands, managing, aggregates, storage aggregate object-store config 
summary: Los comandos de almacén de objetos del agregado de almacenamiento se utilizan para gestionar almacenes de objetos para FabricPool. Los comandos del agregado de almacenamiento se utilizan para gestionar agregados para FabricPool. Es posible usar los comandos de volumen para gestionar volúmenes para FabricPool. 
---
= Comandos para gestionar recursos de FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `storage aggregate object-store`Los comandos se usan para gestionar almacenes de objetos para FabricPool. Los `storage aggregate` comandos se usan para gestionar agregados para FabricPool.  `volume`Los comandos se usan para gestionar volúmenes para FabricPool.

|===


| Si desea... | Utilizar este comando: 


 a| 
Defina la configuración de un almacén de objetos para que ONTAP pueda acceder a él
 a| 
`storage aggregate object-store config create`



 a| 
Modifique los atributos de configuración del almacén de objetos
 a| 
`storage aggregate object-store config modify`



 a| 
Cambie el nombre de una configuración de almacén de objetos existente
 a| 
`storage aggregate object-store config rename`



 a| 
Eliminar la configuración de un almacén de objetos
 a| 
`storage aggregate object-store config delete`



 a| 
Mostrar una lista de configuraciones del almacén de objetos
 a| 
`storage aggregate object-store config show`



 a| 
Asocie un segundo almacén de objetos a una FabricPool nueva o existente como reflejo
 a| 
`storage aggregate object-store mirror` con `-aggregate` `-name` el parámetro and en el nivel de privilegios de administrador



 a| 
Quite un reflejo de almacén de objetos de un reflejo de FabricPool existente
 a| 
`storage aggregate object-store unmirror` con `-aggregate` `-name` el parámetro and en el nivel de privilegios de administrador



 a| 
Supervisar el estado de resincronización de mirroring FabricPool
 a| 
`storage aggregate object-store show-resync-status`



 a| 
Muestra los detalles del reflejo de FabricPool
 a| 
`storage aggregate object-store show`



 a| 
Promocione un reflejo de almacén de objetos para reemplazar un almacén de objetos principal en una configuración de mirroring FabricPool
 a| 
`storage aggregate object-store modify` con `-aggregate` el parámetro en el nivel de privilegios de administrador



 a| 
Probar la latencia y el rendimiento de un almacén de objetos sin adjuntar el almacén de objetos a un agregado
 a| 
`storage aggregate object-store profiler start` con `-object-store-name` `-node` el parámetro and en el nivel de privilegio avanzado



 a| 
Supervise el estado del perfilador del almacén de objetos
 a| 
`storage aggregate object-store profiler show` con `-object-store-name` `-node` el parámetro and en el nivel de privilegio avanzado



 a| 
Aborte el perfilador del almacén de objetos cuando se está ejecutando
 a| 
`storage aggregate object-store profiler abort` con `-object-store-name` `-node` el parámetro and en el nivel de privilegio avanzado



 a| 
Asocie un almacén de objetos a un agregado para usar FabricPool
 a| 
`storage aggregate object-store attach`



 a| 
Asocie un almacén de objetos a un agregado que contiene un volumen de FlexGroup para usar FabricPool
 a| 
`storage aggregate object-store attach` con la `allow-flexgroup` `true`



 a| 
Muestra detalles de los almacenes de objetos adjuntos a agregados habilitados para FabricPool
 a| 
`storage aggregate object-store show`



 a| 
Muestre el umbral de ocupación del agregado utilizado por el análisis de organización en niveles
 a| 
`storage aggregate object-store show` con `-fields tiering-fullness-threshold` el parámetro en el nivel de privilegio avanzado



 a| 
Muestra el uso de espacio de los almacenes de objetos adjuntos a agregados habilitados para FabricPool
 a| 
`storage aggregate object-store show-space`



 a| 
Habilite la generación de informes de datos inactivos en un agregado que no se use para FabricPool
 a| 
`storage aggregate modify` con el `-is-inactive-data-reporting-enabled true` parámetro



 a| 
Mostrar si la generación de informes de datos inactivos está habilitada en un agregado
 a| 
`storage aggregate show` con el `-fields is-inactive-data-reporting-enabled` parámetro



 a| 
Muestra información sobre la cantidad de datos de usuario que están inactivos en un agregado
 a| 
`storage aggregate show-space` con el `-fields performance-tier-inactive-user-data,performance-tier-inactive-user-data-percent` parámetro



 a| 
Cree un volumen para FabricPool, incluidos los siguientes elementos:

* La política de organización en niveles
* El período de enfriamiento mínimo de organización en niveles (para `snapshot-only` `auto` la política o de organización en niveles)

 a| 
`volume create`

* Use `-tiering-policy` el parámetro para especificar la política de organización en niveles.
* Use `-tiering-minimum-cooling-days` el parámetro del nivel de privilegio avanzado para especificar el período de enfriamiento mínimo de la organización en niveles.




 a| 
Modifique un volumen para FabricPool, incluidos los siguientes elementos:

* La política de organización en niveles
* El período de enfriamiento mínimo de organización en niveles (para `snapshot-only` `auto` la política o de organización en niveles)

 a| 
`volume modify`

* Use `-tiering-policy` el parámetro para especificar la política de organización en niveles.
* Use `-tiering-minimum-cooling-days` el parámetro del nivel de privilegio avanzado para especificar el período de enfriamiento mínimo de la organización en niveles.




 a| 
Muestra información de FabricPool relacionada con un volumen, incluidos los siguientes:

* El período de enfriamiento mínimo de organización en niveles
* ¿Qué cantidad de datos de usuario no están activos

 a| 
`volume show`

* Use `-fields tiering-minimum-cooling-days` el parámetro del nivel de privilegio avanzado para mostrar el período de enfriamiento mínimo de la organización en niveles.
* El `-fields performance-tier-inactive-user-data,performance-tier-inactive-user-data-percent` parámetro se utiliza para mostrar la cantidad de datos de usuario inactivos.




 a| 
Mover un volumen dentro o fuera de FabricPool
 a| 
`volume move start` El `-tiering-policy` parámetro opcional se usa para especificar la política de organización en niveles del volumen.



 a| 
Modifique el umbral para recuperar espacio no referenciado (el umbral de desfragmentación) para FabricPool
 a| 
`storage aggregate object-store modify` con `-unreclaimed-space-threshold` el parámetro en el nivel de privilegio avanzado



 a| 
Modifique el umbral del porcentaje de completado del agregado antes de que el análisis por niveles comience a organizar los datos en niveles para FabricPool

FabricPool sigue organizando datos fríos en niveles en un nivel de cloud hasta que el nivel local alcanza un 98 % de la capacidad.
 a| 
`storage aggregate object-store modify` con `-tiering-fullness-threshold` el parámetro en el nivel de privilegio avanzado



 a| 
Muestre el umbral para recuperar espacio no referenciado para FabricPool
 a| 
`storage aggregate object-store show` o `storage aggregate object-store show-space` comando con `-unreclaimed-space-threshold` el parámetro en el nivel de privilegio avanzado

|===