---
permalink: fabricpool/delete-tag-task.html 
sidebar: sidebar 
keywords: deleting, tag, existing 
summary: Puede eliminar etiquetas de objetos cuando ya no desee que estén establecidas en un volumen o en objetos del almacén de objetos. 
---
= Eliminar una etiqueta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede eliminar etiquetas de objetos cuando ya no desee que estén establecidas en un volumen o en objetos del almacén de objetos.



== Procedimiento

Puede eliminar etiquetas de objetos con ONTAP System Manager o la interfaz de línea de comandos de ONTAP.

[role="tabbed-block"]
====
.System Manager
--
. Vaya a *almacenamiento > niveles*.
. Busque un nivel de almacenamiento con volúmenes que contengan etiquetas que desee eliminar.
. Haga clic en la ficha *Volumes*.
. Localice el volumen con etiquetas que desee eliminar y, en la columna *Etiquetas de objeto*, haga clic en el nombre de la etiqueta.
. Para eliminar la etiqueta, haga clic en el icono de papelera.
. Haga clic en *aplicar*.


--
.CLI
--
. Utilice la `volume modify` con el `-tiering-object-tags` opción seguida de un valor vacío (`""`) para eliminar una etiqueta existente.
+
En el siguiente ejemplo, se eliminan las etiquetas existentes en fp_volume1.

+
[listing]
----
vol modify -volume fp_volume1 -vserver vs0 -tiering-object-tags ""
----


--
====