---
permalink: fabricpool/install-ca-certificate-storagegrid-task.html 
sidebar: sidebar 
keywords: installing, ca certificate, storagegrid 
summary: A menos que planifique deshabilitar la comprobación de certificados para StorageGRID, debe instalar un certificado de CA de StorageGRID en el clúster para que ONTAP pueda autenticarse con StorageGRID como almacén de objetos para FabricPool. 
---
= Instale un certificado de CA si utiliza StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A menos que planifique deshabilitar la comprobación de certificados para StorageGRID, debe instalar un certificado de CA de StorageGRID en el clúster para que ONTAP pueda autenticarse con StorageGRID como almacén de objetos para FabricPool.

.Acerca de esta tarea
ONTAP 9.4 y versiones posteriores permiten deshabilitar la comprobación de certificados para StorageGRID.

.Pasos
. Póngase en contacto con el administrador de StorageGRID para obtener el certificado de CA del sistema StorageGRID.
. Utilice la `security certificate install` con el `-type` `server-ca` Parámetro para instalar el certificado de CA de StorageGRID en el clúster.
+
El nombre de dominio completo (FQDN) que introduzca debe coincidir con el nombre común personalizado del certificado de CA de StorageGRID.





== Actualice un certificado caducado

Para actualizar un certificado caducado, la práctica recomendada es usar una CA de confianza para generar el nuevo certificado de servidor. Además, debe asegurarse de que el certificado se actualice en el servidor StorageGRID y en el clúster de ONTAP al mismo tiempo para mantener el tiempo de inactividad al mínimo.

.Información relacionada
https://www.netapp.com/data-storage/storagegrid/documentation["Recursos de StorageGRID"]
