---
permalink: fabricpool/install-ca-certificate-ontap-s3-task.html 
sidebar: sidebar 
keywords: installing, ca certificate, ontap s3 
summary: A menos que planifique deshabilitar la comprobación de certificados para ONTAP S3, debe instalar un certificado de CA de ONTAP S3 en el clúster para que ONTAP pueda autenticarse con ONTAP S3 como almacén de objetos para FabricPool. 
---
= Instale un certificado de CA si usa ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A menos que planifique deshabilitar la comprobación de certificados para ONTAP S3, debe instalar un certificado de CA de ONTAP S3 en el clúster para que ONTAP pueda autenticarse con ONTAP S3 como almacén de objetos para FabricPool.

.Pasos
. Obtenga el certificado de CA del sistema ONTAP S3.
. Utilice la `security certificate install` con el `-type` `server-ca` Parámetro para instalar el certificado de CA de ONTAP S3 en el clúster.
+
El nombre de dominio completo (FQDN) que introduzca debe coincidir con el nombre común personalizado en el certificado de CA de ONTAP S3.





== Actualice un certificado caducado

Para actualizar un certificado caducado, la práctica recomendada es usar una CA de confianza para generar el nuevo certificado de servidor. Además, debe asegurarse de que el certificado se actualice en el servidor ONTAP S3 y en el clúster ONTAP al mismo tiempo para mantener el tiempo de inactividad al mínimo.

.Información relacionada
link:../s3-config/index.html["Configuración de S3"]
