---
permalink: fabricpool/migration-controls-override-tiering-policy-task.html 
sidebar: sidebar 
keywords: cloud migration, controls, override, volume, default, tiering policy 
summary: Es posible cambiar la política de organización en niveles predeterminada de un volumen para controlar la recuperación de datos de usuario del nivel de cloud al nivel de rendimiento con la opción de política -cloud-recuperación-introducida en ONTAP 9.8. 
---
= Modifique la política de organización en niveles predeterminada de FabricPool de un volumen de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede cambiar la política de organización en niveles predeterminada de un volumen para controlar la recuperación de datos de usuario del nivel de cloud al nivel de rendimiento con `-cloud-retrieval-policy` la opción introducida en ONTAP 9.8.

.Antes de empezar
* Para modificar un volumen que utiliza `-cloud-retrieval-policy` la opción, se requiere ONTAP 9 Intersight 8 o posterior.
* Debe tener el nivel de privilegio avanzado para realizar esta operación.
* Debe comprender el comportamiento de las políticas de organización en niveles con `-cloud-retrieval-policy`.
+
link:tiering-policies-concept.html#how-tiering-policies-work-with-cloud-migration["Funcionamiento de las políticas de organización en niveles con la migración al cloud"]



.Paso
. Modifique el comportamiento de la política de organización en niveles para un volumen existente mediante `volume modify` el comando con `-cloud-retrieval-policy` la opción:
+
[listing]
----
 volume create -volume <volume_name> -vserver <vserver_name> - tiering-policy <policy_name> -cloud-retrieval-policy
----
+
[listing]
----
vol modify -volume fp_volume4 -vserver vs0 -cloud-retrieval-policy promote
----

