---
permalink: fabricpool/modify-cloud-retrieval-policy-task.html 
sidebar: sidebar 
keywords: cloud retrieval, controls, volume, default, tiering policy 
summary: Puedes cambiar la política de recuperación en la nube de un volumen usando la opción -cloud-retrieval-policy, que se introdujo en ONTAP 9.8. 
---
= Modificar la política de recuperación en la nube de un volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La recuperación de datos en la nube de FabricPool está controlada por políticas de recuperación que determinan cuándo los datos se escriben de nuevo en el nivel local. Los patrones de lectura pueden ser secuenciales o aleatorios.

Por ejemplo, cuando usas la política de jerarquización de volúmenes 'Auto', si los bloques fríos se leen de forma secuencial, siguen fríos y permanecen en el cloud tier. Para la mayoría de las aplicaciones cliente, este es un comportamiento deseable y evita que los análisis profundos de archivos, comunes en aplicaciones antivirus y de analytics, escriban datos fríos de nuevo en el tier local.

A partir de ONTAP 9.8, puedes cambiar la política de recuperación en la nube de un volumen para anular el comportamiento de link:tiering-policies-concept.html#how-cloud-retrieval-policies-work-with-tiering-policies["Recuperación predeterminada en la nube"].

.Antes de empezar
* Para modificar un volumen que utiliza `-cloud-retrieval-policy` la opción, se requiere ONTAP 9 Intersight 8 o posterior.
* Debe tener el nivel de privilegio avanzado para realizar esta operación.
* Debe comprender el comportamiento de las políticas de organización en niveles con `-cloud-retrieval-policy`.
+
link:tiering-policies-concept.html#how-cloud-retrieval-policies-work-with-tiering-policies["Cómo funcionan las políticas de recuperación en la nube junto con las políticas de clasificación por niveles"]



.Paso
. Modifica la política de recuperación en la nube de un volumen existente usando el comando  `volume modify` con la opción  `-cloud-retrieval-policy`:
+
[listing]
----
volume create -volume <volume_name> -vserver <vserver_name> - tiering-policy <policy_name> -cloud-retrieval-policy
----
+
[listing]
----
vol modify -volume fp_volume4 -vserver vs0 -cloud-retrieval-policy promote
----

