---
permalink: fabricpool/monitor-space-utilization-task.html 
sidebar: sidebar 
keywords: monitoring, space, utilization, fabricpool 
summary: Necesita saber cuántos datos se almacenan en el rendimiento y los niveles cloud para FabricPool. Esa información le ayuda a determinar si necesita cambiar la política de organización en niveles de un volumen, aumentar el límite de uso de licencias de FabricPool o aumentar el espacio de almacenamiento del nivel de cloud. 
---
= Supervise el uso de espacio para FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Necesita saber cuántos datos se almacenan en el rendimiento y los niveles cloud para FabricPool. Esa información le ayuda a determinar si necesita cambiar la política de organización en niveles de un volumen, aumentar el límite de uso de licencias de FabricPool o aumentar el espacio de almacenamiento del nivel de cloud.

.Pasos
. Supervise el uso del espacio de los agregados habilitados para FabricPool utilizando uno de los siguientes comandos para mostrar la información:
+
|===


| Si desea mostrar... | Después, utilice este comando: 


 a| 
El tamaño usado del nivel de cloud en un agregado
 a| 
`storage aggregate show` con la `-instance` parámetro



 a| 
Detalles del uso de espacio dentro de un agregado, incluida la capacidad de referencia del almacén de objetos
 a| 
`storage aggregate show-space` con la `-instance` parámetro



 a| 
Aprovechamiento de espacio de los almacenes de objetos adjuntos a los agregados, incluido la cantidad de espacio de licencia que se está utilizando
 a| 
`storage aggregate object-store show-space`



 a| 
Una lista de volúmenes de un agregado y los espacios utilizados por sus datos y metadatos
 a| 
`volume show-footprint`

|===
+
Además de usar comandos de la CLI, puede usar Active IQ Unified Manager (anteriormente Unified Manager de OnCommand), junto con FabricPool Advisor, que está compatible con ONTAP 9.4 y clústeres posteriores, o System Manager para supervisar el uso de espacio.

+
El ejemplo siguiente muestra maneras de mostrar la utilización del espacio y la información relacionada para FabricPool:

+
[listing]
----
cluster1::> storage aggregate show-space -instance

                          Aggregate: MyFabricPool
                                                                   ...
                                               Aggregate Display Name: MyFabricPool
                                                                   ...
                          Total Object Store Logical Referenced Capacity: -
                          Object Store Logical Referenced Capacity Percentage: -
                                                                   ...
                                                       Object Store Size: -
                          Object Store Space Saved by Storage Efficiency: -
                          Object Store Space Saved by Storage Efficiency Percentage: -
                                                 Total Logical Used Size: -
                                                 Logical Used Percentage: -
                                           Logical Unreferenced Capacity: -
                                         Logical Unreferenced Percentage: -

----
+
[listing]
----
cluster1::> storage aggregate show -instance

                           Aggregate: MyFabricPool
                           ...
                           Composite: true
                           Capacity Tier Used Size:
                           ...
----
+
[listing]
----
cluster1::> volume show-footprint

Vserver : vs1
Volume : rootvol

Feature                          Used       Used%
-------------------------------- ---------- -----
Volume Footprint                 KB          %
Volume Guarantee                 MB          %
Flexible Volume Metadata         KB          %
Delayed Frees                    KB          %
Total Footprint                  MB          %

Vserver : vs1
Volume : vol

Feature                          Used       Used%
-------------------------------- ---------- -----
Volume Footprint                 KB          %
Footprint in Performance Tier    KB          %
Footprint in Amazon01            KB          %
Flexible Volume Metadata         MB          %
Delayed Frees                    KB          %
Total Footprint                  MB          %
...
----
. Realice una de las siguientes acciones según sea necesario:
+
|===


| Si desea... | Realice lo siguiente... 


 a| 
Cambiar la política de organización en niveles de un volumen
 a| 
Siga el procedimiento descrito en link:modify-tiering-policy-cooling-period-task.html["Gestionar el almacenamiento por niveles mediante la modificación de la política de organización en niveles de un volumen o la organización en niveles del período de refrigeración mínimo"].



 a| 
Aumente el límite de uso de licencias de FabricPool
 a| 
Comuníquese con su representante de ventas para socios o con el representante de NetApp.

https://mysupport.netapp.com/site/global/dashboard["Soporte de NetApp"]



 a| 
Aumente el espacio de almacenamiento del nivel de cloud
 a| 
Póngase en contacto con el proveedor del almacén de objetos que usa para el nivel de cloud.

|===

