---
permalink: fabricpool/replace-mirror-mcc-task.html 
sidebar: sidebar 
keywords: replacing, fabricpool, mirror, metrocluster, configuration 
summary: Si uno de los almacenes de objetos de un reflejo de FabricPool se destruye o deja de estar disponible en una configuración de MetroCluster, puede hacer que el almacén de objetos del reflejo no sea el reflejo, si ya no se encuentra dañado, retirar el almacén de objetos del reflejo de FabricPool, Y, a continuación, añada un nuevo reflejo de almacén de objetos a la FabricPool. 
---
= Reemplace un reflejo de FabricPool en una configuración ONTAP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si uno de los almacenes de objetos de un reflejo de FabricPool se destruye o deja de estar disponible en una configuración de MetroCluster, puede hacer que el almacén de objetos del reflejo no sea el reflejo, si ya no se encuentra dañado, retirar el almacén de objetos del reflejo de FabricPool, Y, a continuación, añada un nuevo reflejo de almacén de objetos a la FabricPool.

.Pasos
. Si el almacén de objetos dañado aún no es el reflejo, haga que el objeto almacene el reflejo con el `storage aggregate object-store modify` comando.
+
[listing]
----
storage aggregate object-store modify -aggregate -aggregate fp_aggr1_A01 -name mcc1_ostore1 -mirror-type mirror
----
. Quite el reflejo de almacén de objetos de la FabricPool con `storage aggregate object-store unmirror` el comando.
+
[listing]
----
storage aggregate object-store unmirror -aggregate <aggregate name> -name mcc1_ostore1
----
. Puede forzar la reanudación de la organización en niveles en el almacén de datos primario después de eliminar el almacén de datos de reflejos mediante `storage aggregate object-store modify` `-force-tiering-on-metrocluster true` la opción con la.
+
La ausencia de un reflejo interfiere con los requisitos de replicación de la configuración de MetroCluster.

+
[listing]
----
storage aggregate object-store modify -aggregate <aggregate name> -name mcc1_ostore1 -force-tiering-on-metrocluster true
----
. Cree un almacén de objetos de reemplazo mediante `storage aggregate object-store config create` el comando.
+
[listing]
----
storage aggregate object-store config create -object-store-name mcc1_ostore3 -cluster clusterA -provider-type SGWS -server <SGWS-server-1> -container-name <SGWS-bucket-1> -access-key <key> -secret-password <password> -encrypt <true|false> -provider <provider-type> -is-ssl-enabled <true|false> ipspace <IPSpace>
----
. Añada el reflejo del almacén de objetos a la FabricPool mirror con `storage aggregate object-store mirror` el comando.
+
[listing]
----
storage aggregate object-store mirror -aggregate aggr1 -name mcc1_ostore3-mc
----
. Muestra la información del almacén de objetos mediante `storage aggregate object-store show` el comando.
+
[listing]
----
storage aggregate object-store show -fields mirror-type,is-mirror-degraded
----
+
[listing]
----
aggregate      object-store-name mirror-type     is-mirror-degraded
-------------- ----------------- ------------- ------------------
aggr1          mcc1_ostore1-mc    primary           -
               mcc1_ostore3-mc    mirror          true
----
. Supervise el estado de resincronización de mirroring con `storage aggregate object-store show-resync-status` el comando.
+
[listing]
----
storage aggregate object-store show-resync-status -aggregate aggr1
----
+
[listing]
----
                                                  Complete
      Aggregate    Primary        Mirror          Percentage
      ---------    -----------    ----------      ----------
      aggr1        mcc1_ostore1-mc mcc1_ostore3-mc   40%
----


.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-create.html["almacenamiento agregado objeto-almacén configuración crear"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-mirror.html["espejo de almacén de objetos agregados de almacenamiento"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-modify.html["almacenamiento agregado objeto-almacén modificar"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-show.html["almacenamiento agregado objeto-almacén mostrar"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-show-resync-status.html["almacenamiento agregado almacén de objetos mostrar estado de resincronización"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-unmirror.html["almacenamiento agregado objeto-almacén desduplicado"^]

