---
permalink: fabricpool/replace-existing-object-store-mirror-task.html 
sidebar: sidebar 
keywords: replacing, existing, object, store, fabricpool, mirror 
summary: Es posible usar la tecnología de duplicación FabricPool para reemplazar un almacén de objetos por otro. No es necesario que el nuevo almacén de objetos utilice el mismo proveedor de cloud que el almacén de objetos original. 
---
= Reemplace un almacén de objetos existente por medio de un reflejo FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible usar la tecnología de duplicación FabricPool para reemplazar un almacén de objetos por otro. No es necesario que el nuevo almacén de objetos utilice el mismo proveedor de cloud que el almacén de objetos original.

.Acerca de esta tarea
Puede reemplazar el almacén de objetos original por un almacén de objetos que utilice un proveedor de cloud diferente. Por ejemplo, su almacén de objetos original podría usar AWS como proveedor de cloud, pero puede reemplazarlo por un almacén de objetos que usa Azure como proveedor de cloud y viceversa. Sin embargo, el nuevo almacén de objetos debe conservar el mismo tamaño de objeto que el original.

.Pasos
. Cree un reflejo de FabricPool añadiendo un almacén de objetos nuevo a una FabricPool existente mediante el `storage aggregate object-store mirror` comando.
+
[listing]
----
cluster1::> storage aggregate object-store mirror -aggregate aggr1 -name my-AZURE-store
----
. Supervise el estado de resincronización de mirroring mediante el `storage aggregate object-store show-resync-status` comando.
+
[listing]
----
cluster1::> storage aggregate object-store show-resync-status -aggregate aggr1
----
+
[listing]
----
                                                  Complete
      Aggregate    Primary          Mirror        Percentage
      ---------    -----------      ----------    ----------
      aggr1        my-AWS-store     my-AZURE-store     40%
----
. Compruebe que el reflejo esté sincronizado mediante el `storage aggregate object-store> show -fields mirror-type,is-mirror-degraded` comando.
+
[listing]
----
cluster1::> storage aggregate object-store show -fields mirror-type,is-mirror-degraded
----
+
[listing]
----
aggregate      object-store-name mirror-type     is-mirror-degraded
-------------- ----------------- ------------- ------------------
aggr1          my-AWS-store        primary           -
               my-AZURE-store      mirror          false
----
. Cambie el almacén de objetos principal por el almacén de objetos mirror mediante `storage aggregate object-store modify` comando.
+
[listing]
----
cluster1::> storage aggregate object-store modify -aggregate aggr1 -name my-AZURE-store -mirror-type primary
----
. Muestra detalles sobre el reflejo de FabricPool mediante el `storage aggregate object-store show -fields mirror-type,is-mirror-degraded` comando.
+
Este ejemplo muestra la información sobre el reflejo FabricPool, que incluye si el reflejo está degradado (no está sincronizado).

+
[listing]
----
cluster1::> storage aggregate object-store show -fields mirror-type, is-mirror-degraded
----
+
[listing]
----
aggregate      object-store-name mirror-type     is-mirror-degraded
-------------- ----------------- ------------- ------------------
aggr1          my-AZURE-store      primary           -
               my-AWS-store        mirror          false
----
. Quite el espejo FabricPool con el `storage aggregate object-store unmirror` comando.
+
[listing]
----
cluster1::> storage aggregate object-store unmirror -aggregate aggr1
----
. Compruebe que la FabricPool vuelve a estar en una configuración de almacén de objetos individual mediante el `storage aggregate object-store show -fields mirror-type,is-mirror-degraded` comando.
+
[listing]
----
cluster1::> storage aggregate object-store show -fields mirror-type,is-mirror-degraded
----
+
[listing]
----
aggregate      object-store-name mirror-type     is-mirror-degraded
-------------- ----------------- ------------- ------------------
aggr1          my-AZURE-store      primary           -
----

