---
permalink: fabricpool/requirements-concept.html 
sidebar: sidebar 
keywords: considerations, requirements, using, fabricpool 
summary: Para garantizar la optimización de sus configuraciones de FabricPool, debe familiarizarse con algunas consideraciones y requisitos sobre el uso de FabricPool. 
---
= Requisitos para usar ONTAP FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para garantizar la optimización de sus configuraciones de FabricPool, debe familiarizarse con algunas consideraciones y requisitos sobre el uso de FabricPool.



== Consideraciones y requisitos generales



=== ONTAP 9,2

Debe ejecutar ONTAP 9,2 o una versión posterior de FabricPool.



=== ONTAP 9,4

* Debe ejecutar ONTAP 9.4 o versiones posteriores para la siguiente funcionalidad de FabricPool:
+
** La `auto` link:tiering-policies-concept.html#types-of-fabricpool-tiering-policies["política de organización en niveles"]
** Especificación del período de enfriamiento mínimo de organización en niveles
** Generación de informes de datos inactivos (IDR)
** Uso del almacenamiento de Microsoft Azure Blob para el cloud como nivel de cloud para FabricPool
** Uso de FabricPool con ONTAP Select






=== ONTAP 9,5

* Debe ejecutar ONTAP 9,5 o versiones posteriores para establecer la siguiente funcionalidad de FabricPool:
+
** Especificar el umbral de ocupación de la organización en niveles
** Uso del almacenamiento de objetos en el cloud de IBM como nivel de cloud para FabricPool
** NetApp Volume Encryption (NVE) del nivel de cloud, habilitado de forma predeterminada.






=== ONTAP 9,6

* Debe ejecutar ONTAP 9,6 o versiones posteriores para establecer la siguiente funcionalidad de FabricPool:
+
** La `all` política de organización en niveles
** Generación de informes de datos inactivos habilitada manualmente en agregados de HDD
** La generación de informes de datos inactivos se habilita automáticamente para los agregados de SSD cuando actualiza a ONTAP 9.6 y en el momento en que se crea el agregado, a excepción de los sistemas de gama baja con menos de 4 CPU, menos de 6 GB de RAM o cuando el tamaño de la caché de búfer de WAFL es inferior a 3 GB.
+
ONTAP supervisa la carga del sistema y si la carga permanece alta durante 4 minutos continuos, el IDR se desactiva y no se activa automáticamente. Puede volver a habilitar IDR manualmente, sin embargo, IDR habilitado manualmente no se desactiva automáticamente.

** Uso de Alibaba Cloud Object Storage como nivel cloud para FabricPool
** Uso de Google Cloud Platform como nivel de cloud para FabricPool
** Movimiento de volúmenes sin copia de datos de nivel en el cloud






=== ONTAP 9,7

* Debe ejecutar ONTAP 9,7 o versiones posteriores para establecer la siguiente funcionalidad de FabricPool:
+
** Proxy HTTP y HTTPS no transparente para proporcionar acceso sólo a puntos de acceso en lista blanca y para proporcionar funciones de auditoría e informes.
** Mirroring de FabricPool para organizar los datos inactivos en niveles en dos almacenes de datos de forma simultánea
** Reflejos FabricPool en configuraciones MetroCluster
** El volcado y la restauración de NDMP están habilitados de manera predeterminada en los agregados conectados a FabricPool.
+
[NOTE]
====
Si la aplicación de backup utiliza un protocolo distinto a NDMP, como NFS o SMB, el backup de todos los datos del nivel de rendimiento se activa y puede afectar a la organización en niveles de dichos datos en el nivel de cloud. Las lecturas que no sean de NDMP pueden provocar la migración de datos desde el nivel de cloud hasta el nivel de rendimiento.

====
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/NDMP_Backup_and_Restore_supported_for_FabricPool%3F["Compatibilidad con backup y restauración NDMP para FabricPool"]







=== ONTAP 9,8

* Debe ejecutar ONTAP 9.8 o una versión posterior para obtener la siguiente funcionalidad de FabricPool:
+
** Recuperación del cloud
** FabricPool con SnapLock Enterprise. FabricPool con SnapLock Enterprise requiere una solicitud de variación de productos (FPVR) destacada. Para crear un FPVR, póngase en contacto con su equipo de ventas.
** Período mínimo de enfriamiento máximo de 183 días
** Etiquetado de objetos mediante etiquetas personalizadas creadas por el usuario
** Agregados de HDD FabricPool
+
Los FabricPool de HDD solo son compatibles con discos SAS, FSAS, BSAS y MSATA en sistemas con 6 o más núcleos de CPU.

+
Comprobar https://hwu.netapp.com/Home/Index["Hardware Universe"^] para obtener los últimos modelos admitidos.







=== ONTAP 9.10.1

* Debe ejecutar ONTAP 9.10.1 o una versión posterior para obtener la siguiente funcionalidad de FabricPool:
+
** Limitación de PUT
** Eficiencia del almacenamiento sensible a la temperatura (TSSE).






=== ONTAP 9.12.1

* Debe ejecutar ONTAP 9.12.1 o una versión posterior para obtener la siguiente funcionalidad de FabricPool:
+
** Migrar SVM
** Compatibilidad con el trabajo conjunto de FabricPool, FlexGroup y SVM-DR. (Antes de la versión 9.12.1, dos de estas funciones funcionaban juntas, pero no las tres juntas).






=== ONTAP 9.14.1

* Debe ejecutar ONTAP 9.14.1 o una versión posterior para obtener la siguiente funcionalidad de FabricPool:
+
** Escritura en nube
** Lectura agresiva






== Niveles locales (agregados)

FabricPool admite los siguientes tipos de agregados:

* En sistemas AFF, solo se pueden usar agregados de SSD para FabricPool.
* En los sistemas de FAS, puede usar agregados SSD o HDD para FabricPool.
* En Cloud Volumes ONTAP y ONTAP Select, se pueden usar agregados de SSD o HDD para FabricPool. Se recomienda usar agregados de SSD.


[NOTE]
====
No se admiten los agregados de Flash Pool, que contienen tanto SSD como HDD.

====


== Niveles de cloud

FabricPool admite el uso de los siguientes almacenes de objetos como nivel de cloud:

* Servicio de almacenamiento de objetos en cloud de Alibaba (estándar, acceso poco frecuente)
* Amazon S3 (Estándar, Estándar-IA, Una Zona-IA, Capa Inteligente, Recuperación Instantánea de Glacier)
* Servicios de cloud comercial de Amazon (C2S)
* Almacenamiento en cloud de Google (multiregional, regional, Nearline, Coldline, archivado)
* Almacenamiento de objetos en cloud de IBM (estándar, almacén, almacén frío, Flex)
* Almacenamiento de Microsoft Azure Blob (Hot and Cool)
* NetApp ONTAP S3 (ONTAP 9.8 y posterior)
* NetApp StorageGRID (StorageGRID 10,3 y posterior)


[NOTE]
====
Glacier Flexible Retrieval y Glacier Deep Archive no son compatibles.

====
* El almacén de objetos «'bucket» (contenedor) que vaya a utilizar debe estar ya configurado, tener al menos 10 GB de espacio de almacenamiento y no debe cambiarse de nombre.
* Las parejas de ALTA DISPONIBILIDAD que usan FabricPool requieren una LIF de interconexión de clústeres para comunicarse con el almacén de objetos.
* No es posible desvincular un nivel de cloud de un nivel local una vez asociado; sin embargo, puede utilizar link:create-mirror-task.html["Espejo de FabricPool"] para adjuntar un nivel local a un nivel de nube diferente.




== Eficiencias del almacenamiento de ONTAP

Las eficiencias del almacenamiento como la compresión, la deduplicación y la compactación se preservan al mover los datos al nivel de cloud, lo cual reduce la capacidad de almacenamiento de objetos y los costes de transporte necesarios.


NOTE: A partir de ONTAP 9.15.1, FabricPool admite la tecnología Intel QuickAssist (QAT4), que proporciona ahorros en eficiencia de almacenamiento más agresivos y de mayor rendimiento.

La deduplicación inline del agregado es compatible con el nivel local, pero las eficiencias del almacenamiento asociadas no se transfieren a los objetos almacenados en el nivel de cloud.

Al utilizar la política de organización en niveles de todos los volúmenes, es posible reducir las eficiencias del almacenamiento asociadas a los procesos de deduplicación en segundo plano a medida que es probable que los datos se organicen antes de aplicar las eficiencias adicionales del almacenamiento.



== Licencia de organización en niveles de BlueXP

FabricPool requiere una licencia basada en la capacidad cuando se adjuntan proveedores de almacenamiento de objetos de terceros (como Amazon S3) como niveles cloud para sistemas AFF y FAS. No es necesario contar con una licencia de organización en niveles de BlueXP cuando se usa StorageGRID o ONTAP S3 como nivel de nube, o cuando se organizan en niveles con Cloud Volumes ONTAP, Amazon FSx para NetApp ONTAP o Azure NetApp Files.

Las licencias de BlueXP (incluidas las extensiones o complementos a licencias de FabricPool preexistentes) se activan en la link:https://docs.netapp.com/us-en/bluexp-tiering/concept-cloud-tiering.html["Cartera digital de BlueXP"^].



== Controles de consistencia StorageGRID

Los controles de coherencia de StorageGRID afectan a la forma en que son los metadatos que utiliza StorageGRID para realizar el seguimiento de los objetos
distribuido entre nodos y la disponibilidad de objetos para solicitudes de cliente. NetApp recomienda el uso
El control de consistencia predeterminado, de lectura tras nueva escritura para los buckets utilizados como destinos de FabricPool.


NOTE: No utilice el control de consistencia disponible para los depósitos utilizados como destinos FabricPool.



== Consideraciones adicionales sobre la organización en niveles de los datos a los que se accede mediante los protocolos SAN

Cuando se organizan en niveles los datos a los que se accede mediante protocolos SAN, NetApp recomienda usar clouds privados, como ONTAP S3 o StorageGRID, debido a consideraciones de conectividad.


IMPORTANT: Debe tener en cuenta que, al usar FabricPool en un entorno SAN con un host Windows, si el almacenamiento de objetos deja de estar disponible durante un periodo prolongado a la hora de organizar en niveles los datos en el cloud, es posible que no se pueda acceder o desaparezcan los archivos del LUN de NetApp en el host de Windows. Consulte el artículo de la base de conocimientos link:https://kb.netapp.com/onprem/ontap/os/During_FabricPool_S3_object_store_unavailable_Windows_SAN_host_reported_filesystem_corruption["Durante el almacén de objetos de FabricPool S3 no disponible, un host SAN de Windows informó de daños en el sistema de archivos"^].



== Calidad de servicio

* Si utiliza pisos de rendimiento (calidad de servicio mínima), la política de organización en niveles de los volúmenes se debe establecer en `none` Antes de que el agregado pueda adjuntarse a FabricPool.
+
Otras políticas de organización en niveles impiden que el agregado se anexe a FabricPool. Una política de calidad de servicio no impondrá pisos de rendimiento cuando FabricPool está habilitado.





== Funcionalidad o funciones no compatibles con FabricPool

* Almacenes de objetos con WORM habilitado y versionado de objetos activado.
* Políticas de gestión de la vida útil de la información (ILM) que se aplican a los bloques de almacenamiento de objetos
+
FabricPool es compatible con las políticas de gestión del ciclo de vida de la información de StorageGRID solo para la replicación y el código de borrado de datos y proteger los datos del nivel de cloud ante fallos. Sin embargo, FabricPool no admite reglas avanzadas de ILM, como filtrado basado en metadatos o etiquetas de usuario. ILM suele incluir diversas políticas de movimiento y eliminación. Estas políticas pueden provocar interrupciones en los datos del nivel de cloud de FabricPool. El uso de FabricPool con políticas de ILM que están configuradas en almacenes de objetos puede ocasionar la pérdida de datos.

* Transición de datos de 7-Mode mediante comandos de la CLI de ONTAP o la herramienta de transición de 7-Mode
* Virtualización FlexArray
* RAID SyncMirror, excepto en una configuración MetroCluster
* Volúmenes de SnapLock al utilizar ONTAP 9.7 y versiones anteriores
* Backup a cinta mediante SMTape para agregados habilitados para FabricPool
* La función de equilibrio automático
* Volúmenes que usan una garantía de espacio distinta de `none`
+
Con la excepción de los volúmenes raíz de SVM y los volúmenes de configuración de auditoría CIFS, FabricPool no admite la asociación de un nivel de cloud a un agregado que contenga volúmenes que utilicen una garantía de espacio distinta de `none`. Por ejemplo, un volumen con una garantía de espacio de `volume` (`-space-guarantee` `volume`) no es compatible.

* Clústeres con link:../data-protection/snapmirror-licensing-concept.html#data-protection-optimized-license["Licencia DP_Optimized"]
* Agregados de Flash Pool

