---
permalink: fabricpool/setup-alibaba-object-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting, up, alibaba cloud object, storage, cloud tier 
summary: Si utiliza ONTAP 9.6 o una versión posterior, puede configurar Alibaba Cloud Object Storage como nivel cloud para FabricPool. 
---
= Configure el almacenamiento de objetos en cloud de Alibaba como el nivel de cloud de ONTAP FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si utiliza ONTAP 9.6 o una versión posterior, puede configurar Alibaba Cloud Object Storage como nivel cloud para FabricPool.

.Consideraciones sobre el uso del almacenamiento de objetos en cloud de Alibaba con FabricPool
* Se requiere un link:https://bluexp.netapp.com/cloud-tiering["Licencia de organización en niveles de BlueXP"]cuando se organiza en niveles en el almacenamiento de objetos en cloud de Alibaba. Para obtener más información, consulte link:install-license-aws-azure-ibm-task.html["Instale una licencia de FabricPool en un clúster de ONTAP"].
* En los sistemas AFF y FAS y ONTAP Select, FabricPool es compatible con las siguientes clases de servicio de almacenamiento de objetos Alibaba:
+
** Estándar de servicio de almacenamiento de objetos de Alibaba
** Acceso poco frecuente al servicio de almacenamiento de objetos de Alibaba
+
https://www.alibabacloud.com/help/doc-detail/51374.htm["Alibaba Cloud: Introducción a clases de almacenamiento"^]





Póngase en contacto con el representante de ventas de NetApp para obtener información sobre las clases de almacenamiento que no figuran en esta lista.

.Pasos
. Especifique la información de configuración de Alibaba Cloud Object Storage mediante `storage aggregate object-store config create` el comando con `-provider-type` `AliCloud` el parámetro.
+
** El `storage aggregate object-store config create` comando falla si ONTAP no puede acceder al almacenamiento de objetos de la nube de Alibaba con la información proporcionada.
** Utilice el `-access-key` parámetro para especificar la clave de acceso para autorizar solicitudes al almacén de objetos Alibaba Cloud Object Storage.
** Si se cambia la contraseña de almacenamiento de objetos Alibaba Cloud, debe actualizar la contraseña correspondiente almacenada en ONTAP inmediatamente.
+
Con ello, ONTAP puede acceder a los datos en el almacenamiento de objetos en cloud de Alibaba sin interrupciones.



+
[listing]
----
storage aggregate object-store config create my_ali_oss_store_1
-provider-type AliCloud -server oss-us-east-1.aliyuncs.com
-container-name my-ali-oss-bucket -access-key DXJRXHPXHYXA9X31X3JX
----
. Muestre y verifique la información de configuración de Alibaba Cloud Object Storage mediante el `storage aggregate object-store config show` comando.
+
El `storage aggregate object-store config modify` comando le permite modificar la información de configuración del almacenamiento de objetos de nube de Alibaba para FabricPool.



.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-create.html["almacenamiento agregado objeto-almacén configuración crear"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-object-store-config-modify.html["almacenamiento agregado objeto-almacén configuración modificar"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-show.html["Mostrar configuración del almacén de objetos agregados de almacenamiento"^]

