---
permalink: fabricpool/tiering-policies-concept.html 
sidebar: sidebar 
keywords: understanding, fabricpool, tiering, policies, types, modify, volume, clone, cloud migration 
summary: Las políticas de organización en niveles de FabricPool le permiten mover los datos de forma eficiente entre niveles a medida que estos se activan o inactivan. Comprender las políticas de organización en niveles le ayuda a seleccionar la política adecuada que se adapte a sus necesidades de gestión del almacenamiento. 
---
= FabricPool políticas de organización por niveles de volúmenes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool las políticas de clasificación por niveles de los volúmenes determinan qué datos de un volumen pueden clasificarse en distintos niveles y el parámetro de días mínimos de enfriamiento para la clasificación por niveles determina cuándo se considera que los datos están inactivos y son aptos para ser clasificados en distintos niveles.

[NOTE]
====
Las listas de control de acceso (ACL), las estructuras de directorios y los metadatos nunca se trasladan a otro nivel, siempre permanecen en el nivel local.

====
Un escaneo diario de clasificación por niveles en segundo plano busca bloques inactivos. Cuando se han recopilado suficientes bloques de 4KB del mismo volumen, se concatenan en un objeto de 4MB y se trasladan al nivel de la nube según la política de clasificación por niveles del volumen.

Comprender cómo funcionan las políticas de clasificación por niveles te ayudará a seleccionar la política más adecuada para tus necesidades de gestión del almacenamiento.



[[volume-tiering-policy-options]]
== Opciones de la política de organización por niveles de volumen

De forma predeterminada, los volúmenes utilizan la política de clasificación de volúmenes None. La excepción a esto son los volúmenes FlexVol recién creados en agregados FabricPool, que utilizan la política de clasificación de volúmenes Snapshot-Only.

Puede usar el `volume object-store tiering show` comando para ver el estado de organización en niveles de un volumen de FabricPool. Obtenga más información sobre `volume object-store tiering show` en el link:https://docs.netapp.com/us-en/ontap-cli//volume-object-store-tiering-show.html["Referencia de comandos del ONTAP"^].

La política de organización en niveles de FabricPool se especifica a nivel de volumen. Hay cuatro opciones disponibles:



[[snapshot-only]]
=== Solo instantáneas

La  `snapshot-only` política de almacenamiento por niveles clasifica en niveles los datos de instantáneas que ya no están asociados al sistema de archivos activo. Por defecto, deben transcurrir dos días de inactividad antes de que una instantánea pueda ser clasificada en un nivel inferior. La mayoría de las políticas de protección son horarias o diarias, y leen los datos localmente antes de clasificarlos en un nivel inferior.

Puedes modificar la configuración predeterminada del periodo mínimo de enfriamiento para la clasificación por niveles con el parámetro  `-tiering-minimum-cooling-days` en el nivel de privilegio avanzado de los comandos  `volume create` y  `volume modify`. Los valores válidos son de 2 a 183 días usando ONTAP 9.8 y versiones posteriores. Si usas una versión de ONTAP anterior a la 9.8, los valores válidos son de 2 a 63 días.

Al leerlos, los bloques fríos asociados a las copias snapshot permanecen fríos y no se escriben de nuevo en el nivel local.



[[auto]]
=== Automático

La política de almacenamiento por niveles  `auto` clasifica todos los datos inactivos del volumen, tanto las instantáneas como el sistema de archivos activo, en el nivel de la nube. El periodo mínimo de inactividad predeterminado para el almacenamiento por niveles es de 31 días y se aplica a todo el volumen, tanto al sistema de archivos activo como a las instantáneas.

Puede modificar la configuración predeterminada del período mínimo de enfriamiento de la organización en niveles con `-tiering-minimum-cooling-days` el parámetro en el nivel de privilegio avanzado de los `volume create` `volume modify` comandos y. Los valores válidos abarcan de 2 a 183 días.

Cuando se leen de forma aleatoria, los bloques fríos de un volumen con una política de jerarquización configurada en Auto pasan a ser calientes y se escriben de nuevo en el nivel local.

Cuando se leen de forma secuencial, los bloques cold de un volumen con una política de jerarquización configurada en Auto permanecen cold y se mantienen en el nivel de la nube. No se escriben de nuevo en el nivel local.



[[all]]
=== Todo

La política de tiering  `all` marca inmediatamente todos los datos del volumen como fríos y comienza a trasladarlos al nivel de cloud lo antes posible. No es necesario esperar 48 horas para que los nuevos bloques en un volumen que use la política de tiering  `all` se vuelvan fríos.

El período mínimo de enfriamiento de la organización en niveles no se aplica porque los datos se mueven al nivel de cloud en cuanto se ejecuta el análisis de la organización en niveles y no se puede modificar la configuración.

Cuando se leen bloques «cold» en un volumen cuya política de almacenamiento por niveles esté configurada en «All», estos siguen siendo «cold» y permanecen en el nivel de la nube. No se vuelven a escribir en el nivel local.

[NOTE]
====
 `all`No se debe utilizar la política de organización en niveles de volúmenes de lectura/escritura que tengan tráfico de clientes normal.

El almacenamiento de objetos no es transaccional como el almacenamiento de archivos o de bloques. Hacer cambios en archivos almacenados como objetos en volúmenes que usan la política All tiering puede resultar en la creación de nuevos objetos, fragmentación de objetos existentes, disminución del rendimiento de lectura y aumento de ineficiencias en el almacenamiento.

====


[[none]]
=== Ninguno

La política de jerarquización  `none` mantiene los datos de un volumen en el nivel de rendimiento y no los clasifica en niveles.

Establecer la política de organización en niveles `none` para evitar una nueva organización en niveles. Los datos del volumen que anteriormente se han movido al nivel de cloud permanecen en el nivel de cloud hasta que se activan y se trasladan de forma automática al nivel local.

El período de refrigeración mínimo de organización en niveles no se aplica porque los datos nunca se mueven al nivel de cloud y no se puede modificar el ajuste.

Cuando se `none` leen bloques inactivos de un volumen con una política de organización en niveles establecida en, se activan y se escriben en el nivel local.

 `volume show`El resultado del comando muestra la política de organización en niveles de un volumen. Un volumen que no se ha usado con FabricPool, muestra `none` la política de organización en niveles en el resultado.


NOTE: Cuando están en una relación de recuperación ante desastres de la SVM, los volúmenes de origen y de destino no necesitan usar agregados de FabricPool, pero deben usar la misma política de organización en niveles.



[[what-happens-when-you-modify-a-volume-tiering-policy]]
== ¿Qué ocurre cuando modificas una política de organización por niveles de un volumen?

Puede modificar la política de organización en niveles de un volumen mediante una `volume modify` operación. Debe comprender cómo el cambio de la política de organización en niveles puede afectar el tiempo que tardan los datos en dejar de estar activos y moverse al nivel de cloud.

* Al cambiar la política de organización en niveles `snapshot-only` `none` `auto` de o a, ONTAP envía bloques de datos de usuario en el sistema de archivos activo que ya están inactivos en el nivel de cloud, incluso si esos bloques de datos de usuario no eran aptos anteriormente para el nivel de cloud.
* Al cambiar la política de organización en niveles a `all` desde otra política, ONTAP mueve todos los bloques de usuario del sistema de archivos activo y de los snapshots al cloud lo antes posible. Antes de ONTAP 9,8, los bloques tenían que esperar hasta que se ejecutara el siguiente análisis de organización en niveles.
+
No se permite volver a mover los bloques al nivel de rendimiento.

* Cambiar la política de organización en niveles `auto` `snapshot-only` de a o `none` no provocará que los bloques activos del sistema de archivos que ya se han movido al nivel de cloud se vuelvan a trasladar al nivel de rendimiento.
+
Las lecturas de volumen son necesarias para que los datos se muevan de nuevo al nivel de rendimiento.

* Cada vez que cambie la política de organización en niveles de un volumen, el período de refrigeración mínimo de organización en niveles se restablece al valor predeterminado para la política.




[[what-happens-to-the-tiering-policy-when-you-move-a-volume]]
== Qué sucede con la política de organización en niveles al mover un volumen

* A menos que se especifique explícitamente una política de organización en niveles diferente, un volumen conserva su política de organización en niveles original cuando este se mueve dentro y fuera de un agregado habilitado para FabricPool.
+
Sin embargo, la política de organización en niveles solo se aplica cuando el volumen se encuentra en un agregado habilitado para FabricPool.

* El valor existente `-tiering-minimum-cooling-days` del parámetro para un volumen se mueve con el volumen a menos que se especifique una política de organización en niveles diferente para el destino.
+
Si especifica una política de organización en niveles diferente, el volumen utiliza el período de refrigeración mínimo de organización en niveles predeterminado para esa política. Este es el caso si el destino es FabricPool o no.

* Puede mover un volumen entre agregados y, al mismo tiempo, modificar la política de organización en niveles.
* Debe prestar atención especial cuando una `volume move` operación incluye `auto` la política de organización en niveles.
+
Suponiendo que tanto el origen como el destino son agregados habilitados para FabricPool, la siguiente tabla resume el resultado de una `volume move` operación que implica cambios de política relacionados con `auto` :

+
|===


| Cuando se mueve un volumen con una política de organización en niveles de... | Y la política de organización en niveles se cambia a... | Después de mover el volumen... 


 a| 
`all`
 a| 
`auto`
 a| 
Todos los datos se mueven al nivel de rendimiento.



 a| 
`snapshot-only`, , `none` o. `auto`
 a| 
`auto`
 a| 
Los bloques de datos se mueven al mismo nivel del destino que anteriormente se encontraban en el origen.



 a| 
`auto` o. `all`
 a| 
`snapshot-only`
 a| 
Todos los datos se mueven al nivel de rendimiento.



 a| 
`auto`
 a| 
`all`
 a| 
Todos los datos de usuario se mueven al nivel de cloud.



 a| 
`snapshot-only`,`auto` o. `all`
 a| 
`none`
 a| 
Todos los datos se conservan en el nivel de rendimiento.

|===




[[what-happens-to-the-tiering-policy-when-you-clone-a-volume]]
== Qué sucede en la política de organización en niveles al clonar un volumen

* A partir de ONTAP 9.8, un volumen clonado siempre hereda la política de organización en niveles y la política de recuperación de cloud del volumen principal.
+
En versiones anteriores a ONTAP 9.8, un clon hereda la política de organización en niveles del elemento principal excepto cuando el elemento principal tiene la `all` política de organización en niveles.

* Si el volumen primario tiene la `never` política de recuperación de cloud, su volumen clonado debe tener `never` la política de recuperación de cloud o la `all` política de organización en niveles, y una política de recuperación de cloud correspondiente `default` .
* No se puede cambiar la política de recuperación de cloud del volumen primario `never` a menos que todos sus volúmenes clonados tengan una política de recuperación de cloud `never` .


Al clonar volúmenes, tenga en cuenta las siguientes prácticas recomendadas:

*  `-tiering-policy`La opción y `tiering-minimum-cooling-days` la opción del clon solo controlan el comportamiento de la organización en niveles de los bloques únicos del clon. Por lo tanto, se recomienda utilizar la configuración de organización en niveles en la FlexVol principal que mueva la misma cantidad de datos o mueva menos datos que ninguno de los clones
* La política de recuperación de cloud del FlexVol principal debería mover la misma cantidad de datos o debería mover más datos que la política de recuperación de cualquiera de los clones




[[how-tiering-policies-work-with-cloud-migration]]
== Funcionamiento de las políticas de organización en niveles con la migración al cloud

La recuperación de datos en el cloud de FabricPool se controla mediante políticas de niveles que determinan la recuperación de datos del nivel de cloud al nivel de rendimiento según el patrón de lectura. Los patrones de lectura pueden ser secuenciales o aleatorios.

En la siguiente tabla, se enumeran las políticas de organización en niveles y las reglas de recuperación de datos en el cloud para cada política.

|===


| Política de organización en niveles | Comportamiento de la recuperación 


 a| 
ninguno
 a| 
Lecturas secuenciales y aleatorias



 a| 
solo snapshot
 a| 
Lecturas secuenciales y aleatorias



 a| 
automático
 a| 
Lecturas aleatorias



 a| 
todo
 a| 
Sin recuperación de datos

|===
A partir de ONTAP 9.8, la `cloud-retrieval-policy` opción de control de migración en la nube anula el comportamiento predeterminado de migración o recuperación a la nube controlado por la política de organización en niveles.

En la siguiente tabla se enumeran las políticas de recuperación de cloud admitidas y su comportamiento de recuperación.

|===


| Política de recuperación de cloud | Comportamiento de la recuperación 


 a| 
predeterminado
 a| 
La política de organización en niveles decide qué datos se deben recuperar, de modo que no hay cambios en la recuperación de datos en la nube con «almacén,`" `cloud-retrieval-policy`». Esta política es el valor predeterminado para cualquier volumen independientemente del tipo de agregado alojado.



 a| 
lectura
 a| 
Todas las lecturas de datos condicionadas por el cliente se realiza desde el nivel de cloud al nivel de rendimiento.



 a| 
nunca
 a| 
No se datos controlados por el cliente que pase del nivel de cloud al nivel de rendimiento



 a| 
promocionar
 a| 
* En lo que respecta a la política de organización en niveles «'none», todos los datos del cloud se envían del nivel de cloud al nivel de rendimiento
* En cuanto a la política de organización en niveles, se obtienen los datos de AFS «solo sinapshot».


|===
Obtenga más información sobre los comandos descritos en este procedimiento en el link:https://docs.netapp.com/us-en/ontap-cli/["Referencia de comandos del ONTAP"^].
