---
permalink: nfs-config/add-storage-capacity-nfs-enabled-svm-concept.html 
sidebar: sidebar 
keywords: add, storage, capacity, nfs-enabled, svm 
summary: Para añadir capacidad de almacenamiento a una SVM habilitada para NFS, debe crear un volumen o un qtree para proporcionar un contenedor de almacenamiento y crear o modificar una política de exportación para ese contenedor. Después, puede verificar el acceso del cliente NFS desde el clúster y probar el acceso desde los sistemas cliente. 
---
= Añadir capacidad de almacenamiento a una información general de SVM habilitada para NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para añadir capacidad de almacenamiento a una SVM habilitada para NFS, debe crear un volumen o un qtree para proporcionar un contenedor de almacenamiento y crear o modificar una política de exportación para ese contenedor. Después, puede verificar el acceso del cliente NFS desde el clúster y probar el acceso desde los sistemas cliente.

.Antes de empezar
* NFS debe estar configurado por completo en la SVM.
* La política de exportación predeterminada del volumen raíz de la SVM debe contener una regla que permita el acceso a todos los clientes.
* Se debe completar cualquier actualización de la configuración de los servicios de nombres.
* Deben completarse todas las adiciones o modificaciones que se realicen en una configuración de Kerberos.

