---
permalink: nfs-config/assess-physical-storage-requirements-task.html 
sidebar: sidebar 
keywords: assess, physical, storage, requirements 
summary: Antes de aprovisionar almacenamiento de NFS para clientes, debe asegurarse de que haya espacio suficiente en un agregado existente para el nuevo volumen. Si no lo hay, puede añadir discos a un agregado existente o crear uno nuevo con el tipo deseado. 
---
= Evaluar los requisitos de almacenamiento físico de ONTAP NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de aprovisionar almacenamiento de NFS para clientes, debe asegurarse de que haya espacio suficiente en un agregado existente para el nuevo volumen. Si no lo hay, puede añadir discos a un agregado existente o crear uno nuevo con el tipo deseado.

.Pasos
. Mostrar el espacio disponible en los agregados existentes:
+
`storage aggregate show`

+
Si hay un agregado con suficiente espacio, registre su nombre en la hoja de cálculo.

+
[listing]
----
cluster::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes  RAID Status
--------- -------- --------- ----- ------- ------ ------ -----------
aggr_0     239.0GB   11.13GB   95% online       1 node1  raid_dp,
                                                         normal
aggr_1     239.0GB   11.13GB   95% online       1 node1  raid_dp,
                                                         normal
aggr_2     239.0GB   11.13GB   95% online       1 node2  raid_dp,
                                                         normal
aggr_3     239.0GB   11.13GB   95% online       1 node2  raid_dp,
                                                         normal
aggr_4     239.0GB   238.9GB   95% online       5 node3  raid_dp,
                                                         normal
aggr_5     239.0GB   239.0GB   95% online       4 node4  raid_dp,
                                                         normal
6 entries were displayed.
----
. Si no hay agregados con espacio suficiente, añada discos a un agregado existente mediante `storage aggregate add-disks` el comando o cree un agregado nuevo mediante el `storage aggregate create` comando.


.Información relacionada
* link:../disks-aggregates/add-disks-local-tier-aggr-task.html["Añadir discos a un nivel local (agregado)"]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-add-disks.html["agregado de almacenamiento, agregar discos"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-create.html["creación de agregados de almacenamiento"^]

