---
permalink: nfs-config/assign-export-policy-qtree-task.html 
sidebar: sidebar 
keywords: assign, export, policy, qtree 
summary: En lugar de exportar un volumen completo, también puede exportar un qtree concreto de un volumen para que los clientes puedan acceder a él directamente. Puede asignar una política de exportación a un qtree para exportarlo. Puede asignar la política de exportación al crear un qtree nuevo o al modificar un qtree existente. 
---
= Asigne una política de exportación a un qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En lugar de exportar un volumen completo, también puede exportar un qtree concreto de un volumen para que los clientes puedan acceder a él directamente. Puede asignar una política de exportación a un qtree para exportarlo. Puede asignar la política de exportación al crear un qtree nuevo o al modificar un qtree existente.

.Lo que necesitará
Debe existir la política de exportación.

.Acerca de esta tarea
De forma predeterminada, los qtrees heredan la política de exportación principal del volumen que contiene si no se especifica de otro modo en el momento de la creación.

Puede asociar una política de exportación a un qtree al crear el qtree o en cualquier momento después de crearlo. Puede asociar una política de exportación al qtree, aunque otra se puede asociar con muchos qtrees.

.Pasos
. Si no se especificó una política de exportación al crear el qtree, asigne una política de exportación al qtree:
+
`volume qtree modify -vserver _vserver_name_ -qtree-path /vol/_volume_name/qtree_name_ -export-policy _export_policy_name_`

. Compruebe que la política se ha asignado al qtree:
+
`volume qtree show -qtree _qtree_name_ -fields export-policy`



.Ejemplo
Los siguientes comandos asignan la política de exportación nfs_policy al qtree qt1 en la SVM vs1 y verifican la asignación:

[listing]
----
cluster::> volume modify -v1server vs1 -qtree-path /vol/vol1/qt1 -policy nfs_policy

cluster::>volume qtree show -volume vol1 -fields export-policy
vserver volume qtree export-policy
------- ------ ----- -------------
vs1     data1  qt01  nfs_policy
----