---
permalink: nfs-config/associate-export-policy-flexvol-task.html 
sidebar: sidebar 
keywords: assign, export, policy, volume 
summary: Cada volumen incluido en la SVM debe estar asociado a una política de exportación que contenga reglas de exportación para que los clientes accedan a los datos del volumen. 
---
= Asignar una política de exportación a un volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada volumen incluido en la SVM debe estar asociado a una política de exportación que contenga reglas de exportación para que los clientes accedan a los datos del volumen.

.Acerca de esta tarea
Es posible asociar una política de exportación a un volumen cuando se crea el volumen o en cualquier momento después de crearlo. Es posible asociar una política de exportación al volumen, aunque otra se puede asociar a muchos volúmenes.

.Pasos
. Si no se especificó una política de exportación cuando se creó el volumen, asigne una política de exportación al volumen:
+
`volume modify -vserver _vserver_name_ -volume _volume_name_ -policy _export_policy_name_`

. Compruebe que la política se haya asignado al volumen:
+
`volume show -volume _volume_name_ -fields policy`



.Ejemplo
Los siguientes comandos asignan la política de exportación nfs_policy al volumen vol1 en la SVM vs1 y verifican la asignación:

[listing]
----
cluster::> volume modify -v1server vs1 -volume vol1 -policy nfs_policy

cluster::>volume show -volume vol -fields policy
vserver volume       policy
------- ------------ ----------------
vs1     vol1         nfs_policy
----