---
permalink: nfs-config/comparison-exports-7-mode-concept.html 
sidebar: sidebar 
keywords: comparison, exports, 7-mode ontap 
summary: Las exportaciones en ONTAP se definen y utilizan de forma diferente a las que se utilizan en entornos de 7-Mode. 
---
= Comparación de exportaciones en 7-Mode y ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las exportaciones en ONTAP se definen y utilizan de forma diferente a las que se utilizan en entornos de 7-Mode.

|===


| Áreas de diferencia | 7-Mode | ONTAP 


 a| 
Cómo se definen las exportaciones
 a| 
Las exportaciones se definen en la `/etc/exports` archivo.
 a| 
Las exportaciones se definen mediante la creación de una política de exportación dentro de una SVM. Una SVM puede incluir más de una política de exportación.



 a| 
Ámbito de exportación
 a| 
* Las exportaciones se aplican a una ruta de archivo o qtree especificados.
* Debe crear una entrada independiente en `/etc/exports` para cada qtree o ruta de archivo.
* Las exportaciones sólo son persistentes si se definen en la `/etc/exports` archivo.

 a| 
* Las políticas de exportación se aplican a un volumen completo, incluidos todos los qtrees y rutas de archivos contenidos en el volumen.
* Las políticas de exportación se pueden aplicar a más de un volumen si se desea.
* Todas las políticas de exportación son persistentes a través de reinicios del sistema.




 a| 
Cercado (especificando un acceso diferente para clientes específicos a los mismos recursos)
 a| 
Para proporcionar a clientes específicos un acceso diferente a un recurso exportado único, debe enumerar cada cliente y su acceso permitido en el `/etc/exports` archivo.
 a| 
Las políticas de exportación están compuestas por varias reglas individuales de exportación. Cada regla de exportación define permisos de acceso específicos para un recurso y enumera los clientes que tienen dichos permisos. Para especificar un acceso diferente para clientes específicos, debe crear una regla de exportación para cada conjunto específico de permisos de acceso, enumerar los clientes que tienen esos permisos y, a continuación, agregar las reglas a la directiva de exportación.



 a| 
Alias de nombre
 a| 
Al definir una exportación, puede elegir que el nombre de la exportación sea diferente del nombre de la ruta de acceso del archivo. Debe utilizar el `-actual` parámetro al definir dicha exportación en la `/etc/exports` archivo.
 a| 
Es posible optar por que el nombre del volumen exportado sea diferente del nombre del volumen real. Para ello, debe montar el volumen con un nombre de ruta de unión personalizado dentro del espacio de nombres de la SVM.


NOTE: De manera predeterminada, los volúmenes se montan con su nombre de volumen. Para personalizar el nombre de ruta de unión de un volumen, debe desmontarlo, cambiarle el nombre y, a continuación, volver a montarlo.

|===