---
permalink: nfs-config/create-svms-data-access-task.html 
sidebar: sidebar 
keywords: create, svm 
summary: Si no tiene al menos una SVM en un clúster para proporcionar acceso a los datos a los clientes NFS, debe crear una. 
---
= Cree una SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si no tiene al menos una SVM en un clúster para proporcionar acceso a los datos a los clientes NFS, debe crear una.

.Antes de empezar
* A partir de ONTAP 9.13.1, puede establecer una capacidad máxima para una máquina virtual de almacenamiento. También puede configurar alertas cuando la SVM se acerca a un nivel de umbral de capacidad. Para obtener más información, consulte xref:../volumes/manage-svm-capacity.html[Gestionar la capacidad de SVM].


.Pasos
. Cree una SVM:
+
`vserver create -vserver _vserver_name_ -rootvolume _root_volume_name_ -aggregate _aggregate_name_ -rootvolume-security-style unix -language C.UTF-8 -ipspace _ipspace_name_`

+
** Utilice el valor UNIX del `-rootvolume-security-style` opción.
** Utilice el C.UTF-8 predeterminado `-language` opción.
** La `ipspace` el ajuste es opcional.


. Compruebe la configuración y el estado de la SVM recién creada:
+
`vserver show -vserver _vserver_name_`

+
La `Allowed Protocols` El campo debe incluir NFS. Puede editar esta lista más tarde.

+
La `Vserver Operational State` el campo debe mostrar la `running` estado. Si muestra la `initializing` estado, significa que hubo un error en algunas operaciones intermedias, como la creación del volumen raíz, y que debe eliminarse la SVM y volver a crearla.



.Ejemplos
El siguiente comando crea una SVM para acceder a los datos en el espacio IP ipspaceA:

[listing]
----
cluster1::> vserver create -vserver vs1.example.com -rootvolume root_vs1 -aggregate aggr1
-rootvolume-security-style unix -language C.UTF-8 -ipspace ipspaceA

[Job 2059] Job succeeded:
Vserver creation completed
----
El siguiente comando muestra que se creó una SVM con un volumen raíz de 1 GB, y se inició automáticamente y está en `running` estado. El volumen raíz tiene una política de exportación predeterminada que no incluye reglas, por lo que el volumen raíz no se exporta tras la creación.

[listing]
----
cluster1::> vserver show -vserver vs1.example.com
                                    Vserver: vs1.example.com
                               Vserver Type: data
                            Vserver Subtype: default
                               Vserver UUID: b8375669-19b0-11e5-b9d1-00a0983d9736
                                Root Volume: root_vs1
                                  Aggregate: aggr1
                                 NIS Domain: -
                 Root Volume Security Style: unix
                                LDAP Client: -
               Default Volume Language Code: C.UTF-8
                            Snapshot Policy: default
                                    Comment:
                               Quota Policy: default
                List of Aggregates Assigned: -
 Limit on Maximum Number of Volumes allowed: unlimited
                        Vserver Admin State: running
                  Vserver Operational State: running
   Vserver Operational State Stopped Reason: -
                          Allowed Protocols: nfs, cifs, fcp, iscsi, ndmp
                       Disallowed Protocols: -
                           QoS Policy Group: -
                                Config Lock: false
                               IPspace Name: ipspaceA
----

NOTE: A partir de ONTAP 9.13.1, puede establecer una plantilla de grupo de políticas de calidad de servicio adaptativa, aplicando un límite máximo y mínimo de rendimiento a los volúmenes en la SVM. Solo puede aplicar esta política después de crear la SVM. Para obtener más información sobre este proceso, consulte xref:../performance-admin/adaptive-policy-template-task.html[Defina una plantilla de grupo de políticas adaptativas].
