---
permalink: nfs-config/create-new-ldap-client-schema-task.html 
sidebar: sidebar 
keywords: create, new, ldap, client, schema 
summary: Si el esquema LDAP del entorno difiere de los valores predeterminados de ONTAP, debe crear un nuevo esquema de cliente LDAP para ONTAP antes de crear la configuración de cliente LDAP. 
---
= Cree un nuevo esquema de cliente LDAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si el esquema LDAP del entorno difiere de los valores predeterminados de ONTAP, debe crear un nuevo esquema de cliente LDAP para ONTAP antes de crear la configuración de cliente LDAP.

.Acerca de esta tarea
La mayoría de los servidores LDAP pueden utilizar los esquemas predeterminados proporcionados por ONTAP:

* MS-AD-BIS (el esquema preferido para la mayoría de los servidores AD de Windows 2012 y posteriores)
* AD-IDMU (servidores AD de Windows 2008, Windows 2012 y posteriores)
* AD-SFU (servidores Windows 2003 y anteriores de AD)
* RFC-2307 (SERVIDORES UNIX LDAP)


Si necesita utilizar un esquema LDAP no predeterminado, debe crearlo antes de crear la configuración del cliente LDAP. Consulte con el administrador LDAP antes de crear un nuevo esquema.

Los esquemas LDAP predeterminados proporcionados por ONTAP no se pueden modificar. Para crear un nuevo esquema, cree una copia y, a continuación, modifique la copia en consecuencia.

.Pasos
. Mostrar las plantillas de esquema de cliente LDAP existentes para identificar la que desea copiar:
+
`vserver services name-service ldap client schema show`

. Configure el nivel de privilegio en Advanced:
+
`set -privilege advanced`

. Haga una copia de un esquema de cliente LDAP existente:
+
`vserver services name-service ldap client schema copy -vserver _vserver_name_ -schema _existing_schema_name_ -new-schema-name _new_schema_name_`

. Modifique el nuevo esquema y personalícelo para su entorno:
+
`vserver services name-service ldap client schema modify`

. Vuelva al nivel de privilegio de administrador:
+
`set -privilege admin`


