---
permalink: nfs-config/export-policies-concept.html 
sidebar: sidebar 
keywords: secure, nfs, access, using, export, policies 
summary: Puede utilizar las políticas de exportación para restringir el acceso de NFS a volúmenes o qtrees a clientes que coincidan con parámetros específicos. Al aprovisionar almacenamiento nuevo, puede usar una política y reglas existentes, agregar reglas a una política existente o crear una nueva política y reglas. También puede comprobar la configuración de las políticas de exportación 
---
= Acceso NFS seguro mediante políticas de exportación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar las políticas de exportación para restringir el acceso de NFS a volúmenes o qtrees a clientes que coincidan con parámetros específicos. Al aprovisionar almacenamiento nuevo, puede usar una política y reglas existentes, agregar reglas a una política existente o crear una nueva política y reglas. También puede comprobar la configuración de las políticas de exportación

[NOTE]
====
A partir de ONTAP 9.3, puede habilitar la comprobación de la configuración de la política de exportación como un trabajo en segundo plano que registra cualquier infracción de reglas en una lista de reglas de error. La `vserver export-policy config-checker` Los comandos invocan el comprobador y muestran los resultados, que se pueden utilizar para verificar la configuración y eliminar reglas erróneas de la directiva. Los comandos sólo validan la configuración de exportación para los nombres de host, grupos de red y usuarios anónimos.

====