---
permalink: nfs-config/exports-differ-concept.html 
sidebar: sidebar 
keywords: ontap, exports, differ, 7-mode, exports 
summary: Si no está familiarizado con el modo en que ONTAP implementa exportaciones NFS, puede comparar las herramientas de configuración de exportación de 7-Mode y ONTAP, así como archivos de ejemplo de 7-Mode /etc/exports con reglas y políticas en clúster. 
---
= En qué se diferencian las exportaciones de ONTAP de las exportaciones de 7-Mode
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si no está familiarizado con cómo ONTAP implementa exportaciones NFS, puede comparar las herramientas de configuración de exportación de 7-Mode y ONTAP, así como las herramientas de ejemplo de 7-Mode `/etc/exports` archivos con reglas y políticas en clúster.

En ONTAP no hay `/etc/exports` archivo y no `exportfs` comando. En su lugar, debe definir una política de exportación. Las políticas de exportación le permiten controlar el acceso de los clientes de la misma forma que en 7-Mode, pero le proporcionan funcionalidades adicionales como la capacidad de reutilizar la misma política de exportación para varios volúmenes.

.Información relacionada
link:../nfs-admin/index.html["Gestión de NFS"]

http://www.netapp.com/us/media/tr-4067.pdf["Informe técnico de NetApp 4067: Guía de prácticas recomendadas e implementación de NFS"^]
