---
permalink: nfs-config/install-self-signed-root-ca-certificate-svm-task.html 
sidebar: sidebar 
keywords: install, self-signed, root, ca certificate, svm 
summary: Si se requiere la autenticación LDAP con TLS al enlazar con servidores LDAP, primero debe instalar el certificado de CA raíz autofirmado en la SVM. 
---
= Instale el certificado de CA raíz autofirmado en la SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si se requiere la autenticación LDAP con TLS al enlazar con servidores LDAP, primero debe instalar el certificado de CA raíz autofirmado en la SVM.

.Acerca de esta tarea
Cuando LDAP over TLS está habilitado, el cliente LDAP de ONTAP en la SVM no admite certificados revocados en ONTAP 9.0 y 9.1.

A partir de ONTAP 9.2, todas las aplicaciones de ONTAP que utilizan comunicaciones TLS pueden comprobar el estado de certificado digital mediante el protocolo de estado de certificado en línea (OCSP). Si OCSP está habilitado para LDAP over TLS, se rechazan los certificados revocados y la conexión falla.

.Pasos
. Instale el certificado de CA raíz autofirmado:
+
.. Comience la instalación del certificado:
 +
`security certificate install -vserver _vserver_name_ -type server-ca`
+
El resultado de la consola muestra el siguiente mensaje:

+
`Please enter Certificate: Press <Enter> when done`

.. Abra el certificado `.pem` archivo con un editor de texto, copie el certificado, incluidas las líneas que empiezan por `-----BEGIN CERTIFICATE-----` y terminar con `-----END CERTIFICATE-----`y, a continuación, pegue el certificado después del símbolo del sistema.
.. Compruebe que el certificado se muestra correctamente.
.. Para completar la instalación, pulse Intro.


. Compruebe que el certificado esté instalado:
+
`security certificate show -vserver _vserver_name_`


