---
permalink: nfs-config/open-export-policy-svm-root-volume-task.html 
sidebar: sidebar 
keywords: open, export, policy, svm, root, volume 
summary: La política de exportación predeterminada del volumen raíz de la SVM debe incluir una regla para permitir que todos los clientes tengan acceso abierto a través de NFS. Sin esta regla, se deniega el acceso a la SVM y a sus volúmenes a todos los clientes NFS. 
---
= Abra la política de exportación del volumen raíz de la SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La política de exportación predeterminada del volumen raíz de la SVM debe incluir una regla para permitir que todos los clientes tengan acceso abierto a través de NFS. Sin esta regla, se deniega el acceso a la SVM y a sus volúmenes a todos los clientes NFS.

.Acerca de esta tarea
Cuando se crea una SVM nueva, se crea automáticamente una política de exportación predeterminada (denominada predeterminada) para el volumen raíz de la SVM. Debe crear una o varias reglas para la política de exportación predeterminada para que los clientes puedan acceder a los datos de la SVM.

Debe verificar que el acceso está abierto a todos los clientes NFS de la política de exportación predeterminada y, más adelante, restringir el acceso a volúmenes individuales mediante la creación de políticas de exportación personalizadas para volúmenes o qtrees individuales.

.Pasos
. Si va a utilizar una SVM existente, compruebe la política de exportación de volumen raíz predeterminada:
+
`vserver export-policy rule show`

+
El resultado del comando debe ser similar a lo siguiente:

+
[listing]
----

cluster::> vserver export-policy rule show -vserver vs1.example.com -policyname default -instance

                                    Vserver: vs1.example.com
                                Policy Name: default
                                 Rule Index: 1
                            Access Protocol:  nfs
Client Match Hostname, IP Address, Netgroup, or Domain: 0.0.0.0/0
                             RO Access Rule: any
                             RW Access Rule: any
User ID To Which Anonymous Users Are Mapped: 65534
                   Superuser Security Types: any
               Honor SetUID Bits in SETATTR: true
                  Allow Creation of Devices: true
----
+
Si existe una regla de este tipo que permite el acceso abierto, esta tarea se completa. De lo contrario, continúe con el siguiente paso.

. Cree una regla de exportación para el volumen raíz de la SVM:
+
`vserver export-policy rule create -vserver _vserver_name_ -policyname default -ruleindex 1 -protocol nfs -clientmatch 0.0.0.0/0 -rorule any ‑rwrule any -superuser any`

+
Si la SVM solo contendrá volúmenes protegidos por Kerberos, puede establecer las opciones de la regla de exportación `-rorule` , `-rwrule` y `-superuser` para el volumen raíz en `krb5` o `krb5i`. Por ejemplo:

+
`-rorule krb5i -rwrule krb5i -superuser krb5i`

. Verifique la creación de reglas con el `vserver export-policy rule show` comando.


.Resultado
Ahora, cualquier cliente de NFS puede acceder a cualquier volumen o qtree creado en la SVM.
