---
permalink: nfs-config/set-export-rules-index-number-task.html 
sidebar: sidebar 
keywords: manage, processing, order, export rules 
summary: Puede utilizar el comando setindex de reglas de política de exportación de Vserver para establecer manualmente el número de índice de una regla de exportación existente. Esto le permite especificar la prioridad mediante la cual ONTAP aplica reglas de exportación a las solicitudes de clientes. 
---
= Gestionar la orden de procesamiento de las reglas de exportación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar `vserver export-policy rule setindex` el comando para definir manualmente el número de índice de una regla de exportación existente. Esto le permite especificar la prioridad mediante la cual ONTAP aplica reglas de exportación a las solicitudes de clientes.

.Acerca de esta tarea
Si el nuevo número de índice ya está en uso, el comando inserta la regla en el punto especificado y vuelve a ordenar la lista en consecuencia.

.Paso
. Modifique el número de índice de una regla de exportación especificada:
+
`vserver export-policy rule setindex -vserver _virtual_server_name_ -policyname _policy_name_ -ruleindex _integer_ -newruleindex _integer_`



.Ejemplo
El siguiente comando cambia el número de índice de una regla de exportación en el número de índice 3 al número de índice 2 de una política de exportación denominada r1 en la SVM denominada vs1:

[listing]
----
vs1::> vserver export-policy rule setindex -vserver vs1
-policyname rs1 -ruleindex 3 -newruleindex 2
----