---
permalink: nfs-config/tls-nfs-strong-security-concept.html 
sidebar: sidebar 
keywords: use, tls, nfs, strong, security 
summary: TLS permite las comunicaciones de red cifradas con una seguridad equivalente y menos complejidad que Kerberos. 
---
= Información general sobre el uso de TLS con NFS para una seguridad sólida
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead lead"]
TLS permite las comunicaciones de red cifradas con una seguridad equivalente y menor complejidad que Kerberos e IPsec. Como administrador, puede habilitar, configurar y deshabilitar TLS para brindar una fuerte seguridad con conexiones NFSv3 y NFSv4.x mediante System Manager, la interfaz de línea de comandos de ONTAP o la API DE REST DE ONTAP.


NOTE: NFS con TLS está disponible en ONTAP 9.15.1 como versión preliminar pública. Como oferta de vista previa, NFS sobre TLS no se admite en las cargas de trabajo de producción en ONTAP 9.15.1.

ONTAP utiliza TLS 1,3 para conexiones NFS over TLS.



== Requisitos

NFS a través de TLS requiere certificados X,509. Puede instalar un certificado de servidor firmado por CA en el clúster de ONTAP o instalar un certificado que el servicio NFS utilice directamente. Sus certificados deben cumplir las siguientes directrices:

* Cada certificado debe configurarse con el Nombre de dominio completo (FQDN) del servidor NFS (LIF de datos en el que se habilitará/configurará TLS) como nombre común (CN).
* Cada certificado debe configurarse con la dirección IP o FQDN del servidor NFS (o ambos) como nombre alternativo del asunto (SAN). Si se configuran tanto la dirección IP como el FQDN, los clientes NFS pueden conectarse mediante la dirección IP o el FQDN.
* Puede instalar varios certificados de servicio NFS para la misma LIF, pero solo se puede utilizar uno de ellos simultáneamente como parte de la configuración TLS de NFS.

