---
permalink: nfs-config/verify-status-netgroup-definitions-task.html 
sidebar: sidebar 
keywords: verify, status, netgroup, definitions 
summary: Después de cargar los grupos de red en la SVM, puede utilizar el comando vserver Services NAME-service netgroup status para verificar el estado de las definiciones de netgroup. Esto permite determinar si las definiciones de grupos de red son consistentes en todos los nodos que forman parte de la SVM. 
---
= Verificar las definiciones de grupos de redes SVM de ONTAP NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de cargar netgroups en la SVM, puede utilizar `vserver services name-service netgroup status` el comando para comprobar el estado de las definiciones de netgroup. Esto permite determinar si las definiciones de grupos de red son consistentes en todos los nodos que forman parte de la SVM.

.Pasos
. Configure el nivel de privilegio en Advanced:
+
`set -privilege advanced`

. Compruebe el estado de las definiciones de netgroup:
+
`vserver services name-service netgroup status`

+
Puede visualizar información adicional en una vista más detallada.

. Vuelva al nivel de privilegio de administrador:
+
`set -privilege admin`



.Ejemplo
Una vez establecido el nivel de privilegio, el siguiente comando muestra el estado de netgroup para todas las SVM:

[listing]
----
vs1::> set -privilege advanced

Warning: These advanced commands are potentially dangerous; use them only when
         directed to do so by technical support.
Do you wish to continue? (y or n): y

vs1::*> vserver services name-service netgroup status
Virtual
Server    Node            Load Time           Hash Value
--------- --------------- ------------------- --------------------------------
vs1
          node1           9/20/2006 16:04:53  e6cb38ec1396a280c0d2b77e3a84eda2
          node2           9/20/2006 16:06:26  e6cb38ec1396a280c0d2b77e3a84eda2
          node3           9/20/2006 16:08:08  e6cb38ec1396a280c0d2b77e3a84eda2
          node4           9/20/2006 16:11:33  e6cb38ec1396a280c0d2b77e3a84eda2
----