---
permalink: nfs-config/work-netgroups-task.html 
sidebar: sidebar 
keywords: work, netgroups 
summary: 'Puede utilizar netgroups para la autenticación de usuarios y para que coincida con los clientes en las reglas de directiva de exportación. Puede proporcionar acceso a los grupos de red desde servidores de nombres externos (LDAP o NIS), o puede cargar grupos de red desde un identificador de recursos uniforme (URI) a las SVM mediante el comando Vserver Services name-service netgroup load.' 
---
= Información general sobre cómo trabajar con grupos de red
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar netgroups para la autenticación de usuarios y para que coincida con los clientes en las reglas de directiva de exportación. Es posible proporcionar acceso a los grupos de red de servidores de nombres externos (LDAP o NIS), o puede cargar grupos de redes desde un identificador de recurso uniforme (URI) a las SVM mediante el `vserver services name-service netgroup load` comando.

.Antes de empezar
Antes de trabajar con netgroups, debe asegurarse de que se cumplen las siguientes condiciones:

* Todos los hosts de los grupos de red, independientemente del origen (NIS, LDAP o archivos locales), deben tener registros DNS tanto de reenvío (A) como de retroceso (PTR) para proporcionar búsquedas DNS de reenvío e inversa coherentes.
+
Además, si una dirección IP de un cliente tiene varios registros PTR, todos esos nombres de host deben ser miembros del netgroup y tener registros Correspondientes.

* Los nombres de todos los hosts de netgroups, independientemente de su origen (NIS, LDAP o archivos locales), deben estar escritos correctamente y utilizar el caso correcto. Las incoherencias de los casos en los nombres de host utilizados en los grupos de redes pueden dar lugar a un comportamiento inesperado, como las comprobaciones de exportación fallidas.
* Todas las direcciones IPv6 especificadas en los grupos de red deben acortarse y comprimirse como se especifica en RFC 5952.
+
Por ejemplo, 2011:hu9:0:0:0:0:3:1 debe acortarse a 2011:hu9::3:1.



.Acerca de esta tarea
Al trabajar con netgroups, puede realizar las siguientes operaciones:

* Puede utilizar el `vserver export-policy netgroup check-membership` Comando para ayudar a determinar si una IP de cliente es miembro de un determinado netgroup.
* Puede utilizar el `vserver services name-service getxxbyyy netgrp` comando para comprobar si un cliente forma parte de un netgroup.
+
El servicio subyacente para realizar la búsqueda se selecciona según el orden de cambio de servicio de nombres configurado.


