---
permalink: system-admin/accessg-node-log-core-dump-mib-files-task.html 
sidebar: sidebar 
keywords: service, processor, infrastructure, spi, web, service, node, log, core, dump, mib, file, browser 
summary: 'El servicio web Service Processor Infrastructure (spi) está habilitado de forma predeterminada para habilitar un explorador web para acceder al registro, al volcado principal y a los archivos MIB de un nodo del clúster. Todavía es posible acceder a los archivos incluso cuando el nodo está inactivo, siempre que su partner haga el control del nodo.' 
---
= Acceda a los archivos log, core dump y MIB de un nodo mediante un navegador web
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La infraestructura del procesador de servicio (`spi`) El servicio web está habilitado de forma predeterminada para habilitar un explorador web para acceder a los archivos log, core dump y MIB de un nodo en el clúster. Todavía es posible acceder a los archivos incluso cuando el nodo está inactivo, siempre que su partner haga el control del nodo.

.Lo que necesitará
* El LIF de gestión del clúster debe estar activo.
+
Puede utilizar la LIF de gestión del clúster o de un nodo para acceder al `spi` servicio web. Sin embargo, se recomienda utilizar el LIF de gestión del clúster.

+
La `network interface show` El comando muestra el estado de todas las LIF del clúster.

* Se debe usar una cuenta de usuario local para acceder al `spi` servicio web, las cuentas de usuario de dominio no son compatibles.
* Si su cuenta de usuario no tiene la función «'admin'» (que tiene acceso a la `spi` servicio web de forma predeterminada), la función de control de acceso debe tener acceso a `spi` servicio web.
+
La `vserver services web access show` el comando muestra qué funciones tienen acceso a qué servicios web.

* Si no está utilizando la cuenta de usuario «'admin'» (que incluye la `http` método de acceso de forma predeterminada), la cuenta de usuario debe configurarse con el `http` método de acceso.
+
La `security login show` el comando muestra los métodos de acceso e inicio de sesión de las cuentas de usuario, así como sus roles de control de acceso.

* Si desea utilizar HTTPS para obtener acceso web seguro, debe habilitarse SSL y debe instalarse un certificado digital.
+
La `system services web show` el comando muestra la configuración del motor de protocolo web en el nivel del clúster.



.Acerca de esta tarea
La `spi` el servicio web está activado de forma predeterminada y el servicio se puede desactivar manualmente (`vserver services web modify -vserver * -name spi -enabled false`).

La función «admin» tiene acceso a la `spi` servicio web de forma predeterminada y el acceso se puede deshabilitar manualmente (`services web access delete -vserver _cluster_name_ -name spi -role admin`).

.Pasos
. Dirija el navegador web al `spi` Dirección URL del servicio web en uno de los siguientes formatos:
+
** `http://_cluster-mgmt-LIF_/spi/`
** `https://_cluster-mgmt-LIF_/spi/`
+
`cluster-mgmt-LIF` Es la dirección IP de la LIF de gestión del clúster.



. Cuando el navegador lo solicite, introduzca su cuenta de usuario y contraseña.
+
Una vez autenticada su cuenta, el explorador mostrará vínculos a `/mroot/etc/log/`, `/mroot/etc/crash/`, y. `/mroot/etc/mib/` directorios de cada nodo del clúster.


