---
permalink: system-admin/access-cluster-telnet-task.html 
sidebar: sidebar 
keywords: access, cluster, telnet, administrative, tasks, disbale, default 
summary: Puede enviar solicitudes Telnet al clúster para realizar tareas administrativas. Telnet está desactivado de forma predeterminada. 
---
= Acceda al clúster mediante Telnet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede enviar solicitudes Telnet al clúster para realizar tareas administrativas. Telnet está desactivado de forma predeterminada.

.Lo que necesitará
Para poder utilizar Telnet para acceder al clúster se deben cumplir las siguientes condiciones:

* Debe tener una cuenta de usuario local de clúster configurada para utilizar Telnet como método de acceso.
+
La `-application` parámetro de `security login` los comandos especifican el método de acceso para una cuenta de usuario. Para obtener más información, consulte `security login` páginas de manual.



.Acerca de esta tarea
* Telnet no es un protocolo seguro.
+
Debe considerar utilizar SSH para acceder al clúster. SSH proporciona un shell remoto seguro y una sesión de red interactiva.

* ONTAP admite un máximo de 50 sesiones Telnet simultáneas por nodo.
+
Si el LIF de gestión del clúster reside en el nodo, comparte este límite con la LIF de gestión del nodo.

+
Si la tasa de conexiones próximas es superior a 10 por segundo, el servicio se deshabilitará temporalmente durante 60 segundos.

* Si desea acceder a la CLI de ONTAP desde un host de Windows, puede utilizar una herramienta de otro proveedor, como PuTTY.
* Los comandos RSH requieren privilegios avanzados.


.Pasos
. Confirme que el protocolo de seguridad Telnet está activado:
+
`security protocol show`

+
.. Si el protocolo de seguridad Telnet está activado, continúe con el siguiente paso.
.. Si el protocolo de seguridad Telnet no está habilitado, utilice el siguiente comando para activarlo:
+
`security protocol modify -application telnet -enabled true`



. Confirme que `management-telnet-server` el servicio existe en las LIF de gestión:
+
`network interface show -services management-telnet-server`

+
.. Si el `management-telnet-server` servicio existe, continúe con el siguiente paso.
.. Si el `management-telnet-server` servicio no existe, utilice el siguiente comando para agregarlo:
+
`network interface service-policy add-service -vserver cluster1 -policy default-management -service management-telnet-server`





.Ejemplo de una solicitud Telnet
El siguiente ejemplo muestra cómo el usuario llamado "'joe'", que se ha configurado con acceso Telnet, puede emitir una solicitud Telnet para acceder a un clúster cuya LIF de administración de clúster es 10.72.137.28:

[listing]
----
admin_host$ telnet 10.72.137.28
Data ONTAP
login: joe
Password:
cluster1::>
----