---
permalink: system-admin/accounts-access-sp-concept.html 
sidebar: sidebar 
keywords: account, access, sp, cluster, user, cli, node 
summary: Cuando intenta acceder al SP, se le solicita la credencial de. Las cuentas de usuario del clúster que se crean con el tipo de aplicación de procesador de servicio tienen acceso a la CLI de SP en cualquier nodo del clúster. Las cuentas de usuario del SP se gestionan desde ONTAP y se autentican mediante contraseña. A partir de ONTAP 9.9.1, las cuentas de usuario del SP deben tener el rol de administrador. 
---
= Acceda a la instancia de ONTAP Processor con una cuenta de usuario de clúster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando intenta acceder al SP, se le solicita la credencial de. Las cuentas de usuario del clúster que se crean con el `service-processor` tipo de aplicación tienen acceso a la CLI de SP en cualquier nodo del clúster. Las cuentas de usuario del SP se gestionan desde ONTAP y se autentican mediante contraseña. A partir de ONTAP 9.9,1, las cuentas de usuario de SP deben tener `admin` el rol.

Las cuentas de usuario para acceder al SP se gestionan desde ONTAP en lugar de desde la CLI de SP. Una cuenta de usuario de clúster puede acceder a la SP si se crea con el `-application` parámetro `security login create` del conjunto de comandos en `service-processor` y el `-authmethod` parámetro establecido en `password`. El SP solo admite la autenticación por contraseña.

Es necesario especificar `-role` el parámetro cuando se crea una cuenta de usuario de SP.

* En ONTAP 9.9,1 y versiones posteriores, es necesario especificar `admin` el `-role` parámetro y las modificaciones de una cuenta requerirán el `admin` rol. Ya no se permiten otras funciones por motivos de seguridad.
+
** Si va a actualizar a ONTAP 9.9,1 o versiones posteriores, consulte link:../upgrade/sp-user-accounts-change-concept.html["Cambio en las cuentas de usuario que pueden acceder a Service Processor"].
** Si va a volver a ONTAP 9.8 o versiones anteriores, consulte link:../revert/verify-sp-user-accounts-task.html["Compruebe las cuentas de usuario que pueden acceder a Service Processor"].


* En ONTAP 9, 8 y versiones anteriores, cualquier rol puede acceder a SP, pero `admin` se recomienda.


De forma predeterminada, la cuenta de usuario del clúster denominada «`admin`» incluye `service-processor` el tipo de aplicación y tiene acceso a la SP.

ONTAP evita la creación de cuentas de usuario con nombres reservados para el sistema (como «'root'» y «'naroot'»). No puede utilizar un nombre reservado con el sistema para acceder al clúster ni a SP.

Puede mostrar las cuentas de usuario de SP actuales con `-application service-processor` el parámetro `security login show` del comando.
