---
permalink: system-admin/accounts-access-sp-concept.html 
sidebar: sidebar 
keywords: account, access, sp, cluster, user, cli, node 
summary: Cuando intenta acceder al SP, se le solicita la credencial de. Las cuentas de usuario del clúster que se crean con el tipo de aplicación de procesador de servicio tienen acceso a la CLI de SP en cualquier nodo del clúster. Las cuentas de usuario del SP se gestionan desde ONTAP y se autentican mediante contraseña. A partir de ONTAP 9.9.1, las cuentas de usuario del SP deben tener el rol de administrador. 
---
= Cuentas que pueden acceder al SP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando intenta acceder al SP, se le solicita la credencial de. Las cuentas de usuario del clúster que se crean con la `service-processor` El tipo de aplicación tiene acceso a la CLI del SP en cualquier nodo del clúster. Las cuentas de usuario del SP se gestionan desde ONTAP y se autentican mediante contraseña. A partir de ONTAP 9.9.1, las cuentas de usuario del SP deben tener el `admin` función.

Las cuentas de usuario para acceder al SP se gestionan desde ONTAP en lugar de desde la CLI de SP. Una cuenta de usuario del clúster puede acceder al SP si se crea con el `-application` parámetro de `security login create` comando establecido en `service-processor` y la `-authmethod` parámetro establecido en `password`. El SP solo admite la autenticación por contraseña.

Debe especificar el `-role` Parámetro al crear una cuenta de usuario del SP.

* En ONTAP 9.9.1 y versiones posteriores, es necesario especificar `admin` para la `-role` y cualquier modificación en una cuenta requiere el `admin` función. Ya no se permiten otras funciones por motivos de seguridad.
+
** Si va a actualizar a ONTAP 9.9.1 o versiones posteriores, consulte link:../upgrade/sp-user-accounts-change-concept.html["Cambio en las cuentas de usuario que pueden acceder a Service Processor"].
** Si va a revertir a ONTAP 9.8 o versiones anteriores, consulte link:../revert/verify-sp-user-accounts-task.html["Compruebe las cuentas de usuario que pueden acceder a Service Processor"].


* En ONTAP 9.8 y versiones anteriores, cualquier rol puede acceder al SP, pero `admin` es recomendable.


De forma predeterminada, la cuenta de usuario del clúster denominada «'admin'» incluye `service-processor` Tipo de aplicación y tiene acceso al SP.

ONTAP evita la creación de cuentas de usuario con nombres reservados para el sistema (como «'root'» y «'naroot'»). No puede utilizar un nombre reservado con el sistema para acceder al clúster ni a SP.

Puede mostrar cuentas de usuario actuales del SP mediante el `-application service-processor` parámetro de `security login show` comando.
