---
permalink: system-admin/add-nodes-cluster-concept.html 
sidebar: sidebar 
keywords: add, node, cluster, create, expand 
summary: Después de crear un clúster, puede ampliarlo añadiendo nodos a él. Solo añade un nodo a la vez. 
---
= Añada nodos a un clúster de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de crear un clúster, puede ampliarlo añadiendo nodos a él. Solo añade un nodo a la vez.

.Antes de empezar
* Si va a añadir nodos a un clúster de varios nodos, todos los nodos existentes del clúster deben estar en buen estado (indicado por `cluster show`). Obtenga más información sobre `cluster show` en el link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["Referencia de comandos del ONTAP"^].
* Si va a añadir nodos a un clúster de dos nodos sin switches, debe convertir un clúster de dos nodos sin switches en un clúster conectado a switches mediante un switch de clúster compatible con NetApp.
+
La funcionalidad de clúster sin switch solo se admite en un clúster de dos nodos.

* Si va a añadir un segundo nodo a un clúster de un solo nodo, debe haber instalado el segundo nodo y debe haber configurado la red de clúster.
* Si el clúster tiene habilitada la configuración automática de SP, la subred especificada para el SP debe tener recursos disponibles para permitir que el nodo de unión utilice la subred especificada para configurar automáticamente el SP.
* Debe haber recopilado la siguiente información para la LIF de gestión de nodos del nuevo nodo:
+
** Puerto
** Dirección IP
** Máscara de red
** Pasarela predeterminada




.Acerca de esta tarea
Los nodos deben tener números pares para que puedan formar pares de alta disponibilidad. Después de comenzar a añadir un nodo al clúster, debe completar el proceso. El nodo debe formar parte del clúster antes de poder empezar a añadir otro nodo.

.Pasos
. Encienda el nodo que desea añadir al clúster.
+
El nodo arranca y se inicia el Asistente de configuración de nodos en la consola.

+
[listing]
----
Welcome to node setup.

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the setup wizard.
     Any changes you made before quitting will be saved.

To accept a default or omit a question, do not enter a value.

Enter the node management interface port [e0M]:
----
. Salga del asistente de configuración de nodos: `exit`
+
Se cerrará el asistente de configuración de nodos y aparecerá una solicitud de inicio de sesión con la advertencia de que no ha completado las tareas de configuración.

+
Obtenga más información sobre `exit` en el link:https://docs.netapp.com/us-en/ontap-cli/exit.html["Referencia de comandos del ONTAP"^].

. Inicie sesión en la cuenta de administrador con `admin` el nombre de usuario.
. Inicie el asistente Cluster Setup:
+
`*cluster setup*`

+
[listing]
----
::> cluster setup

Welcome to the cluster setup wizard.

You can enter the following commands at any time:
 "help" or "?" - if you want to have a question clarified,
 "back" - if you want to change previously answered questions, and
 "exit" or "quit" - if you want to quit the cluster setup wizard.
 Any changes you made before quitting will be saved.

You can return to cluster setup at any time by typing "cluster setup".
To accept a default or omit a question, do not enter a value....

Use your web browser to complete cluster setup by accessing
https://<node_mgmt_or_e0M_IP_address>

Otherwise, press Enter to complete cluster setup using the
command line interface:
----
+
[NOTE]
====
Para obtener más información sobre cómo configurar un clúster mediante la GUI de configuración, consulte link:https://docs.netapp.com/us-en/ontap/task_admin_add_nodes_to_cluster.html["System Manager"]la ayuda en línea. Obtenga más información sobre `cluster setup` en el link:https://docs.netapp.com/us-en/ontap-cli/cluster-setup.html["Referencia de comandos del ONTAP"^].

====
. Presione Enter para usar la CLI para completar esta tarea. Cuando se le solicite crear un nuevo cluster o unirse a uno existente, introduzca `*join*`.
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
join
----
+
Si la versión de ONTAP que se ejecuta en el nodo nuevo es diferente a la versión de que se ejecuta en el clúster existente, el sistema informará de un `System checks Error: Cluster join operation cannot be performed at this time` error. Este es el comportamiento esperado. Para continuar, ejecute `add-node -allow-mixed-version-join new_node_name` el comando en el nivel de privilegio avanzado desde un nodo existente del clúster.

. Siga las instrucciones para configurar el nodo y unirlo al clúster:
+
** Para aceptar el valor predeterminado de una petición de datos, pulse Intro.
** Para introducir su propio valor para una petición de datos, introduzca el valor y, a continuación, pulse Intro.


. Repita los pasos anteriores para cada nodo adicional que desee añadir.


.Después de terminar
Después de añadir nodos al clúster, debe habilitar la conmutación por error del almacenamiento para cada pareja de alta disponibilidad.

.Información relacionada
link:../upgrade/concept_mixed_version_requirements.html#mixed-version-clusters-supported-for-ontap-software-upgrades["Clústeres de ONTAP de versión mixta"]
