---
permalink: system-admin/audit-display-log-contents-task.html 
sidebar: sidebar 
keywords: audit, log, cluster, display 
summary: Puede mostrar el contenido del archivo /mroot/etc/log/mlog/audit.log mediante la CLI de ONTAP, System Manager o un navegador web. 
---
= Mostrar el contenido del registro de auditoría de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede mostrar el contenido de `/mroot/etc/log/mlog/audit.log` los archivos del clúster mediante la CLI de ONTAP, System Manager o un explorador web.

Las entradas del archivo de registro del clúster incluyen lo siguiente:

Tiempo:: Marca de hora de entrada del registro.
Cliente más:: La aplicación utilizada para conectarse al clúster. Ejemplos de valores posibles son `internal`, , `console`, , `ssh` `http` `ontapi` , , , `snmp`, `rsh`, `telnet`, y `service-processor`.
Usuario:: El nombre de usuario del usuario remoto.
Estado:: Estado actual de la solicitud de auditoría, que puede ser `success`, `pending` o `error`.
Mensaje:: Un campo opcional que puede contener errores o información adicional acerca del estado de un comando.
ID de sesión:: El ID de sesión en el que se recibe la solicitud. A cada SSH _Session_ se le asigna un ID de sesión, mientras que a cada HTTP, ONAPI o SNMP _Request_ se le asigna un ID de sesión único.
Máquina virtual de almacenamiento:: La SVM a través de la cual se conectó el usuario.
Ámbito:: Muestra `svm` cuando la solicitud está en una máquina virtual de almacenamiento de datos; de lo contrario, muestra `cluster`.
ID del comando:: El ID de cada comando recibido en una sesión de CLI. Esto permite correlacionar una solicitud y una respuesta. LAS solicitudes ZAPI, HTTP y SNMP no tienen ID de comandos.


Puede mostrar las entradas del registro del clúster desde la interfaz de línea de comandos de ONTAP, desde un explorador web y a partir de ONTAP 9.11.1, desde System Manager.

[role="tabbed-block"]
====
.System Manager
--
* Para visualizar el inventario, seleccione *Eventos y trabajos > registros de auditoría*. + cada columna tiene controles para filtrar, ordenar, buscar, mostrar e inventario. Los detalles del inventario se pueden descargar como un libro de Excel.
* Para definir los filtros, haga clic en el botón *filtro* situado en la parte superior derecha y, a continuación, seleccione los campos deseados. + también puede ver todos los comandos ejecutados en la sesión en la que se produjo un error haciendo clic en el enlace ID de sesión.


--
.CLI
--
Para mostrar las entradas de auditoría fusionadas de varios nodos del clúster, introduzca: +
`security audit log show <[parameters]>`

Puede usar el `security audit log show` comando para mostrar entradas de auditoría de nodos individuales o fusionadas desde varios nodos del clúster. También puede mostrar el contenido `/mroot/etc/log/mlog` del directorio en un solo nodo mediante un navegador web. Obtenga más información sobre `security audit log show` en el link:https://docs.netapp.com/us-en/ontap-cli/security-audit-log-show.html["Referencia de comandos del ONTAP"^].

--
.Navegador Web
--
Puede mostrar el contenido `/mroot/etc/log/mlog` del directorio en un solo nodo mediante un navegador web. link:accessg-node-log-core-dump-mib-files-task.html["Obtenga información sobre cómo acceder al registro de un nodo, al volcado de memoria y a archivos MIB mediante un explorador web"].

--
====