---
permalink: system-admin/autosupport-size-time-budgets-reference.html 
sidebar: sidebar 
keywords: autosupport, size, time, budget, subsystem, payload, data, delivery 
summary: AutoSupport recopila información organizada por subsistemas y aplica un presupuesto de tamaño y tiempo sobre el contenido de cada subsistema. A medida que crecen los sistemas de almacenamiento, los presupuestos de AutoSupport proporcionan control sobre la carga útil de AutoSupport, que, a su vez, proporciona una entrega escalable de datos de AutoSupport. 
---
= Obtenga información sobre el tamaño y los presupuestos de tiempo de ONTAP AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport recopila información organizada por subsistemas y aplica un presupuesto de tamaño y tiempo sobre el contenido de cada subsistema. A medida que crecen los sistemas de almacenamiento, los presupuestos de AutoSupport proporcionan control sobre la carga útil de AutoSupport, que, a su vez, proporciona una entrega escalable de datos de AutoSupport.

AutoSupport deja de recopilar información y acorta el contenido de AutoSupport si el contenido del subsistema supera su tamaño o presupuesto para tiempo. Si el contenido no se puede truncar fácilmente (por ejemplo, archivos binarios), AutoSupport omite el contenido.

Solo debe modificar el tamaño y el presupuesto de tiempo predeterminados si el soporte de NetApp le solicita que lo haga. También puede revisar el tamaño por defecto y los presupuestos de tiempo de los subsistemas mediante el `autosupport manifest show` comando.
