---
permalink: system-admin/autosupport-active-iq-digital-advisor-concept.html 
sidebar: sidebar 
keywords: autosupport, active iq, digital advisor, active, iq, digital, advisor, telemetry, artificial, intelligence 
summary: El componente AutoSupport de ONTAP recopila telemetría y la envía para su análisis. El asesor digital analiza los datos de AutoSupport y ofrece una optimización y atención proactivas. Mediante la inteligencia artificial, el asesor digital puede identificar problemas potenciales y ayudarle a resolverlos antes de que afecten a su negocio. 
---
= Obtén más información sobre el asesor digital y ONTAP AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El componente AutoSupport de ONTAP recopila telemetría y la envía para su análisis. El asesor digital analiza los datos de AutoSupport y ofrece una optimización y atención proactivas. Mediante la inteligencia artificial, el asesor digital puede identificar problemas potenciales y ayudarle a resolverlos antes de que afecten a su negocio.

El asesor digital le permite optimizar su infraestructura de datos en el cloud híbrido global mediante análisis predictivos aplicables y soporte proactivo a través de un portal basado en cloud y una aplicación móvil. La información y las recomendaciones impulsadas por los datos del asesor digital están disponibles para todos los clientes de NetApp con un contrato de SupportEdge activo (las funciones varían según el producto y el nivel de soporte).

Estas son algunas cosas que puedes hacer con Digital Advisor:

* Planificación de actualizaciones. El asesor digital identifica problemas en su entorno que pueden resolverse actualizando a una versión más reciente de ONTAP y el componente Asesor de renovación le ayudará a planificar una actualización correcta.
* Ver el bienestar del sistema. Su consola del asesor digital notifica cualquier problema de estado y le ayuda a corregir esos problemas. Supervise la capacidad del sistema para asegurarse de que nunca se queda sin espacio de almacenamiento. Vea los casos de soporte de su sistema.
* Gestión del rendimiento. El asesor digital muestra el rendimiento del sistema durante un período más largo del que se puede observar en System Manager. Identifique problemas de configuración y del sistema que afectan a su rendimiento.
* Optimice la eficiencia. Consulte los criterios de medición de la eficiencia del almacenamiento e identifique formas de almacenar más datos en menos espacio.
* Ver el inventario y la configuración. El asesor digital muestra información completa sobre la configuración de software y hardware. Vea cuándo caducan los contratos de servicio y renueve su soporte para asegurarse de que sigue siendo compatible.


.Información relacionada
https://docs.netapp.com/us-en/active-iq/["Documentación de NetApp: Asesor digital"^]

https://aiq.netapp.com/custom-dashboard/search["Inicie el asesor digital"^]

https://www.netapp.com/us/services/support-edge.aspx["Servicios de SupportEdge"^]
