---
permalink: system-admin/boot-ontap-at-boot-environment-prompt-task.html 
sidebar: sidebar 
keywords: boot, ontap, environment, prompt, current, release, node 
summary: Puede arrancar la versión actual o la versión de backup de ONTAP cuando se encuentra en el símbolo del sistema de un entorno de arranque de un nodo. 
---
= Arranque ONTAP en el símbolo del sistema del entorno de arranque
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede arrancar la versión actual o la versión de backup de ONTAP cuando se encuentra en el símbolo del sistema de un entorno de arranque de un nodo.

.Pasos
. Acceda al símbolo del sistema del entorno de arranque desde el símbolo del sistema del sistema de almacenamiento mediante el `system node halt` comando.
+
La consola del sistema de almacenamiento muestra el símbolo del sistema del entorno de arranque.

. En el símbolo del sistema de entorno de arranque, introduzca uno de los siguientes comandos:
+
|===
| Para arrancar... | Introduzca... 


 a| 
La versión actual de ONTAP
 a| 
`boot_ontap`



 a| 
La imagen principal de ONTAP desde el dispositivo de arranque
 a| 
`boot_primary`



 a| 
La imagen de copia de seguridad de ONTAP desde el dispositivo de arranque
 a| 
`boot_backup`

|===
+
Si no está seguro de qué imagen usar, debe usar `boot_ontap` en primer lugar.


