---
permalink: system-admin/changes-audit-logging-ontap-9-concept.html 
sidebar: sidebar 
keywords: audit, logging, ontap, 9, command, history, scripts, tool 
summary: A partir de ONTAP 9, el archivo command-history.log se reemplaza por audit.log, y el archivo mgwd.log ya no contiene información de auditoría. Si actualiza a ONTAP 9, debe revisar cualquier script o herramienta que haga referencia a los archivos heredados y su contenido. 
---
= Cambios en el registro de auditoría en ONTAP 9
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9, el `command-history.log` el archivo se sustituye por `audit.log`, y la `mgwd.log` el archivo ya no contiene información de auditoría. Si actualiza a ONTAP 9, debe revisar cualquier script o herramienta que haga referencia a los archivos heredados y su contenido.

Después de actualizar a ONTAP 9, existente `command-history.log` los archivos se conservan. Se rotan (eliminan) como nuevas `audit.log` los archivos se giran en (crean).

Herramientas y scripts que comprueban `command-history.log` es posible que el archivo continúe funcionando, porque un vínculo de software de `command-history.log` para `audit.log` se crea al actualizar. Sin embargo, herramientas y scripts que comprueban `mgwd.log` el archivo fallará porque ese archivo ya no contiene información de auditoría.

Además, los registros de auditoría de ONTAP 9 y versiones posteriores ya no incluyen las siguientes entradas porque no se consideran útiles y provocan una actividad de registro innecesaria:

* Comandos internos ejecutados por ONTAP (es decir, donde username=root)
* Alias de comandos (por separado del comando al que apuntan)


A partir de ONTAP 9, puede transmitir los registros de auditoría de manera segura a destinos externos mediante los protocolos TCP y TLS.
