---
permalink: system-admin/changes-audit-logging-ontap-9-concept.html 
sidebar: sidebar 
keywords: audit, logging, ontap, 9, command, history, scripts, tool 
summary: A partir de ONTAP 9, el archivo command-history.log se reemplaza por audit.log, y el archivo mgwd.log ya no contiene información de auditoría. Si actualiza a ONTAP 9, debe revisar cualquier script o herramienta que haga referencia a los archivos heredados y su contenido. 
---
= Obtenga más información sobre los cambios en el registro de auditorías de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9, el `command-history.log` archivo se sustituye por `audit.log`, y el `mgwd.log` archivo ya no contiene información de auditoría. Si actualiza a ONTAP 9, debe revisar cualquier script o herramienta que haga referencia a los archivos heredados y su contenido.

Después de actualizar a ONTAP 9, `command-history.log` se conservan los archivos existentes. Se rotan (se eliminan) a medida que los nuevos `audit.log` archivos se rotan (se crean).

Las herramientas y los scripts que comprueban el `command-history.log` archivo pueden seguir funcionando, ya que se `command-history.log` `audit.log` crea un enlace flexible de a durante la actualización. Sin embargo, las herramientas y los scripts que comprueban el `mgwd.log` archivo fallarán, ya que ese archivo ya no contiene información de auditoría.

Además, los registros de auditoría de ONTAP 9 y versiones posteriores ya no incluyen las siguientes entradas porque no se consideran útiles y provocan una actividad de registro innecesaria:

* Comandos internos ejecutados por ONTAP (es decir, donde username=root)
* Alias de comandos (por separado del comando al que apuntan)


A partir de ONTAP 9, puede transmitir los registros de auditoría de manera segura a destinos externos mediante los protocolos TCP y TLS.
