---
permalink: system-admin/cluster-svm-administrators-concept.html 
sidebar: sidebar 
keywords: cluster, svm, administrators,cluster, storage, virtual, machines, svm, vserver 
summary: 'Los administradores de clúster administran todo el clúster y las máquinas virtuales de almacenamiento (SVM, antes denominadas Vserver) que contiene. Los administradores de SVM solo administran sus propias SVM de datos.' 
---
= Administradores de clústeres y SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los administradores de clúster administran todo el clúster y las máquinas virtuales de almacenamiento (SVM, antes denominadas Vserver) que contiene. Los administradores de SVM solo administran sus propias SVM de datos.

Los administradores del clúster pueden administrar todo el clúster y sus recursos. También pueden configurar SVM de datos y delegar la administración de SVM a los administradores de SVM. Las funcionalidades específicas que tienen los administradores de clúster dependen de sus roles de control de acceso. De forma predeterminada, un administrador de clúster con el nombre de cuenta o el nombre de la función «'admin'» tiene todas las funcionalidades necesarias para gestionar el clúster y las SVM.

Los administradores de SVM solo pueden administrar sus propios recursos de red y almacenamiento de SVM, como volúmenes, protocolos, LIF y servicios. Las funcionalidades específicas que tienen los administradores de SVM dependen de los roles de control de acceso que asignan los administradores del clúster.

[NOTE]
====
La interfaz de línea de comandos (CLI) de ONTAP sigue utilizando el término _vserver_ en la salida y. `vserver` como comando o nombre de parámetro no se ha modificado.

====