---
permalink: system-admin/cluster-management-server-concept.html 
sidebar: sidebar 
keywords: cluster, management, server, adminsvm, svm, single, entity 
summary: 'El servidor de gestión de clústeres, también denominado adminSVM, es una implementación de máquinas virtuales de almacenamiento (SVM) especializada que presenta el clúster como una única entidad gestionable. Además de servir como dominio administrativo de nivel superior, el servidor de gestión de clústeres posee recursos que no pertenecen lógicamente a una SVM de datos.' 
---
= Obtenga información sobre el servidor de gestión de clústeres de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El servidor de gestión de clústeres, también llamado __admin__SVM, es una implementación de máquinas virtuales de almacenamiento (SVM) especializada que presenta el clúster como una única entidad gestionable. Además de servir como dominio administrativo de nivel superior, el servidor de gestión de clústeres posee recursos que no pertenecen lógicamente a una SVM de datos.

El servidor de gestión de clústeres está siempre disponible en el clúster. Puede acceder al servidor de gestión de clústeres mediante la LIF de gestión de la consola o el clúster.

En caso de fallo del puerto de red inicial, el LIF de gestión de clústeres conmuta automáticamente a otro nodo del clúster. En función de las características de conectividad del protocolo de gestión que utilice, es posible que note la conmutación por error o no. Si utiliza un protocolo sin conexión (por ejemplo, SNMP) o tiene una conexión limitada (por ejemplo, HTTP), no es probable que note la conmutación por error. Sin embargo, si utiliza una conexión a largo plazo (por ejemplo, SSH), deberá volver a conectarse al servidor de gestión de clústeres después de la conmutación al respaldo.

Cuando se crea un clúster, se configuran todas las características de la LIF de gestión del clúster, incluida su dirección IP, máscara de red, puerta de enlace y puerto.

A diferencia de una SVM de datos o una SVM de nodo, un servidor de gestión de clústeres no tiene un volumen raíz o volúmenes de usuario host (aunque puede alojar volúmenes del sistema). Además, un servidor de gestión de clústeres solo puede tener LIF del tipo de gestión de clústeres.

Si ejecuta `vserver show` el comando, el servidor de administración del clúster aparece en la lista de resultados de ese comando.
