---
permalink: system-admin/commands-manage-node-remotely-reference.html 
sidebar: sidebar 
keywords: command, manage, node, remotely, sp, cli, cluster 
summary: Puede gestionar un nodo de forma remota accediendo a su SP y ejecutando comandos de la CLI de SP para realizar tareas de gestión de nodos. Para varias tareas de gestión remota de nodos de ejecución común, también puede utilizar comandos ONTAP de otro nodo en el clúster. Algunos comandos del SP son específicos de la plataforma y es posible que no estén disponibles en la plataforma. 
---
= Comandos ONTAP para la gestión de nodos remotos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede gestionar un nodo de forma remota accediendo a su SP y ejecutando comandos de la CLI de SP para realizar tareas de gestión de nodos. Para varias tareas de gestión remota de nodos de ejecución común, también puede utilizar comandos ONTAP de otro nodo en el clúster. Algunos comandos del SP son específicos de la plataforma y es posible que no estén disponibles en la plataforma.

|===
| Si desea... | Usar este comando del SP... | Usar este comando de BMC... | O este comando de ONTAP ... 


 a| 
Mostrar los comandos de SP disponibles o subcomandos de un comando de SP especificado
 a| 
`help` [`command`]
 a| 
 a| 



 a| 
Muestra el nivel actual de privilegio de la CLI del SP
 a| 
`priv show`
 a| 
 a| 



 a| 
Establezca el nivel de privilegio para acceder al modo especificado para la CLI del SP
 a| 
`priv set` {`admin` | `advanced` | `diag`}
 a| 
 a| 



 a| 
Muestra la fecha y la hora del sistema
 a| 
`date`
 a| 
 a| 
`date`



 a| 
Muestra los eventos que ha registrado el SP
 a| 
`events` {`all` | `info` | `newest` `number` | `oldest number` | `search keyword`}
 a| 
 a| 



 a| 
Mostrar el estado del SP y la información de configuración de red
 a| 
`sp status` [`-v` | `-d`]

La `-v` La opción muestra las estadísticas de SP en forma detallada. La `-d` La opción añade el registro de depuración del SP a la pantalla.
 a| 
`bmc status` [`-v` | `-d`]

La `-v` La opción muestra las estadísticas de SP en forma detallada. La `-d` La opción añade el registro de depuración del SP a la pantalla.
 a| 
`system service-processor show`



 a| 
Muestra la cantidad de tiempo que ha estado activo el SP y el número medio de trabajos de la cola de ejecución durante los últimos 1, 5 y 15 minutos
 a| 
`sp uptime`
 a| 
`bmc uptime`
 a| 



 a| 
Mostrar los registros de la consola del sistema
 a| 
`system log`
 a| 
 a| 



 a| 
Mostrar los archivos de registro del SP o los archivos de un archivo
 a| 
`sp log history show` [`-archive` {`latest` |{`all` | `archive-name`}] [`-dump` {`all` | `file-name`}]
 a| 
`bmc log history show` [`-archive` {`latest` |{`all` | `archive-name`}] [`-dump` {`all` | `file-name`}]
 a| 



 a| 
Muestra el estado de alimentación de la controladora de un nodo
 a| 
`system power status`
 a| 
 a| 
`system node power show`



 a| 
Muestra información de la batería
 a| 
`system battery show`
 a| 
 a| 



 a| 
Muestre información de ACP o el estado de los sensores de ampliación
 a| 
`system acp` [`show` | `sensors show`]
 a| 
 a| 



 a| 
Enumerar todas las FRU del sistema y sus ID
 a| 
`system fru list`
 a| 
 a| 



 a| 
Muestra información de producto de la FRU especificada
 a| 
`system fru show` `fru_id`
 a| 
 a| 



 a| 
Mostrar el registro del historial de datos de FRU
 a| 
`system fru log show` (nivel de privilegio avanzado)
 a| 
 a| 



 a| 
Muestra el estado de los sensores medioambientales, incluidos sus estados y valores actuales
 a| 
`system sensors` o. `system sensors show`
 a| 
 a| 
`system node environment sensors show`



 a| 
Muestra el estado y los detalles del sensor especificado
 a| 
`system sensors get` `sensor_name`

Usted puede obtener `sensor_name` mediante el uso de `system sensors` o la `system sensors show` comando.
 a| 
 a| 



 a| 
Muestra la información de la versión del firmware del SP
 a| 
`version`
 a| 
 a| 
`system service-processor image show`



 a| 
Muestra el historial de comandos del SP
 a| 
`sp log audit` (nivel de privilegio avanzado)
 a| 
`bmc log audit`
 a| 



 a| 
Muestra la información de depuración del SP
 a| 
`sp log debug` (nivel de privilegio avanzado)
 a| 
`bmc log debug` (nivel de privilegio avanzado)
 a| 



 a| 
Muestra el archivo de mensajes del SP
 a| 
`sp log messages` (nivel de privilegio avanzado)
 a| 
`bmc log messages` (nivel de privilegio avanzado)
 a| 



 a| 
Mostrar la configuración para recopilar información forense del sistema en un evento de restablecimiento del guardián, mostrar la información forense del sistema recopilada durante un evento de restablecimiento del guardián o borrar la información forense del sistema recopilada
 a| 
`system forensics` [`show` | `log dump` | `log clear`]
 a| 
 a| 



 a| 
Inicie sesión en la consola del sistema
 a| 
`system console`
 a| 
 a| 
`system node run-console`



 a| 
Debe pulsar Ctrl-D para salir de la sesión de la consola del sistema.



 a| 
Encender o apagar el nodo, o realizar un ciclo de encendido y apagado (apagando la alimentación y volviendo a encender)
 a| 
`system power` `on`
 a| 
 a| 
`system node power on` (nivel de privilegio avanzado)



 a| 
`system power` `off`
 a| 
 a| 



 a| 
`system power` `cycle`
 a| 
 a| 



 a| 
La alimentación en espera permanece encendida para mantener el SP en funcionamiento sin interrupciones. Durante el ciclo de encendido, se produce una breve pausa antes de volver a encender la alimentación.

[NOTE]
====
El uso de estos comandos para apagar o realizar un ciclo de apagado y encendido del nodo puede provocar un apagado incorrecto del nodo (también llamado _dirty shutdown_) y no es un sustituto para un apagado correcto usando la ONTAP `system node halt` comando.

====


 a| 
Cree un volcado de memoria y restablezca el nodo
 a| 
`system core` [`-f`]

La `-f` option fuerza la creación de un volcado de memoria y el restablecimiento del nodo.
 a| 
 a| 
`system node coredump trigger`

(nivel de privilegio avanzado)



 a| 
Estos comandos tienen el mismo efecto que presionar el botón de interrupción no enmascarable (NMI) en un nodo, lo que provoca un apagado con errores del nodo y obliga a un volcado de los archivos principales cuando se detenga el nodo. Estos comandos son útiles cuando ONTAP del nodo está colgado o no responde a comandos como `system node shutdown`. Los archivos de volcado de memoria generados se muestran en el resultado del `system node coredump show` comando. El SP sigue operativo siempre que no se interrumpa la alimentación de entrada del nodo.



 a| 
Reinicie el nodo con una imagen de firmware de BIOS especificada opcionalmente (principal, de backup o actual) para recuperarse de problemas, como una imagen dañada del dispositivo de arranque del nodo
 a| 
`system reset` {`primary` | `backup` | `current`}
 a| 
 a| 
`system node reset` con la `-firmware` {`primary` | `backup` | `current`parámetro } (nivel de privilegio avanzado)

`system node reset`



 a| 
[NOTE]
====
Esta operación provoca un apagado con errores del nodo.

====
Si no se especifica ninguna imagen de firmware de BIOS, se utiliza la imagen actual para el reinicio. El SP sigue operativo siempre que no se interrumpa la alimentación de entrada del nodo.



 a| 
Muestra el estado de la actualización automática del firmware de la batería, o habilita o deshabilita la actualización automática del firmware de la batería tras el siguiente arranque del SP
 a| 
`system battery auto_update` [`status` | `enable` | `disable`]

(nivel de privilegio avanzado)
 a| 
 a| 



 a| 
Compare la imagen del firmware de la batería actual con una imagen de firmware especificada
 a| 
`system battery verify` [`image_URL`]

(nivel de privilegio avanzado)

Si `image_URL` no se especifica, se utiliza la imagen de firmware de la batería predeterminada para la comparación.
 a| 
 a| 



 a| 
Actualice el firmware de la batería desde la imagen en la ubicación especificada
 a| 
`system battery flash` `image_URL`

(nivel de privilegio avanzado)

Es posible utilizar este comando si no se pudo realizar el proceso de actualización automática del firmware de la batería por algún motivo.
 a| 
 a| 



 a| 
Actualice el firmware del SP con la imagen en la ubicación especificada
 a| 
`sp update` `image_URL image_URL` no debe superar los 200 caracteres.
 a| 
`bmc update` `image_URL image_URL` no debe superar los 200 caracteres.
 a| 
`system service-processor image update`



 a| 
Reinicia el SP
 a| 
`sp reboot`
 a| 
 a| 
`system service-processor reboot-sp`



 a| 
Borre el contenido flash de NVRAM
 a| 
`system nvram flash clear` (nivel de privilegio avanzado)

No es posible iniciar este comando cuando la controladora está apagada (`system power off`).
 a| 
 a| 



 a| 
Salga de la CLI del SP
 a| 
`exit`
 a| 
 a| 

|===