---
permalink: system-admin/commands-manage-job-schedules-reference.html 
sidebar: sidebar 
keywords: command, manage, job, schedule, volume, snapshot, copy, cron, interval 
summary: 'Puede configurar muchas tareas, como las copias Snapshot de volumen, para que se ejecuten en programaciones específicas. Las programaciones que se ejecutan a horas específicas se denominan programas cron (similares a las programaciones cron de UNIX). Las programaciones que se ejecutan a intervalos se denominan programaciones de intervalos. Los comandos de programación de trabajos se utilizan para gestionar las programaciones de trabajos.' 
---
= Comandos para gestionar programaciones de trabajos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Muchas tareas, por ejemplo, copias Snapshot de volumen, se pueden configurar para ejecutarse en programaciones específicas.las programaciones que se ejecuten en momentos específicos se denominan programaciones _cron_ (similares a UNIX) `cron` horarios). Los horarios que se ejecutan a intervalos se denominan programas _INTERVAL_. Utilice la `job schedule` comandos para gestionar programaciones de trabajos.

Las programaciones de trabajos no se ajustan a los cambios manuales en la fecha y la hora del clúster. Estos trabajos se programan para que se ejecuten en función de la hora actual del clúster cuando se creó el trabajo o cuando se ejecutó el trabajo más recientemente. Por lo tanto, si cambia manualmente la fecha o la hora del clúster, debe usar el `job show` y.. `job history show` comandos para verificar que todos los trabajos programados se ponen en cola y se completan de acuerdo con los requisitos que haya.

Si el clúster forma parte de una configuración de MetroCluster, las programaciones de trabajos en ambos clústeres deben ser idénticas. Por lo tanto, si crea, modifica o elimina una programación de trabajos, debe realizar la misma operación en el clúster remoto.

|===
| Si desea... | Se usa este comando... 


 a| 
Muestra información sobre todos los programas
 a| 
`job schedule show`



 a| 
Mostrar la lista de trabajos según la programación
 a| 
`job schedule show-jobs`



 a| 
Mostrar información acerca de las programaciones de cron
 a| 
`job schedule cron show`



 a| 
Muestra información acerca de los programas de intervalos
 a| 
`job schedule interval show`



 a| 
Cree una programación cron 1
 a| 
`job schedule cron create`



 a| 
Cree una programación de intervalo
 a| 
`job schedule interval create`

Debe especificar al menos uno de los siguientes parámetros: `-days`, `-hours`, `-minutes`, o. `-seconds`.



 a| 
Modificar una programación de cron
 a| 
`job schedule cron modify`



 a| 
Modificar una programación de intervalo
 a| 
`job schedule interval modify`



 a| 
Eliminar una programación
 a| 
`job schedule delete`



 a| 
Eliminar una programación cron
 a| 
`job schedule cron delete`



 a| 
Eliminar una programación de intervalo
 a| 
`job schedule interval delete`

|===
A partir de ONTAP 9.10.1, al crear una programación de trabajo mediante la `job schedule cron create` Comando, puede incluir Vserver para la programación de trabajos.

.Información relacionada
http://["Comandos de ONTAP 9"^]
