---
permalink: system-admin/commands-manage-web-services-reference.html 
sidebar: sidebar 
keywords: command, manage, web, service, vserver, svm, storage, virtual. machine 
summary: 'Puede utilizar los comandos web de los servicios Vserver para gestionar la disponibilidad de los servicios web para el clúster o una máquina virtual de almacenamiento (SVM). Los comandos de acceso web de los servicios Vserver se utilizan para controlar el acceso de una función a un servicio web.' 
---
= Comandos para gestionar servicios web
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilice la `vserver services web` Comandos para gestionar la disponibilidad de servicios web para el clúster o una máquina virtual de almacenamiento (SVM). Utilice la `vserver services web access` comandos para controlar el acceso de un rol a un servicio web.

|===
| Si desea... | Se usa este comando... 


 a| 
Configure un servicio web para el clúster o ANSVM:

* Activar o desactivar un servicio Web
* Especifique si sólo se puede utilizar HTTPS para acceder a un servicio web

 a| 
`vserver services web modify`



 a| 
Muestre la configuración y la disponibilidad de servicios web del clúster o ANSVM
 a| 
`vserver services web show`



 a| 
Autorice a un rol para acceder a un servicio web en el clúster o anSVM
 a| 
`vserver services web access create`



 a| 
Muestre los roles que están autorizados a acceder a los servicios web en el clúster o anSVM
 a| 
`vserver services web access show`



 a| 
Evite que un rol acceda a un servicio web en el clúster o anSVM
 a| 
`vserver services web access delete`

|===
.Información relacionada
http://["Comandos de ONTAP 9"^]
