---
permalink: system-admin/commands-monitor-health-system-reference.html 
sidebar: sidebar 
keywords: command, monitor, health, system, display, status, cli, software, version, switches, alert 
summary: Puede usar los comandos de estado del sistema para mostrar información sobre el estado de los recursos del sistema, responder a las alertas y configurar alertas futuras. El uso de los comandos de la CLI le permite ver información en profundidad sobre la configuración del control del estado. Las páginas de manual de los comandos contienen más información. 
---
= Comandos para supervisar el estado del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar `system health` los comandos para mostrar información sobre el estado de los recursos del sistema, para responder a las alertas y para configurar futuras alertas. El uso de los comandos de la CLI le permite ver información en profundidad sobre la configuración del control del estado. Obtenga más información sobre `system health` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+health["Referencia de comandos de la ONTAP"^].



== Mostrar el estado del estado del sistema

|===
| Si desea... | Se usa este comando... 


 a| 
Muestre el estado del sistema, que refleja el estado general de cada monitor de estado
 a| 
`system health status show`



 a| 
Mostrar el estado de los subsistemas para los que está disponible la supervisión de estado
 a| 
`system health subsystem show`

|===


== Mostrar el estado de conectividad de los nodos

|===
| Si desea... | Se usa este comando... 


 a| 
Muestra detalles acerca de la conectividad del nodo a la bandeja de almacenamiento, incluida la información de puertos, la velocidad del puerto de HBA, el rendimiento de I/o y la tasa de operaciones de I/o por segundo
 a| 
`storage shelf show -connectivity`

Utilice la `-instance` para mostrar información detallada de cada bandeja.



 a| 
Muestra información sobre las unidades y los LUN de cabina, incluidos el espacio utilizable, los números de bandeja y bahía y el nombre del nodo propietario
 a| 
`storage disk show`

Utilice la `-instance` parámetro para mostrar información detallada acerca de cada unidad.



 a| 
Muestra información detallada sobre los puertos de las bandejas de almacenamiento, incluido el tipo de puerto, la velocidad y el estado
 a| 
`storage port show`

Utilice la `-instance` parámetro para mostrar información detallada sobre cada adaptador.

|===


== Gestionar la detección de switches de redes de gestión, almacenamiento y clúster

[cols="3*"]
|===
| Si desea... | Utilice este comando. (ONTAP 9.8 y posterior) | Utilice este comando. (ONTAP 9.7 y anterior) 


 a| 
Muestre los switches que supervisa el clúster
 a| 
`system switch ethernet show`
 a| 
`system cluster-switch show`



 a| 
Muestre los switches que el clúster supervisa actualmente, incluidos los switches que ha eliminado (que se muestran en la columna motivo del resultado del comando), y la información de configuración que necesita para el acceso de red a los switches de red de gestión y clúster.

Este comando solo está disponible en el nivel de privilegios avanzado.
 a| 
`system switch ethernet show-all`
 a| 
`system cluster-switch show-all`



 a| 
Configurar la detección de un switch no detectado
 a| 
`system switch ethernet create`
 a| 
`system cluster-switch create`



 a| 
Modificar la información sobre un conmutador que supervisa el clúster (por ejemplo, nombre de dispositivo, dirección IP, versión SNMP y cadena de comunidad)
 a| 
`system switch ethernet modify`
 a| 
`system cluster-switch modify`



 a| 
Desactive la supervisión de un interruptor
 a| 
`system switch ethernet modify -disable-monitoring`
 a| 
`system cluster-switch modify -disable-monitoring`



 a| 
Desactive la detección y supervisión de un switch y elimine la información de configuración del switch
 a| 
`system switch ethernet delete`
 a| 
`system cluster-switch delete`



 a| 
Eliminar permanentemente la información de configuración del conmutador almacenada en la base de datos (al hacerlo se vuelve a activar el descubrimiento automático del conmutador)
 a| 
`system switch ethernet delete -force`
 a| 
`system cluster-switch delete -force`



 a| 
Active el registro automático para que se envíe con mensajes de AutoSupport.
 a| 
`system switch ethernet log`
 a| 
`system cluster-switch log`

|===


== Responda a alertas generadas

|===
| Si desea... | Se usa este comando... 


 a| 
Muestra información sobre las alertas generadas, como el recurso y el nodo donde se activó la alerta, y la gravedad y la causa probable de la alerta
 a| 
`system health alert show`



 a| 
Muestra información sobre cada alerta generada
 a| 
`system health alert show -instance`



 a| 
Indique que alguien está trabajando en una alerta
 a| 
`system health alert modify`



 a| 
Reconozca una alerta
 a| 
`system health alert modify -acknowledge`



 a| 
Suprimir una alerta posterior para que no afecte al estado de un subsistema
 a| 
`system health alert modify -suppress`



 a| 
Eliminar una alerta que no se borró automáticamente
 a| 
`system health alert delete`



 a| 
Muestra información sobre los mensajes de AutoSupport que se han activado en la última semana, por ejemplo, para determinar si una alerta ha activado un mensaje de AutoSupport
 a| 
`system health autosupport trigger history show`

|===


== Configurar alertas futuras

|===
| Si desea... | Se usa este comando... 


 a| 
Habilite o deshabilite la política que controla si un estado de recurso específico genera una alerta específica
 a| 
`system health policy definition modify`

|===


== Muestra información acerca de cómo se configura la supervisión del estado

|===
| Si desea... | Se usa este comando... 


 a| 
Muestra información acerca de los monitores de estado, como sus nodos, nombres, subsistemas y estado
 a| 
`system health config show`

[NOTE]
====
Utilice la `-instance` parámetro para mostrar información detallada sobre cada monitor de estado.

====


 a| 
Muestre información sobre las alertas que un monitor de estado puede generar potencialmente
 a| 
`system health alert definition show`

[NOTE]
====
Utilice la `-instance` parámetro para mostrar información detallada sobre cada definición de alerta.

====


 a| 
Muestra información sobre las políticas de control de estado, que determinan cuándo se generan las alertas
 a| 
`system health policy definition show`

[NOTE]
====
Utilice la `-instance` parámetro para mostrar información detallada de cada política. Utilice otros parámetros para filtrar la lista de alertas, por ejemplo, el estado de la política (habilitada o no), el monitor de estado, las alertas, etc.

====
|===
Obtenga más información sobre los comandos descritos en este procedimiento en el link:https://docs.netapp.com/us-en/ontap-cli/["Referencia de comandos de la ONTAP"^].
