---
permalink: system-admin/commands-manage-audit-settings-reference.html 
sidebar: sidebar 
keywords: command, manage, audit, settings, management, activity 
summary: Los comandos de auditoría de seguridad se utilizan para gestionar las actividades de administración que se han iniciado sesión en el archivo audit.log. Los comandos cluster log-reforwarding se utilizan para gestionar destinos a los que se debe reenviar el registro de auditoría a. 
---
= Comandos para gestionar la configuración de auditoría para actividades de gestión
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilice la `security audit` comandos para gestionar las actividades de administración que se han iniciado sesión en `audit.log` archivo. Utilice la `cluster log-forwarding` comandos para gestionar destinos a los que se debe reenviar el registro de auditoría a.

|===
| Si desea... | Se usa este comando... 


 a| 
Especifique que las solicitudes Get desde la interfaz de línea de comandos o las API de ONTAP se deben registrar en el registro de auditoría (el `audit.log` archivo), además de establecer solicitudes predeterminadas
 a| 
`security audit modify`



 a| 
Muestre la configuración del registro de auditoría
 a| 
`security audit show`



 a| 
Muestra las entradas de auditoría combinadas de varios nodos en el clúster
 a| 
`security audit log show`



 a| 
Especifique un destino de reenvío para el registro de auditoría y las medidas de seguridad para la transmisión
 a| 
`cluster log-forwarding create`



 a| 
Modificar un destino para el registro de auditoría
 a| 
`cluster log-forwarding modify`



 a| 
Eliminar un destino del registro de auditoría
 a| 
`cluster log-forwarding delete`



 a| 
Muestra los destinos configurados para el registro de auditoría
 a| 
`cluster log-forwarding show`

|===
.Información relacionada
http://["Comandos de ONTAP 9"^]
