---
permalink: system-admin/commands-manage-jobs-reference.html 
sidebar: sidebar 
keywords: command, manage, jobs, queue, cluster, resources 
summary: Los trabajos se colocan en una cola de trabajos y se ejecutan en segundo plano cuando los recursos están disponibles. Si una tarea consume demasiados recursos del clúster, puede detenerla o pausar hasta que haya menos demanda en el clúster. También puede supervisar y reiniciar los trabajos. 
---
= Comandos para gestionar trabajos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los trabajos se colocan en una cola de trabajos y se ejecutan en segundo plano cuando los recursos están disponibles. Si una tarea consume demasiados recursos del clúster, puede detenerla o pausar hasta que haya menos demanda en el clúster. También puede supervisar y reiniciar los trabajos.

Cuando se introduce un comando que invoca un trabajo, normalmente, el comando le informa de que el trabajo se ha puesto en cola y, a continuación, vuelve al símbolo del sistema de la CLI. Sin embargo, algunos comandos, en su lugar, informan el progreso de los trabajos y no vuelven a símbolo del sistema de la CLI hasta que se completa el trabajo. En estos casos, puede pulsar Ctrl-C para mover el trabajo al fondo.

|===
| Si desea... | Se usa este comando... 


 a| 
Muestra información sobre todos los trabajos
 a| 
`job show`



 a| 
Muestra información sobre los trabajos nodo a nodo
 a| 
`job show bynode`



 a| 
Muestra información acerca de los trabajos afiliados al clúster
 a| 
`job show-cluster`



 a| 
Muestra información sobre los trabajos completados
 a| 
`job show-completed`



 a| 
Muestra información sobre el historial de trabajos
 a| 
`job history show`

Se almacenan hasta 25,000 registros de trabajos para cada nodo del clúster. Por lo tanto, intentar mostrar el historial completo del trabajo puede tardar mucho tiempo. Para evitar tiempos de espera potencialmente largos, debe mostrar trabajos por nodo, máquina virtual de almacenamiento (SVM) o ID de registro.



 a| 
Mostrar la lista de trabajos privados
 a| 
`job private show` (nivel de privilegio avanzado)



 a| 
Muestra información sobre los trabajos privados completados
 a| 
`job private show-completed` (nivel de privilegio avanzado)



 a| 
Muestra información sobre el estado de inicialización de los gestores de trabajos
 a| 
`job initstate show` (nivel de privilegio avanzado)



 a| 
Supervise el progreso de un trabajo
 a| 
`job watch-progress`



 a| 
Supervisar el progreso de un trabajo privado
 a| 
`job private watch-progress` (nivel de privilegio avanzado)



 a| 
Poner en pausa un trabajo
 a| 
`job pause`



 a| 
Poner en pausa un trabajo privado
 a| 
`job private pause` (nivel de privilegio avanzado)



 a| 
Reanudar un trabajo pausado
 a| 
`job resume`



 a| 
Reanudar un trabajo privado en pausa
 a| 
`job private resume` (nivel de privilegio avanzado)



 a| 
Detener un trabajo
 a| 
`job stop`



 a| 
Detener un trabajo privado
 a| 
`job private stop` (nivel de privilegio avanzado)



 a| 
Eliminar un trabajo
 a| 
`job delete`



 a| 
Eliminar un trabajo privado
 a| 
`job private delete` (nivel de privilegio avanzado)



 a| 
Desasociar un trabajo afiliado al clúster con un nodo no disponible que lo posea, de forma que otro nodo pueda hacerse cargo de ese trabajo
 a| 
`job unclaim` (nivel de privilegio avanzado)

|===
[NOTE]
====
Puede utilizar el `event log show` comando para determinar el resultado de un trabajo completado.

====
.Información relacionada
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Comandos de ONTAP 9"^]
