---
permalink: system-admin/commands-manage-system-time-reference.html 
sidebar: sidebar 
keywords: command, manage, cluster, time, ntp, server, date, ntp, time, manually 
summary: Se utilizan los comandos del servidor ntp de hora del clúster para gestionar los servidores NTP para el clúster. Debe utilizar los comandos de fecha del clúster para gestionar la hora del clúster de forma manual. 
---
= Comandos para gestionar la hora del clúster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilice la `cluster time-service ntp server` Comandos para gestionar los servidores NTP para el clúster. Utilice la `cluster date` comandos para gestionar la hora del clúster de forma manual.

A partir de ONTAP 9.5, puede configurar el servidor NTP con autenticación simétrica.

Los siguientes comandos permiten gestionar los servidores NTP para el clúster:

|===
| Si desea... | Se usa este comando... 


 a| 
Asocie el clúster con un servidor NTP externo sin autenticación simétrica
 a| 
`cluster time-service ntp server create -server server_name`



 a| 
Asocie el clúster con un servidor NTP externo con autenticación simétrica. Disponibilidad en ONTAP 9.5 o posterior
 a| 
`cluster time-service ntp server create -server server_ip_address -key-id key_id`

[NOTE]
====
La `key_id` debe hacer referencia a una clave compartida existente configurada con ''clave ntp de servicio de tiempo del clúster'.

====


 a| 
Habilitar autenticación simétrica para un servidor NTP existente se puede modificar el servidor NTP existente para habilitar la autenticación agregando el Id. De clave requerido

Disponible en ONTAP 9.5 o posterior
 a| 
`cluster time-service ntp server modify -server server_name -key-id key_id`



 a| 
Deshabilitar la autenticación simétrica
 a| 
`cluster time-service ntp server modify -server server_name -is-authentication-enabled false`



 a| 
Configure una clave NTP compartida
 a| 
`cluster time-service ntp key create -id shared_key_id -type shared_key_type -value shared_key_value`

[NOTE]
====
Las claves compartidas se refieren a un ID. El ID, su tipo y el valor deben ser idénticos tanto en el nodo como en el servidor NTP

====


 a| 
Muestra información sobre los servidores NTP asociados con el clúster
 a| 
`cluster time-service ntp server show`



 a| 
Modifique la configuración de un servidor NTP externo asociado con el clúster
 a| 
`cluster time-service ntp server modify`



 a| 
Disocie un servidor NTP del clúster
 a| 
`cluster time-service ntp server delete`



 a| 
Restablezca la configuración borrando la asociación de todos los servidores NTP externos con el clúster
 a| 
`cluster time-service ntp server reset`

[NOTE]
====
Este comando requiere el nivel de privilegio avanzado.

====
|===
Los siguientes comandos le permiten gestionar la hora del clúster de forma manual:

|===
| Si desea... | Se usa este comando... 


 a| 
Configure o modifique la zona horaria, la fecha y la hora
 a| 
`cluster date modify`



 a| 
Muestre la configuración de la zona horaria, la fecha y la hora del clúster
 a| 
`cluster date show`

|===
.Información relacionada
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Comandos de ONTAP 9"^]
