---
permalink: system-admin/commands-manage-audit-settings-reference.html 
sidebar: sidebar 
keywords: command, manage, audit, settings, management, activity 
summary: Los comandos de auditoría de seguridad se utilizan para gestionar las actividades de administración que se han iniciado sesión en el archivo audit.log. Los comandos cluster log-reforwarding se utilizan para gestionar destinos a los que se debe reenviar el registro de auditoría a. 
---
= Comandos para gestionar la configuración de auditoría para actividades de gestión
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los `security audit` comandos se utilizan para gestionar las actividades de gestión que se han registrado en `audit.log` el archivo. Se usan `cluster log-forwarding` los comandos para gestionar los destinos para reenviar el registro de auditoría a.

|===
| Si desea... | Se usa este comando... 


 a| 
Especifique que las solicitudes GET de la interfaz de línea de comandos de ONTAP o las API se deben registrar en el registro de auditoría ( `audit.log`el archivo), además de las solicitudes SET predeterminadas
 a| 
`security audit modify`



 a| 
Muestre la configuración del registro de auditoría
 a| 
`security audit show`



 a| 
Muestra las entradas de auditoría combinadas de varios nodos en el clúster
 a| 
`security audit log show`



 a| 
Especifique un destino de reenvío para el registro de auditoría y las medidas de seguridad para la transmisión
 a| 
`cluster log-forwarding create`



 a| 
Modificar un destino para el registro de auditoría
 a| 
`cluster log-forwarding modify`



 a| 
Eliminar un destino del registro de auditoría
 a| 
`cluster log-forwarding delete`



 a| 
Muestra los destinos configurados para el registro de auditoría
 a| 
`cluster log-forwarding show`

|===
.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/["Referencia de comandos del ONTAP"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=cluster+log-forwarding["reenvío de registros del clúster"^]

