---
permalink: system-admin/configure-discovery-cluster-management-switches-task.html 
sidebar: sidebar 
keywords: configuring, discovery, cluster, management, network, switches, cisco, discovery, protocol, cdp, switch, health 
summary: 'El monitor de estado del switch de clúster intenta automáticamente detectar los switches de red de gestión y clúster mediante el protocolo de detección de Cisco (CDP). Debe configurar el monitor de estado si no puede detectar automáticamente un switch o si no desea usar CDP para la detección automática.' 
---
= Configurar la detección de switches de red de gestión y clústeres
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El monitor de estado del switch de clúster intenta automáticamente detectar los switches de red de gestión y clúster mediante el protocolo de detección de Cisco (CDP). Debe configurar el monitor de estado si no puede detectar automáticamente un switch o si no desea usar CDP para la detección automática.

.Acerca de esta tarea
La `system cluster-switch show` el comando enumera los switches que detectó el monitor de estado. Si no ve un switch que esperaba ver en esa lista, el monitor de estado no podrá detectarlo automáticamente.

.Pasos
. Si desea utilizar CDP para la detección automática, haga lo siguiente:
+
.. Asegúrese de que el protocolo de descubrimiento de Cisco (CDP) está habilitado en los switches.
+
Consulte la documentación de su switch para obtener instrucciones.

.. Ejecute el siguiente comando en cada nodo del clúster para verificar si CDP está habilitado o deshabilitado:
+
`*run -node _node_name_ -command options cdpd.enable*`

+
Si CDP está habilitado, vaya al paso d. Si CDP está desactivado, vaya al paso c.

.. Ejecute el siguiente comando para habilitar CDP:
+
`*run -node _node_name_ -command options cdpd.enable on*`

+
Espere cinco minutos antes de pasar al siguiente paso.

.. Utilice la `system cluster-switch show` Para verificar si ONTAP ahora puede detectar automáticamente los switches.


. Si el monitor de estado no puede detectar automáticamente un switch, use el `system cluster-switch create` comando para configurar la detección del switch:
+
[listing]
----
cluster1::> system cluster-switch create -device switch1 -address 192.0.2.250 -snmp-version SNMPv2c -community cshm1! -model NX5020 -type cluster-network
----
+
Espere cinco minutos antes de pasar al siguiente paso.

. Utilice la `system cluster-switch show` Comando para verificar que ONTAP puede detectar el switch al que ha añadido información.


.Después de terminar
Compruebe que el monitor de estado puede supervisar los switches.
