---
permalink: system-admin/create-banner-task.html 
sidebar: sidebar 
keywords: create, banner, svm, access, cluster, ssh, session 
summary: Puede crear un banner para mostrar un mensaje para una persona que intente acceder al clúster o a la SVM en una consola o una sesión SSH. 
---
= Cree un banner de inicio de sesión de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear un banner para que muestre un mensaje a alguien que intente acceder al clúster o a una SVM. El banner se muestra en una sesión de consola (solo para el acceso al clúster) o una sesión SSH (para el acceso a clústeres o SVM) antes de que se pida al usuario que realice la autenticación.

.Pasos
. Utilice la `security login banner modify` Comando para crear un banner para el clúster o la SVM:
+
|===
| Si desea... | Realice lo siguiente... 


 a| 
Especifique un mensaje que sea una sola línea
 a| 
Utilice el `-message`[.code]``<text>`` parámetro «» para especificar el texto.



 a| 
Incluya nuevas líneas (también conocidas como fin de líneas) en el mensaje
 a| 
Utilice el comando sin el `-message` o. `-uri` parámetro para iniciar el modo interactivo de edición del banner.



 a| 
Cargue el contenido de una ubicación para usarlo como banner
 a| 
Utilice la `-uri` Parámetro para especificar la ubicación FTP o HTTP del contenido.

|===
+
El tamaño máximo de un banner es de 2,048 bytes, incluidas las líneas nuevas.

+
Un banner creado mediante el `-uri` el parámetro es estático. No se actualiza automáticamente para reflejar los cambios posteriores del contenido de origen.

+
El banner creado para el clúster también se muestra para todas las SVM que no tienen un banner existente. Cualquier banner creado posteriormente para una SVM anula el banner a nivel de clúster de esa SVM. Especifique el `-message` parámetro con un guión entre comillas dobles (`"-"`) Para que la SVM restablece la SVM para usar el banner a nivel de clúster.

. Verifique que el banner se haya creado mostrándolo con el `security login banner show` comando.
+
Especifique el `-message` parámetro con una cadena vacía (`""`) muestra banners que no tienen contenido.

+
Especifique el `-message` parámetro con `"-"` Muestra todas las SVM (administrador o datos) que no tienen un banner configurado.



.Ejemplos de creación de banners
En el siguiente ejemplo se utiliza el modo no interactivo para crear un banner para el clúster "'cluster1'":

[listing]
----
cluster1::> security login banner modify -message "Authorized users only!"

cluster1::>
----
En el siguiente ejemplo se usa el modo interactivo para crear un banner para la `svm1` SVM:

[listing]
----
cluster1::> security login banner modify -vserver svm1

Enter the message of the day for Vserver "svm1".
Max size: 2048. Enter a blank line to terminate input. Press Ctrl-C to abort.
0        1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
The svm1 SVM is reserved for authorized users only!


cluster1::>
----
El siguiente ejemplo muestra los banners que se han creado:

[listing]
----
cluster1::> security login banner show
Vserver: cluster1
Message
-----------------------------------------------------------------------------
Authorized users only!

Vserver: svm1
Message
-----------------------------------------------------------------------------
The svm1 SVM is reserved for authorized users only!

2 entries were displayed.

cluster1::>
----
.Información relacionada
xref:manage-banner-reference.adoc[Gestión del banner]
