---
permalink: system-admin/different-shells-cli-commands-concept.html 
sidebar: sidebar 
keywords: diag, secd, different, shells, cli, commands, cluster, administrators, clustershell, nodeshell, systemshell 
summary: El clúster tiene tres shell distintos para los comandos de la CLI, el clustershell, el nodesinfierno y el systemshell. Los shells son para propósitos diferentes, y cada uno tiene un conjunto de comandos diferente. 
---
= Acerca de los distintos shell para los comandos de la CLI (solo administradores de clúster)
:allow-uri-read: 


[role="lead"]
El clúster tiene tres shell diferentes para los comandos de la CLI, el _clustershell_, el _nodeshell_ y el _systemshell_. Los shells son para propósitos diferentes, y cada uno tiene un conjunto de comandos diferente.

* Clustershell es el shell nativo que se inicia automáticamente cuando se inicia sesión en el clúster.
+
Se proporcionan todos los comandos que necesita para configurar y gestionar el clúster. La ayuda de la CLI de clustershell (activada por `?` en el símbolo del sistema de clustershell) muestra los comandos de clustershell disponibles.  `man`El comando en clustershell muestra la página man para el comando clustershell especificado (`man <command_name>`). Obtenga más información sobre `man` en el link:https://docs.netapp.com/us-en/ontap-cli/man.html["Referencia de comandos del ONTAP"^].

* El nodesinfierno es un shell especial para comandos que sólo tienen efecto a nivel de nodo.
+
Se puede acceder al infierno de `system node run` la nariz a través del comando. Obtenga más información sobre `system node run` en el link:https://docs.netapp.com/us-en/ontap-cli/system-node-run.html["Referencia de comandos del ONTAP"^].

+
La ayuda de la CLI de nodeshell (activada por `?` o `help` en la indicación de nodeshell) muestra comandos de nodeshell disponibles. El `man` comando del infierno de nodos muestra la página man para el comando nodeshell especificado.

+
Muchos comandos y opciones de nodeshell utilizados comúnmente se tunean o se alian en el clustershell y pueden ejecutarse también desde el clustershell.

* El shell del sistema es un shell de bajo nivel que se utiliza sólo para fines de diagnóstico y solución de problemas.
+
El systemshell y la cuenta asociada `diag` están pensados para fines de diagnóstico de bajo nivel. Su acceso requiere el nivel de privilegio de diagnóstico y se reserva únicamente para que el soporte técnico realice tareas de solución de problemas.



Obtenga más información sobre los comandos descritos en este procedimiento en el link:https://docs.netapp.com/us-en/ontap-cli/["Referencia de comandos del ONTAP"^].
