---
permalink: system-admin/display-nodeshell-commands-task.html 
sidebar: sidebar 
keywords: display, nodeshell, command, cli, list, help 
summary: Puede obtener una lista de los comandos nodeshell disponibles utilizando la ayuda de la CLI de nodeshell. 
---
= Mostrar los comandos nodeshell disponibles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede obtener una lista de los comandos nodeshell disponibles utilizando la ayuda de la CLI de nodeshell.

.Pasos
. Para acceder a nodeshell, introduzca el siguiente comando en el símbolo del sistema del clustershell:
+
`*system node run -node {_nodename_|local}*`

+
`local` es el nodo que utilizó para acceder al clúster.

+
[NOTE]
====
La `system node run` el comando tiene un comando de alias, `run`.

====
. Introduzca el siguiente comando en el nodeshell para ver la lista de comandos nodeshell disponibles:
+
`*[_commandname_] help*`

+
 `_commandname_` es el nombre del comando cuya disponibilidad desea mostrar. Si no incluye `_commandname_`, La CLI muestra todos los comandos nodeshell disponibles.

+
Introduzca `exit` O bien escriba Ctrl-d para volver a la CLI del clustershell.



.Ejemplo de visualización de comandos nodeshell disponibles
En el ejemplo siguiente se accede al nodo nodesinfierno de un nodo llamado 2 y se muestra información sobre el comando nodeshell `environment`:

[listing]
----
cluster1::> system node run -node node2
Type 'exit' or 'Ctrl-D' to return to the CLI

node2> environment help
Usage: environment status |
     [status] [shelf [<adapter>[.<shelf-number>]]] |
     [status] [shelf_log] |
     [status] [shelf_stats] |
     [status] [shelf_power_status] |
     [status] [chassis [all | list-sensors | Temperature | PSU 1 |
     PSU 2 | Voltage | SYS FAN | NVRAM6-temperature-3 | NVRAM6-battery-3]]
----