---
permalink: system-admin/display-nodes-cluster-task.html 
sidebar: sidebar 
keywords: display, view, information, node, cluster, name, healthy, epsilon 
summary: Puede mostrar los nombres de nodo, si los nodos están en buen estado y si pueden participar en el clúster. En el nivel de privilegio avanzado, también puede mostrar si un nodo está configurado con épsilon. 
---
= Vea detalles del nivel del nodo en un clúster de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ver los nombres de nodo, si los nodos están en buen estado y si pueden participar en el clúster. En el nivel de privilegio avanzado, también puede mostrar si un nodo está configurado con épsilon.

.Pasos
. Para ver información acerca de los nodos de un clúster, utilice `cluster show` el comando.
+
Si desea que la salida muestre si un nodo está configurado con épsilon, ejecute el comando en el nivel de privilegio avanzado.

+
Obtenga más información sobre `cluster show` en el link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["Referencia de comandos de la ONTAP"^].



.Ejemplos de mostrar los nodos en un clúster
En el siguiente ejemplo se muestra información sobre todos los nodos de un clúster de cuatro nodos:

[listing]
----

cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
node1                 true    true
node2                 true    true
node3                 true    true
node4                 true    true
----
En el siguiente ejemplo, se muestra información detallada acerca del nodo denominado «'1'» en el nivel de privilegio avanzado:

[listing]
----

cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them only when directed to do so by support personnel.
Do you want to continue? {y|n}: y

cluster1::*> cluster show -node node1

       Node: node1
  Node UUID: a67f9f34-9d8f-11da-b484-000423b6f094
    Epsilon: false
Eligibility: true
     Health: true
----