---
permalink: system-admin/download-nlf-task.html 
sidebar: sidebar 
keywords: install, license, convert, download, add, record, software, entitlement, keys, codes, cluster, administrator, nlf, ontap one 
summary: Si su sistema ejecuta ONTAP 9.10.1 o una versión posterior, puede actualizar los archivos de licencia o las claves de licencia de 28 caracteres en los sistemas existentes descargando NLF para ONTAP One o ONTAP Core desde el sitio de soporte de NetApp. 
---
= Descargue los archivos de licencia de NetApp (NLF) desde el sitio de soporte de NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si el sistema ejecuta ONTAP 9.10.1 o una versión posterior, puede actualizar los archivos de licencia del paquete en los sistemas existentes descargando NLF para ONTAP One o ONTAP Core desde el sitio de soporte de NetApp.


NOTE: Las licencias de cloud de SnapMirror y SnapMirror S3 no se incluyen con ONTAP One. Son parte del paquete de compatibilidad ONTAP One, que puede obtener de forma gratuita si tiene ONTAP One y link:../data-protection/install-snapmirror-cloud-license-task.html["solicite por separado"].

.Pasos
Puede descargar archivos de licencia de ONTAP One para sistemas con paquetes de archivos de licencia de NetApp existentes y para sistemas con claves de licencia de 28 caracteres que se han convertido a archivos de licencia de NetApp en sistemas que ejecutan ONTAP 9.10.1 y versiones posteriores. Por un cargo, también puede actualizar los sistemas de la base ONTAP a ONTAP One.

[role="tabbed-block"]
====
.Actualice NLF existente
--
. Póngase en contacto con su equipo de ventas de NetApp y solicite el paquete de archivos de licencia que desee actualizar o convertir (por ejemplo, ONTAP Base to ONTAP One o el paquete central y el paquete de protección de datos a ONTAP One).
+
Cuando se procese su solicitud, recibirá un correo electrónico de netappsw@netapp.com con el asunto «Notificación de licencias de software de NetApp para el n.o de SO [número de SO]» y el correo electrónico incluirá un archivo adjunto en PDF que incluya el número de serie de su licencia.

. Inicie sesión en la link:https://mysupport.netapp.com/site/["Sitio de soporte de NetApp"^].
. Selecciona *Sistemas > Licencias de software*.
. En el menú, elija *Número de serie*, ingrese el número de serie que recibió y haga clic en *Nueva búsqueda*.
. Localice el paquete de licencias que desea convertir.
. Haga clic en *Obtener archivo de licencia de NetApp* para cada paquete de licencia y descargue los NLF cuando estén disponibles.
. link:../system-admin/install-license-task.html["Instale"] El archivo ONTAP One.


--
.Actualizar NLF convertido desde clave de licencia
--
. Inicie sesión en la link:https://mysupport.netapp.com/site/["Sitio de soporte de NetApp"^].
. Selecciona *Sistemas > Licencias de software*.
. En el menú, elija *Número de serie*, ingrese el número de serie del sistema y haga clic en *Nueva búsqueda*.
. Localice la licencia que desea convertir, y en la columna *Elegibilidad* haga clic en *Comprobar*.
. En el formulario *Comprobar elegibilidad*, haz clic en *Generar licencias para 9,10.x y posteriores*.
. Cierre el formulario *Comprobar elegibilidad*.
+
Tendrá que esperar al menos 2 horas para que se generen las licencias.

. Repita los pasos 1 a 3.
. Busque la licencia de ONTAP One, haga clic en *Obtener archivo de licencia de NetApp* y elija el método de entrega.
. link:../system-admin/install-license-task.html["Instale"] El archivo ONTAP One.


--
====