---
permalink: system-admin/enable-sp-bmc-automatic-network-config-task.html 
sidebar: sidebar 
keywords: enable, sp, bmc, automatic, network, configuration 
summary: Habilitar el SP para utilizar la configuración de red automática es preferible de configurar manualmente la red del SP. Dado que la configuración de red automática del SP es de todo el clúster, no es necesario que gestione manualmente la red del SP para nodos individuales. 
---
= Habilitar la configuración de red automática ONTAP SP/BMC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Habilitar el SP para utilizar la configuración de red automática es preferible de configurar manualmente la red del SP. Dado que la configuración de red automática del SP es de todo el clúster, no es necesario que gestione manualmente la red del SP para nodos individuales.

[NOTE]
====
Esta tarea se aplica tanto al SP como al BMC.

====
* La subred que desea utilizar para la configuración de red automática del SP ya debe estar definida en el clúster y no debe haber conflictos de recursos con la interfaz de red del SP.
+
 `network subnet show`El comando muestra información de subred del clúster.

+
Obtenga más información sobre `network subnet show` en el link:https://docs.netapp.com/us-en/ontap-cli/network-subnet-show.html["Referencia de comandos del ONTAP"^].

+
El parámetro que fuerza la asociación de subred (el `-force-update-lif-associations` parámetro de `network subnet` los comandos) solo se admite en las LIF de red y no en la interfaz de red de SP.

* Si desea utilizar conexiones IPv6 para el SP, IPv6 ya debe estar configurado y habilitado para ONTAP.
+
El `network options ipv6 show` comando muestra el estado actual de IPv6 configuración para ONTAP. Obtenga más información sobre `network options ipv6 show` en el link:https://docs.netapp.com/us-en/ontap-cli/network-options-ipv6-show.html["Referencia de comandos del ONTAP"^].



.Pasos
. Especifique la familia y el nombre de dirección IPv4 o IPv6 de la subred que desea que la SP utilice con `system service-processor network auto-configuration enable` el comando.
. Visualice la configuración de red automática de SP mediante `system service-processor network auto-configuration show` el comando.
. Si posteriormente desea deshabilitar o volver a habilitar la interfaz de red SP IPv4 o IPv6 para todos los nodos que están en quórum, utilice `system service-processor network modify` el comando con `-address-family` [`IPv4`|`IPv6` `-enable` [`true`|`false`los parámetros ] y].
+
Cuando se habilita la configuración de red automática del SP, no es posible modificar la dirección IP de SP para un nodo que está en quórum. Solo puede habilitar o deshabilitar la interfaz de red IPv4 o IPv6 del SP.

+
Si un nodo no tiene quórum, puede modificar la configuración de red SP del nodo, incluida la dirección IP de SP, ejecutando `system service-processor network modify` desde el nodo y confirmando que desea anular la configuración de red automática de SP para el nodo. Sin embargo, cuando el nodo se une al quórum, la reconfiguración automática del SP se lleva a cabo para el nodo según la subred especificada.


