---
permalink: system-admin/example-responding-degraded-system-health-concept.html 
sidebar: sidebar 
keywords: respond, degraded, system, health, node, cli 
summary: Al revisar un ejemplo específico de estado del sistema degradado causado por una bandeja que carece de dos rutas a un nodo, puede ver lo que muestra la CLI cuando responde a una alerta. 
---
= Ejemplo de respuesta al estado degradado del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al revisar un ejemplo específico de estado del sistema degradado causado por una bandeja que carece de dos rutas a un nodo, puede ver lo que muestra la CLI cuando responde a una alerta.

Después de iniciar ONTAP, compruebe el estado del sistema y detecte que el estado es degradado:

[listing]
----

      cluster1::>system health status show
        Status
        ---------------
        degraded
----
Muestra las alertas para averiguar dónde está el problema y ver que la bandeja 2 no tiene dos rutas al nodo 1:

[listing]
----

      cluster1::>system health alert show
               Node: node1
           Resource: Shelf ID 2
           Severity: Major
	   Indication Time: Mon Nov 10 16:48:12 2013
     Probable Cause: Disk shelf 2 does not have two paths to controller
                     node1.
    Possible Effect: Access to disk shelf 2 via controller node1 will be
                     lost with a single hardware component failure (e.g.
                     cable, HBA, or IOM failure).
 Corrective Actions: 1. Halt controller node1 and all controllers attached to disk shelf 2.
                     2. Connect disk shelf 2 to controller node1 via two paths following the rules in the Universal SAS and ACP Cabling Guide.
                     3. Reboot the halted controllers.
                     4. Contact support personnel if the alert persists.
----
Se muestran detalles de la alerta para obtener más información, incluido el ID de alerta:

[listing]
----

      cluster1::>system health alert show -monitor node-connect -alert-id DualPathToDiskShelf_Alert -instance
                  Node: node1
               Monitor: node-connect
              Alert ID: DualPathToDiskShelf_Alert
     Alerting Resource: 50:05:0c:c1:02:00:0f:02
             Subsystem: SAS-connect
       Indication Time: Mon Mar 21 10:26:38 2011
    Perceived Severity: Major
        Probable Cause: Connection_establishment_error
           Description: Disk shelf 2 does not have two paths to controller node1.
    Corrective Actions: 1. Halt controller node1 and all controllers attached to disk shelf 2.
                        2. Connect disk shelf 2 to controller node1 via two paths following the rules in the Universal SAS and ACP Cabling Guide.
                        3. Reboot the halted controllers.
                        4. Contact support personnel if the alert persists.
       Possible Effect: Access to disk shelf 2 via controller node1 will be lost with a single
 hardware component failure (e.g. cable, HBA, or IOM failure).
           Acknowledge: false
              Suppress: false
                Policy: DualPathToDiskShelf_Policy
          Acknowledger: -
            Suppressor: -
Additional Information: Shelf uuid: 50:05:0c:c1:02:00:0f:02
                        Shelf id: 2
                        Shelf Name: 4d.shelf2
                        Number of Paths: 1
                        Number of Disks: 6
                        Adapter connected to IOMA:
                        Adapter connected to IOMB: 4d
Alerting Resource Name: Shelf ID 2
----
Reconoce la alerta para indicar que está trabajando en ella.

[listing]
----

      cluster1::>system health alert modify -node node1 -alert-id DualPathToDiskShelf_Alert -acknowledge true
----
Fije el cableado entre la bandeja 2 y la nodo 1 y, a continuación, reinicie el sistema. Luego, vuelva a comprobar el estado del sistema y compruebe que el estado es `OK`:

[listing]
----

      cluster1::>system health status show
        Status
        ---------------
        OK
----