---
permalink: system-admin/files-sent-event-triggered-autosupport-messages-concept.html 
sidebar: sidebar 
keywords: files, event, triggered, autosupport, message, troubleshoot, subsystem, problem 
summary: Los mensajes AutoSupport activados por eventos sólo contienen información básica y de solución de problemas de subsistemas asociados al evento que provocó que AutoSupport genere el mensaje. Los datos específicos ayudan a los partners de soporte y soporte de NetApp a solucionar el problema. 
---
= Archivos enviados en mensajes AutoSupport activados por eventos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los mensajes AutoSupport activados por eventos sólo contienen información básica y de solución de problemas de subsistemas asociados al evento que provocó que AutoSupport genere el mensaje. Los datos específicos ayudan a los partners de soporte y soporte de NetApp a solucionar el problema.

AutoSupport utiliza los siguientes criterios para controlar el contenido de los mensajes de AutoSupport activados por un evento:

* Qué subsistemas están incluidos
+
Los datos se agrupan en subsistemas, incluidos subsistemas comunes, como los archivos de registro y subsistemas específicos, como RAID. Cada evento activa un mensaje que sólo contiene los datos de subsistemas específicos.

* El nivel de detalle de cada subsistema incluido
+
Los datos de cada subsistema incluido se proporcionan a nivel básico o de resolución de problemas.



Puede ver todos los eventos posibles y determinar qué subsistemas se incluyen en los mensajes acerca de cada evento mediante el `system node autosupport trigger show` con el `-instance` parámetro.

Además de los subsistemas incluidos de forma predeterminada para cada evento, puede agregar subsistemas adicionales en un nivel básico o de solución de problemas mediante el `system node autosupport trigger modify` comando.
