---
permalink: system-admin/find-config-recover-cluster-task.html 
sidebar: sidebar 
keywords: cluster, configuration, recover, node, backup, file 
summary: Utiliza la configuración desde un nodo del clúster o un archivo de backup de configuración de clústeres para recuperar un clúster. 
---
= Localice el archivo de backup de configuración del clúster de ONTAP para restaurar un clúster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utiliza la configuración desde un nodo del clúster o un archivo de backup de configuración de clústeres para recuperar un clúster.

.Pasos
. Seleccione un tipo de configuración para recuperar el clúster.
+
** Un nodo en el clúster
+
Si el clúster consta de más de un nodo y uno de los nodos tiene una configuración de clúster desde cuando el clúster estaba en la configuración deseada, entonces puede recuperar el clúster mediante la configuración almacenada en ese nodo.

+
En la mayoría de los casos, el nodo que contiene el anillo de replicación con el identificador de transacción más reciente es el mejor nodo que se puede usar para restaurar la configuración de clúster. La `cluster ring show` el comando en el nivel de privilegio avanzado le permite ver una lista de los anillos replicados disponibles en cada nodo del clúster.

** Un archivo de copia de seguridad de configuración de clúster
+
Si no puede identificar un nodo con la configuración de clúster correcta o si el clúster consta de un único nodo, puede utilizar un archivo de backup de configuración de clúster para recuperar el clúster.

+
Si va a recuperar el clúster a partir de un archivo de copia de seguridad de configuración, se perderán todos los cambios de configuración realizados desde que se realizó la copia de seguridad. Debe resolver las discrepancias entre el archivo de copia de seguridad de la configuración y la actual después de la recuperación. Consulte el artículo de Knowledge base link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/ONTAP_Configuration_Backup_Resolution_Guide["Guía de resolución de backups de configuración de ONTAP"] para obtener orientación sobre la solución de problemas.



. Si decide utilizar un archivo de copia de seguridad de configuración de clúster, haga que el archivo esté disponible para el nodo que planea utilizar para recuperar el clúster.
+
|===
| Si el archivo de copia de seguridad de configuración se encuentra... | Realice lo siguiente... 


 a| 
En una URL remota
 a| 
Utilice la `system configuration backup download` en el nivel de privilegio avanzado para descargarlo en el nodo en recuperación.



 a| 
En un nodo del clúster
 a| 
.. Utilice la `system configuration backup show` comando en el nivel de privilegio avanzado para encontrar un archivo de backup de configuración de clúster que se creó cuando el clúster estaba en la configuración deseada.
.. Si el archivo de backup de configuración del clúster no se encuentra en el nodo que planea utilizar para recuperar el clúster, utilice el `system configuration backup copy` para copiarla en el nodo en recuperación.


|===

