---
permalink: system-admin/find-config-backup-file-recovering-node-task.html 
sidebar: sidebar 
keywords: configuration, backup, file, recovering, node, remote, url, cluster 
summary: Para recuperar una configuración de nodo, se utiliza un archivo de backup de configuración ubicado en una URL remota o en un nodo del clúster. 
---
= Localice el archivo de backup de configuración del nodo ONTAP para restaurar un nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para recuperar una configuración de nodo, se utiliza un archivo de backup de configuración ubicado en una URL remota o en un nodo del clúster.

.Acerca de esta tarea
Puede usar un archivo de backup de configuración de clúster o nodo para restaurar una configuración de nodos.

.Paso
. Haga que el archivo de copia de seguridad de configuración esté disponible en el nodo para el que necesita restaurar la configuración.
+
|===
| Si el archivo de copia de seguridad de configuración se encuentra... | Realice lo siguiente... 


 a| 
En una URL remota
 a| 
Utilice `system configuration backup download` el comando en el nivel de privilegio avanzado para descargarlo en el nodo de recuperación.



 a| 
En un nodo del clúster
 a| 
.. Utilice `system configuration backup show` el comando en el nivel de privilegio avanzado para ver la lista de archivos de copia de seguridad de configuración disponibles en el clúster que contiene la configuración del nodo de recuperación.
.. Si el archivo de copia de seguridad de configuración que identifica no existe en el nodo de recuperación, utilice el `system configuration backup copy` comando para copiarlo en el nodo de recuperación.


|===
+
Si anteriormente volvió a crear el clúster, debe elegir un archivo de backup de configuración que se creó después de la recreación del clúster. Si debe utilizar un archivo de backup de configuración que se creó antes de la recreación de clúster, después de recuperar el nodo, debe volver a crear el clúster.


