---
permalink: system-admin/free-space-node-root-volume-task.html 
sidebar: sidebar 
keywords: free, space, node, root, volume, full, delete, file, core, dump 
summary: Aparece un mensaje de advertencia cuando el volumen raíz de un nodo está lleno o casi lleno. El nodo no puede funcionar correctamente cuando su volumen raíz está lleno. Puede liberar espacio en el volumen raíz de un nodo eliminando archivos de volcado principales, archivos de seguimiento de paquetes y copias Snapshot de volumen raíz. 
---
= Libere espacio en el volumen raíz de un nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aparece un mensaje de advertencia cuando el volumen raíz de un nodo se ha lleno o casi lleno. El nodo no puede funcionar correctamente cuando su volumen raíz está lleno. Puede liberar espacio en el volumen raíz de un nodo si elimina los archivos de volcado principales, los archivos de seguimiento de paquetes y las copias Snapshot de volumen raíz.

.Pasos
. Muestre los archivos de volcado principales del nodo y sus nombres mediante el `system node coredump show` comando.
. Elimine los archivos de volcado de memoria no deseados del nodo mediante el `system node coredump delete` comando.
. Accede a la Nodesinfierno:
+
`*system node run -node _nodename_*`

+
`_nodename_` es el nombre del nodo cuyo espacio del volumen raíz desea liberar.

. Cambie al nivel de privilegio avanzado nodesinfierno desde el nodesinfierno:
+
`*priv set advanced*`

. Mostrar y eliminar los archivos de seguimiento de paquetes del nodo a través de nodeshell:
+
.. Muestre todos los archivos del volumen raíz del nodo:
+
`*ls /etc*`

.. Si hay archivos de seguimiento de paquetes (`*.trc`) se encuentran en el volumen raíz del nodo, elimínelos de forma individual:
+
`*rm /etc/log/packet_traces/_file_name.trc_*`



. Identificar y eliminar las copias snapshot del volumen raíz del nodo a través del infierno:
+
.. Identifique el nombre del volumen raíz:
+
`*vol status*`

+
El volumen raíz se indica mediante la palabra «'root'» de la columna «'Options'» de la `vol status` resultado del comando.

+
En el siguiente ejemplo, el volumen raíz es `vol0`:

+
[listing]
----
node1*> vol status

         Volume State           Status            Options
           vol0 online          raid_dp, flex     root, nvfail=on
                                64-bit
----
.. Mostrar copias Snapshot de volumen raíz:
+
`*snap list root_vol_name*`

.. Elimine las copias Snapshot de volumen raíz que no desee:
+
`*snap delete root_vol_namesnapshot_name*`



. Salga de nodeshell y vuelva al clustershell:
+
`*exit*`


