---
permalink: system-admin/generate-certificate-signing-request-cluster-task.html 
sidebar: sidebar 
keywords: generate, certificate, sign, request, cluster, csr, ca 
summary: 'Es posible utilizar el comando Security certificate generate-csr para generar una solicitud de firma de certificación (CSR). Después de procesar la solicitud, la entidad de certificación (CA) envía el certificado digital firmado.' 
---
= Genere una solicitud de firma de certificación para el clúster en ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el certificado de seguridad `generate-csr` Comando para generar una solicitud de firma de certificación (CSR). Después de procesar la solicitud, la entidad de certificación (CA) envía el certificado digital firmado.

.Antes de empezar
Debe ser un administrador de clúster o un administrador de SVM para ejecutar esta tarea.

.Pasos
. Genere una CSR:
+
`*security certificate generate-csr -common-name _FQDN_or_common_name_ -size 512|1024|1536|2048 -country _country_ -state _state_ -locality _locality_ -organization _organization_ -unit _unit_ -email-addr _email_of_contact_ -hash-function SHA1|SHA256|MD5*`

+
Obtenga más información sobre `security certificate generate-csr` en el link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-generate-csr.html["Referencia de comandos de la ONTAP"^].

+
El siguiente comando crea una CSR con una clave privada de 2,048 bits generada por la función de hashing SHA256 para que la utilice el grupo Software del departamento DE TI de una empresa cuyo nombre común personalizado es server1.companyname.com, ubicado en Sunnyvale, California, EE. UU. La dirección de correo electrónico del administrador de contacto de la SVM es \web@example.com. El sistema muestra la CSR y la clave privada en la salida.

+
[listing]
----
cluster1::>security certificate generate-csr -common-name
server1.companyname.com -size 2048 -country US -state California -
locality Sunnyvale -organization IT -unit Software -email-addr
web@example.com -hash-function SHA256
Certificate Signing Request :
-----BEGIN CERTIFICATE REQUEST-----
<certificate_value>
-----END CERTIFICATE REQUEST-----
Private Key :
24 | Administrator Authentication and RBAC
-----BEGIN RSA PRIVATE KEY-----
<key_value>
-----END RSA PRIVATE KEY-----
Note: Please keep a copy of your certificate request and private key
for future reference.
----
. Copie la solicitud de certificado de la salida CSR y envíela en formato electrónico (por ejemplo, correo electrónico) a una CA de terceros de confianza para su firma.
+
Después de procesar la solicitud, la CA envía el certificado digital firmado. Debe conservar una copia de la clave privada y el certificado digital firmado por la CA.


