---
permalink: system-admin/health-monitors-concept.html 
sidebar: sidebar 
keywords: available, cluster, health, monitors, errors, detect, events, alerts, delete 
summary: Existen varios monitores de estado que supervisan diferentes partes de un clúster. Los monitores de estado le ayudan a recuperarse de errores en sistemas ONTAP mediante la detección de eventos, el envío de alertas a usted y la eliminación de eventos según los borre. 
---
= Obtenga información sobre las supervisiones de estado del clúster de ONTAP disponibles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existen varios monitores de estado que supervisan diferentes partes de un clúster. Los monitores de estado le ayudan a recuperarse de errores en sistemas ONTAP mediante la detección de eventos, el envío de alertas a usted y la eliminación de eventos según los borre.

|===
| Nombre del monitor de estado (identificador) | Nombre del subsistema (identificador) | Específico 


 a| 
Switch Ethernet
 a| 
Switch (Switch-Health)
 a| 
El monitor de estado del switch Ethernet (CSHM) de ONTAP supervisa el estado de los switches de clúster y de red de almacenamiento mientras recoge registros para el análisis. De forma predeterminada, CSHM sondea cada switch a través de SNMPv2c cada 5 minutos para actualizar las tablas de recursos con información sobre compatibilidad, estado de monitoreo, sensores de temperatura, uso de CPU, configuraciones y conexiones de interfaz, redundancia de los switches de cluster y operaciones de fuente de alimentación y ventilador. Además, si está configurado, CSHM recopila registros a través de SSH/SCP cada hora, que se envían a través de AutoSupport para su posterior análisis. A petición, CSHM también puede realizar una recopilación de registros de soporte técnico más detallada utilizando SSH/SCP.

Consulte link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-cshm/config-overview.html["Supervisión del estado del switch"^] para obtener más información.



 a| 
Estructura MetroCluster
 a| 
Conmutador
 a| 
Supervisa la topología de la estructura del back-end de la configuración de MetroCluster y detecta mala configuración como el cableado y la división en zonas incorrectas y los fallos de ISL.



 a| 
MetroCluster Salud
 a| 
Interconexión, RAID y almacenamiento
 a| 
Supervisa los adaptadores FC-VI, los adaptadores del iniciador FC, los agregados y discos subyacentes y los puertos entre clústeres



 a| 
Conectividad de nodo (conexión por nodo)
 a| 
Operaciones no disruptivas de CIFS (CIFS-NDO)
 a| 
Supervisa conexiones SMB para proporcionar operaciones no disruptivas a aplicaciones de Hyper-V.



 a| 
Almacenamiento (conexión SAS)
 a| 
Supervisa las bandejas, los discos y los adaptadores a nivel de nodo para obtener las rutas y conexiones adecuadas.



 a| 
Sistema
 a| 
no aplicable
 a| 
Agrega información de otros monitores de estado.



 a| 
Conectividad del sistema (conexión del sistema)
 a| 
Almacenamiento (conexión SAS)
 a| 
Supervisa las bandejas a nivel de clúster para conocer las rutas adecuadas a dos nodos en clúster de alta disponibilidad.

|===