---
permalink: system-admin/health-monitors-concept.html 
sidebar: sidebar 
keywords: available, cluster, health, monitors, errors, detect, events, alerts, delete 
summary: Existen varios monitores de estado que supervisan diferentes partes de un clúster. Los monitores de estado le ayudan a recuperarse de errores en sistemas ONTAP mediante la detección de eventos, el envío de alertas a usted y la eliminación de eventos según los borre. 
---
= Obtenga información sobre las supervisiones de estado del clúster de ONTAP disponibles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existen varios monitores de estado que supervisan diferentes partes de un clúster. Los monitores de estado le ayudan a recuperarse de errores en sistemas ONTAP mediante la detección de eventos, el envío de alertas a usted y la eliminación de eventos según los borre.

|===
| Nombre del monitor de estado (identificador) | Nombre del subsistema (identificador) | Específico 


 a| 
Switch de clúster (switch de clúster)
 a| 
Switch (Switch-Health)
 a| 
Supervisa los switches de red de clúster y los switches de red de gestión para obtener temperatura, utilización, configuración de interfaces, redundancia (solo switches de red de clúster) y funcionamiento de suministro de alimentación y ventilador. El monitor de estado del switch del clúster se comunica con los switches a través de SNMP. SNMPv2c es el valor predeterminado.

[NOTE]
====
A partir de ONTAP 9.2, este monitor puede detectar y generar informes cuando se ha reiniciado un switch de clúster desde el último periodo de sondeo.

====


 a| 
Estructura MetroCluster
 a| 
Conmutador
 a| 
Supervisa la topología de la estructura del back-end de la configuración de MetroCluster y detecta mala configuración como el cableado y la división en zonas incorrectas y los fallos de ISL.



 a| 
MetroCluster Salud
 a| 
Interconexión, RAID y almacenamiento
 a| 
Supervisa los adaptadores FC-VI, los adaptadores del iniciador FC, los agregados y discos subyacentes y los puertos entre clústeres



 a| 
Conectividad de nodo (conexión por nodo)
 a| 
Operaciones no disruptivas de CIFS (CIFS-NDO)
 a| 
Supervisa conexiones SMB para proporcionar operaciones no disruptivas a aplicaciones de Hyper-V.



 a| 
Almacenamiento (conexión SAS)
 a| 
Supervisa las bandejas, los discos y los adaptadores a nivel de nodo para obtener las rutas y conexiones adecuadas.



 a| 
Sistema
 a| 
no aplicable
 a| 
Agrega información de otros monitores de estado.



 a| 
Conectividad del sistema (conexión del sistema)
 a| 
Almacenamiento (conexión SAS)
 a| 
Supervisa las bandejas a nivel de clúster para conocer las rutas adecuadas a dos nodos en clúster de alta disponibilidad.

|===