---
permalink: system-admin/install-ca-signed-server-certificate-cluster-task.html 
sidebar: sidebar 
keywords: install, ca, signed, server, certificate, cluster, ssl, svm, sotrage, virtual, machine, administrator 
summary: 'Para habilitar un servidor SSL que autentique el clúster o la máquina virtual de almacenamiento (SVM) como cliente SSL, se instala un certificado digital con el tipo de cliente en el clúster o la SVM. A continuación, proporcionará el certificado de CA de cliente al administrador del servidor SSL para su instalación en el servidor.' 
---
= Instalar un certificado de servidor firmado por CA para el clúster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para habilitar un servidor SSL que autentique el clúster o la máquina virtual de almacenamiento (SVM) como cliente SSL, se instala un certificado digital con el tipo de cliente en el clúster o la SVM. A continuación, proporcionará el certificado de CA de cliente al administrador del servidor SSL para su instalación en el servidor.

.Antes de empezar
Ya debe haber instalado el certificado raíz del servidor SSL en el clúster o en la SVM con el `server-ca` tipo de certificado.

.Pasos
. Si desea utilizar un certificado digital autofirmado para la autenticación de cliente, utilice `security certificate create` el comando con `type client` el parámetro.
+
Obtenga más información sobre `security certificate create` en el link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-create.html["Referencia de comandos del ONTAP"^].

. Para utilizar un certificado digital firmado por CA para la autenticación de clientes, complete los siguientes pasos:
+
.. Genere una solicitud de firma de certificación (CSR) digital mediante `generate-csr` el comando security certificate.
+
ONTAP muestra el resultado de CSR, que incluye una solicitud de certificado y una clave privada, y le recuerda que debe copiar el resultado en un archivo para futura referencia.

.. Envíe la solicitud de certificado de la salida de CSR en un formulario electrónico (como por ejemplo, correo electrónico) a una CA de confianza para su firma.
+
Debe conservar una copia de la clave privada y el certificado firmado por CA para referencia futura.

+
Después de procesar la solicitud, la CA envía el certificado digital firmado.

.. Instale el certificado firmado por CA mediante `security certificate install` el comando con el `-type client` parámetro.
.. Introduzca el certificado y la clave privada cuando se le solicite y, a continuación, pulse *Intro*.
.. Introduzca cualquier certificado raíz o intermedio adicional cuando se le solicite y, a continuación, pulse *Intro*.
+
Puede instalar un certificado intermedio en el clúster o la SVM si a una cadena de certificados que comienza en la CA raíz de confianza y finaliza con el certificado SSL emitido para usted, le faltan los certificados intermedios. Un certificado intermedio es un certificado subordinado emitido por el raíz de confianza específicamente para emitir certificados de servidor de entidades finales. El resultado es una cadena de certificados que comienza en la CA raíz de confianza, atraviesa el certificado intermedio y termina con el certificado SSL que se le emitió.



. Proporcione `client-ca` el certificado del clúster o SVM al administrador del servidor SSL para su instalación en el servidor.
+
El comando security certificate show con los `-instance` `-type client-ca` parámetros y muestra `client-ca` la información de certificados.



.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["instalación del certificado de seguridad"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-show.html["Mostrar certificado de seguridad"^]

