---
permalink: system-admin/manage-web-services-concept.html 
sidebar: sidebar 
keywords: manage, web, services, svm, storage, virtual, machine, cluster, controler, user 
summary: 'Puede habilitar o deshabilitar un servicio web para el clúster o una máquina virtual de almacenamiento (SVM), mostrar la configuración de los servicios web y controlar si los usuarios de un rol pueden acceder a un servicio web.' 
---
= Información general sobre los servicios web de Manage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar o deshabilitar un servicio web para el clúster o una máquina virtual de almacenamiento (SVM), mostrar la configuración de los servicios web y controlar si los usuarios de un rol pueden acceder a un servicio web.

Puede gestionar los servicios web para el clúster o una SVM de las siguientes formas:

* Activación o desactivación de un servicio Web específico
* Especificar si el acceso a un servicio Web está restringido a sólo HTTP (SSL) cifrado
* Mostrar la disponibilidad de los servicios web
* Permitir o rechazar a los usuarios de una función acceder a un servicio web
* Mostrar los roles que pueden tener acceso a un servicio Web


Para que un usuario pueda acceder a un servicio web, se deben cumplir todas las siguientes condiciones:

* Se debe autenticar al usuario.
+
Por ejemplo, un servicio Web puede solicitar un nombre de usuario y una contraseña. La respuesta del usuario debe coincidir con una cuenta válida.

* Debe configurarse el usuario con el método de acceso correcto.
+
La autenticación sólo se realiza correctamente para los usuarios con el método de acceso correcto para el servicio web dado. Para el servicio web de la API de ONTAP  `ontapi`), los usuarios deben tener el `ontapi` método de acceso. Para todos los demás servicios web, los usuarios deben tener `http` método de acceso.

+
[NOTE]
====
Utilice la `security login` comandos para gestionar los métodos de acceso y los métodos de autenticación de los usuarios.

====
* El servicio web debe estar configurado para permitir la función de control de acceso del usuario.
+
[NOTE]
====
Utilice la `vserver services web access` comandos para controlar el acceso de un rol a un servicio web.

====


Si hay un firewall habilitado, la política de firewall para el LIF que se utilizará para los servicios web debe configurarse para permitir HTTP o HTTPS.

Si utiliza HTTPS para el acceso a servicios web, debe habilitar SSL para el clúster o la SVM que ofrece el servicio web, y debe proporcionar un certificado digital para el clúster o la SVM.
