---
permalink: system-admin/manage-core-dumps-concept.html 
sidebar: sidebar 
keywords: manage, core, dump, cluster, administrator, node, panic, configure, attributes, save, display, segment, upload, delete 
summary: Puede configurar o mostrar atributos de volcado de memoria del nodo y gestionar archivos de volcado de memoria del nodo. 
---
= Gestionar volcados principales de nodos para un clúster de ONTAP (solo administradores de clústeres)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando un nodo produce una alarma, se produce un volcado de memoria y el sistema crea un archivo de volcado de memoria que el soporte técnico puede utilizar para solucionar el problema. Es posible configurar o mostrar atributos de volcado de memoria. También puede guardar, mostrar, segmentar, cargar o eliminar un archivo de volcado de memoria.

Puede gestionar volcados de memoria de las siguientes maneras:

* Configurar volcados de memoria y mostrar las opciones de configuración
* Mostrar información básica, el estado y los atributos de los volcados principales
+
Los archivos de volcado de memoria e informes se almacenan en `/mroot/etc/crash/` el directorio de un nodo. Puede mostrar el contenido del directorio mediante `system node coredump` los comandos o un navegador web.

* Se guarda el contenido de volcado principal y se carga el archivo guardado en una ubicación específica o al soporte técnico
+
ONTAP evita que se inicie el almacenamiento de un archivo de volcado principal durante la toma de control, la reubicación de agregados o una devolución del nodo principal.

* Eliminación de archivos de volcado de memoria que ya no son necesarios




== Comandos para gestionar volcados de memoria

Los `system node coredump config` comandos se utilizan para gestionar la configuración de volcados principales, `system node coredump` los comandos para gestionar los archivos de volcado principal y `system node coredump reports` los comandos para gestionar los informes de núcleo de la aplicación.

Obtenga más información sobre los comandos descritos en este tema en la link:https://docs.netapp.com/us-en/ontap-cli/["Referencia de comandos del ONTAP"]sección .

|===
| Si desea... | Se usa este comando... 


 a| 
Configurar volcados de memoria
 a| 
`system node coredump config modify`



 a| 
Muestra las opciones de configuración de los volcados principales
 a| 
`system node coredump config show`



 a| 
Mostrar información básica sobre volcados de memoria
 a| 
`system node coredump show`



 a| 
Active manualmente un volcado de memoria cuando reinicie un nodo
 a| 
`system node reboot` con `-dump` `-skip-lif-migration-before-reboot` los parámetros y.

[NOTE]
====
El parámetro LINK:https://docs.NetApp.com/us-en/ONTAP-cli//system-node-reboot.html#parameters[`skip-lif-migration-before-reboot`^] especifica que se omitirá la migración de LIF antes de un reinicio.

====


 a| 
Active manualmente un volcado de memoria cuando apague un nodo
 a| 
`system node halt` con `-dump` `-skip-lif-migration-before-shutdown` los parámetros y.

[NOTE]
====
El parámetro LINK:https://docs.NetApp.com/us-en/ONTAP-cli/system-node-halt.html#parameters[`skip-lif-migration-before-shutdown`^] especifica que se omitirá la migración de LIF antes de un apagado.

====


 a| 
Guarde un volcado de memoria especificado
 a| 
`system node coredump save`



 a| 
Guarde todos los volcados de memoria no guardados que estén en un nodo especificado
 a| 
`system node coredump save-all`



 a| 
Genere y envíe un mensaje de AutoSupport con un archivo de volcado principal que especifique
 a| 
`system node autosupport invoke-core-upload`

[NOTE]
====
El `-uri` parámetro opcional especifica un destino alternativo para el mensaje de AutoSupport.

====


 a| 
Mostrar información de estado de volcados principales
 a| 
`system node coredump status`



 a| 
Elimine un volcado de memoria especificado
 a| 
`system node coredump delete`



 a| 
Elimine todos los volcados de memoria que no haya guardado o todos los archivos principales guardados de un nodo
 a| 
`system node coredump delete-all`



 a| 
Mostrar informes de volcado de memoria de aplicaciones
 a| 
`system node coredump reports show`



 a| 
Elimine un informe de volcado de memoria de la aplicación
 a| 
`system node coredump reports delete`

|===
.Información relacionada
link:../concepts/manual-pages.html["Referencia de comandos del ONTAP"]
