---
permalink: system-admin/manage-licenses-concept.html 
sidebar: sidebar 
keywords: manage, license, enable, add, record, software, entitlement, keys, codes, risk, usage, cluster, administrator, nlf 
summary: 'Una licencia es un registro de uno o más derechos de software. En ONTAP 8.2 a ONTAP 9.9.1, las licencias se ofrecen como cadenas de 28 caracteres y hay una clave por función ONTAP. Se introdujo un nuevo formato de licencia denominado archivo de licencia de NetApp (NLF) en ONTAP 9.2 con el fin de incluir únicamente funciones para todo el clúster, como FabricPool.' 
---
= Información general sobre gestionar licencias (solo administradores de clúster)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una licencia es un registro de uno o más derechos de software. En ONTAP 8.2 a ONTAP 9.9.1, las claves de licencia se entregan como cadenas de 28 caracteres y hay una clave por función ONTAP. Se introdujo un nuevo formato de clave de licencia denominado archivo de licencia de NetApp (NLF) en ONTAP 9.2 con el fin de incluir únicamente funciones para todo el clúster, como FabricPool.

A partir de ONTAP 9.10.1, toda la licencia se entrega como NLF. Las licencias de NLF pueden activar una o más funciones de ONTAP, según la compra. Para recuperar licencias de NLF desde el sitio de soporte de NetApp, busque el número de serie del sistema (controladora).

Puede encontrar licencias para los pedidos de software iniciales o adicionales en el sitio de soporte de NetApp en *My Support* > *Software Licenses* (se requiere inicio de sesión). Para obtener más información acerca de los reemplazos de licencia, consulte el artículo de Knowledge base link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/Post_Motherboard_Replacement_Process_to_update_Licensing_on_a_AFF_FAS_system["Tras el proceso de sustitución de la placa base, se actualizan las licencias en un sistema AFF/FAS"].

ONTAP permite gestionar licencias de funciones de las siguientes maneras:

* Muestra información sobre las licencias instaladas (`system license show`)
* Muestra los paquetes que requieren licencias y su estado de licencia actual en el clúster (`system license status show`)
* Elimine una licencia del clúster o de un nodo cuyo número de serie especifique (`system license delete`)
* Muestra o elimina licencias caducadas o no utilizadas (`system license clean-up`)


ONTAP le permite supervisar el uso de funciones y el riesgo de concesión de licencias de las siguientes formas:

* Muestre un resumen del uso de las funciones en el clúster por nodo (`system feature-usage show-summary`)
+
El resumen incluye información de contador, como el número de semanas que una operación estaba en uso y la última fecha y hora en que se utilizó la función.

* Muestre el estado de uso de las funciones en el clúster por nodo y por semana (`system feature-usage show-history`)
+
El estado de uso de la función puede ser `not-used`, `configured`, o. `in-use`. Si la información de uso no está disponible, el estado muestra `not-available`.

* Muestra el estado del riesgo de autorización de licencia de cada paquete de licencia (`system license entitlement-risk show`)
+
El estado de riesgo puede ser `low`, `medium`, `high`, `unlicensed`, o. `unknown`. El estado del riesgo también se incluye en el mensaje AutoSupport. El riesgo de concesión de licencia no se aplica al paquete de licencia base.

+
El riesgo de autorización de licencia se evalúa utilizando varios factores, que pueden incluir, entre otros, los siguientes:

+
** Estado de licencia de cada paquete
** El tipo de licencia, su estado de caducidad y la uniformidad de las licencias en todo el clúster
** Uso de las funciones asociadas con el paquete de licencia Si el proceso de evaluación determina que el clúster tiene un riesgo de autorización de licencia, el resultado del comando también sugiere una acción correctiva.




[NOTE]
====
Nota: ONTAP 9.10.1 también admite claves de licencia de 28 caracteres mediante el Administrador del sistema o la CLI. Sin embargo, si se instala una licencia de NLF para una función, no puede instalar una clave de licencia de 28 caracteres sobre la licencia de NLF para la misma función. Para obtener información acerca de la instalación de NLF o claves de licencia mediante System Manager, consulte el apartado “Habilitar nuevas funciones”.

====
.Información relacionada
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_are_Data_ONTAP_8.2_and_8.3_licensing_overview_and_references%3F["¿Qué referencias y información general sobre las licencias de Data ONTAP 8.2 y 8.3?"^]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_verify_Data_ONTAP_Software_Entitlements_and_related_License_Keys_using_the_Support_Site["Cómo comprobar las autorizaciones de software de Data ONTAP y las claves de licencia relacionadas a través del sitio de soporte"^]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/FAQ%3A_Licensing_updates_in_Data_ONTAP_9.2["Preguntas más frecuentes: Actualizaciones de licencias en Data ONTAP 9.2"^]

http://mysupport.netapp.com/licensing/ontapentitlementriskstatus["NetApp: Estado de riesgo de autorizaciones de Data ONTAP"^]
