---
permalink: system-admin/manage-core-dumps-concept.html 
sidebar: sidebar 
keywords: manage, core, dump, cluster, administrator, node, panic, configure, attributes, save, display, segment, upload, delete 
summary: Cuando un nodo produce una alarma, se produce un volcado de memoria y el sistema crea un archivo de volcado de memoria que el soporte técnico puede utilizar para solucionar el problema. Es posible configurar o mostrar atributos de volcado de memoria. También puede guardar, mostrar, segmentar, cargar o eliminar un archivo de volcado de memoria. 
---
= Gestionar volcados de memoria (solo administradores de clúster)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando un nodo produce una alarma, se produce un volcado de memoria y el sistema crea un archivo de volcado de memoria que el soporte técnico puede utilizar para solucionar el problema. Es posible configurar o mostrar atributos de volcado de memoria. También puede guardar, mostrar, segmentar, cargar o eliminar un archivo de volcado de memoria.

Puede gestionar volcados de memoria de las siguientes maneras:

* Configurar volcados de memoria y mostrar las opciones de configuración
* Mostrar información básica, el estado y los atributos de los volcados principales
+
Los archivos de volcado principal y los informes se almacenan en la `/mroot/etc/crash/` directorio de un nodo. Puede mostrar el contenido del directorio mediante `system node coredump` o un navegador web.

* Se guarda el contenido de volcado principal y se carga el archivo guardado en una ubicación específica o al soporte técnico
+
ONTAP evita que se inicie el almacenamiento de un archivo de volcado principal durante la toma de control, la reubicación de agregados o una devolución del nodo principal.

* Eliminación de archivos de volcado de memoria que ya no son necesarios




== Comandos para gestionar volcados de memoria

Utilice la `system node coredump config` comandos para gestionar la configuración de volcados principales, el `system node coredump` comandos para gestionar los archivos de volcado principales y el `system node coredump reports` comandos para gestionar informes principales de aplicaciones.

|===
| Si desea... | Se usa este comando... 


 a| 
Configurar volcados de memoria
 a| 
`system node coredump config modify`



 a| 
Muestra las opciones de configuración de los volcados principales
 a| 
`system node coredump config show`



 a| 
Mostrar información básica sobre volcados de memoria
 a| 
`system node coredump show`



 a| 
Active manualmente un volcado de memoria cuando reinicie un nodo
 a| 
`system node reboot` con ambos `-dump` y.. `-skip-lif-migration-before-reboot` parámetros

[NOTE]
====
El enlace: https://docs.netapp.com/us-en/ontap-cli-9141//system-node-reboot.html#parameters[`skip-lif-migration-before-reboot`] Especifica que se omitirá la migración de LIF antes de un reinicio.

====


 a| 
Active manualmente un volcado de memoria cuando apague un nodo
 a| 
`system node halt` con ambos `-dump` y.. `-skip-lif-migration-before-shutdown` parámetros

[NOTE]
====
El enlace: https://docs.netapp.com/us-en/ontap-cli-9141/system-node-halt.html#parameters[`skip-lif-migration-before-shutdown`El parámetro ] especifica que se omitirá la migración de LIF antes de un apagado.

====


 a| 
Guarde un volcado de memoria especificado
 a| 
`system node coredump save`



 a| 
Guarde todos los volcados de memoria no guardados que estén en un nodo especificado
 a| 
`system node coredump save-all`



 a| 
Genere y envíe un mensaje de AutoSupport con un archivo de volcado principal que especifique
 a| 
`system node autosupport invoke-core-upload`

[NOTE]
====
La `-uri` El parámetro opcional especifica un destino alternativo para el mensaje AutoSupport.

====


 a| 
Mostrar información de estado de volcados principales
 a| 
`system node coredump status`



 a| 
Elimine un volcado de memoria especificado
 a| 
`system node coredump delete`



 a| 
Elimine todos los volcados de memoria que no haya guardado o todos los archivos principales guardados de un nodo
 a| 
`system node coredump delete-all`



 a| 
Mostrar informes de volcado de memoria de aplicaciones
 a| 
`system node coredump reports show`



 a| 
Elimine un informe de volcado de memoria de la aplicación
 a| 
`system node coredump reports delete`

|===
.Información relacionada
link:https://docs.netapp.com/us-en/ontap/concepts/manual-pages.html["Comandos de ONTAP 9"^]
