---
permalink: system-admin/manage-banner-motd-concept.html 
sidebar: sidebar 
keywords: manage, banner, motd, clu, user, svm, storage, virtual, machine, cluster 
summary: 'ONTAP permite configurar un banner de inicio de sesión o un mensaje del día (MOTD) para comunicar la información administrativa a los usuarios de la CLI del clúster o de la máquina virtual de almacenamiento (SVM).' 
---
= Gestione el banner y la visión general de MOTD
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP permite configurar un banner de inicio de sesión o un mensaje del día (MOTD) para comunicar la información administrativa a los usuarios de la CLI del clúster o de la máquina virtual de almacenamiento (SVM).

Se muestra un banner en una sesión de consola (solo para el acceso al clúster) o una sesión SSH (para el acceso al clúster o a SVM) antes de que se solicite a un usuario que realice la autenticación, como una contraseña. Por ejemplo, puede utilizar el banner para mostrar un mensaje de advertencia como el siguiente a alguien que intenta iniciar sesión en el sistema:

[listing]
----
$ ssh admin@cluster1-01

This system is for authorized users only. Your IP Address has been logged.

Password:

----
Un MDT se muestra en una sesión de consola (sólo para acceso a clústeres) o una sesión SSH (para acceso a clústeres o SVM) después de que un usuario se autentica pero antes de que aparezca el mensaje clustershell. Por ejemplo, puede utilizar el MOTD para mostrar un mensaje de bienvenida o informativo como el siguiente, que sólo verán los usuarios autenticados:

[listing]
----
$ ssh admin@cluster1-01

Password:

Greetings. This system is running ONTAP 9.0.
Your user name is 'admin'. Your last login was Wed Apr 08 16:46:53 2015 from 10.72.137.28.

----
Puede crear o modificar el contenido del banner o el MOTD mediante el `security login banner modify` o. `security login motd modify` command, respectivamente, de las siguientes formas:

* Puede utilizar la CLI de forma interactiva o no interactiva para especificar el texto que se va a utilizar para el banner o el MOTD.
+
El modo interactivo, se inicia cuando el comando se utiliza sin el `-message` o. `-uri` parámetro, permite utilizar nuevas líneas (también llamadas fin de líneas) en el mensaje.

+
El modo no interactivo, que utiliza `-message` parámetro para especificar la cadena de mensaje, no admite newlines.

* Puede cargar contenido desde una ubicación FTP o HTTP para utilizarlo en el banner o en el MOTD.
* Puede configurar el módulo MOTD para que muestre contenido dinámico.
+
Algunos ejemplos de lo que puede configurar el MOTD para que se muestre dinámicamente son los siguientes:

+
** El nombre del clúster, el nombre del nodo o el nombre de SVM
** Fecha y hora del clúster
** Nombre del usuario que inicia sesión
** Último inicio de sesión para el usuario en cualquier nodo del clúster
** Nombre de dispositivo de inicio de sesión o dirección IP
** Nombre del sistema operativo
** Versión del software
** La versión del clúster efectiva cadena de `security login motd modify` La página man describe las secuencias de escape que puede utilizar para permitir que el MOTD muestre contenido generado dinámicamente.


+
El banner no admite contenido dinámico.



Puede gestionar el banner y el MOTD en el nivel de clúster o SVM:

* Los siguientes hechos se aplican al banner:
+
** El banner configurado para el clúster también se usa para todas las SVM que no tienen un mensaje de banner definido.
** Se puede configurar un banner a nivel de SVM para cada SVM.
+
Si se configuró un banner a nivel de clúster, este será anulado por el banner de SVM de la SVM indicada.



* Los siguientes hechos se aplican al MDD:
+
** De forma predeterminada, el MOTD configurado para el clúster también está habilitado para todas las SVM.
** Además, se puede configurar un MOTD a nivel de SVM para cada SVM.
+
En este caso, los usuarios que inicien sesión en la SVM verán dos MODs, uno definido a nivel de clúster y el otro a nivel de SVM.

** El administrador del clúster puede habilitar o deshabilitar el MOTD a nivel de clúster por SVM.
+
Si el administrador de clúster deshabilita el MOTD a nivel de clúster para una SVM, un usuario que inicia sesión en la SVM no ve el MOTD a nivel de clúster.




