---
permalink: system-admin/manage-licenses-concept.html 
sidebar: sidebar 
keywords: manage, license, ontap one, enable, add, record, software, entitlement, keys, codes, risk, usage, cluster, administrator, nlf 
summary: 'Una licencia es un registro de uno o más derechos de software. A partir de ONTAP 9.10.1, todas las licencias se proporcionan como archivo de licencia de NetApp (NLF), que es un solo archivo que admite varias funciones.  A partir de mayo de 2023, todos los sistemas AFF (tanto A-series como C-series) y los sistemas FAS se venden con la suite de software ONTAP One o la suite de software básico ONTAP. A partir de junio de 2023, todos los sistemas ASA se venden con ONTAP One para SAN.' 
---
= Información general de las licencias de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una licencia es un registro de uno o más derechos de software. A partir de ONTAP 9.10.1, todas las licencias se proporcionan como archivo de licencia de NetApp (NLF), que es un solo archivo que admite varias funciones.  A partir de mayo de 2023, todos los sistemas AFF (tanto A-series como C-series) y los sistemas FAS se venden con la suite de software ONTAP One o la suite de software básico ONTAP. A partir de junio de 2023, todos los sistemas ASA se venden con ONTAP One para SAN. Cada suite de software se entrega como un único NLF, en sustitución de los paquetes NLF independientes que se introdujeron primero en ONTAP 9.10.1.



== Licencias incluidas con ONTAP One

ONTAP One contiene todas las funciones con licencia disponibles. Contiene una combinación de los contenidos del paquete Core anterior, el bundle de protección de datos, el bundle de seguridad y cumplimiento de normativas, el bundle de cloud híbrido y el bundle de cifrado, como se muestra en la tabla. El cifrado no está disponible en países restringidos.

|===


| Nombre de grupo anterior | Claves ONTAP incluidas 


.5+| Bundle principal | FlexClone 


| SnapRestore 


| NFS, SMB, S3 


| FC, iSCSI 


| NVMe-oF 


.3+| Bundle de seguridad y cumplimiento de normativas | Protección autónoma de ransomware 


| MTKM 


| SnapLock 


.3+| Bundle de protección de datos | SnapMirror (asíncrono, síncrono, continuidad del negocio) 


| SnapCenter 


| SnapMirror S3 para destinos NetApp 


.2+| Bundle de cloud híbrido | Cloud de SnapMirror 


| SnapMirror S3 para destinos que no son de NetApp 


.2+| Bundle de cifrado | Cifrado de volúmenes de NetApp 


| Módulo de plataforma de confianza 
|===


== Licencias no incluidas con ONTAP One

ONTAP One no incluye ninguno de los servicios proporcionados en cloud de NetApp, como los siguientes:

* Organización en niveles de BlueXP
* Cloud Insights
* Backup de BlueXP
* Regulación de datos




== ONTAP One para sistemas existentes

Si tiene sistemas existentes que se encuentran actualmente en soporte de NetApp pero no se han actualizado a ONTAP One, las licencias existentes en esos sistemas siguen siendo válidas y siguen funcionando según lo previsto. Por ejemplo, si la licencia de SnapMirror ya está instalada en sistemas existentes, no es necesario actualizar a ONTAP One para obtener una nueva licencia de SnapMirror. Sin embargo, si no tiene instalada una licencia de SnapMirror en un sistema ya existente, la única forma de obtener dicha licencia consiste en actualizar a ONTAP One por una tarifa adicional.

A partir de junio de 2023, los sistemas ONTAP que utilizan claves de licencia de 28 caracteres también pueden link:https://kb.netapp.com/onprem/ontap/os/How_to_get_an_ONTAP_One_license_when_the_system_has_28_character_keys["Actualice al paquete de compatibilidad ONTAP One o ONTAP Base"].



== Licencias incluidas con ONTAP Base

Base de ONTAP es una suite de software opcional que es una alternativa a ONTAP One para los sistemas ONTAP. Es para casos de uso específicos en los que no se necesitan tecnologías de protección de datos como SnapMirror y SnapCenter, así como funciones de seguridad como ransomware autónomo, como sistemas que no son de producción para entornos de prueba o desarrollo dedicados. No se pueden añadir licencias adicionales a la base de ONTAP. Si desea añadir licencias, como SnapMirror, debe actualizar a ONTAP One.

|===


| Nombre de grupo anterior | Claves ONTAP incluidas 


.5+| Bundle principal | FlexClone 


| SnapRestore 


| NFS, SMB, S3 


| FC, iSCSI 


| NVMe-oF 


.2+| Bundle de cifrado | Cifrado de volúmenes de NetApp 


| Módulo de plataforma de confianza 
|===


== Licencias incluidas con ONTAP One para SAN

ONTAP One para SAN está disponible para los sistemas ASA A-series y C-series. Se trata de la única suite de software disponible para SAN. ONTAP One para SAN contiene las siguientes licencias:

|===


| Claves ONTAP incluidas 


| FlexClone 


| SnapRestore 


| FC, iSCSI 


| NVMe-oF 


| MTKM 


| SnapLock 


| SnapMirror (asíncrono, síncrono, continuidad del negocio) 


| SnapCenter 


| Cloud de SnapMirror 


| Cifrado de volúmenes de NetApp 


| Módulo de plataforma de confianza 
|===


== Otros métodos de entrega de licencias

En ONTAP 8.2 a ONTAP 9.9.1, las claves de licencia se entregan como cadenas de 28 caracteres y hay una clave por función ONTAP. Utilice la interfaz de línea de comandos de ONTAP para instalar claves de licencia si utiliza ONTAP 8,2 a través de ONTAP 9,9.1.

[NOTE]
====
ONTAP 9.10.1 admite la instalación de claves de licencia de 28 caracteres mediante System Manager o la CLI. Sin embargo, si se instala una licencia NLF para una función, no es posible instalar una clave de licencia de 28 caracteres en el archivo de licencia de NetApp para la misma función. Para obtener información sobre la instalación de NLF o claves de licencia mediante System Manager, consulte link:../system-admin/install-license-task.html["Instalar licencias de ONTAP"].

====
.Información relacionada
https://kb.netapp.com/onprem/ontap/os/How_to_get_an_ONTAP_One_license_when_the_system_has_NLFs_already["Cómo obtener una licencia de ONTAP One cuando el sistema ya tiene NLF"]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_verify_Data_ONTAP_Software_Entitlements_and_related_License_Keys_using_the_Support_Site["Cómo comprobar las autorizaciones de software de ONTAP y las claves de licencia relacionadas a través del sitio de soporte"^]

http://mysupport.netapp.com/licensing/ontapentitlementriskstatus["NetApp: Estado de riesgo de derecho de ONTAP"^]
