---
permalink: system-admin/methods-manage-sp-bmc-firmware-updates-concept.html 
sidebar: sidebar 
keywords: methods, manage, sp, bmc, firmware, update, image, baseline, download 
summary: ONTAP incluye una imagen de firmware del SP que se denomina imagen de línea de base. Si una nueva versión del firmware del SP se encuentra disponible posteriormente, tiene la opción de descargarlo y actualizar el firmware del SP a la versión descargada sin actualizar la versión de ONTAP. 
---
= Gestionar actualizaciones de firmware de ONTAP SP/BMC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP incluye una imagen de firmware del SP que se denomina _baseline_. Si una nueva versión del firmware del SP se encuentra disponible posteriormente, tiene la opción de descargarlo y actualizar el firmware del SP a la versión descargada sin actualizar la versión de ONTAP.

[NOTE]
====
Este tema se aplica tanto al SP como al BMC.

====
ONTAP ofrece los siguientes métodos para gestionar las actualizaciones del firmware del SP:

* La funcionalidad de actualización automática del SP está habilitada de forma predeterminada, lo que permite que el firmware del SP se actualice automáticamente en las siguientes situaciones:
+
** Al actualizar a una nueva versión de ONTAP
+
El proceso de actualización de ONTAP incluye automáticamente la actualización del firmware del SP, siempre y cuando la versión del firmware del SP incluida con ONTAP sea más reciente que la versión del SP que se ejecuta en el nodo.

+
[NOTE]
====
ONTAP detecta una actualización automática de SP fallida y activa una acción correctiva para volver a intentar la actualización automática de SP hasta tres veces. Si los tres reintentos fallan, consulte lalink:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Health_Monitor_SPAutoUpgradeFailedMajorAlert__SP_upgrade_fails_-_AutoSupport_Message["Base de conocimientos de NetApp : Monitor de estado SPAutoUpgradeFailedMajorAlert Error en la actualización de SP - Mensaje de AutoSupport"^] .

====
** Cuando descarga una versión del firmware del SP desde el sitio de soporte de NetApp y la versión descargada es posterior a la que ejecuta el SP actualmente
** Al degradar o revertir a una versión anterior de ONTAP
+
El firmware del SP se actualiza automáticamente a la versión compatible más reciente compatible, compatible con la versión de ONTAP a la que se revierte o degradó. No es necesaria una actualización manual del firmware del SP.



+
Puede deshabilitar la funcionalidad de actualización automática de SP mediante `system service-processor image modify` el comando. Sin embargo, se recomienda dejar la funcionalidad habilitada. Al deshabilitar la funcionalidad, puede haber combinaciones no cualificadas entre la imagen ONTAP y la imagen del firmware del SP.

* ONTAP le permite activar una actualización de SP manualmente y especificar cómo se debe realizar la actualización mediante `system service-processor image update` el comando.
+
Puede especificar las siguientes opciones:

+
** El paquete de firmware de SP que se va a utilizar (`-package`)
+
Puede actualizar el firmware del SP en un paquete descargado especificando el nombre del archivo del paquete. El `system image package show` comando advanced muestra todos los archivos de paquete (incluidos los archivos para el paquete de firmware de SP) que están disponibles en un nodo.

** Si se debe utilizar el paquete de firmware de SP de referencia para la actualización de SP (`-baseline`)
+
Puede actualizar el firmware del SP a la versión de referencia que se incluye en el paquete con la versión actualmente en ejecución de ONTAP.



+
[NOTE]
====
Si utiliza algunas de las opciones o parámetros de actualización más avanzadas, es posible que los ajustes de configuración del BMC se borren temporalmente. Tras el reinicio, ONTAP puede tardar hasta 10 minutos en restaurar la configuración del BMC.

====
* ONTAP permite mostrar el estado de la actualización de firmware más reciente de SP activada desde ONTAP mediante `system service-processor image update-progress show` el comando.


Cualquier conexión existente con el SP finaliza cuando se actualiza el firmware del SP. Este es el caso si la actualización del firmware del SP se activa de forma automática o manual.

.Información relacionada
https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["Descargas de NetApp: Diagnóstico y firmware del sistema"^]
