---
permalink: system-admin/methods-extended-queries-concept.html 
sidebar: sidebar 
keywords: method, extended, queries, operations, perform, specified, values 
summary: Puede utilizar consultas ampliadas para hacer coincidir y realizar operaciones en objetos que tienen valores especificados. 
---
= Métodos de uso de consultas extendidas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar consultas ampliadas para hacer coincidir y realizar operaciones en objetos que tienen valores especificados.

Las consultas extendidas se especifican encerrándolas entre corchetes ({}). Se debe especificar una consulta ampliada como primer argumento después del nombre del comando, antes que los demás parámetros. Por ejemplo, para establecer sin conexión todos los volúmenes cuyos nombres incluyen la cadena `tmp`, ejecute el comando en el ejemplo siguiente:

[listing]
----
cluster1::> volume modify {-volume *tmp*} -state offline
----
Las consultas ampliadas son generalmente útiles sólo con `modify` y.. `delete` comandos. No tienen sentido en `create` o. `show` comandos.

La combinación de consultas y operaciones de modificación es una herramienta útil. Sin embargo, puede causar confusión y errores si se implementa incorrectamente. Por ejemplo, mediante el (privilegio avanzado) `system node image modify` el comando para establecer la imagen de software predeterminada de un nodo establece automáticamente la otra imagen de software que no es la predeterminada. El comando del siguiente ejemplo es efectivamente una operación nula:

[listing]
----
cluster1::*> system node image modify {-isdefault true} -isdefault false
----
Este comando establece la imagen predeterminada actual como la imagen no predeterminada y, a continuación, establece la nueva imagen predeterminada (la imagen no predeterminada anterior) en la imagen no predeterminada, lo que resulta en la retención de la configuración predeterminada original. Para realizar la operación correctamente, puede utilizar el comando tal como se indica en el ejemplo siguiente:

[listing]
----
cluster1::*> system node image modify {-iscurrent false} -isdefault true
----