---
permalink: system-admin/methods-view-command-history-concept.html 
sidebar: sidebar 
keywords: method, view, command, history, reissue, command 
summary: Cada sesión de la CLI conserva un historial de todos los comandos emitidos en ella. Puede ver el historial de comandos de la sesión en la que está actualmente. También puede volver a emitir comandos. 
---
= Consulte el historial de comandos de ONTAP y vuelva a ejecutar cualquier comando desde el historial
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada sesión de la CLI conserva un historial de todos los comandos emitidos en ella. Puede ver el historial de comandos de la sesión en la que está actualmente. También puede volver a emitir comandos.

Para ver el historial de comandos, puede utilizar `history` el comando.

Para volver a emitir un comando, puede utilizar `redo` el comando con uno de los siguientes argumentos:

* Cadena que coincide con parte de un comando anterior
+
Por ejemplo, si el único `volume` comando que ha ejecutado es `volume show`, puede utilizar `redo volume` el comando para volver a ejecutar el comando.

* ID numérico de un comando anterior, como se indica en el `history` comando
+
Por ejemplo, puede utilizar `redo 4` el comando para volver a emitir el cuarto comando de la lista de historial.

* Un desplazamiento negativo desde el final de la lista de historial
+
Por ejemplo, puede utilizar `redo -2` el comando para volver a emitir el comando que ejecutó hace dos comandos.



Por ejemplo, para rehacer el mandato que es tercero desde el final del historial de comandos, debe introducir el siguiente comando:

[listing]
----
cluster1::> redo -3
----
.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/history.html["historia"^]
* link:https://docs.netapp.com/us-en/ontap-cli/redo.html["rehacer"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume["volumen"^]

