---
permalink: system-admin/methods-manage-sp-bmc-firmware-updates-concept.html 
sidebar: sidebar 
keywords: methods, manage, sp, bmc, firmware, update, image, baseline, download 
summary: ONTAP incluye una imagen de firmware del SP que se denomina imagen de línea de base. Si una nueva versión del firmware del SP se encuentra disponible posteriormente, tiene la opción de descargarlo y actualizar el firmware del SP a la versión descargada sin actualizar la versión de ONTAP. 
---
= Métodos para gestionar actualizaciones del firmware del SP/BMC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP incluye una imagen de firmware del SP que se denomina _baseline_. Si una nueva versión del firmware del SP se encuentra disponible posteriormente, tiene la opción de descargarlo y actualizar el firmware del SP a la versión descargada sin actualizar la versión de ONTAP.

[NOTE]
====
Este tema se aplica tanto al SP como al BMC.

====
ONTAP ofrece los siguientes métodos para gestionar las actualizaciones del firmware del SP:

* La funcionalidad de actualización automática del SP está habilitada de forma predeterminada, lo que permite que el firmware del SP se actualice automáticamente en las siguientes situaciones:
+
** Al actualizar a una nueva versión de ONTAP
+
El proceso de actualización de ONTAP incluye automáticamente la actualización del firmware del SP, siempre y cuando la versión del firmware del SP incluida con ONTAP sea más reciente que la versión del SP que se ejecuta en el nodo.

+
[NOTE]
====
ONTAP detecta una actualización automática del SP con errores y activa una acción correctiva para volver a intentar la actualización automática del SP hasta tres veces. Si los tres reintentos fallan, consulte el vínculo del artículo de la base de conocimientos: Error en la actualización SP Monitor SPAutoUpgradeFailedMajorAlert de https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Health_Monitor_SPAutoUpgradeFailedMajorAlert__SP_upgrade_fails_-_AutoSupport_Message[Health: Mensaje de AutoSupport].

====
** Cuando descarga una versión del firmware del SP desde el sitio de soporte de NetApp y la versión descargada es posterior a la que ejecuta el SP actualmente
** Al degradar o revertir a una versión anterior de ONTAP
+
El firmware del SP se actualiza automáticamente a la versión compatible más reciente compatible, compatible con la versión de ONTAP a la que se revierte o degradó. No es necesaria una actualización manual del firmware del SP.



+
Tiene la opción de deshabilitar la funcionalidad de actualización automática del SP mediante el `system service-processor image modify` comando. Sin embargo, se recomienda dejar la funcionalidad habilitada. Al deshabilitar la funcionalidad, puede haber combinaciones no cualificadas entre la imagen ONTAP y la imagen del firmware del SP.

* ONTAP le permite activar una actualización de SP manualmente y especificar cómo debe realizarse la actualización mediante el `system service-processor image update` comando.
+
Puede especificar las siguientes opciones:

+
** El paquete de firmware del SP que se va a utilizar (`-package`)
+
Puede actualizar el firmware del SP en un paquete descargado especificando el nombre del archivo del paquete. Avance `system image package show` El comando muestra todos los archivos de paquetes (incluidos los archivos del paquete de firmware del SP) disponibles en un nodo.

** Si se utiliza el paquete de firmware del SP de referencia para la actualización del SP (`-baseline`)
+
Puede actualizar el firmware del SP a la versión de referencia que se incluye en el paquete con la versión actualmente en ejecución de ONTAP.



+
[NOTE]
====
Si utiliza algunas de las opciones o parámetros de actualización más avanzadas, es posible que los ajustes de configuración del BMC se borren temporalmente. Tras el reinicio, ONTAP puede tardar hasta 10 minutos en restaurar la configuración del BMC.

====
* ONTAP le permite mostrar el estado de la última actualización del firmware del SP activada desde ONTAP mediante el `system service-processor image update-progress show` comando.


Cualquier conexión existente con el SP finaliza cuando se actualiza el firmware del SP. Este es el caso si la actualización del firmware del SP se activa de forma automática o manual.

.Información relacionada
https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["Descargas de NetApp: Diagnóstico y firmware del sistema"]
