---
permalink: system-admin/methods-view-command-history-concept.html 
sidebar: sidebar 
keywords: method, view, command, history, reissue, command 
summary: Cada sesión de la CLI conserva un historial de todos los comandos emitidos en ella. Puede ver el historial de comandos de la sesión en la que está actualmente. También puede volver a emitir comandos. 
---
= Métodos para ver el historial de comandos y volver a emitir comandos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada sesión de la CLI conserva un historial de todos los comandos emitidos en ella. Puede ver el historial de comandos de la sesión en la que está actualmente. También puede volver a emitir comandos.

Para ver el historial de comandos, puede utilizar `history` comando.

Para volver a emitir un comando, puede utilizar el `redo` comando con uno de los siguientes argumentos:

* Cadena que coincide con parte de un comando anterior
+
Por ejemplo, si el único `volume` el comando que ha ejecutado es `volume show`, puede utilizar la `redo volume` para volver a ejecutar el comando.

* El código numérico de un comando anterior, según se indica en la `history` comando
+
Por ejemplo, puede usar el `redo 4` comando para volver a emitir el cuarto comando en la lista de historial.

* Un desplazamiento negativo desde el final de la lista de historial
+
Por ejemplo, puede usar el `redo -2` comando para volver a emitir el comando que ejecutó hace dos comandos.



Por ejemplo, para rehacer el mandato que es tercero desde el final del historial de comandos, debe introducir el siguiente comando:

[listing]
----
cluster1::> redo -3
----