---
permalink: system-admin/modify-node-attributes-task.html 
sidebar: sidebar 
keywords: modify, node, attributes, owner, information, location, asset, tag, eligibility, cluster 
summary: Puede modificar los atributos de un nodo según sea necesario. Los atributos que puede modificar incluyen la información del propietario del nodo, la información de ubicación, la etiqueta de activo y la elegibilidad para participar en el clúster. 
---
= Modifique los atributos de un nodo ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede modificar los atributos de un nodo según sea necesario. Los atributos que puede modificar incluyen la información del propietario del nodo, la información de ubicación, la etiqueta de activo y la elegibilidad para participar en el clúster.

.Acerca de esta tarea
La elegibilidad de un nodo para participar en el clúster puede modificarse en el nivel de privilegio avanzado mediante el `–eligibility` parámetro de `system node modify` o. `cluster modify` comando. Si establece la idoneidad de un nodo `false`, el nodo se vuelve inactivo en el clúster.

[NOTE]
====
No puede modificar la idoneidad del nodo de forma local. Debe modificarse desde un nodo diferente. La eligiblidad del nodo tampoco se puede modificar con una configuración de alta disponibilidad de clúster.

====
[NOTE]
====
Debe evitar establecer la idoneidad de un nodo `false`, excepto en situaciones como restaurar la configuración del nodo o el mantenimiento prolongado de los nodos. El acceso a datos DE SAN y NAS al nodo puede verse afectado cuando el nodo no cumple con los requisitos.

====
.Pasos
. Utilice la `system node modify` comando para modificar los atributos de un nodo.


.Ejemplo de modificación de atributos de nodo
El siguiente comando modifica los atributos del nodo "'1'". El propietario del nodo se establece en "'Joe Smith'" y su etiqueta de activo se establece en "'js1234'":

[listing]
----
cluster1::> system node modify -node node1 -owner "Joe Smith" -assettag js1234
----
.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/system-node-modify.html["modificación del nodo del sistema"^]
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-modify.html["modificar el clúster"^]

