---
permalink: system-admin/modify-cluster-attributes-task.html 
sidebar: sidebar 
keywords: modify, cluster, attributes, name, location, contact, information 
summary: Puede modificar los atributos de un clúster, como el nombre del clúster, la ubicación y la información de contacto según sea necesario. 
---
= Modifique los atributos del clúster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede modificar los atributos de un clúster, como el nombre del clúster, la ubicación y la información de contacto, según sea necesario.

.Acerca de esta tarea
No puede cambiar el UUID de un clúster, que se establece cuando se crea el clúster.

.Pasos
. Para modificar los atributos del clúster, utilice el `cluster identity modify` comando.
+
La `-name` el parámetro especifica el nombre del clúster. La `cluster identity modify` la página man describe las reglas para especificar el nombre del clúster.

+
La `-location` el parámetro especifica la ubicación del clúster.

+
La `-contact` parámetro especifica la información de contacto, como un nombre o una dirección de correo electrónico.



.Ejemplo de cambio de nombre de un clúster
El siguiente comando cambia el nombre del clúster actual ("'cluster1'") a «'cluster2'»:

[listing]
----
cluster1::> cluster identity modify -name cluster2
----