---
permalink: system-admin/ontap-implements-audit-logging-concept.html 
sidebar: sidebar 
keywords: ontap, implement, audit, logging, management, autosupport, ems, messages, log, cli, web, browser 
summary: Las actividades de gestión registradas en el registro de auditoría se incluyen en los informes estándar de AutoSupport y determinadas actividades de registro se incluyen en los mensajes de EMS. También puede reenviar el registro de auditoría a los destinos que especifique y mostrar los archivos de registro de auditoría mediante la CLI o un explorador web. 
---
= Obtenga más información sobre la implementación del registro de auditorías de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las actividades de administración registradas en el registro de auditoría se incluyen en los informes estándar de AutoSupport , y ciertas actividades de registro se incluyen en los mensajes EMS. También puede reenviar el registro de auditoría a los destinos que especifique y visualizar los archivos de registro de auditoría mediante la CLI de ONTAP o un navegador web.

A partir de ONTAP 9.11.1, es posible mostrar contenido del registro de auditoría mediante System Manager.

A partir de ONTAP 9.12.1, ONTAP proporciona alertas de manipulación para los registros de auditoría. ONTAP ejecuta un trabajo diario en segundo plano para comprobar si hay manipulación de archivos audit.log y envía una alerta de EMS si encuentra algún archivo de registro que se haya modificado o alterado.

A partir de ONTAP 9.17.1, y con ONTAP 9.16.1 P4 y versiones posteriores de parches 9.16.1, link:audit-manage-cross-cluster-requests.html["También se pueden registrar las actividades de administración remota iniciadas desde un clúster emparejado mediante operaciones entre clústeres."]. Estas actividades incluyen operaciones internas e impulsadas por el usuario que se originan en otro clúster

.Actividades de gestión registradas en ONTAP
ONTAP registra las actividades de administración que se realizan en un clúster, como qué solicitud se emitió, el usuario que activó la solicitud, el método de acceso del usuario y la hora de la solicitud.

Las actividades de gestión pueden ser de los siguientes tipos:

* *Solicitudes SET*:
+
** Estas solicitudes generalmente se aplican a comandos u operaciones que no son de visualización.
** Estas solicitudes se emiten cuando se ejecuta un `create` `modify` `delete` comando , , o, por ejemplo.
** Las solicitudes SET se registran de forma predeterminada.


* *Solicitudes GET*:
+
** Estas solicitudes recuperan información y la muestran en la interfaz de administración.
** Estas solicitudes se emiten cuando se ejecuta `show` un comando, por ejemplo.
** Las solicitudes GET no se registran de forma predeterminada, pero puede controlar si se envían solicitudes GET desde la CLI de ONTAP (`-cliget` ), de la API de ONTAP (`-ontapiget` ), o desde la API REST de ONTAP (`-httpget` ) se registran en el archivo.




.Registro y rotación de registros de auditoría
Actividades de gestión de registros de ONTAP en el  `/mroot/etc/log/mlog/audit.log` Archivo de un nodo. Los comandos de los tres shells para los comandos CLI: clustershell, nodeshell y systemshell no interactivo, así como los comandos de la API, se registran aquí. Los comandos systemshell interactivos no se registran. Los registros de auditoría incluyen marcas de tiempo para mostrar si todos los nodos de un clúster están sincronizados.

El `audit.log` archivo se envía mediante la herramienta AutoSupport a los destinatarios especificados. También es posible reenviar el contenido de manera segura a destinos externos que especifique; por ejemplo, un servidor de Splunk o syslog.

El `audit.log` archivo se gira diariamente. La rotación también ocurre cuando alcanza los 100 MB de tamaño y se conservan las 48 copias anteriores (con un máximo de 49 archivos). Cuando el archivo de auditoría realiza su rotación diaria, no se genera ningún mensaje EMS. Si el archivo de auditoría gira porque se supera el límite de tamaño de archivo, se genera un mensaje EMS.

Al habilitar la auditoría GET, considere configurar el reenvío de registros para evitar la pérdida de datos debido a la rotación rápida de registros. Para más información, consulte el siguiente artículo de la base de conocimientos: https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/Enabling_audit-log_forwarding["Habilitar el reenvío de registros de auditoría"^] .
