---
permalink: system-admin/positional-parameters-concept.html 
sidebar: sidebar 
keywords: understand, positional, parameters, cli, command, input, query 
summary: Puede aprovechar la funcionalidad de parámetro posicional de la CLI de ONTAP para aumentar la eficiencia de la entrada de comandos. Puede consultar un comando para identificar parámetros que son posicionales para el comando. 
---
= Utilice los parámetros de posición de la CLI de ONTAP en la entrada de comandos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede aprovechar la funcionalidad de parámetro posicional de la CLI de ONTAP para aumentar la eficiencia de la entrada de comandos. Puede consultar un comando para identificar parámetros que son posicionales para el comando.



== Qué es un parámetro posicional

* Un parámetro posicional es un parámetro que no requiere que especifique el nombre del parámetro antes de especificar el valor del parámetro.
* Un parámetro posicional se puede intercalar con parámetros no posicionales en la entrada del comando, siempre y cuando observe su secuencia relativa con otros parámetros posicionales en el mismo comando, como se indica en la `*_command_name ?_*` salida.
* Un parámetro posicional puede ser un parámetro obligatorio u opcional para un comando.
* Un parámetro puede ser posicional para un comando pero no posicional para otro.


[NOTE]
====
No se recomienda utilizar la funcionalidad del parámetro posicional en los scripts, especialmente cuando los parámetros posicionales son opcionales para el comando o tienen parámetros opcionales listados antes de ellos.

====


== Identificar un parámetro posicional

Puede identificar un parámetro de posición en `*_command_name ?_*` el resultado del comando. Un parámetro posicional tiene corchetes que rodean su nombre de parámetro, en uno de los siguientes formatos:

* [`_-parameter_name_`] `_parameter_value_` muestra un parámetro necesario que es posicional.
* [[`_-parameter_name_`] `_parameter_value_`] muestra un parámetro opcional posicional.


Por ejemplo, cuando se muestra como siguiente en el `*_command_name ?_*` resultado, el parámetro es posicional para el comando que aparece en:

* `[-lif] <lif-name>`
* `[[-lif] <lif-name>]`


Sin embargo, cuando se muestra como lo siguiente, el parámetro no es posicional para el comando que aparece en:

* `-lif <lif-name>`
* `[-lif <lif-name>]`




== Ejemplos de uso de parámetros posicionales

En el siguiente ejemplo, el `*_volume create ?_*` resultado muestra que tres parámetros son posicionales para el comando `-volume`: , `-aggregate` Y `-size`.

[listing]
----
cluster1::> volume create ?
   -vserver <vserver name>                Vserver Name
   [-volume] <volume name>                Volume Name
   [-aggregate] <aggregate name>          Aggregate Name
  [[-size] {<integer>[KB|MB|GB|TB|PB]}]   Volume Size
  [ -state {online|restricted|offline|force-online|force-offline|mixed} ]
                                          Volume State (default: online)
  [ -type {RW|DP|DC} ]                    Volume Type (default: RW)
  [ -policy <text> ]                      Export Policy
  [ -user <user name> ]                   User ID
  ...
  [ -space-guarantee|-s {none|volume} ]   Space Guarantee Style (default: volume)
  [ -percent-snapshot-space <percent> ]   Space Reserved for Snapshot Copies
  ...
----
En el ejemplo siguiente, el `volume create` comando se especifica sin aprovechar la funcionalidad del parámetro posicional:

`cluster1::> volume create -vserver svm1 -volume vol1 -aggregate *aggr1 -size 1g* -percent-snapshot-space 0`

Los siguientes ejemplos utilizan la funcionalidad del parámetro posicional para aumentar la eficiencia de la entrada de comando. Los parámetros de posición se intercalan con los parámetros no posicionales en el `volume create` comando, y los valores de los parámetros posicionales se especifican sin los nombres de los parámetros. Los parámetros de posición se especifican en la misma secuencia indicada por la `*volume create ?*` salida. Es decir, el valor para `-volume` se especifica antes que el de `-aggregate`, que a su vez se especifica antes que el de `-size`.

`cluster1::> volume create *vol2* *aggr1* *1g* -vserver svm1 -percent-snapshot-space 0`

`cluster1::> volume create -vserver svm1 *vol3* -snapshot-policy default *aggr1* -nvfail off *1g* -space-guarantee none`
