---
permalink: system-admin/receive-system-health-alerts-automatic-task.html 
sidebar: sidebar 
keywords: receive, system, health, alert, automatically, system, show, command, ems, event, management, monito 
summary: 'Puede ver manualmente las alertas de estado del sistema usando el comando system health alert show. Sin embargo, debe suscribirse a mensajes específicos de Event Management System (EMS) para recibir notificaciones automáticamente cuando un monitor de estado genera una alerta.' 
---
= Reciba automáticamente alertas de estado del sistema ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ver manualmente las alertas de estado del sistema `system health alert show` con el comando. Sin embargo, debe suscribirse a mensajes específicos de Event Management System (EMS) para recibir notificaciones automáticamente cuando un monitor de estado genera una alerta. Obtenga más información sobre `system health alert show` en el link:https://docs.netapp.com/us-en/ontap-cli/system-health-alert-show.html["Referencia de comandos de la ONTAP"^].

.Acerca de esta tarea
En el siguiente procedimiento se muestra cómo configurar notificaciones para todos los mensajes hm.alert.levantados y todos los mensajes hm.alert.borrados.

Todos los mensajes hm.alert.levantados y todos los mensajes hm.alert.borrados incluyen una captura SNMP. Los nombres de las capturas SNMP son `HealthMonitorAlertRaised` y.. `HealthMonitorAlertCleared`. Para obtener información acerca de las capturas SNMP, consulte _Network Management Guide_.

.Pasos
. Utilice la `event destination create` Comando para definir el destino al que desea enviar mensajes de EMS.
+
[listing]
----
cluster1::> event destination create -name health_alerts -mail admin@example.com
----
+
Obtenga más información sobre `event destination create` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=event+destination+create["Referencia de comandos de la ONTAP"^].

. Utilice la `event route add-destinations` comando para enrutar la `hm.alert.raised` y el `hm.alert.cleared` mensaje a un destino.
+
[listing]
----
cluster1::> event route add-destinations -messagename hm.alert* -destinations health_alerts
----
+
Obtenga más información sobre `event route add-destinations` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=event+route+add-destinations["Referencia de comandos de la ONTAP"^].



.Información relacionada
* link:../networking/networking_reference.html["Gestión de redes"]

