---
permalink: system-admin/record-cli-session-task.html 
sidebar: sidebar 
keywords: record, cli, script, start, stop, session 
summary: Puede grabar una sesión de CLI en un archivo con un límite de nombre y tamaño especificado y, a continuación, cargarlo a un destino FTP o HTTP. 
---
= Registre una sesión de la CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede grabar una sesión de CLI en un archivo con un límite de nombre y tamaño especificado y, a continuación, cargarlo a un destino FTP o HTTP. También puede mostrar o eliminar archivos en los que haya grabado previamente las sesiones de la CLI.

Un registro de una sesión CLI termina cuando se detiene la grabación o finaliza la sesión CLI, o cuando el archivo alcanza el límite de tamaño especificado. El límite de tamaño de archivo predeterminado es de 1 MB. El límite máximo de tamaño de archivo es 2 GB.

La grabación de una sesión CLI es útil, por ejemplo, si está solucionando problemas y desea guardar información detallada o si desea crear un registro permanente del uso de espacio en un momento determinado.

.Pasos
. Inicie la grabación de la sesión de CLI actual en un archivo:
+
`system script start`

+
Para obtener más información acerca del uso de `system script start` consulte la página man.

+
ONTAP inicia la grabación de la sesión CLI en el archivo especificado.

. Continúe con la sesión de la CLI.
. Cuando termine, detenga la grabación de la sesión:
+
`system script stop`

+
Para obtener más información acerca del uso de `system script stop` consulte la página man.

+
ONTAP deja de grabar la sesión CLI.


