---
permalink: system-admin/remove-nodes-cluster-concept.html 
sidebar: sidebar 
keywords: remove, node, cluster, failover, partner, erase, inaccessible 
summary: Es posible eliminar nodos no deseados de un clúster, de uno en uno. Después de quitar un nodo, también debe quitar su compañero de conmutación al nodo de respaldo. Si va a quitar un nodo, sus datos se vuelven inaccesibles o se borran. 
---
= Quite los nodos de un clúster de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible eliminar nodos no deseados de un clúster, de uno en uno. Después de quitar un nodo, también debe quitar su compañero de conmutación al nodo de respaldo. Si va a quitar un nodo, sus datos se vuelven inaccesibles o se borran.

.Antes de empezar
Debe cumplir las siguientes condiciones antes de quitar nodos del clúster:

* Más de la mitad de los nodos del clúster deben estar en buen estado.
* Todos los datos, volúmenes y agregados que no sean raíz se han reubicado o eliminado del nodo.
+
** Debe haberse evacuado todos los datos del nodo que desea quitar. Esto puede incluir link:../encryption-at-rest/secure-purge-data-encrypted-volume-concept.html["purgado de datos desde un volumen cifrado"].
** Todos los volúmenes que no son raíz link:../volumes/move-volume-task.html["movido"]provienen de agregados que pertenecen al nodo.
** Todos los agregados que no son raíz link:../disks-aggregates/commands-manage-aggregates-reference.html["eliminado"]se han extraído del nodo.


* Todos los LIF y las VLAN se han reubicado o eliminado del nodo.
+
** Los LIF de datos han sido link:../networking/delete_a_lif.html["eliminado"] o link:../networking/migrate_a_lif.html["reubicado"] desde el nodo.
** Las LIF de administración de clúster han sido link:../networking/migrate_a_lif.html["reubicado"]del nodo y los puertos de inicio han cambiado.
** Todas las LIF de interconexión de clústeres han sido link:../networking/delete_a_lif.html["quitada"]. Cuando elimina las LIF de interconexión de clústeres, se muestra una advertencia que puede ignorarse.
** Todas las VLAN del nodo han sido link:../networking/configure_vlans_over_physical_ports.html#delete-a-vlan["eliminado"].


* El nodo no participa en ninguna relación de conmutación al respaldo.
+
** Se ha producido la conmutación al link:../high-availability/ha_commands_for_enabling_and_disabling_storage_failover.html["deshabilitado"]nodo de respaldo de almacenamiento.
** Todas las reglas de recuperación tras fallos de LIF han sido link:../networking/commands_for_managing_failover_groups_and_policies.html["modificado"]para quitar puertos del nodo.


* Si el nodo tiene discos de estándar de procesamiento de información federal (FIPS) o discos de autocifrado (SED), link:../encryption-at-rest/return-seds-unprotected-mode-task.html["se ha eliminado el cifrado del disco"]devolviendo los discos al modo no protegido.
+
** Puede que también desee link:../encryption-at-rest/sanitize-fips-drive-sed-task.html["Desinfecte unidades FIPS o SED"].


* Si tiene LUN del nodo que se va a quitar, debe link:../san-admin/modify-slm-reporting-nodes-task.html["Modifique la lista nodos de generación de informes de asignación de LUN selectiva (SLM)"] antes de quitar el nodo.
+
Si no elimina el nodo y su partner de alta disponibilidad de la lista Reporting-Nodes de SLM, se puede perder el acceso a las LUN que anteriormente existían en el nodo aunque los volúmenes que contenían dichas LUN se hayan movido a otro nodo.



Se recomienda emitir un mensaje de AutoSupport para notificar al soporte técnico de NetApp que se está realizando la eliminación de nodos.


IMPORTANT: No realice operaciones como `cluster remove-node` , , `cluster unjoin` y `node rename` cuando una actualización automática de ONTAP está en curso.

.Acerca de esta tarea
* Si ejecuta un clúster de versión mixta, puede eliminar el último nodo de versión baja con uno de los comandos de privilegio avanzados desde ONTAP 9.3:
+
** ONTAP 9.3: `cluster unjoin -skip-last-low-version-node-check`
** ONTAP 9.4 y posterior: `cluster remove-node -skip-last-low-version-node-check`


* Si desune 2 nodos de un clúster de 4 nodos, la alta disponibilidad de clúster se habilita automáticamente en los dos nodos que quedan.



NOTE: Antes de quitar un nodo del clúster, se deben hacer inaccesibles a todos los datos del sistema y del usuario de todos los discos que están conectados al nodo. Si un nodo se desunió incorrectamente desde un clúster, póngase en contacto con el soporte de NetApp para obtener ayuda con las opciones de recuperación.

.Pasos
. Cambie el nivel de privilegio a avanzado:
+
[source, cli]
----
set -privilege advanced
----
. Compruebe si un nodo del clúster contiene épsilon:
+
[source, cli]
----
cluster show -epsilon true
----
. Si un nodo del clúster contiene épsilon y ese nodo se va a desunir, mueva épsilon a un nodo que no se va a desvincular:
+
.. Mueva épsilon del nodo que se va a desunir
+
[source, cli]
----
cluster modify -node <name_of_node_to_be_unjoined> -epsilon false
----
.. Mueva épsilon a un nodo que no se va a desunir:
+
[source, cli]
----
cluster modify -node <node_name> -epsilon true
----


. Identifique el nodo maestro actual:
+
[source, cli]
----
cluster ring show
----
+
El nodo maestro es el nodo que contiene procesos `mgmt` como , , , , `vldb` `vifmgr` `bcomd` y `crs`.

. Si el nodo que desea quitar es el nodo maestro actual, habilite otro nodo del clúster para que se seleccione como nodo maestro:
+
.. Haga que el nodo maestro actual no sea apto para participar en el cluster:
+
[source, cli]
----
cluster modify -node <node_name> -eligibility false
----
+
Esto hará que el nodo se marque como en mal estado hasta que se restaure la elegibilidad en el siguiente paso. Cuando el nodo maestro deja de ser elegible, el quórum del clúster selecciona uno de los nodos restantes como el nuevo nodo principal.

.. Haga que el nodo maestro anterior sea apto para participar de nuevo en el clúster:
+
[source, cli]
----
cluster modify -node <node_name> -eligibility true
----


. Inicie sesión en la LIF de gestión de nodos remotos o en la LIF de gestión de clústeres en un nodo que no sea el que se está quitando.
. Quite el nodo del clúster:
+
|===
| Para esta versión de ONTAP... | Se usa este comando... 


 a| 
ONTAP 9,3
 a| 
[source, cli]
----
cluster unjoin
----


 a| 
ONTAP 9,4 y versiones posteriores
 a| 
Con el nombre de nodo:

[source, cli]
----
cluster remove-node -node <node_name>
----
Con dirección IP del nodo:

[source, cli]
----
cluster remove-node -cluster_ip <node_ip>
----
|===
+
Si tiene un clúster de versión mixta y va a eliminar el último nodo de versión inferior, utilice `-skip-last-low-version-node-check` el parámetro con estos comandos.

+
El sistema le informa de lo siguiente:

+
** También debe quitar del clúster el compañero de conmutación al nodo de respaldo.
** Una vez que se ha eliminado el nodo y antes de poder volver a unirse a un clúster, debe utilizar la opción del menú de arranque (4) limpiar la configuración e inicializar todos los discos u opción (9) Configurar la partición avanzada de unidades para borrar la configuración del nodo e inicializar todos los discos.
+
Se genera un mensaje de fallo si tiene condiciones que debe abordar antes de quitar el nodo. Por ejemplo, el mensaje podría indicar que el nodo tiene recursos compartidos que debe quitar o que el nodo está en una configuración de alta disponibilidad de clúster o en una configuración de recuperación tras fallos de almacenamiento que debe deshabilitar.

+
Si el nodo es el maestro de quórum, el clúster perderá brevemente y volverá al quórum. Esta pérdida de quórum es temporal y no afecta a ninguna operación de datos.



. Si un mensaje de fallo indica condiciones de error, solucione esas condiciones y vuelva a ejecutar `cluster remove-node` `cluster unjoin` el comando o.
+
El nodo se reinicia automáticamente después de que se quita correctamente del clúster.

. Si va a reutilizar el nodo, borre la configuración del nodo e inicialice todos los discos:
+
.. Durante el proceso de inicio, pulse Ctrl-C para mostrar el menú de inicio cuando se le solicite.
.. Seleccione la opción del menú de inicio (4) Limpiar configuración e inicializar todos los discos.


. Volver al nivel de privilegio de administrador:
+
[source, cli]
----
set -privilege admin
----
. Repita los pasos anteriores para eliminar el partner de conmutación por error del clúster.


.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-remove-node.html["cluster remove-node"^]

