---
permalink: system-admin/respond-degraded-system-health-task.html 
sidebar: sidebar 
keywords: respond, degraded, system, health, status, show, alerts, corrective, probable, cause 
summary: Cuando el estado del sistema sea degradado, puede mostrar alertas, leer acerca de la causa probable y las acciones correctivas, mostrar información sobre el subsistema degradado y resolver el problema. También se muestran alertas suprimidas para que pueda modificarlas y ver si se han reconocido. 
---
= Responda al estado del sistema ONTAP degradado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando el estado del sistema es degradado, puede mostrar alertas, leer acerca de la causa probable y acciones correctivas, mostrar información sobre el subsistema degradado y resolver el problema. También se muestran alertas suprimidas para que pueda modificarlas y ver si se han reconocido.

.Acerca de esta tarea
Puede detectar que una alerta se generó viendo un mensaje de AutoSupport o un evento de EMS, o bien utilizando `system health` los comandos.

.Pasos
. Utilice `system health alert show` el comando para ver las alertas que están afectando el estado del sistema.
. Lea la causa probable, el posible efecto y las acciones correctivas de la alerta para determinar si puede resolver el problema o necesita más información.
. Si necesita más información, utilice `system health alert show -instance` el comando para ver la información adicional disponible de la alerta.
. Utilice `system health alert modify` el comando con `-acknowledge` el parámetro para indicar que está trabajando en una alerta específica.
. Tome las acciones correctivas para resolver el problema como se describe en `Corrective Actions` el campo en la alerta.
+
Las acciones correctivas pueden incluir reiniciar el sistema.

+
Cuando se resuelve el problema, la alerta se borra automáticamente. Si el subsistema no tiene otras alertas, el estado del subsistema cambia a `OK`. Si el estado de todos los subsistemas es correcto, el estado general del sistema cambia a `OK`.

. Utilice `system health status show` el comando para confirmar que el estado del sistema es `OK`.
+
Si el estado del sistema no es `OK` , repita este procedimiento.


