---
permalink: system-admin/set-display-preferences-task.html 
sidebar: sidebar 
keywords: set, display, preferences, cli, session, set, rows 
summary: Puede configurar preferencias de visualización para una sesión de la CLI usando el comando set command y rows. Las preferencias definidas se aplican sólo a la sesión en la que se encuentra. No son persistentes en todas las sesiones. 
---
= Configure las preferencias de visualización para la CLI de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar las preferencias de visualización para una sesión de la CLI mediante `set` el comando y `rows` el comando. Las preferencias definidas se aplican sólo a la sesión en la que se encuentra. No son persistentes en todas las sesiones.

.Acerca de esta tarea
Puede configurar las siguientes preferencias de visualización de la CLI:

* El nivel de privilegio de la sesión de comandos
* Si se emiten confirmaciones para comandos potencialmente disruptivos
* Si `show` los comandos muestran todos los campos
* El carácter o caracteres que se van a utilizar como separador de campo
* La unidad predeterminada al informar de tamaños de datos
* El número de filas que muestra la pantalla en la sesión CLI actual antes de que la interfaz detenga la salida
+
Si no se especifica el número preferido de filas, se ajusta automáticamente en función de la altura real del terminal. Si la altura real no está definida, el número predeterminado de filas es 24.

* El nodo o la máquina virtual de almacenamiento predeterminado (SVM)
* Si un comando continue debería detenerse si encuentra un error


.Pasos
. Para configurar las preferencias de visualización de la CLI, utilice `set` el comando.
+
Para establecer el número de filas que muestra la pantalla en la sesión de CLI actual, también puede utilizar `rows` el comando.

+
Obtenga más información sobre `set` y `rows` en el link:https://docs.netapp.com/us-en/ontap-cli/["Referencia de comandos del ONTAP"^].



.Ejemplo de configuración de preferencias de visualización en la CLI
En el siguiente ejemplo, se establece una coma como separador de campos, se define `GB` como la unidad de tamaño de datos predeterminada y el número de filas se establece en 50:

[listing]
----
cluster1::> set -showseparator "," -units GB
cluster1::> rows 50
----
.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=show["mostrar"^]
* link:https://docs.netapp.com/us-en/ontap-cli/set.html["listo"^]
* link:https://docs.netapp.com/us-en/ontap-cli/rows.html["filas"^]

