---
permalink: system-admin/sp-bmc-network-interface--firmware-updates-concept.html 
sidebar: sidebar 
keywords: sp, bmc, network, interface, firmware, update 
summary: Una actualización del firmware del SP que se activa desde ONTAP con el SP que ejecuta la versión 1.5, 2.5, 3.1 o posterior admite el uso de un mecanismo de transferencia de archivos basado en IP a través de la interfaz de red del SP. 
---
= Cuando SP/BMC utiliza la interfaz de red para las actualizaciones de firmware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una actualización del firmware del SP que se activa desde ONTAP con el SP que ejecuta la versión 1.5, 2.5, 3.1 o posterior admite el uso de un mecanismo de transferencia de archivos basado en IP a través de la interfaz de red del SP.

[NOTE]
====
Este tema se aplica tanto al SP como al BMC.

====
Una actualización del firmware del SP a través de la interfaz de red es más rápida que una actualización a través de la interfaz de serie. Reduce la ventana de mantenimiento durante la cual se actualiza el firmware del SP y también no es disruptivo para el funcionamiento de ONTAP. Las versiones del SP compatibles con esta funcionalidad se incluyen en ONTAP. También están disponibles en el sitio de soporte de NetApp y se pueden instalar en controladoras que ejecuten una versión compatible de ONTAP.

Cuando está ejecutando SP versión 1.5, 2.5, 3.1 o posterior, se aplican los siguientes comportamientos de actualización del firmware:

* Una actualización del firmware del SP que es _automáticamente_ activada por ONTAP de forma predeterminada a la utilización de la interfaz de red para la actualización; sin embargo, la actualización automática del SP cambia a utilizar la interfaz de serie para la actualización del firmware si se da alguna de las condiciones siguientes:
+
** La interfaz de red del SP no está configurada o no está disponible.
** Se produce un error en la transferencia del archivo basado en IP.
** El servicio API del SP está deshabilitado.




Independientemente de la versión del SP que esté ejecutando, una actualización del firmware del SP activada desde la CLI de SP siempre utiliza la interfaz de red del SP para la actualización.

.Información relacionada
https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["Descargas de NetApp: Diagnóstico y firmware del sistema"]
