---
permalink: system-admin/ssh-login-security-concept.html 
sidebar: sidebar 
keywords: ssh, login, security, information, view, changes, privileges, unsuccessful, attempts, previous, successful, restrictions, considerations 
summary: A partir de ONTAP 9.5, puede ver información acerca de inicios de sesión anteriores, intentos fallidos de inicio de sesión y cambios en sus privilegios desde el último inicio de sesión correcto. 
---
= Seguridad de inicio de sesión SSH de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.5, puede ver información acerca de inicios de sesión anteriores, intentos fallidos de inicio de sesión y cambios en sus privilegios desde el último inicio de sesión correcto.

La información relacionada con la seguridad se muestra cuando inicia sesión correctamente como usuario administrador de SSH. Se le ha alertado de las siguientes condiciones:

* La última vez que se inició sesión en su nombre de cuenta.
* Número de intentos de inicio de sesión fallidos desde el último inicio de sesión correcto.
* Si el rol ha cambiado desde el último inicio de sesión (por ejemplo, si el rol de la cuenta del administrador ha cambiado de "admin" a "backup").
* Si las funcionalidades de adición, modificación o eliminación del rol se modificaron desde el último inicio de sesión.


[NOTE]
====
Si alguna de las informaciones mostradas es sospechosa, debe ponerse en contacto inmediatamente con su departamento de seguridad.

====
Para obtener esta información al iniciar sesión, se deben cumplir los siguientes requisitos previos:

* Su cuenta de usuario SSH debe estar aprovisionada en ONTAP.
* Se debe crear el inicio de sesión de seguridad SSH.
* Su intento de inicio de sesión debe ser correcto.




== Restricciones y otras consideraciones sobre la seguridad de inicio de sesión SSH

Las siguientes restricciones y consideraciones se aplican a la información de seguridad de inicio de sesión SSH:

* La información solo está disponible para inicios de sesión basados en SSH.
* En el caso de las cuentas admin basadas en grupos, como las cuentas LDAP/NIS y AD, los usuarios pueden ver la información de inicio de sesión SSH si el grupo al que pertenecen se aprovisiona como una cuenta de administrador en ONTAP.
+
Sin embargo, estos usuarios no pueden mostrar alertas sobre los cambios en el rol de la cuenta de usuario. Además, los usuarios que pertenecen a un grupo AD aprovisionado como cuenta de administrador en ONTAP no pueden ver el número de intentos de inicio de sesión fallidos que se produjeron desde la última vez que se iniciaron sesión.

* La información que se mantiene para un usuario se elimina cuando la cuenta de usuario se elimina de ONTAP.
* La información no se muestra para las conexiones con aplicaciones distintas de SSH.




== Ejemplos de información de seguridad de inicio de sesión SSH

Los siguientes ejemplos muestran el tipo de información que se muestra después de iniciar sesión.

* Este mensaje se muestra después de cada inicio de sesión correcto:
+
[listing]
----

Last Login : 7/19/2018 06:11:32
----
* Estos mensajes se muestran si no se han podido iniciar sesión desde la última sesión correcta:
+
[listing]
----

Last Login : 4/12/2018 08:21:26
Unsuccessful login attempts since last login - 5
----
* Estos mensajes se muestran si no se ha podido iniciar sesión y los privilegios se han modificado desde el último inicio de sesión correcto:
+
[listing]
----

Last Login : 8/22/2018 20:08:21
Unsuccessful login attempts since last login - 3
Your privileges have changed since last login
----

