---
permalink: system-admin/structure-autosupport-messages-sent-email-concept.html 
sidebar: sidebar 
keywords: structure, autosupport, messages, sent, email, subject, standard, brief, body, large, attachment, 7z, file, data 
summary: Cuando se envía un mensaje AutoSupport por correo electrónico, el mensaje tiene un asunto estándar, un cuerpo breve y un archivo adjunto grande en formato de archivo 7z que contiene los datos. 
---
= Obtenga información sobre la estructura de los mensajes de ONTAP AutoSupport enviados por correo electrónico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se envía un mensaje AutoSupport por correo electrónico, el mensaje tiene un asunto estándar, un cuerpo breve y un archivo adjunto grande en formato de archivo 7z que contiene los datos.

[NOTE]
====
Si AutoSupport está configurado para ocultar datos privados, cierta información, como el nombre de host, se omite o se oculta en el encabezado, el asunto, el cuerpo y los datos adjuntos.

====


== Asunto

La línea de asunto de los mensajes enviados por el mecanismo AutoSupport contiene una cadena de texto que identifica el motivo de la notificación. El formato de la línea del asunto es el siguiente:

Notificación DE grupo HA de _System_Name_ (_Message_) _Severity_

* _System_Name_ es el nombre de host o el ID del sistema, según la configuración de AutoSupport




== Cuerpo

El cuerpo del mensaje de AutoSupport contiene la siguiente información:

* Fecha y Marca de hora del mensaje
* Versión de ONTAP en el nodo que generó el mensaje
* El ID del sistema, el número de serie y el nombre de host del nodo que generó el mensaje
* Número de secuencia de AutoSupport
* Nombre y ubicación del contacto SNMP, si se especifica
* El ID del sistema y el nombre de host del partner de alta disponibilidad




== Archivos adjuntos

La información clave de un mensaje de AutoSupport contiene archivos comprimidos en un archivo 7z llamado `body.7z` y adjunto al mensaje.

Los archivos contenidos en el archivo adjunto son específicos del tipo de mensaje AutoSupport.
