---
permalink: system-admin/system-health-monitoring-concept.html 
sidebar: sidebar 
keywords: monitor, health, system, cluster, conditions, alert, fault, risk, degraded, status, active 
summary: Los monitores de estado supervisan proactivamente ciertas condiciones críticas de su clúster y generan alertas si detectan una falla o un riesgo. Si hay alertas activas, el estado del sistema informa de un estado degradado para el clúster. Las alertas incluyen la información que necesita para responder a un estado del sistema degradado. 
---
= Supervise el estado de la información general del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los monitores de estado supervisan proactivamente ciertas condiciones críticas de su clúster y generan alertas si detectan una falla o un riesgo. Si hay alertas activas, el estado del sistema informa de un estado degradado para el clúster. Las alertas incluyen la información que necesita para responder a un estado del sistema degradado.

Si el estado es degradado, puede ver detalles del problema, incluidas la causa probable y las acciones de recuperación recomendadas. Después de resolver el problema, el estado del sistema vuelve automáticamente a OK.

El estado del sistema refleja varios monitores de estado independientes. Un estado degradado en un monitor de estado individual provoca un estado degradado para el estado general del sistema.

Si quiere más información sobre cómo ONTAP admite los switches de clúster para supervisar el estado del sistema en el clúster, puede consultar el _Hardware Universe_.

https://["Los switches compatibles del Hardware Universe"^]

Para obtener información detallada sobre las causas de los mensajes de AutoSupport del monitor de estado del switch de clúster (CSHM) y las acciones necesarias para resolver estas alertas, consulte el artículo de la base de conocimientos.

https://["Mensaje de AutoSupport: Proceso del monitor de estado CSHM"]
