---
permalink: system-admin/troubleshoot-autosupport-subsystem-task.html 
sidebar: sidebar 
keywords: troubleshoot, autosupport, subsystem, node, check, show, command, issue, problem, delivery 
summary: Los comandos de comprobaci贸n de nodo del sistema pueden utilizarse para verificar y solucionar los problemas relacionados con la configuraci贸n y la entrega de AutoSupport. 
---
= Solucionar los problemas del subsistema ONTAP AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `system node check show` Los comandos se pueden utilizar para verificar y solucionar los problemas relacionados con la configuraci贸n y la entrega de AutoSupport.

.Paso
. Use los siguientes comandos para mostrar el estado del subsistema AutoSupport.
+
|===
| Se usa este comando... | Para hacer esto... 


 a| 
`system node autosupport check show`
 a| 
Mostrar el estado general del subsistema AutoSupport, como el estado del destino HTTP o HTTPS de AutoSupport, destinos SMTP de AutoSupport, servidor AutoSupport OnDemand y la configuraci贸n de AutoSupport



 a| 
`system node autosupport check show-details`
 a| 
Mostrar el estado detallado del subsistema AutoSupport, como descripciones detalladas de errores y las acciones correctivas

|===

