---
permalink: system-admin/troubleshoot-web-access-problems-concept.html 
sidebar: sidebar 
keywords: troubleshoot, web, services, access, problems, lif, firewall, policy, protocol, engin, digital, certificate, user, access, authorization 
summary: Los errores de configuración provocan problemas de acceso al servicio web. Puede resolver los errores garantizando que la LIF, la política de firewall, el motor de protocolo web, los servicios web, los certificados digitales, y la autorización de acceso del usuario está configurada correctamente. 
---
= Solucionar problemas de acceso al servicio web
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los errores de configuración provocan problemas de acceso al servicio web. Puede resolver los errores garantizando que la LIF, la política de firewall, el motor de protocolo web, los servicios web, los certificados digitales, y la autorización de acceso del usuario está configurada correctamente.

La tabla siguiente le ayuda a identificar y solucionar errores de configuración del servicio web:

|===
| Este problema de acceso... | Se produce debido a este error de configuración... | Para solucionar el error... 


 a| 
Su navegador web devuelve un `unable to connect` `failure to establish a connection` error OR cuando intenta acceder a un servicio web.
 a| 
Es posible que el LIF se haya configurado incorrectamente.
 a| 
Asegúrese de que puede hacer ping al LIF que proporciona el servicio web.

[NOTE]
====
Usted utiliza `network ping` el comando para hacer ping a una LIF. Para obtener información acerca de la configuración de red, consulte la _Network Management Guide_.

====


 a| 
Es posible que el firewall esté configurado incorrectamente.
 a| 
Asegúrese de que se haya configurado una política de firewall para que sea compatible con HTTP o HTTPS y de que la política esté asignada a la LIF que proporciona el servicio web.

[NOTE]
====
Los `system services firewall policy` comandos se utilizan para administrar las políticas de firewall. Puede utilizar `network interface modify` el comando con `-firewall-policy` el parámetro para asociar una política a una LIF.

====


 a| 
Es posible que el motor de protocolo web esté desactivado.
 a| 
Asegúrese de que el motor de protocolo web está activado para que los servicios web estén accesibles.

[NOTE]
====
 `system services web`Los comandos se usan para administrar el motor de protocolo web del clúster.

====


 a| 
Su navegador web devuelve un `not found` error cuando intenta acceder a un servicio web.
 a| 
Es posible que el servicio web esté desactivado.
 a| 
Asegúrese de que todos los servicios web a los que desea permitir el acceso están habilitados individualmente.

[NOTE]
====
El `vserver services web modify` comando se utiliza para habilitar un servicio web para el acceso.

====


 a| 
El explorador Web no puede iniciar sesión en un servicio Web con el nombre de cuenta y la contraseña de un usuario.
 a| 
El usuario no se puede autenticar, el método de acceso no es correcto o el usuario no está autorizado a acceder al servicio web.
 a| 
Asegúrese de que la cuenta de usuario exista y esté configurada con el método de acceso y el método de autenticación correctos. Asimismo, asegúrese de que la función del usuario está autorizada para acceder al servicio web.

[NOTE]
====
Los `security login` comandos se utilizan para administrar las cuentas de usuario y sus métodos de acceso y métodos de autenticación. Para acceder al servicio web de la API de ONTAP se requiere `ontapi` el método de acceso. El acceso a todos los demás servicios web requiere el `http` método de acceso. Los `vserver services web access` comandos se utilizan para gestionar el acceso de un rol a un servicio web.

====


 a| 
Se conecta al servicio web con HTTPS y el explorador web indica que la conexión se ha interrumpido.
 a| 
Es posible que no tenga habilitado SSL en el clúster ni la SVM que proporciona el servicio web.
 a| 
Compruebe que el clúster o la SVM tengan habilitada SSL y que el certificado digital sea válido.

[NOTE]
====
Los `security ssl` comandos se utilizan para administrar la configuración SSL para servidores HTTP y `security certificate show` el comando para mostrar información de certificados digitales.

====


 a| 
Se conecta al servicio web mediante HTTPS y el navegador web indica que la conexión no es de confianza.
 a| 
Es posible que utilice un certificado digital autofirmado.
 a| 
Compruebe que el certificado digital asociado con el clúster o la SVM esté firmado por una CA de confianza.

[NOTE]
====
El `security certificate generate-csr` comando se utiliza para generar una solicitud de firma de certificación digital y `security certificate install` el comando para instalar un certificado digital firmado por una CA. Utilizarás `security ssl` los comandos para gestionar la configuración de SSL del clúster o la SVM que proporciona el servicio web.

====
|===
.Información relacionada
* link:https://docs.netapp.com/us-en/ontap-cli/network-ping.html["ping de red"^]
* link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["modificación de la interfaz de red"]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-generate-csr.html["Generación de certificado de seguridad CSR"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["instalación del certificado de seguridad"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-show.html["Mostrar certificado de seguridad"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+ssl["seguridad SSL"^]

