---
permalink: system-admin/types-autosupport-messages-reference.html 
sidebar: sidebar 
keywords: active, iq, autosupport, messages, content, support, subsystems 
summary: 'Los mensajes AutoSupport contienen información de estado acerca de los subsistemas compatibles. Saber qué contienen los mensajes de AutoSupport puede ayudarle a interpretar o a responder a los mensajes que reciba por correo electrónico o que aparecen en el sitio Web de Active IQ (anteriormente denominado My AutoSupport).' 
---
= Tipos de mensajes de AutoSupport y su contenido
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los mensajes AutoSupport contienen información de estado acerca de los subsistemas compatibles. Saber qué contienen los mensajes de AutoSupport puede ayudarle a interpretar o a responder a los mensajes que reciba por correo electrónico o que aparecen en el sitio Web de Active IQ (anteriormente denominado My AutoSupport).

|===
| Tipo de mensaje | Tipo de datos que contiene el mensaje 


 a| 
Activado por evento
 a| 
Archivos que contienen datos contextuales sobre el subsistema específico en el que se produjo el evento



 a| 
Todos los días
 a| 
Archivos de registro



 a| 
Rendimiento
 a| 
Datos de rendimiento muestreados durante las 24 horas anteriores



 a| 
Semanal
 a| 
Datos de configuración y estado



 a| 
Activado por la `system node autosupport invoke` comando
 a| 
Depende del valor especificado en la `-type` parámetro:

* `test` envía un mensaje activado por el usuario con algunos datos básicos.
+
Este mensaje también activa una respuesta de correo electrónico automática del soporte técnico a cualquier dirección de correo electrónico especificada mediante el `-to` Para confirmar que se están recibiendo mensajes de AutoSupport.

* `performance` envía datos de rendimiento.
* `all` envía un mensaje activado por el usuario con un conjunto completo de datos similar al mensaje semanal, incluidos los datos de resolución de problemas de cada subsistema.
+
El soporte técnico normalmente solicita este mensaje.





 a| 
Activado por la `system node autosupport invoke-core-upload` comando
 a| 
Archivos de volcado principales para un nodo



 a| 
Activado por la `system node autosupport invoke-performance-archive` comando
 a| 
Archivos de archivado de rendimiento durante un periodo de tiempo específico



 a| 
Activado por AutoSupport OnDemand
 a| 
AutoSupport OnDemand puede solicitar mensajes nuevos o pasados:

* Los mensajes nuevos, dependiendo del tipo de colección AutoSupport, pueden ser `test`, `all`, o. `performance`.
* Los mensajes anteriores dependen del tipo de mensaje que se vuelva a enviar.


AutoSupport OnDemand puede solicitar nuevos mensajes que cargan los siguientes archivos en el sitio de soporte de NetApp en http://["mysupport.netapp.com"]:

* Volcado de memoria
* Archivado del rendimiento


|===