---
permalink: system-admin/upload-core-dump-files-task.html 
sidebar: sidebar 
keywords: upload, core, dump, file, autosupport, device, send, messages, email 
summary: Cuando se guarda un archivo de volcado principal, se genera un mensaje de evento. Si el servicio AutoSupport está habilitado y configurado para enviar mensajes al soporte de NetApp, se transmite un mensaje AutoSupport y se le envía un mensaje de correo electrónico de confirmación automatizado. 
---
= Cargar archivos de volcado de memoria ONTAP AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se guarda un archivo de volcado principal, se genera un mensaje de evento. Si el servicio AutoSupport está habilitado y configurado para enviar mensajes al soporte de NetApp, se transmite un mensaje AutoSupport y se le envía un mensaje de correo electrónico de confirmación automatizado.

.Antes de empezar
* Configuró AutoSupport con los siguientes ajustes:
+
** AutoSupport está habilitado en el nodo.
** AutoSupport está configurado para enviar mensajes al soporte técnico.
** AutoSupport se configura para utilizar el protocolo de transporte HTTPS.
+
El protocolo de transporte SMTP no se admite cuando se envían mensajes que incluyen archivos de gran tamaño, como archivos de volcado principales.





.Acerca de esta tarea
También se puede cargar el archivo de volcado de memoria a través del servicio AutoSupport a través de HTTPS mediante `system node autosupport invoke-core-upload` el comando, si lo solicita el soporte de NetApp.

https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_upload_an_ONTAP_9_core_file_for_analysis["Cómo cargar un archivo principal de ONTAP 9 para su análisis"^]

.Pasos
. Para ver los archivos de volcado de memoria de un nodo con `system node coredump show` el comando.
+
En el siguiente ejemplo, se muestran los archivos de volcado principales para el nodo local:

+
[listing]
----
cluster1::> system node coredump show -node local
Node:Type Core Name Saved Panic Time
--------- ------------------------------------------- ----- -----------------
node:kernel
core.4073000068.2013-09-11.15_05_01.nz true 9/11/2013 15:05:01
----
. Genere un mensaje de AutoSupport y cargue un archivo de volcado de memoria mediante `system node autosupport invoke-core-upload` el comando.
+
En el siguiente ejemplo, se genera un mensaje de AutoSupport y se envía a la ubicación predeterminada, es decir, al soporte técnico, y el archivo de volcado principal se carga en la ubicación predeterminada, que es el sitio de soporte de NetApp:

+
[listing]
----
cluster1::> system node autosupport invoke-core-upload -core-filename
core.4073000068.2013-09-11.15_05_01.nz -node local
----
+
En el ejemplo siguiente, se genera un mensaje de AutoSupport que se envía a la ubicación especificada en el URI y el archivo de volcado principal se carga en el URI:

+
[listing]
----
cluster1::> system node autosupport invoke-core-upload -uri https//files.company.com -core-filename
core.4073000068.2013-09-11.15_05_01.nz -node local
----

