---
permalink: system-admin/upload-core-dump-files-task.html 
sidebar: sidebar 
keywords: upload, core, dump, file, autosupport, device, send, messages, email 
summary: Cuando se guarda un archivo de volcado principal, se genera un mensaje de evento. Si el servicio AutoSupport está habilitado y configurado para enviar mensajes al soporte de NetApp, se transmite un mensaje AutoSupport y se le envía un mensaje de correo electrónico de confirmación automatizado. 
---
= Cargar archivos de volcado de memoria ONTAP AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se guarda un archivo de volcado principal, se genera un mensaje de evento. Si el servicio AutoSupport está habilitado y configurado para enviar mensajes al soporte de NetApp, se transmite un mensaje AutoSupport y se le envía un mensaje de correo electrónico de confirmación automatizado.

.Lo que necesitará
* Debe haber configurado AutoSupport con las siguientes opciones:
+
** AutoSupport está habilitado en el nodo.
** AutoSupport está configurado para enviar mensajes al soporte técnico.
** AutoSupport está configurado para utilizar el protocolo de transporte HTTP o HTTPS.
+
El protocolo de transporte SMTP no se admite cuando se envían mensajes que incluyen archivos de gran tamaño, como archivos de volcado principales.





.Acerca de esta tarea
También se puede cargar el archivo de volcado principal a través del servicio AutoSupport mediante HTTPS con el `system node autosupport invoke-core-upload` Si lo solicita el soporte de NetApp.

https://kb.netapp.com/Advice_and_Troubleshooting/Miscellaneous/How_to_upload_a_file_to_NetApp["Cómo cargar un archivo en NetApp"^]

.Pasos
. Vea los archivos de volcado principales de un nodo mediante el `system node coredump show` comando.
+
En el siguiente ejemplo, se muestran los archivos de volcado principales para el nodo local:

+
[listing]
----
cluster1::> system node coredump show -node local
Node:Type Core Name Saved Panic Time
--------- ------------------------------------------- ----- -----------------
node:kernel
core.4073000068.2013-09-11.15_05_01.nz true 9/11/2013 15:05:01
----
. Genere un mensaje de AutoSupport y cargue un archivo de volcado principal con la `system node autosupport invoke-core-upload` comando.
+
En el siguiente ejemplo, se genera un mensaje de AutoSupport y se envía a la ubicación predeterminada, es decir, al soporte técnico, y el archivo de volcado principal se carga en la ubicación predeterminada, que es el sitio de soporte de NetApp:

+
[listing]
----
cluster1::> system node autosupport invoke-core-upload -core-filename
core.4073000068.2013-09-11.15_05_01.nz -node local
----
+
En el ejemplo siguiente, se genera un mensaje de AutoSupport que se envía a la ubicación especificada en el URI y el archivo de volcado principal se carga en el URI:

+
[listing]
----
cluster1::> system node autosupport invoke-core-upload -uri https//files.company.com -core-filename
core.4073000068.2013-09-11.15_05_01.nz -node local
----

