---
permalink: system-admin/verify-monitor-cluster-management-network-switches-task.html 
sidebar: sidebar 
keywords: verify, monitor, cluster, management, network, switches, heath, monitor 
summary: El monitor de estado del switch de clúster intenta supervisar automáticamente los switches que detecta; sin embargo, es posible que la supervisión no se produzca de manera automática si los switches no se han configurado correctamente. Debe verificar que el monitor de estado esté correctamente configurado para supervisar los switches. 
---
= Compruebe la supervisión de los switches de red de clúster y de gestión
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El monitor de estado del switch de clúster intenta supervisar automáticamente los switches que detecta; sin embargo, es posible que la supervisión no se produzca de manera automática si los switches no se han configurado correctamente. Debe verificar que el monitor de estado esté correctamente configurado para supervisar los switches.

.Pasos
. Para identificar los switches que detectó el monitor de estado del switch del clúster, introduzca el siguiente comando:
+
[role="tabbed-block"]
====
.ONTAP 9,8 y versiones posteriores
--
`system switch ethernet show`

--
.ONTAP 9,7 y anteriores
--
`system cluster-switch show`

--
====
+
Si la `Model` columna muestra el valor `OTHER`, Entonces ONTAP no puede supervisar el conmutador. ONTAP establece el valor en `OTHER` si un switch que detecta automáticamente no es compatible con la supervisión del estado.

+
[NOTE]
====
Si un switch no se muestra en el resultado del comando, debe configurar la detección del switch.

====
. Actualice al software de switch más reciente admitido y consulte el archivo de configuración (RCF) desde el sitio de soporte de NetApp.
+
http://support.netapp.com/NOW/download/software/cm_switches/["Página de descargas de soporte de NetApp"^]

+
La cadena de comunidad en el RCF del conmutador debe coincidir con la cadena de comunidad que el monitor de estado está configurado para utilizar. De forma predeterminada, el monitor de estado utiliza la cadena de comunidad `cshm1!`.

+
[NOTE]
====
En este momento, el monitor de estado sólo admite SNMPv2.

====
+
Si necesita cambiar información sobre un switch que supervisa el clúster, puede modificar la cadena de comunidad que utiliza el monitor de estado mediante el siguiente comando:

+
[role="tabbed-block"]
====
.ONTAP 9,8 y versiones posteriores
--
`system switch ethernet modify`

--
.ONTAP 9,7 y anteriores
--
`system cluster-switch modify`

--
====
. Compruebe que el puerto de gestión del switch está conectado a la red de gestión.
+
Esta conexión es necesaria para realizar consultas SNMP.


