---
permalink: system-admin/when-where-autosupport-messages-sent-concept.html 
sidebar: sidebar 
keywords: active, iq, digital advisor, active iq, autosupport, messages, email, manual, scheduled, event, triggered 
summary: AutoSupport envûÙa mensajes a diferentes destinatarios, en funciû°n del tipo de mensaje. Saber cuûÀndo y dû°nde envûÙa los mensajes AutoSupport puede ayudarle a comprender los mensajes que recibe por correo electrû°nico o los ve en el sitio web del asesor digital. 
---
= Descubra cuûÀndo y dû°nde se envûÙan los mensajes de ONTAP AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport envûÙa mensajes a diferentes destinatarios, en funciû°n del tipo de mensaje. Saber cuûÀndo y dû°nde envûÙa los mensajes AutoSupport puede ayudarle a comprender los mensajes que recibe por correo electrû°nico o los ve en el sitio web del asesor digital.

A menos que se especifique lo contrario, la configuraciû°n de las siguientes tablas son parûÀmetros del `system node autosupport modify` comando.



[[event-triggered-messages]]
== Mensajes activados por eventos

Cuando se producen eventos en el sistema que requieren una acciû°n correctiva, AutoSupport envûÙa automûÀticamente un mensaje activado por el evento.

|===
| Cuando se envûÙa el mensaje | Dû°nde se envûÙa el mensaje 


 a| 
AutoSupport responde a un evento desencadenante en EMS
 a| 
Direcciones especificadas en `-to` y `-noteto`. (Solo se envûÙan los eventos crûÙticos que afectan al servicio).

Direcciones especificadas en `-partner-address`

Soporte tûˋcnico, si `-support` se establece en `enable`

|===


[[scheduled-messages]]
== Mensajes programados

AutoSupport envûÙa automûÀticamente varios mensajes con una programaciû°n normal.

|===
| Cuando se envûÙa el mensaje | Dû°nde se envûÙa el mensaje 


 a| 
Diario (por defecto, enviado entre las 12:00 a.m. y las 1:00 a.m. como mensaje de registro)
 a| 
Direcciones especificadas en `-partner-address`

Soporte tûˋcnico, si `-support` se establece en `enable`



 a| 
Diario (por defecto, se envûÙa entre las 12:00 a.m. y las 1:00 a.m. como mensaje de rendimiento), si el `-perf` parûÀmetro estûÀ establecido en `true`
 a| 
Direcciones especificadas en -Partner-address'

Soporte tûˋcnico, si `-support` se establece en `enable`



 a| 
Semanal (por defecto, enviado el domingo entre las 12:00 a.m. y las 1:00 a.m.)
 a| 
Direcciones especificadas en `-partner-address`

Soporte tûˋcnico, si `-support` se establece en `enable`

|===


[[manually-triggered-messages]]
== Mensajes activados manualmente

Puede iniciar o reenviar manualmente un mensaje de AutoSupport.

|===
| Cuando se envûÙa el mensaje | Dû°nde se envûÙa el mensaje 


 a| 
Puede iniciar un mensaje de forma manual con `system node autosupport invoke` el comando
 a| 
Si se especifica un URI mediante `-uri` el parûÀmetro del `system node autosupport invoke` comando, el mensaje se envûÙa a ese URI.

Si `-uri` se omite, el mensaje se envûÙa a las direcciones especificadas en `-to` y `-partner-address`. El mensaje tambiûˋn se envûÙa al soporte tûˋcnico si `-support` se establece en `enable`.



 a| 
Puede iniciar un mensaje de forma manual con `system node autosupport invoke-core-upload` el comando
 a| 
Si se especifica un URI con `-uri` el parûÀmetro en `system node autosupport invoke-core-upload` el comando, el mensaje se envûÙa a ese URI y el archivo de volcado de memoria se carga en el URI.

Si `-uri` se omite en el `system node autosupport invoke-core-upload` comando, el mensaje se envûÙa al soporte tûˋcnico y el archivo de volcado de memoria se carga en el sitio de soporte tûˋcnico.

Ambos escenarios requieren que `-support` estûˋ definido en `enable` y `-transport` estûˋ definido en `https` o `http`.

Debido al gran tamaûÝo de los archivos de volcado de memoria, no se envûÙa el mensaje a las direcciones especificadas en los `-to` `-partner-addresses` parûÀmetros y.



 a| 
Puede iniciar un mensaje de forma manual con `system node autosupport invoke-performance-archive` el comando
 a| 
Si se especifica un URI mediante `-uri` el parûÀmetro del `system node autosupport invoke-performance-archive` comando, el mensaje se envûÙa a ese URI y el archivo de almacenamiento de rendimiento se carga en el URI.

Si `-uri` se omite en `system node autosupport invoke-performance-archive` , el mensaje se envûÙa al soporte tûˋcnico y el archivo de archivo de rendimiento se carga en el sitio de soporte tûˋcnico.

Ambos escenarios requieren que `-support` estûˋ definido en `enable` y `-transport` estûˋ definido en `https` o `http`.

Debido al gran tamaûÝo de los archivos de almacenamiento de rendimiento, el mensaje no se envûÙa a las direcciones especificadas en los `-to` `-partner-addresses` parûÀmetros y.



 a| 
Se debe reenviar manualmente un mensaje pasado con `system node autosupport history retransmit` el comando
 a| 
Solo al URI que especifique en el `-uri` parûÀmetro `system node autosupport history retransmit` del comando

|===


[[messages-triggered-by-technical-support]]
== Mensajes activados por el soporte tûˋcnico

El soporte tûˋcnico puede solicitar mensajes de AutoSupport con la funciû°n AutoSupport OnDemand.

|===
| Cuando se envûÙa el mensaje | Dû°nde se envûÙa el mensaje 


 a| 
Cuando AutoSupport obtiene instrucciones de entrega para generar nuevos mensajes de AutoSupport
 a| 
Direcciones especificadas en `-partner-address`

El soporte tûˋcnico, si `-support` se establece en `enable` y `-transport` se establece en `https`



 a| 
Cuando AutoSupport obtiene instrucciones de entrega para reenviar mensajes anteriores de AutoSupport
 a| 
El soporte tûˋcnico, si `-support` se establece en `enable` y `-transport` se establece en `https`



 a| 
Cuando AutoSupport obtiene instrucciones de entrega para generar nuevos mensajes de AutoSupport que cargan archivos de volcado principales o de archivo de rendimiento
 a| 
Soporte tûˋcnico, si `-support` se establece en `enable` y `-transport` se establece en `https`. El volcado principal o el archivo de archivado de rendimiento se cargan en el sitio de soporte tûˋcnico.

|===