---
permalink: authentication/create-svm-user-accounts-task.html 
sidebar: sidebar 
keywords: create, login accounts 
summary: Puede habilitar cuentas de administrador de SVM y de clúster local o remoto. Una cuenta local es aquella en la que reside la información de la cuenta, la clave pública o el certificado de seguridad en el sistema de almacenamiento. La información DE la cuenta DE AD se almacena en un controlador de dominio. Las cuentas LDAP y NIS residen en servidores LDAP y NIS. 
---
= Obtenga más información sobre la creación de cuentas de inicio de sesión de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar cuentas de administrador de SVM y de clúster local o remoto. Una cuenta local es aquella en la que reside la información de la cuenta, la clave pública o el certificado de seguridad en el sistema de almacenamiento. La información DE la cuenta DE AD se almacena en un controlador de dominio. Las cuentas LDAP y NIS residen en servidores LDAP y NIS.



== Administradores de clústeres y SVM

Un administrador de _cluster_ accede a la SVM de administrador del clúster. La SVM de administrador y un administrador de clúster con el nombre reservado `admin` se crean automáticamente cuando se configura el clúster.

Un administrador de clústeres con `admin` el rol predeterminado puede administrar todo el clúster y sus recursos. El administrador de clúster puede crear administradores de clúster adicionales con diferentes roles según sea necesario.

Un administrador de _SVM_ accede a una SVM de datos. El administrador de clúster crea SVM de datos y administradores de SVM según sea necesario.

 `vsadmin`De forma predeterminada, a los administradores de SVM se les asigna el rol. El administrador de clúster puede asignar diferentes roles a los administradores de SVM según sea necesario.



=== Convenciones de nomenclatura

Los siguientes nombres genéricos no se pueden utilizar para cuentas de administrador de SVM o de clúster remoto:

* adm
* bandeja
* cli
* demonio
* ftp
* “juegos”
* detener
* lp
* correo
* «hombre»
* «naroot»
* «NetApp»
* «noticias»
* «nadie»
* operador
* «raíz»
* apagado
* sshd
* sincronizar
* sistema
* uucp
* «www»




== Roles fusionados

Si habilita varias cuentas remotas para el mismo usuario, se le asigna la unión de todas las funciones especificadas para las cuentas. Es decir, si se asigna `vsadmin` el rol a una cuenta de LDAP o NIS y se asigna `vsadmin-volume` el rol a la cuenta de grupo de AD para el mismo usuario, el usuario de AD inicia sesión con las `vsadmin` capacidades más inclusivas. Se dice que los roles son _fusionado_.
