---
permalink: authentication/enable-ssl-certificate-accounts-task.html 
sidebar: sidebar 
keywords: enable, ssl certificate, accounts, security login create 
summary: Puede usar el comando Security login create para habilitar cuentas de administrador para acceder a un administrador o una SVM de datos con un certificado SSL. 
---
= Habilite cuentas de certificado SSL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `security login create` Comando para habilitar las cuentas de administrador para acceder a una SVM de administrador o de datos con un certificado SSL.

.Acerca de esta tarea
* Para que la cuenta pueda acceder a la SVM, debe instalar un certificado digital de servidor firmado por CA.
+
xref:install-server-certificate-cluster-svm-ssl-server-task.adoc[Generar e instalar un certificado de servidor firmado por CA]

+
Puede realizar esta tarea antes o después de habilitar el acceso a la cuenta.

* Si no está seguro del rol de control de acceso que desea asignar a la cuenta de inicio de sesión, puede añadir el rol más adelante con la `security login modify` comando.
+
xref:modify-role-assigned-administrator-task.adoc[Modificar el rol asignado a un administrador]




NOTE: Para las cuentas de administrador de clúster, se admite la autenticación de certificados con el `http`, `ontapi`, y. `rest` más grandes. Para las cuentas de administrador de SVM, la autenticación de certificados solo se admite con el `ontapi` y.. `rest` más grandes.

.Paso
. Habilite las cuentas de administrador local para acceder a una SVM mediante un certificado SSL:
+
`security login create -vserver SVM_name -user-or-group-name user_or_group_name -application application -authmethod authentication_method -role role -comment comment`

+
Para obtener una sintaxis de comando completa, consulte la link:../concepts/manual-pages.html["Páginas manuales de ONTAP por versión"].

+
El siguiente comando habilita la cuenta de administrador de SVM `svmadmin2` con el valor predeterminado `vsadmin` Rol para acceder a la SVM``engData2`` Mediante un certificado digital SSL.

+
[listing]
----
cluster1::>security login create -vserver engData2 -user-or-group-name svmadmin2 -application ontapi -authmethod cert
----


.Después de terminar
Si no instaló un certificado digital de servidor firmado por CA, debe hacerlo para que la cuenta pueda acceder a la SVM.

xref:install-server-certificate-cluster-svm-ssl-server-task.adoc[Generar e instalar un certificado de servidor firmado por CA]
