---
permalink: authentication/enable-password-account-access-task.html 
sidebar: sidebar 
keywords: enable, password, account, access 
summary: Puede usar el comando Security login create para habilitar las cuentas de administrador para acceder a un administrador o una SVM de datos con una contraseña. Se le pedirá la contraseña después de introducir el comando. 
---
= Active el acceso a la cuenta de contraseña
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `security login create` Comando para habilitar las cuentas de administrador para acceder a una SVM de administrador o de datos con una contraseña. Se le pedirá la contraseña después de introducir el comando.

.Acerca de esta tarea
Si no está seguro de la función de control de acceso que desea asignar a la cuenta de inicio de sesión, puede usar la `security login modify` comando para añadir el rol más adelante.

.Antes de empezar
Para realizar esta tarea, debe ser un administrador de clústeres.

.Paso
. Habilite las cuentas de administrador local para acceder a una SVM mediante una contraseña:
+
`security login create -vserver _SVM_name_ -user-or-group-name _user_or_group_name_ -application _application_ -authmethod _authentication_method_ -role _role_ -comment _comment_`

+
Para obtener una sintaxis completa del comando, consulte link:config-worksheets-reference.html["hoja de trabajo"].

+
El siguiente comando habilita la cuenta de administrador de clúster `admin1` con los predefinidos `backup` Rol para acceder a la SVM de administrador``engCluster`` usar una contraseña. Se le pedirá la contraseña después de introducir el comando.

+
[listing]
----
cluster1::>security login create -vserver engCluster -user-or-group-name admin1 -application ssh -authmethod password -role backup
----

