---
permalink: authentication/enable-ad-users-groups-access-cluster-svm-task.html 
sidebar: sidebar 
keywords: configure, active directory, domain, controller access 
summary: Para poder acceder a la SVM, es necesario configurar el acceso de la controladora de dominio de AD al clúster o a la SVM. Si ya ha configurado un servidor SMB para una SVM de datos, puede configurar la SVM como una puerta de enlace o túnel para el acceso de AD al clúster. Si no configuró un servidor SMB, puede crear una cuenta de equipo para la SVM en el dominio de AD. 
---
= Configurar la información general de acceso al controlador de dominio de Active Directory
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para poder acceder a la SVM, es necesario configurar el acceso de la controladora de dominio de AD al clúster o a la SVM. Si ya ha configurado un servidor SMB para una SVM de datos, puede configurar la SVM como puerta de enlace, o _tunnel_, para el acceso de AD al clúster. Si no configuró un servidor SMB, puede crear una cuenta de equipo para la SVM en el dominio de AD.

ONTAP admite los siguientes servicios de autenticación de controladores de dominio:

* Kerberos
* LDAP
* Netlogon
* Autoridad de seguridad local (LSA)


ONTAP admite los siguientes algoritmos de clave de sesión para conexiones seguras de Netlogon:

|===


| Algoritmo de clave de sesión | Disponible en... 


| HMAC-SHA256, basado en el estándar de cifrado avanzado (AES) | ONTAP 9.10.1 y posteriores 


| DES y HMAC-MD5 (cuando se establece la clave fuerte) | Todas las versiones de ONTAP 9 
|===
Si desea utilizar claves de sesión AES durante el establecimiento de canal seguro de Netlogon en ONTAP 9.10.1 y posterior, debe habilitarlas utilizando el siguiente comando:

`cifs security modify -vserver vs1 -aes-enabled-for-netlogon-channel true`

El valor predeterminado es `false`.

En las versiones de ONTAP anteriores a 9.10.1, si el controlador de dominio aplica AES para servicios de Netlogon seguros, la conexión falla. El controlador de dominio debe configurarse para aceptar conexiones de clave segura con ONTAP en estas versiones.
