---
permalink: authentication/grant-access-nis-ldap-user-accounts-task.html 
sidebar: sidebar 
keywords: enable, ldap, nis, account access 
summary: Puede utilizar el comando Security login create para habilitar cuentas de usuario LDAP o NIS con el fin de acceder a un administrador o a una SVM de datos. Si no ha configurado el acceso del servidor LDAP o NIS a la SVM, debe hacerlo antes de que la cuenta pueda acceder a la SVM. 
---
= Habilite el acceso a cuenta de LDAP o NIS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `security login create` Comando para habilitar cuentas de usuario LDAP o NIS para acceder a un administrador o una SVM de datos. Si no ha configurado el acceso del servidor LDAP o NIS a la SVM, debe hacerlo antes de que la cuenta pueda acceder a la SVM.

.Acerca de esta tarea
* Las cuentas de grupo no son compatibles.
* Para que la cuenta pueda acceder a la SVM, debe configurar el acceso del servidor LDAP o NIS con la SVM.
+
xref:enable-nis-ldap-users-access-cluster-task.adoc[Configurar el acceso a servidores LDAP o NIS]

+
Puede realizar esta tarea antes o después de habilitar el acceso a la cuenta.

* Si no está seguro de la función de control de acceso que desea asignar a la cuenta de inicio de sesión, puede usar la `security login modify` comando para añadir el rol más adelante.
+
xref:modify-role-assigned-administrator-task.adoc[Modificar el rol asignado a un administrador]

* A partir de ONTAP 9.4, la autenticación multifactor (MFA) es compatible para usuarios remotos a través de servidores LDAP o NIS.
* A partir de ONTAP 9.11.1, se puede utilizar link:../nfs-admin/ldap-fast-bind-nsswitch-authentication-task.html["Enlace rápido LDAP para la autenticación nsswitch"] Si es compatible con el servidor LDAP.
* Debido a un problema LDAP conocido, no debe utilizar el `':'` (Dos puntos) carácter en cualquier campo de la información de la cuenta de usuario LDAP (por ejemplo, `gecos`, `userPassword`, y así sucesivamente). De lo contrario, la operación de búsqueda fallará para ese usuario.


.Antes de empezar
Para realizar esta tarea, debe ser un administrador de clústeres.

.Pasos
. Habilite las cuentas de usuario o grupo de LDAP o NIS para acceder a una SVM:
+
`security login create -vserver SVM_name -user-or-group-name user_name -application application -authmethod nsswitch -role role -comment comment -is-ns-switch-group yes|no [-is-ldap-fastbind true]`

+
Para obtener una sintaxis completa del comando, consulte link:config-worksheets-reference.html["hoja de trabajo"].

+
link:config-worksheets-reference.html["Crear o modificar cuentas de inicio de sesión"]

+
El siguiente comando habilita la cuenta de administrador de clúster LDAP o NIS `guest2` con los predefinidos `backup` Rol para acceder a la SVM de administrador``engCluster``.

+
[listing]
----
cluster1::>security login create -vserver engCluster -user-or-group-name guest2 -application ssh -authmethod nsswitch -role backup
----
. Habilitar el inicio de sesión MFA para usuarios de LDAP o NIS:
+
``security login modify -user-or-group-name rem_usr1 -application ssh -authentication-method nsswitch -role admin -is-ns-switch-group no -second-authentication-method publickey``

+
El método de autenticación se puede especificar como `publickey` y el segundo método de autenticación como `nsswitch`.

+
En el siguiente ejemplo, se muestra la autenticación MFA que está habilitada:

+
[listing]
----
cluster-1::*> security login modify -user-or-group-name rem_usr2 -application ssh -authentication-method nsswitch -vserver
cluster-1 -second-authentication-method publickey"
----


.Después de terminar
Si no ha configurado el acceso del servidor LDAP o NIS a la SVM, debe hacerlo antes de que la cuenta pueda acceder a la SVM.

xref:enable-nis-ldap-users-access-cluster-task.adoc[Configurar el acceso a servidores LDAP o NIS]
