---
permalink: authentication/index.html 
sidebar: sidebar 
keywords: decide, overview, administrator, authentication, rbac, role-based, access, control 
summary: 'Puede habilitar cuentas de inicio de sesión para los administradores del clúster ONTAP y los administradores de máquinas virtuales de almacenamiento (SVM). También es posible usar el control de acceso basado en roles (RBAC) para definir las funcionalidades de los administradores.' 
---
= Autenticación de administrador y información general de RBAC con la interfaz de línea de comandos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar cuentas de inicio de sesión para los administradores del clúster ONTAP y los administradores de máquinas virtuales de almacenamiento (SVM). También es posible usar el control de acceso basado en roles (RBAC) para definir las funcionalidades de los administradores.

Las cuentas de inicio de sesión y RBAC se habilitan de las siguientes maneras:

* Desea usar la interfaz de línea de comandos (CLI) de ONTAP, no System Manager ni una herramienta de secuencias de comandos automatizada.
* Quiere utilizar las prácticas recomendadas, no explorar todas las opciones disponibles.
* No utiliza SNMP para recopilar información sobre el clúster.

