---
permalink: authentication/lock-unlock-user-account-task.html 
sidebar: sidebar 
keywords: lock, unlock, administrator account 
summary: Puede utilizar el comando Security login lock para bloquear una cuenta de administrador y el comando Security login unlock para desbloquear la cuenta. 
---
= Bloquear y desbloquear una cuenta de administrador de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `security login lock` comando para bloquear una cuenta de administrador y el `security login unlock` comando para desbloquear la cuenta.

.Antes de empezar
Para poder realizar estas tareas, debe ser un administrador de clústeres.

.Pasos
. Bloquear una cuenta de administrador:
+
`security login lock -vserver SVM_name -username user_name`

+
El siguiente comando bloquea la cuenta de administrador de `admin1` la SVM``vs1.example.com``:

+
[listing]
----
cluster1::>security login lock -vserver engData -username admin1
----
+
Obtenga más información sobre `security login lock` en el link:https://docs.netapp.com/us-en/ontap-cli/security-login-lock.html["Referencia de comandos del ONTAP"^].

. Desbloquear una cuenta de administrador:
+
`security login unlock -vserver SVM_name -username user_name`

+
El siguiente comando desbloquea la cuenta de administrador `admin1` para la SVM``vs1.example.com``:

+
[listing]
----
cluster1::>security login unlock -vserver engData -username admin1
----
+
Obtenga más información sobre `security login unlock` en el link:https://docs.netapp.com/us-en/ontap-cli/security-login-unlock.html["Referencia de comandos del ONTAP"^].



Obtenga más información sobre `security login` en el link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+login["Referencia de comandos del ONTAP"^].
