---
permalink: authentication/manage-public-key-authentication-concept.html 
sidebar: sidebar 
keywords: associate, public key, administrator account 
summary: Para la autenticación de clave pública SSH, debe asociar la clave pública a una cuenta de administrador para que la cuenta pueda acceder a la SVM. Puede utilizar el comando create publickey de inicio de sesión de seguridad para asociar una clave con una cuenta de administrador. 
---
= Asociar una clave pública a una cuenta de administrador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para la autenticación de clave pública SSH, debe asociar la clave pública a una cuenta de administrador para que la cuenta pueda acceder a la SVM. Puede utilizar el `security login publickey create` comando para asociar una clave a una cuenta de administrador.

.Antes de empezar
* Debe haber generado la clave SSH.
* Debe ser un administrador de clúster o de SVM para ejecutar esta tarea.


.Acerca de esta tarea
Si autentica una cuenta a través de SSH tanto con una contraseña como con una clave pública SSH, la cuenta se autentica primero con la clave pública.

.Paso
. Asociar una clave pública a una cuenta de administrador:
+
`security login publickey create -vserver _SVM_name_ -username _user_name_ -index _index_ -publickey _certificate_ -comment _comment_`

+
Para obtener una sintaxis completa del comando, consulte link:config-worksheets-reference.html["hoja de trabajo"].

+
link:config-worksheets-reference.html["Asociación de una clave pública con una cuenta de usuario"]

+
El siguiente comando asocia una clave pública con la cuenta de administrador de SVM `svmadmin1` Para la SVM ``engData1``. A la clave pública se le asigna el número de índice 5.

+
[listing]
----
cluster1::>security login publickey create -vserver engData1 -username svmadmin1 -index 5 -publickey
"ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEAspH64CYbUsDQCdW22JnK6J
/vU9upnKzd2zAk9C1f7YaWRUAFNs2Qe5lUmQ3ldi8AD0Vfbr5T6HZPCixNAIza
FciDy7hgnmdj9eNGedGr/JNrftQbLD1hZybX+72DpQB0tYWBhe6eDJ1oPLob
ZBGfMlPXh8VjeU44i7W4+s0hG0E=tsmith@publickey.example.com"
----

